### ISSUE TITLE
Ingress controller toggles between initializing and running states as the healthcheckstates goes from unhealthy to healthy

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#10057]
**Rancher versions:**
rancher/server:v1.6.11-rc1

**Docker version: (`docker version`,`docker info` preferred)** 1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** Ubuntu

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** Digital Ocean

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**: Single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes

**Steps to Reproduce:**

1. Create a 4 host setup and create user pods/ingress
2. Turn OFF hosts which have etcd running 
3. Delete the Kubernetes stack and the hosts powered OFF
4. Launch Kubernetes stack again. 
5. Wait for the Kuberentes stack to come up successfully. It should become a healthy single node cluster.

Rancher ingress controller toggles from initiliazing state to running state. The healthcheck state goes from unhealthy to initializing/healthy states. 
Dashboard cannot be launched.

<img width="262" alt="screen shot 2017-10-09 at 11 14 00 am" src="https://user-images.githubusercontent.com/18536626/31352287-0ff1805a-ace3-11e7-97b4-821611e88040.png">

Rancher Ingress controller logs:
```

10/9/2017 11:19:59 AM++ awk '{print $1}'
10/9/2017 11:20:00 AM+ TOKEN=8f64787444ee62c1e764bc54f97ee4f72ab54b00db50ac5f19335f9ec361f480
10/9/2017 11:20:00 AM+ exec lb-controller --controller=kubernetes --provider=rancher
10/9/2017 11:20:00 AM+ echo 8f64787444ee62c1e764bc54f97ee4f72ab54b00db50ac5f19335f9ec361f480
10/9/2017 11:20:04 AMtime="2017-10-09T18:20:04Z" level=info msg="Starting Rancher LB service"
10/9/2017 11:20:04 AMtime="2017-10-09T18:20:04Z" level=info msg="LB controller: kubernetes"
10/9/2017 11:20:04 AMtime="2017-10-09T18:20:04Z" level=info msg="LB provider: rancher"
10/9/2017 11:20:04 AMtime="2017-10-09T18:20:04Z" level=info msg="starting kubernetes controller"
10/9/2017 11:20:04 AMtime="2017-10-09T18:20:04Z" level=info msg="Healthcheck handler is listening on :10241"
10/9/2017 11:20:05 AMtime="2017-10-09T18:20:05Z" level=info msg="Event(api.ObjectReference{Kind:\"Ingress\", Namespace:\"default\", Name:\"ingress1\", UID:\"30e29b6d-acb2-11e7-b54c-027170449214\", APIVersion:\"extensions\", ResourceVersion:\"2610\", FieldPath:\"\"}): type: 'Normal' reason: 'CREATE' default/ingress1"
10/9/2017 11:20:17 AMtime="2017-10-09T18:20:17Z" level=info msg="Updating Rancher LB with the new lbConfig [&{{  map[] map[]} []   [] %!s(*client.LoadBalancerCookieStickinessPolicy=<nil>)}] "
10/9/2017 11:20:38 AMtime="2017-10-09T18:20:38Z" level=info msg="Updating Rancher LB with the new lbConfig [&{{  map[] map[]} []   [{{  map[] map[]}  foo.bar.com /service3.html %!s(int64=0) http  1s79 %!s(int64=83) %!s(int64=81)}] %!s(*client.LoadBalancerCookieStickinessPolicy=<nil>)}] "


```
Also, this issue is observed when we start off with a 3 node cluster and delete hosts to get to a two node or single node cluster

**Comment by alena1108** [comment]
Ingress controller health check reports OK only when k8s api server is reachable. Not the case in this setup. Here is the error from API server:

```
1011 20:59:06.765422       1 wrap.go:34] APIServer panic'd on GET /api/v1/services?resourceVersion=0: kill connection/stream
10/11/2017 1:59:06 PMgoroutine 102668 [running]:
10/11/2017 1:59:06 PMruntime/debug.Stack(0x828e0c0, 0xc422796a10, 0x3a701d6)
10/11/2017 1:59:06 PM	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
10/11/2017 1:59:06 PMk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1.1(0x321a660, 0xc42015c5e0)
10/11/2017 1:59:06 PM	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:34 +0x74
10/11/2017 1:59:06 PMk8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc4293a9c88, 0x1, 0x1)
10/11/2017 1:59:06 PM	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:54 +0xe5
10/11/2017 1:59:06 PMpanic(0x321a660, 0xc42015c5e0)
10/11/2017 1:59:06 PM	/usr/local/go/src/runtime/panic.go:489 +0x2cf
10/11/2017 1:59:06 PMk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc423629e60, 0xc427188120)
10/11/2017 1:59:06 PM	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:230 +0x182
10/11/2017 1:59:06 PMk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc423f4ca60, 0x828e0c0, 0xc422796a10, 0xc423eeaa00)
10/11/2017 1:59:06 PM	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:114 +0x28c
10/11/2017 1:59:06 PMk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x828e0c0, 0xc422796a10, 0xc423eeaa00)
10/11/2017 1:59:06 PM	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:45 +0x219
10/11/2017 1:59:06 PMnet/http.HandlerFunc.ServeHTTP(0xc4276dc300, 0x828e0c0, 0xc422796a10, 0xc423eeaa00)
10/11/2017 1:59:06 PM	/usr/local/go/src/net/http/server.go:1942 +0x44
10/11/2017 1:59:06 PMk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0x828e0c0, 0xc422796a10, 0xc423eeaa00)
10/11/2017 1:59:06 PM	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xef
10/11/2017 1:59:06 PMnet/http.HandlerFunc.ServeHTTP(0xc423f4ca80, 0x828e0c0, 0xc422796a10, 0xc423eeaa00)
10/11/2017 1:59:06 PM	/usr/local/go/src/net/http/server.go:1942 +0x44
10/11/2017 1:59:06 PMk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1(0x828e0c0, 0xc422796a10, 0xc423eeaa00)
10/11/2017 1:59:06 PM	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/
```

And the etcd keeps on crashing.

**Comment by alena1108** [comment]
@galal-hussein could you look into etcd issue. I'll provide you with the setup details separately.

**Comment by galal-hussein** [comment]
@alena1108 @soumyalj After troubleshooting, it turns out that etcd couldn't write correctly due to lack of resources on the single host which has only 1 GB of RAM, we recommend at least 2GB of RAM for kubernetes hosts, after testing with single host of 2GB of RAM, the issue is not found anymore.
