### ISSUE TITLE
Intermitted issue with load balancer service stuck in activating state

### ISSUE THREAD

**Issue by sabiodelhielo** [rancher/rancher#10129]
**Rancher versions:**
rancher/server: master
rancher/agent: v2.0-alpha4

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
DO

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Embedded K8s

**Steps to Reproduce:**
Create service, scale 2, image: nginx, no published ports
Create a lb service, scale 1, add the nginx service as the listener port

**Results:**
Intermitted lb service will get stuck in a Activating state, looks like it eventually gets deleted and tried to starts a new one again:

10/16/2017 3:46:55 PMINFO[5325] Waiting for containers of pod test-loadbalance-for-service-lb-smoke-test-loadbalance-9e8c0008 to be ready
10/16/2017 3:46:56 PMINFO[5326] Reply: &{Resource:{Id: Type: Links:map[] Actions:map[]} Data:map[] Name:reply.8276662965232347586 PreviousId:cd2f6199-8c51-45fc-85d9-259eb0111fc1 PreviousIds:[] ResourceId: ResourceType: Time:0 Transitioning:yes TransitioningMessage:PodInitializing}
10/16/2017 3:46:56 PMINFO[5326] Waiting for containers of pod test-loadbalance-for-service-lb-smoke-test-loadbalance-9e8c0008 to be ready
10/16/2017 3:46:57 PMINFO[5327] Waiting for containers of pod test-loadbalance-for-service-lb-smoke-test-loadbalance-9e8c0008 to be ready
10/16/2017 3:46:58 PMINFO[5328] Waiting for containers of pod test-loadbalance-for-service-lb-smoke-test-loadbalance-9e8c0008 to be ready
10/16/2017 3:46:59 PMINFO[5329] Waiting for containers of pod test-loadbalance-for-service-lb-smoke-test-loadbalance-9e8c0008 to be ready
10/16/2017 3:47:00 PMINFO[5330] Reply: &{Resource:{Id: Type: Links:map[] Actions:map[]} Data:map[deploymentSyncResponse:0xc4202fa070] Name:reply.8276662965232347586 PreviousId:cd2f6199-8c51-45fc-85d9-259eb0111fc1 PreviousIds:[] ResourceId: ResourceType: Time:0 Transitioning: TransitioningMessage:}
10/16/2017 3:47:33 PM2017-10-16 22:47:33,348 ERROR [:] [] [] [] [sched-core-16  ] [i.c.p.task.impl.TaskManagerImpl     ] Task [resource.change.monitor] failed java.util.ConcurrentModificationException: null
10/16/2017 3:47:33 PM	at java.util.ArrayList.forEach(ArrayList.java:1252)
10/16/2017 3:47:33 PM	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2062)
10/16/2017 3:47:33 PM	at io.cattle.platform.object.monitor.impl.ResourceMonitorImpl.lambda$run$2(ResourceMonitorImpl.java:144)
10/16/2017 3:47:33 PM	at java.util.ArrayList.forEach(ArrayList.java:1249)
10/16/2017 3:47:33 PM	at io.cattle.platform.object.monitor.impl.ResourceMonitorImpl.run(ResourceMonitorImpl.java:142)
10/16/2017 3:47:33 PM	at io.cattle.platform.task.impl.TaskManagerImpl$1.doRun(TaskManagerImpl.java:103)
10/16/2017 3:47:33 PM	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15)
10/16/2017 3:47:33 PM	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:36)
10/16/2017 3:47:33 PM	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:57)
10/16/2017 3:47:33 PM	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:110)
10/16/2017 3:47:33 PM	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:54)
10/16/2017 3:47:33 PM	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:33)
10/16/2017 3:47:33 PM	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
10/16/2017 3:47:33 PM	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
10/16/2017 3:47:33 PM	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
10/16/2017 3:47:33 PM	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
10/16/2017 3:47:33 PM	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
10/16/2017 3:47:33 PM	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
10/16/2017 3:47:33 PM	at java.lang.Thread.run(Thread.java:748)
10/16/2017 3:47:33 PM
10/16/2017 3:48:00 PMINFO[5390] Deleting pod test-loadbalance-for-service-lb-smoke-test-loadbalance-9e8c0008
10/16/2017 3:48:00 PMINFO[5390] Waiting for pod test-loadbalance-for-service-lb-smoke-test-loadbalance-9e8c0008 to be deleted
10/16/2017 3:48:01 PMINFO[5391] Waiting for pod test-loadbalance-for-service-lb-smoke-test-loadbalance-9e8c0008 to be deleted: all containers stopped
10/16/2017 3:48:01 PMINFO[5391] Reply: &{Resource:{Id: Type: Links:map[] Actions:map[]} Data:map[deploymentSyncResponse:0xc4202629a0] Name:reply.8470132237976444544 PreviousId:64d2d47d-8dee-4351-9be3-63709f3ce8bf PreviousIds:[] ResourceId: ResourceType: Time:0 Transitioning: TransitioningMessage:}

**Comment by sabiodelhielo** [comment]
Alena says this pull should fix the issue: https://github.com/rancher/cattle/pull/3060

**Comment by sabiodelhielo** [comment]
The merge fixed this, smoke tests for the load balancer are consistently
