### ISSUE TITLE
Rancher 2.0 rancher-server crashes after several hours of inactivity

### ISSUE THREAD

**Issue by 0ff** [rancher/rancher#10124]
**Rancher versions:**
rancher/server: v2.0.0-alpha9
rancher/agent: v2.0-alpha4

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Server Version: 17.05.0-ce
Kernel Version: 4.4.0-97-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953GiB

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.4.0-97-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
DigitalOcean

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher beta

**Steps to Reproduce:**
1. Install rancher on DO with 1 server and 2 agents (agents provisioned through rancher UI).
2. Wait.

**Results:**
After a couple of hours, rancher-server quits for no particular reason (at least as far as I can tell) and then I need to reboot the server-host to make it work again (`docker restart` does not work).

This is a log where you can see that suddenly the server stops working (full log available but before that nothing too interesting happens):
```
I1014 08:11:04.759793     154 trace.go:61] Trace "GuaranteedUpdate etcd3: *api.Endpoints" (started 2017-10-14 08:11:04.239947361 +0000 UTC):
[142.390663ms] [142.390663ms] initial value restored
[167.049381ms] [24.658718ms] Transaction prepared
[482.384512ms] [315.335131ms] Transaction committed
"GuaranteedUpdate etcd3: *api.Endpoints" [507.189383ms] [24.804871ms] END
I1014 08:11:04.766476     154 trace.go:61] Trace "Update /api/v1/namespaces/kube-system/endpoints/kube-scheduler" (started 2017-10-14 08:11:04.203105922 +0000 UTC):
[4.028182ms] [4.028182ms] About to convert to expected version
[21.336981ms] [17.308799ms] Conversion done
[26.865937ms] [5.528956ms] About to store object in database
[558.066466ms] [531.200529ms] Object stored in database
[559.281022ms] [1.214556ms] Self-link added
"Update /api/v1/namespaces/kube-system/endpoints/kube-scheduler" [563.294718ms] [4.013696ms] END
I1014 08:11:13.437917     154 trace.go:61] Trace "Get /api/v1/namespaces/kube-system" (started 2017-10-14 08:11:09.618606331 +0000 UTC):
[270.618131ms] [270.618131ms] About to Get from storage
[2.840342621s] [2.56972449s] About to write a response
"Get /api/v1/namespaces/kube-system" [3.615538493s] [775.195872ms] END
time="2017-10-14T08:11:12Z" level=error msg="Failed to find cluster: Get http://localhost:8081/v3/clusters/1c1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2017-10-14T08:11:14Z" level=error msg="Failed to find cluster: Get http://localhost:8081/v3/clusters/1c1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2017-10-14T08:11:14Z" level=error msg="Failed to find cluster: Get http://localhost:8081/v3/clusters/1c1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2017-10-14T08:11:16Z" level=error msg="Failed to find cluster: Get http://localhost:8081/v3/clusters/1c1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2017-10-14T08:11:16Z" level=error msg="Failed to find cluster: Get http://localhost:8081/v3/clusters/1c1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2017-10-14T08:11:19Z" level=error msg="Failed to find cluster: Get http://localhost:8081/v3/clusters/1c1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
I1014 08:11:20.706256     154 trace.go:61] Trace "List /apis/extensions/v1beta1/thirdpartyresources" (started 2017-10-14 08:11:13.179920293 +0000 UTC):
[238.914386ms] [238.914386ms] About to List from storage
[2.332382484s] [2.093468098s] Listing from storage done
[2.487162761s] [154.780277ms] Self-linking done
[5.399311873s] [2.912149112s] Writing http response done (0 items)
"List /apis/extensions/v1beta1/thirdpartyresources" [5.437319854s] [38.007981ms] END
time="2017-10-14T08:11:20Z" level=error msg="Failed to find cluster: Get http://localhost:8081/v3/clusters/1c1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2017-10-14T08:11:20Z" level=error msg="Failed to find cluster: Get http://localhost:8081/v3/clusters/1c1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2017-10-14T08:11:21Z" level=error msg="Failed to find cluster: Get http://localhost:8081/v3/clusters/1c1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2017-10-14T08:11:22Z" level=error msg="Failed to find cluster: Get http://localhost:8081/v3/clusters/1c1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2017-10-14T08:11:22Z" level=error msg="Failed to find cluster: Get http://localhost:8081/v3/clusters/1c1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2017-10-14T08:11:22Z" level=error msg="Failed to find cluster: Get http://localhost:8081/v3/clusters/1c1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
I1014 08:11:24.889502     154 trace.go:61] Trace "Get /api/v1/namespaces/kube-system/endpoints/kube-controller-manager" (started 2017-10-14 08:11:17.234612094 +0000 UTC):
[1.28822972s] [1.28822972s] About to Get from storage
[5.204804014s] [3.916574294s] About to write a response
"Get /api/v1/namespaces/kube-system/endpoints/kube-controller-manager" [7.139996596s] [1.935192582s] END
I1014 08:11:25.447907     154 trace.go:61] Trace "Get /api/v1/namespaces/kube-public" (started 2017-10-14 08:11:19.097117414 +0000 UTC):
[811.316742ms] [811.316742ms] About to Get from storage
[5.08546213s] [4.274145388s] About to write a response
"Get /api/v1/namespaces/kube-public" [6.031442969s] [945.980839ms] END
I1014 08:11:27.113206     154 trace.go:61] Trace "Get /api/v1/namespaces/default" (started 2017-10-14 08:11:22.325244721 +0000 UTC):
[503.469812ms] [503.469812ms] About to Get from storage
[3.817703468s] [3.314233656s] About to write a response
"Get /api/v1/namespaces/default" [4.463072691s] [645.369223ms] END
time="2017-10-14T08:11:26Z" level=error msg="Failed to find cluster: Get http://localhost:8081/v3/clusters/1c1: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" 
time="2017-10-14T08:11:30Z" level=error msg="Failed to find cluster: Get http://localhost:8081/v3/clusters/1c1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2017-10-14T08:11:31Z" level=error msg="Failed to find cluster: Get http://localhost:8081/v3/clusters/1c1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2017-10-14T08:11:32Z" level=error msg="Failed to find cluster: Get http://localhost:8081/v3/clusters/1c1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2017-10-14T08:11:32Z" level=error msg="Failed to find cluster: Get http://localhost:8081/v3/clusters/1c1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2017-10-14T08:11:34Z" level=error msg="Failed to find cluster: Get http://localhost:8081/v3/clusters/1c1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
2017/10/14 08:11:35 httputil: ReverseProxy read error during body copy: context canceled
2017/10/14 08:11:35 httputil: ReverseProxy read error during body copy: context canceled
2017/10/14 08:11:35 httputil: ReverseProxy read error during body copy: context canceled
2017/10/14 08:11:35 httputil: ReverseProxy read error during body copy: context canceled
```

Other errors start appearing too:
```
2017-10-14 08:16:47,629 ERROR [:] [] [] [] [core-7         ] [i.c.platform.loop.MetadataClientLoop] Failed to sync metadata with agent [11] [{}] io.cattle.platform.eventing.exception.EventExecutionException: Post http://10.135.47.188/v3/publish: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
    at io.cattle.platform.eventing.exception.EventExecutionException.fromEvent(EventExecutionException.java:53)
    at io.cattle.platform.eventing.impl.FutureEventListener.onEvent(FutureEventListener.java:48)
    at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:112)
    at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15)
    at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:36)
    at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:57)
    at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:110)
    at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:54)
    at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:33)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

```
I1014 08:16:56.512107     154 logs.go:41] http: panic serving 127.0.0.1:48042: kill connection/stream
goroutine 1964599 [running]:
net/http.(*conn).serve.func1(0xc42142edc0)
    /usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x2b21f60, 0xc420232580)
    /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/rancher/netes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc420f2cf20, 0xc430d02280)
    /go/src/github.com/rancher/netes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:212 +0x182
github.com/rancher/netes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc4207cc500, 0x66cc960, 0xc421a98380, 0xc4217cec00)
    /go/src/github.com/rancher/netes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:96 +0x278
github.com/rancher/netes/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x66cc960, 0xc421a98380, 0xc4217cec00)
    /go/src/github.com/rancher/netes/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:95 +0x197
net/http.HandlerFunc.ServeHTTP(0xc420725600, 0x66cc960, 0xc421a98380, 0xc4217cec00)
    /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/rancher/netes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x66cc960, 0xc421a98380, 0xc4217cec00)
    /go/src/github.com/rancher/netes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:45 +0x200
net/http.HandlerFunc.ServeHTTP(0xc4207c6b40, 0x66cc960, 0xc421a98380, 0xc4217cec00)
    /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/rancher/netes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0x66cc960, 0xc421a98380, 0xc4217cec00)
    /go/src/github.com/rancher/netes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xef
net/http.HandlerFunc.ServeHTTP(0xc4207cc580, 0x66cc960, 0xc421a98380, 0xc4217cec00)
    /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/rancher/netes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc4207c6b70, 0x66cc960, 0xc421a98380, 0xc4217cec00)
    /go/src/github.com/rancher/netes/vendor/k8s.io/apiserver/pkg/server/handler.go:198 +0x51
github.com/rancher/netes/server/embedded.(*Server).Handler.func1(0x66cc960, 0xc421a98380, 0xc4217cec00)
    /go/src/github.com/rancher/netes/server/embedded/embedded_server.go:50 +0x142
net/http.HandlerFunc.ServeHTTP(0xc4363f3b30, 0x66cc960, 0xc421a98380, 0xc4217cec00)
    /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/rancher/netes/router.(*Router).ServeHTTP(0xc420174cd0, 0x66cc960, 0xc421a98380, 0xc422098600)
    /go/src/github.com/rancher/netes/router/router.go:38 +0xf1
net/http.serverHandler.ServeHTTP(0xc420094d10, 0x66cc960, 0xc421a98380, 0xc422098600)
    /usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42142edc0, 0x66ce3a0, 0xc461c24f80)
    /usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:2668 +0x2ce
2017/10/14 08:16:57 http: proxy error: context canceled
time="2017-10-14T08:16:56Z" level=error msg="Failed to find cluster: Get http://localhost:8081/v3/clusters/1c1: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" 
```

After rebooting, everything is fine again. Also, the agents don't seem to be affected by this, they are running fine (although they are not doing anything except for running the stock services).

Any input as to how to track this down any further would be appreciated.

**Comment by superseb** [comment]
To track this down, can you add some more info:

- Droplet size
- With or without private networking and IPv6?
- Are you just joining two hosts running `rancher/agent` and wait a couple of hours before it happens? (no actions on the cluster through kubectl or UI)

**Comment by 0ff** [comment]
Sure:
* **Droplet size server:** `2 GB Memory / 40 GB Disk / FRA1`
* **Droplet size agent:** `1 GB Memory / 30 GB Disk / FRA1`
* **With private networking and without IPv6** (server is registered using its private ip)
* **Are you just joining two hosts running rancher/agent and wait a couple of hours before it happens?** yes. I did browse through the rancher UI after rebooting to make sure it works, but nothing else.

**Comment by superseb** [comment]
Can you add a screenshot of the Containers view in the System environment? Or send it to me on Rancher Users Slack (https://slack.rancher.io)

**Comment by 0ff** [comment]
Sure thing, as you can see none of them needed to be restarted and they seem to be running for 11days without a problem:
![screen shot 2017-10-16 at 20 10 46](https://user-images.githubusercontent.com/1755213/31627637-35606cf4-b2ae-11e7-8da3-87858ee7e36c.png)

**Comment by vincent99** [comment]
Unrelated, but are the horizontal lines separating each container missing under the image names as they are in that screenshot?  If so what browser/os?

**Comment by 0ff** [comment]
Great catch, they are not though. This only happens when I scale down the page to ~75% so it all fits into one screenshot. In full-size it looks as intended:
<img width="1275" alt="screen shot 2017-10-16 at 20 27 21" src="https://user-images.githubusercontent.com/1755213/31628263-78a12c5e-b2b0-11e7-8a7e-17aef287f2ad.png">

**Comment by vincent99** [comment]
ok good, though odd it's per-column.  There's a screenshot-entire-page feature in current Chrome now, but I can't remember where to find it.. I've always use [this extension](https://chrome.google.com/webstore/detail/full-page-screen-capture/fdpohaocaechififmbbbbbknoalclacl).

**Comment by superseb** [comment]
Can you also add a screenshot of the `Flat Container List` which you can view by clicking the single container icon on the left of `Import from YAML`. Thanks

**Comment by superseb** [comment]
With the release of [Tech Preview 2](https://forums.rancher.com/t/rancher-release-v2-0-0-tech-preview-2/8282/3), the architecture behind 2.0 has significantly changed. Any issues with any release prior to v2.0.0-alpha12 is most likely invalid. 

Please watch our [Tech Preview 2 meetup](https://www.youtube.com/watch?v=ld7ctOg3waM) to learn more about the changes in 2.0 in Tech Preview 2. 

Please file new issues after using Tech Preview 2 (any release v2.0.0-alpha12+). As always, thanks for using Rancher!
