### ISSUE TITLE
Service containers with no ipaddress having drain_time out set get stuck in "stopping" state forever and Lb service panics.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10176]
Server version - v1.6.11-rc4

Steps to reproduce the problem:

Scenario 1:
Create a service with anti affinity scheduling rule and drainIp set.
Add this service as a target to LB.
Scale up service  beyond number of hosts available in the environment.
This results in containers getting into "Error" state because of allocation failure and then getting stuck in "Stopping" state.
LB service starts having  panics. 

Scenario 2:

Create a service in host network and drainIp set.
Add this service as a target to LB.
Upgrade service.
Service container is stuck in "stopping" state forever.

LB service has a panic. 

```
10/19/2017 1:45:54 PMc269dc26-090e-4fd4-8138-b12e2e232885time="2017-10-19T20:45:54Z" level=info msg="Starting Rancher LB service"
10/19/2017 1:45:54 PMtime="2017-10-19T20:45:54Z" level=error msg="Failed to initialize Kubernetes controller: KUBERNETES_URL is not set"
10/19/2017 1:45:54 PMtime="2017-10-19T20:45:54Z" level=info msg="CATTLE_ACCESS_KEY is not set, skipping init of Rancher LB provider"
10/19/2017 1:45:55 PMtime="2017-10-19T20:45:55Z" level=info msg="LB controller: rancher"
10/19/2017 1:45:55 PMtime="2017-10-19T20:45:55Z" level=info msg="LB provider: haproxy"
10/19/2017 1:45:55 PMtime="2017-10-19T20:45:55Z" level=info msg="starting rancher controller"
10/19/2017 1:45:55 PMtime="2017-10-19T20:45:55Z" level=info msg="Healthcheck handler is listening on :10241"
10/19/2017 1:45:55 PMtime="2017-10-19T20:45:55Z" level=info msg="Initializing event router" workerCount=250
10/19/2017 1:45:55 PMtime="2017-10-19T20:45:55Z" level=info msg="Connection established"
10/19/2017 1:45:55 PMtime="2017-10-19T20:45:55Z" level=info msg="Starting websocket pings"
10/19/2017 1:45:56 PMtime="2017-10-19T20:45:56Z" level=info msg=" -- starting haproxy\n * Starting haproxy haproxy\n   ...done.\n"
10/19/2017 1:45:57 PMtime="2017-10-19T20:45:57Z" level=info msg=" -- reloading haproxy config with the new config changes\n * Reloading haproxy haproxy\n[WARNING] 291/204557 (52) : config : 'option forwardfor' ignored for proxy 'default' as it requires HTTP mode.\n[WARNING] 291/204557 (54) : config : 'option forwardfor' ignored for proxy 'default' as it requires HTTP mode.\n   ...done.\n"
10/19/2017 1:46:05 PMtime="2017-10-19T20:46:05Z" level=info msg="Received target.drain IP: <nil>, drainTimeout: 25000, eventID: 90575301-a087-46f8-a58c-9b4b61737468, resourceID 1i1007"
10/19/2017 1:46:05 PMpanic: interface conversion: interface {} is nil, not string
10/19/2017 1:46:05 PM
10/19/2017 1:46:05 PMgoroutine 114 [running]:
10/19/2017 1:46:05 PMgithub.com/rancher/lb-controller/controller/rancher.(*REventsHandler).HandleDrainEvent(0xc420470960, 0xc42029ad00, 0xc420242a80, 0xc, 0x1, 0x1)
10/19/2017 1:46:05 PM	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher_events_handler.go:131 +0x64d
10/19/2017 1:46:05 PMgithub.com/rancher/lb-controller/controller/rancher.(*REventsHandler).handle(0xc420470960, 0xc42029ad00, 0xc420242a80, 0xc420037df8, 0xc4203b6410)
10/19/2017 1:46:05 PM	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher_events_handler.go:63 +0x346
10/19/2017 1:46:05 PMgithub.com/rancher/lb-controller/controller/rancher.(*REventsHandler).(github.com/rancher/lb-controller/controller/rancher.handle)-fm(0xc42029ad00, 0xc420242a80, 0xc4206c60a0, 0xc)
10/19/2017 1:46:05 PM	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher_events_handler.go:32 +0x3e
10/19/2017 1:46:05 PMgithub.com/rancher/lb-controller/vendor/github.com/rancher/event-subscriber/events.doWork(0xc42029ad00, 0xc420678b70, 0xc420242a80, 0x2a3bfc0, 0x2ab3f40)
10/19/2017 1:46:05 PM	/go/src/github.com/rancher/lb-controller/vendor/github.com/rancher/event-subscriber/events/worker.go:94 +0x28d
10/19/2017 1:46:05 PMgithub.com/rancher/lb-controller/vendor/github.com/rancher/event-subscriber/events.(*skippingWorkerPool).HandleWork.func1(0xc42067a070, 0x1, 0xc42029ad00, 0xc420678b70, 0xc420242a80)
10/19/2017 1:46:05 PM	/go/src/github.com/rancher/lb-controller/vendor/github.com/rancher/event-subscriber/events/worker.go:47 +0x9e
10/19/2017 1:46:05 PMcreated by github.com/rancher/lb-controller/vendor/github.com/rancher/event-subscriber/events.(*skippingWorkerPool).HandleWork
10/19/2017 1:46:05 PM	/go/src/github.com/rancher/lb-controller/vendor/github.com/rancher/event-subscriber/events/worker.go:48 +0x18d
```

**Comment by sangeethah** [comment]
Tested with Rancher Server build from v1.6 branch (v1.6-development).

Scenario 1:
Create a service with anti affinity scheduling rule and drainIp set.
Add this service as a target to LB.
Scale up service beyond number of hosts available in the environment.
This results in containers getting into "Error" state because of allocation failure .
Containers in "Error" state dont get stuck "Stopping" state. No panics in LB.

Scenario 2:

Create a service in host network and drainIp set.
Add this service as a target to LB.
Upgrade service.
Service container dont get stuck "stopping" state and upgrade of service succeeds as expected.
In this case , containers in host network do not honor drain settings.
