### ISSUE TITLE
Incorrect string value error when upgrading Kubernetes stack to 1.8.3

### ISSUE THREAD

**Issue by dymo** [rancher/rancher#10341]
**Rancher versions:**
rancher/server: 1.6.11
rancher/agent: 1.2.7

**Infrastructure Stack versions:**
healthcheck: 0.3.3
ipsec: 0.2.0
network-services: 0.2.7
scheduler: 0.6.3
kubernetes (if applicable): 1.8.3, but not really

**Docker version:**
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64

**Operating system and kernel:**
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"

4.10.0-38-generic

**Type/provider of hosts:**
Bare-metal

**Setup details:**
Single node, external MySQL

**Environment Template:**
Kubernetes

**Steps to Reproduce:**
Upgrade Rancher from 1.6.10 to 1.6.11 and then upgrade Kubernetes stack after upgrading network-services and ipsec.

**Results:**
In the UI I get "Upgrade Error Conflict" and in the log I get this:

```
2017-11-15 10:09:21,116 ERROR [:] [] [] [] [tp1020391880-66] [i.g.i.g.s.ApiRequestFilterDelegate  ] Unhandled exception in API for request [https://ranch.algoplanner.dk/v2-beta/projects/1a7/stacks/1st9/] org.jooq.exception.DataAccessException: SQL [insert into `audit_log` (`account_id`, `authenticated_as_account_id`, `kind`, `auth_type`, `event_type`, `resource_type`, `resource_id`, `description`, `created`, `data`, `authenticated_as_identity_id`, `runtime`, `client_ip`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; (conn:56) Incorrect string value: '\xEF\xBC\x9Agcr...' for column 'data' at row 1
Query is: insert into `audit_log` (`account_id`, `authenticated_as_account_id`, `kind`, `auth_type`, `event_type`, `resource_type`, `resource_id`, `description`, `created`, `data`, `authenticated_as_identity_id`, `runtime`, `client_ip`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), parameters [7,1,'auditLog','TokenAuth','api.stack.upgrade','stack',<null>,<null>,'2017-11-15 10:09:21.108','{"fields":{"responseObject":"{\"id\":\"cae8c6c0-f4ce-4b77-9061-9322f47d5656\",\"type\":\"error\",\"links\":{},\"actions\":{},\"status\":409,\"code\":\"Conflict\",\"message\":\"Conflict\",\"detail\":null,\"baseType\":\"error\"}","requestObject":"{\"environment\":{\"CONSTRAINT_TYPE\":\"none\",\"CLOUD_PROVIDER\":\"rancher\",\"AZURE_CLOUD\":\"AzurePublicCloud\",\"AZURE_TENANT_ID\":\"\",\"AZURE_CLIENT_ID\":\"\",\"AZURE_CLIENT_SECRET\":\"\",\"AZURE_SEC_GROUP\":\"\",\"RBAC\":\"true\",\"REGISTRY\":\"\",\"BASE_IMAGE_NAMESPACE\":\"\",\"HELM_IMAGE_NAMESPACE\":\"\",\"DNS_REPLICAS\":\"2\",\"ENABLE_RANCHER_INGRESS_CONTROLLER\":\"false\",\"FAIL_...
	at org.jooq.impl.Utils.translate(Utils.java:1287)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:495)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:326)
	at org.jooq.impl.UpdatableRecordImpl.storeInsert0(UpdatableRecordImpl.java:230)
	at org.jooq.impl.UpdatableRecordImpl.access$100(UpdatableRecordImpl.java:90)
	at org.jooq.impl.UpdatableRecordImpl$2.operate(UpdatableRecordImpl.java:201)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:123)
	at org.jooq.impl.UpdatableRecordImpl.storeInsert(UpdatableRecordImpl.java:196)
	at org.jooq.impl.UpdatableRecordImpl.insert(UpdatableRecordImpl.java:144)
	at io.cattle.platform.object.impl.JooqObjectManager$1.executeNoResult(JooqObjectManager.java:80)
	at io.cattle.platform.engine.idempotent.IdempotentExecutionNoReturn.execute(IdempotentExecutionNoReturn.java:7)
	at io.cattle.platform.engine.idempotent.IdempotentExecutionNoReturn.execute(IdempotentExecutionNoReturn.java:3)
	at io.cattle.platform.engine.idempotent.Idempotent.change(Idempotent.java:88)
	at io.cattle.platform.object.impl.JooqObjectManager.insert(JooqObjectManager.java:77)
	at io.cattle.platform.object.impl.AbstractObjectManager.create(AbstractObjectManager.java:51)
	at io.cattle.platform.object.impl.AbstractObjectManager.create(AbstractObjectManager.java:33)
	at io.cattle.platform.iaas.api.auditing.dao.impl.AuditLogDaoImpl.create(AuditLogDaoImpl.java:39)
	at io.cattle.platform.iaas.api.auditing.AuditServiceImpl.logRequest(AuditServiceImpl.java:102)
	at io.cattle.platform.iaas.api.auditing.AuditLogsRequestHandler.handle(AuditLogsRequestHandler.java:23)
	at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:99)
	at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:96)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:106)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: (conn:56) Incorrect string value: '\xEF\xBC\x9Agcr...' for column 'data' at row 1
Query is: insert into `audit_log` (`account_id`, `authenticated_as_account_id`, `kind`, `auth_type`, `event_type`, `resource_type`, `resource_id`, `description`, `created`, `data`, `authenticated_as_identity_id`, `runtime`, `client_ip`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), parameters [7,1,'auditLog','TokenAuth','api.stack.upgrade','stack',<null>,<null>,'2017-11-15 10:09:21.108','{"fields":{"responseObject":"{\"id\":\"cae8c6c0-f4ce-4b77-9061-9322f47d5656\",\"type\":\"error\",\"links\":{},\"actions\":{},\"status\":409,\"code\":\"Conflict\",\"message\":\"Conflict\",\"detail\":null,\"baseType\":\"error\"}","requestObject":"{\"environment\":{\"CONSTRAINT_TYPE\":\"none\",\"CLOUD_PROVIDER\":\"rancher\",\"AZURE_CLOUD\":\"AzurePublicCloud\",\"AZURE_TENANT_ID\":\"\",\"AZURE_CLIENT_ID\":\"\",\"AZURE_CLIENT_SECRET\":\"\",\"AZURE_SEC_GROUP\":\"\",\"RBAC\":\"true\",\"REGISTRY\":\"\",\"BASE_IMAGE_NAMESPACE\":\"\",\"HELM_IMAGE_NAMESPACE\":\"\",\"DNS_REPLICAS\":\"2\",\"ENABLE_RANCHER_INGRESS_CONTROLLER\":\"false\",\"FAIL_...
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:150)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.getException(ExceptionMapper.java:101)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwAndLogException(ExceptionMapper.java:77)
	at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:224)
	at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:411)
	at org.mariadb.jdbc.MariaDbServerPreparedStatement.execute(MariaDbServerPreparedStatement.java:361)
	at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeUpdate(MariaDbServerPreparedStatement.java:350)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.executeUpdate(DefaultPreparedStatement.java:88)
	at org.jooq.impl.AbstractStoreQuery.execute(AbstractStoreQuery.java:346)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:322)
	... 45 common frames omitted
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Incorrect string value: '\xEF\xBC\x9Agcr...' for column 'data' at row 1
Query is: insert into `audit_log` (`account_id`, `authenticated_as_account_id`, `kind`, `auth_type`, `event_type`, `resource_type`, `resource_id`, `description`, `created`, `data`, `authenticated_as_identity_id`, `runtime`, `client_ip`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), parameters [7,1,'auditLog','TokenAuth','api.stack.upgrade','stack',<null>,<null>,'2017-11-15 10:09:21.108','{"fields":{"responseObject":"{\"id\":\"cae8c6c0-f4ce-4b77-9061-9322f47d5656\",\"type\":\"error\",\"links\":{},\"actions\":{},\"status\":409,\"code\":\"Conflict\",\"message\":\"Conflict\",\"detail\":null,\"baseType\":\"error\"}","requestObject":"{\"environment\":{\"CONSTRAINT_TYPE\":\"none\",\"CLOUD_PROVIDER\":\"rancher\",\"AZURE_CLOUD\":\"AzurePublicCloud\",\"AZURE_TENANT_ID\":\"\",\"AZURE_CLIENT_ID\":\"\",\"AZURE_CLIENT_SECRET\":\"\",\"AZURE_SEC_GROUP\":\"\",\"RBAC\":\"true\",\"REGISTRY\":\"\",\"BASE_IMAGE_NAMESPACE\":\"\",\"HELM_IMAGE_NAMESPACE\":\"\",\"DNS_REPLICAS\":\"2\",\"ENABLE_RANCHER_INGRESS_CONTROLLER\":\"false\",\"FAIL_...
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1115)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1047)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1002)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executePreparedQuery(AbstractQueryProtocol.java:588)
	at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:399)
	... 52 common frames omitted
```

Then in Infrastructure stacks, it say Kubernetes is up to date v1.8.3-rancher1, but the containers still use image: rancher/k8s:v1.7.7-rancher1

**Comment by superseb** [comment]
This is usually when the wrong database collation and/or character set is configured, can you run:

```USE cattle; SELECT @@character_set_database, @@collation_database;```

This should say `utf8` and `utf8_general_ci`.

**Comment by dymo** [comment]
```
+--------------------------+----------------------+
| @@character_set_database | @@collation_database |
+--------------------------+----------------------+
| latin1                   | latin1_swedish_ci    |
+--------------------------+----------------------+
```

I have no idea why it is set to Swedish. Is there an easy way to fix that or do I have to go through all ~100 tables?

**Comment by superseb** [comment]
I have a gist here you can use to convert the DB: https://gist.github.com/superseb/652cc3cac140e70b9d0443cde3221409. You have to double-check if this matches the `latin1_swedish_ci` as well.

**Comment by dymo** [comment]
Thanks, that fixed the problem  :+1:

No changes needed for the sed script.

**Comment by superseb** [comment]
Created https://github.com/rancher/rancher/issues/10342 to explore how to make this a better experience.

**Comment by 7wonders** [comment]
This did the trick for me on aurora rds when kubernetes got stuck at "Creating Kubernetes system stack".
```
ALTER DATABASE cattle CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE DATABASECHANGELOG CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE DATABASECHANGELOGLOCK CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE account CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE account_link CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE agent CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE agent_group CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE audit_log CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE auth_token CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE backup CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE backup_target CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE catalog CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE catalog_category CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE catalog_file CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE catalog_label CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE catalog_template CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE catalog_template_category CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE catalog_version CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE catalog_version_label CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE certificate CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE cluster_host_map CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE cluster_membership CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE container_event CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE credential CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE credential_instance_map CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE data CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE deployment_unit CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE dynamic_schema CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE dynamic_schema_role CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE environment CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE external_event CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE external_handler CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE external_handler_external_handler_process_map CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE external_handler_process CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE generic_object CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE global_load_balancer CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE healthcheck_instance CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE healthcheck_instance_host_map CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE host CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE host_ip_address_map CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE host_label_map CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE host_template CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE host_vnet_map CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE image CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE image_storage_pool_map CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE instance CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE instance_host_map CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE instance_label_map CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE instance_link CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE ip_address CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE ip_address_nic_map CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE ip_association CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE ip_pool CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE label CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE load_balancer CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE load_balancer_certificate_map CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE load_balancer_config CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE load_balancer_config_listener_map CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE load_balancer_host_map CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE load_balancer_listener CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE load_balancer_target CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE machine_driver CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE mount CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE network CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE network_driver CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE network_service CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE network_service_provider CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE network_service_provider_instance_map CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE nic CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE offering CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE physical_host CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE port CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE process_execution CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE process_instance CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE project_member CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE project_template CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE resource_pool CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE scheduled_upgrade CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE secret CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE service CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE service_consume_map CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE service_event CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE service_expose_map CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE service_index CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE service_log CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE setting CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE snapshot CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE snapshot_storage_pool_map CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE storage_driver CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE storage_pool CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE storage_pool_host_map CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE subnet CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE subnet_vnet_map CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE task CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE task_instance CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE ui_challenge CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE user_preference CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE vnet CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE volume CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE volume_storage_pool_map CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE volume_template CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE zone CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE config_item_status DROP FOREIGN KEY fk_config_item__name;
ALTER TABLE config_item CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE config_item_status CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE config_item_status ADD FOREIGN KEY (name) REFERENCES config_item (name) ON DELETE CASCADE ON UPDATE CASCADE;
```

**Comment by wizonesolutions** [comment]
https://github.com/rancher/rancher/issues/10341#issuecomment-346943410 worked. A couple of `ALTER TABLE`s failed because of foreign keys...hopefully, that won't come back to bite me, but in any case, Kubernetes is upgrading now.

**Comment by 7wonders** [comment]
@wizonesolutions - check the last 4 rows and use the same method on the rows that failed. It drops the FK, does the convert then re-adds the FK.

**Comment by leonsp** [comment]
I got the same `Upgrade Error Conflict` message because the database disk was full.
