### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by colinlabs** [rancher/rancher#10358]
**Rancher versions:**
rancher/server: v1.6.11

**Docker version:**
docker version
```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
```
docer info
```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 25
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.797 GiB
Name: iZ2ze1zz9zmbbh6ah52701Z
```

 Experimental: false

**Operating system and kernel: **
4.4.0-62-generic
Ubuntu 16.04.2 LTS

**Type/provider of hosts:**
alicloud

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
 HA rancher, external DB

**Steps to Reproduce:**
deploy new rancher server,and always show this errors

**Results:**
```
rancher    | fatal error: unexpected signal during runtime execution
rancher    | [signal 0xb code=0x1 addr=0x63 pc=0x7fa341aecb2c]
rancher    |
rancher    | runtime stack:
rancher    | runtime.throw(0xbeffa0, 0x2a)
rancher    | 	/usr/local/go/src/runtime/panic.go:547 +0x90
rancher    | runtime.sigpanic()
rancher    | 	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
rancher    |
rancher    | goroutine 12 [syscall, locked to thread]:
rancher    | runtime.cgocall(0x840af0, 0xc82003cbd8, 0x0)
rancher    | 	/usr/local/go/src/runtime/cgocall.go:123 +0x11b fp=0xc82003cb78 sp=0xc82003cb48
rancher    | net._C2func_getaddrinfo(0x7fa3380008c0, 0x0, 0xc82010e5d0, 0xc82002c560, 0x0, 0x0, 0x0)
rancher    | 	??:0 +0x55 fp=0xc82003cbd8 sp=0xc82003cb78
rancher    | net.cgoLookupIPCNAME(0xc82010e457, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc60300)
rancher    | 	/usr/local/go/src/net/cgo_unix.go:111 +0x448 fp=0xc82003cd50 sp=0xc82003cbd8
rancher    | net.cgoLookupIP(0xc82010e457, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
rancher    | 	/usr/local/go/src/net/cgo_unix.go:163 +0x56 fp=0xc82003cda8 sp=0xc82003cd50
rancher    | net.lookupIP(0xc82010e457, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0)
rancher    | 	/usr/local/go/src/net/lookup_unix.go:67 +0x94 fp=0xc82003ce18 sp=0xc82003cda8
rancher    | net.glob.func16(0xc603f8, 0xc82010e457, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0)
rancher    | 	/usr/local/go/src/net/hook.go:10 +0x4d fp=0xc82003ce58 sp=0xc82003ce18
rancher    | net.lookupIPDeadline.func1(0x0, 0x0, 0x0, 0x0)
rancher    | 	/usr/local/go/src/net/lookup.go:106 +0x71 fp=0xc82003ced8 sp=0xc82003ce58
rancher    | internal/singleflight.(*Group).doCall(0x108ecd0, 0xc82000f0e0, 0xc82010e457, 0x9, 0xc8200bfa80)
rancher    | 	/usr/local/go/src/internal/singleflight/singleflight.go:93 +0x2c fp=0xc82003cf88 sp=0xc82003ced8
rancher    | runtime.goexit()
rancher    | 	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82003cf90 sp=0xc82003cf88
rancher    | created by internal/singleflight.(*Group).DoChan
rancher    | 	/usr/local/go/src/internal/singleflight/singleflight.go:86 +0x3ee
rancher    |
rancher    | goroutine 1 [IO wait]:
rancher    | net.runtime_pollWait(0x7fa3424fafd8, 0x72, 0x0)
rancher    | 	/usr/local/go/src/runtime/netpoll.go:160 +0x60
rancher    | net.(*pollDesc).Wait(0xc820106140, 0x72, 0x0, 0x0)
rancher    | 	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
rancher    | net.(*pollDesc).WaitRead(0xc820106140, 0x0, 0x0)
rancher    | 	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
rancher    | net.(*netFD).accept(0xc8201060e0, 0x0, 0x7fa3424fb0d0, 0xc8200fa160)
rancher    | 	/usr/local/go/src/net/fd_unix.go:426 +0x27c
rancher    | net.(*TCPListener).AcceptTCP(0xc8200f8008, 0x59e631, 0x0, 0x0)
rancher    | 	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
rancher    | net/http.tcpKeepAliveListener.Accept(0xc8200f8008, 0x0, 0x0, 0x0, 0x0)
rancher    | 	/usr/local/go/src/net/http/server.go:2427 +0x41
rancher    | net/http.(*Server).Serve(0xc82010a000, 0x7fa3424fb098, 0xc8200f8008, 0x0, 0x0)
rancher    | 	/usr/local/go/src/net/http/server.go:2117 +0x129
rancher    | net/http.(*Server).ListenAndServe(0xc82010a000, 0x0, 0x0)
rancher    | 	/usr/local/go/src/net/http/server.go:2098 +0x136
rancher    | net/http.ListenAndServe(0xc8200fe020, 0xc, 0x7fa3424fa000, 0xc82000eb90, 0x0, 0x0)
rancher    | 	/usr/local/go/src/net/http/server.go:2195 +0x98
rancher    | github.com/rancher/telemetry/cmd.clientRun(0xc82008c640, 0x0, 0x0)
rancher    | 	/go/src/github.com/rancher/telemetry/cmd/client.go:142 +0x896
rancher    | reflect.Value.call(0x945160, 0xc60168, 0x13, 0xb1f9d0, 0x4, 0xc8200ef150, 0x1, 0x1, 0x0, 0x0, ...)
rancher    | 	/usr/local/go/src/reflect/value.go:435 +0x120d
rancher    | reflect.Value.Call(0x945160, 0xc60168, 0x13, 0xc8200ef150, 0x1, 0x1, 0x0, 0x0, 0x0)
rancher    | 	/usr/local/go/src/reflect/value.go:303 +0xb1
rancher    | github.com/rancher/telemetry/vendor/github.com/urfave/cli.HandleAction(0x945160, 0xc60168, 0xc82008c640, 0x0, 0x0)
rancher    | 	/go/src/github.com/rancher/telemetry/vendor/github.com/urfave/cli/app.go:481 +0x2ee
rancher    | github.com/rancher/telemetry/vendor/github.com/urfave/cli.Command.Run(0xb22120, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xbd71e0, 0x22, 0x0, ...)
rancher    | 	/go/src/github.com/rancher/telemetry/vendor/github.com/urfave/cli/command.go:186 +0x1301
rancher    | github.com/rancher/telemetry/vendor/github.com/urfave/cli.(*App).Run(0xc820001500, 0xc82000a2e0, 0x2, 0x2, 0x0, 0x0)
rancher    | 	/go/src/github.com/rancher/telemetry/vendor/github.com/urfave/cli/app.go:235 +0xa9c
rancher    | main.main()
rancher    | 	/go/src/github.com/rancher/telemetry/main.go:58 +0x54e
rancher    |
rancher    | goroutine 17 [syscall, locked to thread]:
rancher    | runtime.goexit()
rancher    | 	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1
rancher    |
rancher    | goroutine 6 [chan receive]:
rancher    | github.com/rancher/telemetry/cmd.clientRun.func1(0xc820014ec0)
rancher    | 	/go/src/github.com/rancher/telemetry/cmd/client.go:127 +0x47
rancher    | created by github.com/rancher/telemetry/cmd.clientRun
rancher    | 	/go/src/github.com/rancher/telemetry/cmd/client.go:131 +0x66d
rancher    |
rancher    | goroutine 18 [select]:
rancher    | net/http.(*Transport).getConn(0xc8200c2000, 0xc82001c7e0, 0x0, 0xc82010e450, 0x4, 0xc82010e457, 0xe, 0x0, 0x0, 0x0)
rancher    | 	/usr/local/go/src/net/http/transport.go:711 +0x4ef
rancher    | net/http.(*Transport).RoundTrip(0xc8200c2000, 0xc82001c7e0, 0xc8200c2000, 0x0, 0x0)
rancher    | 	/usr/local/go/src/net/http/transport.go:311 +0x7e9
rancher    | net/http.send(0xc82001c700, 0x7fa343540578, 0xc8200c2000, 0xed1a0700d, 0x2f7e5040, 0x108f8e0, 0xc82010e4b0, 0x0, 0x0)
rancher    | 	/usr/local/go/src/net/http/client.go:260 +0x6b7
rancher    | net/http.(*Client).send(0xc820013ef0, 0xc82001c700, 0xed1a0700d, 0x2f7e5040, 0x108f8e0, 0xc820078f20, 0x0, 0x0)
rancher    | 	/usr/local/go/src/net/http/client.go:155 +0x185
rancher    | net/http.(*Client).doFollowingRedirects(0xc820013ef0, 0xc82001c700, 0xc60620, 0x0, 0x0, 0x0)
rancher    | 	/usr/local/go/src/net/http/client.go:475 +0x8a4
rancher    | net/http.(*Client).Do(0xc820013ef0, 0xc82001c700, 0x14, 0x0, 0x0)
rancher    | 	/usr/local/go/src/net/http/client.go:188 +0xff
rancher    | github.com/rancher/telemetry/vendor/github.com/rancher/go-rancher/v2.setupRancherBaseClient(0xc8200bf600, 0xc820014f00, 0x0, 0x0)
rancher    | 	/go/src/github.com/rancher/telemetry/vendor/github.com/rancher/go-rancher/v2/common.go:179 +0x90e
rancher    | github.com/rancher/telemetry/vendor/github.com/rancher/go-rancher/v2.NewRancherClient(0xc820014f00, 0xc820014f00, 0x0, 0x0)
rancher    | 	/go/src/github.com/rancher/telemetry/vendor/github.com/rancher/go-rancher/v2/generated_client.go:327 +0xcb
rancher    | github.com/rancher/telemetry/cmd.collect(0xc820024750, 0x0, 0x0)
rancher    | 	/go/src/github.com/rancher/telemetry/cmd/client.go:209 +0xd9
rancher    | github.com/rancher/telemetry/cmd.report()
rancher    | 	/go/src/github.com/rancher/telemetry/cmd/client.go:186 +0x133
rancher    | created by github.com/rancher/telemetry/cmd.clientRun
rancher    | 	/go/src/github.com/rancher/telemetry/cmd/client.go:137 +0x697
rancher    |
rancher    | goroutine 7 [select]:
rancher    | net/http.setRequestCancel.func4(0x0, 0xc820013f50, 0xc820014fc0, 0xc820010de0)
rancher    | 	/usr/local/go/src/net/http/client.go:333 +0x12e
rancher    | created by net/http.setRequestCancel
rancher    | 	/usr/local/go/src/net/http/client.go:341 +0x2f7
rancher    |
rancher    | goroutine 19 [select]:
rancher    | net/http.(*persistConn).readLoop(0xc82005fe10)
rancher    | 	/usr/local/go/src/net/http/transport.go:1182 +0xd52
rancher    | created by net/http.(*Transport).dialConn
rancher    | 	/usr/local/go/src/net/http/transport.go:857 +0x10a6
rancher    |
rancher    | goroutine 20 [select]:
rancher    | net/http.(*persistConn).writeLoop(0xc82005fe10)
rancher    | 	/usr/local/go/src/net/http/transport.go:1277 +0x472
rancher    | created by net/http.(*Transport).dialConn
rancher    | 	/usr/local/go/src/net/http/transport.go:858 +0x10cb
rancher    |
rancher    | goroutine 10 [select]:
rancher    | net/http.setRequestCancel.func4(0x0, 0xc82010e4e0, 0xc820015440, 0xc8200113e0)
rancher    | 	/usr/local/go/src/net/http/client.go:333 +0x12e
rancher    | created by net/http.setRequestCancel
rancher    | 	/usr/local/go/src/net/http/client.go:341 +0x2f7
rancher    |
rancher    | goroutine 11 [select]:
rancher    | net.lookupIPDeadline(0xc82010e457, 0x9, 0xed1a07021, 0x2f7f023a, 0x108f8e0, 0x0, 0x0, 0x0, 0x0, 0x0)
rancher    | 	/usr/local/go/src/net/lookup.go:109 +0x6a6
rancher    | net.internetAddrList(0xb24788, 0x3, 0xc82010e457, 0xe, 0xed1a07021, 0x2f7f023a, 0x108f8e0, 0x0, 0x0, 0x0, ...)
rancher    | 	/usr/local/go/src/net/ipsock.go:252 +0x6ee
rancher    | net.resolveAddrList(0xb223f8, 0x4, 0xb24788, 0x3, 0xc82010e457, 0xe, 0xed1a07021, 0x2f7f023a, 0x108f8e0, 0x0, ...)
rancher    | 	/usr/local/go/src/net/dial.go:158 +0x466
rancher    | net.(*Dialer).Dial(0xc82000e4b0, 0xb24788, 0x3, 0xc82010e457, 0xe, 0x0, 0x0, 0x0, 0x0)
rancher    | 	/usr/local/go/src/net/dial.go:216 +0x124
rancher    | net.(*Dialer).Dial-fm(0xb24788, 0x3, 0xc82010e457, 0xe, 0x0, 0x0, 0x0, 0x0)
rancher    | 	/usr/local/go/src/net/http/transport.go:38 +0x6e
rancher    | net/http.(*Transport).dial(0xc8200c2000, 0xb24788, 0x3, 0xc82010e457, 0xe, 0x0, 0x0, 0x0, 0x0)
rancher    | 	/usr/local/go/src/net/http/transport.go:659 +0x96
rancher    | net/http.(*Transport).dialConn(0xc8200c2000, 0x0, 0xc82010e450, 0x4, 0xc82010e457, 0xe, 0x0, 0x0, 0x0)
rancher    | 	/usr/local/go/src/net/http/transport.go:762 +0x1e3d
rancher    | net/http.(*Transport).getConn.func4(0xc8200c2000, 0x0, 0xc82010e450, 0x4, 0xc82010e457, 0xe, 0xc8200114a0)
rancher    | 	/usr/local/go/src/net/http/transport.go:706 +0x66
rancher    | created by net/http.(*Transport).getConn
rancher    | 	/usr/local/go/src/net/http/transport.go:708 +0x262
```

**Comment by superseb** [comment]
Can you share your `docker-compose.yml` file you use to start this? And  does it also occur when you run `docker run -d --restart=unless-stopped -p 8080:8080 rancher/server:v1.6.11` ?

**Comment by superseb** [comment]
Any update on this @colinlabs ?

**Comment by colinlabs** [comment]
sorry, I just saw your message, it always occur when i `restart` or `up`,this is my `docker-compose.yml`
```
version: "2"
services:
  rancher:
    image: rancher/server:v1.6.10
    container_name: rancher
    restart: always
    environment:
    - CATTLE_DB_CATTLE_DATABASE=mysql
    - CATTLE_DB_CATTLE_MYSQL_HOST=mysql
    - CATTLE_DB_CATTLE_MYSQL_NAME=rancher
    - CATTLE_DB_CATTLE_MYSQL_PORT=3306
    - CATTLE_DB_CATTLE_USERNAME=rancher
    - CATTLE_DB_CATTLE_PASSWORD=p@assword
    - VIRTUAL_HOST=rancher.simpletour.com
    - VIRTUAL_PORT=8080
    - VIRTUAL_PROTO=https
    command: --advertise-address 172.17.10.1
    ports:
    - 9345:9345
    - 8081:8080

networks:
  default:
    external:
      name: core
```

**Comment by superseb** [comment]
If I run just this, I won't get a trace. Can you share the full log? And the output of `docker network inspect core`

**Comment by colinlabs** [comment]
@superseb  gist https://gist.github.com/colinlabs/f8c1d40d1dbfe2f1692c72cc39c26c35,

`docker network inspect core`
```
[
    {
        "Name": "core",
        "Id": "233569bea57bbc9529f397e00ed74aea09effe251c5592366d8e3d5d36d64671",
        "Created": "2017-11-02T10:16:56.716530599+08:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.19.0.0/16",
                    "Gateway": "172.19.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Containers": {
            "36e50e026e0b0e220e748e1a2c987b21377978ef6840701649bf0ed999b32c36": {
                "Name": "rancher",
                "EndpointID": "0d43f3aaea1b68f6107abc9b6baf54bc87a18fcfa61c5d6af7c67a29dcb65b69",
                "MacAddress": "02:42:ac:13:00:02",
                "IPv4Address": "172.19.0.2/16",
                "IPv6Address": ""
            },
            "3ce7a04ee271880a0a6935180b25596da60e9bb37abd293af8fbe59542f1c967": {
                "Name": "harbor-ui",
                "EndpointID": "47113024c339d9d961dfe54871c8f373df5cde6368caacbcd3a224efa9b22b46",
                "MacAddress": "02:42:ac:13:00:07",
                "IPv4Address": "172.19.0.7/16",
                "IPv6Address": ""
            },
            "42dd3384807f0a3bbb799cb3d7fc5c448f0bc62cfc96d415c9d8e0e5f5648175": {
                "Name": "registry",
                "EndpointID": "8034be96393e98f909291fec7c399f02c24a707d46f59d29887db2b1549c397a",
                "MacAddress": "02:42:ac:13:00:04",
                "IPv4Address": "172.19.0.4/16",
                "IPv6Address": ""
            },
            "451292d6dc6d002d72715792e8017b3c562233b7c3cde9280eac0f3dc7d80624": {
                "Name": "nginx-proxy",
                "EndpointID": "9b8636c0e053e116844aebf88d0904b609817ffc31e6f24e8e0f8665871dfee0",
                "MacAddress": "02:42:ac:13:00:03",
                "IPv4Address": "172.19.0.3/16",
                "IPv6Address": ""
            },
            "64130a7dc5f3f357e27221a3615a0435686dffa5f735350e02c6563dde8d4951": {
                "Name": "harbor-jobservice",
                "EndpointID": "f8fb14d789df3256ee393ba82588cb56d9128df0e7e463a75808bad427a28cf6",
                "MacAddress": "02:42:ac:13:00:08",
                "IPv4Address": "172.19.0.8/16",
                "IPv6Address": ""
            },
            "e01514c02d56304694932e0871b44525aebc816649d7bf0928d91b2eaa086519": {
                "Name": "harbor-adminserver",
                "EndpointID": "73e0c914f27c6acb1290f1c18deed343a61257bda4ec2ed4dd29c0099f9a172c",
                "MacAddress": "02:42:ac:13:00:06",
                "IPv4Address": "172.19.0.6/16",
                "IPv6Address": ""
            },
            "ef9c57f32af41756be3d123b7171d20a8dea1a41d5206d0b0ea7b6387e971506": {
                "Name": "harbor-proxy",
                "EndpointID": "fadbf294ea864368edfea171958b0e03016a077a6e3610da82cc42d4e19aeee7",
                "MacAddress": "02:42:ac:13:00:05",
                "IPv4Address": "172.19.0.5/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
