### ISSUE TITLE
rancher/container-crontab is panicing on invalid cron.schedule syntax

### ISSUE THREAD

**Issue by useltmann** [rancher/rancher#10369]
**Rancher versions:**
rancher/server: v1.6.10
rancher/agent: v1.2.6

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: v0.11.9
network-services:
* rancher/metadata:v0.9.4
* rancher/network-manager:v0.7.8
scheduler: v0.8.2
kubernetes (if applicable): -

**Docker version: (`docker version`,`docker info` preferred)**
```bash
$ docker info
Containers: 30
 Running: 27
 Paused: 0
 Stopped: 3
Images: 54
Server Version: 17.03.2-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: rancher-secrets local rancher-nfs
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.45-rancher
Operating System: RancherOS v1.1.0
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67 GiB
Name: john
ID: UAW3:ZOJU:ISXD:GDRB:RI7Q:WIWS:3FK4:6JYY:XUK6:EGFP:NF46:YYND
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```bash
$ uname -r
4.9.45-rancher
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMWare

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. have a infrastructure service 'container-crontab'
2. create a service with label `cron.schedule` and empty value.
3. watch 'container-crontab' container restart endlessly with the error
```
goroutine 1 [running]:
panic(0x7fb640, 0xc42000c090)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/rancher/container-crontab/vendor/github.com/robfig/cron.Parser.Parse(0xff, 0x1, 0x0, 0x0, 0xcc000000005060fa, 0x8, 0xccf2a72134421474, 0x0)
	/go/src/github.com/rancher/container-crontab/vendor/github.com/robfig/cron/parser.go:79 +0x89a
github.com/rancher/container-crontab/vendor/github.com/robfig/cron.Parse(0x0, 0x0, 0x40ba81, 0xc42028e260, 0xc42030ef28, 0xc42030eea8)
	/go/src/github.com/rancher/container-crontab/vendor/github.com/robfig/cron/parser.go:182 +0x4d
github.com/rancher/container-crontab/vendor/github.com/robfig/cron.(*Cron).AddJob(0xc4201f86e0, 0x0, 0x0, 0xc1bf20, 0xc42029cf50, 0x1, 0x1)
	/go/src/github.com/rancher/container-crontab/vendor/github.com/robfig/cron/cron.go:103 +0x3f
github.com/rancher/container-crontab/cron.(*Crontab).AddJob(0xc42024e780, 0xc4202980c0, 0x40, 0xc420290240, 0x85ea12, 0x6, 0x0, 0x0)
	/go/src/github.com/rancher/container-crontab/cron/cron.go:59 +0x29d
github.com/rancher/container-crontab/events.NewDockerHandler(0x845a60)
	/go/src/github.com/rancher/container-crontab/events/events.go:54 +0x2b8
github.com/rancher/container-crontab/events.StartRouter(0xc1d2e0, 0xc42022a680)
	/go/src/github.com/rancher/container-crontab/events/events.go:100 +0x56
main.start(0xc420224b40, 0x5, 0xc42016fc00)
	/go/src/github.com/rancher/container-crontab/main.go:43 +0x5e
github.com/rancher/container-crontab/vendor/github.com/urfave/cli.HandleAction(0x7e7f60, 0x88c7b0, 0xc420224b40, 0xc4201da720, 0x0)
	/go/src/github.com/rancher/container-crontab/vendor/github.com/urfave/cli/app.go:485 +0xd4
github.com/rancher/container-crontab/vendor/github.com/urfave/cli.(*App).Run(0xc42008cb60, 0xc42000c1f0, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/rancher/container-crontab/vendor/github.com/urfave/cli/app.go:259 +0x74f
main.main()
	/go/src/github.com/rancher/container-crontab/main.go:34 +0x1b3
time="2017-11-20T09:41:01Z" level=info msg="Starting Cron"
time="2017-11-20T09:41:01Z" level=info msg="Scanning for container cron entries"
time="2017-11-20T09:41:01Z" level=info msg="Added: 82553c757a953d54eb1a616534b0aa401d73a7ff294d1d2c7512aa6c71b3971e, with schedule: 0 0 0 * * ?"
panic: runtime error: index out of range
```
One can see, that the first container with correct `cron.schedule` syntax is added, and the second container causes a `panic`. 

**Results:**
Services with correct `cron.schedule` will not be executed.

**Expected:**
services with invalid syntax should be ignored, at least not causing a panic.

**Comment by stieler-it** [comment]
Just wanted to say that the current fail-fast approach helps to quickly notice an invalid schedule configuration. Otherwise it would only be visible in the container logs or if some cron jobs are simply not executed. So the bug could actually be considered as a feature.
However, it should behave congruently - so if the panic only occurs in case of an empty `cron.schedule` (and maybe not if it is invalid in some other way) - it is not useful this way.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
