### ISSUE TITLE
Regions - After environment name is changed, metadata does not establish links with this environment when LB services are created with cross environment targets.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10364]
Rancher versions: Build from https://github.com/alena1108/cattle - "region" branch
network policy manager - leodotcloud/network-policy-manager:regions

Steps to reproduce the problem:
Had following setup:
Region1 with environments - "test1","test2","test3"
Region2 with environments - "test1","test2"

Region2/test2 had Lbs with targets from Region1/test1 , Region1/test2
LB work works as expected and is able to target services cross region.

Edit Region1/test1 environment and set its name to test12
LB does not have targets from this region anymore which is expected.

Edit LB and change the existing portRule to point region from "test1" to "test12".
Even after this, we do not see any environments getting linked and targets are not getting populated from this environment.

Starting new Lb services which have port rules having region set to "test12" is also not working.
Current environment when Lb service is present does not get linked to environment with edited name.

Following errors seen in cattle server logs:

```
2017-11-18 00:06:18,495 ERROR [:] [] [] [] [p2023938592-360] [i.c.p.s.s.impl.RegionServiceImpl    ] Failed to create external agent java.io.IOException: Failed to create external agent with uri [event:///
external=region2_test2_62cfdc5d-b5c7-4a5a-83ef-39194a3c60a2_44dcd4c0-f26d-4247-9131-d0fd1d8c6401] in environment [test12] in region [region1]: response error code status code 422
        at io.cattle.platform.servicediscovery.service.impl.RegionUtil$5.handleResponse(RegionUtil.java:134)
        at io.cattle.platform.servicediscovery.service.impl.RegionUtil$5.handleResponse(RegionUtil.java:129)
        at org.apache.http.client.fluent.Response.handleResponse(Response.java:85)
        at io.cattle.platform.servicediscovery.service.impl.RegionUtil.createExternalAgent(RegionUtil.java:129)
        at io.cattle.platform.servicediscovery.service.impl.RegionServiceImpl.createExternalAgent(RegionServiceImpl.java:289)
        at io.cattle.platform.servicediscovery.service.impl.RegionServiceImpl.reconcileExternalAgents(RegionServiceImpl.java:377)
        at io.cattle.platform.servicediscovery.service.impl.RegionServiceImpl.reconcileExternalCredentials(RegionServiceImpl.java:254)
        at io.cattle.platform.servicediscovery.service.impl.RegionServiceImpl.reconcileAgentExternalCredentials(RegionServiceImpl.java:237)
        at io.cattle.platform.configitem.context.dao.impl.MetaDataInfoDaoImpl.fetchCredentials(MetaDataInfoDaoImpl.java:657)
        at io.cattle.platform.configitem.context.dao.impl.MetaDataInfoDaoImpl.fetchSelf(MetaDataInfoDaoImpl.java:424)
        at io.cattle.platform.configitem.context.impl.ServiceMetadataInfoFactory.writeCachedGenericData(ServiceMetadataInfoFactory.java:196)
        at io.cattle.platform.configitem.context.impl.ServiceMetadataInfoFactory.writeMetadata(ServiceMetadataInfoFactory.java:120)
        at io.cattle.platform.configitem.server.model.impl.MetadataConfigItem.handleRequest(MetadataConfigItem.java:64)
        at io.cattle.platform.configitem.server.impl.ConfigItemServerImpl.handleDownload(ConfigItemServerImpl.java:97)
        at io.cattle.platform.configitem.server.impl.ConfigItemServerImpl.handleRequest(ConfigItemServerImpl.java:40)
        at io.cattle.platform.configitem.api.manager.ConfigContentManager.handle(ConfigContentManager.java:80)
        at io.cattle.platform.configitem.api.manager.ConfigContentManager.getByIdInternal(ConfigContentManager.java:49)
        at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.getById(AbstractBaseResourceManager.java:61)
        at io.github.ibuildthecloud.gdapi.request.handler.ResourceManagerRequestHandler.generate(ResourceManagerRequestHandler.java:50)
        at io.github.ibuildthecloud.gdapi.request.handler.AbstractResponseGenerator.handle(AbstractResponseGenerator.java:14)
        at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.handle(DefaultReadWriteApiDelegate.java:27)
        at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.read(DefaultReadWriteApiDelegate.java:17)
        at sun.reflect.GeneratedMethodAccessor407.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:280)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy66.read(Unknown Source)
        at io.github.ibuildthecloud.gdapi.request.handler.write.ReadWriteApiHandler.handle(ReadWriteApiHandler.java:21)
        at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:99)
        at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:96)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
        at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:106)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
"cattle-error.log" 750 lines, 76728 characters
        at io.cattle.platform.configitem.api.manager.ConfigContentManager.getByIdInternal(ConfigContentManager.java:49)
        at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.getById(AbstractBaseResourceManager.java:61)
        at io.github.ibuildthecloud.gdapi.request.handler.ResourceManagerRequestHandler.generate(ResourceManagerRequestHandler.java:50)
        at io.github.ibuildthecloud.gdapi.request.handler.AbstractResponseGenerator.handle(AbstractResponseGenerator.java:14)
        at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.handle(DefaultReadWriteApiDelegate.java:27)
        at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.read(DefaultReadWriteApiDelegate.java:17)
        at sun.reflect.GeneratedMethodAccessor407.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:280)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy66.read(Unknown Source)
        at io.github.ibuildthecloud.gdapi.request.handler.write.ReadWriteApiHandler.handle(ReadWriteApiHandler.java:21)
        at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:99)
        at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:96)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
        at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:106)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by sangeethah** [comment]
This issue still exists when testing with latest build from 1.6 branch.

Had following setup:
Region1 with environments - "test1","test2","test3"
Region2 with environments - "test1","test2","test3"

Region1/test1 had Lbs with targets from Region2/test3 
LB work works as expected and is able to target services cross region.

Edit Region2/test3 environment and set its name to test3new
LB does not have targets from this region anymore which is expected.

Edit LB and change the existing portRule to point region from "test3" to "test3new".
Even after this, we do not see any environments getting linked and targets are not getting populated from this environment.

We see a new account_link entry being created in the DB . But metadata still does not reflect the new region as being linked. 

data field for the new account_link created is empty in this case:
```
| 10 | NULL |         14 | accountLink | 808f56f2-7897-4df1-bd57-0da168fd75dc | NULL        | inactive    | 2018-01-30 00:22:46 | NULL                | NULL                | {}                                                         |              NULL | test3new       |                2 | region1       |          |
+----+------+------------+-------------+--------------------------------------+-------------+-------------+---------------------+---------------------+---------------------+------------------------------------------------------------+-------------------+----------------+------------------+---------------+----------+
```

**Comment by sangeethah** [comment]
Tested with latest build from 1.6 branch. After environment name is changed and LB service is edited to reflect the new environment name , LB becomes functional and is able to reach targets cross region as expected.
