### ISSUE TITLE
HTTP ERROR 403 Problem accessing /. Reason: Forbidden

### ISSUE THREAD

**Issue by dkirrane** [rancher/rancher#10410]
**Rancher versions:**
latest 2.0 preview

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): kubeadm cluster with k8s v1.8.4

**Docker version: (`docker version`,`docker info` preferred)**
```
 docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-61.git85d7426.el7.centos.x86_64
 Go version:      go1.8.3
 Git commit:      85d7426/1.12.6
 Built:           Tue Oct 24 15:40:21 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-61.git85d7426.el7.centos.x86_64
 Go version:      go1.8.3
 Git commit:      85d7426/1.12.6
 Built:           Tue Oct 24 15:40:21 2017
 OS/Arch:         linux/amd64
```

```
docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-253:0-16840378-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.509 GB
 Data Space Total: 107.4 GB
 Data Space Available: 15 GB
 Metadata Space Used: 2.49 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp
Kernel Version: 3.10.0-693.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 2
Total Memory: 1.789 GiB
Name: rancher
ID: XPM2:A4MH:INZD:MGRR:HIH4:FY4T:25RP:NBYY:MK6T:YS6O:IQPS:5M6S
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 24
 Goroutines: 32
 System Time: 2017-11-27T20:51:23.422227621Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Insecure Registries:
 mynexusreg:60001
 mynexusreg:60002
 127.0.0.0/8
Registries: docker.io (secure)
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMWare Centos 7.4 vms

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

sudo docker run -d --restart=unless-stopped -p 8080:8080 rancher/server:preview

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
sudo docker run -d --restart=unless-stopped -p 8080:8080 rancher/server:preview

**Results:**
http://<host-ip>:8080/

![image](https://user-images.githubusercontent.com/1280116/33286620-da81cadc-d3ad-11e7-9cd7-6b6b564a3d77.png)

**Comment by superseb** [comment]
Hi,

Can you check if the fix supplied in https://github.com/rancher/rancher/issues/10396 works for you?

**Comment by dkirrane** [comment]
Hi,
Don't have a proxy.
I tried stop the container and start again and now I'm htting

```
/usr/bin/docker-current: Error response from daemon: driver failed programming external connectivity on endpoint jovial_wilson (b4ff3a22a68e3be2e0efe51d72ec402a5cc45d71c3ca13c83fa70fa357629113):
iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 8080 -j DNAT --to-destination 172.17.0.2:8080 ! -i docker0: iptables: No chain/target/match by that name.
 (exit status 1).
```

**Comment by superseb** [comment]
Can you supply output of `docker version` and `docker info`?

**Comment by dkirrane** [comment]
Updated above. 
docker logs shows `Failed to load UI from [https://releases.rancher.com/ui/2.0.11/index.html] javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

My company uses an intermediate root certificate. Anyway to add that cert so it can be used to verify https://releases.rancher.com/ui/2.0.11/index.html

Full docker logs
```
2017-11-27 20:51:34,916 ERROR [:] [] [] [] [core-7         ] [i.c.p.e.manager.impl.LoopWrapper    ] Loop [conditions-loop] [null] 2/2/0 7ms java.lang.NullPointerException: null
        at io.cattle.platform.loop.ConditionsLoop.checkHealthyHosts(ConditionsLoop.java:76)
        at io.cattle.platform.loop.ConditionsLoop.run(ConditionsLoop.java:31)
        at io.cattle.platform.engine.manager.impl.LoopWrapper.lambda$executeLoop$1(LoopWrapper.java:112)
        at io.cattle.platform.deferred.util.DeferredUtils.nest(DeferredUtils.java:53)
        at io.cattle.platform.engine.manager.impl.LoopWrapper.executeLoop(LoopWrapper.java:112)
        at org.apache.cloudstack.managed.context.NoException$1.doRun(NoException.java:10)
        at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:36)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:57)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:110)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:54)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:33)
        at org.apache.cloudstack.managed.context.NoException.run(NoException.java:12)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2017-11-27 20:51:35,223 ERROR [:] [] [] [] [main           ] [i.c.platform.api.servlet.IndexFile  ] Failed to load UI from [https://releases.rancher.com/ui/2.0.11/index.html] javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at io.cattle.platform.api.servlet.IndexFile.reloadIndex(IndexFile.java:76)
```

**Comment by superseb** [comment]
Ok, thanks. The error you get during restart sounds like an issue with `firewalld` tbh. Restarting Docker could fix it.

Regarding the download, I'm starting to see where this is going wrong. Can you run `sudo docker run -d --restart=unless-stopped -p 8080:8080 rancher/server:v2.0.0-alpha10` just to isolate this to the UI not being able to be downloaded? Remember that this technical preview still needs proper internet access.

**Comment by dkirrane** [comment]
Thanks, that works
```
docker rm -f -v <containerId>
systemctl disable firewalld
systemctl stop firewalld
systemctl restart docker
sudo docker run -d --restart=unless-stopped -p 8080:8080 rancher/server:v2.0.0-alpha10
```

**Comment by mumutu66** [comment]
got same problem

**Comment by superseb** [comment]
With the release of [Tech Preview 2](https://forums.rancher.com/t/rancher-release-v2-0-0-tech-preview-2/8282/3), the architecture behind 2.0 has significantly changed. Any issues with any release prior to v2.0.0-alpha12 is most likely invalid. 

Please watch our [Tech Preview 2 meetup](https://www.youtube.com/watch?v=ld7ctOg3waM) to learn more about the changes in 2.0 in Tech Preview 2. 

Please file new issues after using Tech Preview 2 (any release v2.0.0-alpha12+). As always, thanks for using Rancher!
