### ISSUE TITLE
New Environment with Kubernetes stuck at  Creating Kubernetes system stack

### ISSUE THREAD

**Issue by mickengland** [rancher/rancher#10454]
*Describe your issue here*

I am having difficulty getting a kubernetes environment up and running. I tried first in v1.6.11 and now on latest v1.6.12 after completely recreating my environment, including RDS instances. When the host first comes up I see the Network-services stack created but not running and no ipsec or healthcheck stacks. If I manually start the network-stack it comes up fine. I am then able to install the ipsec stack from the catalog and when this is up install the healthcheck stack. All of these come up as active but when I click kubernetes it is stuck in the "Creating Kubernetes system stack" under Setting up Kubernetes.

Any advice appreciated. This is using the current default kubernetes template Kubernetes v1.8.3.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.12` Cattle: `v0.183.30` UI: `v1.6.30` |
|Access|`github` `admin`|
|Orchestration|`Kubernetes`|
|Route|`k8s-tab.dashboard`|

**Comment by aemneina** [comment]
can you provide info on the hosts (OS, docker version, uname -a). Are you deploying a kubernetes environment template, unmodified?

**Comment by mickengland** [comment]
Yes I am trying to run a kubernetes environment from an unmodified template. Here is the host info:

Operating System: RancherOS \v \n \l
uname: Linux rancher-k8-host 4.9.45-rancher #1 SMP Sun Aug 27 23:25:47 UTC 2017 x86_64 GNU/Linux
Docker version 1.12.6, build 78d1802

**Comment by superseb** [comment]
Can you share the logging in the `rancher/server` container?

**Comment by mickengland** [comment]
Here are the rancher/server logs:

[log.txt](https://github.com/rancher/rancher/files/1527389/log.txt)

**Comment by superseb** [comment]
Please create the database with the character set/collation from the docs and let me know if that resolves it (http://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/#single-container-external-database);

```CREATE DATABASE IF NOT EXISTS cattle COLLATE = 'utf8_general_ci' CHARACTER SET = 'utf8';
```

**Comment by mickengland** [comment]
My database is running on RDS. I dropped the database and recreated it with those options then restarted the servers but I am seeing a bunch of errors on startup

```
Query is : CREATE INDEX idx_label_key_value ON label(`key`(255), `value`(255))
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:139)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.getException(ExceptionMapper.java:101)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwAndLogException(ExceptionMapper.java:77)
	at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:224)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:253)
	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:266)
	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:294)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:54)
	... 176 common frames omitted
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Duplicate key name 'idx_label_key_value'
Query is : CREATE INDEX idx_label_key_value ON label(`key`(255), `value`(255))
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1115)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1047)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1002)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:142)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:243)
	... 181 common frames omitted
STARTUP FAILED [17936] ms
```

**Comment by mickengland** [comment]
Looks like I am running into this issue:

https://github.com/rancher/rancher/issues/10341

```
mysql> SELECT @@character_set_database, @@collation_database;
+--------------------------+----------------------+
| @@character_set_database | @@collation_database |
+--------------------------+----------------------+
| latin1                   | latin1_swedish_ci    |
+--------------------------+----------------------+
```
Verified this with a fresh install. Will try running the reference script.

**Comment by mickengland** [comment]
Running the commands in the last comment of the issue linked above worked and Kubernetes initialization resumed straight away with no server restart needed.
