### ISSUE TITLE
Regions - "500 Internal Server Error" when trying to create a external service link with no alias name. Not able to load stack/user UI anymore.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10462]
Rancher versions: Build from https://github.com/alena1108/cattle - "region" branch
network policy manager - leodotcloud/network-policy-manager:regions

Steps to reproduce the problem:Had following setup:
Region1 with environments - "test1","test2"
There were 2 hosts in both the environments.
"network policy manager"  was deployed with "allow within linked services" and deny for all other policies.

From test1 environment:
Create a service test1 with service link pointing to "region1/test2/stack1/service1" with no alias name provided.

NullPointerException exception seen in logs:
```
2017-12-02 00:43:01,944 DEBUG [:] [] [] [] [ecutorService-7] [i.c.p.c.v.impl.ConfigUpdatePublisher] 		Finished work item agent:133 [180190889] 
2017-12-02 00:43:02,132 ERROR [:] [] [] [] [cutorService-15] [o.a.c.m.context.NoExceptionRunnable ] Uncaught exception java.lang.NullPointerException: null
	at io.cattle.platform.iaas.api.filter.service.ServiceOutputFilter.filter(ServiceOutputFilter.java:78)
	at io.github.ibuildthecloud.gdapi.response.impl.ResourceOutputFilterChain.filter(ResourceOutputFilterChain.java:20)
	at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.convertResponse(AbstractBaseResourceManager.java:200)
	at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.convertResponse(FilteredResourceManager.java:76)
	at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.convertResponse(FilteredResourceManager.java:76)
	at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.convertResponse(FilteredResourceManager.java:76)
	at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.convertResponse(FilteredResourceManager.java:76)
	at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.convertResponse(FilteredResourceManager.java:76)
	at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.convertResponse(FilteredResourceManager.java:76)
	at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.convertResponse(FilteredResourceManager.java:76)
	at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.convertResponse(FilteredResourceManager.java:76)
	at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.convertResponse(FilteredResourceManager.java:76)
	at io.cattle.platform.iaas.api.change.impl.ResourceChangeEventProcessor.processEvent(ResourceChangeEventProcessor.java:57)
	at io.cattle.platform.api.pubsub.subscribe.NonBlockingSubscriptionHandler.postProcess(NonBlockingSubscriptionHandler.java:106)
	at io.cattle.platform.api.pubsub.subscribe.NonBlockingSubscriptionHandler$1.onEvent(NonBlockingSubscriptionHandler.java:82)
	at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:141)
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sangeethah** [comment]
After this error is seen , I tried deleting the service which was stuck in "registering" state which also fails.
Now I am not able to load UI to display user stacks . "500 Internal Server Error" encountered when UI is trying to list all services.

**Comment by sangeethah** [comment]
@alena I dont see service stuck in "registering" state anymore. But in this case , do we expect the API to error out ? How will the user be able to use this external service link in this case .

**Comment by alena1108** [comment]
@sangeethah for now, we just ignore the error. But I can add an extra API validation to error out when alias is absent while region is present in the link

**Comment by sangeethah** [comment]
Tested with Rancher server version-v1.6.13-rc6 .

When attempting to create services with external service link with no alias name following error is presented to the user - ``` Setservicelinks Error:Validation failed in API: name is required```
