### ISSUE TITLE
Agent will stop and panic after start a while

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#10536]
**Rancher versions:**
rancher/server: v1.6.13-rc2
rancher/agent: 

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Windows
**Steps to Reproduce:**
1. In Windows environment, Add host.
2. The agent service will start and print log.
3. after a while, agent print panic log as following
```
fatal error: unexpected signal during runtime execution
[signal 0xc0000005 code=0x0 addr=0x1000002b8 pc=0x40db92]

goroutine 29 [running]:
runtime.throw(0xa103fb, 0x2a)
	/usr/local/go/src/runtime/panic.go:596 +0x9c fp=0xc0422dbe18 sp=0xc0422dbdf8
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_windows.go:155 +0x18b fp=0xc0422dbe48 sp=0xc0422dbe18
runtime.unlock(0xc9a978)
	/usr/local/go/src/runtime/lock_sema.go:107 +0x72 fp=0xc0422dbe70 sp=0xc0422dbe48
runtime.chansend(0x8c6c20, 0xc9a920, 0xc0422dbfb0, 0xc0422dbf01, 0x71824a, 0xc0422dbf9c)
	/usr/local/go/src/runtime/chan.go:179 +0x8af fp=0xc0422dbf20 sp=0xc0422dbe70
runtime.chansend1(0x8c6c20, 0xc9a920, 0xc0422dbfb0)
	/usr/local/go/src/runtime/chan.go:113 +0x4d fp=0xc0422dbf60 sp=0xc0422dbf20
github.com/rancher/agent/vendor/github.com/Microsoft/go-winio.ioCompletionProcessor(0x270)
	/go/src/github.com/rancher/agent/vendor/github.com/Microsoft/go-winio/file.go:131 +0xea fp=0xc0422dbfd8 sp=0xc0422dbf60
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc0422dbfe0 sp=0xc0422dbfd8
created by github.com/rancher/agent/vendor/github.com/Microsoft/go-winio.initIo
	/go/src/github.com/rancher/agent/vendor/github.com/Microsoft/go-winio/file.go:55 +0x87

goroutine 1 [IO wait]:
net.runtime_pollWait(0xe5cee0, 0x72, 0xc98350)
	/usr/local/go/src/runtime/netpoll.go:164 +0x60
net.(*pollDesc).wait(0xc0420b9be0, 0x72, 0xc98350, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x3f
net.(*ioSrv).ExecIO(0xc0420044a0, 0xc0420b9aa0, 0x9fd420, 0x7, 0xa18d18, 0x2, 0x0, 0x0)
	/usr/local/go/src/net/fd_windows.go:196 +0xfe
net.(*netFD).Read(0xc0420b9a40, 0xc042468000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/fd_windows.go:452 +0x13d
net.(*conn).Read(0xc042005af8, 0xc042468000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:181 +0x77
bufio.(*Reader).Read(0xc0423fcfc0, 0xc04221ade0, 0x2, 0x8, 0xc0424db8b0, 0x40faef, 0x10)
	/usr/local/go/src/bufio/bufio.go:213 +0x319
github.com/rancher/agent/vendor/github.com/gorilla/websocket.(*Conn).readFull(0xc0423dcc00, 0xc04221ade0, 0x2, 0x8, 0x0, 0x0)
	/go/src/github.com/rancher/agent/vendor/github.com/gorilla/websocket/conn.go:617 +0x98
github.com/rancher/agent/vendor/github.com/gorilla/websocket.(*Conn).advanceFrame(0xc0423dcc00, 0xa, 0x0, 0x0)
	/go/src/github.com/rancher/agent/vendor/github.com/gorilla/websocket/conn.go:641 +0x96
github.com/rancher/agent/vendor/github.com/gorilla/websocket.(*Conn).NextReader(0xc0423dcc00, 0xc04238ea80, 0x89a1c0, 0x16, 0x0, 0x0)
	/go/src/github.com/rancher/agent/vendor/github.com/gorilla/websocket/conn.go:780 +0x5e
github.com/rancher/agent/vendor/github.com/gorilla/websocket.(*Conn).ReadMessage(0xc0423dcc00, 0xc0424a41a0, 0xc04245cf90, 0xc04238ea80, 0xc042005dd8, 0x0, 0x0)
	/go/src/github.com/rancher/agent/vendor/github.com/gorilla/websocket/conn.go:852 +0x36
github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events.(*EventRouter).run(0xc04225dea0, 0xc9a4a0, 0xc04245e570, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events/listener.go:139 +0x760
github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events.(*EventRouter).StartWithoutCreate(0xc04225dea0, 0x0, 0x0, 0xc04235eea0)
	/go/src/github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events/listener.go:93 +0x84
github.com/rancher/agent/events.Listen(0xc04235eea0, 0x1d, 0xc04235eec0, 0x14, 0xc042325fb0, 0x28, 0xfa, 0x0, 0x60)
	/go/src/github.com/rancher/agent/events/listener.go:53 +0x3fc
main.main()
	/go/src/github.com/rancher/agent/main.go:59 +0x421
...
```

**Comment by orangedeng** [comment]
I find out that we changing to golang 1.8.3 instead of 1.7.5. We need to update dependence of following package `github.com/microsoft/go-winio` refer to https://github.com/Microsoft/go-winio/issues/41

**Comment by kingsd041** [comment]
Tested with Rancher/server:v1.6.13-rc3, the agent did not appear panic log.
