### ISSUE TITLE
Unhandled exception when creating EC2 instances

### ISSUE THREAD

**Issue by pkaramol** [rancher/rancher#10541]
**Rancher versions:**
rancher/server: 1.6.12
rancher/agent: N/A

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec:v0.13.5
network-services:
rancher/metadata:v0.9.5
rancher/network-manager:v0.7.18
scheduler:v0.8.2
kubernetes (if applicable): N/A

**Docker version: (`docker version`,`docker info` preferred)**
```bash
$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.09.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1043-aws
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 990.9MiB
Name: ip-10-0-0-58
ID: OGE4:6JUL:LEEA:QTOD:NDQC:UE2E:5OLE:I3VL:4YIK:DLHY:PNDH:NONJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
$ uname -r
4.4.0-1043-aws

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS - using `t2.micro` instance for the Server.
The Rancher server is behind a classic ELB with SSL termination (on the ELB)

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Rancher Node (EC2 t2.small instance / External DB RDS)

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1. Log in to the host running the rancher/server container
2. Get the id of the rancher/server container
3. execute `docker logs -f <container_id>`
4. Get into the process of adding EC2 instances as hosts

**Results:**
The following error appears in the logs (and the ssh connection with the server terminates abruptly)

```java
2017-12-12 15:38:34,964 ERROR [:] [] [] [] [tp1020391880-15] [i.g.i.g.s.ApiRequestFilterDelegate  ] Unhandled exception in API for request [http://rancher-elb-bd9bf16e9d3f0384.elb.eu-west-1.amazonaws.com/v2-beta/identities] java.lang.IllegalArgumentException: No enum constant io.github.ibuildthecloud.gdapi.model.Schema.Method.OPTIONS
	at java.lang.Enum.valueOf(Enum.java:238)
	at io.github.ibuildthecloud.gdapi.model.Schema$Method.valueOf(Schema.java:10)
	at io.cattle.platform.iaas.api.auditing.AuditServiceImpl.convertToAction(AuditServiceImpl.java:139)
	at io.cattle.platform.iaas.api.auditing.AuditServiceImpl.logRequest(AuditServiceImpl.java:101)
	at io.cattle.platform.iaas.api.auditing.AuditLogsRequestHandler.handle(AuditLogsRequestHandler.java:23)
	at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:99)
	at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:96)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:106)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:496)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

Host creation fails as depicted below:

![screenshot from 2017-12-13 12-56-39](https://user-images.githubusercontent.com/2778429/33935581-1f96f396-e005-11e7-9d86-0ed9cfe79143.png)

The third host on AWS console seems to be terminated for some reason.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
