### ISSUE TITLE
Rancher Master Fails to Start Cluster

### ISSUE THREAD

**Issue by alexanderson1993** [rancher/rancher#10672]
**Rancher versions:**
rancher/server: 1.6.10, 1.6.11, 1.6.12
rancher/agent: N/A

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version:**
Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel:**
NAME="RancherOS"
VERSION=v1.1.0
ID=rancheros
ID_LIKE=
VERSION_ID=v1.1.0
PRETTY_NAME="RancherOS v1.1.0"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=

**Type/provider of hosts:** AWS

**Setup details:**
HA rancher
external DB on RDS

**Environment Template:** Cattle

**Steps to Reproduce:** None, I haven't been able to reproduce it with a fresh database

**Results:**
I attempted to upgrade Rancher from 1.6.10 to 1.6.12. We use AWS Launch Configurations to spawn auto-scaling EC2 instances. After modifying the launch config with the updated docker image tag and reinstating the images, I continuously get the following error:

19:49:28.001 [main] INFO  ConsoleStatus - Loading configuration
19:49:29.431 [main] INFO  ConsoleStatus - Starting DB migration
19:49:31.770 [main] INFO  ConsoleStatus - DB migration done
19:49:32.002 [main] INFO  ConsoleStatus - Cluster membership changed [172.19.30.218:9345] *this is the IP address of the EC2 instance*
19:49:32.004 [main] INFO  ConsoleStatus - Checking cluster state on start-up
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'Startup': Invocation of init method failed; nested exception is java.lang.AbstractMethodError
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:776)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at io.cattle.platform.launcher.jetty.Main.main(Main.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.cattle.platform.launcher.Main.run(Main.java:188)
	at io.cattle.platform.launcher.Main.main(Main.java:251)
Caused by: java.lang.AbstractMethodError
	at ch.qos.logback.core.OutputStreamAppender.encoderInit(OutputStreamAppender.java:180)
	at ch.qos.logback.core.OutputStreamAppender.setOutputStream(OutputStreamAppender.java:171)
	at ch.qos.logback.core.ConsoleAppender.start(ConsoleAppender.java:81)
	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)
	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at io.cattle.platform.logback.LogbackStartup.run(LogbackStartup.java:34)
	at io.cattle.platform.logback.Startup.init(Startup.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:365)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:310)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
	... 36 more

**Comment by cinsaydev** [comment]
I am also experiencing this same issue when I attempt to upgrade from rancher server 1.6.10 to 1.6.11 and above.

**Comment by superseb** [comment]
What is the exact command used to launch the new `rancher/server` container? And are all the `rancher/server` containers shut down before starting a new one?

**Comment by cinsaydev** [comment]
For mine the exact command is `docker run -d --restart=unless-stopped -p 8080:8080 -p 9345:9345 -e JAVA_OPT="-Xmx8192m" -e CATTLE_LOGBACK_OUTPUT_CONSOLE="false" -e CATTLE_LOGBACK_OUTPUT_LOGSTASH_CONSOLE="true" rancher/server:v1.6.12 --advertise-address $(wget -qO - http://169.254.169.254/2016-06-30/meta-data/local-ipv4) --db-host $DBHOST --db-pass $DBPASS --db-name $DBNAME --db-user $DBUSER`. We have shut down the all old containers prior to loading the new ones. 

Also I can get Rancher to start again if I switch back to 1.6.10

**Comment by superseb** [comment]
Can you try without the `-e CATTLE_LOGBACK_OUTPUT_CONSOLE="false" -e CATTLE_LOGBACK_OUTPUT_LOGSTASH_CONSOLE="true"` ?

**Comment by cinsaydev** [comment]
@superseb Thank you very much that did it, removing those allowed the upgrade to 1.6.14 without issue.

**Comment by alexanderson1993** [comment]
@superseb That also worked for me. I'll go ahead and close the issue.
