### ISSUE TITLE
Upgrading Stacks takes forever, because single containers will not stop.

### ISSUE THREAD

**Issue by tknecht** [rancher/rancher#10700]
**Rancher versions:**
rancher/server: 1.6.12
rancher/agent: rancher/agent:v1.2.7

**Infrastructure Stack versions:**
healthcheck: not used
ipsec: not used
network-services: not used
scheduler: not used
kubernetes (if applicable): not used

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 1.13.1, build 092cba3

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

4.4.0-104-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
all types, DO,AWS, Bare-metal, raspberry pi, ...

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Sinlge Node, external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle without any additional services. This is only being used to run single docker containers on a huge amount of servers. Nothing else.

**Steps to Reproduce:**
Upgrade or Stop Container.

**Results:**
Some Containers go down really fast and being upgraded super fast.
Others are stuck forever.
Rancher-Agent shows:
`time="2017-12-30T00:22:39Z" level=info msg="Received event: Name: compute.instance.deactivate, Event Id: 6195d394-1d81-48a8-8cbf-98354148d58d, Resource Id: 1ihm18824"`
`time="2017-12-30T00:23:09Z" level=error msg="Error processing event" err="Failed to stop container 454be2a7-156c-4f17-b77e-7626003525f8" eventId=6195d394-1d81-48a8-8cbf-98354148d58d eventName=compute.instance.deactivate resourceId=1ihm18824
time="2017-12-30T00:23:24Z" level=info msg="Received event: Name: compute.instance.deactivate, Event Id: dad77b44-20fd-4694-90dc-d8903cd8db85, Resource Id: 1ihm18824"`
`time="2017-12-30T00:23:54Z" level=error msg="Error processing event" err="Failed to stop container 454be2a7-156c-4f17-b77e-7626003525f8" eventId=dad77b44-20fd-4694-90dc-d8903cd8db85 eventName=compute.instance.deactivate resourceId=1ihm18824`
`[...]`
`[...]`
`time="2017-12-30T00:43:55Z" level=info msg="Received event: Name: compute.instance.deactivate, Event Id: 9182b6fe-d848-411a-9d78-7f31173d41db, Resource Id: 1ihm18824"`
`time="2017-12-30T00:44:25Z" level=error msg="Error processing event" err="Failed to stop container 454be2a7-156c-4f17-b77e-7626003525f8" eventId=9182b6fe-d848-411a-9d78-7f31173d41db eventName=compute.instance.deactivate resourceId=1ihm18824`

This is now 21 minutes and no end in sight that rancher-agent tries to stop a super small mini container. 

Error Codes are useless. Forcing a stop of the container does not help, because the rancher-agent does not understand that the container is not there anymore.

**Comment by superseb** [comment]
Are the containers on the same host or on different hosts? Is there any logging of the Docker daemon that reveals any problems?

**Comment by tknecht** [comment]
I couldn't find anything in the docker logs.
These are different machines all over the place. 

What I found in the rancher-server log is the following

```
2018-01-05 16:50:03,967 ERROR [:] [] [] [] [cutorService-15] [.e.s.i.ProcessInstanceDispatcherImpl] Unknown exception running process [service.upgrade:211068] on [15] org.jooq.exception.DataChangedException: Database record has been changed
	at org.jooq.impl.UpdatableRecordImpl.checkIfChanged(UpdatableRecordImpl.java:550)
	at org.jooq.impl.UpdatableRecordImpl.storeUpdate0(UpdatableRecordImpl.java:291)
	at org.jooq.impl.UpdatableRecordImpl.access$200(UpdatableRecordImpl.java:90)
	at org.jooq.impl.UpdatableRecordImpl$3.operate(UpdatableRecordImpl.java:260)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:123)
	at org.jooq.impl.UpdatableRecordImpl.storeUpdate(UpdatableRecordImpl.java:255)
	at org.jooq.impl.UpdatableRecordImpl.update(UpdatableRecordImpl.java:149)
	at io.cattle.platform.servicediscovery.dao.impl.ServiceExposeMapDaoImpl.createServiceInstance(ServiceExposeMapDaoImpl.java:66)
	at sun.reflect.GeneratedMethodAccessor1475.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:280)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy53.createServiceInstance(Unknown Source)
	at io.cattle.platform.servicediscovery.deployment.impl.unit.DefaultDeploymentUnitInstance.create(DefaultDeploymentUnitInstance.java:137)
	at io.cattle.platform.servicediscovery.deployment.impl.unit.DeploymentUnit.createInstance(DeploymentUnit.java:378)
	at io.cattle.platform.servicediscovery.deployment.impl.unit.DeploymentUnit.createServiceInstances(DeploymentUnit.java:336)
	at io.cattle.platform.servicediscovery.deployment.impl.unit.DeploymentUnit.create(DeploymentUnit.java:327)
	at io.cattle.platform.servicediscovery.deployment.ServiceDeploymentPlanner.deploy(ServiceDeploymentPlanner.java:153)
	at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl.startUnits(DeploymentManagerImpl.java:438)
	at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl$2.run(DeploymentManagerImpl.java:403)
	at io.cattle.platform.activity.ActivityService.run(ActivityService.java:43)
	at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl.activateDeploymentUnits(DeploymentManagerImpl.java:400)
	at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:300)
	at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl.reconcileDeployment(DeploymentManagerImpl.java:160)
	at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl$1.doWithLock(DeploymentManagerImpl.java:149)
	at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl$1.doWithLock(DeploymentManagerImpl.java:137)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
	at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl.activate(DeploymentManagerImpl.java:137)
	at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl.activate(DeploymentManagerImpl.java:123)
	at io.cattle.platform.servicediscovery.upgrade.impl.UpgradeManagerImpl$5.run(UpgradeManagerImpl.java:613)
	at io.cattle.platform.activity.ActivityService.run(ActivityService.java:43)
	at io.cattle.platform.servicediscovery.upgrade.impl.UpgradeManagerImpl.activate(UpgradeManagerImpl.java:610)
	at io.cattle.platform.servicediscovery.upgrade.impl.UpgradeManagerImpl$1.doWithLockNoResult(UpgradeManagerImpl.java:168)
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7)
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
	at io.cattle.platform.servicediscovery.upgrade.impl.UpgradeManagerImpl.upgradeDeploymentUnits(UpgradeManagerImpl.java:140)
	at io.cattle.platform.servicediscovery.upgrade.impl.UpgradeManagerImpl.doInServiceUpgrade(UpgradeManagerImpl.java:112)
	at io.cattle.platform.servicediscovery.upgrade.impl.UpgradeManagerImpl.doUpgrade(UpgradeManagerImpl.java:342)
	at io.cattle.platform.servicediscovery.upgrade.impl.UpgradeManagerImpl.upgrade(UpgradeManagerImpl.java:321)
	at io.cattle.platform.servicediscovery.process.ServiceUpgrade$1.run(ServiceUpgrade.java:39)
	at io.cattle.platform.activity.ActivityService.run(ActivityService.java:43)
	at io.cattle.platform.servicediscovery.process.ServiceUpgrade.handle(ServiceUpgrade.java:36)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:470)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:421)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:415)
	at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:415)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:517)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:345)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:245)
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7)
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:242)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:184)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:157)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:116)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:113)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:113)
	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl.processExecuteWithLock(ProcessInstanceDispatcherImpl.java:136)
	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl$1.doWithLock(ProcessInstanceDispatcherImpl.java:123)
	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl$1.doWithLock(ProcessInstanceDispatcherImpl.java:120)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$4.doWithLock(AbstractLockManagerImpl.java:50)
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:25)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:47)
	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl.execute(ProcessInstanceDispatcherImpl.java:120)
	at io.cattle.platform.engine.server.ProcessInstanceReference.doRun(ProcessInstanceReference.java:59)
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
Even if I deactivate machine, it takes another 15 minutes until Rancher stops trying to stop the container and start a new one. This is blocking upgrades of all other hosts, which is a problem. 

Please let me know if there is anything else I can provide.

**Comment by superseb** [comment]
What database are you using here? As the error usually shows when the DB is slow/can't keep up.

And count is `huge amount of servers` ?

**Comment by tknecht** [comment]
mysql-server-5.7

We are using Rancher more as Orchestration tool for single instances of sensors that are spread world wide. So we do not use any of the Network Stack Stuff or anything else. We run between 1 and 4 docker containers on each of the 150 machines.

**Comment by superseb** [comment]
I'm not sure what specifications your DB server has, but I would recommend scaling the amount of hosts running `rancher/server` (HA) and check cpu/mem/disk io on the DB server.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
