### ISSUE TITLE
agents catatonic after upgrade

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#11157]
**Rancher versions:**
rancher/server: 1.6.14
rancher/agent: 1.2.9

@cjellick @StrongMonkey suggests that a handshake timeout might be missing, which caused this.

agent thread dump:
```
SIGQUIT: quit
PC=0x456c73 m=0 sigcode=0

goroutine 6 [syscall]:
runtime.notetsleepg(0xf75bd8, 0x654b9fa8, 0x0)
	/usr/local/go/src/runtime/lock_futex.go:205 +0x42 fp=0xc420026760 sp=0xc420026730
runtime.timerproc()
	/usr/local/go/src/runtime/time.go:209 +0x327 fp=0xc4200267e0 sp=0xc420026760
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4200267e8 sp=0xc4200267e0
created by runtime.addtimerLocked
	/usr/local/go/src/runtime/time.go:116 +0xed

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7fc797f11e38, 0x72, 0x6)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc42033eae8, 0x72, 0xf46b80, 0xf42870)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc42033eae8, 0xc42022c400, 0x400)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc42033ea80, 0xc42022c400, 0x400, 0x400, 0x0, 0xf46b80, 0xf42870)
	/usr/local/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc42017c000, 0xc42022c400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:181 +0x70
crypto/tls.(*block).readFromUntil(0xc42035e0c0, 0x7fc796e43000, 0xc42017c000, 0x5, 0xc42017c000, 0x402d1d)
	/usr/local/go/src/crypto/tls/conn.go:488 +0x98
crypto/tls.(*Conn).readRecord(0xc420228000, 0xa91717, 0xc420228120, 0x4e84d2)
	/usr/local/go/src/crypto/tls/conn.go:590 +0xc4
crypto/tls.(*Conn).Read(0xc420228000, 0xc42022f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1134 +0x11d
bufio.(*Reader).Read(0xc4201e6840, 0xc42051aa50, 0x2, 0x8, 0xc4201838e8, 0x4101e8, 0x10)
	/usr/local/go/src/bufio/bufio.go:213 +0x312
github.com/rancher/agent/vendor/github.com/gorilla/websocket.(*Conn).readFull(0xc42000af00, 0xc42051aa50, 0x2, 0x8, 0x428c86, 0xc420064e00)
	/go/src/github.com/rancher/agent/vendor/github.com/gorilla/websocket/conn.go:617 +0x91
github.com/rancher/agent/vendor/github.com/gorilla/websocket.(*Conn).advanceFrame(0xc42000af00, 0xc420183a78, 0xc420183a68, 0x70147d)
	/go/src/github.com/rancher/agent/vendor/github.com/gorilla/websocket/conn.go:641 +0x8f
github.com/rancher/agent/vendor/github.com/gorilla/websocket.(*Conn).NextReader(0xc42000af00, 0xc420082a80, 0x910cc0, 0xd7, 0x0, 0x0)
	/go/src/github.com/rancher/agent/vendor/github.com/gorilla/websocket/conn.go:780 +0x57
github.com/rancher/agent/vendor/github.com/gorilla/websocket.(*Conn).ReadMessage(0xc42000af00, 0xc42019c8f0, 0xc420444930, 0xc420082a80, 0xc42017c058, 0x0, 0x0)
	/go/src/github.com/rancher/agent/vendor/github.com/gorilla/websocket/conn.go:852 +0x2f
github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events.(*EventRouter).run(0xc420116780, 0xf44880, 0xc4205031f0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events/listener.go:139 +0x759
github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events.(*EventRouter).StartWithoutCreate(0xc420116780, 0x0, 0x0, 0xc42001410b)
	/go/src/github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events/listener.go:93 +0x7d
github.com/rancher/agent/events.Listen(0xc42001410b, 0x2a, 0xc4200160a2, 0x14, 0xc4200140d2, 0x28, 0xfa, 0xc4201a9f28, 0x729a98)
	/go/src/github.com/rancher/agent/events/listener.go:53 +0x3f5
main.main()
	/go/src/github.com/rancher/agent/main.go:65 +0x333

goroutine 17 [syscall, 71 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 8 [chan receive, 60 minutes]:
github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/locks.locker()
	/go/src/github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/locks/locks.go:95 +0xf0
created by github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/locks.init.1
	/go/src/github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/locks/locks.go:6 +0x35

goroutine 9 [chan receive]:
github.com/rancher/agent/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0xf760e0)
	/go/src/github.com/rancher/agent/vendor/github.com/golang/glog/glog.go:879 +0x7a
created by github.com/rancher/agent/vendor/github.com/golang/glog.init.1
	/go/src/github.com/rancher/agent/vendor/github.com/golang/glog/glog.go:410 +0x21d

goroutine 87 [IO wait, 71 minutes]:
net.runtime_pollWait(0x7fc797f11fb8, 0x72, 0x9)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc42033ebc8, 0x72, 0xf46b80, 0xf42870)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc42033ebc8, 0xc4203b4000, 0x1000)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc42033eb60, 0xc4203b4000, 0x1000, 0x1000, 0x0, 0xf46b80, 0xf42870)
	/usr/local/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc42000e610, 0xc4203b4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:181 +0x70
net/http.(*persistConn).Read(0xc42034b200, 0xc4203b4000, 0x1000, 0x1000, 0xc4200cd000, 0xc4201765a0, 0x0)
	/usr/local/go/src/net/http/transport.go:1316 +0x14b
bufio.(*Reader).fill(0xc420363680)
	/usr/local/go/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).ReadSlice(0xc420363680, 0xc6350cdd854e6f0a, 0xc9ed70fc598973e7, 0x26a31d28764216ea, 0x7120dbd46b1b3c34, 0x3194b7d470e5fa55, 0x4c92969b864ce8f1)
	/usr/local/go/src/bufio/bufio.go:338 +0xbb
net/http/internal.readChunkLine(0xc420363680, 0x0, 0x0, 0x9b65acaca7b34e62, 0x1f783d53813432f0, 0x53a2438985b51148)
	/usr/local/go/src/net/http/internal/chunked.go:122 +0x34
net/http/internal.(*chunkedReader).beginChunk(0xc420444d50)
	/usr/local/go/src/net/http/internal/chunked.go:48 +0x32
net/http/internal.(*chunkedReader).Read(0xc420444d50, 0xc420084800, 0x200, 0x200, 0xc420014180, 0xc420084800, 0x65230d)
	/usr/local/go/src/net/http/internal/chunked.go:93 +0x128
net/http.(*body).readLocked(0xc42048fb40, 0xc420084800, 0x200, 0x200, 0x0, 0x7fc799768000, 0x0)
	/usr/local/go/src/net/http/transfer.go:761 +0x61
net/http.(*body).Read(0xc42048fb40, 0xc420084800, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transfer.go:753 +0xfd
net/http.(*bodyEOFSignal).Read(0xc42048fb80, 0xc420084800, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:2035 +0xe9
encoding/json.(*Decoder).refill(0xc4201bb340, 0x80, 0x78)
	/usr/local/go/src/encoding/json/stream.go:152 +0x109
encoding/json.(*Decoder).readValue(0xc4201bb340, 0x0, 0x0, 0x4101e8)
	/usr/local/go/src/encoding/json/stream.go:128 +0x1ca
encoding/json.(*Decoder).Decode(0xc4201bb340, 0x919a00, 0xc420345c80, 0xf44f00, 0xc42048fb80)
	/usr/local/go/src/encoding/json/stream.go:57 +0x85
github.com/rancher/agent/vendor/github.com/docker/docker/client.(*Client).Events.func1(0xc4203630e0, 0xc42033e000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fc797ec6080, 0xc4204fb900, 0xc420363080)
	/go/src/github.com/rancher/agent/vendor/github.com/docker/docker/client/events.go:50 +0x262
created by github.com/rancher/agent/vendor/github.com/docker/docker/client.(*Client).Events
	/go/src/github.com/rancher/agent/vendor/github.com/docker/docker/client/events.go:63 +0xe2

goroutine 42 [select, 71 minutes]:
github.com/rancher/agent/service/hostapi/events.(*EventRouter).Start.func1(0xc4201cef90)
	/go/src/github.com/rancher/agent/service/hostapi/events/event_router.go:57 +0x33f
created by github.com/rancher/agent/service/hostapi/events.(*EventRouter).Start
	/go/src/github.com/rancher/agent/service/hostapi/events/event_router.go:73 +0xda

goroutine 12 [IO wait]:
net.runtime_pollWait(0x7fc797f11cb8, 0x72, 0x8)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc420369878, 0x72, 0xf46b80, 0xf42870)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420369878, 0xc420508000, 0x800)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc420369810, 0xc420508000, 0x800, 0x800, 0x0, 0xf46b80, 0xf42870)
	/usr/local/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc42032ca88, 0xc420508000, 0x800, 0x800, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:181 +0x70
crypto/tls.(*block).readFromUntil(0xc4200bd7d0, 0x7fc796e43000, 0xc42032ca88, 0x5, 0xc42032ca88, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:488 +0x98
crypto/tls.(*Conn).readRecord(0xc420179180, 0xa91717, 0xc4201792a0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:590 +0xc4
crypto/tls.(*Conn).Read(0xc420179180, 0xc4201b9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1134 +0x11d
bufio.(*Reader).Read(0xc4200182a0, 0xc42051a918, 0x2, 0x8, 0xc42012b510, 0x4101e8, 0x8)
	/usr/local/go/src/bufio/bufio.go:213 +0x312
github.com/rancher/agent/vendor/github.com/gorilla/websocket.(*Conn).readFull(0xc42000a500, 0xc42051a918, 0x2, 0x8, 0x0, 0x0)
	/go/src/github.com/rancher/agent/vendor/github.com/gorilla/websocket/conn.go:617 +0x91
github.com/rancher/agent/vendor/github.com/gorilla/websocket.(*Conn).advanceFrame(0xc42000a500, 0xa, 0x0, 0x0)
	/go/src/github.com/rancher/agent/vendor/github.com/gorilla/websocket/conn.go:641 +0x8f
github.com/rancher/agent/vendor/github.com/gorilla/websocket.(*Conn).NextReader(0xc42000a500, 0x1, 0x5b3a1c7f51174fd6, 0x0, 0x10, 0xc42012ba00)
	/go/src/github.com/rancher/agent/vendor/github.com/gorilla/websocket/conn.go:780 +0x57
github.com/rancher/agent/vendor/github.com/gorilla/websocket.(*Conn).ReadMessage(0xc42000a500, 0xc42012b928, 0xc42012b858, 0x24, 0xc42012ba78, 0x1, 0xc420497d70)
	/go/src/github.com/rancher/agent/vendor/github.com/gorilla/websocket/conn.go:852 +0x2f
github.com/rancher/agent/vendor/github.com/rancher/websocket-proxy/backend.connectToProxyWS(0xc42000a500, 0xc42012be90, 0x26e, 0xc4200bd3e0)
	/go/src/github.com/rancher/agent/vendor/github.com/rancher/websocket-proxy/backend/backend.go:63 +0x1ab
github.com/rancher/agent/vendor/github.com/rancher/websocket-proxy/backend.ConnectToProxy(0xc4204e0c80, 0x26e, 0xc42012be90, 0xa76ab1, 0x7)
	/go/src/github.com/rancher/agent/vendor/github.com/rancher/websocket-proxy/backend/backend.go:33 +0x426
github.com/rancher/agent/service/hostapi.StartUp()
	/go/src/github.com/rancher/agent/service/hostapi/hostapi.go:98 +0xd42
created by github.com/rancher/agent/events.Listen
	/go/src/github.com/rancher/agent/events/listener.go:26 +0x2d6

goroutine 13 [sleep]:
time.Sleep(0x77359400)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/rancher/agent/events.Listen.func1()
	/go/src/github.com/rancher/agent/events/listener.go:35 +0x5f
created by github.com/rancher/agent/events.Listen
	/go/src/github.com/rancher/agent/events/listener.go:37 +0x2ee

goroutine 103 [select]:
github.com/rancher/agent/vendor/github.com/rancher/websocket-proxy/backend.connectToProxyWS.func1(0xc420018300, 0xc42000a500)
	/go/src/github.com/rancher/agent/vendor/github.com/rancher/websocket-proxy/backend/backend.go:45 +0x362
created by github.com/rancher/agent/vendor/github.com/rancher/websocket-proxy/backend.connectToProxyWS
	/go/src/github.com/rancher/agent/vendor/github.com/rancher/websocket-proxy/backend/backend.go:56 +0x118

goroutine 15 [IO wait, 71 minutes]:
net.runtime_pollWait(0x7fc797f12078, 0x72, 0x3)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc420306fb8, 0x72, 0xf46b80, 0xf42870)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420306fb8, 0xc420330000, 0x1000)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc420306f50, 0xc420330000, 0x1000, 0x1000, 0x0, 0xf46b80, 0xf42870)
	/usr/local/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc42000e530, 0xc420330000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:181 +0x70
net/http.(*persistConn).Read(0xc4202f8a20, 0xc420330000, 0x1000, 0x1000, 0x4, 0x44fd30, 0xc4201e7320)
	/usr/local/go/src/net/http/transport.go:1316 +0x14b
bufio.(*Reader).fill(0xc4201e71a0)
	/usr/local/go/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).Peek(0xc4201e71a0, 0x1, 0xc420037be5, 0x1, 0x0, 0xc4204ec480, 0x0)
	/usr/local/go/src/bufio/bufio.go:129 +0x67
net/http.(*persistConn).readLoop(0xc4202f8a20)
	/usr/local/go/src/net/http/transport.go:1474 +0x196
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1117 +0xa35

goroutine 16 [select, 71 minutes]:
net/http.(*persistConn).writeLoop(0xc4202f8a20)
	/usr/local/go/src/net/http/transport.go:1704 +0x43a
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1118 +0xa5a

goroutine 39 [select]:
github.com/rancher/agent/vendor/github.com/patrickmn/go-cache.(*janitor).Run(0xc4204111a0, 0xc420448300)
	/go/src/github.com/rancher/agent/vendor/github.com/patrickmn/go-cache/cache.go:1037 +0x171
created by github.com/rancher/agent/vendor/github.com/patrickmn/go-cache.runJanitor
	/go/src/github.com/rancher/agent/vendor/github.com/patrickmn/go-cache/cache.go:1056 +0x8d

goroutine 40 [select]:
github.com/rancher/agent/vendor/github.com/patrickmn/go-cache.(*janitor).Run(0xc4204111b0, 0xc420448340)
	/go/src/github.com/rancher/agent/vendor/github.com/patrickmn/go-cache/cache.go:1037 +0x171
created by github.com/rancher/agent/vendor/github.com/patrickmn/go-cache.runJanitor
	/go/src/github.com/rancher/agent/vendor/github.com/patrickmn/go-cache/cache.go:1056 +0x8d

goroutine 89 [select, 71 minutes]:
net/http.(*persistConn).readLoop(0xc42034b200)
	/usr/local/go/src/net/http/transport.go:1599 +0x9ec
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1117 +0xa35

goroutine 25 [chan receive]:
github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events.(*EventRouter).sendWebsocketPings(0xc420116780)
	/go/src/github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events/websocket_pings.go:27 +0x10c
created by github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events.(*EventRouter).run
	/go/src/github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events/listener.go:136 +0x744

goroutine 41 [chan receive, 71 minutes]:
github.com/rancher/agent/service/hostapi/events.(*EventRouter).routeEvents(0xc4201cef90)
	/go/src/github.com/rancher/agent/service/hostapi/events/event_router.go:87 +0x63
created by github.com/rancher/agent/service/hostapi/events.(*EventRouter).Start
	/go/src/github.com/rancher/agent/service/hostapi/events/event_router.go:49 +0xb8

goroutine 90 [select, 71 minutes]:
net/http.(*persistConn).writeLoop(0xc42034b200)
	/usr/local/go/src/net/http/transport.go:1704 +0x43a
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1118 +0xa5a

goroutine 44 [IO wait, 71 minutes]:
net.runtime_pollWait(0x7fc797f11ef8, 0x72, 0x4)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4200531e8, 0x72, 0xf46b80, 0xf42870)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4200531e8, 0xc4201b1000, 0x1000)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc420053180, 0xc4201b1000, 0x1000, 0x1000, 0x0, 0xf46b80, 0xf42870)
	/usr/local/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc42017c060, 0xc4201b1000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:181 +0x70
net/http.(*persistConn).Read(0xc42019bd40, 0xc4201b1000, 0x1000, 0x1000, 0x4, 0x44fd30, 0xc4201e7620)
	/usr/local/go/src/net/http/transport.go:1316 +0x14b
bufio.(*Reader).fill(0xc4201e7440)
	/usr/local/go/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).Peek(0xc4201e7440, 0x1, 0xc420033be5, 0x1, 0x0, 0xc4201e74a0, 0x0)
	/usr/local/go/src/bufio/bufio.go:129 +0x67
net/http.(*persistConn).readLoop(0xc42019bd40)
	/usr/local/go/src/net/http/transport.go:1474 +0x196
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1117 +0xa35

goroutine 45 [select, 71 minutes]:
net/http.(*persistConn).writeLoop(0xc42019bd40)
	/usr/local/go/src/net/http/transport.go:1704 +0x43a
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1118 +0xa5a

goroutine 24 [select]:
github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events.(*pongHandler).startTimer(0xc4200168a0, 0x1388, 0xea60)
	/go/src/github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events/websocket_pings.go:60 +0x301
created by github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events.newPongHandler
	/go/src/github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events/websocket_pings.go:44 +0x149

goroutine 104 [chan receive]:
github.com/rancher/agent/vendor/github.com/rancher/websocket-proxy/backend.(*pongHandler).startTimer(0xc420148180, 0x1388, 0x2710)
	/go/src/github.com/rancher/agent/vendor/github.com/rancher/websocket-proxy/backend/pong_handler.go:32 +0xbc
created by github.com/rancher/agent/vendor/github.com/rancher/websocket-proxy/backend.newPongHandler
	/go/src/github.com/rancher/agent/vendor/github.com/rancher/websocket-proxy/backend/pong_handler.go:18 +0xfc

goroutine 293 [IO wait, 65 minutes]:
net.runtime_pollWait(0x7fc797f11bf8, 0x72, 0xa)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc420052c38, 0x72, 0xf46b80, 0xf42870)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420052c38, 0xc420088000, 0x1000)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc420052bd0, 0xc420088000, 0x1000, 0x1000, 0x0, 0xf46b80, 0xf42870)
	/usr/local/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc42000e658, 0xc420088000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:181 +0x70
net/http.(*persistConn).Read(0xc42057e240, 0xc420088000, 0x1000, 0x1000, 0x4, 0x44fd30, 0xc4202dca20)
	/usr/local/go/src/net/http/transport.go:1316 +0x14b
bufio.(*Reader).fill(0xc4202dc840)
	/usr/local/go/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).Peek(0xc4202dc840, 0x1, 0xc420298be5, 0x1, 0x0, 0xc4202dd860, 0x0)
	/usr/local/go/src/bufio/bufio.go:129 +0x67
net/http.(*persistConn).readLoop(0xc42057e240)
	/usr/local/go/src/net/http/transport.go:1474 +0x196
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1117 +0xa35

goroutine 294 [select, 65 minutes]:
net/http.(*persistConn).writeLoop(0xc42057e240)
	/usr/local/go/src/net/http/transport.go:1704 +0x43a
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1118 +0xa5a

rax    0xfffffffffffffffc
rbx    0x29b0d5a8
rcx    0x456c73
rdx    0x0
rdi    0xf75bd8
rsi    0x0
rbp    0xc4200266e8
rsp    0xc4200266a0
r8     0x0
r9     0x0
r10    0xc4200266d8
r11    0x202
r12    0x1bad85d68e399f
r13    0x1bad85d68e399f
r14    0x0
r15    0xf3
rip    0x456c73
rflags 0x202
cs     0x33
fs     0x0
gs     0x0
```

**Comment by deniseschannon** [comment]
@aemneina we need more details on how to reliably reproduce.

**Comment by aemneina** [comment]
Let me see if I can recall the events:
setup:
3 rancher servers in HA behind an ELB
~20 agents in this environment

steps:
- take down the servers, upgrade one server host using a newer image (1.6.10 -> 1.6.14)
- wait for all the agents to reconnect
- wait for another 10-15 mins
- upgrade the other two rancher servers
- agents all went disconnected
- kill -3 on agents yielded the stacktrace above and the agent happily restarted and reconnected to the servers.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
