### ISSUE TITLE
Network Policy manager keeps restarting because of panic when network policy on the environment was modified. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11210]
Rancher server - Build from v1.6 branch with rancher/network-policy-manager:v0.2.6

Setup:
region1 with 3 environments test1,test2 and test3
region2 with 3 environments test1,test2 and test3

Lb in region1/test1 environment has targets from region2/test2.

Updated network policy in region2/test2 to following from the default network policy configuration which was allow all:
<img width="1296" alt="screen shot 2018-01-29 at 12 29 23 pm" src="https://user-images.githubusercontent.com/4266958/35532976-ec3e43e4-04f0-11e8-92cb-300d8728bd7b.png">

After this Network Policy manager in region2/test2  keeps restarting because of the following panic seen in logs:

```
1/29/2018 12:23:54 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:1224 +0x31f
1/29/2018 12:23:54 PMgithub.com/rancher/network-policy-manager/policy.(*watcher).onChangeNoError(0xc4200b88c0, 0xc420053d40, 0x24)
1/29/2018 12:23:54 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:185 +0xd8
1/29/2018 12:23:54 PMgithub.com/rancher/network-policy-manager/policy.(*watcher).(github.com/rancher/network-policy-manager/policy.onChangeNoError)-fm(0xc420053d40, 0x24)
1/29/2018 12:23:54 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:160 +0x3e
1/29/2018 12:23:54 PMgithub.com/rancher/network-policy-manager/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).OnChange.func1(0xc420053d40, 0x24)
1/29/2018 12:23:54 PM	/go/src/github.com/rancher/network-policy-manager/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:36 +0x5f
1/29/2018 12:23:54 PMgithub.com/rancher/network-policy-manager/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).onChangeFromVersionWithError(0xc4200532f0, 0x8a0735, 0x4, 0x5, 0xc4200d7fa0, 0x0, 0xc420012d80)
1/29/2018 12:23:54 PM	/go/src/github.com/rancher/network-policy-manager/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:25 +0x1bb
1/29/2018 12:23:54 PMgithub.com/rancher/network-policy-manager/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).OnChange(0xc4200532f0, 0x5, 0xc420011710)
1/29/2018 12:23:54 PM	/go/src/github.com/rancher/network-policy-manager/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:40 +0x9e
1/29/2018 12:23:54 PMcreated by github.com/rancher/network-policy-manager/policy.Watch
1/29/2018 12:23:54 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:160 +0x2a3
1/29/2018 12:24:05 PMtime="2018-01-29T20:24:05Z" level=info msg="Waiting for metadata"
1/29/2018 12:24:05 PMtime="2018-01-29T20:24:05Z" level=info msg="Listening on /tmp/log.sock"
1/29/2018 12:24:05 PMpanic: runtime error: index out of range
1/29/2018 12:24:05 PM
1/29/2018 12:24:05 PMgoroutine 15 [running]:
1/29/2018 12:24:05 PMgithub.com/rancher/network-policy-manager/policy.(*watcher).covertToLocalLink(0xc4200b88c0, 0xc4201c81e0, 0x1c, 0x2, 0x2, 0x2)
1/29/2018 12:24:05 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:955 +0x252
1/29/2018 12:24:05 PMgithub.com/rancher/network-policy-manager/policy.(*watcher).buildLinkedMappings(0xc4200b88c0, 0x0)
1/29/2018 12:24:05 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:918 +0x572
1/29/2018 12:24:05 PMgithub.com/rancher/network-policy-manager/policy.(*watcher).withinLinkedHandler(0xc4200b88c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4202ea47a, 0x6, 0x0, 0xc4202ea475, ...)
1/29/2018 12:24:05 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:696 +0xac
1/29/2018 12:24:05 PMgithub.com/rancher/network-policy-manager/policy.(*watcher).withinPolicyHandler(0xc4200b88c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4202ea47a, 0x6, 0x0, 0xc4202ea475, ...)
1/29/2018 12:24:05 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:974 +0x205
1/29/2018 12:24:05 PMgithub.com/rancher/network-policy-manager/policy.(*watcher).translatePolicy(0xc4200b88c0, 0xc420340090, 0x0, 0x0)
1/29/2018 12:24:05 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:1038 +0x8f3
1/29/2018 12:24:05 PMgithub.com/rancher/network-policy-manager/policy.(*watcher).onChange(0xc4200b88c0, 0xc420053d40, 0x24, 0x1, 0x1)
1/29/2018 12:24:05 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:1224 +0x31f
1/29/2018 12:24:05 PMgithub.com/rancher/network-policy-manager/policy.(*watcher).onChangeNoError(0xc4200b88c0, 0xc420053d40, 0x24)
1/29/2018 12:24:05 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:185 +0xd8
1/29/2018 12:24:05 PMgithub.com/rancher/network-policy-manager/policy.(*watcher).(github.com/rancher/network-policy-manager/policy.onChangeNoError)-fm(0xc420053d40, 0x24)
1/29/2018 12:24:05 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:160 +0x3e
1/29/2018 12:24:05 PMgithub.com/rancher/network-policy-manager/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).OnChange.func1(0xc420053d40, 0x24)
1/29/2018 12:24:05 PM	/go/src/github.com/rancher/network-policy-manager/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:36 +0x5f
1/29/2018 12:24:05 PMgithub.com/rancher/network-policy-manager/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).onChangeFromVersionWithError(0xc4200532f0, 0x8a0735, 0x4, 0x5, 0xc4200d7fa0, 0x0, 0xc420012d80)
1/29/2018 12:24:05 PM	/go/src/github.com/rancher/network-policy-manager/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:25 +0x1bb
1/29/2018 12:24:05 PMgithub.com/rancher/network-policy-manager/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).OnChange(0xc4200532f0, 0x5, 0xc420011710)
1/29/2018 12:24:05 PM	/go/src/github.com/rancher/network-policy-manager/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:40 +0x9e
1/29/2018 12:24:05 PMcreated by github.com/rancher/network-policy-manager/policy.Watch
1/29/2018 12:24:05 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:160 +0x2a3
1/29/2018 12:24:23 PMtime="2018-01-29T20:24:23Z" level=info msg="Waiting for metadata"
1/29/2018 12:24:23 PMtime="2018-01-29T20:24:23Z" level=info msg="Listening on /tmp/log.sock"
1/29/2018 12:24:23 PMpanic: runtime error: index out of range
1/29/2018 12:24:23 PM
1/29/2018 12:24:23 PMgoroutine 15 [running]:
1/29/2018 12:24:23 PMgithub.com/rancher/network-policy-manager/policy.(*watcher).covertToLocalLink(0xc4200b88c0, 0xc4201c81c0, 0x1c, 0x2, 0x2, 0x2)
1/29/2018 12:24:23 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:955 +0x252
1/29/2018 12:24:23 PMgithub.com/rancher/network-policy-manager/policy.(*watcher).buildLinkedMappings(0xc4200b88c0, 0x0)
1/29/2018 12:24:23 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:918 +0x572
1/29/2018 12:24:23 PMgithub.com/rancher/network-policy-manager/policy.(*watcher).withinLinkedHandler(0xc4200b88c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4202ea46a, 0x6, 0x0, 0xc4202ea465, ...)
1/29/2018 12:24:23 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:696 +0xac
1/29/2018 12:24:23 PMgithub.com/rancher/network-policy-manager/policy.(*watcher).withinPolicyHandler(0xc4200b88c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4202ea46a, 0x6, 0x0, 0xc4202ea465, ...)
1/29/2018 12:24:23 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:974 +0x205
1/29/2018 12:24:23 PMgithub.com/rancher/network-policy-manager/policy.(*watcher).translatePolicy(0xc4200b88c0, 0xc420340090, 0x0, 0x0)
1/29/2018 12:24:23 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:1038 +0x8f3
1/29/2018 12:24:23 PMgithub.com/rancher/network-policy-manager/policy.(*watcher).onChange(0xc4200b88c0, 0xc420053d40, 0x24, 0x1, 0x1)
1/29/2018 12:24:23 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:1224 +0x31f
1/29/2018 12:24:23 PMgithub.com/rancher/network-policy-manager/policy.(*watcher).onChangeNoError(0xc4200b88c0, 0xc420053d40, 0x24)
1/29/2018 12:24:23 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:185 +0xd8
1/29/2018 12:24:23 PMgithub.com/rancher/network-policy-manager/policy.(*watcher).(github.com/rancher/network-policy-manager/policy.onChangeNoError)-fm(0xc420053d40, 0x24)
1/29/2018 12:24:23 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:160 +0x3e
1/29/2018 12:24:23 PMgithub.com/rancher/network-policy-manager/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).OnChange.func1(0xc420053d40, 0x24)
1/29/2018 12:24:23 PM	/go/src/github.com/rancher/network-policy-manager/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:36 +0x5f
1/29/2018 12:24:23 PMgithub.com/rancher/network-policy-manager/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).onChangeFromVersionWithError(0xc4200532f0, 0x8a0735, 0x4, 0x5, 0xc4200d7fa0, 0x0, 0xc420012d80)
1/29/2018 12:24:23 PM	/go/src/github.com/rancher/network-policy-manager/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:25 +0x1bb
1/29/2018 12:24:23 PMgithub.com/rancher/network-policy-manager/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).OnChange(0xc4200532f0, 0x5, 0xc420011700)
1/29/2018 12:24:23 PM	/go/src/github.com/rancher/network-policy-manager/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:40 +0x9e
1/29/2018 12:24:23 PMcreated by github.com/rancher/network-policy-manager/policy.Watch
1/29/2018 12:24:23 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:160 +0x2a3
1/29/2018 12:24:54 PMtime="2018-01-29T20:24:54Z" level=info msg="Waiting for metadata"
1/29/2018 12:24:54 PMtime="2018-01-29T20:24:54Z" level=info msg="Listening on /tmp/log.sock"
1/29/2018 12:24:54 PMpanic: runtime error: index out of range
1/29/2018 12:24:54 PM
1/29/2018 12:24:54 PMgoroutine 15 [running]:
1/29/2018 12:24:54 PMgithub.com/rancher/network-policy-manager/policy.(*watcher).covertToLocalLink(0xc4200b68c0, 0xc4201c81e0, 0x1c, 0x2, 0x2, 0x2)
1/29/2018 12:24:54 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:955 +0x252
1/29/2018 12:24:54 PMgithub.com/rancher/network-policy-manager/policy.(*watcher).buildLinkedMappings(0xc4200b68c0, 0x0)
1/29/2018 12:24:54 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:918 +0x572
1/29/2018 12:24:54 PMgithub.com/rancher/network-policy-manager/policy.(*watcher).withinLinkedHandler(0xc4200b68c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4202e846a, 0x6, 0x0, 0xc4202e8465, ...)
1/29/2018 12:24:54 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:696 +0xac
1/29/2018 12:24:54 PMgithub.com/rancher/network-policy-manager/policy.(*watcher).withinPolicyHandler(0xc4200b68c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4202e846a, 0x6, 0x0, 0xc4202e8465, ...)
1/29/2018 12:24:54 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:974 +0x205
1/29/2018 12:24:54 PMgithub.com/rancher/network-policy-manager/policy.(*watcher).translatePolicy(0xc4200b68c0, 0xc42033e090, 0x0, 0x0)
1/29/2018 12:24:54 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:1038 +0x8f3
1/29/2018 12:24:54 PMgithub.com/rancher/network-policy-manager/policy.(*watcher).onChange(0xc4200b68c0, 0xc420053d40, 0x24, 0x1, 0x1)
1/29/2018 12:24:54 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:1224 +0x31f
1/29/2018 12:24:54 PMgithub.com/rancher/network-policy-manager/policy.(*watcher).onChangeNoError(0xc4200b68c0, 0xc420053d40, 0x24)
1/29/2018 12:24:54 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:185 +0xd8
1/29/2018 12:24:54 PMgithub.com/rancher/network-policy-manager/policy.(*watcher).(github.com/rancher/network-policy-manager/policy.onChangeNoError)-fm(0xc420053d40, 0x24)
1/29/2018 12:24:54 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:160 +0x3e
1/29/2018 12:24:54 PMgithub.com/rancher/network-policy-manager/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).OnChange.func1(0xc420053d40, 0x24)
1/29/2018 12:24:54 PM	/go/src/github.com/rancher/network-policy-manager/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:36 +0x5f
1/29/2018 12:24:54 PMgithub.com/rancher/network-policy-manager/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).onChangeFromVersionWithError(0xc4200532f0, 0x8a0735, 0x4, 0x5, 0xc4200d7fa0, 0x0, 0xc420012d80)
1/29/2018 12:24:54 PM	/go/src/github.com/rancher/network-policy-manager/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:25 +0x1bb
1/29/2018 12:24:54 PMgithub.com/rancher/network-policy-manager/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).OnChange(0xc4200532f0, 0x5, 0xc420011710)
1/29/2018 12:24:54 PM	/go/src/github.com/rancher/network-policy-manager/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:40 +0x9e
1/29/2018 12:24:54 PMcreated by github.com/rancher/network-policy-manager/policy.Watch
1/29/2018 12:24:54 PM	/go/src/github.com/rancher/network-policy-manager/policy/watcher.go:160 +0x2a3
```

**Comment by sangeethah** [comment]
Rancher server -  with rancher/server version v1.6.15-rc3 and rancher/network-policy-manager:v0.2.7.

This issue is not reproducible anymore.

Able to do have LB work as expected when its targets are cross region and both the environments ( when Lb is present and targets are present) have "Allow" for only "Between Linked Services" and Deny for all other policies.
