### ISSUE TITLE
Regions - When existing environment ( which is linked externally) gets deleted , it continues to be linked.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11213]
Rancher Version - Build from 1.6

Steps to reproduce the problem:

Have 2 rancher-servers linked by region entries - region1 and region2.
Have environment test1 in region1.
Have environment test1 in region2.
Create Lb in region2 with port rules have region="region1" and environment="test2"
Delete test2 in region1.

region2 continues to be linked with "test2"
```
root@6c1d0ea105a0:/# curl http://rancher-metadata/latest/environments
1=test2
root@6c1d0ea105a0:/#
```
Following error is seen every 2 mts in the logs:
```
 [3]
Caused by: java.lang.RuntimeException: Failed to find target environment by name [test2] in region [region2]
2018-01-29 21:43:39,658 ERROR [b4f740a5-db0d-434f-abdc-1777f8f8961a:1280] [accountLink:3] [accountlink.create] [] [ecutorService-1] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception java.lang.RuntimeException: Failed to create external account link for accountLink [3]
Caused by: java.lang.RuntimeException: Failed to find target environment by name [test2] in region [region2]
2018-01-29 21:43:39,695 ERROR [:] [] [] [] [ecutorService-1] [.e.s.i.ProcessInstanceDispatcherImpl] Unknown exception running process [accountlink.create:1280] on [3] java.lang.RuntimeException: Failed to create external account link for accountLink [3]
Caused by: java.lang.RuntimeException: Failed to find target environment by name [test2] in region [region2]
2018-01-29 21:45:39,751 ERROR [6d8c480f-3926-47b9-9db7-2e25ec5a0857:1280] [accountLink:3] [accountlink.create] [] [ecutorService-2] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception java.lang.RuntimeException: Failed to create external account link for accountLink [3]
Caused by: java.lang.RuntimeException: Failed to find target environment by name [test2] in region [region2]
2018-01-29 21:45:39,796 ERROR [:] [] [] [] [ecutorService-2] [.e.s.i.ProcessInstanceDispatcherImpl] Unknown exception running process [accountlink.create:1280] on [3] java.lang.RuntimeException: Failed to create external account link for accountLink [3]
Caused by: java.lang.RuntimeException: Failed to find target environment by name [test2] in region [region2]
2018-01-29 21:47:39,714 ERROR [2de2dc93-828e-42f6-810f-827e317addb0:1280] [accountLink:3] [accountlink.create] [] [ecutorService-3] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception java.lang.RuntimeException: Failed to create external account link for accountLink [3]
Caused by: java.lang.RuntimeException: Failed to find target environment by name [test2] in region [region2]
2018-01-29 21:47:39,753 ERROR [:] [] [] [] [ecutorService-3] [.e.s.i.ProcessInstanceDispatcherImpl] Unknown exception running process [accountlink.create:1280] on [3] java.lang.RuntimeException: Failed to create external account link for accountLink [3]
Caused by: java.lang.RuntimeException: Failed to find target environment by name [test2] in region [region2]
2018-01-29 21:49:39,806 ERROR [a8956593-c187-4550-8c07-61f5987b0b8e:1280] [accountLink:3] [accountlink.create] [] [ecutorService-1] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception java.lang.RuntimeException: Failed to create external account link for accountLink [3]
Caused by: java.lang.RuntimeException: Failed to find target environment by name [test2] in region [region2]
2018-01-29 21:49:39,930 ERROR [:] [] [] [] [ecutorService-1] [.e.s.i.ProcessInstanceDispatcherImpl] Unknown exception running process [accountlink.create:1280] on [3] java.lang.RuntimeException: Failed to create external account link for accountLink [3]
Caused by: java.lang.RuntimeException: Failed to find target environment by name [test2] in region [region2]
2018-01-29 21:51:39,918 ERROR [1d900efa-7580-4c8d-a40f-874b19c2d61c:1280] [accountLink:3] [accountlink.create] [] [ecutorService-2] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception java.lang.RuntimeException: Failed to create external account link for accountLink [3]
Caused by: java.lang.RuntimeException: Failed to find target environment by name [test2] in region [region2]
2018-01-29 21:51:39,995 ERROR [:] [] [] [] [ecutorService-2] [.e.s.i.ProcessInstanceDispatcherImpl] Unknown exception running process [accountlink.create:1280] on [3] java.lang.RuntimeException: Failed to create external account link for accountLink [3]
Caused by: java.lang.RuntimeException: Failed to find target environment by name [test2] in region [region2]
```

```
mysql> select * from account_link;
+----+------+------------+-------------+--------------------------------------+-------------+-------------+---------------------+---------------------+---------------------+------------------------------------------------------------+-------------------+----------------+------------------+---------------+----------+
| id | name | account_id | kind        | uuid                                 | description | state       | created             | removed             | remove_time         | data                                                       | linked_account_id | linked_account | linked_region_id | linked_region | external |
+----+------+------------+-------------+--------------------------------------+-------------+-------------+---------------------+---------------------+---------------------+------------------------------------------------------------+-------------------+----------------+------------------+---------------+----------+
|  1 | NULL |         14 | accountLink | d946a14e-c0d0-49eb-ba57-afbcd63b91bc | NULL        | inactive    | 2018-01-29 20:11:36 | NULL                | NULL                | {"fields":{"uuid":"673360af-a856-4098-91f7-83012c39b6b5"}} |              NULL | test1          |                2 | region1       |          |
|  2 | NULL |         14 | accountLink | 95d17e07-6a96-481e-85fb-6447ecb40fec | NULL        | purged      | 2018-01-29 20:11:36 | 2018-01-29 21:29:52 | 2018-01-29 21:30:31 | {"fields":{"uuid":"2e31212a-6a5f-42c7-bb6a-9f6287ecff4d"}} |              NULL | test2          |                2 | region1       |          |
|  3 | NULL |         14 | accountLink | 7965e12a-cf8d-4133-8f22-3764e2f1e149 | NULL        | registering | 2018-01-29 21:29:52 | NULL                | NULL                | {}                                                         |              NULL | test2          |                2 | region1       |          |
+----+------+------------+-------------+--------------------------------------+-------------+-------------+---------------------+---------------------+---------------------+------------------------------------------------------------+-------------------+----------------+------------------+---------------+----------+
3 rows in set (0.00 sec)
```

**Comment by sangeethah** [comment]
Rancher Server version - v1.6.15-rc3

This issue is still reproducible.

Additionally I now see NPE in this case:

```
2018-02-01 21:28:47,102 WARN  [:] [] [] [] [ecutorService-8] [i.c.p.s.s.impl.RegionServiceImpl    ] Failed to monitor account link for %s - %s java.lang.NullPointerException: null
	at io.cattle.platform.servicediscovery.process.RegionMonitor.run(RegionMonitor.java:106)
	at io.cattle.platform.task.impl.TaskManagerImpl$1.doRun(TaskManagerImpl.java:100)
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2018-02-01 21:29:47,144 WARN  [:] [] [] [] [ecutorService-2] [i.c.p.s.s.impl.RegionServiceImpl    ] Failed to monitor account link for %s - %s java.lang.NullPointerException: null
	at io.cattle.platform.servicediscovery.process.RegionMonitor.run(RegionMonitor.java:106)
	at io.cattle.platform.task.impl.TaskManagerImpl$1.doRun(TaskManagerImpl.java:100)
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

DB entries:

```
|  3 | NULL |         15 | accountLink | 1472c3e4-e5c7-40ba-ba9b-d2f37f73a2a8 | NULL        | inactive | 2018-02-01 21:12:09 | NULL    | NULL        | {"fields":{"linkedAccountUuid":"33aa762e-039f-4593-bec7-d20e94a6b94a"}} |              NULL | test3r2        |                2 | region2       |          |
+----+------+------------+-------------+--------------------------------------+-------------+----------+---------------------+---------+-------------+-------------------------------------------------------------------------+-------------------+----------------+------------------+---------------+----------+
```

**Comment by sangeethah** [comment]
This issue is not seen anymore when testing with rancher-server builds from 1.6 branch.
