### ISSUE TITLE
cannot upgrade/remove rancher-efs . 

### ISSUE THREAD

**Issue by kgk** [rancher/rancher#11373]
**Rancher versions:**
rancher/server: 1.6.14
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

ubuntu

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher 

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

cattle 

**Steps to Reproduce:**
EFS  was not responding in containers.. tried to remove/restart rancher-nfs
Now rancher-nfs is restarted continously and cannot be removed
and it appears entire environment is hosed.

**Results:**

```
`2018-02-09` 18:15:51,756 ERROR [c1ef1c60-3511-4a1f-8a58-a92fe0c3d8ca:10582068] [volume:197241->mount:76652] [volume.remove->(VolumeRemove)->mount.remove] [] [ecutorService-3] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [storage.volume.remove.reply;agent=12904]: Error response from daemon: get lets-encrypt: Post http://%2Frun%2Fdocker%2Fplugins%2Francher-nfs.sock/VolumeDriver.Get: dial unix /run/docker/plugins/rancher-nfs.sock: connect: connection refused 
2018-02-09 18:15:51,759 ERROR [c1ef1c60-3511-4a1f-8a58-a92fe0c3d8ca:10582068] [volume:197241] [volume.remove] [] [ecutorService-3] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [storage.volume.remove.reply;agent=12904]: Error response from daemon: get lets-encrypt: Post http://%2Frun%2Fdocker%2Fplugins%2Francher-nfs.sock/VolumeDriver.Get: dial unix /run/docker/plugins/rancher-nfs.sock: connect: connection refused 
2018-02-09 18:15:51,770 ERROR [:] [] [] [] [ecutorService-3] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [storage.volume.remove.reply;agent=12904]: Error response from daemon: get lets-encrypt: Post http://%2Frun%2Fdocker%2Fplugins%2Francher-nfs.sock/VolumeDriver.Get: dial unix /run/docker/plugins/rancher-nfs.sock: connect: connection refused 
2018-02-09 18:16:06,815 ERROR [58a8be21-9c64-49c8-9582-1424ffd53633:10582142] [volume:197241->mount:76652] [volume.remove->(VolumeRemove)->mount.remove] [] [ecutorService-2] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [storage.volume.remove.reply;agent=12904]: Error response from daemon: get lets-encrypt: Post http://%2Frun%2Fdocker%2Fplugins%2Francher-nfs.sock/VolumeDriver.Get: dial unix /run/docker/plugins/rancher-nfs.sock: connect: connection refused 
2018-02-09 18:16:06,816 ERROR [58a8be21-9c64-49c8-9582-1424ffd53633:10582142] [volume:197241] [volume.remove] [] [ecutorService-2] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [storage.volume.remove.reply;agent=12904]: Error response from daemon: get lets-encrypt: Post http://%2Frun%2Fdocker%2Fplugins%2Francher-nfs.sock/VolumeDriver.Get: dial unix /run/docker/plugins/rancher-nfs.sock: connect: connection refused 
2018-02-09 18:16:06,827 ERROR [:] [] [] [] [ecutorService-2] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [storage.volume.remove.reply;agent=12904]: Error response from daemon: get lets-encrypt: Post http://%2Frun%2Fdocker%2Fplugins%2Francher-nfs.sock/VolumeDriver.Get: dial unix /run/docker/plugins/rancher-nfs.sock: connect: connection refused 
2018-02-09 18:16:15,269 ERROR [744983f3-8e68-4b89-9ccf-5ee6b575e8ee:10588804] [agent:13730] [agent.activate->(MetadataProcessHandler)] [] [cutorService-24] [i.c.p.p.m.MetadataProcessHandler    ] Failed to find account id for agent:13730 
2018-02-09 18:16:19,153 ERROR [422e7adc-c3f4-4b27-b4fe-27135f19b10d:10588817] [agent:13730] [agent.deactivate->(MetadataProcessHandler)] [] [cutorService-23] [i.c.p.p.m.MetadataProcessHandler    ] Failed to find account id for agent:13730 
2018-02-09 18:16:19,208 ERROR [26603313-eb2f-458d-b60d-7aa1f5a33419:10588825] [agent:13730] [agent.remove->(MetadataProcessHandler)] [] [cutorService-23] [i.c.p.p.m.MetadataProcessHandler    ] Failed to find account id for agent:13730 
2018-02-09 18:16:21,865 ERROR [4cd945af-c4f0-448d-b9f1-952ef72bc94a:10582999] [volume:197241->mount:76652] [volume.remove->(VolumeRemove)->mount.remove] [] [ecutorService-1] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [storage.volume.remove.reply;agent=12904]: Error response from daemon: get lets-encrypt: Post http://%2Frun%2Fdocker%2Fplugins%2Francher-nfs.sock/VolumeDriver.Get: dial unix /run/docker/plugins/rancher-nfs.sock: connect: connection refused 
2018-02-09 18:16:21,866 ERROR [4cd945af-c4f0-448d-b9f1-952ef72bc94a:10582999] [volume:197241] [volume.remove] [] [ecutorService-1] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [storage.volume.remove.reply;agent=12904]: Error response from daemon: get lets-encrypt: Post http://%2Frun%2Fdocker%2Fplugins%2Francher-nfs.sock/VolumeDriver.Get: dial unix /run/docker/plugins/rancher-nfs.sock: connect: connection refused 
2018-02-09 18:16:21,875 ERROR [:] [] [] [] [ecutorService-1] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [storage.volume.remove.reply;agent=12904]: Error response from daemon: get lets-encrypt: Post http://%2Frun%2Fdocker%2Fplugins%2Francher-nfs.sock/VolumeDriver.Get: dial unix /run/docker/plugins/rancher-nfs.sock: connect: connection refused 
2018-02-09 18:16:36,922 ERROR [b25a935c-8da2-4dcd-9b77-5f189a555c02:10583074] [volume:197241->mount:76652] [volume.remove->(VolumeRemove)->mount.remove] [] [ecutorService-3] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [storage.volume.remove.reply;agent=12904]: Error response from daemon: get lets-encrypt: Post http://%2Frun%2Fdocker%2Fplugins%2Francher-nfs.sock/VolumeDriver.Get: dial unix /run/docker/plugins/rancher-nfs.sock: connect: connection refused 
2018-02-09 18:16:36,924 ERROR [b25a935c-8da2-4dcd-9b77-5f189a555c02:10583074] [volume:197241] [volume.remove] [] [ecutorService-3] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [storage.volume.remove.reply;agent=12904]: Error response from daemon: get lets-encrypt: Post http://%2Frun%2Fdocker%2Fplugins%2Francher-nfs.sock/VolumeDriver.Get: dial unix /run/docker/plugins/rancher-nfs.sock: connect: connection refused 
2018-02-09 18:16:36,933 ERROR [:] [] [] [] [ecutorService-3] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [storage.volume.remove.reply;agent=12904]: Error response from daemon: get lets-encrypt: Post http://%2Frun%2Fdocker%2Fplugins%2Francher-nfs.sock/VolumeDriver.Get: dial unix /run/docker/plugins/rancher-nfs.sock: connect: connection refused 
2018-02-09 18:16:51,392 ERROR [:] [] [] [] [ecutorService-1] [i.c.p.task.impl.TaskManagerImpl     ] Task [evacuate.hosts] failed io.cattle.platform.engine.process.impl.ProcessCancelException: State [purged] is not valid for process [agent.deactivate:10588832] on resource [143]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:316)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:245)
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7)
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:242)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:184)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:157)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:116)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:113)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:113)
	at io.cattle.platform.engine.manager.impl.DefaultProcessManager.scheduleProcessInstance(DefaultProcessManager.java:69)
	at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.scheduleProcessInstance(DefaultObjectProcessManager.java:50)
	at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.scheduleStandardProcess(DefaultObjectProcessManager.java:43)
	at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.scheduleStandardProcess(DefaultObjectProcessManager.java:37)
	at io.cattle.platform.object.process.impl.DefaultObjectProcessManager$2.run(DefaultObjectProcessManager.java:129)
	at io.cattle.platform.deferred.util.DeferredUtils$3.call(DeferredUtils.java:43)
	at io.cattle.platform.deferred.util.DeferredUtils.nest(DeferredUtils.java:53)
	at io.cattle.platform.deferred.util.DeferredUtils.nest(DeferredUtils.java:40)
	at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.scheduleStandardProcessAsync(DefaultObjectProcessManager.java:126)
	at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.scheduleStandardChainedProcessAsync(DefaultObjectProcessManager.java:147)
	at io.cattle.platform.process.host.HostRemoveMonitorImpl.run(HostRemoveMonitorImpl.java:40)
	at io.cattle.platform.task.impl.TaskManagerImpl$1.doRun(TaskManagerImpl.java:100)
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2018-02-09 18:17:37,782 ERROR [a8480b1c-a315-4a39-be8e-6c185d942772:10588852] [agent:13728] [agent.deactivate->(MetadataProcessHandler)] [] [cutorService-25] [i.c.p.p.m.MetadataProcessHandler    ] Failed to find account id for agent:13728 
2018-02-09 18:17:37,816 ERROR [d039c311-8b4d-401a-b74e-388c87faae8d:10588854] [agent:13728] [agent.remove->(MetadataProcessHandler)] [] [cutorService-25] [i.c.p.p.m.MetadataProcessHandler    ] Failed to find account id for agent:13728 
2018-02-09 18:17:38,666 ERROR [d5348d25-4552-4178-8693-0ecaae39cc1e:10588859] [agent:13731] [agent.activate->(MetadataProcessHandler)] [] [cutorService-17] [i.c.p.p.m.MetadataProcessHandler    ] Failed to find account id for agent:13731 
2018-02-09 18:17:51,413 ERROR [:] [] [] [] [ecutorService-6] [i.c.p.task.impl.TaskManagerImpl     ] Task [evacuate.hosts] failed io.cattle.platform.engine.process.impl.ProcessCancelException: State [purged] is not valid for process [agent.deactivate:10588870] on resource [143]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:316)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:245)
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7)
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:242)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:184)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:157)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:116)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:113)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:113)
	at io.cattle.platform.engine.manager.impl.DefaultProcessManager.scheduleProcessInstance(DefaultProcessManager.java:69)
	at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.scheduleProcessInstance(DefaultObjectProcessManager.java:50)
	at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.scheduleStandardProcess(DefaultObjectProcessManager.java:43)
	at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.scheduleStandardProcess(DefaultObjectProcessManager.java:37)
	at io.cattle.platform.object.process.impl.DefaultObjectProcessManager$2.run(DefaultObjectProcessManager.java:129)
	at io.cattle.platform.deferred.util.DeferredUtils$3.call(DeferredUtils.java:43)
	at io.cattle.platform.deferred.util.DeferredUtils.nest(DeferredUtils.java:53)
	at io.cattle.platform.deferred.util.DeferredUtils.nest(DeferredUtils.java:40)
	at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.scheduleStandardProcessAsync(DefaultObjectProcessManager.java:126)
	at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.scheduleStandardChainedProcessAsync(DefaultObjectProcessManager.java:147)
	at io.cattle.platform.process.host.HostRemoveMonitorImpl.run(HostRemoveMonitorImpl.java:40)
	at io.cattle.platform.task.impl.TaskManagerImpl$1.doRun(TaskManagerImpl.java:100)
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2018-02-09 18:17:51,720 ERROR [de6fc84b-de4d-4e17-bb84-fd8c30e63ee2:10580785] [volume:197241->mount:76652] [volume.remove->(VolumeRemove)->mount.remove] [] [ecutorService-2] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [storage.volume.remove.reply;agent=12904]: Error response from daemon: get lets-encrypt: Post http://%2Frun%2Fdocker%2Fplugins%2Francher-nfs.sock/VolumeDriver.Get: dial unix /run/docker/plugins/rancher-nfs.sock: connect: connection refused 
2018-02-09 18:17:51,721 ERROR [de6fc84b-de4d-4e17-bb84-fd8c30e63ee2:10580785] [volume:197241] [volume.remove] [] [ecutorService-2] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [storage.volume.remove.reply;agent=12904]: Error response from daemon: get lets-encrypt: Post http://%2Frun%2Fdocker%2Fplugins%2Francher-nfs.sock/VolumeDriver.Get: dial unix /run/docker/plugins/rancher-nfs.sock: connect: connection refused 
2018-02-09 18:17:51,727 ERROR [:] [] [] [] [ecutorService-2] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [storage.volume.remove.reply;agent=12904]: Error response from daemon: get lets-encrypt: Post http://%2Frun%2Fdocker%2Fplugins%2Francher-nfs.sock/VolumeDriver.Get: dial unix /run/docker/plugins/rancher-nfs.sock: connect: connection refused 
2018-02-09 18:18:06,774 ERROR [c0dc7446-7af6-4a0d-b509-5f7652978e8c:10582068] [volume:197241->mount:76652] [volume.remove->(VolumeRemove)->mount.remove] [] [ecutorService-3] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [storage.volume.remove.reply;agent=12904]: Error response from daemon: get lets-encrypt: Post http://%2Frun%2Fdocker%2Fplugins%2Francher-nfs.sock/VolumeDriver.Get: dial unix /run/docker/plugins/rancher-nfs.sock: connect: connection refused 
2018-02-09 18:18:06,777 ERROR [c0dc7446-7af6-4a0d-b509-5f7652978e8c:10582068] [volume:197241] [volume.remove] [] [ecutorService-3] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [storage.volume.remove.reply;agent=12904]: Error response from daemon: get lets-encrypt: Post http://%2Frun%2Fdocker%2Fplugins%2Francher-nfs.sock/VolumeDriver.Get: dial unix /run/docker/plugins/rancher-nfs.sock: connect: connection refused 
2018-02-09 18:18:06,783 ERROR [:] [] [] [] [ecutorService-3] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [storage.volume.remove.reply;agent=12904]: Error response from daemon: get lets-encrypt: Post http://%2Frun%2Fdocker%2Fplugins%2Francher-nfs.sock/VolumeDriver.Get: dial unix /run/docker/plugins/rancher-nfs.sock: connect: connection refused 
`
```

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
