### ISSUE TITLE
NPE in region monitor

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11407]
Rancher-server version - v1.6.15-rc4

Steps to reproduce the problem:
Region1 - with 3 environments
Region2 - with 3 environments

Deactivate Region1's api keys.

Try to create LB from region1 with targets in region2.

See the following NPE in region2 server logs:

```
2018-02-13 20:55:54,269 ERROR [:] [] [] [] [ecutorService-2] [i.c.p.task.impl.TaskManagerImpl     ] Task [region.monitor] failed java.lang.NullPointerException: null
	at io.cattle.platform.process.common.handler.AbstractObjectProcessLogic.deactivateThenRemove(AbstractObjectProcessLogic.java:46)
	at io.cattle.platform.servicediscovery.process.RegionMonitor$AgentRemove.deactivateThenRemove(RegionMonitor.java:198)
	at io.cattle.platform.servicediscovery.process.RegionMonitor.cleanAgents(RegionMonitor.java:181)
	at io.cattle.platform.servicediscovery.process.RegionMonitor.run(RegionMonitor.java:87)
	at io.cattle.platform.task.impl.TaskManagerImpl$1.doRun(TaskManagerImpl.java:100)
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by kinarashah** [comment]
https://github.com/rancher/rancher/issues/10648

**Comment by sangeethah** [comment]
Tested with latest build from 1.6 branch.
There is no "java.lang.NullPointerException" when monitor job for regions is run for the scenario mentioned in the issue.
