### ISSUE TITLE
ipsec-connectivity-check shows panic when deleting disconnected hosts

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#11437]
**Rancher versions:**
rancher/server: v1.6.14
rancher/agent: v1.2.9

**Infrastructure Stack versions:**
healthcheck: v0.3.3-1
ipsec: 0.2.2
network-services: v0.2.8
scheduler: v0.8.3

**Docker version: (`docker version`,`docker info` preferred)**
`17.03.2-ce`

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.3, `4.4.0-112-generic`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
DO

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Add hosts to env
1. Delete rancher-agent container and wait for Host to into Disconnected state
1. Deactive disconnected host and delete

**Results:**
One of the ipsec-connectivity-check containers will panic, probably some ordering issue when watching peers.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x692abc]

goroutine 34 [running]:
github.com/rancher/connectivity-check/checker.(*Peer).consider(0xc42006acc0, 0x851d58)
        /go/src/github.com/rancher/connectivity-check/checker/peer.go:144 +0xdc
github.com/rancher/connectivity-check/checker.(*Peer).Consider(0xc42006acc0, 0xc420465000)
        /go/src/github.com/rancher/connectivity-check/checker/peer.go:164 +0x6c
github.com/rancher/connectivity-check/checker.(*PeersWatcher).doWork(0xc4201461e0)
        /go/src/github.com/rancher/connectivity-check/checker/watcher.go:134 +0x769
github.com/rancher/connectivity-check/checker.(*PeersWatcher).Run(0xc4201461e0)
        /go/src/github.com/rancher/connectivity-check/checker/watcher.go:159 +0xcb
created by github.com/rancher/connectivity-check/checker.(*PeersWatcher).Start
        /go/src/github.com/rancher/connectivity-check/checker/watcher.go:168 +0x77
```

**Comment by superseb** [comment]
Fixed by https://github.com/rancher/connectivity-check/pull/3  / `rancher/net:v0.13.10` / `rancher/server:v1.6.15`
