### ISSUE TITLE
Alert manager occupying 200% CPU

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#11439]
Go routine dump:

```
PC=0x45df41 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0xda3ff0, 0x0, 0x0, 0x0, 0x0, 0x100000000, 0x0, 0x0, 0x7ffe4e064ab8, 0x40f85b, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:438 +0x21
runtime.futexsleep(0xda3ff0, 0xc400000000, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os_linux.go:45 +0x62
runtime.notesleep(0xda3ff0)
	/usr/local/go/src/runtime/lock_futex.go:151 +0x9b
runtime.stopm()
	/usr/local/go/src/runtime/proc.go:1680 +0xe5
runtime.findrunnable(0xc42001d300, 0x0)
	/usr/local/go/src/runtime/proc.go:2135 +0x4d2
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2255 +0x12c
runtime.park_m(0xc420717800)
	/usr/local/go/src/runtime/proc.go:2318 +0xb6
runtime.mcall(0x7ffe4e064c50)
	/usr/local/go/src/runtime/asm_amd64.s:286 +0x5b

goroutine 1 [chan receive, 6 minutes]:
main.main()
	/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:393 +0x19b7

goroutine 5 [syscall, 6 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 22 [select]:
github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh.(*localPeer).actorLoop(0xc420166c90, 0xc42017a360)
	/go/src/github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh/local_peer.go:141 +0xf5
created by github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh.newLocalPeer
	/go/src/github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh/local_peer.go:31 +0x125

goroutine 23 [select]:
github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh.(*routes).run(0xc420196300, 0xc42017a480, 0xc420172060, 0xc4201720c0)
	/go/src/github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh/routes.go:177 +0x11f
created by github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh.newRoutes
	/go/src/github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh/routes.go:44 +0x3ff

goroutine 24 [select, 6 minutes]:
github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh.(*connectionMaker).queryLoop(0xc420176460, 0xc42017a4e0)
	/go/src/github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh/connection_maker.go:226 +0x122
created by github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh.newConnectionMaker
	/go/src/github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh/connection_maker.go:75 +0x1f9

goroutine 30 [select, 6 minutes]:
github.com/prometheus/alertmanager/nflog.(*nlog).run(0xc420196500)
	/go/src/github.com/prometheus/alertmanager/nflog/nflog.go:309 +0x1cd
created by github.com/prometheus/alertmanager/nflog.New
	/go/src/github.com/prometheus/alertmanager/nflog/nflog.go:268 +0x1c1

goroutine 41 [select, 6 minutes]:
github.com/prometheus/alertmanager/silence.(*Silences).Maintenance(0xc420164780, 0xd18c2e2800, 0xc420154020, 0x16, 0xc420172120)
	/go/src/github.com/prometheus/alertmanager/silence/silence.go:284 +0x1a4
main.main.func3(0xc420164780, 0xc4201682c0, 0xc420172120, 0xc42016c110)
	/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:229 +0xb1
created by main.main
	/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:228 +0xe6b

goroutine 42 [IO wait, 6 minutes]:
internal/poll.runtime_pollWait(0x7fda4ed77f70, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420196718, 0x72, 0xc420024d00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420196718, 0xffffffffffffff00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc420196700, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:335 +0x1e2
net.(*netFD).accept(0xc420196700, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc42016a098, 0xc420024f88, 0x18, 0x855793)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc42016a098, 0xa09390, 0xc42016a098, 0x0)
	/usr/local/go/src/net/tcpsock.go:234 +0x49
github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh.(*Router).listenTCP.func1(0xc42016a098, 0xc4201a8000)
	/go/src/github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh/router.go:113 +0x59
created by github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh.(*Router).listenTCP
	/go/src/github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh/router.go:110 +0x15e

goroutine 43 [select, 6 minutes]:
github.com/prometheus/alertmanager/provider/mem.(*Alerts).runGC(0xc420164a50)
	/go/src/github.com/prometheus/alertmanager/provider/mem/mem.go:54 +0x1ef
created by github.com/prometheus/alertmanager/provider/mem.NewAlerts
	/go/src/github.com/prometheus/alertmanager/provider/mem/mem.go:47 +0x15f

goroutine 65 [chan receive, 6 minutes]:
github.com/prometheus/alertmanager/provider/mem.(*Alerts).Subscribe.func1(0xc420164a50, 0x0, 0xc4202d8000, 0xdc2d10, 0x0, 0x0, 0xc4202d00c0)
	/go/src/github.com/prometheus/alertmanager/provider/mem/mem.go:114 +0x195
created by github.com/prometheus/alertmanager/provider/mem.(*Alerts).Subscribe
	/go/src/github.com/prometheus/alertmanager/provider/mem/mem.go:98 +0x19a

goroutine 66 [select, 6 minutes]:
github.com/prometheus/alertmanager/inhibit.(*Inhibitor).runGC(0xc42013e1c0, 0xcb5ee0, 0xc4202d4140)
	/go/src/github.com/prometheus/alertmanager/inhibit/inhibit.go:60 +0x148
github.com/prometheus/alertmanager/inhibit.(*Inhibitor).Run.func1(0x10, 0xc4200257c8)
	/go/src/github.com/prometheus/alertmanager/inhibit/inhibit.go:111 +0x3c
github.com/prometheus/alertmanager/vendor/github.com/oklog/oklog/pkg/group.(*Group).Run.func1(0xc4202d8180, 0xc4202e0040, 0xc4202d6040)
	/go/src/github.com/prometheus/alertmanager/vendor/github.com/oklog/oklog/pkg/group/group.go:38 +0x27
created by github.com/prometheus/alertmanager/vendor/github.com/oklog/oklog/pkg/group.(*Group).Run
	/go/src/github.com/prometheus/alertmanager/vendor/github.com/oklog/oklog/pkg/group/group.go:37 +0xa8

goroutine 16 [select]:
github.com/prometheus/alertmanager/dispatch.(*Dispatcher).run(0xc42013c240, 0xcb46e0, 0xc4202e0000)
	/go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:178 +0x208
github.com/prometheus/alertmanager/dispatch.(*Dispatcher).Run(0xc42013c240)
	/go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:70 +0x135
created by main.main.func8
	/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:339 +0x652

goroutine 49 [chan receive, 6 minutes]:
github.com/prometheus/alertmanager/vendor/github.com/oklog/oklog/pkg/group.(*Group).Run(0xc420022fb0, 0xc4202d6050, 0x1)
	/go/src/github.com/prometheus/alertmanager/vendor/github.com/oklog/oklog/pkg/group/group.go:43 +0xf6
github.com/prometheus/alertmanager/inhibit.(*Inhibitor).Run(0xc42013e1c0)
	/go/src/github.com/prometheus/alertmanager/inhibit/inhibit.go:123 +0x32f
created by main.main.func8
	/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:340 +0x67a

goroutine 67 [select]:
github.com/prometheus/alertmanager/inhibit.(*Inhibitor).run(0xc42013e1c0, 0xcb5ee0, 0xc4202d4180)
	/go/src/github.com/prometheus/alertmanager/inhibit/inhibit.go:76 +0x181
github.com/prometheus/alertmanager/inhibit.(*Inhibitor).Run.func3(0xc4202e0000, 0xc4202d4000)
	/go/src/github.com/prometheus/alertmanager/inhibit/inhibit.go:117 +0x3c
github.com/prometheus/alertmanager/vendor/github.com/oklog/oklog/pkg/group.(*Group).Run.func1(0xc4202d8180, 0xc4202e0060, 0xc4202d6060)
	/go/src/github.com/prometheus/alertmanager/vendor/github.com/oklog/oklog/pkg/group/group.go:38 +0x27
created by github.com/prometheus/alertmanager/vendor/github.com/oklog/oklog/pkg/group.(*Group).Run
	/go/src/github.com/prometheus/alertmanager/vendor/github.com/oklog/oklog/pkg/group/group.go:37 +0xa8

goroutine 68 [chan receive, 6 minutes]:
github.com/prometheus/alertmanager/provider/mem.(*Alerts).Subscribe.func1(0xc420164a50, 0x1, 0xc4202d8240, 0xdc2d10, 0x0, 0x0, 0xc4202d0180)
	/go/src/github.com/prometheus/alertmanager/provider/mem/mem.go:114 +0x195
created by github.com/prometheus/alertmanager/provider/mem.(*Alerts).Subscribe
	/go/src/github.com/prometheus/alertmanager/provider/mem/mem.go:98 +0x19a

goroutine 134 [IO wait]:
internal/poll.runtime_pollWait(0x7fda4ed77eb0, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420162098, 0x72, 0xc4202e5c00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420162098, 0xffffffffffffff00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc420162080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:335 +0x1e2
net.(*netFD).accept(0xc420162080, 0x411ad9, 0xc420742da0, 0x9320e0)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc420152018, 0x9320e0, 0xc4202e5dd0, 0x401137)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc420152018, 0xc4202e5e18, 0xc4202e5e20, 0xc4202e5e10)
	/usr/local/go/src/net/tcpsock.go:234 +0x49
net/http.tcpKeepAliveListener.Accept(0xc420152018, 0xa094f8, 0xc420742d20, 0xcb5fa0, 0xc42000ef90)
	/usr/local/go/src/net/http/server.go:3120 +0x2f
net/http.(*Server).Serve(0xc42007a4e0, 0xcb5920, 0xc420152018, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2695 +0x1b2
net/http.(*Server).ListenAndServe(0xc42007a4e0, 0xc42007a4e0, 0x456c00)
	/usr/local/go/src/net/http/server.go:2636 +0xa9
net/http.ListenAndServe(0x9e302c, 0x5, 0xcaec20, 0xc4202753e0, 0x726301, 0xc4202eef98)
	/usr/local/go/src/net/http/server.go:2882 +0x7f
main.listen(0x9e302c, 0x5, 0xc4202753e0, 0xcae8a0, 0xc4201669c0)
	/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:500 +0x52
created by main.main
	/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:369 +0x17cc

goroutine 135 [select, 6 minutes, locked to thread]:
runtime.gopark(0xa09b20, 0x0, 0x9e480a, 0x6, 0x18, 0x1)
	/usr/local/go/src/runtime/proc.go:287 +0x12c
runtime.selectgo(0xc4205c3f50, 0xc4202d0420)
	/usr/local/go/src/runtime/select.go:395 +0x1149
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:511 +0x220
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1

goroutine 145 [select, 6 minutes]:
main.main.func9(0xc4202d0300, 0xc4202d02a0, 0xc420070300, 0xc4201940a0)
	/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:382 +0xfa
created by main.main
	/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:379 +0x198c

goroutine 46 [IO wait]:
internal/poll.runtime_pollWait(0x7fda4ed77df0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420162118, 0x72, 0xffffffffffffff00, 0xcb11e0, 0xcac410)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420162118, 0xc420216000, 0x1000, 0x1000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420162100, 0xc420216000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc420162100, 0xc420216000, 0x1000, 0x1000, 0xc4205bf8c8, 0x66b7ca, 0xc42000f1d8)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc420152028, 0xc420216000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
net/http.(*connReader).Read(0xc42000f1d0, 0xc420216000, 0x1000, 0x1000, 0xc42004e180, 0xcac03a, 0x2)
	/usr/local/go/src/net/http/server.go:753 +0x105
bufio.(*Reader).fill(0xc4201c0360)
	/usr/local/go/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).ReadSlice(0xc4201c0360, 0xc4205bfa0a, 0x4104b6, 0x7fda4ed360b0, 0x4, 0xc4205bfab8, 0xc4205bfa48)
	/usr/local/go/src/bufio/bufio.go:338 +0x2c
bufio.(*Reader).ReadLine(0xc4201c0360, 0x100, 0xf8, 0x9d4b60, 0x411901, 0x12200205bfa90, 0xf8)
	/usr/local/go/src/bufio/bufio.go:367 +0x34
net/textproto.(*Reader).readLineSlice(0xc4202370b0, 0xc4205bfb20, 0xc4205bfb20, 0x4110a8, 0x100, 0x9d4b60)
	/usr/local/go/src/net/textproto/reader.go:55 +0x70
net/textproto.(*Reader).ReadLine(0xc4202370b0, 0xc420250400, 0x0, 0xc4205bfb90, 0x4b8102)
	/usr/local/go/src/net/textproto/reader.go:36 +0x2b
net/http.readRequest(0xc4201c0360, 0x0, 0xc420250400, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:925 +0x99
net/http.(*conn).readRequest(0xc420194000, 0xcb5ee0, 0xc42004e140, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:933 +0x17c
net/http.(*conn).serve(0xc420194000, 0xcb5ee0, 0xc42004e140)
	/usr/local/go/src/net/http/server.go:1739 +0x50e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2720 +0x288

goroutine 166 [semacquire]:
sync.runtime_Semacquire(0xc4208621ac)
	/usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc4208621a0)
	/usr/local/go/src/sync/waitgroup.go:131 +0x72
github.com/prometheus/alertmanager/notify.FanoutStage.Exec(0xc42013b9e0, 0x1, 0x1, 0xcb6520, 0xc4209ef110, 0xcae8a0, 0xc4202908d0, 0xc4201521c0, 0x1, 0x1, ...)
	/go/src/github.com/prometheus/alertmanager/notify/notify.go:307 +0x165
github.com/prometheus/alertmanager/notify.(*FanoutStage).Exec(0xc4202753a0, 0xcb6520, 0xc4209ef110, 0xcae8a0, 0xc4202908d0, 0xc4201521c0, 0x1, 0x1, 0xcb6520, 0xc4209ef110, ...)
	<autogenerated>:1 +0xc6
github.com/prometheus/alertmanager/notify.MultiStage.Exec(0xc4202908a0, 0x3, 0x3, 0xcb6520, 0xc4209ef110, 0xcae8a0, 0xc4202908d0, 0xc4201521a8, 0x1, 0x1, ...)
	/go/src/github.com/prometheus/alertmanager/notify/notify.go:278 +0xf4
github.com/prometheus/alertmanager/notify.(*MultiStage).Exec(0xc4202753c0, 0xcb6520, 0xc4209ef110, 0xcae8a0, 0xc4202908d0, 0xc4201521a8, 0x1, 0x1, 0x9a5920, 0xc420930570, ...)
	<autogenerated>:1 +0xc6
github.com/prometheus/alertmanager/notify.RoutingStage.Exec(0xc420290810, 0xcb6520, 0xc4209ef110, 0xcae8a0, 0xc4202908d0, 0xc4201521a8, 0x1, 0x1, 0x50, 0x5, ...)
	/go/src/github.com/prometheus/alertmanager/notify/notify.go:264 +0xea
github.com/prometheus/alertmanager/dispatch.(*Dispatcher).processAlert.func1(0xcb6520, 0xc4209ef110, 0xc4201521a8, 0x1, 0x1, 0xc4209fc640)
	/go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:264 +0xa6
github.com/prometheus/alertmanager/dispatch.(*aggrGroup).run.func1(0xc4201521a8, 0x1, 0x1, 0x4)
	/go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:372 +0x58
github.com/prometheus/alertmanager/dispatch.(*aggrGroup).flush(0xc42013c360, 0xc4205f1f20)
	/go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:432 +0x53d
github.com/prometheus/alertmanager/dispatch.(*aggrGroup).run(0xc42013c360, 0xc42004d2e0)
	/go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:371 +0x183
created by github.com/prometheus/alertmanager/dispatch.(*Dispatcher).processAlert
	/go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:263 +0x38e

goroutine 6919567 [IO wait]:
internal/poll.runtime_pollWait(0x7fda4ed77d30, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420196018, 0x72, 0xffffffffffffff00, 0xcb11e0, 0xcac410)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420196018, 0xc42098e000, 0x1000, 0x1000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420196000, 0xc42098e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc420196000, 0xc42098e000, 0x1000, 0x1000, 0xc4205efb00, 0x66b7ca, 0xc4209807b8)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc4209cf838, 0xc42098e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
net/http.(*connReader).Read(0xc4209807b0, 0xc42098e000, 0x1000, 0x1000, 0xc4205efbe8, 0x508b2c, 0xc420196000)
	/usr/local/go/src/net/http/server.go:753 +0x105
bufio.(*Reader).fill(0xc4207f7ce0)
	/usr/local/go/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).Peek(0xc4207f7ce0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x7fda4ed77d00)
	/usr/local/go/src/bufio/bufio.go:129 +0x3a
net/http.(*conn).readRequest(0xc420742d20, 0xcb5ee0, 0xc42085f640, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:930 +0xc77
net/http.(*conn).serve(0xc420742d20, 0xcb5ee0, 0xc42085f640)
	/usr/local/go/src/net/http/server.go:1739 +0x50e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2720 +0x288

goroutine 7144732 [runnable]:
time.Time.Add(0x38c05d9e, 0xed217a8b0, 0x0, 0xfffffcb9cf476000, 0x0, 0x0, 0xc4201521c8)
	/usr/local/go/src/time/time.go:844 +0x151
github.com/prometheus/alertmanager/notify.(*DedupStage).needsUpdate(0xc420290870, 0xc42018c120, 0xc4209ef230, 0xc4209ef260, 0x34630b8a000, 0x1, 0x1, 0x0)
	/go/src/github.com/prometheus/alertmanager/notify/notify.go:491 +0xca
github.com/prometheus/alertmanager/notify.(*DedupStage).Exec(0xc420290870, 0xcb6520, 0xc4209ef110, 0xcae8a0, 0xc4202908d0, 0xc4201521c0, 0x1, 0x1, 0xcb6520, 0xc4209ef110, ...)
	/go/src/github.com/prometheus/alertmanager/notify/notify.go:539 +0x7ce
github.com/prometheus/alertmanager/notify.MultiStage.Exec(0xc42028ef80, 0x4, 0x4, 0xcb6520, 0xc4209ef110, 0xcae8a0, 0xc4202908d0, 0xc4201521c0, 0x1, 0x1, ...)
	/go/src/github.com/prometheus/alertmanager/notify/notify.go:278 +0xf4
github.com/prometheus/alertmanager/notify.(*MultiStage).Exec(0xc420275380, 0xcb6520, 0xc4209ef110, 0xcae8a0, 0xc4202908d0, 0xc4201521c0, 0x1, 0x1, 0x0, 0x0, ...)
	<autogenerated>:1 +0xc6
github.com/prometheus/alertmanager/notify.FanoutStage.Exec.func1(0xcb6520, 0xc4209ef110, 0xcae8a0, 0xc4202908d0, 0xc4201521c0, 0x1, 0x1, 0xc4209f0d00, 0xc4208621a0, 0xcb04a0, ...)
	/go/src/github.com/prometheus/alertmanager/notify/notify.go:300 +0xa4
created by github.com/prometheus/alertmanager/notify.FanoutStage.Exec
	/go/src/github.com/prometheus/alertmanager/notify/notify.go:299 +0x135

rax    0xca
rbx    0xda3ee0
rcx    0x45df43
rdx    0x0
rdi    0xda3ff0
rsi    0x0
rbp    0x7ffe4e064a80
rsp    0x7ffe4e064a38
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x1
r13    0xc420998cc0
r14    0x1
r15    0x0
rip    0x45df41
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```

```
goroutine 166 [semacquire]:
sync.runtime_Semacquire(0xc4208621ac)
    /usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc4208621a0)
    /usr/local/go/src/sync/waitgroup.go:131 +0x72
github.com/prometheus/alertmanager/notify.FanoutStage.Exec(0xc42013b9e0, 0x1, 0x1, 0xcb6520, 0xc4209ef110, 0xcae8a0, 0xc4202908d0, 0xc4201521c0, 0x1, 0x1, ...)
    /go/src/github.com/prometheus/alertmanager/notify/notify.go:307 +0x165
github.com/prometheus/alertmanager/notify.(*FanoutStage).Exec(0xc4202753a0, 0xcb6520, 0xc4209ef110, 0xcae8a0, 0xc4202908d0, 0xc4201521c0, 0x1, 0x1, 0xcb6520, 0xc4209ef110, ...)
    <autogenerated>:1 +0xc6
github.com/prometheus/alertmanager/notify.MultiStage.Exec(0xc4202908a0, 0x3, 0x3, 0xcb6520, 0xc4209ef110, 0xcae8a0, 0xc4202908d0, 0xc4201521a8, 0x1, 0x1, ...)
    /go/src/github.com/prometheus/alertmanager/notify/notify.go:278 +0xf4
github.com/prometheus/alertmanager/notify.(*MultiStage).Exec(0xc4202753c0, 0xcb6520, 0xc4209ef110, 0xcae8a0, 0xc4202908d0, 0xc4201521a8, 0x1, 0x1, 0x9a5920, 0xc420930570, ...)
    <autogenerated>:1 +0xc6
github.com/prometheus/alertmanager/notify.RoutingStage.Exec(0xc420290810, 0xcb6520, 0xc4209ef110, 0xcae8a0, 0xc4202908d0, 0xc4201521a8, 0x1, 0x1, 0x50, 0x5, ...)
    /go/src/github.com/prometheus/alertmanager/notify/notify.go:264 +0xea
github.com/prometheus/alertmanager/dispatch.(*Dispatcher).processAlert.func1(0xcb6520, 0xc4209ef110, 0xc4201521a8, 0x1, 0x1, 0xc4209fc640)
    /go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:264 +0xa6
github.com/prometheus/alertmanager/dispatch.(*aggrGroup).run.func1(0xc4201521a8, 0x1, 0x1, 0x4)
    /go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:372 +0x58
github.com/prometheus/alertmanager/dispatch.(*aggrGroup).flush(0xc42013c360, 0xc4205f1f20)
    /go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:432 +0x53d
github.com/prometheus/alertmanager/dispatch.(*aggrGroup).run(0xc42013c360, 0xc42004d2e0)
    /go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:371 +0x183
created by github.com/prometheus/alertmanager/dispatch.(*Dispatcher).processAlert
    /go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:263 +0x38e
```

**Comment by superseb** [comment]
Possibly related: https://github.com/prometheus/alertmanager/pull/1230

**Comment by zionwu** [comment]
According to this issue https://github.com/prometheus/alertmanager/issues/583, the default group_interval should not be 0.
