### ISSUE TITLE
ui crashes when installing apps from community catalog

### ISSUE THREAD

**Issue by levensailor** [rancher/rancher#11481]
when loading cloudfare app page

Uncaught TypeError: (0 , a.compare) is not a function
    at https://rancher.presidio.cloud/assets/vendor-07924e371a1924abb9f3f1f6ee4ace61.js:12466:250
    at Array.sort (native)
    at i.<anonymous> (https://rancher.presidio.cloud/assets/vendor-07924e371a1924abb9f3f1f6ee4ace61.js:12466:182)
    at fe.Wt.get (https://rancher.presidio.cloud/assets/vendor-07924e371a1924abb9f3f1f6ee4ace61.js:2945:20)
    at te (https://rancher.presidio.cloud/assets/vendor-07924e371a1924abb9f3f1f6ee4ace61.js:2798:55)
    at n.compute (https://rancher.presidio.cloud/assets/vendor-07924e371a1924abb9f3f1f6ee4ace61.js:2713:16)
    at n.value (https://rancher.presidio.cloud/assets/vendor-07924e371a1924abb9f3f1f6ee4ace61.js:2709:50)
    at e.value (https://rancher.presidio.cloud/assets/vendor-07924e371a1924abb9f3f1f6ee4ace61.js:1554:37)
    at e.processComponentArgs (https://rancher.presidio.cloud/assets/vendor-07924e371a1924abb9f3f1f6ee4ace61.js:2702:62)
    at r.create (https://rancher.presidio.cloud/assets/vendor-07924e371a1924abb9f3f1f6ee4ace61.js:2337:183)
(anonymous) @ component.js:111
(anonymous) @ component.js:109
Wt.get @ ember-metal.js:2904
te @ ember-metal.js:2270
n.compute @ references.js:116
n.value @ references.js:38
e.value @ runtime.js:723
e.processComponentArgs @ process-args.js:15
r.create @ curly.js:224
(anonymous) @ runtime.js:1778
e.evaluate @ runtime.js:73
e.next @ runtime.js:7521
e.execute @ runtime.js:7507
r.handleException @ runtime.js:6897
e.handleException @ runtime.js:7096
e.throw @ runtime.js:6776
t.evaluate @ runtime.js:983
e.execute @ runtime.js:6763
e.rerender @ runtime.js:7127
o.render @ renderer.js:68
e.runInTransaction @ ember-metal.js:621
e._renderRoots @ renderer.js:346
e._renderRootsTransaction @ renderer.js:384
e._revalidate @ renderer.js:426
e.invoke @ backburner.js:291
e.flush @ backburner.js:159
e.flush @ backburner.js:361
e.end @ backburner.js:471
e.run @ backburner.js:560
Ne @ ember-metal.js:3875
e.handler @ action.js:119
(anonymous) @ event_dispatcher.js:235
dispatch @ jquery.js:5206
g.handle @ jquery.js:5014
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-alpha16` UI: `v2.0.20` |
|Access|`local` `admin`|
|Route|`apps-tab.index`|

**Comment by vincent99** [comment]
None of the catalog works in the current preview.
