### ISSUE TITLE
Rancher server crashes when trying to create ingress without host path in ingress rules.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11590]
Rancher server - 2.0 build from master
Steps to reproduce the problem:
Create a workload of type deployment.
Create a Ingress with workload rules having only port set.
Rancher server crashes:

```
panic: interface conversion: interface {} is nil, not string

goroutine 268432 [running]:
github.com/rancher/rancher/pkg/api/store/ingress.getPaths(0xc42c66b1d0, 0xc43040deb0, 0x1)
    /go/src/github.com/rancher/rancher/pkg/api/store/ingress/store.go:115 +0x474
github.com/rancher/rancher/pkg/api/store/ingress.formatData(0xc42c66b1d0, 0xc42f686001)
    /go/src/github.com/rancher/rancher/pkg/api/store/ingress/store.go:45 +0x143
github.com/rancher/rancher/pkg/api/store/ingress.New.func1(0xc42b680a00, 0xc42c66b1d0, 0xc429fd6180, 0xc4287b27a8, 0xc4287b2701, 0x1160101)
    /go/src/github.com/rancher/rancher/pkg/api/store/ingress/store.go:148 +0x30
github.com/rancher/rancher/vendor/github.com/rancher/norman/store/transform.(*Store).Watch.func1(0xc42c66b1d0, 0xc4287b27a8)
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/transform/transform.go:47 +0x45
github.com/rancher/rancher/vendor/github.com/rancher/norman/types/convert.Chan.func1(0xc42f686000, 0xc425e702a0, 0xc42f686060)
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/types/convert/convert.go:21 +0x67
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/types/convert.Chan
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/types/convert/convert.go:19 +0x7f
```

**Comment by sangeethah** [comment]
Tested with latest build from master - Feb 28

We are allowed to create Ingress with workload rules having only port set. There is no un handled exceptions.

Ingress is not functional .This issue is tracked in https://github.com/rancher/rancher/issues/11646
