### ISSUE TITLE
Can not set a value on a null target

### ISSUE THREAD

**Issue by asAngus** [rancher/rancher#11621]
**Rancher versions:**
rancher/server:v1.6.14
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:v0.3.3
ipsec:v0.13.7
network-services:v0.9.5
scheduler:v0.8.3

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:10:14 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:46 2017
  OS/Arch:	linux/amd64
  Experimental:	false
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
external DB
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**

**Results:**

2018-02-24T13:47:55.836897127Z 2018-02-24 13:47:55,835 ERROR [44a6a6da-7b4d-40d1-9b6d-8227ea089603:7573] [volumeStoragePoolMap:297] [volumestoragepoolmap.remove] [] [ecutorService-1] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception java.lang.IllegalStateException: Can not set a value on a null target
2018-02-24T13:47:55.836965227Z 	at io.cattle.platform.object.util.DataAccessor.getTargetMap(DataAccessor.java:218)
2018-02-24T13:47:55.836988144Z 	at io.cattle.platform.object.util.DataAccessor.get(DataAccessor.java:184)
2018-02-24T13:47:55.837003017Z 	at io.cattle.platform.object.util.DataAccessor.as(DataAccessor.java:180)
2018-02-24T13:47:55.837016585Z 	at io.cattle.platform.agent.instance.serialization.AgentInstanceAuthObjectPostProcessor.process(AgentInstanceAuthObjectPostProcessor.java:56)
2018-02-24T13:47:55.837030487Z 	at io.cattle.platform.object.serialization.impl.DefaultObjectSerializerImpl.marshall(DefaultObjectSerializerImpl.java:81)
2018-02-24T13:47:55.837044025Z 	at io.cattle.platform.object.serialization.impl.DefaultObjectSerializerImpl.marshall(DefaultObjectSerializerImpl.java:71)
2018-02-24T13:47:55.837058241Z 	at io.cattle.platform.object.serialization.impl.DefaultObjectSerializerImpl.marshall(DefaultObjectSerializerImpl.java:71)
2018-02-24T13:47:55.837072561Z 	at io.cattle.platform.object.serialization.impl.DefaultObjectSerializerImpl.serialize(DefaultObjectSerializerImpl.java:38)
2018-02-24T13:47:55.837086072Z 	at io.cattle.platform.process.common.handler.AgentBasedProcessLogic.handleEvent(AgentBasedProcessLogic.java:130)
2018-02-24T13:47:55.837100268Z 	at io.cattle.platform.process.common.handler.AgentBasedProcessLogic.handle(AgentBasedProcessLogic.java:111)
2018-02-24T13:47:55.837115114Z 	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:470)
2018-02-24T13:47:55.837146526Z 	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:421)
2018-02-24T13:47:55.837166421Z 	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:415)
2018-02-24T13:47:55.837181613Z 	at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42)
2018-02-24T13:47:55.837197176Z 	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:415)
2018-02-24T13:47:55.837211696Z 	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:517)
2018-02-24T13:47:55.837231400Z 	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:345)
2018-02-24T13:47:55.837248189Z 	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:245)
2018-02-24T13:47:55.837277517Z 	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7)
2018-02-24T13:47:55.837292971Z 	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3)
2018-02-24T13:47:55.837307465Z 	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
2018-02-24T13:47:55.837322812Z 	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
2018-02-24T13:47:55.837336750Z 	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
2018-02-24T13:47:55.837351010Z 	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
2018-02-24T13:47:55.837366307Z 	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:242)
2018-02-24T13:47:55.837380848Z 	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:184)
2018-02-24T13:47:55.837394847Z 	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:157)
2018-02-24T13:47:55.837408870Z 	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:116)
2018-02-24T13:47:55.837423831Z 	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:113)
2018-02-24T13:47:55.837438223Z 	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
2018-02-24T13:47:55.837453893Z 	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
2018-02-24T13:47:55.837468191Z 	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
2018-02-24T13:47:55.837480368Z 	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
2018-02-24T13:47:55.837489268Z 	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:113)
2018-02-24T13:47:55.837505360Z 	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl.processExecuteWithLock(ProcessInstanceDispatcherImpl.java:136)
2018-02-24T13:47:55.837517146Z 	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl$1.doWithLock(ProcessInstanceDispatcherImpl.java:123)
2018-02-24T13:47:55.837526794Z 	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl$1.doWithLock(ProcessInstanceDispatcherImpl.java:120)

**Comment by vingov** [comment]
We are facing the same issue.

**Comment by superseb** [comment]
Please provide information what you ran/did to get into this state so we can reproduce and investigate.

**Comment by untoldone** [comment]
I just got into a similar looking state on server 1.6.17. I'm unsure what we did to trigger this if anything. Currently, our rancher server's website just shows "Loading..." and there's a number of other exceptions and errors in the console.

Let me know what debugging information I can provide if any to help debug.

**Comment by untoldone** [comment]
* Tried restarting container -- didn't work
* Tried recreating server container (no local volume, uses remote external DB) -- didn't work
* Tried restarting host with rancher server -- this fixed the issues

However -- i still see the exceptions in the logs that match the exception listed here.. but I don't see anything in particular that seems broken in our current rancher installation any longer.

    2018-06-06 17:03:03,114 ERROR [:] [] [] [] [cutorService-11] [.e.s.i.ProcessInstanceDispatcherImpl] Unknown exception running process [volumestoragepoolmap.remove:567729] on [9825] java.lang.IllegalStateException: Can not set a value on a null target
      at io.cattle.platform.object.util.DataAccessor.getTargetMap(DataAccessor.java:218)
      at io.cattle.platform.object.util.DataAccessor.get(DataAccessor.java:184)
      at io.cattle.platform.object.util.DataAccessor.as(DataAccessor.java:180)
      at io.cattle.platform.agent.instance.serialization.AgentInstanceAuthObjectPostProcessor.process(AgentInstanceAuthObjectPostProcessor.java:56)
      at io.cattle.platform.object.serialization.impl.DefaultObjectSerializerImpl.marshall(DefaultObjectSerializerImpl.java:81)
      at io.cattle.platform.object.serialization.impl.DefaultObjectSerializerImpl.marshall(DefaultObjectSerializerImpl.java:71)
      at io.cattle.platform.object.serialization.impl.DefaultObjectSerializerImpl.marshall(DefaultObjectSerializerImpl.java:71)
      at io.cattle.platform.object.serialization.impl.DefaultObjectSerializerImpl.serialize(DefaultObjectSerializerImpl.java:38)
      at io.cattle.platform.process.common.handler.AgentBasedProcessLogic.handleEvent(AgentBasedProcessLogic.java:130)
      at io.cattle.platform.process.common.handler.AgentBasedProcessLogic.handle(AgentBasedProcessLogic.java:111)
      at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:470)
      at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:421)
      at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:415)
      at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42)
      at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:415)
      at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:517)
      at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:345)
      at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:245)
      at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7)
      at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3)
      at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
      at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
      at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
      at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
      at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:242)
      at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:184)
      at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:157)
      at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:116)
      at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:113)
      at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
      at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
      at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
      at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
      at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:113)
      at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl.processExecuteWithLock(ProcessInstanceDispatcherImpl.java:136)
      at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl$1.doWithLock(ProcessInstanceDispatcherImpl.java:123)
      at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl$1.doWithLock(ProcessInstanceDispatcherImpl.java:120)
      at io.cattle.platform.lock.impl.AbstractLockManagerImpl$4.doWithLock(AbstractLockManagerImpl.java:50)
      at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
      at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:25)
      at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:47)
      at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl.execute(ProcessInstanceDispatcherImpl.java:120)
      at io.cattle.platform.engine.server.ProcessInstanceReference.doRun(ProcessInstanceReference.java:59)
      at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15)
      at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
      at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
      at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108)
      at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
      at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      at java.lang.Thread.run(Thread.java:745)

durring server startup I see:

    2018-06-06 17:02:49,906 INFO    [main] [ConsoleStatus] Starting [37/93]: ConfigItemServerImpl
    time="2018-06-06T17:02:50Z" level=info msg="Downloading key from http://localhost:8081/v1/scripts/api.crt"
    time="2018-06-06T17:02:50Z" level=fatal msg="Error getting config." error="Invalid key content"
    2018-06-06 17:02:50,460 INFO    [main] [ConsoleStatus] Starting [38/93]: ConfigUpdatePublisher
    2018-06-06 17:02:50,466 INFO    [main] [ConsoleStatus] Starting [39/93]: DataManager
    2018-06-06 17:02:50,466 INFO    [main] [ConsoleStatus] Starting [40/93]: DefaultAuthorizationProvider
    time="2018-06-06T17:02:51Z" level=info msg="Downloading key from http://localhost:8081/v1/scripts/api.crt"
    time="2018-06-06T17:02:51Z" level=fatal msg="Error getting config." error="Invalid key content"
    time="2018-06-06T17:02:51Z" level=info msg="Starting rancher-compose-executor" version=v0.14.28
    time="2018-06-06T17:02:51Z" level=fatal msg="Unable to create event router" error="Get http://localhost:8080/v2-beta: dial tcp 127.0.0.1:8080: getsockopt: connection refused"
    time="2018-06-06T17:02:51Z" level=fatal msg="Failed to configure cattle client: Get http://localhost:8080/v2-beta: dial tcp 127.0.0.1:8080: connect: connection refused"
    time="2018-06-06T17:02:51Z" level=warning msg="Couldn't load install uuid: Get http://localhost:8080/v2-beta: dial tcp 127.0.0.1:8080: getsockopt: connection refused"
    time="2018-06-06T17:02:51Z" level=info msg="Starting Catalog Service (port 8088, refresh interval 300 seconds)"
    2018-06-06 17:02:53,272 INFO    [main] [ConsoleStatus] Starting [41/93]: DefaultJooqResourceManager

and

    time="2018-06-06T17:02:53Z" level=info msg="Starting rancher-compose-executor" version=v0.14.28
    time="2018-06-06T17:02:53Z" level=fatal msg="Unable to create event router" error="Get http://localhost:8080/v2-beta: dial tcp 127.0.0.1:8080: getsockopt: connection refused"
    time="2018-06-06T17:02:53Z" level=fatal msg="Failed to configure cattle client: Get http://localhost:8080/v2-beta: dial tcp 127.0.0.1:8080: connect: connection refused"
    time="2018-06-06T17:02:53Z" level=info msg="Downloading key from http://localhost:8081/v1/scripts/api.crt"
    time="2018-06-06T17:02:53Z" level=info msg="Starting websocket proxy. Listening on [:8080], Proxying to cattle API at [localhost:8081], Monitoring parent pid [8]."
    time="2018-06-06T17:02:53Z" level=info msg="Master config file: master.conf"
    time="2018-06-06T17:02:53Z" level=info msg="Configured http API filter"

In case its helpful, I'm running Docker version 18.03.1-ce, build 9ee9f40 on Debian 8.6.

**Comment by deniseschannon** [comment]
Available in v1.6.19-rc2
