### ISSUE TITLE
Rancher Agent 1.2.9 Failed to connect to proxy." error="websocket: bad handshake

### ISSUE THREAD

**Issue by moshe0076** [rancher/rancher#11926]
**Rancher versions:**
rancher/server:1.6.14
rancher/agent:1.2.9

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: 0.2.2
network-services: 0.2.8
scheduler:
kubernetes (if applicable):k8s:v1.7.7-rancher1

**Docker version: (`docker version`,`docker info` preferred)** 
1.12.6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.3 LTS (4.4.0)
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher with ALB in front with 3 hosts running Rancher agnet
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
Updating to 1.6.14 from 1.6.10. One of the nodes failed and was replaced.
The Rancher Agent Docker keeps crashing and get replaced every 1-3 hours. In the Rancher Agent logs I can See the following errors:
  time="2018-03-04T08:33:12Z" level=error msg="Failed to connect to proxy." error="websocket: bad handshake" 
time="2018-03-04T08:33:12Z" level=error msg="Failed to connect to websocket proxy: %vwebsocket: bad handshake" 
time="2018-03-04T08:33:17Z" level=info msg="Connecting to proxy." .............

In the Rancher UI the node is marked Active but trying to see logs on the Rancher-Agent via the UI gives "Disconnected".
The node was replaced a number of time during investigation but the result is the same. The other two nodes are working normal
**Results:**

**Comment by moshe0076** [comment]
Hi,

Any news?

Thanks!

**Comment by superseb** [comment]
ALB is not recommended, you'd better configure ELB (http://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/basic-ssl-config/#elb)

**Comment by aschrijver** [comment]
I have the same problem with same versions. Just installed `rancher-server:stable` on an AWS t2.micro and agent on on t2.medium using github authentication. Everything working fine.
Then in UI I added a community catalog pointing to a github repo, pressed OK and got a Server 500 error. Afterwards the rancher-server container became unresponsive and the instance _really slow_.

Restarting the rancher-server container and it works again. The rancher server runs on port 8080 and is behind an `nginx` proxy that does SSL termination (using default install instructions)

**Comment by aschrijver** [comment]
This error occurs from time to time when trying to access the community catalog:

```text
018-03-10 20:18:52,941 ERROR [:] [] [] [] [p1020391880-186] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [https://rancher.example.com/v1/proxy/http://localhost:8088/v1-catalog/templates]. Error id: [8fcf5efd-f1aa-42d8-b6a7-a25de2a965b7]. org.apache.http.conn.HttpHostConnectException: Connect to localhost:8088 [localhost/127.0.0.1] failed: Connection refused
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:138)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:357)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:218)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.apache.http.client.fluent.Executor.execute(Executor.java:215)
	at io.cattle.platform.iaas.api.request.handler.GenericWhitelistedProxy.generate(GenericWhitelistedProxy.java:353)
	at io.github.ibuildthecloud.gdapi.request.handler.AbstractResponseGenerator.handle(AbstractResponseGenerator.java:14)
	at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:99)
	at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:96)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:106)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at io.cattle.platform.iaas.api.servlet.filter.ProxyPreFilter.doFilter(ProxyPreFilter.java:22)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:595)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:191)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:72)
	at io.cattle.platform.iaas.api.servlet.filter.ProxyFilter.doFilter(ProxyFilter.java:65)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:118)
	... 56 common frames omitted

time="2018-03-10T20:18:53Z" level=info msg="Starting Catalog Service (port 8088, refresh interval 300 seconds)" 
time="2018-03-10T20:18:57Z" level=info msg="Handling backend connection request." 
time="2018-03-10T20:18:57Z" level=error msg="Error during upgrade for host [4e4075eb-824a-432e-64fd-26b8bcce8b27]: [websocket: could not find connection header with token 'upgrade']" 
2018/03/10 20:18:57 http: multiple response.WriteHeader calls
```

**Comment by superseb** [comment]
@aschrijver Can you create a new issue with versions and configs used? `t2.micro` is enough in theory, not sure what OS you are using and how many envs/hosts you are running.

If you also see bad handshake errors, might be something wrong in the proxy config. Please share nginx version and config used. Basically include any step/config that can help reproduce.

**Comment by aschrijver** [comment]
Thank you @superseb ! I will do that!

**Comment by aschrijver** [comment]
Having typed a complete issue suddenly I am wondering if it is possible to run rancher-server on a `t2.micro` memory-wise.. probably not, because it is truly micro with just 1GB memory :(

`top` shows `VSZ = 3145m (316%)` for the Java process running rancher server
