### ISSUE TITLE
Fluentd pod crashing on Zookeeper configuration update

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#11950]
**Rancher versions:**  05/03 master

**Steps to Reproduce:**
Intermittent issue. Configure a kafka logging target and save it. Next, try to update the settings and check the fluentd container logs
**Results:**
Fluentd logs:

```
2018-03-05 14:31:01 +0000 [error]: #0 unexpected error error_class=Zookeeper::Exceptions::ContinuationTimeoutError error="response for meth: :get_children, args: [0, \"/brokers/ids\", nil, nil], not received within 30 seconds"
  2018-03-05 14:31:01 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/zookeeper-1.4.11/lib/zookeeper/continuation.rb:117:in `block in value'
  2018-03-05 14:31:01 +0000 [error]: #0 /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  2018-03-05 14:31:01 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/zookeeper-1.4.11/lib/zookeeper/continuation.rb:107:in `value'
  2018-03-05 14:31:01 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/zookeeper-1.4.11/ext/c_zookeeper.rb:231:in `submit_and_block'
  2018-03-05 14:31:01 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/zookeeper-1.4.11/ext/c_zookeeper.rb:40:in `get_children'
  2018-03-05 14:31:01 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/zookeeper-1.4.11/lib/zookeeper/client_methods.rb:69:in `get_children'
  2018-03-05 14:31:01 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.6.6/lib/fluent/plugin/out_kafka_buffered.rb:112:in `refresh_client'
  2018-03-05 14:31:01 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.6.6/lib/fluent/plugin/out_kafka_buffered.rb:189:in `start'
  2018-03-05 14:31:01 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/compat/call_super_mixin.rb:42:in `start'
  2018-03-05 14:31:01 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/root_agent.rb:165:in `block in start'
  2018-03-05 14:31:01 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/root_agent.rb:154:in `block (2 levels) in lifecycle'
  2018-03-05 14:31:01 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/root_agent.rb:153:in `each'
  2018-03-05 14:31:01 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/root_agent.rb:153:in `block in lifecycle'
  2018-03-05 14:31:01 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/root_agent.rb:140:in `each'
  2018-03-05 14:31:01 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/root_agent.rb:140:in `lifecycle'
  2018-03-05 14:31:01 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/root_agent.rb:164:in `start'
  2018-03-05 14:31:01 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/engine.rb:274:in `start'
  2018-03-05 14:31:01 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/engine.rb:219:in `run'
  2018-03-05 14:31:01 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/supervisor.rb:774:in `run_engine'
  2018-03-05 14:31:01 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/supervisor.rb:523:in `block in run_worker'
  2018-03-05 14:31:01 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/supervisor.rb:699:in `main_process'
  2018-03-05 14:31:01 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/supervisor.rb:518:in `run_worker'
  2018-03-05 14:31:01 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
  2018-03-05 14:31:01 +0000 [error]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-03-05 14:31:01 +0000 [error]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-03-05 14:31:01 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/bin/fluentd:8:in `<top (required)>'
  2018-03-05 14:31:01 +0000 [error]: #0 /usr/local/bin/fluentd:22:in `load'
  2018-03-05 14:31:01 +0000 [error]: #0 /usr/local/bin/fluentd:22:in `<main>'
2018-03-05 14:31:01 +0000 [error]: #0 unexpected error error_class=Zookeeper::Exceptions::ContinuationTimeoutError error="response for meth: :get_children, args: [0, \"/brokers/ids\", nil, nil], not received within 30 seconds"
  2018-03-05 14:31:01 +0000 [error]: #0 suppressed same stacktrace
```

**Comment by moelsayed** [comment]
Unable to validate due to #12366.

**Comment by moelsayed** [comment]
I can still see the following error in fluentd logs:
```
2018-04-04 01:39:14 +0000 [error]: #0 unexpected error error_class=Zookeeper::Exceptions::ContinuationTimeoutError error="response for meth: :get_children, args: [0, \"/brokers/ids\", nil, nil], not received within 30 seconds"
  2018-04-04 01:39:14 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/zookeeper-1.4.11/lib/zookeeper/continuation.rb:117:in `block in value'
  2018-04-04 01:39:14 +0000 [error]: #0 /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  2018-04-04 01:39:14 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/zookeeper-1.4.11/lib/zookeeper/continuation.rb:107:in `value'
  2018-04-04 01:39:14 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/zookeeper-1.4.11/ext/c_zookeeper.rb:231:in `submit_and_block'
  2018-04-04 01:39:14 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/zookeeper-1.4.11/ext/c_zookeeper.rb:40:in `get_children'
  2018-04-04 01:39:14 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/zookeeper-1.4.11/lib/zookeeper/client_methods.rb:69:in `get_children'
  2018-04-04 01:39:14 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.6.6/lib/fluent/plugin/out_kafka_buffered.rb:112:in `refresh_client'
  2018-04-04 01:39:14 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.6.6/lib/fluent/plugin/out_kafka_buffered.rb:189:in `start'
  2018-04-04 01:39:14 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/compat/call_super_mixin.rb:42:in `start'
  2018-04-04 01:39:14 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/root_agent.rb:165:in `block in start'
  2018-04-04 01:39:14 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/root_agent.rb:154:in `block (2 levels) in lifecycle'
  2018-04-04 01:39:14 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/root_agent.rb:153:in `each'
  2018-04-04 01:39:14 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/root_agent.rb:153:in `block in lifecycle'
  2018-04-04 01:39:14 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/root_agent.rb:140:in `each'
  2018-04-04 01:39:14 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/root_agent.rb:140:in `lifecycle'
  2018-04-04 01:39:14 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/root_agent.rb:164:in `start'
  2018-04-04 01:39:14 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/engine.rb:274:in `start'
  2018-04-04 01:39:14 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/engine.rb:219:in `run'
  2018-04-04 01:39:14 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/supervisor.rb:774:in `run_engine'
  2018-04-04 01:39:14 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/supervisor.rb:523:in `block in run_worker'
  2018-04-04 01:39:14 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/supervisor.rb:699:in `main_process'
  2018-04-04 01:39:14 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/supervisor.rb:518:in `run_worker'
  2018-04-04 01:39:14 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
  2018-04-04 01:39:14 +0000 [error]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-04-04 01:39:14 +0000 [error]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-04-04 01:39:14 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/bin/fluentd:8:in `<top (required)>'
  2018-04-04 01:39:14 +0000 [error]: #0 /usr/local/bin/fluentd:22:in `load'
  2018-04-04 01:39:14 +0000 [error]: #0 /usr/local/bin/fluentd:22:in `<main>'
```

**Comment by aiwantaozi** [comment]
@moelsayed have you check the kafka you config before? You could use the kafka I send you yesterday. Just let me know if you need any help.

**Comment by moelsayed** [comment]
After reviewing the logging server configuration with @aiwantaozi, I was able to validate the fix and confirm logging target working as expected.
