### ISSUE TITLE
[api] 500 on /v1/localauthconfig

### ISSUE THREAD

**Issue by bartoszcisek** [rancher/rancher#12089]
**Rancher versions:**
rancher/server:v1.6.14
rancher/agent:v1.2.9

**Infrastructure Stack versions:**
healthcheck:v0.3.3
network-manager:v0.7.19

**Docker version: (`docker version`,`docker info` preferred)**
```
Containers: 11
 Running: 10
 Paused: 0
 Stopped: 1
Images: 8
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 82
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-1011-azure
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.64 GiB
Name: <redacted>
ID: <redacted> 
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.13.0-1011-azure
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Azure
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
```
$ curl -i -H 'Content-Type: application/json' -u <accessKey>:<secretKey> -X POST --data @/opt/rancher/.access_control/access_control_localauth.json http://10.0.x.y:8080/v1/localauthconfig
HTTP/1.1 500 Internal Server Error
Content-Type: application/json; charset=utf-8
Date: Tue, 13 Mar 2018 14:39:11 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Jetty(9.2.11.v20150529)
Set-Cookie: PL=rancher;Path=/
X-Api-Account-Id: 1a1
X-Api-Client-Ip: 172.17.0.1
X-Api-Schemas: http://10.0.x.y:8080/v1/schemas
X-Api-User-Id: 1a1
X-Rancher-Version: v1.6.14
Content-Length: 195

{"id":"9219b67b-0cf1-403c-b3ca-374e2c52a744","type":"error","links":{},"actions":{},"status":500,"code":"Internal Server Error","message":"Internal Server Error","detail":null,"baseType":"error"}
$ cat /opt/rancher/.access_control/access_control_localauth.json
{
  "description": "Access control - localauth",
  "name": "Rancher admin",
  "accessMode":"restricted",
  "enabled":true,
  "username":"<redacted>",
  "password":"<redacted>"
}
```

**Comment by vincent99** [comment]
- Getting all your friends to thumbs up comments doesn't accomplish anything.
- Access control is off, so sending api keys is redundant.
- 500 means there's a stack trace to look at in the server log.  Could be related to the characters in the user/pass.
- Works fine on a fresh container:
```bash
$ curl -v -H 'Content-Type: application/json' -X POST --data @test.json http://localhost:8080/v1/localauthconfig | jq
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> POST /v1/localauthconfig HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 161
>
* upload completely sent off: 161 out of 161 bytes
< HTTP/1.1 201 Created
< Content-Type: application/json; charset=utf-8
< Date: Tue, 13 Mar 2018 21:46:00 GMT
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Server: Jetty(9.2.11.v20150529)
< Set-Cookie: PL=rancher;Path=/
< X-Api-Account-Id: 1a1
< X-Api-Client-Ip: 172.17.0.1
< X-Api-Schemas: http://localhost:8080/v1/schemas
< X-Api-User-Id: 1a1
< X-Rancher-Version: v1.6.14
< Content-Length: 192
<
* Connection #0 to host localhost left intact
{
  "id": null,
  "type": "localAuthConfig",
  "links": {},
  "actions": {},
  "baseType": "localAuthConfig",
  "accessMode": "restricted",
  "enabled": true,
  "name": "Rancher admin",
  "password": "secret",
  "username": "admin"
}

$ cat test.json
{
  "description": "Access control - localauth",
  "name": "Rancher admin",
  "accessMode":"restricted",
  "enabled":true,
  "username":"admin",
  "password":"secret"
}
```

**Comment by bartoszcisek** [comment]
Hey!

Sorry for my foolish thumbs up incident. I looked into logs and found stack trace you mentioned. Let me give a bit more background when this situation occurs: we use `ansible` to deploy rancher and sometimes playbooks need second run. First `ansible` pass enables access control, so second run had it already enabled. That is why access and secret keys were used.  

Strange is that I tried to reproduce the same behavior on my laptop using both 1.6.14 and latest rancher. Unfortunatelly I was _not able_ to get `500` by trying to turn on access control while already being on.  Rancher was retuning `201` as expected.

I definitely get `500` so there is a problem somewhere, i just need some more time to identify where it is ;-)

```
2018-03-23 14:57:37,778 ERROR [:] [] [] [] [p1020391880-347] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [http://10.0.x.y:8080/v1/localauthconfig]. Error id: [0e4dc9dd-9a51-4b58-8938-09a0f619b3fc]. org.jooq.exception.InvalidResultException: Cursor returned more than one result
	at org.jooq.impl.Utils.fetchOne(Utils.java:950)
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:470)
	at org.jooq.impl.SelectImpl.fetchOne(SelectImpl.java:2372)
	at io.cattle.platform.object.impl.JooqObjectManager.findOne(JooqObjectManager.java:351)
	at io.cattle.platform.object.impl.JooqObjectManager.findOne(JooqObjectManager.java:357)
	at io.cattle.platform.core.util.SettingsUtils.changeSetting(SettingsUtils.java:24)
	at io.cattle.platform.iaas.api.auth.integration.local.LocalAuthConfigManager.createInternal(LocalAuthConfigManager.java:52)
	at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.create(AbstractBaseResourceManager.java:115)
	at io.github.ibuildthecloud.gdapi.request.handler.ResourceManagerRequestHandler.generate(ResourceManagerRequestHandler.java:40)
	at io.github.ibuildthecloud.gdapi.request.handler.AbstractResponseGenerator.handle(AbstractResponseGenerator.java:14)
	at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.handle(DefaultReadWriteApiDelegate.java:27)
	at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.write(DefaultReadWriteApiDelegate.java:22)
	at sun.reflect.GeneratedMethodAccessor576.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:280)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy73.write(Unknown Source)
	at io.github.ibuildthecloud.gdapi.request.handler.write.ReadWriteApiHandler.handle(ReadWriteApiHandler.java:19)
	at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:99)
	at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:96)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:106)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```
