### ISSUE TITLE
Rancher-server crash when opening a project in an unprovisioned cluster.

### ISSUE THREAD

**Issue by Dremor** [rancher/rancher#12354]
**Rancher versions:**
rancher/server: v2.0.0-alpha24
rancher/agent: N/A

**Infrastructure Stack versions:**
healthcheck: N/A
ipsec: N/A
network-services: N/A
scheduler: N/A
kubernetes (if applicable): N/A

**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Linux 4.4.0-116-generic (Ubuntu 16.04)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** : Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** : Single-node, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** : Kubernetes

**Steps to Reproduce:**

- Create a new Cluster (without provisioning it)
- Create and open a new project (or open the Default project, it also work)

**Results:**
The whole Rancher server crash.

**Stacktrace**
```
29/03/2018 15:04:07E0329 13:04:07.177939       1 generic_controller.go:204] ClusterRoleTemplateBindingController cluster-gbhds/creator [mgmt-auth-crtb-controller] failed with : couldn't create role cluster-owner: roles.rbac.authorization.k8s.io "cluster-owner" already exists
29/03/2018 15:04:072018/03/29 13:04:07 [INFO] Reconciling RoleTemplates
29/03/2018 15:04:18E0329 13:04:18.158205       1 certificates.go:48] Failed to start certificate controller: error reading CA cert file "/etc/kubernetes/ca/ca.pem": open /etc/kubernetes/ca/ca.pem: no such file or directory
29/03/2018 15:04:18E0329 13:04:18.388067       1 core.go:70] Failed to start service controller: WARNING: no cloud provider provided, services of type LoadBalancer will fail.
29/03/2018 15:04:202018-03-29 13:04:20.370746 W | etcdserver: apply entries took too long [428.953709ms for 1 entries]
29/03/2018 15:04:202018-03-29 13:04:20.370776 W | etcdserver: avoid queries with large range/delete range!
29/03/2018 15:04:39WARNING: 2018/03/29 13:04:39 grpc: addrConn.transportMonitor didn't get server preface after waiting. Closing the new transport now.
29/03/2018 15:09:28panic: runtime error: invalid memory address or nil pointer dereference
29/03/2018 15:09:28[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x171b239]
29/03/2018 15:09:28
29/03/2018 15:09:28goroutine 51199 [running]:
29/03/2018 15:09:28github.com/rancher/rancher/pkg/clustermanager.(*Manager).UserContext(0xc42ec644d0, 0xc42c6fce8d, 0xd, 0xd, 0xc46c3fbd01, 0x3813609)
29/03/2018 15:09:28	/go/src/github.com/rancher/rancher/pkg/clustermanager/manager.go:248 +0x1c9
29/03/2018 15:09:28github.com/rancher/rancher/pkg/api/store/projectsetter.(*transformer).lister(0xc429c80540, 0xc449387200, 0xc42421ca80, 0xc42e20bb80, 0xc434c471a0)
29/03/2018 15:09:28	/go/src/github.com/rancher/rancher/pkg/api/store/projectsetter/store.go:68 +0xe8
29/03/2018 15:09:28github.com/rancher/rancher/pkg/api/store/projectsetter.(*transformer).stream(0xc429c80540, 0xc449387200, 0xc42421ca80, 0xc434c471a0, 0xc43657b800, 0x8000107, 0x0, 0xffffffffffffffff)
29/03/2018 15:09:28	/go/src/github.com/rancher/rancher/pkg/api/store/projectsetter/store.go:47 +0x43
29/03/2018 15:09:28github.com/rancher/rancher/pkg/api/store/projectsetter.(*transformer).(github.com/rancher/rancher/pkg/api/store/projectsetter.stream)-fm(0xc449387200, 0xc42421ca80, 0xc434c471a0, 0xc43657b800, 0xc434c471a0, 0x0, 0x0)
29/03/2018 15:09:28	/go/src/github.com/rancher/rancher/pkg/api/store/projectsetter/store.go:20 +0x52
29/03/2018 15:09:28github.com/rancher/rancher/vendor/github.com/rancher/norman/store/transform.(*Store).Watch(0xc42cb70990, 0xc449387200, 0xc42421ca80, 0xc43657b800, 0x0, 0xc42ea99260, 0x0)
29/03/2018 15:09:28	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/transform/transform.go:47 +0x1dd
29/03/2018 15:09:28github.com/rancher/rancher/vendor/github.com/rancher/norman/store/wrapper.(*StoreWrapper).Watch(0xc42e55b7a0, 0xc449387200, 0xc42421ca80, 0xc43657b800, 0x4c128db, 0x3, 0x0)
29/03/2018 15:09:28	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/wrapper/wrapper.go:45 +0x55
29/03/2018 15:09:28github.com/rancher/rancher/vendor/github.com/rancher/norman/pkg/subscribe.streamStore.func1(0x8, 0x4dd47f0)
29/03/2018 15:09:28	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/pkg/subscribe/handler.go:148 +0xf2
29/03/2018 15:09:28github.com/rancher/rancher/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc42e20b600, 0xc42aa92c40)
29/03/2018 15:09:28	/go/src/github.com/rancher/rancher/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
29/03/2018 15:09:28created by github.com/rancher/rancher/vendor/golang.org/x/sync/errgroup.(*Group).Go
29/03/2018 15:09:28	/go/src/github.com/rancher/rancher/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66
```

**Comment by soumyalj** [comment]
Reproduced the issue in v2.0.0-alpha24. 
Tested with build from master. 
Created a custom/imported cluster without provisioning nodes. 
Navigate to the projects page and opened default project .
There was no server crash and all tabs were operational.
