### ISSUE TITLE
cattle Null pointer exception

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#12856]
**Rancher versions:**
rancher/server: 1.6.17

```
4/19/2018 12:27:42 AM2018-04-19 07:27:42,508 ERROR [11515368-1218-4086-a98d-6a0b9b3a1685:14608] [externalHandler:29] [externalhandler.activate] [] [ecutorService-2] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception java.lang.NullPointerException: null
4/19/2018 12:27:42 AM	at io.cattle.platform.extension.dynamic.process.ExternalHandlerActivate.handle(ExternalHandlerActivate.java:49)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:470)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:421)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:415)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:415)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:517)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:345)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:245)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:242)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:184)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:157)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:116)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:113)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:113)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl.processExecuteWithLock(ProcessInstanceDispatcherImpl.java:136)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl$1.doWithLock(ProcessInstanceDispatcherImpl.java:123)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl$1.doWithLock(ProcessInstanceDispatcherImpl.java:120)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$4.doWithLock(AbstractLockManagerImpl.java:50)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:25)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:47)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl.execute(ProcessInstanceDispatcherImpl.java:120)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.server.ProcessInstanceReference.doRun(ProcessInstanceReference.java:59)
4/19/2018 12:27:42 AM	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15)
4/19/2018 12:27:42 AM	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
4/19/2018 12:27:42 AM	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
4/19/2018 12:27:42 AM	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108)
4/19/2018 12:27:42 AM	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
4/19/2018 12:27:42 AM	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
4/19/2018 12:27:42 AM	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
4/19/2018 12:27:42 AM	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
4/19/2018 12:27:42 AM	at java.lang.Thread.run(Thread.java:745)
4/19/2018 12:27:42 AM
4/19/2018 12:27:42 AM2018-04-19 07:27:42,508 ERROR [0bd0efb0-a2f7-4d70-9b95-176ddd34da7a:14609] [externalHandler:30] [externalhandler.activate] [] [ecutorService-3] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception java.lang.NullPointerException: null
4/19/2018 12:27:42 AM	at io.cattle.platform.extension.dynamic.process.ExternalHandlerActivate.handle(ExternalHandlerActivate.java:49)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:470)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:421)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:415)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:415)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:517)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:345)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:245)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:242)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:184)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:157)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:116)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:113)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:113)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl.processExecuteWithLock(ProcessInstanceDispatcherImpl.java:136)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl$1.doWithLock(ProcessInstanceDispatcherImpl.java:123)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl$1.doWithLock(ProcessInstanceDispatcherImpl.java:120)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$4.doWithLock(AbstractLockManagerImpl.java:50)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:25)
4/19/2018 12:27:42 AM	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:47)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl.execute(ProcessInstanceDispatcherImpl.java:120)
4/19/2018 12:27:42 AM	at io.cattle.platform.engine.server.ProcessInstanceReference.doRun(ProcessInstanceReference.java:59)
4/19/2018 12:27:42 AM	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15)
4/19/2018 12:27:42 AM	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
4/19/2018 12:27:42 AM	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
4/19/2018 12:27:42 AM	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108)
4/19/2018 12:27:42 AM	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
4/19/2018 12:27:42 AM	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
4/19/2018 12:27:42 AM	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
4/19/2018 12:27:42 AM	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
4/19/2018 12:27:42 AM	at java.lang.Thread.run(Thread.java:745)
4/19/2018 12:27:42 AM
```

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
