### ISSUE TITLE
rancher-server crashed with "fatal error: concurrent map iteration and map write"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12979]
**Rancher versions: Build from master - Apr 23
**Steps to Reproduce:**
Created a 1 node DO cluster.
Added few users.
Tried to access project view from UI after the cluster got to "active" state.
Not able to access rancher UI anymore.

rancher-server crashed with "fatal error: concurrent map iteration and map write"

logs:

```
E0423 16:45:33.091612       1 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
2018/04/23 16:46:57 [INFO] Creating new GlobalRoleBinding for GlobalRoleBinding grb-brvxc
2018/04/23 16:47:07 [INFO] Creating new GlobalRoleBinding for GlobalRoleBinding grb-bg74g
2018/04/23 16:47:16 [INFO] Creating new GlobalRoleBinding for GlobalRoleBinding grb-497fh
2018/04/23 16:47:24 [INFO] Creating new GlobalRoleBinding for GlobalRoleBinding grb-5268c
fatal error: concurrent map iteration and map write

goroutine 107391 [running]:
runtime.throw(0x4e906f9, 0x26)
    /usr/local/go/src/runtime/panic.go:605 +0x95 fp=0xc43c7f6ca8 sp=0xc43c7f6c88 pc=0x42ba95
runtime.mapiternext(0xc43c7f6e40)
    /usr/local/go/src/runtime/hashmap.go:778 +0x6f1 fp=0xc43c7f6d40 sp=0xc43c7f6ca8 pc=0x409e21
github.com/rancher/rancher/pkg/broadcast.cloneMap(0xc42c76c240, 0xc43c7f6ef8)
    /go/src/github.com/rancher/rancher/pkg/broadcast/broadcaster.go:88 +0xda fp=0xc43c7f6eb0 sp=0xc43c7f6d40 pc=0x38d61fa
github.com/rancher/rancher/pkg/broadcast.(*Broadcaster).stream(0xc4259a2620, 0xc42d1376e0)
    /go/src/github.com/rancher/rancher/pkg/broadcast/broadcaster.go:63 +0x74 fp=0xc43c7f6fd0 sp=0xc43c7f6eb0 pc=0x38d5ee4
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc43c7f6fd8 sp=0xc43c7f6fd0 pc=0x45ce61
created by github.com/rancher/rancher/pkg/broadcast.(*Broadcaster).start
    /go/src/github.com/rancher/rancher/pkg/broadcast/broadcaster.go:54 +0x79

goroutine 1 [chan receive, 9 minutes]:
github.com/rancher/rancher/app.Run(0xa831180, 0xc4202b5640, 0xc420c66e60, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /go/src/github.com/rancher/rancher/app/app.go:108 +0x24c
main.run(0xab3e438, 0x0, 0x0, 0x4df6883, 0x4, 0x0, 0x0, 0x0, 0x50, 0x1bb, ...)
    /go/src/github.com/rancher/rancher/main.go:143 +0x27d
main.main.func1(0xc42016b4a0, 0xc42016b4a0, 0xc42103b997)
    /go/src/github.com/rancher/rancher/main.go:104 +0xf1
github.com/rancher/rancher/vendor/github.com/urfave/cli.HandleAction(0x414e020, 0xc4205f5300, 0xc42016b4a0, 0xc420ec1500, 0x0)
    /go/src/github.com/rancher/rancher/vendor/github.com/urfave/cli/app.go:502 +0xd2
github.com/rancher/rancher/vendor/github.com/urfave/cli.(*App).Run(0xc4204ae000, 0xc42006e060, 0x3, 0x3, 0x0, 0x0)
    /go/src/github.com/rancher/rancher/vendor/github.com/urfave/cli/app.go:268 +0x653
main.main()
    /go/src/github.com/rancher/rancher/main.go:111 +0x797

goroutine 21 [chan receive]:
github.com/rancher/rancher/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0xab146a0)
    /go/src/github.com/rancher/rancher/vendor/github.com/golang/glog/glog.go:879 +0x9f
created by github.com/rancher/rancher/vendor/github.com/golang/glog.init.0
    /go/src/github.com/rancher/rancher/vendor/github.com/golang/glog/glog.go:410 +0x203

goroutine 3 [syscall, 9 minutes]:
os/signal.signal_recv(0x0)

```

**Comment by sangeethah** [comment]
This issue is not seen anymore when testing with latest builds.
