### ISSUE TITLE
fatal error: concurrent map writes killing rancher server

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#12974]
**Rancher versions:**
master 4/23
**Steps to Reproduce:**
1. add a single node DO cluster
2. go to the workload page of default project.
3. open a new browser tab that goes into the same workload page as well.
3. switch to `loadbalancing` tab of workload pages in these two browser tabs close to the same time.

**Results:**
rancher server stopped and logged a fatal error following with tons of goroutine dumps.
```
2018/04/23 10:22:20 [INFO] namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=project-5pc4q to namespace=cattle-system
fatal error: concurrent map writes

goroutine 5804385 [running]:
runtime.throw(0x4e2f43b, 0x15)
	/usr/local/go/src/runtime/panic.go:605 +0x95 fp=0xc434f2d670 sp=0xc434f2d650 pc=0x42ba95
runtime.mapassign_faststr(0x43ef4c0, 0xc430ef2ea0, 0x4dff992, 0x9, 0xab3dae0)
	/usr/local/go/src/runtime/hashmap_fast.go:685 +0x4da fp=0xc434f2d6f0 sp=0xc434f2d670 pc=0x40ce7a
github.com/rancher/rancher/pkg/api/store/projectsetter.setProjectID(0xa7fd500, 0xc44338d830, 0xc430ef2ea0)
	/go/src/github.com/rancher/rancher/pkg/api/store/projectsetter/store.go:101 +0x1ad fp=0xc434f2d768 sp=0xc434f2d6f0 pc=0x39612dd
github.com/rancher/rancher/pkg/api/store/projectsetter.(*transformer).stream.func1(0xc430ef2ea0, 0xc434f2d7a8)
	/go/src/github.com/rancher/rancher/pkg/api/store/projectsetter/store.go:53 +0x3d fp=0xc434f2d790 sp=0xc434f2d768 pc=0x39613bd
github.com/rancher/rancher/vendor/github.com/rancher/norman/types/convert.Chan.func1(0xc440ae94a0, 0xc447d39d00, 0xc4480767e0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/types/convert/convert.go:21 +0x67 fp=0xc434f2d7c8 sp=0xc434f2d790 pc=0xa66a67
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc434f2d7d0 sp=0xc434f2d7c8 pc=0x45ce61
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/types/convert.Chan
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/types/convert/convert.go:19 +0x7f

goroutine 1 [chan receive, 255 minutes]:
github.com/rancher/rancher/app.Run(0xa82f180, 0xc420f465c0, 0xc420c8d7e0, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rancher/app/app.go:108 +0x24c
main.run(0xab3c438, 0x0, 0x0, 0x4df5763, 0x4, 0x0, 0x0, 0x0, 0x50, 0x1bb, ...)
	/go/src/github.com/rancher/rancher/main.go:143 +0x27d
main.main.func1(0xc4209f38c0, 0xc4209f38c0, 0xc42100d997)
	/go/src/github.com/rancher/rancher/main.go:104 +0xf1
github.com/rancher/rancher/vendor/github.com/urfave/cli.HandleAction(0x414d260, 0xc4206e5f70, 0xc4209f38c0, 0xc420839860, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/urfave/cli/app.go:502 +0xd2
github.com/rancher/rancher/vendor/github.com/urfave/cli.(*App).Run(0xc4205e2c40, 0xc420010090, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/urfave/cli/app.go:268 +0x653
main.main()
	/go/src/github.com/rancher/rancher/main.go:111 +0x797
...
```

**Comment by sangeethah** [comment]
Tested with latest builds from master (Apr 23/24)
This issue is not seen anymore.
