### ISSUE TITLE
Panic when deploying a EKS cluster

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#13091]
**Rancher versions:**
rancher/server: v2.0.0-beta4-rc4

**Steps to Reproduce:**
1. Create a EKS cluster. [Also deployed GKE and Azure container service cluster at the same time.]

The server crashed with a panic below
```

2018/04/25 19:43:25 [ERROR] error updating ns kube-system status: Operation cannot be fulfilled on namespaces "kube-system": the object has been modified; please apply your changes to the latest version and try again
E0425 19:43:25.731993       1 generic_controller.go:204] RoleTemplateController cluster-owner [cluster-roletemplate-sync] failed with : couldn't ensure roles: couldn't create role cluster-owner: clusterroles.rbac.authorization.k8s.io "cluster-owner" already exists
E0425 19:43:25.731993       1 generic_controller.go:204] RoleTemplateController project-owner [cluster-roletemplate-sync] failed with : couldn't ensure roles: couldn't create role project-owner: clusterroles.rbac.authorization.k8s.io "project-owner" already exists
2018/04/25 19:43:25 [ERROR] error updating ns default status: Operation cannot be fulfilled on namespaces "default": the object has been modified; please apply your changes to the latest version and try again
E0425 19:43:25.734764       1 generic_controller.go:204] ClusterRoleTemplateBindingController c-z5fcf/user-spq4m-admin [cluster-crtb-sync] failed with : couldn't ensure roles: couldn't create role cluster-owner: clusterroles.rbac.authorization.k8s.io "cluster-owner" already exists
2018/04/25 19:43:25 [ERROR] error updating ns kube-public status: Operation cannot be fulfilled on namespaces "kube-public": the object has been modified; please apply your changes to the latest version and try again
2018/04/25 19:43:25 [INFO] namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=project-zlwpk to namespace=default
2018/04/25 19:43:43 [INFO] Handling backend connection request [machine-lrmgm]
2018/04/25 19:43:43 [INFO] Handling backend connection request [machine-5n5ff]
2018/04/25 19:43:43 [INFO] Cluster has not yet completed provisioning, waiting another 30 seconds
2018/04/25 19:43:44 [INFO] Handling backend connection request [machine-q9z8c]
2018/04/25 19:43:44 [INFO] Handling backend connection request [c-z5fcf]
2018/04/25 19:43:55 [INFO] Waiting for cluster to finish provisioning
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x141c2d0]

goroutine 42774 [running]:
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/eks.(*Driver).waitForClusterReady(0xc42015d600, 0xc42252ad50, 0x7, 0xc42252ad90, 0xd, 0xc4351e3800, 0x14, 0xc42647bc50, 0x28, 0x0, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go:551 +0x70
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/eks.(*Driver).Create(0xc42015d600, 0xa84d560, 0xc434262d20, 0xc423882760, 0x0, 0xa86d280, 0x46beea0, 0xc434240e01)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go:347 +0x108e
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types.(*GrpcServer).Create(0xc420353e80, 0xa84d560, 0xc434262c60, 0xc42013ae10, 0xc420353e80, 0x1129eb9549b13157, 0xf6dff8c83944d58d)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/rpc_server.go:45 +0x79
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types._Driver_Create_Handler(0x4ad41e0, 0xc420353e80, 0xa84d560, 0xc434262c60, 0xc434240e00, 0x0, 0x0, 0x0, 0x433d64, 0xc433bac480)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/drivers.pb.go:580 +0x276
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4208bd8c0, 0xa862600, 0xc433803b00, 0xc43427c280, 0xc420cd2630, 0xa7f17a0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:921 +0x96e
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4208bd8c0, 0xa862600, 0xc433803b00, 0xc43427c280, 0x0)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:1143 +0x1528
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc423318e70, 0xc4208bd8c0, 0xa862600, 0xc433803b00, 0xc43427c280)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:638 +0x9f
created by github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:636 +0xa1

```

**Comment by soumyalj** [comment]
Tested with rancher version v2.0.0-rc1. Created EKS cluster successfully. Did not see the server crash.
