### ISSUE TITLE
Panic after adding a node to a custom cluster

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#13170]
**Rancher versions:**
rancher/rancher:2.0.0.-rc1

**Steps to Reproduce:**
1. Create a custom cluster using private registry
2. After the cluster comes up, add another custom node with all roles(control, etcd, worker)

Server crashes with the below panic:
```
2018/04/27 18:42:24 [INFO] Updating cluster [c-btrmx]
2018/04/27 18:42:25 [INFO] cluster [c-btrmx] provisioning: Building Kubernetes cluster
2018/04/27 18:42:25 [INFO] cluster [c-btrmx] provisioning: [dialer] Setup tunnel for host [206.189.163.18]
2018/04/27 18:42:25 [INFO] cluster [c-btrmx] provisioning: [dialer] Setup tunnel for host [159.65.37.70]
2018/04/27 18:42:25 [INFO] cluster [c-btrmx] provisioning: [state] Found local kube config file, trying to get state from cluster
2018/04/27 18:42:25 [INFO] cluster [c-btrmx] provisioning: [state] Fetching cluster state from Kubernetes
2018/04/27 18:42:25 [INFO] cluster [c-btrmx] provisioning: [state] Successfully Fetched cluster state to Kubernetes ConfigMap: cluster-state
2018/04/27 18:42:25 [INFO] cluster [c-btrmx] provisioning: [certificates] Getting Cluster certificates from Kubernetes
panic: runtime error: index out of range

goroutine 6967046 [running]:
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.getClusterCerts(0xa8524e0, 0xc447601080, 0xc452c844e0, 0xc449c4d040, 0x2, 0x2, 0x0, 0xc4443d8600, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/certificates.go:134 +0xab7
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.(*Cluster).GetClusterState(0xc4443d8600, 0xa8524e0, 0xc447601080, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/state.go:71 +0x42f
github.com/rancher/rancher/vendor/github.com/rancher/rke/cmd.ClusterUp(0xa8524e0, 0xc447601080, 0xc450815400, 0xc4274001c0, 0xc4274001d0, 0xc455d0c220, 0x0, 0xc450530270, 0x2e, 0x0, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cmd/up.go:71 +0x191
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/rke.(*Driver).Update(0xc420490000, 0xa8524e0, 0xc447601080, 0xc4414f13f0, 0xc455c97c60, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/rke/rke_driver.go:182 +0x268
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types.(*GrpcServer).Update(0xc420152160, 0xa8524e0, 0xc443633bc0, 0xc441142f10, 0xc420152160, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/rpc_server.go:55 +0x79
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types._Driver_Update_Handler(0x4ad72c0, 0xc420152160, 0xa8524e0, 0xc443633bc0, 0xc4530e0230, 0x0, 0x0, 0x0, 0x433d64, 0xc446401200)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/drivers.pb.go:598 +0x276
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc420157760, 0xa867460, 0xc44d1f4a80, 0xc455e5d540, 0xc420a1b410, 0xa7f67b8, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:921 +0x96e
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420157760, 0xa867460, 0xc44d1f4a80, 0xc455e5d540, 0x0)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:1143 +0x1528
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc44c2647e0, 0xc420157760, 0xa867460, 0xc44d1f4a80, 0xc455e5d540)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:638 +0x9f
created by github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:636 +0xa1





```

**Comment by soumyalj** [comment]
Tested with v2.0.0-rc3. Created a single node cluster(all roles) using private registry. After the cluster was created successfully, added another node with all roles. 
The node got added successfully without any panic. Workloads were also created fine.

![screen shot 2018-04-27 at 9 55 04 pm](https://user-images.githubusercontent.com/18536626/39392159-b76aca88-4a65-11e8-843c-851aaa0ae0f0.png)
