### ISSUE TITLE
"java.sql.SQLException: Too many connections" encountered multiple times.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1346]
Server version - Server built from jun 26

When executing tests relating to services,Lb services, DNS services , external_services which involve scenarios like stopping/starting containers , scaling up/scaling down services , activating/deactivating services , there is  "java.sql.SQLException: Too many connections" encountered multiple times.

```
2015-06-26 18:06:23,311 ERROR [:] [] [] [] [utorService-926] [o.a.c.m.context.NoExceptionRunnable ] Uncaught exception org.jooq.exception.DataAccessException: SQL [select `ip_address`.`id`, `ip_address`.`name`, `ip_address`.`account
_id`, `ip_address`.`kind`, `ip_address`.`uuid`, `ip_address`.`description`, `ip_address`.`state`, `ip_address`.`created`, `ip_address`.`removed`, `ip_address`.`remove_time`, `ip_address`.`data`, `ip_address`.`address`, `ip_address`.
`subnet_id`, `ip_address`.`network_id`, `ip_address`.`is_public`, `ip_address`.`role`, `ip_address`.`hostname`, `ip_address`.`ip_pool_id`, `table1_host`.`id` as `table1_id`, `table1_host`.`name` as `table1_name`, `table1_host`.`acco
unt_id` as `table1_account_id`, `table1_host`.`kind` as `table1_kind`, `table1_host`.`uuid` as `table1_uuid`, `table1_host`.`description` as `table1_description`, `table1_host`.`state` as `table1_state`, `table1_host`.`created` as `
table1_created`, `table1_host`.`removed` as `table1_removed`, `table1_host`.`remove_time` as `table1_remove_time`, `table1_host`.`data` as `table1_data`, `table1_host`.`uri` as `table1_uri`, `table1_host`.`compute_free` as `table1_c
ompute_free`, `table1_host`.`compute_total` as `table1_compute_total`, `table1_host`.`agent_id` as `table1_agent_id`, `table1_host`.`zone_id` as `table1_zone_id`, `table1_host`.`physical_host_id` as `table1_physical_host_id`, `table
1_host`.`is_public` as `table1_is_public`, `table1_host`.`agent_state` as `table1_agent_state` from `ip_address` left outer join `host_ip_address_map` on (`ip_address`.`id` = `host_ip_address_map`.`ip_address_id` and `host_ip_addres
s_map`.`removed` is null) left outer join `host` as `table1_host` on `host_ip_address_map`.`host_id` = `table1_host`.`id` where (`ip_address`.`id` = ? and (`ip_address`.`is_public` = true or `ip_address`.`account_id` = ?)) limit ? o
ffset ?]; Too many connections
        at org.jooq.impl.Utils.translate(Utils.java:1287) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:495) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:326) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:330) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.AbstractResultQuery.fetchInto(AbstractResultQuery.java:656) ~[jooq-3.3.0.jar:na]
        at io.cattle.platform.api.resource.jooq.AbstractJooqResourceManager.listInternal(AbstractJooqResourceManager.java:80) ~[cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.api.resource.jooq.AbstractJooqResourceManager.listInternal(AbstractJooqResourceManager.java:54) ~[cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.getByIdInternal(AbstractBaseResourceManager.java:68) ~[gdapi-java-server-0.11.1.1.jar:na]
        at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.getById(AbstractBaseResourceManager.java:61) ~[gdapi-java-server-0.11.1.1.jar:na]
        at io.cattle.platform.iaas.api.change.impl.ResourceChangeEventProcessor.processEvent(ResourceChangeEventProcessor.java:47) ~[cattle-iaas-api-logic-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.api.pubsub.subscribe.NonBlockingSubscriptionHandler.postProcess(NonBlockingSubscriptionHandler.java:113) ~[cattle-framework-api-pub-sub-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.api.pubsub.subscribe.NonBlockingSubscriptionHandler$1.onEvent(NonBlockingSubscriptionHandler.java:91) ~[cattle-framework-api-pub-sub-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Caused by: java.sql.SQLException: Too many connections
        at org.mariadb.jdbc.internal.SQLExceptionMapper.get(SQLExceptionMapper.java:149) ~[mariadb-java-client-1.1.7.jar:na]
        at org.mariadb.jdbc.internal.SQLExceptionMapper.throwException(SQLExceptionMapper.java:106) ~[mariadb-java-client-1.1.7.jar:na]
        at org.mariadb.jdbc.Driver.connect(Driver.java:114) ~[mariadb-java-client-1.1.7.jar:na]
        at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
        at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582) ~[commons-dbcp-1.4.jar:1.4]
        at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1188) ~[commons-pool-1.6.jar:1.6]
        at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106) ~[commons-dbcp-1.4.jar:1.4]
        at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044) ~[commons-dbcp-1.4.jar:1.4]
        at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111) ~[spring-jdbc-3.2.4.RELEASE.jar:3.2.4.RELEASE]
        at org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler.invoke(TransactionAwareDataSourceProxy.java:224) ~[spring-jdbc-3.2.4.RELEASE.jar:3.2.4.RELEASE]
        at com.sun.proxy.$Proxy50.prepareStatement(Unknown Source) ~[na:na]
        at org.jooq.impl.ProviderEnabledConnection.prepareStatement(ProviderEnabledConnection.java:112) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.SettingsEnabledConnection.prepareStatement(SettingsEnabledConnection.java:76) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.AbstractResultQuery.prepare(AbstractResultQuery.java:230) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:296) ~[jooq-3.3.0.jar:na]
        ... 19 common frames omitted
Caused by: org.mariadb.jdbc.internal.common.QueryException: Too many connections
        at org.mariadb.jdbc.internal.mysql.MySQLProtocol.connect(MySQLProtocol.java:398) ~[mariadb-java-client-1.1.7.jar:na]
        at org.mariadb.jdbc.internal.mysql.MySQLProtocol.connect(MySQLProtocol.java:673) ~[mariadb-java-client-1.1.7.jar:na]
        at org.mariadb.jdbc.internal.mysql.MySQLProtocol.<init>(MySQLProtocol.java:266) ~[mariadb-java-client-1.1.7.jar:na]
        at org.mariadb.jdbc.Driver.connect(Driver.java:110) ~[mariadb-java-client-1.1.7.jar:na]
        ... 31 common frames omitted
```

**Comment by will-chan** [comment]
Closed as Obsolete.

**Comment by xaka** [comment]
I'm seeing same error after upgrading from 0.63 to 1.0.
