### ISSUE TITLE
Setting node alert for a host, then delete host causes rancher-server to crash and not recover

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#13605]
I added a cluster alert for an existing node. Then deleted the node to test the alert.  This caused the rancher server to repeatedly crash.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x218 pc=0x191490f]

goroutine 9652 [running]:
github.com/rancher/rancher/pkg/controllers/user/alert/watcher.(*NodeWatcher).checkNodeReady(0xc42e4c4a20, 0xc4235bd698, 0x0)
        /go/src/github.com/rancher/rancher/pkg/controllers/user/alert/watcher/node.go:200 +0x9f
github.com/rancher/rancher/pkg/controllers/user/alert/watcher.(*NodeWatcher).checkNodeCondition(0xc42e4c4a20, 0xc4235bd698, 0x0)
        /go/src/github.com/rancher/rancher/pkg/controllers/user/alert/watcher/node.go:122 +0xaa
github.com/rancher/rancher/pkg/controllers/user/alert/watcher.(*NodeWatcher).watchRule(0xc42e4c4a20, 0xc42e4cd798, 0x6fc23ac01)
        /go/src/github.com/rancher/rancher/pkg/controllers/user/alert/watcher/node.go:83 +0x7a2
github.com/rancher/rancher/pkg/controllers/user/alert/watcher.(*NodeWatcher).watch(0xc42e4c4a20, 0xa85a460, 0xc42e300f40, 0x6fc23ac00)
        /go/src/github.com/rancher/rancher/pkg/controllers/user/alert/watcher/node.go:45 +0xbb
created by github.com/rancher/rancher/pkg/controllers/user/alert/watcher.StartNodeWatcher
        /go/src/github.com/rancher/rancher/pkg/controllers/user/alert/watcher/node.go:40 +0x318
```

**Rancher versions:**
rancher/rancher:v2.0.0

**Setup details:**
HA rancher (rke created management cluster)

**Steps to Reproduce:**
Cluster ->  Tools -> Alerts -> Add alerts

![image](https://user-images.githubusercontent.com/5324639/40256707-ff6a84ee-5ab0-11e8-88f2-230c36fda550.png)

Then from the Cluster -> Nodes screen, I deleted the jgreat-demo2-do-worker4.

This caused rancher server to go into a crash loop.

**Recovery**
Find the clusteralert object that's broken

```
kubectl --kubeconfig=kube_config_cluster.yml get clusteralerts.management.cattle.io --all-namespaces
```

Delete the object

```
kubectl --kubeconfig=kube_config_cluster.yml delete clusteralerts.management.cattle.io <name>
```

**Comment by adingilloRancher** [comment]
Master 6/12/18

Delete nodes assigned to alerts and also scaled down node pool with nodes assigned to alerts. Verified server does not go into a crash loop
