### ISSUE TITLE
Rancher Server/UI stopped responding

### ISSUE THREAD

**Issue by moimael** [rancher/rancher#1375]
I was browsing Rancher UI, stopping/removing/purging several container when everything stopped working (no ui access, ...)

I got this stacktrace : 

```
2015-07-01 13:26:01,392 ERROR [:] [] [] [] [ecutorService-5] [o.a.c.m.context.NoExceptionRunnable ] Uncaught exception org.jooq.exception.DataChangedException: Database record has been changed
	at org.jooq.impl.UpdatableRecordImpl.checkIfChanged(UpdatableRecordImpl.java:550) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.UpdatableRecordImpl.storeUpdate0(UpdatableRecordImpl.java:291) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.UpdatableRecordImpl.access$200(UpdatableRecordImpl.java:90) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.UpdatableRecordImpl$3.operate(UpdatableRecordImpl.java:260) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:123) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.UpdatableRecordImpl.storeUpdate(UpdatableRecordImpl.java:255) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.UpdatableRecordImpl.update(UpdatableRecordImpl.java:149) ~[jooq-3.3.0.jar:na]
	at io.cattle.platform.object.impl.JooqObjectManager.persistRecord(JooqObjectManager.java:216) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.object.impl.JooqObjectManager.setFieldsInternal(JooqObjectManager.java:125) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.object.impl.JooqObjectManager$3.execute(JooqObjectManager.java:113) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.idempotent.Idempotent.change(Idempotent.java:88) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.object.impl.JooqObjectManager.setFields(JooqObjectManager.java:110) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.agent.server.resource.impl.AgentResourcesMonitorImpl.setHosts(AgentResourcesMonitorImpl.java:206) ~[cattle-iaas-agent-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.agent.server.resource.impl.AgentResourcesMonitorImpl$2.doWithLockNoResult(AgentResourcesMonitorImpl.java:125) ~[cattle-iaas-agent-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.agent.server.resource.impl.AgentResourcesMonitorImpl.pingReply(AgentResourcesMonitorImpl.java:116) ~[cattle-iaas-agent-server-0.5.0-SNAPSHOT.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
	at io.cattle.platform.eventing.annotation.MethodInvokingListener$1.doWithLockNoResult(MethodInvokingListener.java:69) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.annotation.MethodInvokingListener.onEvent(MethodInvokingListener.java:65) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]

2015-07-01 13:26:04,244 ERROR [:] [] [] [] [cutorService-13] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [12] count [2] 
time="2015-07-01T13:26:04Z" level=info msg="Registering backend for host [2c8979ad-f968-48eb-ac3f-24cd1da39cf7]" 
2015-07-01 13:26:09,247 ERROR [:] [] [] [] [ecutorService-9] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [12] count [1] 
2015-07-01 13:26:15,786 ERROR [:] [] [] [] [ecutorService-6] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed update [ipsec-hosts, hosts, iptables] on [agent:11], exit code [1] output [INFO: Updating ipsec-hosts
INFO: Removing ipsec-hosts-94-0ae365b7258d2059101719aeca0f6b708bf43153214ab891f171d1b0cb90a8e6
INFO: Downloading http://rancher.alinto.net/v1//configcontent//ipsec-hosts current=ipsec-hosts-103-0ae365b7258d2059101719aeca0f6b708bf43153214ab891f171d1b0cb90a8e6
INFO: Running /var/lib/cattle/download/ipsec-hosts/ipsec-hosts-107-0ae365b7258d2059101719aeca0f6b708bf43153214ab891f171d1b0cb90a8e6/apply.sh
line 13: Family mismatch at [ out ipsec esp/tunnel/172.17.0.8-::ffff:172.17.42.1/require]
parse failed, line 13.
[[scripts.sh:198] docker_env
[[scripts.sh:26] '[' -e /.dockerenv ']'
[[[scripts.sh:27] docker_env_vars
[[[scripts.sh:19] '[' -e /.dockerenv ']'
[[[scripts.sh:20] xargs -0 '-I{}' echo export '"{}"'
[[[scripts.sh:20] grep CATTLE_
[[[scripts.sh:20] cat /proc/1/environ
[[scripts.sh:27] eval export '"CATTLE_CONFIG_URL=http://rancher.alinto.net/v1"' export '"CATTLE_AGENT_INSTANCE_AUTH=Basic' 'NEFFNjJDQTA0NTY5QkJGMjZGRUM6N1hTcVNZZXpvOVdkcHQ3VnlRdUVpMzNrTTRZcEZKS3R0NzZKZ3FLUw=="' export '"CATTLE_HOME=/var/lib/cattle"'
[[[scripts.sh:27] export CATTLE_CONFIG_URL=http://rancher.alinto.net/v1 export 'CATTLE_AGENT_INSTANCE_AUTH=Basic NEFFNjJDQTA0NTY5QkJGMjZGRUM6N1hTcVNZZXpvOVdkcHQ3VnlRdUVpMzNrTTRZcEZKS3R0NzZKZ3FLUw==' export CATTLE_HOME=/var/lib/cattle
[[[scripts.sh:27] CATTLE_CONFIG_URL=http://rancher.alinto.net/v1
[[[scripts.sh:27] CATTLE_AGENT_INSTANCE_AUTH='Basic NEFFNjJDQTA0NTY5QkJGMjZGRUM6N1hTcVNZZXpvOVdkcHQ3VnlRdUVpMzNrTTRZcEZKS3R0NzZKZ3FLUw=='
[[[scripts.sh:27] CATTLE_HOME=/var/lib/cattle
[[scripts.sh:199] script_env
[[scripts.sh:123] '[' -n http://rancher.alinto.net/v1 ']'
[[scripts.sh:124] return
[[scripts.sh:201] export CATTLE_HOME=/var/lib/cattle
[[scripts.sh:201] CATTLE_HOME=/var/lib/cattle
[[scripts.sh:202] export CATTLE_CONFIG_URL=http://rancher.alinto.net/v1
[[scripts.sh:202] CATTLE_CONFIG_URL=http://rancher.alinto.net/v1
[[scripts.sh:203] export CATTLE_STORAGE_URL=
[[scripts.sh:203] CATTLE_STORAGE_URL=
[apply.sh:5] ARPDEV=arpproxy
[apply.sh:6] IFACE=eth0
[[apply.sh:7] ifconfig eth0
[[apply.sh:7] grep 'inet addr:'
[[apply.sh:7] awk '{print $2}'
[[apply.sh:7] cut -f2 -d:
[apply.sh:7] IP=172.17.0.8
[apply.sh:19] create_dummy
[apply.sh:11] ip link show dev arpproxy
[[apply.sh:15] ip link show dev eth0
[[apply.sh:15] sed -n 's/.*mtu \([0-9][0-9]*\).*/\1/p'
[apply.sh:15] MTU=1500
[apply.sh:16] ip link set dev arpproxy mtu 1500 up
[apply.sh:20] add_route_table 200 'iif eth0'
[scripts.sh:174] local id=200
[scripts.sh:175] local 'opts=iif eth0'
[scripts.sh:176] cut -f1 -d:
[scripts.sh:176] grep -q '^200$'
[scripts.sh:176] ip rule show
[apply.sh:22] sed -i s/%HOST_IP%/172.17.0.8/g content-home/etc/cattle/setkey
[apply.sh:24] apply_config ip -batch etc/cattle/ipsec-tunnel-routes
[scripts.sh:161] local file=etc/cattle/ipsec-tunnel-routes
[scripts.sh:162] local 'cmd=ip -batch'
[scripts.sh:164] ip -batch content-home/etc/cattle/ipsec-tunnel-routes
[apply.sh:25] apply_config /usr/sbin/setkey -f etc/cattle/setkey
[scripts.sh:161] local file=etc/cattle/setkey
[scripts.sh:162] local 'cmd=/usr/sbin/setkey -f'
[scripts.sh:164] /usr/sbin/setkey -f content-home/etc/cattle/setkey
line 13: Family mismatch at [ out ipsec esp/tunnel/172.17.0.8-::ffff:172.17.42.1/require]
parse failed, line 13.
[scripts.sh:165] '[' -e /var/lib/cattle/etc/cattle/setkey ']'
[scripts.sh:166] /usr/sbin/setkey -f /var/lib/cattle/etc/cattle/setkey
[scripts.sh:168] return 1
```

**Comment by cjellick** [comment]
Hi @moimael. Seems like you might have multiple problems here.

We'll investigate those stacktraces, but on the surface, I don't think the should have caused Rancher to completely stop working). I know it has been awhile now, but did the rancher/server container stop running?

Could you hit the api? If so, you should get a json response when you run `curl http:/you-hostname-here/v1`

**Comment by moimael** [comment]
Hi @cjellick,

Now my rancher cluster is up and running, I seems to hit some random issues when upgrading RancherOS or Rancher and this is one of them.

I can't help you to further investigate since I can't reproduce it right now. 

I think rancher/server stopped running. It looked like the process crashed.

Thanks !

**Comment by cjellick** [comment]
Ok @moimael , thanks for the quick response and let us know if it happens again.

**Comment by cjellick** [comment]
Leaving this issue until we investigate the stacktraces
