### ISSUE TITLE
Unable to use an ElasticSearch server with https/SSL enabled

### ISSUE THREAD

**Issue by dxxxxxg** [rancher/rancher#13760]
unable to use an ElasticSearch server with https/SSL enabled due certificate not trusted error. We need to be able to add the CA.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`` `admin`|
|Route|`global-admin.clusters.index`|

**Comment by dxxxxxg** [comment]
Here's the log:
2018-05-22 15:09:18 +0000 [warn]: #0 failed to flush the buffer. retry_time=8 next_retry_seconds=2018-05-22 15:09:49 +0000 chunk="56cccbb673775d4d7a263e21c4aab7b1" error_class=Faraday::SSLError err            or="SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError) Unable to verify certificate. This may be an issue with the remote host or with Excon. Excon has c            ertificates bundled, but these can be customized:\n\n            `Excon.defaults[:ssl_ca_path] = path_to_certs`\n            `ENV['SSL_CERT_DIR'] = path_to_certs`\n            `Excon.defaults[:ssl_            ca_file] = path_to_file`\n            `ENV['SSL_CERT_FILE'] = path_to_file`\n            `Excon.defaults[:ssl_verify_callback] = callback`\n                (see OpenSSL::SSL::SSLContext#verify_call            back)\nor:\n            `Excon.defaults[:ssl_verify_peer] = false` (less secure).\n"
  2018-05-22 15:09:18 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/excon-0.62.0/lib/excon/ssl_socket.rb:125:in `connect'
  2018-05-22 15:09:18 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/excon-0.62.0/lib/excon/ssl_socket.rb:125:in `initialize'
  2018-05-22 15:09:18 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/excon-0.62.0/lib/excon/connection.rb:429:in `new'
  2018-05-22 15:09:18 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/excon-0.62.0/lib/excon/connection.rb:429:in `socket'
  2018-05-22 15:09:18 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/excon-0.62.0/lib/excon/connection.rb:111:in `request_call'
  2018-05-22 15:09:18 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/excon-0.62.0/lib/excon/middlewares/mock.rb:48:in `request_call'
  2018-05-22 15:09:18 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/excon-0.62.0/lib/excon/middlewares/instrumentor.rb:26:in `request_call'
  2018-05-22 15:09:18 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:16:in `request_call'
  2018-05-22 15:09:18 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:16:in `request_call'
  2018-05-22 15:09:18 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:16:in `request_call'
  2018-05-22 15:09:18 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/excon-0.62.0/lib/excon/connection.rb:260:in `request'
  2018-05-22 15:09:18 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/faraday-0.15.0/lib/faraday/adapter/excon.rb:49:in `call'
  2018-05-22 15:09:18 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/faraday-0.15.0/lib/faraday/rack_builder.rb:143:in `build_response'
  2018-05-22 15:09:18 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/faraday-0.15.0/lib/faraday/connection.rb:387:in `run_request'
  2018-05-22 15:09:18 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/elasticsearch-transport-6.0.2/lib/elasticsearch/transport/transport/http/faraday.rb:23:in `block in perform_request'
  2018-05-22 15:09:18 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/elasticsearch-transport-6.0.2/lib/elasticsearch/transport/transport/base.rb:266:in `perform_request'
  2018-05-22 15:09:18 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/elasticsearch-transport-6.0.2/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2018-05-22 15:09:18 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/elasticsearch-transport-6.0.2/lib/elasticsearch/transport/client.rb:131:in `perform_request'
  2018-05-22 15:09:18 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/elasticsearch-api-6.0.2/lib/elasticsearch/api/actions/ping.rb:20:in `ping'
  2018-05-22 15:09:18 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-2.9.0/lib/fluent/plugin/out_elasticsearch.rb:245:in `client'
  2018-05-22 15:09:18 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-2.9.0/lib/fluent/plugin/out_elasticsearch.rb:497:in `rescue in send_bulk'
  2018-05-22 15:09:18 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-2.9.0/lib/fluent/plugin/out_elasticsearch.rb:494:in `send_bulk'
  2018-05-22 15:09:18 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-2.9.0/lib/fluent/plugin/out_elasticsearch.rb:397:in `write'
  2018-05-22 15:09:18 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/plugin/output.rb:1093:in `try_flush'
  2018-05-22 15:09:18 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/plugin/output.rb:1318:in `flush_thread_run'
  2018-05-22 15:09:18 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
  2018-05-22 15:09:18 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.25/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'

**Comment by OBenned** [comment]
This is probally the same as i mentioned earlier #13065 
So either we need to able to add the CA or set the ssl_verify flag, preferably both

**Comment by aiwantaozi** [comment]
Thanks guys, we will support SSL soon

**Comment by bmdepesa** [comment]
rancher/rancher:master 9/10

Connection over HTTPS to elasticsearch is successful. 

* Setup ES cluster
* Enabled TLS on transport / http layers with self-signed cert
* Enable ES logging w/ https endpoint & x-pack security
* Connection is successful & logs are sent successfully
