### ISSUE TITLE
Panic when removing IP's from ingress

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#13767]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.17
rancher/agent or rancher/rancher-agent: 1.2.10

**Infrastructure Stack versions:**
kubernetes (if applicable): 1.9.5-rancher1-3
ingress controller image: rancher/lb-service-rancher:v0.7.17

time="2018-05-28T22:39:04Z" level=info msg="Updating ingress default/someingress Removing IP 172.16.22.11" 
panic: runtime error: slice bounds out of range

goroutine 90 [running]:
github.com/rancher/lb-controller/controller/kubernetes.(*loadBalancerController).updateIngressStatus(0xc420024960, 0xc4200193c0, 0x32)
    /go/src/github.com/rancher/lb-controller/controller/kubernetes/kubernetes.go:329 +0xbd7
github.com/rancher/lb-controller/controller/kubernetes.(*loadBalancerController).(github.com/rancher/lb-controller/controller/kubernetes.updateIngressStatus)-fm(0xc4200193c0, 0x32)
    /go/src/github.com/rancher/lb-controller/controller/kubernetes/kubernetes.go:147 +0x3e
github.com/rancher/lb-controller/utils.(*TaskQueue).worker(0xc4200c5c60)
    /go/src/github.com/rancher/lb-controller/utils/utils.go:64 +0xd8
github.com/rancher/lb-controller/utils.(*TaskQueue).(github.com/rancher/lb-controller/utils.worker)-fm()
    /go/src/github.com/rancher/lb-controller/utils/utils.go:33 +0x2a
github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc4201e27a8)
    /go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:84 +0x25
github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc42078bfa8, 0x3b9aca00, 0x0, 0x1, 0xc4200e4660)
    /go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:85 +0xad
github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.Until(0xc4201e27a8, 0x3b9aca00, 0xc4200e4660)
    /go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x4d
github.com/rancher/lb-controller/utils.(*TaskQueue).Run(0xc4200c5c60, 0x3b9aca00, 0xc4200e4660)
    /go/src/github.com/rancher/lb-controller/utils/utils.go:33 +0x5e
created by github.com/rancher/lb-controller/controller/kubernetes.(*loadBalancerController).Run
    /go/src/github.com/rancher/lb-controller/controller/kubernetes/kubernetes.go:394 +0x1c6
+ curl -s -f http://rancher-metadata/2015-12-19/stacks/Kubernetes/services/kubernetes/uuid
+ /usr/bin/update-rancher-ssl
++ curl -s http://rancher-metadata/2015-12-19/stacks/Kubernetes/services/kubernetes/uuid
+ UUID=64cd6741-87cb-4150-b16e-cc7da3dd0770
++ curl -s -u D9AECE8E36F5628625B3:xEK55xP1tLmKupYNTCwv9QbELD53yTSjxrYN3ntK 'http://rancher_host:8080/v1/services?uuid=64cd6741-87cb-4150-b16e-cc7da3dd0770'
++ jq -r '.data[0].actions.certificate'
+ ACTION='http://rancher_host:8080/v1/services/1s38/?action=certificate'
+ KUBERNETES_URL=https://kubernetes.kubernetes.rancher.internal:6443```

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
