### ISSUE TITLE
Unknown exception running process - Can't start containers

### ISSUE THREAD

**Issue by haswalt** [rancher/rancher#1379]
When trying to start a new container on a host the container never starts and the following logs are constantly output:

# Server

```
2015-07-02 09:08:05,846 ERROR [:] [] [] [] [cutorService-22] [i.c.p.e.e.i.ProcessEventListenerImpl] Unknown exception running process [instance.start:36] on [1] java.lang.IllegalArgumentException: Invalid path string "/cattle/locks/59/206/DOCKER.STORAGE_POOL.VOLUME.CREATE.1.file:///var/lib/docker/volumes/6ff0e5a73f59c13956584d1d5e648fb674039c9702ad794559b353cf9193ca02/_data" caused by empty node name specified @63
	at org.apache.curator.utils.PathUtils.validatePath(PathUtils.java:101) ~[curator-client-2.3.0.jar:na]
	at org.apache.curator.framework.recipes.locks.LockInternals.<init>(LockInternals.java:103) ~[curator-recipes-2.3.0.jar:na]
	at org.apache.curator.framework.recipes.locks.InterProcessMutex.<init>(InterProcessMutex.java:190) ~[curator-recipes-2.3.0.jar:na]
	at org.apache.curator.framework.recipes.locks.InterProcessMutex.<init>(InterProcessMutex.java:64) ~[curator-recipes-2.3.0.jar:na]
	at io.cattle.platform.zookeeper.lock.ZookeeperLockProvider.getLock(ZookeeperLockProvider.java:38) ~[cattle-zookeeper-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.zookeeper.lock.ZookeeperLockProvider.createLock(ZookeeperLockProvider.java:27) ~[cattle-zookeeper-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.provider.impl.AbstractStandardLockProvider.getLock(AbstractStandardLockProvider.java:37) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.getLock(LockManagerImpl.java:66) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:23) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.docker.process.instancehostmap.DockerPostInstanceHostMapActivate.createVolumeInStoragePool(DockerPostInstanceHostMapActivate.java:193) ~[cattle-docker-compute-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.docker.process.instancehostmap.DockerPostInstanceHostMapActivate.processVolumes(DockerPostInstanceHostMapActivate.java:171) ~[cattle-docker-compute-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.docker.process.instancehostmap.DockerPostInstanceHostMapActivate.handle(DockerPostInstanceHostMapActivate.java:113) ~[cattle-docker-compute-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:455) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:395) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:389) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:389) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:522) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:322) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:258) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:255) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:188) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:161) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:110) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:107) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:107) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.executeStandardProcess(DefaultObjectProcessManager.java:29) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.common.handler.AbstractObjectProcessLogic.activate(AbstractObjectProcessLogic.java:31) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.instance.InstanceStart.compute(InstanceStart.java:179) ~[cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.instance.InstanceStart.handle(InstanceStart.java:72) ~[cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:455) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:395) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:389) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:389) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:519) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:322) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:258) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:255) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:188) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:161) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:110) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:107) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:107) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.eventing.impl.ProcessEventListenerImpl.processExecute(ProcessEventListenerImpl.java:66) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at sun.reflect.GeneratedMethodAccessor516.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
	at io.cattle.platform.eventing.annotation.MethodInvokingListener$1.doWithLockNoResult(MethodInvokingListener.java:69) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.annotation.MethodInvokingListener.onEvent(MethodInvokingListener.java:65) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
```

## Rancher version:

```
Rancher	v0.25.0
Cattle	v0.58.0
User Interface	v0.29.0
Rancher Compose	latest
```

## docker info

```
Containers: 1
Images: 29
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 31
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-52-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 490 MiB
```

```
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

The server and node are running on Digital Ocean using their docker images with swap and memory limits enabled. I've tested other docker machines and they start fine when started manually with the docker CLI.

The network agent appears to be created and started fine but the container gets stuck at "Starting" until it times out.

There are messages about container being locked on the host so we get sequential start, start, start die events repeated.

This was done on a fresh install with multiple nodes to test this issue. tested using a manually created host machine and one autocreated using the Digital Ocean API. Both nodes are hosted on Digital Ocean

Each node has 512MB and 1GB RAM with equivalent swap available.

**Comment by haswalt** [comment]
This is what the agent does upon create/start container:

```
2015-07-02 10:01:58,156 ERROR docker [140205506878192] [delegate.py:126] Can not call [682d7e22-80eb-491f-b210-82dfc3995384], container is not running
time="2015-07-02T10:01:58Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"7cf99f8b2c0016653b8e414bafdce78abbcb7cda7e73a16c7393b0a4d8ae054a\", From:\"rancher/agent-instance:v0.3.1\", Time:1435831318}"
time="2015-07-02T10:01:58Z" level="info" msg="Assigning IP [10.42.112.236/16], ContainerId [7cf99f8b2c0016653b8e414bafdce78abbcb7cda7e73a16c7393b0a4d8ae054a], Pid [23068]"
time="2015-07-02T10:01:58Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"7cf99f8b2c0016653b8e414bafdce78abbcb7cda7e73a16c7393b0a4d8ae054a\", From:\"-simulated-\", Time:0}"
time="2015-07-02T10:01:58Z" level="info" msg="Container locked. Can't run StartHandler. ID: [7cf99f8b2c0016653b8e414bafdce78abbcb7cda7e73a16c7393b0a4d8ae054a]"
time="2015-07-02T10:02:58Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"c06127e00fb78b583a687809d9bc0e9b3b9233e0a66717fb06679b1f3890e43f\", From:\"ghost:latest\", Time:1435831378}"
time="2015-07-02T10:02:58Z" level="info" msg="Assigning IP [10.42.159.210/16], ContainerId [c06127e00fb78b583a687809d9bc0e9b3b9233e0a66717fb06679b1f3890e43f], Pid [24825]"
time="2015-07-02T10:02:58Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"c06127e00fb78b583a687809d9bc0e9b3b9233e0a66717fb06679b1f3890e43f\", From:\"-simulated-\", Time:0}"
time="2015-07-02T10:02:58Z" level="info" msg="Container locked. Can't run StartHandler. ID: [c06127e00fb78b583a687809d9bc0e9b3b9233e0a66717fb06679b1f3890e43f]"
time="2015-07-02T10:03:06Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"c06127e00fb78b583a687809d9bc0e9b3b9233e0a66717fb06679b1f3890e43f\", From:\"-simulated-\", Time:0}"
```

This is then repeated until the eventual fail

```
time="2015-07-02T10:07:36Z" level="info" msg="Assigning IP [10.42.159.210/16], ContainerId [c06127e00fb78b583a687809d9bc0e9b3b9233e0a66717fb06679b1f3890e43f], Pid [24825]"
time="2015-07-02T10:08:06Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"c06127e00fb78b583a687809d9bc0e9b3b9233e0a66717fb06679b1f3890e43f\", From:\"-simulated-\", Time:0}"
```

**Comment by haswalt** [comment]
A basic image of ubuntu:14.04 will start correctly however attempting to start a container of mysql, ghost or wordpress all eventually fail

**Comment by haswalt** [comment]
FYI tested using a manually created host machine and one autocreated using the Digital Ocean API. Both nodes are hosted on Digital Ocean

**Comment by deniseschannon** [comment]
Could you provide the exact command you used to start rancher server and when you did the manually created host? I see that you mention memory and swap limits, so I would like to test using the same limits.

**Comment by haswalt** [comment]
@deniseschannon I'm running a multi-node setup so you'll see a load of private ips configured but here is the command for starting rancher server

```
docker run -d --restart=always -p 8080:8080 \
    -e CATTLE_DB_CATTLE_MYSQL_HOST=10.131.151.219 \
    -e CATTLE_DB_CATTLE_MYSQL_PORT=3306 \
    -e CATTLE_DB_CATTLE_MYSQL_NAME=cattle \
    -e CATTLE_DB_CATTLE_USERNAME=cattle \
    -e CATTLE_DB_CATTLE_PASSWORD=<password>\
    -e CATTLE_ZOOKEEPER_CONNECTION_STRING=10.131.151.221 \
    -e CATTLE_REDIS_HOSTS=10.131.151.220 \
    rancher/server:latest
```

For the agent on the custom machine:

```
docker run -d --privileged -e CATTLE_AGENT_IP=46.101.29.19
 -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.7.9 http://10.131.152.4:8080/v1/scripts/5D1CB8F8C1D5DA116679:1435752000000:wb9zLIj4XCeRyXDCwpUdKDqMY
```

Both machines i'm currently connected as root, the other host node is created by rancher itself using the Digital Ocean API. When I say swap and cpu limits I mean enabling these features in the kernel as per the docker docs:  https://docs.docker.com/installation/ubuntulinux/#adjust-memory-and-swap-accounting

**Comment by cloudnautique** [comment]
@haswalt, our documentation for the multi-node setup is a bit out of date. We are working through the setup again including how to configure the websocket-proxy in a multinode(ha) setup. 

We introduced a proxy for the hosts to connect to, instead of us reaching out to every node. This provides a few benefits, one of which is easier SSL termination, but it also means you don't need to open up the TCP ports on the compute nodes. By default these proxies are running inside the rancher-server container. We are working on documenting the new way to run these servers. 

I'm assuming you are running two rancher-servers behind a LB? Are you seeing your nodes drop in and out of active/registering?

**Comment by haswalt** [comment]
@cloudnautique Currently I'm running a single rancher server whilst i'm testing it. full setup is

Zookeeper single node
Redis single node
Rancher server single node
Rancher host 2 nodes
Web facing Load balance single node

All the machines can talk over their private networks to each other. The LB is proxying web traffic and any web service traffic to the rancher server.

Any ideas when the docs will be updated or any pointers for this? Happy to test stuff out whilst i'm at it.

**Comment by cloudnautique** [comment]
Interesting, it looks like this issue has to do with our system creating a lock in Zookeeper. Do you have the container you are trying to run command? I'd like to try and reproduce.

**Comment by haswalt** [comment]
Nothing special. Just try any of the ones on docker hub that require network it seems. 

I've tried ghost, Wordpress, redis and MySQL

**Comment by cloudnautique** [comment]
OK. Will take a look. Thank you.

**Comment by haswalt** [comment]
This is fixed for me using rc3 and now container boot correctly

**Comment by amalagaura** [comment]
I am running into this same issue with the latest Rancher and a latest docker

Getting these in the agent log when trying to start a container from Rancher: `Container locked. Can't run StartHandler`

> Component	Version
> Rancher	v0.44.0
> Cattle	v0.107.0
> User Interface	v0.65.0
> Rancher Compose	v0.5.1

docker version: Docker version 1.9.0, build 76d6bc9
