### ISSUE TITLE
when creating app in catalog, get some problems about api

### ISSUE THREAD

**Issue by jianzi123** [rancher/rancher#13811]
**Rancher versions:**
rancher/server or rancher/rancher: `rancher version v2.0.0`
rancher/agent or rancher/rancher-agent: `rancher-agent v2.0.0`

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

```
Client:
Version:      1.13.1
API version:  1.26
Go version:   go1.6.2
Git commit:   092cba3
Built:        Thu Nov  2 20:40:23 2017
OS/Arch:      linux/amd64

Server:
Version:      1.13.1
API version:  1.26 (minimum version 1.12)
Go version:   go1.6.2
Git commit:   092cba3
Built:        Thu Nov  2 20:40:23 2017
OS/Arch:      linux/amd64
Experimental: false
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
`VMware`
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
`single node rancher`
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
`Kubernetes`
**Steps to Reproduce:**

**Results:**
```
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
k8s.io/helm/pkg/strvals.(*parser).listItem(0xc4207b3798, 0xc42063c1e0, 0x3, 0x3, 0x0, 0x1, 0x5b, 0x0, 0x0, 0x0)
        /home/darren/.gpath/3ef6bc96094c0cb608fe5ee0babfa6c6abd39686/src/k8s.io/helm/pkg/strvals/parser.go:226 +0xf71
k8s.io/helm/pkg/strvals.(*parser).key(0xc4207b3798, 0xc42074bb60, 0x0, 0x0)
        /home/darren/.gpath/3ef6bc96094c0cb608fe5ee0babfa6c6abd39686/src/k8s.io/helm/pkg/strvals/parser.go:120 +0xbe7
k8s.io/helm/pkg/strvals.(*parser).parse(0xc4207b3798, 0xc4205baa80, 0x2c0)
        /home/darren/.gpath/3ef6bc96094c0cb608fe5ee0babfa6c6abd39686/src/k8s.io/helm/pkg/strvals/parser.go:76 +0x38
k8s.io/helm/pkg/strvals.ParseInto(0x7ffcd70c3a65, 0x2c0, 0xc42074bb60, 0x0, 0xc42074bb60)
        /home/darren/.gpath/3ef6bc96094c0cb608fe5ee0babfa6c6abd39686/src/k8s.io/helm/pkg/strvals/parser.go:60 +0xb9
main.vals(0x0, 0x0, 0x0, 0xc4202817b0, 0x1, 0x1, 0x7fb5885086c8, 0x29ff960, 0x7fb5885086c8, 0x0, ...)
        /home/darren/.gpath/3ef6bc96094c0cb608fe5ee0babfa6c6abd39686/src/k8s.io/helm/cmd/helm/install.go:353 +0x45b
main.(*templateCmd).run(0xc4205ae3c0, 0xc4203f86c0, 0xc42072c150, 0x1, 0x7, 0x0, 0x0)
        /home/darren/.gpath/3ef6bc96094c0cb608fe5ee0babfa6c6abd39686/src/k8s.io/helm/cmd/helm/template.go:152 +0x620
main.(*templateCmd).(main.run)-fm(0xc4203f86c0, 0xc42072c150, 0x1, 0x7, 0x0, 0x0)
        /home/darren/.gpath/3ef6bc96094c0cb608fe5ee0babfa6c6abd39686/src/k8s.io/helm/cmd/helm/template.go:89 +0x52
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).execute(0xc4203f86c0, 0xc42072c0e0, 0x7, 0x7, 0xc4203f86c0, 0xc42072c0e0)
        /home/darren/.gpath/3ef6bc96094c0cb608fe5ee0babfa6c6abd39686/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:599 +0x3e8
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42033efc0, 0xc4203f86c0, 0xc4203f9440, 0xc4203f98c0)
        /home/darren/.gpath/3ef6bc96094c0cb608fe5ee0babfa6c6abd39686/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:689 +0x2fe
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42033efc0, 0x8, 0x8)
        /home/darren/.gpath/3ef6bc96094c0cb608fe5ee0babfa6c6abd39686/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
        /home/darren/.gpath/3ef6bc96094c0cb608fe5ee0babfa6c6abd39686/src/k8s.io/helm/cmd/helm/helm.go:159 +0x75
: exit status 2  appid="*****:*****" cluster=**** code=200 namespace=****
```

**Comment by jianzi123** [comment]
when creating app in catalog, we get api from rancher 
`/v3/project/c-8nlwv:p-nhggc/apps/p-nhggc:glusterfs-****`
we get `conditions` in up api and 
```
"conditions": [
{
"lastUpdateTime": "*****",
"Reason": "error",
"status": "False",
"type": "Installed"
}
],
```
but finally the app was installed and we get 
```
"conditions": [
{
"lastUpdateTime": "2018-06-01T06:56:26Z",
"status": "True",
"type": "Installed"
}
],
```
