### ISSUE TITLE
Network Agent stuck in "starting" state when trying to restart the Network agent from rancher UI.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1406]
rancher/server:v0.26.0-rc1

Steps to reproduce the problem:
Had a set up with 3 hosts.
Had few Lb rules on one of the hosts.
Lb rule was not able to redirect traffic to containers in other host . So i tried to restart the network agent on this host.

This resulted in the host itself getting into "reconnecting" state and then get back to "up" state.
The Network agent remains stuck in "starting" state.

docker command (docker ps) hangs on this host now.

agent logs:
```
2015-07-06 19:54:35,437 INFO agent [139830458470224] [utils.py:424] worker23 : Starting request 082e48e4-c601-44c2-a4f5-c72f9a1fa721 for compute.instance.activate 
2015-07-06 19:54:35,688 INFO agent [139830458470224] [utils.py:424] worker23 : Done request 082e48e4-c601-44c2-a4f5-c72f9a1fa721 for compute.instance.activate [0.250898838043] seconds 
2015-07-06 19:54:35,688 INFO agent [139830458470224] [event.py:103] Failed to lock [instance-5] for compute.instance.activate 
2015-07-06 19:54:36,440 INFO agent [139830458467344] [utils.py:424] Request: {"id":"aa2b461c-c08b-4120-a200-587daca4b6ff","name":"delegate.request","replyTo":"reply.2187627961564214010","resourceId":null,"resourceType":null,"pu
blisher":null,"transitioning":null,"transitioningMessage":null,"transitioningInternalMessage":null,"previousIds":null,"previousNames":null,"data":{"instanceData":{"domain":null,"description":null,"token":"P1m9PUiOx63EWGfSr6jIwL
gLqzMu5z7b8c8rNChDjagHo4BXo0AHzPMiCAJikzyLzR6tFnTZCSeyyQN8VZg","data":{"fields":{"imageUuid":"docker:rancher/agent-instance:v0.3.1","networkIds":[],"vnetIds":[2],"privileged":true,"transitioningMessage":"Post-network","transiti
oningProgress":95,"dockerHostIp":"104.154.41.99","dockerIp":"172.17.0.4","dockerPorts":{"4500/udp":"4500","500/udp":"500"},"primaryIpAddress":"10.42.171.46"},"ipsec":{"1":{"isakmp":500,"nat":4500}},"dockerInspect":{"State":{"Pi
d":4916,"OOMKilled":false,"Dead":false,"Paused":false,"Running":true,"FinishedAt":"0001-01-01T00:00:00Z","Restarting":false,"Error":"","StartedAt":"2015-07-06T15:37:28.817026873Z","ExitCode":0},"Config":{"PortSpecs":null,"Hostn
ame":"5abb0acb407e","Entrypoint":null,"Env":["CATTLE_CONFIG_URL=http://104.154.63.20:8080/v1","CATTLE_AGENT_INSTANCE_AUTH=Basic NEYwRDgzREIwMkNFMDY4QTYyQUE6TFBkZW9MSnVwZkpMQ0VvaEo0RUpGdDRndEJhNTY0cUptcjN3cDltUw==","HOME=/","PAT
H=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Memory":0,"OnBuild":null,"OpenStdin":false,"MacAddress":"02:4e:fb:2b:2c:19","Cpuset":"","User":"","VolumeDriver":"","AttachStderr":false,"AttachStdout":false,"Ne
tworkDisabled":false,"WorkingDir":"","Cmd":["/etc/init.d/agent-instance-startup","init"],"StdinOnce":false,"AttachStdin":false,"Volumes":{},"MemorySwap":0,"Tty":false,"CpuShares":0,"Domainname":"","Image":"rancher/agent-instanc
e:v0.3.1","Labels":{"io.rancher.container.system":"NetworkAgent","io.rancher.container.uuid":"338ca195-6050-4b67-90ff-3cd61f3e5d00","io.rancher.container.ip":"10.42.171.46/16"},"ExposedPorts":{"4500/udp":{},"500/udp":{}}},"Host
sPath":"/var/lib/docker/containers/5abb0acb407e1dc880f86fcf8375d89330b3cf81b0b79e1584031a209f360b25/hosts","Args":["init"],"Driver":"aufs","ExecDriver":"native-0.2","Path":"/etc/init.d/agent-instance-startup","HostnamePath":"/v
ar/lib/docker/containers/5abb0acb407e1dc880f86fcf8375d89330b3cf81b0b79e1584031a209f360b25/hostname","VolumesRW":{},"RestartCount":0,"Name":"/338ca195-6050-4b67-90ff-3cd61f3e5d00","Created":"2015-07-06T15:37:26.551628087Z","Reso
lvConfPath":"/var/lib/docker/containers/5abb0acb407e1dc880f86fcf8375d89330b3cf81b0b79e1584031a209f360b25/resolv.conf","Volumes":{},"ExecIDs":null,"ProcessLabel":"","NetworkSettings":{"NetworkID":"0921837c9ff045092fb03185b914eb1
8f7838997c88fb619a64f1b377d901e9b","Bridge":"","GlobalIPv6PrefixLen":0,"LinkLocalIPv6Address":"","HairpinMode":false,"IPv6Gateway":"","SecondaryIPAddresses":null,"PortMapping":null,"GlobalIPv6Address":"","LinkLocalIPv6PrefixLen
":0,"EndpointID":"f891461911c004e4cbce42f301c60842c492a457cc2de057d21794354e19b6b3","SandboxKey":"/var/run/docker/netns/5abb0acb407e","MacAddress":"02:4e:fb:2b:2c:19","SecondaryIPv6Addresses":null,"IPPrefixLen":16,"IPAddress":"
172.17.0.4","Gateway":"172.17.42.1","Ports":{"4500/udp":[{"HostPort":"4500","HostIp":"0.0.0.0"}],"500/udp":[{"HostPort":"500","HostIp":"0.0.0.0"}]}},"AppArmorProfile":"","Image":"3b0ebcadd8a7ee5a9b4ef203f14337853acdd5294592f00d
a6e52fe78341dd65","LogPath":"/var/lib/docker/containers/5abb0acb407e1dc880f86fcf8375d89330b3cf81b0b79e1584031a209f360b25/5abb0acb407e1dc880f86fcf8375d89330b3cf81b0b79e1584031a209f360b25-json.log","HostConfig":{"CpuPeriod":0,"Co
ntainerIDFile":"","CpusetMems":"","Dns":null,"Memory":0,"DnsSearch":null,"Privileged":true,"Ulimits":null,"CpusetCpus":"","PidMode":"","CgroupParent":"","BlkioWeight":0,"RestartPolicy":{"MaximumRetryCount":0,"Name":""},"Publish
AllPorts":false,"ReadonlyRootfs":false,"CpuShares":0,"OomKillDisable":false,"NetworkMode":"bridge","LxcConf":null,"Devices":null,"Binds":null,"CpuQuota":0,"MemorySwap":0,"UTSMode":"","ExtraHosts":null,"VolumesFrom":null,"CapDro
p":null,"Links":null,"IpcMode":"","PortBindings":{"4500/udp":[{"HostPort":"4500","HostIp":"0.0.0.0"}],"500/udp":[{"HostPort":"500","HostIp":"0.0.0.0"}]},"SecurityOpt":null,"CapAdd":null,"LogConfig":{"Config":{},"Type":"json-fil
e"}},"MountLabel":"","Id":"5abb0acb407e1dc880f86fcf8375d89330b3cf81b0b79e1584031a209f360b25"},"dockerContainer":{"Status":"Up Less than a second","Created":1436197046,"Image":"rancher/agent-instance:v0.3.1","Labels":{"io.ranche
r.container.system":"NetworkAgent","io.rancher.container.uuid":"338ca195-6050-4b67-90ff-3cd61f3e5d00","io.rancher.container.ip":"10.42.171.46/16"},"Ports":[{"IP":"0.0.0.0","Type":"udp","PublicPort":4500,"PrivatePort":4500},{"IP
":"0.0.0.0","Type":"udp","PublicPort":500,"PrivatePort":500}],"Command":"/etc/init.d/agent-instance-startup init","Names":["/338ca195-6050-4b67-90ff-3cd61f3e5d00"],"Id":"5abb0acb407e1dc880f86fcf8375d89330b3cf81b0b79e1584031a209
f360b25"}},"created":1436197017000,"name":"Network Agent","id":5,"state":"running","kind":"container","removed":null,"startCount":null,"hostname":null,"uuid":"338ca195-6050-4b67-90ff-3cd61f3e5d00","imageId":5,"memoryMb":null,"u
serdata":null,"offeringId":null,"firstRunning":1436197049000,"compute":null,"externalId":"5abb0acb407e1dc880f86fcf8375d89330b3cf81b0b79e1584031a209f360b25","instanceTriggeredStop":"restart","zoneId":1,"accountId":5,"healthState
":null,"systemContainer":"NetworkAgent","agentId":5,"allocationState":"active","nativeContainer":false,"networkContainerId":null,"registryCredentialId":null,"removeTime":null},"event":{"id":"bb829ba9-3543-42f1-b830-45d67296b52a
","name":"config.update","replyTo":"config.update.reply","resourceId":"5","resourceType":"agent","publisher":null,"transitioning":null,"transitioningMessage":null,"transitioningInternalMessage":null,"previousIds":null,"previous
Names":null,"data":{"configUrl":"http://172.17.0.1:8080/v1","items":[{"name":"agent-instance-startup","requestedVersion":3,"apply":true,"increment":true,"checkInSyncOnly":false}]},"time":1436212460089,"timeoutMillis":2000,"tran
sitioningProgress":null,"context":{"processId":"14121","logicPath":"instance.start->(AgentInstanceInstanceStart)","logicName":"AgentInstanceInstanceStart","prettyResource":"instance:5","processName":"instance.start","topResourc
eType":"instance","resouceId":"5","resouceType":"instance","prettyProcess":"instance.start","topProcessName":"instance.start","topResourceId":"5","processUuid":"ccd58d88-628d-4dd6-b0fa-63018e590bb7"}}},"time":1436212476420,"tim
eoutMillis":2000,"transitioningProgress":null,"context":{"processId":"14121","logicPath":"instance.start->(AgentInstanceInstanceStart)","logicName":"AgentInstanceInstanceStart","prettyResource":"instance:5","processName":"insta
nce.start","topResourceType":"instance","resouceId":"5","resouceType":"instance","prettyProcess":"instance.start","topProcessName":"instance.start","topResourceId":"5","processUuid":"ccd58d88-628d-4dd6-b0fa-63018e590bb7"}} 
2015-07-06 19:54:36,440 INFO agent [139830458467344] [utils.py:424] worker27 : Starting request aa2b461c-c08b-4120-a200-587daca4b6ff for delegate.request 
2015-07-06 19:54:37,142 INFO agent [139830458457136] [event.py:189] Dropping request {"id":"b5cbf448-42a3-4727-928c-8c01be07a3ad","name":"ping","replyTo":"reply.3888660928027072102","resourceId":"1a1","resourceType":"agent","pu
blisher":null,"transitioning":null,"transitioningMessage":null,"transitioningInternalMessage":null,"previousIds":null,"previousNames":null,"data":{"options":{"instances":true},"resources":[]},"time":1436212477131,"timeoutMillis
":5000,"transitioningProgress":null,"context":null} 
2015-07-06 19:54:37,143 ERROR agent [139830458457136] [event.py:197] Max dropped requests [10] exceeded 
2015-07-06 19:54:43,424 INFO process-manager [140605988108400] [process_manager.py:65] Launching ['/var/lib/cattle/pyagent/cattle/process_watcher.sh'] 
2015-07-06 19:54:43,426 INFO process-manager [140605988108400] [process_manager.py:68] Launched ['/var/lib/cattle/pyagent/cattle/process_watcher.sh'] as pid 15255 
2015-07-06 19:54:43,428 INFO agent [140605988108400] [__init__.py:15] Loading Plugin: docker from /var/lib/cattle/pyagent/cattle/plugins 
2015-07-06 19:55:43,453 ERROR docker [140605988108400] [__init__.py:101] Disabling docker, could not contact docker 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/__init__.py", line 99, in <module>
    docker_client().info()
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 730, in info
    return self._result(self._get(self._url("/info")),
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 106, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
2015-07-06 19:55:43,454 ERROR agent [140605988108400] [__init__.py:20] Exception loading module 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/plugins/__init__.py", line 18, in _load
    return imp.load_module(std_name, m[0], m[1], m[2])
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/__init__.py", line 119, in <module>
    raise Exception('Failed to initialize Docker')
Exception: Failed to initialize Docker
2015-07-06 19:55:43,455 INFO agent [140605988108400] [__init__.py:15] Loading Plugin: cadvisor from /var/lib/cattle/pyagent/cattle/plugins 
2015-07-06 19:55:43,455 INFO agent [140605988108400] [__init__.py:15] Loading Plugin: volmgr from /var/lib/cattle/pyagent/cattle/plugins 
2015-07-06 19:55:43,457 INFO agent [140605988108400] [__init__.py:15] Loading Plugin: host_info from /var/lib/cattle/pyagent/cattle/plugins 
2015-07-06 19:55:43,457 INFO agent [140605988108400] [__init__.py:15] Loading Plugin: host-api from /var/lib/cattle/pyagent/cattle/plugins 
2015-07-06 19:56:43,462 ERROR docker [140605988108400] [__init__.py:101] Disabling docker, could not contact docker 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/__init__.py", line 99, in <module>
    docker_client().info()
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 730, in info
    return self._result(self._get(self._url("/info")),
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 106, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
2015-07-06 19:56:43,463 ERROR agent [140605988108400] [__init__.py:20] Exception loading module 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/plugins/__init__.py", line 18, in _load
    return imp.load_module(std_name, m[0], m[1], m[2])
  File "/var/lib/cattle/pyagent/cattle/plugins/host-api/__init__.py", line 3, in <module>
    from .host_api import HostApi
  File "/var/lib/cattle/pyagent/cattle/plugins/host-api/host_api.py", line 2, in <module>
    from cattle.plugins.docker import DockerConfig
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/__init__.py", line 119, in <module>
    raise Exception('Failed to initialize Docker')
Exception: Failed to initialize Docker
2015-07-06 19:56:43,463 INFO agent [140605988108400] [main.py:91] API URL http://104.154.63.20:8080/v1 
2015-07-06 19:56:43,464 INFO agent [140605988108400] [main.py:97] Subscribing to ['ping', 'config.update', 'storage.snapshot.backup', 'storage.snapshot.create', 'storage.snapshot.remove'] 
2015-07-06 19:56:43,464 INFO process-manager [140605988108400] [process_manager.py:65] Launching ['cadvisor.sh', 'cadvisor', '-logtostderr=true', '-listen_ip', '127.0.0.1', '-port', '9344'] 
2015-07-06 19:56:43,467 INFO process-manager [140605988108400] [process_manager.py:68] Launched ['cadvisor.sh', 'cadvisor', '-logtostderr=true', '-listen_ip', '127.0.0.1', '-port', '9344'] as pid 15353 
2015-07-06 19:56:43,469 INFO requests.packages.urllib3.connectionpool [140605966969904] [connectionpool.py:203] Starting new HTTP connection (1): 104.154.63.20 
2015-07-06 19:56:45,499 INFO requests.packages.urllib3.connectionpool [140605966286352] [connectionpool.py:203] Starting new HTTP connection (1): 104.154.63.20 
```

**Comment by will-chan** [comment]
Obsolete.  File a new issue if this is happening with 0.59+.
