### ISSUE TITLE
 Encountered "Uncaught exception java.lang.OutOfMemoryError: Direct buffer memory" and hosts get stuck in "reconnecting" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1408]
rancher/server:v0.26.0-rc1

Steps to reproduce the problem:
Had a set up with 3 hosts.
I was in the process of deleting many containers when I hit the following exception and the UI would not refresh all. 

```
2015-07-06 23:53:46,739 INFO  [:] [] [] [] [utorService-302] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [instance.purge:18220] on resource [497] 
2015-07-06 23:53:46,740 INFO  [:] [] [] [] [utorService-302] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [PROCESS_ALREADY_IN_PROGRESS] process [instance.purge:18220] on resource [497] 
2015-07-06 23:53:46,742 INFO  [:] [] [] [] [utorService-283] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [volume.purge:18441] on resource [765] 
2015-07-06 23:53:46,743 INFO  [cdae283f-ce1d-4255-a44f-4a55a4d7c12c:18425] [volume:739] [volume.purge->(VolumePurge)] [] [utorService-274] [c.p.e.p.i.DefaultProcessInstanceImpl] Running handler [VolumePurge] 
2015-07-06 23:53:46,744 INFO  [:] [] [] [] [utorService-341] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [instance.purge:18194] on resource [403] 
2015-07-06 23:53:46,744 INFO  [:] [] [] [] [utorService-341] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [PROCESS_ALREADY_IN_PROGRESS] process [instance.purge:18194] on resource [403] 
2015-07-06 23:53:46,746 DEBUG [e4e20e8c-6f86-4a5b-bc7f-de728940e100:18127] [instance:282->nic:282] [instance.stop->(InstanceStop)->nic.deactivate->(AgentInstanceApplyItems)] [] [orService-10684] [i.c.p.e.memory.InMemoryEventService ] Unsubscribing from [reply.3961563517661789841] 
2015-07-06 23:53:46,746 DEBUG [e4e20e8c-6f86-4a5b-bc7f-de728940e100:18127] [instance:282->nic:282] [instance.stop->(InstanceStop)->nic.deactivate->(AgentInstanceApplyItems)] [] [orService-10684] [i.c.p.e.memory.InMemoryEventService ] Subscribing to [reply.9007809057649471972] 
2015-07-06 23:53:46,749 INFO  [5ffdb3b8-88c8-491a-8f99-c75bf593f935:18423] [volume:735] [volume.purge->(VolumePurge)] [] [cutorService-90] [c.p.e.p.i.DefaultProcessInstanceImpl] Running handler [VolumePurge] 
2015-07-06 23:53:46,730 INFO  [:] [] [] [] [torService-8331] [i.c.p.a.s.s.impl.AgentServiceImpl   ] Timeout waiting for response to [config.update] id [8fbe2443-4aa6-4f06-aabe-cce9a202022d] 
2015-07-06 23:53:46,097 INFO  [:] [] [] [] [utorService-269] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [volume.purge:18445] on resource [777] 
2015-07-06 23:53:46,096 ERROR [b646a121-a4ee-4f4c-9d0d-3d86a8ba1aee:18203] [instance:480] [instance.purge->(PostInstancePurge)] [] [torService-9202] [o.a.c.m.context.NoExceptionRunnable ] Uncaught exception java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:658) ~[na:1.7.0_79]
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123) ~[na:1.7.0_79]
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:306) ~[na:1.7.0_79]
	at sun.nio.ch.Util.getTemporaryDirectBuffer(Util.java:174) ~[na:1.7.0_79]
	at sun.nio.ch.IOUtil.write(IOUtil.java:58) ~[na:1.7.0_79]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:487) ~[na:1.7.0_79]
	at org.eclipse.jetty.io.nio.ChannelEndPoint.flush(ChannelEndPoint.java:310) ~[na:na]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.flush(SelectChannelEndPoint.java:402) ~[na:na]
	at org.eclipse.jetty.io.nio.ChannelEndPoint.flush(ChannelEndPoint.java:346) ~[na:na]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.flush(SelectChannelEndPoint.java:376) ~[na:na]
	at org.eclipse.jetty.http.HttpGenerator.flushBuffer(HttpGenerator.java:841) ~[na:na]
	at org.eclipse.jetty.http.AbstractGenerator.blockForOutput(AbstractGenerator.java:523) ~[na:na]
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:170) ~[na:na]
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:117) ~[na:na]
	at io.cattle.platform.api.pubsub.subscribe.OutputStreamMessageWriter.write(OutputStreamMessageWriter.java:32) ~[cattle-framework-api-pub-sub-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.pubsub.subscribe.NonBlockingSubscriptionHandler.write(NonBlockingSubscriptionHandler.java:147) ~[cattle-framework-api-pub-sub-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.pubsub.subscribe.NonBlockingSubscriptionHandler.write(NonBlockingSubscriptionHandler.java:143) ~[cattle-framework-api-pub-sub-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.pubsub.subscribe.NonBlockingSubscriptionHandler$1.onEvent(NonBlockingSubscriptionHandler.java:94) ~[cattle-framework-api-pub-sub-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]

2015-07-06 23:53:46,093 DEBUG [e4e20e8c-6f86-4a5b-bc7f-de728940e100:18127] [instance:282->nic:282] [instance.stop->(InstanceStop)->nic.deactivate->(AgentInstanceApplyItems)] [] [orService-12103] [i.c.p.e.memory.InMemoryEventService ] Subscribing to [reply.6637530976030019153] 
2015-07-06 23:53:46,092 INFO  [:] [] [] [] [utorService-356] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [volume.purge:18421] on resource [733] 
2015-07-06 23:53:46,752 INFO  [:] [] [] [] [utorService-356] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [PROCESS_ALREADY_IN_PROGRESS] process [volume.purge:18421] on resource [733] 
2015-07-06 23:53:46,091 INFO  [:] [] [] [] [utorService-359] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [volume.purge:18430] on resource [746] 
2015-07-06 23:53:46,752 INFO  [:] [] [] [] [utorService-359] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [PROCESS_ALREADY_IN_PROGRESS] process [volume.purge:18430] on resource [746] 
2015-07-06 23:53:46,090 INFO  [:] [] [] [] [utorService-246] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [instance.purge:18201] on resource [464] 
2015-07-06 23:53:46,752 INFO  [:] [] [] [] [utorService-246] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [PROCESS_ALREADY_IN_PROGRESS] process [instance.purge:18201] on resource [464] 
2015-07-06 23:53:46,086 INFO  [:] [] [] [] [utorService-191] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [volume.purge:18424] on resource [738] 
2015-07-06 23:53:46,752 INFO  [:] [] [] [] [utorService-191] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [PROCESS_ALREADY_IN_PROGRESS] process [volume.purge:18424] on resource [738] 
2015-07-06 23:53:46,084 INFO  [:] [] [] [] [utorService-238] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [volumestoragepoolmap.purge:18453] on resource [118] 
2015-07-06 23:53:46,079 INFO  [:] [] [] [] [utorService-241] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [volume.purge:18434] on resource [755] 
2015-07-06 23:53:46,752 INFO  [:] [] [] [] [utorService-241] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [PROCESS_ALREADY_IN_PROGRESS] process [volume.purge:18434] on resource [755] 
2015-07-06 23:53:46,078 INFO  [:] [] [] [] [utorService-255] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [instance.remove:18447] on resource [227] 
2015-07-06 23:53:46,077 INFO  [:] [] [] [] [utorService-309] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [volume.purge:18431] on resource [747] 
2015-07-06 23:53:46,753 INFO  [:] [] [] [] [utorService-309] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [PROCESS_ALREADY_IN_PROGRESS] process [volume.purge:18431] on resource [747] 
2015-07-06 23:53:46,077 INFO  [:] [] [] [] [utorService-281] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [instance.purge:18209] on resource [486] 
2015-07-06 23:53:46,753 INFO  [:] [] [] [] [utorService-281] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [PROCESS_ALREADY_IN_PROGRESS] process [instance.purge:18209] on resource [486] 
2015-07-06 23:53:46,077 DEBUG [90b9c2de-9e14-4371-a603-4cba015f4539:18527] [instance:189] [instance.purge->(PostInstancePurge)] [] [cutorService-25] [i.c.p.e.memory.InMemoryEventService ] Subscribing to [reply.2600077883383018896] 
2015-07-06 23:53:46,075 INFO  [c3687294-85c2-4575-8cdd-007e7609106c:18537] [instance:208->instanceHostMap:208] [instance.purge->(InstancePurge)->instance.deallocate->(InstanceDeallocate)->instancehostmap.remove] [] [utorService-330] [c.p.e.p.i.DefaultProcessInstanceImpl] Changing state [removing->removed] on [instanceHostMap:208] 
2015-07-06 23:53:46,759 INFO  [9917189d-1c97-42fc-b4a9-39402121cdce:18529] [instance:194] [instance.purge->(InstancePurge)->instance.deallocate->(InstanceDeallocate)] [] [torService-9696] [c.p.a.e.i.AllocatorEventListenerImpl] Deallocator [SimpleAllocator] handled request [AllocationRequest [type=INSTANCE, resource=194]] 
2015-07-06 23:53:46,772 INFO  [:] [] [] [] [utorService-219] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [volume.purge:18420] on resource [730] 
2015-07-06 23:53:46,772 INFO  [:] [] [] [] [utorService-219] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [PROCESS_ALREADY_IN_PROGRESS] process [volume.purge:18420] on resource [730] 
2015-07-06 23:53:46,773 DEBUG [33c0dfd0-0d5b-436e-a72b-85c90c8e19fb:18528] [instance:193] [instance.purge->(PostInstancePurge)] [] [utorService-156] [i.c.p.e.memory.InMemoryEventService ] Subscribing to [reply.2691186976123170286] 
2015-07-06 23:53:46,775 INFO  [:] [] [] [] [utorService-240] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [volume.purge:18438] on resource [759] 
2015-07-06 23:53:46,775 INFO  [:] [] [] [] [utorService-240] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [PROCESS_ALREADY_IN_PROGRESS] process [volume.purge:18438] on resource [759] 
2015-07-06 23:53:46,781 INFO  [c3687294-85c2-4575-8cdd-007e7609106c:18537] [instance:208] [instance.purge->(InstancePurge)->instance.deallocate->(InstanceDeallocate)] [] [utorService-330] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [DONE] process [instancehostmap.remove:null] on resource [208] 
2015-07-06 23:53:46,781 INFO  [c3687294-85c2-4575-8cdd-007e7609106c:18537] [instance:208] [instance.purge->(InstancePurge)->instance.deallocate->(InstanceDeallocate)] [] [utorService-330] [c.p.e.p.i.DefaultProcessInstanceImpl] Finished handler [InstanceDeallocate] 
2015-07-06 23:53:46,785 INFO  [:] [] [] [] [utorService-326] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [volumestoragepoolmap.purge:18457] on resource [119] 
2015-07-06 23:53:46,786 INFO  [:] [] [] [] [utorService-299] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [volume.purge:18444] on resource [775] 
2015-07-06 23:53:46,786 INFO  [:] [] [] [] [utorService-320] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [containerevent.create:18458] on resource [2106] 
2015-07-06 23:53:46,787 INFO  [:] [] [] [] [utorService-297] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [volume.purge:18442] on resource [766] 
2015-07-06 23:53:46,790 INFO  [:] [] [] [] [utorService-138] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [volume.purge:18435] on resource [756] 
2015-07-06 23:53:46,790 INFO  [:] [] [] [] [utorService-138] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [PROCESS_ALREADY_IN_PROGRESS] process [volume.purge:18435] on resource [756] 
2015-07-06 23:53:46,796 INFO  [5ffdb3b8-88c8-491a-8f99-c75bf593f935:18423] [volume:735] [volume.purge->(VolumePurge)] [] [cutorService-90] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [volume.deallocate:null] on resource [735] 
2015-07-06 23:53:46,796 INFO  [cdae283f-ce1d-4255-a44f-4a55a4d7c12c:18425] [volume:739] [volume.purge->(VolumePurge)] [] [utorService-274] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [volume.deallocate:null] on resource [739] 
2015-07-06 23:53:46,804 INFO  [:] [] [] [] [utorService-239] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [volume.purge:18439] on resource [763] 
2015-07-06 23:53:46,807 INFO  [:] [] [] [] [utorService-199] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [volume.purge:18443] on resource [774] 
2015-07-06 23:53:46,825 INFO  [:] [] [] [] [utorService-286] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [volume.purge:18440] on resource [764] 
2015-07-06 23:53:46,827 INFO  [9917189d-1c97-42fc-b4a9-39402121cdce:18529] [instance:194] [instance.purge->(InstancePurge)->instance.deallocate->(InstanceDeallocate)] [] [utorService-277] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [instancehostmap.remove:null] on resource [194] 
2015-07-06 23:53:46,828 INFO  [:] [] [] [] [utorService-358] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [volume.purge:18437] on resource [758] 
2015-07-06 23:53:46,818 INFO  [:] [] [] [] [utorService-344] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [volume.purge:18436] on resource [757] 
2015-07-06 23:53:46,818 INFO  [81dd0c9b-ffa6-4180-b09f-11eaad38ae0f:18519] [instance:164->instanceHostMap:164] [instance.purge->(InstancePurge)->instance.deallocate->(InstanceDeallocate)->instancehostmap.remove->(SetRemovedFields)] [] [utorService-270] [c.p.e.p.i.DefaultProcessInstanceImpl] Running post listener [SetRemovedFields] 
2015-07-06 23:53:46,836 INFO  [81dd0c9b-ffa6-4180-b09f-11eaad38ae0f:18519] [instance:164->instanceHostMap:164] [instance.purge->(InstancePurge)->instance.deallocate->(InstanceDeallocate)->instancehostmap.remove->(SetRemovedFields)] [] [utorService-270] [c.p.e.p.i.DefaultProcessInstanceImpl] Finished post listener [SetRemovedFields] 
2015-07-06 23:53:46,831 INFO  [df8bca08-4565-4811-9ce3-eaac18c09b5c:18562] [ipAddress:344] [ipaddress.purge] [] [ecutorService-5] [c.p.e.p.i.DefaultProcessInstanceImpl] Changing state [removed->purging] on [ipAddress:344] 
2015-07-06 23:53:46,837 INFO  [df8bca08-4565-4811-9ce3-eaac18c09b5c:18562] [ipAddress:344] [ipaddress.purge] [] [ecutorService-5] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting with code [SCHEDULED] : SCHEDULED 
2015-07-06 23:53:46,840 INFO  [7b8351f2-8861-4b2e-89d5-6e87c5b1ec52:18455] [containerEvent:2105] [containerevent.create->(ContainerEventPreCreate)] [] [utorService-313] [c.p.e.p.i.DefaultProcessInstanceImpl] Finished pre listener [ContainerEventPreCreate] 
2015-07-06 23:53:46,841 INFO  [:] [] [] [] [utorService-358] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [PROCESS_ALREADY_IN_PROGRESS] process [volume.purge:18437] on resource [758] 
2015-07-06 23:53:46,843 INFO  [:] [] [] [] [utorService-303] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [containerevent.create:18462] on resource [2111] 
2015-07-06 23:53:46,845 INFO  [:] [] [] [] [utorService-344] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [PROCESS_ALREADY_IN_PROGRESS] process [volume.purge:18436] on resource [757] 
2015-07-06 23:53:46,851 INFO  [445088e8-79de-4bb5-a253-be177aab3c1a:18447] [instance:227] [instance.remove->(ServiceDiscoveryInstanceRemovePreListener)] [] [utorService-255] [c.p.e.p.i.DefaultProcessInstanceImpl] Running pre listener [ServiceDiscoveryInstanceRemovePreListener] 
2015-07-06 23:53:46,852 INFO  [445088e8-79de-4bb5-a253-be177aab3c1a:18447] [instance:227] [instance.remove->(ServiceDiscoveryInstanceRemovePreListener)] [] [utorService-255] [c.p.e.p.i.DefaultProcessInstanceImpl] Finished pre listener [ServiceDiscoveryInstanceRemovePreListener] 
2015-07-06 23:53:46,861 INFO  [:] [] [] [] [utorService-252] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [containerevent.create:18464] on resource [2110] 
2015-07-06 23:53:46,867 ERROR [4134d338-7a28-47ab-b175-60e3940b74f3:18533] [instance:200] [instance.purge->(PostInstancePurge)] [] [torService-8355] [o.a.c.m.context.NoExceptionRunnable ] Uncaught exception java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:658) ~[na:1.7.0_79]
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123) ~[na:1.7.0_79]
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:306) ~[na:1.7.0_79]
	at sun.nio.ch.Util.getTemporaryDirectBuffer(Util.java:174) ~[na:1.7.0_79]
	at sun.nio.ch.IOUtil.write(IOUtil.java:58) ~[na:1.7.0_79]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:487) ~[na:1.7.0_79]
	at org.eclipse.jetty.io.nio.ChannelEndPoint.flush(ChannelEndPoint.java:310) ~[na:na]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.flush(SelectChannelEndPoint.java:402) ~[na:na]
	at org.eclipse.jetty.http.HttpGenerator.flushBuffer(HttpGenerator.java:853) ~[na:na]
	at org.eclipse.jetty.http.AbstractGenerator.blockForOutput(AbstractGenerator.java:523) ~[na:na]
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:147) ~[na:na]
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:117) ~[na:na]
	at io.cattle.platform.api.pubsub.subscribe.OutputStreamMessageWriter.write(OutputStreamMessageWriter.java:32) ~[cattle-framework-api-pub-sub-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.pubsub.subscribe.NonBlockingSubscriptionHandler.write(NonBlockingSubscriptionHandler.java:147) ~[cattle-framework-api-pub-sub-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.pubsub.subscribe.NonBlockingSubscriptionHandler.write(NonBlockingSubscriptionHandler.java:143) ~[cattle-framework-api-pub-sub-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.pubsub.subscribe.NonBlockingSubscriptionHandler$1.onEvent(NonBlockingSubscriptionHandler.java:94) ~[cattle-framework-api-pub-sub-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]

```
After a while UI responds successfully.But I see all the agents being stuck in "Reconnecting" state 
<img width="996" alt="screen shot 2015-07-06 at 4 59 56 pm" src="https://cloud.githubusercontent.com/assets/4266958/8536016/85a06b54-2400-11e5-93de-5381714c3e81.png">

**Comment by ibuildthecloud** [comment]
This issue happens because of a blocking operation on a websocket that then creates a bazillion threads when there is backpressure and then we have no more memory.  So I think we shouldn't create a bazillion threads :)

**Comment by cjellick** [comment]
@ibuildthecloud what do you mean by a blocking operation on a websocket?

**Comment by sangeethah** [comment]
I see the same issue happen again when testing with server version - V0.27.0-rc4.

**Comment by sangeethah** [comment]
I encounter the same issue when testing with server version - V0.28.0-rc1 

I attempted to run test cases in 5 parallel threads. For while tests are working as expected. After this when i see tests failing , I notice that following exception in the logs:

2015-07-20 17:30:11,302 ERROR [:] [] [] [] [orService-12306] [o.a.c.m.context.NoExceptionRunnable ] Uncaught exception java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:658) ~[na:1.7.0_79]
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123) ~[na:1.7.0_79]
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:306) ~[na:1.7.0_79]
	at org.eclipse.jetty.io.nio.DirectNIOBuffer.<init>(DirectNIOBuffer.java:51) ~[na:na]
	at org.eclipse.jetty.io.AbstractBuffers.newHeader(AbstractBuffers.java:73) ~[na:na]
	at org.eclipse.jetty.io.ThreadLocalBuffers.getHeader(ThreadLocalBuffers.java:85) ~[na:na]
	at org.eclipse.jetty.websocket.WebSocketBuffers.getDirectBuffer(WebSocketBuffers.java:53) ~[na:na]
	at org.eclipse.jetty.websocket.WebSocketGeneratorRFC6455.addFrame(WebSocketGeneratorRFC6455.java:77) ~[na:na]
	at org.eclipse.jetty.websocket.WebSocketConnectionRFC6455$WSFrameConnection.sendMessage(WebSocketConnectionRFC6455.java:439) ~[na:na]
	at io.cattle.platform.api.pubsub.subscribe.jetty.WebSocketMessageWriter.write(WebSocketMessageWriter.java:34) ~[cattle-framework-api-pub-sub-jetty-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.pubsub.subscribe.NonBlockingSubscriptionHandler.write(NonBlockingSubscriptionHandler.java:147) ~[cattle-framework-api-pub-sub-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.pubsub.subscribe.NonBlockingSubscriptionHandler.write(NonBlockingSubscriptionHandler.java:143) ~[cattle-framework-api-pub-sub-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.pubsub.subscribe.NonBlockingSubscriptionHandler$2.run(NonBlockingSubscriptionHandler.java:182) ~[cattle-framework-api-pub-sub-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.async.retry.impl.RetryTimeoutServiceImpl$1$1.doRun(RetryTimeoutServiceImpl.java:63) ~[cattle-framework-async-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.async.retry.impl.RetryTimeoutServiceImpl$1.run(RetryTimeoutServiceImpl.java:59) [cattle-framework-async-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]


After this I am not able to access the rancher server using the UI, I see this message "waiting for available socket" and the connection never errors out.
My test client seems to not progress after this point.

**Comment by sangeethah** [comment]
Tested with v0.32.0-rc1.
I have not seen this issue when testing with rancher-server being up for couple of days. I have tried running tests with similar setups as before and am not seeing this issue anymore.
