### ISSUE TITLE
Pipeline fails when multiple steps in single stage

### ISSUE THREAD

**Issue by KaelBaldwin** [rancher/rancher#14172]
**Rancher versions:**
rancher/server or rancher/rancher: rancher/rancher (v2.0.2)
rancher/agent or rancher/rancher-agent: rancher/rancher-agent

**Infrastructure Stack versions:**
healthcheck: 
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

Not sure how to check all of the above, I just did a standard rancher/rancher:latest deploy.

**Docker version: (`docker version`,`docker info` preferred)**

```
Containers: 37
 Running: 27
 Paused: 0
 Stopped: 10
Images: 243
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 591
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-127-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.826 GiB
Name: KaelBuntu
ID: RVNY:CHH2:OIZH:F7SN:LHFU:SLQV:AYQM:NZJX:G2LP:VHP5:IER4:2SI3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
4.4.0-127-generic

NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
I think this would be Kubernetes with rancher 2.0?

**Steps to Reproduce:**

1. Create a new pipeline
2. Select Required Fields for Add Repository step, shouldn't matter.
3. For the build stage add a second step.
4. Give the pipeline a name and click add.
5. Try to run the pipeline once.

**Results:**

1.The Spinning wheel / progress message gets stuck on "Assigning jobs to pipeline engine" indefinitely.
2. After a minute or two the status changes from Running to Fail

I checked what logs I could and there error I saw was this:
```
Jun 22, 2018 9:05:28 PM org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator$1 doLaunch
INFO: Created process inside pod: [jenkins-slave-m2pkp-sc3w3], container: [step-2-0] with pid:[-1]
Jun 22, 2018 9:05:35 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
INFO: Terminating Kubernetes instance for agent jenkins-slave-m2pkp-sc3w3
Jun 22, 2018 9:05:35 PM jenkins.slaves.DefaultJnlpSlaveReceiver channelClosed
WARNING: Computer.threadPoolForRemoting [#127] for jenkins-slave-m2pkp-sc3w3 terminated
java.nio.channels.ClosedChannelException
	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:208)
	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:222)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:832)
	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:181)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:283)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:503)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:248)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:200)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFilterLayer.java:213)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doCloseSend(ProtocolStack.java:800)
	at org.jenkinsci.remoting.protocol.ApplicationLayer.doCloseWrite(ApplicationLayer.java:173)
	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:313)
	at hudson.remoting.Channel.close(Channel.java:1446)
	at hudson.remoting.Channel.close(Channel.java:1399)
	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:746)
	at hudson.slaves.SlaveComputer.access$800(SlaveComputer.java:99)
	at hudson.slaves.SlaveComputer$3.run(SlaveComputer.java:664)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by KaelBaldwin** [comment]
I took the same pipeline I had created and removed the second step, and the pipeline would then run.

**Comment by bmdepesa** [comment]
rancher/rancher:master 9/5

Created a stage with multiple steps. Pipeline executed successfully.
