### ISSUE TITLE
Rancher CLI panic when listing upgradable stacks

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#14415]
**Rancher versions:** v1.6.19-rc2
**RancherCLI version:** v0.6.10
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
k8s
**Steps to Reproduce:**
deploy a stack that has an upgrade
run `rancher stacks ` using rancherCLI
**Results:**
```
# rancher stacks -s
ID        NAME               STATE     CATALOG                                       SERVICES   SYSTEM    DETAIL    AVAILABLE UPGRADES
1st1      healthcheck        healthy   catalog://library:infra*healthcheck:7         1          true                
1st2      ipsec              healthy   catalog://library:infra*ipsec:17              2          true                
1st3      scheduler          healthy   catalog://library:infra*scheduler:12          1          true                
1st4      network-services   healthy   catalog://library:infra*network-services:28   2          true                
1st5      kubernetes         healthy   catalog://library:infra*k8s:48                12         true                library:infra*k8s:49
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0x472c97]

goroutine 1 [running]:
panic(0xa10860, 0xc4200100c0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/rancher/cli/vendor/github.com/urfave/cli.HandleAction.func1(0xc4203f7ee0)
        /go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:472 +0x29e
panic(0xa10860, 0xc4200100c0)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/rancher/cli/cmd.(*CatalogOperator).GetTemplateVersionUpgrades(0xc420072480, 0x0, 0x31, 0x0, 0xdea0a0)
        /go/src/github.com/rancher/cli/cmd/catalog.go:576 +0x37
github.com/rancher/cli/cmd.(*CatalogOperator).GetTemplateVersionUpgradesByID(0xc420072480, 0xc420270e80, 0x31, 0x6, 0x1, 0xc42047f2ee)
        /go/src/github.com/rancher/cli/cmd/catalog.go:572 +0x57
github.com/rancher/cli/cmd.stackLs(0xc4202fef00, 0x0, 0x0)
        /go/src/github.com/rancher/cli/cmd/stack.go:132 +0x85d
github.com/rancher/cli/cmd.defaultAction.func1(0xc4202fef00, 0x0, 0x0)
        /go/src/github.com/rancher/cli/cmd/common.go:298 +0x93
reflect.Value.call(0x9d0540, 0xc420320780, 0x13, 0xade6d9, 0x4, 0xc4203f7e80, 0x1, 0x1, 0x4a3148, 0xac5c60, ...)
        /usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x9d0540, 0xc420320780, 0x13, 0xc4203f7e80, 0x1, 0x1, 0xc420321136, 0x4a84f4, 0xa08fe0)
        /usr/local/go/src/reflect/value.go:302 +0xa4
github.com/rancher/cli/vendor/github.com/urfave/cli.HandleAction(0x9d0540, 0xc420320780, 0xc4202fef00, 0x0, 0x0)
        /go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:481 +0x1e0
github.com/rancher/cli/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc4202e8300, 0xc4202fedc0, 0x0, 0x0)
        /go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:360 +0x9ee
github.com/rancher/cli/vendor/github.com/urfave/cli.Command.startApp(0xae1079, 0x6, 0xadfd3a, 0x5, 0x0, 0x0, 0x0, 0xaec2b0, 0x14, 0x0, ...)
        /go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/command.go:273 +0x823
github.com/rancher/cli/vendor/github.com/urfave/cli.Command.Run(0xae1079, 0x6, 0xadfd3a, 0x5, 0x0, 0x0, 0x0, 0xaec2b0, 0x14, 0x0, ...)
        /go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/command.go:74 +0x1638
github.com/rancher/cli/vendor/github.com/urfave/cli.(*App).Run(0xc4202e8180, 0xc42000a120, 0x3, 0x3, 0x0, 0x0)
        /go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:235 +0x60c
main.mainErr(0x0, 0xc4203206a0)
        /go/src/github.com/rancher/cli/main.go:150 +0x20e6
main.main()
        /go/src/github.com/rancher/cli/main.go:37 +0x26
```

**Comment by cjellick** [comment]
:scream:

**Comment by vukor** [comment]
**Rancher versions:** v1.6.18
**RancherCLI version:** v0.6.8-rc3 - v0.6.11-rc2
**Environment Template: Cattle**

Same for me on all versions ```v0.6.8-rc3``` - ```v0.6.11-rc2```, it works on ```v0.6.8-rc2```
**Results:**
```
$ docker run --rm -v ~/.rancher/:/root/.rancher rancher/cli:v0.6.8-rc3 stack ls
Unable to find image 'rancher/cli:v0.6.8-rc3' locally
v0.6.8-rc3: Pulling from rancher/cli
550fe1bea624: Already exists
6d7ee243d9a8: Already exists
d822ae330d72: Pull complete
Digest: sha256:b4aa290e10b05cd94b2f02eab689229464171656492225b7ba662a3ac6bfbab7
Status: Downloaded newer image for rancher/cli:v0.6.8-rc3
ID        NAME                   STATE      CATALOG                        SERVICES   SYSTEM    DETAIL    AVAILABLE UPGRADES
*******   Default                healthy                                   0          false
*******   ****************       healthy                                   1          false
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0x473c77]

goroutine 1 [running]:
panic(0xad4500, 0xc420014060)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/rancher/cli/vendor/github.com/urfave/cli.HandleAction.func1(0xc420551b18)
	/go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:472 +0x29e
panic(0xad4500, 0xc420014060)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/rancher/cli/cmd.(*CatalogOperator).GetTemplateVersionUpgrades(0xc4203bbb00, 0x0, 0x21, 0x0, 0x110c080)
	/go/src/github.com/rancher/cli/cmd/catalog.go:576 +0x37
github.com/rancher/cli/cmd.(*CatalogOperator).GetTemplateVersionUpgradesByID(0xc4203bbb00, 0xc420482630, 0x21, 0x6, 0x1, 0x0)
	/go/src/github.com/rancher/cli/cmd/catalog.go:572 +0x57
github.com/rancher/cli/cmd.stackLs(0xc420329180, 0x0, 0x0)
	/go/src/github.com/rancher/cli/cmd/stack.go:132 +0x85d
reflect.Value.call(0xa91940, 0xc17b20, 0x13, 0xbac6b7, 0x4, 0xc420551ab8, 0x1, 0x1, 0x4a4818, 0xb93080, ...)
	/usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0xa91940, 0xc17b20, 0x13, 0xc420551ab8, 0x1, 0x1, 0x0, 0x140, 0x140)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/rancher/cli/vendor/github.com/urfave/cli.HandleAction(0xa91940, 0xc17b20, 0xc420329180, 0x0, 0x0)
	/go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:481 +0x1e0
github.com/rancher/cli/vendor/github.com/urfave/cli.Command.Run(0xbabe23, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0xbb38b0, 0xb, 0x0, ...)
	/go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/command.go:186 +0xc26
github.com/rancher/cli/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc420312300, 0xc420328f00, 0x0, 0x0)
	/go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:355 +0xa64
github.com/rancher/cli/vendor/github.com/urfave/cli.Command.startApp(0xbaf0ff, 0x6, 0xbadd62, 0x5, 0x0, 0x0, 0x0, 0xbba738, 0x14, 0x0, ...)
	/go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/command.go:273 +0x823
github.com/rancher/cli/vendor/github.com/urfave/cli.Command.Run(0xbaf0ff, 0x6, 0xbadd62, 0x5, 0x0, 0x0, 0x0, 0xbba738, 0x14, 0x0, ...)
	/go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/command.go:74 +0x1638
github.com/rancher/cli/vendor/github.com/urfave/cli.(*App).Run(0xc420312180, 0xc42000c0f0, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:235 +0x60c
main.mainErr(0x0, 0xc42034c760)
	/go/src/github.com/rancher/cli/main.go:150 +0x20e6
main.main()
	/go/src/github.com/rancher/cli/main.go:37 +0x26
```

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
