### ISSUE TITLE
Access control is not configured after authentification

### ISSUE THREAD

**Issue by IMikkeI** [rancher/rancher#1444]
Hi,

I've tried to connect with my github account for Acess Control. I have followed the number 1 and 2 steps. When I click on "authentification with github", it redirect me on github page, I accept and It redirect me on Rancher main page. But the red banner which says "access control in not configured" is always here. 
I have the same error with Docker on a Linux VM (ubuntu 14.04) and docker with boot2docker.
I'm behind a proxy, I have setted http_proxy, https_proxy, HTTP_PROXY and HTTPS_proxy with -e on the server command line start.

I have the following error on the server logs :

2015-07-09 09:23:09,124 ERROR [:] [] [] [] [tp1394454342-40] [i.g.i.g.r.handler.
ExceptionHandler  ] Exception in API for request [io.github.ibuildthecloud.gdapi
.request.ApiRequest@7914c86f] java.lang.RuntimeException: org.apache.http.conn.C
onnectTimeoutException: Connect to github.com:443 [github.com/192.30.252.131] fa
iled: Connection timed out
        at io.cattle.platform.iaas.api.auth.github.TokenResourceManager.createIn
ternal(TokenResourceManager.java:52) ~[cattle-iaas-auth-logic-0.5.0-SNAPSHOT.jar
:na]
        at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseReso
urceManager.create(AbstractBaseResourceManager.java:115) ~[gdapi-java-server-0.1
1.1.1.jar:na]
        at io.github.ibuildthecloud.gdapi.request.handler.ResourceManagerRequest
Handler.generate(ResourceManagerRequestHandler.java:39) ~[gdapi-java-server-0.11
.1.1.jar:na]
        at io.github.ibuildthecloud.gdapi.request.handler.AbstractResponseGenera
tor.handle(AbstractResponseGenerator.java:14) ~[gdapi-java-server-0.11.1.1.jar:n
a]
        at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWrite
ApiDelegate.handle(DefaultReadWriteApiDelegate.java:27) ~[gdapi-java-server-0.11
.1.1.jar:na]
        at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWrite
ApiDelegate.write(DefaultReadWriteApiDelegate.java:22) ~[gdapi-java-server-0.11.
1.1.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.
0_79]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57) ~[na:1.7.0_79]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43) ~[na:1.7.0_79]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflecti
on(AopUtils.java:317) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJo
inpoint(ReflectiveMethodInvocation.java:183) ~[spring-aop-3.2.5.RELEASE.jar:3.2.
5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(
ReflectiveMethodInvocation.java:150) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEAS
E]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.
proceedWithInvocation(TransactionInterceptor.java:96) ~[spring-tx-3.2.4.RELEASE.
jar:3.2.4.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.
invokeWithinTransaction(TransactionAspectSupport.java:260) ~[spring-tx-3.2.4.REL
EASE.jar:3.2.4.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.in
voke(TransactionInterceptor.java:94) ~[spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE
]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(
ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEAS
E]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invok
e(ExposeInvocationInterceptor.java:91) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELE
ASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(
ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEAS
E]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynami
cAopProxy.java:204) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at com.sun.proxy.$Proxy36.write(Unknown Source) ~[na:na]
        at io.github.ibuildthecloud.gdapi.request.handler.write.ReadWriteApiHand
ler.handle(ReadWriteApiHandler.java:19) ~[gdapi-java-server-0.11.1.1.jar:na]
        at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFil
ter(ApiRequestFilterDelegate.java:88) ~[gdapi-java-server-0.11.1.1.jar:na]
        at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiReq
uestFilter.java:60) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(Ma
nagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.j
ar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.ca
ll(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSH
OT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.call
WithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.
5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runW
ithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.
0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(Mana
gedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar
:na]
        at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFi
lter.java:53) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1419) [jetty-servlet-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.j
ava:82) [jetty-servlets-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:256) [
jetty-servlets-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1419) [jetty-servlet-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java
:455) [jetty-servlet-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.j
ava:137) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.jav
a:557) [jetty-security-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandl
er.java:231) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandl
er.java:1075) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:
384) [jetty-servlet-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandle
r.java:193) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandle
r.java:1009) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.j
ava:135) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper
.java:116) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.server.Server.handle(Server.java:370) [jetty-server
-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(Abstrac
tHttpConnection.java:489) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpC
onnection.java:960) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.conten
t(AbstractHttpConnection.java:1021) [jetty-server-8.1.11.v20130520.jar:8.1.11.v2
0130520]
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865) [jet
ty-http-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
 [jetty-http-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnecti
on.java:82) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEn
dPoint.java:668) [jetty-io-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEnd
Point.java:52) [jetty-io-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPoo
l.java:608) [jetty-util-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool
.java:543) [jetty-util-8.1.11.v20130520.jar:8.1.11.v20130520]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to github.com:4
43 [github.com/192.30.252.131] failed: Connection timed out
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpCl
ientConnectionOperator.java:136) ~[httpclient-4.3.1.jar:4.3.1]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(
PoolingHttpClientConnectionManager.java:314) ~[httpclient-4.3.1.jar:4.3.1]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClie
ntExec.java:357) ~[httpclient-4.3.1.jar:4.3.1]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.
java:218) ~[httpclient-4.3.1.jar:4.3.1]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java
:194) ~[httpclient-4.3.1.jar:4.3.1]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85) ~
[httpclient-4.3.1.jar:4.3.1]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java
:108) ~[httpclient-4.3.1.jar:4.3.1]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttp
Client.java:186) ~[httpclient-4.3.1.jar:4.3.1]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttp
Client.java:82) ~[httpclient-4.3.1.jar:4.3.1]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttp
Client.java:106) ~[httpclient-4.3.1.jar:4.3.1]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttp
Client.java:57) ~[httpclient-4.3.1.jar:4.3.1]
        at org.apache.http.client.fluent.Request.execute(Request.java:143) ~[flu
ent-hc-4.3.1.jar:4.3.1]
        at io.cattle.platform.iaas.api.auth.github.GithubClient.getAccessToken(G
ithubClient.java:52) ~[cattle-iaas-auth-logic-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.iaas.api.auth.github.GithubTokenHandler.getToken(G
ithubTokenHandler.java:123) ~[cattle-iaas-auth-logic-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.iaas.api.auth.github.TokenResourceManager.getToken
(TokenResourceManager.java:59) ~[cattle-iaas-auth-logic-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.iaas.api.auth.github.TokenResourceManager.createIn
ternal(TokenResourceManager.java:50) ~[cattle-iaas-auth-logic-0.5.0-SNAPSHOT.jar
:na]
        ... 55 common frames omitted
Caused by: java.net.ConnectException: Connection timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_79]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.ja
va:339) ~[na:1.7.0_79]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocket
Impl.java:200) ~[na:1.7.0_79]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java
:182) ~[na:1.7.0_79]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0
_79]
        at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_79]
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:625) ~[na:1
.7.0_79]
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSL
ConnectionSocketFactory.java:250) ~[httpclient-4.3.1.jar:4.3.1]
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpCl
ientConnectionOperator.java:118) ~[httpclient-4.3.1.jar:4.3.1]
        ... 70 common frames omitted

Any help will be fine, I really want to use your product.

**Comment by vincent99** [comment]
@ibuildthecloud Cattle needs to be able to use a proxy...

**Comment by tfiduccia** [comment]
@IMikkeI Looks like we did this - here are the instructions
http://docs.rancher.com/rancher/latest/en/installing-rancher/installing-server/no-internet-access/#using-http-proxy
