### ISSUE TITLE
Container process exits with error: unable to register configz: register config "componentconfig" twice

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14538]
Version: master 7/13

Seen this happen randomly, first observation is that it happens when `kube-controller-manager` is started before `kube-scheduler`

```
2018/07/13 14:34:38 [INFO] Running kube-controller-manager --cluster-cidr=10.42.0.0/16 --allow-untagged-cloud=true --configure-cloud-routes=false --leader-elect=true --node-monitor-grace-period=40s --v=2 --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-controller-manager.yaml --service-account-private-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem --address=0.0.0.0 --allocate-node-cidrs=true --service-cluster-ip-range=10.43.0.0/16 --enable-hostpath-provisioner=false --pod-eviction-timeout=5m0s --cloud-provider= --root-ca-file=/etc/kubernetes/ssl/kube-ca.pem --use-service-account-credentials=true --logtostderr=false --alsologtostderr=false
2018/07/13 14:34:38 [INFO] Running kube-scheduler --leader-elect=true --v=2 --address=0.0.0.0 --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-scheduler.yaml --logtostderr=false --alsologtostderr=false
F0713 14:34:38.699730       1 helpers.go:119] error: unable to register configz: register config "componentconfig" twice
goroutine 4576 [running]:
github.com/rancher/rancher/vendor/github.com/golang/glog.stacks(0xc420853500, 0xc420a1c000, 0x79, 0x1c6)
        /go/src/github.com/rancher/rancher/vendor/github.com/golang/glog/glog.go:766 +0xcf
github.com/rancher/rancher/vendor/github.com/golang/glog.(*loggingT).output(0xc0e6b60, 0xc400000003, 0xc421196210, 0xbaba0be, 0xa, 0x77, 0x0)
        /go/src/github.com/rancher/rancher/vendor/github.com/golang/glog/glog.go:717 +0x322
github.com/rancher/rancher/vendor/github.com/golang/glog.(*loggingT).printDepth(0xc0e6b60, 0x3, 0x2, 0xc428f50a30, 0x1, 0x1)
        /go/src/github.com/rancher/rancher/vendor/github.com/golang/glog/glog.go:646 +0x12a
github.com/rancher/rancher/vendor/github.com/golang/glog.FatalDepth(0x2, 0xc428f50a30, 0x1, 0x1)
        /go/src/github.com/rancher/rancher/vendor/github.com/golang/glog/glog.go:1131 +0x5d
github.com/rancher/rancher/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/util.fatal(0xc425980000, 0x4a, 0x1)
        /go/src/github.com/rancher/rancher/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/util/helpers.go:97 +0x236
github.com/rancher/rancher/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/util.checkErr(0xbd68d20, 0xc4289888b0, 0x54536e0)
        /go/src/github.com/rancher/rancher/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/util/helpers.go:173 +0x8f9
github.com/rancher/rancher/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/util.CheckErr(0xbd68d20, 0xc4289888b0)
        /go/src/github.com/rancher/rancher/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/util/helpers.go:119 +0x41
github.com/rancher/rancher/vendor/k8s.io/kubernetes/cmd/kube-scheduler/app.NewSchedulerCommand.func1(0xc420453900, 0xc110940, 0x0, 0x0)
        /go/src/github.com/rancher/rancher/vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:343 +0xb4
github.com/rancher/rancher/vendor/github.com/spf13/cobra.(*Command).execute(0xc420453900, 0xc4296c9620, 0x0, 0x6, 0xc420453900, 0xc4296c9620)
        /go/src/github.com/rancher/rancher/vendor/github.com/spf13/cobra/command.go:757 +0x2c1
github.com/rancher/rancher/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420453900, 0xdf8475800, 0x20002, 0xc428ca67a4)
        /go/src/github.com/rancher/rancher/vendor/github.com/spf13/cobra/command.go:843 +0x334
github.com/rancher/rancher/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420453900, 0x5b7767, 0x1)
        /go/src/github.com/rancher/rancher/vendor/github.com/spf13/cobra/command.go:791 +0x2b
github.com/rancher/rancher/pkg/hyperkube.NewScheduler.func1(0xc4296c9500, 0xc4296c9620, 0x0, 0x6, 0xc42001a660, 0x100010000, 0x0)
        /go/src/github.com/rancher/rancher/pkg/hyperkube/kube-scheduler.go:43 +0x63
github.com/rancher/rancher/pkg/hyperkube.(*HyperKube).Run.func1(0xc42c371f80, 0xc4296c9500)
        /go/src/github.com/rancher/rancher/pkg/hyperkube/hyperkube.go:184 +0x76
created by github.com/rancher/rancher/pkg/hyperkube.(*HyperKube).Run
        /go/src/github.com/rancher/rancher/pkg/hyperkube/hyperkube.go:183 +0x539
```

Good run:

```
2018/07/13 14:40:38 [INFO] Running kube-scheduler --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-scheduler.yaml --leader-elect=true --v=2 --address=0.0.0.0 --logtostderr=false --alsologtostderr=false
2018/07/13 14:40:38 [INFO] Running kube-controller-manager --cloud-provider= --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-controller-manager.yaml --address=0.0.0.0 --allow-untagged-cloud=true --enable-hostpath-provisioner=false --allocate-node-cidrs=true --v=2 --service-cluster-ip-range=10.43.0.0/16 --service-accoun
t-private-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem --root-ca-file=/etc/kubernetes/ssl/kube-ca.pem --configure-cloud-routes=false --leader-elect=true --node-monitor-grace-period=40s --pod-eviction-timeout=5m0s --cluster-cidr=10.42.0.0/16 --use-service-account-credentials=true --logtostderr=false --alsologto
stderr=false
E0713 14:40:38.456163       1 controllermanager.go:121] unable to register configz: &{%!c(string=register config "componentconfig" twice)}
E0713 14:40:38.580990       1 leaderelection.go:224] error retrieving resource lock kube-system/kube-controller-manager: endpoints "kube-controller-manager" is forbidden: User "system:kube-controller-manager" cannot get endpoints in the namespace "kube-system"
E0713 14:40:38.581450       1 reflector.go:205] github.com/rancher/rancher/vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:594: Failed to list *v1.Pod: pods is forbidden: User "system:kube-scheduler" cannot list pods at the cluster scope
E0713 14:40:38.581785       1 reflector.go:205] github.com/rancher/rancher/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:kube-scheduler" cannot list storageclasses.storage.k8s.io at the cluster scope
2018/07/13 14:40:38 [DEBUG] REST GET api//v1//namespaces/cattle-system
2018/07/13 14:40:38 [DEBUG] REST CREATE api//v1//namespaces
```

**Comment by superseb** [comment]
No error in ~20 runs, seems resolved. We can re-open if it is seen.
