### ISSUE TITLE
panic: "assignment to entry in nil map" when try to create node by calling POST /v3/nodes

### ISSUE THREAD

**Issue by ukinau** [rancher/rancher#14867]
**Rancher versions:**
rancher/rancher: v2.0.6
rancher/rancher-agent: v2.0.6

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
3.10.0-693.17.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
kvm + qemu

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Steps to Reproduce:**
1. deploy rancer/rancher with v2.0.6
2. call POST /v3/nodes 

**Results:**
you will get no response from rancher server and also
If you see the log of rancher-server, you should be able to see rancher-server container restarted because of following panic 

```
panic: assignment to entry in nil map

goroutine 9113 [running]:
github.com/rancher/rancher/vendor/github.com/rancher/types/mapper.OSInfo.FromInternal(0x0)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/mapper/os_info.go:33 +0x921
github.com/rancher/rancher/vendor/github.com/rancher/types/mapper.(*OSInfo).FromInternal(0xacdec40, 0x0)
        <autogenerated>:1 +0x3e
github.com/rancher/rancher/vendor/github.com/rancher/norman/types.Mappers.FromInternal(0xc4201d2510, 0x9, 0x9, 0x0)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/types/mapper.go:20 +0x4b
github.com/rancher/rancher/vendor/github.com/rancher/norman/types.(*Mappers).FromInternal(0xc420341340, 0x0)
        <autogenerated>:1 +0x58
github.com/rancher/rancher/vendor/github.com/rancher/norman/types.Mappers.FromInternal(0xc42032b6b0, 0x3, 0x3, 0x0)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/types/mapper.go:20 +0x4b
github.com/rancher/rancher/vendor/github.com/rancher/norman/types.(*typeMapper).FromInternal(0xc420125700, 0x0)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/types/mapper.go:67 +0x2c6
github.com/rancher/rancher/vendor/github.com/rancher/norman/types.(*typeMapper).FromInternal(0xc420300340, 0x0)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/types/mapper.go:53 +0x12a
github.com/rancher/rancher/vendor/github.com/rancher/norman/types.(*typeMapper).FromInternal(0xc420300500, 0xc42a9c1200)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/types/mapper.go:53 +0x12a
github.com/rancher/rancher/vendor/github.com/rancher/norman/store/proxy.(*Store).fromInternal(0xc4207775e0, 0xc4222308c0, 0xc42a9c1200, 0xc4310023f0)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/proxy/proxy_store.go:441 +0x5d
github.com/rancher/rancher/vendor/github.com/rancher/norman/store/proxy.(*Store).realWatch.func2(0xc43131a690, 0xc4207775e0, 0xc4222308c0, 0xc4280acb40)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/proxy/proxy_store.go:256 +0x113
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/store/proxy.(*Store).realWatch
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/proxy/proxy_store.go:253 +0x55e
```

**Comment by soumyalj** [comment]
Tested with fresh install of master build and also upgrade to master build. I still see the issue when a node is created through v3/nodes POST call
```
panic: assignment to entry in nil map

goroutine 61923 [running]:
github.com/rancher/rancher/vendor/github.com/rancher/types/mapper.OSInfo.FromInternal(0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/mapper/os_info.go:33 +0x921
github.com/rancher/rancher/vendor/github.com/rancher/types/mapper.(*OSInfo).FromInternal(0xc382100, 0x0)
	<autogenerated>:1 +0x3e
github.com/rancher/rancher/vendor/github.com/rancher/norman/types.Mappers.FromInternal(0xc4201de090, 0x9, 0x9, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/types/mapper.go:21 +0x4b
github.com/rancher/rancher/vendor/github.com/rancher/norman/types.(*Mappers).FromInternal(0xc4200ce500, 0x0)
	<autogenerated>:1 +0x58
github.com/rancher/rancher/vendor/github.com/rancher/norman/types.Mappers.FromInternal(0xc42064b800, 0x3, 0x3, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/types/mapper.go:21 +0x4b
github.com/rancher/rancher/vendor/github.com/rancher/norman/types.(*typeMapper).FromInternal(0xc42006d950, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/types/mapper.go:89 +0x58d
github.com/rancher/rancher/vendor/github.com/rancher/norman/types.(*typeMapper).FromInternal(0xc4201118b0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/types/mapper.go:60 +0x22a
github.com/rancher/rancher/vendor/github.com/rancher/norman/types.(*typeMapper).FromInternal(0xc420111950, 0xc432bcd5c0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/types/mapper.go:60 +0x22a
github.com/rancher/rancher/vendor/github.com/rancher/norman/store/proxy.(*Store).fromInternal(0xc423fec640, 0xc4244a3b00, 0xc42e0b8c40, 0xc432bcd5c0, 0xc4367507b0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/proxy/proxy_store.go:468 +0xde
github.com/rancher/rancher/vendor/github.com/rancher/norman/store/proxy.(*Store).realWatch.func2(0xc42b6996e0, 0xc423fec640, 0xc4244a3b00, 0xc42e0b8c40, 0xc42bf976e0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/proxy/proxy_store.go:257 +0x120
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/store/proxy.(*Store).realWatch
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/proxy/proxy_store.go:254 +0x571



```

**Comment by StrongMonkey** [comment]
@soumyalj can you re-verify it? I think you were using the wrong image to test at that time and it doesn't include the fix.

**Comment by soumyalj** [comment]
Tested with master build from Sep 6th. Created a DO cluster and added nodes using v3/nodes post call. The API request was successful and the node was added successfully. Example below:

```
API Request
cURL command line: 
curl -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
-X POST \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
-d '{"amazonec2Config":null, "azureConfig":null, "clusterId":"c-d4z8p", "controlPlane":false, "customConfig":null, "digitaloceanConfig":null, "etcd":false, "imported":false, "namespaceId":"", "nodeTemplateId":"user-4znvb:nt-cc2hg", "requestedHostname":"soumyabugtestworker", "vmwarevsphereConfig":null, "worker":true}' \
'https://1.2.3.4/v3/nodes'
HTTP Request:
HTTP/1.1 POST /v3/nodes
Host: 1.2.3.4
Accept: application/json
Content-Type: application/json
Content-Length: 301

{
"amazonec2Config": null,
"azureConfig": null,
"clusterId": "c-d4z8p",
"controlPlane": false,
"customConfig": null,
"digitaloceanConfig": null,
"etcd": false,
"imported": false,
"namespaceId": "",
"nodeTemplateId": "user-4znvb:nt-cc2hg",
"requestedHostname": "soumyabugtestworker",
"vmwarevsphereConfig": null,
"worker": true
}
HTTP Response:
HTTP/1.1 201
date: Thu, 06 Sep 2018 22:41:42 GMT
x-api-schemas: https://1.2.3.4/v3/schemas
content-type: application/json
content-length: 994
expires: Wed 24 Feb 1982 18:42:00 GMT

{
"actions": {
"cordon": "…/v3/nodes/c-d4z8p:n-kbxdh?action=cordon",
"drain": "…/v3/nodes/c-d4z8p:n-kbxdh?action=drain"
},
"amazonec2Config": null,
"azureConfig": null,
"baseType": "node",
"clusterId": "c-d4z8p",
"controlPlane": false,
"created": "2018-09-06T22:41:42Z",
"createdTS": 1536273702000,
"creatorId": null,
"customConfig": null,
"digitaloceanConfig": null,
"etcd": false,
"id": "c-d4z8p:n-kbxdh",
"imported": false,
"links": {
"nodeConfig": "…/v3/nodes/c-d4z8p:n-kbxdh/nodeconfig",
"remove": "…/v3/nodes/c-d4z8p:n-kbxdh",
"self": "…/v3/nodes/c-d4z8p:n-kbxdh",
"update": "…/v3/nodes/c-d4z8p:n-kbxdh"
},
"namespaceId": null,
"nodePoolId": null,
"nodeTemplateId": "user-4znvb:nt-cc2hg",
"requestedHostname": "soumyabugtestworker",
"state": "active",
"transitioning": "no",
"transitioningMessage": "",
"type": "node",
"unschedulable": false,
"uuid": "0676e78e-b226-11e8-85bd-0242ac110002",
"vmwarevsphereConfig": null,
"worker": true
}

```
Did not see any panic in the server logs. Proper logging as we see when a node gets added
```
2018/09/06 22:41:42 [INFO] stdout: Creating CA: management-state/node/nodes/soumyabugtestworker/certs/ca.pem
2018/09/06 22:41:43 [INFO] stdout: Creating client certificate: management-state/node/nodes/soumyabugtestworker/certs/cert.pem
2018/09/06 22:41:43 [INFO] stdout: Running pre-create checks...
2018/09/06 22:41:45 [INFO] stdout: Creating machine...
2018/09/06 22:41:45 [INFO] stdout: (soumyabugtestworker) Creating SSH key...
2018/09/06 22:41:45 [INFO] stdout: (soumyabugtestworker) Creating Digital Ocean droplet...
2018/09/06 22:41:46 [INFO] stdout: (soumyabugtestworker) Waiting for IP address to be assigned to the Droplet...
2018/09/06 22:41:47 [INFO] stdout: Waiting for machine to be running, this may take a few minutes...
2018/09/06 22:42:02 [INFO] stdout: Detecting operating system of created instance...
2018/09/06 22:42:02 [INFO] stdout: Waiting for SSH to be available...
2018/09/06 22:42:22 [INFO] stdout: Detecting the provisioner...
2018/09/06 22:42:22 [INFO] stdout: Provisioning with ubuntu(systemd)...
2018/09/06 22:42:36 [INFO] stdout: Installing Docker...



```
