### ISSUE TITLE
Specifying a private registry with non default port cause panic when creating cluster

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#15024]
rancher/rancher:master

when specifying the private registry to an address with non default port:
```
example.com:7000
```
this will cause a panic when creating a cluster:
```
DEBU[0052] [pre-deploy] No pull necessary, image [rancher/hyperkube:v1.11.1-rancher1] exists on host [142.93.99.49]
INFO[0052] Kubernetes images pulled successfully
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1de4f5f]

goroutine 1 [running]:
github.com/rancher/rke/vendor/github.com/urfave/cli.HandleAction.func1(0xc4207a0700)
        /go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/app.go:472 +0x28d
panic(0x1f65aa0, 0x2a04fa0)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/rancher/rke/cluster.(*Cluster).getRKEToolsEntryPoint(0xc4203f1800, 0x7000000000000, 0x22)
        /go/src/github.com/rancher/rke/cluster/plan.go:741 +0xbf
github.com/rancher/rke/cluster.(*Cluster).BuildKubeletProcess(0xc4203f1800, 0xc4200ff700, 0x2109e4e, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/rancher/rke/cluster/plan.go:305 +0x71
github.com/rancher/rke/cluster.BuildRKEConfigNodePlan(0x29c88c0, 0xc420012808, 0xc4203f1800, 0xc4200ff700, 0xc420014540, 0x3b, 0x1, 0x1, 0x0, 0x0, ...)
        /go/src/github.com/rancher/rke/cluster/plan.go:56 +0x22c
github.com/rancher/rke/cluster.(*Cluster).DeployControlPlane(0xc4203f1800, 0x29c88c0, 0xc420012808, 0x0, 0x0)
        /go/src/github.com/rancher/rke/cluster/cluster.go:71 +0x14d
github.com/rancher/rke/cmd.ClusterUp(0x29c88c0, 0xc420012808, 0xc42040ce00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/rancher/rke/cmd/up.go:113 +0x302
github.com/rancher/rke/cmd.clusterUpFromCli(0xc420399a40, 0x0, 0x0)
        /go/src/github.com/rancher/rke/cmd/up.go:200 +0x365
reflect.Value.call(0x1f01280, 0x21a0f40, 0x13, 0x210a631, 0x4, 0xc4202ec6a0, 0x1, 0x1, 0xc4202ec628, 0x20d1ac0, ...)
        /usr/local/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0x1f01280, 0x21a0f40, 0x13, 0xc4202ec6a0, 0x1, 0x1, 0x140, 0xc420399a40, 0x0)
        /usr/local/go/src/reflect/value.go:302 +0xa4
github.com/rancher/rke/vendor/github.com/urfave/cli.HandleAction(0x1f01280, 0x21a0f40, 0xc420399a40, 0x0, 0x0)
        /go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/app.go:481 +0x198
github.com/rancher/rke/vendor/github.com/urfave/cli.Command.Run(0x210a070, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x211f7ec, 0x14, 0x0, ...)
        /go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/command.go:186 +0xab8
github.com/rancher/rke/vendor/github.com/urfave/cli.(*App).Run(0xc4201df800, 0xc42000e2a0, 0x3, 0x3, 0x0, 0x0)
        /go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/app.go:235 +0x5d6
main.mainErr(0xc4202edf78, 0x1dfba28)
        /go/src/github.com/rancher/rke/main.go:52 +0x12d3
main.main()
        /go/src/github.com/rancher/rke/main.go:16 +0x22
```

https://github.com/rancher/rke/issues/855

**Comment by moelsayed** [comment]
Tested and confirmed working with a private registry using a non-standard port using v2.0.7-rc3. Works as expected.
