### ISSUE TITLE
Fatal Error in Rancher (Drone) - Concurrent Map Read/Write

### ISSUE THREAD

**Issue by nathan-jenan-rancher** [rancher/rancher#15168]
Got the following error in drone.

```
fatal error: concurrent map read and map write

goroutine 83721 [running]:
runtime.throw(0x546e240, 0x21)
    /usr/local/go/src/runtime/panic.go:605 +0x95 fp=0xc431a50580 sp=0xc431a50560 pc=0x42bd35
runtime.mapaccess2_faststr(0x49260c0, 0xc440258a50, 0x543be11, 0x19, 0x0, 0xc420ec8fe0)
    /usr/local/go/src/runtime/hashmap_fast.go:324 +0x47a fp=0xc431a505d8 sp=0xc431a50580 pc=0x40c42a
github.com/rancher/rancher/pkg/controllers/user/rbac.updateStatusAnnotation(0x1, 0xc4279c0280, 0xc426745d10)
    /go/src/github.com/rancher/rancher/pkg/controllers/user/rbac/namespace_handler.go:397 +0x6b fp=0xc431a507c8 sp=0xc431a505d8 pc=0x3a3fe9b
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc431a507d0 sp=0xc431a507c8 pc=0x45d101
created by github.com/rancher/rancher/pkg/controllers/user/rbac.(*nsLifecycle).Create
    /go/src/github.com/rancher/rancher/pkg/controllers/user/rbac/namespace_handler.go:63 +0x10c
```

**Comment by sangeethah** [comment]
Tested with rancher server version v2.0.8-rc3

Able to create namespace and deploy workloads in the namespace using UI as well as API (validation tests).
