### ISSUE TITLE
Rancher UI workloads page freezes for CRD pods

### ISSUE THREAD

**Issue by alexandrem** [rancher/rancher#15199]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.7
rancher/agent or rancher/rancher-agent: v2.0.7

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** HA rancher on k8s

**Problem summary**

We are using Agones (https://github.com/GoogleCloudPlatform/agones) to deploy game server instances to Kubernetes clusters deployed on Openstack.

It seems like pods from CRDs make the rancher UI freeze completely when browsing the properties.

**Steps to Reproduce:**

We can probably reproduce this with other operators, but our steps are:

- Deploy Agones
- Launch the simple UDP example manifests (https://github.com/GoogleCloudPlatform/agones/tree/master/examples/simple-udp)
- Go to the workloads page, select "Flat List" view
- Enter the "simple-udp-xxx" pod
- Click a few sections (e.g Networking, Status, Events) then see that everything is frozen
- Reload the page and see the infinite loading icon

Example page that freezes:
https://company.com/p/c-m456f:p-f284s/workloads/default:simple-udp-svmx6

**Results:**

UI becomes unresponsive. If you reload, the page is grayed out and shows the loading icon infinitely. 

There's a javascript error in the console:

```
ember-metal.js:3007 Uncaught n {stack: "Error: Property set failed: object in path "servic…endor-7ff515c5da3fecb7eeb480f8a1f012b1.js:2523:9)", description: undefined, fileName: undefined, lineNumber: undefined, message: "Property set failed: object in path "service" could not be found or was destroyed.", …}code: undefineddescription: undefinedfileName: undefinedlineNumber: undefinedmessage: "Property set failed: object in path "service" could not be found or was destroyed."name: "Error"number: undefinedstack: "Error: Property set failed: object in path "service" could not be found or was destroyed.↵    at new n (https://uks.ubisoft.com/assets/vendor-7ff515c5da3fecb7eeb480f8a1f012b1.js:2330:13)↵    at https://uks.ubisoft.com/assets/vendor-7ff515c5da3fecb7eeb480f8a1f012b1.js:2854:13↵    at Object.Te [as set] (https://uks.ubisoft.com/assets/vendor-7ff515c5da3fecb7eeb480f8a1f012b1.js:2854:109)↵    at a.scaleModeDidChange (https://uks.ubisoft.com/assets/ui-fcb5f943a63deddc875f4b32d3fd0d82.js:226:93)↵    at a.init (https://uks.ubisoft.com/assets/ui-fcb5f943a63deddc875f4b32d3fd0d82.js:224:2785)↵    at a.n [as init] (https://uks.ubisoft.com/assets/vendor-7ff515c5da3fecb7eeb480f8a1f012b1.js:3611:9)↵    at new a (https://uks.ubisoft.com/assets/vendor-7ff515c5da3fecb7eeb480f8a1f012b1.js:3520:76)↵    at Function.u.create (https://uks.ubisoft.com/assets/vendor-7ff515c5da3fecb7eeb480f8a1f012b1.js:3529:414)↵    at e.create (https://uks.ubisoft.com/assets/vendor-7ff515c5da3fecb7eeb480f8a1f012b1.js:2171:18)↵    at n.create (https://uks.ubisoft.com/assets/vendor-7ff515c5da3fecb7eeb480f8a1f012b1.js:2523:9)"__proto__: tconstructor: ƒ n(r)__proto__: Error
(anonymous) @ ember-metal.js:3007
Te @ ember-metal.js:2958
(anonymous) @ component.js:49
init @ component.js:28
n @ ember-utils.js:360
a @ core_object.js:107
u.create @ core_object.js:260
e.create @ container.js:371
n.create @ ember-glimmer.js:3908
(anonymous) @ runtime.js:1148
e.evaluate @ runtime.js:30
e.evaluateSyscall @ runtime.js:2792
e.evaluateInner @ runtime.js:2768
e.evaluateOuter @ runtime.js:2760
e.next @ runtime.js:4867
e.execute @ runtime.js:4852
e.insert @ runtime.js:3886
e.nextInsert @ reference.js:610
e.nextAppend @ reference.js:573
e.sync @ reference.js:531
r.evaluate @ runtime.js:3974
e.execute @ runtime.js:3741
e.rerender @ runtime.js:4040
s.render @ ember-glimmer.js:4232
e.runInTransaction @ ember-metal.js:1152
e._renderRoots @ ember-glimmer.js:4498
e._renderRootsTransaction @ ember-glimmer.js:4531
e._revalidate @ ember-glimmer.js:4574
e.invoke @ backburner.js:218
e.flush @ backburner.js:134
e.flush @ backburner.js:290
e.end @ backburner.js:423
_boundAutorunEnd @ backburner.js:385
setTimeout (async)
i.next @ backburner.js:373
e._ensureInstance @ backburner.js:942
e.ensureInstance @ backburner.js:777
(anonymous) @ ember-metal.js:1078
_ @ ember-metal.js:1067
L @ ember-metal.js:1337
Te @ ember-metal.js:2990
set @ observable.js:104
(anonymous) @ type.js:39
(anonymous) @ serializable.js:80
eachKeys @ serializable.js:79
replaceWith @ type.js:38
_typeify @ store.js:661
u @ subscribe.js:153
processQueue @ subscribe.js:125
setInterval (async)
subscribeConnected @ subscribe.js:255
(anonymous) @ subscribe.js:81
m @ ember-metal.js:247
trigger @ evented.js:76
_opened @ socket.js:156
e._run @ backburner.js:804
e._join @ backburner.js:782
e.join @ backburner.js:492
y.join @ ember-metal.js:420
(anonymous) @ ember-metal.js:499
```

Reloading the page in the browser won't fix it, it will repeat the same problem.

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/17
Verified fixed
