### ISSUE TITLE
NPE when CLI is used against an URL with unverified certificate chain and no valid cacerts JSON response

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15235]
CLI version: v2.0.4

```
# ./rancher --version
rancher version v2.0.4
root@seb-rancherserver:~/rancher-v2.0.4# ./rancher login https://self-signed.badssl.com --token a:b                                                                                                                                                                                        
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7c2b33]

goroutine 1 [running]:
github.com/rancher/cli/cmd.getCertFromServer(0xc4200534a0, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/cli/cmd/login.go:263 +0x2d3
github.com/rancher/cli/cmd.loginSetup(0xc420010b00, 0xc420072200, 0xc420010b00)
        /go/src/github.com/rancher/cli/cmd/login.go:122 +0x597
github.com/rancher/cli/vendor/github.com/urfave/cli.HandleAction(0x8427a0, 0x923328, 0xc420010b00, 0x0, 0xc420053440)
        /go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:501 +0xd2
github.com/rancher/cli/vendor/github.com/urfave/cli.Command.Run(0x906bee, 0x5, 0x0, 0x0, 0xc4200470d0, 0x1, 0x1, 0x90ebc6, 0x19, 0x0, ...)
        /go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/command.go:165 +0x4bb
github.com/rancher/cli/vendor/github.com/urfave/cli.(*App).Run(0xc42010a1c0, 0xc420072200, 0x5, 0x8, 0x0, 0x0)
        /go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:259 +0x740
main.mainErr(0xc42008df70, 0x0)
        /go/src/github.com/rancher/cli/main.go:113 +0x140b
main.main()
        /go/src/github.com/rancher/cli/main.go:57 +0x22
```

**Comment by carolynhu** [comment]
Verified on CLI v2.0.4
<img width="785" alt="screen shot 2018-09-18 at 10 40 50 am" src="https://user-images.githubusercontent.com/29208297/45705804-5f358480-bb2f-11e8-8499-49efc2449bb5.png">

**Comment by carolynhu** [comment]
tested with v2.0.5-rc2: no NPE found.
root@carolyn-test-cert:~/rancher-v2.0.5-rc2# ./rancher --version
rancher version v2.0.5-rc2
root@carolyn-test-cert:~/rancher-v2.0.5-rc2# ./rancher login https://carolyn-rancher-server --token token-xxxx:xxxx
