### ISSUE TITLE
Rancher server crashed when node is draining.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#15586]
**Rancher versions:** Build from master

Setup:
DO cluster with 3 worker nodes.
Drain one of the nodes.
When the pods was still in the process of draining , rancher server container crashed and restarted.

rancher-server logs:

```
2018/09/13 23:05:48 [ERROR] nodeDrain: [santestworker3] in cluster [c-xkhlt] : pod/cattle-cluster-agent-5c769fdb64-jt5ld
pod/santest1-66b4cddc7f-8lckg
pod/santest1-66b4cddc7f-9hspm
pod/santest1-66b4cddc7f-mkgfl
pod/santest1-66b4cddc7f-nnwzn
pod/santest1-66b4cddc7f-q76kr
pod/santest1-66b4cddc7f-rt8hx
pod/default-http-backend-797c5bc547-ft8tb
pod/kube-dns-7588d5b5f5-bcbh6
pod/kube-dns-autoscaler-5db9bbb766-8khxm
pod/metrics-server-97bc649d5-wnfdz

 santestworker3
error: error when evicting pod "santest1-66b4cddc7f-q76kr": the server is currently unable to handle the request (post pods.policy santest1-66b4cddc7f-q76kr)
 Operation cannot be fulfilled on nodes.management.cattle.io "m-cxmhq": the object has been modified; please apply your changes to the latest version and try again
2018/09/13 23:05:50 [INFO] Handling backend connection request [c-xkhlt]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x380ab40]

goroutine 196538 [running]:
github.com/rancher/rancher/pkg/controllers/user/nodesyncer.(*NodeDrain).drain(0xc016df8090, 0x80affe0, 0xc007e1cac0, 0xc01484a800, 0xc01e328360)
	/go/src/github.com/rancher/rancher/pkg/controllers/user/nodesyncer/cordonfieldssyncer.go:128 +0x200
created by github.com/rancher/rancher/pkg/controllers/user/nodesyncer.(*NodeDrain).drainNode
	/go/src/github.com/rancher/rancher/pkg/controllers/user/nodesyncer/cordonfieldssyncer.go:79 +0x2d9
```

**Comment by sangeethah** [comment]
Rancher server goes into a crash loop with this exception:

```
2018/09/13 23:12:55 [INFO] registering podsecuritypolicy namespace handler for cluster c-xkhlt
2018/09/13 23:12:55 [INFO] registering podsecuritypolicy serviceaccount handler for cluster c-xkhlt
2018/09/13 23:12:55 [INFO] registering podsecuritypolicy template handler for cluster c-xkhlt
2018/09/13 23:12:55 [INFO] Starting cluster controllers for c-xkhlt
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x380ab40]

goroutine 16871 [running]:
github.com/rancher/rancher/pkg/controllers/user/nodesyncer.(*NodeDrain).drain(0xc0063503f0, 0x80affe0, 0xc010fca100, 0xc009e1f750, 0xc006460470)
	/go/src/github.com/rancher/rancher/pkg/controllers/user/nodesyncer/cordonfieldssyncer.go:128 +0x200
created by github.com/rancher/rancher/pkg/controllers/user/nodesyncer.(*NodeDrain).drainNode
	/go/src/github.com/rancher/rancher/pkg/controllers/user/nodesyncer/cordonfieldssyncer.go:79 +0x2d9


```

**Comment by sangeethah** [comment]
Tested with latest build from master.

Able to drain nodes successfully.
