### ISSUE TITLE
Panic error on catalog app deployment

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#15588]
Noticed several times on Drone. The test `test_app_namespace_annotation` creating and removing the catalog app fails, and the following panic is observed in the log:

```
goroutine 8 [chan receive]:
k8s.io/helm/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x25fad00)
    /home/darren/.gpath/3ef6bc96094c0cb608fe5ee0babfa6c6abd39686/src/k8s.io/helm/vendor/github.com/golang/glog/glog.go:879 +0x8b
created by k8s.io/helm/vendor/github.com/golang/glog.init.0
    /home/darren/.gpath/3ef6bc96094c0cb608fe5ee0babfa6c6abd39686/src/k8s.io/helm/vendor/github.com/golang/glog/glog.go:410 +0x203
goroutine 60 [syscall]:
os/signal.signal_recv(0x0)
    /home/darren/.local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
    /home/darren/.local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
    /home/darren/.local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 31 [runnable]:
internal/poll.(*pollDesc).waitRead(0xc000644518, 0xffffffffffffff00, 0x0, 0x0)
    /home/darren/.local/go/src/internal/poll/fd_poll_runtime.go:89 +0x60
internal/poll.(*FD).Accept(0xc000644500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/darren/.local/go/src/internal/poll/fd_unix.go:384 +0x1a0
```

**Comment by StrongMonkey** [comment]
@sangeethah To verify this you have to create app and watch the rancher server logs to check if there are panics in the log. This is also a race condition bug so make sure to try enough times. Also we can check if there is any panic in our ci builds.

**Comment by sangeethah** [comment]
Tested with v2.1.0-rc2
Deployed few apps (~20 ) . There were no panics reported in the logs during app deployment.
