### ISSUE TITLE
[Windows] Adding a windows node after enabling Amazon cloud provider failed

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#15593]
**Rancher versions:**
rancher/server or rancher/rancher: maiwj/rancher:625cc739
rancher/agent or rancher/rancher-agent: maiwj/rancher-agent:625cc739

**Docker version: (`docker version`,`docker info` preferred)**
linux: 17.03.2-ce
windows: 17.06.2-ee-16
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
linux: ubuntu 1604
windows: 1803
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
1. Add a custom cluster, enable Windows Support and cloud provider select Amazon
2. Add a linux node with the "All" role
3. Add a windows node
**Results:**
The linux node can be added successfully, but I added the windows node failed, and the kubelet has some strange logs.
I can't find the routing information of the windows node on the linux node.
I think this issue is related to the aws cloud provider, because windows nodes work fine if I don't enable the cloud provider.
```
I0914 02:32:01.764958    6052 kubelet_node_status.go:437] Using node IP: "172.31.23.118"
I0914 02:32:04.099893    6052 server.go:796] GET /stats/summary/: (1.0082ms) 401
goroutine 251 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc042da6690, 0x191)
        /workspace/anago-v1.10.5-beta.0.53+32ac1c9073b132/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:207 +0xe4
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc042da6690, 0x191)
        /workspace/anago-v1.10.5-beta.0.53+32ac1c9073b132/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:186 +0x3c
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Response).WriteHeader(0xc042dce0c0, 0x191)
        /workspace/anago-v1.10.5-beta.0.53+32ac1c9073b132/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/response.go:201 +0x48
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Response).WriteErrorString(0xc042dce0c0, 0x191, 0x39fcf2f, 0xc, 0x0, 0x0)
        /workspace/anago-v1.10.5-beta.0.53+32ac1c9073b132/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/response.go:181 +0x4d
k8s.io/kubernetes/pkg/kubelet/server.(*Server).InstallAuthFilter.func1(0xc042da9e90, 0xc042dce0c0, 0xc042da9f20)
        /workspace/anago-v1.10.5-beta.0.53+32ac1c9073b132/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:231 +0x802
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc042da9f20, 0xc042da9e90, 0xc042dce0c0)
        /workspace/anago-v1.10.5-beta.0.53+32ac1c9073b132/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/filter.go:19 +0x6f
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc042a7e090, 0x56f1c00, 0xc042da6690, 0xc042dbc800)
        /workspace/anago-v1.10.5-beta.0.53+32ac1c9073b132/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:274 +0x906
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).(k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.dispatch)-fm(0x56f1c00, 0xc042da6690, 0xc042dbc800)
        /workspace/anago-v1.10.5-beta.0.53+32ac1c9073b132/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:120 +0x4f
net/http.HandlerFunc.ServeHTTP(0xc04225d140, 0x56f1c00, 0xc042da6690, 0xc042dbc800)
        /usr/local/go/src/net/http/server.go:1918 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc0425c2330, 0x56f1c00, 0xc042da6690, 0xc042dbc800)
        /usr/local/go/src/net/http/server.go:2254 +0x137
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc042a7e090, 0x56f1c00, 0xc042da6690, 0xc042dbc800)
        /workspace/anago-v1.10.5-beta.0.53+32ac1c9073b132/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:292 +0x54
k8s.io/kubernetes/pkg/kubelet/server.(*Server).ServeHTTP(0xc042298d20, 0x56f1c00, 0xc042da6690, 0xc042dbc800)
        /workspace/anago-v1.10.5-beta.0.53+32ac1c9073b132/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:795 +0x10d
net/http.serverHandler.ServeHTTP(0xc0425c09c0, 0x56f2280, 0xc0429bd420, 0xc042dbc800)
        /usr/local/go/src/net/http/server.go:2619 +0xbb
net/http.(*conn).serve(0xc042d09220, 0x56f4500, 0xc042d8aa00)
        /usr/local/go/src/net/http/server.go:1801 +0x724
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2720 +0x28f

logging error output: "Unauthorized"
 [[Go-http-client/1.1] 172.31.17.7:43776]
E0914 02:32:10.072697    6052 streamwatcher.go:109] Unable to decode an event from the watch stream: read tcp 127.0.0.1:50165->127.0.0.1:6443: wsarecv: An existing connection was forcibly closed by the remote host.
E0914 02:32:10.077697    6052 streamwatcher.go:109] Unable to decode an event from the watch stream: read tcp 127.0.0.1:50165->127.0.0.1:6443: wsarecv: An existing connection was forcibly closed by the remote host.
E0914 02:32:10.077697    6052 streamwatcher.go:109] Unable to decode an event from the watch stream: read tcp 127.0.0.1:50165->127.0.0.1:6443: wsarecv: An existing connection was forcibly closed by the remote host.
E0914 02:32:11.580669    6052 helpers.go:739] eviction manager: failed to construct signal: "allocatableMemory.available" error: system container "pods" not found in metrics
W0914 02:32:11.583668    6052 helpers.go:812] eviction manager: no observation found for eviction signal nodefs.inodesFree
I0914 02:32:11.816668    6052 kuberuntime_manager.go:917] updating runtime config through cri with podcidr 10.42.3.0/24
I0914 02:32:11.818667    6052 docker_service.go:340] docker cri received runtime config &RuntimeConfig{NetworkConfig:&NetworkConfig{PodCidr:10.42.3.0/24,},}
I0914 02:32:11.819668    6052 kubelet_network.go:196] Setting Pod CIDR:  -> 10.42.3.0/24
I0914 02:32:11.822668    6052 kubelet_node_status.go:437] Using node IP: "172.31.23.118"
E0914 02:32:13.081608    6052 reflector.go:322] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to watch *v1.Pod: Get https://127.0.0.1:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dec2amaz-lg8fmra&resourceVersion=1032&timeoutSeconds=311&watch=true: read tcp 127.0.0.1:50190->127.0.0.1:6443: wsarecv: An existing connection was forcibly closed by the remote host.
E0914 02:32:21.606366    6052 helpers.go:739] eviction manager: failed to construct signal: "allocatableMemory.available" error: system container "pods" not found in metrics
W0914 02:32:21.607366    6052 helpers.go:812] eviction manager: no observation found for eviction signal nodefs.inodesFree
I0914 02:32:21.835366    6052 kubelet_node_status.go:437] Using node IP: "172.31.23.118"
E0914 02:32:28.801154    6052 streamwatcher.go:109] Unable to decode an event from the watch stream: read tcp 127.0.0.1:50194->127.0.0.1:6443: wsarecv: An existing connection was forcibly closed by the remote host.
E0914 02:32:28.808152    6052 streamwatcher.go:109] Unable to decode an event from the watch stream: read tcp 127.0.0.1:50194->127.0.0.1:6443: wsarecv: An existing connection was forcibly closed by the remote host.
E0914 02:32:28.808152    6052 streamwatcher.go:109] Unable to decode an event from the watch stream: read tcp 127.0.0.1:50194->127.0.0.1:6443: wsarecv: An existing connection was forcibly closed by the remote host.
E0914 02:32:31.621063    6052 helpers.go:739] eviction manager: failed to construct signal: "allocatableMemory.available" error: system container "pods" not found in metrics
W0914 02:32:31.621063    6052 helpers.go:812] eviction manager: no observation found for eviction signal nodefs.inodesFree
I0914 02:32:31.850064    6052 kubelet_node_status.go:437] Using node IP: "172.31.23.118"
E0914 02:32:41.635734    6052 helpers.go:739] eviction manager: failed to construct signal: "allocatableMemory.available" error: system container "pods" not found in metrics
W0914 02:32:41.637761    6052 helpers.go:812] eviction manager: no observation found for eviction signal nodefs.inodesFree
I0914 02:32:41.865758    6052 kubelet_node_status.go:437] Using node IP: "172.31.23.118"
E0914 02:32:51.651458    6052 helpers.go:739] eviction manager: failed to construct signal: "allocatableMemory.available" error: system container "pods" not found in metrics
W0914 02:32:51.666458    6052 helpers.go:812] eviction manager: no observation found for eviction signal nodefs.inodesFree
I0914 02:32:51.903459    6052 kubelet_node_status.go:437] Using node IP: "172.31.23.118"
E0914 02:33:01.519160    6052 kubelet_network.go:225] Failed to ensure that nat chain KUBE-MARK-DROP exists: error creating chain "KUBE-MARK-DROP": executable file not found in %PATH%:
E0914 02:33:01.684159    6052 helpers.go:739] eviction manager: failed to construct signal: "allocatableMemory.available" error: system container "pods" not found in metrics
W0914 02:33:01.684159    6052 helpers.go:812] eviction manager: no observation found for eviction signal nodefs.inodesFree
I0914 02:33:01.962129    6052 kubelet_node_status.go:437] Using node IP: "172.31.23.118"
I0914 02:33:04.086063    6052 server.go:796] GET /stats/summary/: (0s) 401
```
---
**Environmental information:**
**linux node:**

eth0      Link encap:Ethernet  HWaddr 02:5c:b5:cb:ae:00
          inet addr:172.31.17.7  Bcast:172.31.31.255  Mask:255.255.240.0
          inet6 addr: fe80::5c:b5ff:fecb:ae00/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:535709 errors:0 dropped:0 overruns:0 frame:0
          TX packets:223695 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:731621797 (731.6 MB)  TX bytes:38142553 (38.1 MB)

cni0      Link encap:Ethernet  HWaddr 0a:58:0a:2a:00:01
          inet addr:10.42.0.1  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::10d2:21ff:fe3a:eac9/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:26981 errors:0 dropped:0 overruns:0 frame:0
          TX packets:25607 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:9770393 (9.7 MB)  TX bytes:18964182 (18.9 MB)
**windows node:**
Ethernet adapter vEthernet (Ethernet 2):

   Connection-specific DNS Suffix  . : eu-west-1.compute.internal
   Link-local IPv6 Address . . . . . : fe80::415e:3a11:7989:871e%15
   IPv4 Address. . . . . . . . . . . : 172.31.23.118
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . : 172.31.16.1

Ethernet adapter vEthernet (cbr0_ep):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::295c:546:c09b:40aa%22
   IPv4 Address. . . . . . . . . . . : 10.42.2.2
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 10.42.2.1

**Comment by kingsd041** [comment]
@thxCode 
Tested with maiwj/rancher:db7cb551 with maiwj/rancher-agent:v0.11.9
This version can add windows nodes on AWS and I tested adding Layer-4 Load Balancer and kubernetes network, it should be fixed.
