### ISSUE TITLE
ensure-default-admin script panics when default admin user is already present.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#15613]
Rancher Server version - Latest build from master

Steps to reproduce the problem:
Execute ensure-default-admin script when default admin user is already present.

```
root@santest208now:~# docker exec ff4  ensure-default-admin
Found existing default admin user (user-kzw5v)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3aec689]

goroutine 1 [running]:
github.com/rancher/rancher/app.ensureAdminIsEnabled(0xc000ca0844, 0x4, 0xc000bca420, 0x17, 0xc000ca0876, 0xa, 0xc000ca0860, 0x5, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rancher/app/ensure_admin_user.go:126 +0x29
github.com/rancher/rancher/app.ensureDefaultAdmin.func1(0xc000118000, 0xc000118000, 0xc00138d717)
	/go/src/github.com/rancher/rancher/app/ensure_admin_user.go:65 +0x709
github.com/rancher/rancher/vendor/github.com/urfave/cli.HandleAction(0x4203000, 0x516a770, 0xc000118000, 0xc0011d2180, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/urfave/cli/app.go:502 +0xc8
github.com/rancher/rancher/vendor/github.com/urfave/cli.(*App).Run(0xc0009888c0, 0xc00006c1c0, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/urfave/cli/app.go:268 +0x5b7
github.com/rancher/rancher/app.ensureDefaultAdmin()
	/go/src/github.com/rancher/rancher/app/ensure_admin_user.go:89 +0xa0
github.com/rancher/rancher/vendor/github.com/docker/docker/pkg/reexec.Init(0x1)
	/go/src/github.com/rancher/rancher/vendor/github.com/docker/docker/pkg/reexec/reexec.go:26 +0x76
main.main()
	/go/src/github.com/rancher/rancher/main.go:32 +0x5c
```

**Comment by maxkorp** [comment]
When we create a new user, the Enabled pointer is nil, it has an assumed default of true. Since we were dereferencing the pointer, it would panic if they had not previously been explicitly enabled/disabled.

Will be made correct in #15616

**Comment by sangeethah** [comment]
Tested with latest build from master

Execute ensure-default-admin script when default admin user is already present.
No panic encountered and script reports default admin user is already present.
```
~# docker exec 2d2b ensure-default-admin
Found existing default admin user (user-2v8lz)
Existing default admin user (user-2v8lz) is already enabled
Existing default admin user (user-2v8lz) already labeled as admin
Existing default admin user (user-2v8lz) is already an admin
~# 
```
