### ISSUE TITLE
Running > 1 containers with unpulled image results in already exists

### ISSUE THREAD

**Issue by flaccid** [rancher/rancher#1563]
Fresh rancher and host. Use rancher-compose and run up 2 containers using the same image but potentially different versions (shared layers).

One of them can error out with an already exists message (either for the layer or the image). Sorry I don't have more data, it happened quickly. Not sure if this is considered an upstream issue with docker or docker compose.

**Comment by ibuildthecloud** [comment]
@flaccid My random guess sounds like this is more of a Docker issue.  Would need a bit more info.  If you have the `/var/log/rancher/agent.log` files from the Docker host the error you saw should be in there.

**Comment by deniseschannon** [comment]
We just recently added some directions on how to retrieve the `agent.log` files in our FAQs. 

http://docs.rancher.com/rancher/faqs/troubleshooting/#agent-logs

**Comment by flaccid** [comment]
I had to move on so lost the agent log in this instance. I just stood up fresh again can see similar conflicts. So rancher-compose up 2 containers, different versions so some shared layers. They wrestle until one succeeds, then eventually the other.

```
2015-07-19 01:02:43,282 ERROR agent [140097549241552] [event.py:111] 18194f2b-4891-4f08-9d59-acca57095e31 : Unknown error
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 94, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 34, in execute
    return method(req=req, **req.data.__dict__)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 454, in instance_activate
    self._do_instance_activate(instance, host, progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 516, in _do_instance_activate
    progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 539, in _create_container
    **create_config)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 485, in create_container
    return self.create_container_from_config(config, name)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 493, in create_container_from_config
    return self._result(res, True)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 126, in _result
    self._raise_for_status(response)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 122, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 404 Client Error: Not Found ("could not find image: no such id: 33f4f2e9ec4ff48a93c2b9dcf81282414c4051290647131c5e32e005c5faefdb")
2015-07-19 01:02:45,922 ERROR agent [140097549152080] [event.py:111] 185b0a14-4b4b-41e6-a16b-5ae779e54276 : Unknown error
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 94, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 34, in execute
    return method(req=req, **req.data.__dict__)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 454, in instance_activate
    self._do_instance_activate(instance, host, progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 516, in _do_instance_activate
    progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 539, in _create_container
    **create_config)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 485, in create_container
    return self.create_container_from_config(config, name)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 493, in create_container_from_config
    return self._result(res, True)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 126, in _result
    self._raise_for_status(response)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 122, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 404 Client Error: Not Found ("could not find image: no such id: 33f4f2e9ec4ff48a93c2b9dcf81282414c4051290647131c5e32e005c5faefdb")
2015-07-19 01:03:00,692 ERROR agent [140097549239952] [event.py:111] b557eb58-fd3b-4e7e-a1b9-c5873aadc4df : Unknown error
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 94, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 34, in execute
    return method(req=req, **req.data.__dict__)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 454, in instance_activate
    self._do_instance_activate(instance, host, progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 516, in _do_instance_activate
    progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 539, in _create_container
    **create_config)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 485, in create_container
    return self.create_container_from_config(config, name)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 493, in create_container_from_config
    return self._result(res, True)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 126, in _result
    self._raise_for_status(response)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 122, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 404 Client Error: Not Found ("could not find image: no such id: 33f4f2e9ec4ff48a93c2b9dcf81282414c4051290647131c5e32e005c5faefdb")
2015-07-19 01:03:21,964 ERROR agent [140097549150960] [event.py:111] 6c8333fe-186c-47b3-8eec-fa0249d80e57 : Unknown error
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 94, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 34, in execute
    return method(req=req, **req.data.__dict__)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 454, in instance_activate
    self._do_instance_activate(instance, host, progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 516, in _do_instance_activate
    progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 539, in _create_container
    **create_config)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 485, in create_container
    return self.create_container_from_config(config, name)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 493, in create_container_from_config
    return self._result(res, True)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 126, in _result
    self._raise_for_status(response)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 122, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 404 Client Error: Not Found ("could not find image: no such id: 33f4f2e9ec4ff48a93c2b9dcf81282414c4051290647131c5e32e005c5faefdb")
2015-07-19 01:03:30,770 ERROR agent [140097549150960] [event.py:111] 36254cc4-53a2-4875-9190-f056aad8565e : Unknown error
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 94, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 34, in execute
    return method(req=req, **req.data.__dict__)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 454, in instance_activate
    self._do_instance_activate(instance, host, progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 516, in _do_instance_activate
    progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 539, in _create_container
    **create_config)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 485, in create_container
    return self.create_container_from_config(config, name)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 493, in create_container_from_config
    return self._result(res, True)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 126, in _result
    self._raise_for_status(response)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 122, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 404 Client Error: Not Found ("could not find image: no such id: 33f4f2e9ec4ff48a93c2b9dcf81282414c4051290647131c5e32e005c5faefdb")
2015-07-19 01:03:45,809 ERROR agent [140097549151760] [event.py:111] df3d60a9-20fd-4587-b32d-a97ca7c44d08 : Unknown error
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 94, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 34, in execute
    return method(req=req, **req.data.__dict__)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 454, in instance_activate
    self._do_instance_activate(instance, host, progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 516, in _do_instance_activate
    progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 539, in _create_container
    **create_config)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 485, in create_container
    return self.create_container_from_config(config, name)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 493, in create_container_from_config
    return self._result(res, True)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 126, in _result
    self._raise_for_status(response)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 122, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 404 Client Error: Not Found ("could not find image: no such id: 33f4f2e9ec4ff48a93c2b9dcf81282414c4051290647131c5e32e005c5faefdb")
time="2015-07-19T01:04:01Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"062969c8503b96a66e4afb4f875a72cfef2658318c84744cd691c5e245a1a297\", From:\"flaccid/countdown_example:v2\", Time:1437267841}"
time="2015-07-19T01:04:01Z" level="info" msg="Assigning IP [10.42.113.62/16], ContainerId [062969c8503b96a66e4afb4f875a72cfef2658318c84744cd691c5e245a1a297], Pid [6699]"
time="2015-07-19T01:04:01Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"062969c8503b96a66e4afb4f875a72cfef2658318c84744cd691c5e245a1a297\", From:\"-simulated-\", Time:0}"
time="2015-07-19T01:04:01Z" level="info" msg="Container locked. Can't run StartHandler. ID: [062969c8503b96a66e4afb4f875a72cfef2658318c84744cd691c5e245a1a297]"
time="2015-07-19T01:04:06Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"8caa552a6267f344c2dea11ab2ff84cae1d6453fb1a4cb55073216175482fda4\", From:\"flaccid/countdown_example:v1\", Time:1437267846}"
time="2015-07-19T01:04:06Z" level="info" msg="Assigning IP [10.42.178.139/16], ContainerId [8caa552a6267f344c2dea11ab2ff84cae1d6453fb1a4cb55073216175482fda4], Pid [7367]"
time="2015-07-19T01:04:06Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"8caa552a6267f344c2dea11ab2ff84cae1d6453fb1a4cb55073216175482fda4\", From:\"-simulated-\", Time:0}"
time="2015-07-19T01:04:06Z" level="info" msg="Container locked. Can't run StartHandler. ID: [8caa552a6267f344c2dea11ab2ff84cae1d6453fb1a4cb55073216175482fda4]"
time="2015-07-19T01:04:09Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"a6365d48eee477e2973877dd3ff59a3e2c9dfe9cad8b90ae4a74ebb20d6d4272\", From:\"rancher/agent-instance:v0.3.1\", Time:1437267849}"
time="2015-07-19T01:04:09Z" level="info" msg="Assigning IP [10.42.140.82/16], ContainerId [a6365d48eee477e2973877dd3ff59a3e2c9dfe9cad8b90ae4a74ebb20d6d4272], Pid [7718]"
time="2015-07-19T01:04:09Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"a6365d48eee477e2973877dd3ff59a3e2c9dfe9cad8b90ae4a74ebb20d6d4272\", From:\"-simulated-\", Time:0}"
time="2015-07-19T01:04:09Z" level="info" msg="Container locked. Can't run StartHandler. ID: [a6365d48eee477e2973877dd3ff59a3e2c9dfe9cad8b90ae4a74ebb20d6d4272]"
```

**Comment by hibooboo2** [comment]
@flaccid What version of rancher/ cattle are you using?

**Comment by flaccid** [comment]
This would be with current release v0.28.0.

**Comment by deniseschannon** [comment]
@flaccid I haven't been able to produce your setup. Do you have specific images (and the versions) that you could share with me to try? Could you share your `docker-compose`?

**Comment by flaccid** [comment]
Yep, see if you can reproduce it on Ubuntu 14.04 using https://github.com/flaccid/countdown_example/blob/master/docker-compose.yml and https://github.com/flaccid/countdown_example/blob/master/rancher-compose.yml which use https://registry.hub.docker.com/u/flaccid/countdown_example/. Cheers!

**Comment by deniseschannon** [comment]
I'm able to reproduce with your setup even though it looks like you removed v1 from your file. :) In my case it ended up crashing rancher agent. 

@hibooboo2 Let me know if you want to look at my setup.

**Comment by deniseschannon** [comment]
Looking at my rancher-agent, here's the docker inspect of my rancher agent.
```
"State": {
        "Running": false,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 0,
        "ExitCode": -1,
        "Error": "[8] System error: Unit docker-50be44a13d2dd58ca4318e458dd56b09e1b73c5cf34b8a08479330dd3fdedc6e.scope already exists.",
        "StartedAt": "2015-07-28T18:45:50.961019005Z",
        "FinishedAt": "2015-07-28T18:55:08.775898927Z"
    }
```

**Comment by will-chan** [comment]
please re-test.

**Comment by deniseschannon** [comment]
Unable to reproduce with the provided files.
