### ISSUE TITLE
lb-controller slice out of bounds error

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#15674]
**Rancher versions:**
rancher/server or rancher/rancher: v1.6.10

**Infrastructure Stack versions:**
kubernetes (if applicable): 1.7.7-rancher1 

There seems to be a bug in public ips removal from ingress endpoint which panics with the following log message:

```
panic: runtime error: slice bounds out of range

goroutine 30 [running]:
github.com/rancher/lb-controller/controller/kubernetes.(*loadBalancerController).updateIngressStatus(0xc4200e8780, 0xc42027bac0, 0x13)
	/go/src/github.com/rancher/lb-controller/controller/kubernetes/kubernetes.go:306 +0xbd7
github.com/rancher/lb-controller/controller/kubernetes.(*loadBalancerController).(github.com/rancher/lb-controller/controller/kubernetes.updateIngressStatus)-fm(0xc42027bac0, 0x13)
	/go/src/github.com/rancher/lb-controller/controller/kubernetes/kubernetes.go:127 +0x3e
github.com/rancher/lb-controller/utils.(*TaskQueue).worker(0xc42012d120)
	/go/src/github.com/rancher/lb-controller/utils/utils.go:64 +0xd8
github.com/rancher/lb-controller/utils.(*TaskQueue).(github.com/rancher/lb-controller/utils.worker)-fm()
	/go/src/github.com/rancher/lb-controller/utils/utils.go:33 +0x2a
github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc4200317a8)
	/go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:84 +0x25
github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc4206cdfa8, 0x3b9aca00, 0x0, 0x1, 0xc4200790e0)
	/go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:85 +0xad
github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.Until(0xc4200317a8, 0x3b9aca00, 0xc4200790e0)
	/go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x4d
github.com/rancher/lb-controller/utils.(*TaskQueue).Run(0xc42012d120, 0x3b9aca00, 0xc4200790e0)
	/go/src/github.com/rancher/lb-controller/utils/utils.go:33 +0x5e
created by github.com/rancher/lb-controller/controller/kubernetes.(*loadBalancerController).Run
	/go/src/github.com/rancher/lb-controller/controller/kubernetes/kubernetes.go:371 +0x1c6
```

**Comment by alena1108** [comment]
The issue happens when the LB backing up ingress on rancher side, looses its public endpoints - it causes ingress addresses being updated too. Most likely it's out of bound exception

**Comment by alena1108** [comment]
Fixed in rancher/lb-service-rancher:v0.9.7

**Comment by alena1108** [comment]
Can be tested with `rancher/server:v1.6.26-rc1`

**Comment by sangeethah** [comment]
Tested with Rancher server version - v1.6.26-rc4

K8s environment - rancher/k8s:v1.12.5-rancher1-1 with 3 hosts.

Steps to reproduce the problem:
Deploy few ingress.
Power down the host (say host1) were ingress is running.
Ingress migrates to another host say host2.
During this process Ip addresses gets removed from ingress as expected .
Panic reported in this issue is not seen in rancher-ingress-controller logs.

There is a delay observed in removal of ips which is tracked in https://github.com/rancher/rancher/issues/17633
