### ISSUE TITLE
Failed to get attributes for some LDAP users

### ISSUE THREAD

**Issue by kvaps** [rancher/rancher#15757]
**Rancher versions:**
rancher/server or rancher/rancher: `v2.0.8`

**Infrastructure Stack versions:**
kubernetes: `v1.11.2`
freeipa: `4.5.4`

**Docker version: `17.03.2-ce`

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts**: Bare-metal

**Setup details**: single node rancher

**Environment Template**: Kubernetes

**Steps to Reproduce:**
I don't know for sure, but maybe it is connected with large attributes number inside LDAP user.
Some users can't login via LDAP, but some of them can

**Results:**

GUI shows:
```
No response received
```

There is an error in logs:

```
[ERROR] Failed to get attributes for uid=kvaps,cn=users,cn=accounts,dc=example,dc=org
[INFO] 2018/09/21 10:15:37 http: panic serving 10.31.1.145:53468: runtime error: invalid memory address or nil pointer dereference
[INFO] goroutine 456233 [running]:
[INFO] net/http.(*conn).serve.func1(0xc43e684dc0)
[INFO]      /usr/local/go/src/net/http/server.go:1697 +0xd0
[INFO] panic(0x49742c0, 0xbfb7c50)
[INFO]      /usr/local/go/src/runtime/panic.go:491 +0x283
[INFO] github.com/rancher/rancher/pkg/auth/providers/ldap.(*ldapProvider).getPrincipalsFromSearchResult(0xc42bb58630, 0xc43e1deaf0, 0xc43db929b0, 0xc4210c3400, 0xc43d89a5a0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
[INFO]      /go/src/github.com/rancher/rancher/pkg/auth/providers/ldap/ldap_client.go:134 +0x532
[INFO] github.com/rancher/rancher/pkg/auth/providers/ldap.(*ldapProvider).loginUser(0xc42bb58630, 0xc42a8e9390, 0xc4210c3400, 0xc43ace5290, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
[INFO]      /go/src/github.com/rancher/rancher/pkg/auth/providers/ldap/ldap_client.go:79 +0x10ad
[INFO] github.com/rancher/rancher/pkg/auth/providers/ldap.(*ldapProvider).testAndApply(0xc42bb58630, 0xc4338e9d27, 0xc, 0xc43c916c20, 0xc427a0aea0, 0x7, 0xc058aa0)
[INFO]      /go/src/github.com/rancher/rancher/pkg/auth/providers/ldap/ldap_actions.go:76 +0x516
[INFO] github.com/rancher/rancher/pkg/auth/providers/ldap.(*ldapProvider).actionHandler(0xc42bb58630, 0xc4338e9d27, 0xc, 0xc43c916c20, 0xc427a0aea0, 0x0, 0x0)
[INFO]      /go/src/github.com/rancher/rancher/pkg/auth/providers/ldap/ldap_actions.go:33 +0x1eb
[INFO] github.com/rancher/rancher/pkg/auth/providers/ldap.(*ldapProvider).(github.com/rancher/rancher/pkg/auth/providers/ldap.actionHandler)-fm(0xc4338e9d27, 0xc, 0xc43c916c20, 0xc427a0aea0, 0xc431cc0cf3, 0x7)
[INFO]      /go/src/github.com/rancher/rancher/pkg/auth/providers/ldap/ldap_provider.go:66 +0x52
[INFO] github.com/rancher/rancher/vendor/github.com/rancher/norman/api.handleAction(0xc43c916c20, 0xc427a0aea0, 0x0, 0x0)
[INFO]      /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:254 +0x62
[INFO] github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).handle(0xc42ce6e840, 0xc0304c0, 0xc43d271960, 0xc432def600, 0xc4328a58c8, 0xc4328a58d0, 0xc432def600)
[INFO]      /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:242 +0xdb
[INFO] github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP(0xc42ce6e840, 0xc0304c0, 0xc43d271960, 0xc432def600)
[INFO]      /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:171 +0x49
[INFO] github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc42c2eff10, 0xc0304c0, 0xc43d271960, 0xc432def600)
[INFO]      /go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:159 +0xed
[INFO] github.com/rancher/rancher/pkg/filter.authHandler.ServeHTTP(0xbffc880, 0xc42eb905a0, 0xbfe43c0, 0xc42c2eff10, 0x0, 0xc0304c0, 0xc43d271960, 0xc432def400)
[INFO]      /go/src/github.com/rancher/rancher/pkg/filter/filter.go:92 +0x2ed
[INFO] github.com/rancher/rancher/pkg/filter.(*authHandler).ServeHTTP(0xc42bc1b1d0, 0xc0304c0, 0xc43d271960, 0xc432def400)
[INFO]      <autogenerated>:1 +0x76
[INFO] github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc42c2efea0, 0xc0304c0, 0xc43d271960, 0xc432def400)
[INFO]      /go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:159 +0xed
[INFO] github.com/rancher/rancher/pkg/dynamiclistener.(*Server).cacheIPHandler.func1(0xc0304c0, 0xc43d271960, 0xc432def200)
[INFO]      /go/src/github.com/rancher/rancher/pkg/dynamiclistener/server.go:376 +0x103
[INFO] net/http.HandlerFunc.ServeHTTP(0xc4252c99c0, 0xc0304c0, 0xc43d271960, 0xc432def200)
[INFO]      /usr/local/go/src/net/http/server.go:1918 +0x44
[INFO] net/http.serverHandler.ServeHTTP(0xc42ba58a90, 0xc0304c0, 0xc43d271960, 0xc432def200)
[INFO]      /usr/local/go/src/net/http/server.go:2619 +0xb4
[INFO] net/http.(*conn).serve(0xc43e684dc0, 0xc034180, 0xc43d928d00)
[INFO]      /usr/local/go/src/net/http/server.go:1801 +0x71d
[INFO] created by net/http.(*Server).Serve
[INFO]      /usr/local/go/src/net/http/server.go:2720 +0x288
```

**Comment by superseb** [comment]
Can you enable debug logging on the `rancher/rancher` container (https://rancher.com/docs/rancher/v2.x/en/faq/technical/#how-can-i-enable-debug-logging) and do a successful login and an unsuccessful one? If it contains sensitive info, please remove it or you can share it in Rancher User Slack (https://slack.rancher.io)

**Comment by cjellick** [comment]
The panic comes from this code snippet:
```
	user, err := ldap.AttributesToPrincipal(entry.Attributes, result.Entries[0].DN, userScope, p.providerName, config.UserObjectClass, config.UserNameAttribute, config.UserLoginAttribute, config.GroupObjectClass, config.GroupNameAttribute)
	userPrincipal = *user
	if err != nil {
		return userPrincipal, groupPrincipals, err
	}
```
In this case, it looks like an error was returned and `user` was nil and dereferencing it via `*user` causes the panic. Simple fix is to do the error check before the dereferencing. To be safe, maybe do a nil check on user before assiging it and if it is nil, return an error.

**Comment by superseb** [comment]
@kvaps Are you able to test current master build `rancher/rancher:master`? This is not an official release, nor a release to be used in any environment, but it would help to root cause the issue you are having.

**Comment by kvaps** [comment]
Sure, give me little time

**Comment by kvaps** [comment]
Same result without changes:
```
[DEBUG] Now generating Ldap token
[DEBUG] Now creating Ldap connection
[DEBUG] Binding service account username password
[DEBUG] Binding username password
[DEBUG] Failed to determine if object is type: inetorgperson
[DEBUG] getPrincipals: user attributes: [0xc0174c2d40 0xc0174c2dc0 0xc0174c2e40 0xc0174c2e80] 
[DEBUG] SearchResult memberOf attribute {[cn=admins,cn=groups,cn=accounts,dc=example,dc=org cn=Replication Administrators,cn=privileges,cn=pbac,dc=example,dc=org ...]}
[DEBUG] Failed to determine if object is type: inetorgperson
[DEBUG] Failed to determine if object is type: groupofnames
[ERROR] Unknown error: Failed to get attributes for uid=kvaps,cn=users,cn=accounts,dc=example,dc=org
```

**Comment by kvaps** [comment]
@superseb, same result without changes:
```
[DEBUG] Now generating Ldap token
[DEBUG] Now creating Ldap connection
[DEBUG] Binding service account username password
[DEBUG] Binding username password
[DEBUG] Failed to determine if object is type: inetorgperson
[DEBUG] getPrincipals: user attributes: [0xc0174c2d40 0xc0174c2dc0 0xc0174c2e40 0xc0174c2e80] 
[DEBUG] SearchResult memberOf attribute {[cn=admins,cn=groups,cn=accounts,dc=example,dc=org cn=Replication Administrators,cn=privileges,cn=pbac,dc=example,dc=org ...]}
[DEBUG] Failed to determine if object is type: inetorgperson
[DEBUG] Failed to determine if object is type: groupofnames
[ERROR] Unknown error: Failed to get attributes for uid=kvaps,cn=users,cn=accounts,dc=example,dc=org
```

**Comment by mrajashree** [comment]
I think with the fix the code won't panic anymore. @kvaps can you confirm if your group `cn=admins,cn=groups` also has `groupofnames` value as objectClass?

**Comment by kvaps** [comment]
@mrajashree, to be true, my entry have a lot of values in `memberOf` (48 values)
Not all of them have `groupofnames` as `objectClass`.

**Comment by kvaps** [comment]
I've tried to compare users and it seems I've catch this bug.

This is good user:

```ldif
objectClass: inetorgperson
```
This is bad user:
```ldif
objectClass: inetOrgPerson
```

So seems problem in the case sensitive check for objectClasses

**Comment by kvaps** [comment]
Agree, problem is exactly here, after changing  `objectClass: inetorgperson` to `objectClass: inetOrgPerson` in rancher config, my user started working, but old one isn't working anymore.

You probably should correct check for objectClasses to be case insensitive.

**Comment by mrajashree** [comment]
@kvaps case insensitive search makes sense. But also whatever value you provide as UserObjectClass or GroupObjectClass should be one of the values for the objectClass attribute

**Comment by kvaps** [comment]
Of course it one of the values for the objectClass attribute.

The problem is that LDAP is case insensitive, but rancher see the difference between `inetorgperson` and `inetOrgPerson` - that wrong.

**Comment by mrajashree** [comment]
@kvaps I get that Rancher isn't finding it because of case sensitive search and it should be insensitive instead. My comment about the value being one of the values in objectClass was in reference to your comment where you said `Not all of them have groupofnames as objectClass.`

**Comment by sangeethah** [comment]
@mrajashree @dramich I am reopening this issue to see if we want to go with making case insensitive searches.

**Comment by kvaps** [comment]
Hi @cjellick for me still not working:
```
2018/10/02 01:36:22 [DEBUG] Failed to determine if object is type: inetorgperson
2018/10/02 01:36:22 [DEBUG] Failed to determine if object is type: groupofnames
```

```
rancher version ed7bd7d9
```
image `rancher/rancher:master`:
```
sha256:9c66711995ae2639ae629bfe0cbcc94c314618ce664cde8565e7fcf16bef1b92
```

**Comment by cjellick** [comment]
We had a glitch in our build system and I don’t know if you got a version of master with the fix in it. Can you try rancher/rancher:v2.1.0-rc8?

**Comment by cjellick** [comment]
Actually @kvaps I didnt notice you posted ther version hash. I can say definitively that that version _did not_ have the fix

**Comment by sangeethah** [comment]
Able to reproduce the issue using 	v2.0.8:

When enabling openLDAP , set the value for  Object Class as "INETOrgPerson" (default in "inetOrgPerson") in Customize Schema settings". 
This fails with Error (undefined - undefined) and following exception seen in logs:
```
18/10/03 18:33:33 [ERROR] Failed to get attributes for uid=testuser1,ou=dev,dc=us-west-2,dc=compute,dc=internal
2018/10/03 18:33:33 [INFO] 2018/10/03 18:33:33 http: panic serving 65.49.70.250:54100: runtime error: invalid memory address or nil pointer dereference
2018/10/03 18:33:33 [INFO] goroutine 254938 [running]:
2018/10/03 18:33:33 [INFO] net/http.(*conn).serve.func1(0xc423d90500)
2018/10/03 18:33:33 [INFO] 	/usr/local/go/src/net/http/server.go:1697 +0xd0
2018/10/03 18:33:33 [INFO] panic(0x49742c0, 0xbfb7c50)
2018/10/03 18:33:33 [INFO] 	/usr/local/go/src/runtime/panic.go:491 +0x283
2018/10/03 18:33:33 [INFO] github.com/rancher/rancher/pkg/auth/providers/ldap.(*ldapProvider).getPrincipalsFromSearchResult(0xc426782120, 0xc42ddfb7c0, 0xc42ddfbe50, 0xc42184e400, 0xc423d53860, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018/10/03 18:33:33 [INFO] 	/go/src/github.com/rancher/rancher/pkg/auth/providers/ldap/ldap_client.go:134 +0x532
2018/10/03 18:33:33 [INFO] github.com/rancher/rancher/pkg/auth/providers/ldap.(*ldapProvider).loginUser(0xc426782120, 0xc434ad3390, 0xc42184e400, 0xc42e568a20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018/10/03 18:33:33 [INFO] 	/go/src/github.com/rancher/rancher/pkg/auth/providers/ldap/ldap_client.go:79 +0x10ad
2018/10/03 18:33:33 [INFO] github.com/rancher/rancher/pkg/auth/providers/ldap.(*ldapProvider).testAndApply(0xc426782120, 0xc428a98f29, 0xc, 0xc42a002ac0, 0xc424c926c0, 0x8, 0xc058aa0)
2018/10/03 18:33:33 [INFO] 	/go/src/github.com/rancher/rancher/pkg/auth/providers/ldap/ldap_actions.go:76 +0x516
2018/10/03 18:33:33 [INFO] github.com/rancher/rancher/pkg/auth/providers/ldap.(*ldapProvider).actionHandler(0xc426782120, 0xc428a98f29, 0xc, 0xc42a002ac0, 0xc424c926c0, 0x0, 0x0)
2018/10/03 18:33:33 [INFO] 	/go/src/github.com/rancher/rancher/pkg/auth/providers/ldap/ldap_actions.go:33 +0x1eb
2018/10/03 18:33:33 [INFO] github.com/rancher/rancher/pkg/auth/providers/ldap.(*ldapProvider).(github.com/rancher/rancher/pkg/auth/providers/ldap.actionHandler)-fm(0xc428a98f29, 0xc, 0xc42a002ac0, 0xc424c926c0, 0xc434c0ccd4, 0x8)
2018/10/03 18:33:33 [INFO] 	/go/src/github.com/rancher/rancher/pkg/auth/providers/ldap/ldap_provider.go:66 +0x52
2018/10/03 18:33:33 [INFO] github.com/rancher/rancher/vendor/github.com/rancher/norman/api.handleAction(0xc42a002ac0, 0xc424c926c0, 0x0, 0x0)
2018/10/03 18:33:33 [INFO] 	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:254 +0x62
2018/10/03 18:33:33 [INFO] github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).handle(0xc42eea9810, 0xc0304c0, 0xc426d7f340, 0xc427e68b00, 0xc426fb38c8, 0xc426fb38d0, 0xc427e68b00)
2018/10/03 18:33:33 [INFO] 	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:242 +0xdb
2018/10/03 18:33:33 [INFO] github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP(0xc42eea9810, 0xc0304c0, 0xc426d7f340, 0xc427e68b00)
2018/10/03 18:33:33 [INFO] 	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:171 +0x49
2018/10/03 18:33:33 [INFO] github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4211f0460, 0xc0304c0, 0xc426d7f340, 0xc427e68b00)
2018/10/03 18:33:33 [INFO] 	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:159 +0xed
2018/10/03 18:33:33 [INFO] github.com/rancher/rancher/pkg/filter.authHandler.ServeHTTP(0xbffc880, 0xc42c15bc20, 0xbfe43c0, 0xc4211f0460, 0x0, 0xc0304c0, 0xc426d7f340, 0xc427e68900)
2018/10/03 18:33:33 [INFO] 	/go/src/github.com/rancher/rancher/pkg/filter/filter.go:92 +0x2ed
2018/10/03 18:33:33 [INFO] github.com/rancher/rancher/pkg/filter.(*authHandler).ServeHTTP(0xc425946fc0, 0xc0304c0, 0xc426d7f340, 0xc427e68900)
2018/10/03 18:33:33 [INFO] 	<autogenerated>:1 +0x76
2018/10/03 18:33:33 [INFO] github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc42112b8f0, 0xc0304c0, 0xc426d7f340, 0xc427e68900)
2018/10/03 18:33:33 [INFO] 	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:159 +0xed
2018/10/03 18:33:33 [INFO] github.com/rancher/rancher/pkg/dynamiclistener.(*Server).cacheIPHandler.func1(0xc0304c0, 0xc426d7f340, 0xc427e68700)
2018/10/03 18:33:33 [INFO] 	/go/src/github.com/rancher/rancher/pkg/dynamiclistener/server.go:376 +0x103
2018/10/03 18:33:33 [INFO] net/http.HandlerFunc.ServeHTTP(0xc427cd6060, 0xc0304c0, 0xc426d7f340, 0xc427e68700)
2018/10/03 18:33:33 [INFO] 	/usr/local/go/src/net/http/server.go:1918 +0x44
2018/10/03 18:33:33 [INFO] net/http.serverHandler.ServeHTTP(0xc429363e10, 0xc0304c0, 0xc426d7f340, 0xc427e68700)
2018/10/03 18:33:33 [INFO] 	/usr/local/go/src/net/http/server.go:2619 +0xb4
2018/10/03 18:33:33 [INFO] net/http.(*conn).serve(0xc423d90500, 0xc034180, 0xc42c31e300)
2018/10/03 18:33:33 [INFO] 	/usr/local/go/src/net/http/server.go:1801 +0x71d
2018/10/03 18:33:33 [INFO] created by net/http.(*Server).Serve
2018/10/03 18:33:33 [INFO] 	/usr/local/go/src/net/http/server.go:2720 +0x288
```

Tested the same scenario with rancher server version v2.1.0-rc8.
When enabling openLDAP , set the value for  Object Class as "INETOrgPerson" (default in "inetOrgPerson") in Customize Schema settings" , we are able to enable openLDAP successfully.
Able to add users to site access and they are able to log in to rancher-server as expected.

Also tried with "User Member Attribute" set to "MEMBEROf"( instead of memberOf) . Able to add groups to site access and member from the group have access to the rancher server as expected.

Tried to set attribute to a incorrect value like Object Class as "INETOrgPerson1" (default in "inetOrgPerson") in Customize Schema settings". In this case we are not able to enable openLDAP as expected and following error message is presented to user:
"Cannot locate user information for (&(objectClass=INETOrgPerson1)(uid=testuser1))"

No NullPointer Errors in logs.

**Comment by kvaps** [comment]
Hi @cjellick, this one: `rancher/rancher:v2.1.0-rc8?` is not working too
```
rancher version v2.1.0-rc8
```

but current `master` seems ok:
```
rancher version 8e7761d2
```

**Comment by coder-michaelwu** [comment]
Rancher Version: `v2.1.7`
When enabling openLDAP ,I get a error message : `Cannot locate user information for (objectClass=inetOrgPerson)`.
I Just set first options `1. Configuer an OpenLDAP server`, And the sencond options `2. Customize Schema` keeps default value.
The same setup was successful in Rancher Version 1.6.25.
