### ISSUE TITLE
TLS handshake error from IP: acme/autocert: host not configured

### ISSUE THREAD

**Issue by steve-todorov** [rancher/rancher#16081]
**Rancher versions:**
`rancher/rancher:latest:v2.1.0`
`rancher/rancher-agent:v2.1.0`

**Infrastructure Stack versions:**
kubernetes: `v.11.3-rancher1-1`

**Docker version: (`docker version`,`docker info` preferred)**
```
Containers: 39
 Running: 26
 Paused: 0
 Stopped: 13
Images: 22
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-36-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.79GiB
Name: quantum
ID: 3MB5:5ZZ5:SESA:NO65:3XJW:DDDZ:TVTF:YIWZ:EZEE:VYN7:DSIX:QH7B
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
```
Bare metal
```

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher (following steps from [documentation](https://rancher.com/docs/rancher/v2.x/en/installation/single-node/) for letsencrypt)

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
```
Kubernetes
```

**Steps to Reproduce:**
```
docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  -v /docker/rancher:/var/lib/rancher \
  -e AUDIT_LEVEL=1 \
  rancher/rancher:latest \
  --acme-domain rancher.my-domain.com

docker logs -f rancher_server_container
```

**Results:**
Between 10 and 30 log lines per second like the ones below which at some point crash Rancher and that restarts the server container. 

```
2018/10/11 13:03:53 [INFO] 2018/10/11 13:03:53 http: TLS handshake error from 109.202.0.188:53344: acme/autocert: host not configured
2018/10/11 13:03:54 [INFO] 2018/10/11 13:03:54 http: TLS handshake error from 89.197.152.162:56431: acme/autocert: host not configured
2018/10/11 13:03:54 [INFO] 2018/10/11 13:03:54 http: TLS handshake error from 89.197.152.162:42404: acme/autocert: host not configured
2018/10/11 13:03:55 [INFO] 2018/10/11 13:03:55 http: TLS handshake error from 89.197.152.162:47577: acme/autocert: host not configured
2018/10/11 13:03:56 [INFO] 2018/10/11 13:03:56 http: TLS handshake error from 89.197.152.162:58896: acme/autocert: host not configured
2018/10/11 13:03:56 [INFO] 2018/10/11 13:03:56 http: TLS handshake error from 89.197.152.162:63709: acme/autocert: host not configured
2018/10/11 13:03:56 [INFO] 2018/10/11 13:03:56 http: TLS handshake error from 89.197.152.162:59552: acme/autocert: host not configured
panic: Header called after Handler finished

goroutine 148508 [running]:
net/http.(*http2responseWriter).Header(0xc00e1da730, 0xc00374ee00)
	/usr/local/go/src/net/http/h2_bundle.go:6310 +0x99
github.com/rancher/rancher/pkg/filter.(*wrapWriter).Write.func1(0xc0115f0960, 0xc015478000, 0x35264, 0x3b757)
	/go/src/github.com/rancher/rancher/pkg/filter/filter.go:37 +0x38
created by github.com/rancher/rancher/pkg/filter.(*wrapWriter).Write
	/go/src/github.com/rancher/rancher/pkg/filter/filter.go:36 +0xb4
```

**Comment by superseb** [comment]
Can you drop the `  -e AUDIT_LEVEL=1 \` and does it still happen then?

**Comment by steve-todorov** [comment]
Thanks for your fast response! I've recreated the container removing the `-e AUDIT_LEVEL`. This did not fix the `http: TLS handshake error from IP: acme/autocert: host not configured` error, but so far it looks like it won't crash.

**Comment by steve-todorov** [comment]
I have managed to understand why we were seeing the handshake error. The machine where `rancher.my-domain.com` is hosted uses an IP which is also used for some other services we used to had. Bots are trying to index subdomains which are pointing to the same IP address. So what happens is a bot tries to access `https://some-sub-domain.my-domain.com` which resolves to the `public ip` where `rancher.my-domain.com` is hosted and currently Rancher has not been setup to respond to that request as we're migrating from 1.6. 

I confirmed my finding by doing a `curl` from outside to `https://some-sub-domain.my-domain.com` and the IP address from which I was testing appeared in the logs with the same `TLS handshake` error.

Thanks for your help and fast responses! I think we could close this although it would be good if there was a nicer message about this.

**Comment by bzd2000** [comment]
I have the same error. 
Can not reach the rancher ui by via domain name, via its IP it is working fine.

Not clear how you solved it

**Comment by D3473R** [comment]
The same error occures for me.
I can not provision any new clusters.
Tested with `ec2` and [hetzner](https://github.com/mxschmitt/ui-driver-hetzner)  as the provider.

Maybe related? #16220

My `docker-compose.yml`:
```yml
version: '3'

services:
  rancher:
    image: rancher/rancher:v2.1.1
    container_name: rancher
    network_mode: host
    restart: unless-stopped
    volumes:
      - /mnt/rancher2:/var/lib/rancher
    command: --acme-domain rancher.example.com
```
<details>
 <summary>Full rancher log</summary>

```
2018/11/19 10:23:29 [INFO] [mgmt-cluster-rbac-delete] Creating namespace c-tfmr6
2018/11/19 10:23:29 [INFO] [mgmt-cluster-rbac-delete] Creating Default project for cluster c-tfmr6
2018/11/19 10:23:29 [INFO] [mgmt-project-rbac-create] Creating namespace p-gtzwf
2018/11/19 10:23:29 [INFO] [mgmt-cluster-rbac-delete] Creating System project for cluster c-tfmr6
2018/11/19 10:23:29 [INFO] [mgmt-project-rbac-create] Creating creator projectRoleTemplateBinding for user user-2fbzl for project p-gtzwf
2018/11/19 10:23:29 [INFO] [mgmt-cluster-rbac-delete] Updating cluster c-tfmr6
2018/11/19 10:23:29 [INFO] [mgmt-project-rbac-create] Creating namespace p-hc2qs
2018/11/19 10:23:29 [INFO] [mgmt-project-rbac-create] Creating creator clusterRoleTemplateBinding for user user-2fbzl for cluster c-tfmr6
2018/11/19 10:23:29 [INFO] [mgmt-project-rbac-create] Creating creator projectRoleTemplateBinding for user user-2fbzl for project p-hc2qs
2018/11/19 10:23:29 [INFO] [mgmt-auth-crtb-controller] Setting InitialRolesPopulated condition on project p-gtzwf
2018/11/19 10:23:29 [INFO] [mgmt-auth-prtb-controller] Creating clusterRole p-gtzwf-projectowner
2018/11/19 10:23:29 [INFO] [mgmt-auth-crtb-controller] Setting InitialRolesPopulated condition on project p-hc2qs
2018/11/19 10:23:29 [INFO] [mgmt-project-rbac-create] Updating project p-gtzwf
2018/11/19 10:23:29 [INFO] [mgmt-auth-crtb-controller] Creating clusterRole c-tfmr6-clusterowner
2018/11/19 10:23:29 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for membership in project p-gtzwf for subject user-2fbzl
2018/11/19 10:23:29 [INFO] [mgmt-auth-prtb-controller] Creating clusterRole p-hc2qs-projectowner
2018/11/19 10:23:29 [INFO] [mgmt-project-rbac-create] Updating project p-hc2qs
2018/11/19 10:23:29 [INFO] [mgmt-auth-crtb-controller] Setting InitialRolesPopulated condition on cluster 
2018/11/19 10:23:29 [INFO] [mgmt-cluster-rbac-delete] Updating cluster c-tfmr6
2018/11/19 10:23:29 [INFO] [mgmt-auth-prtb-controller] Creating clusterRole c-tfmr6-clustermember
2018/11/19 10:23:29 [INFO] [mgmt-auth-crtb-controller] Creating clusterRoleBinding for membership in cluster c-tfmr6 for subject user-2fbzl
2018/11/19 10:23:29 [INFO] [mgmt-auth-prtb-controller] Creating clusterRoleBinding for membership in cluster c-tfmr6 for subject user-2fbzl
2018/11/19 10:23:29 [INFO] [mgmt-auth-crtb-controller] Creating role cluster-owner in namespace c-tfmr6
2018/11/19 10:23:29 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for membership in project p-hc2qs for subject user-2fbzl
2018/11/19 10:23:29 [INFO] [mgmt-project-rbac-create] Updating project p-gtzwf
2018/11/19 10:23:29 [INFO] [mgmt-auth-prtb-controller] Creating role project-owner in namespace c-tfmr6
2018/11/19 10:23:29 [INFO] [mgmt-project-rbac-create] Updating project p-hc2qs
2018/11/19 10:23:29 [INFO] [mgmt-auth-prtb-controller] Updating clusterRoleBinding clusterrolebinding-fr2q8 for cluster membership in cluster c-tfmr6 for subject user-2fbzl
2018/11/19 10:23:29 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for subject user-2fbzl with role project-owner in namespace 
2018/11/19 10:23:29 [INFO] [mgmt-auth-crtb-controller] Creating roleBinding for subject user-2fbzl with role cluster-owner in namespace 
2018/11/19 10:23:29 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for subject user-2fbzl with role project-owner in namespace 
2018/11/19 10:23:29 [INFO] [mgmt-project-rbac-create] Updating project p-hc2qs
2018/11/19 10:23:29 [INFO] [mgmt-auth-crtb-controller] Creating role cluster-owner in namespace p-gtzwf
2018/11/19 10:23:29 [INFO] [mgmt-auth-prtb-controller] Creating role admin in namespace p-gtzwf
2018/11/19 10:23:29 [INFO] [mgmt-auth-crtb-controller] Creating roleBinding for subject user-2fbzl with role cluster-owner in namespace 
2018/11/19 10:23:29 [INFO] [mgmt-auth-prtb-controller] Creating role project-owner in namespace p-hc2qs
2018/11/19 10:23:29 [INFO] [mgmt-auth-prtb-controller] Creating role project-owner in namespace p-gtzwf
2018/11/19 10:23:29 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for subject user-2fbzl with role admin in namespace 
2018/11/19 10:23:29 [INFO] [mgmt-auth-crtb-controller] Creating role cluster-owner in namespace p-hc2qs
2018/11/19 10:23:29 [INFO] [mgmt-auth-prtb-controller] Creating role admin in namespace p-hc2qs
2018/11/19 10:23:29 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for subject user-2fbzl with role project-owner in namespace 
2018/11/19 10:23:29 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for subject user-2fbzl with role admin in namespace 
2018/11/19 10:23:29 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for subject user-2fbzl with role project-owner in namespace 
2018/11/19 10:23:29 [INFO] [mgmt-auth-crtb-controller] Creating roleBinding for subject user-2fbzl with role cluster-owner in namespace 
2018/11/19 10:23:29 [INFO] [mgmt-cluster-rbac-delete] Updating cluster c-tfmr6
2018/11/19 10:23:29 [INFO] [mgmt-cluster-rbac-delete] Updating cluster c-tfmr6
2018/11/19 10:23:29 [INFO] [mgmt-cluster-rbac-delete] Updating cluster c-tfmr6
2018/11/19 10:23:30 [INFO] stdout: Creating CA: management-state/node/nodes/bb-8/certs/ca.pem
2018/11/19 10:23:30 [INFO] stdout: Creating client certificate: management-state/node/nodes/bb-8/certs/cert.pem
2018/11/19 10:23:31 [INFO] stdout: Running pre-create checks...
2018/11/19 10:23:31 [INFO] stdout: Creating machine...
2018/11/19 10:23:31 [INFO] stdout: (bb-8) Creating SSH key...
2018/11/19 10:23:31 [INFO] stdout: (bb-8) Creating Hetzner server...
2018/11/19 10:23:32 [INFO] stdout: (bb-8)  -> Creating server bb-8[1391215] in create_server[8279609]
2018/11/19 10:23:35 [INFO] stdout: (bb-8)  -> Server bb-8[1391215]: Waiting to come up...
2018/11/19 10:23:48 [INFO] stdout: Waiting for machine to be running, this may take a few minutes...
2018/11/19 10:23:48 [INFO] stdout: Detecting operating system of created instance...
2018/11/19 10:23:48 [INFO] stdout: Waiting for SSH to be available...
2018/11/19 10:24:19 [INFO] stdout: Detecting the provisioner...
2018/11/19 10:24:19 [INFO] stdout: Provisioning with ubuntu(systemd)...
2018/11/19 10:24:56 [INFO] stdout: Installing Docker...
2018/11/19 10:25:25 [INFO] stdout: Copying certs to the local machine directory...
2018/11/19 10:25:27 [INFO] stdout: Copying certs to the remote machine...
2018/11/19 10:25:29 [INFO] stdout: Setting Docker configuration on the remote daemon...
2018/11/19 10:25:32 [INFO] stdout: Checking connection to Docker...
2018/11/19 10:25:32 [INFO] stdout: Docker is up and running!
2018/11/19 10:25:44 [INFO] Generating and uploading node config bb-8
2018/11/19 10:25:44 [INFO] 2018/11/19 10:25:44 http: TLS handshake error from 192.0.2.0:55296: acme/autocert: host not configured
2018/11/19 10:25:44 [INFO] Provisioning cluster [c-tfmr6]
2018/11/19 10:25:44 [INFO] Creating cluster [c-tfmr6]
2018/11/19 10:25:44 [INFO] cluster [c-tfmr6] provisioning: Building Kubernetes cluster
2018/11/19 10:25:44 [INFO] cluster [c-tfmr6] provisioning: [dialer] Setup tunnel for host [192.0.2.0]
2018/11/19 10:25:44 [INFO] cluster [c-tfmr6] provisioning: [network] Deploying port listener containers
2018/11/19 10:25:44 [INFO] cluster [c-tfmr6] provisioning: [network] Pulling image [rancher/rke-tools:v0.1.15] on host [192.0.2.0]
2018/11/19 10:25:44 [INFO] 2018/11/19 10:25:44 http: TLS handshake error from 192.0.2.0:55300: acme/autocert: host not configured
2018/11/19 10:25:44 [INFO] 2018/11/19 10:25:44 http: TLS handshake error from 192.0.2.0:55304: acme/autocert: host not configured
2018/11/19 10:25:45 [INFO] 2018/11/19 10:25:45 http: TLS handshake error from 192.0.2.0:55308: acme/autocert: host not configured
2018/11/19 10:25:46 [INFO] 2018/11/19 10:25:46 http: TLS handshake error from 192.0.2.0:55340: acme/autocert: host not configured
2018/11/19 10:25:48 [INFO] 2018/11/19 10:25:48 http: TLS handshake error from 192.0.2.0:55368: acme/autocert: host not configured
2018/11/19 10:25:52 [INFO] 2018/11/19 10:25:52 http: TLS handshake error from 192.0.2.0:55370: acme/autocert: host not configured
2018/11/19 10:25:53 [INFO] cluster [c-tfmr6] provisioning: [network] Successfully pulled image [rancher/rke-tools:v0.1.15] on host [192.0.2.0]
2018/11/19 10:25:54 [INFO] cluster [c-tfmr6] provisioning: [network] Successfully started [rke-etcd-port-listener] container on host [192.0.2.0]
2018/11/19 10:25:54 [INFO] cluster [c-tfmr6] provisioning: [network] Successfully started [rke-cp-port-listener] container on host [192.0.2.0]
2018/11/19 10:25:55 [INFO] cluster [c-tfmr6] provisioning: [network] Successfully started [rke-worker-port-listener] container on host [192.0.2.0]
2018/11/19 10:25:55 [INFO] cluster [c-tfmr6] provisioning: [network] Port listener containers deployed successfully
2018/11/19 10:25:55 [INFO] cluster [c-tfmr6] provisioning: [network] Running control plane -> etcd port checks
2018/11/19 10:25:56 [INFO] cluster [c-tfmr6] provisioning: [network] Successfully started [rke-port-checker] container on host [192.0.2.0]
2018/11/19 10:25:56 [INFO] cluster [c-tfmr6] provisioning: [network] Running control plane -> worker port checks
2018/11/19 10:25:57 [INFO] cluster [c-tfmr6] provisioning: [network] Successfully started [rke-port-checker] container on host [192.0.2.0]
2018/11/19 10:25:57 [INFO] cluster [c-tfmr6] provisioning: [network] Running workers -> control plane port checks
2018/11/19 10:25:58 [INFO] cluster [c-tfmr6] provisioning: [network] Successfully started [rke-port-checker] container on host [192.0.2.0]
2018/11/19 10:25:58 [INFO] cluster [c-tfmr6] provisioning: [network] Skipping kubeapi port check
2018/11/19 10:25:58 [INFO] cluster [c-tfmr6] provisioning: [network] Removing port listener containers
2018/11/19 10:25:58 [INFO] cluster [c-tfmr6] provisioning: [remove/rke-etcd-port-listener] Successfully removed container on host [192.0.2.0]
2018/11/19 10:25:59 [INFO] 2018/11/19 10:25:59 http: TLS handshake error from 192.0.2.0:55372: acme/autocert: host not configured
2018/11/19 10:25:59 [INFO] cluster [c-tfmr6] provisioning: [remove/rke-cp-port-listener] Successfully removed container on host [192.0.2.0]
2018/11/19 10:26:00 [INFO] cluster [c-tfmr6] provisioning: [remove/rke-worker-port-listener] Successfully removed container on host [192.0.2.0]
2018/11/19 10:26:00 [INFO] cluster [c-tfmr6] provisioning: [network] Port listener containers removed successfully
2018/11/19 10:26:00 [INFO] cluster [c-tfmr6] provisioning: [certificates] Attempting to recover certificates from backup on [etcd,controlPlane] hosts
2018/11/19 10:26:00 [INFO] cluster [c-tfmr6] provisioning: [certificates] Successfully started [cert-fetcher] container on host [192.0.2.0]
2018/11/19 10:26:01 [INFO] cluster [c-tfmr6] provisioning: [certificates] No Certificate backup found on [etcd,controlPlane] hosts
2018/11/19 10:26:01 [INFO] cluster [c-tfmr6] provisioning: [certificates] Generating CA kubernetes certificates
2018/11/19 10:26:01 [INFO] cluster [c-tfmr6] provisioning: [certificates] Generating Kubernetes API server certificates
2018/11/19 10:26:01 [INFO] cluster [c-tfmr6] provisioning: [certificates] Generating Kube Controller certificates
2018/11/19 10:26:01 [INFO] cluster [c-tfmr6] provisioning: [certificates] Generating Kube Scheduler certificates
2018/11/19 10:26:01 [INFO] cluster [c-tfmr6] provisioning: [certificates] Generating Kube Proxy certificates
2018/11/19 10:26:02 [INFO] cluster [c-tfmr6] provisioning: [certificates] Generating Node certificate
2018/11/19 10:26:02 [INFO] cluster [c-tfmr6] provisioning: [certificates] Generating admin certificates and kubeconfig
2018/11/19 10:26:02 [INFO] cluster [c-tfmr6] provisioning: [certificates] Generating etcd-192.0.2.0 certificate and key
2018/11/19 10:26:03 [INFO] cluster [c-tfmr6] provisioning: [certificates] Generating Kubernetes API server aggregation layer requestheader client CA certificates
2018/11/19 10:26:03 [INFO] cluster [c-tfmr6] provisioning: [certificates] Generating Kubernetes API server proxy client certificates
2018/11/19 10:26:03 [INFO] cluster [c-tfmr6] provisioning: [certificates] Temporarily saving certs to [etcd,controlPlane] hosts
2018-11-19 10:26:07.962389 I | mvcc: store.index: compact 453157
2018-11-19 10:26:07.971374 I | mvcc: finished scheduled compaction at 453157 (took 6.234591ms)
2018/11/19 10:26:10 [INFO] cluster [c-tfmr6] provisioning: [certificates] Saved certs to [etcd,controlPlane] hosts
2018/11/19 10:26:10 [INFO] cluster [c-tfmr6] provisioning: [reconcile] Reconciling cluster state
2018/11/19 10:26:10 [INFO] cluster [c-tfmr6] provisioning: [reconcile] This is newly generated cluster
2018/11/19 10:26:10 [INFO] cluster [c-tfmr6] provisioning: [certificates] Deploying kubernetes certificates to Cluster nodes
2018/11/19 10:26:12 [INFO] 2018/11/19 10:26:12 http: TLS handshake error from 192.0.2.0:55374: acme/autocert: host not configured
2018/11/19 10:26:15 [INFO] cluster [c-tfmr6] provisioning: Successfully Deployed local admin kubeconfig at [management-state/rke/rke-047776818/kube_config_cluster.yml]
2018/11/19 10:26:15 [INFO] cluster [c-tfmr6] provisioning: [certificates] Successfully deployed kubernetes certificates to Cluster nodes
2018/11/19 10:26:15 [INFO] cluster [c-tfmr6] provisioning: Pre-pulling kubernetes images
2018/11/19 10:26:15 [INFO] cluster [c-tfmr6] provisioning: [pre-deploy] Pulling image [rancher/hyperkube:v1.11.3-rancher1] on host [192.0.2.0]
2018/11/19 10:26:38 [INFO] 2018/11/19 10:26:38 http: TLS handshake error from 192.0.2.0:55422: acme/autocert: host not configured
2018/11/19 10:27:04 [INFO] cluster [c-tfmr6] provisioning: [pre-deploy] Successfully pulled image [rancher/hyperkube:v1.11.3-rancher1] on host [192.0.2.0]
2018/11/19 10:27:04 [INFO] cluster [c-tfmr6] provisioning: Kubernetes images pulled successfully
2018/11/19 10:27:04 [INFO] cluster [c-tfmr6] provisioning: [etcd] Building up etcd plane..
2018/11/19 10:27:04 [INFO] cluster [c-tfmr6] provisioning: [etcd] Pulling image [rancher/coreos-etcd:v3.2.18] on host [192.0.2.0]
2018/11/19 10:27:07 [INFO] cluster [c-tfmr6] provisioning: [etcd] Successfully pulled image [rancher/coreos-etcd:v3.2.18] on host [192.0.2.0]
2018/11/19 10:27:08 [INFO] cluster [c-tfmr6] provisioning: [etcd] Successfully started [etcd] container on host [192.0.2.0]
2018/11/19 10:27:08 [INFO] cluster [c-tfmr6] provisioning: [etcd] Successfully started [rke-log-linker] container on host [192.0.2.0]
2018/11/19 10:27:08 [INFO] cluster [c-tfmr6] provisioning: [remove/rke-log-linker] Successfully removed container on host [192.0.2.0]
2018/11/19 10:27:08 [INFO] cluster [c-tfmr6] provisioning: [etcd] Successfully started etcd plane..
2018/11/19 10:27:08 [INFO] cluster [c-tfmr6] provisioning: [controlplane] Building up Controller Plane..
2018/11/19 10:27:09 [INFO] cluster [c-tfmr6] provisioning: [controlplane] Successfully started [kube-apiserver] container on host [192.0.2.0]
2018/11/19 10:27:09 [INFO] cluster [c-tfmr6] provisioning: [healthcheck] Start Healthcheck on service [kube-apiserver] on host [192.0.2.0]
2018/11/19 10:27:30 [INFO] 2018/11/19 10:27:30 http: TLS handshake error from 192.0.2.0:55608: acme/autocert: host not configured
2018/11/19 10:27:59 [ERROR] cluster [c-tfmr6] provisioning: [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [192.0.2.0]: Get https://localhost:6443/healthz: can not build dialer to c-tfmr6:m-p6qc2, log: I1119 10:27:26.917706       1 storage_rbac.go:276] created rolebinding.rbac.authorization.k8s.io/system:controller:bootstrap-signer in kube-public
2018/11/19 10:27:59 [ERROR] ClusterController c-tfmr6 [cluster-provisioner-controller] failed with : [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [192.0.2.0]: Get https://localhost:6443/healthz: can not build dialer to c-tfmr6:m-p6qc2, log: I1119 10:27:26.917706       1 storage_rbac.go:276] created rolebinding.rbac.authorization.k8s.io/system:controller:bootstrap-signer in kube-public
```
</details>

**Comment by nachokb** [comment]
I'm having the same issue. Ref: https://gist.github.com/nachokb/27f5f33ce7e1de261f6581a0df8efc6a (run command and rancher log).

* host has public IP;
* DNS is set up;
* I _can_ access the app if I ignore the invalid cert warnings;
* ports 80 an 443 are exposed (as per the _run_ command's `-p` arguments);
* host has just been provisioned (there are no other apps listening);
* error says `http: TLS handshake error from <PUBLIC_IP>:39010: acme/autocert: host not configured`;
  * this comes up sometimes 10 times a second;
  * port changes every time error shows up;
  * those ports are _not_ exposed, and I don't think they could be either;

I followed instructions from [Option 2-D in the Single Node Install Installation Guide](https://rancher.com/docs/rancher/v2.x/en/installation/single-node/)

**Comment by nachokb** [comment]
please check https://github.com/golang/crypto/pull/63

**Comment by nachokb** [comment]
in my case I had set it yo using a different subdomain, then changed it

also changed it in settings, but that was not enough

as it was a _new_ installation I just started over again

**Comment by superseb** [comment]
Root cause of this error is known, if this is reproducible on latest version, please supply steps to reproduce from scratch so we can investigate.
