### ISSUE TITLE
New agents unable to register with Rancher Server

### ISSUE THREAD

**Issue by shakefu** [rancher/rancher#16284]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug/Question

**Steps to reproduce (least amount of steps as possible):**

Unknown reproduction.

**Result:**

Current situation is that existing hosts already registered can reconnect, but new hosts time out during registration.

**Other details that may be helpful:**

16 days ago is our last successful registration - 8 days ago it no longer was working.

**Environment information**

Rancher Server 1.6.23

Rancher Agent 1.2.11

Non-HA Server

**Cluster information**

AWS EC2 instances running in VPC

- Docker (use `docker info`):

```
 # docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: v0.13.2 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 4.14.67-coreos
Operating System: Container Linux by CoreOS 1855.4.0 (Rhyolite)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 14.93GiB
Name: ip-172-22-222-118
ID: FJC3:IJ6R:QCM3:YNLJ:ZYOC:X7AI:2VDY:YREO:A26N:RP4G:3TPM:2X35
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

We are seeing the following in the Rancher Agent startup: 

```
sudo docker run -e CATTLE_AGENT_IP="172.22.222.118"  --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.11 https://rancher_server/v1/scripts/6ED9DB0F2FA4D07DDCAF:1514678400000:UzvsHFAk3SN7w29awlPZU29Ioig

INFO: Running Agent Registration Process, CATTLE_URL=https://rancher_server/v1
INFO: Attempting to connect to: https://rancher_server/v1
INFO: https://rancher_server/v1 is accessible
INFO: Configured Host Registration URL info: CATTLE_URL=https://rancher_server/v1 ENV_URL=https://rancher_server/v1
INFO: Inspecting host capabilities
INFO: Boot2Docker: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
Traceback (most recent call last):
  File "./register.py", line 28, in <module>
    r = client.list_register(key=key)[0]
IndexError: list index out of range
```

And also:

```
# sudo docker run -e "LOGLEVEL=DEBUG" -e CATTLE_AGENT_IP="172.22.222.118"  --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.11 https://rancher_server/v1/scripts/<SNIP>

INFO: Running Agent Registration Process, CATTLE_URL=https://rancher_server/v1
INFO: Attempting to connect to: https://rancher_server/v1
INFO: https://rancher_server/v1 is accessible
INFO: Configured Host Registration URL info: CATTLE_URL=https://rancher_server/v1 ENV_URL=https://rancher_server/v1
INFO: Inspecting host capabilities
INFO: Boot2Docker: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
Traceback (most recent call last):
  File "./register.py", line 31, in <module>
    r = client.wait_success(r, timeout=300)
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 15, in wait_success
    obj = self.wait_transitioning(obj, timeout)
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 33, in wait_transitioning
    raise Exception(msg)
Exception: Timeout waiting for [register:1r105] to be done after 300.121813059 seconds
```

Rancher Server shows the `api.register.create` event in the audit logs, with the following API entries:

```
{
"id": "1go106",
"type": "register",
"links": {
"self": "…/v2-beta/register/1go106",
"account": "…/v2-beta/register/1go106/account"
},
"actions": {
"stop": "…/v2-beta/register/1go106/?action=stop"
},
"baseType": "genericObject",
"name": null,
"state": "removed",
"accountId": "1a92",
"created": "2018-10-24T21:17:57Z",
"createdTS": 1540415877000,
"data": {
"agentId": 135367
},
"description": null,
"kind": "register",
"removeTime": "2018-10-24T21:29:50Z",
"removeTimeTS": 1540416590000,
"removed": "2018-10-24T21:23:49Z",
"removedTS": 1540416229000,
"resourceData": null,
"transitioning": "no",
"transitioningMessage": null,
"transitioningProgress": null,
"uuid": "c8d8d43f-6717-43e6-84c7-708a3d9355cd"
}
```

The entry never goes "active" and stays in "transitioning" until it is "removed".

On the Rancher Server in the cattle-debug.log the only relevant line I can find is:

```
2018-10-24 21:30:03,657 INFO  [:] [] [] [] [ecutorService-3] [.e.s.i.ProcessInstanceDispatcherImpl] Timeout on process [genericobject.create:14445292] on [107] : Waiting: credentials assigned [registeredAgent:1ra135381]
```

But I can provide full logs if needed.

**Comment by shakefu** [comment]
We're also seeing a ton of services stuck in the "Waiting: Allocated container" state.

I've confirmed the Rancher Server can reach the internal IPs set by the `CATTLE_AGENT_IP` env var:

```
root@556c897bb7f7:/var/lib/cattle/logs# ping 172.22.222.118
PING 172.22.222.118 (172.22.222.118) 56(84) bytes of data.
64 bytes from 172.22.222.118: icmp_seq=1 ttl=63 time=0.619 ms
64 bytes from 172.22.222.118: icmp_seq=2 ttl=63 time=0.587 ms
^C
--- 172.22.222.118 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1024ms
rtt min/avg/max/mdev = 0.587/0.603/0.619/0.016 ms
root@556c897bb7f7:/var/lib/cattle/logs#
```

**Comment by shakefu** [comment]
We're also seeing "Timeout getting IP Address" for a lot of containers on a single host in our cluster. It seems the DB for Rancher Server may be deadlocked?

**Comment by shakefu** [comment]
Also seeing new container instances unable to start, and errors in the Rancher Server logs:

```
2018-10-24 21:47:48,850 ERROR [0efc5ca6-f095-4cff-bdea-d97e49ac9696:14446090] [instance:156555] [instance.start->(InstanceStart)] [] [cutorService-10] [i.c.p.process.instance.InstanceStart] Failed [Dependencies readiness error instance is not running] for instance [156555]
2018-10-24 21:47:48,868 INFO  [:] [] [] [] [cutorService-15] [.e.s.i.ProcessInstanceDispatcherImpl] Timeout on process [instance.create:14446152] on [156557] : Waiting: active credentials [agent:1a135383]
2018-10-24 21:47:48,881 ERROR [0efc5ca6-f095-4cff-bdea-d97e49ac9696:14446090] [instance:156555] [instance.start] [] [cutorService-10] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.util.exception.ExecutionException: Dependencies readiness error
	at io.cattle.platform.process.instance.InstanceStart.waitForDependenciesStart(InstanceStart.java:294)
	at io.cattle.platform.process.instance.InstanceStart.handle(InstanceStart.java:118)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:470)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:421)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:415)
	at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:415)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:517)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:345)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:245)
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7)
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:242)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:184)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:157)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:116)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:113)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:113)
	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl.processExecuteWithLock(ProcessInstanceDispatcherImpl.java:136)
	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl$1.doWithLock(ProcessInstanceDispatcherImpl.java:123)
	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl$1.doWithLock(ProcessInstanceDispatcherImpl.java:120)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$4.doWithLock(AbstractLockManagerImpl.java:50)
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:25)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:47)
	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl.execute(ProcessInstanceDispatcherImpl.java:120)
	at io.cattle.platform.engine.server.ProcessInstanceReference.doRun(ProcessInstanceReference.java:59)
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by shakefu** [comment]
Possibly related, the `rancher/scheduler` server had crashed completely and now refuses to start. I'm assuming that means any containers with scheduling rules won't start either.

It is showing the "Waiting: allocated container" message in the UI, and I'm seeing the same logs:

```
2018-10-24 22:10:14,127 INFO  [:] [] [] [] [cutorService-16] [.e.s.i.ProcessInstanceDispatcherImpl] Timeout on process [instance.create:14447755] on [156580] : Waiting: active credentials [agent:1a135389]
2018-10-24 22:10:14,172 INFO  [:] [] [] [] [cutorService-14] [.e.s.i.ProcessInstanceDispatcherImpl] Timeout on process [service.upgrade:14447754] on [140] : Waiting: allocated [container:1i156580]
2018-10-24 22:10:44,132 INFO  [:] [] [] [] [ecutorService-3] [.e.s.i.ProcessInstanceDispatcherImpl] Timeout on process [instance.create:13363144] on [155503] : Waiting: active credentials [agent:1a135334]
2018-10-24 22:11:14,139 INFO  [:] [] [] [] [ecutorService-4] [.e.s.i.ProcessInstanceDispatcherImpl] Timeout on process [instance.create:14447755] on [156580] : Waiting: active credentials [agent:1a135389]
2018-10-24 22:11:14,232 INFO  [:] [] [] [] [ecutorService-2] [.e.s.i.ProcessInstanceDispatcherImpl] Timeout on process [service.upgrade:14447754] on [140] : Waiting: allocated [container:1i156580]
```

**Comment by shakefu** [comment]
Also saw similar error on `rancher/external-dns`:

```
10/24/2018 4:03:10 PMtime="2018-10-24T23:03:10Z" level=info msg="Starting Rancher External DNS service v0.7.9"
10/24/2018 4:03:10 PMtime="2018-10-24T23:03:10Z" level=fatal msg="Environment variable 'CATTLE_URL' is not set"
```

**Comment by shakefu** [comment]
I've confirmed that all the services which are failing with the missing environment variables do have `io.rancher.container.create_agent` set to 'true' in their configurations.

**Comment by shakefu** [comment]
Also seeing the same in our Healthcheck container:

```


10/24/2018 5:32:18 PMtime="2018-10-25T00:32:18Z" level=info msg="CATTLE_URL is not set"
10/24/2018 5:32:18 PMtime="2018-10-25T00:32:18Z" level=fatal msg="Can not create RancherClient, No credentials found"
10/24/2018 5:32:25 PMtime="2018-10-25T00:32:25Z" level=info msg="CATTLE_URL is not set"
10/24/2018 5:32:25 PMtime="2018-10-25T00:32:25Z" level=fatal msg="Can not create RancherClient, No credentials found"
10/24/2018 5:32:27 PMtime="2018-10-25T00:32:27Z" level=info msg="CATTLE_URL is not set"
10/24/2018 5:32:27 PMtime="2018-10-25T00:32:27Z" level=fatal msg="Can not create RancherClient, No credentials found"
```

**Comment by shakefu** [comment]
Pinging @deniseschannon in case someone is willing to help out. Our infrastructure is gently crumbling since no system services can start.

**Comment by cloudlady911** [comment]
I am having a similar issue.  New hosts are not registering with the server.  v1.6.16/agent 1.2.10

**Comment by shakefu** [comment]
For those who find this - we were unable to find a solution to the issue - something in the database had broken irreparably. We ended up doing a rebuild from scratch after removing our `cattle` database from RDS and using Terraform to recreate our service instances.

We used the `rancher` CLI to export all our service stacks before doing the rebuild, so the whole process only took a couple hour maintenance window to complete.

**Comment by hwaastad** [comment]
Hi,
I know this issue is closed but I just want to inform that we had the same issue. Loadbalancer did'nt work and no new agents could register.
We had to restart metaservices, clone scheduler (and delete the old one) and then reinstall our load balancers. Then our clusters were alright again. (phew...)
