### ISSUE TITLE
"panic: runtime error: " when upgrade is attempted with source service that does not exist.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1634]
rancher-server version - v0.29.0-rc1
rancher-compose version - v0.2.3-rc1

Attempt to upgrade with source service that does not exist - "test3" doesnot exist.

./rancher-compose -p testyo upgrade test3 test4 --batch-size 4 --scale 12 --interval "30000" -w
```
root@sangee01:/home/sangeethahariharan1/v23/rancher-compose-v0.2.3-rc1# ./rancher-compose -p testyo upgrade test3 test4 --batch-size 4 --scale 12 --interval "30000" -w
INFO[0000] Creating service test4                       
INFO[0002] Upgrading test3 to test4, scale=12           
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5f24d2]

goroutine 1 [running]:
github.com/rancherio/go-rancher/client.(*ServiceClient).ActionUpgrade(0xc208030390, 0x0, 0xc20826d500, 0x3, 0x0, 0x0)
	/source/Godeps/_workspace/src/github.com/rancherio/go-rancher/client/generated_service.go:203 +0x122
github.com/rancherio/rancher-compose/upgrade.Upgrade(0xc208040180, 0x7ffd14b9e89c, 0x5, 0x7ffd14b9e8a2, 0x5, 0x4, 0x7530, 0xc, 0x101, 0x0, ...)
	/source/gopath/src/github.com/rancherio/rancher-compose/upgrade/upgrade.go:69 +0x7d1
github.com/rancherio/rancher-compose/app.Upgrade(0xc208040180, 0xc2080b40c0)
	/source/gopath/src/github.com/rancherio/rancher-compose/app/app.go:73 +0x236
github.com/docker/libcompose/app.func·001(0xc2080b40c0)
	/source/Godeps/_workspace/src/github.com/docker/libcompose/app/app.go:30 +0x160
github.com/codegangsta/cli.Command.Run(0xa12ca0, 0x7, 0x0, 0x0, 0xacb610, 0x28, 0x0, 0x0, 0x0, 0x0, ...)
	/source/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:113 +0x1038
github.com/codegangsta/cli.(*App).Run(0xc20800ad00, 0xc20800a000, 0xd, 0xd, 0x0, 0x0)
	/source/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:156 +0xcf7
main.main()
	/source/main.go:63 +0xeee

goroutine 5 [chan send]:
github.com/docker/libcompose/logger.generateColors()
	/source/Godeps/_workspace/src/github.com/docker/libcompose/logger/colors.go:27 +0x191
created by github.com/docker/libcompose/logger.init·1
	/source/Godeps/_workspace/src/github.com/docker/libcompose/logger/colors.go:33 +0x25

goroutine 6 [syscall]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [chan receive]:
github.com/docker/libcompose/project.(*defaultListener).start(0xc2080552a0)
	/source/Godeps/_workspace/src/github.com/docker/libcompose/project/listener.go:37 +0x7b
created by github.com/docker/libcompose/project.NewProject
	/source/Godeps/_workspace/src/github.com/docker/libcompose/project/project.go:50 +0x291

goroutine 13 [runnable]:
net/http.(*persistConn).readLoop(0xc20809a210)
	/usr/src/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/src/go/src/net/http/transport.go:660 +0xc9f

goroutine 14 [select]:
net/http.(*persistConn).writeLoop(0xc20809a210)
	/usr/src/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/src/go/src/net/http/transport.go:661 +0xcbc
root@sangee01:/home/sangeethahariharan1/v23/rancher-compose-v0.2.3-rc1# 
root@sangee01:/home/sangeethahariharan1/v23/rancher-compose-v0.2.3-rc1# cat docker-compose.yml 
test3:
  tty: true
  image: sangeetha/testupgrade:v2
  stdin_open: true
test4:
  tty: true
  image: sangeetha/testupgrade:v1
  stdin_open: true
root@sangee01:/home/sangeethahariharan1/v23/rancher-compose-v0.2.3-rc1# 
```

**Comment by sangeethah** [comment]
rancher-server version - v0.30.0-rc3
rancher-compose version v0.2.4-rc1

when upgrade is attempted with source service that does not exist , following error message is presented to the user:

FATA[0000] Failed to find service test1
