### ISSUE TITLE
Could not get stats from cAdvisor

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#1638]
This is from the agent log for v0.7.10 (rancher v0.28.0) on a fresh install, so I suppose it's a known bug, but I couldn't find anything relating to it on github...

It keeps popping up, so it doesn't seem to be transient during boot only..

```
2015-07-24 12:32:52,046 ERROR cattle [140517975243664] [utils.py:126] Could not get stats from cAdvisor at: http://127.0.0.1:9344/api/v1.2/containers 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/utils.py", line 120, in _get
    with closing(urllib2.urlopen(url, timeout=5)) as resp:
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Unable to connect
```

**Comment by ebuildy** [comment]
Don't you see cadvisor running? 

In my case:

![cAdvisor]
(https://beemapp.s3-eu-west-1.amazonaws.com/dcdcfe6e-84ea-4dd5-8ad9-e68c80257ae7.jpg)

You can see it eating 5% of CPU for nothing ;-(

**Comment by kaos** [comment]
Yes, I do see `.cadvisor` running.. 
And, if I try curl on the failing URL, it works from the host:
```
[root@tsy04 ~]# curl http://127.0.0.1:9344/api/v1.2/containers 
{"name":"/","subcontainers":[{"name":"/machine.slice"},{"name":"/system.slice"},{"name":"/user.slice"}],"spec":{"creation_time":"2015-02-12T14:20:26.559999249+01:00","has_cpu":true,"cpu":{"limit":1024,"max_limit":0,"mask":"0-39"},"has_memory":true,"memory":{"limit":9223372036854775807,"swap_limit":9223372036854775807},"has_network":true,"has_filesystem":true,"has_diskio":true},"stats":[{"timestamp":"2015-07-27T11:23:04.882214384+02:00","cpu":{"usage":{"total":1067414896217566,"per_cpu_usage":[52434019916363,39848226235193,48748723186086,45457886965288,35762992587544,32752827433977,36250755483557,30610828283732,29069681497732,27885826350187,18769054187162,17244159522717,34372047961442,28877525874900,23153437024446,19525002467599,18581662583199,17663701103628,17268360579771,16971470306203,5510979081878,1484
.............
```

but from the agent container, it fails:
```
[root@tsy04 ~]# docker exec -it rancher-agent /bin/bash
root@tsy04:/# curl http://127.0.0.1:9344/api/v1.2/containers 
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

<head>
<title>500 Unable to connect</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</head>

<body>

<h1>Unable to connect</h1>

<p>Tinyproxy was unable to connect to the remote web server.</p>

<hr />

<p><em>Generated by <a href="https://banu.com/tinyproxy/">tinyproxy</a> version 1.8.3.</em></p>

</body>

</html>
root@tsy04:/# 
```

**Comment by ebuildy** [comment]
Is ** tinyproxy** from Rancher?

**Comment by kaos** [comment]
Yep.

**Comment by ebuildy** [comment]
Are you sure you don't have proxy?

For me running

````
docker exec -it rancher-agent curl http://127.0.0.1:9344/api/v1.2/containers
````

Gives me a big JSON with cool numbers.

**Comment by kaos** [comment]
this was caused by bad proxy settings. I have `http_proxy` set, but didn't have `NO_PROXY=127.0.0.1` ..

**Comment by jgato** [comment]
@kaos  I have the same issue, how did you set that NO_PROXY?

**Comment by kaos** [comment]
by passing env vars to docker when starting rancher.. `docker run -e NO_PROXY=... `
