### ISSUE TITLE
Rancher servers crashes every other hour

### ISSUE THREAD

**Issue by dhirenshumsher** [rancher/rancher#16451]
Not sure if i should have added this to https://github.com/rancher/rancher/issues/14322 ,

Rancher server crashes often and randomly due to ETCD, **leaderelection lost for cattle-controllers**

All catalogs are disabled.

This issue has creeped up since last few days after upgrading to 2.1.1 and remained even on downgrading rancher back to 2.1.0

[restarts-evryhour.log](https://github.com/rancher/rancher/files/2549850/restarts-evryhour.log)

**`2018/11/05 13:01:08 [FATAL] leaderelection lost for cattle-controllers`
`2018/11/05 15:01:09 [FATAL] leaderelection lost for cattle-controllers`
`2018/11/05 17:01:09 [FATAL] leaderelection lost for cattle-controllers`**

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.1
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 16/34
- Kubernetes version (use `kubectl version`): 1.11.3
```
[restarts-evryhour.log](https://github.com/rancher/rancher/files/2549844/restarts-evryhour.log)

```

- Docker (use `docker info`):17.06

```

E1105 17:00:22.482452       7 status.go:64] apiserver received an error that is not an metav1.Status: etcdserver: request timed out
E1105 17:00:22.483204       7 leaderelection.go:258] Failed to update lock: etcdserver: request timed out
E1105 17:00:39.483079       7 leaderelection.go:224] error retrieving resource lock kube-system/cattle-controllers: Get https://127.0.0.1:6443/api/v1/namespaces/kube-system/configmaps/cattle-controllers?timeout=30s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1105 17:00:55.501990       7 available_controller.go:295] v1.authorization.k8s.io failed with: Timeout: request did not complete within allowed duration
E1105 17:00:55.502072       7 available_controller.go:295] v3.project.cattle.io failed with: Timeout: request did not complete within allowed duration
E1105 17:00:55.502001       7 available_controller.go:295] v1beta1.policy failed with: Timeout: request did not complete within allowed duration
E1105 17:00:55.502102       7 available_controller.go:295] v1.apps failed with: Timeout: request did not complete within allowed duration
E1105 17:00:55.502111       7 available_controller.go:295] v1.rbac.authorization.k8s.io failed with: Timeout: request did not complete within allowed duration
E1105 17:01:06.896590       7 cronjob_controller.go:118] can't list Jobs: the server was unable to return a response in the time allotted, but may still be processing the request (get jobs.batch)
E1105 17:01:09.483568       7 leaderelection.go:224] error retrieving resource lock kube-system/cattle-controllers: Get https://127.0.0.1:6443/api/v1/namespaces/kube-system/configmaps/cattle-controllers?timeout=30s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1105 17:01:09.483613       7 event.go:260] Could not construct reference to: '&v1.ConfigMap{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Data:map[string]string(nil), BinaryData:map[string][]uint8(nil)}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'LeaderElection' '9a7daec675d3 stopped leading'
2018/11/05 17:01:09 [FATAL] leaderelection lost for cattle-controllers
2018/11/05 17:01:53 [INFO] Rancher version v2.1.1 is starting
2018/11/05 17:01:53 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:auto Embedded:false KubeConfig: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false NoCACerts:false ListenConfig:<nil> AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0}
2018/11/05 17:01:53 [INFO] Listening on /tmp/log.sock
2018/11/05 17:01:53 [INFO] Running etcd --peer-client-cert-auth --client-cert-auth --key-file=/etc/kubernetes/ssl/kube-etcd-127-0-0-1-key.pem --cert-file=/etc/kubernetes/ssl/kube-etcd-127-0-0-1.pem --heartbeat-interval=500 --election-timeout=5000 --data-dir=/var/lib/rancher/etcd/ --advertise-client-urls=https://127.0.0.1:2379,https://127.0.0.1:4001 --initial-advertise-peer-urls=https://127.0.0.1:2380 --initial-cluster=etcd-master=https://127.0.0.1:2380 --peer-trusted-ca-file=/etc/kubernetes/ssl/kube-ca.pem --listen-client-urls=https://0.0.0.0:2379 --listen-peer-urls=https://0.0.0.0:2380 --initial-cluster-state=new --peer-cert-file=/etc/kubernetes/ssl/kube-etcd-127-0-0-1.pem --initial-cluster-token=etcd-cluster-1 --name=etcd-master --trusted-ca-file=/etc/kubernetes/ssl/kube-ca.pem --peer-key-file=/etc/kubernetes/ssl/kube-etcd-127-0-0-1-key.pem
2018-11-05 17:01:53.937479 I | etcdmain: etcd Version: 3.2.13
2018-11-05 17:01:53.937516 I | etcdmain: Git SHA: Not provided (use ./build instead of go build)
2018-11-05 17:01:53.937526 I | etcdmain: Go Version: go1.11
2018-11-05 17:01:53.937533 I | etcdmain: Go OS/Arch: linux/amd64
2018-11-05 17:01:53.937541 I | etcdmain: setting maximum number of CPUs to 16, total number of available CPUs is 16
2018-11-05 17:01:53.938048 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2018-11-05 17:01:53.938094 I | embed: peerTLS: cert = /etc/kubernetes/ssl/kube-etcd-127-0-0-1.pem, key = /etc/kubernetes/ssl/kube-etcd-127-0-0-1-key.pem, ca = , trusted-ca = /etc/kubernetes/ssl/kube-ca.pem, client-cert-auth = true
2018-11-05 17:01:53.938644 I | embed: listening for peers on https://0.0.0.0:2380
2018-11-05 17:01:53.938699 I | embed: listening for client requests on 0.0.0.0:2379
2018-11-05 17:01:56.993564 I | etcdserver: recovered store from snapshot at index 8402990
2018-11-05 17:01:57.044412 I | mvcc: restore compact to 7109031
2018-11-05 17:01:57.057008 I | etcdserver: name = etcd-master
2018-11-05 17:01:57.057052 I | etcdserver: data dir = /var/lib/rancher/etcd/
2018-11-05 17:01:57.057065 I | etcdserver: member dir = /var/lib/rancher/etcd/member
2018-11-05 17:01:57.057075 I | etcdserver: heartbeat = 500ms
2018-11-05 17:01:57.057082 I | etcdserver: election = 5000ms
2018-11-05 17:01:57.057090 I | etcdserver: snapshot count = 100000
2018-11-05 17:01:57.057111 I | etcdserver: advertise client URLs = https://127.0.0.1:2379,https://127.0.0.1:4001
2018-11-05 17:01:57.399651 I | etcdserver: restarting member e92d66acd89ecf29 in cluster 7581d6eb2d25405b at commit index 8436253
2018-11-05 17:01:57.403984 I | raft: e92d66acd89ecf29 became follower at term 191
2018-11-05 17:01:57.404019 I | raft: newRaft e92d66acd89ecf29 [peers: [e92d66acd89ecf29], term: 191, commit: 8436253, applied: 8402990, lastindex: 8436253, lastterm: 191]
2018-11-05 17:01:57.404229 I | etcdserver/api: enabled capabilities for version 3.2
2018-11-05 17:01:57.404260 I | etcdserver/membership: added member e92d66acd89ecf29 [https://127.0.0.1:2380] to cluster 7581d6eb2d25405b from store
2018-11-05 17:01:57.404286 I | etcdserver/membership: set the cluster version to 3.2 from store
2018-11-05 17:01:57.517055 I | mvcc: restore compact to 7109031
2018-11-05 17:01:57.524114 W | auth: simple token is not cryptographically signed
2018-11-05 17:01:57.622868 I | etcdserver: starting server... [version: 3.2.13, cluster version: 3.2]
2018-11-05 17:01:57.623436 I | embed: ClientTLS: cert = /etc/kubernetes/ssl/kube-etcd-127-0-0-1.pem, key = /etc/kubernetes/ssl/kube-etcd-127-0-0-1-key.pem, ca = , trusted-ca = /etc/kubernetes/ssl/kube-ca.pem, client-cert-auth = true
2018-11-05 17:01:59.926787 I | raft: e92d66acd89ecf29 is starting a new election at term 191
2018-11-05 17:01:59.926876 I | raft: e92d66acd89ecf29 became candidate at term 192
2018-11-05 17:01:59.926895 I | raft: e92d66acd89ecf29 received MsgVoteResp from e92d66acd89ecf29 at term 192
2018-11-05 17:01:59.926920 I | raft: e92d66acd89ecf29 became leader at term 192
2018-11-05 17:01:59.926934 I | raft: raft.node: e92d66acd89ecf29 elected leader e92d66acd89ecf29 at term 192
2018-11-05 17:01:59.927334 I | etcdserver: published {Name:etcd-master ClientURLs:[https://127.0.0.1:2379 https://127.0.0.1:4001]} to cluster 7581d6eb2d25405b
2018-11-05 17:01:59.927361 I | embed: ready to serve client requests
2018-11-05 17:01:59.927667 I | embed: serving client requests on [::]:2379
2018/11/05 17:01:59 [INFO] Running kube-apiserver --insecure-port=0 --allow-privileged=true --storage-backend=etcd3 --etcd-keyfile=/etc/kubernetes/ssl/kube-node-key.pem --etcd-prefix=/registry --proxy-client-cert-file= --enable-admission-plugins=ServiceAccount,NamespaceLifecycle,LimitRanger,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds --insecure-bind-address=127.0.0.1 --secure-port=6443 --service-node-port-range=30000-32767 --tls-private-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem --kubelet-client-key=/etc/kubernetes/ssl/kube-apiserver-key.pem --advertise-address=10.43.0.1 --requestheader-allowed-names= --requestheader-group-headers= --etcd-certfile=/etc/kubernetes/ssl/kube-node.pem --requestheader-extra-headers-prefix= --requestheader-client-ca-file= --bind-address=127.0.0.1 --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --service-cluster-ip-range=10.43.0.0/16 --service-account-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --authorization-mode=Node,RBAC --requestheader-username-headers= --tls-cert-file=/etc/kubernetes/ssl/kube-apiserver.pem --etcd-servers=https://127.0.0.1:2379 --proxy-client-key-file= --endpoint-reconciler-type=lease --cloud-provider= --client-ca-file=/etc/kubernetes/ssl/kube-ca.pem --kubelet-client-certificate=/etc/kubernetes/ssl/kube-apiserver.pem --etcd-cafile=/etc/kubernetes/ssl/kube-ca.pem -v=1 --logtostderr=false --alsologtostderr=false
2018/11/05 17:01:59 [INFO] Activating driver gke
2018/11/05 17:01:59 [INFO] Activating driver gke done
2018/11/05 17:01:59 [INFO] Activating driver aks
2018/11/05 17:01:59 [INFO] Activating driver aks done
2018/11/05 17:01:59 [INFO] Activating driver eks
2018/11/05 17:01:59 [INFO] Activating driver eks done
2018/11/05 17:01:59 [INFO] Activating driver import
2018/11/05 17:01:59 [INFO] Activating driver import done
2018/11/05 17:01:59 [INFO] Activating driver rke
2018/11/05 17:01:59 [INFO] Activating driver rke done
[restful] 2018/11/05 17:02:01 log.go:33: [restful/swagger] listing is available at https://10.43.0.1:6443/swaggerapi
[restful] 2018/11/05 17:02:01 log.go:33: [restful/swagger] https://10.43.0.1:6443/swaggerui/ is mapped to folder /swagger-ui/
[restful] 2018/11/05 17:02:03 log.go:33: [restful/swagger] listing is available at https://10.43.0.1:6443/swaggerapi
[restful] 2018/11/05 17:02:03 log.go:33: [restful/swagger] https://10.43.0.1:6443/swaggerui/ is mapped to folder /swagger-ui/
2018/11/05 17:02:07 [INFO] Running kube-controller-manager --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-controller-manager.yaml --cluster-cidr=10.42.0.0/16 --leader-elect=true --pod-eviction-timeout=5m0s --allocate-node-cidrs=true --address=0.0.0.0 --enable-hostpath-provisioner=false --service-cluster-ip-range=10.43.0.0/16 --root-ca-file=/etc/kubernetes/ssl/kube-ca.pem --node-monitor-grace-period=40s --cloud-provider= --v=2 --service-account-private-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem --allow-untagged-cloud=true --configure-cloud-routes=false --use-service-account-credentials=true -v=1 --logtostderr=false --alsologtostderr=false --controllers * --controllers -resourcequota --controllers -service
2018/11/05 17:02:07 [INFO] Running in single server mode, will not peer connections
E1105 17:02:22.118400       7 controller.go:143] Unable to perform initial Kubernetes service initialization: etcdserver: request timed out
2018-11-05 17:02:22.121590 W | etcdserver: timed out waiting for read index response
panic: creating CRD store Get https://127.0.0.1:6443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions?timeout=30s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

goroutine 5141 [running]:
github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd.(*Factory).BatchCreateCRDs.func1(0xc00c16be20, 0xc00d16c700, 0x8, 0x8, 0xc0010885a0, 0xb9f0c60, 0x80c9800, 0xc00149ad40, 0x4f9600a, 0x4)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd/init.go:65 +0x2d9
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd.(*Factory).BatchCreateCRDs
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd/init.go:50 +0xce
2018/11/05 17:03:39 [INFO] Rancher version v2.1.1 is starting
2018/11/05 17:03:39 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:auto Embedded:false KubeConfig: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false NoCACerts:false ListenConfig:<nil> AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0}
2018/11/05 17:03:39 [INFO] Listening on /tmp/log.sock
2018/11/05 17:03:39 [INFO] Running etcd --peer-client-cert-auth --client-cert-auth --trusted-ca-file=/etc/kubernetes/ssl/kube-ca.pem --initial-cluster-token=etcd-cluster-1 --initial-cluster=etcd-master=https://127.0.0.1:2380 --listen-peer-urls=https://0.0.0.0:2380 --initial-cluster-state=new --advertise-client-urls=https://127.0.0.1:2379,https://127.0.0.1:4001 --listen-client-urls=https://0.0.0.0:2379 --peer-cert-file=/etc/kubernetes/ssl/kube-etcd-127-0-0-1.pem --peer-key-file=/etc/kubernetes/ssl/kube-etcd-127-0-0-1-key.pem --name=etcd-master --initial-advertise-peer-urls=https://127.0.0.1:2380 --cert-file=/etc/kubernetes/ssl/kube-etcd-127-0-0-1.pem --key-file=/etc/kubernetes/ssl/kube-etcd-127-0-0-1-key.pem --election-timeout=5000 --heartbeat-interval=500 --data-dir=/var/lib/rancher/etcd/ --peer-trusted-ca-file=/etc/kubernetes/ssl/kube-ca.pem
2018-11-05 17:03:39.742909 I | etcdmain: etcd Version: 3.2.13
2018-11-05 17:03:39.742935 I | etcdmain: Git SHA: Not provided (use ./build instead of go build)
2018-11-05 17:03:39.742945 I | etcdmain: Go Version: go1.11
2018-11-05 17:03:39.742954 I | etcdmain: Go OS/Arch: linux/amd64
2018-11-05 17:03:39.742990 I | etcdmain: setting maximum number of CPUs to 16, total number of available CPUs is 16
2018-11-05 17:03:39.743833 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2018-11-05 17:03:39.743899 I | embed: peerTLS: cert = /etc/kubernetes/ssl/kube-etcd-127-0-0-1.pem, key = /etc/kubernetes/ssl/kube-etcd-127-0-0-1-key.pem, ca = , trusted-ca = /etc/kubernetes/ssl/kube-ca.pem, client-cert-auth = true
2018-11-05 17:03:39.744490 I | embed: listening for peers on https://0.0.0.0:2380
2018-11-05 17:03:39.744548 I | embed: listening for client requests on 0.0.0.0:2379
2018-11-05 17:03:49.618453 I | etcdserver: recovered store from snapshot at index 8402990
2018-11-05 17:03:50.665411 I | mvcc: restore compact to 7109031
2018-11-05 17:03:50.679651 I | etcdserver: name = etcd-master
2018-11-05 17:03:50.679686 I | etcdserver: data dir = /var/lib/rancher/etcd/
2018-11-05 17:03:50.679699 I | etcdserver: member dir = /var/lib/rancher/etcd/member
2018-11-05 17:03:50.679707 I | etcdserver: heartbeat = 500ms
2018-11-05 17:03:50.679714 I | etcdserver: election = 5000ms
2018-11-05 17:03:50.679721 I | etcdserver: snapshot count = 100000
2018-11-05 17:03:50.679742 I | etcdserver: advertise client URLs = https://127.0.0.1:2379,https://127.0.0.1:4001
2018-11-05 17:03:51.023515 I | etcdserver: restarting member e92d66acd89ecf29 in cluster 7581d6eb2d25405b at commit index 8436257
2018-11-05 17:03:51.025492 I | raft: e92d66acd89ecf29 became follower at term 192
2018-11-05 17:03:51.025526 I | raft: newRaft e92d66acd89ecf29 [peers: [e92d66acd89ecf29], term: 192, commit: 8436257, applied: 8402990, lastindex: 8436257, lastterm: 192]
2018-11-05 17:03:51.025724 I | etcdserver/api: enabled capabilities for version 3.2
2018-11-05 17:03:51.025754 I | etcdserver/membership: added member e92d66acd89ecf29 [https://127.0.0.1:2380] to cluster 7581d6eb2d25405b from store
2018-11-05 17:03:51.025773 I | etcdserver/membership: set the cluster version to 3.2 from store
2018-11-05 17:03:56.765123 I | mvcc: restore compact to 7109031
2018-11-05 17:03:56.779554 W | auth: simple token is not cryptographically signed
2018-11-05 17:03:57.272948 I | etcdserver: starting server... [version: 3.2.13, cluster version: 3.2]
2018-11-05 17:03:57.273578 I | embed: ClientTLS: cert = /etc/kubernetes/ssl/kube-etcd-127-0-0-1.pem, key = /etc/kubernetes/ssl/kube-etcd-127-0-0-1-key.pem, ca = , trusted-ca = /etc/kubernetes/ssl/kube-ca.pem, client-cert-auth = true
2018-11-05 17:03:58.795552 I | raft: e92d66acd89ecf29 is starting a new election at term 192
2018-11-05 17:03:58.795632 I | raft: e92d66acd89ecf29 became candidate at term 193
2018-11-05 17:03:58.795652 I | raft: e92d66acd89ecf29 received MsgVoteResp from e92d66acd89ecf29 at term 193
2018-11-05 17:03:58.795671 I | raft: e92d66acd89ecf29 became leader at term 193
2018-11-05 17:03:58.795684 I | raft: raft.node: e92d66acd89ecf29 elected leader e92d66acd89ecf29 at term 193
2018-11-05 17:03:58.819613 I | etcdserver: published {Name:etcd-master ClientURLs:[https://127.0.0.1:2379 https://127.0.0.1:4001]} to cluster 7581d6eb2d25405b
2018-11-05 17:03:58.819640 I | embed: ready to serve client requests
2018-11-05 17:03:58.820058 I | embed: serving client requests on [::]:2379
2018/11/05 17:03:58 [INFO] Running kube-apiserver --client-ca-file=/etc/kubernetes/ssl/kube-ca.pem --kubelet-client-key=/etc/kubernetes/ssl/kube-apiserver-key.pem --service-node-port-range=30000-32767 --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --endpoint-reconciler-type=lease --insecure-bind-address=127.0.0.1 --requestheader-extra-headers-prefix= --requestheader-group-headers= --tls-private-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem --kubelet-client-certificate=/etc/kubernetes/ssl/kube-apiserver.pem --etcd-prefix=/registry --requestheader-allowed-names= --etcd-cafile=/etc/kubernetes/ssl/kube-ca.pem --requestheader-client-ca-file= --authorization-mode=Node,RBAC --secure-port=6443 --storage-backend=etcd3 --etcd-servers=https://127.0.0.1:2379 --proxy-client-key-file= --proxy-client-cert-file= --enable-admission-plugins=ServiceAccount,NamespaceLifecycle,LimitRanger,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds --advertise-address=10.43.0.1 --insecure-port=0 --cloud-provider= --service-cluster-ip-range=10.43.0.0/16 --tls-cert-file=/etc/kubernetes/ssl/kube-apiserver.pem --etcd-certfile=/etc/kubernetes/ssl/kube-node.pem --etcd-keyfile=/etc/kubernetes/ssl/kube-node-key.pem --requestheader-username-headers= --bind-address=127.0.0.1 --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --service-account-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem --allow-privileged=true -v=1 --logtostderr=false --alsologtostderr=false
2018/11/05 17:03:58 [INFO] Activating driver rke
2018/11/05 17:03:58 [INFO] Activating driver rke done
2018/11/05 17:03:58 [INFO] Activating driver gke
2018/11/05 17:03:58 [INFO] Activating driver gke done
2018/11/05 17:03:58 [INFO] Activating driver aks
2018/11/05 17:03:58 [INFO] Activating driver aks done
2018/11/05 17:03:58 [INFO] Activating driver eks
2018/11/05 17:03:58 [INFO] Activating driver eks done
2018/11/05 17:03:58 [INFO] Activating driver import
2018/11/05 17:03:58 [INFO] Activating driver import done
[restful] 2018/11/05 17:04:00 log.go:33: [restful/swagger] listing is available at https://10.43.0.1:6443/swaggerapi
[restful] 2018/11/05 17:04:00 log.go:33: [restful/swagger] https://10.43.0.1:6443/swaggerui/ is mapped to folder /swagger-ui/
[restful] 2018/11/05 17:04:01 log.go:33: [restful/swagger] listing is available at https://10.43.0.1:6443/swaggerapi
[restful] 2018/11/05 17:04:01 log.go:33: [restful/swagger] https://10.43.0.1:6443/swaggerui/ is mapped to folder /swagger-ui/
2018/11/05 17:04:05 [INFO] Running in single server mode, will not peer connections
2018/11/05 17:04:05 [INFO] Running kube-controller-manager --leader-elect=true --root-ca-file=/etc/kubernetes/ssl/kube-ca.pem --allow-untagged-cloud=true --allocate-node-cidrs=true --cluster-cidr=10.42.0.0/16 --configure-cloud-routes=false --node-monitor-grace-period=40s --pod-eviction-timeout=5m0s --service-cluster-ip-range=10.43.0.0/16 --service-account-private-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem --enable-hostpath-provisioner=false --v=2 --cloud-provider= --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-controller-manager.yaml --address=0.0.0.0 --use-service-account-credentials=true -v=1 --logtostderr=false --alsologtostderr=false --controllers * --controllers -resourcequota --controllers -service
2018/11/05 17:04:06 [INFO] Starting API controllers
2018/11/05 17:04:06 [INFO] Listening on :443
2018/11/05 17:04:06 [INFO] Listening on :80
2018/11/05 17:04:06 [INFO] Starting catalog controller
2018/11/05 17:04:06 [INFO] Stopping cluster agent for c-8z7g7
2018/11/05 17:04:06 [ERROR] ClusterController c-8z7g7 [user-controllers-controller] failed with : failed to start user controllers for cluster c-8z7g7: failed to contact server: Get https://10.113.32.244:6443/version?timeout=30s: waiting for cluster agent to connect
2018/11/05 17:04:06 [INFO] Starting management controllers
2018/11/05 17:04:06 [INFO] Stopping cluster agent for c-8z7g7
2018/11/05 17:04:06 [ERROR] ClusterController c-8z7g7 [user-controllers-controller] failed with : failed to start user controllers for cluster c-8z7g7: failed to contact server: Get https://10.113.32.244:6443/version?timeout=30s: waiting for cluster agent to connect
2018/11/05 17:04:07 [INFO] Stopping cluster agent for c-8z7g7
2018/11/05 17:04:07 [ERROR] ClusterController c-8z7g7 [user-controllers-controller] failed with : failed to start user controllers for cluster c-8z7g7: failed to contact server: Get https://10.113.32.244:6443/version?timeout=30s: waiting for cluster agent to connect
2018/11/05 17:04:07 [INFO] Reconciling GlobalRoles
2018/11/05 17:04:07 [INFO] Reconciling RoleTemplates
2018/11/05 17:04:08 [INFO] Rancher startup complete
2018/11/05 17:04:09 [ERROR] ClusterController c-8z7g7 [user-controllers-controller] failed with : failed to start user controllers for cluster c-8z7g7: failed to contact server: Get https://10.113.32.244:6443/version?timeout=30s: waiting for cluster agent to connect
time="2018-11-05 17:04:11" level=info msg="Telemetry Client v0.5.1"
time="2018-11-05 17:04:11" level=info msg="Listening on 0.0.0.0:8114"
2018/11/05 17:04:12 [INFO] Handling backend connection request [c-8z7g7]
2018/11/05 17:04:12 [INFO] Handling backend connection request [c-8z7g7:m-4e85d16a18cc]
2018/11/05 17:04:12 [INFO] Handling backend connection request [c-8z7g7]
2018/11/05 17:04:12 [INFO] Handling backend connection request [c-8z7g7]
2018/11/05 17:04:12 [INFO] Handling backend connection request [c-8z7g7:m-39952c490128]
2018/11/05 17:04:12 [INFO] Handling backend connection request [c-8z7g7]
2018/11/05 17:04:13 [INFO] Registering project network policy
2018/11/05 17:04:13 [INFO] Registering namespaceHandler for adding labels
2018/11/05 17:04:13 [INFO] registering podsecuritypolicy cluster handler for cluster c-8z7g7
2018/11/05 17:04:13 [INFO] registering podsecuritypolicy project handler for cluster c-8z7g7
2018/11/05 17:04:13 [INFO] registering podsecuritypolicy namespace handler for cluster c-8z7g7
2018/11/05 17:04:13 [INFO] registering podsecuritypolicy serviceaccount handler for cluster c-8z7g7
2018/11/05 17:04:13 [INFO] registering podsecuritypolicy template handler for cluster c-8z7g7
2018/11/05 17:04:13 [INFO] Starting cluster controllers for c-8z7g7
2018/11/05 17:04:13 [INFO] Starting cluster agent for c-8z7g7 [owner=true]

```

**Comment by cjellick** [comment]
Do you think you are running out of diskpace or memory on the host running rancher?
For disk run:
```
df -h
```
Fore memory run:
```
free
```

**Comment by ibuildthecloud** [comment]
I wonder if the rancher server is effectively stuck in a loop and keeps updating etcd.  Can you turn on debug logs by doing `docker exec -it ${CONTAINER_ID}| loglevel --set debug`.  The look at the logs from the docker container.  It it is printing a lot of logs very fast it is most likely stuck in a loop.

**Comment by dhirenshumsher** [comment]
This can be closed, seems like the block storage for rancher volume was the issue. Moved rancher to new storage and have since the issue since.

**Comment by cjellick** [comment]
ok, thanks for getting back to us. closing
