### ISSUE TITLE
Halt / Destroy container with downed host causes rancher to crash

### ISSUE THREAD

**Issue by haswalt** [rancher/rancher#1660]
I'm not sure if this is the same as another bug about too many threads getting opened but I tried to stop and then delete a container on a host that was currently down.

I would expect 2 things:

1) Rancher to detect the downed host almost immediately and update the UI to reflect this
2) Pause all operations on this host until it comes back

Instead the UI showed the host as active and up for about 10 minutes after it was downed and continued to attempt to stop the container. This then cashed the rancher server with out of memory errors:

```
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x69f177

goroutine 0 [idle]:

goroutine 1 [running]:
runtime.switchtoM()
	/usr/src/go/src/runtime/asm_amd64.s:198 fp=0xc20801a798 sp=0xc20801a790
runtime.main()
	/usr/src/go/src/runtime/proc.go:32 +0x58 fp=0xc20801a7e0 sp=0xc20801a798
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801a7e8 sp=0xc20801a7e0

rax     0x0
rbx     0xb912a8
rcx     0xffffffffffffffff
rdx     0x6
rdi     0x637
rsi     0x637
rbp     0x6dbbd2
rsp     0x7ffcebdfe3d8
r8      0xa
r9      0xfb7880
r10     0x8
r11     0x202
r12     0xfb9bc0
r13     0x6514b0
r14     0x651540
r15     0x0
rip     0x69f177
rflags  0x202
cs      0x33
fs      0x0
gs      0x0
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xb98497)
	/usr/src/go/src/runtime/panic.go:491 +0xad fp=0x7ffe5d1ba748 sp=0x7ffe5d1ba718
runtime.SysMap(0xc208000000, 0x100000, 0x0, 0xbba0f8)
	/usr/src/go/src/runtime/mem_linux.c:149 +0x98 fp=0x7ffe5d1ba780 sp=0x7ffe5d1ba748
runtime.MHeap_SysAlloc(0xbbf7e0, 0x100000, 0x42dda2)
	/usr/src/go/src/runtime/malloc.c:284 +0x124 fp=0x7ffe5d1ba7d8 sp=0x7ffe5d1ba780
MHeap_Grow(0xbbf7e0, 0x8, 0x0)
	/usr/src/go/src/runtime/mheap.c:398 +0x58 fp=0x7ffe5d1ba818 sp=0x7ffe5d1ba7d8
MHeap_AllocSpanLocked(0xbbf7e0, 0x1, 0x0)
	/usr/src/go/src/runtime/mheap.c:298 +0x365 fp=0x7ffe5d1ba858 sp=0x7ffe5d1ba818
mheap_alloc(0xbbf7e0, 0x1, 0x12, 0x0)
	/usr/src/go/src/runtime/mheap.c:190 +0x121 fp=0x7ffe5d1ba880 sp=0x7ffe5d1ba858
runtime.MHeap_Alloc(0xbbf7e0, 0x1, 0x10000000012, 0x40d79e)
	/usr/src/go/src/runtime/mheap.c:240 +0x66 fp=0x7ffe5d1ba8b8 sp=0x7ffe5d1ba880
MCentral_Grow(0xbc7558, 0x0)
	/usr/src/go/src/runtime/mcentral.c:197 +0x8b fp=0x7ffe5d1ba920 sp=0x7ffe5d1ba8b8
runtime.MCentral_CacheSpan(0xbc7558, 0x0)
	/usr/src/go/src/runtime/mcentral.c:85 +0x167 fp=0x7ffe5d1ba958 sp=0x7ffe5d1ba920
runtime.MCache_Refill(0x7f1d9befa000, 0x12, 0x7c)
	/usr/src/go/src/runtime/mcache.c:90 +0xa0 fp=0x7ffe5d1ba980 sp=0x7ffe5d1ba958
runtime.mcacheRefill_m()
	/usr/src/go/src/runtime/malloc.c:368 +0x57 fp=0x7ffe5d1ba9a0 sp=0x7ffe5d1ba980
runtime.onM(0x87a820)
	/usr/src/go/src/runtime/asm_amd64.s:273 +0x9a fp=0x7ffe5d1ba9a8 sp=0x7ffe5d1ba9a0
runtime.mallocgc(0x120, 0x7cd440, 0x0, 0x7f1d00000000)
	/usr/src/go/src/runtime/malloc.go:178 +0x849 fp=0x7ffe5d1baa58 sp=0x7ffe5d1ba9a8
runtime.newobject(0x7cd440, 0x7f1d9befa000)
	/usr/src/go/src/runtime/malloc.go:353 +0x49 fp=0x7ffe5d1baa80 sp=0x7ffe5d1baa58
runtime.newG(0x426b6a)
	/usr/src/go/src/runtime/proc.go:233 +0x2a fp=0x7ffe5d1baa98 sp=0x7ffe5d1baa80
allocg(0xba9b20)
	/usr/src/go/src/runtime/proc.c:925 +0x1f fp=0x7ffe5d1baaa8 sp=0x7ffe5d1baa98
runtime.malg(0x8000, 0xba9ce0)
	/usr/src/go/src/runtime/proc.c:2106 +0x1f fp=0x7ffe5d1baad8 sp=0x7ffe5d1baaa8
runtime.mpreinit(0xbaa300)
	/usr/src/go/src/runtime/os_linux.c:219 +0x27 fp=0x7ffe5d1baaf0 sp=0x7ffe5d1baad8
mcommoninit(0xbaa300)
	/usr/src/go/src/runtime/proc.c:201 +0xc9 fp=0x7ffe5d1bab18 sp=0x7ffe5d1baaf0
runtime.schedinit()
	/usr/src/go/src/runtime/proc.c:138 +0x55 fp=0x7ffe5d1bab40 sp=0x7ffe5d1bab18
runtime.rt0_go(0x7ffe5d1bac48, 0x1, 0x7ffe5d1bac48, 0x4002a8, 0x651020, 0x0, 0x100000000, 0x7ffe5d1bac48, 0x43e980, 0x4002a8, ...)
	/usr/src/go/src/runtime/asm_amd64.s:95 +0x116 fp=0x7ffe5d1bab48 sp=0x7ffe5d1bab40
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xb98497)
	/usr/src/go/src/runtime/panic.go:491 +0xad fp=0x7ffe10d95868 sp=0x7ffe10d95838
runtime.SysMap(0xc208000000, 0x100000, 0x0, 0xbba0f8)
	/usr/src/go/src/runtime/mem_linux.c:149 +0x98 fp=0x7ffe10d958a0 sp=0x7ffe10d95868
runtime.MHeap_SysAlloc(0xbbf7e0fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xaae0f7)
	/usr/src/go/src/runtime/panic.go:491 +0xad fp=0x7ffd1b8a7638 sp=0x7ffd1b8a7608
runtime.SysMap(0xc208000000, 0x100000, 0x7ffd1b8a7800, 0xad2c38)
	/usr/src/go/src/runtime/mem_linux.c:149 +0x98 fp=0x7ffd1b8a7670 sp=0x7ffd1b8a7638
runtime.MHeap_SysAlloc(0xad8320, 0x100000, 0x42d942)
	/usr/src/go/src/runtime/malloc.c:284 +0x124 fp=0x7ffd1b8a76c8 sp=0x7ffd1b8a7670
MHeap_Grow(0xad8320, 0x8, 0x0)
	/usr/src/go/src/runtime/mheap.c:398 +0x58 fp=0x7ffd1b8a7708 sp=0x7ffd1b8a76c8
MHeap_AllocSpanLocked(0xad8320, 0x1, 0x1f25bc2)
	/usr/src/go/src/runtime/mheap.c:298 +0x365 fp=0x7ffd1b8a7748 sp=0x7ffd1b8a7708
mheap_alloc(0xad8320, 0x1, 0x7f0000000012, 0x7f3e660cbffe)
```

Testing with the latest image from yesterday - cattle 0.64.0

**Comment by ebuildy** [comment]
How much memory server has?

**Comment by haswalt** [comment]
Only 512mb at the moment but it runs fine up until this point. It seems to be caused by an error in communication with he host / container. Might also be a race condition which causes lots of threads to be spawned which eats all the available memory. Will try and reproduce on 1gb image

**Comment by deniseschannon** [comment]
We recommend using at least 1GB of memory with Rancher server. http://docs.rancher.com/rancher/installing-rancher/installing-server/#requirements

I tested your scenario with 1GB and had no issues with Rancher detecting that the host was down. In this case, we show that the host is in a "Reconnecting" state with a ? mark icon.

Any actions performed on an unconnected host will occur when/if the host gets back to an active state. In your case, your host was deleted, but in other use cases, the host might be down and just needs to rebooted. 

We're currently focusing on adding new features into Rancher, but we will be working on performance improvements before v1.0.0

**Comment by haswalt** [comment]
seems reasonable, however when I tried to retry the same scenario after resizing my VM I hit my other bug again: #1383 which is a pretty big blocker since it breaks the UI and later interaction. IE my env is now in a position that it will never start a container even on fresh hosts as something gets stuck.
