### ISSUE TITLE
Panic seen in logs when provisioning cluster.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#16682]
Rancher server version - v2.1.2-rc13

Steps to reproduce the problem:

Provision a 1 node DO cluster.

Cluster provisioning succeeded . But following panic is seen in logs: 
```
2018/11/22 00:32:47 [INFO] cluster [c-5txzx] provisioning: [worker] Successfully started [rke-log-linker] container on host [<ip>]
2018/11/22 00:32:49 [INFO] 2018/11/22 00:32:49 http: panic serving <ip>:59674: runtime error: invalid memory address or nil pointer dereference
2018/11/22 00:32:49 [INFO] goroutine 21496615 [running]:
2018/11/22 00:32:49 [INFO] net/http.(*conn).serve.func1(0xc01f5a1a40)
2018/11/22 00:32:49 [INFO]     /usr/local/go/src/net/http/server.go:1746 +0xd0
2018/11/22 00:32:49 [INFO] panic(0x4590140, 0xba68cd0)
2018/11/22 00:32:49 [INFO]     /usr/local/go/src/runtime/panic.go:513 +0x1b9
2018/11/22 00:32:49 [INFO] github.com/rancher/rancher/pkg/api/store/cluster.(*Store).ByID(0xc007f6ab40, 0xc019f39b00, 0xc0095fddc0, 0xc0223db58d, 0x7, 0x4fd9aa5, 0xc01acd1768, 0x3938515)
2018/11/22 00:32:49 [INFO]     /go/src/github.com/rancher/rancher/pkg/api/store/cluster/cluster_store.go:76 +0xc2
2018/11/22 00:32:49 [INFO] github.com/rancher/rancher/vendor/github.com/rancher/norman/store/wrapper.(*StoreWrapper).ByID(0xc0083266e0, 0xc019f39b00, 0xc0095fddc0, 0xc0223db58d, 0x7, 0xc00bd4c060, 0x4fd9aa5, 0xa3f552)
2018/11/22 00:32:49 [INFO]     /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/wrapper/wrapper.go:24 +0x68
2018/11/22 00:32:49 [INFO] github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler.ListHandler(0xc019f39b00, 0x51c5910, 0xc0095fddc0, 0x0)
2018/11/22 00:32:49 [INFO]     /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler/list.go:28 +0xa2
2018/11/22 00:32:49 [INFO] github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).handle(0xc0004bafd0, 0x81109a0, 0xc05e91da40, 0xc017562f00, 0xc007e3d700, 0xc0051a42d0, 0xc01acd1908)
2018/11/22 00:32:49 [INFO]     /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:240 +0x2a2
2018/11/22 00:32:49 [INFO] github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP(0xc0004bafd0, 0x81109a0, 0xc05e91da40, 0xc017562f00)
2018/11/22 00:32:49 [INFO]     /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:171 +0x49
2018/11/22 00:32:49 [INFO] github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00076be30, 0x81109a0, 0xc05e91da40, 0xc017562f00)
2018/11/22 00:32:49 [INFO]     /go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:159 +0xf1
2018/11/22 00:32:49 [INFO] github.com/rancher/rancher/pkg/filter.authHandler.ServeHTTP(0x80d30e0, 0xc00b322b40, 0x80c4fc0, 0xc00076be30, 0x0, 0x81109a0, 0xc05e91da40, 0xc017562d00)
2018/11/22 00:32:49 [INFO]     /go/src/github.com/rancher/rancher/pkg/filter/filter.go:92 +0x2e5
2018/11/22 00:32:49 [INFO] github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00076bdc0, 0x81109a0, 0xc05e91da40, 0xc017562d00)
2018/11/22 00:32:49 [INFO]     /go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:159 +0xf1

2018/11/22 00:32:49 [INFO] github.com/rancher/rancher/pkg/dynamiclistener.(*Server).cacheIPHandler.func1(0x81109a0, 0xc05e91da40, 0xc017562b00)
2018/11/22 00:32:49 [INFO]     /go/src/github.com/rancher/rancher/pkg/dynamiclistener/server.go:382 +0x101
2018/11/22 00:32:49 [INFO] net/http.HandlerFunc.ServeHTTP(0xc008dc8b40, 0x81109a0, 0xc05e91da40, 0xc017562b00)
2018/11/22 00:32:49 [INFO]     /usr/local/go/src/net/http/server.go:1964 +0x44
2018/11/22 00:32:49 [INFO] net/http.serverHandler.ServeHTTP(0xc0101729c0, 0x81109a0, 0xc05e91da40, 0xc017562b00)
2018/11/22 00:32:49 [INFO]     /usr/local/go/src/net/http/server.go:2741 +0xab
2018/11/22 00:32:49 [INFO] net/http.(*conn).serve(0xc01f5a1a40, 0x8119a60, 0xc0554aca80)
2018/11/22 00:32:49 [INFO]     /usr/local/go/src/net/http/server.go:1847 +0x646
2018/11/22 00:32:49 [INFO] created by net/http.(*Server).Serve
2018/11/22 00:32:49 [INFO]     /usr/local/go/src/net/http/server.go:2851 +0x2f5
```

**Comment by alena1108** [comment]
@maxkorp looks like this panic happens due to the recent changes done in `cluster_store.go` (defaulting snapshots)

**Comment by sangeethah** [comment]
Tested with latest build from master (Nov 26) .
There is no panic in server logs when clusters get provisioned.
