### ISSUE TITLE
Error in HTTP GET to [https://git.rancher.io/charts/index.yaml]

### ISSUE THREAD

**Issue by Celestialdeath99** [rancher/rancher#16697]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**
Follow the procedure exactly as outlined in [https://rancher.com/docs/rancher/v2.x/en/installation/ha/](https://rancher.com/docs/rancher/v2.x/en/installation/ha/) for a HA install and then in section 4 _(Install Rancher)_ I have added `--set tls=external` for TLS Termination on the Load Balancer.

**Result:**
The install completed without any errors and I have been able to access the installation, however I am unable to load any of the catalogs.
![image](https://user-images.githubusercontent.com/6267549/48962495-4342ca80-ef46-11e8-9ddb-4092326e9431.png)
_NOTE: In the image above, the blacked out section is my domain name._

**Other details that may be helpful:**
I have followed the guide exactly as it goes, and I did not get any errors during install and all the nodes report healthy with no issues. I can access the installation with no issue on my domain. My load balancer is my pfsense firewall using the HAProxy service. My SSL certificates are provided through the ACME Certificated function on pfsense and are issued by LetsEncrypt. I have a few other subdomains running there as well, and HAProxy redirects to the correct backend servers based on the domain entered. I had a previous version of rancher running on a single server without HA and used the same setup for redirecting to the actual server and I had no issues. Can someone please help me figure out why this is not working? I am not the most familiar with rancher and am trying it out to see if I want to use it for some projects, but I need the catalog to work.

**Environment information**
- Rancher version: _2.1.1_
- Installation option: _HA_

**Comment by Celestialdeath99** [comment]
After working with it some more I have found that it seems to be unable to work with almost anything externally. In attempting to link a pipeline with GitLab I also received a similar error.
![image](https://user-images.githubusercontent.com/6267549/48964779-a5b2bf80-ef74-11e8-9d78-ec48ae60c02e.png)

I have run various tests and everything shows my certificates are valid. I cannot figure this out at all :/

**Comment by superseb** [comment]
Both outgoing requests get a certificate presented from your own domain instead of the requested domain. The certificates from both domains are valid, so I can only guess you have your pfSense in SSL/MiTM/transparent proxy mode where certificates are issued for the requested outgoing connections. To see the actual certificate that gets presented you can run `openssl s_client -connect git.rancher.io:443 -servername git.rancher.io -showcerts | openssl x509 -noout -text` inside the container. Simplest option to rule this out is to disable the proxy functionality and let the hosts/container have direct internet access to see if that resolves the issue. If you still have the issue then, let me know so we can investigate as it doesn't reproduce on a clean install on a host with direct internet access.

**Comment by Celestialdeath99** [comment]
Last night I removed the HAProxy from it and gave the system direct access to the internet and encountered the same issue. I ran the command on rancher container and it says it is unable to get the local issuer certificate:
```
root@rancher-79977f9d95-66jxl:/var/lib/rancher# openssl s_client -connect git.rancher.io:443 -servername git.rancher.io -showcerts | openssl x509 -noout -text
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify error:num=20:unable to get local issuer certificate
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            03:50:73:ee:c6:7a:2c:73:f3:23:f1:d5:02:b4:91:4a:30:86
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
        Validity
            Not Before: Nov 24 03:09:11 2018 GMT
            Not After : Feb 22 03:09:11 2019 GMT
        Subject: CN = *.celestialdata.net
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:d3:68:ba:a6:a6:86:df:73:7f:7d:fb:5a:76:5b:
                    2d:49:8f:a4:ce:60:7c:26:42:65:17:45:e1:44:c1:
                    d4:29:aa:17:ba:c3:f6:e0:28:e7:a9:f7:cc:8d:5d:
                    63:4b:64:6f:68:a2:a3:b4:34:61:64:eb:93:ad:ef:
                    a0:56:97:76:c3:9c:df:d8:f6:2c:8e:9b:ef:fd:b9:
                    73:39:06:68:1f:9e:ae:9b:85:05:68:f3:ee:6d:0a:
                    e2:7a:18:da:d1:4f:1c:e4:92:01:7b:96:16:74:60:
                    f2:ed:6e:d6:b8:69:c7:76:0c:be:21:e4:a7:9b:e4:
                    4f:4b:b2:b5:eb:f8:d6:3f:2a:3a:de:77:b3:6a:a5:
                    37:dd:6b:12:33:ec:dc:ea:e3:53:2d:ec:7a:78:63:
                    76:9a:e2:d9:47:85:66:76:18:d7:e2:20:68:2d:5c:
                    73:16:bc:2f:5a:8e:46:bd:6d:a4:61:dd:3d:ba:a2:
                    0b:e3:31:12:4d:79:62:46:ec:2e:fb:7a:6f:47:a4:
                    ea:5d:c2:64:90:e2:92:20:97:74:b0:df:77:2d:0f:
                    08:ba:87:ae:34:a5:18:2e:6e:4c:15:cc:e1:02:65:
                    55:55:2d:34:21:c5:ef:c7:f6:7b:36:b6:b7:b5:64:
                    7a:e7:1c:a3:7c:79:8b:b2:58:1f:82:fd:8b:fe:b7:
                    f1:63
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier:
                33:C5:82:86:78:D2:4C:A6:61:A7:76:3E:99:B1:CC:E0:81:32:13:3E
            X509v3 Authority Key Identifier:
                keyid:A8:4A:6A:63:04:7D:DD:BA:E6:D1:39:B7:A6:45:65:EF:F3:A8:EC:A1

            Authority Information Access:
                OCSP - URI:http://ocsp.int-x3.letsencrypt.org
                CA Issuers - URI:http://cert.int-x3.letsencrypt.org/

            X509v3 Subject Alternative Name:
                DNS:*.celestialdata.net
            X509v3 Certificate Policies:
                Policy: 2.23.140.1.2.1
                Policy: 1.3.6.1.4.1.44947.1.1.1
                  CPS: http://cps.letsencrypt.org

            CT Precertificate SCTs:
                Signed Certificate Timestamp:
                    Version   : v1 (0x0)
                    Log ID    : 55:81:D4:C2:16:90:36:01:4A:EA:0B:9B:57:3C:53:F0:
                                C0:E4:38:78:70:25:08:17:2F:A3:AA:1D:07:13:D3:0C
                    Timestamp : Nov 24 04:09:11.983 2018 GMT
                    Extensions: none
                    Signature : ecdsa-with-SHA256
                                30:44:02:20:3B:DC:BA:59:DB:F1:3F:14:E7:29:EF:00:
                                B6:77:75:B7:68:36:A9:4A:A7:F4:BC:0B:8D:FD:39:9E:
                                3A:00:FD:3C:02:20:26:67:88:89:86:D5:8C:C0:4F:66:
                                14:1F:46:CE:9D:1A:45:34:05:5D:ED:15:1E:FF:2B:72:
                                D6:03:C7:93:51:43
                Signed Certificate Timestamp:
                    Version   : v1 (0x0)
                    Log ID    : 29:3C:51:96:54:C8:39:65:BA:AA:50:FC:58:07:D4:B7:
                                6F:BF:58:7A:29:72:DC:A4:C3:0C:F4:E5:45:47:F4:78
                    Timestamp : Nov 24 04:09:12.012 2018 GMT
                    Extensions: none
                    Signature : ecdsa-with-SHA256
                                30:44:02:20:64:B5:9C:C6:B1:19:2B:BC:7C:4F:AD:9C:
                                2E:3B:65:BC:35:B6:7F:5D:AA:1B:F4:6D:05:2B:D0:18:
                                73:F7:5D:9A:02:20:4C:72:61:53:89:46:43:FB:EA:86:
                                C8:34:02:EC:66:90:13:43:9D:67:58:AD:4A:C9:84:72:
                                DE:14:22:83:80:46
    Signature Algorithm: sha256WithRSAEncryption
         22:f3:8e:cf:ad:dd:e6:03:bd:b0:5e:67:86:a0:b5:19:b7:b4:
         54:f6:0e:46:fb:6a:8b:89:a0:af:23:d5:3b:bc:30:09:ef:31:
         01:59:6c:d7:70:69:e0:9b:ee:19:ae:41:8f:7b:74:80:10:d7:
         81:c6:0d:f9:bd:aa:a7:62:d0:3d:aa:7c:02:70:a3:14:4d:9d:
         24:d1:8c:34:bc:04:e5:80:5d:21:8e:39:ab:cf:97:31:6c:7f:
         59:fb:a4:ad:6e:0c:9e:53:f5:1d:8a:45:b5:b8:a3:1c:3d:31:
         cb:27:5d:d1:8a:14:97:94:3b:82:6d:fe:2f:53:bd:1b:87:35:
         3c:4d:83:de:ad:25:98:27:ec:44:b3:fa:e5:67:13:cc:dc:4a:
         70:4b:4f:de:f7:85:aa:12:0a:19:21:1c:44:b8:c7:62:36:88:
         b1:1a:45:6f:99:70:14:b5:c7:41:8f:f1:ff:73:93:5d:c4:90:
         19:65:b0:6f:c3:60:46:23:41:3e:82:4a:28:00:a3:ee:87:1d:
         6a:e2:cc:4e:a4:14:6e:99:93:d5:e6:2e:08:67:55:8b:70:ff:
         a1:fe:e8:34:15:25:10:7b:22:ad:59:6d:6a:df:99:52:29:17:
         ca:a2:7b:ed:ae:eb:db:93:39:99:0c:60:c9:55:d2:5b:df:7b:
         ae:18:3b:ce
```

However, if I run the same command from the kubectl terminal for the cluster I get `verify error:num=19:self signed certificate in certificate chain`:
```
> openssl s_client -connect git.rancher.io:443 -servername git.rancher.io -showcerts | openssl x509 -noout -text
depth=3 C = US, O = "The Go Daddy Group, Inc.", OU = Go Daddy Class 2 Certification Authority
verify error:num=19:self signed certificate in certificate chain
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            95:d6:19:4b:fb:a3:32:87
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, ST = Arizona, L = Scottsdale, O = "GoDaddy.com, Inc.", OU = http://certs.godaddy.com/repository/, CN = Go Daddy Secure Certificate Authority - G2
        Validity
            Not Before: Jan  4 19:03:00 2018 GMT
            Not After : Mar  5 23:34:40 2019 GMT
        Subject: OU = Domain Control Validated, CN = *.rancher.io
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:c7:9b:7d:ca:98:27:d2:de:1d:4a:4a:b1:20:d3:
                    17:60:3c:73:44:92:55:1b:45:94:21:01:a7:3e:e0:
                    e3:67:ac:a9:71:bb:9c:91:19:34:67:a5:0d:49:28:
                    13:9a:7b:5e:3b:89:83:de:a6:ca:f3:ec:bb:6d:a2:
                    79:bd:f1:10:b8:69:3f:ae:61:01:dd:b1:1f:9e:d7:
                    43:a5:06:b5:e6:2a:13:db:22:95:56:c6:8b:1f:54:
                    38:a2:24:21:3d:51:01:40:55:eb:d0:17:f4:cf:25:
                    d1:6e:e8:c5:6d:ba:bb:f1:be:ee:7f:e5:af:73:97:
                    43:38:bc:a7:14:d8:3e:11:e3:f3:52:88:57:db:3c:
                    0d:54:3a:42:b8:a3:9b:ee:71:01:32:b3:53:b3:94:
                    0d:94:86:5c:55:a2:7d:1a:66:7c:97:72:f1:a7:69:
                    0b:df:10:58:e3:2f:85:b8:3e:37:6d:fa:28:a7:2d:
                    d7:8a:07:de:4b:fc:cf:87:db:18:3e:95:a8:a7:5c:
                    3f:22:ba:08:79:45:cf:de:61:15:68:80:81:b1:81:
                    5b:a2:bd:3c:7b:29:97:e0:0a:b2:76:5b:9c:96:aa:
                    64:b8:28:78:b8:30:d7:89:22:e9:cd:19:22:71:b0:
                    4c:83:07:7c:4b:c7:f0:1b:4f:65:96:d3:f8:05:32:
                    bb:49
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 CRL Distribution Points:

                Full Name:
                  URI:http://crl.godaddy.com/gdig2s1-799.crl

            X509v3 Certificate Policies:
                Policy: 2.16.840.1.114413.1.7.23.1
                  CPS: http://certificates.godaddy.com/repository/
                Policy: 2.23.140.1.2.1

            Authority Information Access:
                OCSP - URI:http://ocsp.godaddy.com/
                CA Issuers - URI:http://certificates.godaddy.com/repository/gdig2.crt

            X509v3 Authority Key Identifier:
                keyid:40:C2:BD:27:8E:CC:34:83:30:A2:33:D7:FB:6C:B3:F0:B4:2C:80:CE

            X509v3 Subject Alternative Name:
                DNS:*.rancher.io, DNS:rancher.io
            X509v3 Subject Key Identifier:
                D0:39:02:53:EB:AE:DF:3F:15:07:84:8C:24:CF:FB:74:D7:84:F8:6D
    Signature Algorithm: sha256WithRSAEncryption
         1c:92:b4:ce:d9:41:00:26:13:dc:85:32:27:13:96:2a:7c:00:
         ae:04:45:64:24:a1:d0:aa:fb:4b:01:9d:23:34:14:9c:b5:bd:
         d0:7f:b3:ee:1f:06:7f:c9:43:53:1f:88:17:a0:18:8c:f9:5f:
         5e:6e:09:32:6b:95:10:13:4c:34:19:04:08:e3:82:0e:b4:85:
         49:bf:96:1a:9f:92:a5:76:33:f6:21:9a:bf:b8:31:fd:4f:43:
         60:5d:32:0c:18:49:30:14:ef:55:08:e9:cb:8f:09:ca:fc:04:
         e2:87:58:22:a8:66:4e:7c:b2:cb:87:c2:5d:ee:24:15:67:89:
         7a:87:77:d2:21:17:8f:1d:60:b4:9c:6d:d6:00:ed:29:2e:0b:
         ba:05:40:c3:1c:8f:30:9b:25:af:6f:ef:b6:fa:66:d8:d4:35:
         ca:b7:0b:17:e3:9c:d2:1c:07:80:9c:80:9d:86:ed:98:a5:98:
         e7:eb:71:a0:44:16:7a:d8:88:0d:4e:4d:d2:62:c4:ac:b8:0b:
         16:90:ec:83:99:b1:83:ab:51:08:de:53:93:30:b3:7b:c7:61:
         dd:98:db:ab:79:8a:56:9a:11:8d:ec:da:15:8c:f7:55:bf:e5:
         1c:27:ce:7d:5e:2b:99:33:26:17:6c:3f:70:56:08:34:43:79:
         a6:0a:e6:ac
```

And finally if I run it on the actual baremetal node itself _(ubuntu server 16.04.5 LTS)_ there are no issues:
```
ubuntu@rancher-01:~$ openssl s_client -connect git.rancher.io:443 -servername git.rancher.io -showcerts | openssl x509 -noout -text
depth=3 C = US, O = "The Go Daddy Group, Inc.", OU = Go Daddy Class 2 Certification Authority
verify return:1
depth=2 C = US, ST = Arizona, L = Scottsdale, O = "GoDaddy.com, Inc.", CN = Go Daddy Root Certificate Authority - G2
verify return:1
depth=1 C = US, ST = Arizona, L = Scottsdale, O = "GoDaddy.com, Inc.", OU = http://certs.godaddy.com/repository/, CN = Go Daddy Secure Certificate Authority - G2
verify return:1
depth=0 OU = Domain Control Validated, CN = *.rancher.io
verify return:1
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 10796844970802360967 (0x95d6194bfba33287)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, ST=Arizona, L=Scottsdale, O=GoDaddy.com, Inc., OU=http://certs.godaddy.com/repository/, CN=Go Daddy Secure Certificate Authority - G2
        Validity
            Not Before: Jan  4 19:03:00 2018 GMT
            Not After : Mar  5 23:34:40 2019 GMT
        Subject: OU=Domain Control Validated, CN=*.rancher.io
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:c7:9b:7d:ca:98:27:d2:de:1d:4a:4a:b1:20:d3:
                    17:60:3c:73:44:92:55:1b:45:94:21:01:a7:3e:e0:
                    e3:67:ac:a9:71:bb:9c:91:19:34:67:a5:0d:49:28:
                    13:9a:7b:5e:3b:89:83:de:a6:ca:f3:ec:bb:6d:a2:
                    79:bd:f1:10:b8:69:3f:ae:61:01:dd:b1:1f:9e:d7:
                    43:a5:06:b5:e6:2a:13:db:22:95:56:c6:8b:1f:54:
                    38:a2:24:21:3d:51:01:40:55:eb:d0:17:f4:cf:25:
                    d1:6e:e8:c5:6d:ba:bb:f1:be:ee:7f:e5:af:73:97:
                    43:38:bc:a7:14:d8:3e:11:e3:f3:52:88:57:db:3c:
                    0d:54:3a:42:b8:a3:9b:ee:71:01:32:b3:53:b3:94:
                    0d:94:86:5c:55:a2:7d:1a:66:7c:97:72:f1:a7:69:
                    0b:df:10:58:e3:2f:85:b8:3e:37:6d:fa:28:a7:2d:
                    d7:8a:07:de:4b:fc:cf:87:db:18:3e:95:a8:a7:5c:
                    3f:22:ba:08:79:45:cf:de:61:15:68:80:81:b1:81:
                    5b:a2:bd:3c:7b:29:97:e0:0a:b2:76:5b:9c:96:aa:
                    64:b8:28:78:b8:30:d7:89:22:e9:cd:19:22:71:b0:
                    4c:83:07:7c:4b:c7:f0:1b:4f:65:96:d3:f8:05:32:
                    bb:49
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 CRL Distribution Points:

                Full Name:
                  URI:http://crl.godaddy.com/gdig2s1-799.crl

            X509v3 Certificate Policies:
                Policy: 2.16.840.1.114413.1.7.23.1
                  CPS: http://certificates.godaddy.com/repository/
                Policy: 2.23.140.1.2.1

            Authority Information Access:
                OCSP - URI:http://ocsp.godaddy.com/
                CA Issuers - URI:http://certificates.godaddy.com/repository/gdig2.crt

            X509v3 Authority Key Identifier:
                keyid:40:C2:BD:27:8E:CC:34:83:30:A2:33:D7:FB:6C:B3:F0:B4:2C:80:CE

            X509v3 Subject Alternative Name:
                DNS:*.rancher.io, DNS:rancher.io
            X509v3 Subject Key Identifier:
                D0:39:02:53:EB:AE:DF:3F:15:07:84:8C:24:CF:FB:74:D7:84:F8:6D
    Signature Algorithm: sha256WithRSAEncryption
         1c:92:b4:ce:d9:41:00:26:13:dc:85:32:27:13:96:2a:7c:00:
         ae:04:45:64:24:a1:d0:aa:fb:4b:01:9d:23:34:14:9c:b5:bd:
         d0:7f:b3:ee:1f:06:7f:c9:43:53:1f:88:17:a0:18:8c:f9:5f:
         5e:6e:09:32:6b:95:10:13:4c:34:19:04:08:e3:82:0e:b4:85:
         49:bf:96:1a:9f:92:a5:76:33:f6:21:9a:bf:b8:31:fd:4f:43:
         60:5d:32:0c:18:49:30:14:ef:55:08:e9:cb:8f:09:ca:fc:04:
         e2:87:58:22:a8:66:4e:7c:b2:cb:87:c2:5d:ee:24:15:67:89:
         7a:87:77:d2:21:17:8f:1d:60:b4:9c:6d:d6:00:ed:29:2e:0b:
         ba:05:40:c3:1c:8f:30:9b:25:af:6f:ef:b6:fa:66:d8:d4:35:
         ca:b7:0b:17:e3:9c:d2:1c:07:80:9c:80:9d:86:ed:98:a5:98:
         e7:eb:71:a0:44:16:7a:d8:88:0d:4e:4d:d2:62:c4:ac:b8:0b:
         16:90:ec:83:99:b1:83:ab:51:08:de:53:93:30:b3:7b:c7:61:
         dd:98:db:ab:79:8a:56:9a:11:8d:ec:da:15:8c:f7:55:bf:e5:
         1c:27:ce:7d:5e:2b:99:33:26:17:6c:3f:70:56:08:34:43:79:
         a6:0a:e6:ac
```

I do not understand what is going on here at all. If the baremetal server which everything goes to can communicate without issue and all of my other 50+ server applications running in the same server network configured the same way work I do not understand why Rancher is having issues.

**Comment by Celestialdeath99** [comment]
I just created a container on the cluster with a nginx web server and ran the command on there as well. The output was the same as that recieved when I ran the command on the baremetal server. I also assigned it to the ingress of the cluster using a L7 load balancer with the domain [testnginx.celestialdata.net](testnginx.celestialdata.net) and I am able to access it without issue.

**Comment by superseb** [comment]
Pretty sure this is caused by the wildcard record for your domain. As Kubernetes puts `ndots: 5` in `/etc/resolv.conf`, and your search domain probably set to `celestialdata.net` it will resolve `git.rancher.io.celestialdata.net` and point to itself. Then the certificate doesn't match.

You can validate this by removing the `options ndots:5` or `celestialdata.net` and check if that resolves the issue to validate this is the actual root cause. See more discussion in https://github.com/kubernetes/kubernetes/issues/64924

**Comment by Celestialdeath99** [comment]
I have looked in all containers, within the nodes and on the baremetal servers. None of them have `options ndots:5` set. The search domain on all is set to my other domain that my main network uses, mcresolution.org however that is not the certificate that it is returning so I do not think that is what is going on.

**Comment by Celestialdeath99** [comment]
**Update:** I found that that the only container that has the `options ndots:5` is the actual rancher containers. However I am not sure how I can update that. Whenever I try to remove it through the execution shell it says that the resource is currently busy.

**Comment by Celestialdeath99** [comment]
I have found a temporary solution, that is to use the Networking options and adding a host alias for the domain I need it to be able to access to whatever container I am having an issue with. However as you could probably imagine this is pretty inconvenient. It also does not work for pipelines, as when the pipeline goes to clone the repository I get the following:
```
05:24:39 Cloning the remote Git repository
05:24:39 Cloning repository https://gitlab.com/objective-driveyards/ody-management-platform.git
05:24:39  > git init /home/jenkins/workspace/pipeline_p-wv6ls-7 # timeout=10
05:24:39 Fetching upstream changes from https://gitlab.com/objective-driveyards/ody-management-platform.git
05:24:39  > git --version # timeout=10
05:24:39 using GIT_ASKPASS to set credentials 
05:24:39  > git fetch --tags --progress https://gitlab.com/objective-driveyards/ody-management-platform.git +refs/heads/*:refs/remotes/origin/*
05:24:39 ERROR: Error cloning remote repo 'origin'
05:24:39 hudson.plugins.git.GitException: Command "git fetch --tags --progress https://gitlab.com/objective-driveyards/ody-management-platform.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
05:24:39 stdout: 
05:24:39 stderr: fatal: unable to access 'https://gitlab.com/objective-driveyards/ody-management-platform.git/': SSL: no alternative certificate subject name matches target host name 'gitlab.com'
05:24:39 
05:24:39 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2002)
05:24:39 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1721)
05:24:39 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:72)
05:24:39 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:405)
05:24:39 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:614)
05:24:39 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
05:24:39 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
05:24:39 	at hudson.remoting.UserRequest.perform(UserRequest.java:181)
05:24:39 	at hudson.remoting.UserRequest.perform(UserRequest.java:52)
05:24:39 	at hudson.remoting.Request$2.run(Request.java:336)
05:24:39 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
05:24:39 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05:24:39 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
05:24:39 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
05:24:39 	at hudson.remoting.Engine$1$1.run(Engine.java:98)
05:24:39 	at java.lang.Thread.run(Thread.java:748)
05:24:39 	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 10.42.2.41/10.42.2.41:37546
05:24:39 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
05:24:39 		at hudson.remoting.UserResponse.retrieve(UserRequest.java:389)
05:24:39 		at hudson.remoting.Channel.call(Channel.java:955)
05:24:39 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
05:24:39 		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
05:24:39 		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
05:24:39 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
05:24:39 		at java.lang.reflect.Method.invoke(Method.java:498)
05:24:39 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
05:24:39 		at com.sun.proxy.$Proxy81.execute(Unknown Source)
05:24:39 		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1083)
05:24:39 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1123)
05:24:39 		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:113)
05:24:39 		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:85)
05:24:39 		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:75)
05:24:39 		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
05:24:39 		at hudson.security.ACL.impersonate(ACL.java:290)
05:24:39 		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
05:24:39 		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
05:24:39 		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05:24:39 		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
05:24:39 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
05:24:39 		... 1 more
```
I am assuming that this is resulting from the same issue. I have been unable to find a way to stop the `options ndots:5` from being added, or to change it to 1. I am not very experienced with Kubernetes or Rancher in general so I have a hard time following a lot of things. How can I either get it to use a value of 1 or remove it altogether?

**Comment by NULLx76** [comment]
Is there any update on this as I'm experiencing the same issue, I am able to change it to ndots:1 when editing the yml of individual containers (found nothing yet to change it globally) . However I'm not sure as how to fix this for the webui as I'm unsure which container is responsible for resolving for the webui

**Comment by sdanieru** [comment]
@Celestialdeath99 @NULLx76 I recently encountered this problem and found a high-level work-around: I basically dropped `dns-search my.domain` from my kubernetes hosting nodes so that it never propagates up into any of the containers. The change necessitates using FQDNs on those hosts when resolving other hosts under `my.domain`, but for my use case the trade-off is totally worth it to avoid mucking about with `dnsConfig` on a per-pod basis in Kubernetes.
