### ISSUE TITLE
Concurrent Map read/write on master

### ISSUE THREAD

**Issue by nathan-jenan-rancher** [rancher/rancher#16891]
I got this issue locally, but @kinarashah has seen it occur in Drone as well.

Error was encountered on commit: 9c0bf8f1a1a9cd9a6382862d4e95d55acf46f6da

stack
```
2018/12/05 14:39:21 [INFO] [mgmt-auth-prtb-controller] Creating clusterRoleBinding for membership in cluster c-8xzhx for subject user-fm47s
2018/12/05 14:39:21 [INFO] [mgmt-project-rbac-create] Updating project p-vvxd6
2018/12/05 14:39:21 [INFO] [mgmt-auth-prtb-controller] Creating clusterRole p-vvxd6-projectowner
2018/12/05 14:39:21 [INFO] [mgmt-auth-crtb-controller] Creating roleBinding for subject user-fm47s with role cluster-owner in namespace 
2018/12/05 14:39:21 [INFO] [mgmt-auth-prtb-controller] Creating role project-owner in namespace c-8xzhx
2018/12/05 14:39:21 [INFO] [mgmt-auth-crtb-controller] Creating role cluster-owner in namespace p-vvxd6
fatal error: concurrent map read and map write

goroutine 15667 [running]:
runtime.throw(0x3437b44, 0x21)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/panic.go:608 +0x72 fp=0xc006ace440 sp=0xc006ace410 pc=0x102e112
runtime.mapaccess2_faststr(0x2ee5560, 0xc0061128d0, 0x34245a8, 0x19, 0x0, 0x0)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/map_faststr.go:110 +0x458 fp=0xc006ace4b0 sp=0xc006ace440 pc=0x1014608
github.com/rancher/rancher/pkg/controllers/user/rbac.updateStatusAnnotation(0x0, 0xc0039bd330, 0x9, 0xc0039bd318, 0x2, 0xc0039bd340, 0x7, 0x0, 0x0, 0x0, ...)
	/Users/nathanieljenan/go/src/github.com/rancher/rancher/pkg/controllers/user/rbac/namespace_handler.go:404 +0x64 fp=0xc006ace6a0 sp=0xc006ace4b0 pc=0x21fa6f4
runtime.goexit()
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc006ace6a8 sp=0xc006ace6a0 pc=0x105e1d1
created by github.com/rancher/rancher/pkg/controllers/user/rbac.(*nsLifecycle).Create
	/Users/nathanieljenan/go/src/github.com/rancher/rancher/pkg/controllers/user/rbac/namespace_handler.go:66 +0x19b
```

Full log file attached:
[output.1.log](https://github.com/rancher/rancher/files/2650793/output.1.log)

**Comment by nathan-jenan-rancher** [comment]
May be related to: https://github.com/rancher/rancher/issues/16759

**Comment by cjellick** [comment]
just closing...qa cant test this

**Comment by xiaoluhong** [comment]
The same issue exists in Rancher V2.4.5.

```bash
2020/08/07 06:08:47 [INFO] Handling backend connection request [c-rcl7f:m-243c46922809]
2020/08/07 06:08:47 [INFO] Handling backend connection request [c-rcl7f:m-b5901042768f]
2020/08/07 06:08:47 [INFO] Handling backend connection request [c-rcl7f:m-5c7b5acf44d1]
2020/08/07 06:08:47 [INFO] Handling backend connection request [c-rcl7f:m-488cc7e47d6b]
2020/08/07 06:08:47 [INFO] Handling backend connection request [c-rcl7f:m-061637392e50]
2020/08/07 06:08:47 [INFO] Handling backend connection request [c-rcl7f:m-e25dc52eea93]
2020/08/07 06:08:47 [INFO] Handling backend connection request [c-rcl7f:m-c70d844342a0]
2020/08/07 06:08:47 [INFO] Handling backend connection request [c-rcl7f:m-d1a26cd74777]
2020/08/07 06:08:47 [INFO] Handling backend connection request [c-rcl7f:m-cabf8ae850e8]
2020/08/07 06:08:47 [INFO] Handling backend connection request [c-rcl7f:m-41da6c9e8a8b]
2020/08/07 06:08:47 [INFO] Handling backend connection request [c-rcl7f:m-e53c4426fcb1]
2020/08/07 06:08:47 [INFO] Handling backend connection request [c-rcl7f:m-56f8d14e6a93]
2020/08/07 06:08:47 [INFO] Handling backend connection request [c-rcl7f:m-7f56d75bf688]
2020/08/07 06:08:47 [INFO] Handling backend connection request [local]
2020/08/07 06:08:47 [INFO] Handling backend connection request [c-rcl7f:m-ba79040db8e3]
2020/08/07 06:08:47 [INFO] Handling backend connection request [c-rcl7f:m-17f99a358212]
2020/08/07 06:08:50 [INFO] Starting cluster controllers for c-rcl7f
2020/08/07 06:08:51 [INFO] Starting cluster agent for c-rcl7f [owner=false]
2020/08/07 06:08:51 [INFO] Starting rbac.authorization.k8s.io/v1, Kind=ClusterRole controller
2020/08/07 06:08:51 [INFO] Starting rbac.authorization.k8s.io/v1, Kind=Role controller
I0807 06:08:51.526720       7 http.go:116] HTTP2 has been explicitly disabled
fatal error: concurrent map read and map write

goroutine 6491 [running]:
runtime.throw(0x3fb5abb, 0x21)
 /usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc00651fd20 sp=0xc00651fcf0 pc=0x42fb12
runtime.mapaccess2_faststr(0x3642e20, 0xc008552450, 0xc0088
```
