### ISSUE TITLE
Monitoring - rancher server died because of monitoring

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#16914]
Bug. 

Rancher master on 12/5.

Standalone installation. After enabling the project level monitoring, the rancher server dies with the following info in the log:

```
goroutine 97148 [running]:
runtime.throw(0x37b2743, 0x15)
        /usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc01e17db70 sp=0xc01e17db40 pc=0x42c4c2
runtime.mapassign_faststr(0x3099ac0, 0xc014fb0ea0, 0x37a5ffe, 0x11, 0xc01c3b8500)
        /usr/local/go/src/runtime/map_faststr.go:199 +0x3da fp=0xc01e17dbd8 sp=0xc01e17db70 pc=0x412a6a
github.com/rancher/rancher/vendor/github.com/rancher/norman/objectclient.(*ObjectClient).Create(0xc029413ce0, 0x3dd7f60, 0xc01c3b8500, 0x3787120, 0x2, 0x379c981, 0xe)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/objectclient/object_client.go:106 +0x716 fp=0xc01e17ddc8 sp=0xc01e17dbd8 pc=0x1d8c576
github.com/rancher/rancher/vendor/github.com/rancher/types/apis/core/v1.(*serviceAccountClient).Create(0xc01a2a6180, 0xc01c3b8500, 0x19, 0x3e44140, 0xc01a2a6180)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/core/v1/zz_generated_service_account_controller.go:191 +0x49 fp=0xc01e17de10 sp=0xc01e17ddc8 pc=0x1f16c19
github.com/rancher/rancher/pkg/controllers/user/monitoring.(*appHandler).grantProjectMonitoringPermissions.func1(0x38ebad8, 0x0)
        /go/src/github.com/rancher/rancher/pkg/controllers/user/monitoring/projectHandler.go:206 +0x1e2 fp=0xc01e17dfa0 sp=0xc01e17de10 pc=0x215d2d2
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/errors.AggregateGoroutines.func1(0xc009ae13e0, 0xc003e49ec0)
        /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/errors/errors.go:189 +0x27 fp=0xc01e17dfd0 sp=0xc01e17dfa0 pc=0x7d0237
runtime.goexit()
```

**Comment by loganhz** [comment]
The fix has been merged.

**Comment by jiaqiluo** [comment]
Validated on master 11/7

In my test, the rancher server has kept running for 5 hours without problems. 
```
CONTAINER ID        IMAGE                    COMMAND             CREATED             STATUS              PORTS                                      NAMES
31316aac0706        rancher/rancher:master   "entrypoint.sh"     5 hours ago         Up 5 hours          0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   xenodochial_swirles
```
