### ISSUE TITLE
rancher stack view/export broken

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#16995]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Not sure what the reproduction is here. Trying to export or view config of stack results in error.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server`):  rancher/server:v1.6.16
- Installation option (single install/HA): Single

- Exception seen:
```
2018-12-03 21:45:31,771 ERROR [:] [] [] [] [020391880-32246] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [http://rancher-srv:8080/v2-beta/projects/1a9/stacks/1st228/]. Error id: [90a5409e-9d93-4372-abb5-eb901856dcae]. java.lang.NullPointerException: null
                at io.cattle.platform.servicediscovery.api.service.impl.ServiceDiscoveryApiServiceImpl.populateSecrets(ServiceDiscoveryApiServiceImpl.java:420)
                at io.cattle.platform.servicediscovery.api.service.impl.ServiceDiscoveryApiServiceImpl.createComposeData(ServiceDiscoveryApiServiceImpl.java:215)
                at io.cattle.platform.servicediscovery.api.service.impl.ServiceDiscoveryApiServiceImpl.buildDockerComposeConfig(ServiceDiscoveryApiServiceImpl.java:136)
                at io.cattle.platform.servicediscovery.api.service.impl.ServiceDiscoveryApiServiceImpl.buildComposeConfig(ServiceDiscoveryApiServiceImpl.java:127)
                at io.cattle.platform.servicediscovery.api.action.StackExportConfigActionHandler.perform(StackExportConfigActionHandler.java:57)
                at io.cattle.platform.api.resource.AbstractObjectResourceManager.resourceActionInternal(AbstractObjectResourceManager.java:382)
                at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.resourceAction(AbstractBaseResourceManager.java:414)
                at io.github.ibuildthecloud.gdapi.request.resource.AbstractResourceManagerFilter.resourceAction(AbstractResourceManagerFilter.java:58)
                at io.cattle.platform.servicediscovery.api.filter.ServiceStackStorageDriverFilter.resourceAction(ServiceStackStorageDriverFilter.java:85)
                at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.resourceAction(FilteredResourceManager.java:86)
                at io.github.ibuildthecloud.gdapi.request.resource.AbstractResourceManagerFilter.resourceAction(AbstractResourceManagerFilter.java:58)
                at io.cattle.platform.servicediscovery.api.filter.ServiceStackNetworkDriverFilter.resourceAction(ServiceStackNetworkDriverFilter.java:85)
                at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.resourceAction(FilteredResourceManager.java:86)
                at io.github.ibuildthecloud.gdapi.request.resource.AbstractResourceManagerFilter.resourceAction(AbstractResourceManagerFilter.java:58)
                at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.resourceAction(FilteredResourceManager.java:86)
                at io.github.ibuildthecloud.gdapi.request.handler.ResourceManagerRequestHandler.generate(ResourceManagerRequestHandler.java:44)
                at io.github.ibuildthecloud.gdapi.request.handler.AbstractResponseGenerator.handle(AbstractResponseGenerator.java:14)
                at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.handle(DefaultReadWriteApiDelegate.java:27)
                at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.write(DefaultReadWriteApiDelegate.java:22)
                at sun.reflect.GeneratedMethodAccessor468.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
                at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
                at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:280)
                at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
                at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
                at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
                at com.sun.proxy.$Proxy73.write(Unknown Source)
                at io.github.ibuildthecloud.gdapi.request.handler.write.ReadWriteApiHandler.handle(ReadWriteApiHandler.java:19)
                at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:99)
                at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:100)
                at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
                at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
                at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108)
                at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
                at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
                at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:110)
                at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
                at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
                at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300)
                at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
                at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
                at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
                at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
                at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
                at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
                at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
                at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
                at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
                at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
                at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
                at org.eclipse.jetty.server.Server.handle(Server.java:499)
                at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
                at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
                at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
                at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
                at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
                at java.lang.Thread.run(Thread.java:745)
```

**Comment by alena1108** [comment]
Can be tested with `rancher/server:v1.6.26-rc1`

**Comment by sangeethah** [comment]
@alena1108 I am not able to reproduce this issue with the following steps . 

In Cattle environment,
1. Create a secret.
2. Create a Stack.
3. Deploy a service using the above created secret in step1.
4. Delete secret created in step1.
5. Try to export or view config of stack.

I dont see any errors being reported in the rancher server logs.
Are these correct steps ?

**Comment by sangeethah** [comment]
@alena1108  I am able to reproduce the issue, if we wait for the secrets to be purged from the DB and then try to export or view config of stack.
This fails with "Internal Server Error (500)" and exception reported in the issue is encountered.

**Comment by soumyalj** [comment]
Reproduced the issue in v1.6.17
<img width="1134" alt="screen shot 2019-01-11 at 11 16 09 am" src="https://user-images.githubusercontent.com/18536626/51054644-565f3780-1592-11e9-8c19-05a39415c74e.png">

**Comment by soumyalj** [comment]
Tested with v1.6.26-rc1. 
1. Create a secret.
2. Create a Stack.
3. Deploy a service using the above created secret in step1.
4. Delete secret created in step1.
Export or view config of stack was successful. UI did not have any issues. 
There was no null pointer exception in the logs.
