### ISSUE TITLE
Kubectl and pods not working after upgrade to rancher 2.1.3

### ISSUE THREAD

**Issue by mpostument** [rancher/rancher#17063]
After upgrade from 2.1.1 to 2.1.3 kubectl not working from Rancher UI also jenkins is not able to create dynamic slaves using kubernetes plugin
> kubectl get all -v9
```
I1212 13:23:24.333344      45 loader.go:357] Config loaded from file /nonexistent/.kube/config
I1212 13:23:24.334425      45 round_trippers.go:386] curl -k -v -XGET  -H "User-Agent: kubectl/v1.10.5 (linux/amd64) kubernetes/32ac1c9" -H "Authorization: Bearer kubectl-shell-user-qkb47:123" -H "Accept: application/json, */*" https://rancher.test.com.com/k8s/clusters/c-qjh9w/api
I1212 13:23:24.428311      45 round_trippers.go:405] GET https://rancher.test.com.com/k8s/clusters/c-qjh9w/api 200 OK in 93 milliseconds
I1212 13:23:24.428327      45 round_trippers.go:411] Response Headers:
I1212 13:23:24.428333      45 round_trippers.go:414]     Server: nginx/1.12.2
I1212 13:23:24.428337      45 round_trippers.go:414]     Date: Wed, 12 Dec 2018 13:23:24 GMT
I1212 13:23:24.428342      45 round_trippers.go:414]     Content-Type: application/json
I1212 13:23:24.428347      45 round_trippers.go:414]     Content-Length: 137
I1212 13:23:24.428351      45 round_trippers.go:414]     X-Frame-Options: SAMEORIGIN
I1212 13:23:24.428552      45 request.go:874] Response Body: {"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"10.246.132.104:6443"}]}
I1212 13:23:24.428897      45 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.10.5 (linux/amd64) kubernetes/32ac1c9" -H "Authorization: Bearer kubectl-shell-user123:123" https://rancher.test.com.com/k8s/clusters/c-qjh9w/apis
I1212 13:23:24.444424      45 round_trippers.go:405] GET https://rancher.test.com.com/k8s/clusters/c-qjh9w/apis 200 OK in 15 milliseconds
I1212 13:23:24.444438      45 round_trippers.go:411] Response Headers:
I1212 13:23:24.444443      45 round_trippers.go:414]     Server: nginx/1.12.2
I1212 13:23:24.444448      45 round_trippers.go:414]     Date: Wed, 12 Dec 2018 13:23:24 GMT
I1212 13:23:24.444470      45 round_trippers.go:414]     Content-Type: application/json
I1212 13:23:24.444474      45 round_trippers.go:414]     X-Frame-Options: SAMEORIGIN
I1212 13:23:24.444491      45 request.go:779] Stream error http2.StreamError{StreamID:0x3, Code:0x2, Cause:error(nil)} when reading response body, may be caused by closed connection.
I1212 13:23:24.444540      45 cached_discovery.go:124] skipped caching discovery info due to Stream error http2.StreamError{StreamID:0x3, Code:0x2, Cause:error(nil)} when reading response body, may be caused by closed connection. Please retry.
I1212 13:23:24.444588      45 round_trippers.go:386] curl -k -v -XGET  -H "Authorization: Bearer kubectl-shell-user-qkb47:123" -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.10.5 (linux/amd64) kubernetes/32ac1c9" https://rancher.test.com.com/k8s/clusters/c-qjh9w/api
I1212 13:23:24.460054      45 round_trippers.go:405] GET https://rancher.test.com.com/k8s/clusters/c-qjh9w/api 200 OK in 15 milliseconds
I1212 13:23:24.460068      45 round_trippers.go:411] Response Headers:
I1212 13:23:24.460074      45 round_trippers.go:414]     X-Frame-Options: SAMEORIGIN
I1212 13:23:24.460079      45 round_trippers.go:414]     Server: nginx/1.12.2
I1212 13:23:24.460084      45 round_trippers.go:414]     Date: Wed, 12 Dec 2018 13:23:24 GMT
I1212 13:23:24.460089      45 round_trippers.go:414]     Content-Type: application/json
I1212 13:23:24.460094      45 round_trippers.go:414]     Content-Length: 137
I1212 13:23:24.460274      45 request.go:874] Response Body: {"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"10.246.132.104:6443"}]}
I1212 13:23:24.460442      45 round_trippers.go:386] curl -k -v -XGET  -H "User-Agent: kubectl/v1.10.5 (linux/amd64) kubernetes/32ac1c9" -H "Accept: application/json, */*" -H "Authorization: Bearer kubectl-shell-user-qkb47:123" https://rancher.test.com.com/k8s/clusters/c-qjh9w/apis
I1212 13:23:24.474885      45 round_trippers.go:405] GET https://rancher.test.com.com/k8s/clusters/c-qjh9w/apis 200 OK in 14 milliseconds
I1212 13:23:24.474897      45 round_trippers.go:411] Response Headers:
I1212 13:23:24.474902      45 round_trippers.go:414]     Server: nginx/1.12.2
I1212 13:23:24.474907      45 round_trippers.go:414]     Date: Wed, 12 Dec 2018 13:23:24 GMT
I1212 13:23:24.474912      45 round_trippers.go:414]     Content-Type: application/json
I1212 13:23:24.474916      45 round_trippers.go:414]     X-Frame-Options: SAMEORIGIN
I1212 13:23:24.474931      45 request.go:779] Stream error http2.StreamError{StreamID:0x7, Code:0x2, Cause:error(nil)} when reading response body, may be caused by closed connection.
I1212 13:23:24.474968      45 cached_discovery.go:124] skipped caching discovery info due to Stream error http2.StreamError{StreamID:0x7, Code:0x2, Cause:error(nil)} when reading response body, may be caused by closed connection. Please retry.
I1212 13:23:24.475412      45 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.10.5 (linux/amd64) kubernetes/32ac1c9" -H "Authorization: Bearer kubectl-shell-user-qkb47:123" https://rancher.test.com.com/k8s/clusters/c-qjh9w/api
I1212 13:23:24.490413      45 round_trippers.go:405] GET https://rancher.test.com.com/k8s/clusters/c-qjh9w/api 200 OK in 14 milliseconds
I1212 13:23:24.490425      45 round_trippers.go:411] Response Headers:
I1212 13:23:24.490431      45 round_trippers.go:414]     Server: nginx/1.12.2
I1212 13:23:24.490436      45 round_trippers.go:414]     Date: Wed, 12 Dec 2018 13:23:24 GMT
I1212 13:23:24.490441      45 round_trippers.go:414]     Content-Type: application/json
I1212 13:23:24.490445      45 round_trippers.go:414]     Content-Length: 137
I1212 13:23:24.490450      45 round_trippers.go:414]     X-Frame-Options: SAMEORIGIN
I1212 13:23:24.490556      45 request.go:874] Response Body: {"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"10.246.132.104:6443"}]}
I1212 13:23:24.490734      45 round_trippers.go:386] curl -k -v -XGET  -H "User-Agent: kubectl/v1.10.5 (linux/amd64) kubernetes/32ac1c9" -H "Authorization: Bearer kubectl-shell-user-qkb47:123" -H "Accept: application/json, */*" https://rancher.test.com.com/k8s/clusters/c-qjh9w/apis
I1212 13:23:24.505839      45 round_trippers.go:405] GET https://rancher.test.com.com/k8s/clusters/c-qjh9w/apis 200 OK in 15 milliseconds
I1212 13:23:24.505854      45 round_trippers.go:411] Response Headers:
I1212 13:23:24.505861      45 round_trippers.go:414]     Server: nginx/1.12.2
I1212 13:23:24.505868      45 round_trippers.go:414]     Date: Wed, 12 Dec 2018 13:23:24 GMT
I1212 13:23:24.505874      45 round_trippers.go:414]     Content-Type: application/json
I1212 13:23:24.505880      45 round_trippers.go:414]     X-Frame-Options: SAMEORIGIN
I1212 13:23:24.505895      45 request.go:779] Stream error http2.StreamError{StreamID:0xb, Code:0x2, Cause:error(nil)} when reading response body, may be caused by closed connection.
I1212 13:23:24.505947      45 cached_discovery.go:124] skipped caching discovery info due to Stream error http2.StreamError{StreamID:0xb, Code:0x2, Cause:error(nil)} when reading response body, may be caused by closed connection. Please retry.
I1212 13:23:24.505964      45 factory_object_mapping.go:93] Unable to retrieve API resources, falling back to hardcoded types: Stream error http2.StreamError{StreamID:0xb, Code:0x2, Cause:error(nil)} when reading response body, may be caused by closed connection. Please retry.
F1212 13:23:24.506427      45 helpers.go:119] error: the server doesn't have a resource type "cronjobs"
```
Also, Jenkins with kubernetes plugin not able to create slaves dynamically.

Logs from rancher container:
```
E1212 13:30:36.237772       6 upgradeaware.go:308] Error proxying data from client to backend: EOF
```
Logs from jenkins slave pod:
```
INFO: [JNLP4-connect connection to jenkins-jnlp.default.svc.cluster.local/10.43.137.115:50000] Local headers refused by remote: Unknown client name: slave-x7ckf
Dec 12, 2018 1:30:25 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Protocol JNLP4-connect encountered an unexpected exception
java.util.concurrent.ExecutionException: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Unknown client name: slave-x7ckf
at org.jenkinsci.remoting.util.SettableFuture.get(SettableFuture.java:223)
at hudson.remoting.Engine.innerRun(Engine.java:614)
at hudson.remoting.Engine.run(Engine.java:474)
Caused by: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Unknown client name: slave-x7ckf
at org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer.newAbortCause(ConnectionHeadersFilterLayer.java:378)
at org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer.onRecvClosed(ConnectionHeadersFilterLayer.java:433)
at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:816)
at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287)
at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:172)
at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:816)
at org.jenkinsci.remoting.protocol.NetworkLayer.onRecvClosed(NetworkLayer.java:154)
at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer.access$1500(BIONetworkLayer.java:48)
at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer$Reader.run(BIONetworkLayer.java:247)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
at java.lang.Thread.run(Thread.java:748)
Suppressed: java.nio.channels.ClosedChannelException
... 7 more
Dec 12, 2018 1:30:25 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to 10.43.137.115:50000
Dec 12, 2018 1:30:25 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Server reports protocol JNLP4-plaintext not supported, skipping
Dec 12, 2018 1:30:25 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Protocol JNLP3-connect is not enabled, skipping
Dec 12, 2018 1:30:25 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Server reports protocol JNLP2-connect not supported, skipping
Dec 12, 2018 1:30:25 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Server reports protocol JNLP-connect not supported, skipping
Dec 12, 2018 1:30:25 PM hudson.remoting.jnlp.Main$CuiListener error
SEVERE: The server rejected the connection: None of the protocols were accepted
java.lang.Exception: The server rejected the connection: None of the protocols were accepted
at hudson.remoting.Engine.onConnectionRejected(Engine.java:675)
at hudson.remoting.Engine.innerRun(Engine.java:639)
at hudson.remoting.Engine.run(Engine.java:474)
```
Logs from jenkins master:
```
Dec 12, 2018 1:32:02 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
INFO: Excess workload after pending Kubernetes agents: 1
Dec 12, 2018 1:32:02 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
INFO: Template for label slave: Kubernetes Pod Template
Dec 12, 2018 1:32:02 PM okhttp3.internal.platform.Platform log
INFO: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
Dec 12, 2018 1:32:02 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
WARNING: Failed to count the # of live instances on Kubernetes
com.fasterxml.jackson.databind.JsonMappingException: (was java.io.EOFException) (through reference chain: io.fabric8.kubernetes.api.model.PodList["items"]->java.util.ArrayList[0]->io.fabric8.kubernetes.api.model.Pod["spec"]->io.fabric8.kubernetes.api.model.PodSpec["containers"]->java.util.ArrayList[0]->io.fabric8.kubernetes.api.model.Container["env"]->java.util.ArrayList[3])
at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:365)
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:302)
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3077)
at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:235)
at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:190)
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:383)
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:328)
at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:598)
at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:63)
at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.addProvisionedSlave(KubernetesCloud.java:499)
at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.provision(KubernetesCloud.java:452)
at hudson.slaves.NodeProvisioner$StandardStrategyImpl.apply(NodeProvisioner.java:715)
at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:320)
at hudson.slaves.NodeProvisioner.access$000(NodeProvisioner.java:61)
at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:809)
at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:72)
at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
at okio.RealBufferedSource.require(RealBufferedSource.java:60)
at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:294)
at okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:466)
at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:446)
at okio.RealBufferedSource$1.read(RealBufferedSource.java:430)
at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._loadMore(UTF8StreamJsonParser.java:205)
at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._loadMoreGuaranteed(UTF8StreamJsonParser.java:2340)
at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2425)
at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2405)
at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:269)
at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:35)
at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:10)
at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
... 44 more
```
After i rollback to 2.1.1 issues gone.
Same error on version 2.1.2, 2.1.4 lastet rc and 2.2.0 latest alpha
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.3` UI: `v2.1.17` |
|Route|`authenticated.cluster.index`|

**Comment by cjellick** [comment]
I dont typically ask this but it seems like you have the ability to try different versions of rancher, including ones that are not production ready. If you have the time and inclination, perhaps you can try a few other versions to help us pinpoint where this broke.
Could you try `v2.1.2-rc10`
If rc10 is broke, try `v2.1.2-rc5`
If rc10 is not broke, try `v2.1.2-rc13`

If you don't have the time or inclination to do this, I completely understand. Also, we need the following additional information:

Installation option (single install/HA). If HA, whats the k8s version of the cluster where you deployed rancher

Cluster information  of the cluster you are trying to access
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

Docker (use `docker info`):

**Comment by mpostument** [comment]
Installation option - single install with nginx
Cluster type - Imported
Machine type - Azure VM
Kubernetes version - 
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
Docker info - 
```
docker info
Containers: 69
 Running: 40
 Paused: 0
 Stopped: 29
Images: 36
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 5eda6f6fd0c2884c2c8e78a6e7119e8d0ecedb77 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
 selinux
Kernel Version: 3.10.0-862.14.4.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 2
Total Memory: 6.795 GiB
Name: 
ID: 
Docker Root Dir: /docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true
Registries: docker.io (secure)
```
`v2.1.2-rc10` - not working
`v2.1.2-rc5` - not working
`v2.1.2-rc13` - not working at all
```
2018/12/12 19:16:58 [INFO] 2018/12/12 19:16:58 http: panic serving 172.17.0.1:60232: runtime error: invalid memory address or nil pointer dereference
2018/12/12 19:16:58 [INFO] goroutine 30327 [running]:
2018/12/12 19:16:58 [INFO] net/http.(*conn).serve.func1(0xc007a9aaa0)
2018/12/12 19:16:58 [INFO]      /usr/local/go/src/net/http/server.go:1746 +0xd0
2018/12/12 19:16:58 [INFO] panic(0x4590140, 0xba68cd0)
2018/12/12 19:16:58 [INFO]      /usr/local/go/src/runtime/panic.go:513 +0x1b9
2018/12/12 19:16:58 [INFO] github.com/rancher/rancher/pkg/api/store/cluster.(*Store).ByID(0xc010ff0200, 0xc00f00d560, 0xc008c30e00, 0xc00165400d, 0x7, 0x1, 0xc00cc7f0d0, 0x3938b23)
2018/12/12 19:16:58 [INFO]      /go/src/github.com/rancher/rancher/pkg/api/store/cluster/cluster_store.go:76 +0xc2
2018/12/12 19:16:58 [INFO] github.com/rancher/rancher/vendor/github.com/rancher/norman/store/wrapper.(*StoreWrapper).ByID(0xc010c2bcc0, 0xc00f00d560, 0xc008c30e00, 0xc00165400d, 0x7, 0x4fd9aa5, 0xc0168b7768, 0x3938515)
2018/12/12 19:16:58 [INFO]      /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/wrapper/wrapper.go:24 +0x68
2018/12/12 19:16:58 [INFO] github.com/rancher/rancher/vendor/github.com/rancher/norman/store/wrapper.(*StoreWrapper).ByID(0xc009776010, 0xc00f00d560, 0xc008c30e00, 0xc00165400d, 0x7, 0xc010ff0200, 0x4fd9aa5, 0xa3f552)
2018/12/12 19:16:58 [INFO]      /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/wrapper/wrapper.go:24 +0x68
2018/12/12 19:16:58 [INFO] github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler.ListHandler(0xc00f00d560, 0x51c5910, 0xc008c30e00, 0x0)
2018/12/12 19:16:58 [INFO]      /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler/list.go:28 +0xa2
2018/12/12 19:16:58 [INFO] github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).handle(0xc0004bbd90, 0x81109a0, 0xc01227f960, 0xc00b55e100, 0xc0106266c0, 0xc0122cf0e0, 0xc0168b7908)
2018/12/12 19:16:58 [INFO]      /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:240 +0x2a2
2018/12/12 19:16:58 [INFO] github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP(0xc0004bbd90, 0x81109a0, 0xc01227f960, 0xc00b55e100)
2018/12/12 19:16:58 [INFO]      /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:171 +0x49
2018/12/12 19:16:58 [INFO] github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc001ccf2d0, 0x81109a0, 0xc01227f960, 0xc00b55e100)
2018/12/12 19:16:58 [INFO]      /go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:159 +0xf1
2018/12/12 19:16:58 [INFO] github.com/rancher/rancher/pkg/filter.authHandler.ServeHTTP(0x80d30e0, 0xc0122d7b60, 0x80c4fc0, 0xc001ccf2d0, 0x0, 0x81109a0, 0xc01227f960, 0xc00e423700)
2018/12/12 19:16:58 [INFO]      /go/src/github.com/rancher/rancher/pkg/filter/filter.go:92 +0x2e5
2018/12/12 19:16:58 [INFO] github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc001ccf260, 0x81109a0, 0xc01227f960, 0xc00e423700)
2018/12/12 19:16:58 [INFO]      /go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:159 +0xf1
2018/12/12 19:16:58 [INFO] github.com/rancher/rancher/pkg/dynamiclistener.(*Server).cacheIPHandler.func1(0x81109a0, 0xc01227f960, 0xc00e423400)
2018/12/12 19:16:58 [INFO]      /go/src/github.com/rancher/rancher/pkg/dynamiclistener/server.go:382 +0x101
2018/12/12 19:16:58 [INFO] net/http.HandlerFunc.ServeHTTP(0xc0061bdbe0, 0x81109a0, 0xc01227f960, 0xc00e423400)
2018/12/12 19:16:58 [INFO]      /usr/local/go/src/net/http/server.go:1964 +0x44
2018/12/12 19:16:58 [INFO] net/http.serverHandler.ServeHTTP(0xc01097e410, 0x81109a0, 0xc01227f960, 0xc00e423400)
2018/12/12 19:16:58 [INFO]      /usr/local/go/src/net/http/server.go:2741 +0xab
2018/12/12 19:16:58 [INFO] net/http.(*conn).serve(0xc007a9aaa0, 0x8119a60, 0xc00495f680)
2018/12/12 19:16:58 [INFO]      /usr/local/go/src/net/http/server.go:1847 +0x646
2018/12/12 19:16:58 [INFO] created by net/http.(*Server).Serve
2018/12/12 19:16:58 [INFO]      /usr/local/go/src/net/http/server.go:2851 +0x2f5
```

**Comment by mpostument** [comment]
After changing nginx conf from proxy_set_header Connection "Upgrade" to proxy_set_header Connection $connection_upgrade;

map $http_upgrade $connection_upgrade {
        default Upgrade;
            ''      close;
            }
the issue was resolved, going to monitor for a few days

**Comment by mpostument** [comment]
Rancher 2.1.4 working without issues. Going close this issue
