### ISSUE TITLE
starting and stopping agents is unpleasantly slow and fails often

### ISSUE THREAD

**Issue by feliksik** [rancher/rancher#172]
I don't know why, it worked before, but it seems something got sick. The agents logs say: 

```
I0308 14:12:30.188472 20600 manager.go:395] Added container: "/docker/bcbddf3196f1099f80a652df8e92ea954498831f0f278a348098be47246b94bd" (aliases: [proxy2 bcbddf3196f1099f80a652df8e92ea954498831f0f278a348098be47246b94bd], namespace: "docker")
I0308 14:12:30.188526 20600 container.go:154] Start housekeeping for container "/docker/bcbddf3196f1099f80a652df8e92ea954498831f0f278a348098be47246b94bd"
I0308 14:12:50.350785 20600 manager.go:429] Destroyed container: "/docker/bcbddf3196f1099f80a652df8e92ea954498831f0f278a348098be47246b94bd" (aliases: [proxy2 bcbddf3196f1099f80a652df8e92ea954498831f0f278a348098be47246b94bd], namespace: "docker")
I0308 14:13:14.815844 20600 manager.go:395] Added container: "/docker/13c9acebe3739f40e98b9c70a6648fbfbcdbd9eb11395a362c6cde5a93fda320" (aliases: [proxy3 13c9acebe3739f40e98b9c70a6648fbfbcdbd9eb11395a362c6cde5a93fda320], namespace: "docker")
I0308 14:13:14.815912 20600 container.go:154] Start housekeeping for container "/docker/13c9acebe3739f40e98b9c70a6648fbfbcdbd9eb11395a362c6cde5a93fda320"
I0308 14:13:22.282766 20600 manager.go:429] Destroyed container: "/docker/13c9acebe3739f40e98b9c70a6648fbfbcdbd9eb11395a362c6cde5a93fda320" (aliases: [proxy3 13c9acebe3739f40e98b9c70a6648fbfbcdbd9eb11395a362c6cde5a93fda320], namespace: "docker")
I0308 14:13:41.296479 20600 manager.go:395] Added container: "/docker/13c9acebe3739f40e98b9c70a6648fbfbcdbd9eb11395a362c6cde5a93fda320" (aliases: [proxy3 13c9acebe3739f40e98b9c70a6648fbfbcdbd9eb11395a362c6cde5a93fda320], namespace: "docker")
I0308 14:13:41.296533 20600 container.go:154] Start housekeeping for container "/docker/13c9acebe3739f40e98b9c70a6648fbfbcdbd9eb11395a362c6cde5a93fda320"
I0308 14:14:01.966628 20600 manager.go:429] Destroyed container: "/docker/13c9acebe3739f40e98b9c70a6648fbfbcdbd9eb11395a362c6cde5a93fda320" (aliases: [proxy3 13c9acebe3739f40e98b9c70a6648fbfbcdbd9eb11395a362c6cde5a93fda320], namespace: "docker")
2015-03-08 13:16:30,899 ERROR agent [139802978835184] [event.py:108] 55587bff-1b5d-4120-8aec-acca2649465d : Unknown error 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 91, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 33, in execute
    return method(req=req, **req.data.__dict__)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/delegate.py", line 145, in delegate_request
    event)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/delegate.py", line 87, in container_exec
    }, timeout=DockerConfig.delegate_timeout())
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 500, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

**Comment by ibuildthecloud** [comment]
Bad status line usually means the HTTP response is malformed.  I've only seen this before when I was running in an environment where the network streams got corrupted.

**Comment by feliksik** [comment]
If you cannot print the HTTP response in the status line, that it may be nice to at log the request URL that generated the error. Even if it is a POST of which the body is not logged. A ConnectionError suggests that there is no nice HTTP endpoint, which you can often debug even with an empty POST body I guess (does the server talk HTTP nicely, or not)

**Comment by deniseschannon** [comment]
@feliksik In the latest versions, are you still seeing this happening?

**Comment by deniseschannon** [comment]
Marking this as obsolete as we haven't had others complaining about this. @feliksik If you still see similar issues, please open a new issue.
