### ISSUE TITLE
Rancher crash every boot

### ISSUE THREAD

**Issue by segator** [rancher/rancher#17301]
I have rancher latest version rancher/rancher:latest

It work pretty fine more 10 days but today I tried to access to rancher UI and I see the system is rebooting every 5 minutes

I don't understand I didn't modify anything, yesterday night it worked perfectly today is not able to boot.

There is some log, there are a lot and I don't see what exactly show you. 
```
2019/01/03 18:16:43 [INFO] Rancher version v2.1.4 is starting
2019/01/03 18:16:43 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:auto Embedded:false KubeConfig: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false NoCACerts:false ListenConfig:<nil> AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0}
2019/01/03 18:16:43 [INFO] Listening on /tmp/log.sock
2019/01/03 18:16:43 [INFO] Running etcd --peer-client-cert-auth --client-cert-auth --initial-cluster=etcd-master=https://127.0.0.1:2380 --listen-client-urls=https://0.0.0.0:2379 --listen-peer-urls=https://0.0.0.0:2380 --initial-cluster-state=new --peer-cert-file=/etc/kubernetes/ssl/kube-etcd-127-0-0-1.pem --heartbeat-interval=500 --initial-cluster-token=etcd-cluster-1 --peer-key-file=/etc/kubernetes/ssl/kube-etcd-127-0-0-1-key.pem --election-timeout=5000 --cert-file=/etc/kubernetes/ssl/kube-etcd-127-0-0-1.pem --key-file=/etc/kubernetes/ssl/kube-etcd-127-0-0-1-key.pem --data-dir=/var/lib/rancher/etcd/ --name=etcd-master --advertise-client-urls=https://127.0.0.1:2379,https://127.0.0.1:4001 --initial-advertise-peer-urls=https://127.0.0.1:2380 --trusted-ca-file=/etc/kubernetes/ssl/kube-ca.pem --peer-trusted-ca-file=/etc/kubernetes/ssl/kube-ca.pem
2019-01-03 18:16:43.728113 I | etcdmain: etcd Version: 3.2.13
2019-01-03 18:16:43.728127 I | etcdmain: Git SHA: Not provided (use ./build instead of go build)
2019-01-03 18:16:43.728132 I | etcdmain: Go Version: go1.11
2019-01-03 18:16:43.728140 I | etcdmain: Go OS/Arch: linux/amd64
2019-01-03 18:16:43.728145 I | etcdmain: setting maximum number of CPUs to 8, total number of available CPUs is 8
2019-01-03 18:16:43.728245 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2019-01-03 18:16:43.728274 I | embed: peerTLS: cert = /etc/kubernetes/ssl/kube-etcd-127-0-0-1.pem, key = /etc/kubernetes/ssl/kube-etcd-127-0-0-1-key.pem, ca = , trusted-ca = /etc/kubernetes/ssl/kube-ca.pem, client-cert-auth = true
2019-01-03 18:16:43.728737 I | embed: listening for peers on https://0.0.0.0:2380
2019-01-03 18:16:43.728766 I | embed: listening for client requests on 0.0.0.0:2379
2019-01-03 18:16:44.787935 W | etcdserver: another etcd process is using "/var/lib/rancher/etcd/member/snap/db" and holds the file lock.
2019-01-03 18:16:44.787957 W | etcdserver: waiting for it to exit before starting...
2019-01-03 18:16:46.013549 I | etcdserver: recovered store from snapshot at index 3600039
2019-01-03 18:16:46.082076 I | mvcc: restore compact to 3013331
2019-01-03 18:16:46.224948 I | etcdserver: name = etcd-master
2019-01-03 18:16:46.224975 I | etcdserver: data dir = /var/lib/rancher/etcd/
2019-01-03 18:16:46.224983 I | etcdserver: member dir = /var/lib/rancher/etcd/member
2019-01-03 18:16:46.224987 I | etcdserver: heartbeat = 500ms
2019-01-03 18:16:46.224990 I | etcdserver: election = 5000ms
2019-01-03 18:16:46.224994 I | etcdserver: snapshot count = 100000
2019-01-03 18:16:46.225009 I | etcdserver: advertise client URLs = https://127.0.0.1:2379,https://127.0.0.1:4001
2019-01-03 18:16:46.225122 W | wal: ignored file 000000000000004d-000000000036f6de.wal.broken in wal
2019-01-03 18:16:46.225132 W | wal: ignored file 000000000000004e-0000000000374761.wal.broken in wal
2019-01-03 18:16:46.225145 W | wal: ignored file 0000000000000050-000000000037a40b.wal.broken in wal
2019-01-03 18:17:06.550745 I | etcdserver: restarting member e92d66acd89ecf29 in cluster 7581d6eb2d25405b at commit index 3663868
2019-01-03 18:17:06.553661 I | raft: e92d66acd89ecf29 became follower at term 343
2019-01-03 18:17:06.553692 I | raft: newRaft e92d66acd89ecf29 [peers: [e92d66acd89ecf29], term: 343, commit: 3663868, applied: 3600039, lastindex: 3663868, lastterm: 343]
2019-01-03 18:17:06.553851 I | etcdserver/api: enabled capabilities for version 3.2
2019-01-03 18:17:06.553870 I | etcdserver/membership: added member e92d66acd89ecf29 [https://127.0.0.1:2380] to cluster 7581d6eb2d25405b from store
2019-01-03 18:17:06.553877 I | etcdserver/membership: set the cluster version to 3.2 from store
2019-01-03 18:17:06.666227 I | mvcc: restore compact to 3013331
2019-01-03 18:17:06.773283 W | auth: simple token is not cryptographically signed
2019-01-03 18:17:07.098780 I | etcdserver: starting server... [version: 3.2.13, cluster version: 3.2]
2019-01-03 18:17:07.099226 I | embed: ClientTLS: cert = /etc/kubernetes/ssl/kube-etcd-127-0-0-1.pem, key = /etc/kubernetes/ssl/kube-etcd-127-0-0-1-key.pem, ca = , trusted-ca = /etc/kubernetes/ssl/kube-ca.pem, client-cert-auth = true
2019-01-03 18:17:11.554263 I | raft: e92d66acd89ecf29 is starting a new election at term 343
2019-01-03 18:17:11.554329 I | raft: e92d66acd89ecf29 became candidate at term 344
2019-01-03 18:17:11.554343 I | raft: e92d66acd89ecf29 received MsgVoteResp from e92d66acd89ecf29 at term 344
2019-01-03 18:17:11.554353 I | raft: e92d66acd89ecf29 became leader at term 344
2019-01-03 18:17:11.554358 I | raft: raft.node: e92d66acd89ecf29 elected leader e92d66acd89ecf29 at term 344
2019-01-03 18:17:11.554682 I | etcdserver: published {Name:etcd-master ClientURLs:[https://127.0.0.1:2379 https://127.0.0.1:4001]} to cluster 7581d6eb2d25405b
2019-01-03 18:17:11.554708 I | embed: ready to serve client requests
2019-01-03 18:17:11.554899 I | embed: serving client requests on [::]:2379
2019/01/03 18:17:11 [INFO] Running kube-apiserver --proxy-client-cert-file= --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --endpoint-reconciler-type=lease --authorization-mode=Node,RBAC --insecure-bind-address=127.0.0.1 --requestheader-extra-headers-prefix= --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --client-ca-file=/etc/kubernetes/ssl/kube-ca.pem --tls-private-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem --kubelet-client-key=/etc/kubernetes/ssl/kube-apiserver-key.pem --etcd-keyfile=/etc/kubernetes/ssl/kube-node-key.pem --etcd-prefix=/registry --secure-port=6443 --allow-privileged=true --storage-backend=etcd3 --requestheader-username-headers= --service-node-port-range=30000-32767 --etcd-cafile=/etc/kubernetes/ssl/kube-ca.pem --proxy-client-key-file= --insecure-port=0 --requestheader-allowed-names= --cloud-provider= --service-cluster-ip-range=10.43.0.0/16 --kubelet-client-certificate=/etc/kubernetes/ssl/kube-apiserver.pem --etcd-servers=https://127.0.0.1:2379 --advertise-address=10.43.0.1 --bind-address=127.0.0.1 --requestheader-client-ca-file= --tls-cert-file=/etc/kubernetes/ssl/kube-apiserver.pem --etcd-certfile=/etc/kubernetes/ssl/kube-node.pem --requestheader-group-headers= --enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota --service-account-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem -v=1 --logtostderr=false --alsologtostderr=false
2019/01/03 18:17:11 [INFO] Activating driver rke
2019/01/03 18:17:11 [INFO] Activating driver rke done
2019/01/03 18:17:11 [INFO] Activating driver gke
2019/01/03 18:17:11 [INFO] Activating driver gke done
2019/01/03 18:17:11 [INFO] Activating driver aks
2019/01/03 18:17:11 [INFO] Activating driver aks done
2019/01/03 18:17:11 [INFO] Activating driver eks
2019/01/03 18:17:11 [INFO] Activating driver eks done
2019/01/03 18:17:11 [INFO] Activating driver import
2019/01/03 18:17:11 [INFO] Activating driver import done
[restful] 2019/01/03 18:17:12 log.go:33: [restful/swagger] listing is available at https://10.43.0.1:6443/swaggerapi
[restful] 2019/01/03 18:17:12 log.go:33: [restful/swagger] https://10.43.0.1:6443/swaggerui/ is mapped to folder /swagger-ui/
[restful] 2019/01/03 18:17:14 log.go:33: [restful/swagger] listing is available at https://10.43.0.1:6443/swaggerapi
[restful] 2019/01/03 18:17:14 log.go:33: [restful/swagger] https://10.43.0.1:6443/swaggerui/ is mapped to folder /swagger-ui/
2019/01/03 18:17:18 [INFO] Running kube-controller-manager --configure-cloud-routes=false --pod-eviction-timeout=5m0s --v=2 --root-ca-file=/etc/kubernetes/ssl/kube-ca.pem --enable-hostpath-provisioner=false --node-monitor-grace-period=40s --allocate-node-cidrs=true --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-controller-manager.yaml --cluster-cidr=10.42.0.0/16 --address=0.0.0.0 --leader-elect=true --cloud-provider= --allow-untagged-cloud=true --service-cluster-ip-range=10.43.0.0/16 --service-account-private-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem --use-service-account-credentials=true -v=1 --logtostderr=false --alsologtostderr=false --controllers * --controllers -resourcequota --controllers -service
2019/01/03 18:17:18 [INFO] Running in single server mode, will not peer connections
E0103 18:17:18.519601       8 leaderelection.go:224] error retrieving resource lock kube-system/kube-controller-manager: endpoints "kube-controller-manager" is forbidden: User "system:kube-controller-manager" cannot get endpoints in the namespace "kube-system"
E0103 18:17:33.520669       8 controller.go:143] Unable to perform initial Kubernetes service initialization: etcdserver: request timed out
2019-01-03 18:17:33.720750 W | etcdserver: timed out waiting for read index response
2019-01-03 18:17:35.385218 W | wal: sync duration of 16.865387566s, expected less than 1s
panic: creating CRD store Get https://127.0.0.1:6443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions?timeout=30s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

goroutine 5073 [running]:
github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd.(*Factory).BatchCreateCRDs.func1(0xc01cbd8d20, 0xc01350e080, 0x8, 0x8, 0xc01a3f2000, 0xba81e00, 0x8121320, 0xc001381ec0, 0x4fdbb05, 0x4)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd/init.go:65 +0x2d9
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd.(*Factory).BatchCreateCRDs
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd/init.go:50 +0xce
panic: creating CRD store Get https://127.0.0.1:6443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions?timeout=30s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

goroutine 4944 [running]:
github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd.(*Factory).BatchCreateCRDs.func1(0xc01cbd8d20, 0xc029f78900, 0x24, 0x24, 0xc01a3f2000, 0xba81d40, 0x8121320, 0xc001381ec0, 0x4fdbb05, 0x4)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd/init.go:65 +0x2d9
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd.(*Factory).BatchCreateCRDs
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd/init.go:50 +0xce
```

**Comment by superseb** [comment]
Please supply the exact `docker run` command used to launch the container. Also the specifications from the host running it as requested in the issue template (CPU/MEM/DISK IO) and `docker info`

**Comment by segator** [comment]
docker run -d rancher-server --name rancher-server -v /zfs-pool/rancher-server:/var/lib/rancher -p 22443:443 -p 22080:80 rancher/rancher

docker info
`Containers: 78
 Running: 61
 Paused: 0
 Stopped: 17
Images: 80
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-39-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.25GiB
Name: france.nodo.ovh
ID: 7UTU:SYRV:T3LR:PE4T:SVCQ:PUH7:562G:Y3O6:FZ52:RBM3:IQZ4:R5CD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
`
CPU
 Intel(R) Xeon(R) CPU E3-1230 v3

Memory  32G (13GB used)

disk 2x2TB sata(dont know oneprovider.net server)
software raid1 mdadm for /
software raid0 ZFS for /zfs-pool (where rancher-server is running)
I know raid0 is danger, don't care is test environment.

Anyway I fixed the problem moving from raid0 ZFS to raid1 ext4
