### ISSUE TITLE
Target service container stuck in "Post-network" state and LB Service stuck in "activating" state forever.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1736]
Server version - Build from master - Aug 4

Create service1 with scale2 and activate.
Create LB service with scale1  and activate.  
Add service2 as target to LB service.

Service1 is stuck in "activating" state for ever since one of the instances of the service is  stuck in "Post-network" state .
LB service is also stuck in "activating" state.

<img width="1017" alt="screen shot 2015-08-04 at 4 46 54 pm" src="https://cloud.githubusercontent.com/assets/4266958/9075321/74ddc242-3ac8-11e5-9cdd-71fc1ef477ed.png">

Following line is repeated every 30 secs in the logs:

Communication timeout on process [service.activate:79584] on [973] : Object [instance:2046] failed to satisfy predicate [15000] millis 

```
cattle-debug.2015-08-04.log:2015-08-04 19:08:32,951 INFO  [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046] [instance.start->(InstanceStart)] [] [ecutorService-2] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [DONE] process [port.activate:null] on resource [3355] 
cattle-debug.2015-08-04.log:2015-08-04 19:08:32,952 INFO  [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046] [instance.start->(InstanceStart)] [] [ecutorService-2] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [port.activate:null] on resource [3356] 
cattle-debug.2015-08-04.log:2015-08-04 19:08:32,960 INFO  [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046->port:3356] [instance.start->(InstanceStart)->port.activate] [] [ecutorService-2] [c.p.e.p.i.DefaultProcessInstanceImpl] Changing state [inactive->activating] on [port:3356] 
cattle-debug.2015-08-04.log:2015-08-04 19:08:32,968 INFO  [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046->port:3356] [instance.start->(InstanceStart)->port.activate->(PortActivate)] [] [ecutorService-2] [c.p.e.p.i.DefaultProcessInstanceImpl] Running handler [PortActivate] 
cattle-debug.2015-08-04.log:2015-08-04 19:08:32,975 INFO  [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046->port:3356] [instance.start->(InstanceStart)->port.activate->(PortActivate)] [] [ecutorService-2] [c.p.e.p.i.DefaultProcessInstanceImpl] Finished handler [PortActivate] 
cattle-debug.2015-08-04.log:2015-08-04 19:08:32,999 INFO  [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046->port:3356] [instance.start->(InstanceStart)->port.activate->(AgentInstanceHostServicesApplyItems)] [] [ecutorService-2] [c.p.e.p.i.DefaultProcessInstanceImpl] Running post listener [AgentInstanceHostServicesApplyItems] 
cattle-debug.2015-08-04.log:2015-08-04 19:08:33,016 INFO  [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046->port:3356] [instance.start->(InstanceStart)->port.activate->(AgentInstanceHostServicesApplyItems)] [] [ecutorService-2] [c.p.e.p.i.DefaultProcessInstanceImpl] Finished post listener [AgentInstanceHostServicesApplyItems] 
cattle-debug.2015-08-04.log:2015-08-04 19:08:33,199 INFO  [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046->port:3356] [instance.start->(InstanceStart)->port.activate] [] [ecutorService-2] [c.p.e.p.i.DefaultProcessInstanceImpl] Changing state [activating->active] on [port:3356] 
cattle-debug.2015-08-04.log:2015-08-04 19:08:33,243 INFO  [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046] [instance.start->(InstanceStart)] [] [ecutorService-2] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [DONE] process [port.activate:null] on resource [3356] 
cattle-debug.2015-08-04.log:2015-08-04 19:08:33,280 INFO  [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046] [instance.start->(InstanceStart)] [] [ecutorService-2] [c.p.e.p.i.DefaultProcessInstanceImpl] Finished handler [InstanceStart] 
cattle-debug.2015-08-04.log:2015-08-04 19:08:33,406 INFO  [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046] [instance.start->(ServiceDiscoveryInstanceStartPostListener)] [] [ecutorService-2] [c.p.e.p.i.DefaultProcessInstanceImpl] Running post listener [ServiceDiscoveryInstanceStartPostListener] 
cattle-debug.2015-08-04.log:2015-08-04 19:08:33,409 INFO  [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046] [instance.start->(ServiceDiscoveryInstanceStartPostListener)] [] [ecutorService-2] [c.p.e.p.i.DefaultProcessInstanceImpl] Finished post listener [ServiceDiscoveryInstanceStartPostListener] 
cattle-debug.2015-08-04.log:2015-08-04 19:08:33,411 INFO  [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046] [instance.start->(LoadBalancerUpdateConfig)] [] [ecutorService-2] [c.p.e.p.i.DefaultProcessInstanceImpl] Running post listener [LoadBalancerUpdateConfig] 
cattle-debug.2015-08-04.log:2015-08-04 19:08:37,306 DEBUG [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046->instanceHostMap:2045] [instance.start->(InstanceStart)->instancehostmap.activate->(AgentInstanceHostServicesApplyItems)] [] [utorService-788] [i.c.p.e.memory.InMemoryEventService ] Unsubscribing from [reply.7548931495400885208] 
cattle-debug.2015-08-04.log:2015-08-04 19:08:37,308 DEBUG [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046->instanceHostMap:2045] [instance.start->(InstanceStart)->instancehostmap.activate->(AgentInstanceHostServicesApplyItems)] [] [utorService-788] [i.c.p.e.memory.InMemoryEventService ] Unsubscribing from [reply.8541683297889941944] 
cattle-debug.2015-08-04.log:2015-08-04 19:08:37,309 DEBUG [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046->instanceHostMap:2045] [instance.start->(InstanceStart)->instancehostmap.activate->(AgentInstanceHostServicesApplyItems)] [] [utorService-788] [i.c.p.e.memory.InMemoryEventService ] Unsubscribing from [reply.6665372350884109321] 
cattle-debug.2015-08-04.log:2015-08-04 19:08:37,309 DEBUG [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046->instanceHostMap:2045] [instance.start->(InstanceStart)->instancehostmap.activate->(AgentInstanceHostServicesApplyItems)] [] [utorService-788] [i.c.p.e.memory.InMemoryEventService ] Unsubscribing from [reply.1353657311568270722] 
cattle-debug.2015-08-04.log:2015-08-04 19:08:37,309 DEBUG [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046->instanceHostMap:2045] [instance.start->(InstanceStart)->instancehostmap.activate->(AgentInstanceHostServicesApplyItems)] [] [utorService-788] [i.c.p.e.memory.InMemoryEventService ] Unsubscribing from [reply.6182693054014814070] 
cattle-debug.2015-08-04.log:2015-08-04 19:08:37,309 DEBUG [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046->instanceHostMap:2045] [instance.start->(InstanceStart)->instancehostmap.activate->(AgentInstanceHostServicesApplyItems)] [] [utorService-788] [i.c.p.e.memory.InMemoryEventService ] Unsubscribing from [reply.695574322202674423] 
cattle-debug.2015-08-04.log:2015-08-04 19:08:37,309 DEBUG [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046->instanceHostMap:2045] [instance.start->(InstanceStart)->instancehostmap.activate->(AgentInstanceHostServicesApplyItems)] [] [utorService-788] [i.c.p.e.memory.InMemoryEventService ] Unsubscribing from [reply.5491730026907140874] 
cattle-debug.2015-08-04.log:2015-08-04 19:08:37,309 DEBUG [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046->instanceHostMap:2045] [instance.start->(InstanceStart)->instancehostmap.activate->(AgentInstanceHostServicesApplyItems)] [] [utorService-788] [i.c.p.e.memory.InMemoryEventService ] Unsubscribing from [reply.1225222021701671121] 
cattle-debug.2015-08-04.log:2015-08-04 19:08:37,309 DEBUG [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046->instanceHostMap:2045] [instance.start->(InstanceStart)->instancehostmap.activate->(AgentInstanceHostServicesApplyItems)] [] [utorService-788] [i.c.p.e.memory.InMemoryEventService ] Unsubscribing from [reply.6562603104731236540] 
cattle-debug.2015-08-04.log:2015-08-04 19:08:37,309 DEBUG [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046->instanceHostMap:2045] [instance.start->(InstanceStart)->instancehostmap.activate->(AgentInstanceHostServicesApplyItems)] [] [utorService-788] [i.c.p.e.memory.InMemoryEventService ] Unsubscribing from [reply.7021765243358516872] 
cattle-debug.2015-08-04.log:2015-08-04 19:08:37,309 DEBUG [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046->instanceHostMap:2045] [instance.start->(InstanceStart)->instancehostmap.activate->(AgentInstanceHostServicesApplyItems)] [] [utorService-788] [i.c.p.e.memory.InMemoryEventService ] Unsubscribing from [reply.2712424319965701435] 
cattle-debug.2015-08-04.log:2015-08-04 19:08:37,308 DEBUG [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046->port:3355] [instance.start->(InstanceStart)->port.activate->(AgentInstanceHostServicesApplyItems)] [] [utorService-915] [i.c.p.e.memory.InMemoryEventService ] Unsubscribing from [reply.7761192692835214225] 
cattle-debug.2015-08-04.log:2015-08-04 19:08:46,183 INFO  [:] [] [] [] [utorService-148] [i.c.p.e.e.i.ProcessEventListenerImpl] Communication timeout on process [service.activate:79584] on [973] : Object [instance:2046] failed to satisfy predicate [15000] millis 
cattle-debug.2015-08-04.log:2015-08-04 19:09:15,707 INFO  [:] [] [] [] [cutorService-49] [i.c.p.e.e.i.ProcessEventListenerImpl] Communication timeout on process [service.activate:79584] on [973] : Object [instance:2046] failed to satisfy predicate [15000] millis 
cattle-debug.2015-08-04.log:2015-08-04 19:09:45,800 INFO  [:] [] [] [] [utorService-133] [i.c.p.e.e.i.ProcessEventListenerImpl] Communication timeout on process [service.activate:79584] on [973] : Object [instance:2046] failed to satisfy predicate [15000] millis 
cattle-debug.2015-08-04.log:2015-08-04 19:10:15,841 INFO  [:] [] [] [] [utorService-144] [i.c.p.e.e.i.ProcessEventListenerImpl] Communication timeout on process [service.activate:79584] on [973] : Object [instance:2046] failed to satisfy predicate [15000] millis 
cattle-debug.2015-08-04.log:2015-08-04 19:10:46,594 INFO  [:] [] [] [] [utorService-157] [i.c.p.e.e.i.ProcessEventListenerImpl] Communication timeout on process [service.activate:79584] on [973] : Object [instance:2046] failed to satisfy predicate [15000] millis 
cattle-debug.2015-08-04.log:2015-08-04 19:11:16,376 INFO  [:] [] [] [] [cutorService-87] [i.c.p.e.e.i.ProcessEventListenerImpl] Communication timeout on process [service.activate:79584] on [973] : Object [instance:2046] failed to satisfy predicate [15000] millis 
cattle-debug.2015-08-04.log:2015-08-04 19:11:47,020 INFO  [:] [] [] [] [cutorService-68] [i.c.p.e.e.i.ProcessEventListenerImpl] Communication timeout on process [service.activate:79584] on [973] : Object [instance:2046] failed to satisfy predicate [15000] millis 
cattle-debug.2015-08-04.log:2015-08-04 19:12:16,942 INFO  [:] [] [] [] [cutorService-21] [i.c.p.e.e.i.ProcessEventListenerImpl] Communication timeout on process [service.activate:79584] on [973] : Object [instance:2046] failed to satisfy predicate [15000] millis 
cattle-debug.2015-08-04.log:2015-08-04 19:12:49,106 INFO  [:] [] [] [] [utorService-122] [i.c.p.e.e.i.ProcessEventListenerImpl] Communication timeout on process [service.activate:79584] on [973] : Object [instance:2046] failed to satisfy predicate [15000] millis 
cattle-debug.2015-08-04.log:2015-08-04 19:13:18,567 INFO  [:] [] [] [] [cutorService-81] [i.c.p.e.e.i.ProcessEventListenerImpl] Communication timeout on process [service.activate:79584] on [973] : Object [instance:2046] failed to satisfy predicate [15000] millis 

````

**Comment by alena1108** [comment]
The root cause of the problem - container being stuck in Starting state because networking setup failed to complete. The instance being stuck caused its service to be stuck in Activating state forever. And as this service is used as a target for the LB service, LB service activation will get stuck waiting for all target services to become Active.

So we have to figure out what had caused the instance start failure.

**Comment by alena1108** [comment]
The problem happened because host-iptables config item failed to update on the backend host for instanceHostMap process. 

Cattle log:
```
2015-08-04 19:08:37,306 DEBUG [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046->instanceHostMap:2045] [instance.start->(InstanceStart)->instancehostmap.activate->(AgentInstanceHostServicesApplyItems)] [] [utorService-788] [i
.c.p.e.memory.InMemoryEventService ] Unsubscribing from [reply.7548931495400885208]
2015-08-04 19:08:37,308 DEBUG [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046->instanceHostMap:2045] [instance.start->(InstanceStart)->instancehostmap.activate->(AgentInstanceHostServicesApplyItems)] [] [utorService-788] [i
.c.p.e.memory.InMemoryEventService ] Unsubscribing from [reply.8541683297889941944]
2015-08-04 19:08:37,309 DEBUG [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046->instanceHostMap:2045] [instance.start->(InstanceStart)->instancehostmap.activate->(AgentInstanceHostServicesApplyItems)] [] [utorService-788] [i
.c.p.e.memory.InMemoryEventService ] Unsubscribing from [reply.6665372350884109321]
2015-08-04 19:08:37,309 DEBUG [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046->instanceHostMap:2045] [instance.start->(InstanceStart)->instancehostmap.activate->(AgentInstanceHostServicesApplyItems)] [] [utorService-788] [i
.c.p.e.memory.InMemoryEventService ] Unsubscribing from [reply.1353657311568270722]
2015-08-04 19:08:37,309 DEBUG [33309138-7c7c-4380-a9b6-c516c465ef57:79586] [instance:2046->instanceHostMap:2045] [instance.start->(InstanceStart)->instancehostmap.activate->(AgentInstanceHostServicesApplyItems)] [] [utorService-788] [i
.c.p.e.memory.InMemoryEventService ] Unsubscribing from [reply.6182693054014814070]
```

See a bunch of errors in the agent log:
```
ERROR cattle [140331788815408] [utils.py:278] Failed to call (['/var/lib/cattle/config.sh', u'host-iptables'],) {'stderr': -2, 'cwd': '/var/lib/cattle', 'env': {'AGENT_PARENT_PID': '3023', 'CATTLE_CONFIG_URL': 'http://latest.rancher.io/v1', 'CATTLE_AGENT_PIDNS': 'host', 'CATTLE_URL': 'http://latest.rancher.io/v1', 'SHLVL': '1', 'OLDPWD': '/tmp', 'HOSTNAME': 'latest-ubuntu-10acre-2', 'PWD': '/var/lib/cattle/pyagent', 'CATTLE_ACCESS_KEY': '0AFAA38DCC6BEF2A35E2', 'CATTLE_AGENT_LOG_FILE': '/var/log/rancher/agent.log', 'CATTLE_AGENT_IP': '130.211.118.217', 'CATTLE_STATE_DIR': '/var/lib/rancher/state', 'CATTLE_SECRET_KEY': '2uzLwggWF73ARKTYSAVNCpvSsJyB4mvRE98z9eZG', 'CATTLE_SYSTEMD': 'false', 'RANCHER_AGENT_IMAGE': 'rancher/agent:v0.7.11', 'HOME': '/root', 'CATTLE_CADVISOR_WRAPPER': 'cadvisor.sh', 'CATTLE_STORAGE_URL': 'http://latest.rancher.io/v1', 'CATTLE_HOME': '/var/lib/cattle', 'PATH': '/var/lib/cattle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'}}, exit [1], output :

Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/utils.py", line 274, in get_command_output
    return check_output(*args, **kw)
  File "/var/lib/cattle/pyagent/cattle/utils.py", line 331, in check_output
    raise e1
```

Then when tried to execute the config.sh script manually, got the following error:

```
root@latest-ubuntu-10acre-2:/# ./var/lib/cattle/config.sh --force host-iptables
Lock failed (edited)
```

Looks like this problem comes and goes, because I just saw it on 10acre-1 at some point on the latest, then it resolved itself.

@will-chan need someone more familiar with python-agent code to look at it. Something causes lock failures on config item updates, need to figure out what exactly.

**Comment by alena1108** [comment]
@sangeethah Haven't seen this issue for a while, please reopen if it happens again
