### ISSUE TITLE
Rancher v2.1.5 Periodically Restarting

### ISSUE THREAD

**Issue by graememross** [rancher/rancher#17441]
Rancher is periodically restarting (once every few hours). When it restarts it breaks all the port-forward connections we have into the system (this includes telepresence connections being used to debug apps)

I suspect some sort of oom problem as rancher is running usually between 1.6g and 2.1g of ram 
```

top - 10:43:39 up 133 days, 19:08,  1 user,  load average: 0.88, 0.83, 1.04
Tasks: 218 total,   2 running, 216 sleeping,   0 stopped,   0 zombie
%Cpu(s):  8.3 us,  4.4 sy,  0.0 ni, 86.9 id,  0.2 wa,  0.0 hi,  0.3 si,  0.0 st
KiB Mem :  4045920 total,   309552 free,  3159476 used,   576892 buff/cache
KiB Swap: 10485756 total,  9999000 free,   486756 used.   595168 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 7457 root      20   0 1654112 942300  18944 S  27.9 23.3   6148:44 kube-apiserver
11823 root      20   0   12.0g   1.7g 136244 S  11.3 44.1   1:37.91 rancher
29773 root      20   0   10.2g 156164  33172 S   6.0  3.9   1906:27 etcd

```
Rancher is running as a "Single Node Install" on one of the k8s master nodes (I would like to convert the cluster to HA, however I don't want to start from scratch and I can't find a documented upgrade path)
```
[mtlgrr@k8s-dev-m02 ~]$ docker info
Containers: 37
 Running: 16
 Paused: 0
 Stopped: 21
Images: 15
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.5 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.858GiB
Name: k8s-dev-m02
ID: F3VE:FA5F:SU4U:XYTE:TESX:6ZTW:T2OL:VGSL:S2LK:XDMG:CZF4:JLQX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```
The only possibly significant message I have found in the logs before a restart is
```
2019/01/14 13:48:57 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->172.29.217.73:13356: i/o timeout
2019/01/14 13:49:01 [FATAL] leaderelection lost for cattle-controllers
2019/01/14 13:49:01 [INFO] Shutting down NamespaceController controller
2019/01/14 13:49:01 [INFO] Shutting down RoleController controller
2019/01/14 13:49:01 [INFO] Shutting down ClusterRoleController controller
2019/01/14 13:49:01 [INFO] Shutting down UserController controller
2019/01/14 13:49:01 [INFO] Shutting down RoleTemplateController controller
2019/01/14 13:49:10 [INFO] Rancher version v2.1.5 is starting
```
Usually there is nothing

Has anyone any suggestions where I should go from here (my users are very patient but ..... )?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.5` UI: `v2.1.19` |
|Route|`authenticated.cluster.index`|

**Comment by graememross** [comment]
[rancher.log](https://github.com/rancher/rancher/files/2763614/rancher.log)

When I reported this yesterday, I had a good look around the container and I noticed that the catalog-manager cache was over 6.5Gb of data. I cleared this out and restarted the server.

Since then the container seems to be stable (at least it has not restarted in the last 24 hours)

Could it be something to do with the cache manager loading all of the files into memory before processing them?

**Comment by graememross** [comment]
Talked too soon. The situation seems better (almost 24 hours without a restart) but it is still restarting. It happened again about the 10:34 point in the log

[rancher.log](https://github.com/rancher/rancher/files/2763865/rancher.log)

**Comment by fabiorauber** [comment]
I'm having a very similar issue, seems to be the same. I'm using version 2.1.7, standalone:

```
rancher_1        | E0320 16:43:44.890959       8 leaderelection.go:270] error retrieving resource lock kube-system/kube-controller-manager: Get https://127.0.0.1:6443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
rancher_1        | E0320 16:43:44.898609       8 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
rancher_1        | E0320 16:43:44.890980       8 event.go:259] Could not construct reference to: '&v1.Endpoints{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Subsets:[]v1.EndpointSubset(nil)}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'LeaderElection' '7494589777e7_c4cf10f8-4b2e-11e9-995c-0242ac110004 stopped leading'
rancher_1        | F0320 16:43:44.903014       8 controllermanager.go:247] leaderelection lost
rancher_1        | goroutine 5103 [running]:
rancher_1        | github.com/rancher/rancher/vendor/github.com/golang/glog.stacks(0xc007f1cd00, 0xc015ec8d20, 0x4c, 0xe3)
rancher_1        | 	/go/src/github.com/rancher/rancher/vendor/github.com/golang/glog/glog.go:766 +0xd4
rancher_1        | github.com/rancher/rancher/vendor/github.com/golang/glog.(*loggingT).output(0xb6fed40, 0xc000000003, 0xc028e6f4a0, 0xb34d131, 0x14, 0xf7, 0x0)
rancher_1        | 	/go/src/github.com/rancher/rancher/vendor/github.com/golang/glog/glog.go:717 +0x306
rancher_1        | github.com/rancher/rancher/vendor/github.com/golang/glog.(*loggingT).printf(0xb6fed40, 0x3, 0x57f1cce, 0x13, 0x0, 0x0, 0x0)
rancher_1        | 	/go/src/github.com/rancher/rancher/vendor/github.com/golang/glog/glog.go:655 +0x14b
rancher_1        | github.com/rancher/rancher/vendor/github.com/golang/glog.Fatalf(0x57f1cce, 0x13, 0x0, 0x0, 0x0)
rancher_1        | 	/go/src/github.com/rancher/rancher/vendor/github.com/golang/glog/glog.go:1145 +0x67
rancher_1        | github.com/rancher/rancher/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.Run.func2()
rancher_1        | 	/go/src/github.com/rancher/rancher/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:247 +0x47
rancher_1        | github.com/rancher/rancher/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run.func1(0xc011a925a0)
rancher_1        | 	/go/src/github.com/rancher/rancher/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:163 +0x40
rancher_1        | github.com/rancher/rancher/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0xc011a925a0, 0x783b3a0, 0xc035708dc0)
rancher_1        | 	/go/src/github.com/rancher/rancher/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:172 +0x112
rancher_1        | github.com/rancher/rancher/vendor/k8s.io/client-go/tools/leaderelection.RunOrDie(0x783b3e0, 0xc000074058, 0x7853e60, 0xc0192bd0e0, 0x37e11d600, 0x2540be400, 0x77359400, 0xc01d991de0, 0x59f19f8, 0x0, ...)
rancher_1        | 	/go/src/github.com/rancher/rancher/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:184 +0x99
rancher_1        | github.com/rancher/rancher/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.Run(0xc01b5d8ee8, 0xc000078240, 0xc0136224f0, 0xc013622490)
rancher_1        | 	/go/src/github.com/rancher/rancher/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:239 +0x8c3
rancher_1        | github.com/rancher/rancher/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.NewControllerManagerCommand.func1(0xc01582f900, 0xb722d48, 0x0, 0x0)
rancher_1        | 	/go/src/github.com/rancher/rancher/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:104 +0x1e5
rancher_1        | github.com/rancher/rancher/vendor/github.com/spf13/cobra.(*Command).execute(0xc01582f900, 0xc00c5b2820, 0x0, 0x19, 0xc01582f900, 0xc00c5b2820)
rancher_1        | 	/go/src/github.com/rancher/rancher/vendor/github.com/spf13/cobra/command.go:760 +0x2cc
rancher_1        | github.com/rancher/rancher/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc01582f900, 0x0, 0xc017578f60, 0xc017578f60)
rancher_1        | 	/go/src/github.com/rancher/rancher/vendor/github.com/spf13/cobra/command.go:846 +0x2fd
rancher_1        | github.com/rancher/rancher/vendor/github.com/spf13/cobra.(*Command).Execute(0xc01582f900, 0xc0116b1200, 0xc017578fa8)
rancher_1        | 	/go/src/github.com/rancher/rancher/vendor/github.com/spf13/cobra/command.go:794 +0x2b
rancher_1        | github.com/rancher/rancher/pkg/hyperkube.NewKubeControllerManager.func1(0xc012daf380, 0xc00c5b2820, 0x0, 0x19, 0xc000078240, 0xc00bc8fa00, 0x0)
rancher_1        | 	/go/src/github.com/rancher/rancher/pkg/hyperkube/kube-controller-manager.go:44 +0x57
rancher_1        | github.com/rancher/rancher/pkg/hyperkube.(*HyperKube).Run.func1(0xc00df3c5a0, 0xc012daf380)
rancher_1        | 	/go/src/github.com/rancher/rancher/pkg/hyperkube/hyperkube.go:184 +0x76
rancher_1        | created by github.com/rancher/rancher/pkg/hyperkube.(*HyperKube).Run
rancher_1        | 	/go/src/github.com/rancher/rancher/pkg/hyperkube/hyperkube.go:183 +0x4e6
rancher_1        | 2019/03/20 16:43:50 [INFO] Rancher version v2.1.7 is starting
```

**Comment by degerrit** [comment]
Similar issue on v2.1.8 standalone - F0424 ... leaderelection lost.

```
2019/04/24 12:50:43 [INFO] Done running cluster events cleanup
2019/04/24 12:50:43 [ERROR] CatalogController library [catalog] failed with : Error in HTTP GET to [https://git.rancher.io/charts/index.yaml], error: Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 10.4.3.50:53: no such host
2019/04/24 12:50:44 [ERROR] CatalogController library [catalog] failed with : Error in HTTP GET to [https://git.rancher.io/charts/index.yaml], error: Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 10.4.3.50:53: no such host
E0424 12:51:38.750169       7 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
2019/04/24 12:54:50 [ERROR] CatalogController library [catalog] failed with : Error in HTTP GET to [https://git.rancher.io/charts/index.yaml], error: Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 10.4.3.50:53: no such host
2019-04-24 12:55:35.735325 I | mvcc: store.index: compact 2016296
2019-04-24 12:55:35.736479 I | mvcc: finished scheduled compaction at 2016296 (took 693.603µs)
2019-04-24 12:56:38.372874 W | etcdserver: apply entries took too long [9.99348551s for 1 entries]
2019-04-24 12:56:38.373131 W | etcdserver: avoid queries with large range/delete range!
2019-04-24 12:56:38.419171 W | wal: sync duration of 10.039806497s, expected less than 1s
F0424 12:56:38.462964       7 controllermanager.go:247] leaderelection lost
goroutine 5148 [running]:
github.com/rancher/rancher/vendor/github.com/golang/glog.stacks(0xc002070600, 0xc01478c870, 0x4c, 0xf0)
        /go/src/github.com/rancher/rancher/vendor/github.com/golang/glog/glog.go:766 +0xd4
github.com/rancher/rancher/vendor/github.com/golang/glog.(*loggingT).output(0xb709d40, 0xc000000003, 0xc00f3b13f0, 0xb3581e9, 0x14, 0xf7, 0x0)
        /go/src/github.com/rancher/rancher/vendor/github.com/golang/glog/glog.go:717 +0x306
github.com/rancher/rancher/vendor/github.com/golang/glog.(*loggingT).printf(0xb709d40, 0x3, 0x57f3d04, 0x13, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/rancher/vendor/github.com/golang/glog/glog.go:655 +0x14b
github.com/rancher/rancher/vendor/github.com/golang/glog.Fatalf(0x57f3d04, 0x13, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/rancher/vendor/github.com/golang/glog/glog.go:1145 +0x67
github.com/rancher/rancher/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.Run.func2()

```

Incidentally I had to change the restartpolicy, since our server container was initially just shutting down completely (unlike our earlier Rancher 1.6):
`docker update --restart=unless-stopped rancher-server`
We deployed the server through rke.

What seems to trigger this shutdown/restart in our case is increased disk (?) latency. I can often trigger it just by pulling/running any random container on the host running the Rancher server.

We are running on Azure, Standard D2s v3, 30GB Premium SSD - but my impression is small SSDs on Azure perform very badly in terms of IOPS.

**Comment by zhangzhenhao** [comment]
same issue of v1.9.0

**Comment by dhrp** [comment]
I do not believe #20263 and this issue are the same. See my comment on the other issue.

**Comment by superseb** [comment]
This is on a now unsupported version and the error usually means bad (disk) performance causing the leader lock/election to fail.
