### ISSUE TITLE
Rancher server SIGSEGV on RKE cluster provision

### ISSUE THREAD

**Issue by erikwilson** [rancher/rancher#17519]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Provisioned 3 node RKE cluster in Azure

**Result:**
```
2019/01/22 10:13:57 [INFO] cluster [c-cfmv5] provisioning: [certificates] Generating etcd-104.42.171.210 certificate and key
2019/01/22 10:13:57 [INFO] cluster [c-cfmv5] provisioning: [certificates] Generating etcd-104.42.181.61 certificate and key
2019/01/22 10:13:58 [INFO] cluster [c-cfmv5] provisioning: [certificates] Generating etcd-104.42.177.27 certificate and key
2019/01/22 10:13:58 [INFO] cluster [c-cfmv5] provisioning: Successfully Deployed state file at [management-state/rke/rke-653903207/cluster.rkestate]
2019/01/22 10:13:58 [INFO] cluster [c-cfmv5] provisioning: Building Kubernetes cluster
2019/01/22 10:13:58 [INFO] cluster [c-cfmv5] provisioning: [dialer] Setup tunnel for host [104.42.177.27]
2019/01/22 10:13:58 [INFO] cluster [c-cfmv5] provisioning: [dialer] Setup tunnel for host [104.42.171.210]
2019/01/22 10:13:58 [INFO] cluster [c-cfmv5] provisioning: [dialer] Setup tunnel for host [104.42.181.61]
2019/01/22 10:13:58 [ERROR] cluster [c-cfmv5] provisioning: Failed to set up SSH tunneling for host [104.42.171.210]: Can't establish dialer connection: can not build dialer to c-cfmv5:m-5h98p
2019/01/22 10:13:58 [ERROR] cluster [c-cfmv5] provisioning: Failed to set up SSH tunneling for host [104.42.181.61]: Can't establish dialer connection: can not build dialer to c-cfmv5:m-n8mbc
2019/01/22 10:13:58 [ERROR] cluster [c-cfmv5] provisioning: Removing host [104.42.181.61] from node lists
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x2151a85]

goroutine 58779 [running]:
github.com/rancher/rancher/vendor/github.com/docker/docker/client.(*Client).getAPIPath(0x0, 0xc00178b680, 0x27, 0x0, 0x5eb8440, 0x0)
	/Users/erik/go/src/github.com/rancher/rancher/vendor/github.com/docker/docker/client/client.go:310 +0x55
github.com/rancher/rancher/vendor/github.com/docker/docker/client.(*Client).sendRequest(0x0, 0x3903860, 0xc026c73590, 0x34f050b, 0x3, 0xc00178b680, 0x27, 0x0, 0x0, 0x0, ...)
	/Users/erik/go/src/github.com/rancher/rancher/vendor/github.com/docker/docker/client/request.go:118 +0x86
github.com/rancher/rancher/vendor/github.com/docker/docker/client.(*Client).get(0x0, 0x3903860, 0xc026c73590, 0xc00178b680, 0x27, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/erik/go/src/github.com/rancher/rancher/vendor/github.com/docker/docker/client/request.go:37 +0xe3
github.com/rancher/rancher/vendor/github.com/docker/docker/client.(*Client).ContainerInspect(0x0, 0x3903860, 0xc026c73590, 0x351541a, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/erik/go/src/github.com/rancher/rancher/vendor/github.com/docker/docker/client/container_inspect.go:18 +0x10a
github.com/rancher/rancher/vendor/github.com/rancher/rke/docker.DoRunContainer(0x3903860, 0xc026c73590, 0x0, 0xc00f4f7680, 0xc0131c5400, 0x351541a, 0x16, 0xc020e21860, 0xe, 0x34f579d, ...)
	/Users/erik/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/docker/docker.go:52 +0x92
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.(*Cluster).deployListener(0xc021370000, 0x3903860, 0xc026c73590, 0xc00ef4d700, 0x53f59c0, 0x2, 0x2, 0x351541a, 0x16, 0xc0138fc000, ...)
	/Users/erik/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/network.go:334 +0x3e2
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.(*Cluster).deployListenerOnPlane.func1(0x8, 0x35e27b0)
	/Users/erik/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/network.go:301 +0x168
github.com/rancher/rancher/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc021d582a0, 0xc01a20bf90)
	/Users/erik/go/src/github.com/rancher/rancher/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by github.com/rancher/rancher/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/Users/erik/go/src/github.com/rancher/rancher/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66
```

**Other details that may be helpful:**
Found for testing of /issues/15788

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
master (1444ef028a)
- Installation option (single install/HA):
single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Azure/RKE
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
Standard_DS11_v2 (2vcpu/14gb)
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):

```
Containers: 47
 Running: 39
 Paused: 0
 Stopped: 8
Images: 114
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 15.65GiB
Name: linuxkit-025000000001
ID: 7IES:JTCE:43DI:7XOI:Z6PG:SA7H:IQXK:T47X:FEP5:REZM:6TYL:NDNE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Comment by erikwilson** [comment]
Also occurred on DigitalOcean provisioning 5 node cluster:
```
2019/01/23 17:51:00 [INFO] cluster [c-wbflx] provisioning: Building Kubernetes cluster
2019/01/23 17:51:00 [INFO] cluster [c-wbflx] provisioning: [dialer] Setup tunnel for host [68.183.144.129]
2019/01/23 17:51:00 [INFO] cluster [c-wbflx] provisioning: [dialer] Setup tunnel for host [159.65.247.106]
2019/01/23 17:51:00 [INFO] cluster [c-wbflx] provisioning: [dialer] Setup tunnel for host [174.138.58.162]
2019/01/23 17:51:00 [INFO] cluster [c-wbflx] provisioning: [dialer] Setup tunnel for host [159.65.245.49]
2019/01/23 17:51:00 [ERROR] cluster [c-wbflx] provisioning: Failed to set up SSH tunneling for host [68.183.144.129]: Can't establish dialer connection: can not build dialer to c-wbflx:m-zwcxn
2019/01/23 17:51:00 [ERROR] cluster [c-wbflx] provisioning: Failed to set up SSH tunneling for host [174.138.58.162]: Can't establish dialer connection: can not build dialer to c-wbflx:m-ccgjs
2019/01/23 17:51:00 [INFO] cluster [c-wbflx] provisioning: [dialer] Setup tunnel for host [159.65.249.137]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x2152575]

goroutine 9377 [running]:
github.com/rancher/rancher/vendor/github.com/docker/docker/client.(*Client).getAPIPath(0x0, 0xc01ab93890, 0x27, 0x0, 0x5ed0750, 0x0)
	/Users/erik/go/src/github.com/rancher/rancher/vendor/github.com/docker/docker/client/client.go:310 +0x55
github.com/rancher/rancher/vendor/github.com/docker/docker/client.(*Client).sendRequest(0x0, 0x3908a00, 0xc00cc28720, 0x34f330b, 0x3, 0xc01ab93890, 0x27, 0x0, 0x0, 0x0, ...)
	/Users/erik/go/src/github.com/rancher/rancher/vendor/github.com/docker/docker/client/request.go:118 +0x86
github.com/rancher/rancher/vendor/github.com/docker/docker/client.(*Client).get(0x0, 0x3908a00, 0xc00cc28720, 0xc01ab93890, 0x27, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/erik/go/src/github.com/rancher/rancher/vendor/github.com/docker/docker/client/request.go:37 +0xe3
github.com/rancher/rancher/vendor/github.com/docker/docker/client.(*Client).ContainerInspect(0x0, 0x3908a00, 0xc00cc28720, 0x3518264, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/erik/go/src/github.com/rancher/rancher/vendor/github.com/docker/docker/client/container_inspect.go:18 +0x10a
github.com/rancher/rancher/vendor/github.com/rancher/rke/docker.DoRunContainer(0x3908a00, 0xc00cc28720, 0x0, 0xc002d1da40, 0xc00175b000, 0x3518264, 0x16, 0xc01ab6d500, 0xe, 0x34f859d, ...)
	/Users/erik/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/docker/docker.go:52 +0x92
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.(*Cluster).deployListener(0xc006442400, 0x3908a00, 0xc00cc28720, 0xc01af89080, 0x53fba00, 0x2, 0x2, 0x3518264, 0x16, 0xc0174724b0, ...)
	/Users/erik/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/network.go:334 +0x3e2
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.(*Cluster).deployListenerOnPlane.func1(0x8, 0x35e5d90)
	/Users/erik/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/network.go:301 +0x168
github.com/rancher/rancher/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc01454e1b0, 0xc015579a90)
	/Users/erik/go/src/github.com/rancher/rancher/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by github.com/rancher/rancher/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/Users/erik/go/src/github.com/rancher/rancher/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66
```

**Comment by sowmyav27** [comment]
verified on `rancher:v2.2.2-rc9`.
Able to successfully create a DO cluster and an AWS EC2 cluster with 5 nodes(all roles) each.
K8s version - `v1.13.5`
docker version = `18.9.4`
