### ISSUE TITLE
Upgrade Rancher from v2.1.6 to master panic

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#17958]
rancher/rancher:master 2/11

I was testing upgrade Rancher server from v2.1.6 to master and got following panic:

```
2019/02/11 08:16:08 [INFO] Rancher version 532d261d is starting
2019/02/11 08:16:08 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:auto Embedded:false KubeConfig:/tmp/kubeconfig HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false NoCACerts:false ListenConfig:<nil> AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0}
2019/02/11 08:16:08 [INFO] Listening on /tmp/log.sock
I0211 08:16:08.330223       7 http.go:110] HTTP2 has been explicitly disabled
2019/02/11 08:16:08 [INFO] Running in single server mode, will not peer connections
2019/02/11 08:16:08 [INFO] Starting API controllers
I0211 08:16:09.138185       7 leaderelection.go:187] attempting to acquire leader lease  kube-system/cattle-controllers...
2019/02/11 08:16:09 [INFO] Listening on :443
2019/02/11 08:16:09 [INFO] Listening on :80
2019/02/11 08:16:09 [INFO] Registering project network policy
2019/02/11 08:16:09 [INFO] registering podsecuritypolicy cluster handler for cluster local
2019/02/11 08:16:09 [INFO] registering podsecuritypolicy project handler for cluster local
2019/02/11 08:16:09 [INFO] registering podsecuritypolicy namespace handler for cluster local
2019/02/11 08:16:09 [INFO] registering podsecuritypolicy serviceaccount handler for cluster local
2019/02/11 08:16:09 [INFO] registering podsecuritypolicy template handler for cluster local
2019/02/11 08:16:09 [INFO] Registering monitoring for cluster "local"
2019/02/11 08:16:09 [INFO] Registering namespaceHandler for adding labels 
2019/02/11 08:16:09 [INFO] Starting cluster controllers for local
2019/02/11 08:16:09 [INFO] Starting cluster agent for local [owner=true]
2019/02/11 08:16:09 [ERROR] ProjectController local/p-mpzcl [system-image-upgrade-controller] failed with : get template system-library-rancher-logging failed: catalogTemplate.management.cattle.io "cattle-global-data/system-library-rancher-logging" not found
2019/02/11 08:16:09 [ERROR] ProjectController local/p-s2bmb [system-image-upgrade-controller] failed with : get template system-library-rancher-logging failed: catalogTemplate.management.cattle.io "cattle-global-data/system-library-rancher-logging" not found
2019/02/11 08:16:10 [ERROR] ProjectController local/p-mpzcl [system-image-upgrade-controller] failed with : get template system-library-rancher-logging failed: catalogTemplate.management.cattle.io "cattle-global-data/system-library-rancher-logging" not found
2019/02/11 08:16:10 [ERROR] ProjectController local/p-s2bmb [system-image-upgrade-controller] failed with : get template system-library-rancher-logging failed: catalogTemplate.management.cattle.io "cattle-global-data/system-library-rancher-logging" not found
2019/02/11 08:16:11 [INFO] Handling backend connection request [local:machine-h7pfp]
2019/02/11 08:16:11 [INFO] Handling backend connection request [local]
2019/02/11 08:16:11 [ERROR] ProjectController local/p-mpzcl [system-image-upgrade-controller] failed with : get template system-library-rancher-logging failed: catalogTemplate.management.cattle.io "cattle-global-data/system-library-rancher-logging" not found
2019/02/11 08:16:11 [ERROR] ProjectController local/p-s2bmb [system-image-upgrade-controller] failed with : get template system-library-rancher-logging failed: catalogTemplate.management.cattle.io "cattle-global-data/system-library-rancher-logging" not found
2019/02/11 08:16:13 [ERROR] ProjectController local/p-mpzcl [system-image-upgrade-controller] failed with : get template system-library-rancher-logging failed: catalogTemplate.management.cattle.io "cattle-global-data/system-library-rancher-logging" not found
2019/02/11 08:16:13 [ERROR] ProjectController local/p-s2bmb [system-image-upgrade-controller] failed with : get template system-library-rancher-logging failed: catalogTemplate.management.cattle.io "cattle-global-data/system-library-rancher-logging" not found
2019/02/11 08:16:17 [ERROR] ProjectController local/p-mpzcl [system-image-upgrade-controller] failed with : get template system-library-rancher-logging failed: catalogTemplate.management.cattle.io "cattle-global-data/system-library-rancher-logging" not found
2019/02/11 08:16:18 [ERROR] ProjectController local/p-s2bmb [system-image-upgrade-controller] failed with : get template system-library-rancher-logging failed: catalogTemplate.management.cattle.io "cattle-global-data/system-library-rancher-logging" not found
2019/02/11 08:16:26 [ERROR] ProjectController local/p-mpzcl [system-image-upgrade-controller] failed with : get template system-library-rancher-logging failed: catalogTemplate.management.cattle.io "cattle-global-data/system-library-rancher-logging" not found
2019/02/11 08:16:26 [ERROR] ProjectController local/p-s2bmb [system-image-upgrade-controller] failed with : get template system-library-rancher-logging failed: catalogTemplate.management.cattle.io "cattle-global-data/system-library-rancher-logging" not found
2019/02/11 08:16:42 [ERROR] ProjectController local/p-mpzcl [system-image-upgrade-controller] failed with : get template system-library-rancher-logging failed: catalogTemplate.management.cattle.io "cattle-global-data/system-library-rancher-logging" not found
2019/02/11 08:16:42 [ERROR] ProjectController local/p-s2bmb [system-image-upgrade-controller] failed with : get template system-library-rancher-logging failed: catalogTemplate.management.cattle.io "cattle-global-data/system-library-rancher-logging" not found
I0211 08:16:56.135247       7 leaderelection.go:196] successfully acquired lease kube-system/cattle-controllers
2019/02/11 08:16:56 [INFO] Starting catalog controller
2019/02/11 08:16:56 [INFO] Starting project-level catalog controller
2019/02/11 08:16:56 [INFO] Starting cluster-level catalog controller
2019/02/11 08:16:56 [INFO] Starting management controllers
2019/02/11 08:16:56 [INFO] Reconciling GlobalRoles
2019/02/11 08:16:56 [INFO] Reconciling RoleTemplates
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x2133731]

goroutine 7015 [running]:
github.com/rancher/rancher/pkg/auth/providerrefresh.(*refresher).triggerUserRefresh(0xc000b495f0, 0xc001d44440, 0xc, 0x0)
	/go/src/github.com/rancher/rancher/pkg/auth/providerrefresh/refresh_daemon.go:190 +0x211
github.com/rancher/rancher/pkg/auth/providerrefresh.(*refresher).TriggerUserRefresh(0xc000b495f0, 0xc001d44440, 0xc, 0xc0002e2b00)
	/go/src/github.com/rancher/rancher/pkg/auth/providerrefresh/refresh_daemon.go:132 +0x15b
created by github.com/rancher/rancher/pkg/auth/requests.authHeaderHandler.ServeHTTP
	/go/src/github.com/rancher/rancher/pkg/auth/requests/filter.go:109 +0x5cc
```

Step to reproduce:
1. Run a rancher server v2.1.6 in a kubernetes setup. And wait for the setup complete.
2. Upgrade rancher server version to master and wait for the upgrade complete.
3. Got panic in rancher server log.

**Comment by soumyalj** [comment]
Tested with upgrade from v2.1.6 to master. 
1. Create a 3 node cluster with all 3 roles in each of the nodes
2. Upgrade rancher from v2.1.6 to master
After upgrade, there was no panic in the logs.
