### ISSUE TITLE
Fix concurrent map read/write in norman

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#18036]
Saw this panic in CI:
```
fatal error: concurrent map read and map write
2019/02/12 17:51:15 [INFO] [mgmt-auth-gr-controller] Creating clusterRole cattle-globalrole-nodedrivers-manage for corresponding GlobalRole
2019/02/12 17:51:15 [INFO] [mgmt-auth-gr-controller] Creating clusterRole cattle-globalrole-clusters-create for corresponding GlobalRole

goroutine 9635 [running]:
runtime.throw(0x39d8892, 0x21)
	/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc001db6a00 sp=0xc001db69d0 pc=0x42c4c2
runtime.mapaccess2(0x3242420, 0xc00158c060, 0xc00721a180, 0x8, 0x4fd207)
	/usr/local/go/src/runtime/map.go:453 +0x223 fp=0xc001db6a48 sp=0xc001db6a00 pc=0x40db83
reflect.mapaccess(0x3242420, 0xc00158c060, 0xc00721a180, 0x39aed7e)
	/usr/local/go/src/runtime/map.go:1249 +0x3f fp=0xc001db6a80 sp=0xc001db6a48 pc=0x40fccf
reflect.Value.MapIndex(0x3242420, 0xc00682c330, 0x195, 0x3098440, 0xc00721a180, 0x98, 0xc0069f8e80, 0x0, 0xc0000e0380)
	/usr/local/go/src/reflect/value.go:1081 +0x11d fp=0xc001db6b00 sp=0xc001db6a80 pc=0x4bf33d
encoding/json.(*mapEncoder).encode(0xc0002f0258, 0xc0008f4dc0, 0x3242420, 0xc00682c330, 0x195, 0x100)
	/usr/local/go/src/encoding/json/encode.go:692 +0x329 fp=0xc001db6c70 sp=0xc001db6b00 pc=0x717529
encoding/json.(*mapEncoder).encode-fm(0xc0008f4dc0, 0x3242420, 0xc00682c330, 0x195, 0x100)
	/usr/local/go/src/encoding/json/encode.go:708 +0x64 fp=0xc001db6cb0 sp=0xc001db6c70 pc=0x721594
encoding/json.(*structEncoder).encode(0xc001024690, 0xc0008f4dc0, 0x38c2fe0, 0xc00682c2a0, 0x199, 0x100)
	/usr/local/go/src/encoding/json/encode.go:647 +0x280 fp=0xc001db6e10 sp=0xc001db6cb0 pc=0x716e90
encoding/json.(*structEncoder).encode-fm(0xc0008f4dc0, 0x38c2fe0, 0xc00682c2a0, 0x199, 0x100)
	/usr/local/go/src/encoding/json/encode.go:661 +0x64 fp=0xc001db6e50 sp=0xc001db6e10 pc=0x721514
encoding/json.(*structEncoder).encode(0xc002a70810, 0xc0008f4dc0, 0x3631b20, 0xc00682c280, 0x199, 0x710100)
	/usr/local/go/src/encoding/json/encode.go:647 +0x280 fp=0xc001db6fb0 sp=0xc001db6e50 pc=0x716e90
encoding/json.(*structEncoder).encode-fm(0xc0008f4dc0, 0x3631b20, 0xc00682c280, 0x199, 0xc006820100)
	/usr/local/go/src/encoding/json/encode.go:661 +0x64 fp=0xc001db6ff0 sp=0xc001db6fb0 pc=0x721514
encoding/json.(*ptrEncoder).encode(0xc0000141e0, 0xc0008f4dc0, 0x3942c00, 0xc00682c280, 0x16, 0x3940100)
	/usr/local/go/src/encoding/json/encode.go:788 +0xb3 fp=0xc001db7038 sp=0xc001db6ff0 pc=0x7184a3
encoding/json.(*ptrEncoder).encode-fm(0xc0008f4dc0, 0x3942c00, 0xc00682c280, 0x16, 0xc001db0100)
	/usr/local/go/src/encoding/json/encode.go:793 +0x64 fp=0xc001db7078 sp=0xc001db7038 pc=0x721714
encoding/json.(*encodeState).reflectValue(0xc0008f4dc0, 0x3942c00, 0xc00682c280, 0x16, 0x68c0100)
	/usr/local/go/src/encoding/json/encode.go:333 +0x82 fp=0xc001db70b0 sp=0xc001db7078 pc=0x7147c2
encoding/json.(*encodeState).marshal(0xc0008f4dc0, 0x3942c00, 0xc00682c280, 0xc006d50100, 0x0, 0x0)
	/usr/local/go/src/encoding/json/encode.go:305 +0xf4 fp=0xc001db70f8 sp=0xc001db70b0 pc=0x714274
encoding/json.(*Encoder).Encode(0xc001db7240, 0x3942c00, 0xc00682c280, 0x40b9c3, 0x7f6d3adf0e48)
	/usr/local/go/src/encoding/json/stream.go:200 +0x8a fp=0xc001db7188 sp=0xc001db70f8 pc=0x71f33a
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.unstructuredJSONScheme.Encode(0x4049f80, 0xc00682c280, 0x40333e0, 0xc00379e000, 0x0, 0xc005bf4060)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/helpers.go:347 +0x53d fp=0xc001db73a0 sp=0xc001db7188 pc=0x98637d
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*unstructuredJSONScheme).Encode(0x68f4b60, 0x4049f80, 0xc00682c280, 0x40333e0, 0xc00379e000, 0x3942c01, 0xc00379e000)
	<autogenerated>:1 +0x5a fp=0xc001db73e0 sp=0xc001db73a0 pc=0x98c52a
github.com/rancher/rancher/vendor/github.com/rancher/norman/objectclient/dynamic.(*dynamicCodec).Encode(0xc0008b7e40, 0x4049f80, 0xc00682c280, 0x40333e0, 0xc00379e000, 0x3942c00, 0x1)
	<autogenerated>:1 +0x64 fp=0xc001db7428 sp=0xc001db73e0 pc=0x1dbf094
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/runtime.Encode(0x7f6d3b245168, 0xc0008b7e40, 0x4049f80, 0xc00682c280, 0xc00682c280, 0x1, 0x0, 0xc005bf4060, 0x23)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/runtime/codec.go:46 +0x74 fp=0xc001db7478 sp=0xc001db7428 pc=0x84eb54
github.com/rancher/rancher/vendor/k8s.io/client-go/rest.(*Request).Body(0xc006608180, 0x3942c00, 0xc00682c280, 0xc006608180)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/client-go/rest/request.go:400 +0x242 fp=0xc001db7550 sp=0xc001db7478 pc=0x95d7c2
github.com/rancher/rancher/vendor/github.com/rancher/norman/objectclient.(*ObjectClient).Create(0xc0034bea80, 0x4049f80, 0xc00682c280, 0x50, 0x30d9e20, 0x1, 0xc006316960)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/objectclient/object_client.go:125 +0x460 fp=0xc001db7740 sp=0xc001db7550 pc=0xa27690
github.com/rancher/rancher/vendor/github.com/rancher/types/apis/rbac.authorization.k8s.io/v1.(*clusterRoleClient).Create(0xc003c56570, 0xc00682c280, 0xc001db7848, 0x2, 0x2)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/rbac.authorization.k8s.io/v1/zz_generated_cluster_role_controller.go:198 +0x49 fp=0xc001db7788 sp=0xc001db7740 pc=0x2027f49
github.com/rancher/rancher/pkg/controllers/management/auth.(*globalRoleLifecycle).reconcileGlobalRole(0xc003a22600, 0xc0074462c0, 0x1, 0xc001db7920)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/auth/globalrole_handler.go:66 +0x647 fp=0xc001db78b8 sp=0xc001db7788 pc=0x2583787
github.com/rancher/rancher/pkg/controllers/management/auth.(*globalRoleLifecycle).Create(0xc003a22600, 0xc0074462c0, 0x1, 0xc008fd2fc0, 0x1, 0x4)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/auth/globalrole_handler.go:36 +0x35 fp=0xc001db78e8 sp=0xc001db78b8 pc=0x2583085
github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3.(*globalRoleLifecycleAdapter).Create(0xc000c416a0, 0x4043180, 0xc0074462c0, 0x1, 0xc00380cf00, 0x1, 0x1)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_global_role_lifecycle_adapter.go:29 +0x
```

Cause is norman modifies the label map on the resource to add creator. Fix is to copy the labels map before modifying

**Comment by cjellick** [comment]
No way to test. Only ever seen it once in drone. You'll just have to trust me

**Comment by cjellick** [comment]
@daxmc99 to validate

**Comment by daxmc99** [comment]
Steps taken to validate:

1. Run rancher with modified code commented out and observed object creation 
2. Ran rancher with current code and observed object creation.
3. Use debugger to force entry into else-clause (not normally expected to be hit unless multiple calls happen concurrently)
4. Observed creation of cluster roles in all cases.
