### ISSUE TITLE
Intermittent errors seen when adding Digital Ocean machine - "Maximum number of retries (60) exceeded"/"exit status 255"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1806]
Server version - v0.33.0-rc1

In my set up , I had added multiple Digital ocean machines earlier without any issues.

When I tried to add another Digital ocean machine , it failed with "Maximum number of retries (60) exceeded".
In this failure case , I see a machine was created in Digital Ocean,
Right after this failure , I tried to add another Digital ocean machine and this failed with "exit status 255".
In this failure case , I don't  see any attempt being made to create machines in Digital Ocean. It errors out almost immediately.

server logs when this issue was seen:

```
time="2015-08-16T19:15:11Z" level=info msg="Purging Machine" eventId="904ee637-1771-4a91-9fd2-94cf21d2cc1d" resourceId=1ph6 
time="2015-08-16T22:21:11Z" level=info msg="Creating Machine" eventId="0a796c8a-4672-4cf3-927a-6f41f234cb15" resourceId=1ph13 
time="2015-08-16T22:21:11Z" level=info msg="Cmd slice: [create -d digitalocean --digitalocean-access-token 221b602502f01ebb9bb06dd916068cf99dec300d6bd1a5d7491bca7d608564b1 --digitalocean-image ubuntu-14-04-x64 --digitalocean-region nyc3 --digitalocean-size 1gb testme1]" 
time="2015-08-16T22:21:11Z" level=info msg="stdout: Creating CA: /var/lib/cattle/machine/ca395e47-56f6-4ffe-a23c-89c227c1ef1c/certs/ca.pem" resourceId: =1ph13 
time="2015-08-16T22:21:12Z" level=info msg="stdout: Creating client certificate: /var/lib/cattle/machine/ca395e47-56f6-4ffe-a23c-89c227c1ef1c/certs/cert.pem" resourceId: =1ph13 
time="2015-08-16T22:21:13Z" level=info msg="stdout: Creating SSH key..." resourceId: =1ph13 
time="2015-08-16T22:21:14Z" level=info msg="stdout: Creating Digital Ocean droplet..." resourceId: =1ph13 
time="2015-08-16T22:21:34Z" level=info msg="Creating Machine" eventId="250e4735-3166-4758-9990-06d812447764" resourceId=1ph14 
time="2015-08-16T22:21:34Z" level=info msg="Cmd slice: [create -d digitalocean --digitalocean-access-token 221b602502f01ebb9bb06dd916068cf99dec300d6bd1a5d7491bca7d608564b1 --digitalocean-image ubuntu-14-04-x64 --digitalocean-region nyc3 --digitalocean-size 1gb testme2]" 
time="2015-08-16T22:21:34Z" level=info msg="stdout: Creating CA: /var/lib/cattle/machine/6fbfaf35-37b1-43e7-8311-d9223ccf353e/certs/ca.pem" resourceId: =1ph14 
time="2015-08-16T22:21:36Z" level=info msg="stdout: Creating client certificate: /var/lib/cattle/machine/6fbfaf35-37b1-43e7-8311-d9223ccf353e/certs/cert.pem" resourceId: =1ph14 
time="2015-08-16T22:21:37Z" level=info msg="stdout: Creating SSH key..." resourceId: =1ph14 
time="2015-08-16T22:21:38Z" level=info msg="stdout: Creating Digital Ocean droplet..." resourceId: =1ph14 
2015-08-16 22:21:44,050 ERROR [:] [] [] [] [torService-1557] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [70] count [1] 
time="2015-08-16T22:21:46Z" level=info msg="Registering backend for host [ba220d5f-37c0-4326-adda-e669c1c87a49]" 
2015-08-16 22:21:49,050 ERROR [:] [] [] [] [torService-1559] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [70] count [1] 
time="2015-08-16T22:24:36Z" level=info msg="stderr: Error creating machine: Maximum number of retries (60) exceeded" resourceId=1ph13 
time="2015-08-16T22:24:36Z" level=info msg="stderr: You will want to check the provider to make sure the machine and associated resources were properly removed." resourceId=1ph13 
time="2015-08-16T22:24:36Z" level=info msg="starting cleanup..." machine name=testme1 
time="2015-08-16T22:24:36Z" level=info msg="cleanup successful" machine name=testme1 
time="2015-08-16T22:24:36Z" level=error msg="Error processing event" err="Maximum number of retries (60) exceeded" eventId="0a796c8a-4672-4cf3-927a-6f41f234cb15" eventName="physicalhost.create;handler=goMachineService" resourceId=1ph13 
time="2015-08-16T22:25:38Z" level=info msg="stderr: Error creating machine: exit status 255" resourceId=1ph14 
time="2015-08-16T22:25:38Z" level=info msg="stderr: You will want to check the provider to make sure the machine and associated resources were properly removed." resourceId=1ph14 
time="2015-08-16T22:25:38Z" level=info msg="starting cleanup..." machine name=testme2 
time="2015-08-16T22:25:38Z" level=info msg="cleanup successful" machine name=testme2 
time="2015-08-16T22:25:38Z" level=error msg="Error processing event" err="exit status 255" eventId="250e4735-3166-4758-9990-06d812447764" eventName="physicalhost.create;handler=goMachineService" resourceId=1ph14 
```

Also i see go-machine services existing and connecting back mutliple times , because of the following exception seen:

```
2015-08-16 23:07:29,588 ERROR [:] [] [] [] [torService-1596] [o.a.c.m.context.NoExceptionRunnable ] Uncaught exception org.jooq.exception.DataChangedException: Database record has been changed
	at org.jooq.impl.UpdatableRecordImpl.checkIfChanged(UpdatableRecordImpl.java:550) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.UpdatableRecordImpl.storeUpdate0(UpdatableRecordImpl.java:291) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.UpdatableRecordImpl.access$200(UpdatableRecordImpl.java:90) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.UpdatableRecordImpl$3.operate(UpdatableRecordImpl.java:260) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:123) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.UpdatableRecordImpl.storeUpdate(UpdatableRecordImpl.java:255) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.UpdatableRecordImpl.update(UpdatableRecordImpl.java:149) ~[jooq-3.3.0.jar:na]
	at io.cattle.platform.object.impl.JooqObjectManager.persistRecord(JooqObjectManager.java:216) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.object.impl.JooqObjectManager.setFieldsInternal(JooqObjectManager.java:125) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.object.impl.JooqObjectManager$3.execute(JooqObjectManager.java:113) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.idempotent.Idempotent.change(Idempotent.java:88) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.object.impl.JooqObjectManager.setFields(JooqObjectManager.java:110) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.agent.server.resource.impl.AgentResourcesMonitorImpl.setHosts(AgentResourcesMonitorImpl.java:206) ~[cattle-iaas-agent-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.agent.server.resource.impl.AgentResourcesMonitorImpl$2.doWithLockNoResult(AgentResourcesMonitorImpl.java:125) ~[cattle-iaas-agent-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.agent.server.resource.impl.AgentResourcesMonitorImpl.pingReply(AgentResourcesMonitorImpl.java:116) ~[cattle-iaas-agent-server-0.5.0-SNAPSHOT.jar:na]
	at sun.reflect.GeneratedMethodAccessor663.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
	at io.cattle.platform.eventing.annotation.MethodInvokingListener$1.doWithLockNoResult(MethodInvokingListener.java:76) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.annotation.MethodInvokingListener.onEvent(MethodInvokingListener.java:72) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]

time="2015-08-16T23:34:01Z" level=info msg="Exiting go-machine-service..." 
time="2015-08-16T23:34:02Z" level=info msg="Setting log level" logLevel=info 
time="2015-08-16T23:34:02Z" level=info msg="Starting go-machine-service..." gitcommit=102d311 
time="2015-08-16T23:34:02Z" level=info msg="Initializing event router" workerCount=10 
time="2015-08-16T23:34:03Z" level=info msg="Connection established" 
```
Why is this happening ?

**Comment by cjellick** [comment]
docker-machine error...not much we can do here. Can we close?

**Comment by deniseschannon** [comment]
These are all docker-machine bugs, so I'm going to close the issue. There's nothing more that Rancher can do.
