### ISSUE TITLE
Rancher panics when GKE cluster gets created with invalid values

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18073]
Version: Master 2.2 (2/13/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Note it's possible this was environmental.
- Create a GKE cluster that won't provision correctly. Such as selecting a bad Network so it will go in error state.
- Try to delete it in rancher and it will never delete.
![image](https://user-images.githubusercontent.com/45179589/52819687-2f02fb00-3067-11e9-8885-75ca70eeeef9.png)

- Eventually the rancher server might panic as it will actually eventually get removed from GKE if you try in the UI to delete it a few more times but rancher doesn't think it's deleted still. Try to remove from GKE google cloud console and you are pretty much guaranteed to get a panic.
- GKE cluster goes to unavailable state, rancher panics.

**Result:**
Partial log followed by Panic:
```
I0213 20:55:03.843889       8 disruption.go:288] Starting disruption controller
I0213 20:55:03.843928       8 controller_utils.go:1027] Waiting for caches to sync for disruption controller
I0213 20:55:03.843981       8 cronjob_controller.go:94] Starting CronJob Manager
I0213 20:55:03.845373       8 graph_builder.go:308] GraphBuilder running
I0213 20:55:03.930631       8 controller_utils.go:1034] Caches are synced for tokens controller
2019/02/13 20:55:03 [INFO] adding kontainer driver import
2019/02/13 20:55:03 [INFO] adding kontainer driver rancherKubernetesEngine
2019/02/13 20:55:03 [INFO] adding kontainer driver googleKubernetesEngine
2019/02/13 20:55:03 [INFO] adding kontainer driver azureKubernetesService
2019/02/13 20:55:03 [INFO] adding kontainer driver amazonElasticContainerService
2019/02/13 20:55:04 [INFO] adding kontainer driver aliyunkubernetescontainerservice
2019/02/13 20:55:04 [INFO] adding kontainer driver tencentkubernetesengine
2019/02/13 20:55:04 [INFO] adding kontainer driver huaweicontainercloudengine
2019/02/13 20:55:04 [INFO] Rancher startup complete
2019/02/13 20:55:04 [INFO] Starting cluster agent for c-pp6qh [owner=true]
I0213 20:55:04.120836       8 http.go:110] HTTP2 has been explicitly disabled
2019/02/13 20:55:04 [INFO] Registering project network policy
2019/02/13 20:55:04 [INFO] registering podsecuritypolicy cluster handler for cluster c-8rtzh
2019/02/13 20:55:04 [INFO] registering podsecuritypolicy project handler for cluster c-8rtzh
2019/02/13 20:55:04 [INFO] registering podsecuritypolicy namespace handler for cluster c-8rtzh
2019/02/13 20:55:04 [INFO] registering podsecuritypolicy serviceaccount handler for cluster c-8rtzh
2019/02/13 20:55:04 [INFO] registering podsecuritypolicy template handler for cluster c-8rtzh
2019/02/13 20:55:04 [ERROR] ProjectController c-pp6qh/p-n95l4 [system-image-upgrade-controller] failed with : get template system-library-rancher-logging failed: catalogTemplate.management.cattle.io "cattle-global-data/system-library-rancher-logging" not found         
2019/02/13 20:55:04 [ERROR] ProjectController c-pp6qh/p-prw8d [system-image-upgrade-controller] failed with : get template system-library-rancher-logging failed: catalogTemplate.management.cattle.io "cattle-global-data/system-library-rancher-logging" not found         
2019/02/13 20:55:04 [INFO] Registering monitoring for cluster "c-8rtzh"
2019/02/13 20:55:04 [INFO] Starting cluster controllers for c-8rtzh
2019/02/13 20:55:05 [INFO] Starting cluster agent for c-8rtzh [owner=true]
2019/02/13 20:55:05 [ERROR] ClusterController c-8rtzh [user-controllers-controller] failed with : failed to start user controllers for cluster c-b7nkf: failed to contact server: Get https://178.128.76.186:6443/version?timeout=30s: waiting for cluster agent to connect  
2019/02/13 20:55:05 [ERROR] ClusterController c-b7nkf [user-controllers-controller] failed with : failed to start user controllers for cluster c-b7nkf: failed to contact server: Get https://178.128.76.186:6443/version?timeout=30s: waiting for cluster agent to connect  
2019/02/13 20:55:05 [ERROR] ClusterController c-pp6qh [user-controllers-controller] failed with : failed to start user controllers for cluster c-b7nkf: failed to contact server: Get https://178.128.76.186:6443/version?timeout=30s: waiting for cluster agent to connect  
2019/02/13 20:55:05 [ERROR] ClusterController c-6zjvd [user-controllers-controller] failed with : failed to start user controllers for cluster c-b7nkf: failed to contact server: Get https://178.128.76.186:6443/version?timeout=30s: waiting for cluster agent to connect  
2019/02/13 20:55:05 [ERROR] ClusterController c-8rtzh [user-controllers-controller] failed with : failed to start user controllers for cluster c-b7nkf: failed to contact server: Get https://178.128.76.186:6443/version?timeout=30s: waiting for cluster agent to connect  
2019/02/13 20:55:05 [ERROR] ClusterController c-b7nkf [user-controllers-controller] failed with : failed to start user controllers for cluster c-b7nkf: failed to contact server: Get https://178.128.76.186:6443/version?timeout=30s: waiting for cluster agent to connect  
2019/02/13 20:55:06 [ERROR] ClusterController c-pp6qh [user-controllers-controller] failed with : failed to start user controllers for cluster c-b7nkf: failed to contact server: Get https://178.128.76.186:6443/version?timeout=30s: waiting for cluster agent to connect  
2019/02/13 20:55:06 [ERROR] ClusterController c-6zjvd [user-controllers-controller] failed with : failed to start user controllers for cluster c-b7nkf: failed to contact server: Get https://178.128.76.186:6443/version?timeout=30s: waiting for cluster agent to connect  
2019/02/13 20:55:06 [INFO] Handling backend connection request [c-b7nkf:m-dt58t]
2019/02/13 20:55:06 [INFO] Handling backend connection request [c-b7nkf]
2019/02/13 20:55:06 [INFO] Handling backend connection request [c-8rtzh:machine-ghk79]
2019/02/13 20:55:06 [INFO] Handling backend connection request [c-8rtzh:machine-bfvrw]
2019/02/13 20:55:06 [INFO] Handling backend connection request [c-8rtzh:machine-srd7b]
2019/02/13 20:55:06 [INFO] Registering project network policy
2019/02/13 20:55:06 [INFO] registering podsecuritypolicy cluster handler for cluster c-b7nkf
2019/02/13 20:55:06 [INFO] registering podsecuritypolicy project handler for cluster c-b7nkf
2019/02/13 20:55:06 [INFO] registering podsecuritypolicy namespace handler for cluster c-b7nkf
2019/02/13 20:55:06 [INFO] registering podsecuritypolicy serviceaccount handler for cluster c-b7nkf
2019/02/13 20:55:06 [INFO] registering podsecuritypolicy template handler for cluster c-b7nkf
2019/02/13 20:55:06 [INFO] Registering monitoring for cluster "c-b7nkf"
2019/02/13 20:55:06 [INFO] Starting cluster controllers for c-b7nkf
2019-02-13 20:55:07.083507 I | http: TLS handshake error from 127.0.0.1:43026: EOF
2019-02-13 20:55:07.282310 I | http: TLS handshake error from 127.0.0.1:43094: EOF
2019/02/13 20:55:07 [INFO] Starting cluster agent for c-b7nkf [owner=true]
2019/02/13 20:55:08 [INFO] kontainerdriver googlekubernetesengine listening on address 127.0.0.1:10531
2019/02/13 20:55:08 [INFO] kontainerdriver azurekubernetesservice listening on address 127.0.0.1:10191
2019/02/13 20:55:08 [INFO] kontainerdriver googlekubernetesengine listening on address 127.0.0.1:10641
2019/02/13 20:55:08 [WARNING] could not convert <nil> tags=<nil>
2019/02/13 20:55:08 [INFO] kontainerdriver azurekubernetesservice stopped
2019/02/13 20:55:08 [WARNING] could not convert <nil> labels=<nil>
2019/02/13 20:55:08 [WARNING] could not convert <nil> resourceLabels=<nil>
2019/02/13 20:55:08 [WARNING] could not convert <nil> taints=<nil>
2019/02/13 20:55:08 [INFO] kontainerdriver googlekubernetesengine stopped
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe0 pc=0x29f2f45]

goroutine 19344 [running]:
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/gke.(*Driver).Remove(0xc001389c20, 0x4144880, 0xc0105f9f20, 0xc018ae0d00, 0x373fb40, 0x38ee000)                                                                                                
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/gke/gke_driver.go:820 +0x3b5
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types.(*GrpcServer).Remove(0xc010402840, 0x4144880, 0xc0105f9e30, 0xc018ae0d00, 0xc010402840, 0x454c9cc4cdbb87f7, 0xc01712cae8)                                                                        
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/rpc_server.go:85 +0x6d
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types._Driver_Remove_Handler(0x38ee000, 0xc010402840, 0x4144880, 0xc0105f9e30, 0xc0087a1110, 0x0, 0x0, 0x0, 0xc00fb26780, 0x3a4e575)                                                                   
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/drivers.pb.go:1421 +0x23e
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0125f4b00, 0x415cd20, 0xc0155d0a80, 0xc00ae27680, 0xc0105f8ae0, 0x69e28a8, 0x0, 0x0, 0x0)                                                                                              
        /go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:921 +0x7d1
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0125f4b00, 0x415cd20, 0xc0155d0a80, 0xc00ae27680, 0x0)                                                                                                                                    
        /go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:1143 +0x1308
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc01662ee10, 0xc0125f4b00, 0x415cd20, 0xc0155d0a80, 0xc00ae27680)                                                                                                                   
        /go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:638 +0x9f
created by github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:636 +0xa1
```

**Other details that may be helpful:**
Possibly environmental or requires unique situation. I had several clusters and the only issue I saw was that I could not remove a GKE cluster if in error state. I tried to delete it several times via UI to no effect and eventually it went to unavailable and rancher no longer responded via HTTP. Rancher keeps restarting based on my docker command so is failing constantly. I kept the state.

**Comment by jiaqiluo** [comment]
I met the same bug on my setup: Rancher: master 2/13, single install
Steps:
- add a GKE clsuter with some invalid/wrong setting values.

Result:
- the GKE cluster was falied to provision, after a while I was kicked out from the Rancher UI and cannot log in anymore. 

Rancher's docker log
```
2019/02/13 16:47:16 [INFO] Creating CRD podsecuritypolicytemplates.management.cattle.io
2019/02/13 16:47:17 [INFO] Creating CRD preferences.management.cattle.io
2019/02/13 16:47:17 [INFO] Creating CRD projectalerts.management.cattle.io
2019/02/13 16:47:17 [INFO] Creating CRD projectalertgroups.management.cattle.io
                                                                                                                                                                                  1,1           Top
I0213 21:17:02.198755       7 controllermanager.go:455] Started "garbagecollector"
I0213 21:17:02.198876       7 service_controller.go:175] Starting service controller
I0213 21:17:02.198893       7 controller_utils.go:1027] Waiting for caches to sync for service controller
I0213 21:17:02.199039       7 attach_detach_controller.go:309] Starting attach detach controller
I0213 21:17:02.199051       7 controller_utils.go:1027] Waiting for caches to sync for attach detach controller
I0213 21:17:02.199216       7 clusterroleaggregation_controller.go:148] Starting ClusterRoleAggregator
I0213 21:17:02.199227       7 controller_utils.go:1027] Waiting for caches to sync for ClusterRoleAggregator controller
I0213 21:17:02.199230       7 controllermanager.go:455] Started "daemonset"
I0213 21:17:02.199404       7 pv_protection_controller.go:81] Starting PV protection controller
I0213 21:17:02.199415       7 controller_utils.go:1027] Waiting for caches to sync for PV protection controller
I0213 21:17:02.199436       7 node_ipam_controller.go:95] Sending events to api server.
I0213 21:17:02.199522       7 garbagecollector.go:133] Starting garbage collector controller
I0213 21:17:02.199536       7 controller_utils.go:1027] Waiting for caches to sync for garbage collector controller
I0213 21:17:02.199552       7 daemon_controller.go:270] Starting daemon sets controller
I0213 21:17:02.199560       7 controller_utils.go:1027] Waiting for caches to sync for daemon sets controller
I0213 21:17:02.199574       7 graph_builder.go:308] GraphBuilder running
I0213 21:17:02.285878       7 controller_utils.go:1034] Caches are synced for tokens controller
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe0 pc=0x29f3065]

goroutine 14205 [running]:
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/gke.(*Driver).Remove(0xc001454870, 0x41448c0, 0xc011f00870, 0xc00b6b4dd0, 0x373fb40, 0x38ee000)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/gke/gke_driver.go:820 +0x3b5
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types.(*GrpcServer).Remove(0xc00745f1a0, 0x41448c0, 0xc0085e1320, 0xc00b6b4dd0, 0xc00745f1a0, 0xc00ba17840, 0xc0114b7ae8)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/rpc_server.go:85 +0x6d
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types._Driver_Remove_Handler(0x38ee000, 0xc00745f1a0, 0x41448c0, 0xc0085e1320, 0xc0066c61c0, 0x0, 0x0, 0x0, 0xc0116b8600, 0x9585f6)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/drivers.pb.go:1421 +0x23e
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc00b4e4000, 0x415cd60, 0xc014c7d800, 0xc00b670640, 0xc011f006f0, 0x69e28a8, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:921 +0x7d1
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).handleStream(0xc00b4e4000, 0x415cd60, 0xc014c7d800, 0xc00b670640, 0x0)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:1143 +0x1308
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc012d2fda0, 0xc00b4e4000, 0x415cd60, 0xc014c7d800, 0xc00b670640)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:638 +0x9f
created by github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:636 +0xa1
```

**Comment by jiaqiluo** [comment]
In my recent try with Rancher: master 2/14

I cannot remove a failed GKE cluster form Rancher UI. the cluster is stick on the removing state.

<img width="1410" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/52818733-c74bb080-3064-11e9-8533-a17f8b3b9618.png">

also, in Google UI it shows the cluster faield to run up.
￼
<img width="940" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/52818805-ef3b1400-3064-11e9-8732-5d5410a38bab.png">

Rancher will crash if I delete the cluster from Google UI

**Comment by davidnuzik** [comment]
Having a hard time reproducing with 2/14/19 master imageID: 1d8e92cc20ad 3 hours old

**Comment by cjellick** [comment]
@jianghang8421 can you supply the git commit has of the rancher server build? it is logged near the first line of the container logs

**Comment by davidnuzik** [comment]
Closing issue; neither @jiaqiluo or myself can reproduce this anymore when using latest master 1d8e92cc20ad 2/14
