### ISSUE TITLE
gdapi.ApiError creating a "custom host" 

### ISSUE THREAD

**Issue by michaelbironneau** [rancher/rancher#1808]
I've been following the [Quickstart guide](http://docs.rancher.com/rancher/quick-start-guide/) and have run into an issue adding the same host running the Rancher server as a host. The Rancher version is v0.32.0.

The Rancher server is running at http://192.168.31.62:8080 and the UI works fine.

The command I ran to create/register the agent was `sudo docker run -e CATTLE_AGENT_IP=192.168.31.62 -d --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.7.11 http://192.168.31.62:8080/v1/scripts/E0B8CDED0BC26F86EC6A:1439805600000:WlfUnOtpUI7nE7dk22z9AT11SI`

which fails with the output

```
...
INFO: Attempting to connect to: http://192.168.31.62:8080/v1
INFO: http://192.168.31.62:8080/v1 is accessible
INFO: Inspecting host capabilities
INFO: System: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
Traceback (most recent call last):
  File "./register.py", line 11, in <module>
    secret_key=os.environ['CATTLE_REGISTRATION_SECRET_KEY'])
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 37, in from_env
    return gdapi.from_env(prefix=prefix, factory=Client, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 608, in from_env
    return _from_env(prefix=prefix, factory=factory, **args)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 627, in _from_env
    return factory(**result)
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 12, in __init__
    super(Client, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 195, in __init__
    self._load_schemas()
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 313, in _load_schemas
    response = self._get_response(self._url)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 264, in _get_response
    self._error(r.text)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 253, in _error
    raise ApiError(self._unmarshall(text))
gdapi.ApiError: (ApiError(...), 'API Error')
```

When I look at the Rancher server logs, they are full of 
```
time="2015-08-17T11:04:58Z" level=info msg="Starting go-machine-service..." gitcommit=102d311 
time="2015-08-17T11:04:58Z" level=error msg="Unable to create EventRouter" Err="Bad response from [http://192.168.31.62/v1], statusCode [404]. Status [404 Not Found]. Body: []" 
time="2015-08-17T11:04:58Z" level=info msg="Exiting go-machine-service..." 
time="2015-08-17T11:05:00Z" level=info msg="Setting log level" logLevel=info 
time="2015-08-17T11:05:00Z" level=info msg="Starting go-machine-service..." gitcommit=102d311 
time="2015-08-17T11:05:00Z" level=error msg="Unable to create EventRouter" Err="Bad response from [http://192.168.31.62/v1], statusCode [404]. Status [404 Not Found]. Body: []" 
time="2015-08-17T11:05:00Z" level=info msg="Exiting go-machine-service..." 
```

Any idea what the problem might be?

Thanks

**Comment by deniseschannon** [comment]
Any chance you've had containers that were started when you had Docker 1.5 on your machine? If so, you'll need to remove them for Rancher server to work. There is a little more detail here: 

https://github.com/rancher/rancher/issues/1147

**Comment by michaelbironneau** [comment]
You're right, that fixed the issue, thanks.
