### ISSUE TITLE
Panic when adding targets to multi cluster app

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#18136]
rancher/master: 2/14 HA 

Created multi cluster app with one target. Came to active. 
Upgraded to add 2 more targets, got `addProject` error in UI, seeing this panic in logs, 

```
2019/02/14 23:24:32 [ERROR] Panic serving api request: 
goroutine 28763 [running]:
runtime/debug.Stack(0xc0073ca8f0, 0x33aba40, 0x69d8ec0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP.func1(0x41460a0, 0xc001229c00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:175 +0x67
panic(0x33aba40, 0x69d8ec0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/rancher/rancher/pkg/api/customization/globalnamespaceaccess.(*MemberAccess).EnsureRoleInTargets(0xc0073cb208, 0xc00a377580, 0x2, 0x4, 0xc004b78680, 0x2, 0x4, 0xc00339f720, 0xa, 0x0, ...)
	/go/src/github.com/rancher/rancher/pkg/api/customization/globalnamespaceaccess/access_common.go:50 +0x229
github.com/rancher/rancher/pkg/api/customization/multiclusterapp.Wrapper.modifyProjects(0x418a480, 0xc000c54450, 0x41159a0, 0xc000fda558, 0x41159e0, 0xc000fda570, 0x4115e60, 0xc000fda578, 0x4115620, 0xc000fda580, ...)
	/go/src/github.com/rancher/rancher/pkg/api/customization/multiclusterapp/multi_cluster_app.go:169 +0xb3e
github.com/rancher/rancher/pkg/api/customization/multiclusterapp.Wrapper.addProjects(0x418a480, 0xc000c54450, 0x41159a0, 0xc000fda558, 0x41159e0, 0xc000fda570, 0x4115e60, 0xc000fda578, 0x4115620, 0xc000fda580, ...)
	/go/src/github.com/rancher/rancher/pkg/api/customization/multiclusterapp/multi_cluster_app.go:82 +0x7a
github.com/rancher/rancher/pkg/api/customization/multiclusterapp.Wrapper.ActionHandler(0x418a480, 0xc000c54450, 0x41159a0, 0xc000fda558, 0x41159e0, 0xc000fda570, 0x4115e60, 0xc000fda578, 0x4115620, 0xc000fda580, ...)
	/go/src/github.com/rancher/rancher/pkg/api/customization/multiclusterapp/multi_cluster_app.go:73 +0x273
github.com/rancher/rancher/pkg/api/customization/multiclusterapp.Wrapper.ActionHandler-fm(0xc0083e0e1e, 0xb, 0xc009b88540, 0xc00617b200, 0xc00a4cf155, 0x1c)
	/go/src/github.com/rancher/rancher/pkg/api/server/managementstored/setup.go:629 +0x88
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.handleAction(0xc009b88540, 0xc00617b200, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:263 +0x62
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).handle(0xc000918370, 0x41460a0, 0xc001229c00, 0xc00459c100, 0xc008a25b80, 0xc000e3d4d0, 0xc0073cb738)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:251 +0xd2
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP(0xc000918370, 0x41460a0, 0xc001229c00, 0xc00459c100)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:180 +0x7d
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0006bd0a0, 0x41460a0, 0xc001229c00, 0xc00459c100)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:159 +0xf1
github.com/rancher/rancher/pkg/auth/requests.authHeaderHandler.ServeHTTP(0x41104a0, 0xc0012fb620, 0x4105ca0, 0xc0006bd0a0, 0x4124120, 0xc000e4a800, 0x4110460, 0xc000e3db90, 0x41460a0, 0xc001229c00, ...)
	/go/src/github.com/rancher/rancher/pkg/auth/requests/filter.go:110 +0x60d
github.com/rancher/rancher/pkg/audit.auditHandler.ServeHTTP(0x41045e0, 0xc00102b0c0, 0x0, 0x41460a0, 0xc001229c00, 0xc00a1a5f00)
	/go/src/github.com/rancher/rancher/pkg/audit/filter.go:28 +0x46a
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0006bd030, 0x41460a0, 0xc001229c00, 0xc00a1a5f00)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:159 +0xf1
github.com/rancher/rancher/pkg/dynamiclistener.httpRedirect.func1(0x41460a0, 0xc001229c00, 0xc00a1a4b00)
	/go/src/github.com/rancher/rancher/pkg/dynamiclistener/server.go:441 +0x278
net/http.HandlerFunc.ServeHTTP(0xc001f2f760, 0x41460a0, 0xc001229c00, 0xc00a1a4b00)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/rancher/rancher/pkg/dynamiclistener.(*Server).cacheIPHandler.func1(0x41460a0, 0xc001229c00, 0xc00a1a4b00)
	/go/src/github.com/rancher/rancher/pkg/dynamiclistener/server.go:384 +0x101
net/http.HandlerFunc.ServeHTTP(0xc001f2f780, 0x41460a0, 0xc001229c00, 0xc00a1a4b00)
	/usr/local/go/src/net/http/server.go:1964 +0x44
net/http.serverHandler.ServeHTTP(0xc00120d450, 0x41460a0, 0xc001229c00, 0xc00a1a4b00)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc009b28960, 0x414f460, 0xc0086f0c00)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5
```

**Comment by mrajashree** [comment]
This got closed due to my PR containing the word "fix"

**Comment by bmdepesa** [comment]
rancher/rancher:master 2/19

Panic no longer occurs when adding targets to multicluster app
