### ISSUE TITLE
Kontainer-Engine - Upgrade rancher-server crash with GKE

### ISSUE THREAD

**Issue by thxCode** [rancher/rancher#18154]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
old server version: 2.1.5
new server version: master

- Start an old version server
- Create a GKE cluster
- Upgrade rancher server to `rancher/rancher:master`

**Result:**
Rancher server will Crash

**Other details that may be helpful:**
Panic log from rancher server
```
2019/02/15 04:20:06 [INFO] kontainerdriver googlekubernetesengine listening on address 127.0.0.1:10386
2019/02/15 04:20:06 [WARNING] could not convert <nil> MasterAuth=<nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x29f1e6b]

goroutine 14289 [running]:
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/gke.(*Driver).Update(0xc0011c7440, 0x414c520, 0xc00c2300f0, 0xc00fcb1c70, 0xc00c7c9d80, 0x38f47e0, 0xc00c7c3100, 0x41853c0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/gke/gke_driver.go:634 +0x2fb
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types.(*GrpcServer).Update(0xc00c3cb9c0, 0x414c520, 0xc00c7dbef0, 0xc00c7dbf80, 0xc00c3cb9c0, 0xc00f27fa80, 0xc00aa44ae8)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/rpc_server.go:52 +0x7c
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types._Driver_Update_Handler(0x38f47e0, 0xc00c3cb9c0, 0x414c520, 0xc00c7dbef0, 0xc00c7c3180, 0x0, 0x0, 0x0, 0xc009d53980, 0x40c50b)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/drivers.pb.go:1385 +0x241
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc00c7cb1e0, 0x4164900, 0xc00c7a0900, 0xc00c8b3b80, 0xc00c7db1a0, 0x69ed8b8, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:921 +0x7d1
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).handleStream(0xc00c7cb1e0, 0x4164900, 0xc00c7a0900, 0xc00c8b3b80, 0x0)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:1143 +0x1308
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00c773680, 0xc00c7cb1e0, 0x4164900, 0xc00c7a0900, 0xc00c8b3b80)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:638 +0x9f
created by github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:636 +0xa1
```

**Support:**
- [x] Need more testings for other kontainer-engine drivers when upgrading from `2.1.x` to `2.2`
   - [x] EKS, no crash but https://github.com/rancher/rancher/issues/18162
   - [x] AKS, no crash but https://github.com/rancher/rancher/issues/18165
   - [ ] ~~Others~~

@sangeethah

**Comment by loganhz** [comment]
@thxCode Please validate it

**Comment by thxCode** [comment]
**Steps:**
old server version: 2.1.5
new server version: master

* Start an old version server
* Create a GKE cluster
* Upgrade rancher server to `rancher/rancher:master`

**Result:**
No crash
