### ISSUE TITLE
"Uncaught exception io.cattle.platform.async.utils.TimeoutException: Object [credential:1] failed to satisfy predicate"  exception seen in logs when LDAP authentication is enabled.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1828]
Rancher server version - V0.33.0-rc3
Server version - V0.33.0-rc3

Following exception seen in logs when LDAP authentication is enabled:

2015-08-19 18:27:52,233 ERROR [:] [] [] [] [cutorService-10] [o.a.c.m.context.NoExceptionRunnable ] Uncaught exception io.cattle.platform.async.utils.TimeoutException: Object [credential:1] failed to satisfy predicate [15000] millis
	at io.cattle.platform.object.monitor.impl.ResourceMonitorImpl.waitFor(ResourceMonitorImpl.java:92) ~[cattle-framework-resource-monitor-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.object.monitor.impl.ResourceMonitorImpl.waitFor(ResourceMonitorImpl.java:97) ~[cattle-framework-resource-monitor-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.object.monitor.impl.ResourceMonitorImpl.waitForState(ResourceMonitorImpl.java:114) ~[cattle-framework-resource-monitor-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.docker.machine.launch.MachineLauncher.getCredential(MachineLauncher.java:100) ~[cattle-docker-machine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.docker.machine.launch.MachineLauncher.doRun(MachineLauncher.java:132) ~[cattle-docker-machine-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]

**Comment by hibooboo2** [comment]
@sangeethah This is not caused by authentication code. This is machine related.

**Comment by will-chan** [comment]
Is this a machine issue?

**Comment by wlan0** [comment]
It doesn't seem like a machine issue. How do I reproduce this issue?

**Comment by sangeethah** [comment]
Enabled LDAP authentication.
logs shows this stack trace.

**Comment by wlan0** [comment]
That workflow doesn't interact with machine. @hibooboo2 Can you explain how this is machine related?

**Comment by cjellick** [comment]
While this error does occur in MachineLauncher (the class that launches go-machine-service), the error is not caused by anything machine related. It is caused by the launcher attempting to get a credential. I would say this is an auth bug, not a machine bug. Hopefully, its been fixed as LDAP has stabilized. Assigning to @hibooboo2. Can you see if you can repro and then assign to @sangeethah to close if you cant?

**Comment by hibooboo2** [comment]
I have fixed this bug in master. With rancher/cattle#1108

**Comment by cjellick** [comment]
K. Assigning to @sangeethah so she can close

**Comment by hibooboo2** [comment]
@cjellick I am not sure If it is that bug for sure or not. It seems like it might be but I think it might not be.

**Comment by sangeethah** [comment]
Tested with rancher server version - V0.61.0-rc3.

Exception mentioned in the bug is not seen any more in logs when LDAP autthetication is enabled.
