### ISSUE TITLE
Rancher Server crashes when two nodes are powered OFF and backup is performed

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#18451]
Rancher version: Master

Steps:
1. Create a 3 node cluster with all roles and local backup configured:
N1, N2, N3:  etcd, worker and control 
2. Create few workloads
3. Power OFF 2 nodes (N2, N3)
4. After power off, perform a local backup

Rancher server crashes with the below error:
```
2019/02/27 19:24:34 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/02/27 19:24:34 [ERROR] EtcdBackupController c-rqbmm/c-rqbmm-xlwpp [etcdbackup-controller] failed with : [etcd-backup] failed to perform etcd backup: Can't remove Docker container [old-etcd-snapshot-once] for host [a.b.c.d]: Error: No such container: old-etcd-snapshot-once
2019/02/27 19:24:38 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:10355
2019/02/27 19:24:38 [INFO] Starting saving snapshot on etcd hosts
2019/02/27 19:24:38 [INFO] [dialer] Setup tunnel for host [a.b.c.d]
2019/02/27 19:24:38 [INFO] [dialer] Setup tunnel for host [d.e.f.g]
2019/02/27 19:24:38 [WARNING] Failed to set up SSH tunneling for host  [d.e.f.g]: Can't establish dialer connection: can not build dialer to c-rqbmm:m-fb767ab755d8
2019/02/27 19:24:38 [INFO] [dialer] Setup tunnel for host [18.188.222.17]
2019/02/27 19:24:38 [WARNING] Failed to set up SSH tunneling for host [z.x.y.z]: Can't establish dialer connection: can not build dialer to c-rqbmm:m-5f2c5fe672d0
2019/02/27 19:24:38 [WARNING] Removing host [d.e.f.g] from node lists
2019/02/27 19:24:38 [WARNING] Removing host [d.e.f.g] from node lists
2019/02/27 19:24:38 [INFO] [etcd] Saving snapshot [c-rqbmm-424tm] on host [z.x.y.z]
2019/02/27 19:24:39 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:10397
2019/02/27 19:24:39 [INFO] Starting saving snapshot on etcd hosts
2019/02/27 19:24:39 [INFO] [dialer] Setup tunnel for host [a.b.c.d]
2019/02/27 19:24:39 [WARNING] Failed to set up SSH tunneling for host [d.e.f.g]: Can't establish dialer connection: can not build dialer to c-rqbmm:m-fb767ab755d8
2019/02/27 19:24:39 [INFO] [dialer] Setup tunnel for host [a,b.c.d]
2019/02/27 19:24:39 [WARNING] Failed to set up SSH tunneling for host [d.e.f.g]: Can't establish dialer connection: can not build dialer to c-rqbmm:m-5f2c5fe672d0
2019/02/27 19:24:39 [INFO] [dialer] Setup tunnel for host [a.b.c.d]
2019/02/27 19:24:39 [WARNING] Removing host [a.b.c.d] from node lists
2019/02/27 19:24:39 [WARNING] Removing host [d.e.f.g] from node lists
2019/02/27 19:24:39 [INFO] [etcd] Saving snapshot [c-rqbmm-xlwpp] on host [a.b.c.d]
panic: runtime error: index out of range

goroutine 102368 [running]:
github.com/rancher/rancher/vendor/github.com/rancher/rke/docker.IsContainerRunning(0x416ad40, 0xc002413f50, 0xc011488e00, 0xc013826410, 0xd, 0xc014ccb820, 0x16, 0xc014ccb801, 0xc005a5f810, 0x0, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/docker/docker.go:173 +0x5a6
github.com/rancher/rancher/vendor/github.com/rancher/rke/docker.StopRenameContainer(0x416ad40, 0xc002413f50, 0xc011488e00, 0xc013826410, 0xd, 0x3a7c920, 0x12, 0xc014ccb820, 0x16, 0xc0023b7f80, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/docker/docker.go:324 +0x9c
github.com/rancher/rancher/vendor/github.com/rancher/rke/docker.DoRollingUpdateContainer(0x416ad40, 0xc002413f50, 0xc011488e00, 0xc022b8f400, 0xc0224ea000, 0x3a7c920, 0x12, 0xc013826410, 0xd, 0x3a5a69c, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/docker/docker.go:122 +0x3bf
github.com/rancher/rancher/vendor/github.com/rancher/rke/docker.DoRunContainer(0x416ad40, 0xc002413f50, 0xc011488e00, 0xc022b8f400, 0xc0224ea000, 0x3a7c920, 0x12, 0xc013826410, 0xd, 0x3a5a69c, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/docker/docker.go:89 +0x3df
github.com/rancher/rancher/vendor/github.com/rancher/rke/services.RunEtcdSnapshotSave(0x416ad40, 0xc002413f50, 0xc0188f5080, 0xc0023b7f80, 0xc01309bb00, 0x19, 0xc013826110, 0xd, 0xc00b039601, 0xc01309baa0, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/services/etcd.go:308 +0x7b1
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.(*Cluster).SnapshotEtcd(0xc007ff0900, 0x416ad40, 0xc002413f50, 0xc013826110, 0xd, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/etcd.go:20 +0x179
github.com/rancher/rancher/vendor/github.com/rancher/rke/cmd.SnapshotSaveEtcdHosts(0x416ad40, 0xc002413f50, 0xc0197b6c00, 0xc003f381a0, 0xc003f381b0, 0xc00e41e440, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cmd/etcd.go:98 +0x1fd
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/rke.(*Driver).ETCDSave(0xc00090a500, 0x416ad40, 0xc002413f50, 0xc017c5bc70, 0xc018adefc0, 0xc013826110, 0xd, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/rke/rke_driver.go:498 +0x33f
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types.(*GrpcServer).ETCDSave(0xc00fdf9e00, 0x416ad40, 0xc002413f50, 0xc018adef80, 0xc00fdf9e00, 0x0, 0xc013e9aae8)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/rpc_server.go:76 +0x76
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types._Driver_ETCDSave_Handler(0x390b0c0, 0xc00fdf9e00, 0x416ad40, 0xc002413f50, 0xc016b8b3b0, 0x0, 0x0, 0x0, 0xc0085de900, 0x300000002)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/drivers.pb.go:1565 +0x23e
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc01d58da20, 0x41831a0, 0xc011214c00, 0xc01b5dfe00, 0xc003698540, 0x6a189c8, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:921 +0x7d1
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).handleStream(0xc01d58da20, 0x41831a0, 0xc011214c00, 0xc01b5dfe00, 0x0)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:1143 +0x1308
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc013874890, 0xc01d58da20, 0x41831a0, 0xc011214c00, 0xc01b5dfe00)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:638 +0x9f
created by github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:636 +0xa1






```

**Comment by soumyalj** [comment]
Tested with master build from Feb 28.

* Create a 3 node cluster with all roles and local backup configured:
  N1, N2, N3:  etcd, worker and control
* Create few workloads
* Power OFF 2 nodes (N2, N3)
* After power off, perform a local backup

There was no panic /server crash after backup operation.
