### ISSUE TITLE
Rancher server crashes when backup to S3 fails

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#18452]
Rancher version: Master

Steps:

1. Create a single node cluster with all roles and S3 backup configured. Provide invalid S3 credentials
2. Create few workloads
3. Perform a backup
The backup listed in the backup tab shows "Activating" and the rancher server crashes

Rancher server logs below:
```

2019/02/27 20:57:07 [ERROR] EtcdBackupController c-vnrxn/c-vnrxn-bs9bg [etcdbackup-controller] failed with : [etcd-backup] failed to perform etcd backup: Error waiting for container [etcd-snapshot-once] on host [a.b.c.d]: Error response from daemon: No such container: etcd-snapshot-once
2019/02/27 20:57:12 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:10233
2019/02/27 20:57:12 [INFO] Starting saving snapshot on etcd hosts
2019/02/27 20:57:12 [INFO] [dialer] Setup tunnel for host [a.b.c.d]
2019/02/27 20:57:12 [INFO] [etcd] Saving snapshot [c-vnrxn-qd46x] on host [a.b.c.d]
2019/02/27 20:57:12 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:10750
2019/02/27 20:57:12 [INFO] Starting saving snapshot on etcd hosts
2019/02/27 20:57:12 [INFO] [dialer] Setup tunnel for host [a.b.c.d]
2019/02/27 20:57:12 [INFO] [etcd] Saving snapshot [c-vnrxn-bs9bg] on host  [a.b.c.d]
2019/02/27 20:57:16 [INFO] [etcd] Successfully started [etcd-snapshot-once] container on host  [a.b.c.d]
2019/02/27 20:57:21 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/02/27 20:57:21 [ERROR] EtcdBackupController c-vnrxn/c-vnrxn-qd46x [etcdbackup-controller] failed with : [etcd-backup] failed to perform etcd backup: Failed to take one-time snapshot, exit code [1]: time="2019-02-27T20:57:20Z" level=fatal msg="faield to set s3 server: failed to check s3 bucket:soumyabkptestbucket2, err:The request signature we calculated does not match the signature you provided. Check your key and signing method." 
2019/02/27 20:57:21 [INFO] [etcd] Successfully updated [etcd-snapshot-once] container on host [a.b.c.d]
2019/02/27 20:57:21 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/02/27 20:57:21 [ERROR] EtcdBackupController c-vnrxn/c-vnrxn-bs9bg [etcdbackup-controller] failed with : [etcd-backup] failed to perform etcd backup: Can't remove Docker container [old-etcd-snapshot-once] for host [a.b.c.d]: Error: No such container: old-etcd-snapshot-once
2019/02/27 20:57:26 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:10798
2019/02/27 20:57:26 [INFO] Starting saving snapshot on etcd hosts
2019/02/27 20:57:26 [INFO] [dialer] Setup tunnel for host [a.b.c.d]
2019/02/27 20:57:26 [INFO] [etcd] Saving snapshot [c-vnrxn-qd46x] on host [a.b.c.d]
2019/02/27 20:57:26 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:10642
2019/02/27 20:57:26 [INFO] Starting saving snapshot on etcd hosts
2019/02/27 20:57:26 [INFO] [dialer] Setup tunnel for host [a.b.c.d]
2019/02/27 20:57:26 [INFO] [etcd] Saving snapshot [c-vnrxn-bs9bg] on host [a.b.c.d]
panic: runtime error: index out of range

goroutine 134643 [running]:
github.com/rancher/rancher/vendor/github.com/rancher/rke/docker.IsContainerRunning(0x416ad40, 0xc00fe3bb60, 0xc00dedfb80, 0xc011b3dcc0, 0xd, 0xc0107fe2a0, 0x16, 0xc0107fe201, 0xc00f16b810, 0x0, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/docker/docker.go:173 +0x5a6
github.com/rancher/rancher/vendor/github.com/rancher/rke/docker.StopRenameContainer(0x416ad40, 0xc00fe3bb60, 0xc00dedfb80, 0xc011b3dcc0, 0xd, 0x3a7c920, 0x12, 0xc0107fe2a0, 0x16, 0xc00fd48330, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/docker/docker.go:324 +0x9c
github.com/rancher/rancher/vendor/github.com/rancher/rke/docker.DoRollingUpdateContainer(0x416ad40, 0xc00fe3bb60, 0xc00dedfb80, 0xc00ea0c500, 0xc009947c00, 0x3a7c920, 0x12, 0xc011b3dcc0, 0xd, 0x3a5a69c, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/docker/docker.go:122 +0x3bf
github.com/rancher/rancher/vendor/github.com/rancher/rke/docker.DoRunContainer(0x416ad40, 0xc00fe3bb60, 0xc00dedfb80, 0xc00ea0c500, 0xc009947c00, 0x3a7c920, 0x12, 0xc011b3dcc0, 0xd, 0x3a5a69c, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/docker/docker.go:89 +0x3df
github.com/rancher/rancher/vendor/github.com/rancher/rke/services.RunEtcdSnapshotSave(0x416ad40, 0xc00fe3bb60, 0xc00ad64c00, 0xc00fd48330, 0xc01335e5a0, 0x19, 0xc011b3dc40, 0xd, 0x32fb501, 0xc01335e540, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/services/etcd.go:308 +0x7b1
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.(*Cluster).SnapshotEtcd(0xc0095c4000, 0x416ad40, 0xc00fe3bb60, 0xc011b3dc40, 0xd, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/etcd.go:20 +0x179
github.com/rancher/rancher/vendor/github.com/rancher/rke/cmd.SnapshotSaveEtcdHosts(0x416ad40, 0xc00fe3bb60, 0xc013eecc00, 0xc00583c000, 0xc00583c010, 0xc00fc906c0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cmd/etcd.go:98 +0x1fd
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/rke.(*Driver).ETCDSave(0xc000160000, 0x416ad40, 0xc00fe3bb60, 0xc01b17f110, 0xc00e38f5c0, 0xc011b3dc40, 0xd, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/rke/rke_driver.go:498 +0x33f
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types.(*GrpcServer).ETCDSave(0xc01054d780, 0x416ad40, 0xc00fe3bb60, 0xc00e38f580, 0xc01054d780, 0xc0100b8140, 0xc004f16ae8)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/rpc_server.go:76 +0x76
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types._Driver_ETCDSave_Handler(0x390b0c0, 0xc01054d780, 0x416ad40, 0xc00fe3bb60, 0xc00185d3b0, 0x0, 0x0, 0x0, 0xc01532d110, 0x40c50b)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/drivers.pb.go:1565 +0x23e
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc011070c60, 0x41831a0, 0xc01b0df200, 0xc00c827cc0, 0xc00fe67560, 0x6a189c8, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:921 +0x7d1
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).handleStream(0xc011070c60, 0x41831a0, 0xc01b0df200, 0xc00c827cc0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:1143 +0x1308
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc011b3d850, 0xc011070c60, 0x41831a0, 0xc01b0df200, 0xc00c827cc0)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:638 +0x9f
created by github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:636 +0xa1

```
Expected:
User should be provided relevant error message since invalid credentials are provided and backup to S3 fails

**Comment by moelsayed** [comment]
fixed in https://github.com/rancher/rke/pull/1161

**Comment by soumyalj** [comment]
Tested with master build from Feb 28th. 
* Create a single node cluster with all roles and S3 backup configured. Provide invalid S3 credentials
* Create few workloads
* Perform a backup
  Rancher server crash is fixed. There is no panic. 
The issue of "activating" state for backup is tracked below:
https://github.com/rancher/rancher/issues/18465
