### ISSUE TITLE
Container stuck in Stopping(Draining...) on upgrade

### ISSUE THREAD

**Issue by Chris7** [rancher/rancher#18587]
**What kind of request is this (question/bug/enhancement/feature request):**
Question/Bug

**Steps to reproduce (least amount of steps as possible):**
1) Upgrade a service without drain_timeout (may not be crucial that it previously does not have it) via rancher-cli
2) New containers start, pass healthchecks, accept traffic
3) Old containers stay in `Stopping` state (even if said containers are actually deleted -- I did a docker restart eventually on the host after-which the container were deleted)

**Result:**
Container stuck in stopping state

**Other details that may be helpful:**
No messages in docker daemon logs

Logs in load-balancer:
```
INFO[34255] Received target.drain IP: 10.42.128.28, drainTimeout: 600000, eventID: cb08d755-fa87-4217-82e7-1926b2586a3f, resourceID 1i2295016 
INFO[34255] Received target.drain IP: 10.42.178.183, drainTimeout: 600000, eventID: e582f56e-74f4-4330-878e-13c8298e1ddc, resourceID 1i2294990 
INFO[34270] Received target.drain IP: 10.42.174.142, drainTimeout: 600000, eventID: 97e0838c-67b9-4720-914b-85c117317150, resourceID 1i2295015 
INFO[34270] Received target.drain IP: 10.42.105.84, drainTimeout: 600000, eventID: 6c88d867-b7aa-4e89-91c8-183f035a95a1, resourceID 1i2293146 
Mar  5 14:21:05 localhost haproxy[58094]: 10.26.65.89:52044 [05/Mar/2019:14:20:10.121] 80 80/<NOSRV> -1/-1/-1/-1/55154 400 188 - - CR-- 2/2/0/0/0 0/0 "<BADREQ>"
Mar  5 14:21:05 localhost haproxy[58094]: 10.26.65.89:52044 [05/Mar/2019:14:20:10.121] 80 80/<NOSRV> -1/-1/-1/-1/55154 400 188 - - CR-- 2/2/0/0/0 0/0 "<BADREQ>"
INFO[34319] [Endpoint IP: 10.42.85.224, name: e23e0c7c1390bbef5805b2ccae08f35e090ebcfc] Result: DrainTimeout hit 
INFO[34319] Removed Endpoint %v From Drain&{e23e0c7c1390bbef5805b2ccae08f35e090ebcfc 10.42.85.224 0  false 120000 0} 
INFO[34319] New reply: &client.Publish{Resource:client.Resource{Id:"", Type:"", Links:map[string]string(nil), Actions:map[string]string(nil)}, Data:map[string]interface {}(nil), Name:"reply.5402356524834032592", PreviousIds:[]string{"7f34087f-528f-4c3e-945a-a392d248cbd0"}, Publisher:"", ResourceId:"1i2292810", ResourceType:"instance", Time:0, Transitioning:"", TransitioningInternalMessage:"", TransitioningMessage:"", TransitioningProgress:0} created to the event: &events.Event{Name:"target.drain", ID:"7f34087f-528f-4c3e-945a-a392d248cbd0", PreviousIds:"", PreviousNames:"", Publisher:"", ReplyTo:"reply.5402356524834032592", ResourceID:"1i2292810", ResourceType:"instance", Transitioning:"", TransitioningInternalMessage:"", TransitioningMessage:"", TransitioningProgress:"", Data:map[string]interface {}{"drainTimeout":"120000", "targetIPaddress":"10.42.85.224"}, Time:1.551795575834e+12} 
INFO[34321] New reply: &client.Publish{Resource:client.Resource{Id:"", Type:"", Links:map[string]string(nil), Actions:map[string]string(nil)}, Data:map[string]interface {}(nil), Name:"reply.5402356524834032592", PreviousIds:[]string{"7f34087f-528f-4c3e-945a-a392d248cbd0"}, Publisher:"", ResourceId:"1i2292810", ResourceType:"instance", Time:0, Transitioning:"", TransitioningInternalMessage:"", TransitioningMessage:"", TransitioningProgress:0} created to the event: &events.Event{Name:"target.drain", ID:"7f34087f-528f-4c3e-945a-a392d248cbd0", PreviousIds:"", PreviousNames:"", Publisher:"", ReplyTo:"reply.5402356524834032592", ResourceID:"1i2292810", ResourceType:"instance", Transitioning:"", TransitioningInternalMessage:"", TransitioningMessage:"", TransitioningProgress:"", Data:map[string]interface {}{"drainTimeout":"120000", "targetIPaddress":"10.42.85.224"}, Time:1.551795575834e+12} 
INFO[34364] Received target.drain IP: 10.42.85.224, drainTimeout: 120000, eventID: fc653ce4-2fb2-4d37-a65d-e014d12bdef0, resourceID 1i2292810 
INFO[34420] Received target.drain IP: 10.42.128.28, drainTimeout: 600000, eventID: 23f86205-2751-4bdd-9c50-d6a966ef7243, resourceID 1i2295016 
INFO[34423] Received target.drain IP: 10.42.178.183, drainTimeout: 600000, eventID: 2f661725-d077-4c65-8c23-d339a4d62924, resourceID 1i2294990 
INFO[34435] Received target.drain IP: 10.42.105.84, drainTimeout: 600000, eventID: 02be0f85-d774-4093-a6ce-0afc4b2146d9, resourceID 1i2293146 
INFO[34435] Received target.drain IP: 10.42.174.142, drainTimeout: 600000, eventID: 2afd4cae-82d4-45c7-b557-ee2e660eeb13, resourceID 1i2295015 
```

It seems to be continually entering the drain loop, with a timeout being hit, then added back instead of being removed.

Process timeout on stop:
![image](https://user-images.githubusercontent.com/963909/53811208-d072c380-3f26-11e9-92cf-96948e849f2c.png)

Stack Trace:
```
io.cattle.platform.async.utils.TimeoutException: Timeout
	at io.cattle.platform.async.retry.impl.RetryTimeoutServiceImpl.retry(RetryTimeoutServiceImpl.java:41)
	at sun.reflect.GeneratedMethodAccessor563.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Environment information**
- Rancher version 1.6.22
- Installation option (single install/HA): HA

- Docker version (use `docker version`): 17.09.0-ce

**Comment by jamieleecho** [comment]
This may be triggered by not having enough `sysctl fs.inotify.max_user_watches` and  `fs.inotify.max_user_instances`. It seems by increasing these numbers the problem goes away but I have not validated this correlation. Is this a plausible hypothesis?

**Comment by deniseschannon** [comment]
As 1.6 is EOL as of June 30, 2020, we are closing 1.6 issues.
