### ISSUE TITLE
Upgrade - panic - runtime error seen in the logs after rancher is upgraded to master from v2.0.6

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#18608]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a DO cluster in rancher:v2.0.6 server.  (1 etcd/1control plane/1worker nodes)
2. Upgrade to rancher:master.
3. Scale up the number of control plane nodes.

**Expected Result:**
Control plane should be scaled up successfully in the cluster.

**Actual Result:**
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2c0 pc=0x22d19ff]` seen in the logs.

Cluster is still in `Updating` state.

**Logs:**
```
2019/03/06 00:00:53 [INFO] Provisioning node sowmya-v206-ctrl2
2019/03/06 00:00:53 [INFO] stdout: Creating CA: management-state/node/nodes/sowmya-v206-ctrl2/certs/ca.pem
2019/03/06 00:00:53 [INFO] Creating CA: management-state/node/nodes/sowmya-v206-ctrl2/certs/ca.pem
2019/03/06 00:00:54 [INFO] stdout: Creating client certificate: management-state/node/nodes/sowmya-v206-ctrl2/certs/cert.pem
2019/03/06 00:00:54 [INFO] Creating client certificate: management-state/node/nodes/sowmya-v206-ctrl2/certs/cert.pem
2019/03/06 00:00:54 [INFO] stdout: Running pre-create checks...
2019/03/06 00:00:54 [INFO] Running pre-create checks...
2019/03/06 00:00:55 [INFO] stdout: Creating machine...
2019/03/06 00:00:55 [INFO] Creating machine...
2019/03/06 00:00:55 [INFO] stdout: (sowmya-v206-ctrl2) Creating SSH key...
2019/03/06 00:00:55 [INFO] (sowmya-v206-ctrl2) Creating SSH key...
2019/03/06 00:00:56 [INFO] stdout: (sowmya-v206-ctrl2) Creating Digital Ocean droplet...
2019/03/06 00:00:56 [INFO] (sowmya-v206-ctrl2) Creating Digital Ocean droplet...
2019/03/06 00:01:04 [INFO] stdout: (sowmya-v206-ctrl2) Waiting for IP address to be assigned to the Droplet...
2019/03/06 00:01:04 [INFO] (sowmya-v206-ctrl2) Waiting for IP address to be assigned to the Droplet...
2019/03/06 00:01:05 [INFO] stdout: Waiting for machine to be running, this may take a few minutes...
2019/03/06 00:01:05 [INFO] Waiting for machine to be running, this may take a few minutes...
2019-03-06 00:01:48.701736 W | wal: sync duration of 1.139414456s, expected less than 1s
I0306 00:01:48.921983       5 trace.go:76] Trace[798269108]: "Get /api/v1/namespaces/kube-system/endpoints/kube-scheduler" (started: 2019-03-06 00:01:48.145202996 +0000 UTC m=+460.920981818) (total time: 776.756551ms):
Trace[798269108]: [776.710062ms] [776.63012ms] About to write a response
2019/03/06 00:01:51 [INFO] stdout: Detecting operating system of created instance...
2019/03/06 00:01:51 [INFO] Detecting operating system of created instance...
2019/03/06 00:01:51 [INFO] stdout: Waiting for SSH to be available...
2019/03/06 00:01:51 [INFO] Waiting for SSH to be available...
2019/03/06 00:01:52 [INFO] stdout: Detecting the provisioner...
2019/03/06 00:01:52 [INFO] Detecting the provisioner...
2019/03/06 00:01:53 [INFO] stdout: Provisioning with ubuntu(systemd)...
2019/03/06 00:01:53 [INFO] Provisioning with ubuntu(systemd)...
2019/03/06 00:02:05 [INFO] stdout: Installing Docker...
2019/03/06 00:02:05 [INFO] Installing Docker...
2019-03-06 00:02:07.130346 W | etcdserver: apply entries took too long [962.499873ms for 1 entries]
2019-03-06 00:02:07.130372 W | etcdserver: avoid queries with large range/delete range!
2019/03/06 00:02:22 [INFO] stdout: Copying certs to the local machine directory...
2019/03/06 00:02:22 [INFO] Copying certs to the local machine directory...
2019/03/06 00:02:25 [INFO] stdout: Copying certs to the remote machine...
2019/03/06 00:02:25 [INFO] Copying certs to the remote machine...
2019/03/06 00:02:27 [INFO] stdout: Setting Docker configuration on the remote daemon...
2019/03/06 00:02:27 [INFO] Setting Docker configuration on the remote daemon...
2019/03/06 00:02:30 [INFO] stdout: Checking connection to Docker...
2019/03/06 00:02:30 [INFO] Checking connection to Docker...
2019/03/06 00:02:30 [INFO] stdout: Docker is up and running!
2019/03/06 00:02:30 [INFO] Docker is up and running!
2019/03/06 00:02:43 [INFO] Provisioning node sowmya-v206-ctrl2 done
2019/03/06 00:02:43 [INFO] Generating and uploading node config sowmya-v206-ctrl2
2019/03/06 00:02:43 [INFO] Provisioning cluster [c-rzcsp]
2019/03/06 00:02:43 [INFO] Updating cluster [c-rzcsp]
2019/03/06 00:02:44 [INFO] Handling backend connection request [c-rzcsp:m-mgw42]
2019/03/06 00:02:48 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:10044
2019/03/06 00:02:48 [INFO] cluster [c-rzcsp] provisioning: Initiating Kubernetes cluster
2019/03/06 00:02:48 [INFO] cluster [c-rzcsp] provisioning: [state] Possible legacy cluster detected, trying to upgrade
2019/03/06 00:02:48 [INFO] cluster [c-rzcsp] provisioning: [reconcile] Rebuilding and updating local kube config
2019/03/06 00:02:48 [INFO] cluster [c-rzcsp] provisioning: Successfully Deployed local admin kubeconfig at [management-state/rke/rke-888810430/kube_config_cluster.yml]
2019/03/06 00:02:48 [INFO] cluster [c-rzcsp] provisioning: [reconcile] host [<>] is active master on the cluster
2019/03/06 00:02:48 [INFO] cluster [c-rzcsp] provisioning: [state] Fetching cluster state from Kubernetes
2019/03/06 00:02:48 [INFO] cluster [c-rzcsp] provisioning: [state] Successfully Fetched cluster state to Kubernetes ConfigMap: cluster-state
2019/03/06 00:02:48 [INFO] cluster [c-rzcsp] provisioning: [certificates] Getting Cluster certificates from Kubernetes
2019/03/06 00:02:48 [INFO] cluster [c-rzcsp] provisioning: [certificates] Creating service account token key
2019/03/06 00:02:48 [INFO] cluster [c-rzcsp] provisioning: [certificates] Successfully fetched Cluster certificates from Kubernetes
2019/03/06 00:02:48 [INFO] cluster [c-rzcsp] provisioning: Successfully Deployed state file at [management-state/rke/rke-888810430/cluster.rkestate]
2019/03/06 00:02:48 [INFO] cluster [c-rzcsp] provisioning: [certificates] Generating Kubernetes API server certificates
2019/03/06 00:02:48 [INFO] cluster [c-rzcsp] provisioning: [certificates] Generating admin certificates and kubeconfig
2019/03/06 00:02:48 [INFO] cluster [c-rzcsp] provisioning: [certificates] Generating Kubernetes API server proxy client certificates
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2c0 pc=0x22d19ff]

goroutine 45737 [running]:
github.com/rancher/rancher/vendor/github.com/rancher/rke/pki.newSignedCert(0x3aa4371, 0x1b, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/pki/util.go:423 +0x28f
github.com/rancher/rancher/vendor/github.com/rancher/rke/pki.GenerateSignedCertAndKey(0x0, 0x0, 0x4123401, 0x3aa4371, 0x1b, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/pki/util.go:59 +0x1aa
github.com/rancher/rancher/vendor/github.com/rancher/rke/pki.GenerateAPIProxyClientCertificate(0x417c000, 0xc0133aae40, 0xc010c6c840, 0xc0069ec2c0, 0x3, 0x3, 0xc0075b4ea0, 0x1b, 0xc0133ab170, 0x6a64830, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/pki/services.go:285 +0x196
github.com/rancher/rancher/vendor/github.com/rancher/rke/pki.GenerateRKEServicesCerts(0x417c000, 0xc0133aae40, 0xc010c6c840, 0xc0069ec2c0, 0x3, 0x3, 0xc0075b4ea0, 0x1b, 0xc0133ab170, 0x6a64830, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/pki/services.go:435 +0x1b4
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.RebuildState(0x417c000, 0xc0133aae40, 0xc00f34dc50, 0xc006ced640, 0xc0103ebe60, 0x30, 0x0, 0x0, 0x0, 0xc0103ebc20, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/state.go:179 +0x13f
github.com/rancher/rancher/vendor/github.com/rancher/rke/cmd.ClusterInit(0x417c000, 0xc0133aae40, 0xc00d884c18, 0xc00cd5c6b0, 0xc00cd5c6c0, 0xc006ced5c0, 0xc0103ebe60, 0x30, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cmd/common.go:93 +0x432
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/rke.(*Driver).Update(0xc0008e2ff0, 0x417c000, 0xc0133aae40, 0xc010411ee0, 0xc00d86db00, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/rke/rke_driver.go:191 +0x348
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types.(*GrpcServer).Update(0xc006640040, 0x417c000, 0xc0133aab70, 0xc0133aad50, 0xc006640040, 0xc006a8dbc0, 0xc00ed2cae8)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/rpc_server.go:52 +0x7c
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types._Driver_Update_Handler(0x39113e0, 0xc006640040, 0x417c000, 0xc0133aab70, 0xc00d20e930, 0x0, 0x0, 0x0, 0x200, 0x200)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/drivers.pb.go:1385 +0x241
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc014c1fa20, 0x4194460, 0xc0163c8f00, 0xc00efb3cc0, 0xc01259c0c0, 0x6a2b8d8, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:921 +0x7d1
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).handleStream(0xc014c1fa20, 0x4194460, 0xc0163c8f00, 0xc00efb3cc0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:1143 +0x1308
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00b3e14c0, 0xc014c1fa20, 0x4194460, 0xc0163c8f00, 0xc00efb3cc0)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:638 +0x9f
created by github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:636 +0xa1
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:v2.0.6 to rancher:master
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): DO cluster
- Kubernetes version (use `kubectl version`): 

```
v1.10.5
```

- Docker version (use `docker version`):

```
17.3.2
```

**Comment by sowmyav27** [comment]
verified on rancher:master. Cluster comes to `Active` state after scaling up the number of control plane nodes after rancher upgrade from v2.0.6. Panic is not seen in the rancher logs.
