### ISSUE TITLE
Exception in API for request /v1/configcontent/metadata-answers: IOException: Broken pipe

### ISSUE THREAD

**Issue by viceice** [rancher/rancher#18668]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug. I get the exception every few seconds.

**Steps to reproduce (least amount of steps as possible):**
* single install 1.6.26
* nginx as reverse proxy

**Result:**
Exception in API for request [https://rancher.visualon.de/v1/configcontent/metadata-answers]. Error id: [08724b0c-920a-4e1a-817a-c6d3f54a031b]. java.lang.IllegalStateException: org.eclipse.jetty.io.EofException

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):  1.6.26
- Installation option (single install/HA): single install
- Ubuntu 18.04.2 LTS with local nginx as https reverse proxy

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:53:11 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by ViceIce** [comment]
**log:**
```
2019-03-07 06:02:59,773 ERROR [:] [] [] [] [tp766572210-124] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [https://rancher.visualon.de/v1/configcontent/metadata-answers]. Error id: [ba79ab2b-231c-4ae8-a5ed-cb3f3b942216]. java.lang.IllegalStateException: org.eclipse.jetty.io.EofException
	at io.cattle.platform.util.exception.ExceptionUtils.rethrowExpectedRuntime(ExceptionUtils.java:27)
	at io.cattle.platform.configitem.context.dao.impl.MetaDataInfoDaoImpl.writeToJson(MetaDataInfoDaoImpl.java:414)
	at io.cattle.platform.configitem.context.dao.impl.MetaDataInfoDaoImpl.fetchSelf(MetaDataInfoDaoImpl.java:428)
	at io.cattle.platform.configitem.context.impl.ServiceMetadataInfoFactory.writeCachedGenericData(ServiceMetadataInfoFactory.java:196)
	at io.cattle.platform.configitem.context.impl.ServiceMetadataInfoFactory.writeMetadata(ServiceMetadataInfoFactory.java:120)
	at io.cattle.platform.configitem.server.model.impl.MetadataConfigItem.handleRequest(MetadataConfigItem.java:64)
	at io.cattle.platform.configitem.server.impl.ConfigItemServerImpl.handleDownload(ConfigItemServerImpl.java:97)
	at io.cattle.platform.configitem.server.impl.ConfigItemServerImpl.handleRequest(ConfigItemServerImpl.java:40)
	at io.cattle.platform.configitem.api.manager.ConfigContentManager.handle(ConfigContentManager.java:80)
	at io.cattle.platform.configitem.api.manager.ConfigContentManager.getByIdInternal(ConfigContentManager.java:49)
	at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.getById(AbstractBaseResourceManager.java:61)
	at io.github.ibuildthecloud.gdapi.request.handler.ResourceManagerRequestHandler.generate(ResourceManagerRequestHandler.java:50)
	at io.github.ibuildthecloud.gdapi.request.handler.AbstractResponseGenerator.handle(AbstractResponseGenerator.java:14)
	at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.handle(DefaultReadWriteApiDelegate.java:27)
	at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.read(DefaultReadWriteApiDelegate.java:17)
	at sun.reflect.GeneratedMethodAccessor537.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:280)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy73.read(Unknown Source)
	at io.github.ibuildthecloud.gdapi.request.handler.write.ReadWriteApiHandler.handle(ReadWriteApiHandler.java:21)
	at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:99)
	at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:100)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:110)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:365)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
	Suppressed: org.eclipse.jetty.io.EofException: null
		at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:192)
		at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:408)
		at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:302)
		at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:129)
		at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:729)
		at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:246)
		at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:208)
		at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:481)
		at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:761)
		at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:794)
		at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:155)
		at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:148)
		at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:391)
		at org.eclipse.jetty.servlets.gzip.DeflatedOutputStream.deflate(DeflatedOutputStream.java:74)
		at org.eclipse.jetty.servlets.gzip.DeflatedOutputStream.write(DeflatedOutputStream.java:64)
		at org.eclipse.jetty.servlets.gzip.GzipOutputStream.write(GzipOutputStream.java:46)
		at org.eclipse.jetty.servlets.gzip.AbstractCompressedStream.write(AbstractCompressedStream.java:230)
		at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:253)
		at java.util.zip.DeflaterOutputStream.finish(DeflaterOutputStream.java:226)
		at java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:238)
		at io.cattle.platform.configitem.context.impl.ServiceMetadataInfoFactory.writeCachedGenericData(ServiceMetadataInfoFactory.java:202)
		... 55 common frames omitted
	Caused by: java.io.IOException: Broken pipe
		at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
		at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
		at sun.nio.ch.IOUtil.write(IOUtil.java:148)
		at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504)
		at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:172)
		... 75 common frames omitted
Caused by: org.eclipse.jetty.io.EofException: null
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:192)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:408)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:302)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:129)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:729)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:246)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:208)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:481)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:761)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:794)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:155)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:148)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:386)
	at org.eclipse.jetty.servlets.gzip.DeflatedOutputStream.deflate(DeflatedOutputStream.java:74)
	at org.eclipse.jetty.servlets.gzip.DeflatedOutputStream.write(DeflatedOutputStream.java:64)
	at org.eclipse.jetty.servlets.gzip.GzipOutputStream.write(GzipOutputStream.java:46)
	at org.eclipse.jetty.servlets.gzip.AbstractCompressedStream.write(AbstractCompressedStream.java:230)
	at java.util.zip.DeflaterOutputStream.flush(DeflaterOutputStream.java:277)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.close(UTF8JsonGenerator.java:1085)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3387)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2745)
	at io.cattle.platform.json.JacksonJsonMapper.writeValue(JacksonJsonMapper.java:84)
	at io.cattle.platform.configitem.context.dao.impl.MetaDataInfoDaoImpl.writeToJson(MetaDataInfoDaoImpl.java:412)
	... 57 common frames omitted
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.write(IOUtil.java:148)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:172)
	... 79 common frames omitted
2019-03-07 06:03:04,982 ERROR [:] [] [] [] [tp766572210-135] [i.c.p.c.a.m.ConfigContentManager    ] Failed to download [metadata-answers] for agent [40169] org.eclipse.jetty.io.EofException: null
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:192)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:408)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:302)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:129)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:729)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:246)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:208)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:481)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:761)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:794)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:155)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:148)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:386)
	at org.eclipse.jetty.servlets.gzip.DeflatedOutputStream.deflate(DeflatedOutputStream.java:74)
	at org.eclipse.jetty.servlets.gzip.DeflatedOutputStream.finish(DeflatedOutputStream.java:85)
	at org.eclipse.jetty.servlets.gzip.GzipOutputStream.finish(GzipOutputStream.java:55)
	at org.eclipse.jetty.servlets.gzip.DeflatedOutputStream.close(DeflatedOutputStream.java:95)
	at org.eclipse.jetty.servlets.gzip.AbstractCompressedStream.close(AbstractCompressedStream.java:166)
	at java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:241)
	at io.cattle.platform.configitem.context.impl.ServiceMetadataInfoFactory.writeCachedGenericData(ServiceMetadataInfoFactory.java:202)
	at io.cattle.platform.configitem.context.impl.ServiceMetadataInfoFactory.writeMetadata(ServiceMetadataInfoFactory.java:120)
	at io.cattle.platform.configitem.server.model.impl.MetadataConfigItem.handleRequest(MetadataConfigItem.java:64)
	at io.cattle.platform.configitem.server.impl.ConfigItemServerImpl.handleDownload(ConfigItemServerImpl.java:97)
	at io.cattle.platform.configitem.server.impl.ConfigItemServerImpl.handleRequest(ConfigItemServerImpl.java:40)
	at io.cattle.platform.configitem.api.manager.ConfigContentManager.handle(ConfigContentManager.java:80)
	at io.cattle.platform.configitem.api.manager.ConfigContentManager.getByIdInternal(ConfigContentManager.java:49)
	at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.getById(AbstractBaseResourceManager.java:61)
	at io.github.ibuildthecloud.gdapi.request.handler.ResourceManagerRequestHandler.generate(ResourceManagerRequestHandler.java:50)
	at io.github.ibuildthecloud.gdapi.request.handler.AbstractResponseGenerator.handle(AbstractResponseGenerator.java:14)
	at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.handle(DefaultReadWriteApiDelegate.java:27)
	at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.read(DefaultReadWriteApiDelegate.java:17)
	at sun.reflect.GeneratedMethodAccessor537.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:280)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy73.read(Unknown Source)
	at io.github.ibuildthecloud.gdapi.request.handler.write.ReadWriteApiHandler.handle(ReadWriteApiHandler.java:21)
	at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:99)
	at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:100)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:110)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:365)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.write(IOUtil.java:148)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:172)
	... 74 common frames omitted
```

**Comment by ViceIce** [comment]
# Nginx

**conf.d/vo.conf**
```
map $http_upgrade $connection_upgrade {
    default Upgrade;
    ''      close;
}

upstream rancher {
# mapped to container 8080:8080
  server localhost:8080;
}
```

**sites-enabled/rancher**
```
server {
  listen 80;
  server_name rancher.visualon.de;
  return 301 https://$server_name$request_uri;
}

server {
  listen 443 ssl http2;

  server_name rancher.visualon.de;

  include snippets/vo.conf;

  location / {
    include snippets/vo.proxy.conf;
    proxy_pass http://rancher;
  }
}
```

**snippets/vo.proxy.conf**
```
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header Host $host;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Server $host;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_ssl_server_name on;

proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $connection_upgrade;

proxy_read_timeout 900s;
proxy_request_buffering off;
proxy_buffering off;

client_max_body_size 250M;
```

**snippets/vo.conf**
```
ssl_certificate /etc/nginx/vo.cert.chained.pem;
ssl_certificate_key /etc/nginx/vo.privkey.pem;

set_real_ip_from  172.16.5.2;
#real_ip_header    X-Forwarded-For;
real_ip_recursive on;
```
