### ISSUE TITLE
Global DNS Edit Fails with Empty Response From API

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#18839]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a Global DNS Provider
2. Create a Global DNS Entry that targets a project
3. Edit new Global DNS entry, change fqdn, and save

**Result:**
Expected: Edit succeeds
Actual: A 500 error is returned with an empty response

**Other details that may be helpful:**
The log output indicates a panic 
```
2019/03/12 17:34:49 [ERROR] Panic serving api request:
goroutine 114612 [running]:
runtime/debug.Stack(0xc005838e20, 0x33ccdc0, 0x6a23e70)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP.func1(0x417fbe0, 0xc00fe86b60)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:175 +0x67
panic(0x33ccdc0, 0x6a23e70)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/rancher/rancher/pkg/api/customization/globalnamespaceaccess.(*MemberAccess).IsAdmin(0xc005839438, 0xc00d611960, 0xa, 0x0, 0xc0170f4c68, 0x3be3848)
	/go/src/github.com/rancher/rancher/pkg/api/customization/globalnamespaceaccess/access_common.go:63 +0xcb
github.com/rancher/rancher/pkg/api/customization/globalnamespaceaccess.(*MemberAccess).GetAccessTypeOfCaller(0xc005839438, 0xc00d611960, 0xa, 0xc01207de10, 0xa, 0xc01207de20, 0x8, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rancher/pkg/api/customization/globalnamespaceaccess/access_common.go:383 +0x78
github.com/rancher/rancher/pkg/api/customization/globaldns.Wrapper.Validator(0x414f320, 0xc0045feb48, 0x41c3580, 0xc004c7a9c0, 0x414fa60, 0xc0045feb50, 0x414f5a0, 0xc0045feb58, 0x41c4ca0, 0xc004c7ac30, ...)
	/go/src/github.com/rancher/rancher/pkg/api/customization/globaldns/validator_globaldns.go:83 +0x2b9
github.com/rancher/rancher/pkg/api/customization/globaldns.Wrapper.Validator-fm(0xc015e21440, 0xc0033b63c0, 0xc01590e810, 0x3a6ce01, 0x6)
	/go/src/github.com/rancher/rancher/pkg/api/server/managementstored/setup.go:667 +0x66
github.com/rancher/rancher/vendor/github.com/rancher/norman/parse/builder.(*Builder).Construct(0xc01590e7e0, 0xc0033b63c0, 0xc01590e750, 0x3a6ced9, 0x6, 0x0, 0x3a69a7e, 0x4)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/parse/builder/builder.go:58 +0x113
github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler.ParseAndValidateBody(0xc015e21440, 0x0, 0x0, 0xc005839718, 0x25904a8)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler/validate.go:36 +0x233
github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler.UpdateHandler(0xc015e21440, 0x3bdb5c0, 0x0, 0xc0033b63c0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler/update.go:11 +0x34
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).handle(0xc000a89290, 0x417fbe0, 0xc00fe86b60, 0xc00ea48100, 0xc011101880, 0xc00565d200, 0xc0058397d8)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:249 +0x2a2
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP(0xc000a89290, 0x417fbe0, 0xc00fe86b60, 0xc00ea48100)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:180 +0x7d
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc003111420, 0x417fbe0, 0xc00fe86b60, 0xc00ea48100)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:159 +0xf1
github.com/rancher/rancher/pkg/auth/requests.authHeaderHandler.ServeHTTP(0x414a0a0, 0xc00264b020, 0x413f8a0, 0xc003111420, 0x415dd20, 0xc0037f3a00, 0x414a060, 0xc00565d8c0, 0x417fbe0, 0xc00fe86b60, ...)
	/go/src/github.com/rancher/rancher/pkg/auth/requests/filter.go:110 +0x60d
github.com/rancher/rancher/pkg/audit.auditHandler.ServeHTTP(0x413e1e0, 0xc0040eecc0, 0x0, 0x417fbe0, 0xc00fe86b60, 0xc01050bf00)
	/go/src/github.com/rancher/rancher/pkg/audit/filter.go:31 +0x46a
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc003111340, 0x417fbe0, 0xc00fe86b60, 0xc01050bf00)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:159 +0xf1
github.com/rancher/rancher/pkg/dynamiclistener.(*Server).cacheIPHandler.func1(0x417fbe0, 0xc00fe86b60, 0xc01050bc00)
	/go/src/github.com/rancher/rancher/pkg/dynamiclistener/server.go:419 +0x101
net/http.HandlerFunc.ServeHTTP(0xc00000b980, 0x417fbe0, 0xc00fe86b60, 0xc01050bc00)
	/usr/local/go/src/net/http/server.go:1964 +0x44
net/http.serverHandler.ServeHTTP(0xc008f01c70, 0x417fbe0, 0xc00fe86b60, 0xc01050bc00)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc00e378a00, 0x4188fe0, 0xc00c6d0cc0)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:master (as of 9am 3/12/2019)
- Installation option (single install/HA): HA

**Comment by sangeethah** [comment]
Tested with Rancher version 8657cb2e

As Global Admin user ,
Create a Global DNS Provider
Create a Global DNS Entry that targets a project
Edit new Global DNS entry, change fqdn, and save.

Able to edit Global DNS entries successfully.
