### ISSUE TITLE
Deleting certificates results in certificates to be stuck in "removing" state forever.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1897]
Server version - Build from master - Aug 26

When deleting certificates, they are stuck in "removing" state forever. 
This issue is reproducible only with certain certificates. 
The certificate I attempted to delete , was used by LB at some point and but then it was removed.
 
```
mysql> select * from load_balancer_certificate_map where certificate_id in (1,3,11);
+----+------+------------+----------------------------+--------------------------------------+-------------+---------+---------------------+---------------------+---------------------+------+------------------+----------------+------------+
| id | name | account_id | kind                       | uuid                                 | description | state   | created             | removed             | remove_time         | data | load_balancer_id | certificate_id | is_default |
+----+------+------------+----------------------------+--------------------------------------+-------------+---------+---------------------+---------------------+---------------------+------+------------------+----------------+------------+
|  1 | NULL |          5 | loadBalancerCertificateMap | 5fb1c43c-954f-454c-9d5f-60f3b8121891 | NULL        | removed | 2015-08-26 23:35:16 | 2015-08-27 00:25:41 | 2015-08-27 00:26:41 | {}   |                2 |              1 |           |
|  2 | NULL |          5 | loadBalancerCertificateMap | 47ef3c5c-f238-4302-aa6e-75c8ece8a1d9 | NULL        | active  | 2015-08-26 23:57:48 | NULL                | NULL                | {}   |                3 |              1 |           |
|  3 | NULL |          5 | loadBalancerCertificateMap | 6b029f92-8c9f-42cb-ba31-afee14bbee9a | NULL        | removed | 2015-08-27 00:20:37 | 2015-08-27 00:25:41 | 2015-08-27 00:26:41 | {}   |                2 |              3 |            |
|  4 | NULL |          5 | loadBalancerCertificateMap | 47f31538-45da-4d2b-a3b0-9f4d12cd19fd | NULL        | active  | 2015-08-27 00:28:41 | NULL                | NULL                | {}   |                4 |              1 |           |
|  5 | NULL |          5 | loadBalancerCertificateMap | a6a781aa-2c53-422f-a253-97cca43672ed | NULL        | active  | 2015-08-27 00:28:41 | NULL                | NULL                | {}   |                4 |              3 |            |
|  6 | NULL |          5 | loadBalancerCertificateMap | 0df3a230-a3c9-4e1e-81fb-28d9a04a93ec | NULL        | removed | 2015-08-27 00:39:17 | 2015-08-27 01:58:23 | 2015-08-27 01:59:23 | {}   |                5 |              1 |           |
|  7 | NULL |          5 | loadBalancerCertificateMap | 061680cd-998a-4f07-ba1e-2738487a9ca0 | NULL        | removed | 2015-08-27 00:39:17 | 2015-08-27 02:23:34 | 2015-08-27 02:24:34 | {}   |                5 |              3 |            |
| 10 | NULL |          5 | loadBalancerCertificateMap | 40853953-ebb0-407f-b61a-8f8238a9a842 | NULL        | active  | 2015-08-27 02:31:54 | NULL                | NULL                | {}   |                5 |             11 |           |
| 12 | NULL |          5 | loadBalancerCertificateMap | 13164f47-d4f9-44ad-96e5-960344f259d0 | NULL        | removed | 2015-08-27 04:24:07 | 2015-08-27 04:24:40 | 2015-08-27 04:25:40 | {}   |                7 |             11 |            |
| 13 | NULL |          5 | loadBalancerCertificateMap | b2af4b9b-934b-4102-b9ca-0182070f7203 | NULL        | active  | 2015-08-27 04:28:28 | NULL                | NULL                | {}   |                7 |             11 |           |
| 14 | NULL |          5 | loadBalancerCertificateMap | 3bc38a19-97be-4d1b-8dc0-8b0706820391 | NULL        | removed | 2015-08-27 04:33:26 | 2015-08-27 05:19:34 | 2015-08-27 05:20:34 | {}   |                8 |             11 |           |
+----+------+------------+----------------------------+--------------------------------------+-------------+---------+---------------------+---------------------+---------------------+------+------------------+----------------+------------+
11 rows in set (0.00 sec)

mysql> select id,name,state, created,removed,remove_time from certificate;
+----+---------------------+----------+---------------------+---------------------+---------------------+
| id | name                | state    | created             | removed             | remove_time         |
+----+---------------------+----------+---------------------+---------------------+---------------------+
|  1 | rancher.com         | removing | 2015-08-26 22:47:58 | NULL                | NULL                |
|  2 | NULL                | removed  | 2015-08-26 23:47:00 | 2015-08-26 23:47:11 | 2015-08-26 23:48:11 |
|  3 | mytest1             | removing | 2015-08-27 00:20:16 | NULL                | NULL                |
|  4 | ecc                 | removed  | 2015-08-27 00:33:41 | 2015-08-27 00:33:58 | 2015-08-27 00:34:58 |
|  5 | ecc                 | removed  | 2015-08-27 00:35:43 | 2015-08-27 00:35:58 | 2015-08-27 00:36:58 |
|  6 | rancher_space       | active   | 2015-08-27 01:02:55 | NULL                | NULL                |
|  7 | rancher_rocks       | removed  | 2015-08-27 01:03:15 | 2015-08-27 14:42:26 | 2015-08-27 14:43:26 |
|  8 | abcde_rancher_rocks | active   | 2015-08-27 01:03:31 | NULL                | NULL                |
|  9 | testmeip1           | removed  | 2015-08-27 01:55:26 | 2015-08-27 02:07:34 | 2015-08-27 02:08:34 |
| 10 | test1               | removed  | 2015-08-27 02:23:15 | 2015-08-27 03:03:27 | 2015-08-27 03:04:27 |
| 11 | testip1             | removing | 2015-08-27 02:31:20 | NULL                | NULL                |
| 12 | mytest45            | active   | 2015-08-27 03:58:05 | NULL                | NULL                |
| 13 | mytest2             | removed  | 2015-08-27 05:24:47 | 2015-08-27 16:03:27 | 2015-08-27 16:04:27 |
| 14 | test678             | active   | 2015-08-27 15:11:13 | NULL                | NULL                |
+----+---------------------+----------+---------------------+---------------------+---------------------+
14 rows in set (0.00 sec)
```

**Comment by sangeethah** [comment]
Following exception seen repeatedly in logs:
```
2015-08-28 00:00:57,418 ERROR [:] [] [] [] [utorService-112] [i.c.p.e.e.i.ProcessEventListenerImpl] Unknown exception running process [certificate.remove:1756] on [1] java.lang.IllegalStateException: Attempt to cancel when process is still transitioning
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:194) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:161) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:110) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:107) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:107) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.eventing.impl.ProcessEventListenerImpl.processExecute(ProcessEventListenerImpl.java:66) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at sun.reflect.GeneratedMethodAccessor802.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
        at io.cattle.platform.eventing.annotation.MethodInvokingListener$1.doWithLockNoResult(MethodInvokingListener.java:76) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.eventing.annotation.MethodInvokingListener.onEvent(MethodInvokingListener.java:72) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]

2015-08-28 00:00:57,419 ERROR [:] [] [] [] [utorService-141] [i.c.p.e.e.i.ProcessEventListenerImpl] Unknown exception running process [certificate.remove:1759] on [3] java.lang.IllegalStateException: Attempt to cancel when process is still transitioning
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:194) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:161) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:110) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:107) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:107) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.eventing.impl.ProcessEventListenerImpl.processExecute(ProcessEventListenerImpl.java:66) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at sun.reflect.GeneratedMethodAccessor802.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
        at io.cattle.platform.eventing.annotation.MethodInvokingListener$1.doWithLockNoResult(MethodInvokingListener.java:76) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.eventing.annotation.MethodInvokingListener.onEvent(MethodInvokingListener.java:72) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
```

**Comment by sangeethah** [comment]
Tested with build from master - Aug 28

Attempting to delete certificates that are still associated with LB rules are not allowed.
Attempting to delete certificates after we delete the LB that uses the certificate / remove the certificate from the  LB rules succeeds.
