### ISSUE TITLE
etcd BackupConfig Enabled may sometimes be null and will cause a panic

### ISSUE THREAD

**Issue by MatthewKohner** [rancher/rancher#19093]
After upgrading from 2.1.6 to 2.2.0 rc6 I get a panic due to BackupConfig.Enabled being null. 

```2019/03/22 09:20:35 [DEBUG] NodeController calling handler nodesSyncer testing-master2
2019/03/22 09:20:36 [DEBUG] [etcd-backup] Checking backups for cluster: c-lzksq
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2aa4c41]

goroutine 11971 [running]:
github.com/rancher/rancher/pkg/controllers/management/etcdbackup.shouldBackup(0xc00d448000, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/etcdbackup/etcdbackup.go:390 +0xd1
github.com/rancher/rancher/pkg/controllers/management/etcdbackup.(*Controller).doClusterBackupSync(0xc0065dd600, 0xc00d448000, 0xc0066ddf58, 0x1)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/etcdbackup/etcdbackup.go:161 +0x6d
github.com/rancher/rancher/pkg/controllers/management/etcdbackup.(*Controller).clusterBackupSync(0xc0065dd600, 0x41914a0, 0xc00611cf00, 0x45d964b800, 0xc0065dd600, 0xc0002d4320)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/etcdbackup/etcdbackup.go:148 +0x14c
created by github.com/rancher/rancher/pkg/controllers/management/etcdbackup.Register
	/go/src/github.com/rancher/rancher/pkg/controllers/management/etcdbackup/etcdbackup.go:69 +0x69f```

**Comment by soumyalj** [comment]
Tested with rancher upgrade from v2.1.6 to v2.2.0-rc6 as mentioned in the issue. 
Did not observed the panic.
Also, edited the cluster to the new backup/restore feature and saved the cluster. After the cluster was active, it was functional. Did not observe the panic.

**Comment by sowmyav27** [comment]
Verified on an upgraded set up from `v2.1.6 to v2.2.0-rc10`.
Did not observe any panic in the server logs.
Performed edit and save of cluster, took backup snapshots, restored from a snapshot, scaling of nodes. Cluster was active & functional.
