### ISSUE TITLE
error building controller context: failed to wait for apiserver being healthy

### ISSUE THREAD

**Issue by jmreicha** [rancher/rancher#19194]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

Start the container.

```
docker run -d --restart=unless-stopped \
    -p 80:80 -p 443:443 --name rancher-server \
    rancher/rancher:v2.2.0 \
    --acme-domain mydomain.com
```

**Result:**

The server looks like it starts to bootstrap itself but then shows the following error message.

```
2019/03/26 19:53:48 [INFO] Creating CRD templates.management.cattle.io
2019-03-26 19:53:48.527023 W | etcdserver: apply entries took too long [207.355696ms for 2 entries]
2019-03-26 19:53:48.527069 W | etcdserver: avoid queries with large range/delete range!
2019/03/26 19:53:48 [INFO] Creating CRD templateversions.management.cattle.io
I0326 19:53:48.554116       6 storage_rbac.go:183] created clusterrole.rbac.authorization.k8s.io/system:aws-cloud-provider
F0326 19:53:48.674266       6 controllermanager.go:184] error building controller context: failed to wait for apiserver being healthy: timed out waiting for the condition: failed to get apiserver /healthz status: an error on the server ("[+]ping ok\n[+]log ok\n[+]etcd ok\n[+]poststarthook/generic-apiserver-start-informers ok\n[+]poststarthook/start-apiextensions-informers ok\n[+]poststarthook/start-apiextensions-controllers ok\n[+]poststarthook/bootstrap-controller ok\n[-]poststarthook/rbac/bootstrap-roles failed: reason withheld\n[+]poststarthook/scheduling/bootstrap-system-priority-classes ok\n[+]poststarthook/start-kube-apiserver-informers ok\n[+]poststarthook/start-kube-apiserver-admission-initializer ok\nhealthz check failed") has prevented the request from succeeding
```

After the first failure, the container starts bootlooping and crashing another error.

```
2019/03/26 20:26:35 [DEBUG] Setting field subscribe.projectId: types.Field{Type:"reference[/v3/schemas/project]", Default:interface {}(nil), Nullable:true, Create:true, WriteOnly:false, Required:false, Update:true, MinLength:(*int64)(nil), MaxLength:(*int64)(nil), Min:(*int64)(nil), Max:(*int64)(nil), Options:[]string(nil), ValidChars:"", InvalidChars:"", Description:"", CodeName:"ProjectID", DynamicField:false}
2019/03/26 20:26:35 [INFO] Creating CRD projects.management.cattle.io
2019/03/26 20:26:35 [INFO] Waiting for CRD  to become available
2019/03/26 20:26:35 [INFO] Done waiting for CRD  to become available
panic: creating CRD store resource name may not be empty

goroutine 2768 [running]:
github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd.(*Factory).BatchCreateCRDs.func1(0xc003f64940, 0xc0036c9880, 0x34, 0x34, 0xc0034e15e0, 0x6a3f920, 0x41915a0, 0xc00113c6c0, 0x3a735de, 0x4)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd/init.go:65 +0x2d9
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd.(*Factory).BatchCreateCRDs
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd/init.go:50 +0xce
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.2.0`
- Installation option (single install/HA): `single install`

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:40:58 2019
 OS/Arch:           linux/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     true

```

I can add any other details if needed.

**Comment by superseb** [comment]
Merging into https://github.com/rancher/rancher/issues/18679
