### ISSUE TITLE
Agent should continue to try to reach Rancher server indefinitely

### ISSUE THREAD

**Issue by aburnett** [rancher/rancher#1936]
I have two GCE VMs running rancher-agent. The VMs each rebooted and the nodes showed as "Reconnecting" in Rancher. Looking at the agent logs, I saw the following in both nodes:

```
2015-08-28 23:56:11,884 ERROR agent [139949644053392] [event.py:111] f3ccd72a-275e-41fa-95b4-a890658ac47d : Unknown error 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 96, in _worker_main
    publisher.publish(resp)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/publisher.py", line 24, in publish
    timeout=60)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 508, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='REDACTED', port=8080): Read timed out. (read timeout=60)
2015-08-28 23:57:11,886 ERROR agent [139949644053392] [event.py:73] ping : Exiting 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/eventlet/greenpool.py", line 80, in _spawn_n_impl
    func(*args, **kwargs)
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 71, in _worker
    _worker_main(worker_name, queue, ppid)
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 122, in _worker_main
    publisher.publish(resp)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/publisher.py", line 24, in publish
    timeout=60)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 508, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='REDACTED', port=8080): Read timed out. (read timeout=60)
2015-08-28 23:57:22,591 ERROR agent [139949644847856] [event.py:201] Max of [10] dropped [ping] requests exceeded 
```

`docker restart rancher-agent` cleared up the problem.

**Comment by ebuildy** [comment]
Looks like your Rancher server is not available at port 8080, isnit ?

**Comment by aburnett** [comment]
It is, I don't know why the agent failed to connect when it did. Really what I'm curious about here is did the agent just give up ("Max of [10] dropped") or did it crash and leave the container in a hung state?

**Comment by ebuildy** [comment]
Can you curl the Rancher server from the agent container ?

Also, I know Rancher plays with some iptables, maybe it broke something

**Comment by aburnett** [comment]
Ya, when I found the agent in this state the server was up and reachable. Restarting the agent container got it to connect back up. If I encounter this situation again, what extra info should I gather?

**Comment by aburnett** [comment]
This happened again on my GCE hosts. Posting more logs from the rancher agent container. I'm not sure why the server is being seen as unreachable. The agents on other VMs don't seem to be having an issue. I think the main issue here is that if this is indeed caused by the server not being reachable, why doesn't the agent continue to retry indefinitely?

    2015-09-03T10:39:02.974494809Z  - exit status 1, continuing to push stats
    2015-09-03T11:35:04.037780066Z 2015-09-03 11:35:04,037 ERROR agent [140648100137712] [event.py:201] Max of [10] dropped [ping] requests exceeded 
    2015-09-03T11:35:04.345056481Z   PID  PGID S TTY          TIME COMMAND
    2015-09-03T11:35:04.345097761Z 12547 12025 S ?        00:00:01 /bin/bash /var/lib/cattle/pyagent/cattle/process_watcher.sh
    2015-09-03T11:35:04.345103869Z 12559 12025 S ?        00:00:00 /bin/bash /var/lib/cattle/bin/cadvisor.sh cadvisor -logtostderr=true -listen_ip 127.0.0.1 -port 9344
    2015-09-03T11:35:04.345109134Z 12560 12025 S ?        00:00:16 /bin/bash /var/lib/cattle/pyagent/cattle/plugins/conntrack/conntrack.sh
    2015-09-03T11:35:04.345114349Z 12572 12025 S ?        00:00:13 host-api -cadvisor-url http://127.0.0.1:9344 -logtostderr=true -ip 0.0.0.0 -port 9345 -auth=true -host-uuid 5b460946-df81-4c12-ad7e-1f37d7a88044 -public-key /var/lib/cattle/etc/cattle/api.crt -cattle-url http://REDACTED:8080/v1 -cattle-state-dir /var/lib/rancher/state/containers
    2015-09-03T11:35:04.345128803Z 12632 12025 S ?        00:03:43 /var/log/rancher/.cadvisor -logtostderr=true -listen_ip 127.0.0.1 -port 9344
    2015-09-03T11:35:04.345133621Z 25917 12025 S ?        00:00:00 sleep 1
    2015-09-03T11:35:04.345137893Z 25923 12025 R ?        00:00:00 ps -eO pgid
    2015-09-03T11:35:04.345142687Z 25924 12025 S ?        00:00:00 grep -E PGID| 12025
    2015-09-03T11:35:04.374526929Z   PID  PGID S TTY          TIME COMMAND
    2015-09-03T11:35:04.374557403Z 12547 12025 S ?        00:00:01 /bin/bash /var/lib/cattle/pyagent/cattle/process_watcher.sh
    2015-09-03T11:35:04.374563898Z 12559 12025 S ?        00:00:00 /bin/bash /var/lib/cattle/bin/cadvisor.sh cadvisor -logtostderr=true -listen_ip 127.0.0.1 -port 9344
    2015-09-03T11:35:04.374569020Z 12560 12025 S ?        00:00:16 /bin/bash /var/lib/cattle/pyagent/cattle/plugins/conntrack/conntrack.sh
    2015-09-03T11:35:04.374574117Z 12572 12025 S ?        00:00:13 host-api -cadvisor-url http://127.0.0.1:9344 -logtostderr=true -ip 0.0.0.0 -port 9345 -auth=true -host-uuid 5b460946-df81-4c12-ad7e-1f37d7a88044 -public-key /var/lib/cattle/etc/cattle/api.crt -cattle-url http://REDACTED:8080/v1 -cattle-state-dir /var/lib/rancher/state/containers
    2015-09-03T11:35:04.374579401Z 12632 12025 S ?        00:03:43 /var/log/rancher/.cadvisor -logtostderr=true -listen_ip 127.0.0.1 -port 9344
    2015-09-03T11:35:04.374583750Z 25917 12025 S ?        00:00:00 sleep 1
    2015-09-03T11:35:04.374595447Z 25930 12025 R ?        00:00:00 ps -eO pgid
    2015-09-03T11:35:04.374600435Z 25931 12025 S ?        00:00:00 grep -E PGID| 12025
    2015-09-03T11:35:04.374830011Z PID 12025 has died doing kill 12559 12560 12572 12632 25917
    2015-09-03T11:35:04.376207442Z I0903 11:35:04.376049 12632 manager.go:862] Exiting thread watching subcontainers
    2015-09-03T11:35:04.376338051Z I0903 11:35:04.376233 12632 manager.go:282] Exiting global housekeeping thread
    2015-09-03T11:35:04.376459576Z I0903 11:35:04.376251 12632 cadvisor.go:124] Exiting given signal: terminated
    2015-09-03T11:35:06.385083265Z   PID  PGID S TTY          TIME COMMAND
    2015-09-03T11:35:06.385115254Z 12547 12025 S ?        00:00:01 /bin/bash /var/lib/cattle/pyagent/cattle/process_watcher.sh
    2015-09-03T11:35:06.385132165Z 25933 12025 R ?        00:00:00 ps -eO pgid
    2015-09-03T11:35:06.385137137Z 25934 12025 S ?        00:00:00 grep -E PGID| 12025
    2015-09-03T11:35:06.390619788Z Caught EXIT
    2015-09-03T11:35:06.394641788Z   PID  PGID S TTY          TIME COMMAND
    2015-09-03T11:35:06.394655582Z 12547 12025 S ?        00:00:01 /bin/bash /var/lib/cattle/pyagent/cattle/process_watcher.sh
    2015-09-03T11:35:06.394660787Z 25940 12025 R ?        00:00:00 ps -eO pgid
    2015-09-03T11:35:06.394665323Z 25941 12025 S ?        00:00:00 grep -E PGID| 12025
    2015-09-03T11:35:10.620458887Z INFO: Starting agent for B84CD6DB1E5B664F3D99
    2015-09-03T11:35:10.802187715Z INFO: Access Key: B84CD6DB1E5B664F3D99
    2015-09-03T11:35:10.802269482Z INFO: Config URL: http://REDACTED:8080/v1
    2015-09-03T11:35:10.802325627Z INFO: Storage URL: http://REDACTED:8080/v1
    2015-09-03T11:35:10.802365524Z INFO: API URL: http://REDACTED:8080/v1
    2015-09-03T11:35:10.802425590Z INFO: IP: 10.240.230.97
    2015-09-03T11:35:10.802490458Z INFO: Port:
    2015-09-03T11:35:10.802531796Z INFO: Required Image: rancher/agent:v0.8.1
    2015-09-03T11:35:10.802635926Z INFO: Current Image: rancher/agent:v0.8.1
    2015-09-03T11:35:10.802747918Z INFO: Using image rancher/agent:v0.8.1
    2015-09-03T11:35:10.819170416Z INFO: Downloading agent http://REDACTED:8080/v1/configcontent/configscripts
    2015-09-03T11:35:10.986812658Z INFO: Updating configscripts
    2015-09-03T11:35:11.003829061Z INFO: Downloading http://REDACTED:8080/v1//configcontent//configscripts current=
    2015-09-03T11:35:11.051615789Z INFO: Running /var/lib/cattle/download/configscripts/configscripts-1-95df366e1639cde360d968d9c39d08f0197a04875985b628a90b1c3352edf6c1/apply.sh
    2015-09-03T11:35:11.093113243Z INFO: Sending configscripts applied 1-95df366e1639cde360d968d9c39d08f0197a04875985b628a90b1c3352edf6c1
    2015-09-03T11:35:12.387735621Z INFO: Updating pyagent
    2015-09-03T11:35:12.428827156Z INFO: Downloading http://REDACTED:8080/v1//configcontent//pyagent current=
    2015-09-03T11:35:12.912665854Z INFO: Running /var/lib/cattle/download/pyagent/pyagent-1-9e3dcab12585149a65d818082279708965cd826df1937a55b24f48428f8f0c06069547103e24f5f4562a2db5d4805d60/apply.sh
    2015-09-03T11:35:12.932355775Z INFO: Updating host-api
    2015-09-03T11:35:12.936624991Z INFO: Downloading http://REDACTED:8080/v1//configcontent//host-api current=1-d413deba118400c256cd64cf9450ed3c73e4ce06a6914429843c2304c20f9d0b
    2015-09-03T11:35:13.434858223Z INFO: Already up to date
    2015-09-03T11:35:13.435187462Z INFO: Sending host-api applied 1-d413deba118400c256cd64cf9450ed3c73e4ce06a6914429843c2304c20f9d0b
    2015-09-03T11:35:14.235804197Z INFO: Updating agent-binaries
    2015-09-03T11:35:14.243516428Z INFO: Downloading http://REDACTED:8080/v1//configcontent//agent-binaries current=1-4200f9b686342da8e941359211b1d8c5f98877ae293d0ead231d43507f1c9eae
    2015-09-03T11:35:14.275646805Z INFO: Already up to date
    2015-09-03T11:35:14.275829906Z INFO: Sending agent-binaries applied 1-4200f9b686342da8e941359211b1d8c5f98877ae293d0ead231d43507f1c9eae
    2015-09-03T11:35:16.047806517Z INFO: Updating python-agent
    2015-09-03T11:35:16.064147646Z INFO: Downloading http://REDACTED:8080/v1//configcontent//python-agent current=1-6c32cbf9f6cd54d8076651492f67cdb5bb32061c3c9e506038a2c2f28927065f
    2015-09-03T11:35:57.180018629Z INFO: Already up to date
    2015-09-03T11:35:57.180228827Z INFO: Sending python-agent applied 1-6c32cbf9f6cd54d8076651492f67cdb5bb32061c3c9e506038a2c2f28927065f
    2015-09-03T11:35:58.591713454Z INFO: Updating cadvisor
    2015-09-03T11:35:58.596171487Z INFO: Downloading http://REDACTED:8080/v1//configcontent//cadvisor current=1-aeae24ebb1a792a2e1d666bf16fc1f8f3105b3041f378d5d57ae8be0cffda36d
    2015-09-03T11:35:58.699725207Z INFO: Already up to date
    2015-09-03T11:35:58.699934517Z INFO: Sending cadvisor applied 1-aeae24ebb1a792a2e1d666bf16fc1f8f3105b3041f378d5d57ae8be0cffda36d
    2015-09-03T11:36:00.117892867Z INFO: Updating volmgr
    2015-09-03T11:36:00.122246278Z INFO: Downloading http://REDACTED:8080/v1//configcontent//volmgr current=1-c813690c24ae9a12f0792378c78a48f447b243517233d7969b99baefbea5af15
    2015-09-03T11:36:00.558843357Z INFO: Already up to date
    2015-09-03T11:36:00.559068256Z INFO: Sending volmgr applied 1-c813690c24ae9a12f0792378c78a48f447b243517233d7969b99baefbea5af15
    2015-09-03T11:36:01.310275498Z INFO: Sending pyagent applied 1-9e3dcab12585149a65d818082279708965cd826df1937a55b24f48428f8f0c06069547103e24f5f4562a2db5d4805d60
    2015-09-03T11:36:02.886722263Z INFO: Starting agent /var/lib/cattle/pyagent/apply.sh
    2015-09-03T11:36:02.897697139Z INFO: Executing /var/lib/cattle/pyagent/main.py
    2015-09-03T11:36:02.921245147Z INFO: Updating host-config
    2015-09-03T11:36:02.925903481Z INFO: Downloading http://REDACTED:8080/v1//configcontent//host-config current=host-config-1-c6d986fb87e2d30b3bfc79690cfecd87bf5876bae5d3d3e73757a6e64a649ccd
    2015-09-03T11:36:02.962941734Z INFO: Already up to date
    2015-09-03T11:36:02.963214418Z INFO: Sending host-config applied 1-c6d986fb87e2d30b3bfc79690cfecd87bf5876bae5d3d3e73757a6e64a649ccd
    2015-09-03T11:36:05.268059008Z I0903 11:36:05.267918 26426 storagedriver.go:92] No backend storage selected
    2015-09-03T11:36:05.268169919Z I0903 11:36:05.268040 26426 storagedriver.go:94] Caching 60 stats in memory
    2015-09-03T11:36:05.268294518Z I0903 11:36:05.268147 26426 manager.go:106] cAdvisor running in container: "/docker/1450efb8e861aa1a61f68fe78a8ab0ecc3973bcbaf6d90b428d5fdbc92fcb6d0"
    2015-09-03T11:36:05.268909007Z I0903 11:36:05.268760 26426 fs.go:87] Filesystem partitions: map[/dev/disk/by-uuid/d1dafa85-9814-47b2-82e2-7b96783380ec:{mountpoint:/ major:8 minor:1}]
    2015-09-03T11:36:05.270501079Z I0903 11:36:05.270158 26426 manager.go:127] Machine: {NumCores:1 CpuFrequency:2599998 MemoryCapacity:618414080 MachineID:06a8bb708fa536f777c2fdbc5507239a SystemUUID:76E15A15-9647-B3DB-8A9D-6CA820EBE85B BootID:1058f03c-d5f4-4c19-b866-8f1d3d59b1dd Filesystems:[{Device:/dev/disk/by-uuid/d1dafa85-9814-47b2-82e2-7b96783380ec Capacity:10534313984}] DiskMap:map[8:0:{Name:sda Major:8 Minor:0 Size:10737418240 Scheduler:noop}] NetworkDevices:[{Name:dummy0 MacAddress:e2:96:35:45:aa:08 Speed:0 Mtu:1500} {Name:eth0 MacAddress:42:01:0a:f0:e6:61 Speed:0 Mtu:1460}] Topology:[{Id:0 Memory:618414080 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:20971520 Type:Unified Level:3}]}]}
    2015-09-03T11:36:05.271350555Z I0903 11:36:05.271226 26426 manager.go:134] Version: {KernelVersion:3.16.0-31-generic ContainerOsVersion:Ubuntu 14.04.2 LTS DockerVersion:1.8.1 CadvisorVersion:0.12.0}
    2015-09-03T11:36:05.364767638Z I0903 11:36:05.363213 26426 factory.go:226] Registering Docker factory
    2015-09-03T11:36:05.364788494Z I0903 11:36:05.363728 26426 factory.go:60] Registering Raw factory
    2015-09-03T11:36:05.364793717Z I0903 11:36:05.364178 26426 manager.go:872] Started watching for new ooms in manager
    2015-09-03T11:36:05.369797621Z I0903 11:36:05.365845 26426 manager.go:212] Starting recovery of all containers
    2015-09-03T11:36:05.395436967Z I0903 11:36:05.395311 26426 manager.go:217] Recovery completed
    2015-09-03T11:36:05.401660646Z I0903 11:36:05.401527 26426 cadvisor.go:90] Starting cAdvisor version: "0.12.0" on port 9344
    2015-09-03T11:36:05.546975180Z time="2015-09-03T11:36:05Z" level="info" msg="Starting event router." 
    2015-09-03T11:36:05.547903684Z time="2015-09-03T11:36:05Z" level="info" msg="Watching state directory: /var/lib/rancher/state/containers" 
    2015-09-03T11:36:05.550239236Z time="2015-09-03T11:36:05Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"c2e7b798c440914fb98c8feb025315b43d6640cbea5221f245783d26d1abe6f9\", From:\"-simulated-\", Time:0}" 
    2015-09-03T11:36:05.550428038Z time="2015-09-03T11:36:05Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"c17546ec0be2428c01704cab7b43ff3b4c0c0dce2ab4c8cf67ae8af7062f0f14\", From:\"-simulated-\", Time:0}" 
    2015-09-03T11:36:05.550575599Z time="2015-09-03T11:36:05Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"1450efb8e861aa1a61f68fe78a8ab0ecc3973bcbaf6d90b428d5fdbc92fcb6d0\", From:\"-simulated-\", Time:0}" 
    2015-09-03T11:36:05.552749065Z time="2015-09-03T11:36:05Z" level="info" msg="Assigning IP [10.42.166.48/16], ContainerId [c17546ec0be2428c01704cab7b43ff3b4c0c0dce2ab4c8cf67ae8af7062f0f14], Pid [2837]" 
    2015-09-03T11:36:05.555521225Z time="2015-09-03T11:36:05Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"d9bc9dc440a08a2b791dc7b3c235a2450295165e064b144c9d2fb441bb0771d4\", From:\"-simulated-\", Time:0}" 
    2015-09-03T11:36:05.557780458Z time="2015-09-03T11:36:05Z" level="info" msg="Assigning IP [10.42.161.149/16], ContainerId [d9bc9dc440a08a2b791dc7b3c235a2450295165e064b144c9d2fb441bb0771d4], Pid [1548]" 
    2015-09-03T11:36:05.558804743Z time="2015-09-03T11:36:05Z" level="info" msg="Assigning IP [10.42.109.135/16], ContainerId [c2e7b798c440914fb98c8feb025315b43d6640cbea5221f245783d26d1abe6f9], Pid [25863]" 
    2015-09-03T11:36:06.290123827Z time="2015-09-03T11:36:06Z" level="info" msg="Connecting to proxy." url="ws://REDACTED:8080/v1/connectbackend?token=eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjE0NDEyODA0NjYsInN1YiI6ImNhdHRsZSIsImlzcyI6Imh0dHA6XC9cL2NhdHRsZS5pbyIsInJlcG9ydGVkVXVpZCI6IjViNDYwOTQ2LWRmODEtNGMxMi1hZDdlLTFmMzdkN2E4ODA0NCIsImlhdCI6MTQ0MTI4MDE2Niwia2lkIjoiZGVmYXVsdCJ9.Rv7fP53HSwWWi-WhnYh1UHoObdTiCTVsyRom3qtAzBE6Lgw35Qwerx8Tdxw2lMd0FdsWEyWbr9FNbEuOciwHVyDjsaOB_OYL1aY45QSrSXKjVmXn7ivyJB_c9K9RNU53QdgOuMO6cgxfMBMwVXqfZxyM92PpO0yuvbrxWLcWTZauQGmjjeZ1TPgjQX5821bwu5xbuoxNFCY6EUoW90wmW1VkTUv20Gj_iByv2RHZFan2uD9QktlZM3rlIP3Plp7zJECYcWKgMiIg8RgVcgTcyImwQ_G401_eGIsenxR7YcXp96HyaJSJ3xYeN4-xhVBYXs2sJHyyUMHX1LYQjeiMKA" 
    2015-09-03T11:52:59.420442336Z I0903 11:52:59.420276 26426 container.go:242] Failed to update stats for container "/docker/c17546ec0be2428c01704cab7b43ff3b4c0c0dce2ab4c8cf67ae8af7062f0f14": du command failed on /var/lib/docker/aufs/diff/c17546ec0be2428c01704cab7b43ff3b4c0c0dce2ab4c8cf67ae8af7062f0f14 with output du: cannot access '/var/lib/docker/aufs/diff/c17546ec0be2428c01704cab7b43ff3b4c0c0dce2ab4c8cf67ae8af7062f0f14/var/lib/cattle/download.dborp8j': No such file or directory
    2015-09-03T11:52:59.420484877Z 59032	/var/lib/docker/aufs/diff/c17546ec0be2428c01704cab7b43ff3b4c0c0dce2ab4c8cf67ae8af7062f0f14
    2015-09-03T11:52:59.420491699Z  - exit status 1, continuing to push stats
    2015-09-03T12:00:42.419809618Z I0903 12:00:42.419648 26426 container.go:242] Failed to update stats for container "/docker/c17546ec0be2428c01704cab7b43ff3b4c0c0dce2ab4c8cf67ae8af7062f0f14": du command failed on /var/lib/docker/aufs/diff/c17546ec0be2428c01704cab7b43ff3b4c0c0dce2ab4c8cf67ae8af7062f0f14 with output du: cannot access '/var/lib/docker/aufs/diff/c17546ec0be2428c01704cab7b43ff3b4c0c0dce2ab4c8cf67ae8af7062f0f14/var/lib/cattle/download.lsjr4jv': No such file or directory
    2015-09-03T12:00:42.419851334Z 59052	/var/lib/docker/aufs/diff/c17546ec0be2428c01704cab7b43ff3b4c0c0dce2ab4c8cf67ae8af7062f0f14
    2015-09-03T12:00:42.419858138Z  - exit status 1, continuing to push stats
    2015-09-03T12:17:42.426412516Z I0903 12:17:42.426233 26426 container.go:242] Failed to update stats for container "/docker/c17546ec0be2428c01704cab7b43ff3b4c0c0dce2ab4c8cf67ae8af7062f0f14": du command failed on /var/lib/docker/aufs/diff/c17546ec0be2428c01704cab7b43ff3b4c0c0dce2ab4c8cf67ae8af7062f0f14 with output du: cannot access '/var/lib/docker/aufs/diff/c17546ec0be2428c01704cab7b43ff3b4c0c0dce2ab4c8cf67ae8af7062f0f14/var/lib/cattle/download.TfxET0C': No such file or directory
    2015-09-03T12:17:42.426461257Z 59068	/var/lib/docker/aufs/diff/c17546ec0be2428c01704cab7b43ff3b4c0c0dce2ab4c8cf67ae8af7062f0f14
    2015-09-03T12:17:42.426489377Z  - exit status 1, continuing to push stats
    2015-09-03T12:19:30.795322903Z 2015-09-03 12:19:30,794 ERROR agent [140410344247376] [event.py:111] 07fad060-eccd-4b89-b803-db5008bf26e4 : Unknown error 
    2015-09-03T12:19:30.795368908Z Traceback (most recent call last):
    2015-09-03T12:19:30.795375095Z   File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 96, in _worker_main
    2015-09-03T12:19:30.795379843Z     publisher.publish(resp)
    2015-09-03T12:19:30.795391456Z   File "/var/lib/cattle/pyagent/cattle/plugins/core/publisher.py", line 24, in publish
    2015-09-03T12:19:30.795396607Z     timeout=60)
    2015-09-03T12:19:30.795401458Z   File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 508, in post
    2015-09-03T12:19:30.795405936Z     return self.request('POST', url, data=data, json=json, **kwargs)
    2015-09-03T12:19:30.795425893Z   File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 465, in request
    2015-09-03T12:19:30.795431063Z     resp = self.send(prep, **send_kwargs)
    2015-09-03T12:19:30.795435114Z   File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 573, in send
    2015-09-03T12:19:30.795439418Z     r = adapter.send(request, **kwargs)
    2015-09-03T12:19:30.795443527Z   File "/var/lib/cattle/pyagent/dist/requests/adapters.py", line 433, in send
    2015-09-03T12:19:30.795447716Z     raise ReadTimeout(e, request=request)
    2015-09-03T12:19:30.795452285Z ReadTimeout: HTTPConnectionPool(host='REDACTED', port=8080): Read timed out. (read timeout=60)
    2015-09-03T12:38:48.420990381Z I0903 12:38:48.420807 26426 container.go:242] Failed to update stats for container "/docker/c17546ec0be2428c01704cab7b43ff3b4c0c0dce2ab4c8cf67ae8af7062f0f14": du command failed on /var/lib/docker/aufs/diff/c17546ec0be2428c01704cab7b43ff3b4c0c0dce2ab4c8cf67ae8af7062f0f14 with output du: cannot access '/var/lib/docker/aufs/diff/c17546ec0be2428c01704cab7b43ff3b4c0c0dce2ab4c8cf67ae8af7062f0f14/var/lib/cattle/download.VOenZnK': No such file or directory
    2015-09-03T12:38:48.421036775Z 59108	/var/lib/docker/aufs/diff/c17546ec0be2428c01704cab7b43ff3b4c0c0dce2ab4c8cf67ae8af7062f0f14
    2015-09-03T12:38:48.421043621Z  - exit status 1, continuing to push stats
    2015-09-03T13:06:55.900775181Z udp      17 29 src=172.17.0.2 dst=10.240.241.71 sport=4500 dport=4500 [UNREPLIED] src=10.240.241.71 dst=10.240.230.97 sport=4500 dport=4500 mark=0 use=1

**Comment by teon** [comment]
+1 - have identical issues on ALL my agents that are not in the same network as rancher server.
host and rancher server (despite the fact that are not on the same network) have conectivity - I can curl the rancher or ping or connect to any port - same as for the host (from rancher server).

BUT if the host is not in the same network - the agent:
- connects
- downloads the configuration
- after some time just stops (max retry conenctions)

**Comment by cjellick** [comment]
@teon @aburnett The intent is that when you see that `Max of [10] dropped [ping] requests exceeded`, we are giving up the process is dying, but it should be immediately restarted.

@aburnett This is why in your second set of logs you posted, you see additional logging after the `Max of [10] dropped...` statement. Was that the end of the logs or did it eventually report `Max of [10]...` statement again?

@teon is your scenario the same? Do you only see this after a reboot of the VM and does restarting rancher-agent fix it for you?

**Comment by aburnett** [comment]
@cjellick Honestly I don't remember at this point re: the second set of logs. I don't think the problem was necessarily that it gave up after 10 retries but rather that stacktrace from events.py. Once that was thrown it was usually game over for the agent.

**Comment by teon** [comment]
@cjellick it is restarting after 10 retries - what warries me is why is the agent dying...
This problem occures if the agent is not in the same network.. but what is wired it may not be the same network but it is my LAN... Whatever the lan segment - Ive double or tripple checked and there is all conectivity.
Also, It connects to the server, I have all my container info, but all agents in other networks servers die and reconnect infinitly..

**Comment by cjellick** [comment]
@teon the connection from agent to server is a long lived websocket connection is it possible you have a network device that is disallowing it or is killing it after some amount of time?

**Comment by aburnett** [comment]
@cjellick how does the websocket behave in the face of a network partition? Will it recover with the partition is resolved?  

Are there any resources you could point us to around agent operations? What to monitor, failure modes, etc?

**Comment by cjellick** [comment]
@aburnett The connection should terminate when the partition occurs. The agent then goes into a continual loop of trying to connect back every few seconds. On the server side, once the agent stopped responding to events (and after some grace period) the corresponding host goes into the "Reconnecting" state. While it is in this state, new containers will not be scheduled to it. Once the partition is resolved, because the agent never stopped trying to connect, it would connect successfully, start responding to ping events, and the host would be transitioned back to the active state.

I don't we have these details further documented elsewhere. The "state" field of the host resource in the API would be a good first line of defense. "active" is the normal healthy state.

**Comment by will-chan** [comment]
Closing due to inactivity.
