### ISSUE TITLE
Rancher server crash with "lost master" error

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#19585]
The same issue as https://github.com/rancher/rancher/issues/18505   in v2.2.2-rc10 and v2.2.2-rc11
setup: single install, 4 vCPU, 8GB memory
It happens after I run the automation in an RKE cluster, and the logs show `lost master` 
```
I0412 00:40:36.159827       7 trace.go:76] Trace[1294926626]: "Get /api/v1/namespaces/kube-system/endpoints/kube-scheduler" (started: 2019-04-12 00:40:26.580904568 +0000 UTC m=+1496.029070405) (total time: 9.578891662s):
Trace[1294926626]: [9.578814204s] [9.57867164s] About to write a response
I0412 00:40:36.580516       7 leaderelection.go:231] failed to renew lease kube-system/kube-scheduler: failed to tryAcquireOrRenew context deadline exceeded
E0412 00:40:36.580567       7 server.go:207] lost master
lost lease
2019/04/12 00:40:51 [INFO] Listening on /tmp/log.sock
2019/04/12 00:40:51 [INFO] Rancher version v2.2.2-rc11 is starting
```

**Comment by Oats87** [comment]
@deniseschannon are we going to backport whatever our fix for this into v2.2.x?

**Comment by chendo** [comment]
Seeing this as well on v2.2.2, single master install:

```
2019-04-29 02:13:43.443529 W | etcdserver: apply entries took too long [2.458767663s for 1 entries]
2019-04-29 02:13:43.443917 W | etcdserver: avoid queries with large range/delete range!
I0429 02:13:47.149286       6 trace.go:76] Trace[1158079405]: "List /apis/management.cattle.io/v3/namespaces/p-28tr9/projectloggings" (started: 2019-04-29 02:13:37.457225975 +0000 UTC m=+3631.790283549) (total time: 9.688945013s):
Trace[1158079405]: [2.612163046s] [2.612163046s] About to List from storage
Trace[1158079405]: [7.486704661s] [4.874541615s] Listing from storage done
Trace[1158079405]: [9.688940071s] [2.201644078s] Writing http response done (0 items)
2019/04/29 02:13:48 [INFO] 2019/04/29 02:13:48 http: response.Write on hijacked connection
2019/04/29 02:13:48 [INFO] 2019/04/29 02:13:48 http: response.Write on hijacked connection
2019/04/29 02:13:47 [INFO] Updating global catalog helm
I0429 02:13:52.161686       6 leaderelection.go:231] failed to renew lease kube-system/kube-scheduler: failed to tryAcquireOrRenew context deadline exceeded
E0429 02:13:52.163380       6 server.go:207] lost master
lost lease
```

**Comment by moschlar** [comment]
Ditto!
Any way to help you debugging?

**Comment by conet** [comment]
I see this while the machine where rancher is running is under IO load (high iowait CPU usage).

**Comment by padiazg** [comment]
I have the same issue running on a DEV1-S (2x X86_64; 2Gb RAM) instance on Scaleway. 
```bash
$ docker logs --tail 20 reverent_agnesi
Trace[1425173740]: [3.03480206s] [2.741645702s] Object stored in database
Trace[1425173740]: [3.688094837s] [650.793617ms] END
2019-05-29 13:03:47.460159 W | etcdserver: apply entries took too long [412.191325ms for 1 entries]
2019-05-29 13:03:47.462421 W | etcdserver: avoid queries with large range/delete range!
I0529 13:03:50.189487       6 trace.go:76] Trace[136167618]: "GuaranteedUpdate etcd3: *core.Endpoints" (started: 2019-05-29 13:03:42.86167069 +0000 UTC m=+43352.109831729) (total time: 7.32275653s):
Trace[136167618]: [885.96215ms] [885.96215ms] initial value restored
Trace[136167618]: [2.581532139s] [1.695569989s] Transaction prepared
Trace[136167618]: [6.512362602s] [3.930830463s] Transaction committed
Trace[136167618]: [7.32275653s] [810.393928ms] END
I0529 13:03:50.665364       6 trace.go:76] Trace[208087820]: "List /api/v1/nodes" (started: 2019-05-29 13:03:48.281352529 +0000 UTC m=+43357.529513598) (total time: 2.38190166s):
Trace[208087820]: [2.117408996s] [2.116666288s] Listing from storage done
Trace[208087820]: [2.381620611s] [262.275262ms] Writing http response done (0 items)
I0529 13:03:52.473159       6 trace.go:76] Trace[1755003858]: "List /apis/batch/v1beta1/cronjobs" (started: 2019-05-29 13:03:49.875716662 +0000 UTC m=+43359.123877541) (total time: 2.516373174s):
Trace[1755003858]: [2.038980283s] [2.038394641s] Listing from storage done
Trace[1755003858]: [2.515297422s] [469.968347ms] Writing http response done (0 items)
2019-05-29 13:03:52.603016 W | etcdserver: apply entries took too long [239.754982ms for 1 entries]
2019-05-29 13:03:52.611325 W | etcdserver: avoid queries with large range/delete range!
I0529 13:03:53.195458       6 leaderelection.go:231] failed to renew lease kube-system/kube-scheduler: failed to tryAcquireOrRenew context deadline exceeded
E0529 13:03:53.468629       6 server.go:207] lost master
lost lease
```

```bash
$ docker -v
Docker version 18.09.6, build 481bc77

$ docker inspect rancher/rancher:latest
[
    {
        "Id": "sha256:1d6627a9e2de32f6e6f1a58723b36cfdcb7293ee82fab70b8b3b756b91a0a25a",
        "RepoTags": [
            "rancher/rancher:latest"
        ],
        "RepoDigests": [
            "rancher/rancher@sha256:75d3321ff1f038b7b2dd8a3de84b70fdd61ce4efead838bec9bc88bf6a99ac2e"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2019-05-14T04:06:54.405526017Z",
        "Container": "36bee6a5995d4b28f30722d843955f02a57b998204560548f423f770445d9589",
        "ContainerConfig": {
            "Hostname": "36bee6a5995d",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "CATTLE_HELM_VERSION=v2.10.0-rancher10",
                "CATTLE_MACHINE_VERSION=v0.15.0-rancher6-1",
                "LOGLEVEL_VERSION=v0.1.2",
                "TINI_VERSION=v0.18.0",
                "TELEMETRY_VERSION=v0.5.3",
                "TINI_URL_amd64=https://github.com/krallin/tini/releases/download/v0.18.0/tini",
                "TINI_URL_arm64=https://github.com/krallin/tini/releases/download/v0.18.0/tini-arm64",
                "TINI_URL=TINI_URL_amd64",
                "HELM_URL_amd64=https://github.com/rancher/helm/releases/download/v2.10.0-rancher10/helm",
                "HELM_URL_arm64=https://github.com/rancher/helm/releases/download/v2.10.0-rancher10/helm-arm64",
                "HELM_URL=HELM_URL_amd64",
                "TILLER_URL_amd64=https://github.com/rancher/helm/releases/download/v2.10.0-rancher10/tiller",
                "TILLER_URL_arm64=https://github.com/rancher/helm/releases/download/v2.10.0-rancher10/tiller-arm64",
                "TILLER_URL=TILLER_URL_amd64",
                "CATTLE_UI_PATH=/usr/share/rancher/ui",
                "CATTLE_UI_VERSION=2.2.41",
                "CATTLE_CLI_VERSION=v2.2.0",
                "CATTLE_API_UI_VERSION=1.1.6",
                "AUDIT_LOG_PATH=/var/log/auditlog/rancher-api-audit.log",
                "AUDIT_LOG_MAXAGE=10",
                "AUDIT_LOG_MAXBACKUP=10",
                "AUDIT_LOG_MAXSIZE=100",
                "AUDIT_LEVEL=0",
                "CATTLE_CLI_URL_DARWIN=https://releases.rancher.com/cli2/v2.2.0/rancher-darwin-amd64-v2.2.0.tar.gz",
                "CATTLE_CLI_URL_LINUX=https://releases.rancher.com/cli2/v2.2.0/rancher-linux-amd64-v2.2.0.tar.gz",
                "CATTLE_CLI_URL_WINDOWS=https://releases.rancher.com/cli2/v2.2.0/rancher-windows-386-v2.2.0.zip",
                "CATTLE_SERVER_VERSION=v2.2.3",
                "CATTLE_AGENT_IMAGE=rancher/rancher-agent:v2.2.3",
                "CATTLE_WINDOWS_AGENT_IMAGE=rancher/rancher-agent:v2.2.3-nanoserver-1803",
                "CATTLE_SERVER_IMAGE=rancher/rancher",
                "ETCD_UNSUPPORTED_ARCH=amd64",
                "SSL_CERT_DIR=/etc/rancher/ssl"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "LABEL org.label-schema.vcs-url=https://github.com/rancher/rancher.git"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:2fcec17d207e9471bcb27c22aef947066413752170115d694be75b31043ba273",
            "Volumes": {
                "/var/lib/rancher": {},
                "/var/log/auditlog": {}
            },
            "WorkingDir": "/var/lib/rancher",
            "Entrypoint": [
                "entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "org.label-schema.build-date": "2019-05-14T04:06:18Z",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vcs-ref": "b1896822e58bb42a513b664aca88ed410a5a7add",
                "org.label-schema.vcs-url": "https://github.com/rancher/rancher.git"
            }
        },
        "DockerVersion": "18.09.4",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "CATTLE_HELM_VERSION=v2.10.0-rancher10",
                "CATTLE_MACHINE_VERSION=v0.15.0-rancher6-1",
                "LOGLEVEL_VERSION=v0.1.2",
                "TINI_VERSION=v0.18.0",
                "TELEMETRY_VERSION=v0.5.3",
                "TINI_URL_amd64=https://github.com/krallin/tini/releases/download/v0.18.0/tini",
                "TINI_URL_arm64=https://github.com/krallin/tini/releases/download/v0.18.0/tini-arm64",
                "TINI_URL=TINI_URL_amd64",
                "HELM_URL_amd64=https://github.com/rancher/helm/releases/download/v2.10.0-rancher10/helm",
                "HELM_URL_arm64=https://github.com/rancher/helm/releases/download/v2.10.0-rancher10/helm-arm64",
                "HELM_URL=HELM_URL_amd64",
                "TILLER_URL_amd64=https://github.com/rancher/helm/releases/download/v2.10.0-rancher10/tiller",
                "TILLER_URL_arm64=https://github.com/rancher/helm/releases/download/v2.10.0-rancher10/tiller-arm64",
                "TILLER_URL=TILLER_URL_amd64",
                "CATTLE_UI_PATH=/usr/share/rancher/ui",
                "CATTLE_UI_VERSION=2.2.41",
                "CATTLE_CLI_VERSION=v2.2.0",
                "CATTLE_API_UI_VERSION=1.1.6",
                "AUDIT_LOG_PATH=/var/log/auditlog/rancher-api-audit.log",
                "AUDIT_LOG_MAXAGE=10",
                "AUDIT_LOG_MAXBACKUP=10",
                "AUDIT_LOG_MAXSIZE=100",
                "AUDIT_LEVEL=0",
                "CATTLE_CLI_URL_DARWIN=https://releases.rancher.com/cli2/v2.2.0/rancher-darwin-amd64-v2.2.0.tar.gz",
                "CATTLE_CLI_URL_LINUX=https://releases.rancher.com/cli2/v2.2.0/rancher-linux-amd64-v2.2.0.tar.gz",
                "CATTLE_CLI_URL_WINDOWS=https://releases.rancher.com/cli2/v2.2.0/rancher-windows-386-v2.2.0.zip",
                "CATTLE_SERVER_VERSION=v2.2.3",
                "CATTLE_AGENT_IMAGE=rancher/rancher-agent:v2.2.3",
                "CATTLE_WINDOWS_AGENT_IMAGE=rancher/rancher-agent:v2.2.3-nanoserver-1803",
                "CATTLE_SERVER_IMAGE=rancher/rancher",
                "ETCD_UNSUPPORTED_ARCH=amd64",
                "SSL_CERT_DIR=/etc/rancher/ssl"
            ],
            "Cmd": null,
            "ArgsEscaped": true,
            "Image": "sha256:2fcec17d207e9471bcb27c22aef947066413752170115d694be75b31043ba273",
            "Volumes": {
                "/var/lib/rancher": {},
                "/var/log/auditlog": {}
            },
            "WorkingDir": "/var/lib/rancher",
            "Entrypoint": [
                "entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "org.label-schema.build-date": "2019-05-14T04:06:18Z",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vcs-ref": "b1896822e58bb42a513b664aca88ed410a5a7add",
                "org.label-schema.vcs-url": "https://github.com/rancher/rancher.git"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 507644667,
        "VirtualSize": 507644667,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/bf4e1ff27cc1dcee2783f010defd10c67200df88889505763c0dfbb8e2ea5554/diff:/var/lib/docker/overlay2/849b450f5cb8726a1aac8e142447446dba3698b32e312606246a7169e523e504/diff:/var/lib/docker/overlay2/9185cf5952cf61c1c69759959052e0ad77bcc0f40ca1f255cd8341d4ee51c309/diff:/var/lib/docker/overlay2/a46270d5d343a82811d0d0c3e49ea24788af78d4a220ae29ad0b6763abf2e00f/diff:/var/lib/docker/overlay2/1c126a2bb74a6255b5514534563f9f4a4bc07a22699fe59b6abe74cc92350ec2/diff:/var/lib/docker/overlay2/9c4069308c8b7b65e04e4fad609408bf434d4ee5da50aa8fa29bcd2dcb858caa/diff:/var/lib/docker/overlay2/1493bc366fca60d7e79210bafa05ac7938e9385ca0e8d506179bb760b041be36/diff:/var/lib/docker/overlay2/1818bd1f73e3548d82bddbb69f4374eb85feb0bb3b8849515ceec7cca242b89f/diff:/var/lib/docker/overlay2/dca4e99e1485007b4499135e2e2209c3475b3da4baae5d18e444fa33673b9e3b/diff:/var/lib/docker/overlay2/ff40cff85b29bcebb01a171ee8bbe70416b9a7b788e64385cbcc12b0fcc572e5/diff:/var/lib/docker/overlay2/34e263e835a5d918923082018793a84567830a55f50a40d640e256f146c047c8/diff",
                "MergedDir": "/var/lib/docker/overlay2/0b2ecafb49ba0b29077c2eff215ded635874d45fc0296219b56504eae04287e8/merged",
                "UpperDir": "/var/lib/docker/overlay2/0b2ecafb49ba0b29077c2eff215ded635874d45fc0296219b56504eae04287e8/diff",
                "WorkDir": "/var/lib/docker/overlay2/0b2ecafb49ba0b29077c2eff215ded635874d45fc0296219b56504eae04287e8/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:604cbde1a4c8fee1b102f8b64d4f41e62d770b5f8a6b06fb809cfd873a2643c3",
                "sha256:5d74a98c48bcfc2d04e9d679ea095d360ac0b2f2a27312c8e95a7f5ba5341d9c",
                "sha256:94e5c4ea5da6d2a5e0232458e8f14a2cdba0d0f0ce1bdd8098789477c89a7f45",
                "sha256:7660ded5319c352f98b8b305b6bd11a501b9704f5e31d1e3b1d3da644f1c3fb8",
                "sha256:40acc7728a085594f9c8acad83a34ee44f9d832dcc383536f8acc432ea280ad3",
                "sha256:1bb3410526e4b490c9f0891db354649d62c435d3fc9f9034d8bbf316bd437043",
                "sha256:9d1b150cb1ce4412843079e3f9b843ffeb3d9c552cd9412653d8ed9a303712fa",
                "sha256:513bfd4b095f69b34acde24ed08987927b959ae8b17940196285362c75db3792",
                "sha256:c8d4d95e43290c758dabed33580a9621e06e6dc2439cdf9fdea20c6c89401e7e",
                "sha256:d863da021f1d1aec7489c28224b90bb2ed3ad73273d8b7a23196c894275a4ed0",
                "sha256:567e9ea423fc21cf0d43b493a73573995dcd2bf9f93c4a7d588f7d4aff0ac884",
                "sha256:9d28042b0feb554f3a8e7fe795a27cd9d5182f201a5791e29a3d5813e063f52f"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```
Master is a K3s on another DEV1-S instance:
````bash
$ k3s -v
k3s version v0.5.0 (8c0116dd)
```

**Comment by ribx** [comment]
I restarted the whole cluster and rancher come up again.

**Comment by ViceIce** [comment]
Having the same issue with rancher v2.2.5 single server

**Comment by cjellick** [comment]
This happens when we cannot read/write to etcd fast enough. Can be due to high load or an underpowered box that rancher is running on.

**Comment by cjellick** [comment]
@dramich i just want to discuss this with @ibuildthecloud before we do anything with it

**Comment by cjellick** [comment]
Id like to investigate this as part of our v2.4 performance bucket of work. cc @cloudnautique @deniseschannon

**Comment by b0r1sp** [comment]
> This happens when we cannot read/write to etcd fast enough. 

Not sure, if that is the reason. I have the same issue running on a DO managed Kubernetes cluster (4x 4GB RAM).

```bash
rancher        | created by github.com/rancher/k3s/pkg/daemons/control.controllerManager
rancher        | 	/go/src/github.com/rancher/k3s/pkg/daemons/control/server.go:119 +0x5cc
rancher        | E1118 14:25:07.331440      31 server.go:252] lost master
rancher        | lost lease
rancher        | E1118 14:25:08.486147       6 reflector.go:280] github.com/rancher/norman/controller/generic_controller.go:175: Failed to watch *v1.RoleBinding: Get https://localhost:6443/apis/rbac.authorization.k8s.io/v1/watch/rolebindings?allowWatchBookmarks=true&resourceVersion=6641056&timeout=30m0s&timeoutSeconds=386: read tcp 127.0.0.1:45284->127.0.0.1:6443: read: connection reset by peer
rancher        | 2019/11/18 14:25:08 [FATAL] k3s exited with: exit status 1
```

**Comment by b0r1sp** [comment]
Actually, that happens on average *once a day*, here's another example:

```bash
rancher        | 2019-11-19 15:41:53.270350 W | etcdserver: read-only range request "key:\"/registry/management.cattle.io/projects\" range_end:\"/registry/management.cattle.io/projectt\" count_only:true " with result "range_response_count:0 size:9" took too long (8.361418847s) to execute
rancher        | 2019-11-19 15:41:53.272986 W | etcdserver: read-only range request "key:\"/registry/horizontalpodautoscalers\" range_end:\"/registry/horizontalpodautoscalert\" count_only:true " with result "range_response_count:0 size:7" took too long (9.149485718s) to execute
rancher        | 2019-11-19 15:41:53.273033 W | etcdserver: read-only range request "key:\"/registry/management.cattle.io/kontainerdrivers\" range_end:\"/registry/management.cattle.io/kontainerdrivert\" count_only:true " with result "range_response_count:0 size:9" took too long (10.223542632s) to execute
rancher        | 2019-11-19 15:41:53.273133 W | etcdserver: read-only range request "key:\"/registry/management.cattle.io/clusterregistrationtokens\" range_end:\"/registry/management.cattle.io/clusterregistrationtokent\" count_only:true " with result "range_response_count:0 size:9" took too long (8.833572345s) to execute
rancher        | E1119 15:41:53.330222      32 server.go:252] lost master
rancher        | lost lease
rancher        | E1119 15:41:53.523336       7 leaderelection.go:365] Failed to update lock: Put https://localhost:6443/api/v1/namespaces/kube-system/configmaps/cattle-controllers?timeout=30s: read tcp 127.0.0.1:45130->127.0.0.1:6443: read: connection reset by peer
rancher        | 2019/11/19 15:41:53 [FATAL] k3s exited with: exit status 1
```

**Comment by cjellick** [comment]
@b0r1sp are you saying the rancher management plane is running on a DO K8s cluster?

**Comment by b0r1sp** [comment]
Yes, a managed DO cluster.

**Comment by soumyalj** [comment]
Tested with master-head from Dec 23(70452ced53c7)

1. Created a rancher server with master-head branch.
2. Set up notifiers and tested alerts.
3. Tested logging feature using fluentd target.

Observed a panic in the logs and rancher server exited after a couple of hours after setup.

```
2019-12-24 04:01:23.261085 W | etcdserver: read-only range request "key:\"/registry/management.cattle.io/clustertemplaterevisions\" range_end:\"/registry/management.cattle.io/clustertemplaterevisiont\" count_only:true " with result "error:etcdserver: request timed out" took too long (21.161702605s) to execute
2019-12-24 04:01:23.261130 W | etcdserver: read-only range request "key:\"/registry/ingress\" range_end:\"/registry/ingrest\" count_only:true " with result "error:etcdserver: request timed out" took too long (14.085359845s) to execute
2019-12-24 04:01:23.261187 W | etcdserver: read-only range request "key:\"/registry/management.cattle.io/multiclusterapprevisions\" range_end:\"/registry/management.cattle.io/multiclusterapprevisiont\" count_only:true " with result "error:etcdserver: request timed out" took too long (21.24195591s) to execute
2019-12-24 04:01:23.261206 W | etcdserver: read-only range request "key:\"/registry/networkpolicies\" range_end:\"/registry/networkpoliciet\" count_only:true " with result "error:etcdserver: request timed out" took too long (14.14726967s) to execute
2019-12-24 04:01:23.261267 W | etcdserver: read-only range request "key:\"/registry/management.cattle.io/settings\" range_end:\"/registry/management.cattle.io/settingt\" count_only:true " with result "error:etcdserver: request timed out" took too long (21.492335718s) to execute
2019-12-24 04:01:23.261311 W | etcdserver: read-only range request "key:\"/registry/persistentvolumes\" range_end:\"/registry/persistentvolumet\" count_only:true " with result "error:etcdserver: request timed out" took too long (14.224109866s) to execute
2019-12-24 04:01:23.261344 W | etcdserver: read-only range request "key:\"/registry/cronjobs/\" range_end:\"/registry/cronjobs0\" limit:500 " with result "error:etcdserver: request timed out" took too long (21.723121196s) to execute
2019-12-24 04:01:23.261353 W | etcdserver: read-only range request "key:\"/registry/management.cattle.io/clusterloggings\" range_end:\"/registry/management.cattle.io/clusterloggingt\" count_only:true " with result "error:etcdserver: request timed out" took too long (18.13349636s) to execute
2019-12-24 04:01:23.261377 W | etcdserver: read-only range request "key:\"/registry/management.cattle.io/rkek8sserviceoptions\" range_end:\"/registry/management.cattle.io/rkek8sserviceoptiont\" count_only:true " with result "error:etcdserver: request timed out" took too long (9.168496616s) to execute
2019-12-24 04:01:23.261420 W | etcdserver: read-only range request "key:\"/registry/management.cattle.io/templatecontents\" range_end:\"/registry/management.cattle.io/templatecontentt\" count_only:true " with result "error:etcdserver: request timed out" took too long (13.228917454s) to execute
2019-12-24 04:01:23.261460 W | etcdserver: read-only range request "key:\"/registry/minions/\" range_end:\"/registry/minions0\" " with result "error:etcdserver: request timed out" took too long (14.181283469s) to execute
2019-12-24 04:01:25.295511 W | wal: sync duration of 15.3773633s, expected less than 1s
E1224 04:01:11.533841      33 leaderelection.go:341] Failed to update lock: Put https://localhost:6444/api/v1/namespaces/kube-system/endpoints/kube-scheduler?timeout=10s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1224 04:01:11.878352      33 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
E1224 04:01:11.878364      33 leaderelection.go:306] error retrieving resource lock kube-system/kube-controller-manager: Get https://localhost:6444/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
E1224 04:01:25.296197      33 status.go:71] apiserver received an error that is not an metav1.Status: rpctypes.EtcdError{code:0xe, desc:"etcdserver: request timed out"}
E1224 04:01:25.296209      33 server.go:252] lost master
F1224 04:01:25.297060      33 controllermanager.go:248] leaderelection lost
goroutine 2218 [running]:
github.com/rancher/k3s/vendor/k8s.io/klog.stacks(0xc0005fb000, 0xc0000d0dc0, 0x4c, 0x150)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:828 +0xb1
github.com/rancher/k3s/vendor/k8s.io/klog.(*loggingT).output(0x6082c40, 0xc000000003, 0xc00eb1e150, 0x5d916fd, 0x14, 0xf8, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:779 +0x2d9
github.com/rancher/k3s/vendor/k8s.io/klog.(*loggingT).printf(0x6082c40, 0x3, 0x34479ed, 0x13, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:678 +0x14e
github.com/rancher/k3s/vendor/k8s.io/klog.Fatalf(...)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:1209
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.Run.func2()
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:248 +0x5c
github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run.func1(0xc002e99d40)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:175 +0x40
github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0xc002e99d40, 0x3c4d4a0, 0xc005779400)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:184 +0x10f
github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection.RunOrDie(0x3c4d4e0, 0xc00005e058, 0x3c74d80, 0xc002fd4c80, 0x37e11d600, 0x2540be400, 0x77359400, 0xc002ff0980, 0x3569778, 0x0, ...)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:196 +0x96
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.Run(0xc002bb2da8, 0xc0004b0060, 0xc002d72f70, 0xc002aba250)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:240 +0x958
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.NewControllerManagerCommand.func1(0xc002b80500, 0xc001bf82c0, 0x0, 0xb)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:101 +0x27c
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).execute(0xc002b80500, 0xc002b6cf00, 0xb, 0x10, 0xc002b80500, 0xc002b6cf00)
	/go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:760 +0x2ae
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc002b80500, 0x34801d1, 0x22, 0xc00204f7a0)
	/go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:846 +0x2ec
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:794
github.com/rancher/k3s/pkg/daemons/control.controllerManager.func1(0xc002b6cf00, 0xb, 0x10, 0xc002b80500)
	/go/src/github.com/rancher/k3s/pkg/daemons/control/server.go:121 +0xb2
created by github.com/rancher/k3s/pkg/daemons/control.controllerManager
	/go/src/github.com/rancher/k3s/pkg/daemons/control/server.go:119 +0x5cc
2019-12-24 04:01:25.365424 W | etcdserver: read-only range request "key:\"/registry/management.cattle.io/nodepools\" range_end:\"/registry/management.cattle.io/nodepoolt\" count_only:true " with result "range_response_count:0 size:8" took too long (2.424586974s) to execute
2019-12-24 04:01:25.365786 W | etcdserver: read-only range request "key:\"/registry/controllers\" range_end:\"/registry/controllert\" count_only:true " with result "range_response_count:0 size:6" took too long (2.549781675s) to execute



```
