### ISSUE TITLE
[rancher-python] rancher.ApiError in version 2.2.1

### ISSUE THREAD

**Issue by jjkoehorst** [rancher/rancher#19613]
As is mentioned in https://github.com/rancher/client-python/issues/10 and I wasn't sure if it would be picked up since it was created in a different repository...

Any solution for the API Error in the latest Rancher version?

```
venv/lib/python3.7/site-packages/requests/packages/urllib3/connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "rancher_manager.py", line 8, in <module>
    verify=False)
  File "/venv/lib/python3.7/site-packages/rancher.py", line 240, in __init__
    self._load_schemas()
  File "/venv/lib/python3.7/site-packages/rancher.py", line 359, in _load_schemas
    response = self._get_response(self._url)
  File "/venv/lib/python3.7/site-packages/rancher.py", line 310, in _get_response
    self._error(r.text)
  File "/venv/lib/python3.7/site-packages/rancher.py", line 299, in _error
    raise ApiError(self._unmarshall(text))
rancher.ApiError: (ApiError(...), 'API Error')
```

```
client = rancher.Client(url='https://xxx/v3',
                        access_key='xxx',
                        secret_key='xxx',
                        verify=False)
```

**Comment by daxmc99** [comment]
Hi @jjkoehorst,
Can you check that your API keys have not expired and that you are not using cluster scoped API keys? This error typically happens when a 401 error is returned by Rancher.

**Comment by rhinoceros** [comment]
```
client = rancher.Client(url='https://xxx/v3/cluster/c-1234',
                        access_key='xxx',
                        secret_key='xxx',
                        verify=False)
```
c-1234 is cluster id.

**Comment by stroebs** [comment]
For what it's worth, I've just encountered this error myself and cluster-scoped API keys simply don't work anymore.

Using Rancher v2.4.3 and even if I specify a cluster-specific URL using a cluster-scoped key, the same API error occurs. Creating a non-scoped key resolves the problem.
