### ISSUE TITLE
Rancher container crash after 1 minute

### ISSUE THREAD

**Issue by Mnbill** [rancher/rancher#20263]
**What kind of request is this (question/bug/enhancement/feature request):**
question, need help

**Steps to reproduce (least amount of steps as possible):**
start rancher container

**Result:**
my existing rancher container restart after 1 minute

**Other details that may be helpful:**
we have a rancher v2 container on docker 17.03.0 that was okay until 2 days.
I tried rancher v2.0.1 and v2.0.12 but still have the same problem

 
**Environment information**
- Rancher version: 'rancher / rancher' : Rancher v2.0.0
- Installation option (single install/HA): single

**Rancher container log**
```
WARNING: 2019/05/15 09:02:33 Failed to dial 127.0.0.1:2379: connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid"; please retry.
WARNING: 2019/05/15 09:02:33 Failed to dial 127.0.0.1:2379: connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid"; please retry.
WARNING: 2019/05/15 09:02:33 Failed to dial 127.0.0.1:2379: connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid"; please retry.
WARNING: 2019/05/15 09:02:33 Failed to dial 127.0.0.1:2379: connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid"; please retry.
2019/05/15 09:02:34 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version: x509: certificate has expired or is not yet valid
2019/05/15 09:02:34 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version: x509: certificate has expired or is not yet valid
2019/05/15 09:02:34 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version: x509: certificate has expired or is not yet valid
E0515 09:02:34.584108       1 reflector.go:205] github.com/rancher/rancher/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:73: Failed to list *api.LimitRange: the server was unable to return a response in the time allotted, but may still be processing the request (get limitranges)
E0515 09:02:34.584450       1 reflector.go:205] github.com/rancher/rancher/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:73: Failed to list *rbac.Role: the server was unable to return a response in the time allotted, but may still be processing the request (get roles.rbac.authorization.k8s.io)
E0515 09:02:34.584695       1 reflector.go:205] github.com/rancher/rancher/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:73: Failed to list *api.Pod: the server was unable to return a response in the time allotted, but may still be processing the request (get pods)
E0515 09:02:34.585270       1 reflector.go:205] github.com/rancher/rancher/vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/internalversion/factory.go:61: Failed to list *apiextensions.CustomResourceDefinition: the server was unable to return a response in the time allotted, but may still be processing the request (get customresourcedefinitions.apiextensions.k8s.io)
E0515 09:02:34.585557       1 reflector.go:205] github.com/rancher/rancher/vendor/k8s.io/client-go/informers/factory.go:73: Failed to list *v1.Endpoints: the server was unable to return a response in the time allotted, but may still be processing the request (get endpoints)
E0515 09:02:34.586080       1 reflector.go:205] github.com/rancher/rancher/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:73: Failed to list *api.ServiceAccount: the server was unable to return a response in the time allotted, but may still be processing the request (get serviceaccounts)
E0515 09:02:34.586103       1 reflector.go:205] github.com/rancher/rancher/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:73: Failed to list *rbac.ClusterRoleBinding: the server was unable to return a response in the time allotted, but may still be processing the request (get clusterrolebindings.rbac.authorization.k8s.io)
E0515 09:02:34.586375       1 reflector.go:205] github.com/rancher/rancher/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:73: Failed to list *api.ResourceQuota: the server was unable to return a response in the time allotted, but may still be processing the request (get resourcequotas)
E0515 09:02:34.587195       1 reflector.go:205] github.com/rancher/rancher/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:73: Failed to list *rbac.RoleBinding: the server was unable to return a response in the time allotted, but may still be processing the request (get rolebindings.rbac.authorization.k8s.io)
E0515 09:02:34.587550       1 reflector.go:205] github.com/rancher/rancher/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:73: Failed to list *api.Secret: the server was unable to return a response in the time allotted, but may still be processing the request (get secrets)
E0515 09:02:34.602235       1 reflector.go:205] github.com/rancher/rancher/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:73: Failed to list *storage.StorageClass: the server was unable to return a response in the time allotted, but may still be processing the request (get storageclasses.storage.k8s.io)
E0515 09:02:34.602936       1 reflector.go:205] github.com/rancher/rancher/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:73: Failed to list *rbac.ClusterRole: the server was unable to return a response in the time allotted, but may still be processing the request (get clusterroles.rbac.authorization.k8s.io)
E0515 09:02:34.602992       1 reflector.go:205] github.com/rancher/rancher/vendor/k8s.io/client-go/informers/factory.go:73: Failed to list *v1.Namespace: the server was unable to return a response in the time allotted, but may still be processing the request (get namespaces)
E0515 09:02:34.603061       1 reflector.go:205] github.com/rancher/rancher/vendor/k8s.io/client-go/informers/factory.go:73: Failed to list *v1.Service: the server was unable to return a response in the time allotted, but may still be processing the request (get services)
E0515 09:02:34.603079       1 reflector.go:205] github.com/rancher/rancher/vendor/k8s.io/kube-aggregator/pkg/client/informers/internalversion/factory.go:61: Failed to list *apiregistration.APIService: the server was unable to return a response in the time allotted, but may still be processing the request (get apiservices.apiregistration.k8s.io)
E0515 09:02:34.604283       1 reflector.go:205] github.com/rancher/rancher/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:73: Failed to list *api.PersistentVolume: the server was unable to return a response in the time allotted, but may still be processing the request (get persistentvolumes)
WARNING: 2019/05/15 09:02:34 Failed to dial 127.0.0.1:2379: connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid"; please retry.
E0515 09:02:35.561811       1 storage_rbac.go:172] unable to initialize clusterroles: the server was unable to return a response in the time allotted, but may still be processing the request (get clusterroles.rbac.authorization.k8s.io)
E0515 09:02:35.563196       1 client_ca_hook.go:78] Timeout: request did not complete within allowed duration
F0515 09:02:35.563217       1 hooks.go:133] PostStartHook "ca-registration" failed: unable to initialize client CA configmap: timed out waiting for the condition
goroutine 1284 [running]:
github.com/rancher/rancher/vendor/github.com/golang/glog.stacks(0xc420c79f00, 0xc429c24280, 0xa2, 0x138)
        /go/src/github.com/rancher/rancher/vendor/github.com/golang/glog/glog.go:766 +0xcf
github.com/rancher/rancher/vendor/github.com/golang/glog.(*loggingT).output(0xab3dbe0, 0xc400000003, 0xc424db9810, 0xa59b010, 0x8, 0x85, 0x0)
        /go/src/github.com/rancher/rancher/vendor/github.com/golang/glog/glog.go:717 +0x322
github.com/rancher/rancher/vendor/github.com/golang/glog.(*loggingT).printf(0xab3dbe0, 0x3, 0x4e6b067, 0x1b, 0xc424301f80, 0x2, 0x2)
        /go/src/github.com/rancher/rancher/vendor/github.com/golang/glog/glog.go:655 +0x14c
github.com/rancher/rancher/vendor/github.com/golang/glog.Fatalf(0x4e6b067, 0x1b, 0xc424301f80, 0x2, 0x2)
        /go/src/github.com/rancher/rancher/vendor/github.com/golang/glog/glog.go:1145 +0x67
github.com/rancher/rancher/vendor/k8s.io/apiserver/pkg/server.runPostStartHook(0x4e2d15c, 0xf, 0xc420752e60, 0xc424af8660, 0xc42010c5a0, 0xc420dfe240)
        /go/src/github.com/rancher/rancher/vendor/k8s.io/apiserver/pkg/server/hooks.go:133 +0x158
created by github.com/rancher/rancher/vendor/k8s.io/apiserver/pkg/server.(*GenericAPIServer).RunPostStartHooks
        /go/src/github.com/rancher/rancher/vendor/k8s.io/apiserver/pkg/server/hooks.go:112 +0x12d

```

**Comment by salamander-mh** [comment]
我也有这个错
```
E0516 03:13:09.042652       7 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0516 03:13:09.042825       7 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0516 03:13:09.043000       7 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0516 03:13:09.043100       7 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0516 03:13:09.043797       7 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
2019/05/16 03:13:53 [ERROR] Unknown error: pipeline.project.cattle.io "p-r2v88" not found
2019/05/16 03:17:26 [ERROR] Unknown error: pipeline.project.cattle.io "p-r2v88" not found

```

**Comment by sivarajp** [comment]
We have similar issue. Rancher 2.0.6. Anyone?

WARNING: 2019/05/16 21:13:37 Failed to dial 127.0.0.1:2379: connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid"; please retry.
2019/05/16 21:13:37 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version: x509: certificate has expired or is not yet valid
2019/05/16 21:13:37 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version: x509: certificate has expired or is not yet valid
WARNING: 2019/05/16 21:13:38 Failed to dial 127.0.0.1:2379: connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid"; please retry.
ç2019/05/16 21:13:38 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version: x509: certificate has expired or is not yet valid
2019/05/16 21:13:39 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version: x509: certificate has expired or is not yet valid
2019/05/16 21:13:39 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version: x509: certificate has expired or is not yet valid
WARNING: 2019/05/16 21:13:40 Failed to dial 127.0.0.1:2379: connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid"; please retry.
WARNING: 2019/05/16 21:13:40 Failed to dial 127.0.0.1:2379: connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid"; please retry.

**Comment by loganhz** [comment]
Close in favor https://github.com/rancher/rancher/issues/17441

**Comment by dhrp** [comment]
I ran into this very same issue; which I believe is not the same as #17441

The cause for me is that I had rebooted the host on which Rancher runs (single node installation). What then happened is that not the latest version booted, but one that was created over 12 months ago; and of that version the certificate must have expired. Shutting down this container and starting the one that was last running resolved this issue. 

The reason that this can happen is that (to be frank) the upgrade process for single node installs is a bit weird, and you easily get to have a list of docker images which you do not dare to delete because they mount from each other and so forth.

**Comment by vincent99** [comment]
The docs tell you to 

1) run with `--restart=unless-stopped` to begin with (not `always`)
2) stop the old container as part of upgrading, (which would then make it not auto-restart later even if you keep it around)
3) delete the old container entirely at the end of the upgrade.

If you get in this situation, you're not following the installation /upgrade instructions at all.
