### ISSUE TITLE
java.lang.NullPointerException seen in logs every few seconds.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2062]
Server version - V0.38.0-rc1

Rancher server with 3 hosts
Deployed few services.

Following java.lang.NullPointerException seen constantly in logs:

```
2015-09-17 16:43:43,849 INFO  [ce26c0b6-cb20-4ad1-b15c-1e84c4707d2d:23447] [credential:23086] [credential.activate] [] [ecutorService-4] [c.p.e.p.i.DefaultProcessInstanceImpl] Changing state [activating->active] on [credential:23086] 
2015-09-17 16:43:43,860 DEBUG [:] [] [] [] [ecutorService-4] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [DONE] process [credential.activate:23447] on resource [23086] 
2015-09-17 16:43:44,178 ERROR [:] [] [] [] [ecutorService-7] [o.a.c.m.context.NoExceptionRunnable ] Uncaught exception java.lang.NullPointerException: null
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1010) ~[na:1.7.0_79]
	at io.cattle.platform.docker.machine.launch.GenericServiceLauncher.doRun(GenericServiceLauncher.java:167) ~[cattle-docker-machine-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]

2015-09-17 16:43:46,215 DEBUG [:] [] [] [] [ecutorService-3] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [credential.create:23448] on resource [23087] 
```

**Comment by sangeethah** [comment]
Tested with build from master  - Sep 18 
This issue is not seen any more.
