### ISSUE TITLE
[Image pull] - When invalid image name is provided , rancher-compose does not report failure to pull image.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2070]
Server version - Build from master

When invalid image name is provided , rancher-compose does not report failure to pull image.
It simply says pulling image and the process quits.

Also pulling of images failed in 2 hosts . But the output of rancher-compose shows that pulling was attempted in only 1 host:

root@sangee01:/home/sangeethahariharan1/rancher-compose-v0.4.0-rc1# ./rancher-compose -f dc1.yml pull
INFO[0001] Pulling tresane on sangeemaster-10acre-3     
root@sangee01:/home/sangeethahariharan1/rancher-compose-v0.4.0-rc1#

This kind of error message was seen in 2 hosts.

```
2015-09-18 00:46:00,821 INFO agent [139886657888336] [utils.py:430] Response: {"name": "reply.4720179850792048462", "transitioningProgress": null, "resourceType": "resourcePull", "resourceId": null, "id": "9c20c750-303b-4457-bff3-ce1a6c025e76", "transitioningMessage": "Pulling repository docker.io/library/tresane", "time": 1442537160000, "previousNames": ["compute.instance.pull"], "transitioning": "yes", "data": {}, "previousIds": ["9ee884f6-a17d-4508-a2dc-813830e158df"]} [0.00551295280457] seconds 
2015-09-18 00:46:01,002 INFO agent [139886657888336] [utils.py:430] worker34 : Done request 9ee884f6-a17d-4508-a2dc-813830e158df for compute.instance.pull [0.655710935593] seconds 
2015-09-18 00:46:01,002 ERROR agent [139886657888336] [event.py:111] 33b04765-7015-404b-b1cb-47648a228174 : Unknown error 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 94, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 34, in execute
    return method(req=req, **req.data.__dict__)
  File "/var/lib/cattle/pyagent/cattle/compute/__init__.py", line 77, in instance_pull
    result = self._do_instance_pull(instancePull, progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 828, in _do_instance_pull
    DockerPool.image_pull(pull_info.image, progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/storage.py", line 96, in image_pull
    return DockerPool()._do_image_activate(image, None, progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/storage.py", line 158, in _do_image_activate
    message))
ImageValidationError: Image [tresane:latest] failed to pull : Error: image library/tresane:latest not found
2015-09-18 00:46:01,012 INFO agent [139886657888336] [utils.py:430] Response: {"name": "reply.4720179850792048462", "resourceType": "resourcePull", "resourceId": null, "id": "6eabfdb2-08d5-45e2-987a-1a8bb13272a4", "transitioningInternalMessage": "33b04765-7015-404b-b1cb-47648a228174 : Image [tresane:latest] failed to pull : Error: image library/tresane:latest not found", "time": 1442537161000, "previousNames": ["compute.instance.pull"], "transitioning": "error", "data": {}, "previousIds": ["9ee884f6-a17d-4508-a2dc-813830e158df"]} [0.00901293754578] seconds 
(END)
```

**Comment by sangeethah** [comment]
Tested with rancher-compose version  - v0.4.0. 

When image pull fails for any reason , rancher-compose pull reports failure message that was encountered when attempting to pull the image on host

```
root@sangee01:/home/sangeethahariharan1/latest# ./rancher-compose -f dcprivate.yml pull
INFO[0001] Checking for sangeetha/test1 on sangee38rc3again-10acre-1... 
INFO[0001] Checking for sangeetha/test1 on sangee38rc3again-10acre-2... 
INFO[0001] Checking for sangeetha/test1 on sangee38rc3again-10acre-3... 
INFO[0001] Checking for sangeetha/test1 on sangee38rc3again-10acre-2: 4aa55392-fc85-421d-b295-64eaa19a0ea3 : Image [sangeetha/test1:latest] failed to pull : Error: image sangeetha/test1:latest not found 
INFO[0001] Checking for sangeetha/test1 on sangee38rc3again-10acre-3: dfcbfac9-2036-4107-bdff-8be1997ccfb3 : Image [sangeetha/test1:latest] failed to pull : Error: image sangeetha/test1:latest not found 
INFO[0001] Checking for sangeetha/test1 on sangee38rc3again-10acre-1: 498e17b7-d3eb-467c-92a4-fb2f7b03099f : Image [sangeetha/test1:latest] failed to pull : Error: image sangeetha/test1:latest not found 
ERRO[0001] Failed Pulling testprivatereg : Pull failed on one of the hosts 
ERRO[0001] Failed to start: testprivatereg : Pull failed on one of the hosts 
FATA[0001] Pull failed on one of the hosts   
```
