### ISSUE TITLE
Panic after provisioning azure cluster with cloud provider set

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#20767]
Version: Master
K8s: v1.13.5 

Steps: 

1. Provision a Azure cluster  with cloud provider setup.
Observed a Panic few minutes after provisioning the cluster

```
2019/06/10 23:35:53 [INFO] cluster [c-8j7n7] provisioning: [network] Setting up network plugin: canal
2019/06/10 23:35:53 [INFO] cluster [c-8j7n7] provisioning: [addons] Saving ConfigMap for addon rke-network-plugin to Kubernetes
2019/06/10 23:35:53 [INFO] cluster [c-8j7n7] provisioning: [addons] Successfully saved ConfigMap for addon rke-network-plugin to Kubernetes
2019/06/10 23:35:53 [INFO] cluster [c-8j7n7] provisioning: [addons] Executing deploy job rke-network-plugin
2019/06/10 23:36:03 [INFO] cluster [c-8j7n7] provisioning: [addons] Setting up kube-dns
2019/06/10 23:36:03 [INFO] cluster [c-8j7n7] provisioning: [addons] Saving ConfigMap for addon rke-kube-dns-addon to Kubernetes
2019/06/10 23:36:03 [INFO] cluster [c-8j7n7] provisioning: [addons] Successfully saved ConfigMap for addon rke-kube-dns-addon to Kubernetes
2019/06/10 23:36:03 [INFO] cluster [c-8j7n7] provisioning: [addons] Executing deploy job rke-kube-dns-addon
W0610 23:36:15.286085       7 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.Node ended with: too old resource version: 407655 (418924)
2019/06/10 23:36:21 [INFO] cluster [c-8j7n7] provisioning: [addons] kube-dns deployed successfully
2019/06/10 23:36:21 [INFO] cluster [c-8j7n7] provisioning: [dns] DNS provider kube-dns deployed successfully
2019/06/10 23:36:21 [INFO] cluster [c-8j7n7] provisioning: [addons] Setting up Metrics Server
2019/06/10 23:36:21 [INFO] cluster [c-8j7n7] provisioning: [addons] Saving ConfigMap for addon rke-metrics-addon to Kubernetes
2019/06/10 23:36:21 [INFO] cluster [c-8j7n7] provisioning: [addons] Successfully saved ConfigMap for addon rke-metrics-addon to Kubernetes
2019/06/10 23:36:21 [INFO] cluster [c-8j7n7] provisioning: [addons] Executing deploy job rke-metrics-addon
2019/06/10 23:36:31 [INFO] cluster [c-8j7n7] provisioning: [addons] Metrics Server deployed successfully
2019/06/10 23:36:31 [INFO] cluster [c-8j7n7] provisioning: [ingress] Setting up nginx ingress controller
2019/06/10 23:36:31 [INFO] cluster [c-8j7n7] provisioning: [addons] Saving ConfigMap for addon rke-ingress-controller to Kubernetes
2019/06/10 23:36:31 [INFO] cluster [c-8j7n7] provisioning: [addons] Successfully saved ConfigMap for addon rke-ingress-controller to Kubernetes
2019/06/10 23:36:31 [INFO] cluster [c-8j7n7] provisioning: [addons] Executing deploy job rke-ingress-controller
2019/06/10 23:36:41 [INFO] cluster [c-8j7n7] provisioning: [ingress] ingress controller nginx deployed successfully
2019/06/10 23:36:41 [INFO] cluster [c-8j7n7] provisioning: [addons] Setting up user addons
2019/06/10 23:36:41 [INFO] cluster [c-8j7n7] provisioning: [addons] no user addons defined
2019/06/10 23:36:41 [INFO] cluster [c-8j7n7] provisioning: Finished building Kubernetes cluster successfully
2019/06/10 23:36:42 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/06/10 23:36:47 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:10097
2019/06/10 23:36:47 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/06/10 23:36:47 [INFO] Provisioned cluster [c-8j7n7]
I0610 23:36:47.289254       7 http.go:110] HTTP2 has been explicitly disabled
2019/06/10 23:36:47 [INFO] Creating user for principal system://c-8j7n7
2019/06/10 23:36:47 [INFO] Creating globalRoleBindings for u-ci5cs2djms
2019/06/10 23:36:47 [INFO] Creating new GlobalRoleBinding for GlobalRoleBinding grb-wg9wd
2019/06/10 23:36:47 [INFO] [mgmt-auth-grb-controller] Creating clusterRoleBinding for globalRoleBinding grb-wg9wd for user u-ci5cs2djms with role cattle-globalrole-user
2019/06/10 23:36:47 [INFO] Registering project network policy
2019/06/10 23:36:47 [INFO] registering podsecuritypolicy cluster handler for cluster c-8j7n7
2019/06/10 23:36:47 [INFO] registering podsecuritypolicy project handler for cluster c-8j7n7
2019/06/10 23:36:47 [INFO] registering podsecuritypolicy namespace handler for cluster c-8j7n7
2019/06/10 23:36:47 [INFO] registering podsecuritypolicy serviceaccount handler for cluster c-8j7n7
2019/06/10 23:36:47 [INFO] registering podsecuritypolicy template handler for cluster c-8j7n7
2019/06/10 23:36:47 [INFO] Creating token for user u-ci5cs2djms
2019/06/10 23:36:47 [INFO] [mgmt-auth-crtb-controller] Creating clusterRoleBinding for membership in cluster c-8j7n7 for subject u-ci5cs2djms
2019/06/10 23:36:47 [INFO] [mgmt-auth-crtb-controller] Creating roleBinding for subject u-ci5cs2djms with role cluster-owner in namespace 
2019/06/10 23:36:47 [INFO] [mgmt-auth-crtb-controller] Creating roleBinding for subject u-ci5cs2djms with role cluster-owner in namespace 
2019/06/10 23:36:47 [INFO] [mgmt-auth-crtb-controller] Creating roleBinding for subject u-ci5cs2djms with role cluster-owner in namespace 
2019/06/10 23:36:47 [INFO] Registering monitoring for cluster "c-8j7n7"
2019/06/10 23:36:47 [INFO] Registering istio for cluster "c-8j7n7"
2019/06/10 23:36:47 [INFO] Creating CRD clusterauthtokens.cluster.cattle.io
2019/06/10 23:37:02 [ERROR] cluster.management.cattle.io "c-8j7n7" not found
panic: creating CRD store etcdserver: request timed out

goroutine 10803641 [running]:
github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd.(*Factory).BatchCreateCRDs.func1(0xc00daa9340, 0xc00daa9360, 0x2, 0x2, 0xc0044345a0, 0x6ae85c0, 0x420a300, 0xc022f849c0, 0x3abb40c, 0x4)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd/init.go:65 +0x2d9
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd.(*Factory).BatchCreateCRDs
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd/init.go:50 +0xce

```

The setup had 4 other clusters.

**Comment by loganhz** [comment]
Is it a custom cluster or node driver cluster?

**Comment by deniseschannon** [comment]
This is a node driver cluster.

**Comment by cjellick** [comment]
this is not cuased by any recent change. it is long standing code where the crd function is panicing but it should instead just return an error and the caller should know how to receover

**Comment by cjellick** [comment]
this particular instance can be caused simply by some intermittent error talking to the downstream cluster's k8s api

**Comment by deniseschannon** [comment]
@superseb is this related to the panic we saw with RKE templates?

**Comment by superseb** [comment]
No, this panic has been fixed in https://github.com/rancher/norman/pull/354

**Comment by sowmyav27** [comment]
**Verified on 2.4.3-rc6**

- Deploy a cloud provider enabled Azure cluster - 1 etcd, 1 control and 2 worker nodes
- Cluster is deployed successfully.
- No panic seen in the rancher server logs
