### ISSUE TITLE
Rancher crashing every 5 minutes with SIGSEGV in etcdbackup

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#20964]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
unknown

**Result:**
Rancher server is crashing about every 5 minutes. Logs:
```
2019/06/18 23:26:41 [ERROR] CatalogController system-library [catalog] failed with : Timeout in HTTP GET to [https://git.rancher.io/system-charts/index.yaml], did not respond in 30s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2accef2]

goroutine 6313 [running]:
github.com/rancher/rancher/pkg/controllers/management/etcdbackup.isRecurringBackupEnabled(...)
        /go/src/github.com/rancher/rancher/pkg/controllers/management/etcdbackup/etcdbackup.go:439
github.com/rancher/rancher/pkg/controllers/management/etcdbackup.shouldBackup(0xc0161af680, 0x0)
        /go/src/github.com/rancher/rancher/pkg/controllers/management/etcdbackup/etcdbackup.go:417 +0xb2
github.com/rancher/rancher/pkg/controllers/management/etcdbackup.(*Controller).doClusterBackupSync(0xc00e925680, 0xc0161af680, 0xc01f973f58, 0x1)
        /go/src/github.com/rancher/rancher/pkg/controllers/management/etcdbackup/etcdbackup.go:158 +0x6d
github.com/rancher/rancher/pkg/controllers/management/etcdbackup.(*Controller).clusterBackupSync(0xc00e925680, 0x41f1ba0, 0xc014c239c0, 0x45d964b800, 0xc00e925680, 0xc01bf6b380)
        /go/src/github.com/rancher/rancher/pkg/controllers/management/etcdbackup/etcdbackup.go:145 +0x14c
created by github.com/rancher/rancher/pkg/controllers/management/etcdbackup.Register
        /go/src/github.com/rancher/rancher/pkg/controllers/management/etcdbackup/etcdbackup.go:69 +0x69f
2019/06/18 23:26:53 [INFO] Rancher version v2.2.4 is starting
```

**Other details that may be helpful:**
Server was upgraded from v2.0 -> v2.2.0 -> v2.2.4

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.2.4
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
1.13.1
```

- Docker version (use `docker version`):

```
# docker version
Client:
Version:           18.09.3
API version:       1.39
Go version:        go1.10.8
Git commit:        774a1f4
Built:             Thu Feb 28 06:33:21 2019
OS/Arch:           linux/amd64
Experimental:      false
 
Server: Docker Engine - Community
Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:47:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by sowmyav27** [comment]
Reproduce the issue on an upgrade from `2.2.0-alpha6` to `2.2.4`

```
2019/06/20 21:23:16 [INFO] cluster [c-dr82d] provisioning: [remove/rke-log-linker] Successfully removed container on host [165.22.37.100]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2accef2]

goroutine 16542 [running]:
github.com/rancher/rancher/pkg/controllers/management/etcdbackup.isRecurringBackupEnabled(...)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/etcdbackup/etcdbackup.go:439
github.com/rancher/rancher/pkg/controllers/management/etcdbackup.shouldBackup(0xc018e29200, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/etcdbackup/etcdbackup.go:417 +0xb2
github.com/rancher/rancher/pkg/controllers/management/etcdbackup.(*Controller).doClusterBackupSync(0xc00956d200, 0xc018e29200, 0xc0172c3f58, 0x1)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/etcdbackup/etcdbackup.go:158 +0x6d
github.com/rancher/rancher/pkg/controllers/management/etcdbackup.(*Controller).clusterBackupSync(0xc00956d200, 0x41f1ba0, 0xc009137c80, 0x45d964b800, 0xc00956d200, 0xc00deb9fc0)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/etcdbackup/etcdbackup.go:145 +0x14c
created by github.com/rancher/rancher/pkg/controllers/management/etcdbackup.Register
	/go/src/github.com/rancher/rancher/pkg/controllers/management/etcdbackup/etcdbackup.go:69 +0x69f
```

**Comment by sowmyav27** [comment]
Issue is seen in v2.2.4, when the cluster does not have 
```
backupConfig:
    "enabled": true
```
In 2.2.4, edit the cluster CRD, and delete `enabled: true` for backup config. And every five minutes, you will see the rancher server restart with the error mentioned in [https://github.com/rancher/rancher/issues/20964#issuecomment-504212269](url)

Verified on `rancher:master`.
Edit cluster CRD, and delete `enabled: true` for backup config. Rancher server is up and running fine. No panics are seen.
