### ISSUE TITLE
Rancher server crashing SIGSEGV: segmentation violation - EncodeCertPEM

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#21056]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Unknown

**Result:**
Rancher is continuously crashing with the following error:
```
2019-06-21T16:44:59.951887502Z 2019/06/21 16:44:59 [ERROR] cluster [c-c5zq7] provisioning: Unsupported Docker version found [17.09.1-ce], supported versions are [1.11.x 1.12.x 1.13.x 17.03.x 18.06.x 18.09.x]
2019-06-21T16:44:59.969592576Z 2019/06/21 16:44:59 [INFO] cluster [c-c5zq7] provisioning: [network] No hosts added existing cluster, skipping port check
2019-06-21T16:44:59.988224601Z 2019/06/21 16:44:59 [INFO] cluster [c-c5zq7] provisioning: [certificates] Deploying kubernetes certificates to Cluster nodes
2019-06-21T16:45:00.918180578Z 2019/06/21 16:45:00 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:10542
2019-06-21T16:45:05.417053070Z 2019/06/21 16:45:05 [INFO] cluster [c-c5zq7] provisioning: [reconcile] Rebuilding and updating local kube config
2019-06-21T16:45:05.419889067Z I0621 16:45:05.419715       8 http.go:110] HTTP2 has been explicitly disabled
2019-06-21T16:45:05.425344472Z panic: runtime error: invalid memory address or nil pointer dereference
2019-06-21T16:45:05.425382273Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x94787d]
2019-06-21T16:45:05.425391795Z
2019-06-21T16:45:05.425398545Z goroutine 5176 [running]:
2019-06-21T16:45:05.425405320Z github.com/rancher/rancher/vendor/k8s.io/client-go/util/cert.EncodeCertPEM(0x0, 0xc003778bd0, 0x4197c40, 0x6b07da0)
2019-06-21T16:45:05.425412856Z   /go/src/github.com/rancher/rancher/vendor/k8s.io/client-go/util/cert/pem.go:69 +0x4d
2019-06-21T16:45:05.425420143Z github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.reconcileEtcd(0x41f1c60, 0xc004fd95f0, 0xc002b24000, 0xc0010cdb00, 0xc000a41760, 0x0, 0x0)
2019-06-21T16:45:05.425427702Z   /go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/reconcile.go:175 +0x130
2019-06-21T16:45:05.425434944Z github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.ReconcileCluster(0x41f1c60, 0xc004fd95f0, 0xc0010cdb00, 0xc002b24000, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0056083c0, ...)
2019-06-21T16:45:05.425442417Z   /go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/reconcile.go:43 +0x1ab
2019-06-21T16:45:05.425455384Z github.com/rancher/rancher/vendor/github.com/rancher/rke/cmd.ClusterUp(0x41f1c60, 0xc004fd95f0, 0xc000980100, 0xc000980110, 0xc0010788a0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2019-06-21T16:45:05.425463274Z   /go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cmd/up.go:133 +0x557
2019-06-21T16:45:05.425470258Z github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/rke.(*Driver).Update(0xc000ec1f40, 0x41f1c60, 0xc004fd95f0, 0xc0055dda00, 0xc004ca6500, 0x0, 0x0, 0x0)
2019-06-21T16:45:05.425477800Z   /go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/rke/rke_driver.go:192 +0x3d4
2019-06-21T16:45:05.425487925Z github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types.(*GrpcServer).Update(0xc004f524e0, 0x41f1c60, 0xc00598ae10, 0xc004fd9500, 0xc004f524e0, 0x80800, 0xc004da2ae8)
2019-06-21T16:45:05.425495782Z   /go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/rpc_server.go:52 +0x7c
2019-06-21T16:45:05.425602938Z github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types._Driver_Update_Handler(0x39667e0, 0xc004f524e0, 0x41f1c60, 0xc00598ae10, 0xc004d33420, 0x0, 0x0, 0x0, 0x60, 0x40c50b)
2019-06-21T16:45:05.425614805Z   /go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/drivers.pb.go:1454 +0x241
2019-06-21T16:45:05.425622330Z github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0015146e0, 0x420a360, 0xc00557d200, 0xc004467900, 0xc005818db0, 0x6acd9b8, 0x0, 0x0, 0x0)
2019-06-21T16:45:05.425649025Z   /go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:921 +0x7d1
2019-06-21T16:45:05.425657620Z github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0015146e0, 0x420a360, 0xc00557d200, 0xc004467900, 0x0)
2019-06-21T16:45:05.425667355Z   /go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:1143 +0x1308
2019-06-21T16:45:05.425844901Z github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc002fdd6b0, 0xc0015146e0, 0x420a360, 0xc00557d200, 0xc004467900)
2019-06-21T16:45:05.425861176Z   /go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:638 +0x9f
2019-06-21T16:45:05.425868472Z created by github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2019-06-21T16:45:05.425875324Z   /go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:636 +0xa1
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.2.4
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by alena1108** [comment]
As a part of the fix, document the state management flow. It will be useful for support when it comes to debugging the issues caused by inability to fetch the rke cluster state.

**Comment by superseb** [comment]
To verify using RKE:

- Create nodes and install Docker
- Create `cluster.yml` file containing nodes
- Run `rke up`
- Remove `cluster.rkestate` file
- Run `rke up`

**Comment by superseb** [comment]
To verify using Rancher:

- Create custom cluster and add nodes
- Run this script to remove fullstate from the secret for the cluster in Rancher: https://gist.github.com/superseb/28672111f54a632ee1ebdaafcc1de810 (usage is `bash remove_fullstate.sh cluster_name` where `cluster_name` is the name of the custom cluster you created)
- Trigger provisioning by editing something in the cluster via Edit as YAML (Cluster -> Edit -> Edit as YAML -> Change addon_job_timeout from 30 to 31 -> Save)
- Use `docker logs` on the `rancher/rancher` container to see it crash

**Comment by sowmyav27** [comment]
reproduced the panic using rke `v2.0.4`
Steps:

1. Create nodes and install Docker
2. Create cluster.yml file containing nodes
3. Run rke up
4. Remove cluster.rkestate file
5. Run rke up

**Result:**
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x197a7ad]

goroutine 1 [running]:
github.com/rancher/rke/vendor/github.com/urfave/cli.HandleAction.func1(0xc00053aca0)
	/go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/app.go:472 +0x278
panic(0x1f5cb00, 0x2f4b1b0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/rancher/rke/vendor/k8s.io/client-go/util/cert.EncodeCertPEM(0x0, 0xc0003fc510, 0x2334b50, 0x2f87540)
	/go/src/github.com/rancher/rke/vendor/k8s.io/client-go/util/cert/pem.go:69 +0x4d
github.com/rancher/rke/cluster.reconcileEtcd(0x2357440, 0xc00003e060, 0xc000176000, 0xc00044e900, 0xc0002e6690, 0x0, 0x0)
	/go/src/github.com/rancher/rke/cluster/reconcile.go:175 +0x130
github.com/rancher/rke/cluster.ReconcileCluster(0x2357440, 0xc00003e060, 0xc00044e900, 0xc000176000, 0x0, 0x0, 0x7ffeefbffc1a, 0x15, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rke/cluster/reconcile.go:43 +0x1ab
github.com/rancher/rke/cmd.ClusterUp(0x2357440, 0xc00003e060, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffeefbffc1a, 0x15, 0x0, ...)
	/go/src/github.com/rancher/rke/cmd/up.go:133 +0x557
github.com/rancher/rke/cmd.clusterUpFromCli(0xc000254a00, 0x0, 0x0)
	/go/src/github.com/rancher/rke/cmd/up.go:242 +0x582
reflect.Value.call(0x1ef2a80, 0x21c6498, 0x13, 0x2120479, 0x4, 0xc0004dec40, 0x1, 0x1, 0xc0000380c0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:447 +0x449
reflect.Value.Call(0x1ef2a80, 0x21c6498, 0x13, 0xc0004dec40, 0x1, 0x1, 0x5, 0x4, 0xc00043a5a8)
	/usr/local/go/src/reflect/value.go:308 +0xa4
github.com/rancher/rke/vendor/github.com/urfave/cli.HandleAction(0x1ef2a80, 0x21c6498, 0xc000254a00, 0x0, 0x0)
	/go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/app.go:481 +0x1fb
github.com/rancher/rke/vendor/github.com/urfave/cli.Command.Run(0x211feca, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x213177c, 0x14, 0x0, ...)
	/go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/command.go:186 +0x8f6
github.com/rancher/rke/vendor/github.com/urfave/cli.(*App).Run(0xc00008f500, 0xc000038100, 0x4, 0x4, 0x0, 0x0)
	/go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/app.go:235 +0x52e
main.mainErr(0x233d460, 0xc00000c018)
	/go/src/github.com/rancher/rke/main.go:56 +0xf9e
main.main()
```
Verified using `rancher:v2.2.5`
**Steps taken:**

1. Create custom cluster and add nodes
2. Run the script to remove fullstate from the secret for the cluster in Rancher
3. Trigger provisioning by editing something in the cluster via Edit as YAML (Cluster -> Edit -> Edit as YAML -> Change addon_job_timeout from 30 to 31 -> Save)
4. Use docker logs on the rancher/rancher container to see it crash

**Result:**
In rancher logs - panic is seen.
```
2019/07/17 21:26:11 [INFO] cluster [c-hvh7v] provisioning: [remove/file-deployer] Successfully removed container on host [3.16.81.5]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9477cd]

goroutine 127570 [running]:
github.com/rancher/rancher/vendor/k8s.io/client-go/util/cert.EncodeCertPEM(0x0, 0xc004dd8270, 0x41c4e70, 0x6b3ce00)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/client-go/util/cert/pem.go:69 +0x4d
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.reconcileEtcd(0x421efe0, 0xc019552270, 0xc016823600, 0xc010caf200, 0xc010f5e2c0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/reconcile.go:175 +0x130
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.ReconcileCluster(0x421efe0, 0xc019552270, 0xc010caf200, 0xc016823600, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0197cbb30, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/reconcile.go:43 +0x1ab
github.com/rancher/rancher/vendor/github.com/rancher/rke/cmd.ClusterUp(0x421efe0, 0xc019552270, 0xc0072de020, 0xc0072de030, 0xc0118c0520, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cmd/up.go:133 +0x557
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/rke.(*Driver).Update(0xc0011263c0, 0x421efe0, 0xc019552270, 0xc00f344410, 0xc01832cf40, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/rke/rke_driver.go:192 +0x3d4
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types.(*GrpcServer).Update(0xc00e414780, 0x421efe0, 0xc019576090, 0xc0195521b0, 0xc00e414780, 0x0, 0xc006b9dae8)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/rpc_server.go:52 +0x7c
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types._Driver_Update_Handler(0x3976200, 0xc00e414780, 0x421efe0, 0xc019576090, 0xc0197323f0, 0x0, 0x0, 0x0, 0xc011657c70, 0x3ac9443)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/drivers.pb.go:1454 +0x241
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc011524c60, 0x4237740, 0xc0196e0600, 0xc018308a00, 0xc015037f50, 0x6b029d8, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:921 +0x7d1
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).handleStream(0xc011524c60, 0x4237740, 0xc0196e0600, 0xc018308a00, 0x0)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:1143 +0x1308
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc015048660, 0xc011524c60, 0x4237740, 0xc0196e0600, 0xc018308a00)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:638 +0x9f
created by github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:636 +0xa1
```

**Comment by patrick0057** [comment]
Workaround for anyone hitting this before the fix has been released.  You need to copy certificates from /etc/kubernetes/ssl/ to /etc/kubernetes/.tmp/

If you are on CoreOS or RancherOS then you would need to copy the certificates from /opt/rke/etc/kubernetes/ssl/ to /opt/rke/etc/kubernetes/.tmp/

You should only need to do this one one node for the downstream cluster, preferably etcd,controlplane nodes however if that doesn't help then do it on other nodes.
