### ISSUE TITLE
[gdapi-python] Support for Python 3

### ISSUE THREAD

**Issue by andrefreitas** [rancher/rancher#2106]
In Python 3 I get the following error:

```
gdapi
```

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/gdapi", line 9, in <module>
    load_entry_point('gdapi-python==0.5.1', 'console_scripts', 'gdapi')()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pkg_resources/__init__.py", line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2630, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2310, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/gdapi.py", line 48
    print fn.__name__, repr(ret)
           ^
SyntaxError: invalid syntax
```

Prints changed in Python 3. You can use https://docs.python.org/2/library/2to3.html to help the code migration, although is not 100% efficient.

**Comment by nhumrich** [comment]
+1
