### ISSUE TITLE
Offline install, CoreOS 766 and 801 no stats?

### ISSUE THREAD

**Issue by clemenko** [rancher/rancher#2124]
I was able to setup Rancher v0.38.0 on an air-gapped network on CoreOS. Everything works except the stats on CoreOS 766, and 801. I know this are in the alpha channel of CoreOS. Has CoreOS 766/801 been tested? Shoud I deploy with v0.38.1?

**Comment by deniseschannon** [comment]
There were only some minor UI changes in v0.38.1 that included some stat updates, but no one has tested CoreOS. Could you test with v0.38.1?

**Comment by clemenko** [comment]
I will test it tonight on my GCE setup.

**Comment by clemenko** [comment]
From an online install with CoreOS 766 on GCE, v0.38.1 I am still seeing the stats issue.
![screen shot 2015-09-23 at 4 53 48 pm](https://cloud.githubusercontent.com/assets/3177276/10058517/dc3d631c-6213-11e5-82aa-b0b0a1a29162.jpg)
![screen shot 2015-09-23 at 4 54 10 pm](https://cloud.githubusercontent.com/assets/3177276/10058521/df09f4c0-6213-11e5-87a6-79e8e4a9cb94.jpg)

**Comment by cloudnautique** [comment]
It looks like cAdvisor is panicking on startup. That means we aren't able to get stats for the graphs or disks. Need to dig into it.

**Comment by jmreicha** [comment]
+1 I am seeing this infinite connecting behavior as well on CoreOS stable (766.5.0).

I pulled some of the logs from the `rancher-agent` container on one of the servers if it helps.

```
2015-11-05T13:14:43.953434046Z I1105 13:14:43.953319 22059 storagedriver.go:100] No backend storage selected
2015-11-05T13:14:43.953477230Z I1105 13:14:43.953385 22059 storagedriver.go:102] Caching stats in memory for 2m0s
2015-11-05T13:14:43.953719843Z I1105 13:14:43.953448 22059 manager.go:127] cAdvisor running in container: "/system.slice/docker-ff72857caf3a58c9c7c234411e679d2b852d73c0393d8e7029903f2834ab8934.scope"
2015-11-05T13:14:43.954286036Z I1105 13:14:43.953988 22059 fs.go:93] Filesystem partitions: map[/dev/xvda9:{mountpoint:/ major:202 minor:9} /dev/xvda3:{mountpoint:/usr major:202 minor:3} /dev/xvda6:{mountpoint:/usr/share/oem major:202 minor:6}]
2015-11-05T13:14:43.958889062Z fatal error: unexpected signal during runtime execution
2015-11-05T13:14:43.958914142Z [signal 0xb code=0x1 addr=0x0 pc=0x0]
2015-11-05T13:14:43.958924746Z
2015-11-05T13:14:43.958933075Z runtime stack:
2015-11-05T13:14:43.958941740Z runtime.gothrow(0xb9f4d0, 0x2a)
2015-11-05T13:14:43.958956689Z 	/usr/src/go/src/runtime/panic.go:503 +0x8e
2015-11-05T13:14:43.958965930Z runtime.sigpanic()
2015-11-05T13:14:43.958974417Z 	/usr/src/go/src/runtime/sigpanic_unix.go:14 +0x5e
2015-11-05T13:14:43.958982966Z
2015-11-05T13:14:43.958991837Z goroutine 18 [syscall, locked to thread]:
2015-11-05T13:14:43.959000609Z runtime.cgocall_errno(0x401930, 0xc208018cd0, 0x0)
2015-11-05T13:14:43.959015367Z 	/usr/src/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc208018c90 sp=0xc208018c68
2015-11-05T13:14:43.959025026Z net._C2func_getaddrinfo(0x7fbd800008c0, 0x0, 0xc208018dc8, 0xc208018d18, 0x0, 0x0, 0x0)
2015-11-05T13:14:43.959033889Z 	/usr/src/go/src/net/:26 +0x55 fp=0xc208018cd0 sp=0xc208018c90
2015-11-05T13:14:43.959043040Z net.cgoLookupIPCNAME(0xc2081184a0, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2015-11-05T13:14:43.959052381Z 	/usr/src/go/src/net/cgo_unix.go:96 +0x1c5 fp=0xc208018e00 sp=0xc208018cd0
2015-11-05T13:14:43.959081069Z net.cgoLookupIP(0xc2081184a0, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc208000120)
2015-11-05T13:14:43.959090983Z 	/usr/src/go/src/net/cgo_unix.go:148 +0x65 fp=0xc208018e58 sp=0xc208018e00
2015-11-05T13:14:43.959100031Z net.lookupIP(0xc2081184a0, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0)
2015-11-05T13:14:43.959108568Z 	/usr/src/go/src/net/lookup_unix.go:64 +0x5f fp=0xc208018ea0 sp=0xc208018e58
2015-11-05T13:14:43.959142437Z net.func·026(0x0, 0x0, 0x0, 0x0)
2015-11-05T13:14:43.959154715Z 	/usr/src/go/src/net/lookup.go:79 +0x55 fp=0xc208018f08 sp=0xc208018ea0
2015-11-05T13:14:43.959171167Z net.(*singleflight).doCall(0x1112970, 0xc208130240, 0xc2081184a0, 0x18, 0xc208134050)
2015-11-05T13:14:43.959180352Z 	/usr/src/go/src/net/singleflight.go:91 +0x2f fp=0xc208018fb8 sp=0xc208018f08
2015-11-05T13:14:43.959188854Z runtime.goexit()
2015-11-05T13:14:43.959197383Z 	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208018fc0 sp=0xc208018fb8
2015-11-05T13:14:43.959206244Z created by net.(*singleflight).DoChan
2015-11-05T13:14:43.959214749Z 	/usr/src/go/src/net/singleflight.go:84 +0x42b
2015-11-05T13:14:43.959223068Z
2015-11-05T13:14:43.959231030Z goroutine 1 [select]:
2015-11-05T13:14:43.959239721Z net/http.(*Transport).getConn(0xc2080661b0, 0xc208035860, 0x0, 0xb60550, 0x4, 0xc2081184a0, 0x1b, 0x0, 0x0, 0x0)
2015-11-05T13:14:43.959248285Z 	/usr/src/go/src/net/http/transport.go:525 +0x608
2015-11-05T13:14:43.959257121Z net/http.(*Transport).RoundTrip(0xc2080661b0, 0xc208035860, 0xa, 0x0, 0x0)
2015-11-05T13:14:43.959270148Z 	/usr/src/go/src/net/http/transport.go:228 +0x4d4
2015-11-05T13:14:43.959279701Z google.golang.org/cloud/internal.(*UATransport).RoundTrip(0xc20802af70, 0xc208035860, 0xc208118480, 0x0, 0x0)
2015-11-05T13:14:43.959288786Z 	/source/build/src/github.com/google/cadvisor/Godeps/_workspace/src/google.golang.org/cloud/internal/cloud.go:47 +0x109
2015-11-05T13:14:43.959297681Z net/http.send(0xc208035790, 0x7fbd953abc10, 0xc20802af70, 0x1f, 0x0, 0x0)
2015-11-05T13:14:43.959306282Z 	/usr/src/go/src/net/http/client.go:219 +0x4fc
2015-11-05T13:14:43.959315035Z net/http.(*Client).send(0x1113420, 0xc208035790, 0x1f, 0x0, 0x0)
2015-11-05T13:14:43.959323202Z 	/usr/src/go/src/net/http/client.go:142 +0x15b
2015-11-05T13:14:43.959331498Z net/http.(*Client).doFollowingRedirects(0x1113420, 0xc208035790, 0xc08450, 0x0, 0x0, 0x0)
2015-11-05T13:14:43.959343184Z 	/usr/src/go/src/net/http/client.go:367 +0xb25
2015-11-05T13:14:43.959352107Z net/http.(*Client).Get(0x1113420, 0xb60550, 0x1f, 0x25, 0x0, 0x0)
2015-11-05T13:14:43.959360251Z 	/usr/src/go/src/net/http/client.go:299 +0xba
2015-11-05T13:14:43.959368607Z github.com/GoogleCloudPlatform/gcloud-golang/compute/metadata.OnGCE(0x0)
2015-11-05T13:14:43.959377598Z 	/source/build/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/GoogleCloudPlatform/gcloud-golang/compute/metadata/metadata.go:126 +0xa6
2015-11-05T13:14:43.959405203Z github.com/google/cadvisor/utils/cloudinfo.onGCE(0xe)
2015-11-05T13:14:43.959415202Z 	/source/build/src/github.com/google/cadvisor/utils/cloudinfo/gce.go:25 +0x1f
2015-11-05T13:14:43.959423880Z github.com/google/cadvisor/utils/cloudinfo.detectCloudProvider(0x0, 0x0)
2015-11-05T13:14:43.959432255Z 	/source/build/src/github.com/google/cadvisor/utils/cloudinfo/cloudinfo.go:52 +0x31
2015-11-05T13:14:43.959441308Z github.com/google/cadvisor/utils/cloudinfo.NewRealCloudInfo(0x0, 0x0)
2015-11-05T13:14:43.959449164Z 	/source/build/src/github.com/google/cadvisor/utils/cloudinfo/cloudinfo.go:34 +0x31
2015-11-05T13:14:43.959457585Z github.com/google/cadvisor/manager.getMachineInfo(0x7fbd953ac2c0, 0x1122fb8, 0x7fbd953ac430, 0xc2080fead0, 0x11135c0, 0x0, 0x0)
2015-11-05T13:14:43.959466714Z 	/source/build/src/github.com/google/cadvisor/manager/machine.go:277 +0x82e
2015-11-05T13:14:43.959476218Z github.com/google/cadvisor/manager.New(0xc2080d6500, 0x7fbd953ac2c0, 0x1122fb8, 0x0, 0x0, 0x0, 0x0)
2015-11-05T13:14:43.959485918Z 	/source/build/src/github.com/google/cadvisor/manager/manager.go:151 +0x5d0
2015-11-05T13:14:43.959495414Z main.main()
2015-11-05T13:14:43.959501503Z 	/source/build/src/github.com/google/cadvisor/cadvisor.go:69 +0x454
2015-11-05T13:14:43.959506697Z
2015-11-05T13:14:43.959511464Z goroutine 5 [chan receive]:
2015-11-05T13:14:43.959516378Z github.com/golang/glog.(*loggingT).flushDaemon(0x1113980)
2015-11-05T13:14:43.959521270Z 	/source/build/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:839 +0x78
2015-11-05T13:14:43.959526327Z created by github.com/golang/glog.init·1
2015-11-05T13:14:43.959531266Z 	/source/build/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:406 +0x2a7
2015-11-05T13:14:43.959536347Z
2015-11-05T13:14:43.959540958Z goroutine 17 [syscall, locked to thread]:
2015-11-05T13:14:43.959545740Z runtime.goexit()
2015-11-05T13:14:43.959550439Z 	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1
2015-11-05T13:14:43.959555220Z
2015-11-05T13:14:43.959559774Z goroutine 11 [syscall]:
2015-11-05T13:14:43.959564540Z os/signal.loop()
2015-11-05T13:14:43.959569147Z 	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
2015-11-05T13:14:43.959573923Z created by os/signal.init·1
2015-11-05T13:14:43.959578661Z 	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35
2015-11-05T13:14:43.959583433Z
2015-11-05T13:14:43.959588107Z goroutine 13 [select]:
2015-11-05T13:14:43.959592801Z net.lookupIPDeadline(0xc2081184a0, 0x18, 0xecdcd4d44, 0x2a192731, 0x11135c0, 0x0, 0x0, 0x0, 0x0, 0x0)
2015-11-05T13:14:43.959598499Z 	/usr/src/go/src/net/lookup.go:82 +0x6cb
2015-11-05T13:14:43.959603290Z net.resolveInternetAddr(0xace950, 0x3, 0xc2081184a0, 0x1b, 0xecdcd4d44, 0x2a192731, 0x11135c0, 0x0, 0x0, 0x0, ...)
2015-11-05T13:14:43.959613268Z 	/usr/src/go/src/net/ipsock.go:285 +0x49b
2015-11-05T13:14:43.959618595Z net.resolveAddr(0xabff70, 0x4, 0xace950, 0x3, 0xc2081184a0, 0x1b, 0xecdcd4d44, 0x2a192731, 0x11135c0, 0x0, ...)
2015-11-05T13:14:43.959623672Z 	/usr/src/go/src/net/dial.go:110 +0x378
2015-11-05T13:14:43.959628512Z net.(*Dialer).Dial(0xc208032b00, 0xace950, 0x3, 0xc2081184a0, 0x1b, 0x0, 0x0, 0x0, 0x0)
2015-11-05T13:14:43.959633959Z 	/usr/src/go/src/net/dial.go:158 +0xf6
2015-11-05T13:14:43.959832665Z net.*Dialer.Dial·fm(0xace950, 0x3, 0xc2081184a0, 0x1b, 0x0, 0x0, 0x0, 0x0)
2015-11-05T13:14:43.959848737Z 	/usr/src/go/src/net/http/transport.go:38 +0x79
2015-11-05T13:14:43.959857244Z net/http.(*Transport).dial(0xc2080661b0, 0xace950, 0x3, 0xc2081184a0, 0x1b, 0x0, 0x0, 0x0, 0x0)
2015-11-05T13:14:43.959865817Z 	/usr/src/go/src/net/http/transport.go:479 +0x84
2015-11-05T13:14:43.959874029Z net/http.(*Transport).dialConn(0xc2080661b0, 0x0, 0xb60550, 0x4, 0xc2081184a0, 0x1b, 0x0, 0x0, 0x0)
2015-11-05T13:14:43.959882271Z 	/usr/src/go/src/net/http/transport.go:564 +0x1678
2015-11-05T13:14:43.959890414Z net/http.func·019()
2015-11-05T13:14:43.959898590Z 	/usr/src/go/src/net/http/transport.go:520 +0x42
2015-11-05T13:14:43.959906583Z created by net/http.(*Transport).getConn
2015-11-05T13:14:43.959915057Z 	/usr/src/go/src/net/http/transport.go:522 +0x335
```

**Comment by clemenko** [comment]
Rancher v0.46.0-rc1 works with CoreOS 845+

**Comment by jmreicha** [comment]
@clemenko Was there something released in that version of CoreOS that fixes it or was the fix in the newest release of Rancher?

**Comment by clemenko** [comment]
Rancher fixes it. I have not test v0.46.0-rc1 on older versions of coreos.

**Comment by jmreicha** [comment]
Awesome, I'll try it.  Thanks!

**Comment by sshipway** [comment]
Rancher v0.46.0 and v0.47.0 show statistics correctly on CoreOS 766.4.0 and on CoreOS 835.7.0

**Comment by deniseschannon** [comment]
Going to close this as @sshipway says stats are working correctly. Please open a new issue if you still see issues on the latest Rancher.
