### ISSUE TITLE
Panic observed after performing etcd restore from S3

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#21319]
Tested with build from master-head
K8s version : v1.14.3

Steps:
Create a custom cluster using S3 configuration with nodes as below:
N1 - control, worker
N2, N3, N4 - 3 etcds
Create a few workloads
Power off etcd nodes N2, N3, N4

After powering off the etcd nodes, the cluster changed to "Unavailable" state as expected.
Cluster was accessible through UI. The etcd nodes were deleted and new etcd nodes were added. Restore was performed from S3. Restore succeeded the first time.
Perform restore again. Rancher server exited with a panic as below:
```
2019/07/03 21:07:44 [INFO] Image [rancher/hyperkube:v1.14.3-rancher1] exists on host [18.191.135.148]
2019/07/03 21:07:44 [INFO] Starting container [kube-proxy] on host [18.191.135.148], try #1



2019/07/03 21:07:44 [INFO] [worker] Successfully started [kube-proxy] container on host [18.191.135.148]
2019/07/03 21:07:44 [INFO] [healthcheck] Start Healthcheck on service [kube-proxy] on host [18.191.135.148]
2019/07/03 21:07:46 [INFO] Updating workload [ingress-nginx/nginx-ingress-controller] with public endpoints [[{"nodeName":"c-t6krk:m-6da3b06c9597","addresses":["18.191.135.148"],"port":80,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-72x9z","allNodes":false},{"nodeName":"c-t6krk:m-6da3b06c9597","addresses":["18.191.135.148"],"port":443,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-72x9z","allNodes":false}]]
2019/07/03 21:07:47 [INFO] Handling backend connection request [c-t6krk]
2019/07/03 21:07:49 [INFO] [healthcheck] service [kube-proxy] on host [18.191.135.148] is healthy
2019/07/03 21:07:49 [INFO] Checking if image [rancher/rke-tools:v0.1.34] exists on host [18.191.135.148], try #1



2019/07/03 21:07:49 [INFO] Image [rancher/rke-tools:v0.1.34] exists on host [18.191.135.148]
2019/07/03 21:07:50 [INFO] Starting container [rke-log-linker] on host [18.191.135.148], try #1



2019/07/03 21:07:50 [INFO] [worker] Successfully started [rke-log-linker] container on host [18.191.135.148]
2019/07/03 21:07:50 [INFO] Removing container [rke-log-linker] on host [18.191.135.148], try rancher/rancher#1
2019/07/03 21:07:51 [INFO] [remove/rke-log-linker] Successfully removed container on host [18.191.135.148]
2019/07/03 21:08:22 [INFO] Handling backend connection request [c-t6krk:machine-p6gkt]
2019/07/03 21:08:22 [INFO] Handling backend connection request [c-t6krk:machine-44xtq]
2019/07/03 21:08:23 [INFO] Handling backend connection request [c-t6krk:machine-w49n9]
2019/07/03 21:08:28 [WARNING] Can't read container logs for container [kubelet]: error during connect: Get http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.24/containers/kubelet/logs?stderr=1&stdout=1&tail=1: failed to find Session for client c-t6krk:m-842142c4fa5f
2019/07/03 21:08:28 [WARNING] Can't read container logs for container [kubelet]: error during connect: Get http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.24/containers/kubelet/logs?stderr=1&stdout=1&tail=1: failed to find Session for client c-t6krk:m-842142c4fa5f
2019/07/03 21:08:28 [WARNING] Can't read container logs for container [kubelet]: error during connect: Get http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.24/containers/kubelet/logs?stderr=1&stdout=1&tail=1: failed to find Session for client c-t6krk:m-842142c4fa5f
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x275481a]

goroutine 271369 [running]:
github.com/rancher/rancher/vendor/github.com/rancher/rke/docker.GetContainerLogsStdoutStderr(0x4417380, 0xc00d045d10, 0xc00c462600, 0x3c8a1a4, 0x7, 0x3c83b28, 0x1, 0x43ca500, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/docker/docker.go:597 +0x2ba
github.com/rancher/rancher/vendor/github.com/rancher/rke/services.runHealthcheck(0x4417380, 0xc00d045d10, 0xc01c64d600, 0x3c8a1a4, 0x7, 0xc0077c8d10, 0xc005c08560, 0x1f, 0xc003e6a1b0, 0x3c889c6, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/services/healthcheck.go:66 +0x583
github.com/rancher/rancher/vendor/github.com/rancher/rke/services.runKubelet(0x4417380, 0xc00d045d10, 0xc01c64d600, 0xc0077c8d10, 0xc00476b3e0, 0x3c8a1a4, 0x7, 0xc002db9000, 0x1c, 0x20, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/services/kubelet.go:17 +0x191
github.com/rancher/rancher/vendor/github.com/rancher/rke/services.doDeployWorkerPlane(0x4417380, 0xc00d045d10, 0xc01c64d600, 0xc0077c8d10, 0xc00476b3e0, 0xc004bd7ad0, 0xc003e6a1b0, 0xc00aef00e0, 0x19, 0x1, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/services/workerplane.go:147 +0x19e
github.com/rancher/rancher/vendor/github.com/rancher/rke/services.doDeployWorkerPlaneHost(0x4417380, 0xc00d045d10, 0xc01c64d600, 0xc0077c8d10, 0xc00476b3e0, 0xc004bd7ad0, 0xc003e6a1b0, 0x37a4a00, 0xc00aef00e0, 0x19, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/services/workerplane.go:61 +0xc5
github.com/rancher/rancher/vendor/github.com/rancher/rke/services.RunWorkerPlane.func1(0x8, 0x3e0ecd0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/services/workerplane.go:29 +0x1e7
github.com/rancher/rancher/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc004bdc240, 0xc0060097a0)
	/go/src/github.com/rancher/rancher/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by github.com/rancher/rancher/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/go/src/github.com/rancher/rancher/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66

```

**Comment by soumyalj** [comment]
Tested with build from master-head from July 30
K8s version : v1.14.4

Steps:
Create a custom cluster using S3 configuration with nodes as below:
N1 - control, worker
N2, N3, N4 - 3 etcds
Create a few workloads
Power off etcd nodes N2, N3, N4

After powering off the etcd nodes, the cluster changed to "Unavailable" state as expected.
Cluster was accessible through UI. The etcd nodes were deleted and new etcd nodes were added. Restore was performed from S3. Restore succeeded the first time.
Perform restore again. There was no panic observed. 
A related etcd restore issue filed here:
https://github.com/rancher/rancher/issues/21857
