### ISSUE TITLE
Panic when creating a cluster with clusterTemplateRevision with only questions and no clusterConfig set.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#21329]
Rancher server version - from master - `f9aa0fe`

Steps to reproduce the problem:
Create a cluster template revision with with only questions and no clusterConfig set.
Cluster template revision gets created successfully .

Create a cluster using this cluster template revision.

Following panic seen in logs:
```
2019/07/04 03:08:30 [ERROR] Panic serving api request: 
goroutine 939962 [running]:
runtime/debug.Stack(0xc00885af60, 0x3599b20, 0x43c2c10)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP.func1(0x440d900, 0xc005586660)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:175 +0x67
panic(0x3599b20, 0x43c2c10)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/rancher/rancher/pkg/api/store/cluster.loadDataFromTemplate(0xc0069ea000, 0xc015908bd0, 0x0, 0xc0069ea000, 0x0)
	/go/src/github.com/rancher/rancher/pkg/api/store/cluster/cluster_store.go:215 +0x15e
github.com/rancher/rancher/pkg/api/store/cluster.(*Store).Create(0xc00468adc0, 0xc0158206c0, 0xc01d6de3c0, 0xc015908bd0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/api/store/cluster/cluster_store.go:172 +0x8dd
github.com/rancher/rancher/vendor/github.com/rancher/norman/store/wrapper.(*StoreWrapper).Create(0xc0046502a0, 0xc0158206c0, 0xc01d6de3c0, 0xc015908bd0, 0x0, 0xc01d6de3c0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/wrapper/wrapper.go:69 +0x1a9
github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler.CreateHandler(0xc0158206c0, 0x3e068e8, 0xc01d6de3c0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler/create.go:23 +0x81
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).handle(0xc000919600, 0x440d900, 0xc005586660, 0xc00da29400, 0xc0014dcd40, 0xc004818e10, 0xc00885b650)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:249 +0x2a2
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP(0xc000919600, 0x440d900, 0xc005586660, 0xc00da29400)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:180 +0x7d
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00310c230, 0x440d900, 0xc005586660, 0xc00da29400)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:159 +0xf1
github.com/rancher/rancher/pkg/auth/requests.authHeaderHandler.ServeHTTP(0x43d6ac0, 0xc0050c35c0, 0x43cbce0, 0xc00310c230, 0x43eafc0, 0xc003d02680, 0x43d6a80, 0xc0048194d0, 0x440d900, 0xc005586660, ...)
	/go/src/github.com/rancher/rancher/pkg/auth/requests/filter.go:110 +0x60d
github.com/rancher/rancher/pkg/websocket.websocketHandler.ServeHTTP(0x43ca600, 0xc00310ae80, 0x440d900, 0xc005586660, 0xc00da28f00)
	/go/src/github.com/rancher/rancher/pkg/websocket/handler.go:29 +0x6b
github.com/rancher/rancher/pkg/audit.auditHandler.ServeHTTP(0x43ca7c0, 0xc0010048f0, 0x0, 0x440d900, 0xc005586660, 0xc00da28f00)
	/go/src/github.com/rancher/rancher/pkg/audit/filter.go:31 +0x46a
github.com/rancher/rancher/server/responsewriter.ContentType.func1(0x43f8440, 0xc015908690, 0xc00da28f00)
	/go/src/github.com/rancher/rancher/server/responsewriter/content.go:33 +0x93
net/http.HandlerFunc.ServeHTTP(0xc003c36ae0, 0x43f8440, 0xc015908690, 0xc00da28f00)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/rancher/rancher/server/responsewriter.Gzip.func1(0x440d740, 0xc00fa2c8c0, 0xc00da28f00)
	/go/src/github.com/rancher/rancher/server/responsewriter/gzip.go:60 +0x1ac
net/http.HandlerFunc.ServeHTTP(0xc003c36b00, 0x440d740, 0xc00fa2c8c0, 0xc00da28f00)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00310c1c0, 0x440d740, 0xc00fa2c8c0, 0xc00da28f00)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:159 +0xf1
github.com/rancher/rancher/pkg/dynamiclistener.(*Server).cacheIPHandler.func1(0x440d740, 0xc00fa2c8c0, 0xc00a49c800)
	/go/src/github.com/rancher/rancher/pkg/dynamiclistener/server.go:436 +0x101
net/http.HandlerFunc.ServeHTTP(0xc00476b3c0, 0x440d740, 0xc00fa2c8c0, 0xc00a49c800)
	/usr/local/go/src/net/http/server.go:1964 +0x44
net/http.serverHandler.ServeHTTP(0xc004a02750, 0x440d740, 0xc00fa2c8c0, 0xc00a49c800)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc0190701e0, 0x44172c0, 0xc015ffca00)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5
```

**Comment by sangeethah** [comment]
Tested with latest build from master 

We are not allowed to create a templateRevision with with only questions and no clusterConfig set.
Api fails with following error message:

```
{
"baseType": "error",
"code": "MissingRequired",
"message": "ClusterTemplateRevision field ClusterConfig is required",
"status": 422,
"type": "error"
}
```
