### ISSUE TITLE
[rancher-python] 

### ISSUE THREAD

**Issue by muhamd-abdullah** [rancher/rancher#21547]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Installed the Python client, provided the corresponding URL and keys, and tried to create a project.

**Result:**
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

**Other details that may be helpful:**

**Environment information**
- Rancher version: 2.2.4
- Installation option (single install/HA): single

```
Output:
Traceback (most recent call last):
  File "/home/xgrid/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/home/xgrid/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/home/xgrid/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/home/xgrid/.local/lib/python3.6/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context)
  File "/home/xgrid/.local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 368, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xgrid/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/xgrid/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/xgrid/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='129.213.111.15', port=443): Max retries exceeded with url: /v3 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    secret_key='c586j7pbpmnx2v6kmwkqcdm54qwqchhkx2px725pdsvf4kdj9xf4lx')
  File "/home/xgrid/Desktop/client-python-master/rancher.py", line 212, in __init__
    self._load_schemas()
  File "/home/xgrid/Desktop/client-python-master/rancher.py", line 331, in _load_schemas
    response = self._get_response(self._url)
  File "/home/xgrid/Desktop/client-python-master/rancher.py", line 280, in _get_response
    headers=self._headers)
  File "/home/xgrid/.local/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/home/xgrid/.local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/xgrid/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/xgrid/.local/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='129.213.111.15', port=443): Max retries exceeded with url: /v3 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))

```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by LGTH** [comment]
you can try add verify to False
```
client = rancher.Client(url='https://xxx/v3',
                        access_key='xxx',
                        secret_key='xxx',
                        verify=False)
```
