### ISSUE TITLE
rancher certificates page empty

### ISSUE THREAD

**Issue by wenlock** [rancher/rancher#2176]
Hi, We're using rancher version 
rancher/server                   latest              0b07ec14c2e7 
Component	Version
Rancher	v0.37.1
Cattle	v0.91.1
User Interface	v0.47.0
Rancher Compose	beta/latest

We have two environments.   In the first environment, we can add certificates without issue.   In the second environment, the certificates dialog never appears, and we never get the add button.   In the browser console output we see this error:

TypeError: Cannot read property 'indexOf' of null
    at http://releases.rancher.com/ui/0.47.0/assets/ui.js:6:18391
    at Array.filter (native)
    at null.<anonymous> (http://releases.rancher.com/ui/0.47.0/assets/ui.js:6:18360)
    at a.f.get (http://releases.rancher.com/ui/0.47.0/assets/vendor.js:8:9571)
    at Object.s (http://releases.rancher.com/ui/0.47.0/assets/vendor.js:9:16168)
    at Object.n.default.compute (http://releases.rancher.com/ui/0.47.0/assets/vendor.js:9:23235)
    at Object.u.value (http://releases.rancher.com/ui/0.47.0/assets/vendor.js:9:25842)
    at Object.a [as read] (http://releases.rancher.com/ui/0.47.0/assets/vendor.js:9:28855)
    at i.n.default.getValue (http://releases.rancher.com/ui/0.47.0/assets/vendor.js:9:22542)
    at Object.n.default.compute (http://releases.rancher.com/ui/0.47.0/assets/vendor.js:9:23213)o @ ember.prod.js:31148e.default.trigger @ ember.prod.js:53549h._onerror @ ember.prod.js:54503d @ ember.prod.js:52837(anonymous function) @ ember.prod.js:31110n.invoke @ ember.prod.js:901n.flush @ ember.prod.js:965r.flush @ ember.prod.js:765a.end @ ember.prod.js:158a.run @ ember.prod.js:226u @ ember.prod.js:19018a @ ajax-promise.js:12(anonymous function) @ jquery.js:3256J.Callbacks.c @ jquery.js:3099J.Callbacks.h.fireWith @ jquery.js:3211n @ jquery.js:8264J.ajaxTransport.K.cors.e.crossDomain.send.t @ jquery.js:8605
2

On the rancher-server logs, we don't see any related errors.

Is this a known bug or does anyone have an idea on how to fix this?

**Comment by deniseschannon** [comment]
I haven't been able to reproduce on v0.37.1 or on the latest (v0.39.0).

But I want to confirm that you are talking about the "Certificates" tab under "Infrastructure".

**Comment by vincent99** [comment]
Does the certificate you tried to add to the broken environment have no CN in it?  I think this is the same issue as #2018.

**Comment by wenlock** [comment]
I no longer see this issue with latest version of rancher.
