### ISSUE TITLE
rancher-server behind SSL nginx-proxy Unable to create event router connection refused

### ISSUE THREAD

**Issue by jmatsushita** [rancher/rancher#2206]
Hi there,

I'm trying to setup rancher-server on Debian Jessie behind SSL using https://github.com/jwilder/nginx-proxy (instead of a manually deployed nginx proxy using --link as suggested in the docs).

I'm able to setup the UI and access it, however I receive the following error message in the docker logs:

```
time="2015-10-01T11:50:11Z" level=error msg="Unable to create event router" error="Get https://example.com/v1: dial tcp PUBLIC_IP:443: connection refused" 
```

Also, don't know if it's related by when clicking on the Admin link on the UI it stays stuck on "Loading". 

Again don't know if it's related but after a while I start getting this in the docker logs of the rancher-server:

```
2015-10-01 12:00:29,334 ERROR [:] [] [] [] [ecutorService-4] [o.a.c.m.context.NoExceptionRunnable ] Uncaught exception io.cattle.platform.lock.exception.FailedToAcquireLockException: Failed to acquire lock [SERVICE.ACCOUNT.CREATE.machineServiceAccount]
	at io.cattle.platform.lock.provider.impl.StandardLock.lock(StandardLock.java:51) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$1.withLock(AbstractLockManagerImpl.java:17) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:30) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.docker.machine.launch.GenericServiceLauncher.getCredential(GenericServiceLauncher.java:86) ~[cattle-docker-machine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.docker.machine.launch.MachineLauncher.setEnvironment(MachineLauncher.java:32) ~[cattle-docker-machine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.docker.machine.launch.GenericServiceLauncher.doRun(GenericServiceLauncher.java:161) ~[cattle-docker-machine-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
```

Finally trying to run a rancher/agent on the same machine with the CATTLE_AGENT_IP environment variable set to the server's public IP also fails with the following message in the logs:
```
INFO: Attempting to connect to: https://example.com/v1
ERROR: https://example.com/v1 is not accessible
```

**Comment by cloudnautique** [comment]
Hi @jmatsushita, I'm not too familiar with the nginx proxy, but it looks pretty cool. 

Is the Nginx container staying up? Or is it getting a 500? Is there any info in the logs that shows how it is rendering the template? It looks like the host is not listening on 443.

Also, Looking at the configs it doesn't appear to be passing all of these headers.

        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

And to get it to you would have to provide the container a Proxy.conf file (That includes the full proxy config).

**Comment by andreycizov** [comment]
@cloudnautique Passing headers causes the same behaviour: cannot open the admin tab and the log message.

**Comment by hrwebasst** [comment]
@jmatsushita any luck with this?

**Comment by deniseschannon** [comment]
@jmatsushita Please re-open if you are still having issues.
