### ISSUE TITLE
Updating host-iptables during service creation/deletion has failed

### ISSUE THREAD

**Issue by aruneli** [rancher/rancher#2232]
```
Component 	Version
Rancher 	v0.40.0-rc1
Cattle 	v0.96.0
User Interface 	v0.53.0
Rancher Compose 	beta/latest
```

Stack trace from cattle log. 
```
2015-10-05 03:51:04,334 ERROR [:] [] [] [] [utorService-263] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed null, exit code [1] output [INFO: Updating host-iptables
INFO: Downloading http://104.154.53.98:8080/v1//configcontent//host-iptables current=host-iptables-11831-d049e47d422e7c2556577ff35624f118e182ec70793d23712724afa2f3165683
basename: missing operand
Try 'basename --help' for more information.
ERROR: Missing SHA1SUMS files, invalid download
]
2015-10-05 03:51:08,327 ERROR [:] [] [] [] [p1709681173-803] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [io.github.ibuildthecloud.gdapi.request.ApiRequest@27c42261] org.jooq.exception.DataAccessException: SQL [select `ip_address_0`.`id` as `ip_address_0_id`, `ip_address_0`.`name` as `ip_address_0_name`, `ip_address_0`.`account_id` as `ip_address_0_account_id`, `ip_address_0`.`kind` as `ip_address_0_kind`, `ip_address_0`.`uuid` as `ip_address_0_uuid`, `ip_address_0`.`description` as `ip_address_0_description`, `ip_address_0`.`state` as `ip_address_0_state`, `ip_address_0`.`created` as `ip_address_0_created`, `ip_address_0`.`removed` as `ip_address_0_removed`, `ip_address_0`.`remove_time` as `ip_address_0_remove_time`, `ip_address_0`.`data` as `ip_address_0_data`, `ip_address_0`.`address` as `ip_address_0_address`, `ip_address_0`.`subnet_id` as `ip_address_0_subnet_id`, `ip_address_0`.`network_id` as `ip_address_0_network_id`, `ip_address_0`.`is_public` as `ip_address_0_is_public`, `ip_address_0`.`role` as `ip_address_0_role`, `ip_address_0`.`hostname` as `ip_address_0_hostname`, `ip_address_0`.`ip_pool_id` as `ip_address_0_ip_pool_id`, `ip_address_1`.`id` as `ip_address_1_id`, `ip_address_1`.`name` as `ip_address_1_name`, `ip_address_1`.`account_id` as `ip_address_1_account_id`, `ip_address_1`.`kind` as `ip_address_1_kind`, `ip_address_1`.`uuid` as `ip_address_1_uuid`, `ip_address_1`.`description` as `ip_address_1_description`, `ip_address_1`.`state` as `ip_address_1_state`, `ip_address_1`.`created` as `ip_address_1_created`, `ip_address_1`.`removed` as `ip_address_1_removed`, `ip_address_1`.`remove_time` as `ip_address_1_remove_time`, `ip_address_1`.`data` as `ip_address_1_data`, `ip_address_1`.`address` as `ip_address_1_address`, `ip_address_1`.`subnet_id` as `ip_address_1_subnet_id`, `ip_address_1`.`network_id` as `ip_address_1_network_id`, `ip_address_1`.`is_public` as `ip_address_1_is_public`, `ip_address_1`.`role` as `ip_address_1_role`, `ip_address_1`.`hostname` as `ip_address_1_hostname`, `ip_address_1`.`ip_pool_id` as `ip_address_1_ip_pool_id`, `port_2`.`id` as `port_2_id`, `port_2`.`name` as `port_2_name`, `port_2`.`account_id` as `port_2_account_id`, `port_2`.`kind` as `port_2_kind`, `port_2`.`uuid` as `port_2_uuid`, `port_2`.`description` as `port_2_description`, `port_2`.`state` as `port_2_state`, `port_2`.`created` as `port_2_created`, `port_2`.`removed` as `port_2_removed`, `port_2`.`remove_time` as `port_2_remove_time`, `port_2`.`data` as `port_2_data`, `port_2`.`public_port` as `port_2_public_port`, `port_2`.`private_port` as `port_2_private_port`, `port_2`.`instance_id` as `port_2_instance_id`, `port_2`.`public_ip_address_id` as `port_2_public_ip_address_id`, `port_2`.`protocol` as `port_2_protocol`, `port_2`.`private_ip_address_id` as `port_2_private_ip_address_id` from `instance_host_map` join `host` on `instance_host_map`.`host_id` = `host`.`id` join `port` as `port_2` on `instance_host_map`.`instance_id` = `port_2`.`instance_id` join `ip_address` as `ip_address_0` on `port_2`.`private_ip_address_id` = `ip_address_0`.`id` join `ip_address` as `ip_address_1` on `port_2`.`public_ip_address_id` = `ip_address_1`.`id` join `nic` on `instance_host_map`.`instance_id` = `nic`.`instance_id` join `network_service` on (`nic`.`network_id` = `network_service`.`network_id` and `network_service`.`kind` = ?) where (`host`.`agent_id` = ? and `instance_host_map`.`removed` is null and `port_2`.`removed` is null and `port_2`.`public_port` is not null and `port_2`.`state` in (?, ?, ?) and `host`.`removed` is null and `nic`.`removed` is null and `network_service`.`removed` is null) order by `port_2`.`created` asc]; Got error 28 from storage engine
	at org.jooq.impl.Utils.translate(Utils.java:1287) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:495) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:326) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:330) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2256) ~[jooq-3.3.0.jar:na]
	at io.cattle.platform.configitem.context.dao.impl.NetworkInfoDaoImpl.getHostPorts(NetworkInfoDaoImpl.java:337) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.context.impl.HostPortInfoFactory.populateContext(HostPortInfoFactory.java:19) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.context.impl.AbstractAgentBaseContextFactory.populateContext(AbstractAgentBaseContextFactory.java:69) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.server.model.impl.AbstractArchiveBasedConfigItem.handleRequest(AbstractArchiveBasedConfigItem.java:56) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.server.impl.ConfigItemServerImpl.handleDownload(ConfigItemServerImpl.java:97) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.server.impl.ConfigItemServerImpl.handleRequest(ConfigItemServerImpl.java:40) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.api.manager.ConfigContentManager.handle(ConfigContentManager.java:80) ~[cattle-config-item-api-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.api.manager.ConfigContentManager.getByIdInternal(ConfigContentManager.java:49) ~[cattle-config-item-api-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.getById(AbstractBaseResourceManager.java:61) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.ResourceManagerRequestHandler.generate(ResourceManagerRequestHandler.java:49) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.AbstractResponseGenerator.handle(AbstractResponseGenerator.java:14) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.handle(DefaultReadWriteApiDelegate.java:27) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.read(DefaultReadWriteApiDelegate.java:17) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at sun.reflect.GeneratedMethodAccessor518.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96) ~[spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260) ~[spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94) ~[spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at com.sun.proxy.$Proxy42.read(Unknown Source) ~[na:na]
	at io.github.ibuildthecloud.gdapi.request.handler.write.ReadWriteApiHandler.handle(ReadWriteApiHandler.java:21) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:86) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:79) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:72) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [jetty-security-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.Server.handle(Server.java:499) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Caused by: java.sql.SQLException: Got error 28 from storage engine
	at org.mariadb.jdbc.internal.SQLExceptionMapper.get(SQLExceptionMapper.java:149) ~[mariadb-java-client-1.1.7.jar:na]
	at org.mariadb.jdbc.internal.SQLExceptionMapper.throwException(SQLExceptionMapper.java:106) ~[mariadb-java-client-1.1.7.jar:na]
	at org.mariadb.jdbc.MySQLStatement.executeQueryEpilog(MySQLStatement.java:264) ~[mariadb-java-client-1.1.7.jar:na]
	at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:288) ~[mariadb-java-client-1.1.7.jar:na]
	at org.mariadb.jdbc.MySQLPreparedStatement.execute(MySQLPreparedStatement.java:141) ~[mariadb-java-client-1.1.7.jar:na]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar:1.4]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:194) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:261) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:322) ~[jooq-3.3.0.jar:na]
	... 59 common frames omitted
Caused by: org.mariadb.jdbc.internal.common.QueryException: Got error 28 from storage engine
	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.getResult(MySQLProtocol.java:942) ~[mariadb-java-client-1.1.7.jar:na]
	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:991) ~[mariadb-java-client-1.1.7.jar:na]
	at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:281) ~[mariadb-java-client-1.1.7.jar:na]
	... 65 common frames omitted

2015-10-05 03:51:08,342 ERROR [:] [] [] [] [utorService-263] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed null, exit code [1] output [INFO: Updating host-iptables
INFO: Downloading http://104.154.53.98:8080/v1//configcontent//host-iptables current=host-iptables-11831-d049e47d422e7c2556577ff35624f118e182ec70793d23712724afa2f3165683
basename: missing operand
Try 'basename --help' for more information.
ERROR: Missing SHA1SUMS files, invalid download
]
```

**Comment by ibuildthecloud** [comment]
@aruneli Mysql error "28 from storage engine" mean that you have run out of disk space I believe.

**Comment by aruneli** [comment]
@ibuildthecloud You are correct. disk is full and here are the top consumers. Do you see anything abnormal? What could be filling the disk?

```
root@10acre-master-0:/# du -x / | awk '{ if ($1 > 500000) { print $0} }'
738860	/usr
792880	/lib/modules
912988	/lib
678356	/var/lib/docker/aufs/diff
678648	/var/lib/docker/aufs
2857624	/var/lib/docker/volumes/b2dfb6bb50da3a4fe977432e8c6aba3c9d41d1388a6bdcf336b4795736cd0364/_data
2857628	/var/lib/docker/volumes/b2dfb6bb50da3a4fe977432e8c6aba3c9d41d1388a6bdcf336b4795736cd0364
3447076	/var/lib/docker/volumes/aec9bec7036b9e70d872d9c0c40b56a769c9b0ed4f068b47e24422f0a5606079/_data
3447080	/var/lib/docker/volumes/aec9bec7036b9e70d872d9c0c40b56a769c9b0ed4f068b47e24422f0a5606079
535728	/var/lib/docker/volumes/5a3f173beb394867e0e4c5ed03c40646f36a04ada6c8381b1dcb40abd91342f9/_data/logs
535736	/var/lib/docker/volumes/5a3f173beb394867e0e4c5ed03c40646f36a04ada6c8381b1dcb40abd91342f9/_data
535740	/var/lib/docker/volumes/5a3f173beb394867e0e4c5ed03c40646f36a04ada6c8381b1dcb40abd91342f9
6840452	/var/lib/docker/volumes
7523512	/var/lib/docker
7670912	/var/lib
7947964	/var
9759816	/
```
