### ISSUE TITLE
Rancher-server — Too many connections

### ISSUE THREAD

**Issue by philp** [rancher/rancher#2236]
_I'd originally posted this on the forums, but realised it may be more appropriate to log as an issue here._

We're running 0.40.0 and I'm seeing a lot of these exceptions in the rancher-server logs. They seem to indicate a problem with DB connectivity. We're using an external DB, which is a MySQL DB set up using AWS RDS.

```
2015-10-05 15:57:30,538 ERROR [:] [] [] [] [cutorService-44] [o.a.c.m.context.NoExceptionRunnable ] Uncaught exception org.jooq.exception.DataAccessException: SQL [select `instance_link`.`id`, `instance_link`.`name`, `instance_link`.`account_id`, `instance_link`.`kind`, `instance_link`.`uuid`, `instance_link`.`description`, `instance_link`.`state`, `instance_link`.`created`, `instance_link`.`removed`, `instance_link`.`remove_time`, `instance_link`.`data`, `instance_link`.`link_name`, `instance_link`.`instance_id`, `instance_link`.`target_instance_id`, `instance_link`.`service_consume_map_id`, `table1_instance`.`id` as `table1_id`, `table1_instance`.`name` as `table1_name`, `table1_instance`.`account_id` as `table1_account_id`, `table1_instance`.`kind` as `table1_kind`, `table1_instance`.`uuid` as `table1_uuid`, `table1_instance`.`description` as `table1_description`, `table1_instance`.`state` as `table1_state`, `table1_instance`.`created` as `table1_created`, `table1_instance`.`removed` as `table1_removed`, `table1_instance`.`remove_time` as `table1_remove_time`, `table1_instance`.`data` as `table1_data`, `table1_instance`.`allocation_state` as `table1_allocation_state`, `table1_instance`.`compute` as `table1_compute`, `table1_instance`.`memory_mb` as `table1_memory_mb`, `table1_instance`.`image_id` as `table1_image_id`, `table1_instance`.`offering_id` as `table1_offering_id`, `table1_instance`.`hostname` as `table1_hostname`, `table1_instance`.`zone_id` as `table1_zone_id`, `table1_instance`.`instance_triggered_stop` as `table1_instance_triggered_stop`, `table1_instance`.`agent_id` as `table1_agent_id`, `table1_instance`.`domain` as `table1_domain`, `table1_instance`.`first_running` as `table1_first_running`, `table1_instance`.`token` as `table1_token`, `table1_instance`.`userdata` as `table1_userdata`, `table1_instance`.`system_container` as `table1_system_container`, `table1_instance`.`registry_credential_id` as `table1_registry_credential_id`, `table1_instance`.`external_id` as `table1_external_id`, `table1_instance`.`native_container` as `table1_native_container`, `table1_instance`.`network_container_id` as `table1_network_container_id`, `table1_instance`.`health_state` as `table1_health_state`, `table1_instance`.`start_count` as `table1_start_count`, `table1_instance`.`create_index` as `table1_create_index`, `table1_instance`.`deployment_unit_uuid` as `table1_deployment_unit_uuid` from `instance_link` left outer join `instance` as `table1_instance` on `instance_link`.`instance_id` = `table1_instance`.`id` where (`instance_link`.`id` = ? and `instance_link`.`account_id` = ?) limit ? offset ?]; Could not connect: Too many connections
	at org.jooq.impl.Utils.translate(Utils.java:1287) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:495) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:326) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:330) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractResultQuery.fetchInto(AbstractResultQuery.java:656) ~[jooq-3.3.0.jar:na]
	at io.cattle.platform.api.resource.jooq.AbstractJooqResourceManager.listInternal(AbstractJooqResourceManager.java:80) ~[cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.resource.jooq.AbstractJooqResourceManager.listInternal(AbstractJooqResourceManager.java:54) ~[cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.getByIdInternal(AbstractBaseResourceManager.java:68) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.getById(AbstractBaseResourceManager.java:61) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.iaas.api.change.impl.ResourceChangeEventProcessor.processEvent(ResourceChangeEventProcessor.java:47) ~[cattle-iaas-api-logic-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.pubsub.subscribe.NonBlockingSubscriptionHandler.postProcess(NonBlockingSubscriptionHandler.java:113) ~[cattle-framework-api-pub-sub-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.pubsub.subscribe.NonBlockingSubscriptionHandler$1.onEvent(NonBlockingSubscriptionHandler.java:91) ~[cattle-framework-api-pub-sub-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Caused by: java.sql.SQLException: Could not connect: Too many connections
	at org.mariadb.jdbc.internal.SQLExceptionMapper.get(SQLExceptionMapper.java:149) ~[mariadb-java-client-1.1.7.jar:na]
	at org.mariadb.jdbc.internal.SQLExceptionMapper.throwException(SQLExceptionMapper.java:106) ~[mariadb-java-client-1.1.7.jar:na]
	at org.mariadb.jdbc.Driver.connect(Driver.java:114) ~[mariadb-java-client-1.1.7.jar:na]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1188) ~[commons-pool-1.6.jar:1.6]
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044) ~[commons-dbcp-1.4.jar:1.4]
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111) ~[spring-jdbc-3.2.4.RELEASE.jar:3.2.4.RELEASE]
	at org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler.invoke(TransactionAwareDataSourceProxy.java:224) ~[spring-jdbc-3.2.4.RELEASE.jar:3.2.4.RELEASE]
	at com.sun.proxy.$Proxy55.prepareStatement(Unknown Source) ~[na:na]
	at org.jooq.impl.ProviderEnabledConnection.prepareStatement(ProviderEnabledConnection.java:112) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.SettingsEnabledConnection.prepareStatement(SettingsEnabledConnection.java:76) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractResultQuery.prepare(AbstractResultQuery.java:230) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:296) ~[jooq-3.3.0.jar:na]
	... 19 common frames omitted
Caused by: org.mariadb.jdbc.internal.common.QueryException: Could not connect: Too many connections
	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.checkErrorPacket(MySQLProtocol.java:526) ~[mariadb-java-client-1.1.7.jar:na]
	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.connect(MySQLProtocol.java:480) ~[mariadb-java-client-1.1.7.jar:na]
	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.connect(MySQLProtocol.java:673) ~[mariadb-java-client-1.1.7.jar:na]
	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.<init>(MySQLProtocol.java:266) ~[mariadb-java-client-1.1.7.jar:na]
	at org.mariadb.jdbc.Driver.connect(Driver.java:110) ~[mariadb-java-client-1.1.7.jar:na]
	... 31 common frames omitted
```

**Comment by cloudnautique** [comment]
@philp which RDS instance are you using? I believe they limit connections based on instance type. Rancher needs ~150 Max connections.

**Comment by philp** [comment]
Aha, I was running with a db.t1.micro while we tested things. I will switch to a larger instance and see if that resolves things.

Is the requirement for maximum connections something which would be worth documenting?

**Comment by deniseschannon** [comment]
@philp I've just added the document for max connections required. If you are still having issues, please re-open.

**Comment by ryanwalls** [comment]
@deniseschannon Where is the documentation for max connections?

**Comment by ryanwalls** [comment]
Update.  I found it.  http://docs.rancher.com/rancher/v1.3/en/installing-rancher/installing-server/
