### ISSUE TITLE
This cluster is currently Unavailable; areas that interact directly with it will not be available until the API is ready.

### ISSUE THREAD

**Issue by taibc** [rancher/rancher#22428]
*After reboot my rancher, I got this error. My kubernetes master is showing "unschedulable", and I check my master by using command "docker ps", the container coreos-etcd is restarting. 

So, I checked log of rancher container, it can not connect to master 

[ERROR] ClusterController c-pcvkj [cluster-agent-controller] failed with : could not contact server: Get https://192.168.142.131:6443/version: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

How can I fix this error ?*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.3` UI: `v2.0.53` |
|Access|`local` `admin`|
|Route|`global-admin.clusters.index`|

**Comment by superseb** [comment]
What are the logs of the etcd container, that should give an indication on why it is restarting. Restarting Rancher doesnt influence cluster that are created with it, unless you are using one node for running Rancher and adding it to a cluster.

On a sidenote, keep in mind v2.0.3 is over a year old and many improvements have been made and many security issues have been fixed.

**Comment by taibc** [comment]
@superseb : Thank you, this is the logs of the etcd container

> 2019-08-27 23:00:35.729815 I | etcdmain: etcd Version: 3.1.12
2019-08-27 23:00:35.729916 I | etcdmain: Git SHA: 918698add
2019-08-27 23:00:35.729923 I | etcdmain: Go Version: go1.8.7
2019-08-27 23:00:35.729931 I | etcdmain: Go OS/Arch: linux/amd64
2019-08-27 23:00:35.729937 I | etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
2019-08-27 23:00:35.729997 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2019-08-27 23:00:35.730033 I | embed: peerTLS: cert = /etc/kubernetes/ssl/kube-etcd-192-168-142-131.pem, key = /etc/kubernetes/ssl/kube-etcd-192-168-142-131-key.pem, ca = , trusted-ca = /etc/kubernetes/ssl/kube-ca.pem, client-cert-auth = true
2019-08-27 23:00:35.735050 I | embed: listening for peers on https://0.0.0.0:2380
2019-08-27 23:00:35.735209 I | embed: listening for client requests on 0.0.0.0:2379
2019-08-27 23:00:35.740081 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
2019-08-27 23:00:35.741193 I | etcdserver: recovered store from snapshot at index 10001
2019-08-27 23:00:35.741209 I | etcdserver: name = etcd-k8s-master
2019-08-27 23:00:35.741214 I | etcdserver: data dir = /var/lib/rancher/etcd/
2019-08-27 23:00:35.741220 I | etcdserver: member dir = /var/lib/rancher/etcd/member
2019-08-27 23:00:35.741225 I | etcdserver: heartbeat = 500ms
2019-08-27 23:00:35.741230 I | etcdserver: election = 5000ms
2019-08-27 23:00:35.741239 I | etcdserver: snapshot count = 10000
2019-08-27 23:00:35.741252 I | etcdserver: advertise client URLs = https://192.168.142.131:2379,https://192.168.142.131:4001
2019-08-27 23:00:36.267303 I | etcdserver: restarting member 7ef14b74d16f9a33 in cluster 98eb3d55c56d141d at commit index 18703
2019-08-27 23:00:36.315884 I | raft: 7ef14b74d16f9a33 became follower at term 3
2019-08-27 23:00:36.315923 I | raft: newRaft 7ef14b74d16f9a33 [peers: [7ef14b74d16f9a33], term: 3, commit: 18703, applied: 10001, lastindex: 18703, lastterm: 3]
2019-08-27 23:00:36.325436 I | etcdserver/api: enabled capabilities for version 3.1
2019-08-27 23:00:36.325482 I | etcdserver/membership: added member 7ef14b74d16f9a33 [https://192.168.142.131:2380] to cluster 98eb3d55c56d141d from store
2019-08-27 23:00:36.325500 I | etcdserver/membership: set the cluster version to 3.1 from store
panic: invalid page type: 419: 10
goroutine 1 [running]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*Cursor).search(0xc42014e0f0, 0xc420e93190, 0x8, 0x8, 0x1a3)
	/usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/cursor.go:256 +0x405
github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*Cursor).seek(0xc42014e0f0, 0xc420e93190, 0x8, 0x8, 0xdb8ba0, 0xa3f401, 0x13bcdc8, 0x1350104, 0x5, 0x5, ...)
	/usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/cursor.go:159 +0xb1
github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*Cursor).Seek(0xc42014e0f0, 0xc420e93190, 0x8, 0x8, 0x0, 0x0, 0x119, 0xc42014e0c0, 0x40f8c0, 0xc420e93190)
	/usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/cursor.go:118 +0x50
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.(*batchTx).UnsafeRange(0xc4201a4cc0, 0x1350104, 0x5, 0x5, 0xc420e93190, 0x8, 0x8, 0xc420e93198, 0x8, 0x8, ...)
	/usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend/batch_tx.go:102 +0x159
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/lease.(*lessor).initAndRecover(0xc42004d5c0)
	/usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/lease/lessor.go:476 +0x1c8
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/lease.newLessor(0x1362e20, 0xc420177320, 0x8, 0xc42107a0e0)
	/usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/lease/lessor.go:167 +0x1c5
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/lease.NewLessor(0x1362e20, 0xc420177320, 0x8, 0xc42107a040, 0x2)
	/usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/lease/lessor.go:153 +0x3f
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.NewServer(0xc4200694a0, 0x0, 0x0, 0x0)
	/usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:448 +0x17b3
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed.StartEtcd(0xc42015ca80, 0xc4200b18c0, 0x0, 0x0)
	/usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed/etcd.go:123 +0x6bc
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcd(0xc42015ca80, 0x6, 0xe98ba4, 0x6, 0x1)
	/usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:187 +0x58
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcdOrProxyV2()
	/usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:104 +0x1579
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.Main()
	/usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/main.go:39 +0x61
main.main()
	/usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/etcd/main.go:28 +0x20

**Comment by svenluzar** [comment]
I had the same problem. I'm using rke to deploy my cluster. After changing node rules, I have executed `rke up` again, but 'rke up' used the latest kubernetes version (1.16). The rancher-server and api were not compatible with this new kubernetes version. As a result, the cluster jumped back and forth between being active and unavailable.

The solution was to find a compatible version mix:

https://rancher.com/support-maintenance-terms/all-supported-versions/rancher-v2.3.3/

After that you have to specify the tag `kubernetes_version` in the cluster.yml file:

https://rancher.com/docs/rke/latest/en/config-options/#kubernetes-version

Finally you have to call `rke up` again.

**Comment by superseb** [comment]
Thanks for the info @svenluzar .

@taibc please let me know if this still reproduces on the latest version so we can investigate.
