### ISSUE TITLE
rancher (v0.6.13) cli crashes on stack ls

### ISSUE THREAD

**Issue by vvatsa** [rancher/rancher#22471]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug with rancher cli

**Steps to reproduce (least amount of steps as possible):**
In our rancher (1.6.26), the rancher cli crashes trying to do a stack ls

```shell
rancher stack ls
```

**Result:**

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0x8f7047]

goroutine 1 [running]:
github.com/rancher/cli/vendor/github.com/urfave/cli.HandleAction.func1(0xc42060bf70)
        /go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:472 +0x279
panic(0xa07880, 0xe81e30)
        /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/rancher/cli/cmd.(*CatalogOperator).GetTemplateVersionUpgrades(0xc420428200, 0x0, 0x2b, 0x0, 0xb6b0a0)
        /go/src/github.com/rancher/cli/cmd/catalog.go:589 +0x37
github.com/rancher/cli/cmd.(*CatalogOperator).GetTemplateVersionUpgradesByID(0xc420428200, 0xc4203082a0, 0x2b, 0xae1bf2, 0x1, 0x0)
        /go/src/github.com/rancher/cli/cmd/catalog.go:585 +0x57
github.com/rancher/cli/cmd.stackLs(0xc4203968c0, 0x0, 0x0)
        /go/src/github.com/rancher/cli/cmd/stack.go:145 +0x8e4
reflect.Value.call(0x9c06a0, 0xb11940, 0x13, 0xae25a8, 0x4, 0xc420267f10, 0x1, 0x1, 0xc4200f0040, 0xac7da0, ...)
        /usr/local/go/src/reflect/value.go:447 +0x969
reflect.Value.Call(0x9c06a0, 0xb11940, 0x13, 0xc420267f10, 0x1, 0x1, 0x4, 0xc420186f50, 0x5)
        /usr/local/go/src/reflect/value.go:308 +0xa4
github.com/rancher/cli/vendor/github.com/urfave/cli.HandleAction(0x9c06a0, 0xb11940, 0xc4203968c0, 0x0, 0x0)
        /go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:481 +0x173
github.com/rancher/cli/vendor/github.com/urfave/cli.Command.Run(0xae1dc9, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0xae8c23, 0xb, 0x0, ...)
        /go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/command.go:186 +0x999
github.com/rancher/cli/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc4200bac00, 0xc420396640, 0x0, 0x0)
        /go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:355 +0x97a
github.com/rancher/cli/vendor/github.com/urfave/cli.Command.startApp(0xae4c97, 0x6, 0xae3a84, 0x5, 0x0, 0x0, 0x0, 0xaef38a, 0x14, 0x0, ...)
        /go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/command.go:273 +0x7fd
github.com/rancher/cli/vendor/github.com/urfave/cli.Command.Run(0xae4c97, 0x6, 0xae3a84, 0x5, 0x0, 0x0, 0x0, 0xaef38a, 0x14, 0x0, ...)
        /go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/command.go:74 +0x1284
github.com/rancher/cli/vendor/github.com/urfave/cli.(*App).Run(0xc4200baa80, 0xc4200d8060, 0x3, 0x3, 0x0, 0x0)
        /go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:235 +0x546
main.mainErr(0x0, 0x0)
        /go/src/github.com/rancher/cli/main.go:150 +0x2730
main.main()
        /go/src/github.com/rancher/cli/main.go:37 +0x22

```
**Other details that may be helpful:**
```shell
rancher --version
rancher version v0.6.13
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Comment by alena1108** [comment]
The fix will be available in v1.6.29-rc2

**Comment by alena1108** [comment]
Can be tested with `rancher/server:v1.6.29-rc2`

**Comment by rawmind0** [comment]
CLI patched version including PR https://github.com/rancher/cli/issues/251 was tested succesfully. @vvatsa could you please confirm that it resolved the issue??

**Comment by soumyalj** [comment]
Tested with CLI  version v0.6.14-rc1
CLI stack ls works as expected. Did not observe a panic. 
```
$ ./rancher --url http://a.b.c.d:8080 --access-key abcdefgh --secret-key sdkjfaldskjflsd --env 1a7 stack ls
ID        NAME         STATE       CATALOG   SERVICES   SYSTEM    DETAIL    AVAILABLE UPGRADES
 
1st249    test910445   healthy               4          false               
1st255    test733755   healthy               3          false               
```
