### ISSUE TITLE
2.2.8 Pipeline cannot fetch code from github

### ISSUE THREAD

**Issue by Qquanwei** [rancher/rancher#22597]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
add pipeline https://github.com/Qquanwei/test-auto-deploy and run it

**Result:**
clone stage failed

![image](https://user-images.githubusercontent.com/9263655/64141435-95503f00-ce3a-11e9-86ae-18222e37e8b2.png)

```
02:27:11 Cloning the remote Git repository
02:27:11 Cloning repository https://github.com/Qquanwei/test-auto-deploy.git
02:27:11  > git init /home/jenkins/workspace/pipeline_p-gqk26-14 # timeout=10
02:27:11 Fetching upstream changes from https://github.com/Qquanwei/test-auto-deploy.git
02:27:11  > git --version # timeout=10
02:27:11 using GIT_ASKPASS to set credentials 
02:27:11  > git fetch --tags --progress https://github.com/Qquanwei/test-auto-deploy.git +refs/heads/*:refs/remotes/origin/*
02:27:12 ERROR: Error cloning remote repo 'origin'
02:27:12 hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/Qquanwei/test-auto-deploy.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
02:27:12 stdout: 
02:27:12 stderr: fatal: unable to access 'https://github.com/Qquanwei/test-auto-deploy.git/': Failed to connect to github.com port 443: Connection refused
02:27:12 
02:27:12 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2002)
02:27:12 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1721)
02:27:12 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:72)
02:27:12 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:405)
02:27:12 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:614)
02:27:12 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
02:27:12 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
02:27:12 	at hudson.remoting.UserRequest.perform(UserRequest.java:181)
02:27:12 	at hudson.remoting.UserRequest.perform(UserRequest.java:52)
02:27:12 	at hudson.remoting.Request$2.run(Request.java:336)
02:27:12 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
02:27:12 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02:27:12 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
02:27:12 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
02:27:12 	at hudson.remoting.Engine$1$1.run(Engine.java:98)
02:27:12 	at java.lang.Thread.run(Thread.java:748)
02:27:12 	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 10.42.0.93/10.42.0.93:60424
02:27:12 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
02:27:12 		at hudson.remoting.UserResponse.retrieve(UserRequest.java:389)
02:27:12 		at hudson.remoting.Channel.call(Channel.java:955)
02:27:12 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
02:27:12 		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:27:12 		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
02:27:12 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:27:12 		at java.lang.reflect.Method.invoke(Method.java:498)
02:27:12 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
02:27:12 		at com.sun.proxy.$Proxy78.execute(Unknown Source)
02:27:12 		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1083)
02:27:12 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1123)
02:27:12 		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:113)
02:27:12 		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:85)
02:27:12 		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:75)
02:27:12 		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
02:27:12 		at hudson.security.ACL.impersonate(ACL.java:290)
02:27:12 		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
02:27:12 		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
02:27:12 		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02:27:12 		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
02:27:12 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
02:27:12 		... 1 more
```

**Other details that may be helpful:**
I can pull code from jenkins pod and other pods, but the jenkins pipeline always failed

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

rancher 2.2.8
k8s: v1.14.6

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

v1.14.6
--

```
(paste the output here)
```

**Comment by gpp0725** [comment]
What's the solution? I've had the same problem

**Comment by hashming** [comment]
Please indicate a solution to the problem

**Comment by Qquanwei** [comment]
> 

抱歉，这个问题时间很久了，我也不记得当初是怎么解决的了。
