### ISSUE TITLE
Longhorn single-cluster app: Failed to rollback to old version Longhorn

### ISSUE THREAD

**Issue by shuo-wu** [rancher/rancher#23017]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Launch a valid old version app.
2. Upgrade to an invalid new version whose workloads will get crashed.
3. Try to roll back to the old version.

**Result:**
1. Rollback gets stuck in the crashed workloads.
2. Wait for a while then error message presented in App detail page: 
```
Failed to install app longhorn-system. Error: UPGRADE FAILED: transport is closing
``` 
4. Delete the workloads after getting the error message. The workload won't be re-created.

Log info of rancher container:
```
[main] 2019/09/23 18:53:48 Starting Tiller v2.10+unreleased (tls=false)
[main] 2019/09/23 18:53:48 GRPC listening on :55164
[main] 2019/09/23 18:53:48 Probes listening on :58284
[main] 2019/09/23 18:53:48 Storage driver is ConfigMap
[main] 2019/09/23 18:53:48 Max history per release is 1
[tiller] 2019/09/23 18:53:49 getting history for release longhorn-system
[storage] 2019/09/23 18:53:49 getting release history for "longhorn-system"
[tiller] 2019/09/23 18:53:49 preparing update for longhorn-system
[storage] 2019/09/23 18:53:49 getting deployed releases from "longhorn-system" history
[storage] 2019/09/23 18:53:49 getting last revision of "longhorn-system"
[storage] 2019/09/23 18:53:49 getting release history for "longhorn-system"
[storage] 2019/09/23 18:53:49 getting release history for "longhorn-system"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x12e8cc8]

goroutine 37 [running]:
k8s.io/helm/pkg/tiller.(*ReleaseServer).performUpdateForce(0xc4208b59b0, 0xc42035cfa0, 0x0, 0x0, 0x17b7b40)
	/go/src/k8s.io/helm/pkg/tiller/release_update.go:166 +0x188
k8s.io/helm/pkg/tiller.(*ReleaseServer).UpdateRelease(0xc4208b59b0, 0x17d8960, 0xc4207805d0, 0xc42035cfa0, 0xc4208b59b0, 0x16b98a6, 0xd)
	/go/src/k8s.io/helm/pkg/tiller/release_update.go:43 +0x245
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_UpdateRelease_Handler.func1(0x17d8960, 0xc4207805d0, 0x16066c0, 0xc42035cfa0, 0x32, 0xc42035d180, 0x1, 0x1681d11)
	/go/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:1244 +0x86
k8s.io/helm/vendor/github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x17d8960, 0xc4207805d0, 0x16066c0, 0xc42035cfa0, 0xc4206e73c0, 0xc4206e73e0, 0x48, 0xc4206e72c0, 0xc42006ba40, 0x4108c8)
	/go/src/k8s.io/helm/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go:86 +0xdb
k8s.io/helm/pkg/tiller.newUnaryInterceptor.func1(0x17d8960, 0xc4207805d0, 0x16066c0, 0xc42035cfa0, 0xc4206e73c0, 0xc4206e73e0, 0xc4208dcab0, 0x4108c8, 0x50, 0x15d88a0)
	/go/src/k8s.io/helm/pkg/tiller/server.go:60 +0xab
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_UpdateRelease_Handler(0x1640500, 0xc4208b59b0, 0x17d8960, 0xc4207805d0, 0xc42035cf50, 0x1715568, 0x0, 0x0, 0x42c96a, 0x171a488)
	/go/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:1246 +0x167
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4201ab180, 0x17e14a0, 0xc42048b4a0, 0xc4201d8d00, 0xc4208b5a40, 0x2162cf0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:826 +0x9c8
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4201ab180, 0x17e14a0, 0xc42048b4a0, 0xc4201d8d00, 0x0)
	/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:1023 +0x1318
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420778270, 0xc4201ab180, 0x17e14a0, 0xc42048b4a0, 0xc4201d8d00)
	/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:572 +0x9f
created by k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:570 +0xa1
2019/09/23 18:53:49 [ERROR] AppController p-xwf7j/longhorn-system [helm-controller] failed with : failed to install app longhorn-system. Error: UPGRADE FAILED: transport is closing
```

**Other details that may be helpful:**

**Environment information**
Rancher version: v.2.2.7
Kubernetes version: v1.13.9-rancher1-2
Docker version: 18.09.7

**Comment by prachidamle** [comment]
@shuo-wu was the app in "active" state before you upgraded to an invalid new version?

**Comment by shuo-wu** [comment]
@prachidamle Yes.

**Comment by alena1108** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/21070.
