### ISSUE TITLE
rke：invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by system51** [rancher/rancher#23048]
**What kind of request is this (question/bug/enhancement/feature request):question

**Steps to reproduce (least amount of steps as possible):
```
./rke up --update-only --config /root/rancher-cluster.yml
```

**Result:**
```
INFO[0029] [reconcile] Check etcd hosts to be deleted   
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x124261d]

goroutine 1 [running]:
github.com/rancher/rke/vendor/github.com/urfave/cli.HandleAction.func1(0xc0005a8d68)
        /go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/app.go:472 +0x287
panic(0x13f7860, 0x2572030)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/rancher/rke/vendor/k8s.io/client-go/util/cert.EncodeCertPEM(...)
        /go/src/github.com/rancher/rke/vendor/k8s.io/client-go/util/cert/pem.go:69
github.com/rancher/rke/cluster.reconcileEtcd(0x18cf5a0, 0xc00003e0f0, 0xc0000b6d00, 0xc00025f600, 0xc0000ed2c0, 0x0, 0x0)
        /go/src/github.com/rancher/rke/cluster/reconcile.go:175 +0x13d
github.com/rancher/rke/cluster.ReconcileCluster(0x18cf5a0, 0xc00003e0f0, 0xc00025f600, 0xc0000b6d00, 0x0, 0x0, 0x7ffe8369e847, 0x19, 0x0, 0x0, ...)
        /go/src/github.com/rancher/rke/cluster/reconcile.go:43 +0x22a
github.com/rancher/rke/cmd.ClusterUp(0x18cf5a0, 0xc00003e0f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffe8369e847, 0x19, 0x0, ...)
        /go/src/github.com/rancher/rke/cmd/up.go:133 +0x650
github.com/rancher/rke/cmd.clusterUpFromCli(0xc0000d7540, 0x0, 0x0)
        /go/src/github.com/rancher/rke/cmd/up.go:242 +0x60e
reflect.Value.call(0x138d4a0, 0x1671228, 0x13, 0x15bf142, 0x4, 0xc0004c4d08, 0x1, 0x1, 0xc00007c080, 0x412324, ...)
        /usr/local/go/src/reflect/value.go:447 +0x461
reflect.Value.Call(0x138d4a0, 0x1671228, 0x13, 0xc0004c4d08, 0x1, 0x1, 0xc0000631a8, 0x140, 0xc000063180)
        /usr/local/go/src/reflect/value.go:308 +0xa4
github.com/rancher/rke/vendor/github.com/urfave/cli.HandleAction(0x138d4a0, 0x1671228, 0xc0000d7540, 0x0, 0x0)
        /go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/app.go:481 +0x1ff
github.com/rancher/rke/vendor/github.com/urfave/cli.Command.Run(0x15beba4, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x15d08a1, 0x14, 0x0, ...)
        /go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/command.go:186 +0x8d1
github.com/rancher/rke/vendor/github.com/urfave/cli.(*App).Run(0xc000001680, 0xc00003a050, 0x5, 0x5, 0x0, 0x0)
        /go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/app.go:235 +0x601
main.mainErr(0x189ad60, 0xc00000e018)
        /go/src/github.com/rancher/rke/main.go:56 +0xf94
main.main()
        /go/src/github.com/rancher/rke/main.go:19 +0x43
```

**Other details that may be helpful:nothing

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

```
[root@k8s-m-1001501022 ~]# ./rke -v
rke version v0.2.8
```

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
[root@k8s-m-1001501022 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
[root@k8s-m-1001501022 ~]# docker version
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    7390fc6
 Built: Tue Feb 27 22:15:20 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6
  Built:        Tue Feb 27 22:17:54 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by superseb** [comment]
See https://github.com/rancher/rke/issues/1586, let us know it it doesn't solve the issue.
