### ISSUE TITLE
Support graylog as a logging target

### ISSUE THREAD

**Issue by huegelc** [rancher/rancher#23052]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
I've already opened a ticket here: https://github.com/Graylog2/graylog2-server/issues/6488 but I think this is actually a Rancher issue

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.4
- Installation option (single install/HA): single

I'm sorry to cross post this issue but I'm not quite sure if this is rancher or graylog related.

Thanks

**Comment by huegelc** [comment]
Rancher 2.2.8 has the same issue.

**Comment by tfiduccia** [comment]
@deniseschannon - looks like we are missing a field.  Should probably add it if we want it to work or remove Fluentd from list.

**Comment by deniseschannon** [comment]
@huegelc I don't quite understand what you're trying to do or where this host field is missing. 

Fluentd is related to our logging, but we can export to logging drivers. Which driver is missing host? Isn't the endpoint  or hostname the same as a host? I haven't checked with the engineers who worked on logging, but we haven't had issues saying we're missing a required field. 

<img width="1381" alt="Screen Shot 2019-10-01 at 1 14 54 PM" src="https://user-images.githubusercontent.com/11410997/65997056-81a1f380-e44d-11e9-82bf-a92f1c617151.png">

**Comment by huegelc** [comment]
@deniseschannon we want to use the rancher fluentd exporter with a Graylog GELF TCP input

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/6955465/66023621-02b2c680-e4f2-11e9-83f3-8b390f5ee3f0.png">

<img width="396" alt="image" src="https://user-images.githubusercontent.com/6955465/66023959-f0855800-e4f2-11e9-951d-4bdd4a74d452.png">

When you hit the **Test** button, Graylog complains that the exported data is missing mandatory fields. Here is a tail of the graylog server logs.

```
2019-10-02T06:47:13.887Z WARN  [GelfCodec] GELF message <776b78d0-e4e0-11e9-b441-00505688767a> (received from <10.2.28.38:43982>) is missing mandatory "host" field.
2019-10-02T06:47:13.890Z ERROR [DecodingProcessor] Unable to decode raw message RawMessage{id=776b78d0-e4e0-11e9-b441-00505688767a, journalOffset=5498786331, codec=gelf, payloadSize=84, timestamp=2019-10-02T06:47:13.885Z, remoteAddress=/10.2.28.38:43982} on input <5d8a29b283623e1684651c3d>.
2019-10-02T06:47:13.892Z ERROR [DecodingProcessor] Error processing message RawMessage{id=776b78d0-e4e0-11e9-b441-00505688767a, journalOffset=5498786331, codec=gelf, payloadSize=84, timestamp=2019-10-02T06:47:13.885Z, remoteAddress=/10.2.28.38:43982}
java.lang.IllegalArgumentException: GELF message <776b78d0-e4e0-11e9-b441-00505688767a> (received from <10.2.28.38:43982>) is missing mandatory "short_message" or "message" field.
	at org.graylog2.inputs.codecs.GelfCodec.validateGELFMessage(GelfCodec.java:262) ~[graylog.jar:?]
	at org.graylog2.inputs.codecs.GelfCodec.decode(GelfCodec.java:134) ~[graylog.jar:?]
	at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:150) ~[graylog.jar:?]
	at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:91) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:86) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:45) [graylog.jar:?]
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

```
This obviously fails and graylog discards the message. 
Initially I thought this is a graylog issue but doing this from the rancher host:

```
echo -n -e '{ "version": "1.1", "host": "example.org", "short_message": "A short message", "level": 5, "_some_info": "foo" }'"\0" | nc -w1 graylog.xxxx.com 12201
```
works as expected and the message is processed by graylog. 
So I suspect there is something wrong with the fluentd exporter in rancher.

**Comment by deniseschannon** [comment]
@huegelc it sounds like you are trying to use export to Graylog, which is currently not supported in Rancher. I'm changing this issue to an enhancement request for graylog.

**Comment by junkiebev** [comment]
@deniseschannon - FYI I have a priority 3 customer support ticket in (`#6457` if you want to reference it) for OOTB graylog support.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/14062
