### ISSUE TITLE
Panic in DeploymentController

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#23083]
rancher v2.2.8. 

Logs from a customer cluster:
```
2019/09/03 20:16:42 [ERROR] DeploymentController <clusterID> recovered from panic "runtime error: invalid memory address or nil pointer dereference". (err=<nil>) Call stack:
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:154
/usr/local/go/src/runtime/panic.go:522
/usr/local/go/src/runtime/panic.go:82
/usr/local/go/src/runtime/signal_unix.go:390
/go/src/github.com/rancher/rancher/pkg/controllers/user/endpoints/endpoints.go:313
/go/src/github.com/rancher/rancher/pkg/controllers/user/endpoints/workload_endpoints.go:90
/go/src/github.com/rancher/rancher/pkg/controllers/user/workload/workload_common.go:139
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/apps/v1beta2/zz_generated_deployment_controller.go:146
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:348
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:258
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:246
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:1337
```

IngressController also hits the same panic in the same logs

**Comment by jnicholls** [comment]
Seeing this occur also on a v2.2.9 HA installation. Looks like a dereference of a nil `rule` here: https://github.com/rancher/rancher/blob/v2.2.9/pkg/controllers/user/endpoints/endpoints.go#L313 as invoked from here https://github.com/rancher/rancher/blob/v2.2.9/pkg/controllers/user/endpoints/workload_endpoints.go#L90

**Comment by bentastic27** [comment]
Seeing on a 2.4.3 HA install as well. Local cluster is 1.15.9. This particular error is for the ingresscontroller, but there are instances of many different types hitting this.

```
grep -ir "invalid memory address" */k8s/podlogs/k8s_rancher_rancher-* | grep -Po '\w+Controller' | sort | uniq -c | sort -rn
   7085 DeploymentController
    970 DaemonSetController
    521 IngressController
    514 StatefulSetController
```

Customer specific stuff replaced with generic names:

```
2020/07/24 16:59:39 [ERROR] IngressController fake-ns/some-ingress recovered from panic "runtime error: invalid memory address or nil pointer dereference". (err=<nil>) Call stack:
goroutine 12769 [running]:
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.RecoverFromPanic(0xc016263d30)
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:158 +0xb5
panic(0x3686a80, 0x6c38c60)
/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/rancher/pkg/controllers/user/endpoints.convertIngressToServicePublicEndpointsMap(0xc00a78a168, 0x1a26c01, 0xc00cd2e1a0)
/go/src/github.com/rancher/rancher/pkg/controllers/user/endpoints/endpoints.go:308 +0x51b
github.com/rancher/rancher/pkg/controllers/user/endpoints.convertIngressToPublicEndpoints(0xc00a78a168, 0xc012d98801, 0x474b160, 0xc012d988a0, 0x474b3a0)
/go/src/github.com/rancher/rancher/pkg/controllers/user/endpoints/endpoints.go:337 +0x4c
github.com/rancher/rancher/pkg/controllers/user/endpoints.(*IngressEndpointsController).reconcileEndpointsForIngress(0xc012d3d200, 0xc00a78a168, 0x46947e0, 0xc015a9b418, 0x4693ea0)
/go/src/github.com/rancher/rancher/pkg/controllers/user/endpoints/ingress_endpoints.go:42 +0x53
github.com/rancher/rancher/pkg/controllers/user/endpoints.(*IngressEndpointsController).sync(0xc012d3d200, 0xc0092120f0, 0x2c, 0xc00a78a168, 0xc000078700, 0x7febebc8c008, 0x0, 0x0)
/go/src/github.com/rancher/rancher/pkg/controllers/user/endpoints/ingress_endpoints.go:35 +0x110
github.com/rancher/rancher/vendor/github.com/rancher/types/apis/extensions/v1beta1.(*ingressController).AddHandler.func1(0xc0092120f0, 0x2c, 0x3e319e0, 0xc00a78a168, 0xc0164facd8, 0x3, 0x3, 0x0)
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/extensions/v1beta1/zz_generated_ingress_controller.go:155 +0x63
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).syncHandler(0xc00e824980, 0x33c6760, 0xc00ee0ba50, 0x0, 0x0)
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:387 +0x371
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).processNextWorkItem(0xc00e824980, 0x0)
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:296 +0xef
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).runWorker(0xc00e824980)
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:284 +0x2b
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0078ec5c0)
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0078ec5c0, 0x3b9aca00, 0x0, 0x1, 0xc012d2c180)
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0078ec5c0, 0x3b9aca00, 0xc012d2c180)
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).run
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:276 +0xe8
```
