### ISSUE TITLE
Rancher server crash with 'panic: interface conversion: runtime.Object is *v1.Status, not *unstructured.Unstructured

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#23162]
Version: Master-head

Steps
1. Created a rancher server from master-head branch (8b1adfcdc80a)
2. Created a DO cluster

Seems like it crashed after creating the first snapshot 
Panic below:
```
2019-10-01 14:36:42.512487 I | mvcc: finished scheduled compaction at 3775 (took 1.338829ms)
2019/10/01 14:36:58 [INFO] [etcd-backup] Cluster [c-f5rfh] has no backups, creating first backup
2019/10/01 14:36:58 [INFO] [etcd-backup] Cluster [c-f5rfh] new backup is created: c-f5rfh-rl-nhmwh
2019/10/01 14:37:03 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:33347
2019/10/01 14:37:03 [INFO] Starting saving snapshot on etcd hosts
2019/10/01 14:37:03 [INFO] [dialer] Setup tunnel for host [abcd]
2019/10/01 14:37:03 [INFO] [etcd] Running snapshot save once on host [abcd]
2019/10/01 14:37:03 [INFO] Checking if image [rancher/rke-tools:v0.1.50] exists on host [abcd], try #1



2019/10/01 14:37:04 [INFO] Image [rancher/rke-tools:v0.1.50] exists on host [abcd]
2019/10/01 14:37:04 [INFO] Starting container [etcd-snapshot-once] on host [abcd], try #1



2019/10/01 14:37:04 [INFO] [etcd] Successfully started [etcd-snapshot-once] container on host [abcd]
2019/10/01 14:37:04 [INFO] Waiting for [etcd-snapshot-once] container to exit on host [abcd]
2019/10/01 14:37:05 [INFO] Removing container [etcd-snapshot-once] on host [abcd], try rancher/rancher#1
2019/10/01 14:37:06 [INFO] Finished saving/uploading snapshot [c-f5rfh-rl-nhmwh_2019-10-01T14:36:58Z] on all etcd hosts
2019/10/01 14:37:06 [INFO] kontainerdriver rancherkubernetesengine stopped
2019-10-01 14:41:42.512792 I | mvcc: store.index: compact 4865
2019-10-01 14:41:42.515605 I | mvcc: finished scheduled compaction at 4865 (took 1.964331ms)
2019/10/01 14:45:20 http: TLS handshake error from 127.0.0.1:46620: EOF
2019-10-01 14:46:42.516115 I | mvcc: store.index: compact 5500
2019-10-01 14:46:42.518309 I | mvcc: finished scheduled compaction at 5500 (took 1.212098ms)
panic: interface conversion: runtime.Object is *v1.Status, not *unstructured.Unstructured

goroutine 6973 [running]:
github.com/rancher/rancher/vendor/github.com/rancher/norman/store/proxy.(*Store).realWatch.func2(0xc00326c3c0, 0xc000e943c0, 0xc00340afc0, 0xc000f0cd20, 0xc0014342a0, 0xc002c74680)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/proxy/proxy_store.go:318 +0x2e3
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/store/proxy.(*Store).realWatch
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/proxy/proxy_store.go:316 +0x616





```

**Comment by soumyalj** [comment]
Observed the crash on another setup too with the same stack trace

**Comment by jiaqiluo** [comment]
version: `master-head` de4448e87 

in my case, the rancher container restarts, but the error message in the log is the same as the issue

```
goroutine 5917 [running]:
github.com/rancher/rancher/vendor/github.com/rancher/norman/store/proxy.(*Store).realWatch.func2(0xc0024c8600, 0xc000d3d7c0, 0xc000b83560, 0xc0011c52c0, 0xc0014d3200, 0xc00111bbb0)
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/proxy/proxy_store.go:318 +0x2e3
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/store/proxy.(*Store).realWatch
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/proxy/proxy_store.go:316 +0x616
```

**Comment by soumyalj** [comment]
Tested with build from master-head (c4917516a922)
1. Created a DO cluster. 
2. Created workloads, HPAs, enabled monitoring etc in the cluster. 

Did not see a panic or restarts in the setup. The setup was running for around 3 hours
```
sudo docker inspect 2d91ea9dbfba|grep -i RESTART
            "Restarting": false,
        "RestartCount": 0,
            "RestartPolicy": {

```
