### ISSUE TITLE
Rancher installation with pod status Errors/CrashLoopBackOff - panic creating driver

### ISSUE THREAD

**Issue by tungstenostrich** [rancher/rancher#23204]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.8
- Installation option (single install/HA): HA installed through helm

**Steps to reproduce (least amount of steps as possible):**

`helm install rancher-stable/rancher --name rancher --namespace cattle-system --set hostname=HOSTNAME  --set tls=external --wait`

**Result:**

Soon after the installation all rancher pods have errors and will eventually end up in status CrashLoopBackOff. The web gui does work to some extend but there are things missing like the _Security/Authentication_ menu section and there are no kubernetes and infrastructure providers in the _Add Cluster_ section. After some minutes the gui wlil be gone and all there shows up is an http _502 Bad gateway_ from nginx.
 

**Other details that may be helpful:**
Following the logs of the rancher pods with`kubectl logs -n cattle-system -l app=rancher -f` I got:

```
2019/10/03 14:28:22 [INFO] Starting API controllers
W1003 14:28:23.105987       7 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.NodePool ended with: too old resource version: 20843528 (20843543)
W1003 14:28:23.106200       7 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.NodeTemplate ended with: too old resource version: 20843528 (20843561)
W1003 14:28:23.107838       7 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.ClusterCatalog ended with: too old resource version: 20843528 (20843543)
W1003 14:28:23.132180       7 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.ClusterRegistrationToken ended with: too old resource version: 20843528 (20843543)
W1003 14:28:23.134708       7 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.MultiClusterApp ended with: too old resource version: 20843528 (20843543)
W1003 14:28:23.142000       7 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.SourceCodeCredential ended with: too old resource version: 20843528 (20843543)
2019/10/03 14:28:23 [INFO] Listening on :443
2019/10/03 14:28:23 [INFO] Listening on :80
I1003 14:28:24.014016       7 leaderelection.go:187] attempting to acquire leader lease  kube-system/cattle-controllers...
2019/10/03 14:28:21 [INFO] password fields {"elasticsearchConfig":{"authPassword":".."},"fluentForwarderConfig":{"fluentServers":{"password":"..","sharedKey":".."}},"kafkaConfig":{"saslPassword":".."},"splunkConfig":{"token":".."},"syslogConfig":{"token":".."}}
2019/10/03 14:28:21 [INFO] password fields {"elasticsearchConfig":{"authPassword":".."},"fluentForwarderConfig":{"fluentServers":{"password":"..","sharedKey":".."}},"kafkaConfig":{"saslPassword":".."},"splunkConfig":{"token":".."},"syslogConfig":{"token":".."}}
2019/10/03 14:28:21 [INFO] Starting API controllers
W1003 14:28:21.741540       6 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.UserAttribute ended with: too old resource version: 20843528 (20843567)
W1003 14:28:21.751468       6 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.NodeDriver ended with: too old resource version: 20843528 (20843632)
W1003 14:28:21.752102       6 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.DynamicSchema ended with: too old resource version: 20843528 (20843632)
W1003 14:28:21.755318       6 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.ClusterRegistrationToken ended with: too old resource version: 20843528 (20843543)
2019/10/03 14:28:18 [INFO] Starting API controllers
W1003 14:28:18.981795       6 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.MultiClusterApp ended with: too old resource version: 20843528 (20843543)
W1003 14:28:18.983559       6 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.PipelineExecution ended with: too old resource version: 20843528 (20843543)
W1003 14:28:18.992830       6 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.DynamicSchema ended with: too old resource version: 20843528 (20843632)
W1003 14:28:18.992944       6 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.GlobalDNS ended with: too old resource version: 20843528 (20843567)
2019/10/03 14:28:21 [INFO] Listening on :443
2019/10/03 14:28:21 [INFO] Listening on :80
I1003 14:28:22.511608       6 leaderelection.go:187] attempting to acquire leader lease  kube-system/cattle-controllers...
W1003 14:28:18.995179       6 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.CatalogTemplate ended with: too old resource version: 20843528 (20843543)
W1003 14:28:19.004853       6 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.MultiClusterAppRevision ended with: too old resource version: 20843528 (20843543)
2019/10/03 14:28:19 [INFO] Listening on :443
2019/10/03 14:28:19 [INFO] Listening on :80
I1003 14:28:20.592355       6 leaderelection.go:187] attempting to acquire leader lease  kube-system/cattle-controllers...
2019/10/03 14:28:34 [INFO] Adding peer wss://172.19.12.44/v3/connect, 172.19.12.44
2019/10/03 14:28:34 [INFO] Adding peer wss://172.19.12.44/v3/connect, 172.19.12.44
2019/10/03 14:28:34 [ERROR] Failed to connect to peer wss://172.19.12.44/v3/connect [local ID=172.19.26.45]: websocket: bad handshake
2019/10/03 14:28:34 [ERROR] Failed to connect to peer wss://172.19.12.44/v3/connect [local ID=172.19.61.46]: websocket: bad handshake
2019/10/03 14:28:39 [INFO] Adding peer wss://172.19.26.45/v3/connect, 172.19.26.45
2019/10/03 14:28:39 [INFO] Adding peer wss://172.19.26.45/v3/connect, 172.19.26.45
2019/10/03 14:28:39 [ERROR] Failed to connect to peer wss://172.19.12.44/v3/connect [local ID=172.19.61.46]: websocket: bad handshake
2019/10/03 14:28:39 [INFO] Handling backend connection request [172.19.26.45]
2019/10/03 14:28:39 [INFO] Handling backend connection request [172.19.12.44]
2019/10/03 14:28:39 [ERROR] Failed to connect to peer wss://172.19.26.45/v3/connect [local ID=172.19.61.46]: websocket: bad handshake
2019/10/03 14:28:44 [ERROR] Failed to connect to peer wss://172.19.12.44/v3/connect [local ID=172.19.61.46]: websocket: bad handshake
2019/10/03 14:28:45 [ERROR] Failed to connect to peer wss://172.19.26.45/v3/connect [local ID=172.19.61.46]: websocket: bad handshake
2019/10/03 14:28:49 [ERROR] Failed to connect to peer wss://172.19.12.44/v3/connect [local ID=172.19.61.46]: websocket: bad handshake
2019/10/03 14:28:50 [ERROR] Failed to connect to peer wss://172.19.26.45/v3/connect [local ID=172.19.61.46]: websocket: bad handshake
2019/10/03 14:28:51 [INFO] Adding peer wss://172.19.61.46/v3/connect, 172.19.61.46
2019/10/03 14:28:51 [INFO] Adding peer wss://172.19.61.46/v3/connect, 172.19.61.46
2019/10/03 14:28:52 [INFO] Handling backend connection request [172.19.12.44]
2019/10/03 14:28:52 [INFO] Handling backend connection request [172.19.26.45]
2019/10/03 14:28:54 [INFO] Handling backend connection request [172.19.61.46]
2019/10/03 14:28:55 [INFO] Handling backend connection request [172.19.61.46]
I1003 14:29:07.444309       6 leaderelection.go:196] successfully acquired lease kube-system/cattle-controllers
2019/10/03 14:29:07 [INFO] Starting catalog controller
2019/10/03 14:29:07 [INFO] Starting project-level catalog controller
2019/10/03 14:29:07 [INFO] Starting cluster-level catalog controller
2019/10/03 14:29:07 [INFO] Starting management controllers
W1003 14:29:07.605439       6 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.GlobalDNSProvider ended with: too old resource version: 20843563 (20843633)
W1003 14:29:07.606781       6 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.App ended with: too old resource version: 20843528 (20843543)
W1003 14:29:07.607199       6 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.GlobalDNS ended with: too old resource version: 20843528 (20843567)
W1003 14:29:07.609490       6 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.GlobalDNS ended with: too old resource version: 20843528 (20843567)
W1003 14:29:07.619843       6 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.NodeDriver ended with: too old resource version: 20843528 (20843632)
W1003 14:29:07.628346       6 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.DynamicSchema ended with: too old resource version: 20843528 (20843632)
W1003 14:29:07.629220       6 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.EtcdBackup ended with: too old resource version: 20843565 (20843633)
2019/10/03 14:29:07 [INFO] remove kontainerdriver googlekubernetesengine
2019/10/03 14:29:07 [INFO] remove kontainerdriver azurekubernetesservice
2019/10/03 14:29:07 [INFO] remove kontainerdriver amazonelasticcontainerservice
2019/10/03 14:29:07 [INFO] remove kontainerdriver baiducloudcontainerengine
2019/10/03 14:29:07 [INFO] remove kontainerdriver aliyunkubernetescontainerservice
2019/10/03 14:29:07 [INFO] remove kontainerdriver tencentkubernetesengine
2019/10/03 14:29:07 [INFO] remove kontainerdriver huaweicontainercloudengine
2019/10/03 14:29:07 [ERROR] KontainerDriverController azurekubernetesservice [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:29:07 [ERROR] KontainerDriverController googlekubernetesengine [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:29:07 [ERROR] KontainerDriverController tencentkubernetesengine [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:29:07 [ERROR] KontainerDriverController huaweicontainercloudengine [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:29:07 [ERROR] KontainerDriverController aliyunkubernetescontainerservice [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:29:07 [ERROR] KontainerDriverController amazonelasticcontainerservice [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:29:07 [ERROR] KontainerDriverController baiducloudcontainerengine [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:29:07 [INFO] Reconciling GlobalRoles
2019/10/03 14:29:07 [INFO] Reconciling RoleTemplates
2019/10/03 14:29:08 [INFO] remove kontainerdriver azurekubernetesservice
2019/10/03 14:29:08 [INFO] remove kontainerdriver googlekubernetesengine
2019/10/03 14:29:08 [ERROR] KontainerDriverController googlekubernetesengine [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:29:08 [ERROR] KontainerDriverController azurekubernetesservice [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:29:08 [INFO] remove kontainerdriver tencentkubernetesengine
2019/10/03 14:29:08 [INFO] remove kontainerdriver huaweicontainercloudengine
2019/10/03 14:29:08 [INFO] remove kontainerdriver aliyunkubernetescontainerservice
2019/10/03 14:29:08 [ERROR] KontainerDriverController tencentkubernetesengine [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:29:08 [INFO] remove kontainerdriver amazonelasticcontainerservice
2019/10/03 14:29:08 [ERROR] KontainerDriverController huaweicontainercloudengine [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:29:08 [ERROR] KontainerDriverController aliyunkubernetescontainerservice [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:29:08 [ERROR] KontainerDriverController amazonelasticcontainerservice [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:29:08 [INFO] remove kontainerdriver baiducloudcontainerengine
2019/10/03 14:29:08 [ERROR] KontainerDriverController baiducloudcontainerengine [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:29:08 [INFO] adding kontainer driver rancherKubernetesEngine
panic: error creating driver: the server does not allow this method on the requested resource (post kontainerdrivers.meta.k8s.io)
2019/10/03 14:29:08 [INFO] error in remotedialer server [400]: websocket: close 1006 unexpected EOF

2019/10/03 14:29:08 [INFO] error in remotedialer server [400]: websocket: close 1006 unexpected EOF
2019/10/03 14:29:08 [ERROR] Failed to serve peer connection 172.19.26.45: websocket: close 1006 unexpected EOF
goroutine 1633 [running]:
github.com/rancher/rancher/app.Run.func1(0x423c340, 0xc0024b21c0)
	/go/src/github.com/rancher/rancher/app/app.go:130 +0x369
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/leader.run.func1
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/leader/leader.go:67 +0x46
2019/10/03 14:29:08 [ERROR] Failed to serve peer connection 172.19.26.45: read tcp 172.19.12.44:51074->172.19.26.45:443: read: connection reset by peer
2019/10/03 14:29:09 [INFO] Removing peer 172.19.26.45
2019/10/03 14:29:09 [INFO] Removing peer 172.19.26.45
rpc error: code = Unknown desc = Error: No such container: 4f2c633d68f553f2f6c0a1e2257d17c48ea0d759b55590c6944beeb7a4be906f

2019/10/03 14:29:48 [ERROR] API error response 401 for POST /v3-public/localProviders/local?action=login. Cause: crypto/bcrypt: hashedPassword is not the hash of the given password
2019/10/03 14:30:05 [ERROR] API error response 401 for POST /v3-public/localProviders/local?action=login. Cause: crypto/bcrypt: hashedPassword is not the hash of the given password
I1003 14:31:33.004742       7 leaderelection.go:196] successfully acquired lease kube-system/cattle-controllers
2019/10/03 14:31:33 [INFO] Starting catalog controller
2019/10/03 14:31:33 [INFO] Starting project-level catalog controller
2019/10/03 14:31:33 [INFO] Starting cluster-level catalog controller
2019/10/03 14:31:33 [INFO] Starting management controllers
W1003 14:31:33.143156       7 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.App ended with: too old resource version: 20843528 (20843543)
W1003 14:31:33.153585       7 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.NodeDriver ended with: too old resource version: 20843528 (20843632)
W1003 14:31:33.161119       7 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.ComposeConfig ended with: too old resource version: 20843563 (20843633)
2019/10/03 14:31:33 [ERROR] UserAttributeController user-bcllg [mgmt-auth-userattributes-controller] failed with : refresh daemon not yet initialized
2019/10/03 14:31:33 [INFO] remove kontainerdriver huaweicontainercloudengine
2019/10/03 14:31:33 [INFO] remove kontainerdriver googlekubernetesengine
2019/10/03 14:31:33 [INFO] remove kontainerdriver azurekubernetesservice
2019/10/03 14:31:33 [INFO] remove kontainerdriver amazonelasticcontainerservice
2019/10/03 14:31:33 [INFO] remove kontainerdriver baiducloudcontainerengine
2019/10/03 14:31:33 [INFO] remove kontainerdriver aliyunkubernetescontainerservice
2019/10/03 14:31:33 [INFO] remove kontainerdriver tencentkubernetesengine
2019/10/03 14:31:33 [INFO] Reconciling GlobalRoles
2019/10/03 14:31:33 [ERROR] KontainerDriverController amazonelasticcontainerservice [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:31:33 [ERROR] KontainerDriverController baiducloudcontainerengine [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:31:33 [ERROR] KontainerDriverController aliyunkubernetescontainerservice [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:31:33 [ERROR] KontainerDriverController huaweicontainercloudengine [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:31:33 [INFO] Reconciling RoleTemplates
2019/10/03 14:31:33 [ERROR] KontainerDriverController tencentkubernetesengine [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:31:33 [ERROR] KontainerDriverController googlekubernetesengine [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:31:33 [ERROR] KontainerDriverController azurekubernetesservice [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:31:33 [ERROR] UserAttributeController user-bcllg [mgmt-auth-userattributes-controller] failed with : refresh daemon not yet initialized
2019/10/03 14:31:33 [INFO] remove kontainerdriver amazonelasticcontainerservice
2019/10/03 14:31:33 [ERROR] KontainerDriverController amazonelasticcontainerservice [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:31:33 [INFO] remove kontainerdriver baiducloudcontainerengine
2019/10/03 14:31:33 [INFO] remove kontainerdriver aliyunkubernetescontainerservice
2019/10/03 14:31:33 [INFO] remove kontainerdriver huaweicontainercloudengine
2019/10/03 14:31:33 [INFO] remove kontainerdriver tencentkubernetesengine
2019/10/03 14:31:33 [INFO] remove kontainerdriver googlekubernetesengine
2019/10/03 14:31:33 [INFO] remove kontainerdriver azurekubernetesservice
2019/10/03 14:31:33 [ERROR] KontainerDriverController tencentkubernetesengine [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:31:33 [ERROR] KontainerDriverController aliyunkubernetescontainerservice [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:31:33 [ERROR] KontainerDriverController baiducloudcontainerengine [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:31:33 [ERROR] KontainerDriverController huaweicontainercloudengine [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:31:33 [ERROR] KontainerDriverController azurekubernetesservice [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:31:33 [ERROR] KontainerDriverController googlekubernetesengine [mgmt-kontainer-driver-lifecycle] failed with : error getting schema: dynamicSchema.management.cattle.io "cluster" not found
2019/10/03 14:31:33 [INFO] adding kontainer driver rancherKubernetesEngine
panic: error creating driver: the server does not allow this method on the requested resource (post kontainerdrivers.meta.k8s.io)

goroutine 2143 [running]:
github.com/rancher/rancher/app.Run.func1(0x423c340, 0xc00119d700)
	/go/src/github.com/rancher/rancher/app/app.go:130 +0x369
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/leader.run.func1
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/leader/leader.go:67 +0x46
2019/10/03 14:31:33 [INFO] error in remotedialer server [400]: websocket: close 1006 unexpected EOF
2019/10/03 14:31:33 [ERROR] Failed to serve peer connection 172.19.61.46: read tcp 172.19.12.44:38332->172.19.61.46:443: read: connection reset by peer
2019/10/03 14:31:34 [INFO] Removing peer 172.19.61.46
rpc error: code = Unknown desc = Error: No such container: 073ed35e3e3c809cf2cc0016313127203b603b051bfa69fba4d24fb85a1faf172019/10/03 14:31:43 [INFO] Received SIGTERM, cancelling
2019/10/03 14:31:43 [INFO] Shutting down ClusterRoleBindingController controller
2019/10/03 14:31:43 [FATAL] context canceled
rpc error: code = Unknown desc = Error: No such container: dcd83979d41afaf01d855dcdc88932a12e80f5710178885b1403399780000ab6
```

**Comment by tungstenostrich** [comment]
Sorry, I totally forgot to add one more thing that might be important. The very first installation of rancher did succeed on the same kubernetes cluster as above. I then removed rancher completely using `system-tools remove`and `helm delete --purge rancher`. This left me with some kubernetes namespaces hanging in status _Terminating_. I removed those by first obtaining their json representation, then removing any finalizers from it and feeding it back to the kubernetes API. After that every thing looked good and I ran `system-tools remove`once more just to make sure everything is fine, which it was.

**Comment by superseb** [comment]
Please provide more info on where you are installing this on. If you are using RKE, please share what version and the `cluster.yml` used. If not, please specify on what you are installing this and how to reproduce using the exact same settings.

**Comment by tungstenostrich** [comment]
We are using Canonical's charmed kubernetes. The kubernetes version is 1.14.7.

**Comment by superseb** [comment]
Can you please supply full configuration/commands used when setting up the cluster?

**Comment by tungstenostrich** [comment]
I'll try to reproduce the error and then post the exact commands/configurations I used. This will take some time, hopefully I have the results by next week.

**Comment by tungstenostrich** [comment]
I couldn't reproduce the original problem. I freshly installed the cluster and everything works as expected.
Sorry for having bothered you.

**Comment by vishnuhd** [comment]
@tungstenostrich @superseb - We are facing the exact same issue. We too user `system-tools` to make sure everything is removed, but after reinstalling its stuck in the above-mentioned errors.

**Comment by vishnuhd** [comment]
I was able to provision Rancher in same cluster. For some reason `system-tools` was not able to delete the CRDs, I had to delete them manually, following this comment - https://github.com/rancher/rancher/issues/14715#issuecomment-564911890. 

Hope this helps someone.
