### ISSUE TITLE
Pipeline fails at setting up executors

### ISSUE THREAD

**Issue by tnaduc** [rancher/rancher#23513]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
setup a pipeline including hook to Github
run the pipeline

**Result:**
Pipeline hangs at "setting up executors"

**Other details that may be helpful:**
Jenkins master doesn't spin up any slave pod

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):Cloud
- Kubernetes version (use `kubectl version`):v1.16.2

Jenkins master pod logs
```
Oct 17, 2019 11:12:03 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
INFO: Terminating Kubernetes instance for agent buildpod.pipeline-p-r2v4h-4.1-9d6r3-2w25c
ERROR: Failed to delete pod for agent p-5m74m-pipeline/buildpod.pipeline-p-r2v4h-4.1-9d6r3-2w25c: not found
Disconnected computer buildpod.pipeline-p-r2v4h-4.1-9d6r3-2w25c
Oct 17, 2019 11:12:03 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave deleteSlavePod
WARNING: Failed to delete pod for agent p-5m74m-pipeline/buildpod.pipeline-p-r2v4h-4.1-9d6r3-2w25c: not found
Oct 17, 2019 11:12:03 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
INFO: Disconnected computer buildpod.pipeline-p-r2v4h-4.1-9d6r3-2w25c
Oct 17, 2019 11:12:05 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
INFO: Excess workload after pending Kubernetes agents: 1
Oct 17, 2019 11:12:05 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
INFO: Template for label buildpod.pipeline_p_r2v4h_4.1: Kubernetes Pod Template
Oct 17, 2019 11:12:05 AM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning Kubernetes Pod Template from kubernetes with 1 executors. Remaining excess workload: 0
Oct 17, 2019 11:12:07 AM hudson.slaves.NodeProvisioner$2 run
INFO: Kubernetes Pod Template provisioning successfully completed. We have now 2 computer(s)
Oct 17, 2019 11:12:07 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
INFO: Excess workload after pending Kubernetes agents: 0
Oct 17, 2019 11:12:07 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
INFO: Template for label buildpod.pipeline_p_r2v4h_4.1: Kubernetes Pod Template
Oct 17, 2019 11:12:07 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
WARNING: Error in provisioning; agent=KubernetesSlave name: buildpod.pipeline-p-r2v4h-4.1-9d6r3-7zs0c, template=PodTemplate{, name='buildpod.pipeline_p_r2v4h_4.1-9d6r3', namespace='p-5m74m-pipeline', instanceCap=1, label='buildpod.pipeline_p_r2v4h_4.1', nodeUsageMode=EXCLUSIVE, annotations=[org.csanchez.jenkins.plugins.kubernetes.PodAnnotation@aab9c821]}
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://kubernetes.default/api/v1/namespaces/p-5m74m-pipeline/pods. Message: Pod "buildpod.pipeline-p-r2v4h-4.1-9d6r3-7zs0c" is invalid: [spec.containers[1].env[5].valueFrom.secretKeyRef.name: Invalid value: "p-5m74m-": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.containers[1].env[6].valueFrom.secretKeyRef.name: Invalid value: "p-5m74m-": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.containers[1].env[5].valueFrom.secretKeyRef.name, message=Invalid value: "p-5m74m-": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), reason=FieldValueInvalid, additionalProperties={}), StatusCause(field=spec.containers[1].env[6].valueFrom.secretKeyRef.name, message=Invalid value: "p-5m74m-": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), reason=FieldValueInvalid, additionalProperties={})], group=null, kind=Pod, name=buildpod.pipeline-p-r2v4h-4.1-9d6r3-7zs0c, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Pod "buildpod.pipeline-p-r2v4h-4.1-9d6r3-7zs0c" is
invalid: [spec.containers[1].env[5].valueFrom.secretKeyRef.name: Invalid value: "p-5m74m-": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.containers[1].env[6].valueFrom.secretKeyRef.name: Invalid value: "p-5m74m-": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')], metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:503)
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:442)
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:406)
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:365)
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:234)
at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:796)
at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:326)
at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:322)
at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:124)
at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:294)
at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)```

**Comment by tnaduc** [comment]
Look like the key issue is here:

```
Message: Pod "buildpod.pipeline-p-r2v4h-4.1-9d6r3-7zs0c" is invalid: [spec.containers[1].env[5].valueFrom.secretKeyRef.name: Invalid value: "p-5m74m-": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

It is interesting that the pipeline namespace is : `p-5m74m-pipeline`

**Comment by gitlawr** [comment]
Given the logs, it seems that an invalid secret reference is used. Can you share the .rancher-pipeline.yaml file with private info detached?

**Comment by tnaduc** [comment]
Hi @gitlawr 
Thanks for responding. Here is my .rancher-pipeline.yaml:

```
stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: analytics-docker/income-pred:latest
      pushRemote: true
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: Deploy Workload
  steps:
  - applyYamlConfig:
      path: ./loan-predict-v1.yaml
- name: Deploy Ingress
  steps:
  - applyYamlConfig:
      path: ./loan-predict-ingress.yaml
timeout: 30
```

**Comment by gitlawr** [comment]
I think the cause is that in the first step, `pushRemote` is set but the registry is not configured, if you've added registry credential in the project, can you update the first step to 
```
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: analytics-docker/income-pred:latest
      pushRemote: true
      registry: yourregistry.com #add this
```
Or remove `pushRemote: true` if you would like to use the internal registry

**Comment by tnaduc** [comment]
Hi @gitlawr ,

Thank you. Yes, that was the issue, after removing the line the pipeline works normally and I tested uploading to a private registry, it worked as well.

Thank you very much for the your help.
