### ISSUE TITLE
Bitbucket Pipeline Git Clone failing with SSL_ERROR_SYSCALL

### ISSUE THREAD

**Issue by l0wskilled** [rancher/rancher#23537]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Add bitbucket pipeline with a single clone step.

**Result:**
```
Cloning the remote Git repository
Cloning repository https://bitbucket.org/***.git
 > git init /home/jenkins/agent/workspace/pipeline_p-pfdqn-8 # timeout=10
Fetching upstream changes from https://bitbucket.org/***.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git fetch --tags --progress https://bitbucket.org/***.git +refs/heads/*:refs/remotes/origin/*
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --tags --progress https://bitbucket.org/***.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: fatal: unable to access 'https://bitbucket.org/***.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to bitbucket.org:443 

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2099)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1791)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$400(CliGitAPIImpl.java:79)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:472)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:685)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
	at hudson.remoting.UserRequest.perform(UserRequest.java:181)
	at hudson.remoting.UserRequest.perform(UserRequest.java:52)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at hudson.remoting.Engine$1$1.run(Engine.java:98)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from localhost/127.0.0.1:54638
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
		at hudson.remoting.UserResponse.retrieve(UserRequest.java:389)
		at hudson.remoting.Channel.call(Channel.java:957)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
		at com.sun.proxy.$Proxy86.execute(Unknown Source)
		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1146)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1186)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:124)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		... 1 more
```
**Other details that may be helpful:**
Did the normal authorization on bitbucket as a consumer. Added Callback URL to `https://rancher.domain/verify-auth`.
Gave Permissions (as stated) for: 
Account: Read
Pull Requests: Read Write
Projects: Read
Webhooks: Read and Write

The funny thing is, rancher is able to push changes on .rancher-pipeline.yml to bitbucket.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.3.1
- Installation option (single install/HA):
single install

**Comment by l0wskilled** [comment]
So after deleting `docker-registry`, `jenkins` and `minio` from the workloads as well as removing the pipeline namespace, then removing the pipeline for the repository and re-enabling the pipeline for the repository, resulting in making Rancher recreate the pipeline setup (jenkins, etc.) for serveral times always resulting in only the first run to succeed. It now seems to be working on each run, but even after the fourth run Rancher says "First time build. Skipping changelog."
```
Cloning the remote Git repository
Cloning repository https://bitbucket.org/***.git
 > git init /home/jenkins/agent/workspace/pipeline_p-vlvs7-4 # timeout=10
Fetching upstream changes from https://bitbucket.org/***.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git fetch --tags --progress https://bitbucket.org/***.git +refs/heads/*:refs/remotes/origin/*
 > git config remote.origin.url https://bitbucket.org/***.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://bitbucket.org/***.git # timeout=10
Fetching upstream changes from https://bitbucket.org/***.git
using GIT_ASKPASS to set credentials 
 > git fetch --tags --progress https://bitbucket.org/***.git +rancher:refs/remotes/local/temp
Checking out Revision bac1c98a9392869411380fb925f0321fdc3b0ff9 (local/temp)
Commit message: "Update .rancher-pipeline.yml file"
First time build. Skipping changelog.
```

Not sure if this was a problem on bitbuckets sites. Im not too fond of their service.

**Comment by gitlawr** [comment]
Are you behind a proxy?

**Comment by l0wskilled** [comment]
Im not sure. I guess not.

**Comment by l0wskilled** [comment]
Not sure if this is a dns error. When the cloning works and im in the running script thing, i launch a container and do `apt-get update` which fails to resolve security.debian.org.
It's accessible by the host though.

**Comment by l0wskilled** [comment]
So i moved the whole stuff now to github to try it out. But it's the same. This just raised more questions.
```
Cloning the remote Git repository
Cloning repository https://github.com/l0wskilled/test.git
 > git init /home/jenkins/agent/workspace/pipeline_p-jvbtf-1 # timeout=10
Fetching upstream changes from https://github.com/l0wskilled/test.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git fetch --tags --progress https://github.com/l0wskilled/test.git +refs/heads/*:refs/remotes/origin/*
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/l0wskilled/test.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: fatal: unable to access 'https://github.com/l0wskilled/test.git/': Failed to connect to github.com port 443: Operation timed out
```

**Comment by l0wskilled** [comment]
I checked the host before by running nslookup and ping to ensure that the domain is reachable.
But now that I've went deeper and actually try to run `git fetch --tags --progress -v https://github.com/l0wskilled/test.git +refs/heads/*:refs/remotes/origin/*` i don't get a username input request every few requests. So this problem is actually on the host system.

**Comment by l0wskilled** [comment]
Even `telnet github.com 443` shows this problem. Sometimes it establishes a connection sometimes it doesn't.

**Comment by l0wskilled** [comment]
So I've just setup a new node. And between each step tested the git fetch. After rancher finished setting up the node (adding it to the same cluster) the connection again timed out.

**Comment by l0wskilled** [comment]
So now created a new node based on rancheros instead of ubuntu 18.04.
It now fails on the run script test of the pipeline.
Step Type: Run Script
Base Image: php:7.3
Shell:
```
apt-get update
apt-get install -y --no-install-recommends git zip

docker-php-ext-install zip curl dev gd mbstring xml xmlrpc bcmath mongo
```

Error in Pipeline: 
```
+ apt-get update
Err:3 http://security.debian.org/debian-security buster/updates InRelease
  Could not connect to security.debian.org:80 (212.211.132.250), connection timed out Could not connect to security.debian.org:80 (217.196.149.233), connection timed out
Err:1 http://cdn-fastly.deb.debian.org/debian buster InRelease
  Could not connect to cdn-fastly.deb.debian.org:80 (151.101.12.204), connection timed out
Err:2 http://cdn-fastly.deb.debian.org/debian buster-updates InRelease
  Unable to connect to cdn-fastly.deb.debian.org:http:
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/buster/InRelease  Could not connect to cdn-fastly.deb.debian.org:80 (151.101.12.204), connection timed out
W: Failed to fetch http://security.debian.org/debian-security/dists/buster/updates/InRelease  Could not connect to security.debian.org:80 (212.211.132.250), connection timed out Could not connect to security.debian.org:80 (217.196.149.233), connection timed out
W: Failed to fetch http://deb.debian.org/debian/dists/buster-updates/InRelease  Unable to connect to cdn-fastly.deb.debian.org:http:
W: Some index files failed to download. They have been ignored, or old ones used instead.
+ apt-get install -y --no-install-recommends git zip
Reading package lists...
Building dependency tree...
Reading state information...
Package git is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'git' has no installation candidate
E: Unable to locate package zip
```

Running the same stuff on the node using docker works:
```
# docker run php:7.3 /bin/bash -c "apt-get update && apt-get install -y --no-install-recommends git zip"
Get:1 http://security-cdn.debian.org/debian-security buster/updates InRelease [39.1 kB]
Get:2 http://security-cdn.debian.org/debian-security buster/updates/main amd64 Packages [99.9 kB]
Get:3 http://cdn-fastly.deb.debian.org/debian buster InRelease [122 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian buster-updates InRelease [49.3 kB]
Get:5 http://cdn-fastly.deb.debian.org/debian buster/main amd64 Packages [7899 kB]
Get:6 http://cdn-fastly.deb.debian.org/debian buster-updates/main amd64 Packages [5792 B]
Fetched 8214 kB in 2s (4146 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following package was automatically installed and is no longer required:
  lsb-base
Use 'apt autoremove' to remove it.
The following additional packages will be installed:
  git-man libcurl3-gnutls liberror-perl libexpat1 libpcre2-8-0
Suggested packages:
  gettext-base git-daemon-run | git-daemon-sysvinit git-doc git-el git-email
  git-gui gitk gitweb git-cvs git-mediawiki git-svn
Recommended packages:
  less ssh-client unzip
The following NEW packages will be installed:
  git git-man libcurl3-gnutls liberror-perl libexpat1 libpcre2-8-0 zip
0 upgraded, 7 newly installed, 0 to remove and 0 not upgraded.
Need to get 8154 kB of archives.
After this operation, 40.4 MB of additional disk space will be used.
Get:1 http://security-cdn.debian.org/debian-security buster/updates/main amd64 libexpat1 amd64 2.2.6-2+deb10u1 [106 kB]
Get:2 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libcurl3-gnutls amd64 7.64.0-4 [329 kB]
Get:3 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libpcre2-8-0 amd64 10.32-5 [213 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian buster/main amd64 liberror-perl all 0.17027-2 [30.9 kB]
Get:5 http://cdn-fastly.deb.debian.org/debian buster/main amd64 git-man all 1:2.20.1-2 [1619 kB]
Get:6 http://cdn-fastly.deb.debian.org/debian buster/main amd64 git amd64 1:2.20.1-2 [5621 kB]
Get:7 http://cdn-fastly.deb.debian.org/debian buster/main amd64 zip amd64 3.0-11+b1 [234 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 8154 kB in 0s (16.9 MB/s)
Selecting previously unselected package libcurl3-gnutls:amd64.
(Reading database ... 12673 files and directories currently installed.)
Preparing to unpack .../0-libcurl3-gnutls_7.64.0-4_amd64.deb ...
Unpacking libcurl3-gnutls:amd64 (7.64.0-4) ...
Selecting previously unselected package libexpat1:amd64.
Preparing to unpack .../1-libexpat1_2.2.6-2+deb10u1_amd64.deb ...
Unpacking libexpat1:amd64 (2.2.6-2+deb10u1) ...
Selecting previously unselected package libpcre2-8-0:amd64.
Preparing to unpack .../2-libpcre2-8-0_10.32-5_amd64.deb ...
Unpacking libpcre2-8-0:amd64 (10.32-5) ...
Selecting previously unselected package liberror-perl.
Preparing to unpack .../3-liberror-perl_0.17027-2_all.deb ...
Unpacking liberror-perl (0.17027-2) ...
Selecting previously unselected package git-man.
Preparing to unpack .../4-git-man_1%3a2.20.1-2_all.deb ...
Unpacking git-man (1:2.20.1-2) ...
Selecting previously unselected package git.
Preparing to unpack .../5-git_1%3a2.20.1-2_amd64.deb ...
Unpacking git (1:2.20.1-2) ...
Selecting previously unselected package zip.
Preparing to unpack .../6-zip_3.0-11+b1_amd64.deb ...
Unpacking zip (3.0-11+b1) ...
Setting up libexpat1:amd64 (2.2.6-2+deb10u1) ...
Setting up libcurl3-gnutls:amd64 (7.64.0-4) ...
Setting up liberror-perl (0.17027-2) ...
Setting up zip (3.0-11+b1) ...
Setting up libpcre2-8-0:amd64 (10.32-5) ...
Setting up git-man (1:2.20.1-2) ...
Setting up git (1:2.20.1-2) ...
Processing triggers for libc-bin (2.28-10) ...
```

**Comment by l0wskilled** [comment]
I also get the occasional timeout to bitbucket with rancheros. This only happens after I executed the node initialization script from rancher, everything works fine before.

**Comment by l0wskilled** [comment]
I ran this to let rancher do the provision stuff:

```
sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.3.1 --server https://rancher.domain --token ************************** --ca-checksum ************************** --etcd --controlplane --worker
```

**Comment by l0wskilled** [comment]
So as I have no problems doing `docker run php:7.3 /bin/bash -c "apt-get update && apt-get install -y --no-install-recommends git zip"` i expect this has something to do with kubernetes. Gonna look into that.

**Comment by l0wskilled** [comment]
Deploying an instance of `ubuntu:xenial` ends also in `apt-get update` not working. Deploying an instance of `ubuntu:18.04` works like a charm.

**Comment by l0wskilled** [comment]
Running `docker run ubuntu:xenial /bin/bash -c "apt-get update"` on the node works perfectly.

**Comment by l0wskilled** [comment]
This is the cluster config:
```
# 
# Cluster Config
# 
answers: {}
docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
local_cluster_auth_endpoint:
  enabled: true
name: beta
# 
# Rancher Config
# 
rancher_kubernetes_engine_config:
  addon_job_timeout: 30
  authentication:
    strategy: x509|webhook
  authorization: {}
  bastion_host:
    ssh_agent_auth: false
  cloud_provider: {}
  ignore_docker_version: true
# 
# # Currently only nginx ingress provider is supported.
# # To disable ingress controller, set `provider: none`
# # To enable ingress on specific nodes, use the node_selector, eg:
#    provider: nginx
#    node_selector:
#      app: ingress
# 
  ingress:
    provider: nginx
  kubernetes_version: v1.15.5-rancher1-2
  monitoring:
    provider: metrics-server
# 
#   If you are using calico on AWS
# 
#    network:
#      plugin: calico
#      calico_network_provider:
#        cloud_provider: aws
# 
# # To specify flannel interface
# 
#    network:
#      plugin: flannel
#      flannel_network_provider:
#      iface: eth1
# 
# # To specify flannel interface for canal plugin
# 
#    network:
#      plugin: canal
#      canal_network_provider:
#        iface: eth1
# 
  network:
    options:
      flannel_backend_type: vxlan
    plugin: canal
  restore:
    restore: false
# 
#    services:
#      kube-api:
#        service_cluster_ip_range: 10.43.0.0/16
#      kube-controller:
#        cluster_cidr: 10.42.0.0/16
#        service_cluster_ip_range: 10.43.0.0/16
#      kubelet:
#        cluster_domain: cluster.local
#        cluster_dns_server: 10.43.0.10
# 
  services:
    etcd:
      backup_config:
        enabled: true
        interval_hours: 12
        retention: 6
        safe_timestamp: false
      creation: 12h
      extra_args:
        election-timeout: '5000'
        heartbeat-interval: '500'
      gid: 0
      retention: 72h
      snapshot: false
      uid: 0
    kube-api:
      always_pull_images: false
      pod_security_policy: false
      service_cluster_ip_range: 10.43.0.0/16
      service_node_port_range: 30000-32767
    kube-controller:
      cluster_cidr: 10.44.0.0/16
      service_cluster_ip_range: 10.43.0.0/16
    kubelet:
      cluster_dns_server: 10.43.0.10
      cluster_domain: cluster.local
      fail_swap_on: false
    kubeproxy: {}
    scheduler: {}
  ssh_agent_auth: false
```

**Comment by l0wskilled** [comment]
My server is behind a firewall which i didn't know was static.
So there was a rule für tcp ack 32768-65535 but as it seems the pods/containers aren't using that range from the linux kernel but use smaller ports too. So increasing this range to 10240-65535 solved my problem.
