### ISSUE TITLE
Pipeline - Jenkins error - DNS-1123

### ISSUE THREAD

**Issue by mkanakis** [rancher/rancher#24044]
**What kind of request is this (question/bug/enhancement/feature request):**
Today I set up the pipeline at rancher 2.3.1. At first it worked fine, but after a while it started producing the following error whenever I tried to a build an image.
It hangs at "Setting up executors". Even deleting everything plus the namespace as suggested elsewhere does not solve the problem.

The error log is from Jenkins pod.

**Steps to reproduce (least amount of steps as possible):**
Not really any steps, it just started hanging after a while.

**Result:**

> WARNING: Error in provisioning; agent=KubernetesSlave name: buildpod.pipeline-p-kp9v9-4.1-bgl4k-7lfz6, template=PodTemplate{, name='buildpod.pipeline_p_kp9v9_4.1-bgl4k', namespace='p-6bzh7-pipeline', instanceCap=1, label='buildpod.pipeline_p_kp9v9_4.1', nodeUsageMode=EXCLUSIVE, annotations=[org.csanchez.jenkins.plugins.kubernetes.PodAnnotation@aab9c821]} 
> io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://kubernetes.default/api/v1/namespaces/p-6bzh7-pipeline/pods. Message: Pod "buildpod.pipeline-p-kp9v9-4.1-bgl4k-7lfz6" is invalid: [spec.containers[1].env[13].name: Required value, spec.containers[1].env[13].valueFrom.secretKeyRef.name: Invalid value: "": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.containers[1].env[13].valueFrom.secretKeyRef.key: Required value]. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.containers[1].env[13].name, message=Required value, reason=FieldValueRequired, additionalProperties={}), StatusCause(field=spec.containers[1].env[13].valueFrom.secretKeyRef.name, message=Invalid value: "": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), reason=FieldValueInvalid, additionalProperties={}), StatusCause(field=spec.containers[1].env[13].valueFrom.secretKeyRef.key, message=Required value, reason=FieldValueRequired, additionalProperties={})], group=null, kind=Pod, name=buildpod.pipeline-p-kp9v9-4.1-bgl4k-7lfz6, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Pod "buildpod.pipeline-p-kp9v9-4.1-bgl4k-7lfz6" is invalid: [spec.containers[1].env[13].name: Required value, spec.containers[1].env[13].valueFrom.secretKeyRef.name: Invalid value: "": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0- 
> *[a-z0-9])?)*'), spec.containers[1].env[13].valueFrom.secretKeyRef.key: Required value], metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}). 
> 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:503) 
> 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:442) 
> 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:406) 
> 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:365) 
> 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:234) 
> 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:796) 
> 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:326) 
> 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:322) 
> 	at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:124) 
> 	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:294) 
> 	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46) 
> 	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71) 
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
> 	at java.lang.Thread.run(Thread.java:748) 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
 v2.3.1

**Comment by gitlawr** [comment]
Can you show the pipeline file(with any private/sensitive info redacted)?

**Comment by mkanakis** [comment]
Yes thanks for the reply.

It is a rather simple config file mostly for testing:

```
stages:
  - name: baby step
     steps:
  - runScriptConfig:
      image: busybox
      shellScript: 
      envFrom:
      - {}
  - name: compile
    steps:
    - publishImageConfig:
       dockerfilePath: ./Dockerfile
       buildContext: .
       tag: testproject:v1
       registry: 127.0.0.1:34301
  timeout: 60
  branch: {}
  notification:
      recipients:
      - recipient: '#monitoring'
        notifier: c-7bkvn:n-p972s
     condition:
     - Success
     - Changed
     - Failed
```

**Comment by gitlawr** [comment]
Can you remove the following content in the first step and try to rebuild it again? It is used for using kubernetes secrets but the secret name is not provided.
```
      envFrom:
      - {}
```
