### ISSUE TITLE
Cert rotate of downstream clusters causes Rancher to crash

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#24097]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
While this seems to be a pretty rare bug to hit, the cause always seems to be rotating certificates on a 2.2.x cluster.

**Result:**

The following logs show up in the Rancher pods, which ultimately causes the pod to crash. It will actually round robin between the pods and causes them all to crashloop. Causing Rancher to become unavailable.

It's worth noting that deleting the problem cluster stops Rancher from crashing.

```
2019/11/13 17:34:08 [INFO] cluster [c-mhx7x] provisioning: [certificates] Generating Kube Proxy certificates
2019/11/13 17:34:08 [INFO] error in remotedialer server [400]: read tcp 10.42.0.34:80->10.42.2.0:53246: i/o timeout
2019/11/13 17:34:08 [INFO] cluster [c-mhx7x] provisioning: [certificates] Generating Node certificate
2019/11/13 17:34:09 [INFO] cluster [c-mhx7x] provisioning: [certificates] Generating admin certificates and kubeconfig
2019/11/13 17:34:09 [INFO] cluster [c-mhx7x] provisioning: [certificates] Generating Kubernetes API server proxy client certificates
2019/11/13 17:34:09 [INFO] cluster [c-mhx7x] provisioning: Successfully Deployed state file at [management-state/rke/rke-189165459/cluster.rkestate]
panic: runtime error: index out of range

goroutine 14149 [running]:
github.com/rancher/rancher/vendor/github.com/rancher/rke/cmd.rebuildClusterWithRotatedCertificates(0x4791be0, 0xc01002bb60, 0xc004bc9b50, 0xc004bc9b60, 0xc0095dcea0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cmd/cert.go:152 +0x11f4
github.com/rancher/rancher/vendor/github.com/rancher/rke/cmd.ClusterUp(0x4791be0, 0xc01002bb60, 0xc004bc9b50, 0xc004bc9b60, 0xc0095dcea0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cmd/up.go:92 +0x1732
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/rke.(*Driver).Update(0xc000a89310, 0x4791be0, 0xc01002bb60, 0xc003ad80d0, 0xc00eefca00, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/rke/rke_driver.go:192 +0x312
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types.(*GrpcServer).Update(0xc008ebea80, 0x4791be0, 0xc0083ca4b0, 0xc01002ba40, 0xc008ebea80, 0xc00d285c00, 0xc00d285bb8)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/rpc_server.go:52 +0x7c
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types._Driver_Update_Handler(0x3c1fae0, 0xc008ebea80, 0x4791be0, 0xc0083ca4b0, 0xc0105f60e0, 0x0, 0x0, 0x0, 0xaadef8, 0x4b)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/drivers.pb.go:1454 +0x241
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc01485e160, 0x47bd760, 0xc011aeea80, 0xc00a758140, 0xc00cfe26c0, 0x72ce3f8, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:921 +0x7d8
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).handleStream(0xc01485e160, 0x47bd760, 0xc011aeea80, 0xc00a758140, 0x0)
        /go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:1143 +0x12b5
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0134656d0, 0xc01485e160, 0x47bd760, 0xc011aeea80, 0xc00a758140)
        /go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:638 +0x9f
created by github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:636 +0xa1
time="2019-11-13 17:34:09" level=error msg="Failed to get cluster c-7tn7t err=Get https://localhost:443/v3/clusters/c-7tn7t: dial tcp [::1]:443: getsockopt: connection refused"
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.2.8

- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
custom

- Machine type (cloud/VM/metal) and specifications (CPU/memory):
baremetal

- Kubernetes version (use `kubectl version`):

In this case there were 4 clusters overall:

Rancher K8S: v1.13.10
Cluster that caused the crash was v1.13.5 (Note: This is the cluster I attempted to upgrade to K8S v1.14.6 and it failed. The cert rotate also failed on this cluster which resulted in this issue). 
The two other clusters were 1.14.6

**Comment by alena1108** [comment]
@sowmyav27 the issue will happen if you run cert rotate command on the cluster that has 0 control plane (api) nodes.

**Comment by sowmyav27** [comment]
**Reproduced the issue using rke version: `1.0.0`**

**Steps:**
- Do an rke up on 3 node cluster - 1 etcd, 1 control plane and 1 worker
- After cluster is built successfully, remove the control plane from cluster.yml and run rke up again.
- Run ./rke cert rotate now on the cluster.

**Result:**
```
INFO[0000] [certificates] Generating admin certificates and kubeconfig 
INFO[0000] [certificates] Generating Kubernetes API server proxy client certificates 
INFO[0001] [certificates] Generating kube-etcd-xxxx certificate and key 
INFO[0001] Successfully Deployed state file at [./rancher-cluster.rkestate] 
INFO[0001] Rebuilding Kubernetes cluster with rotated certificates 
INFO[0001] [dialer] Setup tunnel for host [xxxx] 
INFO[0001] [dialer] Setup tunnel for host [xxxx] 
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 1 [running]:
github.com/rancher/rke/vendor/github.com/urfave/cli.HandleAction.func1(0xc00059dcb0)
	/go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/app.go:472 +0x287
panic(0x21abda0, 0x35e72c0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/rancher/rke/cmd.rebuildClusterWithRotatedCertificates(0x26f7180, 0xc0000ca000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffeefbffc63, 0x13, 0x0, ...)
	/go/src/github.com/rancher/rke/cmd/cert.go:159 +0x1234
github.com/rancher/rke/cmd.ClusterUp(0x26f7180, 0xc0000ca000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffeefbffc63, 0x13, 0x0, ...)
	/go/src/github.com/rancher/rke/cmd/up.go:103 +0x1a44
github.com/rancher/rke/cmd.rotateRKECertificatesFromCli(0xc00002ea00, 0x0, 0x0)
	/go/src/github.com/rancher/rke/cmd/cert.go:103 +0x689
reflect.Value.call(0x2154480, 0x24493a0, 0x13, 0x236edbb, 0x4, 0xc00050dc50, 0x1, 0x1, 0xc000082900, 0x1011e03, ...)
	/usr/local/go/src/reflect/value.go:447 +0x461
reflect.Value.Call(0x2154480, 0x24493a0, 0x13, 0xc00050dc50, 0x1, 0x1, 0xc0000b2820, 0xc0000b2878, 0x140)
	/usr/local/go/src/reflect/value.go:308 +0xa4
github.com/rancher/rke/vendor/github.com/urfave/cli.HandleAction(0x2154480, 0x24493a0, 0xc00002ea00, 0x0, 0x0)
	/go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/app.go:481 +0x1ff
github.com/rancher/rke/vendor/github.com/urfave/cli.Command.Run(0x23700bd, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x238ce11, 0x1f, 0x0, ...)
	/go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/command.go:186 +0x8d1
github.com/rancher/rke/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc0004c7080, 0xc000262280, 0x0, 0x0)
	/go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/app.go:355 +0x79b
github.com/rancher/rke/vendor/github.com/urfave/cli.Command.startApp(0x236ef73, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2398078, 0x27, 0x0, ...)
	/go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/command.go:273 +0x767
github.com/rancher/rke/vendor/github.com/urfave/cli.Command.Run(0x236ef73, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2398078, 0x27, 0x0, ...)
	/go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/command.go:74 +0x125f
github.com/rancher/rke/vendor/github.com/urfave/cli.(*App).Run(0xc000164780, 0xc0000be000, 0x5, 0x5, 0x0, 0x0)
	/go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/app.go:235 +0x601
main.mainErr(0xc0000bc2a0, 0x26be000)
	/go/src/github.com/rancher/rke/main.go:68 +0x1407
main.main()
	/go/src/github.com/rancher/rke/main.go:23 +0x50
```
