### ISSUE TITLE
rancher crashed when connection to cluster timed out

### ISSUE THREAD

**Issue by guoyk93** [rancher/rancher#24610]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
not sure, under some circumstance connection to cluster timed out will crash the rancher manager

**Result:**
```
2019/12/16 06:29:24 [INFO] Stopping cluster agent for c-kh62c
E1216 06:29:24.154140       6 request.go:879] Unexpected error when reading response body: net/http: request canceled (Client.Timeout exceeded while reading body)
E1216 06:29:24.159380       6 request.go:879] Unexpected error when reading response body: net/http: request canceled (Client.Timeout exceeded while reading body)
E1216 06:29:24.161040       6 request.go:879] Unexpected error when reading response body: context deadline exceeded (Client.Timeout exceeded while reading body)
E1216 06:29:24.161397       6 request.go:879] Unexpected error when reading response body: context deadline exceeded
2019/12/16 06:29:34 [INFO] Registering project network policy
2019/12/16 06:29:34 [INFO] Registering CIS controller
2019/12/16 06:29:34 [INFO] registering podsecuritypolicy cluster handler for cluster c-tt85t
2019/12/16 06:29:34 [INFO] registering podsecuritypolicy project handler for cluster c-tt85t
2019/12/16 06:29:34 [INFO] registering podsecuritypolicy namespace handler for cluster c-tt85t
2019/12/16 06:29:34 [INFO] registering podsecuritypolicy serviceaccount handler for cluster c-tt85t
2019/12/16 06:29:34 [INFO] registering podsecuritypolicy template handler for cluster c-tt85t
2019/12/16 06:29:34 [INFO] Registering monitoring for cluster "c-tt85t"
2019/12/16 06:29:34 [INFO] Registering istio for cluster "c-tt85t"
2019/12/16 06:29:49 [ERROR] cluster.management.cattle.io "c-tt85t" not found
2019/12/16 06:30:04 [ERROR] cluster.management.cattle.io "c-tt85t" not found
2019/12/16 06:30:19 [ERROR] cluster.management.cattle.io "c-tt85t" not found
E1216 06:30:25.094905       6 request.go:879] Unexpected error when reading response body: net/http: request canceled (Client.Timeout exceeded while reading body)
panic: creating CRD store unexpected error when reading response body. Please retry. Original error: net/http: request canceled (Client.Timeout exceeded while reading body)

goroutine 181829 [running]:
github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd.(*Factory).BatchCreateCRDs.func1(0xc0275ece80, 0xc0275ecf00, 0x2, 0x2, 0xc02459adc0, 0x6c016c0, 0x41d1bc0, 0xc027498900, 0x3944959, 0x4)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd/init.go:65 +0x2c2
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd.(*Factory).BatchCreateCRDs
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd/init.go:50 +0xce
```

**Other details that may be helpful:**

**Environment information**

```
Custom

Rancher | v2.3.3
-- | --
User Interface | v2.3.25
Helm | v2.14.3-rancher1
Machine | v0.15.0-rancher20-1


```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:47:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by guoyk93** [comment]
https://github.com/rancher/norman/blob/5b9227fe3222a97ba5e7fe399e88a165da8063d9/store/crd/init.go#L65

**Comment by superseb** [comment]
Seems identical to https://github.com/rancher/rancher/issues/20767

**Comment by guoyk93** [comment]
well there is a another problem, rancher manager failed to connect to cluster and print these logs repeatedly:

```
2019/12/16 06:29:24 [INFO] Stopping cluster agent for c-kh62c
E1216 06:29:24.154140       6 request.go:879] Unexpected error when reading response body: net/http: request canceled (Client.Timeout exceeded while reading body)
E1216 06:29:24.159380       6 request.go:879] Unexpected error when reading response body: net/http: request canceled (Client.Timeout exceeded while reading body)
E1216 06:29:24.161040       6 request.go:879] Unexpected error when reading response body: context deadline exceeded (Client.Timeout exceeded while reading body)
E1216 06:29:24.161397       6 request.go:879] Unexpected error when reading response body: context deadline exceeded
```

However, I successfully upgrade all clusters from `1.15` to `1.16` and the problem solved.
