### ISSUE TITLE
"409 internal Server Error" encountered when trying to delete instances.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2493]
Server - Build from master - oct 30

When validation runs are run with 5 parallel threads , all the 5 threads encounter error when trying to clean up the setup , before starting the run:

```
.tox/py27/local/lib/python2.7/site-packages/py/_path/common.py:332: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
.tox/py27/local/lib/python2.7/site-packages/py/_path/common.py:368: in gen
    if p.check(dir=1) and (rec is None or rec(p))])
.tox/py27/local/lib/python2.7/site-packages/_pytest/main.py:632: in _recurse
    ihook.pytest_collect_directory(path=path, parent=self)
.tox/py27/local/lib/python2.7/site-packages/_pytest/main.py:162: in __getattr__
    plugins = self.config._getmatchingplugins(self.fspath)
.tox/py27/local/lib/python2.7/site-packages/_pytest/config.py:692: in _getmatchingplugins
    self._conftest.getconftestmodules(fspath)
.tox/py27/local/lib/python2.7/site-packages/_pytest/config.py:521: in getconftestmodules
    mod = self.importconftest(conftestpath)
.tox/py27/local/lib/python2.7/site-packages/_pytest/config.py:554: in importconftest
    self._onimport(mod)
.tox/py27/local/lib/python2.7/site-packages/_pytest/config.py:680: in _onimportconftest
    self.pluginmanager.consider_conftest(conftestmodule)
.tox/py27/local/lib/python2.7/site-packages/_pytest/core.py:302: in consider_conftest
    conftest=True):
.tox/py27/local/lib/python2.7/site-packages/_pytest/core.py:189: in register
    reg(plugin, name)  # may call addhooks
.tox/py27/local/lib/python2.7/site-packages/_pytest/config.py:613: in _register_plugin
    call_plugin(plugin, "pytest_configure", {'config': self})
.tox/py27/local/lib/python2.7/site-packages/_pytest/core.py:360: in call_plugin
    kwargs=kwargs, firstresult=True).execute()
.tox/py27/local/lib/python2.7/site-packages/_pytest/core.py:394: in execute
    res = method(*args)
cattlevalidationtest/core/conftest.py:9: in pytest_configure
    cleanup()
cattlevalidationtest/core/conftest.py:72: in cleanup
    delete_all(sc, to_delete)
cattlevalidationtest/core/common_fixtures.py:274: in delete_all
    client.delete(i)
.tox/py27/local/lib/python2.7/site-packages/gdapi.py:395: in delete
    return self._delete(i.links.self)
.tox/py27/local/lib/python2.7/site-packages/gdapi.py:62: in wrapped
    return fn(*args, **kw)
.tox/py27/local/lib/python2.7/site-packages/gdapi.py:290: in _delete
    self._error(r.text)
.tox/py27/local/lib/python2.7/site-packages/gdapi.py:253: in _error
    raise ApiError(self._unmarshall(text))
E   ApiError: (ApiError(...), "Internal Server Error : Internal Server Error\n{'status': 500, 'code': u'Internal Server Error', 'id': u'd8356d69-c15e-4030-8ddb-c8f10c09a2ed', 'type': u'error', 'message': u'Internal Server Error', 'actions': {}, 'detail': None, 'links': {}}")
```

Following exception seen in server logs:

```
2015-10-31 04:11:12,337 ERROR [dc7d0361-9303-4af9-ae2a-46a91722ab47:6456433] [instance:145989] [instance.stop] [] [tp1172818142-17] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception org.jooq.exception.DataChangedException: Database record has been changed
        at org.jooq.impl.UpdatableRecordImpl.checkIfChanged(UpdatableRecordImpl.java:550) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.UpdatableRecordImpl.storeUpdate0(UpdatableRecordImpl.java:291) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.UpdatableRecordImpl.access$200(UpdatableRecordImpl.java:90) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.UpdatableRecordImpl$3.operate(UpdatableRecordImpl.java:260) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:123) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.UpdatableRecordImpl.storeUpdate(UpdatableRecordImpl.java:255) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.UpdatableRecordImpl.update(UpdatableRecordImpl.java:149) ~[jooq-3.3.0.jar:na]
        at io.cattle.platform.object.impl.JooqObjectManager.persistRecord(JooqObjectManager.java:216) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.object.impl.JooqObjectManager.setFieldsInternal(JooqObjectManager.java:125) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.object.impl.JooqObjectManager$3.execute(JooqObjectManager.java:113) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.idempotent.Idempotent.change(Idempotent.java:88) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.object.impl.JooqObjectManager.setFields(JooqObjectManager.java:110) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.object.impl.AbstractObjectManager.setFields(AbstractObjectManager.java:135) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.process.common.generic.GenericResourceProcessState.setState(GenericResourceProcessState.java:85) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.AbstractStatesBasedProcessState.setTransitioning(AbstractStatesBasedProcessState.java:27) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.setTransitioning(DefaultProcessInstanceImpl.java:569) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:309) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:259) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:256) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:188) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:161) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:110) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:107) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:107) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.manager.impl.DefaultProcessManager.scheduleProcessInstance(DefaultProcessManager.java:60) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.scheduleProcessInstance(DefaultObjectProcessManager.java:47) [cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.scheduleProcessInstance(DefaultObjectProcessManager.java:52) [cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.api.resource.AbstractObjectResourceManager$1.run(AbstractObjectResourceManager.java:387) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.api.resource.AbstractObjectResourceManager.scheduleProcess(AbstractObjectResourceManager.java:403) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.api.resource.AbstractObjectResourceManager.scheduleProcess(AbstractObjectResourceManager.java:384) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.iaas.api.manager.InstanceManager.deleteInternal(InstanceManager.java:37) [cattle-iaas-api-logic-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.delete(AbstractBaseResourceManager.java:139) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.resource.AbstractResourceManagerFilter.delete(AbstractResourceManagerFilter.java:53) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.delete(FilteredResourceManager.java:66) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.resource.AbstractResourceManagerFilter.delete(AbstractResourceManagerFilter.java:53) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.delete(FilteredResourceManager.java:66) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.resource.AbstractResourceManagerFilter.delete(AbstractResourceManagerFilter.java:53) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.delete(FilteredResourceManager.java:66) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.resource.AbstractResourceManagerFilter.delete(AbstractResourceManagerFilter.java:53) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.delete(FilteredResourceManager.java:66) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.handler.ResourceManagerRequestHandler.generate(ResourceManagerRequestHandler.java:56) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.handler.AbstractResponseGenerator.handle(AbstractResponseGenerator.java:14) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.handle(DefaultReadWriteApiDelegate.java:27) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.write(DefaultReadWriteApiDelegate.java:22) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at sun.reflect.GeneratedMethodAccessor392.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_85]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_85]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) [spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) [spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) [spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96) [spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260) [spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94) [spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) [spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) [spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at com.sun.proxy.$Proxy43.write(Unknown Source) [na:na]
        at io.github.ibuildthecloud.gdapi.request.handler.write.ReadWriteApiHandler.handle(ReadWriteApiHandler.java:19) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:86) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:79) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:72) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [jetty-security-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.Server.handle(Server.java:499) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_85]
```

**Comment by sangeethah** [comment]
This issue is still seen occasionally even when running validation run in single threaded mode.

Today we hit this issue when running validation run in  RHEL7 setup:

```
super_client = <cattle.Client object at 0x7fc8ce6fd610>
client = <cattle.Client object at 0x7fc8ceea20d0>

    def test_dns_cross_link(super_client, client):
    
        port = "31101"
    
        service_scale = 1
        consumed_service_scale = 2
    
        env, service, consumed_service, consumed_service1, dns = \
            create_environment_with_dns_services(
                super_client, client, service_scale, consumed_service_scale,
                port, True)
    
        validate_dns_service(
            super_client, service, [consumed_service, consumed_service1], port,
            dns.name)
    
        delete_all(client, [env, get_env(super_client, consumed_service),
>                           get_env(super_client, consumed_service1), dns])

tests/validation/cattlevalidationtest/core/test_dns_services.py:83: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/validation/cattlevalidationtest/core/common_fixtures.py:282: in delete_all
    client.delete(i)
/usr/local/lib/python2.7/dist-packages/gdapi.py:395: in delete
    return self._delete(i.links.self)
/usr/local/lib/python2.7/dist-packages/gdapi.py:62: in wrapped
    return fn(*args, **kw)
/usr/local/lib/python2.7/dist-packages/gdapi.py:290: in _delete
    self._error(r.text)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <cattle.Client object at 0x7fc8ceea20d0>
text = '{"id":"f6006bee-70e2-4e7b-998b-483f7a7b1133","type":"error","links":{},"actions":{},"status":500,"code":"Internal Server Error","message":"Internal Server Error","detail":null}'

    def _error(self, text):
>       raise ApiError(self._unmarshall(text))
E       ApiError: (ApiError(...), "Internal Server Error : Internal Server Error\n{'status': 500, 'code': u'Internal Server Error', 'links': {}, 'detail': None, 'actions': {}, 'message': u'Internal Server Error', 'type': u'error', 'id': u'f6006bee-70e2-4e7b-998b-483f7a7b1133'}")

/usr/local/lib/python2.7/dist-packages/gdapi.py:253: ApiError
```

**Comment by alena1108** [comment]
The error is changed to 409, but I don't think we are not going to fix this issue in cattle. This error happens when objects API call is performed upon, has been changed a) after the call was issued b) before the call is processed. The issue is recoverable, in 99% of the cases subsequent API call should be successful. The right way to handle Delete/Update in tests - wrap them in retry.

@ibuildthecloud please confirm
