### ISSUE TITLE
exception in nodesyncer

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#25164]
Rancher                             v2.3.3
User Interface                v2.3.25
Helm                                  v2.14.3-rancher1
Machine                            v0.15.0-rancher20-1

```
kubectl logs rancher-747c45b4df-6n62n -n cattle-system -f

(..)

2020/01/27 23:43:59 [ERROR] NodeController c-xdqws/m-03f58edc8f45 recovered from panic "runtime error: invalid memory address or nil pointer dereference". (err=<nil>) Call stack:

goroutine 5057 [running]:

github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.RecoverFromPanic(0xc002903db0)

        /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:158 +0xb5

panic(0x3255340, 0x6bf26d0)

        /usr/local/go/src/runtime/panic.go:522 +0x1b5

github.com/rancher/rancher/pkg/controllers/user/nodesyncer.computeDelta(0xc0010f8b70, 0xc00bd078f0, 0x0, 0x0, 0x0, 0xc007c932f0, 0xc004867f00)

        /go/src/github.com/rancher/rancher/pkg/controllers/user/nodesyncer/nodessyncer.go:250 +0x2c0

github.com/rancher/rancher/pkg/controllers/user/nodesyncer.(*nodesSyncer).updateAnnotations(0xc000130c40, 0xc007b80000, 0xc0077bc480, 0xc0082a03a5, 0xb, 0xc00bd075c0, 0xc00bd07860, 0x1, 0x1, 0xc009ab2fc0, ...)

        /go/src/github.com/rancher/rancher/pkg/controllers/user/nodesyncer/nodessyncer.go:192 +0x69

github.com/rancher/rancher/pkg/controllers/user/nodesyncer.(*nodesSyncer).syncLabels(0xc000130c40, 0xc0063c38e0, 0x16, 0xc0077bc480, 0xc0000d8e00, 0x7f078c8826d0, 0x0, 0x0)

        /go/src/github.com/rancher/rancher/pkg/controllers/user/nodesyncer/nodessyncer.go:228 +0x1f9

github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3.(*nodeController).AddHandler.func1(0xc0063c38e0, 0x16, 0x38ce660, 0xc0077bc480, 0xc001979d58, 0x3, 0x3, 0x0)

        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_node_controller.go:151 +0x63

github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).syncHandler(0xc00280ff00, 0x2fe9880, 0xc0056dff90, 0x0, 0x0)

        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:367 +0x35d

github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).processNextWorkItem(0xc00280ff00, 0xc002f04d00)

        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:276 +0xd3

github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).runWorker(0xc00280ff00)

        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:264 +0x2b

github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc002a9a680)

        /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54

github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc002a9a680, 0x3b9aca00, 0x0, 0x1, 0xc003832720)

        /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8

github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc002a9a680, 0x3b9aca00, 0xc003832720)

        /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d

created by github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).run

        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:256 +0xb7
```

I do not have enough information yet on how this issue happened or how it can be reproduced.

**Comment by iwilltry42** [comment]
Seeing a quite similar error right now.

**Environment:** Rancher v2.4.0, Kubernetes v1.17.4 (set up using RKE v1.1.0).

**When does it happen:**

- When someone tries to add a label to a node using the Rancher UI, it will show in the UI for a second and then disappear. Log of the Rancher Server container is below.
- Adding the label via kubectl is not a problem

```
2020/04/07 05:12:03 [ERROR] NodeController local/machine-l662r recovered from panic "runtime error: invalid memory address or nil pointer dereference". (err=<nil>) Call stack:
goroutine 9023 [running]:
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.RecoverFromPanic(0xc004b64d30)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:158 +0xb5
panic(0x3683900, 0x6c32080)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/rancher/pkg/controllers/user/nodesyncer.(*nodesSyncer).updateLabels(0xc006ed8380, 0xc004ec8900, 0xc006a7c480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rancher/pkg/controllers/user/nodesyncer/nodessyncer.go:185 +0xdf
github.com/rancher/rancher/pkg/controllers/user/nodesyncer.(*nodesSyncer).syncLabels(0xc006ed8380, 0xc01ef5c920, 0x13, 0xc006a7c480, 0xc000bc8000, 0x7f04ded016d0, 0x0, 0xc004b64c50)
	/go/src/github.com/rancher/rancher/pkg/controllers/user/nodesyncer/nodessyncer.go:244 +0x154
github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3.(*nodeController).AddHandler.func1(0xc01ef5c920, 0x13, 0x3dfb720, 0xc006a7c480, 0xc004b64cd8, 0x3, 0x3, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_node_controller.go:154 +0x63
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).syncHandler(0xc009f5c780, 0x33c36c0, 0xc00e55a430, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:387 +0x371
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).processNextWorkItem(0xc009f5c780, 0x206e6f206c6c6100)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:296 +0xef
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).runWorker(0xc009f5c780)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:284 +0x2b
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00064a820)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00064a820, 0x3b9aca00, 0x0, 0x202020200a2c2201, 0xc001d4b4a0)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00064a820, 0x3b9aca00, 0xc001d4b4a0)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).run
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:276 +0xe8
```
