### ISSUE TITLE
CIS Scan - Ability to Schedule Scan and Alert when there is failure

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#25326]
CIS Scheduling:
* Need to make sure it scales with cluster
* Need to Parse the cron string and add 2 fields (Last run & next run time)
* Use Enqueueafter to schedule the run

CIS Alerting:
* New Alert group
* Create a new radio option for "Security Scan"
* The new option will allow for sending alert on Critical or Info
* The existing CIS scan controller will send a "Post" to the alert manager to trigger the alert
     * Need to make sure when the post fails and comes back, the controller won't do another scan just do a post.

**Comment by izaac** [comment]
Rancher version: `2.4 master-head (03/09/2020)` commit id: 17bd84f8d

This is throwing me a panic error:

```log
2020/03/09 21:17:11 [INFO] Provisioned cluster [c-94hv8]
2020/03/09 21:17:11 [INFO] scheduledScanHandler: clusterSync: Scheduled Scan enabled for cluster c-94hv8: */1 * * * *
2020/03/09 21:17:11 [INFO] checking cluster [c-94hv8] for worker nodes upgrade
2020/03/09 21:18:00 [INFO] cisScanHandler: Create: deploying helm chart
2020/03/09 21:18:00 [ERROR] ClusterScanController c-94hv8/ss-cis-1583788680000279059 recovered from panic "runtime error: invalid memory address or nil pointer dereference". (err=<nil>) Call stack:
goroutine 19989 [running]:
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.RecoverFromPanic(0xc007563d30)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:158 +0xb5
panic(0x3664a00, 0x6bed090)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/rancher/pkg/controllers/user/cis.(*cisScanHandler).Create(0xc004555f00, 0xc005decc00, 0xc00982f818, 0x44618c, 0x60, 0x3b69d80)
	/go/src/github.com/rancher/rancher/pkg/controllers/user/cis/clusterScanHandler.go:185 +0xe7f
github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3.(*clusterScanLifecycleAdapter).Create(0xc00544efc0, 0x46639a0, 0xc005decc00, 0xc004d8cb40, 0x1, 0x1, 0xc00414fc80)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_cluster_scan_lifecycle_adapter.go:30 +0x52
github.com/rancher/rancher/vendor/github.com/rancher/norman/lifecycle.checkNil(0x46639a0, 0xc005decc00, 0xc00982fa08, 0xc00ac58900, 0x0, 0x0, 0x40a60a)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/lifecycle/object.go:191 +0x3e
github.com/rancher/rancher/vendor/github.com/rancher/norman/lifecycle.(*objectLifecycleAdapter).record(0xc005782750, 0x46639a0, 0xc00ac58900, 0xc00982fa08, 0xc00544efc0, 0x1, 0x0, 0xc007e15cc0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/lifecycle/object.go:181 +0xd0
github.com/rancher/rancher/vendor/github.com/rancher/norman/lifecycle.(*objectLifecycleAdapter).create(0xc005782750, 0x46639a0, 0xc00ac58900, 0x0, 0x0, 0xc00982fb01, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/lifecycle/object.go:219 +0x2ac
github.com/rancher/rancher/vendor/github.com/rancher/norman/lifecycle.(*objectLifecycleAdapter).sync(0xc005782750, 0xc007d64a20, 0x22, 0x3dbfb80, 0xc00b987b00, 0x7f0e8e74bd40, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/lifecycle/object.go:64 +0x1c0
github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3.NewClusterScanLifecycleAdapter.func1(0xc007d64a20, 0x22, 0xc00b987b00, 0xc00b987b00, 0x40a101, 0x10, 0x33a4ea0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_cluster_scan_lifecycle_adapter.go:60 +0x53
github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3.(*clusterScanController).AddClusterScopedHandler.func1(0xc007d64a20, 0x22, 0x3dbfb80, 0xc00b987b00, 0xc00aa81cd8, 0x3, 0x3, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_cluster_scan_controller.go:180 +0x79
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).syncHandler(0xc007965700, 0x33a5160, 0xc0071853b0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:387 +0x371
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).processNextWorkItem(0xc007965700, 0x2d72657473756c00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:296 +0xef
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).runWorker(0xc007965700)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:284 +0x2b
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0054532a0)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0054532a0, 0x3b9aca00, 0x0, 0x72656e7701, 0xc0001c20c0)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0054532a0, 0x3b9aca00, 0xc0001c20c0)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).run
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:276 +0xe8
```

**Comment by sowmyav27** [comment]
Panic issue logged - being tracked here -- https://github.com/rancher/rancher/issues/25838
Will wait until this is fixed.

**Comment by sowmyav27** [comment]
Verified on latest - master - head - commit id: `570461823`

Issue - https://github.com/rancher/rancher/issues/25838 is seen fixed.
Basic use cases of Alerts and Schedule scans work.
Issues related to them are tracked in separate bugs.

Closing this issue
