### ISSUE TITLE
Panic seen in rancher server logs on master

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25583]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Bring up a master-head.
- Deploy an AWS rke cluster - 7 nodes - 3 etcd, 2 control planes and 2 worker nodes.
- Panic is seen in the rancher server logs

```
2020/02/25 18:54:25 [INFO] [node-controller-rancher-machine] Copying certs to the remote machine...
2020/02/25 18:56:29 [INFO] [node-controller-rancher-machine] Setting Docker configuration on the remote daemon...
2020/02/25 18:56:29 [INFO] [node-controller-rancher-machine] Setting Docker configuration on the remote daemon...
2020/02/25 18:56:29 [INFO] [node-controller-rancher-machine] Setting Docker configuration on the remote daemon...
2020/02/25 18:56:29 [INFO] [node-controller-rancher-machine] Setting Docker configuration on the remote daemon...
2020/02/25 18:56:29 [INFO] [node-controller-rancher-machine] Setting Docker configuration on the remote daemon...
2020/02/25 18:56:30 [INFO] [node-controller-rancher-machine] Setting Docker configuration on the remote daemon...
2020/02/25 18:56:30 [INFO] [node-controller-rancher-machine] Setting Docker configuration on the remote daemon...
E0225 18:57:42.886737      25 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
2020/02/25 18:58:14 [INFO] [node-controller-rancher-machine] Checking connection to Docker...
2020/02/25 18:58:15 [INFO] [node-controller-rancher-machine] Checking connection to Docker...
2020/02/25 18:58:15 [INFO] [node-controller-rancher-machine] Checking connection to Docker...
2020/02/25 18:58:15 [INFO] [node-controller-rancher-machine] Checking connection to Docker...
2020/02/25 18:58:15 [INFO] [node-controller-rancher-machine] Checking connection to Docker...
2020/02/25 18:58:16 [INFO] [node-controller-rancher-machine] Checking connection to Docker...
2020/02/25 18:58:16 [INFO] [node-controller-rancher-machine] Checking connection to Docker...
2020/02/25 18:58:55 [INFO] [node-controller-rancher-machine] Docker is up and running!
I0225 18:58:55.770509      25 controller.go:606] quota admission added evaluator for: clusterregistrationtokens.management.cattle.io
2020/02/25 18:58:55 [INFO] [node-controller-rancher-machine] Docker is up and running!
2020/02/25 18:58:56 [INFO] [node-controller-rancher-machine] Docker is up and running!
2020/02/25 18:58:56 [INFO] [node-controller-rancher-machine] Docker is up and running!
2020/02/25 18:58:56 [INFO] [node-controller-rancher-machine] Docker is up and running!
2020/02/25 18:58:56 [INFO] [node-controller-rancher-machine] Docker is up and running!
2020/02/25 18:58:57 [INFO] [node-controller-rancher-machine] Docker is up and running!
2020-02-25 18:59:00.912986 I | mvcc: store.index: compact 18818
2020-02-25 18:59:00.938969 I | mvcc: finished scheduled compaction at 18818 (took 24.852888ms)
2020/02/25 18:59:44 [INFO] Provisioning node sowmya-etcd-master-1 done
2020/02/25 18:59:44 [INFO] Generating and uploading node config sowmya-etcd-master-1
2020/02/25 18:59:44 [INFO] Provisioning node sowmya-worker-master-2 done
2020/02/25 18:59:44 [INFO] Generating and uploading node config sowmya-worker-master-2
2020/02/25 18:59:44 [INFO] Provisioning node sowmya-etcd-master-2 done
2020/02/25 18:59:44 [INFO] Generating and uploading node config sowmya-etcd-master-2
2020/02/25 18:59:44 [INFO] Creating jail for c-lcwlv
2020/02/25 18:59:44 [INFO] Generating and uploading node config 
2020/02/25 18:59:44 [INFO] Provisioning node sowmya-ctrl-master-1 done
2020/02/25 18:59:44 [INFO] Generating and uploading node config sowmya-ctrl-master-1
2020/02/25 18:59:44 [INFO] Creating jail for c-lcwlv
2020/02/25 18:59:44 [INFO] Provisioning node sowmya-etcd-master-3 done
2020/02/25 18:59:44 [INFO] Generating and uploading node config sowmya-etcd-master-3
2020/02/25 18:59:44 [INFO] Generating and uploading node config 
2020/02/25 18:59:44 [INFO] Creating jail for c-lcwlv
2020/02/25 18:59:44 [INFO] Generating and uploading node config 
2020/02/25 18:59:44 [INFO] Provisioning node sowmya-worker-master-1 done
2020/02/25 18:59:44 [INFO] Generating and uploading node config sowmya-worker-master-1
2020/02/25 18:59:44 [INFO] Creating jail for c-lcwlv
2020/02/25 18:59:44 [INFO] Generating and uploading node config 
2020/02/25 18:59:44 [INFO] Provisioning node sowmya-ctrl-master-2 done
2020/02/25 18:59:44 [INFO] Generating and uploading node config sowmya-ctrl-master-2
2020/02/25 18:59:44 [INFO] Creating jail for c-lcwlv
2020/02/25 18:59:44 [INFO] Generating and uploading node config 
2020/02/25 18:59:44 [INFO] Provisioning cluster [c-lcwlv]
2020/02/25 18:59:44 [INFO] Creating cluster [c-lcwlv]
2020/02/25 18:59:44 [INFO] Handling backend connection request [c-lcwlv:m-w6tbj]
2020/02/25 18:59:44 [INFO] Handling backend connection request [c-lcwlv:m-jvgsg]
2020/02/25 18:59:44 [INFO] Handling backend connection request [c-lcwlv:m-h654g]
fatal error: concurrent map writes

goroutine 24443 [running]:
runtime.throw(0x3d09a84, 0x15)
	/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc003ffb660 sp=0xc003ffb630 pc=0x42fb12
runtime.mapassign(0x34400e0, 0xc0036f9020, 0xc003ffb758, 0x12)
	/usr/local/go/src/runtime/map.go:588 +0x5c3 fp=0xc003ffb6e8 sp=0xc003ffb660 pc=0x40eb93
github.com/rancher/rancher/vendor/github.com/rancher/rke/metadata.initK8sRKESystemImages(0xc0036d5e30, 0xc0036f85a0, 0xc0036f85d0, 0xc0036f8ab0, 0xc0036f8ae0, 0xc0036f8b40, 0xc0036f8b70, 0xc0036f8ba0, 0xc0036f8db0, 0xc0036f8de0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/metadata/metadata.go:129 +0x41a fp=0xc003ffc2a8 sp=0xc003ffb6e8 pc=0x1fef27a
github.com/rancher/rancher/vendor/github.com/rancher/rke/metadata.InitMetadata(0x453e780, 0xc0036d51a0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/metadata/metadata.go:46 +0xf8 fp=0xc003ffc468 sp=0xc003ffc2a8 pc=0x1fee5e8
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.InitClusterObject(0x453e780, 0xc0036d51a0, 0xc003ffcfc8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/cluster.go:587 +0x8c3 fp=0xc003ffc540 sp=0xc003ffc468 pc=0x20b72b3
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.GeneratePlan(0x453e780, 0xc0036d51a0, 0xc002166fc8, 0xc0036d5710, 0xc0036d58c0, 0x0, 0x7f86002e2200, 0x69db7c0, 0x12, 0x198)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/plan.go:74 +0x95 fp=0xc003ffcf78 sp=0xc003ffc540 pc=0x20cfbb5
github.com/rancher/rancher/pkg/librke.(*rke).GeneratePlan(0x0, 0x453e780, 0xc0036d51a0, 0xc0022cf000, 0xc0036d5710, 0xc0036d58c0, 0x0, 0x0, 0x39059a0, 0xc004a90900, ...)
	/go/src/github.com/rancher/rancher/pkg/librke/rke.go:25 +0x82 fp=0xc003ffd7a8 sp=0xc003ffcf78 pc=0x221dce2
github.com/rancher/rancher/pkg/rkenodeconfigserver.(*RKENodeConfigServer).nonWorkerConfig(0xc0010ac720, 0x453e780, 0xc0036d51a0, 0xc003d52100, 0xc004a90900, 0x0, 0x10, 0x32d8ce0)
	/go/src/github.com/rancher/rancher/pkg/rkenodeconfigserver/nodeserver.go:147 +0x28f fp=0xc003ffd970 sp=0xc003ffd7a8 pc=0x2bbdd7f
github.com/rancher/rancher/pkg/rkenodeconfigserver.(*RKENodeConfigServer).ServeHTTP(0xc0010ac720, 0x451da40, 0xc00153acb8, 0xc0026c9500)
	/go/src/github.com/rancher/rancher/pkg/rkenodeconfigserver/nodeserver.go:95 +0x190 fp=0xc003ffda60 sp=0xc003ffd970 pc=0x2bbd4d0
github.com/rancher/rancher/server/responsewriter.ContentTypeOptions.func1(0x451da40, 0xc00153acb8, 0xc0026c9500)
	/go/src/github.com/rancher/rancher/server/responsewriter/cache.go:47 +0x131 fp=0xc003ffdac8 sp=0xc003ffda60 pc=0x19375a1
net/http.HandlerFunc.ServeHTTP(0xc00262fe80, 0x451da40, 0xc00153acb8, 0xc0026c9500)
	/usr/local/go/src/net/http/server.go:2007 +0x44 fp=0xc003ffdaf0 sp=0xc003ffdac8 pc=0x6fd104
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000a1e000, 0x451da40, 0xc00153acb8, 0xc0026c9300)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2 fp=0xc003ffdc20 sp=0xc003ffdaf0 pc=0x192cbc2
github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/server.wrapHandler.func1(0x451da40, 0xc00153acb8, 0xc0026c9300)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/server/server.go:187 +0x95 fp=0xc003ffdc60 sp=0xc003ffdc20 pc=0x259cdf5
net/http.HandlerFunc.ServeHTTP(0xc001e2a510, 0x451da40, 0xc00153acb8, 0xc0026c9300)
	/usr/local/go/src/net/http/server.go:2007 +0x44 fp=0xc003ffdc88 sp=0xc003ffdc60 pc=0x6fd104
github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener.HTTPRedirect.func1(0x451da40, 0xc00153acb8, 0xc0026c9300)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/redirect.go:20 +0x221 fp=0xc003ffdd00 sp=0xc003ffdc88 pc=0x257af31
net/http.HandlerFunc.ServeHTTP(0xc001e131a0, 0x451da40, 0xc00153acb8, 0xc0026c9300)
	/usr/local/go/src/net/http/server.go:2007 +0x44 fp=0xc003ffdd28 sp=0xc003ffdd00 pc=0x6fd104
net/http.serverHandler.ServeHTTP(0xc000151b20, 0x451da40, 0xc00153acb8, 0xc0026c9300)
	/usr/local/go/src/net/http/server.go:2802 +0xa4 fp=0xc003ffdd58 sp=0xc003ffdd28 pc=0x700554
net/http.initNPNRequest.ServeHTTP(0x453e780, 0xc003741bf0, 0xc0032a4a80, 0xc000151b20, 0x451da40, 0xc00153acb8, 0xc0026c9300)
	/usr/local/go/src/net/http/server.go:3365 +0x8d fp=0xc003ffded0 sp=0xc003ffdd58 pc=0x702e6d
net/http.(*initNPNRequest).ServeHTTP(0xc000d42a40, 0x451da40, 0xc00153acb8, 0xc0026c9300)
	<autogenerated>:1 +0x75 fp=0xc003ffdf18 sp=0xc003ffded0 pc=0x72b915
net/http.Handler.ServeHTTP-fm(0x451da40, 0xc00153acb8, 0xc0026c9300)
	/usr/local/go/src/net/http/server.go:86 +0x4d fp=0xc003ffdf48 sp=0xc003ffdf18 pc=0x72c56d
net/http.(*http2serverConn).runHandler(0xc004026600, 0xc00153acb8, 0xc0026c9300, 0xc00262fe20)
	/usr/local/go/src/net/http/h2_bundle.go:5713 +0x9f fp=0xc003ffdfc0 sp=0xc003ffdf48 pc=0x6d4abf
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc003ffdfc8 sp=0xc003ffdfc0 pc=0x45f7a1
created by net/http.(*http2serverConn).processHeaders
	/usr/local/go/src/net/http/h2_bundle.go:5447 +0x4eb

goroutine 1 [chan receive, 75 minutes]:
github.com/rancher/rancher/pkg/tls.ListenAndServe(0x453e6c0, 0xc0011684c0, 0xc000dc6af0, 0x44a9a60, 0xc000a1e000, 0x1bb, 0x50, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rancher/pkg/tls/tls.go:54 +0x29a
github.com/rancher/rancher/app.(*Rancher).ListenAndServe(0xc000d4a460, 0x453e6c0, 0xc0011684c0, 0xc00076adc0, 0xc001425348)
	/go/src/github.com/rancher/rancher/app/app.go:73 +0xdd
main.run(0xc000d489a0, 0x0, 0x0, 0x0, 0x3cd54ee, 0x4, 0x1, 0x50, 0x1bb, 0x3cd54ee, ...)
	/go/src/github.com/rancher/rancher/main.go:227 +0x3fd
main.main.func1(0xc000d489a0, 0x0, 0xc000f3a310)
	/go/src/github.com/rancher/rancher/main.go:170 +0x130
github.com/rancher/rancher/vendor/github.com/urfave/cli.HandleAction(0x32fce00, 0xc0002b5fc0, 0xc000d489a0, 0xc000d489a0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/urfave/cli/app.go:523 +0xbe
github.com/rancher/rancher/vendor/github.com/urfave/cli.(*App).Run(0xc000b52380, 0xc00004c080, 0x8, 0x8, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/urfave/cli/app.go:285 +0x5ec
main.main()

```

**Actual Result:**

- Panic is seen in the logs.
- Rancher server seems to have restarted after. 

**Expected Result:**
No panic should be seen in the rancher server

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `6085a90e2`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke AWS
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by sowmyav27** [comment]
**Verified on latest master-head - commit id: `d8e28c62d`**

- Stopped and restarted the rancher server several times, with a user cluster deployed.
- Did not see any panic

Closing this issue
