### ISSUE TITLE
"fatal error: runtime: out of memory" panic seen in rancher master

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25786]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
This happened on an upgraded set up from 2.3.5 to master-head latest - commit `53e0430e1`.

**What was done in this setup:** 
- In 2.3.5 have a cluster and run pre upgrade automation tests on the cluster (as a std user, enable Auth)
- Create few API tokens from the UI.
- Verified that the tokens are in plain text on the management plane.
- Remote kubectl with kubeconfig (from the rancher UI) works. Save this config to be used after upgrade.
- Upgrade rancher to master-head.
- Existing tokens have the token hashed, they are not seen in plain text on the management plane anymore.
- Post upgrade automation tests work fine.
- Edit cluster, change the k8s version.
- The cluster goes into updating state. And comes up "Active"

**Actual Result:**
Rancher server has restarted, and is up and running
Rancher logs:
```
[storage] 2020/03/05 01:00:04 updating release "mysql.v1"
2020/03/05 01:00:04 [INFO] Creating roleBinding User user-2mpdb Role admin
2020/03/05 01:00:05 [INFO] Creating roleBinding User u-irdieh3onn Role edit
2020/03/05 01:00:05 [INFO] Creating roleBinding User u-irdieh3onn Role project-member
NAME:   mysql
[storage] 2020/03/05 01:00:05 getting last revision of "mysql"
[storage] 2020/03/05 01:00:05 getting release history for "mysql"
I0305 01:00:08.093288      26 trace.go:116] Trace[510403320]: "GuaranteedUpdate etcd3" type:*core.Endpoints (started: 2020-03-05 01:00:06.520831741 +0000 UTC m=+2550.150603306) (total time: 1.430985888s):
Trace[510403320]: [467.046237ms] [436.694507ms] Transaction prepared
Trace[510403320]: [1.415706004s] [948.659767ms] Transaction committed
I0305 01:00:08.881819      26 trace.go:116] Trace[1332190086]: "Update" url:/api/v1/namespaces/kube-system/endpoints/kube-scheduler,user-agent:k3s/v1.17.2+k3s1 (linux/amd64) kubernetes/cdab19b/leader-election,client:127.0.0.1 (started: 2020-03-05 01:00:06.389796989 +0000 UTC m=+2550.019568544) (total time: 2.151701335s):
Trace[1332190086]: [1.816585192s] [1.725122784s] Object stored in database
Trace[1332190086]: [2.151701335s] [335.116143ms] END
I0305 01:00:09.296596      26 trace.go:116] Trace[621657179]: "Get" url:/api/v1/namespaces/kube-system/configmaps/cattle-controllers,user-agent:rancher/v0.0.0 (linux/amd64) kubernetes/$Format,client:127.0.0.1 (started: 2020-03-05 01:00:07.891572882 +0000 UTC m=+2551.521344447) (total time: 1.249256433s):
Trace[621657179]: [926.326429ms] [923.089864ms] About to write a response
Trace[621657179]: [1.248421841s] [322.095412ms] Transformed response object
I0305 01:00:09.738410      26 trace.go:116] Trace[1631221550]: "Get" url:/apis/management.cattle.io/v3/tokens/token-g552z,user-agent:Go-http-client/1.1,client:127.0.0.1 (started: 2020-03-05 01:00:07.497402643 +0000 UTC m=+2551.127174248) (total time: 2.101642253s):
Trace[1631221550]: [303.024151ms] [303.024151ms] About to Get from storage
Trace[1631221550]: [1.718573543s] [1.415549392s] About to write a response
Trace[1631221550]: [2.099743991s] [381.170448ms] Transformed response object
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x3e0736e, 0x16)
	/usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sysMap(0xc0d4000000, 0x4000000, 0x6b66d58)
	/usr/local/go/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x6b4dea0, 0x2000000, 0xc00279be00, 0x437927)
	/usr/local/go/src/runtime/malloc.go:701 +0x1cd
runtime.(*mheap).grow(0x6b4dea0, 0x1000, 0xffffffff)
	/usr/local/go/src/runtime/mheap.go:1255 +0xa3
runtime.(*mheap).allocSpanLocked(0x6b4dea0, 0x1000, 0x6b66d68, 0xc00279bf40)
	/usr/local/go/src/runtime/mheap.go:1170 +0x266
runtime.(*mheap).alloc_m(0x6b4dea0, 0x1000, 0x101, 0x3)
	/usr/local/go/src/runtime/mheap.go:1022 +0xc2
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:1093 +0x4c
runtime.(*mheap).alloc(0x6b4dea0, 0x1000, 0xc002010101, 0xc004e0b880)
	/usr/local/go/src/runtime/mheap.go:1092 +0x8a
runtime.largeAlloc(0x2000000, 0x460101, 0x3)
	/usr/local/go/src/runtime/malloc.go:1138 +0x97
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:1033 +0x46
runtime.systemstack(0xc00326a900)
	/usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1146

goroutine 66791 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc007bc1c70 sp=0xc007bc1c68 pc=0x45d850
runtime.mallocgc(0x2000000, 0x333f9c0, 0xc004e0b801, 0xc00bf40800)
	/usr/local/go/src/runtime/malloc.go:1032 +0x895 fp=0xc007bc1d10 sp=0xc007bc1c70 pc=0x40ca05
runtime.makeslice(0x333f9c0, 0x800000, 0x800000, 0xc00bf40800)
	/usr/local/go/src/runtime/slice.go:49 +0x6c fp=0xc007bc1d40 sp=0xc007bc1d10 pc=0x44618c
github.com/rancher/rancher/vendor/golang.org/x/crypto/scrypt.Key(0xc0058adc40, 0x36, 0x40, 0xc01d4cac90, 0x8, 0x8, 0x8000, 0x8, 0x1, 0x40, ...)
	/go/src/github.com/rancher/rancher/vendor/golang.org/x/crypto/scrypt/scrypt.go:205 +0x14b fp=0xc007bc1df0 sp=0xc007bc1d40 pc=0x174406b
github.com/rancher/rancher/pkg/controllers/user/clusterauthtoken/common.VerifyHash(0xc020d3e200, 0x71, 0xc01f754f24, 0x36, 0x3d65100, 0xc00b0cf180)
	/go/src/github.com/rancher/rancher/pkg/controllers/user/clusterauthtoken/common/crypto.go:61 +0x36b fp=0xc007bc1f38 sp=0xc007bc1df0 pc=0x1744a9b
github.com/rancher/rancher/pkg/auth/tokens.VerifyToken(0xc00b0cf180, 0xc01f754f18, 0xb, 0xc01f754f24, 0x36, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/auth/tokens/token_util.go:109 +0x162 fp=0xc007bc2618 sp=0xc007bc1f38 pc=0x174e752
github.com/rancher/rancher/pkg/auth/requests.(*tokenAuthenticator).TokenFromRequest(0xc000d4a660, 0xc009395100, 0xc004e0b880, 0x7f1efce456d0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/auth/requests/authenticate.go:163 +0x1ef fp=0xc007bc26f8 sp=0xc007bc2618 pc=0x29f073f
github.com/rancher/rancher/pkg/auth/requests.(*tokenAuthenticator).Authenticate(0xc000d4a660, 0xc009395100, 0x3de6140, 0xc01d9cdb00, 0xc003f02a00, 0x5, 0x0, 0x0, 0xc01db74480, 0x1ad)
	/go/src/github.com/rancher/rancher/pkg/auth/requests/authenticate.go:74 +0x50 fp=0xc007bc2e90 sp=0xc007bc26f8 pc=0x29ef940
github.com/rancher/rancher/pkg/auth/requests.(*impersonatingAuth).Authenticate(0xc000239780, 0xc009395100, 0xdec884d151477332, 0xc004852fa0, 0x4090db, 0xc022861c90, 0xdec884d151477332, 0x1, 0xc004852fd0, 0x4140b3)
	/go/src/github.com/rancher/rancher/pkg/auth/requests/impersonate.go:26 +0x55 fp=0xc007bc2f58 sp=0xc007bc2e90 pc=0x29f1625
github.com/rancher/rancher/pkg/auth/requests.(*chainedAuth).Authenticate(0xc000239800, 0xc009395100, 0x0, 0xc004853048, 0x417b1e, 0x7f1ef9775fe8, 0x0, 0xc004853130, 0x8, 0xc004853320)
	/go/src/github.com/rancher/rancher/pkg/auth/requests/chained.go:21 +0x76 fp=0xc007bc2fd0 sp=0xc007bc2f58 pc=0x29f0b76
github.com/rancher/rancher/pkg/auth/requests.authHeaderHandler.ServeHTTP(0x45d2de0, 0xc000239800, 0x4596720, 0xc000a6a0c0, 0x45d2da0, 0xc0010417a0, 0x460b9a0, 0xc02124b1f0, 0xc009395100)
	/go/src/github.com/rancher/rancher/pkg/auth/requests/filter.go:33 +0x59 fp=0xc007bc3108 sp=0xc007bc2fd0 pc=0x29f0f39
github.com/rancher/rancher/pkg/auth/requests.(*authHeaderHandler).ServeHTTP(0xc000d8f140, 0x460b9a0, 0xc02124b1f0, 0xc009395100)
	<autogenerated>:1 +0x9e fp=0xc007bc3190 sp=0xc007bc3108 pc=0x29f22be
github.com/rancher/rancher/pkg/rbac.NewAccessControlHandler.func1(0x460b9a0, 0xc02124b1f0, 0xc008fe3600, 0x4595860, 0xc000d8f140)
	/go/src/github.com/rancher/rancher/pkg/rbac/user_based.go:25 +0x161 fp=0xc007bc3208 sp=0xc007bc3190 pc=0x24802f1
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/auth.Middleware.Wrap.func1(0x460b9a0, 0xc02124b1f0, 0xc008fe3600)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/auth/filter.go:36 +0x55 fp=0xc007bc3240 sp=0xc007bc3208 pc=0x247d605
net/http.HandlerFunc.ServeHTTP(0xc0002399e0, 0x460b9a0, 0xc02124b1f0, 0xc008fe3600)
	/usr/local/go/src/net/http/server.go:2007 +0x44 fp=0xc007bc3268 sp=0xc007bc3240 pc=0x6fd104
github.com/rancher/rancher/pkg/websocket.websocketHandler.ServeHTTP(0x459d5e0, 0xc0002399e0, 0x460b9a0, 0xc02124b1f0, 0xc008fe3600)
	/go/src/github.com/rancher/rancher/pkg/websocket/handler.go:35 +0xa0 fp=0xc007bc32b0 sp=0xc007bc3268 pc=0x2bfcd00
github.com/rancher/rancher/pkg/websocket.(*websocketHandler).ServeHTTP(0xc000666000, 0x460b9a0, 0xc02124b1f0, 0xc008fe3600)
	<autogenerated>:1 +0x63 fp=0xc007bc32e8 sp=0xc007bc32b0 pc=0x2bfd753
github.com/rancher/rancher/pkg/audit.auditHandler.ServeHTTP(0x4595ac0, 0xc000666000, 0x0, 0x460b9a0, 0xc02124b1f0, 0xc008fe3600)
	/go/src/github.com/rancher/rancher/pkg/audit/filter.go:31 +0x623 fp=0xc007bc3398 sp=0xc007bc32e8 pc=0x1276c53
github.com/rancher/rancher/pkg/audit.(*auditHandler).ServeHTTP(0xc000239de0, 0x460b9a0, 0xc02124b1f0, 0xc008fe3600)
	<autogenerated>:1 +0x6c fp=0xc007bc33d8 sp=0xc007bc3398 pc=0x127730c
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentType.func1(0x45f9e20, 0xc00abb9ce0, 0xc008fe3600)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/content.go:33 +0x93 fp=0xc007bc3428 sp=0xc007bc33d8 pc=0x19c27e3
net/http.HandlerFunc.ServeHTTP(0xc00000ce60, 0x45f9e20, 0xc00abb9ce0, 0xc008fe3600)
	/usr/local/go/src/net/http/server.go:2007 +0x44 fp=0xc007bc3450 sp=0xc007bc3428 pc=0x6fd104
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.Gzip.func1(0x460a7a0, 0xc021a6b7a0, 0xc008fe3600)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/gzip.go:60 +0x1f5 fp=0xc007bc3508 sp=0xc007bc3450 pc=0x19c29f5
net/http.HandlerFunc.ServeHTTP(0xc00000cf00, 0x460a7a0, 0xc021a6b7a0, 0xc008fe3600)
	/usr/local/go/src/net/http/server.go:2007 +0x44 fp=0xc007bc3530 sp=0xc007bc3508 pc=0x6fd104
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentTypeOptions.func1(0x460a7a0, 0xc021a6b7a0, 0xc008fe3600)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/cache.go:47 +0x131 fp=0xc007bc3598 sp=0xc007bc3530 pc=0x19c2721
net/http.HandlerFunc.ServeHTTP(0xc009c290e0, 0x460a7a0, 0xc021a6b7a0, 0xc008fe3600)
	/usr/local/go/src/net/http/server.go:2007 +0x44 fp=0xc007bc35c0 sp=0xc007bc3598 pc=0x6fd104
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000a6a000, 0x460a7a0, 0xc021a6b7a0, 0xc008fe3400)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2 fp=0xc007bc36f0 sp=0xc007bc35c0 pc=0x19b7d42
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00198f200, 0x460a7a0, 0xc021a6b7a0, 0xc009395000)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2 fp=0xc007bc3820 sp=0xc007bc36f0 pc=0x19b7d42
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00198f2c0, 0x460a7a0, 0xc021a6b7a0, 0xc009394c00)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2 fp=0xc007bc3950 sp=0xc007bc3820 pc=0x19b7d42
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00198f380, 0x460a7a0, 0xc021a6b7a0, 0xc009394a00)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2 fp=0xc007bc3a80 sp=0xc007bc3950 pc=0x19b7d42
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/dashboard.Route.func2(0x460a7a0, 0xc021a6b7a0, 0xc009394a00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/dashboard/ui.go:56 +0xe5 fp=0xc007bc3ac8 sp=0xc007bc3a80 pc=0x25f1d25
net/http.HandlerFunc.ServeHTTP(0xc000468180, 0x460a7a0, 0xc021a6b7a0, 0xc009394a00)
	/usr/local/go/src/net/http/server.go:2007 +0x44 fp=0xc007bc3af0 sp=0xc007bc3ac8 pc=0x6fd104
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc01dc0d380, 0x460a7a0, 0xc021a6b7a0, 0xc009394800)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2 fp=0xc007bc3c20 sp=0xc007bc3af0 pc=0x19b7d42
github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/server.wrapHandler.func1(0x460a7a0, 0xc021a6b7a0, 0xc009394800)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/server/server.go:187 +0x95 fp=0xc007bc3c60 sp=0xc007bc3c20 pc=0x25d9e55
net/http.HandlerFunc.ServeHTTP(0xc022b8df20, 0x460a7a0, 0xc021a6b7a0, 0xc009394800)
	/usr/local/go/src/net/http/server.go:2007 +0x44 fp=0xc007bc3c88 sp=0xc007bc3c60 pc=0x6fd104
github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener.HTTPRedirect.func1(0x460a7a0, 0xc021a6b7a0, 0xc009394800)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/redirect.go:20 +0x221 fp=0xc007bc3d00 sp=0xc007bc3c88 pc=0x25b7f91
net/http.HandlerFunc.ServeHTTP(0xc022b8f2e0, 0x460a7a0, 0xc021a6b7a0, 0xc009394800)
	/usr/local/go/src/net/http/server.go:2007 +0x44 fp=0xc007bc3d28 sp=0xc007bc3d00 pc=0x6fd104
net/http.serverHandler.ServeHTTP(0xc02064ddc0, 0x460a7a0, 0xc021a6b7a0, 0xc009394800)
	/usr/local/go/src/net/http/server.go:2802 +0xa4 fp=0xc007bc3d58 sp=0xc007bc3d28 pc=0x700554
net/http.initNPNRequest.ServeHTTP(0x462cce0, 0xc0044ac7b0, 0xc004427500, 0xc02064ddc0, 0x460a7a0, 0xc021a6b7a0, 0xc009394800)
	/usr/local/go/src/net/http/server.go:3365 +0x8d fp=0xc007bc3ed0 sp=0xc007bc3d58 pc=0x702e6d
net/http.(*initNPNRequest).ServeHTTP(0xc00218cbe0, 0x460a7a0, 0xc021a6b7a0, 0xc009394800)
	<autogenerated>:1 +0x75 fp=0xc007bc3f18 sp=0xc007bc3ed0 pc=0x72b915
net/http.Handler.ServeHTTP-fm(0x460a7a0, 0xc021a6b7a0, 0xc009394800)
	/usr/local/go/src/net/http/server.go:86 +0x4d fp=0xc007bc3f48 sp=0xc007bc3f18 pc=0x72c56d
net/http.(*http2serverConn).runHandler(0xc004c9c480, 0xc021a6b7a0, 0xc009394800, 0xc003edaa60)
	/usr/local/go/src/net/http/h2_bundle.go:5713 +0x9f fp=0xc007bc3fc0 sp=0xc007bc3f48 pc=0x6d4abf
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc007bc3fc8 sp=0xc007bc3fc0 pc=0x45f7a1
created by net/http.(*http2serverConn).processHeaders
	/usr/local/go/src/net/http/h2_bundle.go:5447 +0x4eb

goroutine 1 [chan receive, 42 minutes]:
github.com/rancher/rancher/pkg/tls.ListenAndServe(0x462cc20, 0xc00068c400, 0xc0004e1c70, 0x4596720, 0xc01dc0d380, 0x1bb, 0x50, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rancher/pkg/tls/tls.go:54 +0x29a
github.com/rancher/rancher/app.(*Rancher).ListenAndServe(0xc0001de620, 0x462cc20, 0xc00068c400, 0xc0005dc7d0, 0xc001447348)
	/go/src/github.com/rancher/rancher/app/app.go:75 +0xdd
main.run(0xc0010754a0, 0x0, 0x0, 0x0, 0x3dcda45, 0x4, 0x1, 0x50, 0x1bb, 0x3dcda45, ...)
	/go/src/github.com/rancher/rancher/main.go:226 +0x3fd
main.main.func1(0xc0010754a0, 0x0, 0xc0001d9f10)
	/go/src/github.com/rancher/rancher/main.go:169 +0x130
github.com/rancher/rancher/vendor/github.com/urfave/cli.HandleAction(0x33ae7c0, 0xc00107a390, 0xc0010754a0, 0xc0010754a0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/urfave/cli/app.go:523 +0xbe
github.com/rancher/rancher/vendor/github.com/urfave/cli.(*App).Run(0xc0009c5180, 0xc0000c4000, 0x8, 0x8, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/urfave/cli/app.go:285 +0x5ec
main.main()
	/go/src/github.com/rancher/rancher/main.go:176 +0xd3f

goroutine 19 [chan receive]:
github.com/rancher/rancher/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x6b46e00)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/klog/klog.go:1010 +0x8b
created by github.com/rancher/rancher/vendor/k8s.io/klog.init.0
	/go/src/github.com/rancher/rancher/vendor/k8s.io/klog/klog.go:411 +0xd6

```
**Expected Result:**

**Other details that may be helpful:**
- Happens on a fresh install of master-head - commit id: `0aea63a4b` also

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head latest - commit `53e0430e1`.
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):  rke do 
- Kubernetes version (use `kubectl version`):

```
1.15.10-rancher 1-1 to 1.16.7rancher1-2
```

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `63306835a` and `beba5247e`**

- Some of the actions performed 
- Run CIS scan on a couple of cluster.
- Verify Alerts from Scans
- Schedule scans on the cluster
- Verify node labels when labels added through node template.

Did not see any panic in the server logs.
Closing the issue.
Will reopen if we see this again
