### ISSUE TITLE
Panic in rancher server logs, rancher server restarts

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26071]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a cluster - 1 node all roles/custom cluster/ RKE do cluster - 1 etcd, 1 contorl 1 worker
- Panic is seen in the logs:
- Logs:

```
2020/03/16 22:02:57 [INFO] cluster [c-rt9wl] provisioning: [remove/rke-etcd-port-listener] Successfully removed container on host [<ip-1>]
2020/03/16 22:02:57 [INFO] Removing container [rke-cp-port-listener] on host [<ip-1>], try #1

2020/03/16 22:02:57 [INFO] cluster [c-rt9wl] provisioning: [remove/rke-cp-port-listener] Successfully removed container on host [<ip-1>]
2020/03/16 22:02:57 [INFO] Removing container [rke-worker-port-listener] on host [<ip-1>], try #1

2020/03/16 22:02:57 [INFO] cluster [c-rt9wl] provisioning: [remove/rke-worker-port-listener] Successfully removed container on host [<ip-1>]
2020/03/16 22:02:57 [INFO] Checking if container [cert-deployer] is running on host [<ip-1>], try #1

2020/03/16 22:02:57 [INFO] cluster [c-rt9wl] provisioning: [network] Port listener containers removed successfully
2020/03/16 22:02:57 [INFO] cluster [c-rt9wl] provisioning: [certificates] Deploying kubernetes certificates to Cluster nodes
2020/03/16 22:02:58 [INFO] Image [rancher/rke-tools:v0.1.53] exists on host [<ip-1>]
2020/03/16 22:02:58 [INFO] Starting container [cert-deployer] on host [<ip-1>], try #1

2020/03/16 22:02:58 [INFO] Checking if container [cert-deployer] is running on host [<ip-1>], try #1

2020/03/16 22:03:03 [INFO] Checking if container [cert-deployer] is running on host [<ip-1>], try #1

2020/03/16 22:03:03 [INFO] Removing container [cert-deployer] on host [<ip-1>], try rancher/rancher#1
2020/03/16 22:03:03 [INFO] cluster [c-rt9wl] provisioning: [reconcile] Rebuilding and updating local kube config
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x19dcfe2]

goroutine 11440 [running]:
github.com/rancher/rancher/pkg/ref.IsNodeNotFound(0x0, 0x0, 0xc0025b8500)
	/go/src/github.com/rancher/rancher/pkg/ref/parse.go:14 +0x22
github.com/rancher/rancher/pkg/rkedialerfactory.(*RKEDialerFactory).WrapTransport.func1.1(0x3e559b7, 0x3, 0xc0025b8500, 0x12, 0xc00328d988, 0x404c4d, 0x60, 0x492090)
	/go/src/github.com/rancher/rancher/pkg/rkedialerfactory/rke_dialer.go:71 +0x151
net/http.(*Transport).dial(0xc0023f7040, 0x46ce4a0, 0xc0017acf00, 0x3e559b7, 0x3, 0xc0025b8500, 0x12, 0x0, 0x1, 0x0, ...)
	/usr/local/go/src/net/http/transport.go:1043 +0x7b
net/http.(*Transport).dialConn(0xc0023f7040, 0x46ce4a0, 0xc0017acf00, 0x0, 0xc0073fd400, 0x5, 0xc0025b8500, 0x12, 0x0, 0xc00499e7d8, ...)
	/usr/local/go/src/net/http/transport.go:1478 +0x193e
net/http.(*Transport).dialConnFor(0xc0023f7040, 0xc000801970)
	/usr/local/go/src/net/http/transport.go:1308 +0xdc
created by net/http.(*Transport).queueForDial
	/usr/local/go/src/net/http/transport.go:1277 +0x41d
2020/03/16 22:03:05 [INFO] Rancher version f1f8b0865 (f1f8b0865) is starting
2020/03/16 22:03:05 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:auto Embedded:false HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features:}
2020/03/16 22:03:05 [INFO] Listening on /tmp/log.sock
2020/03/16 22:03:05 [INFO] Running etcd --data-dir=management-state/etcd
2020-03-16 22:03:05.294355 W | pkg/flags: unrecognized environment variable ETCD_URL_arm64=https://github.com/etcd-io/etcd/releases/download/v3.4.3/etcd-v3.4.3-linux-arm64.tar.gz
2020-03-16 22:03:05.294404 W | pkg/flags: unrecognized environment variable ETCD_URL_amd64=https://github.com/etcd-io/etcd/releases/download/v3.4.3/etcd-v3.4.3-linux-amd64.tar.gz
2020-03-16 22:03:05.294410 W | pkg/flags: unrecognized environment variable ETCD_UNSUPPORTED_ARCH=amd64
2020-03-16 22:03:05.294414 W | pkg/flags: unrecognized environment variable ETCD_URL=ETCD_URL_amd64

```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `f1f8b0865`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke/custom
- Kubernetes version (use `kubectl version`):

```
1.17.4
```

**Comment by sowmyav27** [comment]
Verified on master-head - commit id: `bce9d0d13`

Able to provision a DO rke cluster - 1 etcd, 3 ctrl plane nodes and 4 worker nodes.

No panic/restarts of rancher seen.
