### ISSUE TITLE
Panic in Rancher server logs for dummy node

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26090]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Register node(dummy) through kubectl - no label added or node registered in the /v3/settings/ignore-node-name
- Wait until node is in Unavailable in the Rancher UI
- Upgrade cluster - max Unavailable worker = 10%
- Upgrade goes through. The dummy node is still in unavailable state

**Result:**
Panic is seen in rancher logs when these actions are performed
logs:
```
2020/03/17 18:33:33 [DEBUG] getMachine: looking up machine [m-a42d3429c2c5] in cluster [c-x5l5h]
2020/03/17 18:33:34 [DEBUG] Changes in Allocatable, proposed v1.ResourceList{"cpu":resource.Quantity{i:resource.int64Amount{value:2, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"2", Format:"DecimalSI"}, "ephemeral-storage":resource.Quantity{i:resource.int64Amount{value:51976970240, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"BinarySI"}, "hugepages-2Mi":resource.Quantity{i:resource.int64Amount{value:0, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"0", Format:"DecimalSI"}, "memory":resource.Quantity{i:resource.int64Amount{value:4037328896, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"BinarySI"}, "pods":resource.Quantity{i:resource.int64Amount{value:141, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"141", Format:"DecimalSI"}}, existing: v1.ResourceList{"cpu":resource.Quantity{i:resource.int64Amount{value:2, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"2", Format:"DecimalSI"}, "ephemeral-storage":resource.Quantity{i:resource.int64Amount{value:46779273139, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"46779273139", Format:"DecimalSI"}, "hugepages-2Mi":resource.Quantity{i:resource.int64Amount{value:0, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"0", Format:"DecimalSI"}, "memory":resource.Quantity{i:resource.int64Amount{value:4037328896, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"BinarySI"}, "pods":resource.Quantity{i:resource.int64Amount{value:141, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"141", Format:"DecimalSI"}}
2020/03/17 18:33:34 [DEBUG] ObjectsAreEqualResults for m-8033d51aae94: statusEqual: false specEqual: true nodeNameEqual: true labelsEqual: true annotationsEqual: true requestsEqual: true limitsEqual: true rolesEqual: true
2020/03/17 18:33:34 [DEBUG] Changes in Allocatable, proposed v1.ResourceList{"cpu":resource.Quantity{i:resource.int64Amount{value:2, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"2", Format:"DecimalSI"}, "ephemeral-storage":resource.Quantity{i:resource.int64Amount{value:51976970240, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"BinarySI"}, "hugepages-2Mi":resource.Quantity{i:resource.int64Amount{value:0, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"0", Format:"DecimalSI"}, "memory":resource.Quantity{i:resource.int64Amount{value:4037328896, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"BinarySI"}, "pods":resource.Quantity{i:resource.int64Amount{value:141, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"141", Format:"DecimalSI"}}, existing: v1.ResourceList{"cpu":resource.Quantity{i:resource.int64Amount{value:2, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"2", Format:"DecimalSI"}, "ephemeral-storage":resource.Quantity{i:resource.int64Amount{value:46779273139, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"46779273139", Format:"DecimalSI"}, "hugepages-2Mi":resource.Quantity{i:resource.int64Amount{value:0, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"0", Format:"DecimalSI"}, "memory":resource.Quantity{i:resource.int64Amount{value:4037328896, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"BinarySI"}, "pods":resource.Quantity{i:resource.int64Amount{value:141, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"141", Format:"DecimalSI"}}
2020/03/17 18:33:34 [DEBUG] ObjectsAreEqualResults for m-8033d51aae94: statusEqual: false specEqual: false nodeNameEqual: true labelsEqual: true annotationsEqual: true requestsEqual: true limitsEqual: true rolesEqual: true
2020/03/17 18:33:34 [DEBUG] ObjectsAreEqualResults for m-8033d51aae94: statusEqual: true specEqual: false nodeNameEqual: true labelsEqual: true annotationsEqual: true requestsEqual: true limitsEqual: true rolesEqual: true
2020/03/17 18:33:34 [DEBUG] Skipping v3.node creation for [bigip2] node
2020/03/17 18:33:34 [DEBUG] Skipping v3.node creation for [bigip3] node
2020/03/17 18:33:36 [DEBUG] machineName: returning [m-0f10e32e27a2] for node with RequestedHostname [ip1]
2020/03/17 18:33:36 [DEBUG] getMachine: looking up machine [m-0f10e32e27a2] in cluster [c-x5l5h]
2020/03/17 18:33:46 [DEBUG] machineName: returning [m-8033d51aae94] for node with RequestedHostname [ip2]
2020/03/17 18:33:46 [DEBUG] getMachine: looking up machine [m-8033d51aae94] in cluster [c-x5l5h]
2020/03/17 18:33:49 [DEBUG] machineName: returning [m-8033d51aae94] for node with RequestedHostname [ip2]
2020/03/17 18:33:49 [DEBUG] getMachine: looking up machine [m-8033d51aae94] in cluster [c-x5l5h]
2020/03/17 18:33:59 [ERROR] NodeController c-x5l5h/machine-b46f5 recovered from panic "runtime error: invalid memory address or nil pointer dereference". (err=<nil>) Call stack:
goroutine 5114 [running]:
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.RecoverFromPanic(0xc002391d30)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:158 +0xb5
panic(0x36739e0, 0x6c0beb0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader.(*upgradeHandler).getNodePlan(0xc0005426e0, 0xc03f055680, 0xc00c660680, 0xc0023918c8, 0xd29965, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader/upgrade.go:209 +0x2d
github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader.(*upgradeHandler).updateNodePlan(0xc0005426e0, 0xc03f055680, 0xc00c660680, 0xc031c28a01, 0x7, 0xc00c660680, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader/upgrade.go:158 +0x5a
github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader.(*upgradeHandler).Sync(0xc0005426e0, 0xc036948f00, 0x15, 0xc03f055680, 0xc00092e000, 0x7f45bf3d3008, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader/upgrade.go:92 +0xc71
github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3.(*nodeController).AddHandler.func1(0xc036948f00, 0x15, 0x3dea440, 0xc03f055680, 0xc002391cd8, 0x3, 0x3, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_node_controller.go:154 +0x63
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).syncHandler(0xc001dcac80, 0x33b3c40, 0xc037143420, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:387 +0x371
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).processNextWorkItem(0xc001dcac80, 0xc0017baa00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:296 +0xef
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).runWorker(0xc001dcac80)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:284 +0x2b
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc003e7ce40)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc003e7ce40, 0x3b9aca00, 0x0, 0x1, 0xc001376600)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc003e7ce40, 0x3b9aca00, 0xc001376600)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).run
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:276 +0xe8
2020/03/17 18:34:00 [DEBUG] Checking and deleting unused certificates for cluster c-x5l5h
2020/03/17 18:34:04 [DEBUG] machineName: returning [m-d4bd7f9b5147] for node with RequestedHostname [ip]
2020/03/17 18:34:04 [DEBUG] getMachine: looking up machine [m-d4bd7f9b5147] in cluster [c-x5l5h]
2020/03/17 18:34:08 [DEBUG] machineName: returning [m-a42d3429c2c5] for node with RequestedHostname [ip]
```

**Other details that may be helpful:**
Related to https://github.com/rancher/rancher/issues/26052

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `e651c7a81`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke custom
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `330a4bed0`**

**Steps:**

- Register node(dummy) through kubectl - no label added or node registered in the /v3/settings/ignore-node-name
- Wait until node is in Unavailable in the Rancher UI
- Upgrade cluster k8s version from 1.16 to 1.17
- The upgrade goes through.
- Dummy node is still seen in "Unavailable" state
- No panic seen in logs
