### ISSUE TITLE
Panic thrown in Rancher when adding a cluster with cluster_template resource using terraform provider

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#26459]
**What kind of request is this:**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a cluster with Terraform provider 1.8.2 from a cluster_template resource. Rancher v2.4.2
2. This works in Rancher v2.3.6
3. Adding a new cluster using a cluster template worked for me from the Rancher UI
4. Cluster gets created if I don't use a cluster_template resource in v2.4.2

```terraform
# Create a new rancher2 cluster template
resource "rancher2_cluster_template" "foo-tmpl" {
  name = "foo2"
  description = "Test cluster template v2"
  members {
    access_type = "owner"
    user_principal_id = "local://user-nchm4"
  }
  template_revisions {
    name = "V2"
    default = true
    cluster_config {
      rke_config {
        network {
          plugin = "canal"
        }
        services {
          etcd {
            creation = "6h"
            retention = "24h"
            backup_config {
            enabled = true
            interval_hours = 1
            retention = 3
            s3_backup_config {
              access_key = "SECRET"
              bucket_name = "SECRET"
              endpoint = "SECRET"
              folder = "SECRET"
              region = "SECRET"
              secret_key = "SECRET"
              }
            }
          }
        }
     }
   }
  }
}

# Create a new rancher2 RKE Cluster from template
resource "rancher2_cluster" "foo-do-tmpl" {
  name = "foo-do-tmpl"
  # driver = "rancherKubernetesEngine"
  cluster_template_id = rancher2_cluster_template.foo-tmpl.id
  cluster_template_revision_id = rancher2_cluster_template.foo-tmpl.template_revisions.0.id
  scheduled_cluster_scan {
    enabled = true
    scan_config {
      cis_scan_config {
        debug_master = true
        debug_worker = true
      }
    }
    schedule_config {
      cron_schedule = "0 * * * *"
      retention = 5
    }
  }
}

# Create a new rancher2 Cloud Credential
resource "rancher2_cloud_credential" "foo" {
  name = "foo"
  description= "Terraform cloudCredential acceptance test"
  digitalocean_credential_config {
    access_token = "SECRET"
  }
}
# Create a new rancher2 Node Template
resource "rancher2_node_template" "foo" {
  name = "foo"
  description = "foo test"
  cloud_credential_id = rancher2_cloud_credential.foo.id
  digitalocean_config {
    image    = "ubuntu-18-04-x64"
    region   = "sfo2"
    size     = "s-2vcpu-2gb"
    ssh_port = "22"
    ssh_user = "root"
  }
}
# Create a new rancher2 Node Pool
resource "rancher2_node_pool" "etcd" {
  cluster_id =  rancher2_cluster.foo-do-tmpl.id
  name = "etcd"
  hostname_prefix =  "izaac-tf-etcd-"
  node_template_id = rancher2_node_template.foo.id
  quantity = 1
  etcd = true
}
resource "rancher2_node_pool" "wrkr" {
  cluster_id =  rancher2_cluster.foo-do-tmpl.id
  name = "wrkr"
  hostname_prefix =  "izaac-tf-wrkr-"
  node_template_id = rancher2_node_template.foo.id
  quantity = 3
  worker = true
}
resource "rancher2_node_pool" "cp" {
  cluster_id =  rancher2_cluster.foo-do-tmpl.id
  name = "cp"
  hostname_prefix =  "izaac-tf-cp-"
  node_template_id = rancher2_node_template.foo.id
  quantity = 1
  control_plane = true
}
```

**Result:**

```bash
rancher2_cloud_credential.foo: Creating...
rancher2_cluster_template.foo-tmpl: Creating...
rancher2_cluster_template.foo-tmpl: Creation complete after 0s [id=cattle-global-data:ct-8hpxw]
rancher2_cluster.foo-do-tmpl: Creating...
rancher2_cloud_credential.foo: Creation complete after 2s [id=cattle-global-data:cc-6nqdn]
rancher2_node_template.foo: Creating...
rancher2_node_template.foo: Creation complete after 2s [id=cattle-global-nt:nt-b2hj8]

Error: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [] from [https://96.126.103.245:443/v3/clusters]

```

```log
I0402 21:35:10.987532      26 controller.go:606] quota admission added evaluator for: clustertemplates.management.cattle.io
I0402 21:35:11.040078      26 controller.go:606] quota admission added evaluator for: clustertemplaterevisions.management.cattle.io
2020/04/02 21:35:11 [ERROR] Panic serving api request:
goroutine 12518 [running]:
runtime/debug.Stack(0xc005e6a938, 0x3683900, 0x6c320a0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP.func1(0x46c71a0, 0xc0066a3570)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:175 +0x7a
panic(0x3683900, 0x6c320a0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/rancher/pkg/api/customization/cluster.(*Validator).validateScheduledClusterScan(0xc000cd8000, 0xc003a4f760, 0xc003a4f760, 0x0)
	/go/src/github.com/rancher/rancher/pkg/api/customization/cluster/validator.go:67 +0x70
github.com/rancher/rancher/pkg/api/customization/cluster.(*Validator).Validator(0xc000cd8000, 0xc0060b0900, 0xc004ba2f00, 0xc0035445a0, 0x0, 0xc0035445a0)
	/go/src/github.com/rancher/rancher/pkg/api/customization/cluster/validator.go:56 +0x23d
github.com/rancher/rancher/vendor/github.com/rancher/norman/parse/builder.(*Builder).Construct(0xc003544570, 0xc004ba2f00, 0xc003544360, 0x3e6a1eb, 0x6, 0x3e676be, 0x4, 0xc0060b0a01)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/parse/builder/builder.go:58 +0xe2
github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler.ParseAndValidateBody(0xc0060b0900, 0xc005e6ad01, 0x252a5de, 0xc000d818b8, 0xc0060b0900)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler/validate.go:36 +0x233
github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler.CreateHandler(0xc0060b0900, 0x3ff2110, 0xc004ba2f00, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler/create.go:13 +0x34
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).handle(0xc000505ef0, 0x46c71a0, 0xc0066a3570, 0xc002d9d100, 0xc005e6ae38, 0xba7411a8, 0x53a94414820e76ed)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:249 +0x2a2
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP(0xc000505ef0, 0x46c71a0, 0xc0066a3570, 0xc002d9d100)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:180 +0x99
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentTypeOptions.func1(0x46c71a0, 0xc0066a3570, 0xc002d9d100)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/cache.go:47 +0x131
net/http.HandlerFunc.ServeHTTP(0xc001982940, 0x46c71a0, 0xc0066a3570, 0xc002d9d100)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0008a60c0, 0x46c71a0, 0xc0066a3570, 0xc002d9ce00)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/pkg/auth/requests.authHeaderHandler.ServeHTTP(0x468d560, 0xc0003f13e0, 0x46502e0, 0xc0008a60c0, 0x468d520, 0xc000e96ab0, 0x46c71a0, 0xc0066a3570, 0xc002d9ce00)
	/go/src/github.com/rancher/rancher/pkg/auth/requests/filter.go:62 +0x4eb
github.com/rancher/rancher/pkg/rbac.NewAccessControlHandler.func1(0x46c71a0, 0xc0066a3570, 0xc002d9cc00, 0x464f420, 0xc000d0f2c0)
	/go/src/github.com/rancher/rancher/pkg/rbac/user_based.go:32 +0x194
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/auth.Middleware.Wrap.func1(0x46c71a0, 0xc0066a3570, 0xc002d9cc00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/auth/filter.go:36 +0x55
net/http.HandlerFunc.ServeHTTP(0xc0003f1620, 0x46c71a0, 0xc0066a3570, 0xc002d9cc00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/pkg/websocket.websocketHandler.ServeHTTP(0x46572a0, 0xc0003f1620, 0x46c71a0, 0xc0066a3570, 0xc002d9cc00)
	/go/src/github.com/rancher/rancher/pkg/websocket/handler.go:35 +0xa0
github.com/rancher/rancher/pkg/audit.auditHandler.ServeHTTP(0x464f660, 0xc00034b3e0, 0x0, 0x46c71a0, 0xc0066a3570, 0xc002d9cc00)
	/go/src/github.com/rancher/rancher/pkg/audit/filter.go:31 +0x623
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentType.func1(0x46b5520, 0xc00357dbf0, 0xc002d9cc00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/content.go:33 +0x93
net/http.HandlerFunc.ServeHTTP(0xc0002ce220, 0x46b5520, 0xc00357dbf0, 0xc002d9cc00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.Gzip.func1(0x46c6020, 0xc00472aee0, 0xc002d9cc00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/gzip.go:60 +0x1f5
net/http.HandlerFunc.ServeHTTP(0xc0002ce340, 0x46c6020, 0xc00472aee0, 0xc002d9cc00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentTypeOptions.func1(0x46c6020, 0xc00472aee0, 0xc002d9cc00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/cache.go:47 +0x131
net/http.HandlerFunc.ServeHTTP(0xc001982880, 0x46c6020, 0xc00472aee0, 0xc002d9cc00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0008a6000, 0x46c6020, 0xc00472aee0, 0xc002d9c800)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000e06180, 0x46c6020, 0xc00472aee0, 0xc002d9c400)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000e06240, 0x46c6020, 0xc00472aee0, 0xc001665900)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/dashboard.Route.func2(0x46c6020, 0xc00472aee0, 0xc001665900)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/dashboard/ui.go:56 +0xe5
net/http.HandlerFunc.ServeHTTP(0xc0003ae1b0, 0x46c6020, 0xc00472aee0, 0xc001665900)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001cf140, 0x46c6020, 0xc00472aee0, 0xc001665300)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/server.wrapHandler.func1(0x46c6020, 0xc00472aee0, 0xc001665300)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/server/server.go:187 +0x95
net/http.HandlerFunc.ServeHTTP(0xc003d8d9e0, 0x46c6020, 0xc00472aee0, 0xc001665300)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener.HTTPRedirect.func1(0x46c6020, 0xc00472aee0, 0xc001665300)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/redirect.go:20 +0x221
net/http.HandlerFunc.ServeHTTP(0xc005915ea0, 0x46c6020, 0xc00472aee0, 0xc001665300)
	/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.serverHandler.ServeHTTP(0xc003a64fc0, 0x46c6020, 0xc00472aee0, 0xc001665300)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0052d7c20, 0x46e8a60, 0xc005d23dc0)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e
```

**Other details that may be helpful:**

**Environment information**
- Rancher version: `v2.4.2`
- Installation option (single install/HA): single

**Comment by rawmind0** [comment]
@izaac , your tf file is wrong. you are defining a cluster_template without specifying `scheduled_cluster_scan` and your are deploying a cluster trying to specify `scheduled_cluster_scan`.. This is not allowed.  `scheduled_cluster_scan` should be defined in cluster_template, if you want to use it at downstream clusters. This is not a bug.

**Comment by izaac** [comment]
Closing, As I'm using a Cluster template I should've placed the `scheduled_cluster_scan` section in the TF file above in the Cluster Template instead in the Cluster config.

**Comment by rawmind0** [comment]
Try with this 

```
# Create a new rancher2 cluster template
resource "rancher2_cluster_template" "foo-tmpl" {
  name = "foo2"
  description = "Test cluster template v2"
  members {
    access_type = "owner"
    user_principal_id = "local://user-nchm4"
  }
  template_revisions {
    name = "V2"
    default = true
    cluster_config {
      rke_config {
        network {
          plugin = "canal"
        }
        services {
          etcd {
            creation = "6h"
            retention = "24h"
            backup_config {
              enabled = true
              interval_hours = 1
              retention = 3
              s3_backup_config {
                access_key = "SECRET"
                bucket_name = "SECRET"
                endpoint = "SECRET"
                folder = "SECRET"
                region = "SECRET"
                secret_key = "SECRET"
              }
            }
          }
        }
      }
      scheduled_cluster_scan {
        enabled = true
        scan_config {
          cis_scan_config {
            debug_master = true
            debug_worker = true
          }
        }
        schedule_config {
          cron_schedule = "0 * * * *"
          retention = 5
        }
      }
    }
  }
}

# Create a new rancher2 RKE Cluster from template
resource "rancher2_cluster" "foo-do-tmpl" {
  name = "foo-do-tmpl"
  # driver = "rancherKubernetesEngine"
  cluster_template_id = rancher2_cluster_template.foo-tmpl.id
  cluster_template_revision_id = rancher2_cluster_template.foo-tmpl.template_revisions.0.id
}
```
