### ISSUE TITLE
Helm not updating k8s objects properly

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#26510]
Followup from #21070 

Saw the same behavior using upstream helm too.
Tested with these steps
1. Packaged longhorn app's 0.5.0 and 0.6.0 versions into a chart repo, added this chart repo to minikube cluster
2. Installed longhorn 0.5.0
3. Tiller creates a revision which is shown in "DEPLOYED" state.
```
➜  ~ helm ls
NAME           	REVISION	UPDATED                 	STATUS  	CHART             	APP VERSION	NAMESPACE
cautious-macaw 	1       	Fri Sep 27 15:42:10 2019	DEPLOYED	longhornfive-0.5.0	v0.5.0     	default
```
4. Upgraded release to 0.6.0, upgrade failed with error:
```
➜  ~ UPGRADE FAILED
Error: transport is closing
Error: UPGRADE FAILED: transport is closing
```
5. A release revision corresponding to 0.6.0 is created and is stuck in "PENDING_UPGRADE" as expected since longhorn 0.6.0 was broken.
```
➜  ~ helm history cautious-macaw
REVISION	UPDATED                 	STATUS         	CHART             	DESCRIPTION
1       	Fri Sep 27 15:42:10 2019	DEPLOYED       	longhornfive-0.5.0	Install complete
2       	Fri Sep 27 15:48:08 2019	PENDING_UPGRADE	longhornsix-0.6.0 	Preparing upgrade
3       	Fri Sep 27 15:49:22 2019	PENDING_UPGRADE	longhornfive-0.5.0	Preparing upgrade
```

Also the longhorn pods are stuck in ContainerCreating state
```
➜  ~ kubectl get pods
NAME                                         READY   STATUS              RESTARTS   AGE
longhorn-driver-deployer-7b4fd464d7-7kmkw    0/1     Init:0/1            0          10m
longhorn-driver-deployer-b77fdfbc6-4wsjs     0/1     Init:0/1            0          16m
longhorn-manager-nldt5                       0/1     ContainerCreating   0          10m
longhorn-post-upgrade-v6ftx                  0/1     ContainerCreating   0          10m
```
6. Rollback to version 0.5.0
```
➜  ~ helm rollback cautious-macaw 1
Rollback was a success.
```
Although this is shown as success, the longhorn-manager pods never rollback successfully, they remain stuck in ContainerCreating state and keep using 0.6.0 image instead of 0.5.0
```
longhorn-manager-nldt5                       0/1     ContainerCreating   0          12m
longhorn-post-upgrade-v6ftx                  0/1     ContainerCreating   0          12m
```
7. The configmap created for the latest revision contains 0.5.0 image, same as for Rancher, but never gets applied

So this looks like an upstream helm bug, found similar bugs open in helm repo:
https://github.com/helm/helm/issues/5939
https://github.com/helm/helm/issues/5915

**Comment by zbialik** [comment]
Just ran into something similar on v2.4.. My older helm catalog repo was configured as helm v2 in rancher v2.3.2... when I upgraded, I had no problem deploying most of my helm charts to the kubernetes cluster (which upgraded to v1.17.5). 

But I couldn't get my nginx-ingress controllers helm chart to deploy. Rancher pod logs are shown below:

```
2020/06/02 18:02:51 [INFO] Installing chart using helm version: rancher-helm 
[main] 2020/06/02 18:02:52 Starting Tiller v2.16.5-rancher1 (tls=false) 
[main] 2020/06/02 18:02:52 GRPC listening on :39571 
[main] 2020/06/02 18:02:52 Probes listening on :34926 
[main] 2020/06/02 18:02:52 Storage driver is ConfigMap 
[main] 2020/06/02 18:02:52 Max history per release is 10 
[tiller] 2020/06/02 18:02:52 getting history for release k8s-nginx-ingress 
[storage] 2020/06/02 18:02:52 getting release history for "k8s-nginx-ingress" 
[tiller] 2020/06/02 18:02:53 preparing update for k8s-nginx-ingress 
[storage] 2020/06/02 18:02:53 getting deployed releases from "k8s-nginx-ingress" history 
[storage] 2020/06/02 18:02:53 getting last revision of "k8s-nginx-ingress" 
[storage] 2020/06/02 18:02:53 getting release history for "k8s-nginx-ingress" 
[tiller] 2020/06/02 18:02:53 rendering nginx-ingress chart using values 
[tiller] 2020/06/02 18:02:54 creating updated release for k8s-nginx-ingress 
[storage] 2020/06/02 18:02:54 creating release "k8s-nginx-ingress.v2" 
[storage] 2020/06/02 18:02:54 getting release history for "k8s-nginx-ingress" 
[tiller] 2020/06/02 18:02:54 performing update for k8s-nginx-ingress 
[tiller] 2020/06/02 18:02:54 executing 0 pre-upgrade hooks for k8s-nginx-ingress 
[tiller] 2020/06/02 18:02:54 hooks complete for pre-upgrade k8s-nginx-ingress 
[kube] 2020/06/02 18:02:54 building resources from updated manifest 
[kube] 2020/06/02 18:02:54 checking 13 resources for changes 
[kube] 2020/06/02 18:02:54 Looks like there are no changes for ConfigMap "update-dns-payload" 
[kube] 2020/06/02 18:02:54 Looks like there are no changes for ConfigMap "dns-update-script" 
[kube] 2020/06/02 18:02:54 Looks like there are no changes for ConfigMap "nginx-configuration" 
[kube] 2020/06/02 18:02:54 Looks like there are no changes for ConfigMap "tcp-services" 
[kube] 2020/06/02 18:02:54 Looks like there are no changes for ConfigMap "udp-services" 
[kube] 2020/06/02 18:02:54 Looks like there are no changes for ServiceAccount "nginx-ingress-serviceaccount" 
[kube] 2020/06/02 18:02:54 Looks like there are no changes for ClusterRole "nginx-ingress-clusterrole" 
[kube] 2020/06/02 18:02:54 Looks like there are no changes for ClusterRoleBinding "nginx-ingress-clusterrole-nisa-binding" 
[kube] 2020/06/02 18:02:54 Looks like there are no changes for Role "nginx-ingress-role" 
[kube] 2020/06/02 18:02:54 Looks like there are no changes for RoleBinding "nginx-ingress-role-nisa-binding" 
[kube] 2020/06/02 18:02:54 Looks like there are no changes for Service "nginx-ingress" 
[kube] 2020/06/02 18:02:54 Looks like there are no changes for DaemonSet "nginx-ingress-controller" 
[kube] 2020/06/02 18:02:54 Created a new Job called "dns-update-job" 
[tiller] 2020/06/02 18:02:54 executing 0 post-upgrade hooks for k8s-nginx-ingress 
[tiller] 2020/06/02 18:02:54 hooks complete for post-upgrade k8s-nginx-ingress 
[storage] 2020/06/02 18:02:54 updating release "k8s-nginx-ingress.v1" 
[tiller] 2020/06/02 18:02:55 updating status for updated release for k8s-nginx-ingress 
[storage] 2020/06/02 18:02:55 updating release "k8s-nginx-ingress.v2" 
Release "k8s-nginx-ingress" has been upgraded. 
[storage] 2020/06/02 18:02:55 getting last revision of "k8s-nginx-ingress" 
[storage] 2020/06/02 18:02:55 getting release history for "k8s-nginx-ingress" 
[kube] 2020/06/02 18:02:55 Doing get for ConfigMap: "udp-services" 
[kube] 2020/06/02 18:02:55 Doing get for ConfigMap: "update-dns-payload" 
[kube] 2020/06/02 18:02:55 Doing get for ConfigMap: "dns-update-script" 
[kube] 2020/06/02 18:02:55 Doing get for ConfigMap: "nginx-configuration" 
[kube] 2020/06/02 18:02:55 Doing get for ConfigMap: "tcp-services" 
[kube] 2020/06/02 18:02:55 Doing get for ServiceAccount: "nginx-ingress-serviceaccount" 
[kube] 2020/06/02 18:02:55 Doing get for ClusterRole: "nginx-ingress-clusterrole" 
[kube] 2020/06/02 18:02:55 Doing get for ClusterRoleBinding: "nginx-ingress-clusterrole-nisa-binding" 
[kube] 2020/06/02 18:02:55 Doing get for Role: "nginx-ingress-role" 
[kube] 2020/06/02 18:02:55 Doing get for RoleBinding: "nginx-ingress-role-nisa-binding" 
[kube] 2020/06/02 18:02:55 Doing get for Service: "nginx-ingress" 
[kube] 2020/06/02 18:02:55 Doing get for DaemonSet: "nginx-ingress-controller" 
[kube] 2020/06/02 18:02:55 Doing get for Job: "dns-update-job" 
[kube] 2020/06/02 18:02:55 get relation pod of object: nginx-ingress/ConfigMap/udp-services 
[kube] 2020/06/02 18:02:55 get relation pod of object: nginx-ingress/ConfigMap/dns-update-script 
[kube] 2020/06/02 18:02:55 get relation pod of object: nginx-ingress/ConfigMap/update-dns-payload 
[kube] 2020/06/02 18:02:55 get relation pod of object: nginx-ingress/ConfigMap/nginx-configuration 
[kube] 2020/06/02 18:02:55 get relation pod of object: nginx-ingress/ConfigMap/tcp-services 
[kube] 2020/06/02 18:02:55 get relation pod of object: nginx-ingress/ServiceAccount/nginx-ingress-serviceaccount 
[kube] 2020/06/02 18:02:55 get relation pod of object: /ClusterRole/nginx-ingress-clusterrole 
[kube] 2020/06/02 18:02:55 get relation pod of object: /ClusterRoleBinding/nginx-ingress-clusterrole-nisa-binding 
[kube] 2020/06/02 18:02:55 get relation pod of object: nginx-ingress/Role/nginx-ingress-role 
[kube] 2020/06/02 18:02:55 get relation pod of object: nginx-ingress/RoleBinding/nginx-ingress-role-nisa-binding 
[kube] 2020/06/02 18:02:55 get relation pod of object: nginx-ingress/Service/nginx-ingress 
[kube] 2020/06/02 18:02:55 get relation pod of object: nginx-ingress/DaemonSet/nginx-ingress-controller 
[kube] 2020/06/02 18:02:55 get relation pod of object: nginx-ingress/Job/dns-update-job 
panic: runtime error: invalid memory address or nil pointer dereference 
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x154df7e] 
 
goroutine 767 [running]: 
k8s.io/helm/pkg/kube.getSelectorFromObject(0x1c904c0, 0xc000caa900, 0xc000caa900, 0x0) 
	/go/src/k8s.io/helm/pkg/kube/client.go:1018 +0x2fe 
k8s.io/helm/pkg/kube.(*Client).getSelectRelationPod(0xc00000db80, 0xc000616c40, 0xc0008da300, 0xc0008b01a0, 0x18, 0x0) 
	/go/src/k8s.io/helm/pkg/kube/client.go:1191 +0x195 
k8s.io/helm/pkg/kube.(*Client).Get.func2(0xc000616c40, 0x0, 0x0) 
	/go/src/k8s.io/helm/pkg/kube/client.go:430 +0xa5 
k8s.io/helm/pkg/kube.batchPerform.func1(0xc000456360, 0xc00087d140, 0xc000c4f5b0, 0xc000616c40) 
	/go/src/k8s.io/helm/pkg/kube/client.go:816 +0x30 
created by k8s.io/helm/pkg/kube.batchPerform 
	/go/src/k8s.io/helm/pkg/kube/client.go:815 +0xb8 
2020/06/02 18:02:55 [ERROR] AppController p-vtgw5/k8s-nginx-ingress [helm-controller] failed with : failed to install app k8s-nginx-ingress. Error: transport is closing 
 
```
