### ISSUE TITLE
Panic after adding a worker node to custom cluster

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#26586]
OS: Ubuntu 18.04

Steps :
1. Deploy a custom cluster in 2.0.10 with k8s 1.11.6-rancher1-1 and run pre upgrade checks
2. Upgrade from rancher v2.0.10 to rancher v2.2.9 and run post upgrade checks
3. Upgrade to rancher 2.2.11 and run post upgrade checks
4. Upgrade k8s to 1.14.10 and run post upgrade checks and also add a node
5. Upgrade to 2.4.2 and run post upgrade checks and add a node

The node addition failed and was stuck in "Registering" state :
```
2020/04/09 21:38:08 [ERROR] NodeController c-dkzqr/m-db790889d42b [rke-worker-upgrader] failed with : getNodePlan error for node [m-db790889d42b]: failed to find plan for abcdef
2020/04/09 21:38:08 [ERROR] NodeController c-dkzqr/m-db790889d42b [rke-worker-upgrader] failed with : getNodePlan error for node [m-db790889d42b]: failed to find plan for abcdef
2020/04/09 21:38:09 [INFO] Provisioning cluster [c-dkzqr]
2020/04/09 21:38:09 [INFO] Updating cluster [c-dkzqr]
2020/04/09 21:38:09 [ERROR] NodeController c-dkzqr/m-db790889d42b [rke-worker-upgrader] failed with : getNodePlan error for node [m-db790889d42b]: failed to find plan for abcdef
```
Kubelet does not start on this node. 
```
ubuntu@ip-172-31-11-123:~$ sudo docker ps -a
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS               NAMES
ef2cdc5bb2ea        rancher/hyperkube:v1.14.10-rancher1   "/opt/rke-tools/entr…"   2 hours ago         Up 2 hours                              kube-proxy
9879f038b419        rancher/rancher-agent:v2.4.2          "run.sh --server htt…"   2 hours ago         Up 2 hours                              zen_moore
d49ea28ae1aa        rancher/rke-tools:v0.1.50             "nginx-proxy CP_HOST…"   2 hours ago         Up 2 hours                              nginx-proxy
24edb76888db        rancher/rancher-agent:v2.4.2          "run.sh -- share-roo…"   2 hours ago         Up 2 hours                              share-mnt
11858de1de11        rancher/rke-tools:v0.1.50             "/bin/bash"              2 hours ago         Created                                 service-sidekick
9806205584b1        rancher/rancher-agent:v2.4.2          "run.sh --server htt…"   2 hours ago         Up 2 hours              

```
Added another node and observed a panic as below:
```
2020/04/09 21:59:47 [INFO] Provisioning cluster [c-dkzqr]
2020/04/09 21:59:47 [INFO] Updating cluster [c-dkzqr]
2020/04/09 21:59:51 [INFO] Handling backend connection request [c-dkzqr:m-db790889d42b]
2020/04/09 21:59:51 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
2020/04/09 21:59:52 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:44329
2020/04/09 21:59:52 [INFO] kontainerdriver rancherkubernetesengine stopped
2020/04/09 21:59:52 [INFO] Updated cluster [c-dkzqr] with node version [1]
2020/04/09 21:59:52 [INFO] Provisioned cluster [c-dkzqr]
2020/04/09 21:59:53 [INFO] checking cluster [c-dkzqr] for worker nodes upgrade
2020/04/09 21:59:53 [INFO] binds changed for [kubelet] old: [/etc/kubernetes:/etc/kubernetes:z /etc/cni:/etc/cni:rw,z /opt/cni:/opt/cni:rw,z /var/lib/cni:/var/lib/cni:z /var/lib/calico:/var/lib/calico:z /etc/resolv.conf:/etc/resolv.conf /sys:/sys:rprivate ::rw,rslave,z /var/lib/kubelet:/var/lib/kubelet:shared,z /var/lib/rancher:/var/lib/rancher:shared,z /var/run:/var/run:rw,rprivate /run:/run:rprivate /etc/ceph:/etc/ceph /dev:/host/dev:rprivate /var/log/containers:/var/log/containers:z /var/log/pods:/var/log/pods:z /usr:/host/usr:ro /etc:/host/etc:ro] new [/etc/kubernetes:/etc/kubernetes:z /etc/cni:/etc/cni:rw,z /opt/cni:/opt/cni:rw,z /var/lib/cni:/var/lib/cni:z /var/lib/calico:/var/lib/calico:z /etc/resolv.conf:/etc/resolv.conf /sys:/sys:rprivate /var/lib/docker:/var/lib/docker:rw,rslave,z /var/lib/kubelet:/var/lib/kubelet:shared,z /var/lib/rancher:/var/lib/rancher:shared,z /var/run:/var/run:rw,rprivate /run:/run:rprivate /etc/ceph:/etc/ceph /dev:/host/dev:rprivate /var/log/containers:/var/log/containers:z /var/log/pods:/var/log/pods:z /usr:/host/usr:ro /etc:/host/etc:ro]
2020/04/09 21:59:53 [INFO] cluster [c-dkzqr] worker-upgrade: updated cluster for upgrading: [2] 
2020/04/09 21:59:53 [ERROR] NodeController c-dkzqr/upgrade_ recovered from panic "runtime error: invalid memory address or nil pointer dereference". (err=<nil>) Call stack:
goroutine 12445 [running]:
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.RecoverFromPanic(0xc0080ffd30)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:158 +0xb5
panic(0x3683900, 0x6c320a0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader.(*upgradeHandler).upgradeCluster(0xc0084f0d10, 0xc00ab55180, 0xc00c7dfb50, 0x10, 0x1, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader/upgrade.go:252 +0x613
github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader.(*upgradeHandler).Sync(0xc0084f0d10, 0xc00c7dfb50, 0x10, 0x0, 0xc003098700, 0x7f8109a166d0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader/upgrade.go:83 +0xfc0
github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3.(*nodeController).AddHandler.func1(0xc00c7dfb50, 0x10, 0x0, 0x0, 0xc00b1facd8, 0x3, 0x3, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_node_controller.go:152 +0xe0
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).syncHandler(0xc004844000, 0x33c36c0, 0xc0083f8480, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:387 +0x371
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).processNextWorkItem(0xc004844000, 0xc008623500)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:296 +0xef
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).runWorker(0xc004844000)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:284 +0x2b
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00112ba20)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00112ba20, 0x3b9aca00, 0x0, 0x1, 0xc004a6b680)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00112ba20, 0x3b9aca00, 0xc004a6b680)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).run
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:276 +0xe8

2020/04/09 21:59:54 [INFO] checking cluster [c-dkzqr] for worker nodes upgrade
2020/04/09 21:59:54 [ERROR] NodeController c-dkzqr/upgrade_ recovered from panic "runtime error: invalid memory address or nil pointer dereference". (err=<nil>) Call stack:
goroutine 12441 [running]:

```

The new node got added to the cluster and was in active state.

**Comment by mrajashree** [comment]
Can we also test upgrade from 2.2.11 to 2.3.6 first? So 2.2.11->2.3.6->2.4.2?  
If this issue is repro'd for 2.2.11 to 2.3.6 that will help with debugging

**Comment by soumyalj** [comment]
Tested with upgrade from v 2.0.10 -> v2.2.9->**v2.2.11->v2.3.6-v2.4.2**

1. Deploy a cluster in v2.0.10 with k8s 1.11.6-rancher1-1 using certs from a recognized CA. Cluster config used: 1 control node, 3 etcd nodes and 3 worker nodes
2. Upgrade from rancher v2.0.10 to rancher v2.2.9 
3. Upgrade to  rancher 2.2.11-rc2 and run post upgrade checks
4. Upgrade k8s to 1.14.10 and run post upgrade checks and also add a node
5. Upgrade to 2.3.6 and run post upgrade checks  and add a node
6. Upgrade from v2.3.6 to v2.4.2 . (The cluster went to updating state for a short time).
 Run post upgrade checks and add a node
After upgrading to v2.4.2, logged into each of the nodes and verified that kubelet was running with no restarts. Verified through docker inspect that Restart count = 0
```
      "Name": "/kubelet",
        "RestartCount": 0,

```
Also, verified that all pods in the system project are active.

**Comment by soumyalj** [comment]
Tested with upgrade from v2.2.11 to v2.4.2

1. Created a DO cluster in Rancher v2.2.11 with K8s v1.14.10-rancher1-0. Run pre-upgrade tests
2. Upgrade Rancher to v2.4.2. Run post upgrade tests.
3. Add a new worker node to the cluster and it succeeds.
The following logs are observed :
```
2020/04/15 19:23:01 [INFO] Provisioning node soumyaworker5 done
2020/04/15 19:23:01 [INFO] Generating and uploading node config soumyaworker5
2020/04/15 19:23:01 [ERROR] NodeController c-jfbsd/m-rdr9t [rke-worker-upgrader] failed with : getNodePlan error for node [m-rdr9t]: failed to find plan for abcd
2020/04/15 19:23:01 [ERROR] NodeController c-jfbsd/m-rdr9t [rke-worker-upgrader] failed with : getNodePlan error for node [m-rdr9t]: failed to find plan for abcd
2020/04/15 19:23:02 [INFO] Handling backend connection request [c-jfbsd:m-rdr9t]
2020/04/15 19:23:02 [INFO] Provisioning cluster [c-jfbsd]
2020/04/15 19:23:02 [INFO] Updating cluster [c-jfbsd]
2020/04/15 19:23:06 [ERROR] NodeController c-jfbsd/m-rdr9t [rke-worker-upgrader] failed with : getNodePlan error for node [m-rdr9t]: failed to find plan for abcd
2020/04/15 19:23:07 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:43447
2020/04/15 19:23:07 [INFO] kontainerdriver rancherkubernetesengine stopped
2020/04/15 19:23:07 [INFO] Updated cluster [c-jfbsd] with node version [1]
2020/04/15 19:23:07 [INFO] Provisioned cluster [c-jfbsd]
2020/04/15 19:23:07 [INFO] checking cluster [c-jfbsd] for worker nodes upgrade
```
There was no panic observed in this iteration of testing.

**Comment by soumyalj** [comment]
Tested with upgrade from v 2.0.10 -> v2.2.9->v2.2.11->v2.4-head
Created Rancher server v2.0.10 using Rancher generated certs
Steps:
1. Deploy a cluster in v2.0.10 with k8s 1.11.6-rancher1-1
2. Cluster config used: 1 control node, 3 etcd nodes and 3 worker nodes
3. Upgrade from rancher v2.0.10 to rancher v2.2.9
4. Upgrade to rancher 2.2.11 and run post upgrade checks
5. Upgrade k8s to 1.14.10 and run post upgrade checks and also add a node
6. Upgrade from v2.2.11 to v2.4-head. Run post upgrade checks and add new worker nodes

Node addition was successful There was no panic observed in this upgrade path.
