### ISSUE TITLE
Installing Longhorn causes Rancher panic

### ISSUE THREAD

**Issue by chrisreed87** [rancher/rancher#26599]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
From the Catalog, install Longhorn, using any defaults

**Result:**
Rancher pods log a panic, pods die and respawn/reschedule
```
020/04/09 18:48:51 [INFO] Refreshing all schemas
E0409 18:48:51.727476       7 runtime.go:78] Observed a panic: "close of closed channel" (close of closed channel)
goroutine 27981 [running]:
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3683a20, 0x45ab540)
        /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x3683a20, 0x45ab540)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/rancher/vendor/k8s.io/client-go/tools/cache.(*processorListener).pop(0xc0025b6400)
        /go/src/github.com/rancher/rancher/vendor/k8s.io/client-go/tools/cache/shared_informer.go:632 +0x2e2
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000b33170, 0xc00fa97930)
        /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x59
created by github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
panic: close of closed channel [recovered]
        panic: close of closed channel
goroutine 27981 [running]:
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x3683a20, 0x45ab540)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/rancher/vendor/k8s.io/client-go/tools/cache.(*processorListener).pop(0xc0025b6400)
        /go/src/github.com/rancher/rancher/vendor/k8s.io/client-go/tools/cache/shared_informer.go:632 +0x2e2
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000b33170, 0xc00fa97930)
        /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x59
created by github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
```

**Other details that may be helpful:**
Rancher recovers and Longhorn eventually installs, but this causes a few minutes of Rancher being down. Once this happens is fairly predictable to recreate, uninstall Longhorn, re-install and watch it happen again

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher v2.4.2, longhorn 0.8
- Installation option (single install/HA): HA - K3s backend

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`): 

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4+k3s1", GitCommit:"3eee8ac3a1cf0a216c8a660571329d4bda3bdf77", GitTreeState:"clean", BuildDate:"2020-03-25T16:13:25Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
 
- Docker version (use `docker version`): 

```
N/A, containerd via k3s
```

**Comment by sowmyav27** [comment]
**Verified on 2.4.2 - HA setup - 1 node DO cluster**

- Deploy Longhorn app from the from the catalog.
- Longhorn gets deployed successfully
- No panic is seen in rancher logs.
