### ISSUE TITLE
Cluster goes into updating state when adding a worker node and a panic is seen on the cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26792]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. This is on an upgraded rancher from 2.3.6 to 2.4.3-rc2
2. Deploy a custom cluster - 3 etcd, 2 control, 3 worker nodes in 2.3.6
3. upgrade rancher to 2.4.3-rc2
4. Add a worker node. 
5. Worker node is stuck in "Registering" state
6. Add another worker node.
7. This is also stuck in Registering state, 
8. But an existing worker node in cluster is in "Cordoned" state
9. Cluster goes into "Updating" state.
10. An rke up is triggered.
11. Now the cluster is stuck in "Updating" state
12. There is a panic in the cluster

```
Updated cluster [c-lr9nb] with node version [2]
2020/04/24 01:15:52 [INFO] Provisioned cluster [c-lr9nb]
2020/04/24 01:15:52 [INFO] checking cluster [c-lr9nb] for worker nodes upgrade
2020/04/24 01:15:52 [ERROR] NodeController c-lr9nb/upgrade_ recovered from panic "runtime error: invalid memory address or nil pointer dereference". (err=<nil>) Call stack:
goroutine 18685 [running]:
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.RecoverFromPanic(0xc008911d30)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:158 +0xb5
panic(0x3686aa0, 0x6c38100)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader.(*upgradeHandler).upgradeCluster(0xc00b5af340, 0xc0052e9700, 0xc0064a26a0, 0x10, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader/upgrade.go:262 +0x630
github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader.(*upgradeHandler).Sync(0xc00b5af340, 0xc0064a26a0, 0x10, 0x0, 0xc000abc380, 0x7f63c16cc6d0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader/upgrade.go:84 +0xfc0
github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3.(*nodeController).AddHandler.func1(0xc0064a26a0, 0x10, 0x0, 0x0, 0xc0077a3cd8, 0x3, 0x3, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_node_controller.go:152 +0xe0
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).syncHandler(0xc006a6f480, 0x33c6780, 0xc009e74c40, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:387 +0x371
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).processNextWorkItem(0xc006a6f480, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:296 +0xef
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).runWorker(0xc006a6f480)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:284 +0x2b
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc009713710)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc009713710, 0x3b9aca00, 0x0, 0x1, 0xc001ac5020)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc009713710, 0x3b9aca00, 0xc001ac5020)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).run
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:276 +0xe8

2020/04/24 01:15:53 [INFO] checking cluster [c-lr9nb] for worker nodes upgrade
2020/04/24 01:15:53 [ERROR] NodeController c-lr9nb/upgrade_ recovered from panic "runtime error: invalid memory address or nil pointer dereference". (err=<nil>) Call stack:
goroutine 18686 [running]:
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.RecoverFromPanic(0xc008fd7d30)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:158 +0xb5
panic(0x3686aa0, 0x6c38100)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader.(*upgradeHandler).upgradeCluster(0xc00b5af340, 0xc0052e9700, 0xc0064a26a0, 0x10, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader/upgrade.go:262 +0x630
github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader.(*upgradeHandler).Sync(0xc00b5af340, 0xc0064a26a0, 0x10, 0x0, 0xc0091a9880, 0x7f63c16cc6d0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader/upgrade.go:84 +0xfc0
github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3.(*nodeController).AddHandler.func1(0xc0064a26a0, 0x10, 0x0, 0x0, 0xc00773acd8, 0x3, 0x3, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_node_controller.go:152 +0xe0
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).syncHandler(0xc006a6f480, 0x33c6780, 0xc009e74c40, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:387 +0x371
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).processNextWorkItem(0xc006a6f480, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:296 +0xef
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).runWorker(0xc006a6f480)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:284 +0x2b
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc009713720)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc009713720, 0x3b9aca00, 0x0, 0x1, 0xc001ac5020)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc009713720, 0x3b9aca00, 0xc001ac5020)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).run
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:276 +0xe8

2020/04/24 01:15:55 [INFO] checking cluster [c-lr9nb] for worker nodes upgrade
2020/04/24 01:15:55 [ERROR] NodeController c-lr9nb/upgrade_ recovered from panic "runtime error: invalid memory address or nil pointer dereference". (err=<nil>) Call stack:
goroutine 18682 [running]:
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.RecoverFromPanic(0xc004ae9d30)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:158 +0xb5
panic(0x3686aa0, 0x6c38100)

```

**Expected Result:**
Cluster should not go into updating state when a worker node is added

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.6 to 2.4.3-rc2
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom RKE
- Kubernetes version (use `kubectl version`):

```
1.17.4
```

**Comment by sowmyav27** [comment]
Panic and the cordoning does not seem to be related as per this bug -- https://github.com/rancher/rancher/issues/26807

**Comment by sowmyav27** [comment]
Verified on a custom image from 2.4-release and master branch 

**Steps:**

- Create a custom cluster - 1 node all roles
- Add a worker node - The worker node will be stuck in registering state because of this issue - https://github.com/rancher/rancher/issues/26790
- Add more worker nodes 
- No panic is seen
- The cluster goes into `Updating` state for about 3-5 seconds and comes back to `Active`.
- Existing "Active" worker nodes do NOT go into "Cordoned" state.
