### ISSUE TITLE
Problem with rancher/agent 0.8.2 (some go error)

### ISSUE THREAD

**Issue by disaster37** [rancher/rancher#2682]
Today, I have resintalled on node, but rancher not work.

I have to many log about go error.

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 11 [syscall]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 13 [select]:
net.lookupIPDeadline(0xc2080c3f00, 0x18, 0xecdda6e6e, 0x158de780, 0x11135c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/lookup.go:82 +0x6cb
net.resolveInternetAddr(0xace950, 0x3, 0xc2080c3f00, 0x1b, 0xecdda6e6e, 0x158de780, 0x11135c0, 0x0, 0x0, 0x0, ...)
	/usr/src/go/src/net/ipsock.go:285 +0x49b
net.resolveAddr(0xabff70, 0x4, 0xace950, 0x3, 0xc2080c3f00, 0x1b, 0xecdda6e6e, 0x158de780, 0x11135c0, 0x0, ...)
	/usr/src/go/src/net/dial.go:110 +0x378
net.(*Dialer).Dial(0xc208032b00, 0xace950, 0x3, 0xc2080c3f00, 0x1b, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/dial.go:158 +0xf6
net.*Dialer.Dial·fm(0xace950, 0x3, 0xc2080c3f00, 0x1b, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/http/transport.go:38 +0x79
net/http.(*Transport).dial(0xc2080701b0, 0xace950, 0x3, 0xc2080c3f00, 0x1b, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/http/transport.go:479 +0x84
net/http.(*Transport).dialConn(0xc2080701b0, 0x0, 0xb60550, 0x4, 0xc2080c3f00, 0x1b, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/http/transport.go:564 +0x1678
net/http.func·019()
	/usr/src/go/src/net/http/transport.go:520 +0x42
created by net/http.(*Transport).getConn
	/usr/src/go/src/net/http/transport.go:522 +0x335
I1115 13:15:43.610460 01857 storagedriver.go:100] No backend storage selected
I1115 13:15:43.610532 01857 storagedriver.go:102] Caching stats in memory for 2m0s
I1115 13:15:43.610593 01857 manager.go:127] cAdvisor running in container: "/system.slice/docker-ead0cd1e5eb6665d0631fa7758216deaa236ff05d79ee0aa67b80c94ba7136c1.scope"
I1115 13:15:43.610975 01857 fs.go:93] Filesystem partitions: map[/dev/vda9:{mountpoint:/ major:254 minor:9} /dev/vda3:{mountpoint:/usr major:254 minor:3} /dev/vda6:{mountpoint:/usr/share/oem major:254 minor:6} /dev/mapper/VG_DATA-LV_DOCKER:{mountpoint:/var/lib/docker major:0 minor:36} /dev/mapper/VG_DATA-LV_DATA:{mountpoint:/data major:253 minor:1}]
E1115 13:15:43.611948 01857 machine.go:274] Failed to get system UUID: open /proc/device-tree/vm,uuid: no such file or directory
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.gothrow(0xb9f4d0, 0x2a)
	/usr/src/go/src/runtime/panic.go:503 +0x8e
runtime.sigpanic()
	/usr/src/go/src/runtime/sigpanic_unix.go:14 +0x5e

goroutine 14 [syscall, locked to thread]:
runtime.cgocall_errno(0x401930, 0xc208019cd0, 0x0)
	/usr/src/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc208019c90 sp=0xc208019c68
net._C2func_getaddrinfo(0x119ae50, 0x0, 0xc208019dc8, 0xc208019d18, 0xc200000000, 0x0, 0x0)
	/usr/src/go/src/net/:26 +0x55 fp=0xc208019cd0 sp=0xc208019c90
net.cgoLookupIPCNAME(0xc2080cdd60, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/cgo_unix.go:96 +0x1c5 fp=0xc208019e00 sp=0xc208019cd0
net.cgoLookupIP(0xc2080cdd60, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/cgo_unix.go:148 +0x65 fp=0xc208019e58 sp=0xc208019e00
net.lookupIP(0xc2080cdd60, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/lookup_unix.go:64 +0x5f fp=0xc208019ea0 sp=0xc208019e58
net.func·026(0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/lookup.go:79 +0x55 fp=0xc208019f08 sp=0xc208019ea0
net.(*singleflight).doCall(0x1112970, 0xc208044f60, 0xc2080cdd60, 0x18, 0xc2080757c0)
	/usr/src/go/src/net/singleflight.go:91 +0x2f fp=0xc208019fb8 sp=0xc208019f08
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208019fc0 sp=0xc208019fb8
created by net.(*singleflight).DoChan
	/usr/src/go/src/net/singleflight.go:84 +0x42b

goroutine 1 [select]:
net/http.(*Transport).getConn(0xc2080681b0, 0xc2080356c0, 0x0, 0xb60550, 0x4, 0xc2080cdd60, 0x1b, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/http/transport.go:525 +0x608
net/http.(*Transport).RoundTrip(0xc2080681b0, 0xc2080356c0, 0xa, 0x0, 0x0)
	/usr/src/go/src/net/http/transport.go:228 +0x4d4
google.golang.org/cloud/internal.(*UATransport).RoundTrip(0xc20802af60, 0xc2080356c0, 0xc2080cdd40, 0x0, 0x0)
	/source/build/src/github.com/google/cadvisor/Godeps/_workspace/src/google.golang.org/cloud/internal/cloud.go:47 +0x109
net/http.send(0xc2080355f0, 0x7fc2dd8b5b28, 0xc20802af60, 0x1f, 0x0, 0x0)
	/usr/src/go/src/net/http/client.go:219 +0x4fc
net/http.(*Client).send(0x1113420, 0xc2080355f0, 0x1f, 0x0, 0x0)
	/usr/src/go/src/net/http/client.go:142 +0x15b
net/http.(*Client).doFollowingRedirects(0x1113420, 0xc2080355f0, 0xc08450, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/http/client.go:367 +0xb25
net/http.(*Client).Get(0x1113420, 0xb60550, 0x1f, 0x54, 0x0, 0x0)
	/usr/src/go/src/net/http/client.go:299 +0xba
github.com/GoogleCloudPlatform/gcloud-golang/compute/metadata.OnGCE(0x0)
	/source/build/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/GoogleCloudPlatform/gcloud-golang/compute/metadata/metadata.go:126 +0xa6
github.com/google/cadvisor/utils/cloudinfo.onGCE(0xc20809ee00)
	/source/build/src/github.com/google/cadvisor/utils/cloudinfo/gce.go:25 +0x1f
github.com/google/cadvisor/utils/cloudinfo.detectCloudProvider(0x0, 0x0)
	/source/build/src/github.com/google/cadvisor/utils/cloudinfo/cloudinfo.go:52 +0x31
github.com/google/cadvisor/utils/cloudinfo.NewRealCloudInfo(0x0, 0x0)
	/source/build/src/github.com/google/cadvisor/utils/cloudinfo/cloudinfo.go:34 +0x31
github.com/google/cadvisor/manager.getMachineInfo(0x7fc2dd8b61d8, 0x1122fb8, 0x7fc2dd8b6348, 0xc208074a60, 0x11135c0, 0x0, 0x0)
	/source/build/src/github.com/google/cadvisor/manager/machine.go:277 +0x82e
github.com/google/cadvisor/manager.New(0xc20809c540, 0x7fc2dd8b61d8, 0x1122fb8, 0x0, 0x0, 0x0, 0x0)
	/source/build/src/github.com/google/cadvisor/manager/manager.go:151 +0x5d0
main.main()
	/source/build/src/github.com/google/cadvisor/cadvisor.go:69 +0x454

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1113980)
	/source/build/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:839 +0x78
created by github.com/golang/glog.init·1
	/source/build/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:406 +0x2a7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 11 [syscall]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 13 [select]:
net.lookupIPDeadline(0xc2080cdd60, 0x18, 0xecdda6e70, 0x1593cebb, 0x11135c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/lookup.go:82 +0x6cb
net.resolveInternetAddr(0xace950, 0x3, 0xc2080cdd60, 0x1b, 0xecdda6e70, 0x1593cebb, 0x11135c0, 0x0, 0x0, 0x0, ...)
	/usr/src/go/src/net/ipsock.go:285 +0x49b
net.resolveAddr(0xabff70, 0x4, 0xace950, 0x3, 0xc2080cdd60, 0x1b, 0xecdda6e70, 0x1593cebb, 0x11135c0, 0x0, ...)
	/usr/src/go/src/net/dial.go:110 +0x378
net.(*Dialer).Dial(0xc208032b00, 0xace950, 0x3, 0xc2080cdd60, 0x1b, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/dial.go:158 +0xf6
net.*Dialer.Dial·fm(0xace950, 0x3, 0xc2080cdd60, 0x1b, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/http/transport.go:38 +0x79
net/http.(*Transport).dial(0xc2080681b0, 0xace950, 0x3, 0xc2080cdd60, 0x1b, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/http/transport.go:479 +0x84
net/http.(*Transport).dialConn(0xc2080681b0, 0x0, 0xb60550, 0x4, 0xc2080cdd60, 0x1b, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/http/transport.go:564 +0x1678
net/http.func·019()
	/usr/src/go/src/net/http/transport.go:520 +0x42
created by net/http.(*Transport).getConn
	/usr/src/go/src/net/http/transport.go:522 +0x335
I1115 13:15:45.622782 01887 storagedriver.go:100] No backend storage selected
I1115 13:15:45.623078 01887 storagedriver.go:102] Caching stats in memory for 2m0s
I1115 13:15:45.623173 01887 manager.go:127] cAdvisor running in container: "/system.slice/docker-ead0cd1e5eb6665d0631fa7758216deaa236ff05d79ee0aa67b80c94ba7136c1.scope"
I1115 13:15:45.623819 01887 fs.go:93] Filesystem partitions: map[/dev/vda6:{mountpoint:/usr/share/oem major:254 minor:6} /dev/mapper/VG_DATA-LV_DOCKER:{mountpoint:/var/lib/docker major:0 minor:36} /dev/mapper/VG_DATA-LV_DATA:{mountpoint:/data major:253 minor:1} /dev/vda9:{mountpoint:/ major:254 minor:9} /dev/vda3:{mountpoint:/usr major:254 minor:3}]
E1115 13:15:45.625408 01887 machine.go:274] Failed to get system UUID: open /proc/device-tree/vm,uuid: no such file or directory
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.gothrow(0xb9f4d0, 0x2a)
	/usr/src/go/src/runtime/panic.go:503 +0x8e
runtime.sigpanic()
	/usr/src/go/src/runtime/sigpanic_unix.go:14 +0x5e

goroutine 14 [syscall, locked to thread]:
runtime.cgocall_errno(0x401930, 0xc20801b4d0, 0x0)
	/usr/src/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc20801b490 sp=0xc20801b468
net._C2func_getaddrinfo(0x2aa6e50, 0x0, 0xc20801b5c8, 0xc20801b518, 0xc200000000, 0x0, 0x0)
	/usr/src/go/src/net/:26 +0x55 fp=0xc20801b4d0 sp=0xc20801b490
net.cgoLookupIPCNAME(0xc2080c3f00, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/cgo_unix.go:96 +0x1c5 fp=0xc20801b600 sp=0xc20801b4d0
net.cgoLookupIP(0xc2080c3f00, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/cgo_unix.go:148 +0x65 fp=0xc20801b658 sp=0xc20801b600
net.lookupIP(0xc2080c3f00, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/lookup_unix.go:64 +0x5f fp=0xc20801b6a0 sp=0xc20801b658
net.func·026(0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/lookup.go:79 +0x55 fp=0xc20801b708 sp=0xc20801b6a0
net.(*singleflight).doCall(0x1112970, 0xc208044f60, 0xc2080c3f00, 0x18, 0xc208075920)
	/usr/src/go/src/net/singleflight.go:91 +0x2f fp=0xc20801b7b8 sp=0xc20801b708
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801b7c0 sp=0xc20801b7b8
created by net.(*singleflight).DoChan
	/usr/src/go/src/net/singleflight.go:84 +0x42b

goroutine 1 [select]:
net/http.(*Transport).getConn(0xc2080681b0, 0xc2080356c0, 0x0, 0xb60550, 0x4, 0xc2080c3f00, 0x1b, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/http/transport.go:525 +0x608
net/http.(*Transport).RoundTrip(0xc2080681b0, 0xc2080356c0, 0xa, 0x0, 0x0)
	/usr/src/go/src/net/http/transport.go:228 +0x4d4
google.golang.org/cloud/internal.(*UATransport).RoundTrip(0xc20802af60, 0xc2080356c0, 0xc2080c3ee0, 0x0, 0x0)
	/source/build/src/github.com/google/cadvisor/Godeps/_workspace/src/google.golang.org/cloud/internal/cloud.go:47 +0x109
net/http.send(0xc2080355f0, 0x7f9688ff9b28, 0xc20802af60, 0x1f, 0x0, 0x0)
	/usr/src/go/src/net/http/client.go:219 +0x4fc
net/http.(*Client).send(0x1113420, 0xc2080355f0, 0x1f, 0x0, 0x0)
	/usr/src/go/src/net/http/client.go:142 +0x15b
net/http.(*Client).doFollowingRedirects(0x1113420, 0xc2080355f0, 0xc08450, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/http/client.go:367 +0xb25
net/http.(*Client).Get(0x1113420, 0xb60550, 0x1f, 0x54, 0x0, 0x0)
	/usr/src/go/src/net/http/client.go:299 +0xba
github.com/GoogleCloudPlatform/gcloud-golang/compute/metadata.OnGCE(0x0)
	/source/build/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/GoogleCloudPlatform/gcloud-golang/compute/metadata/metadata.go:126 +0xa6
github.com/google/cadvisor/utils/cloudinfo.onGCE(0xc20809ee00)
	/source/build/src/github.com/google/cadvisor/utils/cloudinfo/gce.go:25 +0x1f
github.com/google/cadvisor/utils/cloudinfo.detectCloudProvider(0x0, 0x0)
	/source/build/src/github.com/google/cadvisor/utils/cloudinfo/cloudinfo.go:52 +0x31
github.com/google/cadvisor/utils/cloudinfo.NewRealCloudInfo(0x0, 0x0)
	/source/build/src/github.com/google/cadvisor/utils/cloudinfo/cloudinfo.go:34 +0x31
github.com/google/cadvisor/manager.getMachineInfo(0x7f9688ffa1d8, 0x1122fb8, 0x7f9688ffa420, 0xc208074bc0, 0x11135c0, 0x0, 0x0)
	/source/build/src/github.com/google/cadvisor/manager/machine.go:277 +0x82e
github.com/google/cadvisor/manager.New(0xc20809c880, 0x7f9688ffa1d8, 0x1122fb8, 0x0, 0x0, 0x0, 0x0)
	/source/build/src/github.com/google/cadvisor/manager/manager.go:151 +0x5d0
main.main()
	/source/build/src/github.com/google/cadvisor/cadvisor.go:69 +0x454

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1113980)
	/source/build/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:839 +0x78
created by github.com/golang/glog.init·1
	/source/build/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:406 +0x2a7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1

**Comment by disaster37** [comment]
already exit on #2664
