### ISSUE TITLE
Catalog git clone can occassionally get stuck in corrupted state. 

### ISSUE THREAD

**Issue by AnalogJ** [rancher/rancher#2683]
I have a custom catalog url specified via an environmental variable. I'm testing rancher+docker inside a vagrant vm. Occassionally after putting my machine to sleep and waking it up again, I'll notice that the Catalog will stop updating (the default update time seems to be 5 minutes). 

I've tried `docker restart` on the manager container, and when I do I see the following message:

        time="2015-11-15T17:09:52Z" level=info msg="Starting Rancher Catalog service" 
        time="2015-11-15T17:09:52Z" level=info msg="Cloning the catalog from github url https://github.com/mediadepot/rancher-catalog.git" 
        Cloning into './DATA'...
        fatal: unable to access 'https://github.com/mediadepot/rancher-catalog.git/': Could not resolve host: github.com
        time="2015-11-15T17:10:12Z" level=fatal msg="Failed to clone the catalog from githubexit status 128" 
        2015-11-15 17:10:12,923 ERROR [:] [] [] [] [tp1860112097-18] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [io.github.ibuildthecloud.gdapi.request.ApiRequest@6ba46df0] org.apache.http.conn.HttpHostConnectException: Connect to localhost:8088 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
                at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:138) ~[httpclient-4.3.1.jar:4.3.1]
                at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314) ~[httpclient-4.3.1.jar:4.3.1]
                at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:357) ~[httpclient-4.3.1.jar:4.3.1]
                at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:218) ~[httpclient-4.3.1.jar:4.3.1]
                at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194) ~[httpclient-4.3.1.jar:4.3.1]
                at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85) ~[httpclient-4.3.1.jar:4.3.1]
                at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108) ~[httpclient-4.3.1.jar:4.3.1]
                at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186) ~[httpclient-4.3.1.jar:4.3.1]
                at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.3.1.jar:4.3.1]
                at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106) ~[httpclient-4.3.1.jar:4.3.1]
                at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57) ~[httpclient-4.3.1.jar:4.3.1]
                at org.apache.http.client.fluent.Request.execute(Request.java:143) ~[fluent-hc-4.3.1.jar:4.3.1]
                at io.cattle.platform.iaas.api.request.handler.GenericWhitelistedProxy.generate(GenericWhitelistedProxy.java:150) ~[cattle-iaas-api-logic-0.5.0-SNAPSHOT.jar:na]
                at io.github.ibuildthecloud.gdapi.request.handler.AbstractResponseGenerator.handle(AbstractResponseGenerator.java:14) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
                at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:86) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
                at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:79) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
                at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
                at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
                at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
                at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
                at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
                at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:72) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
                at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:595) [jetty-security-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:191) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:72) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
                at io.cattle.platform.iaas.api.servlet.filter.ProxyFilter.doFilter(ProxyFilter.java:29) [cattle-iaas-api-logic-0.5.0-SNAPSHOT.jar:na]
                at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [jetty-security-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.server.Server.handle(Server.java:499) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
                at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
                at java.lang.Thread.run(Thread.java:745) [na:1.7.0_85]
        Caused by: java.net.ConnectException: Connection refused
                at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_85]
                at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_85]
                at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_85]
                at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_85]
                at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_85]
                at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_85]
                at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72) ~[httpclient-4.3.1.jar:4.3.1]
                at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:118) ~[httpclient-4.3.1.jar:4.3.1]
                ... 55 common frames omitted

        time="2015-11-15T17:10:14Z" level=info msg="Starting Rancher Catalog service" 
        time="2015-11-15T17:10:14Z" level=info msg="Cloning the catalog from github url https://github.com/mediadepot/rancher-catalog.git" 
        Cloning into './DATA'...
        fatal: unable to access 'https://github.com/mediadepot/rancher-catalog.git/': Could not resolve host: github.com
        time="2015-11-15T17:10:34Z" level=fatal msg="Failed to clone the catalog from githubexit status 128" 
        time="2015-11-15T17:10:36Z" level=info msg="Starting Rancher Catalog service" 
        time="2015-11-15T17:10:36Z" level=info msg="Cloning the catalog from github url https://github.com/mediadepot/rancher-catalog.git" 
        Cloning into './DATA'...
        fatal: unable to access 'https://github.com/mediadepot/rancher-catalog.git/': Could not resolve host: github.com
        time="2015-11-15T17:10:56Z" level=fatal msg="Failed to clone the catalog from githubexit status 128" 
        time="2015-11-15T17:10:58Z" level=info msg="Starting Rancher Catalog service" 
        time="2015-11-15T17:10:58Z" level=info msg="Cloning the catalog from github url https://github.com/mediadepot/rancher-catalog.git" 
        Cloning into './DATA'...
        fatal: unable to access 'https://github.com/mediadepot/rancher-catalog.git/': Could not resolve host: github.com
        time="2015-11-15T17:11:18Z" level=fatal msg="Failed to clone the catalog from githubexit status 128" 
        time="2015-11-15T17:11:20Z" level=info msg="Starting Rancher Catalog service" 
        time="2015-11-15T17:11:20Z" level=info msg="Cloning the catalog from github url https://github.com/mediadepot/rancher-catalog.git" 
        Cloning into './DATA'...

My naive understanding is that the git clone failed due to connection issue, and then every future attempt to download the catalog failed due to a corrupted .git folder

**Comment by prachidamle** [comment]
@AnalogJ  Everytime the Catalog service is started, it is throwing connection refused "Could not resolve host: github.com"

Seems like the server container is not able to reach github.com any time. 

The periodic updates will not kick in until this connection issue is resolved and the catalog is newly cloned successfully(on every start of the service, the previously downloaded catalog is removed and newly cloned from git repo url)

To me it looks like the catalog was never cloned due to connection issue...

**Comment by AnalogJ** [comment]
You might be right about this issue. I've since made some additional configuration changes to my server, and I no longer see this issue. Closing.
