### ISSUE TITLE
Unable to update cluster RKE Template version

### ISSUE THREAD

**Issue by Just-Insane** [rancher/rancher#26845]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1) Create an RKE template for a cluster
2) Update the RKE template to allow changes for ETCD S3 storage location
3) Try to apply the RKE template

**Result:**
RKE template does not apply, error output is per screenshot.

![Screen Shot 2020-04-28 at 6 28 29 PM](https://user-images.githubusercontent.com/15903884/80544649-7d0bd200-897f-11ea-9a25-3772628caa2b.png)

Alternatively, trying in Chrome produces the following:

![Screen Shot 2020-04-28 at 6 47 55 PM](https://user-images.githubusercontent.com/15903884/80545241-de807080-8980-11ea-8c5e-557230a38066.png)

**Other details that may be helpful:**
Rancher master cluster nodes and created cluster nodes are all running the latest version of RancherOS.

Rancher master cluster is behind haproxy, with 3x nodes.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Metal, AMD GX-415GA/4Gb RAM per node, 4 nodes total, 3x etcd & control plane, 1x worker
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:22:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Here are some logs from one of the ETCD nodes in the rancher master cluster when clicking the Save button trying to update the template:

```
2020-04-28T23:23:53.356845015Z 2020/04/28 23:23:53 [ERROR] Panic serving api request:
2020-04-28T23:23:53.356980003Z goroutine 580357 [running]:
2020-04-28T23:23:53.357019303Z runtime/debug.Stack(0xc0190887f8, 0x3683900, 0x6c320a0)
2020-04-28T23:23:53.357055190Z  /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
2020-04-28T23:23:53.357090585Z github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP.func1(0x46c71a0, 0xc0065d6560)
2020-04-28T23:23:53.357125398Z  /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:175 +0x7a
2020-04-28T23:23:53.357160619Z panic(0x3683900, 0x6c320a0)
2020-04-28T23:23:53.357194597Z  /usr/local/go/src/runtime/panic.go:679 +0x1b2
2020-04-28T23:23:53.357228156Z github.com/rancher/rancher/pkg/api/customization/cluster.(*Validator).validateScheduledClusterScan(0xc000d066e0, 0xc01c18edc0, 0xc01c18edc0, 0x0)
2020-04-28T23:23:53.357306357Z  /go/src/github.com/rancher/rancher/pkg/api/customization/cluster/validator.go:67 +0x70
2020-04-28T23:23:53.357339780Z github.com/rancher/rancher/pkg/api/customization/cluster.(*Validator).Validator(0xc000d066e0, 0xc01a416900, 0xc005823a40, 0xc030a891a0, 0x0, 0xc030a891a0)
2020-04-28T23:23:53.357373628Z  /go/src/github.com/rancher/rancher/pkg/api/customization/cluster/validator.go:56 +0x23d
2020-04-28T23:23:53.357405762Z github.com/rancher/rancher/vendor/github.com/rancher/norman/parse/builder.(*Builder).Construct(0xc030a89110, 0xc005823a40, 0xc03037cbd0, 0x3e6af47, 0x6, 0x3e66cdc, 0x3e66cdc, 0x3)
2020-04-28T23:23:53.357438957Z  /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/parse/builder/builder.go:58 +0xe2
2020-04-28T23:23:53.357470969Z github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler.ParseAndValidateBody(0xc01a416900, 0x0, 0x0, 0xc019088c00, 0x252a828)
2020-04-28T23:23:53.357503476Z  /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler/validate.go:36 +0x233
2020-04-28T23:23:53.357535492Z github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler.UpdateHandler(0xc01a416900, 0x3ff2130, 0x0, 0xc005823a40)
2020-04-28T23:23:53.357567787Z  /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler/update.go:11 +0x34
2020-04-28T23:23:53.359577494Z github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).handle(0xc0004a8c60, 0x46c71a0, 0xc0065d6560, 0xc00a18fe00, 0xc019088d08, 0x2872d51, 0x46802e770e68fc88)
2020-04-28T23:23:53.359663254Z  /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:249 +0x2a2
2020-04-28T23:23:53.359709872Z github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP(0xc0004a8c60, 0x46c71a0, 0xc0065d6560, 0xc00a18fe00)
2020-04-28T23:23:53.359732886Z  /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:180 +0x99
2020-04-28T23:23:53.359754841Z github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentTypeOptions.func1(0x46c71a0, 0xc0065d6560, 0xc00a18fe00)
2020-04-28T23:23:53.359777159Z  /go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/cache.go:47 +0x131
2020-04-28T23:23:53.359799351Z net/http.HandlerFunc.ServeHTTP(0xc00afe0600, 0x46c71a0, 0xc0065d6560, 0xc00a18fe00)
2020-04-28T23:23:53.359821124Z  /usr/local/go/src/net/http/server.go:2007 +0x44
2020-04-28T23:23:53.359842970Z github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000d9980, 0x46c71a0, 0xc0065d6560, 0xc00a18f800)
2020-04-28T23:23:53.359864928Z  /go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
2020-04-28T23:23:53.359886526Z github.com/rancher/rancher/pkg/auth/requests.authHeaderHandler.ServeHTTP(0x468d560, 0xc0016d8ea0, 0x46502e0, 0xc0000d9980, 0x468d520, 0xc00166d170, 0x46c71a0, 0xc0065d6560, 0xc00a18f800)
2020-04-28T23:23:53.359908716Z  /go/src/github.com/rancher/rancher/pkg/auth/requests/filter.go:62 +0x4eb
2020-04-28T23:23:53.359929965Z github.com/rancher/rancher/pkg/rbac.NewAccessControlHandler.func1(0x46c71a0, 0xc0065d6560, 0xc00a18f700, 0x464f420, 0xc0016eb710)
2020-04-28T23:23:53.359991724Z  /go/src/github.com/rancher/rancher/pkg/rbac/user_based.go:32 +0x194
2020-04-28T23:23:53.360015322Z github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/auth.Middleware.Wrap.func1(0x46c71a0, 0xc0065d6560, 0xc00a18f700)
2020-04-28T23:23:53.360037806Z  /go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/auth/filter.go:36 +0x55
2020-04-28T23:23:53.360059429Z net/http.HandlerFunc.ServeHTTP(0xc0016d9060, 0x46c71a0, 0xc0065d6560, 0xc00a18f700)
2020-04-28T23:23:53.360081414Z  /usr/local/go/src/net/http/server.go:2007 +0x44
2020-04-28T23:23:53.360102507Z github.com/rancher/rancher/pkg/websocket.websocketHandler.ServeHTTP(0x46572a0, 0xc0016d9060, 0x46c71a0, 0xc0065d6560, 0xc00a18f700)
2020-04-28T23:23:53.360124848Z  /go/src/github.com/rancher/rancher/pkg/websocket/handler.go:35 +0xa0
2020-04-28T23:23:53.360146631Z github.com/rancher/rancher/pkg/audit.auditHandler.ServeHTTP(0x464f660, 0xc00052cb00, 0x0, 0x46c71a0, 0xc0065d6560, 0xc00a18f700)
2020-04-28T23:23:53.360168872Z  /go/src/github.com/rancher/rancher/pkg/audit/filter.go:31 +0x623
2020-04-28T23:23:53.360192368Z github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentType.func1(0x46b5520, 0xc02be3ca80, 0xc00a18f700)
2020-04-28T23:23:53.360214772Z  /go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/content.go:33 +0x93
2020-04-28T23:23:53.360237206Z net/http.HandlerFunc.ServeHTTP(0xc00171c0c0, 0x46b5520, 0xc02be3ca80, 0xc00a18f700)
2020-04-28T23:23:53.360258944Z  /usr/local/go/src/net/http/server.go:2007 +0x44
2020-04-28T23:23:53.360280479Z github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.Gzip.func1(0x46c6020, 0xc0068750a0, 0xc00a18f700)
2020-04-28T23:23:53.360302271Z  /go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/gzip.go:60 +0x1f5
2020-04-28T23:23:53.360323881Z net/http.HandlerFunc.ServeHTTP(0xc00171c0e0, 0x46c6020, 0xc0068750a0, 0xc00a18f700)
2020-04-28T23:23:53.360347166Z  /usr/local/go/src/net/http/server.go:2007 +0x44
2020-04-28T23:23:53.360368826Z github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentTypeOptions.func1(0x46c6020, 0xc0068750a0, 0xc00a18f700)
2020-04-28T23:23:53.360391488Z  /go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/cache.go:47 +0x131
2020-04-28T23:23:53.360413479Z net/http.HandlerFunc.ServeHTTP(0xc00afe0520, 0x46c6020, 0xc0068750a0, 0xc00a18f700)
2020-04-28T23:23:53.360435330Z  /usr/local/go/src/net/http/server.go:2007 +0x44
2020-04-28T23:23:53.360457272Z github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000d98c0, 0x46c6020, 0xc0068750a0, 0xc00a18f300)
2020-04-28T23:23:53.360479432Z  /go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
2020-04-28T23:23:53.360501089Z github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000d92c0, 0x46c6020, 0xc0068750a0, 0xc00a18ed00)
2020-04-28T23:23:53.360543068Z  /go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
2020-04-28T23:23:53.360565822Z github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000d95c0, 0x46c6020, 0xc0068750a0, 0xc00a18e400)
2020-04-28T23:23:53.360588379Z  /go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
2020-04-28T23:23:53.360610366Z github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000d9680, 0x46c6020, 0xc0068750a0, 0xc00a18e100)
2020-04-28T23:23:53.360632096Z  /go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
2020-04-28T23:23:53.360653749Z github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/dashboard.Route.func2(0x46c6020, 0xc0068750a0, 0xc00a18e100)
2020-04-28T23:23:53.360678704Z  /go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/dashboard/ui.go:56 +0xe5
2020-04-28T23:23:53.360700656Z net/http.HandlerFunc.ServeHTTP(0xc00066c790, 0x46c6020, 0xc0068750a0, 0xc00a18e100)
2020-04-28T23:23:53.360825971Z  /usr/local/go/src/net/http/server.go:2007 +0x44
2020-04-28T23:23:53.360850466Z github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00004d200, 0x46c6020, 0xc0068750a0, 0xc005669600)
2020-04-28T23:23:53.360872748Z  /go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
2020-04-28T23:23:53.360894428Z github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/server.wrapHandler.func1(0x46c6020, 0xc0068750a0, 0xc005669600)
2020-04-28T23:23:53.360916330Z  /go/src/github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/server/server.go:187 +0x95
2020-04-28T23:23:53.360938234Z net/http.HandlerFunc.ServeHTTP(0xc004b6b5c0, 0x46c6020, 0xc0068750a0, 0xc005669600)
2020-04-28T23:23:53.360959559Z  /usr/local/go/src/net/http/server.go:2007 +0x44
2020-04-28T23:23:53.360980894Z github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener.HTTPRedirect.func1(0x46c6020, 0xc0068750a0, 0xc005669600)
2020-04-28T23:23:53.361002643Z  /go/src/github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/redirect.go:20 +0x221
2020-04-28T23:23:53.361024286Z net/http.HandlerFunc.ServeHTTP(0xc001de35e0, 0x46c6020, 0xc0068750a0, 0xc005669600)
2020-04-28T23:23:53.361045895Z  /usr/local/go/src/net/http/server.go:2007 +0x44
2020-04-28T23:23:53.361070748Z net/http.serverHandler.ServeHTTP(0xc000e64380, 0x46c6020, 0xc0068750a0, 0xc005669600)
2020-04-28T23:23:53.361092374Z  /usr/local/go/src/net/http/server.go:2802 +0xa4
2020-04-28T23:23:53.361113905Z net/http.(*conn).serve(0xc00340d860, 0x46e8a60, 0xc0056c1d00)
2020-04-28T23:23:53.361134962Z  /usr/local/go/src/net/http/server.go:1890 +0x875
2020-04-28T23:23:53.361156352Z created by net/http.(*Server).Serve
2020-04-28T23:23:53.361177518Z  /usr/local/go/src/net/http/server.go:2927 +0x38e
2020-04-28T23:23:53.361198562Z
```

**Comment by Just-Insane** [comment]
Alternatively, is it possible to unlink the cluster from the template so that it can be manually edited again?

**Comment by superseb** [comment]
Please add exact steps and data used to reproduce in https://github.com/rancher/rancher/issues/26616
