### ISSUE TITLE
Panic on an upgrade from 2.3.2 to master and rancher server keep restarting

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26894]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Bring up 2 clusters - 1.14 and 1.15 clusters - 1 node all roles RKE do cluster in 2.3.2
- Upgrade cluster to master-head

**Actual Result:**
Rancher server keeps restarting
Rancher logs:
```
E0503 01:20:29.930059       7 memcache.go:189] couldn't get current server API group list: Get https://167.99.56.96:6443/api?timeout=30m0s: write tcp 172.17.0.2:443->167.99.56.96:25545: i/o timeout
2020/05/03 01:20:29 [ERROR] ClusterController _all_ recovered from panic "Get https://167.99.56.96:6443/api?timeout=30m0s: write tcp 172.17.0.2:443->167.99.56.96:25545: i/o timeout". (err=<nil>) Call stack:
goroutine 1553 [running]:
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.RecoverFromPanic(0xc0004e7cf8)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:158 +0xb5
panic(0x3883e20, 0xc002cc8ff0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.Must(...)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:171
github.com/rancher/rancher/vendor/github.com/rancher/wrangler-api/pkg/generated/controllers/rbac/v1.NewRoleController(0x3ec9968, 0x19, 0x3e7e292, 0x2, 0x3e7f18c, 0x4, 0x3e80bed, 0x5, 0x46e2880, 0xc000a855e0, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/wrangler-api/pkg/generated/controllers/rbac/v1/role.go:85 +0x1f9
github.com/rancher/rancher/vendor/github.com/rancher/wrangler-api/pkg/generated/controllers/rbac/v1.(*version).Role(0xc00084db40, 0xc002795740, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/wrangler-api/pkg/generated/controllers/rbac/v1/interface.go:56 +0x74
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/accesscontrol.newRoleRevision(0x46e2200, 0xc0008a9980, 0x46e2f40, 0xc00084db40, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/accesscontrol/role_revision_index.go:18 +0x4f
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/accesscontrol.NewAccessStore(0x46e2200, 0xc0008a9980, 0x1, 0x46e2f40, 0xc00084db40, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/accesscontrol/access_store.go:31 +0x4d
github.com/rancher/rancher/pkg/rbac.NewAccessControl(0x46e2200, 0xc0008a9980, 0xc00219c120, 0x7, 0x46e2f40, 0xc00084db40, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/rbac/access_control.go:13 +0x5c
github.com/rancher/rancher/pkg/clustermanager.(*Manager).toRecord(0xc000d56000, 0x46e2200, 0xc0008a9980, 0xc00219e000, 0x0, 0x3df8600, 0xc00219e000)
	/go/src/github.com/rancher/rancher/pkg/clustermanager/manager.go:393 +0x182
github.com/rancher/rancher/pkg/clustermanager.(*Manager).start(0xc000d56000, 0x46e2200, 0xc0008a9980, 0xc00219e000, 0x101, 0xc00219e000, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/clustermanager/manager.go:123 +0x15d
github.com/rancher/rancher/pkg/clustermanager.(*Manager).Start(0xc000d56000, 0x46e2200, 0xc0008a9980, 0xc00219e000, 0x1, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/clustermanager/manager.go:90 +0xc5
github.com/rancher/rancher/pkg/api/controllers/usercontrollers.(*userControllersController).peersSync(0xc0015c05a0, 0xc0003c44f0, 0x203000)
	/go/src/github.com/rancher/rancher/pkg/api/controllers/usercontrollers/usercontroller.go:136 +0x237
github.com/rancher/rancher/pkg/api/controllers/usercontrollers.(*userControllersController).setPeers(0xc0015c05a0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/api/controllers/usercontrollers/usercontroller.go:109 +0x155
github.com/rancher/rancher/pkg/api/controllers/usercontrollers.(*userControllersController).sync(0xc0015c05a0, 0x3e80364, 0x5, 0x0, 0xc00014ca80, 0x7f7abeaa8008, 0x0, 0xc000b4ec18)
	/go/src/github.com/rancher/rancher/pkg/api/controllers/usercontrollers/usercontroller.go:93 +0xfb
github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3.(*clusterController).AddHandler.func1(0x3e80364, 0x5, 0x0, 0x0, 0xc000b4eca0, 0x3, 0x3, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_cluster_controller.go:151 +0xe0
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).syncHandler(0xc0010a4180, 0x33e9480, 0xc0003c44b0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:387 +0x371
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).processNextWorkItem(0xc0010a4180, 0x40c400)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:296 +0xef
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).runWorker(0xc0010a4180)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:284 +0x2b
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0003c4430)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5e
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0003c4430, 0x4651b40, 0xc000fb9b60, 0xc000e37e01, 0xc0012c8960)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0003c4430, 0x3b9aca00, 0x0, 0x1, 0xc0012c8960)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0xe2
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0003c4430, 0x3b9aca00, 0xc0012c8960)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).run
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:276 +0xe8

E0503 01:20:29.931319       7 memcache.go:189] couldn't get current server API group list: Get https://167.99.56.96:6443/api?timeout=30m0s: write tcp 172.17.0.2:443->167.99.56.96:25545: i/o timeout
panic: Get https://167.99.56.96:6443/api?timeout=30m0s: write tcp 172.17.0.2:443->167.99.56.96:25545: i/o timeout

goroutine 430 [running]:
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.Must(...)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:171
github.com/rancher/rancher/vendor/github.com/rancher/wrangler-api/pkg/generated/controllers/rbac/v1.NewRoleController(0x3ec9968, 0x19, 0x3e7e292, 0x2, 0x3e7f18c, 0x4, 0x3e80bed, 0x5, 0x46e2880, 0xc000a569a0, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/wrangler-api/pkg/generated/controllers/rbac/v1/role.go:85 +0x1f9
github.com/rancher/rancher/vendor/github.com/rancher/wrangler-api/pkg/generated/controllers/rbac/v1.(*version).Role(0xc00263c2e0, 0xc0052d76e0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/wrangler-api/pkg/generated/controllers/rbac/v1/interface.go:56 +0x74
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/accesscontrol.newRoleRevision(0x46e2200, 0xc0008a9980, 0x46e2f40, 0xc00263c2e0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/accesscontrol/role_revision_index.go:18 +0x4f
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/accesscontrol.NewAccessStore(0x46e2200, 0xc0008a9980, 0x1, 0x46e2f40, 0xc00263c2e0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/accesscontrol/access_store.go:31 +0x4d
github.com/rancher/rancher/pkg/rbac.NewAccessControl(0x46e2200, 0xc0008a9980, 0xc00219c120, 0x7, 0x46e2f40, 0xc00263c2e0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/rbac/access_control.go:13 +0x5c
github.com/rancher/rancher/pkg/clustermanager.(*Manager).toRecord(0xc000d56000, 0x46e2200, 0xc0008a9980, 0xc00219e000, 0x0, 0x3df8600, 0xc00219e000)
	/go/src/github.com/rancher/rancher/pkg/clustermanager/manager.go:393 +0x182
github.com/rancher/rancher/pkg/clustermanager.(*Manager).start(0xc000d56000, 0x46e2200, 0xc0008a9980, 0xc00219e000, 0x101, 0xc00219e000, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/clustermanager/manager.go:123 +0x15d
github.com/rancher/rancher/pkg/clustermanager.(*Manager).Start(0xc000d56000, 0x46e2200, 0xc0008a9980, 0xc00219e000, 0x1, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/clustermanager/manager.go:90 +0xc5
github.com/rancher/rancher/pkg/api/controllers/usercontrollers.(*userControllersController).peersSync(0xc0015c05a0, 0xc001556c00, 0xc0011a8790)
	/go/src/github.com/rancher/rancher/pkg/api/controllers/usercontrollers/usercontroller.go:136 +0x237
github.com/rancher/rancher/pkg/api/controllers/usercontrollers.(*userControllersController).setPeers(0xc0015c05a0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/api/controllers/usercontrollers/usercontroller.go:109 +0x155
github.com/rancher/rancher/pkg/api/controllers/usercontrollers.Register.func3(0x46e2200, 0xc0008a9980, 0xc0015c05a0)
	/go/src/github.com/rancher/rancher/pkg/api/controllers/usercontrollers/usercontroller.go:66 +0xfe
created by github.com/rancher/rancher/pkg/api/controllers/usercontrollers.Register
	/go/src/github.com/rancher/rancher/pkg/api/controllers/usercontrollers/usercontroller.go:60 +0x2c3
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `9b15c4b14`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke do
- Kubernetes version (use `kubectl version`):

```
1.14 and 1.15 clusters deployed
```

**Comment by sowmyav27** [comment]
**Noticed a similar panic on a freshly installed HA setup on master-head - commit id: `84d937acf`**

```
E0511 19:18:18.383317       6 memcache.go:111] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
2020/05/11 19:18:18 [ERROR] ClusterController _all_ recovered from panic "no matches for kind \"Role\" in version \"rbac.authorization.k8s.io/v1\"". (err=<nil>) Call stack:
goroutine 1758 [running]:
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.RecoverFromPanic(0xc0046e9cf8)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:158 +0xb5
panic(0x3617e00, 0xc003883980)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.Must(...)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:171
github.com/rancher/rancher/vendor/github.com/rancher/wrangler-api/pkg/generated/controllers/rbac/v1.NewRoleController(0x3ec8961, 0x19, 0x3e7d292, 0x2, 0x3e7e18c, 0x4, 0x3e7fbed, 0x5, 0x46e1800, 0xc000124f50, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/wrangler-api/pkg/generated/controllers/rbac/v1/role.go:85 +0x1f9
github.com/rancher/rancher/vendor/github.com/rancher/wrangler-api/pkg/generated/controllers/rbac/v1.(*version).Role(0xc0054d1230, 0xc005877d40, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/wrangler-api/pkg/generated/controllers/rbac/v1/interface.go:56 +0x74
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/accesscontrol.newRoleRevision(0x46e1180, 0xc0006fa640, 0x46e1ec0, 0xc0054d1230, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/accesscontrol/role_revision_index.go:18 +0x4f
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/accesscontrol.NewAccessStore(0x46e1180, 0xc0006fa640, 0x1, 0x46e1ec0, 0xc0054d1230, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/accesscontrol/access_store.go:31 +0x4d
github.com/rancher/rancher/pkg/rbac.NewAccessControl(0x46e1180, 0xc0006fa640, 0xc003ec3990, 0x7, 0x46e1ec0, 0xc0054d1230, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/rbac/access_control.go:13 +0x5c
github.com/rancher/rancher/pkg/clustermanager.(*Manager).toRecord(0xc00185e900, 0x46e1180, 0xc0006fa640, 0xc001103700, 0x0, 0x3df7600, 0xc001103700)
	/go/src/github.com/rancher/rancher/pkg/clustermanager/manager.go:393 +0x182
github.com/rancher/rancher/pkg/clustermanager.(*Manager).start(0xc00185e900, 0x46e1180, 0xc0006fa640, 0xc001103700, 0x1, 0xc001103700, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/clustermanager/manager.go:123 +0x15d
github.com/rancher/rancher/pkg/clustermanager.(*Manager).Start(0xc00185e900, 0x46e1180, 0xc0006fa640, 0xc001103700, 0x0, 0x4, 0x101)
	/go/src/github.com/rancher/rancher/pkg/clustermanager/manager.go:90 +0xc5
github.com/rancher/rancher/pkg/api/controllers/usercontrollers.(*userControllersController).peersSync(0xc0018e8990, 0xc00035e930, 0x40c486)
	/go/src/github.com/rancher/rancher/pkg/api/controllers/usercontrollers/usercontroller.go:136 +0x237
github.com/rancher/rancher/pkg/api/controllers/usercontrollers.(*userControllersController).setPeers(0xc0018e8990, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/api/controllers/usercontrollers/usercontroller.go:109 +0x155
github.com/rancher/rancher/pkg/api/controllers/usercontrollers.(*userControllersController).sync(0xc0018e8990, 0x3e7f364, 0x5, 0x0, 0xc0016cbc00, 0x7fca7fa75008, 0x0, 0xc00704fc18)
	/go/src/github.com/rancher/rancher/pkg/api/controllers/usercontrollers/usercontroller.go:93 +0xfb
github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3.(*clusterController).AddHandler.func1(0x3e7f364, 0x5, 0x0, 0x0, 0xc00704fca0, 0x3, 0x3, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_cluster_controller.go:151 +0xe0
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).syncHandler(0xc000d05d00, 0x33e8480, 0xc0038c4cb0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:387 +0x371
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).processNextWorkItem(0xc000d05d00, 0x40c400)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:296 +0xef
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).runWorker(0xc000d05d00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:284 +0x2b
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0003d63d0)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5e
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0003d63d0, 0x4650b00, 0xc000cab470, 0xc0012fe401, 0xc00009f2c0)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0003d63d0, 0x3b9aca00, 0x0, 0x1, 0xc00009f2c0)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0xe2
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0003d63d0, 0x3b9aca00, 0xc00009f2c0)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).run
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:276 +0xe8
```

**Comment by maggieliu** [comment]
@sowmyav27 can you please retest since there has been a lot of changes since this bug was reported.

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version a1acca856`

Steps:
Run Rancher server v2.3.2
Bring up 2 clusters - 1.14 and 1.15 clusters - 1 node all roles RKE do cluster
Upgrade cluster to master-head

Result:
Rancher server is upgraded and no panic is observed.
