### ISSUE TITLE
[BUG] Can't post to typed index with rancher test button.

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#26994]
**problem**
With elasticsearch the test button is posting to <cluster>/<index>/container_log
For ES6 this is fine, but ES7 and higher types are not allowed anymore.

**suggestion**

- Fluentd ES test button with POST _bulk
- Fluentd ES test button removes the _type containerlog

**support**
ES6: type and id can be mixed
ES7: still allows a single type
ES8: types are going bye bye

**Comment by izaac** [comment]
In Rancher `v2.4.3` I see or can reproduce the `types` deprecation warning:

```
es01    | {"type": "deprecation", "timestamp": "2020-05-29T17:25:35,993Z", "level": "WARN", "component": "o.e.d.r.a.d.RestDeleteAction", "cluster.name": "es-docker-cluster", "node.name": "es01", "message": "[types removal] Specifying types in document index requests is deprecated, use the typeless endpoints instead (/{index}/_doc/{id}, /{index}/_doc, or /{index}/_create/{id}).", "cluster.uuid": "Rx-EdaaKRKK3bUSNkGkpSw", "node.id": "e9G1tdWjSZaMR_x1wjy82A"  }
```

**Comment by izaac** [comment]
The first time I click `Test` the Rancher UI shows that the settings were validated properly.

In the ES 7.7.0 logs I see a different "deprecated" message:

`es01    | {"type": "deprecation", "timestamp": "2020-06-05T22:24:48,744Z", "level": "WARN", "component": "o.e.d.a.b.BulkRequestParser", "cluster.name": "es-docker-cluster", "node.name": "es01", "message": "[types removal] Specifying types in bulk requests is deprecated.", "cluster.uuid": "0Nr9KMwcRgqUuqOAT0wvDQ", "node.id": "XtMNd38TRIaolp-QiE6sBA"  }`

This confirms the new bulk request is sent.

But this is failing the second time I click `Test`:

`couldn't send the request to target http://<elasticsearch_url>:9200/_bulk: Post http://<elasticsearch_url>:9200/_bulk: dial tcp: lookup <elasticsearch_url> on 10.43.0.10:53: server misbehaving`

This wasn't the case previously. 

Also after clicking `Test` I see some errors in the Rancher logs:

```
E0605 22:30:12.838026       6 reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1.ResourceQuota: Get https://<control_plane_ip>:6443/api/v1/resourcequotas?resourceVersion=712&timeout=30s: context deadline exceeded
I0605 22:30:14.574592       6 trace.go:116] Trace[1003281214]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-06-05 22:29:44.574015682 +0000 UTC m=+1123.746334811) (total time: 30.000545154s):
Trace[1003281214]: [30.000545154s] [30.000545154s] END
E0605 22:30:14.574617       6 reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1.Job: Get https://<control_plane_ip>:6443/apis/batch/v1/jobs?resourceVersion=712&timeout=30s: context deadline exceeded
I0605 22:30:16.811210       6 trace.go:116] Trace[118973956]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-06-05 22:29:46.810611916 +0000 UTC m=+1125.982931007) (total time: 30.000566584s):
Trace[118973956]: [30.000566584s] [30.000566584s] END
E0605 22:30:16.811233       6 reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1.NetworkPolicy: Get https://<control_plane_ip>:6443/apis/networking.k8s.io/v1/networkpolicies?resourceVersion=712&timeout=30s: context deadline exceeded
I0605 22:30:35.493930       6 trace.go:116] Trace[2028723006]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-06-05 22:30:05.493343436 +0000 UTC m=+1144.665662553) (total time: 30.00055773s):
Trace[2028723006]: [30.00055773s] [30.00055773s] END
E0605 22:30:35.493955       6 reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1beta1.PodSecurityPolicy: Get https://<control_plane_ip>:6443/apis/policy/v1beta1/podsecuritypolicies?resourceVersion=716&timeout=30s: context deadline exceeded
I0605 22:30:41.065746       6 trace.go:116] Trace[2038934087]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-06-05 22:30:11.065079322 +0000 UTC m=+1150.237398486) (total time: 30.000628192s):
Trace[2038934087]: [30.000628192s] [30.000628192s] END
E0605 22:30:41.065829       6 reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1.StatefulSet: Get https://<control_plane_ip>:6443/apis/apps/v1/statefulsets?resourceVersion=712&timeout=30s: context deadline exceeded
I0605 22:30:46.264959       6 trace.go:116] Trace[410592757]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-06-05 22:30:16.2643517 +0000 UTC m=+1155.436670812) (total time: 30.000576728s):
Trace[410592757]: [30.000576728s] [30.000576728s] END
E0605 22:30:46.264983       6 reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1.LimitRange: Get https://<control_plane_ip>:6443/api/v1/limitranges?resourceVersion=712&timeout=30s: context deadline exceeded
```

**Comment by izaac** [comment]
I am using the docker compose yaml from this guide:

https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

**Comment by izaac** [comment]
Moved back to `To Test` I can't reproduce the issue from my previous comment today, I will investigate a bit further

**Comment by izaac** [comment]
I no longer see issues in Rancher `v2.4.5-rc2` clicking multiple times in the Test button from the Rancher UI. However after saving the configuration and the `rancher-logging-fluentd` pods are provisioned in the System project I see some fluentd/ruby tracebacks the container logs in `Elasticsearch 7.7.1`

```
2020-06-08 19:35:04 +0000 [warn]: #0 failed to flush the buffer. retry_time=5 next_retry_seconds=2020-06-08 19:35:22 +0000 chunk="5a797b14b3e2188e701ab72f0a136dcd" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"izaac6.qa.rancher.space\", :port=>9200, :scheme=>\"http\"}): Connection refused - connect(2) for 45.33.43.81:9200 (Errno::ECONNREFUSED)"
  2020-06-08 19:35:04 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.8.0/lib/fluent/plugin/out_elasticsearch.rb:886:in `rescue in send_bulk'
  2020-06-08 19:35:04 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.8.0/lib/fluent/plugin/out_elasticsearch.rb:848:in `send_bulk'
  2020-06-08 19:35:04 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.8.0/lib/fluent/plugin/out_elasticsearch.rb:710:in `block in write'
  2020-06-08 19:35:04 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.8.0/lib/fluent/plugin/out_elasticsearch.rb:709:in `each'
  2020-06-08 19:35:04 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.8.0/lib/fluent/plugin/out_elasticsearch.rb:709:in `write'
  2020-06-08 19:35:04 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.8.0/lib/fluent/plugin/output.rb:1133:in `try_flush'
  2020-06-08 19:35:04 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.8.0/lib/fluent/plugin/output.rb:1439:in `flush_thread_run'
  2020-06-08 19:35:04 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.8.0/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
  2020-06-08 19:35:04 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.8.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-06-08 19:35:22 +0000 [warn]: #0 retry succeeded. chunk_id="5a797b14b3e2188e701ab72f0a136dcd"
```

This is working fine without errors pointing the same Rancher `v2.4.5-rc2` to an `Elasticsearch 6.7.1`.

Not sure if this is related to the bulk request we're sending now to the ES or if it's a new issue that has to be tracked separately @paynejacob please confirm.

**Comment by izaac** [comment]
OK I validated  Rancher `v2.4.5-rc2` is sending the logs correctly to `ES 7.7.1` and `ES 6.7.1`

I recreated the Rancher install and after enabling ES cluster logging. In both Cluster and Project levels.

Sample query result using ElasticsearchHQ UI:

![Screen Shot 2020-06-09 at 10 26 40 AM](https://user-images.githubusercontent.com/27659/84180319-2d1f3100-aa3c-11ea-8ed9-0655fb1c8b82.png)

**Comment by izaac** [comment]
Reopening https://github.com/rancher/rancher/issues/26994#issuecomment-640926431
