### ISSUE TITLE
500 error while switching to 'Load Banalcing' page in a project

### ISSUE THREAD

**Issue by guoyk93** [rancher/rancher#27009]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

Only one of my projects has this issue, just switch to 'load balancing' page, and web ui reports 500 error, ask me to back or logout

**Result:**

it seems the api `/v3/project/xxxxxx/ingresses` crashed at this line

https://github.com/rancher/rancher/blob/master/pkg/api/store/ingress/store.go#L92

web ui reports 500 error, and found this in rancher log:

```
2020/05/09 03:50:12 [ERROR] Panic serving api request: 
goroutine 110533 [running]:
runtime/debug.Stack(0xc010d166b8, 0x3b6c240, 0xc00c89afc0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP.func1(0x46cb080, 0xc026962fa0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:175 +0x7a
panic(0x3b6c240, 0xc00c89afc0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/rancher/pkg/api/store/ingress.updateDataRules(0xc026a29530)
	/go/src/github.com/rancher/rancher/pkg/api/store/ingress/store.go:92 +0x693
github.com/rancher/rancher/pkg/api/store/ingress.formatData(0xc01d775e80, 0xb, 0xc026a29530, 0x1)
	/go/src/github.com/rancher/rancher/pkg/api/store/ingress/store.go:67 +0x2d1
github.com/rancher/rancher/pkg/api/store/ingress.New.func1(0xc01597c240, 0xc0016c3860, 0xc026a29530, 0xc01913b300, 0x2, 0xc025fa8700, 0x1)
	/go/src/github.com/rancher/rancher/pkg/api/store/ingress/store.go:246 +0x8c
github.com/rancher/rancher/vendor/github.com/rancher/norman/store/transform.(*Store).List(0xc000ffc930, 0xc01597c240, 0xc0016c3860, 0xc01913b300, 0xc01913b300, 0x0, 0x0, 0xc0253ace40, 0x3593b80)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/transform/transform.go:82 +0x149
github.com/rancher/rancher/pkg/api/store/projectsetter.projectSetter.List(0x470cfa0, 0xc000ffc930, 0xc00131d0e0, 0xc01597c240, 0xc0016c3860, 0xc01913b280, 0x8, 0x8, 0xc0122e1a88, 0xc0122e1a80, ...)
	/go/src/github.com/rancher/rancher/pkg/api/store/projectsetter/store.go:46 +0x119
github.com/rancher/rancher/vendor/github.com/rancher/norman/store/transform.(*Store).List(0xc000ffda10, 0xc01597c240, 0xc0016c3860, 0xc01913b280, 0xc0122e1a80, 0x1, 0x1, 0x1, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/transform/transform.go:67 +0x6f
github.com/rancher/rancher/vendor/github.com/rancher/norman/store/wrapper.(*StoreWrapper).List(0xc000343300, 0xc01597c240, 0xc0016c3860, 0xc01913b280, 0x3e6a0a2, 0x3, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/wrapper/wrapper.go:40 +0x148
github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler.ListHandler(0xc01597c240, 0x3ff5950, 0xc0016c3860, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler/list.go:26 +0x287
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).handle(0xc0007b46e0, 0x46cb080, 0xc026962fa0, 0xc016851700, 0xc010d16ec8, 0x9dfec9cb, 0x2fe826b57436ed86)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:249 +0x2a2
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP(0xc0007b46e0, 0x46cb080, 0xc026962fa0, 0xc016851700)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:180 +0x99
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentTypeOptions.func1(0x46cb080, 0xc026962fa0, 0xc016851700)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/cache.go:47 +0x131
net/http.HandlerFunc.ServeHTTP(0xc01ebc3bc0, 0x46cb080, 0xc026962fa0, 0xc016851700)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001f5080, 0x46cb080, 0xc026962fa0, 0xc016851500)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/pkg/auth/requests.authHeaderHandler.ServeHTTP(0x4691480, 0xc0004e3d40, 0x4654200, 0xc0001f5080, 0x4691440, 0xc001307200, 0x46cb080, 0xc026962fa0, 0xc016851500)
	/go/src/github.com/rancher/rancher/pkg/auth/requests/filter.go:62 +0x4eb
github.com/rancher/rancher/pkg/rbac.NewAccessControlHandler.func1(0x46cb080, 0xc026962fa0, 0xc016851400, 0x4653340, 0xc000cba420)
	/go/src/github.com/rancher/rancher/pkg/rbac/user_based.go:32 +0x194
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/auth.Middleware.Wrap.func1(0x46cb080, 0xc026962fa0, 0xc016851400)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/auth/filter.go:36 +0x55
net/http.HandlerFunc.ServeHTTP(0xc000718180, 0x46cb080, 0xc026962fa0, 0xc016851400)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/pkg/websocket.websocketHandler.ServeHTTP(0x465b1c0, 0xc000718180, 0x46cb080, 0xc026962fa0, 0xc016851400)
	/go/src/github.com/rancher/rancher/pkg/websocket/handler.go:35 +0xa0
github.com/rancher/rancher/pkg/audit.auditHandler.ServeHTTP(0x4653580, 0xc0007d1780, 0x0, 0x46cb080, 0xc026962fa0, 0xc016851400)
	/go/src/github.com/rancher/rancher/pkg/audit/filter.go:31 +0x623
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentType.func1(0x46b9400, 0xc0253ac9c0, 0xc016851400)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/content.go:33 +0x93
net/http.HandlerFunc.ServeHTTP(0xc000734940, 0x46b9400, 0xc0253ac9c0, 0xc016851400)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.Gzip.func1(0x46c9e00, 0xc0122e1a78, 0xc016851400)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/gzip.go:60 +0x1f5
net/http.HandlerFunc.ServeHTTP(0xc000734980, 0x46c9e00, 0xc0122e1a78, 0xc016851400)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentTypeOptions.func1(0x46c9e00, 0xc0122e1a78, 0xc016851400)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/cache.go:47 +0x131
net/http.HandlerFunc.ServeHTTP(0xc01ebc3b20, 0x46c9e00, 0xc0122e1a78, 0xc016851400)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001f4fc0, 0x46c9e00, 0xc0122e1a78, 0xc016851200)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc002d11a40, 0x46c9e00, 0xc0122e1a78, 0xc016851000)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc002d11b00, 0x46c9e00, 0xc0122e1a78, 0xc016850e00)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/dashboard.Route.func2(0x46c9e00, 0xc0122e1a78, 0xc016850e00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/dashboard/ui.go:56 +0xe5
net/http.HandlerFunc.ServeHTTP(0xc00355d430, 0x46c9e00, 0xc0122e1a78, 0xc016850e00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc002cf4600, 0x46c9e00, 0xc0122e1a78, 0xc016850c00)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/golang.org/x/crypto/acme/autocert.(*Manager).HTTPHandler.func1(0x46c9e00, 0xc0122e1a78, 0xc016850c00)
	/go/src/github.com/rancher/rancher/vendor/golang.org/x/crypto/acme/autocert/autocert.go:393 +0x2f9
net/http.HandlerFunc.ServeHTTP(0xc00e2f8ce0, 0x46c9e00, 0xc0122e1a78, 0xc016850c00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener.HTTPRedirect.func1(0x46c9e00, 0xc0122e1a78, 0xc016850c00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/redirect.go:20 +0x221
net/http.HandlerFunc.ServeHTTP(0xc00e2f8d00, 0x46c9e00, 0xc0122e1a78, 0xc016850c00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.serverHandler.ServeHTTP(0xc00b150460, 0x46c9e00, 0xc0122e1a78, 0xc016850c00)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.initNPNRequest.ServeHTTP(0x46ec9c0, 0xc02019a9f0, 0xc0184ff500, 0xc00b150460, 0x46c9e00, 0xc0122e1a78, 0xc016850c00)
	/usr/local/go/src/net/http/server.go:3365 +0x8d
net/http.(*http2serverConn).runHandler(0xc01b7a2d80, 0xc0122e1a78, 0xc016850c00, 0xc01ebc3aa0)
	/usr/local/go/src/net/http/h2_bundle.go:5713 +0x9f
created by net/http.(*http2serverConn).processHeaders
	/usr/local/go/src/net/http/h2_bundle.go:5447 +0x4eb
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 

Rancher | v2.4.3
-- | --
User Interface | v2.4.22

- Installation option (single install/HA): 

single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
custom cluster
cloud vps
kubernetes v1.17.5
```

- Docker version (use `docker version`):

```
19.3.5, 19.3.8 mixed
```

**Comment by guoyk93** [comment]
@sangeethah is there any quick fix for this issue, under some circumstances this will crash the whole rancher, and rolling back to 2.4.2 seems no help

**Comment by guoyk93** [comment]
I've made a quick and dirty fix address to this issue, https://github.com/guoyk93/rancher/commit/e194f4e903ed7ab634641b9811e83c026c4757a5, recompiled rancher, and everything seems fine.
