### ISSUE TITLE
Containers sometimes stuck in Networking state when scaling up

### ISSUE THREAD

**Issue by andyshinn** [rancher/rancher#2700]
I was having an issue with the same symptoms as #2571. But it appears to be a different issue (my networks don't appear to overlap, local is 10.20.0.0/16). Containers that get scheduled on a certain host don't startup and are stuck in "Networking" state in UI.

Logs from the `rancher-agent` container (removing the nsenter lines since there are tons of them):

```
time="2015-11-16T23:51:23Z" level="error" msg="Couldn't find container for id." error="No such container: 43887083-5910-4cb4-bc6b-9a8e8c512b44" id="43887083-5910-4cb4-bc6b-9a8e8c512b44" 
time="2015-11-16T23:51:23Z" level="error" msg="Error getting machine info." error="unable to get \"machine info\" from \"http://127.0.0.1:9344/api/v1.3/machine\": Get http://127.0.0.1:9344/api/v1.3/machine: dial tcp 127.0.0.1:9344: connection refused" 
time="2015-11-16T23:51:31Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"16d2e56df5ab92b73d0f625551c87e0c418e182f55b47cc31d8f92ba30b6c495\", From:\"docker-reg-stg:8443/lims-taskscheduler:2.24.173\", Time:1447717891}" 
time="2015-11-16T23:51:31Z" level="info" msg="Assigning IP [10.42.194.221/16], ContainerId [16d2e56df5ab92b73d0f625551c87e0c418e182f55b47cc31d8f92ba30b6c495], Pid [21450]" 
time="2015-11-16T23:51:31Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"16d2e56df5ab92b73d0f625551c87e0c418e182f55b47cc31d8f92ba30b6c495\", From:\"-simulated-\", Time:0}" 
time="2015-11-16T23:51:31Z" level="info" msg="Container locked. Can't run StartHandler. ID: [16d2e56df5ab92b73d0f625551c87e0c418e182f55b47cc31d8f92ba30b6c495]" 
time="2015-11-16T23:51:42Z" level="error" msg="Couldn't find container for id." error="No such container: 43887083-5910-4cb4-bc6b-9a8e8c512b44" id="43887083-5910-4cb4-bc6b-9a8e8c512b44" 
time="2015-11-16T23:51:42Z" level="error" msg="Error getting machine info." error="unable to get \"machine info\" from \"http://127.0.0.1:9344/api/v1.3/machine\": Get http://127.0.0.1:9344/api/v1.3/machine: dial tcp 127.0.0.1:9344: connection refused"
```

Lines from the networking container (agent-instance image):

```
INFO: ROOT -> ./etc/
INFO: ROOT -> ./etc/monit/
INFO: ROOT -> ./etc/monit/conf.d/
INFO: ROOT -> ./etc/monit/conf.d/rancher-dns
INFO: ROOT -> ./etc/init.d/
INFO: ROOT -> ./etc/init.d/rancher-dns
 * rancher-dns is running
 * Stopping rancher-dns configuration rancher-dns
   ...done.
 * Starting rancher-dns configuration rancher-dns
   ...done.
INFO: Sending rancher-dns applied 1-f7a323a556662cba4edbce4b10c3e41fa93247776a7e1f7f963805cf33ce85a4
INFO: Getting host-api
INFO: Updating host-api
INFO: Downloading https://rancher.natera.com/v1//configcontent//host-api current=
INFO: Running /var/lib/cattle/download/host-api/1-cbed785205aa661fd5fff3598faf04649a9a4743bae83643aacdc9e7b3d5289c/apply.sh
INFO: Sending host-api applied 1-cbed785205aa661fd5fff3598faf04649a9a4743bae83643aacdc9e7b3d5289c
INFO: HOME -> ./
INFO: HOME -> ./etc/
INFO: HOME -> ./etc/cattle/
INFO: HOME -> ./etc/cattle/startup-env
INFO: ROOT -> ./
INFO: ROOT -> ./etc/
INFO: ROOT -> ./etc/init.d/
INFO: ROOT -> ./etc/init.d/agent-instance-startup
INFO: Sending agent-instance-startup applied 4-2a88131eee029195e9789b6fe511e1fc9e5c5a540bffa62624a64eba08697665
Starting monit daemon with http interface at [localhost:2812]
```

Logs from `rancher-server` container (with nsenter stuff filtered out):

```
2015-11-16 23:50:29,973 ERROR [:] [] [] [] [ecutorService-6] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [1] count [1] 
2015-11-16 23:50:32,839 ERROR [:] [] [] [] [ecutorService-1] [.p.c.v.i.ConfigItemStatusManagerImpl] Error updating item(s) [ipsec-hosts, hosts, iptables, healthcheck] on [agent:3] io.cattle.platform.eventing.exception.EventExecutionException: d22b566f-25b9-480d-be90-e22b8aa6cdf7 : ('Connection aborted.', error(111, 'ECONNREFUSED'))
	at io.cattle.platform.eventing.exception.EventExecutionException.fromEvent(EventExecutionException.java:53) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.impl.FutureEventListener.onEvent(FutureEventListener.java:47) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_85]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_85]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_85]

2015-11-16 23:50:32,840 ERROR [:] [] [] [] [ecutorService-1] [.p.c.v.i.ConfigItemStatusManagerImpl] Error updating item(s) [ipsec-hosts, hosts, iptables, healthcheck] on [agent:3] io.cattle.platform.eventing.exception.EventExecutionException: d22b566f-25b9-480d-be90-e22b8aa6cdf7 : ('Connection aborted.', error(111, 'ECONNREFUSED'))
	at io.cattle.platform.eventing.exception.EventExecutionException.fromEvent(EventExecutionException.java:53) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.impl.FutureEventListener.onEvent(FutureEventListener.java:47) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_85]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_85]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_85]

2015-11-16 23:50:32,841 ERROR [:] [] [] [] [ecutorService-1] [.p.c.v.i.ConfigItemStatusManagerImpl] Error updating item(s) [ipsec-hosts, hosts, iptables, healthcheck] on [agent:3] io.cattle.platform.eventing.exception.EventExecutionException: d22b566f-25b9-480d-be90-e22b8aa6cdf7 : ('Connection aborted.', error(111, 'ECONNREFUSED'))
	at io.cattle.platform.eventing.exception.EventExecutionException.fromEvent(EventExecutionException.java:53) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.impl.FutureEventListener.onEvent(FutureEventListener.java:47) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_85]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_85]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_85]

2015-11-16 23:50:32,841 ERROR [f81364bc-1128-48e8-9b3b-1dae91bfceed:166] [instance:14->nic:14] [instance.start->(InstanceStart)->nic.activate] [] [ecutorService-9] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.eventing.exception.EventExecutionException: d22b566f-25b9-480d-be90-e22b8aa6cdf7 : ('Connection aborted.', error(111, 'ECONNREFUSED'))
	at io.cattle.platform.eventing.exception.EventExecutionException.fromEvent(EventExecutionException.java:53) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.impl.FutureEventListener.onEvent(FutureEventListener.java:47) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_85]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_85]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_85]

2015-11-16 23:50:32,842 ERROR [f81364bc-1128-48e8-9b3b-1dae91bfceed:166] [instance:14] [instance.start->(InstanceStart)] [] [ecutorService-9] [i.c.p.process.instance.InstanceStart] Failed to Networking for instance [14] 
2015-11-16 23:50:34,972 ERROR [:] [] [] [] [ecutorService-3] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [1] count [2] 
time="2015-11-16T23:50:41Z" level=info msg="Registering backend for host [0a86608c-a4cd-4fca-8665-59d70447bbdd]" 
2015-11-16 23:50:45,811 ERROR [:] [] [] [] [ecutorService-8] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [1] count [1] 
time="2015-11-16T23:53:08Z" level=error msg="Error parsing token." error="token is expired" 
time="2015-11-16T23:54:08Z" level=error msg="Error parsing token." error="token is expired" 
```

Any ideas what might be going on here?

Rancher 0.44.0 installed on Ubuntu 14.04. Agent on Ubuntu 12.04. both Docker 1.9.0.

**Comment by andyshinn** [comment]
I'm noticing that if I restart the Docker daemon on that agent (restarting the agent and networking agent), the the containers waiting on that host do come up (along with the others that were running). But then newly scheduled ones don't seem to work after that (by me just scaling a test stack of ubuntu containers).

**Comment by deniseschannon** [comment]
Is this still the server and host setup that you had migrated over from another box? Or is this a new install?

When the containers are in "Networking" state, have you tried to SSH into the host to make sure Docker isn't hung? By doing a basic `docker ps` would let you know if docker is still working. 

Have you tried using the network agent to ping containers on other hosts to make sure cross host communication is still in tact?

**Comment by andyshinn** [comment]
It is the same machine. But I wiped `/var/lib/rancher` and the MySQL database and started over. Is there anything else that was persistent?

The logs are from the agent host in question. The host isn't hung up and Docker seems to be working fine (I can manually launch containers just fine).

I just tried grabbing a shell on the network agent and host to host communication seems to work. Here are pings to a container and the network agent on another host:

```console
$ sudo docker exec -it 005 bash
root@0056c75aa45e:/var/lib/docker/aufs/mnt/0056c75aa45e1ae8def47e81ccc33105212bcc4789e5d39f034e15d732e34c37# ping 10.42.17.246
PING 10.42.17.246 (10.42.17.246) 56(84) bytes of data.
64 bytes from 10.42.17.246: icmp_req=5 ttl=63 time=0.646 ms
64 bytes from 10.42.17.246: icmp_req=6 ttl=63 time=0.438 ms
64 bytes from 10.42.17.246: icmp_req=7 ttl=63 time=0.478 ms
64 bytes from 10.42.17.246: icmp_req=8 ttl=63 time=0.458 ms
64 bytes from 10.42.17.246: icmp_req=9 ttl=63 time=0.406 ms
64 bytes from 10.42.17.246: icmp_req=10 ttl=63 time=0.439 ms
64 bytes from 10.42.17.246: icmp_req=11 ttl=63 time=0.485 ms
^C
--- 10.42.17.246 ping statistics ---
11 packets transmitted, 7 received, 36% packet loss, time 10022ms
rtt min/avg/max/mdev = 0.406/0.478/0.646/0.076 ms
root@0056c75aa45e:/var/lib/docker/aufs/mnt/0056c75aa45e1ae8def47e81ccc33105212bcc4789e5d39f034e15d732e34c37# ping 10.42.102.93
PING 10.42.102.93 (10.42.102.93) 56(84) bytes of data.
64 bytes from 10.42.102.93: icmp_req=1 ttl=64 time=0.401 ms
64 bytes from 10.42.102.93: icmp_req=2 ttl=64 time=0.391 ms
64 bytes from 10.42.102.93: icmp_req=3 ttl=64 time=0.426 ms
64 bytes from 10.42.102.93: icmp_req=4 ttl=64 time=0.449 ms
^C
--- 10.42.102.93 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 2997ms
rtt min/avg/max/mdev = 0.391/0.416/0.449/0.033 ms
```

The first couple packets didn't get through, not sure if that means anything...

**Comment by deniseschannon** [comment]
The delay before the ping is successful is a known issue. The next time you do it, it will be immediate. 

I don't believe there is anything else persistent. It seems like there is some kind of networking/connection issue based on the logs.

Have you looked through the troubleshooting docs to see if anything pertains to you? Specifically, are your IP tables set up okay? 
http://docs.rancher.com/rancher/faqs/troubleshooting/

I can't see anything specific that jumps out.

**Comment by andyshinn** [comment]
They look good. The IP for the pre-routing rules matches the `agent-instance` container. I compared the rules to another working agent and they line up exact (except for the IPs).

The only thing I notice is that this host is Ubuntu 12.04 where the other working ones are 14.04. I'll add some more 12.04 hosts and see if they exhibit the same behavior.

If it is just a one-off broken host that I can't reproduce then I'll close. But i really want to try Rancher out for some services and would hate to run into a show-stopping bug like this after setting everything up :(

**Comment by andyshinn** [comment]
I solved this and wanted to share in case someone else runs into it. I don't know the exact cause. But this particular host was running kernel 3.2.x. I upgraded to kernel 3.13.0 (`sudo apt-get install linux-image-3.13.0-68-generic`) and it is working now as intended.
