### ISSUE TITLE
[2.4.3] Nil pointer on some helm 2 charts

### ISSUE THREAD

**Issue by Lebvanih** [rancher/rancher#27022]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Using the consul-helm chart after the upgrade to Rancher 2.4.3 we seems to be affected by the following issue that exist in Helm version 2.16.4 to 2.16.5 (https://github.com/helm/helm/issues/7812). The chart will trigger the exact same error if ACLs are enabled.
```
[storage] 2020/05/11 10:08:59 updating release "consul.v1"
NAME:   consul
[storage] 2020/05/11 10:08:59 getting last revision of "consul"
[storage] 2020/05/11 10:08:59 getting release history for "consul"
[kube] 2020/05/11 10:08:59 Doing get for PodDisruptionBudget: "consul-server"
[kube] 2020/05/11 10:08:59 Doing get for ConfigMap: "consul-server-config"
[kube] 2020/05/11 10:08:59 Doing get for ServiceAccount: "consul-server"
[kube] 2020/05/11 10:08:59 Doing get for ServiceAccount: "consul-server-acl-init-cleanup"
[kube] 2020/05/11 10:08:59 Doing get for ServiceAccount: "consul-server-acl-init"
[kube] 2020/05/11 10:08:59 Doing get for ClusterRole: "consul-server-acl-init-cleanup"
[kube] 2020/05/11 10:08:59 Doing get for ClusterRole: "consul-server"
[kube] 2020/05/11 10:08:59 Doing get for ClusterRole: "consul-server-acl-init"
[kube] 2020/05/11 10:09:00 Doing get for ClusterRoleBinding: "consul-server"
[kube] 2020/05/11 10:09:00 Doing get for ClusterRoleBinding: "consul-server-acl-init-cleanup"
[kube] 2020/05/11 10:09:00 Doing get for ClusterRoleBinding: "consul-server-acl-init"
[kube] 2020/05/11 10:09:00 Doing get for Service: "consul-ui"
[kube] 2020/05/11 10:09:00 Doing get for Service: "consul-server"
[kube] 2020/05/11 10:09:00 Doing get for StatefulSet: "consul-server"
[kube] 2020/05/11 10:09:00 Doing get for Job: "consul-server-acl-init"
[kube] 2020/05/11 10:09:00 WARNING: Failed Get for resource "consul-server-acl-init": jobs.batch "consul-server-acl-init" not found
[kube] 2020/05/11 10:09:00 get relation pod of object: testing-ff/PodDisruptionBudget/consul-server
[kube] 2020/05/11 10:09:00 get relation pod of object: testing-ff/ConfigMap/consul-server-config
[kube] 2020/05/11 10:09:00 get relation pod of object: testing-ff/ServiceAccount/consul-server
[kube] 2020/05/11 10:09:00 get relation pod of object: testing-ff/ServiceAccount/consul-server-acl-init-cleanup
[kube] 2020/05/11 10:09:00 get relation pod of object: testing-ff/ServiceAccount/consul-server-acl-init
[kube] 2020/05/11 10:09:00 get relation pod of object: /ClusterRole/consul-server
[kube] 2020/05/11 10:09:00 get relation pod of object: /ClusterRole/consul-server-acl-init-cleanup
[kube] 2020/05/11 10:09:00 get relation pod of object: /ClusterRole/consul-server-acl-init
[kube] 2020/05/11 10:09:00 get relation pod of object: /ClusterRoleBinding/consul-server
[kube] 2020/05/11 10:09:00 get relation pod of object: /ClusterRoleBinding/consul-server-acl-init-cleanup
[kube] 2020/05/11 10:09:00 get relation pod of object: /ClusterRoleBinding/consul-server-acl-init
[kube] 2020/05/11 10:09:00 get relation pod of object: testing-ff/Service/consul-ui
[kube] 2020/05/11 10:09:00 get relation pod of object: testing-ff/Service/consul-server
[kube] 2020/05/11 10:09:00 get relation pod of object: testing-ff/StatefulSet/consul-server
[kube] 2020/05/11 10:09:00 get relation pod of object: testing-ff/Job/consul-server-acl-init
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x154df7e]
goroutine 949 [running]:
k8s.io/helm/pkg/kube.getSelectorFromObject(0x1c904c0, 0xc000c28480, 0xc000c28480, 0x0)
	/go/src/k8s.io/helm/pkg/kube/client.go:1018 +0x2fe
k8s.io/helm/pkg/kube.(*Client).getSelectRelationPod(0xc00053c520, 0xc00018bc00, 0xc00073f020, 0xc00072ece0, 0x11, 0xc000a0c180)
	/go/src/k8s.io/helm/pkg/kube/client.go:1191 +0x195
k8s.io/helm/pkg/kube.(*Client).Get.func2(0xc00018bc00, 0x0, 0x0)
	/go/src/k8s.io/helm/pkg/kube/client.go:430 +0xa5
k8s.io/helm/pkg/kube.batchPerform.func1(0xc0009667e0, 0xc0007a5d70, 0xc000a9a8a4, 0xc00018bc00)
	/go/src/k8s.io/helm/pkg/kube/client.go:816 +0x30
created by k8s.io/helm/pkg/kube.batchPerform
	/go/src/k8s.io/helm/pkg/kube/client.go:815 +0xb8
2020/05/11 10:09:00 [ERROR] AppController p-ngr69/consul [helm-controller] failed with : failed to install app consul. Error: transport is closing
```

**Other details that may be helpful:**
In our case it seems that as the cleanup-job remove one intermediate job, this generate the nil pointer, however, the chart were not changed on our side and it only triggered when we upgraded Rancher and got the 2.16.5-rancher1 version of Tiller from it.

Would it be possible to upgrade the version of Helm 2 to 2.16.6+ in order to have the fix for this nil pointer?

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.3
- Installation option (single install/HA): HA

**Comment by rancher-max** [comment]
@sangeethah @brendarearden @maggieliu I am unable to reproduce this. Looking at the linked helm issue, they were also having a hard time reproducing. I believe that we should bump our helm version though as it appears to fix the issue based on comments there.

**Comment by ChrML** [comment]
Same issue here! Occurs when upgrading Helm 2.x apps after upgrading from Rancher 2.3.6 to 2.4.3. Was not a problem before.

**Comment by ayoubeddafali** [comment]
I think it is related to the following issue : https://github.com/helm/helm/issues/7812
A fix was applied on version ( Changelog )  2.16.7 https://github.com/helm/helm/releases/tag/v2.16.7 
+ commit : https://github.com/helm/helm/commit/88e95b0d7c62ad91e2c910251797e80c4a1cd014

**Comment by ChrML** [comment]
@ayoubeddafali Can we bump up Helm to 2.16.7 for Rancher 2.4.4?

**Comment by ayoubeddafali** [comment]
Yes, please. 
At least to be able to validate the fix.

**Comment by zbialik** [comment]
Same for me! Most of my helm charts work, its just one that doesn't. I changed the helm repo to v3, and that fixed it. But for one of my envs, I can't sync the helm repo as v3 (which is another issue)... 

But I shouldn't have to upgrade the repo to get that one helm chart working. It was working in rancher v2.3.2 --> no longer working in helm v2.4.3.

**Comment by zbialik** [comment]
Why was this not a problem in v2.3.2? Was helm downgraded in v2.4.3?

**Comment by ayoubeddafali** [comment]
Right, it's because of the v2.16.5. 
By setting the env variable, you meant building a custom image, right ?

**Comment by zbialik** [comment]
@ayoubeddafali right, I am trying to build a custom image... having some issues with the exact make command to use but shouldn't be too difficult to figure out
