### ISSUE TITLE
Pipeline fails for BitBucket Cloud branch created by an unmatched Atlassian account

### ISSUE THREAD

**Issue by jackwakefield** [rancher/rancher#27033]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Configure pipelines with a BitBucket repository containing a branch which was created by an email address which doesn't match a registered Atlassian account, and run the pipeline for that branch.

**Result:**
A broken error message is displayed in the browser (with nonsensical characters).

The API request responds with a 500 error containing the body:
`H4sIAAAAAAAA/wEAAP//AAAAAAAAAAA=`

The `rancher/rancher` panics with

```
2020/05/11 22:13:06 [ERROR] Panic serving api request: 
goroutine 50435 [running]:
runtime/debug.Stack(0xc008ad88f0, 0x3686a80, 0x6c38100)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP.func1(0x46cb080, 0xc019bec070)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:175 +0x7a
panic(0x3686a80, 0x6c38100)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/rancher/pkg/pipeline/remote/bitbucketcloud.(*client).GetHeadInfo(0xc008f29c50, 0xc013f6c840, 0x3d, 0xc009f37ad0, 0x6, 0xc013c032c0, 0x94, 0x0, 0x0, 0x471d0e0)
	/go/src/github.com/rancher/rancher/pkg/pipeline/remote/bitbucketcloud/client.go:302 +0x369
github.com/rancher/rancher/pkg/api/customization/pipeline.(*Handler).getBuildInfoByBranch(0xc000bdc040, 0xc012ec0960, 0xc009f37ad0, 0x6, 0xc012ec0960, 0xc009f37ad0, 0x6)
	/go/src/github.com/rancher/rancher/pkg/api/customization/pipeline/pipeline.go:239 +0x129
github.com/rancher/rancher/pkg/api/customization/pipeline.(*Handler).run(0xc000bdc040, 0xc00dec3200, 0xc019b89301, 0xc0010f2d20)
	/go/src/github.com/rancher/rancher/pkg/api/customization/pipeline/pipeline.go:117 +0x336
github.com/rancher/rancher/pkg/api/customization/pipeline.(*Handler).ActionHandler(0xc000bdc040, 0xc007d75a32, 0x3, 0xc00de82da0, 0xc00dec3200, 0xc0010f2d20, 0xc019b89050)
	/go/src/github.com/rancher/rancher/pkg/api/customization/pipeline/pipeline.go:75 +0x330
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.handleAction(0xc00de82da0, 0xc00dec3200, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:263 +0x62
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).handle(0xc0003fab00, 0x46cb080, 0xc019bec070, 0xc0101ba500, 0xc008ad8e38, 0x12ee3bb5, 0x76c9ba98656764c5)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:251 +0xd2
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP(0xc0003fab00, 0x46cb080, 0xc019bec070, 0xc0101ba500)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:180 +0x99
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentTypeOptions.func1(0x46cb080, 0xc019bec070, 0xc0101ba500)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/cache.go:47 +0x131
net/http.HandlerFunc.ServeHTTP(0xc00de82d40, 0x46cb080, 0xc019bec070, 0xc0101ba500)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000a48180, 0x46cb080, 0xc019bec070, 0xc0101ba300)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/pkg/auth/requests.authHeaderHandler.ServeHTTP(0x4691480, 0xc000566860, 0x4654200, 0xc000a48180, 0x4691440, 0xc00163a480, 0x46cb080, 0xc019bec070, 0xc0101ba300)
	/go/src/github.com/rancher/rancher/pkg/auth/requests/filter.go:62 +0x4eb
github.com/rancher/rancher/pkg/rbac.NewAccessControlHandler.func1(0x46cb080, 0xc019bec070, 0xc0101ba200, 0x4653340, 0xc0010221b0)
	/go/src/github.com/rancher/rancher/pkg/rbac/user_based.go:32 +0x194
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/auth.Middleware.Wrap.func1(0x46cb080, 0xc019bec070, 0xc0101ba200)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/auth/filter.go:36 +0x55
net/http.HandlerFunc.ServeHTTP(0xc000566b20, 0x46cb080, 0xc019bec070, 0xc0101ba200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/pkg/websocket.websocketHandler.ServeHTTP(0x465b1c0, 0xc000566b20, 0x46cb080, 0xc019bec070, 0xc0101ba200)
	/go/src/github.com/rancher/rancher/pkg/websocket/handler.go:35 +0xa0
github.com/rancher/rancher/pkg/audit.auditHandler.ServeHTTP(0x4653580, 0xc00074cc40, 0x0, 0x46cb080, 0xc019bec070, 0xc0101ba200)
	/go/src/github.com/rancher/rancher/pkg/audit/filter.go:31 +0x623
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentType.func1(0x46b9400, 0xc019b889f0, 0xc0101ba200)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/content.go:33 +0x93
net/http.HandlerFunc.ServeHTTP(0xc0007ac3c0, 0x46b9400, 0xc019b889f0, 0xc0101ba200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.Gzip.func1(0x46c9f00, 0xc01c16d960, 0xc0101ba200)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/gzip.go:60 +0x1f5
net/http.HandlerFunc.ServeHTTP(0xc0007ac3e0, 0x46c9f00, 0xc01c16d960, 0xc0101ba200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentTypeOptions.func1(0x46c9f00, 0xc01c16d960, 0xc0101ba200)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/cache.go:47 +0x131
net/http.HandlerFunc.ServeHTTP(0xc00de82c40, 0x46c9f00, 0xc01c16d960, 0xc0101ba200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000a480c0, 0x46c9f00, 0xc01c16d960, 0xc0101ba000)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0049fc840, 0x46c9f00, 0xc01c16d960, 0xc00ecfbe00)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0049fc900, 0x46c9f00, 0xc01c16d960, 0xc00ecfbc00)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/dashboard.Route.func2(0x46c9f00, 0xc01c16d960, 0xc00ecfbc00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/dashboard/ui.go:56 +0xe5
net/http.HandlerFunc.ServeHTTP(0xc004e90610, 0x46c9f00, 0xc01c16d960, 0xc00ecfbc00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00156c000, 0x46c9f00, 0xc01c16d960, 0xc00ed6fa00)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/server.wrapHandler.func1(0x46c9f00, 0xc01c16d960, 0xc00ed6fa00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/server/server.go:187 +0x95
net/http.HandlerFunc.ServeHTTP(0xc0084e2f60, 0x46c9f00, 0xc01c16d960, 0xc00ed6fa00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener.HTTPRedirect.func1(0x46c9f00, 0xc01c16d960, 0xc00ed6fa00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/redirect.go:20 +0x221
net/http.HandlerFunc.ServeHTTP(0xc0013b5600, 0x46c9f00, 0xc01c16d960, 0xc00ed6fa00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.serverHandler.ServeHTTP(0xc0021949a0, 0x46c9f00, 0xc01c16d960, 0xc00ed6fa00)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc006944280, 0x46ec900, 0xc016b9eb40)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.4.3 
- Installation option (single install/HA):
single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Baremetal, Intel(R) Xeon(R) E-2276G CPU @ 3.80GHz, 16GB RAM
- Kubernetes version (use `kubectl version`): v1.17.5

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"archive", BuildDate:"2020-04-23T22:11:11Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:27:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:25:42 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

gz#11450

**Comment by flrichar** [comment]
gz#27033

**Comment by ItsReddi** [comment]
I am wondering if https://github.com/rancher/rancher/issues/28781 is the same?
But our pipeline was executing on 2.4.5.
What do you mean with an "unmatched Atlassian account"? did you found any workaround that we can try?

**Comment by jackwakefield** [comment]
It does appear to be the same issue from the stacktrace.

A workaround which worked for us was to add the email address from the last commit to a BitBucket account under [Personal settings -> Email aliases](https://bitbucket.org/account/settings/email/).
