### ISSUE TITLE
Bug: IngressController runtime error invalid memory address

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#27060]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Upgrade from v2.4.2 to v2.4.3

**Result:**
```
2020/05/11 21:13:55 [ERROR] IngressController prod-xxxx/activation-aggregator-redirect recovered from panic "runtime error: invalid memory address or nil pointer dereference". (err=<nil>) Call stack: 
goroutine 47349 [running]: 
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.RecoverFromPanic(0xc027a2bd30) 
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:158 +0xb5 
panic(0x3686a80, 0x6c38100) 
/usr/local/go/src/runtime/panic.go:679 +0x1b2 
github.com/rancher/rancher/pkg/controllers/user/endpoints.convertIngressToServicePublicEndpointsMap(0xc05012ed00, 0x1a26a01, 0xc0294f2920) 
/go/src/github.com/rancher/rancher/pkg/controllers/user/endpoints/endpoints.go:308 +0x51b 
github.com/rancher/rancher/pkg/controllers/user/endpoints.convertIngressToPublicEndpoints(0xc05012ed00, 0xc0238c1a01, 0x474b0e0, 0xc0238c1b90, 0x474b320) 
/go/src/github.com/rancher/rancher/pkg/controllers/user/endpoints/endpoints.go:337 +0x4c 
github.com/rancher/rancher/pkg/controllers/user/endpoints.(*IngressEndpointsController).reconcileEndpointsForIngress(0xc049b26600, 0xc05012ed00, 0x46947c0, 0xc039563c48, 0x4693e80) 
/go/src/github.com/rancher/rancher/pkg/controllers/user/endpoints/ingress_endpoints.go:42 +0x53 
github.com/rancher/rancher/pkg/controllers/user/endpoints.(*IngressEndpointsController).sync(0xc049b26600, 0xc02cdc0ed0, 0x28, 0xc05012ed00, 0xc00c8fd180, 0x7f18bca01008, 0x0, 0x0) 
/go/src/github.com/rancher/rancher/pkg/controllers/user/endpoints/ingress_endpoints.go:35 +0x110 
github.com/rancher/rancher/vendor/github.com/rancher/types/apis/extensions/v1beta1.(*ingressController).AddHandler.func1(0xc02cdc0ed0, 0x28, 0x3e319e0, 0xc05012ed00, 0xc02daf1cd8, 0x3, 0x3, 0x0) 
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/extensions/v1beta1/zz_generated_ingress_controller.go:155 +0x63 
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).syncHandler(0xc0495ab800, 0x33c6760, 0xc03272b5b0, 0x0, 0x0) 
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:387 +0x371 
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).processNextWorkItem(0xc0495ab800, 0x656c6f72222c5d00) 
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:296 +0xef 
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).runWorker(0xc0495ab800) 
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:284 +0x2b 
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc054429bf0) 
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e 
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc054429bf0, 0x3b9aca00, 0x0, 0x3635303530302d01, 0xc0456dacc0) 
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8 
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc054429bf0, 0x3b9aca00, 0xc0456dacc0) 
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d 
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).run 
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:276 +0xe8
```

**Other details that may be helpful:**
Ping me for additional logs or the ingress yaml.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.3
- Installation option (single install/HA): HA

**Comment by khushboo-rancher** [comment]
Couldn't reproduce the issue with below steps

1. Created a rancher v2.4.2 (1 node-all roles) set up.
2. Created an ingress with tls certificate.
3. Upgraded the setup to v2.4.3.
4. The ingress created in step-2 continues to work.
5. Created a new ingress, that worked fine too.

The ingress yaml
```
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      field.cattle.io/creatorId: u-n9nvl
      field.cattle.io/ingressState: '{"aW5ncmVzcy0xL2RlZmF1bHQva2h1c2gtdGVzdDEucWEucmFuY2hlci5zcGFjZS8vbmFtZS5odG1sLzgw":"deployment:default:wk-1","dmFsaWQtY2VydA==":"p-cbq8b:valid-cert"}'
      field.cattle.io/publicEndpoints: '[{"addresses":["x.x.x.x"],"port":443,"protocol":"HTTPS","serviceName":"default:ingress-c3fa5425aaf92c2166aa4e6b88115f1f","ingressName":"default:ingress-1","hostname":"test-host-at-rancher.com","path":"/name.html","allNodes":true}]'
    creationTimestamp: "2020-05-13T22:57:19Z"
    generation: 1
    labels:
      cattle.io/creator: norman
    name: ingress-1
    namespace: default
    resourceVersion: "3531"
    selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/ingress-1
    uid: 7ba5c8c0-de62-4e1c-b672-81fa164d5536
  spec:
    rules:
    - host: test-host-at-rancher.com
      http:
        paths:
        - backend:
            serviceName: ingress-c3fa5425aaf92c2166aa4e6b88115f1f
            servicePort: 80
          path: /name.html
    tls:
    - hosts:
      - test-host-at-rancher.com
      secretName: valid-cert
  status:
    loadBalancer:
      ingress:
      - ip: x.x.x.x

**Comment by sangeethah** [comment]
In this case , prior to upgrade ingress was created by kubectl via it's yaml, not via the web.

**Comment by SamKirsch10** [comment]
Ingress points to service which points to workload. All created via yamls by kubectl

**Comment by patrick0057** [comment]
YAML file of ingress
`
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1beta1","kind":"Ingress","metadata":{"annotations":{"nginx.ingress.kubernetes.io/server-snippet":"return 301 https://ac.company.com$request_uri;\n"},"name":"activation-aggregator-redirect","namespace":"prod-xxxx"},"spec":{"rules":[{"host":"ac-prod.cl.local"}],"tls":[{"secretName":"wildcard-cl-local"}]}}
    nginx.ingress.kubernetes.io/server-snippet: |
      return 301 https://ac.company.com$request_uri;
  creationTimestamp: "2020-05-05T19:10:17Z"
  generation: 1
  name: activation-aggregator-redirect
  namespace: prod-xxxx
  resourceVersion: "199790272"
  selfLink: /apis/extensions/v1beta1/namespaces/prod-xxxx/ingresses/activation-aggregator-redirect
  uid: a8aa647e-ee83-4a5e-820e-5aa63f9a6307
spec:
  rules:
  - host: ac-prod.cl.local
  tls:
  - secretName: wildcard-cl-local
status:
  loadBalancer:
    ingress:
    - ip: 10.229.0.179
    - ip: 10.229.0.180
    - ip: 10.229.0.181
    - ip: 10.229.0.182
    - ip: 10.229.0.183
    - ip: 10.229.0.184
    - ip: 10.229.0.185
    - ip: 10.229.0.186
    - ip: 10.229.0.187
    - ip: 10.229.0.188

`

**Comment by superseb** [comment]
This seems identical to https://github.com/rancher/rancher/issues/27230

**Comment by maggieliu** [comment]
@sangeethah can QA test and confirm if #27230 fixed this issue also?

**Comment by izaac** [comment]
I was able to reproduce in the Rancher upgrade path `v2.4.2 -> v2.4.3`
I no longer see this issue upgrading `v2.4.2 -> v2.4.5-rc2`
