### ISSUE TITLE
Aggressive Drain Causing Panic

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#27168]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a cluster with multiple worker nodes
After the cluster is up and nodes are running, open one of the nodes in the API UI (action menu -> view in api)
Perform the drain node action with `force: true` and `deleteLocalData: true`

**Result:**
Rancher panics and crashes. 

**Other details that may be helpful:**
Found while trying working on https://github.com/rancher/rancher/issues/27111

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Rancher - master-head (5/20/2020 830am)
Rancher-agent - master-2985-head
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Linode

Logs below: 
```
E0520 16:23:43.394495       7 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 4226 [running]:
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3676600, 0x6bad200)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x3676600, 0x6bad200)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/rancher/pkg/controllers/user/nodesyncer.(*nodesSyncer).syncTaints(0xc0046a0690, 0xc004291c30, 0xf, 0xc006c46000, 0xc000096380, 0x7f7d21094008, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/user/nodesyncer/nodetaints.go:32 +0x123
github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3.(*nodeController).AddHandler.func1(0xc004291c30, 0xf, 0x3dcd180, 0xc006c46000, 0xc007ba9ad0, 0x3, 0x3, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_node_controller.go:152 +0x63
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).AddHandler.func1(0xc004291c30, 0xf, 0x464aac0, 0xc006c46000, 0x464aac0, 0xc006c46000, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:57 +0x1e1
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc001843410, 0xc004291c30, 0xf, 0x464aac0, 0xc006c46000, 0x464aac0, 0xc006c46000, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*sharedHandler).OnChange(0xc000e562d0, 0xc004291c30, 0xf, 0x464aac0, 0xc006c46000, 0x42e801, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/sharedhandler.go:65 +0x150
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc00067c840, 0xc004291c30, 0xf, 0xc001857920, 0xc003268d30)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:211 +0xd1
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc00067c840, 0x33ba480, 0xc005255860, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:193 +0xf0
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc00067c840, 0x40c401)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:170 +0x51
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc00067c840)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:159 +0x2b
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0020aa5d0)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5e
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0020aa5d0, 0x460ebc0, 0xc000de6870, 0xc00054de01, 0xc0000b6660)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0020aa5d0, 0x3b9aca00, 0x0, 0x1, 0xc0000b6660)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0xe2
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0020aa5d0, 0x3b9aca00, 0xc0000b6660)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:130 +0x35e
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x168 pc=0x23c9983]

goroutine 4226 [running]:
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x3676600, 0x6bad200)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/rancher/pkg/controllers/user/nodesyncer.(*nodesSyncer).syncTaints(0xc0046a0690, 0xc004291c30, 0xf, 0xc006c46000, 0xc000096380, 0x7f7d21094008, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/user/nodesyncer/nodetaints.go:32 +0x123
github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3.(*nodeController).AddHandler.func1(0xc004291c30, 0xf, 0x3dcd180, 0xc006c46000, 0xc007ba9ad0, 0x3, 0x3, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_node_controller.go:152 +0x63
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).AddHandler.func1(0xc004291c30, 0xf, 0x464aac0, 0xc006c46000, 0x464aac0, 0xc006c46000, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:57 +0x1e1
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc001843410, 0xc004291c30, 0xf, 0x464aac0, 0xc006c46000, 0x464aac0, 0xc006c46000, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*sharedHandler).OnChange(0xc000e562d0, 0xc004291c30, 0xf, 0x464aac0, 0xc006c46000, 0x42e801, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/sharedhandler.go:65 +0x150
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc00067c840, 0xc004291c30, 0xf, 0xc001857920, 0xc003268d30)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:211 +0xd1
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc00067c840, 0x33ba480, 0xc005255860, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:193 +0xf0
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc00067c840, 0x40c401)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:170 +0x51
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc00067c840)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:159 +0x2b
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0020aa5d0)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5e
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0020aa5d0, 0x460ebc0, 0xc000de6870, 0xc00054de01, 0xc0000b6660)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0020aa5d0, 0x3b9aca00, 0x0, 0x1, 0xc0000b6660)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0xe2
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0020aa5d0, 0x3b9aca00, 0xc0000b6660)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:130 +0x35e
```

**Comment by kinarashah** [comment]
Seeing lasso in logs, this'd happen in master-head not 2.4.x, changing milestone

**Comment by sowmyav27** [comment]
This panic seems similar to this one https://github.com/rancher/rancher/issues/27181

**Comment by sowmyav27** [comment]
**on master-head commit id: `fd3e37bec`**

- Do an aggressive drain on a node (AWS cluster 1 msater/control plane and 3 worker nodes)
- Rancher logs : `Draining node <ip> in c-4dkj8 with flags --delete-local-data=true --force=true --grace-period=-1 --ignore-daemonsets=true --timeout=120s`
- No panic is seen in the rancher server logs
- Node is drained successfully.
