### ISSUE TITLE
E0522 03:20:18.688180       1 runtime.go:78] Observed a panic: "close of closed channel" (close of closed channel)

### ISSUE THREAD

**Issue by lhh821** [rancher/rancher#27202]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Result:**
Rancher  cattle-cluster-agent pods log a panic, pods die and respawn/reschedule

**Other details that may be helpful:**

<img width="695" alt="1590117878" src="https://user-images.githubusercontent.com/42127122/82628222-e0a3bb00-9c1e-11ea-8996-949281a37802.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

rancher/rancher v2.4.2
rancher/rancher-agent:v2.4.2

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"
```

- Docker version (use `docker version`):

```
Docker version 19.03.1
```

**Comment by NahaliY** [comment]
Hi All, I have the same issue with the cattle-cluster-agent 
Kubernetes version: v1.17.5
Rancher agent version: rancher/rancher-agent:v2.4.3

```` E0528 11:56:52.261827       7 runtime.go:78] Observed a panic: "close of closed channel" (close of closed channel)
goroutine 9965 [running]:
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3686ba0, 0x45af460)
        /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x3686ba0, 0x45af460)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/rancher/vendor/k8s.io/client-go/tools/cache.(*processorListener).pop(0xc009e44f00)
        /go/src/github.com/rancher/rancher/vendor/k8s.io/client-go/tools/cache/shared_informer.go:632 +0x2e2
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0090b7aa0, 0xc009a95f00)
        /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x59
created by github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
panic: close of closed channel [recovered]
        panic: close of closed channel

goroutine 9965 [running]:
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x3686ba0, 0x45af460)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/rancher/vendor/k8s.io/client-go/tools/cache.(*processorListener).pop(0xc009e44f00)
        /go/src/github.com/rancher/rancher/vendor/k8s.io/client-go/tools/cache/shared_informer.go:632 +0x2e2
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0090b7aa0, 0xc009a95f00)
        /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x59
created by github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
 ````
