### ISSUE TITLE
Panic in debug logs after installing Rancher and provisioning a cluster

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#27288]
**What kind of request is this:**
bug

**Steps to reproduce (least amount of steps as possible):**

- Start Rancher single install (I did this in a Rancher generated certs)
- set `loglevel debug` in the Rancher container
- open the Rancher container logs and continue monitoring
- login to Rancher
- Deploy an RKE cluster (like DO) here keep look at the logs

**Result:**

```
2020/05/26 18:00:02 [DEBUG] 2020/05/26 18:00:02 http: panic serving x.x.x.x:60058: runtime error: invalid memory address or nil pointer dereference
2020/05/26 18:00:02 [DEBUG] goroutine 26265 [running]:
2020/05/26 18:00:02 [DEBUG] net/http.(*conn).serve.func1(0xc003d68960)
2020/05/26 18:00:02 [DEBUG] 	/usr/local/go/src/net/http/server.go:1767 +0x139
2020/05/26 18:00:02 [DEBUG] panic(0x3686a80, 0x6c38100)
2020/05/26 18:00:02 [DEBUG] 	/usr/local/go/src/runtime/panic.go:679 +0x1b2
2020/05/26 18:00:02 [DEBUG] github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentTypeOptions.func1(0x46c9f00, 0xc00713f5e0, 0xc006523b00)
2020/05/26 18:00:02 [DEBUG] 	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/cache.go:47 +0x104
2020/05/26 18:00:02 [DEBUG] net/http.HandlerFunc.ServeHTTP(0xc005f3ec40, 0x46c9f00, 0xc00713f5e0, 0xc006523b00)
2020/05/26 18:00:02 [DEBUG] 	/usr/local/go/src/net/http/server.go:2007 +0x44
2020/05/26 18:00:02 [DEBUG] github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000648f00, 0x46c9f00, 0xc00713f5e0, 0xc006523800)
2020/05/26 18:00:02 [DEBUG] 	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
2020/05/26 18:00:02 [DEBUG] github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentTypeOptions.func1(0x46c9f00, 0xc00713f5e0, 0xc006523800)
2020/05/26 18:00:02 [DEBUG] 	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/cache.go:47 +0x131
2020/05/26 18:00:02 [DEBUG] net/http.HandlerFunc.ServeHTTP(0xc005f3ec20, 0x46c9f00, 0xc00713f5e0, 0xc006523800)
2020/05/26 18:00:02 [DEBUG] 	/usr/local/go/src/net/http/server.go:2007 +0x44
2020/05/26 18:00:02 [DEBUG] github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00102ed80, 0x46c9f00, 0xc00713f5e0, 0xc006523600)
2020/05/26 18:00:02 [DEBUG] 	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
2020/05/26 18:00:02 [DEBUG] github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000649200, 0x46c9f00, 0xc00713f5e0, 0xc006523300)
2020/05/26 18:00:02 [DEBUG] 	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
2020/05/26 18:00:02 [DEBUG] github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0006492c0, 0x46c9f00, 0xc00713f5e0, 0xc006523100)
2020/05/26 18:00:02 [DEBUG] 	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
2020/05/26 18:00:02 [DEBUG] github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/dashboard.Route.func2(0x46c9f00, 0xc00713f5e0, 0xc006523100)
2020/05/26 18:00:02 [DEBUG] 	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/dashboard/ui.go:56 +0xe5
2020/05/26 18:00:02 [DEBUG] net/http.HandlerFunc.ServeHTTP(0xc000850610, 0x46c9f00, 0xc00713f5e0, 0xc006523100)
2020/05/26 18:00:02 [DEBUG] 	/usr/local/go/src/net/http/server.go:2007 +0x44
2020/05/26 18:00:02 [DEBUG] github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001ec840, 0x46c9f00, 0xc00713f5e0, 0xc006522d00)
2020/05/26 18:00:02 [DEBUG] 	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
2020/05/26 18:00:02 [DEBUG] github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/server.wrapHandler.func1(0x46c9f00, 0xc00713f5e0, 0xc006522d00)
2020/05/26 18:00:02 [DEBUG] 	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/server/server.go:187 +0x95
2020/05/26 18:00:02 [DEBUG] net/http.HandlerFunc.ServeHTTP(0xc003676120, 0x46c9f00, 0xc00713f5e0, 0xc006522d00)
2020/05/26 18:00:02 [DEBUG] 	/usr/local/go/src/net/http/server.go:2007 +0x44
2020/05/26 18:00:02 [DEBUG] github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener.HTTPRedirect.func1(0x46c9f00, 0xc00713f5e0, 0xc006522d00)
2020/05/26 18:00:02 [DEBUG] 	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/redirect.go:20 +0x221
2020/05/26 18:00:02 [DEBUG] net/http.HandlerFunc.ServeHTTP(0xc006278280, 0x46c9f00, 0xc00713f5e0, 0xc006522d00)
2020/05/26 18:00:02 [DEBUG] 	/usr/local/go/src/net/http/server.go:2007 +0x44
2020/05/26 18:00:02 [DEBUG] net/http.serverHandler.ServeHTTP(0xc00532ab60, 0x46c9f00, 0xc00713f5e0, 0xc006522d00)
2020/05/26 18:00:02 [DEBUG] 	/usr/local/go/src/net/http/server.go:2802 +0xa4
2020/05/26 18:00:02 [DEBUG] net/http.(*conn).serve(0xc003d68960, 0x46ec900, 0xc003c86880)
2020/05/26 18:00:02 [DEBUG] 	/usr/local/go/src/net/http/server.go:1890 +0x875
2020/05/26 18:00:02 [DEBUG] created by net/http.(*Server).Serve
2020/05/26 18:00:02 [DEBUG] 	/usr/local/go/src/net/http/server.go:2927 +0x38e
2020/05/26 18:00:02 [DEBUG] 2020/05/26 18:00:02 http: panic serving x.x.x.x:60060: runtime error: invalid memory address or nil pointer dereference
2020/05/26 18:00:02 [DEBUG] goroutine 26266 [running]:
2020/05/26 18:00:02 [DEBUG] net/http.(*conn).serve.func1(0xc003d68a00)
2020/05/26 18:00:02 [DEBUG] 	/usr/local/go/src/net/http/server.go:1767 +0x139
2020/05/26 18:00:02 [DEBUG] panic(0x3686a80, 0x6c38100)
2020/05/26 18:00:02 [DEBUG] 	/usr/local/go/src/runtime/panic.go:679 +0x1b2
2020/05/26 18:00:02 [DEBUG] github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentTypeOptions.func1(0x46c9f00, 0xc0092e28c0, 0xc00657cc00)
2020/05/26 18:00:02 [DEBUG] 	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/cache.go:47 +0x104
2020/05/26 18:00:02 [DEBUG] net/http.HandlerFunc.ServeHTTP(0xc005f68c00, 0x46c9f00, 0xc0092e28c0, 0xc00657cc00)
2020/05/26 18:00:02 [DEBUG] 	/usr/local/go/src/net/http/server.go:2007 +0x44
2020/05/26 18:00:02 [DEBUG] github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000648f00, 0x46c9f00, 0xc0092e28c0, 0xc00657c500)
2020/05/26 18:00:02 [DEBUG] 	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
2020/05/26 18:00:02 [DEBUG] github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentTypeOptions.func1(0x46c9f00, 0xc0092e28c0, 0xc00657c500)
2020/05/26 18:00:02 [DEBUG] 	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/cache.go:47 +0x131
2020/05/26 18:00:02 [DEBUG] net/http.HandlerFunc.ServeHTTP(0xc005f68be0, 0x46c9f00, 0xc0092e28c0, 0xc00657c500)
2020/05/26 18:00:02 [DEBUG] 	/usr/local/go/src/net/http/server.go:2007 +0x44
2020/05/26 18:00:02 [DEBUG] github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00102ed80, 0x46c9f00, 0xc0092e28c0, 0xc00657c200)
2020/05/26 18:00:02 [DEBUG] 	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
2020/05/26 18:00:02 [DEBUG] github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000649200, 0x46c9f00, 0xc0092e28c0, 0xc00657c000)
2020/05/26 18:00:02 [DEBUG] 	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
2020/05/26 18:00:02 [DEBUG] github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0006492c0, 0x46c9f00, 0xc0092e28c0, 0xc0064f1d00)
2020/05/26 18:00:02 [DEBUG] 	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
2020/05/26 18:00:02 [DEBUG] github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/dashboard.Route.func2(0x46c9f00, 0xc0092e28c0, 0xc0064f1d00)
2020/05/26 18:00:02 [DEBUG] 	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/dashboard/ui.go:56 +0xe5
2020/05/26 18:00:02 [DEBUG] net/http.HandlerFunc.ServeHTTP(0xc000850610, 0x46c9f00, 0xc0092e28c0, 0xc0064f1d00)
2020/05/26 18:00:02 [DEBUG] 	/usr/local/go/src/net/http/server.go:2007 +0x44
2020/05/26 18:00:02 [DEBUG] github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001ec840, 0x46c9f00, 0xc0092e28c0, 0xc0064f1b00)
2020/05/26 18:00:02 [DEBUG] 	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
2020/05/26 18:00:02 [DEBUG] github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/server.wrapHandler.func1(0x46c9f00, 0xc0092e28c0, 0xc0064f1b00)
2020/05/26 18:00:02 [DEBUG] 	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/server/server.go:187 +0x95
2020/05/26 18:00:02 [DEBUG] net/http.HandlerFunc.ServeHTTP(0xc003676120, 0x46c9f00, 0xc0092e28c0, 0xc0064f1b00)
2020/05/26 18:00:02 [DEBUG] 	/usr/local/go/src/net/http/server.go:2007 +0x44
2020/05/26 18:00:02 [DEBUG] github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener.HTTPRedirect.func1(0x46c9f00, 0xc0092e28c0, 0xc0064f1b00)
2020/05/26 18:00:02 [DEBUG] 	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/redirect.go:20 +0x221
2020/05/26 18:00:02 [DEBUG] net/http.HandlerFunc.ServeHTTP(0xc006278280, 0x46c9f00, 0xc0092e28c0, 0xc0064f1b00)
2020/05/26 18:00:02 [DEBUG] 	/usr/local/go/src/net/http/server.go:2007 +0x44
2020/05/26 18:00:02 [DEBUG] net/http.serverHandler.ServeHTTP(0xc00532ab60, 0x46c9f00, 0xc0092e28c0, 0xc0064f1b00)
2020/05/26 18:00:02 [DEBUG] 	/usr/local/go/src/net/http/server.go:2802 +0xa4
2020/05/26 18:00:02 [DEBUG] net/http.(*conn).serve(0xc003d68a00, 0x46ec900, 0xc003d17580)
2020/05/26 18:00:02 [DEBUG] 	/usr/local/go/src/net/http/server.go:1890 +0x875
2020/05/26 18:00:02 [DEBUG] created by net/http.(*Server).Serve
2020/05/26 18:00:02 [DEBUG] 	/usr/local/go/src/net/http/server.go:2927 +0x38e
```

**Other details that may be helpful:**

**I do not see any impact in the Rancher or clusters functionality.**
After that this panic error will keep appearing in the debug logs intermittently.

**Environment information**
- Rancher versions:
  - Rancher `master-head (05/27/2020)` commit id: d9184e914
  - Rancher `v2.4-head (05/26/2020)` commit id: aae934198
  - Rancher `v2.4.3`
- Installation option: single

**Comment by izaac** [comment]
I also observed this in Rancher `v2.4.3` I updated the issue description with this information too.

**Comment by sangeethah** [comment]
Reopening to get fixes merge to release branch.

**Comment by izaac** [comment]
I am trying in Rancher version `master-head (07/02/2020)`  commit _beae3dfa0_ but the panic is still present in my test environment, do we need to vendor something else in master?

**Comment by izaac** [comment]
Rancher version `v2.4-head (07/08/2020)` commit _43c8db4e2_
Rancher version `master-head (07/08/2020)` commit _6f83549cd_

No longer see the panic error in the Rancher logs with `loglevel` debug.
Validated that enabling Shibboleth auth still works as expected.
