### ISSUE TITLE
Panic in kube-apiserver when there are 10k secrets created in the cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#27519]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Deploy a HA Rancher server
- Deploy a custom cluster - 1 etcd, 1 control plane and 3 worker nodes
- Create 10k+ secrets
- Delete all rancher pods
- User Cluster fails to come up - seen in `Unavailable` state.
- Rancher logs: 
```
2020/06/09 21:00:50 [INFO] Starting cluster controllers for c-d654n
2020/06/09 21:01:20 [INFO] Stopping cluster agent for c-d654n
E0609 21:01:20.070313       6 request.go:879] Unexpected error when reading response body: context deadline exceeded (Client.Timeout exceeded while reading body)
2020/06/09 21:01:23 [INFO] Registering project network policy
2020/06/09 21:01:23 [INFO] Registering CIS controller
2020/06/09 21:01:23 [INFO] registering podsecuritypolicy cluster handler for cluster c-d654n
2020/06/09 21:01:23 [INFO] registering podsecuritypolicy project handler for cluster c-d654n
2020/06/09 21:01:23 [INFO] registering podsecuritypolicy namespace handler for cluster c-d654n
2020/06/09 21:01:23 [INFO] registering podsecuritypolicy serviceaccount handler for cluster c-d654n
2020/06/09 21:01:23 [INFO] registering podsecuritypolicy template handler for cluster c-d654n
2020/06/09 21:01:23 [INFO] Registering monitoring for cluster "c-d654n"
2020/06/09 21:01:23 [INFO] Registering istio for cluster "c-d654n"
2020/06/09 21:01:23 [INFO] Starting cluster controllers for c-d654n
2020/06/09 21:01:53 [INFO] Stopping cluster agent for c-d654n
E0609 21:01:53.997149       6 request.go:879] Unexpected error when reading response body: context deadline exceeded (Client.Timeout exceeded while reading body)
```

- Upgrade to **`2.4.5-rc2`**
- The user cluster comes up fine
- Rancher server logs:
- User is able to list 999 secrets out of 10k+. 
- API call to fetch the secrets first time takes about 2.8 minutes
- However there is a panic in the kube-apiserver of the user cluster 
```
E0609 22:47:37.340335       1 writers.go:105] apiserver was unable to write a JSON response: http: Handler timeout
E0609 22:47:37.340360       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}
E0609 22:47:37.340379       1 runtime.go:78] Observed a panic: &errors.errorString{s:"killing connection/stream because serving request timed out and response had been started"} (killing connection/stream because serving request timed out and response had been started)
goroutine 32766862 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3bbe7e0, 0xc00052e670)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc00f0f9c90, 0x1, 0x1)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x3bbe7e0, 0xc00052e670)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc01f0edd60, 0xc029d9cf00)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:257 +0x1cf
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc007579d60, 0x4fd73e0, 0xc049e7fe30, 0xc013a7c500)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:141 +0x310
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x4fd73e0, 0xc049e7fe30, 0xc013a7c400)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:47 +0x10f
net/http.HandlerFunc.ServeHTTP(0xc0075a2720, 0x4fd73e0, 0xc049e7fe30, 0xc013a7c400)
	/usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x4fd73e0, 0xc049e7fe30, 0xc013a7c300)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x274
net/http.HandlerFunc.ServeHTTP(0xc0075a2750, 0x4fd73e0, 0xc049e7fe30, 0xc013a7c300)
	/usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.WithLogging.func1(0x4fca3e0, 0xc00b65a910, 0xc013831800)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:89 +0x2ca
net/http.HandlerFunc.ServeHTTP(0xc007579d80, 0x4fca3e0, 0xc00b65a910, 0xc013831800)
	/usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x4fca3e0, 0xc00b65a910, 0xc013831800)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:51 +0x13e
net/http.HandlerFunc.ServeHTTP(0xc007579da0, 0x4fca3e0, 0xc00b65a910, 0xc013831800)
	/usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc0075a2780, 0x4fca3e0, 0xc00b65a910, 0xc013831800)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
net/http.serverHandler.ServeHTTP(0xc007aeb6c0, 0x4fca3e0, 0xc00b65a910, 0xc013831800)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.initNPNRequest.ServeHTTP(0x4fe40a0, 0xc037a88600, 0xc00c3b8000, 0xc007aeb6c0, 0x4fca3e0, 0xc00b65a910, 0xc013831800)
	/usr/local/go/src/net/http/server.go:3366 +0x8d
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).runHandler(0xc00dc6d080, 0xc00b65a910, 0xc013831800, 0xc0156a7120)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:2149 +0x9f
created by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).processHeaders
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:1883 +0x4eb
E0609 22:47:37.340413       1 wrap.go:39] apiserver panic'd on GET /api/v1/secrets?limit=500&resourceVersion=0
I0609 22:47:37.340480       1 log.go:172] http2: panic serving 10.42.0.3:32918: killing connection/stream because serving request timed out and response had been started
goroutine 32766862 [running]:
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).runHandler.func1(0xc00b65a910, 0xc00f0f9f67, 0xc00dc6d080)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:2142 +0x16b
panic(0x3bbe7e0, 0xc00052e670)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc00f0f9c90, 0x1, 0x1)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x3bbe7e0, 0xc00052e670)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc01f0edd60, 0xc029d9cf00)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:257 +0x1cf
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc007579d60, 0x4fd73e0, 0xc049e7fe30, 0xc013a7c500)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:141 +0x310
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x4fd73e0, 0xc049e7fe30, 0xc013a7c400)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:47 +0x10f
net/http.HandlerFunc.ServeHTTP(0xc0075a2720, 0x4fd73e0, 0xc049e7fe30, 0xc013a7c400)
	/usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x4fd73e0, 0xc049e7fe30, 0xc013a7c300)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x274
net/http.HandlerFunc.ServeHTTP(0xc0075a2750, 0x4fd73e0, 0xc049e7fe30, 0xc013a7c300)
	/usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.WithLogging.func1(0x4fca3e0, 0xc00b65a910, 0xc013831800)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:89 +0x2ca
net/http.HandlerFunc.ServeHTTP(0xc007579d80, 0x4fca3e0, 0xc00b65a910, 0xc013831800)
	/usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x4fca3e0, 0xc00b65a910, 0xc013831800)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:51 +0x13e
net/http.HandlerFunc.ServeHTTP(0xc007579da0, 0x4fca3e0, 0xc00b65a910, 0xc013831800)
	/usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc0075a2780, 0x4fca3e0, 0xc00b65a910, 0xc013831800)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
net/http.serverHandler.ServeHTTP(0xc007aeb6c0, 0x4fca3e0, 0xc00b65a910, 0xc013831800)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.initNPNRequest.ServeHTTP(0x4fe40a0, 0xc037a88600, 0xc00c3b8000, 0xc007aeb6c0, 0x4fca3e0, 0xc00b65a910, 0xc013831800)
	/usr/local/go/src/net/http/server.go:3366 +0x8d
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).runHandler(0xc00dc6d080, 0xc00b65a910, 0xc013831800, 0xc0156a7120)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:2149 +0x9f
created by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).processHeaders
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:1883 +0x4eb
E0609 22:47:37.341455       1 writers.go:118] apiserver was unable to write a fallback JSON response: http: Handler timeout
I0609 22:47:37.342578       1 trace.go:116] Trace[90318884]: "List" url:/api/v1/secrets,user-agent:agent/v0.0.0 (linux/amd64) kubernetes/$Format,client:10.42.0.3 (started: 2020-06-09 22:46:37.340650343 +0000 UTC m=+14266.777689843) (total time: 1m0.001897595s):
Trace[90318884]: [1m0.001896172s] [59.994691856s] Writing http response done count:11037
I0609 22:47:55.047320       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
E0609 22:48:37.341238       1 runtime.go:78] Observed a panic: &errors.errorString{s:"killing connection/stream because serving request timed out and response had been started"} (killing connection/stream because serving request timed out and response had been started)
goroutine 33149853 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachine
```

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5-rc2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): CUSTOM

gz#10796

**Comment by Jono-SUSE-Rancher** [comment]
Since we've identified the panic can we just write a quick fix for that?

**Comment by SheilaghM** [comment]
This appears to be 'working as designed' in Kubernetes. This is not a rancher issue. Can we close?

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:v2.5-head` `version 38649e2`

Steps:
Deploy a HA Rancher server
Deploy a custom cluster - 1 etcd, 1 control plane and 3 worker nodes
Create 10k+ secrets
Delete all rancher pods

Result:
Custom cluster is available.
User is able to list all 10K+ secrets.
No error observed in Rancher logs.
No panic observed in kube-apiserver.

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:v2.5-head` `version 38649e2`

Steps:
Deploy a HA Rancher server
Deploy a custom cluster (k8s version v1.19.8-rancher1-2) - 1 etcd, 1 control plane and 3 worker nodes
Create 10k+ secrets
Delete all rancher pods

Result:
Custom cluster is available.
User is able to list all 10k+ secrets.
No panic observed in kube-apiserver.
Did not see the error mentioned above: `Unexpected error when reading response body: context deadline exceeded (Client.Timeout exceeded while reading body)`

**Comment by sowmyav27** [comment]
on 1.18.7, upgrade from 2.4.5 to 2.5.8-rc2, no panic is seen in kube-apiserver followed steps in the original issue's comment

**Comment by sowmyav27** [comment]
Closing per comments - https://github.com/rancher/rancher/issues/27519#issuecomment-816420929, https://github.com/rancher/rancher/issues/27519#issuecomment-799853948 and https://github.com/rancher/rancher/issues/27519#issuecomment-794478575
