### ISSUE TITLE
Panic seen in rancher server and rancher server keeps restarting

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#27618]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a cluster through API (Used Jenkins job)
**rke config of cluster created through automation:**
```
rke_config = {
    "addonJobTimeout": 30,
    "authentication":
    {"strategy": "x509",
     "type": "authnConfig"},
    "ignoreDockerVersion": True,
    "ingress":
        {"provider": "nginx",
         "type": "ingressConfig"},
    "monitoring":
        {"provider": "metrics-server",
         "type": "monitoringConfig"},
    "network":
        {"plugin": "canal",
         "type": "networkConfig",
         "options": {"flannel_backend_type": "vxlan"}},
    "services": {
        "etcd": {
            "extraArgs":
                {"heartbeat-interval": 500,
                 "election-timeout": 5000},
            "snapshot": False,
            "backupConfig":
                {"intervalHours": 12, "retention": 6, "type": "backupConfig"},
            "creation": "12h",
            "retention": "72h",
            "type": "etcdService"},
        "kubeApi": {
            "alwaysPullImages": False,
            "podSecurityPolicy": False,
            "serviceNodePortRange": "30000-32767",
            "type": "kubeAPIService"}},
    "sshAgentAuth": False}
```
- Wait for the cluster to come up.
- Edit cluster, set `Drain : True`
- Save the changes made
- The rancher server panics. And keeps restarting

**Rancher logs:**
```
2020/06/16 21:10:17 [INFO] Removing container [etcd-fix-perm] on host [ip], try #1







2020/06/16 21:10:17 [INFO] cluster [c-mvsr4] provisioning: [remove/etcd-fix-perm] Successfully removed container on host [ip]
2020/06/16 21:10:17 [INFO] Image [rancher/rke-tools:v0.1.58] exists on host [ip]
2020/06/16 21:10:18 [INFO] Starting container [rke-log-linker] on host [ip], try #1







2020/06/16 21:10:18 [INFO] cluster [c-mvsr4] provisioning: [etcd] Successfully started [rke-log-linker] container on host [ip]
2020/06/16 21:10:18 [INFO] Removing container [rke-log-linker] on host [ip], try #1







2020/06/16 21:10:18 [INFO] cluster [c-mvsr4] provisioning: [remove/rke-log-linker] Successfully removed container on host [ip]
2020/06/16 21:10:18 [INFO] cluster [c-mvsr4] provisioning: [etcd] Successfully started etcd plane.. Checking etcd cluster health
2020/06/16 21:10:19 [INFO] [controlplane] Now checking status of node priv-ip, try rancher/rancher#1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x226b187]

goroutine 13499 [running]:
github.com/rancher/rancher/vendor/github.com/rancher/rke/services.getDrainHelper(...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/services/node_util.go:55
github.com/rancher/rancher/vendor/github.com/rancher/rke/services.UpgradeControlPlaneNodes(0x47ef500, 0xc005f90960, 0xc0057b71e0, 0xc00738c070, 0x1, 0x1, 0xc002ecd330, 0xc0065e8780, 0xc009f53e00, 0xc0075cf100, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/services/controlplane.go:72 +0xc57
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.(*Cluster).UpgradeControlPlane(0xc009a3a000, 0x47ef500, 0xc005f90960, 0xc0057b71e0, 0xc009f53e00, 0x3b, 0x16, 0xc, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/cluster.go:225 +0xb4f
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.(*Cluster).DeployControlPlane(0xc009a3a000, 0x47ef500, 0xc005f90960, 0xc003ac2c78, 0x1, 0x0, 0x19, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/cluster.go:161 +0x85a
github.com/rancher/rancher/vendor/github.com/rancher/rke/cmd.ClusterUp(0x47ef500, 0xc005f90960, 0xc002ecd320, 0xc002ecd330, 0xc004859ea0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cmd/up.go:195 +0xcee
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/rke.(*Driver).Update(0xc000c24540, 0x47ef500, 0xc005f90960, 0xc002660d00, 0xc00422d080, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/rke/rke_driver.go:229 +0x38f
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types.(*GrpcServer).Update(0xc004c36560, 0x47ef500, 0xc005f90600, 0xc005f90720, 0xc004c36560, 0xc005f90600, 0xc00cfd1b30)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/rpc_server.go:52 +0x7c
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types._Driver_Update_Handler(0x3dfe200, 0xc004c36560, 0x47ef500, 0xc005f90600, 0xc0081a3a40, 0x0, 0x47ef500, 0xc005f90600, 0xc00921a000, 0x60b8b)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/drivers.pb.go:1454 +0x21a
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc00c409080, 0x4824100, 0xc00b79e000, 0xc004406d00, 0xc005fb21e0, 0x6dd0898, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:1024 +0x4f4
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).handleStream(0xc00c409080, 0x4824100, 0xc00b79e000, 0xc004406d00, 0x0)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:1313 +0xd97
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc005777a00, 0xc00c409080, 0x4824100, 0xc00b79e000, 0xc004406d00)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:722 +0xbb
created by github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:720 +0xa1
2020/06/16 21:10:20 [INFO] Rancher version v2.4.5-rc6 (65792cafb) is starting

```

**Expected Result:**
No Panic should be seen

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5-rc6
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Kubernetes version (use `kubectl version`):

```
1.18.3-rancher2-2
```

**Comment by kinarashah** [comment]
@mrajashree is there any empty field that rancher needs to set? @sowmyav27 mentioned it's always reproducible using automation tests

**Comment by sowmyav27** [comment]
**Validated on latest `2.4-head` - commit id: `4ff749272`**

- Deploy a cluster through API (Used Jenkins job)
- rke config of cluster created through automation:

```
rke_config = {
    "addonJobTimeout": 30,
    "authentication":
    {"strategy": "x509",
     "type": "authnConfig"},
    "ignoreDockerVersion": True,
    "ingress":
        {"provider": "nginx",
         "type": "ingressConfig"},
    "monitoring":
        {"provider": "metrics-server",
         "type": "monitoringConfig"},
    "network":
        {"plugin": "canal",
         "type": "networkConfig",
         "options": {"flannel_backend_type": "vxlan"}},
    "services": {
        "etcd": {
            "extraArgs":
                {"heartbeat-interval": 500,
                 "election-timeout": 5000},
            "snapshot": False,
            "backupConfig":
                {"intervalHours": 12, "retention": 6, "type": "backupConfig"},
            "creation": "12h",
            "retention": "72h",
            "type": "etcdService"},
        "kubeApi": {
            "alwaysPullImages": False,
            "podSecurityPolicy": False,
            "serviceNodePortRange": "30000-32767",
            "type": "kubeAPIService"}},
    "sshAgentAuth": False}
```

- Wait for the cluster to come up.
- Edit cluster, set Drain : True
- Save the changes made
- The rancher server panics. And keeps restarting
- Rancher logs:

```
2020/06/17 17:31:39 [INFO] cluster [c-g9bjp] provisioning: [controlplane] Processing controlplane hosts for upgrade 1 at a time
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x226a867]

goroutine 31561 [running]:
github.com/rancher/rancher/vendor/github.com/rancher/rke/services.getDrainHelper(...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/services/node_util.go:53
github.com/rancher/rancher/vendor/github.com/rancher/rke/services.UpgradeControlPlaneNodes(0x47ef500, 0xc005fcd470, 0xc005260f20, 0xc005811ec8, 0x1, 0x1, 0xc000903170, 0xc0064bbc80, 0xc00304c390, 0xc00a05b000, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/services/controlplane.go:72 +0x337
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.(*Cluster).UpgradeControlPlane(0xc009b1ea80, 0x47ef500, 0xc005fcd470, 0xc005260f20, 0xc00304c390, 0x3b, 0x18, 0xc, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/cluster.go:225 +0xb4f
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.(*Cluster).DeployControlPlane(0xc009b1ea80, 0x47ef500, 0xc005fcd470, 0xc0076c4c78, 0x1, 0x0, 0x17, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/cluster.go:161 +0x85a
github.com/rancher/rancher/vendor/github.com/rancher/rke/cmd.ClusterUp(0x47ef500, 0xc005fcd470, 0xc000903150, 0xc000903170, 0xc0039d36c0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cmd/up.go:195 +0xcee
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/rke.(*Driver).Update(0xc0003a1500, 0x47ef500, 0xc005fcd470, 0xc0065bc9c0, 0xc003f69600, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/rke/rke_driver.go:229 +0x38f
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types.(*GrpcServer).Update(0xc006ef2c20, 0x47ef500, 0xc005fcd2f0, 0xc005fcd320, 0xc006ef2c20, 0xc005fcd2f0, 0xc008dfdb30)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/rpc_server.go:52 +0x7c
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types._Driver_Update_Handler(0x3dfe200, 0xc006ef2c20, 0x47ef500, 0xc005fcd2f0, 0xc005ccf380, 0x0, 0x47ef500, 0xc005fcd2f0, 0xc00bc36000, 0x60c87)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/drivers.pb.go:1454 +0x21a
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc00366f200, 0x48240a0, 0xc00467c600, 0xc00a4c7200, 0xc005f70cf0, 0x6dd0898, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:1024 +0x4f4
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).handleStream(0xc00366f200, 0x48240a0, 0xc00467c600, 0xc00a4c7200, 0x0)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:1313 +0xd97
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00906b480, 0xc00366f200, 0x48240a0, 0xc00467c600, 0xc00a4c7200)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:722 +0xbb
created by github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:720 +0xa1
```

**Comment by sowmyav27** [comment]
**Validated on 2.4-head latest - commit id: `143066942` and on master-head commit id: `7d4fa9e09`**

Steps:

- Deploy a cluster through API (Used Jenkins job)
- rke config of cluster created through automation:

```
rke_config = {
    "addonJobTimeout": 30,
    "authentication":
    {"strategy": "x509",
     "type": "authnConfig"},
    "ignoreDockerVersion": True,
    "ingress":
        {"provider": "nginx",
         "type": "ingressConfig"},
    "monitoring":
        {"provider": "metrics-server",
         "type": "monitoringConfig"},
    "network":
        {"plugin": "canal",
         "type": "networkConfig",
         "options": {"flannel_backend_type": "vxlan"}},
    "services": {
        "etcd": {
            "extraArgs":
                {"heartbeat-interval": 500,
                 "election-timeout": 5000},
            "snapshot": False,
            "backupConfig":
                {"intervalHours": 12, "retention": 6, "type": "backupConfig"},
            "creation": "12h",
            "retention": "72h",
            "type": "etcdService"},
        "kubeApi": {
            "alwaysPullImages": False,
            "podSecurityPolicy": False,
            "serviceNodePortRange": "30000-32767",
            "type": "kubeAPIService"}},
    "sshAgentAuth": False}
```

- Wait for the cluster to come up.
- Edit cluster, set Drain : True
- Save the changes made
- NO panic is seen in the rancher logs
- Cluster updates successfully and comes back `Active`
