### ISSUE TITLE
Rancher server restarts and panics seen in rancher logs

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#27858]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
Node on which Rancher server was running - `Ubuntu 18.04 LTS, Linode 2GB: 1 CPU, 50GB`
Deploy clusters. (I had about 9 clusters - windows clusters - 3 windows nodes, 3 linux nodes) deployed
Run automation checks on the clusters - created workloads/ingress
The rancher server restarted a couple of times.
rancher logs of the First restart:
```
I0707 18:35:36.868626      22 leaderelection.go:288] failed to renew lease kube-system/kube-controller-manager: failed to tryAcquireOrRenew context deadline exceeded
F0707 18:35:36.872072      22 controllermanager.go:279] leaderelection lost
2020/07/07 18:35:37 [INFO] [mgmt-project-rbac-create] Creating namespace p-fcvmh
I0707 18:35:38.439249       6 trace.go:116] Trace[255408941]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-07-07 18:35:07.616713903 +0000 UTC m=+5204.445799399) (total time: 30.812192406s):
Trace[255408941]: [30.812192406s] [30.812192406s] END
E0707 18:35:38.440468       6 reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1.ReplicationController: Get https://ip-a:6443/api/v1/replicationcontrollers?resourceVersion=655&timeout=30s: context deadline exceeded
2020-07-07 18:35:38.456099 W | etcdserver: read-only range request "key:\"/registry/secrets/\" range_end:\"/registry/secrets0\" " with result "range_response_count:199 size:2220787" took too long (272.794954ms) to execute
I0707 18:35:39.733500       6 trace.go:116] Trace[375980583]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-07-07 18:35:09.654128849 +0000 UTC m=+5206.483214355) (total time: 30.072609534s):
Trace[375980583]: [30.072609534s] [30.072609534s] END
E0707 18:35:39.736105       6 reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1beta1.PodSecurityPolicy: Get https://ip-e:6443/apis/policy/v1beta1/podsecuritypolicies?resourceVersion=568&timeout=30s: context deadline exceeded
2020/07/07 18:35:39 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->52.15.222.238:50323: read: connection reset by peer
I0707 18:35:40.298041       6 trace.go:116] Trace[1824433804]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-07-07 18:35:09.85766802 +0000 UTC m=+5206.686753516) (total time: 30.435443224s):
Trace[1824433804]: [30.435443224s] [30.435443224s] END
E0707 18:35:40.299694       6 reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1beta1.CronJob: Get https://ip-d:6443/apis/batch/v1beta1/cronjobs?resourceVersion=690&timeout=30s: context deadline exceeded
I0707 18:35:40.935356       6 trace.go:116] Trace[217722830]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-07-07 18:35:10.878577984 +0000 UTC m=+5207.707663450) (total time: 30.052188856s):
Trace[217722830]: [30.052188856s] [30.052188856s] END
E0707 18:35:40.936757       6 reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1beta1.CronJob: Get https://ip-f:6443/apis/batch/v1beta1/cronjobs?resourceVersion=567&timeout=30s: context deadline exceeded
I0707 18:35:43.349377       6 trace.go:116] Trace[1141611668]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-07-07 18:35:13.32962054 +0000 UTC m=+5210.158705996) (total time: 30.017489283s):
Trace[1141611668]: [30.017489283s] [30.017489283s] END
E0707 18:35:43.376061       6 reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1.ReplicationController: Get https://ip-c:6443/api/v1/replicationcontrollers?resourceVersion=653&timeout=30s: context deadline exceeded
I0707 18:35:43.755489       6 trace.go:116] Trace[1490835290]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-07-07 18:35:13.654087293 +0000 UTC m=+5210.483172759) (total time: 30.098019925s):
Trace[1490835290]: [30.098019925s] [30.098019925s] END
E0707 18:35:43.756642       6 reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1.NetworkPolicy: Get https://ip-a:6443/apis/networking.k8s.io/v1/networkpolicies?resourceVersion=655&timeout=30s: context deadline exceeded
I0707 18:35:43.761262       6 trace.go:116] Trace[1023519560]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-07-07 18:35:13.206737369 +0000 UTC m=+5210.035822845) (total time: 30.554361311s):
Trace[1023519560]: [30.554361311s] [30.554361311s] END
E0707 18:35:43.761995       6 reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1.ReplicationController: Get https://ip-b:6443/api/v1/replicationcontrollers?resourceVersion=564&timeout=30s: context deadline exceeded
I0707 18:35:44.419459       6 trace.go:116] Trace[1396055971]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-07-07 18:35:13.972641576 +0000 UTC m=+5210.801727062) (total time: 30.44347379s):
Trace[1396055971]: [30.44347379s] [30.44347379s] END
E0707 18:35:44.420771       6 reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1.Job: Get https://ip-c:6443/apis/batch/v1/jobs?resourceVersion=653&timeout=30s: context deadline exceeded
I0707 18:35:44.741613       6 trace.go:116] Trace[1968503262]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-07-07 18:35:14.399316166 +0000 UTC m=+5211.228401692) (total time: 30.339626081s):
Trace[1968503262]: [30.339626081s] [30.339626081s] END
E0707 18:35:44.742663       6 reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1.NetworkPolicy: Get https://ip-d:6443/apis/networking.k8s.io/v1/networkpolicies?resourceVersion=690&timeout=30s: context deadline exceeded
2020/07/07 18:35:46 [FATAL] k3s exited with: exit status 255
2020/07/07 18:35:49 [INFO] Rancher version fb2c5fb2d (fb2c5fb2d) is starting
```

- Panic seen in logs after the next restart of rancher server
```
Trace[1853087354]: [713.882438ms] [711.923359ms] About to write a response
E0707 19:58:47.481650      22 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
I0707 19:58:48.486529      22 trace.go:116] Trace[1353846683]: "GuaranteedUpdate etcd3" type:*v1.Endpoints (started: 2020-07-07 19:58:47.694802514 +0000 UTC m=+2119.356328930) (total time: 790.007814ms):
Trace[1353846683]: [334.454046ms] [334.454046ms] initial value restored
Trace[1353846683]: [550.463989ms] [216.009943ms] Transaction prepared
Trace[1353846683]: [788.267576ms] [237.803587ms] Transaction committed
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x1093f46, 0x16)
	/usr/local/go/src/runtime/panic.go:617 +0x72
runtime.sysMap(0xc014000000, 0x4000000, 0x1ac3638)
	/usr/local/go/src/runtime/mem_linux.go:170 +0xc7
runtime.(*mheap).sysAlloc(0x1aaaca0, 0x242000, 0x1aaacb0, 0x121)
	/usr/local/go/src/runtime/malloc.go:633 +0x1cd
runtime.(*mheap).grow(0x1aaaca0, 0x121, 0x0)
	/usr/local/go/src/runtime/mheap.go:1222 +0x42
runtime.(*mheap).allocSpanLocked(0x1aaaca0, 0x121, 0x1ac3648, 0xc00006df40)
	/usr/local/go/src/runtime/mheap.go:1150 +0x37f
runtime.(*mheap).alloc_m(0x1aaaca0, 0x121, 0x420101, 0xc000147648)
	/usr/local/go/src/runtime/mheap.go:977 +0xc2
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:1048 +0x4c
runtime.(*mheap).alloc(0x1aaaca0, 0x121, 0xc000010101, 0xc00bcb3380)
	/usr/local/go/src/runtime/mheap.go:1047 +0x8a
runtime.largeAlloc(0x2400b2, 0x101, 0x1)
	/usr/local/go/src/runtime/malloc.go:1055 +0x99
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:950 +0x46
runtime.systemstack(0xc00019a1c0)
	/usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1153

goroutine 38412 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc00aba1368 sp=0xc00aba1360 pc=0x45ac10
runtime.mallocgc(0x2400b2, 0xed6c20, 0x101, 0xc00ffedb00)
	/usr/local/go/src/runtime/malloc.go:949 +0x872 fp=0xc00aba1408 sp=0xc00aba1368 pc=0x40c142
runtime.makeslice(0xed6c20, 0x2400b2, 0x2400b2, 0xc00aba1480)
	/usr/local/go/src/runtime/slice.go:49 +0x6c fp=0xc00aba1438 sp=0xc00aba1408 pc=0x44402c
go.etcd.io/etcd/etcdserver/etcdserverpb.(*RangeResponse).Marshal(0xc00b5954a0, 0x126e340, 0xc00b5954a0, 0x7f502f04e748, 0xc00b5954a0, 0xc00b595401)
	/tmp/etcd-release-3.4.3/etcd/release/etcd/etcdserver/etcdserverpb/rpc.pb.go:5262 +0x4e fp=0xc00aba1490 sp=0xc00aba1438 pc=0x9d231e
github.com/golang/protobuf/proto.Size(0x126e340, 0xc00b5954a0, 0x0)
	/home/ec2-user/go/pkg/mod/github.com/golang/protobuf@v1.3.2/proto/table_marshal.go:2697 +0xfc fp=0xc00aba14d0 sp=0xc00aba1490 pc=0x76b99c
go.etcd.io/etcd/etcdserver.warnOfExpensiveReadOnlyRangeRequest(0x0, 0xbfb952df5f9766f2, 0x1ef59215e2d, 0x1aa2f00, 0x1254f60, 0xc00ba53f10, 0xc00b5954a0, 0x0, 0x0)
	/tmp/etcd-release-3.4.3/etcd/release/etcd/etcdserver/util.go:135 +0x11c fp=0xc00aba1578 sp=0xc00aba14d0 pc=0xc2005c
go.etcd.io/etcd/etcdserver.(*EtcdServer).Range.func1(0xc0000d2000, 0xc00ba53f10, 0xc00aba1680, 0xc00aba16b0, 0xc00ba53f80, 0xbfb952df5f9766f2, 0x1ef59215e2d, 0x1aa2f00)
	/tmp/etcd-release-3.4.3/etcd/release/etcd/etcdserver/v3_server.go:100 +0xb7 fp=0xc00aba1618 sp=0xc00aba1578 pc=0xc30c97
go.etcd.io/etcd/etcdserver.(*EtcdServer).Range(0xc0000d2000, 0x1274bc0, 0xc00b595440, 0xc00ba53f10, 0xc00b5954a0, 0x0, 0x0)
	/tmp/etcd-release-3.4.3/etcd/release/etcd/etcdserver/v3_server.go:126 +0x4c5 fp=0xc00aba1748 sp=0xc00aba1618 pc=0xc22da5
go.etcd.io/etcd/etcdserver/api/v3rpc.(*kvServer).Range(0xc000468500, 0x1274bc0, 0xc00b5953b0, 0xc00ba53f10, 0xf972a0, 0xf85b00, 0x1278740)
	/tmp/etcd-release-3.4.3/etcd/release/etcd/etcdserver/api/v3rpc/key.go:52 +0x79 fp=0xc00aba1798 sp=0xc00aba1748 pc=0xcdb769
go.etcd.io/etcd/etcdserver/api/v3rpc.(*quotaKVServer).Range(0xc000468540, 0x1274bc0, 0xc00b5953b0, 0xc00ba53f10, 0xc000468540, 0x127ea00, 0xc00a052100)
	<autogenerated>:1 +0x5a fp=0xc00aba17e0 sp=0xc00aba1798 pc=0xce98aa
go.etcd.io/etcd/etcdserver/etcdserverpb._KV_Range_Handler.func1(0x1274bc0, 0xc00b5953b0, 0x10408a0, 0xc00ba53f10, 0xcd2ff4, 0xc00a052100, 0xc00b595410, 0x3)
	/tmp/etcd-release-3.4.3/etcd/release/etcd/etcdserver/etcdserverpb/rpc.pb.go:3552 +0x86 fp=0xc00aba1828 sp=0xc00aba17e0 pc=0xa21406
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1274bc0, 0xc00b5953b0, 0x10408a0, 0xc00ba53f10, 0x16, 0xc00c378e60, 0x1ac16e8, 0x1)
	/home/ec2-user/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:31 +0x111 fp=0xc00aba1890 sp=0xc00aba1828 pc=0xccf211
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x1274bc0, 0xc00b5953b0, 0x10408a0, 0xc00ba53f10, 0xc0097d3e20, 0xc00c378e10, 0xc00b595350, 0xc00e8fd760, 0x1ac16e8, 0xfb8040)
	/home/ec2-user/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0xad fp=0xc00aba1908 sp=0xc00aba1890 pc=0xcd3b5d
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1274bc0, 0xc00b5953b0, 0x10408a0, 0xc00ba53f10, 0x1ac2a00, 0x28, 0x8, 0x0)
	/home/ec2-user/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x99 fp=0xc00aba1970 sp=0xc00aba1908 pc=0xccf199
go.etcd.io/etcd/etcdserver/api/v3rpc.newUnaryInterceptor.func1(0x1274bc0, 0xc00b5953b0, 0x10408a0, 0xc00ba53f10, 0xc0097d3e20, 0xc00c378e10, 0xc00b4d4a20, 0x4b5ac6, 0x5f04d3fd, 0xc01f665305)
	/tmp/etcd-release-3.4.3/etcd/release/etcd/etcdserver/api/v3rpc/interceptor.go:64 +0x10a fp=0xc00aba19c8 sp=0xc00aba1970 pc=0xce613a
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1274bc0, 0xc00b5953b0, 0x10408a0, 0xc00ba53f10, 0x48, 0x48, 0xc00c378e10, 0x28)
	/home/ec2-user/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x99 fp=0xc00aba1a30 sp=0xc00aba19c8 pc=0xccf199
go.etcd.io/etcd/etcdserver/api/v3rpc.newLogUnaryInterceptor.func1(0x1274bc0, 0xc00b5953b0, 0x10408a0, 0xc00ba53f10, 0xc0097d3e20, 0xc00c378e10, 0x0, 0x0, 0x0, 0x0)
	/tmp/etcd-release-3.4.3/etcd/release/etcd/etcdserver/api/v3rpc/interceptor.go:71 +0xba fp=0xc00aba1af0 sp=0xc00aba1a30 pc=0xce63ba
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x1274bc0, 0xc00b5953b0, 0x10408a0, 0xc00ba53f10, 0xc0097d3e20, 0xc0097d3e40, 0xc00b4d4bd0, 0x580fda, 0xfeac00, 0xc00b5953b0)
	/home/ec2-user/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:39 +0x153 fp=0xc00aba1b70 sp=0xc00aba1af0 pc=0xccf3b3
go.etcd.io/etcd/etcdserver/etcdserverpb._KV_Range_Handler(0xf972a0, 0xc000468540, 0x1274bc0, 0xc00b5953b0, 0xc00c3fb800, 0xc00c1dd4a0, 0x1274bc0, 0xc00b5953b0, 0xc0089e1020, 0x28)
	/tmp/etcd-release-3.4.3/etcd/release/etcd/etcdserver/etcdserverpb/rpc.pb.go:3554 +0x158 fp=0xc00aba1be0 sp=0xc00aba1b70 pc=0x9c8468
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000cc2c0, 0x1284d00, 0xc00dc47080, 0xc00c358c00, 0xc00c1dd620, 0x1a94060, 0x0, 0x0, 0x0)
	/home/ec2-user/go/pkg/mod/google.golang.org/grpc@v1.23.1/server.go:995 +0x466 fp=0xc00aba1e50 sp=0xc00aba1be0 pc=0x98f406
google.golang.org/grpc.(*Server).handleStream(0xc0000cc2c0, 0x1284d00, 0xc00dc47080, 0xc00c358c00, 0x0)
	/home/ec2-user/go/pkg/mod/google.golang.org/grpc@v1.23.1/server.go:1275 +0xda6 fp=0xc00aba1f80 sp=0xc00aba1e50 pc=0x993266
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00db0cb20, 0xc0000cc2c0, 0x1284d00, 0xc00dc47080, 0xc00c358c00)
	/home/ec2-user/go/pkg/mod/google.golang.org/grpc@v1.23.1/server.go:710 +0x9f fp=0xc00aba1fb8 sp=0xc00aba1f80 pc=0x9a004f
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00aba1fc0 sp=0xc00aba1fb8 pc=0x45cb61
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/ec2-user/go/pkg/mod/google.golang.org/grpc@v1.23.1/server.go:708 +0xa1

goroutine 1 [select, 35 minutes]:
go.etcd.io/etcd/etcdmain.startEtcdOrProxyV2()
	/tmp/etcd-release-3.4.3/etcd/release/etcd/etcdmain/etcd.go:286 +0x15cd
go.etcd.io/etcd/etcdmain.Main()
	/tmp/etcd-release-3.4.3/etcd/release/etcd/etcdmain/main.go:46 +0x38
main.main()
	/tmp/etcd-release-3.4.3/etcd/release/etcd/main.go:28 +0x20

goroutine 54 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc00013e9a0)
	/tmp/etcd-release-3.4.3/etcd/release/etcd/pkg/logutil/merge_logger.go:173 +0x3a2
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
	/tmp/etcd-release-3.4.3/etcd/release/etcd/pkg/logutil/merge_logger.go:91 +0x80

goroutine 91 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc00015c580)
	/tmp/etcd-release-3.4.3/etcd/release/etcd/pkg/logutil/merge_logger.go:173 +0x3a2
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
	/tmp/etcd-release-3.4.3/etcd/release/etcd/pkg/logutil/merge_logger.go:91 +0x80

goroutine 94 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc00015c720)
	/tmp/etcd-release-3.4.3/etcd/release/etcd/pkg/logutil/merge_logger.go:173 +0x3a2
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
	/tmp/etcd-release-3.4.3/etcd/release/etcd/pkg/logutil/merge_logger.go:91 +0x80

goroutine 128 [select]:
go.etcd.io/etcd/raft.(*node).run(0xc0000784e0)
	/tmp/etcd-release-3.4.3/etcd/release/etcd/raft/node.go:337 +0x44f
created by go.etcd.io/etcd/raft.RestartNode
	/tmp/etcd-release-3.4.3/etcd/release/etcd/raft/node.go:240 +0x33c

goroutine 110 [syscall, 35 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 127 [select, 35 minutes]:
go.etcd.io/etcd/wal.(*filePipeline).run(0xc00019a280)
	/tmp/etcd-release-3.4.3/etcd/release/etcd/wal/file_pipeline.go:98 +0x138
created by go.etcd.io/etcd/wal.newFilePipeline
	/tmp/etcd-release-3.4.3/etcd/release/etcd/wal/file_pipeline.go:52 +0x122
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4-head - commit id: `fb2c5fb2d` - `v2.4-3278-head`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom windows clusters
- Kubernetes version (use `kubectl version`):

```
all k8s versions clusters were deployed.
```

**Comment by sowmyav27** [comment]
This issue is because of rancher deployed on a node with a small size of vCPU and RAM. As per docs the a rancher server running about 9 clusters should have 2 vCPU and 8 GB RAM
https://rancher.com/docs/rancher/v2.x/en/installation/requirements/#cpu-and-memory
Closing this issue.
