### ISSUE TITLE
vSphere node provisioning fails when using port groups organized in folders

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#27908]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. In a vSphere datacenter (e.g. `dc-01`) create a new "network folder" in the inventory, e.g. named `dvs-group-folder`
2. Within that folder create a distributed vSwitch, e.g. named `dvs-001`
3. Create a network/port group on the switch, e.g. named `dvs-001-pg-01`
4. The resulting absolute path of the network will be:    
`/dc-01/network/dvs-group-folder/dvs-001/dvs-001-pg-01`
5. Create a vSphere node template in Rancher selecting the network `dvs-001-pg-01` from the list
6. Create a cluster using that node template

**Result:**
Cluster is not created. Node provisioning fails with the following error in the GUI and Rancher logs:

> [Error with pre-create check: "unexpected EOF"]
> Wrapper Docker Machine process exiting due to closed plugin server (connection is shut down)

**Other details that may be helpful:**
Trying to reproduce the issue using the `rancher-machine` command line tools results in the  process to crash with a panic:

```
Running pre-create checks...
(test3) Calling .PreCreateCheck
(test3) DBG | Connecting to vSphere for pre-create checks...
(test3) DBG | panic: reflect.Value.Addr of unaddressable value
(test3) DBG |
(test3) DBG | goroutine 12 [running]:
(test3) DBG | reflect.Value.Addr(0x19b5f00, 0xc00031e980, 0x16, 0x2130500, 0x19eca80, 0x16)
(test3) DBG |   /usr/local/go/src/reflect/value.go:258 +0x96
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000113800, 0x19eca80, 0xc00031e940, 0x194, 0xc00031e900, 0xc00031e940, 0x194)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:347 +0x2f43
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000113800, 0x17f3100, 0xc0003163e8, 0x197, 0xc00031e900, 0xc0003163e8, 0x197)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:442 +0x241d
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc000113800, 0xc0002ec2c0, 0x1c99f40, 0xc0003163c0, 0x199, 0x0, 0x0, 0x0, 0xc00031e900, 0x1, ...)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:716 +0x633
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000113800, 0x1c99f40, 0xc0003163c0, 0x199, 0xc00031e600, 0xc0003163c0, 0x199)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:547 +0x1097
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000113800, 0x17f4e80, 0xc0002eada0, 0x197, 0xc00031e600, 0xc0002eada0, 0x197)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:442 +0x241d
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc000113800, 0xc0002ec140, 0x1c2c5a0, 0xc0002ead80, 0x199, 0x0, 0x0, 0x0, 0xc00031e600, 0xffffffffff01, ...)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:716 +0x633
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000113800, 0x1945ec0, 0xc0004bea70, 0x196, 0xc0002ead40, 0xc0004bea70, 0x196)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:547 +0x1097
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc000113800, 0xc0002e3f00, 0x1ac7700, 0xc0004bea20, 0x199, 0x0, 0x0, 0x0, 0xc0002ead40, 0x203001, ...)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:716 +0x633
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000113800, 0x1ac7700, 0xc0004bea20, 0x199, 0xc0002ea9c0, 0x199, 0x1ac7700)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:547 +0x1097
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000113800, 0x19eca00, 0xc0002eaa40, 0x194, 0xc0002ea9c0, 0xc0002eaa40, 0x194)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:335 +0x2ebb
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000113800, 0x17f30c0, 0xc0002e3e48, 0x197, 0xc0002ea9c0, 0xc0002e3e48, 0x197)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:442 +0x241d
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc000113800, 0xc000280ac0, 0x1ac6b20, 0xc0002e3e40, 0x199, 0x0, 0x0, 0x0, 0xc0002ea9c0, 0xffffffffff01, ...)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:716 +0x633
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000113800, 0x19b5d80, 0xc000412db0, 0x196, 0xc0002ea840, 0xc000412db0, 0x196)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:547 +0x1097
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc000113800, 0xc0004bd820, 0x1cf73a0, 0xc000412d80, 0x199, 0x0, 0x0, 0x0, 0xc0002ea840, 0x1, ...)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:716 +0x633
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000113800, 0x1cf73a0, 0xc000412d80, 0x199, 0xc0002e6a40, 0x199, 0x1cf73a0)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:547 +0x1097
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000113800, 0x19d7a80, 0xc00010c650, 0x194, 0xc0002e6a40, 0xc00010c650, 0x194)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:335 +0x2ebb
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc000113800, 0xc0004bd480, 0x1d54f80, 0xc00010c620, 0x199, 0x0, 0x0, 0x0, 0xc0002e6a40, 0xc0004e1201, ...)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:716 +0x633
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000113800, 0x1d54f80, 0xc00010c620, 0x199, 0xc0002e6680, 0x199, 0x1d54f80)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:547 +0x1097
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000113800, 0x199cac0, 0xc000412d50, 0x194, 0xc0002e6680, 0xc000412d50, 0x194)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:335 +0x2ebb
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc000113800, 0xc0004c6560, 0x1ac7b60, 0xc000412d40, 0x199, 0x0, 0x0, 0x0, 0xc0002e6680, 0x17f3801, ...)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:716 +0x633
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000113800, 0x1ac7b60, 0xc000412d40, 0x199, 0xc0002e6500, 0xc000412d40, 0x199)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:547 +0x1097
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000113800, 0x17f4f80, 0xc00012e610, 0x197, 0xc0002e6500, 0xc00012e610, 0x197)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:442 +0x241d
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc000113800, 0xc0004c6460, 0x1bd55a0, 0xc00012e5f0, 0x199, 0x0, 0x0, 0x0, 0xc0002e6500, 0xc0004e2701, ...)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:716 +0x633
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000113800, 0x1bd55a0, 0xc00012e5f0, 0x199, 0xc0002e1180, 0xc00012e5f0, 0x199)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:547 +0x1097
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000113800, 0x17f8440, 0xc0004bc7a0, 0x197, 0xc0002e1180, 0xc0004bc7a0, 0x197)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:442 +0x241d
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc000113800, 0xc0004c6400, 0x1a5ef80, 0xc0004bc7a0, 0x199, 0x0, 0x0, 0x0, 0xc0002e1180, 0xffffffffff01, ...)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:716 +0x633
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000113800, 0x17b50e0, 0xc00025c1c8, 0x196, 0xc0004c5480, 0xc00025c1c8, 0x196)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:547 +0x1097
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc000113800, 0xc00044ba40, 0x1b508a0, 0xc00025c1c0, 0x199, 0x0, 0x0, 0x0, 0xc0004c5480, 0x7, ...)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:716 +0x633
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000113800, 0x191d7a0, 0xc000230ea8, 0x194, 0xc0004c5340, 0xc000230ea8, 0x194)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:547 +0x1097
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc000113800, 0xc00044a640, 0x1b52ca0, 0xc000230e80, 0x199, 0x0, 0x0, 0x0, 0xc0004c5340, 0xbfba3aa50a02b991, ...)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:716 +0x633
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000113800, 0x1b52ca0, 0xc000230e80, 0x199, 0xc0004c5240, 0x199, 0x0)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:547 +0x1097
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).DecodeElement(0xc000113800, 0x178d0e0, 0xc000230e80, 0x0, 0xc0004c4fc0, 0xbac0710)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:133 +0x12b
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml.(*Decoder).Decode(...)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/xml/read.go:121
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/soap.(*Client).RoundTrip.func1(0xc0000fa510, 0x65670fe, 0x311bd80)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/soap/client.go:595 +0xea
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/soap.(*Client).Do(0xc0001da790, 0x210d000, 0xc00033c870, 0xc000124800, 0xc0004e43e0, 0x0, 0x0)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/soap/client.go:518 +0x2ce
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/soap.(*Client).RoundTrip(0xc0001da790, 0x210cf80, 0xc0000aa078, 0x20e58a0, 0xc00025c1a0, 0x20e58a0, 0xc00025c1c0, 0x417a01, 0xc00025c1c0)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/soap/client.go:583 +0x92a
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25.(*Client).RoundTrip(0xc0001fadc0, 0x210cf80, 0xc0000aa078, 0x20e58a0, 0xc00025c1a0, 0x20e58a0, 0xc00025c1c0, 0x40, 0x1ae7460)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/client.go:120 +0x80
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/methods.RetrieveProperties(0x210cf80, 0xc0000aa078, 0x20e44c0, 0xc0001fadc0, 0xc000230e40, 0x203000, 0x8, 0x203000)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/vim25/methods/methods.go:13799 +0xb8
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/property.(*Collector).RetrieveProperties(0xc000460600, 0x210cf80, 0xc0000aa078, 0x0, 0x0, 0x0, 0x0, 0xc000230e00, 0x1, 0x1, ...)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/property/collector.go:122 +0xf6
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/list.Lister.retrieveProperties(0xc000460600, 0xc0004c0910, 0x6, 0xc0004c0960, 0xb, 0xc0004f3340, 0x1b, 0x1, 0x210cf80, 0xc0000aa078, ...)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/list/lister.go:120 +0x8e
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/list.Lister.ListFolder(0xc000460600, 0xc0004c0910, 0x6, 0xc0004c0960, 0xb, 0xc0004f3340, 0x1b, 0x1, 0x210cf80, 0xc0000aa078, ...)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/list/lister.go:234 +0x463
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/list.Lister.List(0xc000460600, 0xc0004c0910, 0x6, 0xc0004c0960, 0xb, 0xc0004f3340, 0x1b, 0x1, 0x210cf80, 0xc0000aa078, ...)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/list/lister.go:155 +0xd0
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/find.recurser.List(0xc000460600, 0x1, 0x210cf80, 0xc0000aa078, 0xc000309870, 0xc0004f3340, 0x1b, 0x20e8840, 0xc0004241a0, 0xc0000bc090, ...)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/find/recurser.go:171 +0x1b7
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/find.recurser.List(0xc000460600, 0x1, 0x210cf80, 0xc0000aa078, 0xc000309870, 0xc00003afc0, 0x12, 0x20e8840, 0xc000094680, 0xc0000bc080, ...)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/find/recurser.go:202 +0x5f6
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/find.recurser.List(0xc000460600, 0x1, 0x210cf80, 0xc0000aa078, 0xc000309870, 0xc000046b80, 0xa, 0x20e87c0, 0xc0000d9200, 0xc0000bc070, ...)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/find/recurser.go:202 +0x5f6
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/find.recurser.List(0xc000460600, 0x210cf01, 0x210cf80, 0xc0000aa078, 0xc000309870, 0x1d9f676, 0x1, 0x20e4280, 0xc000120cc0, 0xc0000bc060, ...)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/find/recurser.go:202 +0x5f6
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/find.(*Finder).find(0xc000460630, 0x210cf80, 0xc0000aa078, 0xc000041000, 0x32, 0xc0004e5870, 0x8, 0x0, 0x8, 0x0, ...)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/find/finder.go:144 +0x612
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/find.(*Finder).NetworkList(0xc000460630, 0x210cf80, 0xc0000aa078, 0xc000041000, 0x32, 0x9, 0xc0000ae020, 0x1, 0x1, 0x0)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/find/finder.go:754 +0x115
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/find.(*Finder).Network(0xc000460630, 0x210cf80, 0xc0000aa078, 0xc000041000, 0x32, 0x9, 0xc000120c80, 0x0, 0x0)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/find/finder.go:790 +0x5a
(test3) DBG | github.com/rancher/machine/vendor/github.com/vmware/govmomi/find.(*Finder).NetworkOrDefault(0xc000460630, 0x210cf80, 0xc0000aa078, 0xc000041000, 0x32, 0xc000120c80, 0x0, 0x0, 0xc000134000)
(test3) DBG |   /go/src/github.com/rancher/machine/vendor/github.com/vmware/govmomi/find/finder.go:813 +0x60
(test3) DBG | github.com/rancher/machine/drivers/vmwarevsphere.(*Driver).preCreate(0xc0003f4500, 0xc00031bee0, 0x1)
(test3) DBG |   /go/src/github.com/rancher/machine/drivers/vmwarevsphere/create.go:32 +0x20f
(test3) DBG | github.com/rancher/machine/drivers/vmwarevsphere.(*Driver).PreCreateCheck(0xc0003f4500, 0x7f7708ce4008, 0x0)
(test3) DBG |   /go/src/github.com/rancher/machine/drivers/vmwarevsphere/vsphere.go:245 +0x99
(test3) DBG | github.com/rancher/machine/libmachine/drivers/rpc.(*RPCServerDriver).PreCreateCheck(0xc00000db00, 0x3138da8, 0x3138da8, 0x0, 0x0)
(test3) DBG |   /go/src/github.com/rancher/machine/libmachine/drivers/rpc/server_driver.go:201 +0x33
(test3) DBG | reflect.Value.call(0xc000079200, 0xc00000e608, 0x13, 0x1da0135, 0x4, 0xc00008df18, 0x3, 0x3, 0x0, 0x0, ...)
(test3) DBG |   /usr/local/go/src/reflect/value.go:460 +0x5f6
(test3) DBG | reflect.Value.Call(0xc000079200, 0xc00000e608, 0x13, 0xc00005d718, 0x3, 0x3, 0x0, 0x0, 0x0)
(test3) DBG |   /usr/local/go/src/reflect/value.go:321 +0xb4
(test3) DBG | net/rpc.(*service).call(0xc000121400, 0xc000128000, 0xc0000aa780, 0xc0000aa790, 0xc000123780, 0xc00009f840, 0x17dbea0, 0x3138da8, 0x16, 0x17dbea0, ...)
(test3) DBG |   /usr/local/go/src/net/rpc/server.go:377 +0x16f
(test3) DBG | created by net/rpc.(*Server).ServeCodec
(test3) DBG |   /usr/local/go/src/net/rpc/server.go:474 +0x42b
Error with pre-create check: "unexpected EOF"
The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.

notifying bugsnag: [Error with pre-create check: "unexpected EOF"]
Wrapper Docker Machine process exiting due to closed plugin server (connection is shut down)
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by maggieliu** [comment]
As per Jan: UI is stripping an element from the network path while saving the template, rendering the configuration invalid.
That bug should normally cause the provisioning to fail with an error such as "invalid network". Instead, the invalid network configuration triggers another bug in the machine driver plugin itself (probably NPE) that causes the plugin to crash and results in a different error in the GUI that masks the invalid network issue.

**Comment by codyrancher** [comment]
Within our vsphere environment it's not actually straight forward to create the network folders or vswitches so it's a little difficult to reproduce at the moment.

However, on the frontend I did mock out the response we get back from the `/meta/vsphere/networks` api and the frontend posts the exact value returned from the backend when creating the node template. So I believe this needs to be rerouted to the backend.

Mocked response data:
![Screen Shot 2020-12-17 at 3.49.02 PM.png](https://zube.io/files/rancher/cb8988137cb37973acae14653cf640ed-screen-shot-2020-12-17-at-3-49-02-pm.png)

What the frontend posts to the backend when creating the template:
![Screen Shot 2020-12-17 at 3.49.42 PM.png](https://zube.io/files/rancher/03ee8a989cd00bbe69247c9d1852ca19-screen-shot-2020-12-17-at-3-49-42-pm.png)

**Comment by ryansann** [comment]
I can provide some further information after having conducted an initial investigation on this issue:

- Values populated in the network dropdown on the vSphere node template come from the `/meta/vsphere/networks` endpoint, however this api just wraps calls to the govmomi package. This implies that the wrong value being returned is originating in govmomi.
- Panic coming from `rancher-machine create` is also originating in the govmomi package- specifically, while reading an XML response from vSphere.
- Attempted to reproduce the rancher-machine panic by providing an invalid network path, which did not cause a panic. Rather, I got the error: `Error with pre-create check: network not found`
- There is a related issue on the govmomi side that looks to be addressing this panic. That issue is here: https://github.com/vmware/govmomi/issues/1812 and is also related to port groups. A fix for the issue looks to be merged, but it won't be released until govmomi `v0.25.0` (latest release is currently `v0.24.0`)
- The most straightforward path to fixing this looks to be upgrading govmomi to `v0.25.0` when it is released

**Comment by mitchellmaler** [comment]
@deniseschannon @luthermonson Just ran into this same issue. We have deployed clusters in our vSphere Dev environment without an issue and now moving up to STG. All using Rancher 2.5.8.
It looks like https://github.com/vmware/govmomi/pull/2219 has been merged and govmomi v0.26.0 has been released which 0.25.0 includes the fix from the above MR.

When do you think the version of govmomi can be upgraded in rancher/machine?

**Comment by mitchellmaler** [comment]
@ryansann I just tried using the new version of rancher-machine but instead of ending up with that panic it is now just hanging. Switching back to rancher62 and providing the network/folder info ends up with the panic like above.

```
rancher-machine \
  --debug \
  create \
  --driver vmwarevsphere \
  --vmwarevsphere-username "" \
  --vmwarevsphere-password "" \
  --vmwarevsphere-vcenter "" \
  mitch-test1

Docker Machine Version:  v0.15.0-rancher62, build 1baf1d64
Found binary path at /usr/bin/rancher-machine
Launching plugin server for driver vmwarevsphere
Plugin server listening at address 127.0.0.1:44824
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at /usr/bin/rancher-machine
Launching plugin server for driver vmwarevsphere
Plugin server listening at address 127.0.0.1:44917
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(mitch-test1) Calling .GetMachineName
(mitch-test1) Calling .DriverName
(mitch-test1) Calling .GetCreateFlags
(mitch-test1) Calling .GetCreateFlags
(mitch-test1) Calling .SetConfigFromFlags
Reading certificate data from /root/.docker/machine/certs/ca.pem
Decoding PEM data...
Parsing certificate...
Reading certificate data from /root/.docker/machine/certs/cert.pem
Decoding PEM data...
Parsing certificate...
Running pre-create checks...
(mitch-test1) Calling .PreCreateCheck
(mitch-test1) Connecting to vSphere for pre-create checks...

...removed some logs and showing the last entry here where it hangs

(mitch-test-1) DBG | Host: OMITTED:443
(mitch-test-1) DBG | Content-Type: text/xml; charset="utf-8"
(mitch-test-1) DBG | Soapaction: urn:vim25/7.0
(mitch-test-1) DBG |
(mitch-test-1) DBG | <?xml version="1.0" encoding="UTF-8"?>
(mitch-test-1) DBG | <Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/"><Body><RetrieveProperties xmlns="urn:vim25"><_this type="PropertyCollector">propertyCollector</_this><specSet><propSet><type>Folder</type><all>true</all></propSet><propSet><type>Datacenter</type><all>true</all></propSet><propSet><type>VirtualApp</type><all>true</all></propSet><propSet><type>VirtualMachine</type><all>true</all></propSet><propSet><type>Network</type><all>true</all></propSet><propSet><type>ComputeResource</type><all>true</all></propSet><propSet><type>ClusterComputeResource</type><all>true</all></propSet><propSet><type>Datastore</type><all>true</all></propSet><propSet><type>DistributedVirtualSwitch</type><all>true</all></propSet><objectSet><obj type="Folder">group-d1</obj><skip>true</skip><selectSet xmlns:XMLSchema-instance="http://www.w3.org/2001/XMLSchema-instance" XMLSchema-instance:type="TraversalSpec"><type>Folder</type><path>childEntity</path><skip>false</skip></selectSet></objectSet></specSet></RetrieveProperties></Body></Envelope>2021-07-12T18-39-25.689872685 - 0003:     10ms (*methods.RetrievePropertiesBody)
(mitch-test-1) DBG | HTTP/1.1 200 OK
(mitch-test-1) DBG | Transfer-Encoding: chunked
(mitch-test-1) DBG | Cache-Control: no-cache
(mitch-test-1) DBG | Connection: Keep-Alive
(mitch-test-1) DBG | Content-Type: text/xml; charset=utf-8
(mitch-test-1) DBG | Date: Mon, 12 Jul 2021 18:39:57 GMT
(mitch-test-1) DBG |
(mitch-test-1) DBG | <?xml version="1.0" encoding="UTF-8"?>
(mitch-test-1) DBG | <soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
(mitch-test-1) DBG |  xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
(mitch-test-1) DBG |  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
(mitch-test-1) DBG |  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
(mitch-test-1) DBG | <soapenv:Body>
```

**Comment by deniseschannon** [comment]
@mitchellmaler Have you filed a ticket with govmomi? All we had done was a vendor bump and it doesnt' seem to have fixed your issue.

**Comment by mitchellmaler** [comment]
Just logged it https://github.com/vmware/govmomi/issues/2518

**Comment by thedadams** [comment]
The update to rancher-machine was reverted for now because of the hang issue.

**Comment by deniseschannon** [comment]
The hang issue affected all vsphere deployments, not just this use case.

**Comment by Oats87** [comment]
I figured out what the hang issue is, and filed an upstream PR to fix it. I have also opened a PR into rancher/machine that upgrades govmomi to a version that should resolve the issue reported in this issue.

See: https://github.com/rancher/rancher/issues/41133 and https://github.com/rancher/machine/pull/205 for the machine related issue/PR, and see: https://github.com/vmware/govmomi/issues/3099 for the upstream issue

**Comment by markusewalker** [comment]
@Sahota1225 will confirm the milestone for this issue.

**Comment by snasovich** [comment]
@markusewalker @Sahota1225 , the fix will likely be in as part of https://github.com/rancher/machine/pull/205 as it's believed all we need is to bump `govmomi` dependency.
If there is no capacity to test it, it's fine to kick it to the next milestone. But we can't not do the change as it's needed for another issue linked on that PR.
cc: @sowmyav27
