### ISSUE TITLE
'Connection refused' when trying to run agent on same machine as server

### ISSUE THREAD

**Issue by gvd** [rancher/rancher#2794]
When running the agent on the same machine as the server I keep getting a 'Connection refused' error, even when specifying the CATTLE_AGENT_IP

```
sudo docker run --privileged -e CATTLE_AGENT_IP=172.17.0.1 -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.8.2 http://172.17.0.1:8080/v1/scripts/8B87B7DF4CE894907BF7:1448337600000:diIqUTiYxRpxhIyXFqpxDzX5qU
```
or
```
sudo docker run --privileged -e CATTLE_AGENT_IP=10.0.0.8 -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.8.2 http://10.0.0.8:8080/v1/scripts/8B87B7DF4CE894907BF7:1448337600000:diIqUTiYxRpxhIyXFqpxDzX5qU
```

This is the agent log output:

```
INFO: Running Agent Registration Process, CATTLE_URL=http://10.0.0.8:8080/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.9.1
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.9.1
INFO: docker version: Server API version: 1.21
INFO: docker version: Go version (server): go1.4.2
INFO: docker version: Git commit (server): a34a1d5
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker info: Containers: 15
INFO: docker info: Images: 2436
INFO: docker info: Storage Driver: aufs
INFO: docker info: Root Dir: /var/lib/docker/aufs
INFO: docker info: Backing Filesystem: extfs
INFO: docker info: Dirs: 2474
INFO: docker info: Dirperm1 Supported: true
INFO: docker info: Execution Driver: native-0.2
INFO: docker info: Kernel Version: 3.19.0-33-generic
INFO: docker info: Operating System: Ubuntu 15.04
INFO: docker info: CPUs: 8
INFO: docker info: Total Memory: 15.61 GiB
INFO: docker info: Name: xxxxxxx
INFO: docker info: ID: VDGY:42VV:UGYP:F7FF:QRWY:S4VG:CJ5Q:FPXA:I6JO:BJJ3:GCCI:I2MU
WARNING: No swap limit support
INFO: docker info: Http Proxy:
INFO: docker info: Https Proxy:
INFO: docker info: No Proxy:
INFO: Attempting to connect to: http://10.0.0.8:8080/v1
INFO: http://10.0.0.8:8080/v1 is accessible
INFO: Inspecting host capabilities
INFO: System: true
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
Traceback (most recent call last):
  File "./register.py", line 11, in <module>
    secret_key=os.environ['CATTLE_REGISTRATION_SECRET_KEY'])
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 37, in from_env
    return gdapi.from_env(prefix=prefix, factory=Client, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 608, in from_env
    return _from_env(prefix=prefix, factory=factory, **args)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 627, in _from_env
    return factory(**result)
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 12, in __init__
    super(Client, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 195, in __init__
    self._load_schemas()
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 313, in _load_schemas
    response = self._get_response(self._url)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 262, in _get_response
    headers=self._headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
```

**Comment by gvd** [comment]
I just was able to start an agent. I'm not 100% sure what actions resulted in it passing this time. I did stop the rancher server, removed the container, and started a new rancher server.

**Comment by deniseschannon** [comment]
Please re-open if you run into it again, but it sounds like it was a connection issue at the time.

**Comment by gunnarstolz** [comment]
Unfortunately I'm having the same issue here. Scenario is the same, one VM as host and agent. Can this be reopened again?

**Comment by deniseschannon** [comment]
@gunnarstolz Can you open a new issue with details on your setup and specific server logs?
