### ISSUE TITLE
Error in console when creating an AWS node template

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28141]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Go to Node template --> Create a Node template
- Enter AWS access key and secret key (create a cloud credential)
- Click on Save/Next
- Error in console:
- User is able to go to the next page though and create a node template successfully
```
component.js:501 UnknownError: 502
    at constructor.extractError (https://releases.rancher.com/ui/latest-2.4/assets/vendor.js:8939:17)
    at constructor.callListeners (https://releases.rancher.com/ui/latest-2.4/assets/vendor.js:8844:7)
    at constructor.emit (https://releases.rancher.com/ui/latest-2.4/assets/vendor.js:8841:13)
    at constructor.emitEvent (https://releases.rancher.com/ui/latest-2.4/assets/vendor.js:8718:219)
    at constructor.e (https://releases.rancher.com/ui/latest-2.4/assets/vendor.js:8700:29)
    at r.runTo (https://releases.rancher.com/ui/latest-2.4/assets/vendor.js:8723:6)
    at https://releases.rancher.com/ui/latest-2.4/assets/vendor.js:8726:3
    at constructor.<anonymous> (https://releases.rancher.com/ui/latest-2.4/assets/vendor.js:8702:6)
    at constructor.<anonymous> (https://releases.rancher.com/ui/latest-2.4/assets/vendor.js:8718:274)
    at constructor.callListeners (https://releases.rancher.com/ui/latest-2.4/assets/vendor.js:8844:113) "UnknownError: 502
    at constructor.extractError (https://releases.rancher.com/ui/latest-2.4/assets/vendor.js:8939:17)
    at constructor.callListeners (https://releases.rancher.com/ui/latest-2.4/assets/vendor.js:8844:7)
    at constructor.emit (https://releases.rancher.com/ui/latest-2.4/assets/vendor.js:8841:13)
    at constructor.emitEvent (https://releases.rancher.com/ui/latest-2.4/assets/vendor.js:8718:219)
    at constructor.e (https://releases.rancher.com/ui/latest-2.4/assets/vendor.js:8700:29)
    at r.runTo (https://releases.rancher.com/ui/latest-2.4/assets/vendor.js:8723:6)
    at https://releases.rancher.com/ui/latest-2.4/assets/vendor.js:8726:3
    at constructor.<anonymous> (https://releases.rancher.com/ui/latest-2.4/assets/vendor.js:8702:6)
    at constructor.<anonymous> (https://releases.rancher.com/ui/latest-2.4/assets/vendor.js:8718:274)
    at constructor.callListeners (https://releases.rancher.com/ui/latest-2.4/assets/vendor.js:8844:113)"
```

- Rancher logs show:
```
2020/07/29 16:41:21 [INFO] Failed to proxy: invalid host: kms.us-east-2.amazonaws.com
2020/07/29 16:41:21 http: proxy error: unsupported protocol scheme ""
2020/07/29 16:41:52 http: proxy error: unsupported protocol scheme ""
2020/07/29 16:41:52 [INFO] Failed to proxy: invalid host: kms.us-east-2.amazonaws.com
```

- Also the KMS keys dropdown while creating the node template is "Empty" (when `Encrypt EBS Volume` is True)

**Expected Result:**
No error should be seen on the console

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4-head latest - commit id: `6708cf9f1` ui tag: `latest-2.4`
- Installation option (single install/HA): Single

**Comment by westlywright** [comment]
This is not a UI bug. The proxy is having an issue talking to the KMS endpoint OR you do not have permissions to access KMS keys which is why you can still proceed.

**Comment by sowmyav27** [comment]
**Verified on 2.4-head commit id: 0a219c19e ui tag: latest-2.4**

- Go to Node template --> Create a Node template
- Enter AWS access key and secret key (create a cloud credential)
- Click on Save/Next
- No error is seen in console.
- User is able to list KMS keys in the dropdown in the Instance page in the node template
