### ISSUE TITLE
Panic in rancher server and never recovers

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#28193]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Not sure on the exact steps, but I noticed it happen after this:
1. Deploy HA on master-head
2. Enable ECM
3. Import RKE2 cluster - 3 servers 3 agents
4. Attempt to upgrade RKE2 cluster (from alpha22 to beta1)
5. After master nodes upgraded, agent nodes failed to upgrade.
6. Attempted to update a label on one of the agent nodes using Rancher UI

**Result:**
Shortly afterwards I refreshed the screen and noticed a 503 Service Temporarily Unavailable page.
Navigating to the nodes and checking the pods and logs, I see the cert-manager-cainjector pod has 11 restarts but appeared to be running fine after those.
The rancher pods were consistently restarting and in CrashLoopBackOff states. In tailing their logs, I noticed a panic:

```

2020/07/31 20:01:28 [INFO] Starting /v1, Kind=ResourceQuota controller
2020/07/31 20:01:28 [INFO] Starting apps/v1, Kind=ReplicaSet controller
2020/07/31 20:01:28 [INFO] Starting /v1, Kind=Service controller
2020/07/31 20:01:28 [INFO] Starting networking.k8s.io/v1, Kind=NetworkPolicy controller
2020/07/31 20:01:28 [INFO] Starting /v1, Kind=ServiceAccount controller
E0731 20:01:28.436500       6 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 6272 [running]:
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3afa480, 0x7496500)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x3afa480, 0x7496500)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer.(*nodesSyncer).syncTaints(0xc004c42540, 0xc0026eeb80, 0x15, 0xc00960d680, 0xc000270700, 0x7efeaa064008, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer/nodetaints.go:34 +0x123
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*nodeController).AddHandler.func1(0xc0026eeb80, 0x15, 0x4316680, 0xc00960d680, 0xc005f07ad0, 0x3, 0x3, 0x0)
	/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_node_controller.go:150 +0x63
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).AddHandler.func1(0xc0026eeb80, 0x15, 0x4c62960, 0xc00960d680, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:57 +0x1e1
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc0041b5320, 0xc0026eeb80, 0x15, 0x4c62960, 0xc00960d680, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*sharedHandler).OnChange(0xc001001770, 0xc0026eeb80, 0x15, 0x4c62960, 0xc00960d680, 0x42e901, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/sharedhandler.go:65 +0x150
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc0008c2b00, 0xc0026eeb80, 0x15, 0xc0079bbb30, 0xc005f07d30)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:211 +0xd1
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0008c2b00, 0x37f96e0, 0xc0089c8000, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:193 +0xf0
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0008c2b00, 0x40c501)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:170 +0x51
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc0008c2b00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:159 +0x2b
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0032395a0)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5e
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0032395a0, 0x4c23900, 0xc0079bbe60, 0xc00454c601, 0xc0027ef260)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0032395a0, 0x3b9aca00, 0x0, 0x1, 0xc0027ef260)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0xe2
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0032395a0, 0x3b9aca00, 0xc0027ef260)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:130 +0x35e
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x168 pc=0x270fab3]

goroutine 6272 [running]:
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x3afa480, 0x7496500)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer.(*nodesSyncer).syncTaints(0xc004c42540, 0xc0026eeb80, 0x15, 0xc00960d680, 0xc000270700, 0x7efeaa064008, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer/nodetaints.go:34 +0x123
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*nodeController).AddHandler.func1(0xc0026eeb80, 0x15, 0x4316680, 0xc00960d680, 0xc005f07ad0, 0x3, 0x3, 0x0)
	/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_node_controller.go:150 +0x63
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).AddHandler.func1(0xc0026eeb80, 0x15, 0x4c62960, 0xc00960d680, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:57 +0x1e1
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc0041b5320, 0xc0026eeb80, 0x15, 0x4c62960, 0xc00960d680, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*sharedHandler).OnChange(0xc001001770, 0xc0026eeb80, 0x15, 0x4c62960, 0xc00960d680, 0x42e901, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/sharedhandler.go:65 +0x150
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc0008c2b00, 0xc0026eeb80, 0x15, 0xc0079bbb30, 0xc005f07d30)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:211 +0xd1
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0008c2b00, 0x37f96e0, 0xc0089c8000, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:193 +0xf0
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0008c2b00, 0x40c501)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:170 +0x51
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc0008c2b00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:159 +0x2b
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0032395a0)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5e
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0032395a0, 0x4c23900, 0xc0079bbe60, 0xc00454c601, 0xc0027ef260)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0032395a0, 0x3b9aca00, 0x0, 0x1, 0xc0027ef260)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0xe2
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0032395a0, 0x3b9aca00, 0xc0027ef260)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:130 +0x35e
```

- Rancher Version: `5c1c2c5d7`
- HA install
- kubectl version: 1.18

**Additional Info:**
- This server was around for 24 hours before this happened and had been working fine, which makes me think it's related to the steps I mentioned above.
- Rancher server never recovered.

**Comment by rmweir** [comment]
Possibly related: https://github.com/rancher/rancher/issues/28191

**Comment by rancher-max** [comment]
- Unable to recreate this anymore using rancher master-head commit: `f1a410a`
- Tried throughout the day with different settings and upgrades in rke2 cluster to reproduce and was unable to
- Did not reproduce after leaving setup around overnight with unavailable agent nodes

Therefore, I believe this to be fixed.
