### ISSUE TITLE
Panic in rancher server causing rancher to restart

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28191]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a HA on master-head.
- Enable ECM
- Deploy an eks cluster
- Noticed Rancher restart
- Server logs:

```
2020/07/31 18:23:40 [INFO] Updating clusterRoleBinding clusterrolebinding-lkm6p for project access to global resource for subject u-zjjfk role project-owner-promoted.
2020/07/31 18:23:40 [INFO] Updating clusterRoleBinding clusterrolebinding-lkm6p for project access to global resource for subject u-zjjfk role project-owner-promoted.
2020/07/31 18:23:40 [INFO] Deleting roleBinding clusterrolebinding-m2ncp
E0731 18:23:40.682472       6 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 39269 [running]:
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3afc560, 0x749ad60)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x3afc560, 0x749ad60)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0051bcc60, 0x37fb760, 0xc00bdd7d70, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:194 +0x13b
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0051bcc60, 0x40c501)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:170 +0x51
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc0051bcc60)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:159 +0x2b
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc007f6a6c0)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5e
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc007f6a6c0, 0x4c26640, 0xc00751b320, 0xc006422401, 0xc00440d6e0)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc007f6a6c0, 0x3b9aca00, 0x0, 0x1, 0xc00440d6e0)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0xe2
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc007f6a6c0, 0x3b9aca00, 0xc00440d6e0)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:130 +0x35e
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x11739eb]

goroutine 39269 [running]:
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x3afc560, 0x749ad60)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0051bcc60, 0x37fb760, 0xc00bdd7d70, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:194 +0x13b
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0051bcc60, 0x40c501)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:170 +0x51
github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc0051bcc60)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:159 +0x2b
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc007f6a6c0)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5e
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc007f6a6c0, 0x4c26640, 0xc00751b320, 0xc006422401, 0xc00440d6e0)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc007f6a6c0, 0x3b9aca00, 0x0, 0x1, 0xc00440d6e0)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0xe2
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc007f6a6c0, 0x3b9aca00, 0xc00440d6e0)
	/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/lasso/pkg/controller/controller.go:130 +0x35e
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `6aef36313`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Kubernetes version (use `kubectl version`):

```
1.18
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by cbron** [comment]
Should be fixed, please re-test

**Comment by sowmyav27** [comment]
PR: https://github.com/rancher/rancher/pull/28294

**Comment by sowmyav27** [comment]
**Validated on master-head - commit id: `d19f179c4 `**

- Created Hosted and imported EKS clusters. 
- Edited/deleted the clusters. No panics/restarts seen in rancher server logs.
