### ISSUE TITLE
`cattle-cluster-agent` in downstream cluster keeps crashing because of segmentation fault

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#28266]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- install `rancher:master-3420-head` in HA mode
- go to dashboard -> app -> enable the ECM feature
- go to ember UI
- import an RKE cluster ( in my case, 1 node, v1.18.3)

**Result:**
- the cluster fails at health checking
<img width="1445" alt="Screen Shot 2020-08-06 at 11 22 03 AM" src="https://user-images.githubusercontent.com/6218999/89568354-0a10c380-d7d8-11ea-9fe8-8c82b585e9c5.png">

- in the cluster, the pod  `cattle-cluster-agent` is in a crashing loop

```
NAMESPACE       NAME                                      READY   STATUS             RESTARTS   AGE
cattle-system   cattle-cluster-agent-bcb94b77c-dtx2t      0/1     CrashLoopBackOff   5          5m14s
```
- here are the logs of the pod
```
INFO: Environment: CATTLE_ADDRESS=10.42.0.6 CATTLE_CA_CHECKSUM=295b5528d021581b9403663361acc7bfd7ac5c8669c30ca7be307a69e7d96789 CATTLE_CLUSTER=true CATTLE_FEATURES=,multi-cluster-management=disable CATTLE_INTERNAL_ADDRESS= CATTLE_IS_RKE=false CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-bcb94b77c-dtx2t CATTLE_SERVER=https://jiaqi02391.whatever.domain.com
INFO: Using resolv.conf: nameserver 10.43.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local us-west-1.compute.internal options ndots:5
INFO: https://jiaqi02391.whatever.domain.com/ping is accessible
INFO: jiaqi02391.whatever.domain.com resolves to 3.129.28.202
INFO: Value from https://jiaqi02391.whatever.domain.com/v3/settings/cacerts is an x509 certificate
time="2020-08-06T18:19:20Z" level=error msg="failed to apply feature args: feature argument should be of the form \"features=feature1=bool,feature2=bool\""
time="2020-08-06T18:19:20Z" level=info msg="Rancher agent version 9b0dd20b7 is starting"
time="2020-08-06T18:19:20Z" level=info msg="Listening on /tmp/log.sock"
time="2020-08-06T18:19:20Z" level=info msg="Connecting to wss://jiaqi02391.whatever.domain.com/v3/connect/register with token 4qhngkt5pb6xz7j44ml5phdnqwrpkfcqks5wlx6vf7z4t42gdxqzt5"
time="2020-08-06T18:19:20Z" level=info msg="Connecting to proxy" url="wss://jiaqi02391.whatever.domain.com/v3/connect/register"
time="2020-08-06T18:19:20Z" level=info msg="Starting steve"
time="2020-08-06T18:19:20Z" level=info msg="Updating CRD releases.catalog.cattle.io"
I0806 18:19:21.572087       1 leaderelection.go:242] attempting to acquire leader lease  kube-system/cattle-controllers...
time="2020-08-06T18:19:21Z" level=info msg="Starting management.cattle.io/v3, Kind=Setting controller"
time="2020-08-06T18:19:21Z" level=info msg="Starting apiregistration.k8s.io/v1, Kind=APIService controller"
time="2020-08-06T18:19:21Z" level=info msg="Starting management.cattle.io/v3, Kind=Cluster controller"
time="2020-08-06T18:19:21Z" level=info msg="Starting /v1, Kind=ConfigMap controller"
time="2020-08-06T18:19:21Z" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=Role controller"
time="2020-08-06T18:19:21Z" level=info msg="Starting catalog.cattle.io/v1, Kind=Repo controller"
time="2020-08-06T18:19:21Z" level=info msg="Starting catalog.cattle.io/v1, Kind=ClusterRepo controller"
time="2020-08-06T18:19:21Z" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=RoleBinding controller"
time="2020-08-06T18:19:21Z" level=info msg="Starting management.cattle.io/v3, Kind=Feature controller"
time="2020-08-06T18:19:21Z" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding controller"
time="2020-08-06T18:19:21Z" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=ClusterRole controller"
time="2020-08-06T18:19:21Z" level=info msg="Starting apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition controller"
time="2020-08-06T18:19:21Z" level=info msg="Starting /v1, Kind=Secret controller"
I0806 18:19:21.610268       1 leaderelection.go:252] successfully acquired lease kube-system/cattle-controllers
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x290 pc=0x1d9d6c1]

goroutine 196 [running]:
github.com/rancher/rancher/pkg/auth.(*Server).OnLeader(0xc000756700, 0x4ca3140, 0xc000010c80, 0x1, 0x1)
	/go/src/github.com/rancher/rancher/pkg/auth/server.go:118 +0x71
github.com/rancher/rancher/vendor/github.com/rancher/wrangler/pkg/leader.(*Manager).OnLeader.func1(0xc001157c80, 0xc000332480)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/wrangler/pkg/leader/manager.go:51 +0xcc
created by github.com/rancher/rancher/vendor/github.com/rancher/wrangler/pkg/leader.(*Manager).OnLeader
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/wrangler/pkg/leader/manager.go:48 +0x49
```

**Other details that may be helpful:**

The same error happens to custom clusters and rancher-provisioned clusters, too. 

Update:
- see the same error in rancher single-install setup

**Comment by sangeethah** [comment]
This issue is seen when provisioning RKE clusters as well.

**Comment by soumyalj** [comment]
This issue is also observed on a GKE cluster deployed on master-head setup.

**Comment by ibuildthecloud** [comment]
This will apply to all cluster types except local.

**Comment by mr-karan** [comment]
Got bitten by same. Using `rancher/rancher:stable` doesn't have this issue.

**Comment by jiaqiluo** [comment]
The bug fix is validated on the lastest master-head `master-502b1839ebeea78f20828706b4e67e907aa9da8f`

imported RKE cluster and Rancher-provisioned cluster are all active and do not show the error described in the issue.

**Comment by Linutux** [comment]
Is there a workaround for clusters currently running rancher:latest?

**Comment by kenhglee** [comment]
Hi @Linutux, any luck with the existing clusters? I am also experiencing the same with v2.4.6, and I was wondering if things have gotten better. Lots of remedies gathered from older issues to either change the dnsPolicy to Default or None with the appropriate configs haven't worked. Ref) [https://github.com/rancher/rancher/issues/16454](url), [https://github.com/rancher/rancher/issues/18832](url). Any future plan the same fix to be applied for custom node or existing clusters, @jiaqiluo ?
