### ISSUE TITLE
[2.4] Rancher server pods crash with goroutine panic due to concurrent map read and write

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#28293]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Enable dashboard on Rancher 2.4

**Result:**
The rancher pods will consistently crash with goroutine panic due to concurrent map read and write. Segfaults are reported in the system logs at the time that the goroutine panic is seen.

**Other details that may be helpful:**
This code gets called only if the dashboard is enabled, so disabling it fixes the issue.

**Environment information**
- Rancher version: v2.4.5

Relevant stack trace:

```
2020-08-07T16:44:40.526435030Z fatal error: concurrent map read and map write
2020-08-07T16:44:40.529825624Z 
2020-08-07T16:44:40.529838454Z goroutine 47028 [running]:
2020-08-07T16:44:40.529842699Z runtime.throw(0x3fb5abb, 0x21)
2020-08-07T16:44:40.529846089Z 	/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc042f13d20 sp=0xc042f13cf0 pc=0x42fb12
2020-08-07T16:44:40.529850274Z runtime.mapaccess2_faststr(0x3642e20, 0xc03b9e1470, 0xc03513f1c0, 0x1d, 0x0, 0x0)
2020-08-07T16:44:40.529853995Z 	/usr/local/go/src/runtime/map_faststr.go:116 +0x48f fp=0xc042f13d90 sp=0xc042f13d20 pc=0x41335f
2020-08-07T16:44:40.529857761Z github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/schemaserver/subscribe.(*WatchSession).watch(0xc0271a3300, 0xc00d11f4a0, 0xc01570b140, 0x0, 0x0)
2020-08-07T16:44:40.529861769Z 	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/schemaserver/subscribe/watcher.go:129 +0x1e7 fp=0xc042f13ed8 sp=0xc042f13d90 pc=0x25be957
2020-08-07T16:44:40.529865555Z github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/schemaserver/subscribe.(*WatchSession).Watch.func1(0xc01570b140, 0xc0271a3300, 0xc00d11f4a0)
2020-08-07T16:44:40.529869403Z 	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/schemaserver/subscribe/watcher.go:98 +0x91 fp=0xc042f13fc8 sp=0xc042f13ed8 pc=0x25bee71
2020-08-07T16:44:40.529872935Z runtime.goexit()
2020-08-07T16:44:40.529876744Z 	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc042f13fd0 sp=0xc042f13fc8 pc=0x45f7a1
2020-08-07T16:44:40.529880291Z created by github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/schemaserver/subscribe.(*WatchSession).Watch
2020-08-07T16:44:40.529883891Z 	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/schemaserver/subscribe/watcher.go:95 +0x6c
2020-08-07T16:44:40.529887782Z 
```

gzrancher/rancher#11655

gzrancher/rancher#11655

gz#12649

gz#13505

gz#14250

**Comment by cbron** [comment]
See: 
* https://github.com/rancher/steve/blob/release/2.4/pkg/schemaserver/subscribe/watcher.go#L41
* z1-11655-w....

**Comment by sowmyav27** [comment]
**Verified on `2.4.12-rc3` and 2.4-head - commit id: `ca0c2b9f4`**

- Able to deploy rancher.
- No panics seen
- Deployed an rke 1 node cluster successfully.

**Comment by sowmyav27** [comment]
Reopening for an RKE RC from `release/v1.1` branch and vendoring in changes to rancher

**Comment by sowmyav27** [comment]
**On 2.4.13-rc1**
- Able to deploy rancher.
- No panics seen
- Deployed an rke  cluster successfully.
Closing this issue for now.
