### ISSUE TITLE
Panic in EKS controller

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28533]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Created 1 hosted EKS cluster - only Private access selected. (VPC and subnet - same as that of rancher server)
- Created one import EKS cluster. `API server endpoint access` of the cluster created is Private. 
- Logs:
```
W0824 16:27:36.801247       1 loader.go:223] Config not found: /root/.kube/config
time="2020-08-24T16:27:36Z" level=info msg="Starting eks.cattle.io/v1, Kind=EKSClusterConfig controller"
time="2020-08-24T16:27:36Z" level=info msg="Starting /v1, Kind=Secret controller"
time="2020-08-24T16:27:37Z" level=info msg="waiting for cluster [c-m8qpr] to finish creating"
E0824 16:27:37.274757       1 runtime.go:78] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
goroutine 431 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1716740, 0xc000958ec0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.0/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.0/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1716740, 0xc000958ec0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/eks-operator/controller.(*Handler).buildUpstreamClusterState(0xc0005e0240, 0xc0005ee330, 0xd, 0xc0000bd118, 0xc0000102e8, 0x1, 0x1, 0xc0000bd0f0, 0x1, 0x0, ...)
	/go/eks-operator/controller/eks-cluster-config-handler.go:602 +0x7f2
github.com/rancher/eks-operator/controller.(*Handler).importCluster(0xc0005e0240, 0xc0000f2280, 0xc0000bd0f0, 0x0, 0x0, 0xc0000bd108)
	/go/eks-operator/controller/eks-cluster-config-handler.go:904 +0x3fc
github.com/rancher/eks-operator/controller.(*Handler).OnEksConfigChanged(0xc0005e0240, 0xc000588740, 0x1a, 0xc0000f2280, 0xc0001c08f0, 0xc000561680, 0xc0004d60c0)
	/go/eks-operator/controller/eks-cluster-config-handler.go:84 +0x224
github.com/rancher/eks-operator/controller.(*Handler).recordError.func1(0xc000588740, 0x1a, 0xc0000f2280, 0xc00049e670, 0x0, 0xc000561680)
	/go/eks-operator/controller/eks-cluster-config-handler.go:103 +0x67
github.com/rancher/eks-operator/pkg/generated/controllers/eks.cattle.io/v1.FromEKSClusterConfigHandlerToHandler.func1(0xc000588740, 0x1a, 0x1af1f60, 0xc0000f2280, 0x0, 0x0, 0x0, 0x0)
	/go/eks-operator/pkg/generated/controllers/eks.cattle.io/v1/eksclusterconfig.go:105 +0x65
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc0004249b0, 0xc000588740, 0x1a, 0x1af1f60, 0xc0000f2280, 0xc0000caea0, 0xc000439bb8, 0xc000439c20, 0xd7c80f)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200513231433-d0ce66327a25/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*sharedHandler).OnChange(0xc0000a5860, 0xc000588740, 0x1a, 0x1af1f60, 0xc0000f2280, 0x543101, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200513231433-d0ce66327a25/pkg/controller/sharedhandler.go:64 +0x14a
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000290f20, 0xc000588740, 0x1a, 0xd1aae1, 0xc000046440)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200513231433-d0ce66327a25/pkg/controller/controller.go:205 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000290f20, 0x15aa2e0, 0xc000515b70, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200513231433-d0ce66327a25/pkg/controller/controller.go:187 +0xf0
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000290f20, 0x522586)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200513231433-d0ce66327a25/pkg/controller/controller.go:164 +0x51
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc000290f20)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200513231433-d0ce66327a25/pkg/controller/controller.go:153 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000515c00)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.0/pkg/util/wait/wait.go:155 +0x5e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000515c00, 0x1ae8fc0, 0xc000629cb0, 0xc0000bd001, 0xc0004d60c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.0/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000515c00, 0x3b9aca00, 0x0, 0x1, 0xc0004d60c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.0/pkg/util/wait/wait.go:133 +0xe2
k8s.io/apimachinery/pkg/util/wait.Until(0xc000515c00, 0x3b9aca00, 0xc0004d60c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.0/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200513231433-d0ce66327a25/pkg/controller/controller.go:128 +0x35e
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0
goroutine 431 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.0/pkg/util/runtime/runtime.go:55 +0x105
panic(0x1716740, 0xc000958ec0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/eks-operator/controller.(*Handler).buildUpstreamClusterState(0xc0005e0240, 0xc0005ee330, 0xd, 0xc0000bd118, 0xc0000102e8, 0x1, 0x1, 0xc0000bd0f0, 0x1, 0x0, ...)
	/go/eks-operator/controller/eks-cluster-config-handler.go:602 +0x7f2
github.com/rancher/eks-operator/controller.(*Handler).importCluster(0xc0005e0240, 0xc0000f2280, 0xc0000bd0f0, 0x0, 0x0, 0xc0000bd108)
	/go/eks-operator/controller/eks-cluster-config-handler.go:904 +0x3fc
github.com/rancher/eks-operator/controller.(*Handler).OnEksConfigChanged(0xc0005e0240, 0xc000588740, 0x1a, 0xc0000f2280, 0xc0001c08f0, 0xc000561680, 0xc0004d60c0)
	/go/eks-operator/controller/eks-cluster-config-handler.go:84 +0x224
github.com/rancher/eks-operator/controller.(*Handler).recordError.func1(0xc000588740, 0x1a, 0xc0000f2280, 0xc00049e670, 0x0, 0xc000561680)
	/go/eks-operator/controller/eks-cluster-config-handler.go:103 +0x67
github.com/rancher/eks-operator/pkg/generated/controllers/eks.cattle.io/v1.FromEKSClusterConfigHandlerToHandler.func1(0xc000588740, 0x1a, 0x1af1f60, 0xc0000f2280, 0x0, 0x0, 0x0, 0x0)
	/go/eks-operator/pkg/generated/controllers/eks.cattle.io/v1/eksclusterconfig.go:105 +0x65
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc0004249b0, 0xc000588740, 0x1a, 0x1af1f60, 0xc0000f2280, 0xc0000caea0, 0xc000439bb8, 0xc000439c20, 0xd7c80f)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200513231433-d0ce66327a25/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*sharedHandler).OnChange(0xc0000a5860, 0xc000588740, 0x1a, 0x1af1f60, 0xc0000f2280, 0x543101, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200513231433-d0ce66327a25/pkg/controller/sharedhandler.go:64 +0x14a
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000290f20, 0xc000588740, 0x1a, 0xd1aae1, 0xc000046440)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200513231433-d0ce66327a25/pkg/controller/controller.go:205 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000290f20, 0x15aa2e0, 0xc000515b70, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200513231433-d0ce66327a25/pkg/controller/controller.go:187 +0xf0
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000290f20, 0x522586)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200513231433-d0ce66327a25/pkg/controller/controller.go:164 +0x51
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc000290f20)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200513231433-d0ce66327a25/pkg/controller/controller.go:153 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000515c00)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.0/pkg/util/wait/wait.go:155 +0x5e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000515c00, 0x1ae8fc0, 0xc000629cb0, 0xc0000bd001, 0xc0004d60c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.0/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000515c00, 0x3b9aca00, 0x0, 0x1, 0xc0004d60c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.0/pkg/util/wait/wait.go:133 +0xe2
k8s.io/apimachinery/pkg/util/wait.Until(0xc000515c00, 0x3b9aca00, 0xc0004d60c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.0/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200513231433-d0ce66327a25/pkg/controller/controller.go:128 +0x35e
```

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `8a60de75d`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted and imported EKS cluster
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `c428bc9`**

- Created 1 hosted EKS cluster - only Private access selected. (VPC and subnet - same as that of rancher server)
- Created one import EKS cluster. API server endpoint access of the cluster created is Private.
- No panic is seen in the eks operator logs
- Both the clusters come up Active
