### ISSUE TITLE
Recurrent panic when catalog templates loaded 

### ISSUE THREAD

**Issue by adonm** [rancher/rancher#28750]
https://github.com/rancher/rancher/blob/33a181c368f3edacd57b6817439d9023af9701ca/pkg/api/customization/catalog/store.go#L59

It appears the above line is causing our 2.4.8 rancher (deployed as single docker instance) to panic and restart every time some catalog entries are loaded? The issue reoccurs intermittently, sometimes every few minutes, other times with hours to days between problems.

```
panic: interface conversion: interface {} is nil, not string

goroutine 39976 [running]:
github.com/rancher/rancher/pkg/api/customization/catalog.(*templateStore).extractVersionLinks(0xc001352e00, 0xc00c6a9200, 0xc025e2dfb0, 0xc01df39708)
        /go/src/github.com/rancher/rancher/pkg/api/customization/catalog/store.go:59 +0x5bb
github.com/rancher/rancher/pkg/api/customization/catalog.GetTemplateStore.func1(0xc00c6a9200, 0xc0008a10e0, 0xc025e2dfb0, 0xc01d362980, 0xc01cf63fa8, 0xd0ce01, 0x101)
        /go/src/github.com/rancher/rancher/pkg/api/customization/catalog/store.go:39 +0x42
github.com/rancher/rancher/vendor/github.com/rancher/norman/store/transform.(*Store).Watch.func1(0xc025e2dfb0, 0xc01cf63fa8)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/transform/transform.go:58 +0x4e
github.com/rancher/rancher/vendor/github.com/rancher/norman/types/convert.Chan.func1(0xc01e9a6f00, 0xc01ef3df20, 0xc01e9a6f60)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/types/convert/convert.go:21 +0x65
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/types/convert.Chan
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/types/convert/convert.go:19 +0x7f
```

Our catalogs are as follows:

![image](https://user-images.githubusercontent.com/121014/92241969-aae6c180-eef1-11ea-904f-e776d8953de1.png)

Unfortunately we haven't been able to discover the exact sequence of events leading up to / causing the issue

**Comment by adonm** [comment]
Possibly related to #28776
