### ISSUE TITLE
API Panics after upgrade from 2.4.5 (k3s,HA)

### ISSUE THREAD

**Issue by ItsReddi** [rancher/rancher#28781]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Install k3s 2.4.5 HA Cluster
2. Deploy another cluster with nodes
3. Upgrade to 2.4.6
4. Upgrade to 2.4.7
5. Upgrade to 2.4.8
6. Add a bitbucket pipeline and try to run it (worked on 2.4.6)

**Result:**
Receiving API Kernel panics for example, when running a new Pipeline a retrigger of a pipline works well.

**Other details that may be helpful:**
![grafik](https://user-images.githubusercontent.com/3147888/92434943-6bde9780-f1a1-11ea-94ec-143d5f29ac93.png)
```
2020/09/08 04:58:47 [ERROR] Panic serving api request:
goroutine 13270 [running]:
runtime/debug.Stack(0xc0066627c0, 0x37776c0, 0x6e16430)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP.func1(0x480c000, 0xc0165fe090)
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:175 +0x7a
panic(0x37776c0, 0x6e16430)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/rancher/pkg/pipeline/remote/bitbucketcloud.(*client).GetHeadInfo(0xc015a13c80, 0xc00252d2c0, 0x32, 0xc0086ae080, 0x7, 0xc012f226e0, 0x94, 0x0, 0x0, 0x4862760)
	/go/src/github.com/rancher/rancher/pkg/pipeline/remote/bitbucketcloud/client.go:302 +0x369
github.com/rancher/rancher/pkg/api/customization/pipeline.(*Handler).getBuildInfoByBranch(0xc000f2d980, 0xc001595000, 0xc0086ae080, 0x7, 0xc001595000, 0xc0086ae080, 0x7)
	/go/src/github.com/rancher/rancher/pkg/api/customization/pipeline/pipeline.go:239 +0x129
github.com/rancher/rancher/pkg/api/customization/pipeline.(*Handler).run(0xc000f2d980, 0xc0134bb9e0, 0xc0143ae101, 0xc001453860)
	/go/src/github.com/rancher/rancher/pkg/api/customization/pipeline/pipeline.go:117 +0x336
github.com/rancher/rancher/pkg/api/customization/pipeline.(*Handler).ActionHandler(0xc000f2d980, 0xc0084506d2, 0x3, 0xc00ecc8da0, 0xc0134bb9e0, 0xc001453860, 0xc015862e40)
	/go/src/github.com/rancher/rancher/pkg/api/customization/pipeline/pipeline.go:75 +0x330
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.handleAction(0xc00ecc8da0, 0xc0134bb9e0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:263 +0x62
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).handle(0xc000032dc0, 0x480c000, 0xc0165fe090, 0xc0014fa000, 0xc004d74d08, 0x1232e7f3, 0x55025dbb5dfc4a0a)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:251 +0xd2
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP(0xc000032dc0, 0x480c000, 0xc0165fe090, 0xc0014fa000)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:180 +0x99
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentTypeOptions.func1(0x480c000, 0xc0165fe090, 0xc0014fa000)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/cache.go:47 +0x131
net/http.HandlerFunc.ServeHTTP(0xc00ecc8d40, 0x480c000, 0xc0165fe090, 0xc0014fa000)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00004de00, 0x480c000, 0xc0165fe090, 0xc00262a400)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/pkg/auth/requests.authHeaderHandler.ServeHTTP(0x47d1580, 0xc0014cf7e0, 0x4792c40, 0xc00004de00, 0x47d1540, 0xc001470fc0, 0x480c000, 0xc0165fe090, 0xc00262a400)
	/go/src/github.com/rancher/rancher/pkg/auth/requests/filter.go:62 +0x4eb
github.com/rancher/rancher/pkg/rbac.NewAccessControlHandler.func1(0x480c000, 0xc0165fe090, 0xc001cd8100, 0x4791c00, 0xc0011b8990)
	/go/src/github.com/rancher/rancher/pkg/rbac/user_based.go:32 +0x194
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/auth.Middleware.Wrap.func1(0x480c000, 0xc0165fe090, 0xc001cd8100)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/auth/filter.go:36 +0x55
net/http.HandlerFunc.ServeHTTP(0xc0014cf9a0, 0x480c000, 0xc0165fe090, 0xc001cd8100)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/pkg/websocket.websocketHandler.ServeHTTP(0x4799f00, 0xc0014cf9a0, 0x480c000, 0xc0165fe090, 0xc001cd8100)
	/go/src/github.com/rancher/rancher/pkg/websocket/handler.go:35 +0xa0
github.com/rancher/rancher/pkg/audit.auditHandler.ServeHTTP(0x4791e40, 0xc0003476a0, 0x0, 0x480c000, 0xc0165fe090, 0xc001cd8100)
	/go/src/github.com/rancher/rancher/pkg/audit/filter.go:31 +0x623
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentType.func1(0x47f9e00, 0xc013f2e450, 0xc001cd8100)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/content.go:33 +0x93
net/http.HandlerFunc.ServeHTTP(0xc0014df6c0, 0x47f9e00, 0xc013f2e450, 0xc001cd8100)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.Gzip.func1(0x480ae80, 0xc0019d77a0, 0xc001cd8100)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/gzip.go:60 +0x1f5
net/http.HandlerFunc.ServeHTTP(0xc0014df6e0, 0x480ae80, 0xc0019d77a0, 0xc001cd8100)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentTypeOptions.func1(0x480ae80, 0xc0019d77a0, 0xc001cd8100)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/cache.go:47 +0x131
net/http.HandlerFunc.ServeHTTP(0xc00ecc8ca0, 0x480ae80, 0xc0019d77a0, 0xc001cd8100)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00004dd40, 0x480ae80, 0xc0019d77a0, 0xc0026a0000)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0063d8480, 0x480ae80, 0xc0019d77a0, 0xc002bbde00)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0063d8540, 0x480ae80, 0xc0019d77a0, 0xc002bbdb00)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0063d8600, 0x480ae80, 0xc0019d77a0, 0xc002bbd800)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/dashboard.Route.func2(0x480ae80, 0xc0019d77a0, 0xc002bbd800)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/dashboard/ui.go:56 +0xe5
net/http.HandlerFunc.ServeHTTP(0xc0063d59e0, 0x480ae80, 0xc0019d77a0, 0xc002bbd800)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00140b8c0, 0x480ae80, 0xc0019d77a0, 0xc00e1d5800)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/server.wrapHandler.func1(0x480ae80, 0xc0019d77a0, 0xc00e1d5800)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/server/server.go:187 +0x95
net/http.HandlerFunc.ServeHTTP(0xc007354e70, 0x480ae80, 0xc0019d77a0, 0xc00e1d5800)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener.HTTPRedirect.func1(0x480ae80, 0xc0019d77a0, 0xc00e1d5800)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/redirect.go:20 +0x221
net/http.HandlerFunc.ServeHTTP(0xc0098162e0, 0x480ae80, 0xc0019d77a0, 0xc00e1d5800)
	/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.serverHandler.ServeHTTP(0xc000e60620, 0x480ae80, 0xc0019d77a0, 0xc00e1d5800)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc007cab4a0, 0x482de00, 0xc015611d00)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e
```

Missing Variables warning:
```
2020/09/08 04:59:26 [ERROR] ProjectAlertGroupController p-2vhhb/projectalert-workload-alert [project-alert-group-controller] failed with : Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found

2020/09/08 04:59:26 [ERROR] ClusterAlertRuleController c-7bv7h/deployment-event-alert [cluster-alert-rule-controller] failed with : Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found

2020/09/08 04:59:26 [ERROR] ProjectAlertRuleController p-2vhhb/memory-close-to-resource-limited [project-alert-rule-controller] failed with : Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found

2020/09/08 04:59:26 [ERROR] ProjectAlertRuleController p-nqbv9/memory-close-to-resource-limited [project-alert-rule-controller] failed with : Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found

2020/09/08 04:59:26 [ERROR] ProjectAlertRuleController p-5jrp5/less-than-half-workload-available [project-alert-rule-controller] failed with : Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found

2020/09/08 04:59:27 [ERROR] ClusterAlertRuleController c-7bv7h/high-memmory [cluster-alert-rule-controller] failed with : Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found

2020/09/08 04:59:27 [ERROR] ClusterAlertRuleController c-7bv7h/cluster-scan-manual-failure-only [cluster-alert-rule-controller] failed with : Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found

2020/09/08 04:59:27 [ERROR] ClusterAlertGroupController c-7bv7h/event-alert [cluster-alert-group-controller] failed with : Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found

2020/09/08 04:59:27 [ERROR] ClusterAlertGroupController c-7bv7h/etcd-alert [cluster-alert-group-controller] failed with : Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found

2020/09/08 04:59:27 [ERROR] ClusterAlertRuleController c-7bv7h/cluster-scan-scheduled-all [cluster-alert-rule-controller] failed with : Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found

2020/09/08 04:59:27 [ERROR] ClusterAlertRuleController c-7bv7h/scheduler-system-service [cluster-alert-rule-controller] failed with : Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found

2020/09/08 04:59:27 [ERROR] ProjectAlertRuleController p-mknql/memory-close-to-resource-limited [project-alert-rule-controller] failed with : Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found

2020/09/08 04:59:27 [ERROR] ProjectAlertGroupController p-kgn7q/projectalert-workload-alert [project-alert-group-controller] failed with : Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found

2020/09/08 04:59:27 [ERROR] ProjectAlertRuleController p-kgn7q/less-than-half-workload-available [project-alert-rule-controller] failed with : Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found

2020/09/08 04:59:27 [ERROR] ProjectAlertRuleController p-2vhhb/less-than-half-workload-available [project-alert-rule-controller] failed with : Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found

2020/09/08 04:59:27 [ERROR] ProjectAlertGroupController p-mknql/projectalert-workload-alert [project-alert-group-controller] failed with : Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found

2020/09/08 04:59:27 [ERROR] ClusterAlertRuleController c-7bv7h/node-disk-running-full [cluster-alert-rule-controller] failed with : Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found

2020/09/08 04:59:27 [ERROR] ClusterAlertRuleController c-7bv7h/high-cpu-load [cluster-alert-rule-controller] failed with : Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found

2020/09/08 05:03:39 [ERROR] ProjectAlertGroupController p-5jrp5/projectalert-workload-alert [project-alert-group-controller] failed with : Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found

2020/09/08 05:03:39 [ERROR] ClusterAlertRuleController c-7bv7h/db-over-size [cluster-alert-rule-controller] failed with : Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found

2020/09/08 05:03:39 [ERROR] ClusterAlertGroupController c-7bv7h/node-alert [cluster-alert-group-controller] failed with : Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.4.8
- Installation option (single install/HA):
K3s HA

**Comment by steffeneichler** [comment]
same problem on our clusters with v2.4.8
