### ISSUE TITLE
Rancher panic when draining a node in the API

### ISSUE THREAD

**Issue by dkeightley** [rancher/rancher#28905]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a custom cluster - in this case 2 nodes were used as 1 x `all` and 1 x `worker` roles
1. Once created, view the worker node in the API (ellipsis, View in API)
1. In the new API tab, click the green drain button, continue to send the request with defaults

**Result:**

The Rancher pod logs show a panic and crashloop. Removing the node object from nodes.cattle.management.io has been used to resolve the issue.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x245793d]

goroutine 11856 [running]:
github.com/rancher/rancher/pkg/controllers/user/nodesyncer.getFlags(0xc0055f85d0, 0xc002c65b00, 0x410a038, 0x0)
 /go/src/github.com/rancher/rancher/pkg/controllers/user/nodesyncer/cordonfieldssyncer.go:241 +0x1cd
github.com/rancher/rancher/pkg/controllers/user/nodesyncer.(*nodeDrain).drain.func1(0x3f091c0, 0xc002c64900, 0x3f7a9fd, 0x7)
 /go/src/github.com/rancher/rancher/pkg/controllers/user/nodesyncer/cordonfieldssyncer.go:159 +0x13d
github.com/rancher/rancher/vendor/github.com/rancher/norman/condition.Cond.doInternal(0x3f7a9fd, 0x7, 0x47d5f01, 0x47d5f00, 0xc002c64900, 0xc0068b6f58, 0x6, 0x34a6c40, 0xc002071030, 0x198)
 /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/condition/condition.go:212 +0x9c
github.com/rancher/rancher/vendor/github.com/rancher/norman/condition.Cond.do2(0x3f7a9fd, 0x7, 0x3f7a901, 0x47d5f00, 0xc002c64900, 0xc0068b6f58, 0x40618a, 0xc004455440, 0x0, 0xc0063b7000, ...)
 /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/condition/condition.go:181 +0x1d8
github.com/rancher/rancher/vendor/github.com/rancher/norman/condition.Cond.do(...)
 /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/condition/condition.go:170
github.com/rancher/rancher/vendor/github.com/rancher/norman/condition.Cond.DoUntilTrue(0x3f7a9fd, 0x7, 0x47d5f00, 0xc002c64900, 0xc0068b6f58, 0xc00694b548, 0x8, 0xc00694b5b0, 0x5)
 /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/condition/condition.go:136 +0xee
github.com/rancher/rancher/pkg/controllers/user/nodesyncer.(*nodeDrain).drain(0xc00448eaa0, 0x482de00, 0xc0063b7080, 0xc002c64900, 0xc008f34e70, 0xe, 0xc00393d9d0)
 /go/src/github.com/rancher/rancher/pkg/controllers/user/nodesyncer/cordonfieldssyncer.go:146 +0x1ac
created by github.com/rancher/rancher/pkg/controllers/user/nodesyncer.(*nodeDrain).drainNode
 /go/src/github.com/rancher/rancher/pkg/controllers/user/nodesyncer/cordonfieldssyncer.go:97 +0x30e
```

**Other details that may be helpful:**

The following payload is sent for the defaults in the API, the `null` value for `ignoreDaemonSets` appears to be the cause.

```json
    {
    "deleteLocalData": false,
    "force": false,
    "gracePeriod": -1,
    "ignoreDaemonSets": null,
    "timeout": 120
    }
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.8 (also tested on v.2.4.5 and v2.4.6)

gzrancher/rancher#12247

**Comment by sowmyav27** [comment]
**Reproduced this issue on master-head - commit id: `e919796c80`**

**Steps:**
- Deploy a 1 node all roles custom cluster.
- View in API of the node.
- Click on `drain` action.
- Request sent has - 
```
{
"deleteLocalData": false,
"force": false,
"gracePeriod": -1,
"ignoreDaemonSets": null,
"timeout": 120
}
```
- Request says `Error: parsererror`
- Rancher server keeps restarting. 
- Rancher logs : 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x297ee2d]

goroutine 102819 [running]:
github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer.getFlags(0xc0067dd260, 0xc00c949b00, 0x466a380, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer/cordonfieldssyncer.go:243 +0x1cd
github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer.(*nodeDrain).drain.func1(0x4421660, 0xc00cc23680, 0x44a2b4a, 0x7)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer/cordonfieldssyncer.go:161 +0x13d
github.com/rancher/norman/condition.Cond.doInternal(0x44a2b4a, 0x7, 0x4dd8001, 0x4dd8060, 0xc00cc23680, 0xc00837ef38, 0x197, 0x44a0f4b, 0x6, 0x44aa2ca)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200908202416-992a35eef40f/condition/condition.go:212 +0x97
github.com/rancher/norman/condition.Cond.do2(0x44a2b4a, 0x7, 0x44a2b01, 0x4dd8060, 0xc00cc23680, 0xc00837ef38, 0x4065ea, 0xc00f8fac00, 0x0, 0xc005686900, ...)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200908202416-992a35eef40f/condition/condition.go:181 +0x1d8
github.com/rancher/norman/condition.Cond.do(...)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200908202416-992a35eef40f/condition/condition.go:170
github.com/rancher/norman/condition.Cond.DoUntilTrue(0x44a2b4a, 0x7, 0x4dd8060, 0xc00cc23680, 0xc00837ef38, 0xc008695f30, 0x3, 0x3, 0xc008695f2a)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200908202416-992a35eef40f/condition/condition.go:136 +0xb3
github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer.(*nodeDrain).drain(0xc0031cff40, 0x4e3b720, 0xc005686900, 0xc00cc23680, 0xc00d1fd3d0, 0xe, 0xc0060f7b80)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer/cordonfieldssyncer.go:148 +0x1a5
created by github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer.(*nodeDrain).drainNode
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer/cordonfieldssyncer.go:99 +0x335
```

**Comment by sowmyav27** [comment]
**On 2.4.8**

**From UI** - No panic seen
- Drain a node from UI - default values
- Request sent: `2020/09/14 23:21:06 [INFO] Draining node ip-172-31-2-84 in c-8jzbd with flags --delete-local-data=false --force=false --grace-period=-1 --ignore-daemonsets=true --timeout=120s`
- Aggressive drain from UI
- Request sent has:: `2020/09/14 23:22:23 [INFO] Draining node ip-172-31-2-84 in c-8jzbd with flags --delete-local-data=true --force=true --grace-period=-1 --ignore-daemonsets=true --timeout=120s`

**From API:** - Issue seen

- View in API of the node. --> Drain --> Default values set. Request sent has 
```
{
"deleteLocalData": false,
"force": false,
"gracePeriod": -1,
"ignoreDaemonSets": null,
"timeout": 120
}
```
- Panic in rancher logs:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x245793d]

goroutine 30883 [running]:
github.com/rancher/rancher/pkg/controllers/user/nodesyncer.getFlags(0xc005420f30, 0xc009bedb00, 0x410a038, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/user/nodesyncer/cordonfieldssyncer.go:241 +0x1cd
github.com/rancher/rancher/pkg/controllers/user/nodesyncer.(*nodeDrain).drain.func1(0x3f091c0, 0xc007222000, 0x3f7a9fd, 0x7)
	/go/src/github.com/rancher/rancher/pkg/controllers/user/nodesyncer/cordonfieldssyncer.go:159 +0x13d
github.com/rancher/rancher/vendor/github.com/rancher/norman/condition.Cond.doInternal(0x3f7a9fd, 0x7, 0x47d5f01, 0x47d5f00, 0xc007222000, 0xc007d70f58, 0x197, 0x3f78f89, 0x6, 0x3f8143b)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/condition/condition.go:212 +0x9c
github.com/rancher/rancher/vendor/github.com/rancher/norman/condition.Cond.do2(0x3f7a9fd, 0x7, 0x3f7a901, 0x47d5f00, 0xc007222000, 0xc007d70f58, 0x40618a, 0xc0099dfda0, 0x0, 0xc0028a7500, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/condition/condition.go:181 +0x1d8
github.com/rancher/rancher/vendor/github.com/rancher/norman/condition.Cond.do(...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/condition/condition.go:170
github.com/rancher/rancher/vendor/github.com/rancher/norman/condition.Cond.DoUntilTrue(0x3f7a9fd, 0x7, 0x47d5f00, 0xc007222000, 0xc007d70f58, 0xa, 0x2, 0x2, 0xc002f44fa0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/condition/condition.go:136 +0xee
github.com/rancher/rancher/pkg/controllers/user/nodesyncer.(*nodeDrain).drain(0xc003087040, 0x482de00, 0xc0028a75c0, 0xc007222000, 0xc00533b8b0, 0xe, 0xc00a45cc40)
	/go/src/github.com/rancher/rancher/pkg/controllers/user/nodesyncer/cordonfieldssyncer.go:146 +0x1ac
created by github.com/rancher/rancher/pkg/controllers/user/nodesyncer.(*nodeDrain).drainNode
	/go/src/github.com/rancher/rancher/pkg/controllers/user/nodesyncer/cordonfieldssyncer.go:97 +0x30e
```

**Comment by sowmyav27** [comment]
**On master-head - commit id: `ed2749841`**

- Deploy a custom cluster (AWS nodes)
- Do a drain on a worker node from API. 
- Ignoredaemonset was set to NULL
- Panic seen in rancher server:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x298652d]

goroutine 17201 [running]:
github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer.getFlags(0xc0075420c0, 0xc00303f680, 0x46743e0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer/cordonfieldssyncer.go:243 +0x1cd
github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer.(*nodeDrain).drain.func1(0x442b560, 0xc002876900, 0x44acaaa, 0x7)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer/cordonfieldssyncer.go:161 +0x13d
github.com/rancher/norman/condition.Cond.doInternal(0x44acaaa, 0x7, 0x4dea501, 0x4dea560, 0xc002876900, 0xc006dc9f38, 0x6, 0x38ee020, 0xc00d5beeb0, 0x198)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200908202416-992a35eef40f/condition/condition.go:212 +0x97
github.com/rancher/norman/condition.Cond.do2(0x44acaaa, 0x7, 0x44aca01, 0x4dea560, 0xc002876900, 0xc006dc9f38, 0x4065ea, 0xc00c7d5800, 0x0, 0xc008d43d00, ...)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200908202416-992a35eef40f/condition/condition.go:181 +0x1d8
github.com/rancher/norman/condition.Cond.do(...)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200908202416-992a35eef40f/condition/condition.go:170
github.com/rancher/norman/condition.Cond.DoUntilTrue(0x44acaaa, 0x7, 0x4dea560, 0xc002876900, 0xc006dc9f38, 0x10, 0x10, 0x3de3ac0, 0x437adc)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200908202416-992a35eef40f/condition/condition.go:136 +0xb3
github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer.(*nodeDrain).drain(0xc00b5fe780, 0x4e4dca0, 0xc008d43dc0, 0xc002876900, 0xc00bfeca50, 0x10, 0xc0031a6b50)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer/cordonfieldssyncer.go:148 +0x1a5
created by github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer.(*nodeDrain).drainNode
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer/cordonfieldssyncer.go:99 +0x335

```

**Comment by sowmyav27** [comment]
**On master-head -commit id: `e9a98a3238`**
