### ISSUE TITLE
Follow pod output (log) with kubectl doesn't work

### ISSUE THREAD

**Issue by mecseid** [rancher/rancher#28906]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
* Make a simple deployment which generate some log output
* Follow the pod logs with this command:
```
 kubectl --v=7 logs -f --tail=10 random_pod_id
```

**Result:**
I masked out some sensitive information
```
$ kubectl --v=7 logs -f --tail=10 random_pod_id
I0914 21:45:17.840343     296 loader.go:375] Config loaded from file:  <masked>
I0914 21:45:17.845440     296 round_trippers.go:420] GET https://<masked>
I0914 21:45:17.845467     296 round_trippers.go:427] Request Headers:
I0914 21:45:17.845473     296 round_trippers.go:431]     Accept: application/json, */*
I0914 21:45:17.845477     296 round_trippers.go:431]     User-Agent: kubectl/v1.19.1 (linux/amd64) kubernetes/206bcad
I0914 21:45:17.845482     296 round_trippers.go:431]     Authorization: Bearer <masked>
I0914 21:45:17.992892     296 round_trippers.go:446] Response Status: 200 OK in 147 milliseconds
I0914 21:45:17.997699     296 round_trippers.go:420] GET https://<masked>/log?follow=true&tailLines=10
I0914 21:45:17.997737     296 round_trippers.go:427] Request Headers:
I0914 21:45:17.997743     296 round_trippers.go:431]     Accept: application/json, */*
I0914 21:45:17.997748     296 round_trippers.go:431]     User-Agent: kubectl/v1.19.1 (linux/amd64) kubernetes/206bcad
I0914 21:45:17.997754     296 round_trippers.go:431]     Authorization: Bearer <masked>
I0914 21:50:18.035340     296 round_trippers.go:446] Response Status: 200 OK in 300037 milliseconds

<lots of log - more than the last 10 lines>

F0914 21:50:18.037820     296 helpers.go:115] error: stream error: stream ID 3; INTERNAL_ERROR
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc000182001, 0xc000849000, 0x5f, 0x1f8)
        /workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:996 +0xb9
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x2d11ca0, 0xc000000003, 0x0, 0x0, 0xc000887c00, 0x2ae6711, 0xa, 0x73, 0x40b200)
        /workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:945 +0x191
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0x2d11ca0, 0x3, 0x0, 0x0, 0x2, 0xc000a2d788, 0x1, 0x1)
        /workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:718 +0x165
k8s.io/kubernetes/vendor/k8s.io/klog/v2.FatalDepth(...)
        /workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1442
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.fatal(0xc000b320c0, 0x30, 0x1)
        /workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:93 +0x1f0
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.checkErr(0x1e5cee0, 0xc000a0e080, 0x1d05b48)
        /workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:188 +0x945
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.CheckErr(...)
        /workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:115
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/logs.NewCmdLogs.func1(0xc000612000, 0xc000885320, 0x1, 0x6)
        /workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/logs/logs.go:154 +0x1a5
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc000612000, 0xc0008852c0, 0x6, 0x6, 0xc000612000, 0xc0008852c0)
        /workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846 +0x2c2
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00041f600, 0xc000184120, 0xc00018c000, 0x8)
        /workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:950 +0x375
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:887
main.main()
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x21d

goroutine 18 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2d11ca0)
        /workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1131 +0x8b
created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
        /workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:416 +0xd8

goroutine 8 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x1d05a80, 0x1e5a100, 0xc000614000, 0x1, 0xc000196060)
        /workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x149
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x1d05a80, 0x12a05f200, 0x0, 0x1, 0xc000196060)
        /workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0x1d05a80, 0x12a05f200, 0xc000196060)
        /workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs.InitLogs
        /workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs/logs.go:51 +0x96

goroutine 94 [IO wait]:
internal/poll.runtime_pollWait(0x7f243d898a38, 0x72, 0x1e5d2e0)
        /usr/local/go/src/runtime/netpoll.go:220 +0x55
internal/poll.(*pollDesc).wait(0xc000b13298, 0x72, 0xc00069e000, 0x1303, 0x1303)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000b13280, 0xc00069e000, 0x1303, 0x1303, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:159 +0x1b1
net.(*netFD).Read(0xc000b13280, 0xc00069e000, 0x1303, 0x1303, 0x203000, 0x6524db, 0xc000a5c160)
        /usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000182018, 0xc00069e000, 0x1303, 0x1303, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:182 +0x8e
crypto/tls.(*atLeastReader).Read(0xc000a0e0a0, 0xc00069e000, 0x1303, 0x1303, 0x1e, 0x38b, 0xc0008b1730)
        /usr/local/go/src/crypto/tls/conn.go:779 +0x62
bytes.(*Buffer).ReadFrom(0xc000a5c280, 0x1e58b00, 0xc000a0e0a0, 0x40b605, 0x1a18300, 0x1b94480)
        /usr/local/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc000a5c000, 0x1e5b640, 0xc000182018, 0x5, 0xc000182018, 0xd)
        /usr/local/go/src/crypto/tls/conn.go:801 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc000a5c000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:608 +0x115
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:576
crypto/tls.(*Conn).Read(0xc000a5c000, 0xc0005da000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1252 +0x15f
bufio.(*Reader).Read(0xc0003e8e40, 0xc0008d5298, 0x9, 0x9, 0xc000957e58, 0xc000600000, 0xc000600000)
        /usr/local/go/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x1e58920, 0xc0003e8e40, 0xc0008d5298, 0x9, 0x9, 0x9, 0x7f243d627530, 0xc0008b1d60, 0xc000600000)
        /usr/local/go/src/io/io.go:314 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:333
net/http.http2readFrameHeader(0xc0008d5298, 0x9, 0x9, 0x1e58920, 0xc0003e8e40, 0x0, 0x0, 0xc0007bbe10, 0xc00029ef48)
        /usr/local/go/src/net/http/h2_bundle.go:1477 +0x89
net/http.(*http2Framer).ReadFrame(0xc0008d5260, 0xc000c1e0c0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/h2_bundle.go:1735 +0xa5
net/http.(*http2clientConnReadLoop).run(0xc0008b1fa8, 0x0, 0x0)
        /usr/local/go/src/net/http/h2_bundle.go:8240 +0x8d
net/http.(*http2ClientConn).readLoop(0xc000aed800)
        /usr/local/go/src/net/http/h2_bundle.go:8168 +0x6f
created by net/http.(*http2Transport).newClientConn
        /usr/local/go/src/net/http/h2_bundle.go:7173 +0x66e
```

**Other details that may be helpful:**
With some deployments, the log tailing and following works, but most of the time its only hangs and after ~30 seconds I get a similar stacktrace as in the issue.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.4.8
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
VM
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
The bug occured with v1.17.4 kubectl version too.

- Docker version (use `docker version`):

On the Rancher server
```
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.8
 Git commit:        d7080c1
 Built:             Tue Feb 19 23:07:53 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       d7080c1
  Built:            Tue Feb 19 23:07:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

On management nodes:
```
Client:
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.14.3
 Git commit:        42e35e6
 Built:             Sun Jun  7 21:16:58 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.14.3
  Git commit:       42e35e6
  Built:            Sun Jun  7 00:00:00 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3
  GitCommit:
 runc:
  Version:          1.0.0-rc10+dev
  GitCommit:        fbdbaf85ecbc0e077f336c03062710435607dbf1
 docker-init:
  Version:          0.18.0
  GitCommit:
```

On worker nodes:
```
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.8
 Git commit:        d7080c1
 Built:             Tue Feb 19 23:07:53 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       d7080c1
  Built:            Tue Feb 19 23:07:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by hugbubby** [comment]
Have this problem too.
