### ISSUE TITLE
Super slow rancher-compose pulls and lots of exceptions in rancher/server

### ISSUE THREAD

**Issue by shakefu** [rancher/rancher#2897]
Not sure what's going on, but yesterday our rancher/server started behavior very oddly - any `rancher-compose pull` became super slow for some of our images. Others are still perfectly quick:

```
╒=== /tmp/compose ==
$ rancher-compose pull paster
INFO[0000] Checking for REPO/paster:latest on HOSTNAME...
INFO[0000] Checking for REPO/paster:latest on HOSTNAME...
INFO[0000] Checking for REPO/paster:latest on HOSTNAME...
INFO[0000] Checking for REPO/paster:latest on HOSTNAME...
INFO[1324] Finished REPO/paster:latest on HOSTNAME
INFO[1324] Finished REPO/paster:latest on HOSTNAME
INFO[1324] Finished REPO/paster:latest on HOSTNAME
INFO[1324] Finished REPO/paster:latest on HOSTNAME
INFO[1324] Finished pulling REPO/paster:latest
╒=== /tmp/compose ==
$ rancher-compose pull celery
INFO[0000] Checking for REPO/celery:latest on HOSTNAME...
INFO[0000] Checking for REPO/celery:latest on HOSTNAME...
INFO[0000] Checking for REPO/celery:latest on HOSTNAME...
INFO[0000] Checking for REPO/celery:latest on HOSTNAME...
INFO[0742] Finished REPO/celery:latest on HOSTNAME
INFO[0742] Finished REPO/celery:latest on HOSTNAME
INFO[0742] Finished REPO/celery:latest on HOSTNAME
INFO[0743] Finished REPO/celery:latest on HOSTNAME
INFO[0743] Finished pulling REPO/celery:latest
╒=== /tmp/compose ==
$ rancher-compose pull celerybeat
INFO[0000] Checking for REPO/celerybeat:latest on HOSTNAME...
INFO[0000] Checking for REPO/celerybeat:latest on HOSTNAME...
INFO[0000] Checking for REPO/celerybeat:latest on HOSTNAME...
INFO[0000] Checking for REPO/celerybeat:latest on HOSTNAME...
INFO[0995] Finished REPO/celerybeat:latest on HOSTNAME
INFO[0995] Finished REPO/celerybeat:latest on HOSTNAME
INFO[0995] Finished REPO/celerybeat:latest on HOSTNAME
INFO[0996] Finished REPO/celerybeat:latest on HOSTNAME
INFO[0996] Finished pulling REPO/celerybeat:latest
╒=== /tmp/compose ==
$ rancher-compose pull me-server
INFO[0000] Checking for REPO/me_server:latest on HOSTNAME...
INFO[0000] Checking for REPO/me_server:latest on HOSTNAME...
INFO[0000] Checking for REPO/me_server:latest on HOSTNAME...
INFO[0000] Checking for REPO/me_server:latest on HOSTNAME...
INFO[0002] Finished REPO/me_server:latest on HOSTNAME
INFO[0002] Finished REPO/me_server:latest on HOSTNAME
INFO[0002] Finished REPO/me_server:latest on HOSTNAME
INFO[0002] Finished REPO/me_server:latest on HOSTNAME
INFO[0002] Finished pulling REPO/me_server:latest
```

There also seems to be a ton of errors in the rancher/server container, of which this is a sample:

```
2015-12-03 01:35:57,160 ERROR [:] [] [] [] [cutorService-17] [i.c.p.e.e.i.ProcessEventListenerImpl] Unknown exception running process [instance.start:147118] on [4268] io.cattle.platform.eventing.exception.EventExecutionException: b3ec8c9c-b5dc-4beb-809b-20a702ecd9fb : 500 Server Error: Internal Server Error ("Cannot start container 4ae4c9f376aca6b0d9c14fb8e81f7868e9128209b82dd4b09d1fbf1ef3ea916c: [8] System error: Unit docker-4ae4c9f376aca6b0d9c14fb8e81f7868e9128209b82dd4b09d1fbf1ef3ea916c.scope already exists.")
	at io.cattle.platform.eventing.exception.EventExecutionException.fromEvent(EventExecutionException.java:53) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.agent.impl.RemoteAgentImpl.callSync(RemoteAgentImpl.java:72) ~[cattle-iaas-agent-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.agent.impl.RemoteAgentImpl.callSync(RemoteAgentImpl.java:158) ~[cattle-iaas-agent-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.common.handler.AgentBasedProcessHandler.callSync(AgentBasedProcessHandler.java:170) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.common.handler.AgentBasedProcessHandler.handleEvent(AgentBasedProcessHandler.java:156) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.common.handler.AgentBasedProcessHandler.handle(AgentBasedProcessHandler.java:101) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:456) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:396) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:390) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:390) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:520) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:323) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:259) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:256) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:188) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:161) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:110) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:107) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:107) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.executeStandardProcess(DefaultObjectProcessManager.java:29) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.common.handler.AbstractObjectProcessLogic.activate(AbstractObjectProcessLogic.java:31) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.instance.InstanceStart.compute(InstanceStart.java:220) ~[cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.instance.InstanceStart.handle(InstanceStart.java:85) ~[cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:456) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:396) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:390) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:390) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:520) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:323) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:259) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:256) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:188) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:161) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:110) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:107) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:107) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.eventing.impl.ProcessEventListenerImpl.processExecute(ProcessEventListenerImpl.java:66) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at sun.reflect.GeneratedMethodAccessor458.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_85]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_85]
	at io.cattle.platform.eventing.annotation.MethodInvokingListener$1.doWithLockNoResult(MethodInvokingListener.java:76) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.annotation.MethodInvokingListener.onEvent(MethodInvokingListener.java:72) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_85]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_85]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_85]
```

**Comment by shakefu** [comment]
I should add that if I ssh onto the host and just use `docker pull` it's super quick.

**Comment by shakefu** [comment]
More info: We're using rancher/server 0.47.0, rancher-compose 0.5.3.

We've seen it also now hang completely when trying to both pull or upgrade. Not sure where the issue is coming from.

We looked at our nginx logs to rancher/server and see a lot of this: ```
54.173.30.78 - 2523171F2A885B0EB0B3 [03/Dec/2015:01:44:40 +0000] "GET /v1/pulltasks/1go1469 HTTP/1.1" 200 477 "-" "Go 1.1 package http"
54.173.30.78 - 2523171F2A885B0EB0B3 [03/Dec/2015:01:44:40 +0000] "GET /v1/pulltasks/1go1467 HTTP/1.1" 200 474 "-" "Go 1.1 package http"
54.173.30.78 - 2523171F2A885B0EB0B3 [03/Dec/2015:01:44:40 +0000] "GET /v1/pulltasks/1go1442 HTTP/1.1" 200 476 "-" "Go 1.1 package http"
54.173.30.78 - 2523171F2A885B0EB0B3 [03/Dec/2015:01:44:40 +0000] "GET /v1/pulltasks/1go1441 HTTP/1.1" 200 476 "-" "Go 1.1 package http"
54.173.30.78 - 2523171F2A885B0EB0B3 [03/Dec/2015:01:44:40 +0000] "GET /v1/pulltasks/1go1468 HTTP/1.1" 200 477 "-" "Go 1.1 package http"
98.210.11.138 - 2523171F2A885B0EB0B3 [03/Dec/2015:01:44:41 +0000] "GET /v1/pulltasks/1go1474 HTTP/1.1" 200 474 "-" "Go 1.1 package http"
54.173.30.78 - 2523171F2A885B0EB0B3 [03/Dec/2015:01:44:41 +0000] "GET /v1/pulltasks/1go1439 HTTP/1.1" 200 474 "-" "Go 1.1 package http"
54.173.30.78 - 2523171F2A885B0EB0B3 [03/Dec/2015:01:44:41 +0000] "GET /v1/pulltasks/1go1467 HTTP/1.1" 200 474 "-" "Go 1.1 package http"
54.173.30.78 - 2523171F2A885B0EB0B3 [03/Dec/2015:01:44:41 +0000] "GET /v1/pulltasks/1go1469 HTTP/1.1" 200 477 "-" "Go 1.1 package http"
52.21.133.4 - 9FD361D4E6B7CD92AA3A [03/Dec/2015:01:44:41 +0000] "POST /v1/publish HTTP/1.1" 201 0 "-" "python-requests/2.8.1"
52.21.133.4 - 24660D57FBE68ECE2DAF [03/Dec/2015:01:44:41 +0000] "POST /v1/publish HTTP/1.1" 201 0 "-" "python-requests/2.8.1"
52.21.133.4 - 988BC6CB5388C3DDDBF6 [03/Dec/2015:01:44:41 +0000] "POST /v1/publish HTTP/1.1" 201 0 "-" "python-requests/2.8.1"
52.21.133.4 - 1F63EC350BCF22653B6B [03/Dec/2015:01:44:41 +0000] "POST /v1/publish HTTP/1.1" 201 0 "-" "python-requests/2.8.1"
52.21.133.4 - 9E1D6E396CA28FB4D65C [03/Dec/2015:01:44:41 +0000] "POST /v1/publish HTTP/1.1" 201 0 "-" "python-requests/2.8.1"
52.21.133.4 - D208B93CFE4444582ED5 [03/Dec/2015:01:44:41 +0000] "POST /v1/publish HTTP/1.1" 201 0 "-" "python-requests/2.8.1"
52.21.133.4 - 7B73E3C83E4AEF5A9679 [03/Dec/2015:01:44:41 +0000] "POST /v1/publish HTTP/1.1" 201 0 "-" "python-requests/2.8.1"
52.21.133.4 - F35015E3E786C0210D82 [03/Dec/2015:01:44:41 +0000] "POST /v1/publish HTTP/1.1" 201 0 "-" "python-requests/2.8.1"
52.21.133.4 - 1C467E31BBCECCB33FDF [03/Dec/2015:01:44:41 +0000] "POST /v1/publish HTTP/1.1" 201 0 "-" "python-requests/2.8.1"
52.21.133.4 - 8EC74884855C08F280A1 [03/Dec/2015:01:44:41 +0000] "POST /v1/publish HTTP/1.1" 201 0 "-" "python-requests/2.8.1"
54.173.30.78 - 2523171F2A885B0EB0B3 [03/Dec/2015:01:44:41 +0000] "GET /v1/pulltasks/1go1442 HTTP/1.1" 200 476 "-" "Go 1.1 package http"
54.173.30.78 - 2523171F2A885B0EB0B3 [03/Dec/2015:01:44:41 +0000] "GET /v1/pulltasks/1go1441 HTTP/1.1" 200 476 "-" "Go 1.1 package http"
54.173.30.78 - 2523171F2A885B0EB0B3 [03/Dec/2015:01:44:41 +0000] "GET /v1/pulltasks/1go1468 HTTP/1.1" 200 477 "-" "Go 1.1 package http"```

The POST /v1/publish seems to be happening about 10/sec, but I can't find any documentation on what that endpoint is doing.

The GET /v1/pulltasks/[id] is bursting but quite frequent too. I was able to look at /v1/pulltasks in the API and got a list of over 1500 status: "active" pulltasks. I'm not sure if this is normal - that they might stay around after completing, or indicative of some other issue. I also couldn't find any documentation on that endpoint.

**Comment by shakefu** [comment]
We were able to fix this by updating to the latest Docker and clearing out a couple hundred dangling images.
