### ISSUE TITLE
Cannot deploy an EKS cluster, Panic seen in Rancher

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29085]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a hosted EKS cluster from Rancher (default values choosen except for Subnet and Security group)
- API request on a created gives a 500 Error
- Panic in rancher logs:

```
2020/09/22 16:34:09 [ERROR] Panic serving api request: 
goroutine 21157 [running]:
runtime/debug.Stack(0xc001aadcd0, 0x3bf9d00, 0x732a500)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/rancher/norman/api.(*Server).ServeHTTP.func1(0x4e39b40, 0xc00559fe40)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200908202416-992a35eef40f/api/server.go:175 +0x7a
panic(0x3bf9d00, 0x732a500)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/rancher/rancher/pkg/api/norman/customization/cluster.(*Validator).validateEKSConfig(0xc004130420, 0xc0029590e0, 0xc0060001e0, 0xc0074c9800, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/api/norman/customization/cluster/validator.go:354 +0xd20
github.com/rancher/rancher/pkg/api/norman/customization/cluster.(*Validator).Validator(0xc004130420, 0xc0029590e0, 0xc004d230e0, 0xc0060001e0, 0x0, 0xc0060001e0)
	/go/src/github.com/rancher/rancher/pkg/api/norman/customization/cluster/validator.go:75 +0x3e9
github.com/rancher/norman/parse/builder.(*Builder).Construct(0xc0060001b0, 0xc004d230e0, 0xc006000000, 0x44ab469, 0x6, 0x44a7e7d, 0x4, 0xc006d09501)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200908202416-992a35eef40f/parse/builder/builder.go:58 +0xe2
github.com/rancher/norman/api/handler.ParseAndValidateBody(0xc0029590e0, 0xc001aaee01, 0x2a9ed3e, 0xc001d6dd78, 0xc0029590e0)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200908202416-992a35eef40f/api/handler/validate.go:36 +0x233
github.com/rancher/norman/api/handler.CreateHandler(0xc0029590e0, 0x4673e20, 0xc004d230e0, 0x0)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200908202416-992a35eef40f/api/handler/create.go:13 +0x34
github.com/rancher/norman/api.(*Server).handle(0xc0058044d0, 0x4e39b40, 0xc00559fe40, 0xc005fe5700, 0x40a808, 0x4036b20, 0xc00559fe40)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200908202416-992a35eef40f/api/server.go:249 +0x276
github.com/rancher/norman/api.(*Server).ServeHTTP(0xc0058044d0, 0x4e39b40, 0xc00559fe40, 0xc005fe5700)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200908202416-992a35eef40f/api/server.go:180 +0x7d
github.com/rancher/apiserver/pkg/middleware.ContentType.func1(0x4e26140, 0xc007059950, 0xc005fe5700)
	/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20200730050206-780f0e4c5f48/pkg/middleware/content.go:33 +0x93
net/http.HandlerFunc.ServeHTTP(0xc005f14880, 0x4e26140, 0xc007059950, 0xc005fe5700)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/rancher/apiserver/pkg/middleware.Gzip.func1(0x4e38e00, 0xc00714fdc0, 0xc005fe5700)
	/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20200730050206-780f0e4c5f48/pkg/middleware/gzip.go:60 +0x1d5
net/http.HandlerFunc.ServeHTTP(0xc005f148a0, 0x4e38e00, 0xc00714fdc0, 0xc005fe5700)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/rancher/rancher/pkg/auth/requests.authHeaderHandler.ServeHTTP(0x4dc5c60, 0xc005f148a0, 0x4e38e00, 0xc00714fdc0, 0xc005fe5700)
	/go/src/github.com/rancher/rancher/pkg/auth/requests/filter.go:49 +0x4d3
github.com/rancher/rancher/pkg/rbac.NewAccessControlHandler.func1.1(0x4e38e00, 0xc00714fdc0, 0xc005fe5600)
	/go/src/github.com/rancher/rancher/pkg/rbac/user_based.go:33 +0x1ae
net/http.HandlerFunc.ServeHTTP(0xc006d09540, 0x4e38e00, 0xc00714fdc0, 0xc005fe5600)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/rancher/steve/pkg/auth.ToMiddleware.func1.1(0x4e38e00, 0xc00714fdc0, 0xc005fe5500)
	/go/pkg/mod/github.com/rancher/steve@v0.0.0-20200919001914-8db386d2253e/pkg/auth/filter.go:156 +0x1bd
net/http.HandlerFunc.ServeHTTP(0xc007059830, 0x4e38e00, 0xc00714fdc0, 0xc005fe5500)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00184c300, 0x4e38e00, 0xc00714fdc0, 0xc005fe5300)
	/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00184c180, 0x4e38e00, 0xc00714fdc0, 0xc005fe5100)
	/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2
github.com/rancher/rancher/pkg/multiclustermanager.(*DeferredServer).Middleware.func1(0x4e38e00, 0xc00714fdc0, 0xc005fe5100)
	/go/src/github.com/rancher/rancher/pkg/multiclustermanager/deferred.go:77 +0x98
net/http.HandlerFunc.ServeHTTP(0xc000833440, 0x4e38e00, 0xc00714fdc0, 0xc005fe5100)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc001025500, 0x4e38e00, 0xc00714fdc0, 0xc005fe4f00)
	/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2
github.com/rancher/rancher/pkg/api/steve/proxy.NewProxyMiddleware.func1.1(0x4e38e00, 0xc00714fdc0, 0xc005fe4f00)
	/go/src/github.com/rancher/rancher/pkg/api/steve/proxy/proxy.go:75 +0x60
net/http.HandlerFunc.ServeHTTP(0xc000833460, 0x4e38e00, 0xc00714fdc0, 0xc005fe4f00)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/rancher/rancher/pkg/api/steve/proxy.RewriteLocalCluster.func1(0x4e38e00, 0xc00714fdc0, 0xc005fe4f00)
	/go/src/github.com/rancher/rancher/pkg/api/steve/proxy/proxy.go:43 +0xef
net/http.HandlerFunc.ServeHTTP(0xc000833480, 0x4e38e00, 0xc00714fdc0, 0xc005fe4f00)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/rancher/rancher/pkg/websocket.websocketHandler.ServeHTTP(0x4dc5c60, 0xc000833480, 0x4e38e00, 0xc00714fdc0, 0xc005fe4f00)
	/go/src/github.com/rancher/rancher/pkg/websocket/handler.go:35 +0xa0
github.com/rancher/apiserver/pkg/middleware.ContentTypeOptions.func1(0x4e38e00, 0xc00714fdc0, 0xc005fe4f00)
	/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20200730050206-780f0e4c5f48/pkg/middleware/cache.go:47 +0x131
net/http.HandlerFunc.ServeHTTP(0xc0008334a0, 0x4e38e00, 0xc00714fdc0, 0xc005fe4f00)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/rancher/rancher/pkg/auth/audit.auditHandler.ServeHTTP(0x4dc5c60, 0xc0008334a0, 0x0, 0x4e38e00, 0xc00714fdc0, 0xc005fe4f00)
	/go/src/github.com/rancher/rancher/pkg/auth/audit/filter.go:32 +0x522
github.com/rancher/steve/pkg/auth.ToMiddleware.func1.1(0x4e38e00, 0xc00714fdc0, 0xc0073ea000)
	/go/pkg/mod/github.com/rancher/steve@v0.0.0-20200919001914-8db386d2253e/pkg/auth/filter.go:156 +0x1bd
net/http.HandlerFunc.ServeHTTP(0xc00110b410, 0x4e38e00, 0xc00714fdc0, 0xc0073ea000)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/rancher/dynamiclistener/server.wrapHandler.func1(0x4e38e00, 0xc00714fdc0, 0xc0073ea000)
	/go/pkg/mod/github.com/rancher/dynamiclistener@v0.2.1-0.20200910203214-85f32491cb09/server/server.go:187 +0x95
net/http.HandlerFunc.ServeHTTP(0xc000e42450, 0x4e38e00, 0xc00714fdc0, 0xc0073ea000)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/rancher/dynamiclistener.HTTPRedirect.func1(0x4e38e00, 0xc00714fdc0, 0xc0073ea000)
	/go/pkg/mod/github.com/rancher/dynamiclistener@v0.2.1-0.20200910203214-85f32491cb09/redirect.go:20 +0x20a
net/http.HandlerFunc.ServeHTTP(0xc00218a9e0, 0x4e38e00, 0xc00714fdc0, 0xc0073ea000)
	/usr/local/go/src/net/http/server.go:2041 +0x44
net/http.serverHandler.ServeHTTP(0xc000762620, 0x4e38e00, 0xc00714fdc0, 0xc0073ea000)
	/usr/local/go/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc005b25900, 0x4e4de00, 0xc005f6a040)
	/usr/local/go/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2962 +0x35c
```

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `0ccce450`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted EKS
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by aaronRancher** [comment]
This behavior is also seen with EKS imported clusters.
`rancher\rancher:master-head` `version 0ccce45`

Cluster cannot be imported:
![Screen Shot 2020-09-22 at 9 53 28 AM](https://user-images.githubusercontent.com/57409052/93913656-3ca84a00-fcba-11ea-8a17-96ef16fcb0fe.png)
Observed the same panic in Rancher server.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `05164366`**

Able to bring up a Hosted EKS cluster on rancher.

**Comment by aaronRancher** [comment]
On `rancher\rancher:master-head` `version 67e24f2`

Able to import an EKS cluster.
