### ISSUE TITLE
Exception updating public endpoint during host.remove

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#2927]
Steps to reproduce:

1) Have 2 hosts in the system.
2) Create service with global=true and port opened. 2 containers should start.
3) Remove one of the hosts. Following exception occurs:

```
java.lang.NullPointerException
    at io.cattle.platform.process.lock.HostEndpointsUpdateLock.<init>(HostEndpointsUpdateLock.java:9)
    at io.cattle.platform.servicediscovery.service.impl.ServiceDiscoveryServiceImpl.propagatePublicEndpoint(ServiceDiscoveryServiceImpl.java:354)
    at io.cattle.platform.servicediscovery.process.PortActivateDeactivatePostListener.handle(PortActivateDeactivatePostListener.java:72)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:456)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:396)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:1)
    at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:390)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:523)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:323)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:259)
    at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7)
    at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:1)
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
    at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl
```

**Comment by sangeethah** [comment]
Tested with server version - v0.49.0-rc3

1) Had 4 hosts in the system.
2) Create service with global=true and port opened. 4 containers should start.service's endpoint has 4   entries.
3) Remove one of the hosts. 

There is no NullPointer Exception in logs and the service's endpoint has only 3 entries now.
