### ISSUE TITLE
Panic in rancher when upgrading k8s version of cluster with drain enabled

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29381]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- (this was an upgraded rancher HA setup from 2.4.8 to 2.5.0-rc7)
- Upgrade k8s version of the cluster from 1.18.8 to 1.18.9 (custom rke cluster - 5 nodes, 1 etcd, 1 control and 3 worker nodes)
- Panic in rancher server and rancher is seen restarting
- Rancher logs:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2994c5d]

goroutine 10154 [running]:
github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer.getFlags(0xc001c458c0, 0xc008763b00, 0x4690790, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer/cordonfieldssyncer.go:243 +0x1cd
github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer.(*nodeDrain).drain.func1(0x44474e0, 0xc003515b00, 0x44c8a6c, 0x7)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer/cordonfieldssyncer.go:161 +0x13d
github.com/rancher/norman/condition.Cond.doInternal(0x44c8a6c, 0x7, 0x4e25301, 0x4e253e0, 0xc003515b00, 0xc002becf38, 0x6, 0x3906a00, 0xc003499db0, 0x198)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200930000340-693d65aaffe3/condition/condition.go:212 +0x97
github.com/rancher/norman/condition.Cond.do2(0x44c8a6c, 0x7, 0x44c8a01, 0x4e253e0, 0xc003515b00, 0xc002becf38, 0x4065ea, 0xc0047997a0, 0x0, 0xc008702000, ...)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200930000340-693d65aaffe3/condition/condition.go:181 +0x1d8
github.com/rancher/norman/condition.Cond.do(...)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200930000340-693d65aaffe3/condition/condition.go:170
github.com/rancher/norman/condition.Cond.DoUntilTrue(0x44c8a6c, 0x7, 0x4e253e0, 0xc003515b00, 0xc002becf38, 0x0, 0x0, 0x0, 0xc0072dc520)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200930000340-693d65aaffe3/condition/condition.go:136 +0xb3
github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer.(*nodeDrain).drain(0xc004c8d040, 0x4e88f60, 0xc008702080, 0xc003515b00, 0xc005d05bc0, 0xf, 0xc0086ed770)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer/cordonfieldssyncer.go:148 +0x1a5
created by github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer.(*nodeDrain).drainNode
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer/cordonfieldssyncer.go:99 +0x335
```

**Expected Result:**
No panic should be seen when drain is enabled

**Other details that may be helpful:**
- API request sent contains:
```
drain: "true"
maxUnavailableControlplane: "1"
maxUnavailableUnit: "percentage"
maxUnavailableWorker: "10%"
nodeDrainInput: {force: false, deleteLocalData: false}
deleteLocalData: false
force: false
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.0-rc7
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom RKE
- Kubernetes version (use `kubectl version`):

```
1.18.9
```

**Comment by jiaqiluo** [comment]
This bug is reproduced 

- run Rancher v2.4.8 in HA mode in an RKE cluster v1.18.6
- add a custom cluster 1.18.8 (custom rke cluster - 5 nodes, 1 etcd, 1 control and 3 worker nodes)
- upgrade rancher to 2.5.0-rc8
- upgrade the custom cluster with the option `drain node` YES
<img width="965" alt="Screen Shot 2020-10-05 at 1 58 02 PM" src="https://user-images.githubusercontent.com/6218999/95132977-72671d00-0715-11eb-846a-3f83f5372e77.png">

Results:
- Rancher pods start crashing with the following kind of errors
```
[rancher-bbc54ccff-fbpxz] panic: runtime error: invalid memory address or nil pointer dereference
[rancher-bbc54ccff-fbpxz] [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2994c5d]
[rancher-bbc54ccff-fbpxz]
[rancher-bbc54ccff-fbpxz] goroutine 18385 [running]:
[rancher-bbc54ccff-fbpxz] github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer.getFlags(0xc00a3173b0, 0xc009b29b00, 0x4690788, 0x0)
[rancher-bbc54ccff-fbpxz] 	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer/cordonfieldssyncer.go:243 +0x1cd
[rancher-bbc54ccff-fbpxz] github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer.(*nodeDrain).drain.func1(0x44474e0, 0xc0086a6d80, 0x44c8a6c, 0x7)
[rancher-bbc54ccff-fbpxz] 	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer/cordonfieldssyncer.go:161 +0x13d
[rancher-bbc54ccff-fbpxz] github.com/rancher/norman/condition.Cond.doInternal(0x44c8a6c, 0x7, 0x4e25301, 0x4e253e0, 0xc0086a6d80, 0xc0098b6f38, 0x6, 0x3906a00, 0xc00d385db0, 0x198)
[rancher-bbc54ccff-fbpxz] 	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200930000340-693d65aaffe3/condition/condition.go:212 +0x97
[rancher-bbc54ccff-fbpxz] github.com/rancher/norman/condition.Cond.do2(0x44c8a6c, 0x7, 0x44c8a01, 0x4e253e0, 0xc0086a6d80, 0xc0098b6f38, 0x4065ea, 0xc009155b60, 0x0, 0xc00670b000, ...)
[rancher-bbc54ccff-fbpxz] 	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200930000340-693d65aaffe3/condition/condition.go:181 +0x1d8
[rancher-bbc54ccff-fbpxz] github.com/rancher/norman/condition.Cond.do(...)
[rancher-bbc54ccff-fbpxz] 	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200930000340-693d65aaffe3/condition/condition.go:170
[rancher-bbc54ccff-fbpxz] github.com/rancher/norman/condition.Cond.DoUntilTrue(0x44c8a6c, 0x7, 0x4e253e0, 0xc0086a6d80, 0xc0098b6f38, 0x0, 0x203001, 0x203001, 0x390a4c0)
[rancher-bbc54ccff-fbpxz] 	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200930000340-693d65aaffe3/condition/condition.go:136 +0xb3
[rancher-bbc54ccff-fbpxz] github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer.(*nodeDrain).drain(0xc0051d25a0, 0x4e88f60, 0xc00670b080, 0xc0086a6d80, 0xc00a4403f0, 0xe, 0xc00b67c640)
[rancher-bbc54ccff-fbpxz] 	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer/cordonfieldssyncer.go:148 +0x1a5
[rancher-bbc54ccff-fbpxz] created by github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer.(*nodeDrain).drainNode
[rancher-bbc54ccff-fbpxz] 	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer/cordonfieldssyncer.go:99 +0x335
```
- UI is not accessible anymore with `503 Service Temporarily Unavailable`

**Comment by sowmyav27** [comment]
**verified on an upgrade from 2.4.8 to 2.5-head - commit id: `65f3525cd`**

- On 2.4.8 - deploy HA rke cluster and a custom RKE cluster (through API) k8s - 1.18.8
- upgrade rancher to 2.5-head.
- Upgrade k8s version of the cluster to 1.18.9
- API request sent ocntains:
```
upgradeStrategy: {maxUnavailableControlplane: "1", maxUnavailableWorker: "10%", drain: "true",…}
drain: "true"
maxUnavailableControlplane: "1"
maxUnavailableUnit: "percentage"
maxUnavailableWorker: "10%"
nodeDrainInput: {force: false, deleteLocalData: false}
deleteLocalData: false
force: false
```
- Cluster upgrades successfully and no panic/restart is seen in Rancher.

**Comment by sowmyav27** [comment]
**Verified on an upgrade form 2.4.8 to master-head commit id: `6bc32da`**

- On 2.4.8 - deploy HA rke cluster and a custom RKE cluster (through API) k8s - 1.18.8
- upgrade rancher to 2.5-head.
- Upgrade k8s version of the cluster to 1.18.9
- API request sent ocntains:
```
upgradeStrategy: {maxUnavailableControlplane: "1", maxUnavailableWorker: "10%", drain: "true",…}
drain: "true"
maxUnavailableControlplane: "1"
maxUnavailableUnit: "percentage"
maxUnavailableWorker: "10%"
nodeDrainInput: {force: false, deleteLocalData: false}
deleteLocalData: false
force: false
```
- Cluster upgrades successfully and no panic/restart is seen in Rancher.

**Comment by jiaqiluo** [comment]
verified on an upgrade from 2.4.8 to 2.5-head 65f3525cd


- in v2.4.8 deploy Rancher HA in a rke cluster
- add several custom RKE clusters (through API) k8s - 1.18.8
- upgrade rancher to 2.5-head
- Upgrade k8s version of the cluster to 1.18.9 

All clusters are upgraded, and no restart/panic for rancher nodes
