### ISSUE TITLE
OnConfigMapChange panic seen in agent when not being able to process helm configmap/secrets properly

### ISSUE THREAD

**Issue by shanmugakarna** [rancher/rancher#29460]
Cattle Agent is failing with following error on Amazon EKS Cluster

```
time="2020-10-09T22:18:29Z" level=info msg="Watching metadata for monitoring.coreos.com/v1, Kind=ServiceMonitor"
E1009 22:18:42.028702       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1361 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3be6140, 0x731b4b0)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/runtime/runtime.go:48 +0x82
panic(0x3be6140, 0x731b4b0)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/rancher/rancher/pkg/controllers/dashboard/helm.(*appHandler).OnConfigMapChange(0xc000d23040, 0xc001375800, 0x1b, 0xc004c99f00, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/helm/apps.go:124 +0xd4
github.com/rancher/wrangler/pkg/generated/controllers/core/v1.FromConfigMapHandlerToHandler.func1(0xc001375800, 0x1b, 0x4df5de0, 0xc004c99f00, 0xc0061c0d80, 0xc00681a501, 0x0, 0xc002f03be0)
	/go/pkg/mod/github.com/rancher/wrangler@v0.7.2/pkg/generated/controllers/core/v1/configmap.go:102 +0x65
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc000612c80, 0xc001375800, 0x1b, 0x4df5de0, 0xc004c99f00, 0x4035e3, 0x6f000000004097ab, 0xc000500000, 0x3fa4b40)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*sharedHandler).OnChange(0xc003cb75c0, 0xc001375800, 0x1b, 0x4df5de0, 0xc004c99f00, 0xc003fb5c01, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedhandler.go:65 +0x14a
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000c0f1e0, 0xc001375800, 0x1b, 0xc002577560, 0xc002f03d50)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:210 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000c0f1e0, 0x38de060, 0xc00038aa70, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:192 +0xd7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000c0f1e0, 0x203001)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:169 +0x51
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc000c0f1e0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:158 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc001d4e740)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001d4e740, 0x4dc4160, 0xc00415df80, 0xc003cdc101, 0xc00077c300)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001d4e740, 0x3b9aca00, 0x0, 0x1, 0xc00077c300)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc001d4e740, 0x3b9aca00, 0xc00077c300)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:129 +0x31f
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x277a974]

goroutine 1361 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/runtime/runtime.go:55 +0x105
panic(0x3be6140, 0x731b4b0)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/rancher/rancher/pkg/controllers/dashboard/helm.(*appHandler).OnConfigMapChange(0xc000d23040, 0xc001375800, 0x1b, 0xc004c99f00, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/helm/apps.go:124 +0xd4
github.com/rancher/wrangler/pkg/generated/controllers/core/v1.FromConfigMapHandlerToHandler.func1(0xc001375800, 0x1b, 0x4df5de0, 0xc004c99f00, 0xc0061c0d80, 0xc00681a501, 0x0, 0xc002f03be0)
	/go/pkg/mod/github.com/rancher/wrangler@v0.7.2/pkg/generated/controllers/core/v1/configmap.go:102 +0x65
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc000612c80, 0xc001375800, 0x1b, 0x4df5de0, 0xc004c99f00, 0x4035e3, 0x6f000000004097ab, 0xc000500000, 0x3fa4b40)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*sharedHandler).OnChange(0xc003cb75c0, 0xc001375800, 0x1b, 0x4df5de0, 0xc004c99f00, 0xc003fb5c01, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedhandler.go:65 +0x14a
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000c0f1e0, 0xc001375800, 0x1b, 0xc002577560, 0xc002f03d50)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:210 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000c0f1e0, 0x38de060, 0xc00038aa70, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:192 +0xd7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000c0f1e0, 0x203001)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:169 +0x51
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc000c0f1e0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:158 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc001d4e740)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001d4e740, 0x4dc4160, 0xc00415df80, 0xc003cdc101, 0xc00077c300)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001d4e740, 0x3b9aca00, 0x0, 0x1, 0xc00077c300)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc001d4e740, 0x3b9aca00, 0xc00077c300)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:129 +0x31f
```

**Rancher Version:** v2.5.1
**EKS Cluster Version:** v1.16.13-eks-2ba888

**Comment by aaronRancher** [comment]
Was not able to repro this issue with Rancher server `rancher\rancher:v2.5.1`

Steps:
Import an EKS cluster running k8s `v1.16.13-eks-2ba888`

Result:
Cluster is made available:
![Screen Shot 2020-10-09 at 4 45 02 PM](https://user-images.githubusercontent.com/57409052/95639985-61891500-0a4f-11eb-8e31-0a61c3bc28ea.png)
No panic seen in Cattle Agent.

**Comment by shanmugakarna** [comment]
This is specific to single cluster, I have few more clusters running the same version, all upgraded from 2.4.5 and they all work fine. Only one of the cluster errors out like above.

I tried cleaning up all rancher related resources and re-import the cluster, still no luck. Some guidance on where to look further on such error would be helpful.

**Comment by ibuildthecloud** [comment]
This issue will most likely happen when a configmap is deleted in the downstream cluster.  It is not specific to EKS.

**Comment by ibuildthecloud** [comment]
This is not specific to EKS.  This is caused by failing to process a configmap that has helm data.

**Comment by rbq** [comment]
I believe I have the same issue with Rancher 2.5.2 (standalone Docker container), used to manage a single bare-metal cluster (K8s v1.19.2-rancher1-1).

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x289aa4a]

goroutine 7030 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/runtime/runtime.go:55 +0x105
panic(0x3c138c0, 0x73706a0)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/rancher/rancher/pkg/controllers/managementuser/alert/watcher.(*ClusterScanWatcher).isAlertRuleMatching(...)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/alert/watcher/cluster_scan.go:110
github.com/rancher/rancher/pkg/controllers/managementuser/alert/watcher.(*ClusterScanWatcher).Sync(0xc00d96bc70, 0xc01224f830, 0x22, 0xc0222d2300, 0x44c3ef8, 0x4, 0x44d3772, 0xb)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/alert/watcher/cluster_scan.go:79 +0x30a
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*clusterScanController).AddClusterScopedHandler.func1(0xc01224f830, 0x22, 0x442dfa0, 0xc0222d2300, 0xc02224fb20, 0x3, 0x3, 0x0)
	/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_cluster_scan_controller.go:182 +0x79
github.com/rancher/norman/controller.(*genericController).AddHandler.func1(0xc01224f830, 0x22, 0x4e247a0, 0xc0222d2300, 0x4e247a0, 0xc0222d2300, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200930000340-693d65aaffe3/controller/generic_controller.go:62 +0x221
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc00eb509f0, 0xc01224f830, 0x22, 0x4e247a0, 0xc0222d2300, 0x4e247a0, 0xc0222d2300, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*sharedHandler).OnChange(0xc00c375ad0, 0xc01224f830, 0x22, 0x4e247a0, 0xc0222d2300, 0xc00e960301, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedhandler.go:65 +0x14a
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000bfb290, 0xc01224f830, 0x22, 0xc00e95e840, 0xc015946d50)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:210 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000bfb290, 0x390a700, 0xc02167aec0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:192 +0xd7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000bfb290, 0x203003)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:169 +0x51
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc000bfb290)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:158 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00e958c10)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00e958c10, 0x4dfa100, 0xc00d07ee10, 0x3a22636570732201, 0xc00153de00)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00e958c10, 0x3b9aca00, 0x0, 0x3136386664623101, 0xc00153de00)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc00e958c10, 0x3b9aca00, 0xc00153de00)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:129 +0x31f
```

**Comment by superseb** [comment]
@rbq this is a different panic, please file a new issue with your environment details (especially the upgrade path and how many/what clusters you are managing and if you are using cluster scans/alerting)

**Comment by mrajashree** [comment]
I think we can validate the fix around the panic by editing a Helm Secret to have some incorrect value

**Comment by sowmyav27** [comment]
Steps to reproduce as per @mrajashree 

- Launch an app
- Go to “Secrets” and find the helm secret created for the app. If you launched datadog app, the Secret should be sh.helm.release.v1.datadog.v1
- Edit the data.release field to have some incorrect value, easiest way is to remove the first 4 characters so you can still save base 64 encoded secret
- Without the fix you should see the panic for OnSecretChange
- With fix you should see an error like this in logs
```
[ERROR] Failed to process secret default/sh.helm.release.v1.datadog.v1 for helm data: illegal base64 data at input byte 75576
having said this, I don’t know what caused the eks panic
```

**Comment by sowmyav27** [comment]
**Reproduced the issue on 2.5.1**

- Launch an app
- Go to “Secrets” and find the helm secret created for the app. If you launched datadog app, the Secret should be sh.helm.release.v1.datadog.v1
- Edit the data.release field to have some incorrect value, easiest way is to remove the first 4 characters so you can still save base 64 encoded secret

```
time="2020-10-29T05:29:45Z" level=info msg="Starting /v1, Kind=ConfigMap controller"
time="2020-10-29T05:29:45Z" level=info msg="Starting apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition controller"
I1029 05:29:45.278833       1 leaderelection.go:253] successfully acquired lease kube-system/cattle-agent-controllers
time="2020-10-29T05:29:45Z" level=info msg="Listening on 127.0.0.1:6080"
E1029 05:29:45.349149       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1188 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3be6140, 0x731b4b0)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/runtime/runtime.go:48 +0x82
panic(0x3be6140, 0x731b4b0)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/rancher/rancher/pkg/controllers/dashboard/helm.(*appHandler).OnSecretChange(0xc00007cff0, 0xc0021fd0e0, 0x25, 0xc0021f0dc0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/helm/apps.go:149 +0xd4
github.com/rancher/wrangler/pkg/generated/controllers/core/v1.FromSecretHandlerToHandler.func1(0xc0021fd0e0, 0x25, 0x4df66e0, 0xc0021f0dc0, 0xc0007e77d0, 0xc0007e7701, 0xc0007e77d0, 0xc001836be0)
	/go/pkg/mod/github.com/rancher/wrangler@v0.7.2/pkg/generated/controllers/core/v1/secret.go:102 +0x65
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc0007e7060, 0xc0021fd0e0, 0x25, 0x4df66e0, 0xc0021f0dc0, 0x4035e3, 0xa7000000004097ab, 0xc000400000, 0x3fa4b40)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*sharedHandler).OnChange(0xc001c064e0, 0xc0021fd0e0, 0x25, 0x4df66e0, 0xc0021f0dc0, 0xc00260af01, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedhandler.go:65 +0x14a
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc0004d6580, 0xc0021fd0e0, 0x25, 0xc0019e0390, 0xc001836d50)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:210 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0004d6580, 0x38de060, 0xc0007e77e0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:192 +0xd7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0004d6580, 0x203001)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:169 +0x51
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc0004d6580)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:158 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc001ddd6a0)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001ddd6a0, 0x4dc4160, 0xc0019e0420, 0x1, 0xc0022ef4a0)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001ddd6a0, 0x3b9aca00, 0x0, 0x1, 0xc0022ef4a0)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc001ddd6a0, 0x3b9aca00, 0xc0022ef4a0)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:129 +0x31f
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x277adf4]
goroutine 1188 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/runtime/runtime.go:55 +0x105
panic(0x3be6140, 0x731b4b0)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/rancher/rancher/pkg/controllers/dashboard/helm.(*appHandler).OnSecretChange(0xc00007cff0, 0xc0021fd0e0, 0x25, 0xc0021f0dc0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/helm/apps.go:149 +0xd4
github.com/rancher/wrangler/pkg/generated/controllers/core/v1.FromSecretHandlerToHandler.func1(0xc0021fd0e0, 0x25, 0x4df66e0, 0xc0021f0dc0, 0xc0007e77d0, 0xc0007e7701, 0xc0007e77d0, 0xc001836be0)
	/go/pkg/mod/github.com/rancher/wrangler@v0.7.2/pkg/generated/controllers/core/v1/secret.go:102 +0x65
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc0007e7060, 0xc0021fd0e0, 0x25, 0x4df66e0, 0xc0021f0dc0, 0x4035e3, 0xa7000000004097ab, 0xc000400000, 0x3fa4b40)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*sharedHandler).OnChange(0xc001c064e0, 0xc0021fd0e0, 0x25, 0x4df66e0, 0xc0021f0dc0, 0xc00260af01, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedhandler.go:65 +0x14a
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc0004d6580, 0xc0021fd0e0, 0x25, 0xc0019e0390, 0xc001836d50)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:210 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0004d6580, 0x38de060, 0xc0007e77e0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:192 +0xd7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0004d6580, 0x203001)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:169 +0x51
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc0004d6580)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:158 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc001ddd6a0)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001ddd6a0, 0x4dc4160, 0xc0019e0420, 0x1, 0xc0022ef4a0)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001ddd6a0, 0x3b9aca00, 0x0, 0x1, 0xc0022ef4a0)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc001ddd6a0, 0x3b9aca00, 0xc0022ef4a0)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:129 +0x31f
```

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:v2.5-head` `version 0465f04` and `rancher\rancher:master-head` `version d61a1a4`

- Launch an app
- Go to “Secrets” and find the helm secret created for the app. If you launched datadog app, the Secret should be sh.helm.release.v1.datadog.v1
- Edit the data.release field to have some incorrect value, easiest way is to remove the first 4 characters so you can still save base 64 encoded secret
- Cattle-cluster agent will show an error:

```
time="2020-10-29T22:46:13Z" level=error msg="Failed to process secret test-p-9zspd/sh.helm.release.v1.test-p-9zspd.v1 for helm data: illegal base64 data at input byte 51320"
```
