### ISSUE TITLE
Update: Rancher 2.5: alone install k3s and can't start without privileged

### ISSUE THREAD

**Issue by CSRedRat** [rancher/rancher#29513]
**bug:**

**Steps to reproduce:**

1. Install Rancher Docker Admin on A server.
2. Install from Admin with rancher-docker-agent K8S cluster on B server (without ingress, replaced gitlab managed apps ingress)
3. update docker rancher Admin on A server to 2.5.
3.1. rancher can't start without privileged:
```
rancher    | ERROR: Rancher must be ran with the --privileged flag when running outside of Kubernetes
rancher    | ERROR: Rancher must be ran with the --privileged flag when running outside of Kubernetes
*looped
```
3.2. add privileged: true to docker-compose.yml and start rancher docker Admin
4. update from docker Admin B-cluster config to kubernetes 1.19.2
!!!
5. Rancher alone install k3s on A-server
6. update k3s to 1.19.2
!!!

7. stop Rancher docker Admin
```
curl -sfL https://get.k3s.io | sh
/usr/local/bin/k3s-uninstall.sh
```
9. Rancher again require privilege to start docker admin:
```
rancher    | ERROR: Rancher must be ran with the --privileged flag when running outside of Kubernetes
rancher    | ERROR: Rancher must be ran with the --privileged flag when running outside of Kubernetes
rancher    | ERROR: Rancher must be ran with the --privileged flag when running outside of Kubernetes
rancher    | ERROR: Rancher must be ran with the --privileged flag when running outside of Kubernetes
rancher    | ERROR: Rancher must be ran with the --privileged flag when running outside of Kubernetes
rancher    | ERROR: Rancher must be ran with the --privileged flag when running outside of Kubernetes
```

**Result:**
loop installation k3s without possibility remove 

**Environment information**
- Rancher version 2.5 (latest)
- K8S 1.19.2
- k3s 1.19.2
- Ubuntu 18.04

**Cluster information**
- Cluster type Hosted
- Machine type virtual in ESXi on bare-metal
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-09-30T19:31:27Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
docker version
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Comment by CSRedRat** [comment]
is there an option to disable k3s installation with rancher docker?

-  k3s loop configuring/update after install
- can't downgrade k3s kubernetes version after upgrade version up

**Comment by rezicosta** [comment]
@CSRedRat Did u manage to solve it?

**Comment by CSRedRat** [comment]
> @CSRedRat Did u manage to solve it?

No. Downgrade to 2.4.8 failed:
```
rancher    | I1016 08:39:19.246783      37 controllermanager.go:533] Started "namespace"
rancher    | I1016 08:39:19.247435      37 namespace_controller.go:200] Starting namespace controller
rancher    | I1016 08:39:19.249984      37 shared_informer.go:197] Waiting for caches to sync for namespace
rancher    | I1016 08:39:19.266990      37 controllermanager.go:533] Started "csrsigning"
rancher    | I1016 08:39:19.267459      37 certificate_controller.go:118] Starting certificate controller "csrsigning"
rancher    | I1016 08:39:19.267503      37 shared_informer.go:197] Waiting for caches to sync for certificate-csrsigning
rancher    | I1016 08:39:19.288825      37 controllermanager.go:533] Started "ttl"
rancher    | I1016 08:39:19.290532      37 ttl_controller.go:116] Starting TTL controller
rancher    | I1016 08:39:19.290576      37 shared_informer.go:197] Waiting for caches to sync for TTL
rancher    | I1016 08:39:19.302574      37 shared_informer.go:197] Waiting for caches to sync for resource quota
rancher    | I1016 08:39:19.383871      37 shared_informer.go:204] Caches are synced for job
rancher    | I1016 08:39:19.534894      37 shared_informer.go:204] Caches are synced for ClusterRoleAggregator
rancher    | I1016 08:39:19.561111      37 shared_informer.go:204] Caches are synced for PVC protection
rancher    | W1016 08:39:19.582874      37 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="local-node" does not exist
rancher    | I1016 08:39:19.603015      37 shared_informer.go:204] Caches are synced for daemon sets
rancher    | I1016 08:39:19.619268      37 shared_informer.go:204] Caches are synced for taint
rancher    | I1016 08:39:19.620836      37 node_lifecycle_controller.go:1443] Initializing eviction metric for zone:
rancher    | W1016 08:39:19.621279      37 node_lifecycle_controller.go:1058] Missing timestamp for Node local-node. Assuming now as a timestamp.
rancher    | I1016 08:39:19.621448      37 node_lifecycle_controller.go:1209] Controller detected that all Nodes are not-Ready. Entering master disruption mode.
rancher    | I1016 08:39:19.621659      37 event.go:281] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"local-node", UID:"6f1d2cd8-109e-4d93-adf7-f1371bf1d333", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RegisteredNode' Node local-node event: Registered Node local-node in Controller
rancher    | I1016 08:39:19.621773      37 shared_informer.go:204] Caches are synced for TTL
rancher    | I1016 08:39:19.622008      37 taint_manager.go:186] Starting NoExecuteTaintManager
rancher    | I1016 08:39:19.624119      37 trace.go:116] Trace[50258455]: "List" url:/apis/management.cattle.io/v3/catalogtemplateversions,user-agent:rancher/v0.0.0 (linux/amd64) kubernetes/$Format,client:127.0.0.1 (started: 2020-10-16 08:39:19.103504057 +0000 UTC m=+40.440246126) (total time: 520.436337ms):
rancher    | Trace[50258455]: [190.191916ms] [190.082862ms] Listing from storage done
rancher    | Trace[50258455]: [520.432881ms] [330.240965ms] Writing http response done count:500
rancher    | I1016 08:39:19.920785      37 shared_informer.go:204] Caches are synced for stateful set
rancher    | I1016 08:39:19.922691      37 shared_informer.go:204] Caches are synced for node
rancher    | I1016 08:39:19.922882      37 range_allocator.go:172] Starting range CIDR allocator
rancher    | I1016 08:39:19.923045      37 shared_informer.go:197] Waiting for caches to sync for cidrallocator
rancher    | I1016 08:39:19.923157      37 shared_informer.go:204] Caches are synced for cidrallocator
rancher    | I1016 08:39:19.970171      37 shared_informer.go:204] Caches are synced for deployment
rancher    | I1016 08:39:19.978912      37 shared_informer.go:204] Caches are synced for endpoint
rancher    | I1016 08:39:19.979153      37 shared_informer.go:204] Caches are synced for GC
rancher    | I1016 08:39:19.979250      37 shared_informer.go:204] Caches are synced for disruption
rancher    | I1016 08:39:19.979285      37 disruption.go:338] Sending events to api server.
rancher    | I1016 08:39:19.979556      37 shared_informer.go:204] Caches are synced for ReplicaSet
rancher    | I1016 08:39:20.003990      37 shared_informer.go:204] Caches are synced for ReplicationController
rancher    | I1016 08:39:20.091009      37 shared_informer.go:204] Caches are synced for certificate-csrapproving
rancher    | I1016 08:39:20.091077      37 shared_informer.go:204] Caches are synced for certificate-csrsigning
rancher    | I1016 08:39:20.219654      37 shared_informer.go:204] Caches are synced for HPA
rancher    | I1016 08:39:20.256130      37 shared_informer.go:204] Caches are synced for namespace
rancher    | I1016 08:39:20.301901      37 shared_informer.go:197] Waiting for caches to sync for garbage collector
rancher    | I1016 08:39:20.312369      37 shared_informer.go:204] Caches are synced for persistent volume
rancher    | I1016 08:39:20.316928      37 shared_informer.go:204] Caches are synced for service account
rancher    | I1016 08:39:20.322220      37 shared_informer.go:204] Caches are synced for PV protection
rancher    | I1016 08:39:20.327348      37 shared_informer.go:204] Caches are synced for expand
rancher    | I1016 08:39:20.346147      37 shared_informer.go:204] Caches are synced for attach detach
rancher    | I1016 08:39:20.534762      37 trace.go:116] Trace[1805291380]: "List etcd3" key:/management.cattle.io/catalogtemplateversions,resourceVersion:,limit:0,continue: (started: 2020-10-16 08:39:07.057019713 +0000 UTC m=+28.393761856) (total time: 13.477689253s):
rancher    | Trace[1805291380]: [13.477689253s] [13.477689253s] END
rancher    | I1016 08:39:21.507839      37 trace.go:116] Trace[750952006]: "List etcd3" key:/management.cattle.io/catalogtemplateversions,resourceVersion:,limit:500,continue:eyJ2IjoibWV0YS5rOHMuaW8vdjEiLCJydiI6MTI4NjMxNjksInN0YXJ0IjoiY2F0dGxlLWdsb2JhbC1kYXRhL2JpdG5hbWktcmVkaXMtOS4xLjhcdTAwMDAifQ (started: 2020-10-16 08:39:20.743832363 +0000 UTC m=+42.080574449) (total time: 763.941441ms):
rancher    | Trace[750952006]: [763.941441ms] [763.941441ms] END
rancher    | I1016 08:39:22.360139      37 trace.go:116] Trace[411308090]: "List" url:/apis/management.cattle.io/v3/catalogtemplateversions,user-agent:rancher/v0.0.0 (linux/amd64) kubernetes/$Format,client:127.0.0.1 (started: 2020-10-16 08:39:20.743680242 +0000 UTC m=+42.080422308) (total time: 1.61636434s):
rancher    | Trace[411308090]: [768.364869ms] [768.229141ms] Listing from storage done
rancher    | Trace[411308090]: [1.616362371s] [847.997502ms] Writing http response done count:500
rancher    | I1016 08:39:23.722868      37 trace.go:116] Trace[846221274]: "Call validating webhook" configuration:rancher.cattle.io,webhook:rancher.cattle.io,resource:management.cattle.io/v3, Resource=clusters,subresource:,operation:UPDATE,UID:5246a3ee-dcc4-4f21-afc1-39104e398599 (started: 2020-10-16 08:39:13.720512606 +0000 UTC m=+35.057254885) (total time: 10.002275905s):
rancher    | Trace[846221274]: [10.002275905s] [10.002275905s] END
rancher    | W1016 08:39:23.723266      37 dispatcher.go:128] Failed calling webhook, failing open rancher.cattle.io: failed calling webhook "rancher.cattle.io": Post https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s: context deadline exceeded
rancher    | E1016 08:39:23.723310      37 dispatcher.go:129] failed calling webhook "rancher.cattle.io": Post https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s: context deadline exceeded
rancher    | I1016 08:39:23.810608      37 trace.go:116] Trace[937735052]: "GuaranteedUpdate etcd3" type:*unstructured.Unstructured (started: 2020-10-16 08:39:13.704995902 +0000 UTC m=+35.041738072) (total time: 10.105552601s):
rancher    | Trace[937735052]: [10.03858261s] [10.038004513s] Transaction prepared
rancher    | I1016 08:39:23.838815      37 trace.go:116] Trace[1668415040]: "Update" url:/apis/management.cattle.io/v3/clusters/local,user-agent:rancher/v0.0.0 (linux/amd64) kubernetes/$Format,client:127.0.0.1 (started: 2020-10-16 08:39:13.703043166 +0000 UTC m=+35.039785225) (total time: 10.135703249s):
rancher    | Trace[1668415040]: [10.107927285s] [10.106244287s] Object stored in database
rancher    | I1016 08:39:23.962172      37 trace.go:116] Trace[1879322]: "Call validating webhook" configuration:rancher.cattle.io,webhook:rancherauth.cattle.io,resource:management.cattle.io/v3, Resource=roletemplates,subresource:,operation:UPDATE,UID:385513b8-aee8-4b3f-9bad-4fd117d230a9 (started: 2020-10-16 08:39:13.960407567 +0000 UTC m=+35.297149741) (total time: 10.001628179s):
rancher    | Trace[1879322]: [10.001628179s] [10.001628179s] END
rancher    | W1016 08:39:23.962276      37 dispatcher.go:133] Failed calling webhook, failing closed rancherauth.cattle.io: failed calling webhook "rancherauth.cattle.io": Post https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s: dial tcp 10.43.144.55:443: i/o timeout
rancher    | I1016 08:39:25.044647      37 http.go:116] HTTP2 has been explicitly disabled
rancher    | I1016 08:39:25.052032      37 http.go:116] HTTP2 has been explicitly disabled
rancher    | I1016 08:39:25.056552      37 http.go:116] HTTP2 has been explicitly disabled
rancher    | I1016 08:39:26.516928      37 trace.go:116] Trace[1246376285]: "List etcd3" key:/management.cattle.io/catalogtemplateversions,resourceVersion:,limit:500,continue:eyJ2IjoibWV0YS5rOHMuaW8vdjEiLCJydiI6MTI4NjMxNjksInN0YXJ0IjoiY2F0dGxlLWdsb2JhbC1kYXRhL2JpdG5hbWktdGVzdGxpbmstNy4yLjFcdTAwMDAifQ (started: 2020-10-16 08:39:22.937328491 +0000 UTC m=+44.274070577) (total time: 3.57953189s):
rancher    | Trace[1246376285]: [3.57953189s] [3.57953189s] END
rancher    | I1016 08:39:26.922295      37 trace.go:116] Trace[1947731611]: "List" url:/apis/management.cattle.io/v3/catalogtemplateversions,user-agent:rancher/v0.0.0 (linux/amd64) kubernetes/$Format,client:127.0.0.1 (started: 2020-10-16 08:39:22.937227131 +0000 UTC m=+44.273969213) (total time: 3.985001344s):
rancher    | Trace[1947731611]: [3.583150162s] [3.583065141s] Listing from storage done
rancher    | Trace[1947731611]: [3.984998515s] [401.848353ms] Writing http response done count:500
rancher    | I1016 08:39:28.234388      37 trace.go:116] Trace[1838708232]: "List" url:/apis/management.cattle.io/v3/catalogtemplateversions,user-agent:k3s/v1.17.2+k3s1 (linux/amd64) kubernetes/cdab19b/metadata-informers,client:127.0.0.1 (started: 2020-10-16 08:39:21.863838183 +0000 UTC m=+43.200580321) (total time: 6.370485472s):
rancher    | Trace[1838708232]: [4.565419609s] [4.565316006s] Listing from storage done
rancher    | Trace[1838708232]: [6.370483364s] [1.805063755s] Writing http response done count:19095
rancher    | I1016 08:39:29.666450      37 trace.go:116] Trace[2115245709]: "List" url:/apis/management.cattle.io/v3/catalogtemplateversions,user-agent:rancher/v0.0.0 (linux/amd64) kubernetes/$Format,client:127.0.0.1 (started: 2020-10-16 08:39:28.873936738 +0000 UTC m=+50.210678802) (total time: 792.426284ms):
rancher    | Trace[2115245709]: [252.887945ms] [252.80041ms] Listing from storage done
rancher    | Trace[2115245709]: [792.422297ms] [539.534352ms] Writing http response done count:500
rancher    | I1016 08:39:33.299770      37 shared_informer.go:204] Caches are synced for garbage collector
rancher    | I1016 08:39:33.299819      37 garbagecollector.go:138] Garbage collector: all resource monitors have synced. Proceeding to collect garbage
rancher    | I1016 08:39:33.302246      37 shared_informer.go:204] Caches are synced for garbage collector
rancher    | I1016 08:39:33.306029      37 shared_informer.go:204] Caches are synced for resource quota
rancher    | I1016 08:39:33.399148      37 shared_informer.go:204] Caches are synced for resource quota
rancher    | I1016 08:39:34.033403      37 trace.go:116] Trace[1784764623]: "Call validating webhook" configuration:rancher.cattle.io,webhook:rancherauth.cattle.io,resource:management.cattle.io/v3, Resource=roletemplates,subresource:,operation:UPDATE,UID:a52d801e-bddb-4ba6-95a4-cf5347c8922c (started: 2020-10-16 08:39:24.032983083 +0000 UTC m=+45.369725247) (total time: 10.000341449s):
rancher    | Trace[1784764623]: [10.000341449s] [10.000341449s] END
rancher    | W1016 08:39:34.033503      37 dispatcher.go:133] Failed calling webhook, failing closed rancherauth.cattle.io: failed calling webhook "rancherauth.cattle.io": Post https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s: context deadline exceeded
rancher    | I1016 08:39:34.033666      37 trace.go:116] Trace[86604177]: "GuaranteedUpdate etcd3" type:*unstructured.Unstructured (started: 2020-10-16 08:39:13.959477517 +0000 UTC m=+35.296219610) (total time: 20.074153848s):
rancher    | Trace[86604177]: [20.074153848s] [20.073878221s] END
rancher    | I1016 08:39:34.034153      37 trace.go:116] Trace[1366215435]: "Update" url:/apis/management.cattle.io/v3/roletemplates/read-only,user-agent:Go-http-client/1.1,client:127.0.0.1 (started: 2020-10-16 08:39:13.958771429 +0000 UTC m=+35.295513490) (total time: 20.075338982s):
rancher    | Trace[1366215435]: [20.075338982s] [20.074726817s] END
rancher    | panic: problem reconciling role templates: couldn't update read-only: Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s: context deadline exceeded
rancher    |
rancher    | goroutine 2987 [running]:
rancher    | github.com/rancher/rancher/app.(*Rancher).Start.func1(0x482de00, 0xc00f94bf80)
rancher    |    /go/src/github.com/rancher/rancher/app/app.go:245 +0x651
rancher    | created by github.com/rancher/rancher/vendor/github.com/rancher/wrangler/pkg/leader.run.func1
rancher    |    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/wrangler/pkg/leader/leader.go:58 +0x46
```

2.3.9 not compatible with cluster:
```
rancher    | 2020-10-16 08:47:45.046392 I | raft: 8e9e05c52164694d became follower at term 34
rancher    | 2020-10-16 08:47:45.046444 I | raft: newRaft 8e9e05c52164694d [peers: [8e9e05c52164694d], term: 34, commit: 13502988, applied: 13500135, lastindex: 13502988, lastterm: 34]
rancher    | 2020-10-16 08:47:45.046622 C | etcdserver/membership: cluster cannot be downgraded (current version: 3.3.14 is lower than determined cluster version: 3.4).
rancher    | 2020/10/16 08:47:45 [FATAL] etcd exited
```

**Comment by CSRedRat** [comment]
In Dasboard events cluster on server B:

```
cattle-system | Warning | Unhealthy | cattle-cluster-agent-867fc487db-bvkdw | Readiness probe failed: HTTP probe failed with statuscode: 500 | 4 minutes ago
-- | -- | -- | -- | -- | --
```
Status:
```
This cluster is currently Error.
Finished building Kubernetes cluster successfully
```
Kubernetes can't be downgraded to 1.18.9.

local k3s cycled loop Upgrading -> Upgraded -> Normal -> Upgrading .

**Comment by CSRedRat** [comment]
```
rancher    | [kube] 2020/10/16 09:26:33 get relation pod of object: nfs-provisioner/Service/nfs-provisioner
rancher    | [kube] 2020/10/16 09:26:33 get relation pod of object: nfs-provisioner/StatefulSet/nfs-provisioner
rancher    | W1016 09:26:37.850007       8 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
rancher    | 2020-10-16 09:26:40.061608 W | etcdserver: request "header:<ID:7587849799103928069 > txn:<compare:<target:MOD key:\"/registry/management.cattle.io/clusters/local\" mod_revision:12882813 > success:<request_put:<key:\"/registry/management.cattle.io/clusters/local\" value_size:6762 >> failure:<request_range:<key:\"/registry/management.cattle.io/clusters/local\" > >>" with result "size:20" took too long (125.974187ms) to execute
rancher    | W1016 09:26:52.852243       8 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
rancher    | 2020-10-16 09:26:53.310993 W | etcdserver: read-only range request "key:\"/registry/namespaces/cattle-system\" " with result "range_response_count:1 size:672" took too long (247.482251ms) to execute
rancher    | I1016 09:27:03.440587      37 trace.go:116] Trace[1624732129]: "GuaranteedUpdate etcd3" type:*unstructured.Unstructured (started: 2020-10-16 09:27:02.894084785 +0000 UTC m=+998.783837613) (total time: 546.460977ms):
rancher    | Trace[1624732129]: [546.460977ms] [544.997185ms] END
rancher    | I1016 09:27:03.440839      37 trace.go:116] Trace[1793035853]: "Update" url:/apis/management.cattle.io/v3/clusters/local,user-agent:rancher/v0.0.0 (linux/amd64) kubernetes/$Format,client:127.0.0.1 (started: 2020-10-16 09:27:02.892348991 +0000 UTC m=+998.782101828) (total time: 548.456791ms):
rancher    | Trace[1793035853]: [548.456791ms] [546.877962ms] END
rancher    | 2020-10-16 09:27:04.537163 W | etcdserver: read-only range request "key:\"/registry/configmaps/kube-system/k3s\" " with result "range_response_count:1 size:373" took too long (106.079726ms) to execute
rancher    | W1016 09:27:07.852603       8 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
rancher    | W1016 09:27:22.867718       8 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
rancher    | 2020-10-16 09:27:24.670467 W | etcdserver: read-only range request "key:\"/registry/namespaces/cattle-system\" " with result "range_response_count:1 size:672" took too long (182.012048ms) to execute
```
Local k3s explorer:
```
Killing | Pod dashboard-shell-qjqdpStopping container shell | 6 min ago
Killing | Pod dashboard-shell-qjqdpStopping container proxy | 6 min ago
Created | Pod dashboard-shell-qjqdpCreated container proxy | 7 min ago
```
rancher docker logs:
```
rancher    | 2020-10-16 09:30:43.618264 W | etcdserver: read-only range request "key:\"/registry/configmaps/fleet-system/fleet-controller-lock\" " with result "range_response_count:1 size:579" took too long (118.428619ms) to execute
rancher    | 2020-10-16 09:30:44.737821 W | etcdserver: read-only range request "key:\"/registry/leases/kube-system/kube-controller-manager\" " with result "range_response_count:1 size:309" took too long (214.556712ms) to execute
rancher    | 2020-10-16 09:30:44.737989 W | etcdserver: request "header:<ID:7587849799103940763 > txn:<compare:<target:MOD key:\"/registry/management.cattle.io/clusters/local\" mod_revision:12887028 > success:<request_put:<key:\"/registry/management.cattle.io/clusters/local\" value_size:6762 >> failure:<request_range:<key:\"/registry/management.cattle.io/clusters/local\" > >>" with result "size:20" took too long (150.172798ms) to execute
rancher    | 2020-10-16 09:30:44.738878 W | etcdserver: read-only range request "key:\"/registry/storageclasses\" range_end:\"/registry/storageclasset\" count_only:true " with result "range_response_count:0 size:7" took too long (123.888356ms) to execute
rancher    | 2020-10-16 09:30:44.738903 W | etcdserver: read-only range request "key:\"/registry/validatingwebhookconfigurations\" range_end:\"/registry/validatingwebhookconfigurationt\" count_only:true " with result "range_response_count:0 size:9" took too long (198.062536ms) to execute
rancher    | 2020-10-16 09:30:44.739283 W | etcdserver: read-only range request "key:\"/registry/namespaces/default\" " with result "range_response_count:1 size:588" took too long (166.666252ms) to execute
rancher    | 2020-10-16 09:30:44.739519 W | etcdserver: read-only range request "key:\"/registry/configmaps/kube-system/cattle-controllers\" " with result "range_response_count:1 size:403" took too long (115.582746ms) to execute
rancher    | W1016 09:30:52.911233       8 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
rancher    | W1016 09:31:07.873244       8 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
rancher    | W1016 09:31:12.443200      37 watcher.go:199] watch chan error: etcdserver: mvcc: required revision has been compacted
rancher    | W1016 09:31:22.845700       8 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
rancher    | W1016 09:31:37.845054       8 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
rancher    | 2020/10/16 09:31:38 [ERROR] Error during subscribe websocket: close sent
rancher    | 2020/10/16 09:31:38 [ERROR] Error during subscribe websocket: close sent
```
Status k3s node:
```
DiskPressure | False | 2:37 PM | KubeletHasNoDiskPressure | kubelet has no disk pressure
MemoryPressure | False | 2:37 PM | KubeletHasSufficientMemory | kubelet has sufficient memory available
NetworkUnavailable | False | 2:37 PM | FlannelIsUp | Flannel is running on this node
PIDPressure | False | 2:37 PM | KubeletHasSufficientPID | kubelet has sufficient PID available
Provisioned | True | 2:37 PM |   |  
Ready | True | 2:37 PM | KubeletReady | kubelet is posting ready status
Registered | True | 2:37 PM |   | registered with kubernetes
```

**Comment by CSRedRat** [comment]
Provider for local k3s at cluster list: K3Sv1.18.8+k3s1
In Edit cluster: Kubernetes Version v1.19.2+k3s1 and can't be downgraded.
k3s kubectl:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8+k3s1", GitCommit:"6b595318666804506c19cfc3d3d228423d38fab1", GitTreeState:"clean", BuildDate:"2020-08-14T20:42:29Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
How rollback k3s configuration or reset?

**Comment by rezicosta** [comment]
It worked for me by just providing privileged flag. 

`docker run -d --privileged --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher`

**Comment by alphabetek** [comment]
I have the same issue while trying [Rancher Vagrant quickstart](https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/deployment/quickstart-vagrant/). Rancher server keeps restarting and logs show `ERROR: Rancher must be ran with the --privileged flag when running outside of Kubernetes`.

**Comment by CSRedRat** [comment]
@alphabetek @rezicosta problem not in privileged access, rancher docker with update install new local k3s cluster and I can't remove this cluster, can't disable install k3s with docker start rancher (admin dashboard UI). I not found info about k3s with docker image in documentation and was force remove rancher, downgrade to 2.4.8 without k3s autoinstall and reinstall rancher docker again.

**Comment by demangejeremy** [comment]
`sudo docker run -d --privileged --restart=unless-stopped -p 80:80 -p 443:443 -v /host/rancher:/var/lib/rancher rancher/rancher --acme-domain rancher.example.com`

**Comment by superseb** [comment]
The use of the privileged flag is both described in the release notes (https://github.com/rancher/rancher/releases/tag/v2.5.0) and in the docs (https://staging.rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/single-node-docker/), the error should also be descriptive enough.

If you think there is a bug here, please supply the steps to reproduce including a command for each step so we can use that to reproduce and trace down where it might come from.

**Comment by CSRedRat** [comment]
@superseb Thank you, there is no problem with elevation of privileges. On server with docker rancher web UI with update 2.5 is running an unnecessary k3s cluster. How disable k3s local installation and starting kubernetes cluster on Server A with Docker UI (see first message), I need only k8s cluster on Server B. I can remove local k3s cluster only with Rancher Docker UI.

**Comment by vincent99** [comment]
It's not "unnecessary" and isn't new (though it hasn't always been k3s).  Rancher runs only in a kubernetes cluster; everything depends on CRDs and controllers.  The single docker container version has always contained a single node kubernetes cluster inside of it to run that.

The only thing that's new is that it's exposed (as "local") to be selected all the time now, because there are new features that use it.

**Comment by CSRedRat** [comment]
@vincent99 thank you, you answered my question!
