### ISSUE TITLE
Error with rancher/agent when adding localhost with custom host 

### ISSUE THREAD

**Issue by tychota** [rancher/rancher#2978]
On `Ubuntu Wily`, `Docker version 1.9.1, build a34a1d5`
with the following Docker images :

hash                  | tag             | image
--------------------|-----------------|------------
0875c358b79b  | latest          | rancher/server
bd417032148c  | v0.8.2         | rancher/agent

when trying to install agent on my local machine, following the command UI gives me (custom host) : 

```bash
sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.8.2 http://localhost:8080/v1/scripts/redacted1:redacted2:redacted3
```
the docker agent container exit rapidly.
Browsing the container logs with `docker logs hash` gives me: 

```pytb
Traceback (most recent call last):
  File "./register.py", line 11, in <module>
    secret_key=os.environ['CATTLE_REGISTRATION_SECRET_KEY'])
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 37, in from_env
    return gdapi.from_env(prefix=prefix, factory=Client, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 608, in from_env
    return _from_env(prefix=prefix, factory=factory, **args)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 627, in _from_env
    return factory(**result)
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 12, in __init__
    super(Client, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 195, in __init__
    self._load_schemas()
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 313, in _load_schemas
    response = self._get_response(self._url)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 262, in _get_response
    headers=self._headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
```

and no host appears on Host page in th UI.

**Comment by deniseschannon** [comment]
Instead of using `localhost` in your host registration setup page, you should use the actual machine IP. 


So in the docker run command, it would say `http://<server_IP>:8080/v1/scripts/redacted1:redacted2:redacted3`

**Comment by deniseschannon** [comment]
Depending on your version, you can update the host registration by going to **Admin** -> **Settings** or it could be located under **Admin** -> **Host Registration**. 

http://docs.rancher.com/rancher/configuration/settings/#host-registration

**Comment by deniseschannon** [comment]
@tychota If you're able to try with my suggestions and still facing issues, please re-open and provide an update.

**Comment by tychota** [comment]
@deniseschannon sorry for this delay ! I will try again, but maybe not that soon. 

I ve reinstalled my OS since the issue ! And the root problem ("testing a good interface to replace our openvz/proxmox with prehistoric kernel") is somehow delayed since it is too much works for now and ansible deployement kinda works.

This beeing said, I keep that in mind !

I m pretty sure I ve tryed with IP thougt since I spended a lot of time investing this, but nothing 100% sure.

So I'm fine with closing for know, and sorry for the noise/time if I don't answer soon (tm).

**Comment by yasahmed** [comment]
+1
