### ISSUE TITLE
Do not log entire stack trace in logs when look up on user/group fails.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2998]
Server version - Build from master - Dec 10

rancher-server has access controlled enabled using "openLdap".
Create an environment and add  a LDAP group and user to it.

Now delete this LDAP group and user from LDAP.

When trying to list members of this environment , the deleted group/user is listed as being not found. 

Rancher server logs has this stack trace being logged . Can this stack trace be not logged  , since we are handling this case gracefully?

 
```
2015-12-11 01:20:59,763 INFO  [:] [] [] [] [cutorService-31] [i.a.a.i.l.O.OpenLDAPIdentityProvider] Failed to get object: cn=qa5,dc=rancher,dc=io javax.naming.NameNotFoundException: [LDAP: error code 32 - No Such Object]
	at com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3113) ~[na:1.7.0_91]
	at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3034) ~[na:1.7.0_91]
	at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2841) ~[na:1.7.0_91]
	at com.sun.jndi.ldap.LdapCtx.c_getAttributes(LdapCtx.java:1333) ~[na:1.7.0_91]
	at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_getAttributes(ComponentDirContext.java:231) ~[na:1.7.0_91]
	at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.getAttributes(PartialCompositeDirContext.java:139) ~[na:1.7.0_91]
	at javax.naming.directory.InitialDirContext.getAttributes(InitialDirContext.java:152) ~[na:1.7.0_91]
	at javax.naming.directory.InitialDirContext.getAttributes(InitialDirContext.java:147) ~[na:1.7.0_91]
	at io.cattle.platform.iaas.api.auth.integration.ldap.LDAPIdentityProvider.getObject(LDAPIdentityProvider.java:155) [cattle-iaas-auth-logic-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.iaas.api.auth.integration.ldap.LDAPIdentityProvider.getIdentity(LDAPIdentityProvider.java:73) [cattle-iaas-auth-logic-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.iaas.api.auth.identity.IdentityManager.projectMemberToIdentity(IdentityManager.java:128) [cattle-iaas-auth-logic-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.iaas.api.auth.identity.IdentityManager.projectMemberToIdentity(IdentityManager.java:150) [cattle-iaas-auth-logic-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.iaas.api.auth.projects.ProjectMemberResourceManager.listInternal(ProjectMemberResourceManager.java:71) [cattle-iaas-auth-logic-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.getByIdInternal(AbstractBaseResourceManager.java:68) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.getById(AbstractBaseResourceManager.java:61) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.iaas.api.change.impl.ResourceChangeEventProcessor.processEvent(ResourceChangeEventProcessor.java:47) [cattle-iaas-api-logic-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.pubsub.subscribe.NonBlockingSubscriptionHandler.postProcess(NonBlockingSubscriptionHandler.java:113) [cattle-framework-api-pub-sub-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.pubsub.subscribe.NonBlockingSubscriptionHandler$1.onEvent(NonBlockingSubscriptionHandler.java:91) [cattle-framework-api-pub-sub-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_91]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_91]
```

**Comment by hibooboo2** [comment]
How did you cause this stack trace to occur?

**Comment by hibooboo2** [comment]
Suppressing it would cause possible problems in the future that would be impossible to debug easily since it would be suppressing the cause. As this is something that can occur differently depending on the auth provider configured and it is possible that something else may cause this in the future.

**Comment by cjellick** [comment]
@hibooboo2 I think I agree with @sangeethah on this one. I'm not a fan of stack traces on info level statements. People see stack traces and assume something is broken. Logging just e.getMessage() should suffice. That should get you the important part of the message: "[LDAP: error code 32 - No Such Object]".

Can you reopen?

Also, I think as a general practice you probably shouldn't just close bugs opened by QA. It would be better if you make your case for why you'd like to close it and then assign back over to the report and ask him or her if we can close. Checks and balances and whatnot.

**Comment by sangeethah** [comment]
Tested with server version - v0.50.0-rc3

When trying to list members of of environment  that have the deleted group/user as members, following  message is logged in the rancher-server logs. No stack traces are seen.
 
2015-12-14 22:57:18,675 INFO  [:] [] [] [] [cutorService-13] [i.a.a.i.l.O.OpenLDAPIdentityProvider] Failed to get object: cn=qa4,dc=rancher,dc=io : [LDAP: error code 32 - No Such Object]
