### ISSUE TITLE
Panic in latest 2.5-head manager.go

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#30143]
**What kind of request is this:**
bug

**Steps to reproduce:**

- Install singler Rancher docker
- Provision an RKE DO cluster.

**Result:**

Rancher keeps restarting, I can't see the Cluster getting provisioned.

```
E1118 23:10:03.910999       7 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 3089 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3c27180, 0x7392980)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/runtime/runtime.go:48 +0x82
panic(0x3c27180, 0x7392980)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/rancher/rancher/pkg/catalog/manager.(*Manager).ValidateKubeVersion(0xc001c54000, 0xc005765028, 0xc000d54dc4, 0x7, 0xc00a52f801, 0xc00a4f7800)
	/go/src/github.com/rancher/rancher/pkg/catalog/manager/manager.go:229 +0x1c1
github.com/rancher/rancher/pkg/catalog/manager.(*Manager).ValidateChartCompatibility(0xc001c54000, 0xc005765028, 0xc000d54dc4, 0x7, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/catalog/manager/manager.go:208 +0x74
github.com/rancher/rancher/pkg/catalog/manager.(*Manager).LatestAvailableTemplateVersion(0xc001c54000, 0xc001db6ec0, 0xc000d54dc4, 0x7, 0x21, 0xc001db6ec0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/catalog/manager/manager.go:288 +0x211
github.com/rancher/rancher/pkg/controllers/managementuser/alert/deployer.(*AlertService).Upgrade(0xc005e76900, 0xc009ed0de0, 0x2e, 0x8, 0xc009f43828, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/alert/deployer/upgradeimpl.go:95 +0x1a8
github.com/rancher/rancher/pkg/controllers/managementuser/systemimage.(*Syncer).Sync(0xc005eff580, 0xc00254e000, 0x7ff16fca07d0)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/systemimage/systemimage.go:74 +0x2f7
github.com/rancher/rancher/pkg/controllers/managementuser/systemimage.(*Syncer).SyncProject(...)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/systemimage/systemimage.go:31
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*projectController).AddClusterScopedHandler.func1(0xc00327a9c0, 0xf, 0x445cb40, 0xc009f52340, 0xc009a2bb20, 0x3, 0x3, 0x0)
	/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_project_controller.go:182 +0x79
github.com/rancher/norman/controller.(*genericController).AddHandler.func1(0xc00327a9c0, 0xf, 0x4e3e120, 0xc009f52340, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200930000340-693d65aaffe3/controller/generic_controller.go:62 +0x221
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc009228360, 0xc00327a9c0, 0xf, 0x4e3e120, 0xc009f52340, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*sharedHandler).OnChange(0xc0026fe9c0, 0xc00327a9c0, 0xf, 0x4e3e120, 0xc009f52340, 0xc0023ec701, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedhandler.go:65 +0x14a
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc003e61760, 0xc00327a9c0, 0xf, 0xc00346ca50, 0xc009c29d50)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:210 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc003e61760, 0x391d760, 0xc009d59c70, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:192 +0xd7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc003e61760, 0x203001)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:169 +0x51
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc003e61760)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:158 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc003b8c270)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc003b8c270, 0x4e12660, 0xc003ba82a0, 0x1, 0xc0022d7560)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc003b8c270, 0x3b9aca00, 0x0, 0x1, 0xc0022d7560)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc003b8c270, 0x3b9aca00, 0xc0022d7560)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:129 +0x31f
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16a7691]
```

**Other details that may be helpful:**

**Environment information**
- Rancher version: `v2.5-head (11/18/2020)` _9a6780904_
- Installation option: single

**Cluster information**
- Cluster type: Infrastructure RKE DO
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 4 vCPU, 4 GB Ram
- Kubernetes version (use `kubectl version`): `v1.19`

**Comment by jiaqiluo** [comment]
I hit the same issue on v2.5.2 single-install setup after adding a new ec2 cluster 


```
E1119 16:48:41.817251       7 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 2887 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3c26060, 0x7390960)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/runtime/runtime.go:48 +0x82
panic(0x3c26060, 0x7390960)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/rancher/rancher/pkg/catalog/manager.(*Manager).ValidateKubeVersion(0xc001426f00, 0xc007df6fe8, 0xc0022ecd44, 0x7, 0xc003e20901, 0xc0046b5c00)
	/go/src/github.com/rancher/rancher/pkg/catalog/manager/manager.go:229 +0x1c1
github.com/rancher/rancher/pkg/catalog/manager.(*Manager).ValidateChartCompatibility(0xc001426f00, 0xc007df6fe8, 0xc0022ecd44, 0x7, 0x20, 0x0)
	/go/src/github.com/rancher/rancher/pkg/catalog/manager/manager.go:208 +0x74
github.com/rancher/rancher/pkg/catalog/manager.(*Manager).LatestAvailableTemplateVersion(0xc001426f00, 0xc002978ec0, 0xc0022ecd44, 0x7, 0x21, 0xc002978ec0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/catalog/manager/manager.go:288 +0x211
github.com/rancher/rancher/pkg/controllers/managementuser/alert/deployer.(*AlertService).Upgrade(0xc006228100, 0xc0099951a0, 0x2e, 0x8, 0xc009989828, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/alert/deployer/upgradeimpl.go:95 +0x1a8
github.com/rancher/rancher/pkg/controllers/managementuser/systemimage.(*Syncer).Sync(0xc004186480, 0x391c4c0, 0xc0099fc900)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/systemimage/systemimage.go:74 +0x2f7
github.com/rancher/rancher/pkg/controllers/managementuser/systemimage.(*Syncer).SyncCatalog(0xc004186480, 0xc002da06b0, 0xe, 0xc0024ff390, 0xc00116e700, 0x7fa8d040c108, 0xc002ea0d80, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/systemimage/systemimage.go:43 +0xa8
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*catalogController).AddHandler.func1(0xc002da06b0, 0xe, 0x4440560, 0xc0024ff390, 0xc007df7b20, 0x3, 0x3, 0x0)
	/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_catalog_controller.go:155 +0x63
github.com/rancher/norman/controller.(*genericController).AddHandler.func1(0xc002da06b0, 0xe, 0x4e3b180, 0xc0024ff390, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200930000340-693d65aaffe3/controller/generic_controller.go:62 +0x221
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc00306d950, 0xc002da06b0, 0xe, 0x4e3b180, 0xc0024ff390, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*sharedHandler).OnChange(0xc0019a8ff0, 0xc002da06b0, 0xe, 0x4e3b180, 0xc0024ff390, 0xc003187701, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedhandler.go:65 +0x14a
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc001a48160, 0xc002da06b0, 0xe, 0xc002a27740, 0xc002fb4d50)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:210 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc001a48160, 0x391c700, 0xc00461ddc0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:192 +0xd7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc001a48160, 0x203000)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:169 +0x51
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc001a48160)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:158 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0004dc040)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0004dc040, 0x4e10fe0, 0xc002fac0f0, 0xc002dbab01, 0xc001b4c300)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0004dc040, 0x3b9aca00, 0x0, 0x1, 0xc001b4c300)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc0004dc040, 0x3b9aca00, 0xc001b4c300)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:129 +0x31f
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16a7691]

goroutine 2887 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/runtime/runtime.go:55 +0x105
panic(0x3c26060, 0x7390960)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/rancher/rancher/pkg/catalog/manager.(*Manager).ValidateKubeVersion(0xc001426f00, 0xc007df6fe8, 0xc0022ecd44, 0x7, 0xc003e20901, 0xc0046b5c00)
	/go/src/github.com/rancher/rancher/pkg/catalog/manager/manager.go:229 +0x1c1
github.com/rancher/rancher/pkg/catalog/manager.(*Manager).ValidateChartCompatibility(0xc001426f00, 0xc007df6fe8, 0xc0022ecd44, 0x7, 0x20, 0x0)
	/go/src/github.com/rancher/rancher/pkg/catalog/manager/manager.go:208 +0x74
github.com/rancher/rancher/pkg/catalog/manager.(*Manager).LatestAvailableTemplateVersion(0xc001426f00, 0xc002978ec0, 0xc0022ecd44, 0x7, 0x21, 0xc002978ec0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/catalog/manager/manager.go:288 +0x211
github.com/rancher/rancher/pkg/controllers/managementuser/alert/deployer.(*AlertService).Upgrade(0xc006228100, 0xc0099951a0, 0x2e, 0x8, 0xc009989828, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/alert/deployer/upgradeimpl.go:95 +0x1a8
github.com/rancher/rancher/pkg/controllers/managementuser/systemimage.(*Syncer).Sync(0xc004186480, 0x391c4c0, 0xc0099fc900)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/systemimage/systemimage.go:74 +0x2f7
github.com/rancher/rancher/pkg/controllers/managementuser/systemimage.(*Syncer).SyncCatalog(0xc004186480, 0xc002da06b0, 0xe, 0xc0024ff390, 0xc00116e700, 0x7fa8d040c108, 0xc002ea0d80, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/systemimage/systemimage.go:43 +0xa8
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*catalogController).AddHandler.func1(0xc002da06b0, 0xe, 0x4440560, 0xc0024ff390, 0xc007df7b20, 0x3, 0x3, 0x0)
	/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_catalog_controller.go:155 +0x63
github.com/rancher/norman/controller.(*genericController).AddHandler.func1(0xc002da06b0, 0xe, 0x4e3b180, 0xc0024ff390, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200930000340-693d65aaffe3/controller/generic_controller.go:62 +0x221
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc00306d950, 0xc002da06b0, 0xe, 0x4e3b180, 0xc0024ff390, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*sharedHandler).OnChange(0xc0019a8ff0, 0xc002da06b0, 0xe, 0x4e3b180, 0xc0024ff390, 0xc003187701, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedhandler.go:65 +0x14a
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc001a48160, 0xc002da06b0, 0xe, 0xc002a27740, 0xc002fb4d50)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:210 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc001a48160, 0x391c700, 0xc00461ddc0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:192 +0xd7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc001a48160, 0x203000)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:169 +0x51
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc001a48160)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:158 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0004dc040)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0004dc040, 0x4e10fe0, 0xc002fac0f0, 0xc002dbab01, 0xc001b4c300)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0004dc040, 0x3b9aca00, 0x0, 0x1, 0xc001b4c300)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc0004dc040, 0x3b9aca00, 0xc001b4c300)
	/go/pkg/mod/github.com/rancher/apimachinery@v0.19.0-rancher1/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:129 +0x31f
```

**Comment by izaac** [comment]
Rancher version: `v2.5-head (11/20/2020)`  _f67129249_
Rancher version: `master-head (11/20/2020)` _2d92095ee_

I no longer see the panic in the latest builds.
