### ISSUE TITLE
Panic seen in Rancher server

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#30220]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
**On a HA rke setup - 2.4.10**

- Deployed these clusters - 
- AWS (Rancher OS - ROS) - v1.17.14 - PNI Enabled
- DO - v1.15.12
- sowmya-eks-2410 - 1.17
- test-88718 - 1.18.12 -  PNI Enabled
- windows - 1.16.15
- Did the pre upgrade checks using automation
- Upgrade rancher to 2.4.11-rc2
- Rancher server logs shows a panic
- AWS ROS cluster's System project says `Cluster not Ready`, user is NOT able to access the system project.

 
```
2020/11/24 19:32:17 [INFO] Starting cluster controllers for c-ksp5f
2020/11/24 19:32:17 [INFO] Redeploy Rancher Agents is needed for c-ksp5f: forceDeploy=false, agent/auth image changed=true, private repo changed=false, agent features changed=false
2020/11/24 19:32:17 [ERROR] Panic serving api request: 
goroutine 14374 [running]:
runtime/debug.Stack(0xc00cf7e678, 0x3a0fa40, 0x7332a50)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP.func1(0x4b7fc20, 0xc00c1fe0a0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:175 +0x7a
panic(0x3a0fa40, 0x7332a50)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/rancher/pkg/clustermanager.(*Manager).CanList(0xc001111680, 0xc00eafe5a0, 0xc0016f83c0, 0xffffffffffffffff, 0x35)
	/go/src/github.com/rancher/rancher/pkg/clustermanager/rbac.go:31 +0x70
github.com/rancher/rancher/vendor/github.com/rancher/norman/types.(*Schema).CanList(0xc0016f83c0, 0xc00eafe5a0, 0xc0001c3ee0, 0x11)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/types/schema_funcs.go:32 +0x1c4
github.com/rancher/rancher/vendor/github.com/rancher/norman/store/schema.(*Store).List(0x738da68, 0xc00eafe5a0, 0xc000281e00, 0xc00860ac00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/schema/schema_store.go:93 +0x32d
github.com/rancher/rancher/vendor/github.com/rancher/norman/store/wrapper.(*StoreWrapper).List(0xc00086ad30, 0xc00eafe5a0, 0xc000281e00, 0xc00860ac00, 0x4287cf1, 0x3, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/wrapper/wrapper.go:40 +0x148
github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler.ListHandler(0xc00eafe5a0, 0x44284a0, 0xc000281e00, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler/list.go:26 +0x287
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).handle(0xc00002ea50, 0x4b7fc20, 0xc00c1fe0a0, 0xc007a14d00, 0xc00cf7ed08, 0x8dd1f489, 0x4e1bdd98b4c49482)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:249 +0x2a2
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP(0xc00002ea50, 0x4b7fc20, 0xc00c1fe0a0, 0xc007a14d00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:180 +0x99
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentTypeOptions.func1(0x4b7fc20, 0xc00c1fe0a0, 0xc007a14d00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/cache.go:47 +0x131
net/http.HandlerFunc.ServeHTTP(0xc007e86240, 0x4b7fc20, 0xc00c1fe0a0, 0xc007a14d00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0018a80c0, 0x4b7fc20, 0xc00c1fe0a0, 0xc007a14b00)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/pkg/auth/requests.authHeaderHandler.ServeHTTP(0x4b3f860, 0xc001834fc0, 0x4afdbc0, 0xc0018a80c0, 0x4b3f820, 0xc001741710, 0x4b7fc20, 0xc00c1fe0a0, 0xc007a14b00)
	/go/src/github.com/rancher/rancher/pkg/auth/requests/filter.go:62 +0x4eb
github.com/rancher/rancher/pkg/rbac.NewAccessControlHandler.func1(0x4b7fc20, 0xc00c1fe0a0, 0xc007a14a00, 0x4afcb80, 0xc00124c360)
	/go/src/github.com/rancher/rancher/pkg/rbac/user_based.go:32 +0x194
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/auth.Middleware.Wrap.func1(0x4b7fc20, 0xc00c1fe0a0, 0xc007a14a00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/auth/filter.go:36 +0x55
net/http.HandlerFunc.ServeHTTP(0xc001835180, 0x4b7fc20, 0xc00c1fe0a0, 0xc007a14a00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/pkg/websocket.websocketHandler.ServeHTTP(0x4b07c20, 0xc001835180, 0x4b7fc20, 0xc00c1fe0a0, 0xc007a14a00)
	/go/src/github.com/rancher/rancher/pkg/websocket/handler.go:35 +0xa0
github.com/rancher/rancher/pkg/audit.auditHandler.ServeHTTP(0x4afcdc0, 0xc0004fbeb0, 0x0, 0x4b7fc20, 0xc00c1fe0a0, 0xc007a14a00)
	/go/src/github.com/rancher/rancher/pkg/audit/filter.go:31 +0x623
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentType.func1(0x4b6da20, 0xc0094974a0, 0xc007a14a00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/content.go:33 +0x93
net/http.HandlerFunc.ServeHTTP(0xc0018d8400, 0x4b6da20, 0xc0094974a0, 0xc007a14a00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.Gzip.func1(0x4b7eaa0, 0xc007bfa000, 0xc007a14a00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/gzip.go:60 +0x1f5
net/http.HandlerFunc.ServeHTTP(0xc0018d8420, 0x4b7eaa0, 0xc007bfa000, 0xc007a14a00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentTypeOptions.func1(0x4b7eaa0, 0xc007bfa000, 0xc007a14a00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/cache.go:47 +0x131
net/http.HandlerFunc.ServeHTTP(0xc007e86180, 0x4b7eaa0, 0xc007bfa000, 0xc007a14a00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0018a8000, 0x4b7eaa0, 0xc007bfa000, 0xc007a14800)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0027ed5c0, 0x4b7eaa0, 0xc007bfa000, 0xc007a14600)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0027ed680, 0x4b7eaa0, 0xc007bfa000, 0xc007a14400)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0027ed740, 0x4b7eaa0, 0xc007bfa000, 0xc007a14200)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/dashboard.Route.func2(0x4b7eaa0, 0xc007bfa000, 0xc007a14200)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/dashboard/ui.go:56 +0xe5
net/http.HandlerFunc.ServeHTTP(0xc0011c99f0, 0x4b7eaa0, 0xc007bfa000, 0xc007a14200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc001fa7380, 0x4b7eaa0, 0xc007bfa000, 0xc005604200)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/server.wrapHandler.func1(0x4b7eaa0, 0xc007bfa000, 0xc005604200)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/server/server.go:187 +0x95
net/http.HandlerFunc.ServeHTTP(0xc00332af30, 0x4b7eaa0, 0xc007bfa000, 0xc005604200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener.HTTPRedirect.func1(0x4b7eaa0, 0xc007bfa000, 0xc005604200)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/redirect.go:20 +0x221
net/http.HandlerFunc.ServeHTTP(0xc003e28a40, 0x4b7eaa0, 0xc007bfa000, 0xc005604200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.serverHandler.ServeHTTP(0xc006d38700, 0x4b7eaa0, 0xc007bfa000, 0xc005604200)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc002a71360, 0x4ba1da0, 0xc0044c8500)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e

time="2020-11-24 19:32:17" level=error msg="Failed to get project client ID c-5sdt8:p-7llqt err=Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [] from [https://localhost:443/v3/project/c-5sdt8:p-7llqt/schemas]"
2020/11/24 19:32:17 [ERROR] Panic serving api request: 
goroutine 14388 [running]:
runtime/debug.Stack(0xc008e44678, 0x3a0fa40, 0x7332a50)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP.func1(0x4b7fc20, 0xc00bdb1a00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:175 +0x7a
panic(0x3a0fa40, 0x7332a50)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/rancher/pkg/clustermanager.(*Manager).CanList(0xc001111680, 0xc00eb77440, 0xc00170f860, 0xffffffffffffffff, 0x3f)
	/go/src/github.com/rancher/rancher/pkg/clustermanager/rbac.go:31 +0x70
github.com/rancher/rancher/vendor/github.com/rancher/norman/types.(*Schema).CanList(0xc00170f860, 0xc00eb77440, 0xc0007dd660, 0xa)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/types/schema_funcs.go:32 +0x1c4
github.com/rancher/rancher/vendor/github.com/rancher/norman/store/schema.(*Store).List(0x738da68, 0xc00eb77440, 0xc000281e00, 0xc00862d000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/schema/schema_store.go:93 +0x32d
github.com/rancher/rancher/vendor/github.com/rancher/norman/store/wrapper.(*StoreWrapper).List(0xc00086ad30, 0xc00eb77440, 0xc000281e00, 0xc00862d000, 0x4287cf1, 0x3, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/wrapper/wrapper.go:40 +0x148
github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler.ListHandler(0xc00eb77440, 0x44284a0, 0xc000281e00, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler/list.go:26 +0x287
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).handle(0xc00002ea50, 0x4b7fc20, 0xc00bdb1a00, 0xc0087e1d00, 0xc008e44d08, 0x6211f2fa, 0x799045bcf2f39db7)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:249 +0x2a2
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP(0xc00002ea50, 0x4b7fc20, 0xc00bdb1a00, 0xc0087e1d00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:180 +0x99
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentTypeOptions.func1(0x4b7fc20, 0xc00bdb1a00, 0xc0087e1d00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/cache.go:47 +0x131
net/http.HandlerFunc.ServeHTTP(0xc007da2be0, 0x4b7fc20, 0xc00bdb1a00, 0xc0087e1d00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0018a80c0, 0x4b7fc20, 0xc00bdb1a00, 0xc0087e1b00)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/pkg/auth/requests.authHeaderHandler.ServeHTTP(0x4b3f860, 0xc001834fc0, 0x4afdbc0, 0xc0018a80c0, 0x4b3f820, 0xc001741710, 0x4b7fc20, 0xc00bdb1a00, 0xc0087e1b00)
	/go/src/github.com/rancher/rancher/pkg/auth/requests/filter.go:62 +0x4eb
github.com/rancher/rancher/pkg/rbac.NewAccessControlHandler.func1(0x4b7fc20, 0xc00bdb1a00, 0xc0087e1a00, 0x4afcb80, 0xc00124c360)
	/go/src/github.com/rancher/rancher/pkg/rbac/user_based.go:32 +0x194
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/auth.Middleware.Wrap.func1(0x4b7fc20, 0xc00bdb1a00, 0xc0087e1a00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/auth/filter.go:36 +0x55
net/http.HandlerFunc.ServeHTTP(0xc001835180, 0x4b7fc20, 0xc00bdb1a00, 0xc0087e1a00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/pkg/websocket.websocketHandler.ServeHTTP(0x4b07c20, 0xc001835180, 0x4b7fc20, 0xc00bdb1a00, 0xc0087e1a00)
	/go/src/github.com/rancher/rancher/pkg/websocket/handler.go:35 +0xa0
github.com/rancher/rancher/pkg/audit.auditHandler.ServeHTTP(0x4afcdc0, 0xc0004fbeb0, 0x0, 0x4b7fc20, 0xc00bdb1a00, 0xc0087e1a00)
	/go/src/github.com/rancher/rancher/pkg/audit/filter.go:31 +0x623
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentType.func1(0x4b6da20, 0xc0095058f0, 0xc0087e1a00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/content.go:33 +0x93
net/http.HandlerFunc.ServeHTTP(0xc0018d8400, 0x4b6da20, 0xc0095058f0, 0xc0087e1a00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.Gzip.func1(0x4b7eaa0, 0xc008688000, 0xc0087e1a00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/gzip.go:60 +0x1f5
net/http.HandlerFunc.ServeHTTP(0xc0018d8420, 0x4b7eaa0, 0xc008688000, 0xc0087e1a00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentTypeOptions.func1(0x4b7eaa0, 0xc008688000, 0xc0087e1a00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/cache.go:47 +0x131
net/http.HandlerFunc.ServeHTTP(0xc007da2ae0, 0x4b7eaa0, 0xc008688000, 0xc0087e1a00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0018a8000, 0x4b7eaa0, 0xc008688000, 0xc0087e1800)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0027ed5c0, 0x4b7eaa0, 0xc008688000, 0xc0087e1600)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0027ed680, 0x4b7eaa0, 0xc008688000, 0xc0087e1200)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0027ed740, 0x4b7eaa0, 0xc008688000, 0xc0087e1000)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/dashboard.Route.func2(0x4b7eaa0, 0xc008688000, 0xc0087e1000)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/dashboard/ui.go:56 +0xe5
net/http.HandlerFunc.ServeHTTP(0xc0011c99f0, 0x4b7eaa0, 0xc008688000, 0xc0087e1000)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc001fa7380, 0x4b7eaa0, 0xc008688000, 0xc0087e0b00)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/server.wrapHandler.func1(0x4b7eaa0, 0xc008688000, 0xc0087e0b00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/server/server.go:187 +0x95
net/http.HandlerFunc.ServeHTTP(0xc00332af30, 0x4b7eaa0, 0xc008688000, 0xc0087e0b00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener.HTTPRedirect.func1(0x4b7eaa0, 0xc008688000, 0xc0087e0b00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/redirect.go:20 +0x221
net/http.HandlerFunc.ServeHTTP(0xc003e28a40, 0x4b7eaa0, 0xc008688000, 0xc0087e0b00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.serverHandler.ServeHTTP(0xc006d38700, 0x4b7eaa0, 0xc008688000, 0xc0087e0b00)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc00df161e0, 0x4ba1da0, 0xc00604cb00)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e

time="2020-11-24 19:32:17" level=error msg="Failed to get project client ID c-5sdt8:p-b5p25 err=Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [] from [https://localhost:443/v3/project/c-5sdt8:p-b5p25/schemas]"
2020/11/24 19:32:17 [ERROR] Panic serving api request: 
goroutine 14375 [running]:
runtime/debug.Stack(0xc00cf82678, 0x3a0fa40, 0x7332a50)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP.func1(0x4b7fc20, 0xc00acefa10)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:175 +0x7a
panic(0x3a0fa40, 0x7332a50)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/rancher/pkg/clustermanager.(*Manager).CanList(0xc001111680, 0xc00de86b40, 0xc0016f83c0, 0xffffffffffffffff, 0x35)
	/go/src/github.com/rancher/rancher/pkg/clustermanager/rbac.go:31 +0x70
github.com/rancher/rancher/vendor/github.com/rancher/norman/types.(*Schema).CanList(0xc0016f83c0, 0xc00de86b40, 0xc0001c3ee0, 0x11)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/types/schema_funcs.go:32 +0x1c4
github.com/rancher/rancher/vendor/github.com/rancher/norman/store/schema.(*Store).List(0x738da68, 0xc00de86b40, 0xc000281e00, 0xc0084c9b00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/schema/schema_store.go:93 +0x32d
github.com/rancher/rancher/vendor/github.com/rancher/norman/store/wrapper.(*StoreWrapper).List(0xc00086ad30, 0xc00de86b40, 0xc000281e00, 0xc0084c9b00, 0x4287cf1, 0x3, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/wrapper/wrapper.go:40 +0x148
github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler.ListHandler(0xc00de86b40, 0x44284a0, 0xc000281e00, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler/list.go:26 +0x287
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).handle(0xc00002ea50, 0x4b7fc20, 0xc00acefa10, 0xc005605600, 0xc00cf82d08, 0xdddaaa5e, 0xf39ca49d5ca1901)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:249 +0x2a2
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP(0xc00002ea50, 0x4b7fc20, 0xc00acefa10, 0xc005605600)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:180 +0x99
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentTypeOptions.func1(0x4b7fc20, 0xc00acefa10, 0xc005605600)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/cache.go:47 +0x131
net/http.HandlerFunc.ServeHTTP(0xc00aa76300, 0x4b7fc20, 0xc00acefa10, 0xc005605600)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0018a80c0, 0x4b7fc20, 0xc00acefa10, 0xc005605400)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/pkg/auth/requests.authHeaderHandler.ServeHTTP(0x4b3f860, 0xc001834fc0, 0x4afdbc0, 0xc0018a80c0, 0x4b3f820, 0xc001741710, 0x4b7fc20, 0xc00acefa10, 0xc005605400)
	/go/src/github.com/rancher/rancher/pkg/auth/requests/filter.go:62 +0x4eb
github.com/rancher/rancher/pkg/rbac.NewAccessControlHandler.func1(0x4b7fc20, 0xc00acefa10, 0xc005605300, 0x4afcb80, 0xc00124c360)
	/go/src/github.com/rancher/rancher/pkg/rbac/user_based.go:32 +0x194
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/auth.Middleware.Wrap.func1(0x4b7fc20, 0xc00acefa10, 0xc005605300)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/auth/filter.go:36 +0x55
net/http.HandlerFunc.ServeHTTP(0xc001835180, 0x4b7fc20, 0xc00acefa10, 0xc005605300)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/pkg/websocket.websocketHandler.ServeHTTP(0x4b07c20, 0xc001835180, 0x4b7fc20, 0xc00acefa10, 0xc005605300)
	/go/src/github.com/rancher/rancher/pkg/websocket/handler.go:35 +0xa0
github.com/rancher/rancher/pkg/audit.auditHandler.ServeHTTP(0x4afcdc0, 0xc0004fbeb0, 0x0, 0x4b7fc20, 0xc00acefa10, 0xc005605300)
	/go/src/github.com/rancher/rancher/pkg/audit/filter.go:31 +0x623
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentType.func1(0x4b6da20, 0xc0085fbda0, 0xc005605300)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/content.go:33 +0x93
net/http.HandlerFunc.ServeHTTP(0xc0018d8400, 0x4b6da20, 0xc0085fbda0, 0xc005605300)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.Gzip.func1(0x4b7eaa0, 0xc00512c380, 0xc005605300)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/gzip.go:60 +0x1f5
net/http.HandlerFunc.ServeHTTP(0xc0018d8420, 0x4b7eaa0, 0xc00512c380, 0xc005605300)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentTypeOptions.func1(0x4b7eaa0, 0xc00512c380, 0xc005605300)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/cache.go:47 +0x131
net/http.HandlerFunc.ServeHTTP(0xc00aa76240, 0x4b7eaa0, 0xc00512c380, 0xc005605300)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0018a8000, 0x4b7eaa0, 0xc00512c380, 0xc005605100)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0027ed5c0, 0x4b7eaa0, 0xc00512c380, 0xc005604f00)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0027ed680, 0x4b7eaa0, 0xc00512c380, 0xc005604d00)
time="2020-11-24 19:32:17" level=error msg="Failed to get project client ID c-5sdt8:p-whwjb err=Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [] from [https://localhost:443/v3/project/c-5sdt8:p-whwjb/schemas]"
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0027ed740, 0x4b7eaa0, 0xc00512c380, 0xc005604b00)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/dashboard.Route.func2(0x4b7eaa0, 0xc00512c380, 0xc005604b00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/dashboard/ui.go:56 +0xe5
net/http.HandlerFunc.ServeHTTP(0xc0011c99f0, 0x4b7eaa0, 0xc00512c380, 0xc005604b00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc001fa7380, 0x4b7eaa0, 0xc00512c380, 0xc005604900)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/server.wrapHandler.func1(0x4b7eaa0, 0xc00512c380, 0xc005604900)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/server/server.go:187 +0x95
net/http.HandlerFunc.ServeHTTP(0xc00332af30, 0x4b7eaa0, 0xc00512c380, 0xc005604900)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener.HTTPRedirect.func1(0x4b7eaa0, 0xc00512c380, 0xc005604900)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/redirect.go:20 +0x221
net/http.HandlerFunc.ServeHTTP(0xc003e28a40, 0x4b7eaa0, 0xc00512c380, 0xc005604900)
	/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.serverHandler.ServeHTTP(0xc006d38700, 0x4b7eaa0, 0xc00512c380, 0xc005604900)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc002a719a0, 0x4ba1da0, 0xc0044c9f80)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e
```

**Other details that may be helpful:**

- Redeploy HA setup - rancher.
- Panic is seen in the logs

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.10 to 2.4.11-rc2
- Installation option (single install/HA): HA

**Comment by sowmyav27** [comment]
**Upgraded from 2.4.8 to 2.4.-head - commit id: `c334c235c`**

- Deployed few clusters, PNI enabled. Upgraded to 2.4-head - single install.
- No panic seen in rancher server logs.
