### ISSUE TITLE
"fatal error: concurrent map read and map write issue" - causes a panic in Rancher server

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#30224]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Have few custom clusters and AWS ROS node driver clusters with PNI enabled and disabled on the cluster.
- Upgrade from 2.4.8 to 2.4.11-rc2
- Panic seen in rancher logs:

```
2020/11/24 21:41:35 [INFO] APIVersion project.cattle.io/v3 Kind PipelineSetting
2020/11/24 21:41:35 [INFO] image changed for [share-mnt] old: rancher/rancher-agent:v2.4.8 new: rancher/rancher-agent:v2.4.11-rc2
2020/11/24 21:41:35 [INFO] image changed for [share-mnt] old: rancher/rancher-agent:v2.4.8 new: rancher/rancher-agent:v2.4.11-rc2
2020/11/24 21:41:35 [INFO] Starting management.cattle.io/v3, Kind=Cluster controller
2020/11/24 21:41:35 [INFO] image changed for [share-mnt] old: rancher/rancher-agent:v2.4.8 new: rancher/rancher-agent:v2.4.11-rc2
fatal error: concurrent map read and map write
goroutine 3964 [running]:
runtime.throw(0x42fd959, 0x21)
    /usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc0052079e0 sp=0xc0052079b0 pc=0x42fbc2
runtime.mapaccess2(0x38f87e0, 0xc004093470, 0xc0036aa488, 0xc005207ae0, 0x40c536)
    /usr/local/go/src/runtime/map.go:470 +0x278 fp=0xc005207a28 sp=0xc0052079e0 pc=0x40e398
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.(*Cluster).setClusterImageDefaults(0xc0036a9c00, 0xe, 0xc003710af0)
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/defaults.go:437 +0x86 fp=0xc005208248 sp=0xc005207a28 pc=0x22db7a6
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.(*Cluster).setClusterDefaults(0xc0036a9c00, 0x4ba1da0, 0xc002c34400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/defaults.go:210 +0x643 fp=0xc005208508 sp=0xc005208248 pc=0x22d99e3
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.InitClusterObject(0x4ba1da0, 0xc002c34400, 0xc005208900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/cluster.go:733 +0x387 fp=0xc0052085d8 sp=0xc005208508 pc=0x22d4037
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.GeneratePlan(0x4ba1da0, 0xc002c34400, 0xc005208900, 0xc003df5440, 0xc003df5470, 0x0, 0xc005208800, 0xc005208988, 0xc005208950, 0x456897)
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/plan.go:75 +0x95 fp=0xc0052088b0 sp=0xc0052085d8 pc=0x22ef2e5
github.com/rancher/rancher/pkg/librke.(*rke).GeneratePlan(0x0, 0x4ba1da0, 0xc002c34400, 0xc0035cca80, 0xc003df5440, 0xc003df5470, 0x0, 0x0, 0x0, 0x0, ...)
    /go/src/github.com/rancher/rancher/pkg/librke/rke.go:25 +0x82 fp=0xc005209260 sp=0xc0052088b0 pc=0x2347152
github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader.(*upgradeHandler).nonWorkerPlan(0xc000565ce0, 0xc007bec000, 0xc001a94a30, 0x0, 0x0, 0x0)
    /go/src/github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader/plan.go:40 +0x37d fp=0xc005209838 sp=0xc005209260 pc=0x26e652d
github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader.(*upgradeHandler).getNodePlan(0xc000565ce0, 0xc007bec000, 0xc001a94a30, 0xc003710aa0, 0x9, 0x0)
    /go/src/github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader/upgrade.go:225 +0x5f fp=0xc005209878 sp=0xc005209838 pc=0x26eb6cf
github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader.(*upgradeHandler).updateNodePlan(0xc000565ce0, 0xc007bec000, 0xc001a94a30, 0xc00070c300, 0x0, 0x0, 0x0)
    /go/src/github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader/upgrade.go:173 +0x1f6 fp=0xc0052099c0 sp=0xc005209878 pc=0x26eb106
github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader.(*upgradeHandler).Sync(0xc000565ce0, 0xc003ea63a0, 0x16, 0xc007bec000, 0xc00109e380, 0x7fe846c83008, 0x0, 0x0)
    /go/src/github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader/upgrade.go:154 +0x845 fp=0xc005209b10 sp=0xc0052099c0 pc=0x26ea3f5
github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader.(*upgradeHandler).Sync-fm(0xc003ea63a0, 0x16, 0xc007bec000, 0x10, 0x371e180, 0x1, 0xc0007f7750)
    /go/src/github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader/upgrade.go:63 +0x48 fp=0xc005209b60 sp=0xc005209b10 pc=0x26eeee8
github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3.(*nodeController).AddHandler.func1(0xc003ea63a0, 0x16, 0x4213000, 0xc007bec000, 0xc005209cb0, 0x3, 0x3, 0x0)
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_node_controller.go:154 +0x63 fp=0xc005209ba8 sp=0xc005209b60 pc=0x14773a3
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).syncHandler(0xc000fbb000, 0x371e440, 0xc0033ecfe0, 0x0, 0x0)
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:395 +0x371 fp=0xc005209cf0 sp=0xc005209ba8 pc=0xd45ce1
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).processNextWorkItem(0xc000fbb000, 0x0)
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:304 +0xef fp=0xc005209e10 sp=0xc005209cf0 pc=0xd451df
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).runWorker(0xc000fbb000)
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:292 +0x2b fp=0xc005209e30 sp=0xc005209e10 pc=0xd450cb
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).runWorker-fm()
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:291 +0x2a fp=0xc005209e48 sp=0xc005209e30 pc=0xd472ca
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0046ed050)
    /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5e fp=0xc005209eb8 sp=0xc005209e48 pc=0xca623e
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0046ed050, 0x4b01960, 0xc004f696e0, 0xc00457f901, 0xc0011ad980)
    /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3 fp=0xc005209f58 sp=0xc005209eb8 pc=0xca4f53
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0046ed050, 0x3b9aca00, 0x0, 0x1, 0xc0011ad980)
    /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0xaa fp=0xc005209f90 sp=0xc005209f58 pc=0xca4e7a
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0046ed050, 0x3b9aca00, 0xc0011ad980)
    /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d fp=0xc005209fc8 sp=0xc005209f90 pc=0xca4dbd
runtime.goexit()
```

**Other details that may be helpful:**
Clusters:
![Screen Shot 2020-11-24 at 4 47 46 PM](https://user-images.githubusercontent.com/26032343/100155261-f4053c80-2e74-11eb-80b0-4e4ea86ba19a.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.8 to 2.4.11-rc2
- Installation option (single install/HA): single

**Comment by sowmyav27** [comment]
Reopening this for the backport fixes from https://github.com/rancher/rancher/issues/30238

**Comment by sowmyav27** [comment]
Reopening for an RKE RC from `release/v1.1` branch and vendoring in changes to rancher

**Comment by sowmyav27** [comment]
**Upgraded from 2.4.12 to 2.4.13-rc1**

**Steps:**

- On 2.4.12, deployed an RKE cluster
- Ran pre upgrade checks
- Upgraded rancher to 2.4.13-rc1
- Post upgrade checks passed.
- No panics seen on the rancher server

Closing this issue

**Comment by WMP** [comment]
I have this same issue on 2.4.8, i found that previous line before trace log benn:
```
rancher-fbc69fc96-nvztp rancher 2021/02/02 09:30:03 [ERROR] SecretController p-jk9hd/harborcred [secretsController] failed with : Secret "harborcred" is invalid: type: Invalid value: "kubernetes.io/dockerconfigjson": field is immutable
```

I use kubernetes 1.16.13 installed from RKE 1.1.6, and i must make emergency upgrade rancher to 2.4.13, but this version dont support my kubernetes. Is possible to make backport to version 2.4.8 or 2.4.11 ?
