### ISSUE TITLE
LB service remains in degraded state when targets are added with Request Host.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3023]
Server version - V0.50.0-rc3

Steps to reproduce the problem:
Create a LB service add target with "Request Host".
Activate LB service.
LB service remains in degraded state.

Following exception seen in logs:

```
The blamed expression:
==> -2  [in template "jar:file:/usr/share/cattle/e28e8ac2715b5a43c3e510907fd1eb49/WEB-INF/lib/cattle-resources-0.5.0-SNAPSHOT.jar!/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl" at line 58, column 46]

The failing instruction (print stack trace for 1 more):
==> #elseif backend.portSpec.domain[-2..-...  [in template "jar:file:/usr/share/cattle/e28e8ac2715b5a43c3e510907fd1eb49/WEB-INF/lib/cattle-resources-0.5.0-SNAPSHOT.jar!/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl" at line 58, column 13]
	at freemarker.core.DynamicKeyName.dealWithRangeKey(DynamicKeyName.java:214) ~[freemarker-2.3.20.jar:2.3.20]
	at freemarker.core.DynamicKeyName._eval(DynamicKeyName.java:91) ~[freemarker-2.3.20.jar:2.3.20]
	at freemarker.core.Expression.eval(Expression.java:111) ~[freemarker-2.3.20.jar:2.3.20]
	at freemarker.core.EvalUtil.compare(EvalUtil.java:146) ~[freemarker-2.3.20.jar:2.3.20]
	at freemarker.core.ComparisonExpression.evalToBoolean(ComparisonExpression.java:103) ~[freemarker-2.3.20.jar:2.3.20]
	at freemarker.core.IfBlock.accept(IfBlock.java:82) [freemarker-2.3.20.jar:2.3.20]
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:286) [freemarker-2.3.20.jar:2.3.20]
	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:86) [freemarker-2.3.20.jar:2.3.20]
	at freemarker.core.Environment.visit(Environment.java:265) [freemarker-2.3.20.jar:2.3.20]
	at freemarker.core.MixedContent.accept(MixedContent.java:93) [freemarker-2.3.20.jar:2.3.20]
	at freemarker.core.Environment.visit(Environment.java:265) [freemarker-2.3.20.jar:2.3.20]
	at freemarker.core.IfBlock.accept(IfBlock.java:84) [freemarker-2.3.20.jar:2.3.20]
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:286) [freemarker-2.3.20.jar:2.3.20]
	at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:193) [freemarker-2.3.20.jar:2.3.20]
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:509) [freemarker-2.3.20.jar:2.3.20]
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:103) [freemarker-2.3.20.jar:2.3.20]
	at freemarker.core.Environment.visit(Environment.java:265) [freemarker-2.3.20.jar:2.3.20]
	at freemarker.core.MixedContent.accept(MixedContent.java:93) [freemarker-2.3.20.jar:2.3.20]
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:286) [freemarker-2.3.20.jar:2.3.20]
	at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:193) [freemarker-2.3.20.jar:2.3.20]
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:509) [freemarker-2.3.20.jar:2.3.20]
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:103) [freemarker-2.3.20.jar:2.3.20]
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:286) [freemarker-2.3.20.jar:2.3.20]
	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:86) [freemarker-2.3.20.jar:2.3.20]
	at freemarker.core.Environment.visit(Environment.java:265) [freemarker-2.3.20.jar:2.3.20]
	at freemarker.core.MixedContent.accept(MixedContent.java:93) [freemarker-2.3.20.jar:2.3.20]
	at freemarker.core.Environment.visit(Environment.java:265) [freemarker-2.3.20.jar:2.3.20]
	at freemarker.core.Environment.process(Environment.java:243) [freemarker-2.3.20.jar:2.3.20]
	at freemarker.template.Template.process(Template.java:277) [freemarker-2.3.20.jar:2.3.20]
	at io.cattle.platform.configitem.server.template.impl.FreemarkerTemplate.execute(FreemarkerTemplate.java:42) [cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.server.template.TemplatesBasedArchiveItem$1.with(TemplatesBasedArchiveItem.java:48) [cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.server.model.impl.AbstractArchiveBasedConfigItem.withEntry(AbstractArchiveBasedConfigItem.java:125) [cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.server.template.TemplatesBasedArchiveItem.writeContent(TemplatesBasedArchiveItem.java:45) [cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.server.model.impl.AbstractArchiveBasedConfigItem.handleRequest(AbstractArchiveBasedConfigItem.java:59) [cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.server.impl.ConfigItemServerImpl.handleDownload(ConfigItemServerImpl.java:97) [cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.server.impl.ConfigItemServerImpl.handleRequest(ConfigItemServerImpl.java:40) [cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.api.manager.ConfigContentManager.handle(ConfigContentManager.java:80) [cattle-config-item-api-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.api.manager.ConfigContentManager.getByIdInternal(ConfigContentManager.java:49) [cattle-config-item-api-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.getById(AbstractBaseResourceManager.java:61) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.ResourceManagerRequestHandler.generate(ResourceManagerRequestHandler.java:49) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.AbstractResponseGenerator.handle(AbstractResponseGenerator.java:14) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.handle(DefaultReadWriteApiDelegate.java:27) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.read(DefaultReadWriteApiDelegate.java:17) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at sun.reflect.GeneratedMethodAccessor554.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_91]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_91]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) [spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) [spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) [spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96) [spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260) [spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94) [spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) [spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) [spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at com.sun.proxy.$Proxy43.read(Unknown Source) [na:na]
	at io.github.ibuildthecloud.gdapi.request.handler.write.ReadWriteApiHandler.handle(ReadWriteApiHandler.java:21) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:86) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:84) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:77) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [jetty-security-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.Server.handle(Server.java:499) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_91]

```

**Comment by alena1108** [comment]
Regression caused by https://github.com/rancher/cattle/pull/1182

**Comment by sangeethah** [comment]
Tested with Server version - V0.50.0-rc4

LB services that have targets added with Request Host works as expected.
