### ISSUE TITLE
Docker unable to find convoy plugin while using gluster-convoy default template

### ISSUE THREAD

**Issue by CBR09** [rancher/rancher#3038]
Hi @deniseschannon, @cjellick, @ibuildthecloud 
Following the solution from this issue #2836 , I was able to launch glusterfs with convoy plugin using default template.
My environment:
**rancherOS**
>[docker@node1 ~]$ ros --version
ros version v0.4.1

**rancher platform**
>Component	Version
Rancher	v0.50.0
Cattle	v0.126.0
User Interface	v0.74.0
Rancher Compose	v0.6.2

After succesfully lauch the services, I got the following issue while trying to create a volume with docker volume command
>[docker@node1 ~]$ sudo docker volume create --driver=convoy --name=test
Error response from daemon: Error looking up volume plugin convoy: Plugin not found

**docker deamon log**:
>time="2015-12-16T10:48:15.543173394Z" level=info msg="POST /v1.21/volumes/create" 
time="2015-12-16T10:48:15.543361348Z" level=warning msg="Unable to locate plugin: convoy, retrying in 1s" 
time="2015-12-16T10:48:16.544590100Z" level=warning msg="Unable to locate plugin: convoy, retrying in 2s" 
time="2015-12-16T10:48:18.545480343Z" level=warning msg="Unable to locate plugin: convoy, retrying in 4s" 
time="2015-12-16T10:48:18.765697332Z" level=info msg="GET /v1.18/containers/json?all=1&limit=-1&trunc_cmd=0&size=0" 
time="2015-12-16T10:48:18.774472344Z" level=info msg="GET /v1.18/containers/json?all=0&limit=-1&trunc_cmd=0&size=0" 
time="2015-12-16T10:48:22.545831777Z" level=warning msg="Unable to locate plugin: convoy, retrying in 8s" 
time="2015-12-16T10:48:23.765954605Z" level=info msg="GET /v1.18/containers/json?all=1&limit=-1&trunc_cmd=0&size=0" 
time="2015-12-16T10:48:23.769548007Z" level=info msg="GET /v1.18/containers/json?all=0&limit=-1&trunc_cmd=0&size=0" 
time="2015-12-16T10:48:28.796613004Z" level=info msg="GET /v1.18/containers/json?all=1&limit=-1&trunc_cmd=0&size=0" 
time="2015-12-16T10:48:28.806082198Z" level=info msg="GET /v1.18/containers/json?all=0&limit=-1&trunc_cmd=0&size=0" 
time="2015-12-16T10:48:30.547218786Z" level=error msg="Handler for POST /v1.21/volumes/create returned error: Error looking up volume plugin convoy: Plugin not found" 
time="2015-12-16T10:48:30.547380835Z" level=error msg="HTTP Error" err="Error looking up volume plugin convoy: Plugin not found" statusCode=404 

Do you have any suggestion for this issue?
Thanks

**Comment by teon** [comment]
+1 - I've setup glusterfs + gluster convoy from catalog - then created a copose file with 'volume_driver: convoy' and the server has in logs:
```2015-12-16 14:25:50,095 ERROR [e898d0c7-0817-49c8-a371-46280081b6fc:7585] [instance:160->instanceHostMap:160] [instance.start->(InstanceStart)->instancehostmap.activate] [] [cutorService-19] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.eventing.exception.EventExecutionException: 713574a5-69a7-4a37-b751-a9a75a8c172f : 404 Client Error: Not Found ("Error looking up volume plugin convoy: Plugin not found")
	at io.cattle.platform.eventing.exception.EventExecutionException.fromEvent(EventExecutionException.java:53) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.agent.impl.RemoteAgentImpl.callSync(RemoteAgentImpl.java:72) ~[cattle-iaas-agent-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.agent.impl.RemoteAgentImpl.callSync(RemoteAgentImpl.java:158) ~[cattle-iaas-agent-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.common.handler.AgentBasedProcessHandler.callSync(AgentBasedProcessHandler.java:170) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.common.handler.AgentBasedProcessHandler.handleEvent(AgentBasedProcessHandler.java:156) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.common.handler.AgentBasedProcessHandler.handle(AgentBasedProcessHandler.java:101) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:456) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:396) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:390) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:390) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:520) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:323) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:259) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:256) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:188) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:161) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:110) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:107) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:107) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.executeStandardProcess(DefaultObjectProcessManager.java:29) [cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.common.handler.AbstractObjectProcessLogic.activate(AbstractObjectProcessLogic.java:31) [cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.instance.InstanceStart.compute(InstanceStart.java:220) [cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.instance.InstanceStart.handle(InstanceStart.java:85) [cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:456) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:396) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:390) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:390) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:520) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:323) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:259) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:256) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:188) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:161) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:110) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:107) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:107) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.eventing.impl.ProcessEventListenerImpl.processExecute(ProcessEventListenerImpl.java:66) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at sun.reflect.GeneratedMethodAccessor516.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_91]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_91]
	at io.cattle.platform.eventing.annotation.MethodInvokingListener$1.doWithLockNoResult(MethodInvokingListener.java:76) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.annotation.MethodInvokingListener.onEvent(MethodInvokingListener.java:72) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_91]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_91]```

**Comment by cjellick** [comment]
@CBR09 @teon The name of the driver is going to be the name of the convoy gluster storage pool, which by default is convoy-gluster, not just 'convoy'. Have you tried convoy-gluster as the driver name?

**Comment by teon** [comment]
@cjellick the plugin name I've entered in the docker compose: *convoy* was suggested by your blog post (and the youtube tutorial from there): http://rancher.com/how-rancher-storage-services-unleash-the-power-of-software-defined-storage/ - there in docker compose file was this name.

Never the less, still it doesn't work - i've entered: *convoy-gluster* as you suggested and still it doesn't work:

```2015-12-16 16:37:18,815 ERROR [d6652c6b-a642-40ab-86e4-a833494971f6:8305] [instance:190] [instance.start->(InstanceStart)] [] [cutorService-14] [i.c.p.process.instance.InstanceStart] Failed to Starting for instance [190]
2015-12-16 16:37:18,819 ERROR [d6652c6b-a642-40ab-86e4-a833494971f6:8305] [instance:190] [instance.start] [] [cutorService-14] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.eventing.exception.EventExecutionException: 70cd0c55-72b8-4763-beb7-4a0df393b204 : 404 Client Error: Not Found ("Error looking up volume plugin convoy-gluster: Plugin not found")
	at io.cattle.platform.eventing.exception.EventExecutionException.fromEvent(EventExecutionException.java:53) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.agent.impl.RemoteAgentImpl.callSync(RemoteAgentImpl.java:72) ~[cattle-iaas-agent-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.agent.impl.RemoteAgentImpl.callSync(RemoteAgentImpl.java:158) ~[cattle-iaas-agent-0.5.0-SNAPSHOT.jar:na]```

**Comment by cjellick** [comment]
@teon Can you check your rancher-agent logs to see if there is anything interesting there and post it here?

**Comment by teon** [comment]
@cjellick yup, here are my agent logs:
```
time="2015-12-16T20:15:11Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"destroy\", ID:\"7c14fecb4cb16e42794d3b3a536964728e32e3c0031f6136bf048ae7c4d63a10\", From:\"tcn.re/service/ldap:latest\", Time:1450296911}"
2015-12-16 20:15:11,538 ERROR agent [140550618109424] [event.py:111] 82ff91e5-f15e-48ff-84bc-5096a5d1da5a : Unknown error
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 94, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 34, in execute
    return method(req=req, **req.data.__dict__)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 527, in instance_activate
    self._do_instance_activate(instance, host, progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 590, in _do_instance_activate
    progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 636, in _create_container
    name)
  File "/var/lib/cattle/pyagent/dist/docker/api/container.py", line 127, in create_container_from_config
    return self._result(res, True)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 146, in _result
    self._raise_for_status(response)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 141, in _raise_for_status
    raise errors.NotFound(e, response, explanation=explanation)
NotFound: 404 Client Error: Not Found ("Error looking up volume plugin convoy-gluster: Plugin not found")```

**Comment by teon** [comment]
glusterfs (from catalog) and convoy-gluster are running - all done with help and exactly the same configuration as in the blog post I recently referenced.

**Comment by cjellick** [comment]
@teon Are all your hosts in the storage pool? On the storage pool page, it lists the hosts that are part of the storage pool.

The symptoms your are describing lead me to believe that convoy-gluster is not being deployed to all hosts and that containers are being deployed to a host where convoy-gluster is not running.

**Comment by teon** [comment]
@cjellick I'm testing Rancher before deploying to production and have only one host in this environment. So I've deployed glusterfs and convoy only on one host. So all servers and convoy are running on one host.

**Comment by cjellick** [comment]
ok @teon. Could you share the logs for the container with image `rancher/convoy-agent` and command `"/launch volume-agent"`?

Also, on the host, are there any files in /etc/docker/plugins? There should be a file there can you share its contents (which should just be a path to a socket filed).

Finally, what version of ranher and docker are you running?

**Comment by teon** [comment]
@cjellick logs for the convoy-agent container:

```
time="2015-12-16T11:34:14Z" level=info msg="Listening for health checks on 0.0.0.0:10241/healthcheck"
time="2015-12-16T11:34:20Z" level=debug msg="storagepool event [75af02f4-169c-4ac7-845f-2a5afd40f12e]"
```

I think there is an error in the launching volume agent command, sine it does nothing but displaying the help, here is copy paste of few commands I run in the container (I've also run the storepool-agent command to see what will happened):

```
root@ac22bf155424:/# /launch volume-agent                                       
Usage: /launch {volume-agent|storagepool-agent}                                 
root@ac22bf155424:/# /launch volume-agent                                       
Usage: /launch {volume-agent|storagepool-agent}                                 
root@ac22bf155424:/# /launch storagepool-agent                                  
Waiting for metadataINFO[0000] Listening for health checks on 0.0.0.0:10241/heal
thcheck                                                                         
FATA[0000] Error while running healthcheck [listen tcp :10241: bind: address alr
eady in use]                                                                    
root@ac22bf155424:/#                    
```
Software version:
```
Component	Version
Rancher	v0.50.0
Cattle	v0.126.0
User Interface	v0.74.0
Rancher Compose	v0.6.2
```

**Comment by cjellick** [comment]
Can you post the output of `docker ps -a`?

**Comment by teon** [comment]
sure:

```
ac22bf155424        rancher/convoy-agent:v0.1.2     "/launch storagepool-"   10 hours ago        Up 10 hours                                                              6f9f5f4b-d974-4b2b-a216-cd025dbc35b3
26d8603a95d1        rancher/glusterfs:v0.1.3        "/opt/rancher/replica"   11 hours ago        Exited (0) 11 hours ago                                                  ac5accaa-5a17-4ffb-ad38-ce25c5dec419
7a8af0a4f74c        rancher/glusterfs:v0.1.3        "/opt/rancher/peerpro"   11 hours ago        Up 11 hours                                                              087e9e7c-9394-4116-84cd-3d58f1c06006
84e3dae1e214        rancher/glusterfs:v0.1.3        "glusterd -p /var/run"   11 hours ago        Up 11 hours               24007-24008/tcp, 49152/tcp, 24007-24008/udp    46ff9a8e-a1c5-4720-896b-71cd2c60cd99
90584bdbfbce        rancher/glusterfs:v0.1.3        "/bin/true"              11 hours ago        Exited (0) 11 hours ago                                                  f0fc7854-4649-409e-852c-6fe3b1cfa9d0
53749e928e0a        rancher/glusterfs:v0.1.3        "/opt/rancher/replica"   11 hours ago        Exited (0) 11 hours ago                                                  c4ebe59a-9b79-45ab-b33c-aaedee1ef9bd
e9c81f8ff862        rancher/glusterfs:v0.1.3        "/opt/rancher/peerpro"   11 hours ago        Up 11 hours                                                              71a5c663-1a9b-4b00-9125-47723ded7875
ddd0864dec5b        rancher/glusterfs:v0.1.3        "glusterd -p /var/run"   11 hours ago        Up 11 hours               24007-24008/tcp, 49152/tcp, 24007-24008/udp    3ed86860-2306-49e8-ae9d-b69a3873ded9
4d273cc1ead5        rancher/glusterfs:v0.1.3        "/bin/true"              11 hours ago        Exited (0) 11 hours ago                                                  59b41ce4-a6af-47af-b38e-40b25af6edf7
89bce7b26df0        rancher/glusterfs:v0.1.3        "/opt/rancher/replica"   11 hours ago        Exited (0) 10 hours ago                                                  f3702a1b-2f4a-4220-8d00-f233eea91f1f
d65c77af6193        rancher/glusterfs:v0.1.3        "/opt/rancher/peerpro"   11 hours ago        Up 11 hours                                                              5f031d8d-27a9-4661-a731-68199e58a5b7
09d34b116730        rancher/glusterfs:v0.1.3        "glusterd -p /var/run"   11 hours ago        Up 11 hours               24007-24008/tcp, 49152/tcp, 24007-24008/udp    a87f66e1-2923-456c-b9f4-96062cbc9e6c
086bc670a7d4        rancher/glusterfs:v0.1.3        "/bin/true"              11 hours ago        Exited (0) 11 hours ago                                                  a51f7f1a-a781-42d5-8c30-7971313d4c53
5e19a2623d49        rancher/agent-instance:v0.6.0   "/etc/init.d/agent-in"   11 hours ago        Up 11 hours               0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp   16a8e348-f386-47e1-a464-9c5707dabdaa
f69330438231        rancher/agent:v0.8.2            "/run.sh run"            11 hours ago        Up 11 hours                                                              rancher-agent
a05b141fb1d9        rancher/agent:v0.8.2            "/run.sh state"          11 hours ago        Exited (0) 11 hours ago                                                  rancher-agent-state
9da611af25a7        rancher/agent:v0.8.2            "/run.sh https://plei"   11 hours ago        Exited (0) 11 hours ago                                                  determined_heisenberg
```

**Comment by teon** [comment]
@cjellick This is docker ps -a from the host on which the agent runs and storage/gluster/convoy runs.

**Comment by cjellick** [comment]
Cool. Thanks.

There should be two rancher/convoy-agent containers running here: one with the command `/launch storage-pool` and one with the command `/launch volume-agent-glusterfs`.

I only see `/launch storage-pool` running. This is usually caused by the host not having the label specified in the convoy-gluster catalog entry. The volume agent is only deployed to hosts that have that label. By default in the convoy-gluster catalog, the label is `convoy.glusterfs=true`. Does your host have this label in the rancher UI? If not, you can add it by going to the infrastructure tab, clicking the dropdown arrow in the top right corner of your host, clicking edit, and adding the label.

**Comment by teon** [comment]
That helped! The host did not have the label, so I've added the label by hand and after adding, automatically **convoy-gluster_convoy-gluster_1** container was launched. After that the stack using the convoy-gluster volume also launched ;-)

**Comment by cjellick** [comment]
Sorry it took so long and that I didnt ask that sooner!

**Comment by teon** [comment]
@cjellick no need! you guys are doing great work with rancher so I would like to thank you for that! I have high hopes for racher so getting back to work ;-)

**Comment by cjellick** [comment]
haha :+1:

**Comment by teon** [comment]
@cjellick having you on the line - one question regarding storage - I see that all this are working, so I would like to expand the cluster. After adding another host to the cluster how should I migrate (or will rancher do it automatically) one of the 3 gluster-server to new host?

**Comment by teon** [comment]
Also should I deploy convoy-gluster container and tag it with *convoy.glusterfs=true* on that new host?

**Comment by cjellick** [comment]
@teon 
To your first question: scaling/migrating glusterfs is a little tricky. When we first spin up the glusterfs stack, we create a single glusterfs volume (note this is the gluster concept of a volume and not the docker concept). That volume has three replicas (they use the term 'brick') -one on each host. If you added a host and killed one of the glusterfs-server containers, a new container would be created on the second host and that container would join the glusterfs pool. BUT it would not automatically start building a replica/brick for the existing volume. To get it do that would require manual glusterfs commands to add a brick to the existing glusterfs volume using the new container/node.
Hopefully that makes sense.

So, if you don't want to mess with those manual glusterfs volume/brick commands, you may want to start over with three hosts so that glusterfs gets deployed across them. If you did this, you'd need to delete both the glusterfs and convoy-glusterfs stacks and start over.

To your second question: on any host that you want to use the convoy-gluster plugin on, you must also have the convoy-agent running there. So, you must add the label `convoy.glusterfs=true` label there. The convoy glusterfs service scales nicely and just adding hosts and adding the label works perfectly well.

**Comment by CBR09** [comment]
Thanks @cjellick, using 'convoy-gluster' instead 'convoy', everything is okay. I was able to lauch container with convoy-gluster driver.

Ah, I have a question about storage, When deploying convoy-agent, I saw a convoy-agent running with command "/launch storage-pool", What purpose do this container for?

**Comment by teon** [comment]
@cjellick I followed your advice and bootstraped from scrach. I've installed rancher 0.50.1 added 2 hosts (clean dockers) - deployed example container to run on each host - network agents were bootstraped - all seem to work fine.
Now deploying glusterfs from catalog - and... all 3 servers, volumes were created just on one host. Why?
Clicking "Scale +1" and the fourth gluster server is also deployed to the first host.. why?

Don't know how to create a REAL gluster storege... one host storege is no network storage...

**Comment by cjellick** [comment]
@CBR09 The `/launch volume-agent` containers are the ones that actually start convoy and register it as a plugin for docker.

The `/launch storagepool-agent` container manages metadata about all the `/launch volume-agent` containers. It reports monitors and reports to rancher-server about what hosts are in the storage pool.

I should mention that the `/launch volume-agent` containers _also_ send metadata to rancher-server. They report to rancher when convoy volumes are created and destroyed.

**Comment by cjellick** [comment]
@teon That is very strange. The glsuterfs catalog has a soft anti-affinity scheduling rule that should have caused it to get deployed across the two hosts. Could be a new/separate bug. But you are absolutely correct in expecting it to deploy across those two hosts.

**Comment by teon** [comment]
@cjellick the question is right now - what can I do? I'm holding my rancher deployment - since I need persistant storage across all hosts... ;-(

**Comment by cjellick** [comment]
@teon can you destroy and redeploy the the glusterfs catalog item and see if it gets deployed across the two hosts?

Quick question: are you running rancher-server on one of the two hosts?

**Comment by teon** [comment]
@cjellick Redeploymet still deploys on one host. Rancher server is on different host then two hosts in cluster.

**Comment by cjellick** [comment]
Oh, @teon we apparently removed the soft anti-affinity rule for the glusterfs stack. I'm looking into why we did that. In the meantime, the stack is going to deploy following the default "least containers" rule which deploys containsers to the the host with the least number of containers.

**Comment by teon** [comment]
@cjellick I've submitted new bug with all my few days work: #3066

**Comment by bscott** [comment]
I'm currently having an issue where I have all the correct labels and agents running but still cant get driver working.

```
ERROR: Error looking up volume plugin convoy-gluster: Plugin not found
```

**Comment by deniseschannon** [comment]
@teon When reading through this, I don't think there are any more option issues with "Docker unable to find convoy plugin while using gluster-convoy default template". 

I'm going to close. If you have other issues that aren't in #3066, please open a new issue.
