### ISSUE TITLE
V1 Logging on recently upgraded/created AKS clusters fails with "Connection reset by peer"

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#30425]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

Launch Rancher v2.4.8+ and create an AKS cluser of any version with it. Enable Rancher logging.

**Result:**

After some time fluentd containers will error out with the following:

```
Unexpected error error reading from socket: Connection reset by peer
  /usr/lib/ruby/2.3.0/openssl/buffering.rb:125:in `sysread'
  /usr/lib/ruby/2.3.0/openssl/buffering.rb:125:in `readpartial'
  /var/lib/gems/2.3.0/gems/http-4.2.0/lib/http/timeout/null.rb:45:in `readpartial'
  /var/lib/gems/2.3.0/gems/http-4.2.0/lib/http/connection.rb:212:in `read_more'
  /var/lib/gems/2.3.0/gems/http-4.2.0/lib/http/connection.rb:92:in `readpartial'
  /var/lib/gems/2.3.0/gems/http-4.2.0/lib/http/response/body.rb:30:in `readpartial'
  /var/lib/gems/2.3.0/gems/http-4.2.0/lib/http/response/body.rb:36:in `each'
  /var/lib/gems/2.3.0/gems/kubeclient-4.5.0/lib/kubeclient/watch_stream.rb:25:in `each'
  /var/lib/gems/2.3.0/gems/fluent-plugin-kubernetes_metadata_filter-2.4.1/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:49:in `start_pod_watch'
  /var/lib/gems/2.3.0/gems/fluent-plugin-kubernetes_metadata_filter-2.4.1/lib/fluent/plugin/filter_kubernetes_metadata.rb:267:in `block in configure'
```

**Other details that may be helpful:**

A customer is seeing the same issue on AKS v1.16.13. So it doesn't seem to be 1.x dependant

It's also worth noting that the customer has calico installed, but I do not. Changing the image tag to v0.1.21 doesn't change anything either as the kubernetes gem version is the same.

gz#13307

**Comment by bentastic27** [comment]
A possible fix is to upgrade the kubernetes plugin to 2.4.2. There was some retry logic added that should help with this. Apparently, this is an issue with timeouts if there is some kind of proxy between the pod and the Kube API. In AKS this is Tunnelfront if I'm not mistaken.

https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/194

**Comment by bentastic27** [comment]
I downloaded the Dockerfile stuff for the fluentd daemonset and upped the k8s plugin version to 2.4.7. It seemed much more resilient and failed less, but it eventually errored out and exited with the following:

```
Unexpected error Exception encountered parsing pod watch event. The connection might have been closed. Retried 10 times yet still failing. Restarting.
12/10/2020 4:31:51 PM   /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.4.7/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:76:in `rescue in set_up_pod_thread'
12/10/2020 4:31:51 PM   /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.4.7/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:46:in `set_up_pod_thread'
12/10/2020 4:31:51 PM   /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.4.7/lib/fluent/plugin/filter_kubernetes_metadata.rb:276:in `block in configure'
```

It seems to me that the restart is intentional in this case as the message indicates.

**Comment by bentastic27** [comment]
It seems as though similar errors come up for V2 monitoring as well:

```
I1216 09:08:43.422629       1 trace.go:116] Trace[703420834]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105 (started: 2020-12-16 09:08:13.422229967 +0000 UTC m=+52388.189702170) (total time: 30.000383038s):
Trace[703420834]: [30.000383038s] [30.000383038s] END
E1216 09:08:43.422703       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: Failed to list *v1.StatefulSet: Get https://10.0.0.1:443/apis/apps/v1/statefulsets?limit=500&resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout
W1216 11:05:07.254721       1 reflector.go:326] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: watch of *v1.DaemonSet ended with: very short watch: pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: Unexpected watch close - watch lasted less than a second and no items received
W1216 11:05:07.255495       1 reflector.go:326] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: watch of *v1.Role ended with: very short watch: pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: Unexpected watch close - watch lasted less than a second and no items received
```

**Comment by izaac** [comment]
Reproduced on Rancher `v2.4.11`

The error appears after ~3 minutes:

```
, pod_cache_host_updates: 8
Unexpected error error reading from socket: Connection reset by peer
  /usr/lib/ruby/2.3.0/openssl/buffering.rb:125:in `sysread'
  /usr/lib/ruby/2.3.0/openssl/buffering.rb:125:in `readpartial'
  /var/lib/gems/2.3.0/gems/http-4.2.0/lib/http/timeout/null.rb:45:in `readpartial'
  /var/lib/gems/2.3.0/gems/http-4.2.0/lib/http/connection.rb:212:in `read_more'
  /var/lib/gems/2.3.0/gems/http-4.2.0/lib/http/connection.rb:92:in `readpartial'
  /var/lib/gems/2.3.0/gems/http-4.2.0/lib/http/response/body.rb:30:in `readpartial'
  /var/lib/gems/2.3.0/gems/http-4.2.0/lib/http/response/body.rb:36:in `each'
  /var/lib/gems/2.3.0/gems/kubeclient-4.5.0/lib/kubeclient/watch_stream.rb:25:in `each'
  /var/lib/gems/2.3.0/gems/fluent-plugin-kubernetes_metadata_filter-2.4.1/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:36:in `start_namespace_watch'
  /var/lib/gems/2.3.0/gems/fluent-plugin-kubernetes_metadata_filter-2.4.1/lib/fluent/plugin/filter_kubernetes_metadata.rb:269:in `block in configure'
```

**Comment by izaac** [comment]
Rancher version `v2.4.13-rc1 (01/12/2020)` 
rancher-logging v1 chart version: `0.2.4`
Azure AKS: `v1.18.10`
Docker: `19.3.12`

I left logging collecting the cluster container logs for 3 hours I didn't see the exception thrown on any of the fluentd containers.
Logs where flowing properly during this time window.

**Comment by izaac** [comment]
Rancher version `v2.5-head (01/12/2020)` _65a15b9_
rancher-logging v1 chart version: `0.2.4`
Azure AKS: `v1.18.10`
Docker: `19.3.12`

I left logging collecting the cluster container logs for 2 hours I didn't see the exception thrown on any of the fluentd containers.
Logs where flowing properly during this time window.

Logging provider: Elasticsearch `7.8.0`

Repro details: https://github.com/rancher/rancher/issues/30425#issuecomment-749581725
