### ISSUE TITLE
Panics in Rancher server and it crashes after an upgrade

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#30434]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a PNI enabled cluster - 1 etcd/control, 3 workker nodes. Enable cluster level monitoring
- Upgrade rancher from 2.5.2 to 2.5-head.
- Rancher server logs:

```
2020/12/11 06:37:11 [DEBUG] Skipping refresh for user-kt8xj due to max-age
2020/12/11 06:37:11 [DEBUG] Triggering auth refresh on user-kt8xj
2020/12/11 06:37:11 [DEBUG] Skipping refresh for user-kt8xj due to max-age
2020/12/11 06:37:11 [ERROR] Panic serving api request: 
goroutine 11266 [running]:
runtime/debug.Stack(0xc007372820, 0x3c3df00, 0x73c0820)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/rancher/norman/api.(*Server).ServeHTTP.func1(0x4ea7940, 0xc007680340)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200930000340-693d65aaffe3/api/server.go:175 +0x7a
panic(0x3c3df00, 0x73c0820)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/rancher/rancher/pkg/clustermanager.(*Manager).CanList(0xc00192b8c0, 0xc007675c20, 0xc001ff74a0, 0x600000004e28680, 0xffffffffffffffff)
	/go/src/github.com/rancher/rancher/pkg/clustermanager/rbac.go:31 +0x70
github.com/rancher/norman/types.(*Schema).CanList(0xc001ff74a0, 0xc007675c20, 0xc0004bb0a0, 0xa)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200930000340-693d65aaffe3/types/schema_funcs.go:32 +0x1c4
github.com/rancher/norman/store/schema.(*Store).List(0x74464a8, 0xc007675c20, 0xc002e16000, 0xc003201b00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200930000340-693d65aaffe3/store/schema/schema_store.go:93 +0x32d
github.com/rancher/norman/store/wrapper.(*StoreWrapper).List(0xc00043bbd0, 0xc007675c20, 0xc002e16000, 0xc003201b00, 0x44f1597, 0x3, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200930000340-693d65aaffe3/store/wrapper/wrapper.go:40 +0x148
github.com/rancher/norman/api/handler.ListHandler(0xc007675c20, 0x46c1098, 0xc002e16000, 0x0)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200930000340-693d65aaffe3/api/handler/list.go:26 +0x287
github.com/rancher/norman/api.(*Server).handle(0xc0008914a0, 0x4ea7940, 0xc007680340, 0xc003508c00, 0x40a838, 0x407df60, 0xc007680340)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200930000340-693d65aaffe3/api/server.go:249 +0x276
github.com/rancher/norman/api.(*Server).ServeHTTP(0xc0008914a0, 0x4ea7940, 0xc007680340, 0xc003508c00)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200930000340-693d65aaffe3/api/server.go:180 +0x7d
github.com/rancher/apiserver/pkg/middleware.ContentType.func1(0x4e93f00, 0xc004df9380, 0xc003508c00)
	/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20201023000256-1a0a904f9197/pkg/middleware/content.go:33 +0x93
net/http.HandlerFunc.ServeHTTP(0xc0022e2f60, 0x4e93f00, 0xc004df9380, 0xc003508c00)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/rancher/apiserver/pkg/middleware.Gzip.func1(0x4ea6c00, 0xc009b4e700, 0xc003508c00)
	/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20201023000256-1a0a904f9197/pkg/middleware/gzip.go:60 +0x1d5
net/http.HandlerFunc.ServeHTTP(0xc0022e2f80, 0x4ea6c00, 0xc009b4e700, 0xc003508c00)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/rancher/rancher/pkg/auth/requests.authHeaderHandler.ServeHTTP(0x4e32d20, 0xc0022e2f80, 0x4ea6c00, 0xc009b4e700, 0xc003508c00)
	/go/src/github.com/rancher/rancher/pkg/auth/requests/filter.go:49 +0x4d3
github.com/rancher/rancher/pkg/rbac.NewAccessControlHandler.func1.1(0x4ea6c00, 0xc009b4e700, 0xc003508b00)
	/go/src/github.com/rancher/rancher/pkg/rbac/user_based.go:33 +0x1ae
net/http.HandlerFunc.ServeHTTP(0xc00706f6e0, 0x4ea6c00, 0xc009b4e700, 0xc003508b00)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/rancher/steve/pkg/auth.ToMiddleware.func1.1(0x4ea6c00, 0xc009b4e700, 0xc003508a00)
	/go/pkg/mod/github.com/rancher/steve@v0.0.0-20201110183734-21c7add15f64/pkg/auth/filter.go:156 +0x1bd
net/http.HandlerFunc.ServeHTTP(0xc004df9260, 0x4ea6c00, 0xc009b4e700, 0xc003508a00)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001ff140, 0x4ea6c00, 0xc009b4e700, 0xc003508600)
	/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001fefc0, 0x4ea6c00, 0xc009b4e700, 0xc003508400)
	/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2
github.com/rancher/rancher/pkg/multiclustermanager.(*DeferredServer).Middleware.func1(0x4ea6c00, 0xc009b4e700, 0xc003508400)
	/go/src/github.com/rancher/rancher/pkg/multiclustermanager/deferred.go:100 +0x98
net/http.HandlerFunc.ServeHTTP(0xc0004c7e00, 0x4ea6c00, 0xc009b4e700, 0xc003508400)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0004ecd80, 0x4ea6c00, 0xc009b4e700, 0xc003508100)
	/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2
github.com/rancher/rancher/pkg/api/steve/proxy.NewProxyMiddleware.func1.1(0x4ea6c00, 0xc009b4e700, 0xc003508100)
	/go/src/github.com/rancher/rancher/pkg/api/steve/proxy/proxy.go:75 +0x60
net/http.HandlerFunc.ServeHTTP(0xc0004c7e40, 0x4ea6c00, 0xc009b4e700, 0xc003508100)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/rancher/rancher/pkg/api/steve/proxy.RewriteLocalCluster.func1(0x4ea6c00, 0xc009b4e700, 0xc003508100)
	/go/src/github.com/rancher/rancher/pkg/api/steve/proxy/proxy.go:43 +0xef
net/http.HandlerFunc.ServeHTTP(0xc0004c7f40, 0x4ea6c00, 0xc009b4e700, 0xc003508100)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/rancher/rancher/pkg/websocket.websocketHandler.ServeHTTP(0x4e32d20, 0xc0004c7f40, 0x4ea6c00, 0xc009b4e700, 0xc003508100)
	/go/src/github.com/rancher/rancher/pkg/websocket/handler.go:35 +0xa0
github.com/rancher/apiserver/pkg/middleware.ContentTypeOptions.func1(0x4ea6c00, 0xc009b4e700, 0xc003508100)
	/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20201023000256-1a0a904f9197/pkg/middleware/cache.go:47 +0x131
net/http.HandlerFunc.ServeHTTP(0xc0004c7f80, 0x4ea6c00, 0xc009b4e700, 0xc003508100)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/rancher/rancher/pkg/auth/audit.auditHandler.ServeHTTP(0x4e32d20, 0xc0004c7f80, 0x0, 0x4ea6c00, 0xc009b4e700, 0xc003508100)
	/go/src/github.com/rancher/rancher/pkg/auth/audit/filter.go:32 +0x522
github.com/rancher/steve/pkg/auth.ToMiddleware.func1.1(0x4ea6c00, 0xc009b4e700, 0xc0038aa600)
	/go/pkg/mod/github.com/rancher/steve@v0.0.0-20201110183734-21c7add15f64/pkg/auth/filter.go:156 +0x1bd
net/http.HandlerFunc.ServeHTTP(0xc005640060, 0x4ea6c00, 0xc009b4e700, 0xc0038aa600)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/rancher/dynamiclistener/server.wrapHandler.func1(0x4ea6c00, 0xc009b4e700, 0xc0038aa600)
	/go/pkg/mod/github.com/rancher/dynamiclistener@v0.2.1-0.20200910203214-85f32491cb09/server/server.go:187 +0x95
net/http.HandlerFunc.ServeHTTP(0xc003aebbf0, 0x4ea6c00, 0xc009b4e700, 0xc0038aa600)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/rancher/dynamiclistener.HTTPRedirect.func1(0x4ea6c00, 0xc009b4e700, 0xc0038aa600)
	/go/pkg/mod/github.com/rancher/dynamiclistener@v0.2.1-0.20200910203214-85f32491cb09/redirect.go:20 +0x20a
net/http.HandlerFunc.ServeHTTP(0xc003b3e640, 0x4ea6c00, 0xc009b4e700, 0xc0038aa600)
	/usr/local/go/src/net/http/server.go:2041 +0x44
net/http.serverHandler.ServeHTTP(0xc005a8e7e0, 0x4ea6c00, 0xc009b4e700, 0xc0038aa600)
	/usr/local/go/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc002e288c0, 0x4ebbbc0, 0xc0066e4480)
	/usr/local/go/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2962 +0x35c

2020/12/11 06:37:11 [DEBUG] Triggering auth refresh on user-kt8xj
2020/12/11 06:37:11 [DEBUG] Skipping refresh for user-kt8xj due to max-age
2020/12/11 06:37:11 [DEBUG] Triggering auth refresh on user-kt8xj
2020/12/11 06:37:11 [DEBUG] Skipping refresh for user-kt8xj due to max-age
2020/12/11 06:37:11 [DEBUG] Triggering auth refresh on user-kt8xj
2020/12/11 06:37:11 [DEBUG] Skipping refresh for user-kt8xj due to max-age
2020/12/11 06:37:12 [INFO] Handling backend connection request [c-t9v7g:m-x4jjp]
2020/12/11 06:37:12 [INFO] Handling backend connection request [c-t9v7g:m-lrpmv]
2020/12/11 06:37:12 [INFO] Handling backend connection request [c-t9v7g:m-kfkgk]
2020/12/11 06:37:12 [INFO] Handling backend connection request [c-t9v7g:m-9wxhs]
2020/12/11 06:37:12 [INFO] Handling backend connection request [c-t9v7g]
2020/12/11 06:37:14 [DEBUG] Cluster [c-t9v7g] has reconnected, resuming
I1211 06:37:15.916012      26 range_allocator.go:82] Sending events to api server.
I1211 06:37:15.916615      26 range_allocator.go:110] No Service CIDR provided. Skipping filtering out service addresses.
I1211 06:37:15.916877      26 range_allocator.go:116] No Secondary Service CIDR provided. Skipping filtering out secondary service addresses.
I1211 06:37:15.917181      26 controllermanager.go:533] Started "nodeipam"
I1211 06:37:15.917988      26 node_ipam_controller.go:162] Starting ipam controller
I1211 06:37:15.918435      26 shared_informer.go:223] Waiting for caches to sync for node
I1211 06:37:15.923209      26 pvc_protection_controller.go:101] Starting PVC protection controller
I1211 06:37:15.923252      26 shared_informer.go:223] Waiting for caches to sync for PVC protection
I1211 06:37:15.923285      26 controllermanager.go:533] Started "pvc-protection"
I1211 06:37:15.932646      26 shared_informer.go:223] Waiting for caches to sync for garbage collector
I1211 06:37:15.937290      26 shared_informer.go:223] Waiting for caches to sync for resource quota
W1211 06:37:15.972108      26 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="local-node" does not exist
I1211 06:37:16.049308      26 shared_informer.go:230] Caches are synced for node 
I1211 06:37:16.049357      26 range_allocator.go:172] Starting range CIDR allocator
I1211 06:37:16.049365      26 shared_informer.go:223] Waiting for caches to sync for cidrallocator
I1211 06:37:16.049371      26 shared_informer.go:230] Caches are synced for cidrallocator 
I1211 06:37:16.049472      26 shared_informer.go:230] Caches are synced for TTL 
I1211 06:37:16.050447      26 shared_informer.go:230] Caches are synced for endpoint 
I1211 06:37:16.051210      26 shared_informer.go:230] Caches are synced for endpoint_slice 
I1211 06:37:16.055107      26 shared_informer.go:230] Caches are synced for job 
I1211 06:37:16.060691      26 shared_informer.go:230] Caches are synced for GC 
I1211 06:37:16.061397      26 shared_informer.go:230] Caches are synced for daemon sets 
I1211 06:37:16.070637      26 shared_informer.go:230] Caches are synced for taint 
I1211 06:37:16.071541      26 node_lifecycle_controller.go:1433] Initializing eviction metric for zone: 
W1211 06:37:16.071710      26 node_lifecycle_controller.go:1048] Missing timestamp for Node local-node. Assuming now as a timestamp.
I1211 06:37:16.071767      26 node_lifecycle_controller.go:1249] Controller detected that zone  is now in state Normal.
I1211 06:37:16.072306      26 taint_manager.go:187] Starting NoExecuteTaintManager
I1211 06:37:16.073982      26 event.go:278] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"local-node", UID:"fd4f94b3-c85d-44e4-8934-8f059d4543c5", APIVersion:"v1", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RegisteredNode' Node local-node event: Registered Node local-node in Controller
I1211 06:37:16.077343      26 shared_informer.go:230] Caches are synced for ReplicaSet 
I1211 06:37:16.111197      26 shared_informer.go:230] Caches are synced for ReplicationController 
I1211 06:37:16.119038      26 shared_informer.go:230] Caches are synced for service account 
I1211 06:37:16.126287      26 shared_informer.go:230] Caches are synced for PVC protection 
I1211 06:37:16.131698      26 shared_informer.go:230] Caches are synced for stateful set 
I1211 06:37:16.148859      26 controller.go:606] quota admission added evaluator for: endpointslices.discovery.k8s.io
I1211 06:37:16.182512      26 shared_informer.go:230] Caches are synced for HPA 
I1211 06:37:16.185219      26 shared_informer.go:230] Caches are synced for namespace 
I1211 06:37:16.283926      26 shared_informer.go:230] Caches are synced for persistent volume 
I1211 06:37:16.303096      26 shared_informer.go:230] Caches are synced for PV protection 
I1211 06:37:16.310093      26 shared_informer.go:230] Caches are synced for expand 
I1211 06:37:16.387422      26 shared_informer.go:230] Caches are synced for ClusterRoleAggregator 
I1211 06:37:16.432860      26 shared_informer.go:230] Caches are synced for attach detach 
I1211 06:37:16.500068      26 shared_informer.go:230] Caches are synced for certificate-csrapproving 
I1211 06:37:16.543314      26 shared_informer.go:230] Caches are synced for disruption 
I1211 06:37:16.543414      26 disruption.go:339] Sending events to api server.
I1211 06:37:16.554767      26 shared_informer.go:230] Caches are synced for certificate-csrsigning 
I1211 06:37:16.623695      26 shared_informer.go:230] Caches are synced for deployment 
I1211 06:37:16.984445      26 request.go:621] Throttling request took 1.031365555s, request: GET:https://127.0.0.1:6444/apis/management.cattle.io/v3/catalogtemplates?limit=500&resourceVersion=0
2020/12/11 06:37:17 [DEBUG] Cluster [c-t9v7g] has reconnected, resuming
2020/12/11 06:37:18 [DEBUG] Triggering auth refresh on user-kt8xj
2020/12/11 06:37:18 [DEBUG] Skipping refresh for user-kt8xj due to max-age
2020/12/11 06:37:18 [DEBUG] Triggering auth refresh on user-kt8xj
2020/12/11 06:37:18 [DEBUG] Skipping refresh for user-kt8xj due to max-age
2020/12/11 06:37:18 [DEBUG] closing watcher for management.cattle.io.setting
2020/12/11 06:37:18 [DEBUG] closing watcher for namespace
2020/12/11 06:37:18 [DEBUG] closing watcher for management.cattle.io.nodetemplate
2020/12/11 06:37:18 [DEBUG] closing watcher for management.cattle.io.fleetworkspace
2020/12/11 06:37:18 [DEBUG] closing watcher for management.cattle.io.project
2020/12/11 06:37:18 [DEBUG] closing watcher for management.cattle.io.nodepool
2020/12/11 06:37:18 [DEBUG] closing watcher for management.cattle.io.cluster
2020/12/11 06:37:18 [DEBUG] Triggering auth refresh on user-kt8xj
2020/12/11 06:37:18 [DEBUG] Skipping refresh for user-kt8xj due to max-age
2020/12/11 06:37:18 [DEBUG] Triggering auth refresh on user-kt8xj
2020/12/11 06:37:18 [DEBUG] Skipping refresh for user-kt8xj due to max-age
2020/12/11 06:37:18 [DEBUG] Triggering auth refresh on user-kt8xj
2020/12/11 06:37:18 [DEBUG] Skipping refresh for user-kt8xj due to max-age
2020/12/11 06:37:18 [DEBUG] Triggering auth refresh on user-kt8xj
2020/12/11 06:37:18 [DEBUG] Skipping refresh for user-kt8xj due to max-age
2020/12/11 06:37:18 [DEBUG] Triggering auth refresh on user-kt8xj
2020/12/11 06:37:18 [DEBUG] Skipping refresh for user-kt8xj due to max-age
2020/12/11 06:37:18 [DEBUG] Triggering auth refresh on user-kt8xj
2020/12/11 06:37:18 [DEBUG] Skipping refresh for user-kt8xj due to max-age
2020/12/11 06:37:18 [DEBUG] Triggering auth refresh on user-kt8xj
2020/12/11 06:37:18 [DEBUG] Skipping refresh for user-kt8xj due to max-age
2020/12/11 06:37:18 [DEBUG] Triggering auth refresh on user-kt8xj
2020/12/11 06:37:18 [DEBUG] Skipping refresh for user-kt8xj due to max-age
2020/12/11 06:37:19 [DEBUG] Triggering auth refresh on user-kt8xj
2020/12/11 06:37:19 [DEBUG] Skipping refresh for user-kt8xj due to max-age
2020/12/11 06:37:19 [DEBUG] isActiveCluster: true isWindowsCluster: false user: user-kt8xj, canUpdateCluster: true
I1211 06:37:19.421945      26 trace.go:116] Trace[341763750]: "List" url:/apis/management.cattle.io/v3/settings,user-agent:rancher/v0.0.0 (linux/amd64) kubernetes/$Format,client:127.0.0.1 (started: 2020-12-11 06:37:18.916796306 +0000 UTC m=+45.967418765) (total time: 505.09725ms):
Trace[341763750]: [341.12384ms] [341.059999ms] Listing from storage done
Trace[341763750]: [505.09417ms] [163.97033ms] Writing http response done count:78
2020/12/11 06:37:19 [DEBUG] TokenStreamTransformer called
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x2adaee8]

goroutine 12322 [running]:
github.com/rancher/rancher/pkg/clustermanager.(*Manager).Filter(0xc00192b8c0, 0xc00621f320, 0xc001ff74a0, 0xc00ad70360, 0xc002207350, 0xc006d44301)
	/go/src/github.com/rancher/rancher/pkg/clustermanager/rbac.go:73 +0xd8
github.com/rancher/norman/store/proxy.(*Store).Watch.func1(0xc00ad70360, 0xc0092407a8)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200930000340-693d65aaffe3/store/proxy/proxy_store.go:275 +0xbd
github.com/rancher/norman/types/convert.Chan.func1(0xc006d44300, 0xc003cf9aa0, 0xc00ac58420)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200930000340-693d65aaffe3/types/convert/convert.go:21 +0x65
created by github.com/rancher/norman/types/convert.Chan
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200930000340-693d65aaffe3/types/convert/convert.go:19 +0x7f

```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.2 to 2.5-head - commit id: `baf4867cb`
- Installation option (single install/HA): Single nodes

**Comment by sowmyav27** [comment]
Maybe related to - https://github.com/rancher/rancher/issues/30220

**Comment by sowmyav27** [comment]
On an upgrade from 2.5.2 to 2.5.4-rc4, do not hit this issue.
no panics seen.
