### ISSUE TITLE
Panic seen intermittently while logging in with SAML

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#31081]
On HA setups when SAML is configured, at times login throws a 404 with this panic in the logs:
```
2021/01/21 21:00:38 [ERROR] Panic serving api request:
22/01/2021 10:00:38 am goroutine 485670 [running]:
22/01/2021 10:00:38 am runtime/debug.Stack(0xc002b1fdc0, 0x3c26060, 0x7390960)
22/01/2021 10:00:38 am 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
22/01/2021 10:00:38 am github.com/rancher/norman/api.(*Server).ServeHTTP.func1(0x4e78ba0, 0xc024211360)
22/01/2021 10:00:38 am 	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200930000340-693d65aaffe3/api/server.go:175 +0x7a
22/01/2021 10:00:38 am panic(0x3c26060, 0x7390960)
22/01/2021 10:00:38 am 	/usr/local/go/src/runtime/panic.go:969 +0x166
22/01/2021 10:00:38 am github.com/rancher/rancher/pkg/auth/providers/saml.PerformSamlLogin(0x44d8204, 0x4, 0xc0143dcfc0, 0x3c5dd00, 0xc023368680, 0x0, 0x0)
22/01/2021 10:00:38 am 	/go/src/github.com/rancher/rancher/pkg/auth/providers/saml/saml_provider.go:118 +0xc7
22/01/2021 10:00:38 am github.com/rancher/rancher/pkg/auth/providers/publicapi.(*loginHandler).createLoginToken(0xc00efb2780, 0xc0143dcfc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
22/01/2021 10:00:38 am 	/go/src/github.com/rancher/rancher/pkg/auth/providers/publicapi/login.go:172 +0x905
22/01/2021 10:00:38 am github.com/rancher/rancher/pkg/auth/providers/publicapi.(*loginHandler).login(0xc00efb2780, 0xc00678bb6a, 0x5, 0xc014471420, 0xc0143dcfc0, 0xc00482e5a0, 0xc0197ba4b0)
22/01/2021 10:00:38 am 	/go/src/github.com/rancher/rancher/pkg/auth/providers/publicapi/login.go:57 +0x152
22/01/2021 10:00:38 am github.com/rancher/norman/api.handleAction(0xc014471420, 0xc0143dcfc0, 0x0, 0x0)
22/01/2021 10:00:38 am 	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200930000340-693d65aaffe3/api/server.go:263 +0x62
```

gz#14541

**Comment by mrajashree** [comment]
Closing as a dup of https://github.com/rancher/rancher/issues/30710
