### ISSUE TITLE
Active Directory configuration page no longer accessible once set up

### ISSUE THREAD

**Issue by pppq** [rancher/rancher#3146]
(UI v0.78.0)

After enabling Active Directory authentication, clicking on Access Control in the Admin menu brings up the static `/fail` page. Chrome console output:

```
extend-ember-route.js:31 Set previous route to admin-tab.accounts.index []
extend-ember-route.js:31 Set previous route to admin-tab.accounts.index []
route.js:49 Application Error Error: There is no route named admin-tab.auth.ldap
    at Object.v.handlersFor (http://example.com:8080/assets/vendor-af98fd6665a863e6306d14cbb34e54ae.js:17:30526)
    at Object.e.default.i.subclass.applyToState (http://example.com:8080/assets/vendor-af98fd6665a863e6306d14cbb34e54ae.js:18:15057)
    at Object.l.applyIntent (http://example.com:8080/assets/vendor-af98fd6665a863e6306d14cbb34e54ae.js:18:13458)
    at S (http://example.com:8080/assets/vendor-af98fd6665a863e6306d14cbb34e54ae.js:11:18043)
    at c.default.extend._hydrateUnsuppliedQueryParams (http://example.com:8080/assets/vendor-af98fd6665a863e6306d14cbb34e54ae.js:11:25977)
    at c.default.extend._prepareQueryParams (http://example.com:8080/assets/vendor-af98fd6665a863e6306d14cbb34e54ae.js:11:25498)
    at c.default.extend._doTransition (http://example.com:8080/assets/vendor-af98fd6665a863e6306d14cbb34e54ae.js:11:25337)
    at c.default.extend.transitionTo (http://example.com:8080/assets/vendor-af98fd6665a863e6306d14cbb34e54ae.js:11:22358)
    at c.default.extend.replaceWith (http://example.com:8080/assets/vendor-af98fd6665a863e6306d14cbb34e54ae.js:11:22698)
    at m.default.extend.replaceWith (http://example.com:8080/assets/vendor-af98fd6665a863e6306d14cbb34e54ae.js:11:12607)
extend-ember-route.js:31 Set previous route to admin-tab.accounts.index []
```

Navigating to the page by appending `/admin/access/activedirectory` directly to the URL works.

If I disengage authentication settings with the red button, navigation works again as usual.

**Comment by pppq** [comment]
Active Directory configuration is called `ldapconfig` in [app/login/controller.js](https://github.com/rancher/ui/blob/dc3e9fa905475dea35c2df43079bff582f35a2e0/app/login/controller.js#L8), which [app/admin-tab/auth/index/route.js](https://github.com/rancher/ui/blob/c30662c7a4e771ab29d6083e98fe70e45455b921/app/admin-tab/auth/index/route.js#L9) uses after cutting off the `config` suffix of each configuration item. The tab is called `activedirectory` in [app/router.js](https://github.com/rancher/ui/blob/fb5e6ff666d8c12d9aaca42bf055ec8c2d53cb76/app/router.js#L32), however.

**Comment by tfiduccia** [comment]
version - master jan 07
Verified fixed

**Comment by kaos** [comment]
+1, this hit me too. Looking forward to next release. :)
