### ISSUE TITLE
Rancher server panics, when v1 monitoring and cis scans are enabled

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#31749]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

- monitoring version 0.2.1
- master-2dca0c67b48331c23c05c025208bacfc258d45bd-head
- Issue is not seen on v2.5-51253e556b6cc3d9b285b559c4ff043e2301d687-head only seen on master-head

1. Spin up rancher with master-head
2. Create a cluster with 3 worker, 1 etcd, 1 cp
3. Once the cluster is active enable monitoring
4. Enabling fails with 500 internal server error 
<img width="322" alt="Screen Shot 2021-03-18 at 7 44 26 AM" src="https://user-images.githubusercontent.com/38144301/111647369-a748c700-87bf-11eb-862d-c92b8d05fff5.png">

if we enable monitoring on a local cluster, same issue is seen.

**Result:**
```
Some logs from the rancher server
goroutine 246187 [running]:
runtime/debug.Stack(0xc006f2c5a8, 0x31fb6c0, 0x58f8090)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/rancher/norman/api.(*Server).ServeHTTP.func1(0x3ec2150, 0xc00751fbc0)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20210225010917-c7fd1e24145b/api/server.go:175 +0x85
panic(0x31fb6c0, 0x58f8090)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/rancher/rancher/pkg/api/norman/customization/cluster.ActionHandler.validateChartCompatibility(0x7f577303d670, 0xc001b63380, 0x3f16bc8, 0xc0041d91d0, 0x3eda6a0, 0xc0018d5c20, 0x7f577303d690, 0xc001b63380, 0x3f00488, 0xc002a61e10, ...)
	/go/src/github.com/rancher/rancher/pkg/api/norman/customization/cluster/actions_monitoring.go:159 +0xb5
github.com/rancher/rancher/pkg/api/norman/customization/cluster.ActionHandler.enableMonitoring(0x7f577303d670, 0xc001b63380, 0x3f16bc8, 0xc0041d91d0, 0x3eda6a0, 0xc0018d5c20, 0x7f577303d690, 0xc001b63380, 0x3f00488, 0xc002a61e10, ...)
	/go/src/github.com/rancher/rancher/pkg/api/norman/customization/cluster/actions_monitoring.go:111 +0x445
github.com/rancher/rancher/pkg/api/norman/customization/cluster.ActionHandler.ClusterActionHandler(0x7f577303d670, 0xc001b63380, 0x3f16bc8, 0xc0041d91d0, 0x3eda6a0, 0xc0018d5c20, 0x7f577303d690, 0xc001b63380, 0x3f00488, 0xc002a61e10, ...)
	/go/src/github.com/rancher/rancher/pkg/api/norman/customization/cluster/actionhandler.go:80 +0xbf8
github.com/rancher/norman/api.handleAction(0xc0033f3fc0, 0xc00db04c60, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20210225010917-c7fd1e24145b/api/server.go:263 +0x62
github.com/rancher/norman/api.(*Server).handle(0xc004252840, 0x3ec2150, 0xc00751fbc0, 0xc008169700, 0x40b7ec, 0x3559dc0, 0xc00751fbc0)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20210225010917-c7fd1e24145b/api/server.go:251 +0xde
github.com/rancher/norman/api.(*Server).ServeHTTP(0xc004252840, 0x3ec2150, 0xc00751fbc0, 0xc008169700)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20210225010917-c7fd1e24145b/api/server.go:180 +0x7d
github.com/rancher/apiserver/pkg/middleware.ContentType.func1(0x3eb31b0, 0xc007e919b0, 0xc008169700)
	/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20210209001659-a17289640582/pkg/middleware/content.go:33 +0x93
net/http.HandlerFunc.ServeHTTP(0xc004255a58, 0x3eb31b0, 0xc007e919b0, 0xc008169700)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/rancher/apiserver/pkg/middleware.Gzip.func1(0x3ec19a0, 0xc008866ee0, 0xc008169700)
	/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20210209001659-a17289640582/pkg/middleware/gzip.go:60 +0x1e3
net/http.HandlerFunc.ServeHTTP(0xc004255a70, 0x3ec19a0, 0xc008866ee0, 0xc008169700)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/rancher/rancher/pkg/auth/requests.authHeaderHandler.ServeHTTP(0x3e6be20, 0xc004255a70, 0x3ec19a0, 0xc008866ee0, 0xc008169700)
	/go/src/github.com/rancher/rancher/pkg/auth/requests/filter.go:49 +0x577
github.com/rancher/rancher/pkg/rbac.NewAccessControlHandler.func1.1(0x3ec19a0, 0xc008866ee0, 0xc008169600)
	/go/src/github.com/rancher/rancher/pkg/rbac/user_based.go:33 +0x1c7
net/http.HandlerFunc.ServeHTTP(0xc008379968, 0x3ec19a0, 0xc008866ee0, 0xc008169600)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/rancher/steve/pkg/auth.ToMiddleware.func1.1(0x3ec19a0, 0xc008866ee0, 0xc008169500)
	/go/pkg/mod/github.com/rancher/steve@v0.0.0-20210302143000-362617a677a9/pkg/auth/filter.go:167 +0x1c7
net/http.HandlerFunc.ServeHTTP(0xc007e91890, 0x3ec19a0, 0xc008866ee0, 0xc008169500)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00114da40, 0x3ec19a0, 0xc008866ee0, 0xc008169300)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00114d8c0, 0x3ec19a0, 0xc008866ee0, 0xc008168f00)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rancher/rancher/pkg/multiclustermanager.(*DeferredServer).Middleware.func1(0x3ec19a0, 0xc008866ee0, 0xc008168f00)
	/go/src/github.com/rancher/rancher/pkg/multiclustermanager/deferred.go:100 +0x9d
net/http.HandlerFunc.ServeHTTP(0xc00060ce20, 0x3ec19a0, 0xc008866ee0, 0xc008168f00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00114d200, 0x3ec19a0, 0xc008866ee0, 0xc008168c00)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rancher/rancher/pkg/api/steve/proxy.NewProxyMiddleware.func1.1(0x3ec19a0, 0xc008866ee0, 0xc008168c00)
	/go/src/github.com/rancher/rancher/pkg/api/steve/proxy/proxy.go:75 +0x65
net/http.HandlerFunc.ServeHTTP(0xc00060ce40, 0x3ec19a0, 0xc008866ee0, 0xc008168c00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/rancher/rancher/pkg/api/steve/proxy.RewriteLocalCluster.func1(0x3ec19a0, 0xc008866ee0, 0xc008168c00)
	/go/src/github.com/rancher/rancher/pkg/api/steve/proxy/proxy.go:43 +0xf2
net/http.HandlerFunc.ServeHTTP(0xc00155b1b8, 0x3ec19a0, 0xc008866ee0, 0xc008168c00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/rancher/rancher/pkg/websocket.websocketHandler.ServeHTTP(0x3e6be20, 0xc00155b1b8, 0x3ec19a0, 0xc008866ee0, 0xc008168c00)
	/go/src/github.com/rancher/rancher/pkg/websocket/handler.go:35 +0xa2
github.com/rancher/apiserver/pkg/middleware.ContentTypeOptions.func1(0x3ec19a0, 0xc008866ee0, 0xc008168c00)
	/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20210209001659-a17289640582/pkg/middleware/cache.go:47 +0x131
net/http.HandlerFunc.ServeHTTP(0xc00155b1d0, 0x3ec19a0, 0xc008866ee0, 0xc008168c00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/rancher/rancher/pkg/auth/audit.auditHandler.ServeHTTP(0x3e6be20, 0xc00155b1d0, 0x0, 0x3ec19a0, 0xc008866ee0, 0xc008168c00)
	/go/src/github.com/rancher/rancher/pkg/auth/audit/filter.go:32 +0x52e
github.com/rancher/steve/pkg/auth.ToMiddleware.func1.1(0x3ec19a0, 0xc008866ee0, 0xc001c7bd00)
	/go/pkg/mod/github.com/rancher/steve@v0.0.0-20210302143000-362617a677a9/pkg/auth/filter.go:167 +0x1c7
net/http.HandlerFunc.ServeHTTP(0xc003a7de00, 0x3ec19a0, 0xc008866ee0, 0xc001c7bd00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/rancher/dynamiclistener/server.wrapHandler.func1(0x3ec19a0, 0xc008866ee0, 0xc001c7bd00)
	/go/pkg/mod/github.com/rancher/dynamiclistener@v0.2.1-0.20200910203214-85f32491cb09/server/server.go:187 +0x95
net/http.HandlerFunc.ServeHTTP(0xc002be8870, 0x3ec19a0, 0xc008866ee0, 0xc001c7bd00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/rancher/dynamiclistener.HTTPRedirect.func1(0x3ec19a0, 0xc008866ee0, 0xc001c7bd00)
	/go/pkg/mod/github.com/rancher/dynamiclistener@v0.2.1-0.20200910203214-85f32491cb09/redirect.go:20 +0xa4
net/http.HandlerFunc.ServeHTTP(0xc001f07530, 0x3ec19a0, 0xc008866ee0, 0xc001c7bd00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
net/http.serverHandler.ServeHTTP(0xc0038c28c0, 0x3ec19a0, 0xc008866ee0, 0xc001c7bd00)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc002de77c0, 0x3ece280, 0xc001478780)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x39b
```

**Noticed a few things:**

- If istio v1 is enabled, monitoring is enabled automatically, but if we disable istio and thereby disbaling monitoring and we try to enable monitoring again, it is causing a panic in the rancher server.
- Running CIS scans is causing a panic in the rancher server.
- Enabling logging is working

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
master-2dca0c67b48331c23c05c025208bacfc258d45bd-head
- Installation option (single install/HA):
Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud,  12 Cores , 46.2 GiB
- Kubernetes version (use `kubectl version`):

```
{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
20.10.3 
```

**Comment by SheilaghM** [comment]
Can someone besides Darren fix this?
Is it resolved by  https://github.com/rancher/rancher/issues/29247

**Comment by Jono-SUSE-Rancher** [comment]
@anupama2501 - Can you just re-test this with the PR that Darren submitted back in March? Thanks!

**Comment by anupama2501** [comment]
Verified on master-ebad1dfd8457e352709d9789018b94cb6b44b191-head 
Installation - Single

1. Spin up rancher on master-head ebad1
2. Create a cluster with 1 etcd, 1 cp, 3 worker
3. Enable monitoring and no panics are seen in the rancher server and it was successful.
4. Verified also by enabling cis scans and no error seen.
