### ISSUE TITLE
[bug] Rancher backup panics when it encounters an invalid tarball

### ISSUE THREAD

**Issue by dbason** [rancher/rancher#31801]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
Deploy Rancher v2.5.x on a standalone server with docker.
Take a docker backup and upload it to s3
Try to restore the backup file to a kubernetes cluster using Rancher Backups

**Result:**
Rancher backup panics

**Expected Result:**
Rancher backup emits an error message, and gracefully fails the restore 

**Other details that may be helpful:**
Log output of panic
```
goroutine 403 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1691bc0, 0xc0005a10c0)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.0/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.0/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1691bc0, 0xc0005a10c0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/backup-restore-operator/pkg/controllers/restore.getGVR(0xc0000aa000, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/backup-restore-operator/pkg/controllers/restore/controller.go:677 +0x2d4
github.com/rancher/backup-restore-operator/pkg/controllers/restore.(*handler).loadDataFromFile(0xc0000892c0, 0xc0003a3180, 0xc000248a00, 0x13d, 0x200, 0xc0003b8630, 0xc000291380, 0x0, 0xc0004ac120)
        /go/src/github.com/rancher/backup-restore-operator/pkg/controllers/restore/download.go:109 +0x17d
github.com/rancher/backup-restore-operator/pkg/controllers/restore.(*handler).LoadFromTarGzip(0xc0000892c0, 0xc0004ac120, 0x2f, 0xc0003b8630, 0xc000291380, 0x0, 0x0)
        /go/src/github.com/rancher/backup-restore-operator/pkg/controllers/restore/download.go:85 +0x52d
github.com/rancher/backup-restore-operator/pkg/controllers/restore.(*handler).OnRestoreChange(0xc0000892c0, 0xc000629ba0, 0x11, 0xc0002b4680, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/backup-restore-operator/pkg/controllers/restore/controller.go:195 +0x13c9
github.com/rancher/backup-restore-operator/pkg/generated/controllers/resources.cattle.io/v1.FromRestoreHandlerToHandler.func1(0xc000629ba0, 0x11, 0x19a1e40, 0xc0002b4680, 0xc0003eff20, 0xc0003a2460, 0xc00eb24382e3c11a, 0xc0003efbb8)
        /go/src/github.com/rancher/backup-restore-operator/pkg/generated/controllers/resources.cattle.io/v1/restore.go:105 +0x65
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc0003d95c0, 0xc000629ba0, 0x11, 0x19a1e40, 0xc0002b4680, 0xc0003d0cd0, 0x408c9b, 0x183da98, 0xc000133680)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200515155337-a34e1e26ad91/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*sharedHandler).OnChange(0xc00043aed0, 0xc000629ba0, 0x11, 0x19a1e40, 0xc0002b4680, 0x42d201, 0x0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200515155337-a34e1e26ad91/pkg/controller/sharedhandler.go:65 +0x150
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc0002caa50, 0xc000629ba0, 0x11, 0xc000296780, 0xc0003efd30)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200515155337-a34e1e26ad91/pkg/controller/controller.go:211 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0002caa50, 0x1535c00, 0xc000352980, 0x0, 0x0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200515155337-a34e1e26ad91/pkg/controller/controller.go:193 +0xf0
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0002caa50, 0x40be01)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200515155337-a34e1e26ad91/pkg/controller/controller.go:170 +0x51
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc0002caa50)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200515155337-a34e1e26ad91/pkg/controller/controller.go:159 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0003d9ac0)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.0/pkg/util/wait/wait.go:155 +0x5e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0003d9ac0, 0x19990c0, 0xc0002968d0, 0xc0000d0201, 0xc00032d080)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.0/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0003d9ac0, 0x3b9aca00, 0x0, 0xc0003e9801, 0xc00032d080)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.0/pkg/util/wait/wait.go:133 +0xe2
k8s.io/apimachinery/pkg/util/wait.Until(0xc0003d9ac0, 0x3b9aca00, 0xc00032d080)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.0/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200515155337-a34e1e26ad91/pkg/controller/controller.go:130 +0x35e
panic: runtime error: index out of range [1] with length 1 [recovered]
        panic: runtime error: index out of range [1] with length 1

goroutine 403 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.0/pkg/util/runtime/runtime.go:55 +0x105
panic(0x1691bc0, 0xc0005a10c0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/backup-restore-operator/pkg/controllers/restore.getGVR(0xc0000aa000, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/backup-restore-operator/pkg/controllers/restore/controller.go:677 +0x2d4
github.com/rancher/backup-restore-operator/pkg/controllers/restore.(*handler).loadDataFromFile(0xc0000892c0, 0xc0003a3180, 0xc000248a00, 0x13d, 0x200, 0xc0003b8630, 0xc000291380, 0x0, 0xc0004ac120)
        /go/src/github.com/rancher/backup-restore-operator/pkg/controllers/restore/download.go:109 +0x17d
github.com/rancher/backup-restore-operator/pkg/controllers/restore.(*handler).LoadFromTarGzip(0xc0000892c0, 0xc0004ac120, 0x2f, 0xc0003b8630, 0xc000291380, 0x0, 0x0)
        /go/src/github.com/rancher/backup-restore-operator/pkg/controllers/restore/download.go:85 +0x52d
github.com/rancher/backup-restore-operator/pkg/controllers/restore.(*handler).OnRestoreChange(0xc0000892c0, 0xc000629ba0, 0x11, 0xc0002b4680, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/backup-restore-operator/pkg/controllers/restore/controller.go:195 +0x13c9
github.com/rancher/backup-restore-operator/pkg/generated/controllers/resources.cattle.io/v1.FromRestoreHandlerToHandler.func1(0xc000629ba0, 0x11, 0x19a1e40, 0xc0002b4680, 0xc0003eff20, 0xc0003a2460, 0xc00eb24382e3c11a, 0xc0003efbb8)
        /go/src/github.com/rancher/backup-restore-operator/pkg/generated/controllers/resources.cattle.io/v1/restore.go:105 +0x65
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc0003d95c0, 0xc000629ba0, 0x11, 0x19a1e40, 0xc0002b4680, 0xc0003d0cd0, 0x408c9b, 0x183da98, 0xc000133680)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200515155337-a34e1e26ad91/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*sharedHandler).OnChange(0xc00043aed0, 0xc000629ba0, 0x11, 0x19a1e40, 0xc0002b4680, 0x42d201, 0x0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200515155337-a34e1e26ad91/pkg/controller/sharedhandler.go:65 +0x150
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc0002caa50, 0xc000629ba0, 0x11, 0xc000296780, 0xc0003efd30)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200515155337-a34e1e26ad91/pkg/controller/controller.go:211 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0002caa50, 0x1535c00, 0xc000352980, 0x0, 0x0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200515155337-a34e1e26ad91/pkg/controller/controller.go:193 +0xf0
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0002caa50, 0x40be01)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200515155337-a34e1e26ad91/pkg/controller/controller.go:170 +0x51
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc0002caa50)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200515155337-a34e1e26ad91/pkg/controller/controller.go:159 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0003d9ac0)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.0/pkg/util/wait/wait.go:155 +0x5e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0003d9ac0, 0x19990c0, 0xc0002968d0, 0xc0000d0201, 0xc00032d080)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.0/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0003d9ac0, 0x3b9aca00, 0x0, 0xc0003e9801, 0xc00032d080)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.0/pkg/util/wait/wait.go:133 +0xe2
k8s.io/apimachinery/pkg/util/wait.Until(0xc0003d9ac0, 0x3b9aca00, 0xc00032d080)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.0/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200515155337-a34e1e26ad91/pkg/controller/controller.go:130 +0x35e
```

**Comment by dmitrijrub** [comment]
@dbason  Did you managed to solve this?

**Comment by dbason** [comment]
Switching to use a valid Rancher Backup tarball should solve the problem, this issue was raised to improve the error handling.

**Comment by dmitrijrub** [comment]
im trying to migrate rancher from single node docker 2.5.7 to k3s 2.6.3 and i get panic as soon as tar ball is downloaded 
INFO[2022/02/21 11:40:14] Successfully downloaded [backup/backup-02-08.tar.gz]
E0221 11:40:26.969629       1 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)

**Comment by dmitrijrub** [comment]
@dbason im following guide https://rancher.com/docs/rancher/v2.5/en/backups/docker-installs/docker-backups/

**Comment by dbason** [comment]
Yeah that was the mistake I made as well.  You can't use a docker backup, you need to install the rancher backups app to create a rancher backup.  You need to create a regular rancher backup following https://rancher.com/docs/rancher/v2.6/en/backups/back-up-rancher/

**Comment by dmitrijrub** [comment]
Thanks a lot! saved my day

**Comment by 631068264** [comment]
Saved me  and  How to re manage the downstream cluster ?  Get error  “Cluster agent is not connected”  and I edit  CATTLE_SERVER in **cattle-cluster-agent**  deploy  but the agent still connect older rancher server
