### ISSUE TITLE
Panic in rancher causing it to restart

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31989]
**What kind of request is this (question/bug/enhancement/feature request):**

**Steps to reproduce (least amount of steps as possible):**

- Deploy rancher server
- deploy a cloud credential/cluster
- Rancher is seen restarting
- Rancher logs:

```
2021/04/08 02:55:42 [INFO] Watching metadata for rke.cattle.io/v1, Kind=RKECluster
2021/04/08 02:55:42 [INFO] Watching metadata for rancher.cattle.io/v1, Kind=Project
2021/04/08 02:55:42 [INFO] Watching metadata for rke.cattle.io/v1, Kind=RKEBootstrapTemplate
E0408 02:55:44.552087      23 customresource_handler.go:668] error building openapi models for machinehealthchecks.cluster.x-k8s.io: ERROR $root.definitions.io.x-k8s.cluster.v1alpha3.MachineHealthCheck.properties.spec.properties.maxUnhealthy has invalid property: anyOf
ERROR $root.definitions.io.x-k8s.cluster.v1alpha4.MachineHealthCheck.properties.spec.properties.maxUnhealthy has invalid property: anyOf
I0408 02:55:44.613675      23 event.go:291] "Event occurred" object="rancher-operator-system/rancher-operator" kind="Deployment" apiVersion="apps/v1" type="Normal" reason="ScalingReplicaSet" message="Scaled up replica set rancher-operator-5d9c5f4dd9 to 1"
W0408 02:55:45.003246      23 controller.go:142] slow openapi aggregation of "roletemplates.rancher.cattle.io": 3.155904357s
I0408 02:55:46.581020      23 event.go:291] "Event occurred" object="rancher-operator-system/rancher-operator-5d9c5f4dd9" kind="ReplicaSet" apiVersion="apps/v1" type="Normal" reason="SuccessfulCreate" message="Created pod: rancher-operator-5d9c5f4dd9-8ppdf"
I0408 02:55:46.913368      23 topology_manager.go:235] [topologymanager] Topology Admit Handler
I0408 02:55:47.010931      23 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "rancher-operator-token-wprx6" (UniqueName: "kubernetes.io/secret/b55162bd-894e-43c1-97c2-39744548e6b2-rancher-operator-token-wprx6") pod "rancher-operator-5d9c5f4dd9-8ppdf" (UID: "b55162bd-894e-43c1-97c2-39744548e6b2") 
E0408 02:55:47.076181      23 reflector.go:127] object-"rancher-operator-system"/"rancher-operator-token-wprx6": Failed to watch *v1.Secret: failed to list *v1.Secret: secrets "rancher-operator-token-wprx6" is forbidden: User "system:node:local-node" cannot list resource "secrets" in API group "" in the namespace "rancher-operator-system": no relationship found between node 'local-node' and this object
W0408 02:55:47.415769      23 controller.go:142] slow openapi aggregation of "machinehealthchecks.cluster.x-k8s.io": 2.412323346s
E0408 02:55:48.132608      23 secret.go:195] Couldn't get secret rancher-operator-system/rancher-operator-token-wprx6: failed to sync secret cache: timed out waiting for the condition
E0408 02:55:48.133931      23 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/secret/b55162bd-894e-43c1-97c2-39744548e6b2-rancher-operator-token-wprx6 podName:b55162bd-894e-43c1-97c2-39744548e6b2 nodeName:}" failed. No retries permitted until 2021-04-08 02:55:48.632841278 +0000 UTC m=+199.579650094 (durationBeforeRetry 500ms). Error: "MountVolume.SetUp failed for volume \"rancher-operator-token-wprx6\" (UniqueName: \"kubernetes.io/secret/b55162bd-894e-43c1-97c2-39744548e6b2-rancher-operator-token-wprx6\") pod \"rancher-operator-5d9c5f4dd9-8ppdf\" (UID: \"b55162bd-894e-43c1-97c2-39744548e6b2\") : failed to sync secret cache: timed out waiting for the condition"
W0408 02:55:48.647881      23 controller.go:142] slow openapi aggregation of "rkebootstraptemplates.rke.cattle.io": 1.231927179s
I0408 02:55:51.481991      23 trace.go:205] Trace[114704720]: "Get" url:/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-scheduler,user-agent:k3s/v1.19.8+k3s1 (linux/amd64) kubernetes/95fc76b/leader-election,client:127.0.0.1 (08-Apr-2021 02:55:50.907) (total time: 572ms):
Trace[114704720]: ---"About to write a response" 572ms (02:55:00.479)
Trace[114704720]: [572.426511ms] [572.426511ms] END
I0408 02:55:56.765957      23 trace.go:205] Trace[28970979]: "Get" url:/apis/apps/v1/namespaces/rancher-operator-system/deployments/rancher-operator,user-agent:helm/v0.0.0 (linux/amd64) kubernetes/$Format,client:127.0.0.1 (08-Apr-2021 02:55:52.895) (total time: 3870ms):
Trace[28970979]: ---"About to write a response" 3868ms (02:55:00.764)
Trace[28970979]: [3.870161971s] [3.870161971s] END
I0408 02:55:56.766615      23 trace.go:205] Trace[1639025169]: "Get" url:/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-scheduler,user-agent:k3s/v1.19.8+k3s1 (linux/amd64) kubernetes/95fc76b/leader-election,client:127.0.0.1 (08-Apr-2021 02:55:52.895) (total time: 3871ms):
Trace[1639025169]: ---"About to write a response" 3871ms (02:55:00.766)
Trace[1639025169]: [3.871238335s] [3.871238335s] END
E0408 02:56:00.926216      23 leaderelection.go:361] Failed to update lock: resource name may not be empty
I0408 02:56:00.926410      23 leaderelection.go:278] failed to renew lease kube-system/kube-scheduler: timed out waiting for the condition
F0408 02:56:00.927818      23 server.go:199] leaderelection lost
goroutine 1963 [running]:
github.com/rancher/k3s/vendor/k8s.io/klog/v2.stacks(0xc000010001, 0xc02936a000, 0x41, 0xb5)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:996 +0xb9
github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).output(0x6ef5aa0, 0xc000000003, 0x0, 0x0, 0xc0069d8c40, 0x6b88c11, 0x9, 0xc7, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:945 +0x191
github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).printf(0x6ef5aa0, 0x3, 0x0, 0x0, 0x4514b1d, 0x13, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:733 +0x17a
github.com/rancher/k3s/vendor/k8s.io/klog/v2.Fatalf(...)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1456
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-scheduler/app.Run.func1()
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:199 +0x73
github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run.func1(0xc007762b40)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:200 +0x29
github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0xc007762b40, 0x4c77280, 0xc0129e3a80)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:210 +0x15d
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-scheduler/app.Run(0x4c77280, 0xc008926400, 0xc014bf4cb0, 0xc009b797a0, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:207 +0x55c
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-scheduler/app.runCommand(0xc00a336b00, 0xc00a31ad00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:140 +0x27a
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-scheduler/app.NewSchedulerCommand.func1(0xc00a336b00, 0xc0079a4960, 0x0, 0x6)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:81 +0x53
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).execute(0xc00a336b00, 0xc009f09580, 0x6, 0x8, 0xc00a336b00, 0xc009f09580)
	/go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:846 +0x2c2
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00a336b00, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:950 +0x375
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:887
github.com/rancher/k3s/pkg/daemons/executor.Embedded.Scheduler.func1(0xc009ec29c0, 0xc00a336b00)
	/go/src/github.com/rancher/k3s/pkg/daemons/executor/embed.go:67 +0x46
created by github.com/rancher/k3s/pkg/daemons/executor.Embedded.Scheduler
	/go/src/github.com/rancher/k3s/pkg/daemons/executor/embed.go:65 +0x90

goroutine 1 [chan receive, 2 minutes]:
github.com/rancher/k3s/pkg/agent.run(0x4c77280, 0xc0010195c0, 0xc00c339960, 0x6a, 0x0, 0x0, 0x0, 0x0, 0xc00a3b8c60, 0x16, ...)
	/go/src/github.com/rancher/k3s/pkg/agent/run.go:119 +0x2b0
github.com/rancher/k3s/pkg/agent.Run(0x4c77280, 0xc0010195c0, 0xc00c339960, 0x6a, 0x0, 0x0, 0x0, 0x0, 0xc00a3b8c60, 0x16, ...)
	/go/src/github.com/rancher/k3s/pkg/agent/run.go:170 +0x438
github.com/rancher/k3s/pkg/cli/server.run(0xc001040000, 0x6ef6a40, 0xc001438ea8, 0x48)
	/go/src/github.com/rancher/k3s/pkg/cli/server/server.go:283 +0x1778
github.com/rancher/k3s/pkg/cli/server.Run(0xc001040000, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/pkg/cli/server/server.go:38 +0x65
github.com/rancher/k3s/vendor/github.com/urfave/cli.HandleAction(0x3dad8e0, 0x46e5c40, 0xc001040000, 0xc001040000, 0x0)
	/go/src/github.com/rancher/k3s/vendor/github.com/urfave/cli/app.go:523 +0xfd
github.com/rancher/k3s/vendor/github.com/urfave/cli.Command.Run(0x44e7613, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x451be24, 0x15, 0xc000fce300, ...)
	/go/src/github.com/rancher/k3s/vendor/github.com/urfave/cli/command.go:174 +0x58e
github.com/rancher/k3s/vendor/github.com/urfave/cli.(*App).Run(0xc000d6f880, 0xc000070f00, 0x8, 0x8, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/github.com/urfave/cli/app.go:276 +0x7d4
main.main()
	/go/src/github.com/rancher/k3s/cmd/server/main.go:47 +0x61a

goroutine 6 [chan receive]:
github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x6ef5aa0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1131 +0x8b
created by github.com/rancher/k3s/vendor/k8s.io/klog/v2.init.0
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:416 +0xd8

goroutine 7 [chan receive]:
github.com/rancher/k3s/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x6ef58e0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:1010 +0x8b
created by github.com/rancher/k3s/vendor/k8s.io/klog.init.0
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:411 +0xd8

goroutine 165 [chan receive]:
github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc0003bf7a0)
	/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:173 +0x3b3
created by github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/logutil.NewMergeLogger
	/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:91 +0x85

goroutine 125 [chan receive]:
github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc000754ce0)
	/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:173 +0x3b3
created by github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/logutil.NewMergeLogger
	/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:91 +0x85

goroutine 75 [sleep]:
time.Sleep(0x3b9aca00)
	/usr/local/go/src/runtime/time.go:188 +0xbf
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/scheduler/framework/runtime.(*metricsRecorder).run(0xc00063faa0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/scheduler/framework/runtime/metrics_recorder.go:88 +0x3f
created by github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/scheduler/framework/runtime.newMetricsRecorder
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/scheduler/framework/runtime/metrics_recorder.go:60 +0x108

```
**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `f5393c29`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):  rke DO/RKE custom
- Kubernetes version (use `kubectl version`):

```
1.20.5 (Any)
```

**Comment by Jono-SUSE-Rancher** [comment]
@sowmyav27 - Does this happen on every cluster type of only the RKE Digital Ocean/RKE Custom? And does this happen every single time?

**Comment by sowmyav27** [comment]
It happened very consistently. However, i do not think it is related to deploying just "RKE Digital Ocean/RKE Custom".

**Comment by sirredbeard** [comment]
Is this still happening in current master builds?

Can this be reproduced on other clouds or on-prem?

**Comment by deniseschannon** [comment]
@sowmyav27 What's in this issue is that CPU or disk usage was very high and it was causing it to not be able to function. Can we re-test?

**Comment by sowmyav27** [comment]
**on master-head commit id: `70ba0d59`**

this issue is not seen, will reopen or log a new one if we notice it again.
