### ISSUE TITLE
Syslog over UDP doesn't work with Logging v2

### ISSUE THREAD

**Issue by ryanelliottsmith** [rancher/rancher#32144]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
From Cluster Explorer > Logging:
* Set up a ClusterOutput with a syslog over udp endpoint
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: testoutput
  namespace: cattle-logging-system
spec:
  syslog:
    buffer:
      flush_interval: "10"
    format:
      type: json
    host: seq.seq.svc.cluster.local
    insecure: true
    port: 514
    transport: udp
```

* Set up a ClusterFlow with a catch-all rule:
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: testflow
  namespace: cattle-logging-system
spec:
  globalOutputRefs:
  - testoutput
  match:
  - select: {}
```
* Use `tcpdump -u` on the host to monitor traffic between fluentd and the syslog endpoint
**Result:**
No traffic is seen leaving the fluentd pod

**Other details that may be helpful:**
Once the protocol is changed from udp to tcp, fluentd starts sending traffic to syslog.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.7
- Installation option (single install/HA): HA

gz#15819

**Comment by kreuzert** [comment]
Hey,

we have the same issue with rancher-logging.

- Rancher Version: 2.5.7
- Chart Version (in Rancher WebUI Apps & Marketplace -> Logging ): 3.9.000 . 
- Fluentd Images tested: rancher/mirrored-banzaicloud-fluentd:v1.11.5-alpine-9, v1.11.5-alpine-12  , banzaicloud/fluentd:v1.11.5-alpine-13, v1.11.4-alpine-6.

Logs of fluentd process in fluentd container in rancher-logging-fluentd-0.cattle-logging-system  ( exec -- cat /fluentd/log/out ): 

```
2021-04-29 14:48:10 +0000 [warn]: #0 [flow:namespace:defghi:output:namespace:abcdef] failed to flush the buffer. retry_time=0 next_retry_seconds=2021-04-29 14:48:11.481888884 +0000 chunk="5c11d93fa325
ebf8f8d2fdc8098a0893" error_class=Errno::EDESTADDRREQ error="Destination address required"
  2021-04-29 14:48:10 +0000 [warn]: #0 /usr/lib/ruby/2.7.0/socket.rb:456:in `__write_nonblock'                                                                                                                                      2021-04-29 14:48:10 +0000 [warn]: #0 /usr/lib/ruby/2.7.0/socket.rb:456:in `write_nonblock'                                                                                                                                      
  2021-04-29 14:48:10 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-syslog_rfc5424-0.9.0.rc.7/lib/fluent/plugin/out_syslog_rfc5424.rb:35:in `block in write'
  2021-04-29 14:48:10 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.5/lib/fluent/event.rb:325:in `each'                                                                                                               2021-04-29 14:48:10 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.5/lib/fluent/event.rb:325:in `block in each'
  2021-04-29 14:48:10 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.5/lib/fluent/plugin/buffer/file_chunk.rb:171:in `open'
  2021-04-29 14:48:10 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.5/lib/fluent/event.rb:324:in `each'                                                                                                               2021-04-29 14:48:10 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-syslog_rfc5424-0.9.0.rc.7/lib/fluent/plugin/out_syslog_rfc5424.rb:33:in `write'
  2021-04-29 14:48:10 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.5/lib/fluent/plugin/output.rb:1136:in `try_flush'
  2021-04-29 14:48:10 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.5/lib/fluent/plugin/output.rb:1442:in `flush_thread_run'                       
  2021-04-29 14:48:10 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.5/lib/fluent/plugin/output.rb:462:in `block (2 levels) in start'
  2021-04-29 14:48:10 +0000 [warn]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.5/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2021-04-29 14:48:11 +0000 [warn]: #0 [flow:namespace:defghi:output:namespace:abcdef] failed to flush the buffer. retry_time=1 next_retry_seconds=2021-04-29 14:48:12 85886648001327940993/21990232555520
0000000 +0000 chunk="5c11d93fa325ebf8f8d2fdc8098a0893" error_class=Errno::EDESTADDRREQ error="Destination address required"
  2021-04-29 14:48:11 +0000 [warn]: #0 suppressed same stacktrace
```

**Comment by Martin-Weiss** [comment]
Is there any chance to get the UDP functionality fixed in rancher-logging??

**Comment by stefanlasiewski** [comment]
We're seeing the same problem in Rancher v2.5.11

**Comment by stefanlasiewski** [comment]
As a workaround, try a different image in the Helm chart. (Credit goes to Sheilagh at https://github.com/rancher/rancher/issues/35197#issue-1030778932 )

Switch from this:

```
    image:
      repository: rancher/mirrored-banzaicloud-fluentd
      tag: v1.13.3-alpine-XX
```

To the latest compatible version shown at https://github.com/orgs/banzaicloud/packages/container/package/fluentd . For compatibility, if you're using v1.13.x Rancher image, stick with the v1.13.x image provided by Banzaicloud.

```
images:
  fluentd:
    repository: ghcr.io/banzaicloud/fluentd
    tag: v1.13.3-alpine-14
```

**Comment by stefanlasiewski** [comment]
This seems to be fixed in `rancher-logging:3.15.0` which was released recently. That includes the following image:

```
        fluentd:
          repository: rancher/mirrored-banzaicloud-fluentd
          tag: v1.13.3-alpine-11
```

**Comment by superseb** [comment]
@stefanlasiewski  Thanks for testing!

@ryanelliottsmith Can you confirm this works as expected in latest released version?

**Comment by ronhorton** [comment]
**Pass** verified in `2.6-head Commit ID 8cc8121`
1. provisioned a syslog server
2. created a cluster output with server ip and port 514 / UDP
3. created a deployment on cluster 
4. tailed syslog on syslog server

`Logs flowed via UDP`
