### ISSUE TITLE
Panic seen in rancher server

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#32485]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy single node rancher server, tried to deploy a custom cluster in cluster explorer.
- Panic seen in rancher

```
E0430 16:51:32.940017      25 kubelet_volumes.go:154] orphaned pod "40ef6ec0-f9d2-414e-bae9-39aa52e198c1" found, but volume paths are still present on disk : There were a total of 1 errors similar to this. Turn up verbosity to see them.
E0430 16:51:32.962756      25 writers.go:105] apiserver was unable to write a JSON response: write tcp 172.17.0.2:6443->10.42.0.129:39062: write: broken pipe
E0430 16:51:32.962846      25 status.go:71] apiserver received an error that is not an metav1.Status: &tls.permamentError{err:(*net.OpError)(0xc008ae4050)}
E0430 16:51:32.974074      25 runtime.go:76] Observed a panic: runtime error: invalid memory address or nil pointer dereference
goroutine 1550481 [running]:
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1.1(0xc02ffad800)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:108 +0x113
panic(0x3ee8000, 0x6c388a0)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
compress/gzip.(*Writer).Write(0xc009e6f1e0, 0xc030525760, 0xa2, 0xa2, 0x30, 0x40f46c0, 0xc02b68dc01)
	/usr/local/go/src/compress/gzip/gzip.go:168 +0x229
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.(*deferredResponseWriter).Write(0xc007493c70, 0xc030525760, 0xa2, 0xa2, 0xc030525760, 0xa2, 0xa2)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:182 +0x563
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x4506bef, 0x10, 0x7f082f8333c0, 0xc00d043c20, 0x4c4f800, 0xc02dc25870, 0xc02b58bb00, 0xc8, 0x4c26640, 0xc02c844e00)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:117 +0x37e
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated(0x4c57d00, 0xc001117140, 0x4c4f780, 0xc00386a820, 0x0, 0x0, 0x44e1009, 0x2, 0x4c4f800, 0xc02dc25870, ...)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:251 +0x5cd
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/handlers.transformResponseObject(0x4c77340, 0xc030dbf170, 0xc00386a820, 0xc02b68e898, 0xc02b58bb00, 0x4c4f800, 0xc02dc25870, 0xc8, 0x0, 0x0, ...)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/handlers/response.go:137 +0x373
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/handlers.ListResource.func1(0x4c4f800, 0xc02dc25870, 0xc02b58bb00)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/handlers/get.go:284 +0x10fb
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints.restfulListResource.func1(0xc030dbf0b0, 0xc02c844d90)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/installer.go:1157 +0x91
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc030dbf0b0, 0xc02c844d90)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:384 +0x282
github.com/rancher/k3s/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc0010f1830, 0x7f082f196748, 0xc02dc25858, 0xc02b58bb00)
	/go/src/github.com/rancher/k3s/vendor/github.com/emicklei/go-restful/container.go:288 +0xa84
github.com/rancher/k3s/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(...)
	/go/src/github.com/rancher/k3s/vendor/github.com/emicklei/go-restful/container.go:199
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x44ffbc5, 0xe, 0xc0010f1830, 0xc00135ecb0, 0x7f082f196748, 0xc02dc25858, 0xc02b58bb00)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/handler.go:146 +0x539
github.com/rancher/k3s/vendor/k8s.io/kube-aggregator/pkg/apiserver.(*proxyHandler).ServeHTTP(0xc0085b6910, 0x7f082f196748, 0xc02dc25858, 0xc02b58bb00)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go:121 +0x183
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc02daba500, 0x7f082f196748, 0xc02dc25858, 0xc02b58bb00)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:248 +0x3db
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc0005de690, 0x7f082f196748, 0xc02dc25858, 0xc02b58bb00)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x8c
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x4503a32, 0xf, 0xc0028e8090, 0xc0005de690, 0x7f082f196748, 0xc02dc25858, 0xc02b58bb00)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/handler.go:154 +0x74d
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7f082f196748, 0xc02dc25858, 0xc02b58bb00)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:64 +0x563
net/http.HandlerFunc.ServeHTTP(0xc00290ba00, 0x7f082f196748, 0xc02dc25858, 0xc02b58bb00)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7f082f196748, 0xc02dc25858, 0xc02b58bb00)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:184 +0x4cf
net/http.HandlerFunc.ServeHTTP(0xc006875260, 0x7f082f196748, 0xc02dc25858, 0xc02b58bb00)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7f082f196748, 0xc02dc25858, 0xc02b58bb00)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:50 +0x231d
net/http.HandlerFunc.ServeHTTP(0xc00290ba40, 0x7f082f196748, 0xc02dc25858, 0xc02b58bb00)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7f082f196748, 0xc02dc25858, 0xc02b58b900)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:70 +0x672
net/http.HandlerFunc.ServeHTTP(0xc006c799a0, 0x7f082f196748, 0xc02dc25858, 0xc02b58b900)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc02ffad800, 0xc00375a200, 0x4c78c80, 0xc02dc25858, 0xc02b58b900)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:113 +0xb8
created by github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:99 +0x1cc

goroutine 1550483 [running]:
github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3d6dd80, 0xc022aafc50)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa6
github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc00139f590, 0x1, 0x1)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x3d6dd80, 0xc022aafc50)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc00375a200, 0x4c4f9c0, 0xc02c844d20, 0xc02b58b900)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:119 +0x448
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x4c4f9c0, 0xc02c844d20, 0xc02b58b800)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:59 +0x137
net/http.HandlerFunc.ServeHTTP(0xc006875290, 0x4c4f9c0, 0xc02c844d20, 0xc02b58b800)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x4c4f9c0, 0xc02c844d20, 0xc02b58b700)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x269
net/http.HandlerFunc.ServeHTTP(0xc0068752c0, 0x4c4f9c0, 0xc02c844d20, 0xc02b58b700)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithWarningRecorder.func1(0x4c4f9c0, 0xc02c844d20, 0xc02b58b600)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters/warning.go:35 +0x1a7
net/http.HandlerFunc.ServeHTTP(0xc00375a220, 0x4c4f9c0, 0xc02c844d20, 0xc02b58b600)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithCacheControl.func1(0x4c4f9c0, 0xc02c844d20, 0xc02b58b600)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters/cachecontrol.go:31 +0xa8
net/http.HandlerFunc.ServeHTTP(0xc00375a240, 0x4c4f9c0, 0xc02c844d20, 0xc02b58b600)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/httplog.WithLogging.func1(0x4c55b00, 0xc0230e7a40, 0xc02b58b500)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:91 +0x2f2
net/http.HandlerFunc.ServeHTTP(0xc00375a260, 0x4c55b00, 0xc0230e7a40, 0xc02b58b500)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x4c55b00, 0xc0230e7a40, 0xc02b58b500)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:51 +0xe6
net/http.HandlerFunc.ServeHTTP(0xc00375a280, 0x4c55b00, 0xc0230e7a40, 0xc02b58b500)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc0068752f0, 0x4c55b00, 0xc0230e7a40, 0xc02b58b500)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
github.com/rancher/k3s/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00760cb40, 0x4c55b00, 0xc0230e7a40, 0xc02b58b300)
	/go/src/github.com/rancher/k3s/vendor/github.com/gorilla/mux/mux.go:210 +0xd3
github.com/rancher/k3s/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00760cc00, 0x4c55b00, 0xc0230e7a40, 0xc02b58b100)
	/go/src/github.com/rancher/k3s/vendor/github.com/gorilla/mux/mux.go:210 +0xd3
github.com/rancher/k3s/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00760ccc0, 0x4c55b00, 0xc0230e7a40, 0xc02b58af00)
	/go/src/github.com/rancher/k3s/vendor/github.com/gorilla/mux/mux.go:210 +0xd3
github.com/rancher/k3s/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00760ce40, 0x4c55b00, 0xc0230e7a40, 0xc02b37bb00)
	/go/src/github.com/rancher/k3s/vendor/github.com/gorilla/mux/mux.go:210 +0xd3
github.com/rancher/k3s/pkg/cluster.(*Cluster).router.func1(0x4c55b00, 0xc0230e7a40, 0xc02b37bb00)
	/go/src/github.com/rancher/k3s/pkg/cluster/router.go:27 +0x64
net/http.HandlerFunc.ServeHTTP(0xc0008849d0, 0x4c55b00, 0xc0230e7a40, 0xc02b37bb00)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/rancher/k3s/pkg/cluster.(*Cluster).getHandler.func1(0x4c55b00, 0xc0230e7a40, 0xc02b37bb00)
	/go/src/github.com/rancher/k3s/pkg/cluster/router.go:14 +0x95
net/http.HandlerFunc.ServeHTTP(0xc000898120, 0x4c55b00, 0xc0230e7a40, 0xc02b37bb00)
	/usr/local/go/src/net/http/server.go:2042 +0x44
net/http.serverHandler.ServeHTTP(0xc0003d2e00, 0x4c55b00, 0xc0230e7a40, 0xc02b37bb00)
	/usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc02a08f7c0, 0x4c77280, 0xc043d94fc0)
	/usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2969 +0x36c
time="2021-04-30T16:51:32.974433147Z" level=info msg="Cluster-Http-Server 2021/04/30 16:51:32 http: superfluous response.WriteHeader call from github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1 (wrap.go:38)"

```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `7e5ad7fa`
- Installation option (single install/HA): single

**Comment by Jono-SUSE-Rancher** [comment]
@cmurphy  Can you just try to reproduce this and see if it's still an issue on master-head?

**Comment by cmurphy** [comment]
I'm not able to reproduce this exactly, but neither is it working for me. @sowmyav27 does this panic appear before or after the registration command is run? Did you choose a cloud provider or leave it as none? Is it appearing on rancher server or on the agent? Were you using RKE2, RKE or k3s? 1.21 or 1.20? From the log output it looks like this might have come from a k3s agent
`github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1.1(0xc02ffad800)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:108 +0x113`

The log output you posted looks similar to a bug reported [in prometheus](https://github.com/kubernetes-sigs/prometheus-adapter/issues/292) which should be [fixed in kubernetes 1.20](https://github.com/kubernetes/kubernetes/pull/94589).

I'm seeing different problem on the agent where it fails to connect to the server due to a certificate issue:

```
Jul 02 16:24:16 ubuntu rancher-system-agent[2218]: time="2021-07-02T16:24:16Z" level=info msg="Starting remote watch of plans"
Jul 02 16:24:16 ubuntu rancher-system-agent[2218]: panic: error while connecting to Kubernetes cluster
Jul 02 16:24:16 ubuntu rancher-system-agent[2218]: goroutine 6 [running]:
Jul 02 16:24:16 ubuntu rancher-system-agent[2218]: github.com/rancher/system-agent/pkg/k8splan.(*watcher).start(0xc00010a180, 0x1755160, 0xc000450dc0)
Jul 02 16:24:16 ubuntu rancher-system-agent[2218]:         /go/src/github.com/rancher/system-agent/pkg/k8splan/watcher.go:60 +0x7e5
Jul 02 16:24:16 ubuntu rancher-system-agent[2218]: created by github.com/rancher/system-agent/pkg/k8splan.Watch
Jul 02 16:24:16 ubuntu rancher-system-agent[2218]:         /go/src/github.com/rancher/system-agent/pkg/k8splan/watcher.go:39 +0xbe
Jul 02 16:24:16 ubuntu systemd[1]: rancher-system-agent.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 02 16:24:16 ubuntu systemd[1]: rancher-system-agent.service: Failed with result 'exit-code'.
```

**Comment by sowmyav27** [comment]
@cmurphy I am not able to reproduce now on master-head commit id: `1a218f5` using rke1/rke2 custom clusters.. I can reopen this or log a new one if I see this issue

**Comment by snasovich** [comment]
@sowmyav27 , let's close this issue since it's not reproducible any longer. If you see it (or similar) issue pop-up again, please open a new bug with details on how to reproduce it.

**Comment by sowmyav27** [comment]
Closing this.
