### ISSUE TITLE
Single (Docker) Install: Unable to save cluster settings, HTTP 500 ([ERROR] Panic serving api request)

### ISSUE THREAD

**Issue by Napsty** [rancher/rancher#32618]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):** In Rancher UI "Edit" a cluster and at the bottom of the page simply click on Save.

**Result:** An error with weird characters is showing in the UI. 

![image](https://user-images.githubusercontent.com/3702203/117420272-b295b480-af1d-11eb-92fe-e2f0e15bb144.png)

Browser console shows a HTTP 500 Internal Server error on the PUT request on `/v3/clusters/c-xxxxx?_replace=true`

![image](https://user-images.githubusercontent.com/3702203/117420436-e375e980-af1d-11eb-9d2a-6ceb957478b0.png)

Rancher container shows the following error in the logs:

```
2021/05/07 07:20:43 [ERROR] Panic serving api request: 
goroutine 2697421 [running]:
runtime/debug.Stack(0xc00d742910, 0x3749920, 0x6db4920)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP.func1(0x47cd820, 0xc00a4eeeb0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:175 +0x7a
panic(0x3749920, 0x6db4920)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/rancher/pkg/api/customization/cluster.(*Validator).validateScheduledClusterScan(0xc000b70780, 0xc002ae0300, 0xc000ba7b80, 0x0)
	/go/src/github.com/rancher/rancher/pkg/api/customization/cluster/validator.go:85 +0x8f
github.com/rancher/rancher/pkg/api/customization/cluster.(*Validator).Validator(0xc000b70780, 0xc0025e85a0, 0xc00d6e7a40, 0xc005f1f410, 0x0, 0xc005f1f410)
	/go/src/github.com/rancher/rancher/pkg/api/customization/cluster/validator.go:62 +0x3c6
github.com/rancher/rancher/vendor/github.com/rancher/norman/parse/builder.(*Builder).Construct(0xc005f1f3e0, 0xc00d6e7a40, 0xc00c182810, 0x3f466db, 0x6, 0x3f423f7, 0x3f423f7, 0x3)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/parse/builder/builder.go:58 +0xe2
github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler.ParseAndValidateBody(0xc0025e85a0, 0x0, 0x0, 0xc00d742d30, 0x2606d48)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler/validate.go:36 +0x233
github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler.UpdateHandler(0xc0025e85a0, 0x40d6c10, 0x0, 0xc00d6e7a40)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/handler/update.go:11 +0x34
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).handle(0xc0007922c0, 0x47cd820, 0xc00a4eeeb0, 0xc00850f200, 0xc00d742e38, 0x1807f1ab, 0xa42cc7d224b88e50)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:249 +0x2a2
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP(0xc0007922c0, 0x47cd820, 0xc00a4eeeb0, 0xc00850f200)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:180 +0x99
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentTypeOptions.func1(0x47cd820, 0xc00a4eeeb0, 0xc00850f200)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/cache.go:47 +0x131
net/http.HandlerFunc.ServeHTTP(0xc00a6e4300, 0x47cd820, 0xc00a4eeeb0, 0xc00850f200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0017180c0, 0x47cd820, 0xc00a4eeeb0, 0xc00850ef00)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/pkg/auth/requests.authHeaderHandler.ServeHTTP(0x47932a0, 0xc0012e34a0, 0x4754de0, 0xc0017180c0, 0x4793260, 0xc001699170, 0x47cd820, 0xc00a4eeeb0, 0xc00850ef00)
	/go/src/github.com/rancher/rancher/pkg/auth/requests/filter.go:62 +0x4eb
github.com/rancher/rancher/pkg/rbac.NewAccessControlHandler.func1(0x47cd820, 0xc00a4eeeb0, 0xc00850ee00, 0x4753da0, 0xc001722f30)
	/go/src/github.com/rancher/rancher/pkg/rbac/user_based.go:32 +0x194
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/auth.Middleware.Wrap.func1(0x47cd820, 0xc00a4eeeb0, 0xc00850ee00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/auth/filter.go:36 +0x55
net/http.HandlerFunc.ServeHTTP(0xc0012e3660, 0x47cd820, 0xc00a4eeeb0, 0xc00850ee00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/pkg/websocket.websocketHandler.ServeHTTP(0x475c0a0, 0xc0012e3660, 0x47cd820, 0xc00a4eeeb0, 0xc00850ee00)
	/go/src/github.com/rancher/rancher/pkg/websocket/handler.go:35 +0xa0
github.com/rancher/rancher/pkg/audit.auditHandler.ServeHTTP(0x4753fe0, 0xc00036c980, 0x0, 0x47cd820, 0xc00a4eeeb0, 0xc00850ee00)
	/go/src/github.com/rancher/rancher/pkg/audit/filter.go:31 +0x623
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentType.func1(0x47bb660, 0xc00c182390, 0xc00850ee00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/content.go:33 +0x93
net/http.HandlerFunc.ServeHTTP(0xc00172e7a0, 0x47bb660, 0xc00c182390, 0xc00850ee00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.Gzip.func1(0x47cc6a0, 0xc0016b81c0, 0xc00850ee00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/gzip.go:60 +0x1f5
net/http.HandlerFunc.ServeHTTP(0xc00172e7c0, 0x47cc6a0, 0xc0016b81c0, 0xc00850ee00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter.ContentTypeOptions.func1(0x47cc6a0, 0xc0016b81c0, 0xc00850ee00)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/responsewriter/cache.go:47 +0x131
net/http.HandlerFunc.ServeHTTP(0xc00a6e4240, 0x47cc6a0, 0xc0016b81c0, 0xc00850ee00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc001718000, 0x47cc6a0, 0xc0016b81c0, 0xc00850eb00)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00286e840, 0x47cc6a0, 0xc0016b81c0, 0xc00850e900)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00286e900, 0x47cc6a0, 0xc0016b81c0, 0xc00850e600)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/dashboard.Route.func2(0x47cc6a0, 0xc0016b81c0, 0xc00850e600)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/steve/pkg/dashboard/ui.go:56 +0xe5
net/http.HandlerFunc.ServeHTTP(0xc002a4c3d0, 0x47cc6a0, 0xc0016b81c0, 0xc00850e600)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0017186c0, 0x47cc6a0, 0xc0016b81c0, 0xc00850e300)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/server.wrapHandler.func1(0x47cc6a0, 0xc0016b81c0, 0xc00850e300)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/server/server.go:187 +0x95
net/http.HandlerFunc.ServeHTTP(0xc00600d500, 0x47cc6a0, 0xc0016b81c0, 0xc00850e300)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener.HTTPRedirect.func1(0x47cc6a0, 0xc0016b81c0, 0xc00850e300)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/dynamiclistener/redirect.go:20 +0x221
net/http.HandlerFunc.ServeHTTP(0xc00601d080, 0x47cc6a0, 0xc0016b81c0, 0xc00850e300)
	/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.serverHandler.ServeHTTP(0xc0070467e0, 0x47cc6a0, 0xc0016b81c0, 0xc00850e300)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc00a170aa0, 0x47ef4a0, 0xc00c100700)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e
```

**Other details that may be helpful:** A restart of the rancher container did not help.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 8vCPU, 8GB Memory
- Kubernetes version (use `kubectl version`): 1.17 (v1.17.4-rancher1-3)

```
$ kubectl version --insecure-skip-tls-verify=true
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Comment by superseb** [comment]
This could be a regression of https://github.com/rancher/rancher/issues/26616 but we need to know if you are using RKE template and what the cluster config is (YAML) so it can be used to reproduce.
