### ISSUE TITLE
Unable to provision custom RKE2 cluster from Cluster Explorer before accessing Ember UI and setting server_url

### ISSUE THREAD

**Issue by thehejik** [rancher/rancher#32672]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
* Deploy rancher:master-head `6030ab5` on RKE cluster (imported cluster) by helm:
```helm upgrade --install=true rancher rancher-latest/rancher -n cattle-system --version=2.5.8 --set hostname=rancher.mydomain --set replicas=1 --set rancherImageTag=master-head --set rancherImagePullPolicy=Always```
* Access the rancher server by https://rancher.domain - enter default credentials and you will land in Cluster Explorer
* Use `Cluster Management` in Cluster Explorer UI
* Create a Custom RKE2 cluster
* Select the new cluster on Clusters page and open Registration tab
* Copy `Registration Command` to clipboard by clicking on the field
* Paste the `Registration Command` with all 3 roles set into terminal on a node and execute

**Result:**
After a while check status/logs of rancher-system-agent.service systemd service which is failed:
```
# journalctl -u rancher-system-agent.service --no-pager
-- Logs begin at Tue 2021-05-11 13:40:11 UTC, end at Tue 2021-05-11 13:49:26 UTC. --
May 11 13:48:18 dhcp153 systemd[1]: Started Rancher System Agent.
May 11 13:48:18 dhcp153 rancher-system-agent[1989]: time="2021-05-11T13:48:18Z" level=info msg="Rancher System Agent version v0.0.1-alpha18 (be47abc) is starting"
May 11 13:48:18 dhcp153 rancher-system-agent[1989]: time="2021-05-11T13:48:18Z" level=info msg="Using directory /var/lib/rancher/agent/work for work"
May 11 13:48:18 dhcp153 rancher-system-agent[1989]: time="2021-05-11T13:48:18Z" level=debug msg="Instantiated new image utility with imagesDir: /var/lib/rancher/agent/images, imageCredentialProviderConfig: /var/lib/rancher/credentialprovider/config.yaml, imageCredentialProviderBinDir: /var/lib/rancher/credentialprovider/bin, agentRegistriesFile: /etc/rancher/agent/registries.yaml"
May 11 13:48:18 dhcp153 rancher-system-agent[1989]: time="2021-05-11T13:48:18Z" level=info msg="Starting remote watch of plans"
May 11 13:48:18 dhcp153 rancher-system-agent[1989]: time="2021-05-11T13:48:18Z" level=info msg="Starting local watch of plans in /var/lib/rancher/agent/plans"
May 11 13:48:18 dhcp153 rancher-system-agent[1989]: panic: invalid configuration: no server found for cluster "agent"
May 11 13:48:18 dhcp153 rancher-system-agent[1989]: goroutine 21 [running]:
May 11 13:48:18 dhcp153 rancher-system-agent[1989]: github.com/rancher/system-agent/pkg/remoteplan.(*watcher).start(0xc0004fe2a0, 0x174bf00, 0xc0004b8dc0)
May 11 13:48:18 dhcp153 rancher-system-agent[1989]:         /go/src/github.com/rancher/system-agent/pkg/remoteplan/watcher.go:44 +0x765
May 11 13:48:18 dhcp153 rancher-system-agent[1989]: created by github.com/rancher/system-agent/pkg/remoteplan.Watch
May 11 13:48:18 dhcp153 rancher-system-agent[1989]:         /go/src/github.com/rancher/system-agent/pkg/remoteplan/watcher.go:31 +0xbe
May 11 13:48:18 dhcp153 systemd[1]: rancher-system-agent.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 11 13:48:18 dhcp153 systemd[1]: rancher-system-agent.service: Unit entered failed state.
May 11 13:48:18 dhcp153 systemd[1]: rancher-system-agent.service: Failed with result 'exit-code'.
```

Problem is that `server` argument is not parsed correctly in `/var/lib/rancher/agent/rancher2_connection_info.json` file where the value is just empty string server: \"\"\n

Once you enter Cluster Manager / Ember UI and set `server_url` variable within the rancher wizard and execute the `Registration Command` once again (same machine, no cleanup needed) the service will start successfully.

**Other details that may be helpful:**
- probably related to missing `server_url` setup in Cluster Explorer

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:master-head `6030ab5`
- Installation option (single install/HA): any

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom RKE2 
- Machine type (cloud/VM/metal) and specifications (CPU/memory): any
- Kubernetes version (use `kubectl version`): `v1.21.0-alpha2+rke2r1`

**Comment by sowmyav27** [comment]
https://github.com/rancher/dashboard/issues/2800
