### ISSUE TITLE
Restore of rancher/rancher:v2.5.7 docker/docker-compose install with /var/lib/rancher

### ISSUE THREAD

**Issue by arthurlogilab** [rancher/rancher#32791]
**What kind of request is this (question/bug/enhancement/feature request):**

Question

**Steps to reproduce (least amount of steps as possible):**

Following a hardware failure, we are trying to restore our rancher which was hosted in a debian VM running in docker, started by docker-compose. We have a backup of `/var/lib/rancher` which is mounted as a volume and this is what we get : 

```
rancher_1  | 2021/05/19 08:56:00 [INFO] Listening on /tmp/log.sock
rancher_1  | 2021/05/19 08:56:00 [INFO] Rancher version v2.5.7 (c824d91cd) is starting
rancher_1  | 2021/05/19 08:56:00 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:true AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Agent:false Features:}
rancher_1  | 2021/05/19 08:56:00 [INFO] Running etcd --data-dir=management-state/etcd --heartbeat-interval=500 --election-timeout=5000
rancher_1  | 2021-05-19 08:56:01.352204 W | pkg/flags: unrecognized environment variable ETCD_URL_arm64=https://github.com/etcd-io/etcd/releases/download/v3.4.3/etcd-v3.4.3-linux-arm64.tar.gz
rancher_1  | 2021-05-19 08:56:01.352338 W | pkg/flags: unrecognized environment variable ETCD_URL_amd64=https://github.com/etcd-io/etcd/releases/download/v3.4.3/etcd-v3.4.3-linux-amd64.tar.gz
rancher_1  | 2021-05-19 08:56:01.352368 W | pkg/flags: unrecognized environment variable ETCD_UNSUPPORTED_ARCH=amd64
rancher_1  | 2021-05-19 08:56:01.352451 W | pkg/flags: unrecognized environment variable ETCD_URL=ETCD_URL_amd64
rancher_1  | [WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
rancher_1  | 2021-05-19 08:56:01.352587 I | etcdmain: etcd Version: 3.4.3
rancher_1  | 2021-05-19 08:56:01.352628 I | etcdmain: Git SHA: 3cf2f69b5
rancher_1  | 2021-05-19 08:56:01.352653 I | etcdmain: Go Version: go1.12.12
rancher_1  | 2021-05-19 08:56:01.352695 I | etcdmain: Go OS/Arch: linux/amd64
rancher_1  | 2021-05-19 08:56:01.352744 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
rancher_1  | 2021-05-19 08:56:01.352898 N | etcdmain: the server is already initialized as member before, starting as etcd member...
rancher_1  | [WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
rancher_1  | 2021-05-19 08:56:01.362668 I | embed: name = default
rancher_1  | 2021-05-19 08:56:01.362721 I | embed: data dir = management-state/etcd
rancher_1  | 2021-05-19 08:56:01.362750 I | embed: member dir = management-state/etcd/member
rancher_1  | 2021-05-19 08:56:01.362776 I | embed: heartbeat = 500ms
rancher_1  | 2021-05-19 08:56:01.362800 I | embed: election = 5000ms
rancher_1  | 2021-05-19 08:56:01.362853 I | embed: snapshot count = 100000
rancher_1  | 2021-05-19 08:56:01.362930 I | embed: advertise client URLs = http://localhost:2379
rancher_1  | 2021-05-19 08:56:01.362970 I | embed: initial advertise peer URLs = http://localhost:2380
rancher_1  | 2021-05-19 08:56:01.363007 I | embed: initial cluster = 
rancher_1  | 2021-05-19 08:56:02.758668 I | etcdserver: recovered store from snapshot at index 164101648
rancher_1  | 2021-05-19 08:56:02.768881 C | etcdserver: recovering backend from snapshot error: failed to find database snapshot file (snap: snapshot file doesn't exist)
rancher_1  | panic: recovering backend from snapshot error: failed to find database snapshot file (snap: snapshot file doesn't exist)
rancher_1  | 	panic: runtime error: invalid memory address or nil pointer dereference
rancher_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xc2cc4e]
rancher_1  | 
rancher_1  | goroutine 1 [running]:
rancher_1  | go.etcd.io/etcd/etcdserver.NewServer.func1(0xc0002fcf50, 0xc0002faf48)
rancher_1  | 	/tmp/etcd-release-3.4.3/etcd/release/etcd/etcdserver/server.go:335 +0x3e
rancher_1  | panic(0xed6960, 0xc00011c070)
rancher_1  | 	/usr/local/go/src/runtime/panic.go:522 +0x1b5
rancher_1  | github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc00000de20, 0x10aeaf5, 0x2a, 0xc0002fb018, 0x1, 0x1)
rancher_1  | 	/home/ec2-user/go/pkg/mod/github.com/coreos/pkg@v0.0.0-20160727233714-3ac0863d7acf/capnslog/pkg_logger.go:75 +0x135
rancher_1  | go.etcd.io/etcd/etcdserver.NewServer(0x1085123, 0x7, 0x0, 0x0, 0x0, 0x0, 0xc000294a00, 0x1, 0x1, 0xc000294880, ...)
rancher_1  | 	/tmp/etcd-release-3.4.3/etcd/release/etcd/etcdserver/server.go:456 +0x42f7
rancher_1  | go.etcd.io/etcd/embed.StartEtcd(0xc00029a000, 0xc00029a580, 0x0, 0x0)
rancher_1  | 	/tmp/etcd-release-3.4.3/etcd/release/etcd/embed/etcd.go:211 +0x9d0
rancher_1  | go.etcd.io/etcd/etcdmain.startEtcd(0xc00029a000, 0x108423e, 0x6, 0x1, 0xc00021d1d0)
rancher_1  | 	/tmp/etcd-release-3.4.3/etcd/release/etcd/etcdmain/etcd.go:302 +0x40
rancher_1  | go.etcd.io/etcd/etcdmain.startEtcdOrProxyV2()
rancher_1  | 	/tmp/etcd-release-3.4.3/etcd/release/etcd/etcdmain/etcd.go:144 +0x2f71
rancher_1  | go.etcd.io/etcd/etcdmain.Main()
rancher_1  | 	/tmp/etcd-release-3.4.3/etcd/release/etcd/etcdmain/main.go:46 +0x38
rancher_1  | main.main()
rancher_1  | 	/tmp/etcd-release-3.4.3/etcd/release/etcd/main.go:28 +0x20
rancher_1  | 2021/05/19 08:56:02 [FATAL] etcd exited
rancher_rancher_1 exited with code 1


```

We are primarily interested in restoring local users that were created in rancher and some association with objects created using rancher (monitoring deployments for example). 

**Result:**

rancher doesn't start

**Other details that may be helpful:**

We've tried to remove the `wal` files in `/var/lib/rancher/management-state/etcd/member/wal/` or `/var/lib/rancher/etcd/member/wal/` (it's ok to loose a few objects at this point) but it seems that doing so make rancher believe that this is a new install, so it seems to (re)create all objects and in the web interface we are asked to setup an admin account, so it feels it's doing a reset there. 

Thanks for any tips or leads ! 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.7
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 

```
(paste the output here)
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:45 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by arthurlogilab** [comment]
Related issues (which don't have any solution or workaround) : https://github.com/etcd-io/etcd/issues/11949 https://github.com/kubernetes/kubernetes/issues/88574
