### ISSUE TITLE
[Backport] KEv2 operators should get the same ca-additional as the Rancher deployment

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#32903]
https://github.com/rancher/rancher/issues/31846

**Comment by thedadams** [comment]
As discussed offline, this issue only covers deploying of the hosted clusters. Any issues that may occur outside of provisioning and updating the config are outside the scope of this issue.

**Comment by prabalsharma** [comment]
Looks like fixes did not make into 2.5-head.

v2.5-07131035f51f3e264c114e9d9dde65aae37bdf4f-head:

<img width="1349" alt="Screen Shot 2021-08-06 at 1 33 20 PM" src="https://user-images.githubusercontent.com/3749546/128568097-7172beea-093e-46a5-ae6f-1102b64ea93c.png">

**Comment by izaac** [comment]
Rancher version: `v2.6-head (09/14/2021)` _ad21cff_
Behind Squid Proxy with CA self sgined certs.

```
- Create the cattle-system namespace
- Create the cert-manager namespace if needed and install cert-manager
  - kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.0.4/cert-manager.crds.yaml 
  - helm repo add jetstack https://charts.jetstack.io && helm repo update
  - helm upgrade --install cert-manager jetstack/cert-manager  --namespace cert-manager --version v1.0.4  --set http_proxy=http://<PROXY_HOST>:3128 --set https_proxy=http://<PROXY_HOST>:3128 --set no_proxy=127.0.0.0/8\\,10.0.0.0/8\\,cattle-system.svc\\,172.16.0.0/12\\,192.168.0.0/16\\,.svc\\,.cluster.local
- Add the squid cert to the tls-ca-additional secret
  - cp squid-ca-cert-key.pem  ca-additional.pem
  - kubectl -n cattle-system create secret generic tls-ca-additional --from-file=ca-additional.pem=./ca-additional.pem
- Install Rancher
  - helm install rancher rancher-latest/rancher --version 2.5.9 --namespace cattle-system --set hostname=<RANCHER_HOST> --set rancherImageTag=v2.5-head --set proxy="http://<PROXY_HOST>:3128" --set noProxy="127.0.0.0/8\,10.0.0.0/8\,172.16.0.0/12\,192.168.0.0/16\,10.43.0.1/16\,172.31.0.0/16\,.svc\,.cluster.local\,.cattle-system.svc" --set additionalTrustedCAs=true
```

Rancher comes up active and I see traffic going through the Proxy's `access.log`

## EKS Provisioning 

Worked.

## AKS Provisioning
 Resources were created in Azure but the cluster didn't go into Active state in Rancher.

Errors
Rancher logs
```
2021/09/15 00:25:09 [INFO] [azurekubernetesservice] Request submitted, waiting for cluster [c-lgcz2] to finish creating
2021/09/15 00:25:09 [INFO] [azurekubernetesservice] Cluster [c-lgcz2] has not yet completed provisioning, waiting another 30 seconds
2021/09/15 00:27:10 [INFO] [azurekubernetesservice] service account token generation failed, retries left: 4
```

UI Cluster Error

`Post "https://c-2fqh-izakst-14a619-master-8cfffd4f.hcp.centralus.azmk8s.io:443/api/v1/namespaces": x509: certificate signed by unknown authority`


## GKE Provisioning

Resources were created in Google Cloud, but once the cluster was about to get active a Panic was seen in the Rancher logs:

```
goroutine 1460 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/runtime/runtime.go:55 +0x109
panic(0x32307e0, 0x59755e0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/rancher/rancher/pkg/controllers/management/gke.(*gkeOperatorController).onClusterChange(0xc00387a370, 0xc0005932a4, 0x7, 0xc002a5a000, 0x3770180, 0x38373a0, 0x7f41bf378220)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/gke/gke_cluster_handler.go:198 +0xe98
github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3.FromClusterHandlerToHandler.func1(0xc0005932a4, 0x7, 0x3ee9a98, 0xc002a5a000, 0xc002a5a000, 0x7f41bf378220, 0xc002a5a000, 0x1)
	/go/src/github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3/cluster.go:105 +0x6b
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc003abafb0, 0xc0005932a4, 0x7, 0x3ee9a98, 0xc002a5a000, 0x0, 0xc002a5a000, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210408231703-9ddd9378d08d/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc0013e1110, 0xc0005932a4, 0x7, 0x3ee9a98, 0xc002a5a000, 0xc001afe201, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210408231703-9ddd9378d08d/pkg/controller/sharedhandler.go:66 +0x123
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc0009228f0, 0xc0005932a4, 0x7, 0xc001afe3e8, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210408231703-9ddd9378d08d/pkg/controller/controller.go:210 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0009228f0, 0x3083c20, 0xc003abb850, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210408231703-9ddd9378d08d/pkg/controller/controller.go:192 +0xe7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0009228f0, 0x203000)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210408231703-9ddd9378d08d/pkg/controller/controller.go:169 +0x54
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210408231703-9ddd9378d08d/pkg/controller/controller.go:158
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0004c58b0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0004c58b0, 0x3ec98a0, 0xc0013924e0, 0x1, 0xc000054480)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0004c58b0, 0x3b9aca00, 0x0, 0x1, 0xc000054480)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc0004c58b0, 0x3b9aca00, 0xc000054480)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210408231703-9ddd9378d08d/pkg/controller/controller.go:129 +0x33b
```

**Comment by izaac** [comment]
Rancher version: `v2.6-head (09/14/2021)` _ad21cff_
Behind Squid Proxy with CA self sgined certs.


I wasn't able to reproduce the GKE issue reported above it seems similar to this other issue https://github.com/rancher/rancher/issues/31976  (the UI error is very similar).

```
- Create the cattle-system namespace
- Create the cert-manager namespace if needed and install cert-manager
  - kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.5.1/cert-manager.crds.yaml 
  - helm repo add jetstack https://charts.jetstack.io && helm repo update
  - helm upgrade --install cert-manager jetstack/cert-manager  --namespace cert-manager --version v1.5.1  --set http_proxy=http://<PROXY_HOST>:3128 --set https_proxy=http://<PROXY_HOST>:3128 --set no_proxy=127.0.0.0/8\\,10.0.0.0/8\\,cattle-system.svc\\,172.16.0.0/12\\,192.168.0.0/16\\,.svc\\,.cluster.local
- Add the squid cert to the tls-ca-additional secret
  - cp squid-ca-cert-key.pem  ca-additional.pem
  - kubectl -n cattle-system create secret generic tls-ca-additional --from-file=ca-additional.pem=./ca-additional.pem
- Install Rancher
  - helm install rancher rancher-latest/rancher --version 2.5.9 --namespace cattle-system --set hostname=<RANCHER_HOST> --set rancherImageTag=v2.5-head --set proxy="http://<PROXY_HOST>:3128" --set noProxy="127.0.0.0/8\,10.0.0.0/8\,172.16.0.0/12\,192.168.0.0/16\,10.43.0.1/16\,172.31.0.0/16\,.svc\,.cluster.local\,.cattle-system.svc" --set additionalTrustedCAs=true
```


## EKS Provisioning 

Passed


## GKE Provisioning

Passed


## AKS Provisioning

Not in scope as Dev clarification this AKSv2 is 2.6+ only.
