### ISSUE TITLE
Panic crash in upgradeCluster

### ISSUE THREAD

**Issue by jleni** [rancher/rancher#32953]
**Kind of request:** Bug

**Steps to reproduce (least amount of steps as possible):** Unclear

**Result:**

```
E0530 19:58:53.621744       7 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 19737 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3d822e0, 0x7623260)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/runtime/runtime.go:74 +0x92
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/runtime/runtime.go:48 +0x82
panic(0x3d822e0, 0x7623260)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader.(*upgradeHandler).upgradeCluster(0xc009117290, 0xc0027be670, 0xc004a7f124, 0x7, 0xc0091d5900, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader/upgrade.go:320 +0xe1a
github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader.(*upgradeHandler).Sync(0xc009117290, 0xc00459ac30, 0xf, 0xc014e57680, 0xc000180700, 0x7f721d2d6108, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader/upgrade.go:137 +0x3e5
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*nodeController).AddHandler.func1(0xc00459ac30, 0xf, 0x45de300, 0xc014e57680, 0xc0091d5b20, 0x3, 0x3, 0x0)
	/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_node_controller.go:156 +0x63
github.com/rancher/norman/controller.(*genericController).AddHandler.func1(0xc00459ac30, 0xf, 0x5018f20, 0xc014e57680, 0x5018f20, 0xc014e57680, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20210225010917-c7fd1e24145b/controller/generic_controller.go:62 +0x221
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc00c4b6810, 0xc00459ac30, 0xf, 0x5018f20, 0xc014e57680, 0x5018f20, 0xc014e57680, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*sharedHandler).OnChange(0xc0025a4b70, 0xc00459ac30, 0xf, 0x5018f20, 0xc014e57680, 0xc014a00201, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedhandler.go:65 +0x14a
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc002a551e0, 0xc00459ac30, 0xf, 0xc00785d620, 0xc00797cd50)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:210 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc002a551e0, 0x3a62f40, 0xc00c4c4380, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:192 +0xd7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc002a551e0, 0x203001)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:169 +0x51
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc002a551e0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:158 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc002635bd0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc002635bd0, 0x4fecfa0, 0xc00785d920, 0x1, 0xc002ed26c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc002635bd0, 0x3b9aca00, 0x0, 0x1, 0xc002ed26c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc002635bd0, 0x3b9aca00, 0xc002ed26c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:129 +0x31f
2021/05/30 19:58:53 [INFO] cluster [c-jqz5g] worker-upgrade: call upgrade to reconcile for node [m-zzxqh]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2c5aa8a]
goroutine 19737 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/runtime/runtime.go:55 +0x105
panic(0x3d822e0, 0x7623260)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader.(*upgradeHandler).upgradeCluster(0xc009117290, 0xc0027be670, 0xc004a7f124, 0x7, 0xc0091d5900, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader/upgrade.go:320 +0xe1a
github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader.(*upgradeHandler).Sync(0xc009117290, 0xc00459ac30, 0xf, 0xc014e57680, 0xc000180700, 0x7f721d2d6108, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/rkeworkerupgrader/upgrade.go:137 +0x3e5
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*nodeController).AddHandler.func1(0xc00459ac30, 0xf, 0x45de300, 0xc014e57680, 0xc0091d5b20, 0x3, 0x3, 0x0)
	/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_node_controller.go:156 +0x63
github.com/rancher/norman/controller.(*genericController).AddHandler.func1(0xc00459ac30, 0xf, 0x5018f20, 0xc014e57680, 0x5018f20, 0xc014e57680, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20210225010917-c7fd1e24145b/controller/generic_controller.go:62 +0x221
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc00c4b6810, 0xc00459ac30, 0xf, 0x5018f20, 0xc014e57680, 0x5018f20, 0xc014e57680, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*sharedHandler).OnChange(0xc0025a4b70, 0xc00459ac30, 0xf, 0x5018f20, 0xc014e57680, 0xc014a00201, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedhandler.go:65 +0x14a
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc002a551e0, 0xc00459ac30, 0xf, 0xc00785d620, 0xc00797cd50)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:210 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc002a551e0, 0x3a62f40, 0xc00c4c4380, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:192 +0xd7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc002a551e0, 0x203001)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:169 +0x51
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc002a551e0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:158 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc002635bd0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc002635bd0, 0x4fecfa0, 0xc00785d920, 0x1, 0xc002ed26c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc002635bd0, 0x3b9aca00, 0x0, 0x1, 0xc002ed26c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc002635bd0, 0x3b9aca00, 0xc002ed26c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:129 +0x31f
```

**Comment by snasovich** [comment]
@jleni , thank you for submitting this issue.
Is there any information you could share about the steps to reproduce this issue? Thank you in advance.

**Comment by Jono-SUSE-Rancher** [comment]
Without reproduction steps this is going to be hard to track down. While I like fixing all of the panic crashes I see, we're going to need to gather a little additional data. Until then, I am going to kick this down the road a little bit.

**Comment by jleni** [comment]
This was a complete test deployment where we were testing upgrade procedures.
Sadly, we don't have more information. 
This is something that we recognized and collected the logs, however, unfortunately it never happened again and we didn't keep more data on this test cluster.

**Comment by snasovich** [comment]
@jleni , thank you for the update. Given this information, I'm going to close this issue as not reproducible.
Should this happen again, please feel free to reopen this issue or open a new one.
