### ISSUE TITLE
Keycloak OIDC - API returns 500 on user search autocomplete input fields on Ember

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#33036]
**What kind of request is this:**

**Steps to reproduce:**

- Enable Keycloak OIDC from Dashboard
- Have a cluster ready (I used a downstream cluster)
- Navigate to `Cluster Manager` (Legacy Apps)
- Edit downstream cluster or add cluster member page
- Start typing in the autocomplete input/dropdown

**Result:**

500 from the API `/v3/principals?action=search`

**Other details that may be helpful:**

```
2021/06/03 21:28:31 [TRACE] REST UPDATE apis/management.cattle.io/v3//userattributes/user-tcszx
2021/06/03 21:28:31 [TRACE] REST GET apis/management.cattle.io/v3//authconfigs/keycloakoidc
2021/06/03 21:28:31 [ERROR] Panic serving api request:
goroutine 153746 [running]:
runtime/debug.Stack(0xc00d9c9060, 0x488a7c0, 0x82f9f60)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/rancher/norman/api.(*Server).ServeHTTP.func1(0x5b3f420, 0xc001e33d70)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20210513204752-e48df26b54bd/api/server.go:175 +0x85
panic(0x488a7c0, 0x82f9f60)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
net/http.(*Client).deadline(0x0, 0x0, 0xc00d9c9338, 0x40dc9b)
	/usr/local/go/src/net/http/client.go:188 +0x22
net/http.(*Client).do(0x0, 0xc002ff2c00, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:603 +0x2bd
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:585
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.(*KClient).getFromKeyCloak(0xc000fbe1b8, 0x0, 0x0, 0xc00f2c7700, 0x3c, 0xc00fb25a40, 0x3c, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_client.go:173 +0x355
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.(*KClient).searchPrincipals(0xc000fbe1b8, 0xc006804220, 0x2, 0x0, 0x0, 0x0, 0x0, 0xc00fb25a40, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_client.go:62 +0x1fe
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.(*keyCloakOIDCProvider).SearchPrincipals(0xc000c37260, 0xc006804220, 0x2, 0x0, 0x0, 0x52a97d8, 0x5, 0xc008a7c300, 0x17, 0xc00f16a264, ...)
	/go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_provider.go:71 +0x1e5
github.com/rancher/rancher/pkg/auth/providers.SearchPrincipals(0xc006804220, 0x2, 0x0, 0x0, 0x52a97d8, 0x5, 0xc008a7c300, 0x17, 0xc00f16a264, 0xb, ...)
	/go/src/github.com/rancher/rancher/pkg/auth/providers/providers.go:183 +0x135
github.com/rancher/rancher/pkg/auth/principals.(*principalsHandler).actions(0xc0017a19a0, 0xc012918dfb, 0x6, 0xc001745480, 0xc007de0000, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/auth/principals/handler.go:58 +0x41a
github.com/rancher/norman/api.handleAction(0xc001745480, 0xc007de0000, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20210513204752-e48df26b54bd/api/server.go:263 +0x62
github.com/rancher/norman/api.(*Server).handle(0xc000906000, 0x5b3f420, 0xc001e33d70, 0xc006633a00, 0x40b8ec, 0x4d762e0, 0xc001e33d70)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20210513204752-e48df26b54bd/api/server.go:251 +0xde
github.com/rancher/norman/api.(*Server).ServeHTTP(0xc000906000, 0x5b3f420, 0xc001e33d70, 0xc006633a00)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20210513204752-e48df26b54bd/api/server.go:180 +0x7d
github.com/rancher/apiserver/pkg/middleware.ContentType.func1(0x5b2f3a0, 0xc00845fb00, 0xc006633a00)
	/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20210519053359-f943376c4b42/pkg/middleware/content.go:33 +0x93
net/http.HandlerFunc.ServeHTTP(0xc001b6c6a8, 0x5b2f3a0, 0xc00845fb00, 0xc006633a00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/rancher/apiserver/pkg/middleware.Gzip.func1(0x5b3e520, 0xc0046b49a0, 0xc006633a00)
	/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20210519053359-f943376c4b42/pkg/middleware/gzip.go:60 +0x1e3
net/http.HandlerFunc.ServeHTTP(0xc001b6c6c0, 0x5b3e520, 0xc0046b49a0, 0xc006633a00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/rancher/rancher/pkg/auth/requests.authHeaderHandler.ServeHTTP(0x5ad4800, 0xc001b6c6c0, 0x5b3e520, 0xc0046b49a0, 0xc006633a00)
	/go/src/github.com/rancher/rancher/pkg/auth/requests/filter.go:62 +0x93f
github.com/rancher/rancher/pkg/rbac.NewAccessControlHandler.func1.1(0x5b3e520, 0xc0046b49a0, 0xc006633800)
	/go/src/github.com/rancher/rancher/pkg/rbac/user_based.go:33 +0x1c7
net/http.HandlerFunc.ServeHTTP(0xc010824180, 0x5b3e520, 0xc0046b49a0, 0xc006633800)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/rancher/steve/pkg/auth.ToMiddleware.func1.1(0x5b3e520, 0xc0046b49a0, 0xc006633500)
	/go/pkg/mod/github.com/rancher/steve@v0.0.0-20210520191028-52f86dce9bd4/pkg/auth/filter.go:167 +0x1c7
net/http.HandlerFunc.ServeHTTP(0xc00845f830, 0x5b3e520, 0xc0046b49a0, 0xc006633500)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00006ee40, 0x5b3e520, 0xc0046b49a0, 0xc006633200)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/gorilla/mux.(*Router).ServeHTTP(0xc001113740, 0x5b3e520, 0xc0046b49a0, 0xc006632f00)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rancher/rancher/pkg/multiclustermanager.(*DeferredServer).Middleware.func1(0x5b3e520, 0xc0046b49a0, 0xc006632f00)
	/go/src/github.com/rancher/rancher/pkg/multiclustermanager/deferred.go:113 +0x9d
net/http.HandlerFunc.ServeHTTP(0xc000504400, 0x5b3e520, 0xc0046b49a0, 0xc006632f00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000133e00, 0x5b3e520, 0xc0046b49a0, 0xc006632d00)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rancher/rancher/pkg/api/steve/aggregation.(*aggregationHandler).Middleware.func1(0x5b3e520, 0xc0046b49a0, 0xc006632d00)
	/go/src/github.com/rancher/rancher/pkg/api/steve/aggregation/aggregation.go:47 +0x6e
net/http.HandlerFunc.ServeHTTP(0xc000504440, 0x5b3e520, 0xc0046b49a0, 0xc006632d00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000133d40, 0x5b3e520, 0xc0046b49a0, 0xc006632b00)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rancher/rancher/pkg/api/steve/proxy.NewProxyMiddleware.func1.1(0x5b3e520, 0xc0046b49a0, 0xc006632b00)
	/go/src/github.com/rancher/rancher/pkg/api/steve/proxy/proxy.go:75 +0x65
net/http.HandlerFunc.ServeHTTP(0xc0005044a0, 0x5b3e520, 0xc0046b49a0, 0xc006632b00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/rancher/rancher/pkg/api/steve/proxy.RewriteLocalCluster.func1(0x5b3e520, 0xc0046b49a0, 0xc006632b00)
	/go/src/github.com/rancher/rancher/pkg/api/steve/proxy/proxy.go:42 +0xf2
net/http.HandlerFunc.ServeHTTP(0xc0016d1440, 0x5b3e520, 0xc0046b49a0, 0xc006632b00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/rancher/rancher/pkg/websocket.websocketHandler.ServeHTTP(0x5ad4800, 0xc0016d1440, 0x5b3e520, 0xc0046b49a0, 0xc006632b00)
	/go/src/github.com/rancher/rancher/pkg/websocket/handler.go:35 +0xa2
github.com/rancher/apiserver/pkg/middleware.ContentTypeOptions.func1(0x5b3e520, 0xc0046b49a0, 0xc006632b00)
	/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20210519053359-f943376c4b42/pkg/middleware/cache.go:47 +0x131
net/http.HandlerFunc.ServeHTTP(0xc0016d1518, 0x5b3e520, 0xc0046b49a0, 0xc006632b00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/rancher/rancher/pkg/auth.SetXAPICattleAuthHeader.func1(0x5b3e520, 0xc0046b49a0, 0xc006632b00)
	/go/src/github.com/rancher/rancher/pkg/auth/server.go:180 +0x2ac
net/http.HandlerFunc.ServeHTTP(0xc0016d1530, 0x5b3e520, 0xc0046b49a0, 0xc006632b00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/rancher/rancher/pkg/auth/audit.auditHandler.ServeHTTP(0x5ad4800, 0xc0016d1530, 0x0, 0x5b3e520, 0xc0046b49a0, 0xc006632b00)
	/go/src/github.com/rancher/rancher/pkg/auth/audit/filter.go:32 +0x52e
github.com/rancher/steve/pkg/auth.ToMiddleware.func1.1(0x5b3e520, 0xc0046b49a0, 0xc00b5fc100)
	/go/pkg/mod/github.com/rancher/steve@v0.0.0-20210520191028-52f86dce9bd4/pkg/auth/filter.go:167 +0x1c7
net/http.HandlerFunc.ServeHTTP(0xc003737740, 0x5b3e520, 0xc0046b49a0, 0xc00b5fc100)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/rancher/dynamiclistener/server.wrapHandler.func1(0x5b3e520, 0xc0046b49a0, 0xc00b5fc100)
	/go/pkg/mod/github.com/rancher/dynamiclistener@v0.2.1-0.20201110045217-9b1b7d3132e8/server/server.go:187 +0x95
net/http.HandlerFunc.ServeHTTP(0xc00379be30, 0x5b3e520, 0xc0046b49a0, 0xc00b5fc100)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/rancher/dynamiclistener.HTTPRedirect.func1(0x5b3e520, 0xc0046b49a0, 0xc00b5fc100)
	/go/pkg/mod/github.com/rancher/dynamiclistener@v0.2.1-0.20201110045217-9b1b7d3132e8/redirect.go:20 +0xa4
net/http.HandlerFunc.ServeHTTP(0xc000b44420, 0x5b3e520, 0xc0046b49a0, 0xc00b5fc100)
	/usr/local/go/src/net/http/server.go:2069 +0x44
net/http.serverHandler.ServeHTTP(0xc0008fd180, 0x5b3e520, 0xc0046b49a0, 0xc00b5fc100)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc00aef7f40, 0x5b52900, 0xc0014f6400)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x39b
```

**Environment information**
- Rancher version: `2.6 master-head (06/03/2021)` _be03c8b_
- Installation option: RKE1 HA

**Comment by izaac** [comment]
Rancher version `2.6 master-head (06/14/2021)` _9d54b1a_

Auto complete Inputs in Dashboard are working and I can add/remove users for Site Access, but in the case of RKE1 clusters we're still using Ember Ui forms to create/edit. 

The Ember UI Members autocomplete input fields and Groups Dropdown are returning a `500`

`{"baseType":"error","code":"ServerError","message":"invalid character 'B' looking for beginning of value","status":500,"type":"error"}`

Sample form for editing an RKE1 cluster from Dashboard, we can see the `Members` section to add/remove users.

![Screen Shot 2021-06-14 at 4 16 17 PM](https://user-images.githubusercontent.com/27659/121971016-aa0a7800-cd2c-11eb-8a59-8a839b822523.png)

**Comment by izaac** [comment]
Rancher version: `v2.6 master-head (06/21/2021)` _4d18400_

I no longer see the `500` response from the API  neither panic in the Rancher server logs.

**Comment by izaac** [comment]
Rancher version: `v2.6 master-head (06/21/2021)` _4d18400_
Ok reopening, I was able to add a user, login, logout, see the cluster the user was member of but after that trying to add more users I got the `500` from the API.

No longer panic but these errors were observed:

```
2021/06/21 18:29:34 [TRACE] REST GET apis/management.cattle.io/v3//authconfigs/keycloakoidc
2021/06/21 18:29:34 [DEBUG] Triggering auth refresh on user-65l85
2021/06/21 18:29:34 [DEBUG] Skipping refresh for user-65l85 due to max-age
2021/06/21 18:29:34 [TRACE] ConfigMapController calling handler snapshotbackpopulate kube-system/cattle-controllers
2021/06/21 18:29:34 [TRACE] ConfigMapController calling handler snapshotbackpopulate kube-system/cattle-controllers
2021/06/21 18:29:34 [ERROR] [keycloak oidc]: received error unmarshalling search results, err: invalid character 'B' looking for beginning of value
2021/06/21 18:29:34 [ERROR] [keycloak oidc] problem searching keycloak: invalid character 'B' looking for beginning of value
2021/06/21 18:29:34 [ERROR] Unknown error: invalid character 'B' looking for beginning of value
```

**Comment by izaac** [comment]
Ok there seems to be something about session handling here because I will take a closer look
