### ISSUE TITLE
aksv2 - 502 error on the aksVirtualNetworks POST

### ISSUE THREAD

**Issue by mjura** [rancher/rancher#33195]
Try to create an AKS cluster gives a 502 error on the aksVirtualNetworks POST and with trace logging Rancher throws this:
```
2021/06/14 14:18:14 [DEBUG] 2021/06/14 14:18:14 http: panic serving 47.184.166.12:61137: runtime error: invalid memory address or nil pointer dereference
2021/06/14 14:18:14 [DEBUG] goroutine 2075947 [running]:
2021/06/14 14:18:14 [DEBUG] net/http.(*conn).serve.func1(0xc0050a3e00)
2021/06/14 14:18:14 [DEBUG]      /usr/local/go/src/net/http/server.go:1800 +0x139
2021/06/14 14:18:14 [DEBUG] panic(0x3e64d80, 0x77a94f0)
2021/06/14 14:18:14 [DEBUG]      /usr/local/go/src/runtime/panic.go:975 +0x3e3
2021/06/14 14:18:14 [DEBUG] github.com/rancher/rancher/pkg/multiclustermanager/capabilities.(*AKSVirtualNetworksHandler).ServeHTTP(0x782fcc0, 0x519a180, 0xc00627f6c0, 0xc00605a400)
2021/06/14 14:18:14 [DEBUG]
```
FIX https://github.com/rancher/aks-operator/pull/33

**Comment by prabalsharma** [comment]
I don't see this on master-head

**Comment by mjura** [comment]
This was fixed in aks-operator
https://github.com/rancher/aks-operator/pull/33
