### ISSUE TITLE
Keycloak OIDC - Session for the currently logged admin is expiring before time making the user search to fail

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#33314]
**What kind of request is this:**
bug

**Steps to reproduce:**

- Login as Admin 
- Stay logged in for some time
- Enable Keycloak OIDC
- Try searching for users in the Ember Members input fields (Cluster Members, Project Members, Edit Cluster)

**Result:**
I am seeing these after some time (or if the admin has been logged for some time)  and try to do a user search from ember forms:

`user-65l85` is the local `admin`

```
2021/06/21 19:29:10 [DEBUG] Triggering auth refresh on user-65l85
2021/06/21 19:29:10 [DEBUG] Skipping refresh for user-65l85 due to max-age
```

API returns:

`{"baseType":"error","code":"ServerError","message":"invalid character 'B' looking for beginning of value","status":500,"type":"error"}`

**Expected Result:**

Session shouldn't expire before time and the search users fields should continue to work

**Other details that may be helpful:**

The search works again if I log out and log back in.
I also tried to reproduce this with OpenLDAP, the session stays and the user keeps

**Environment information**
- Rancher version: `2.6 master-head (06/21/2021)` _4d18400_
- Installation option: HA RKE1

Related issue: https://github.com/rancher/rancher/issues/33036

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (07/08/2021)` _cf5a75f_


Is the refresh token request on-demand?

Keycloak seems to have a 30 minutes `SSO Session Idle` of 30 minutes by default. 

If I stay longer that that time idle in the current logged in session without searching and then attempt a user/group search I hit the `500` described in this issue not only with admin but with any user that's logged in and idle.

Rancher has a `auth-user-session-ttl-minutes`  that defaults to `960` or 16 hours.

If I match Keycloak's `SSO Session Idle` with Rancher's session TTL I won't hit this issue. But then using defaults makes refresh token fix not relevant if it's on-demand if we hit the `SSO Session Idle` first we will end with a 500 request and the user will have to request a new session (log out and log in again).

Unless there's a way to request Keycloak's `Refresh Token` before we hit the `SSO Session Idle` the session Idle will be bumped automatically for the users instead of trying to request a new refresh token on-demand. As far as I understand from [Keycloak's Docs](https://wjw465150.gitbooks.io/keycloak-documentation/content/server_admin/topics/sessions/timeouts.html).

`Refresh token requests will also bump the idle timeout.`

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (07/14/2021)` __

Principal search is now returning an empty body. But the Rancher server logs show the panic below.
`/v3/principals?action=search` 

```
2021/07/14 19:21:28 [ERROR] Error during subscribe websocket: close sent
2021/07/14 19:21:36 [ERROR] [keycloak oidc]: received error from keycloak: Get "https://<KEYCLOAK_IP>:8443/auth/admin/realms/amp/users?search=tes": oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Token is not active"}
2021/07/14 19:21:36 [ERROR] Panic serving api request:
goroutine 57311 [running]:
runtime/debug.Stack(0xc00539d2c0, 0x489dc00, 0x8328690)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/rancher/norman/api.(*Server).ServeHTTP.func1(0x5b5dd40, 0xc0098eaf50)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20210608202517-59b3523c3133/api/server.go:175 +0x85
panic(0x489dc00, 0x8328690)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.(*KeyCloakClient).getFromKeyCloak(0xc002431ec8, 0xc001fa8500, 0x43, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_client.go:196 +0x265
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.(*KeyCloakClient).searchPrincipals(0xc002431ec8, 0xc008bb7a60, 0x3, 0x0, 0x0, 0xc00532d680, 0x0, 0x1, 0xc009bb0900, 0x8c1, ...)
	/go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_client.go:51 +0x1d7
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.(*keyCloakOIDCProvider).SearchPrincipals(0xc0001b87e0, 0xc008bb7a60, 0x3, 0x0, 0x0, 0x52be9e2, 0x5, 0xc008d5b0c8, 0x17, 0xc005a6e9d4, ...)
	/go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_provider.go:92 +0x30e
github.com/rancher/rancher/pkg/auth/providers.SearchPrincipals(0xc008bb7a60, 0x3, 0x0, 0x0, 0x52be9e2, 0x5, 0xc008d5b0c8, 0x17, 0xc005a6e9d4, 0xb, ...)
	/go/src/github.com/rancher/rancher/pkg/auth/providers/providers.go:183 +0x135
github.com/rancher/rancher/pkg/auth/principals.(*principalsHandler).actions(0xc000107450, 0xc00ace3d8b, 0x6, 0xc003f3a0e0, 0xc0013a4a20, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/auth/principals/handler.go:58 +0x41a
github.com/rancher/norman/api.handleAction(0xc003f3a0e0, 0xc0013a4a20, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20210608202517-59b3523c3133/api/server.go:263 +0x62
github.com/rancher/norman/api.(*Server).handle(0xc0009d4f20, 0x5b5dd40, 0xc0098eaf50, 0xc0074e2200, 0x40b8ec, 0x4d8a520, 0xc0098eaf50)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20210608202517-59b3523c3133/api/server.go:251 +0xde
github.com/rancher/norman/api.(*Server).ServeHTTP(0xc0009d4f20, 0x5b5dd40, 0xc0098eaf50, 0xc0074e2200)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20210608202517-59b3523c3133/api/server.go:180 +0x7d
github.com/rancher/apiserver/pkg/middleware.ContentType.func1(0x5b4dcc0, 0xc0023c02a0, 0xc0074e2200)
	/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20210519053359-f943376c4b42/pkg/middleware/content.go:33 +0x93
net/http.HandlerFunc.ServeHTTP(0xc001dcf590, 0x5b4dcc0, 0xc0023c02a0, 0xc0074e2200)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/rancher/apiserver/pkg/middleware.Gzip.func1(0x5b5ce40, 0xc00e16d500, 0xc0074e2200)
	/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20210519053359-f943376c4b42/pkg/middleware/gzip.go:60 +0x1e3
net/http.HandlerFunc.ServeHTTP(0xc001dcf5a8, 0x5b5ce40, 0xc00e16d500, 0xc0074e2200)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/rancher/rancher/pkg/auth/requests.authHeaderHandler.ServeHTTP(0x5af2fa0, 0xc001dcf5a8, 0x5b5ce40, 0xc00e16d500, 0xc0074e2200)
	/go/src/github.com/rancher/rancher/pkg/auth/requests/filter.go:64 +0x93f
github.com/rancher/rancher/pkg/rbac.NewAccessControlHandler.func1.1(0x5b5ce40, 0xc00e16d500, 0xc0074e2100)
	/go/src/github.com/rancher/rancher/pkg/rbac/user_based.go:33 +0x1c7
net/http.HandlerFunc.ServeHTTP(0xc008939458, 0x5b5ce40, 0xc00e16d500, 0xc0074e2100)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/rancher/steve/pkg/auth.ToMiddleware.func1.1(0x5b5ce40, 0xc00e16d500, 0xc0074e2000)
	/go/pkg/mod/github.com/rancher/steve@v0.0.0-20210520191028-52f86dce9bd4/pkg/auth/filter.go:167 +0x1c7
net/http.HandlerFunc.ServeHTTP(0xc0023c0180, 0x5b5ce40, 0xc00e16d500, 0xc0074e2000)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00267c780, 0x5b5ce40, 0xc00e16d500, 0xc008ea3e00)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00267d440, 0x5b5ce40, 0xc00e16d500, 0xc008ea3c00)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rancher/rancher/pkg/multiclustermanager.(*DeferredServer).Middleware.func1(0x5b5ce40, 0xc00e16d500, 0xc008ea3c00)
	/go/src/github.com/rancher/rancher/pkg/multiclustermanager/deferred.go:113 +0x9d
net/http.HandlerFunc.ServeHTTP(0xc000b47f60, 0x5b5ce40, 0xc00e16d500, 0xc008ea3c00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00267c3c0, 0x5b5ce40, 0xc00e16d500, 0xc008ea3a00)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00267db00, 0x5b5ce40, 0xc00e16d500, 0xc008ea3700)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rancher/rancher/pkg/api/steve/aggregation.(*aggregationHandler).Middleware.func1(0x5b5ce40, 0xc00e16d500, 0xc008ea3700)
	/go/src/github.com/rancher/rancher/pkg/api/steve/aggregation/aggregation.go:52 +0x6e
net/http.HandlerFunc.ServeHTTP(0xc000b47f80, 0x5b5ce40, 0xc00e16d500, 0xc008ea3700)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00267c300, 0x5b5ce40, 0xc00e16d500, 0xc008ea3500)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rancher/rancher/pkg/api/steve/proxy.NewProxyMiddleware.func1.1(0x5b5ce40, 0xc00e16d500, 0xc008ea3500)
	/go/src/github.com/rancher/rancher/pkg/api/steve/proxy/proxy.go:75 +0x65
net/http.HandlerFunc.ServeHTTP(0xc000b47fa0, 0x5b5ce40, 0xc00e16d500, 0xc008ea3500)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/rancher/rancher/pkg/api/steve/proxy.RewriteLocalCluster.func1(0x5b5ce40, 0xc00e16d500, 0xc008ea3500)
	/go/src/github.com/rancher/rancher/pkg/api/steve/proxy/proxy.go:42 +0xf2
net/http.HandlerFunc.ServeHTTP(0xc0026b0048, 0x5b5ce40, 0xc00e16d500, 0xc008ea3500)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/rancher/rancher/pkg/websocket.websocketHandler.ServeHTTP(0x5af2fa0, 0xc0026b0048, 0x5b5ce40, 0xc00e16d500, 0xc008ea3500)
	/go/src/github.com/rancher/rancher/pkg/websocket/handler.go:35 +0xa2
github.com/rancher/apiserver/pkg/middleware.ContentTypeOptions.func1(0x5b5ce40, 0xc00e16d500, 0xc008ea3500)
	/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20210519053359-f943376c4b42/pkg/middleware/cache.go:47 +0x131
net/http.HandlerFunc.ServeHTTP(0xc0026b0060, 0x5b5ce40, 0xc00e16d500, 0xc008ea3500)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/rancher/rancher/pkg/auth.SetXAPICattleAuthHeader.func1(0x5b5ce40, 0xc00e16d500, 0xc008ea3500)
	/go/src/github.com/rancher/rancher/pkg/auth/server.go:180 +0x2ac
net/http.HandlerFunc.ServeHTTP(0xc0026b0078, 0x5b5ce40, 0xc00e16d500, 0xc008ea3500)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/rancher/rancher/pkg/auth/audit.auditHandler.ServeHTTP(0x5af2fa0, 0xc0026b0078, 0x0, 0xc0026ae280, 0x5b5ce40, 0xc00e16d500, 0xc008ea3500)
	/go/src/github.com/rancher/rancher/pkg/auth/audit/filter.go:57 +0x53c
github.com/rancher/steve/pkg/auth.ToMiddleware.func1.1(0x5b5ce40, 0xc00e16d500, 0xc008ea2b00)
	/go/pkg/mod/github.com/rancher/steve@v0.0.0-20210520191028-52f86dce9bd4/pkg/auth/filter.go:167 +0x1c7
net/http.HandlerFunc.ServeHTTP(0xc00257e690, 0x5b5ce40, 0xc00e16d500, 0xc008ea2b00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/rancher/dynamiclistener/server.wrapHandler.func1(0x5b5ce40, 0xc00e16d500, 0xc008ea2b00)
	/go/pkg/mod/github.com/rancher/dynamiclistener@v0.3.1-0.20210616080009-9865ae859c7f/server/server.go:193 +0x95
net/http.HandlerFunc.ServeHTTP(0xc002589ad0, 0x5b5ce40, 0xc00e16d500, 0xc008ea2b00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/rancher/dynamiclistener.HTTPRedirect.func1(0x5b5ce40, 0xc00e16d500, 0xc008ea2b00)
	/go/pkg/mod/github.com/rancher/dynamiclistener@v0.3.1-0.20210616080009-9865ae859c7f/redirect.go:20 +0xa4
net/http.HandlerFunc.ServeHTTP(0xc00294a9a8, 0x5b5ce40, 0xc00e16d500, 0xc008ea2b00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
net/http.serverHandler.ServeHTTP(0xc001b5d960, 0x5b5ce40, 0xc00e16d500, 0xc008ea2b00)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc009abd360, 0x5b71080, 0xc007f1b3c0)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x39b
```

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (07/29/2021) _94bca99_

Originally I was testing this with a low value in this Keycloak setting: `SSO Session Idle` 
This allowed me to observe the panic above because the sessions were getting expired as expected and the panic was thrown.

On the latest master build tested (see first line of this comment) using the same setting I no longer see the panic in Rancher instead the user gets a 401 response and gets redirected back to the login page as the session is expired.

`{"baseType":"error","code":"Unauthorized","message":"invalid token","status":401,"type":"error"}`

That validated the panic fix. But the Keycloak setting to use for testing the Session refresh should be `Access Token Lifespan` 
Citing dev conversation:

> ... a proper test here would be to turn the access token lifespan to less than the session idle time (its currently set to 20 minutes).

This allowed me to observe the searches working after the Token Lifetime time is passed as it triggers the token refresh that allows the API request to continue working.

I've opened a separate issue for token refresh improvements: 
https://github.com/rancher/rancher/issues/33852
