### ISSUE TITLE
Panic in rancher server logs when AKS v2, GKEv2 or EKS cluster is launched in master-head

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#33693]
**Rancher Server Setup**
- Rancher version: master-head commit id: `8a60508`
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): AKS - 1.19.11

**Information about the Cluster**
- Cluster Type (Local/Downstream): Local - AKS - 1.19.11

**Describe the bug**

- Deployed Rancher HA on AKS 1.19.11
- Dpeloy AKS v2 downstream cluster (Happens when GKE v2 cluster is also deployed)
- Noticed panic in one Rancher pod.
- AKS operator or GKE operators dont get deployed.

**Result**
Panic is seen in rancher server logs:
```
2021/07/20 15:30:07 [INFO] Starting monitoring.coreos.com/v1, Kind=ServiceMonitor controller
--
Tue, Jul 20 2021 8:30:07 am | 2021/07/20 15:30:07 [INFO] Starting management.cattle.io/v3, Kind=SamlToken controller
Tue, Jul 20 2021 8:30:07 am | 2021/07/20 15:30:07 [INFO] Watching metadata for cluster.x-k8s.io/v1alpha3, Kind=MachineHealthCheck
Tue, Jul 20 2021 8:30:07 am | E0720 15:30:07.718292 31 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
Tue, Jul 20 2021 8:30:07 am | goroutine 2972 [running]:
Tue, Jul 20 2021 8:30:07 am | k8s.io/apimachinery/pkg/util/runtime.logPanic(0x48a0d20, 0x832e730)
Tue, Jul 20 2021 8:30:07 am | /go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/runtime/runtime.go:74 +0x95
Tue, Jul 20 2021 8:30:07 am | k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
Tue, Jul 20 2021 8:30:07 am | /go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/runtime/runtime.go:48 +0x86
Tue, Jul 20 2021 8:30:07 am | panic(0x48a0d20, 0x832e730)
Tue, Jul 20 2021 8:30:07 am | /usr/local/go/src/runtime/panic.go:965 +0x1b9
Tue, Jul 20 2021 8:30:07 am | github.com/rancher/rancher/pkg/controllers/dashboard/hostedcluster.handler.removeLegacyOperatorIfExists(0xc0013c90e0, 0x0, 0x0, 0x5bd56a0, 0xc00979e150, 0x5b76290, 0xc00977f200, 0x5b771a8, 0xc00977f230, 0x52bf7b5, ...)
Tue, Jul 20 2021 8:30:07 am | /go/src/github.com/rancher/rancher/pkg/controllers/dashboard/hostedcluster/controller.go:146 +0x17f
Tue, Jul 20 2021 8:30:07 am | github.com/rancher/rancher/pkg/controllers/dashboard/hostedcluster.handler.onClusterChange(0xc0013c90e0, 0x0, 0x0, 0x5bd56a0, 0xc00979e150, 0x5b76290, 0xc00977f200, 0x5b771a8, 0xc00977f230, 0xc003139ec0, ...)
Tue, Jul 20 2021 8:30:07 am | /go/src/github.com/rancher/rancher/pkg/controllers/dashboard/hostedcluster/controller.go:102 +0x117
Tue, Jul 20 2021 8:30:07 am | github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3.FromClusterHandlerToHandler.func1(0xc003139ec0, 0x7, 0x5b1e2e0, 0xc0088ba000, 0xc0088ba000, 0x5be66f0, 0xc0088ba000, 0x1)
Tue, Jul 20 2021 8:30:07 am | /go/src/github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3/cluster.go:105 +0x6b
Tue, Jul 20 2021 8:30:07 am | github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc00ec7d970, 0xc003139ec0, 0x7, 0x5b1e2e0, 0xc0088ba000, 0x0, 0xc0088ba000, 0x0, 0x0)
Tue, Jul 20 2021 8:30:07 am | /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/sharedcontroller.go:29 +0x4e
Tue, Jul 20 2021 8:30:07 am | github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc0017b0d40, 0xc003139ec0, 0x7, 0x5b1e2e0, 0xc0088ba000, 0xc002a24101, 0x0)
Tue, Jul 20 2021 8:30:07 am | /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/sharedhandler.go:69 +0x14c
Tue, Jul 20 2021 8:30:07 am | github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc0009e56b0, 0xc003139ec0, 0x7, 0xc002a243e8, 0x202e7365756c61)
Tue, Jul 20 2021 8:30:07 am | /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:215 +0xd1
Tue, Jul 20 2021 8:30:07 am | github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0009e56b0, 0x44ff6e0, 0xc00a3fc720, 0x0, 0x0)
Tue, Jul 20 2021 8:30:07 am | /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:197 +0xe7
Tue, Jul 20 2021 8:30:07 am | github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0009e56b0, 0x203000)
Tue, Jul 20 2021 8:30:07 am | /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:174 +0x54
Tue, Jul 20 2021 8:30:07 am | github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
Tue, Jul 20 2021 8:30:07 am | /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:163
Tue, Jul 20 2021 8:30:07 am | k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000087be0)
Tue, Jul 20 2021 8:30:07 am | /go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:155 +0x5f
Tue, Jul 20 2021 8:30:07 am | k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000087be0, 0x5aefb00, 0xc001b34c60, 0x2020202020202001, 0xc0001032c0)
Tue, Jul 20 2021 8:30:07 am | /go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:156 +0x9b
Tue, Jul 20 2021 8:30:07 am | k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000087be0, 0x3b9aca00, 0x0, 0x63656a626f203a01, 0xc0001032c0)
Tue, Jul 20 2021 8:30:07 am | /go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:133 +0x98
Tue, Jul 20 2021 8:30:07 am | k8s.io/apimachinery/pkg/util/wait.Until(0xc000087be0, 0x3b9aca00, 0xc0001032c0)
Tue, Jul 20 2021 8:30:07 am | /go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:90 +0x4d
Tue, Jul 20 2021 8:30:07 am | created by github.com/rancher/lasso/pkg/controller.(*controller).run
Tue, Jul 20 2021 8:30:07 am | /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:134 +0x33b
Tue, Jul 20 2021 8:30:07 am | panic: runtime error: invalid memory address or nil pointer dereference [recovered]
Tue, Jul 20 2021 8:30:07 am | panic: runtime error: invalid memory address or nil pointer dereference
Tue, Jul 20 2021 8:30:07 am | [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x32b161f]
Tue, Jul 20 2021 8:30:07 am |  
Tue, Jul 20 2021 8:30:07 am | goroutine 2972 [running]:
Tue, Jul 20 2021 8:30:07 am | k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
Tue, Jul 20 2021 8:30:07 am | /go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/runtime/runtime.go:55 +0x109
Tue, Jul 20 2021 8:30:07 am | panic(0x48a0d20, 0x832e730)
Tue, Jul 20 2021 8:30:07 am | /usr/local/go/src/runtime/panic.go:965 +0x1b9
Tue, Jul 20 2021 8:30:07 am | github.com/rancher/rancher/pkg/controllers/dashboard/hostedcluster.handler.removeLegacyOperatorIfExists(0xc0013c90e0, 0x0, 0x0, 0x5bd56a0, 0xc00979e150, 0x5b76290, 0xc00977f200, 0x5b771a8, 0xc00977f230, 0x52bf7b5, ...)
Tue, Jul 20 2021 8:30:07 am | /go/src/github.com/rancher/rancher/pkg/controllers/dashboard/hostedcluster/controller.go:146 +0x17f
Tue, Jul 20 2021 8:30:07 am | github.com/rancher/rancher/pkg/controllers/dashboard/hostedcluster.handler.onClusterChange(0xc0013c90e0, 0x0, 0x0, 0x5bd56a0, 0xc00979e150, 0x5b76290, 0xc00977f200, 0x5b771a8, 0xc00977f230, 0xc003139ec0, ...)
Tue, Jul 20 2021 8:30:07 am | /go/src/github.com/rancher/rancher/pkg/controllers/dashboard/hostedcluster/controller.go:102 +0x117
Tue, Jul 20 2021 8:30:07 am | github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3.FromClusterHandlerToHandler.func1(0xc003139ec0, 0x7, 0x5b1e2e0, 0xc0088ba000, 0xc0088ba000, 0x5be66f0, 0xc0088ba000, 0x1)
Tue, Jul 20 2021 8:30:07 am | /go/src/github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3/cluster.go:105 +0x6b
Tue, Jul 20 2021 8:30:07 am | github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc00ec7d970, 0xc003139ec0, 0x7, 0x5b1e2e0, 0xc0088ba000, 0x0, 0xc0088ba000, 0x0, 0x0)
Tue, Jul 20 2021 8:30:07 am | /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/sharedcontroller.go:29 +0x4e
Tue, Jul 20 2021 8:30:07 am | github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc0017b0d40, 0xc003139ec0, 0x7, 0x5b1e2e0, 0xc0088ba000, 0xc002a24101, 0x0)
Tue, Jul 20 2021 8:30:07 am | /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/sharedhandler.go:69 +0x14c
Tue, Jul 20 2021 8:30:07 am | github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc0009e56b0, 0xc003139ec0, 0x7, 0xc002a243e8, 0x202e7365756c61)
Tue, Jul 20 2021 8:30:07 am | /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:215 +0xd1
Tue, Jul 20 2021 8:30:07 am | github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0009e56b0, 0x44ff6e0, 0xc00a3fc720, 0x0, 0x0)
Tue, Jul 20 2021 8:30:07 am | /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:197 +0xe7
Tue, Jul 20 2021 8:30:07 am | github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0009e56b0, 0x203000)
Tue, Jul 20 2021 8:30:07 am | /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:174 +0x54
Tue, Jul 20 2021 8:30:07 am | github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
Tue, Jul 20 2021 8:30:07 am | /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:163
Tue, Jul 20 2021 8:30:07 am | k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000087be0)
Tue, Jul 20 2021 8:30:07 am | /go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:155 +0x5f
Tue, Jul 20 2021 8:30:07 am | k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000087be0, 0x5aefb00, 0xc001b34c60, 0x2020202020202001, 0xc0001032c0)
Tue, Jul 20 2021 8:30:07 am | /go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:156 +0x9b
Tue, Jul 20 2021 8:30:07 am | k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000087be0, 0x3b9aca00, 0x0, 0x63656a626f203a01, 0xc0001032c0)
Tue, Jul 20 2021 8:30:07 am | /go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:133 +0x98
Tue, Jul 20 2021 8:30:07 am | k8s.io/apimachinery/pkg/util/wait.Until(0xc000087be0, 0x3b9aca00, 0xc0001032c0)
Tue, Jul 20 2021 8:30:07 am | /go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:90 +0x4d
Tue, Jul 20 2021 8:30:07 am | created by github.com/rancher/lasso/pkg/controller.(*controller).run
Tue, Jul 20 2021 8:30:07 am | /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:134 +0x33b


```
- Used `Standard_D2_v2` for nodes.
- Charts commit:
```
status:
  branch: dev-v2.6
  commit: 5163d9813ed4139624d1cd9e01adcc463d4c60c3
```

**Comment by sowmyav27** [comment]
Maybe because of using smaller instances for local cluster. In the process of confirming this

**Comment by sowmyav27** [comment]
On Master-head commit id: `9e0d1b2`, able to deploy AKSv2, EKSv2 and GKEv2 clusters on a HA install. No issues seen
