### ISSUE TITLE
RKE2 Provisioning: Deleting a controlplane+etcd machine from a machine pool does not delete the kubernetes node

### ISSUE THREAD

**Issue by bashofmann** [rancher/rancher#33981]
**Rancher Server Setup**
- Rancher version: v2.6.0-rc1
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): 1.21.3+k3s1
- Proxy/Cert Details: no proxy, Let's Encrypt certificate

**Information about the Cluster**
- Kubernetes version: v1.21.3+rke2r1 
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): infrastructure provider, tested with DO

**Describe the bug**
When you delete a controlplane+etcd machine from a machine pool, for example in order to recreate it, the VM and machine will be deleted and a new VM and machine will be created. But the Kubernetes Node remains.

The Kubernetes Node object has a `deletionTimestamp` but it has a `wrangler.cattle.io/node` finalizer that does not get removed. Removing the finalizer manually also removes the node.

If you delete a worker machine, the kubernetes node is also deleted successfully.

**To Reproduce**
* Create a RKE2 cluster at an infrastructure provider with 1 pool of 3 controlplane+etcd and 1 pool of 2 worker nodes
* Delete a worker machine from the 2nd pool: the machine and vm will be recreated, the original kubernetes node will be deleted
* Delete a controlplane+etcd machine from the 1st pool: the machine and vm will be recreted, the original kubernetes node remains

**Result**
The Kubernetes Node object does not get removed.

**Expected Result**
The Kubernetes Node object does get removed.

**Screenshots**
![Bildschirmfoto 2021-08-05 um 17 34 42](https://user-images.githubusercontent.com/243056/128380207-46df7885-b20e-4914-b654-ae73e319b3eb.png)
![Bildschirmfoto 2021-08-05 um 17 35 43](https://user-images.githubusercontent.com/243056/128380211-24dad548-9666-4544-954e-e58dd8976035.png)
![Bildschirmfoto 2021-08-05 um 17 45 27](https://user-images.githubusercontent.com/243056/128380247-d09e018e-c9fd-48e9-8be0-b3f0d8940232.png)

**Additional context**
I not sure, if this is related: The rancher logs are spammed with:

```
2021/08/05 15:46:29 [INFO] Updating workload [kube-system/rke2-ingress-nginx-controller] with public endpoints [[{"nodeName":"c-m-ceeb1766:machine-cmqc9","addresses":["46.101.53.7"],"port":80,"protocol":"TCP","podName":"kube-system:rke2-ingress-nginx-controller-q5h77","allNodes":false},{"nodeName":"c-m-ceeb1766:machine-cmqc9","addresses":["46.101.53.7"],"port":443,"protocol":"TCP","podName":"kube-system:rke2-ingress-nginx-controller-q5h77","allNodes":false},{"nodeName":"c-m-ceeb1766:machine-cmqc9","addresses":["46.101.53.7"],"port":8443,"protocol":"TCP","podName":"kube-system:rke2-ingress-nginx-controller-q5h77","allNodes":false},{"nodeName":"c-m-ceeb1766:machine-r5b67","addresses":["178.62.97.43"],"port":80,"protocol":"TCP","podName":"kube-system:rke2-ingress-nginx-controller-lvgkz","allNodes":false},{"nodeName":"c-m-ceeb1766:machine-r5b67","addresses":["178.62.97.43"],"port":443,"protocol":"TCP","podName":"kube-system:rke2-ingress-nginx-controller-lvgkz","allNodes":false},{"nodeName":"c-m-ceeb1766:machine-r5b67","addresses":["178.62.97.43"],"port":8443,"protocol":"TCP","podName":"kube-system:rke2-ingress-nginx-controller-lvgkz","allNodes":false},{"nodeName":"c-m-ceeb1766:machine-kb2ck","addresses":["167.99.80.251"],"port":80,"protocol":"TCP","podName":"kube-system:rke2-ingress-nginx-controller-29lmg","allNodes":false},{"nodeName":"c-m-ceeb1766:machine-kb2ck","addresses":["167.99.80.251"],"port":443,"protocol":"TCP","podName":"kube-system:rke2-ingress-nginx-controller-29lmg","allNodes":false},{"nodeName":"c-m-ceeb1766:machine-kb2ck","addresses":["167.99.80.251"],"port":8443,"protocol":"TCP","podName":"kube-system:rke2-ingress-nginx-controller-29lmg","allNodes":false},{"nodeName":"c-m-ceeb1766:machine-vbxwz","addresses":["167.99.83.118"],"port":80,"protocol":"TCP","podName":"kube-system:rke2-ingress-nginx-controller-cfnw4","allNodes":false},{"nodeName":"c-m-ceeb1766:machine-vbxwz","addresses":["167.99.83.118"],"port":443,"protocol":"TCP","podName":"kube-system:rke2-ingress-nginx-controller-cfnw4","allNodes":false},{"nodeName":"c-m-ceeb1766:machine-vbxwz","addresses":["167.99.83.118"],"port":8443,"protocol":"TCP","podName":"kube-system:rke2-ingress-nginx-controller-cfnw4","allNodes":false},{"nodeName":"c-m-ceeb1766:machine-n6p8w","addresses":["167.99.91.220"],"port":80,"protocol":"TCP","podName":"kube-system:rke2-ingress-nginx-controller-7xkg6","allNodes":false},{"nodeName":"c-m-ceeb1766:machine-n6p8w","addresses":["167.99.91.220"],"port":443,"protocol":"TCP","podName":"kube-system:rke2-ingress-nginx-controller-7xkg6","allNodes":false},{"nodeName":"c-m-ceeb1766:machine-n6p8w","addresses":["167.99.91.220"],"port":8443,"protocol":"TCP","podName":"kube-system:rke2-ingress-nginx-controller-7xkg6","allNodes":false},{"nodeName":"c-m-ceeb1766:machine-tbz8g","addresses":["159.65.61.231"],"port":80,"protocol":"TCP","podName":"kube-system:rke2-ingress-nginx-controller-pwxdx","allNodes":false},{"nodeName":"c-m-ceeb1766:machine-tbz8g","addresses":["159.65.61.231"],"port":443,"protocol":"TCP","podName":"kube-system:rke2-ingress-nginx-controller-pwxdx","allNodes":false},{"nodeName":"c-m-ceeb1766:machine-tbz8g","addresses":["159.65.61.231"],"port":8443,"protocol":"TCP","podName":"kube-system:rke2-ingress-nginx-controller-pwxdx","allNodes":false}]]
```

**Comment by ibuildthecloud** [comment]
Did this eventually resolve?  The wrangler.cattle.io/node finalizer will not be removed from the node and the node finally deleted until the node has been fully removed from etcd.  If the old node was the leader this could take some time and usually doesn't seem to happen until the new replacement comes.  In my tests this could be around 10 minutes until it's finally gone.  You can look at `journalctl -u rke2-server` on each control plane node to get an idea of what etcd is doing.

**Comment by ibuildthecloud** [comment]
One thing I've noticed is that if you are watching the nodes in the UI it doesn't always update.  If you refresh the page it resyncs.  I'm not sure why the UI is updating.

**Comment by ibuildthecloud** [comment]
I was able to reproduce.  It seems that the etcd node remove is hanging
````
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]: goroutine 441 [select, 46 minutes]:
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]: google.golang.org/grpc/internal/transport.(*Stream).waitOnHeader(0xc002c18c00)
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]:         /go/pkg/mod/google.golang.org/grpc@v1.27.1/internal/transport/transport.go:318 +0x99
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]: google.golang.org/grpc/internal/transport.(*Stream).RecvCompress(...)
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]:         /go/pkg/mod/google.golang.org/grpc@v1.27.1/internal/transport/transport.go:333
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]: google.golang.org/grpc.(*csAttempt).recvMsg(0xc005f3cc00, 0x623abe0, 0xc005c6fda0, 0x0, 0x0, 0x0)
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]:         /go/pkg/mod/google.golang.org/grpc@v1.27.1/stream.go:871 +0x75e
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]: google.golang.org/grpc.(*clientStream).RecvMsg.func1(0xc005f3cc00, 0xc000ded610, 0xb)
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]:         /go/pkg/mod/google.golang.org/grpc@v1.27.1/stream.go:736 +0x46
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]: google.golang.org/grpc.(*clientStream).withRetry(0xc0015947e0, 0xc001dfd1c0, 0xc001dfd190, 0xc000ded608, 0xc002182390)
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]:         /go/pkg/mod/google.golang.org/grpc@v1.27.1/stream.go:594 +0x9f
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]: google.golang.org/grpc.(*clientStream).RecvMsg(0xc0015947e0, 0x623abe0, 0xc005c6fda0, 0x0, 0x0)
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]:         /go/pkg/mod/google.golang.org/grpc@v1.27.1/stream.go:735 +0x105
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]: google.golang.org/grpc.invoke(0x715a3c0, 0xc002182360, 0x6762889, 0x22, 0x61930a0, 0xc000ded590, 0x623abe0, 0xc005c6fda0, 0xc000852e00, 0xc005907a40, ...)
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]:         /go/pkg/mod/google.golang.org/grpc@v1.27.1/call.go:73 +0x142
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]: go.etcd.io/etcd/clientv3.(*Client).unaryClientInterceptor.func1(0x715a318, 0xc002182360, 0x6762889, 0x22, 0x61930a0, 0xc000ded590, 0x623abe0, 0xc005c6fda0, 0xc000852e00, 0x6928238, ...)
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]:         /go/pkg/mod/github.com/k3s-io/etcd@v0.5.0-alpha.5.0.20201208200253-50621aee4aea/clientv3/retry_interceptor.go:58 +0x45e
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]: google.golang.org/grpc.(*ClientConn).Invoke(0xc000852e00, 0x715a318, 0xc000f4dd80, 0x6762889, 0x22, 0x61930a0, 0xc000ded590, 0x623abe0, 0xc005c6fda0, 0x9d43360, ...)
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]:         /go/pkg/mod/google.golang.org/grpc@v1.27.1/call.go:35 +0x109
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]: google.golang.org/grpc.Invoke(...)
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]:         /go/pkg/mod/google.golang.org/grpc@v1.27.1/call.go:60
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]: go.etcd.io/etcd/etcdserver/etcdserverpb.(*clusterClient).MemberRemove(0xc000939d50, 0x715a318, 0xc000f4dd80, 0xc000ded590, 0x9d43360, 0x3, 0x3, 0x5d12ae0, 0x481201, 0xc000ded590)
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]:         /go/pkg/mod/github.com/k3s-io/etcd@v0.5.0-alpha.5.0.20201208200253-50621aee4aea/etcdserver/etcdserverpb/rpc.pb.go:4045 +0xcf
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]: go.etcd.io/etcd/clientv3.(*retryClusterClient).MemberRemove(0xc00068cc90, 0x715a318, 0xc000f4dd80, 0xc000ded590, 0x9d43360, 0x3, 0x3, 0x3, 0x3, 0xc00058f420)
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]:         /go/pkg/mod/github.com/k3s-io/etcd@v0.5.0-alpha.5.0.20201208200253-50621aee4aea/clientv3/retry.go:175 +0x7c
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]: go.etcd.io/etcd/clientv3.(*cluster).MemberRemove(0xc000c35ef0, 0x715a318, 0xc000f4dd80, 0x8973c6f6015a3689, 0xc001dfda00, 0x3, 0x3)
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]:         /go/pkg/mod/github.com/k3s-io/etcd@v0.5.0-alpha.5.0.20201208200253-50621aee4aea/clientv3/cluster.go:103 +0x88
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]: github.com/rancher/k3s/pkg/etcd.(*ETCD).removePeer(0xc000ba01e0, 0x715a318, 0xc000f4dd80, 0xc000d72920, 0x1c, 0xc001222540, 0xf, 0xc005ce9b00, 0x2a, 0xc005fbeb28)
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]:         /go/pkg/mod/github.com/rancher/k3s@v1.21.1-rc1.0.20210803175321-2069cdf4eee6/pkg/etcd/etcd.go:582 +0x38f
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]: github.com/rancher/k3s/pkg/etcd.(*handler).onRemove(0xc001605a40, 0xc002172c60, 0x13, 0xc00150d200, 0x2, 0x0, 0x2a)
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]:         /go/pkg/mod/github.com/rancher/k3s@v1.21.1-rc1.0.20210803175321-2069cdf4eee6/pkg/etcd/controller.go:90 +0x148
Aug 05 18:19:06 darren2-pool1-xl8sb rke2[6174]: github.com/rancher/wrangler-api/pkg/generated/controllers/core/v1.FromNodeHandlerToHandler.func1(0xc002172c60, 0x13, 0x70ed190, 0xc00150d200, 0x0,```

**Comment by Jono-SUSE-Rancher** [comment]
https://github.com/k3s-io/k3s/issues/2669 being addressed by RKE2 team via https://github.com/rancher/kontainer-driver-metadata/pull/632 should fix this - moving it back into Test.

**Comment by anupama2501** [comment]
Verified on v2.6-head ba95a58

- Created a cluster on rancher HA with 3 etcd+ cp nodes, 2 worker nodes.
- Deleted the worker nodes from cluster management --> cluster page
- Verified from the explore cluster --> kube nodes page, nodes deleted from cluster management page are completely removed.
- New nodes come up active.
