### ISSUE TITLE
Panic in Rancher server after upgrade 2.5

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#34070]
If this is a UI issue, please file an issue at https://github.com/rancher/dashboard/

**Rancher Server Setup**
- Rancher version: upgraded setup from 2.5.3 to 2.6-head commit id: `4b6af95d`
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: Rancher generated

**Describe the bug**
Panic in rancher server

**To Reproduce**
Panic was seen when these steps were taken on the rancher HA.
- Deploy a Rancher server in 2.5.3
- Deploy a couple of RKE1 clusters
- Upgrade rancher to 2.6-head
- Panic seen in rancher logs

**Result**
Rancher logs:
```
2021/08/09 04:54:29 [ERROR] Failed to handling tunnel request from <>:40302: response 400: cluster not found
2021/08/09 04:54:34 [ERROR] Panic serving api request:
goroutine 18643 [running]:
runtime/debug.Stack(0xc008abe1b8, 0x399caa0, 0x68f02d0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/rancher/norman/api.(*Server).ServeHTTP.func1(0x48b9240, 0xc00885e370)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20210608202517-59b3523c3133/api/server.go:175 +0x85
panic(0x399caa0, 0x68f02d0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/rancher/rancher/pkg/impersonation.(*Impersonator).checkAndUpdateRole(0xc008abe500, 0xc00f513c20, 0x4, 0x4, 0x4373c68, 0x4373c68, 0x454c01)
	/go/src/github.com/rancher/rancher/pkg/impersonation/impersonation.go:131 +0x7c
github.com/rancher/rancher/pkg/impersonation.(*Impersonator).SetUpImpersonation(0xc008abe500, 0x4373c68, 0x1)
	/go/src/github.com/rancher/rancher/pkg/impersonation/impersonation.go:35 +0x5b
github.com/rancher/rancher/pkg/clusterrouter/proxy.(*RemoteService).getImpersonatorAccountToken(0xc0082fc3f0, 0x48c9920, 0xc00d8d9a40, 0x48c9920, 0xc00d8d9a40, 0xc008abe601, 0x13)
	/go/src/github.com/rancher/rancher/pkg/clusterrouter/proxy/proxy_server.go:284 +0x68
github.com/rancher/rancher/pkg/clusterrouter/proxy.(*RemoteService).ServeHTTP(0xc0082fc3f0, 0x48b9240, 0xc00885e370, 0xc001d44d00)
	/go/src/github.com/rancher/rancher/pkg/clusterrouter/proxy/proxy_server.go:232 +0x34c
github.com/rancher/rancher/pkg/clusterrouter.(*Router).ServeHTTP(0xc0009fab80, 0x48b9240, 0xc00885e370, 0xc001d44d00)
	/go/src/github.com/rancher/rancher/pkg/clusterrouter/router.go:41 +0x14d
github.com/rancher/rancher/pkg/api/norman/customization/yaml.(*yamlLinkHandler).LinkHandler(0xc000b3f860, 0xc0087027e0, 0x0, 0xc0018e0f00, 0xc00da46a80)
	/go/src/github.com/rancher/rancher/pkg/api/norman/customization/yaml/link.go:65 +0x45b
github.com/rancher/norman/api/handler.ListHandler(0xc0087027e0, 0x4375e68, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20210608202517-59b3523c3133/api/handler/list.go:34 +0x196
github.com/rancher/norman/api.(*Server).handle(0xc0007ec8f0, 0x48b9240, 0xc00885e370, 0xc001d44b00, 0x40b84c, 0x3d91840, 0xc00885e370)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20210608202517-59b3523c3133/api/server.go:249 +0x28c
github.com/rancher/norman/api.(*Server).ServeHTTP(0xc0007ec8f0, 0x48b9240, 0xc00885e370, 0xc001d44b00)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20210608202517-59b3523c3133/api/server.go:180 +0x7d
github.com/rancher/apiserver/pkg/middleware.ContentType.func1(0x48a95e0, 0xc003267a10, 0xc001d44b00)
	/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20210727155917-6a723678dd3d/pkg/middleware/content.go:33 +0x93
net/http.HandlerFunc.ServeHTTP(0xc002488f18, 0x48a95e0, 0xc003267a10, 0xc001d44b00)
	/usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/apiserver/pkg/middleware.Gzip.func1(0x48b8670, 0xc00a7b77a0, 0xc001d44b00)
	/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20210727155917-6a723678dd3d/pkg/middleware/gzip.go:60 +0x1e3
net/http.HandlerFunc.ServeHTTP(0xc002488f30, 0x48b8670, 0xc00a7b77a0, 0xc001d44b00)
	/usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/rancher/pkg/auth/requests.authHeaderHandler.ServeHTTP(0x4859580, 0xc002488f30, 0x48b8670, 0xc00a7b77a0, 0xc001d44b00)
	/go/src/github.com/rancher/rancher/pkg/auth/requests/filter.go:64 +0x93f
github.com/rancher/rancher/pkg/rbac.NewAccessControlHandler.func1.1(0x48b8670, 0xc00a7b77a0, 0xc0057e5f00)
	/go/src/github.com/rancher/rancher/pkg/rbac/user_based.go:33 +0x1c7
net/http.HandlerFunc.ServeHTTP(0xc000fc8720, 0x48b8670, 0xc00a7b77a0, 0xc0057e5f00)
	/usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/steve/pkg/auth.ToMiddleware.func1.1(0x48b8670, 0xc00a7b77a0, 0xc0057e5e00)
	/go/pkg/mod/github.com/rancher/steve@v0.0.0-20210804220357-bb76e4db5669/pkg/auth/filter.go:167 +0x1c7
net/http.HandlerFunc.ServeHTTP(0xc0032678f0, 0x48b8670, 0xc00a7b77a0, 0xc0057e5e00)
	/usr/local/go/src/net/http/server.go:2049 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc002d62780, 0x48b8670, 0xc00a7b77a0, 0xc0057e5c00)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/gorilla/mux.(*Router).ServeHTTP(0xc002d62c00, 0x48b8670, 0xc00a7b77a0, 0xc0057e5a00)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rancher/rancher/pkg/multiclustermanager.(*DeferredServer).Middleware.func1(0x48b8670, 0xc00a7b77a0, 0xc0057e5a00)
	/go/src/github.com/rancher/rancher/pkg/multiclustermanager/deferred.go:113 +0x9d
net/http.HandlerFunc.ServeHTTP(0xc002d9fa40, 0x48b8670, 0xc00a7b77a0, 0xc0057e5a00)
	/usr/local/go/src/net/http/server.go:2049 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc002d62480, 0x48b8670, 0xc00a7b77a0, 0xc0057e5700)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0027b4fc0, 0x48b8670, 0xc00a7b77a0, 0xc0057e5500)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rancher/rancher/pkg/api/steve/aggregation.(*aggregationHandler).Middleware.func1(0x48b8670, 0xc00a7b77a0, 0xc0057e5500)
	/go/src/github.com/rancher/rancher/pkg/api/steve/aggregation/aggregation.go:52 +0x6e
net/http.HandlerFunc.ServeHTTP(0xc002d9fa60, 0x48b8670, 0xc00a7b77a0, 0xc0057e5500)
	/usr/local/go/src/net/http/server.go:2049 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc002d623c0, 0x48b8670, 0xc00a7b77a0, 0xc0057e5100)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rancher/rancher/pkg/api/steve/proxy.NewProxyMiddleware.func1.1(0x48b8670, 0xc00a7b77a0, 0xc0057e5100)
	/go/src/github.com/rancher/rancher/pkg/api/steve/proxy/proxy.go:75 +0x65
net/http.HandlerFunc.ServeHTTP(0xc002d9fa80, 0x48b8670, 0xc00a7b77a0, 0xc0057e5100)
	/usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/rancher/pkg/api/steve/proxy.RewriteLocalCluster.func1(0x48b8670, 0xc00a7b77a0, 0xc0057e5100)
	/go/src/github.com/rancher/rancher/pkg/api/steve/proxy/proxy.go:42 +0xf2
net/http.HandlerFunc.ServeHTTP(0xc001fc7188, 0x48b8670, 0xc00a7b77a0, 0xc0057e5100)
	/usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/rancher/pkg/websocket.websocketHandler.ServeHTTP(0x4859580, 0xc001fc7188, 0x48b8670, 0xc00a7b77a0, 0xc0057e5100)
	/go/src/github.com/rancher/rancher/pkg/websocket/handler.go:35 +0xa2
github.com/rancher/apiserver/pkg/middleware.ContentTypeOptions.func1(0x48b8670, 0xc00a7b77a0, 0xc0057e5100)
	/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20210727155917-6a723678dd3d/pkg/middleware/cache.go:47 +0x131
net/http.HandlerFunc.ServeHTTP(0xc001fc71a0, 0x48b8670, 0xc00a7b77a0, 0xc0057e5100)
	/usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/rancher/pkg/auth.SetXAPICattleAuthHeader.func1(0x48b8670, 0xc00a7b77a0, 0xc0057e5100)
	/go/src/github.com/rancher/rancher/pkg/auth/server.go:180 +0x2ac
net/http.HandlerFunc.ServeHTTP(0xc001fc71b8, 0x48b8670, 0xc00a7b77a0, 0xc0057e5100)
	/usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/rancher/pkg/auth/audit.auditHandler.ServeHTTP(0x4859580, 0xc001fc71b8, 0x0, 0xc002dd57c0, 0x48b8670, 0xc00a7b77a0, 0xc0057e5100)
	/go/src/github.com/rancher/rancher/pkg/auth/audit/filter.go:57 +0x53c
github.com/rancher/steve/pkg/auth.ToMiddleware.func1.1(0x48b8670, 0xc00a7b77a0, 0xc0057e4400)
	/go/pkg/mod/github.com/rancher/steve@v0.0.0-20210804220357-bb76e4db5669/pkg/auth/filter.go:167 +0x1c7
net/http.HandlerFunc.ServeHTTP(0xc001bd2840, 0x48b8670, 0xc00a7b77a0, 0xc0057e4400)
	/usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/dynamiclistener/server.wrapHandler.func1(0x48b8670, 0xc00a7b77a0, 0xc0057e4400)
	/go/pkg/mod/github.com/rancher/dynamiclistener@v0.3.1-0.20210616080009-9865ae859c7f/server/server.go:193 +0x95
net/http.HandlerFunc.ServeHTTP(0xc0018e02a0, 0x48b8670, 0xc00a7b77a0, 0xc0057e4400)
	/usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/dynamiclistener.HTTPRedirect.func1(0x48b8670, 0xc00a7b77a0, 0xc0057e4400)
	/go/pkg/mod/github.com/rancher/dynamiclistener@v0.3.1-0.20210616080009-9865ae859c7f/redirect.go:20 +0xa4
net/http.HandlerFunc.ServeHTTP(0xc000dc8300, 0x48b8670, 0xc00a7b77a0, 0xc0057e4400)
	/usr/local/go/src/net/http/server.go:2049 +0x44
net/http.serverHandler.ServeHTTP(0xc000dfaa80, 0x48b8670, 0xc00a7b77a0, 0xc0057e4400)
	/usr/local/go/src/net/http/server.go:2867 +0xa3
net/http.(*conn).serve(0xc008410140, 0x48c6ba0, 0xc00d8d9100)
	/usr/local/go/src/net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2993 +0x39b
```

**Comment by thedadams** [comment]
The panic seems to be related to the error messages:
```
2021/08/10 01:28:30 [ERROR] Failed to handling tunnel request from 10.42.0.0:39108: response 400: cluster not found
2021/08/10 01:28:31 [ERROR] Failed to handling tunnel request from 10.42.1.0:45308: response 400: cluster not found
2021/08/10 01:28:31 [ERROR] Failed to handling tunnel request from 10.42.0.0:33378: response 400: cluster not found
2021/08/10 01:28:33 [ERROR] Failed to handling tunnel request from 10.42.1.0:57972: response 400: cluster not found
2021/08/10 01:28:36 [ERROR] Failed to handling tunnel request from 172.31.11.229:47872: response 400: cluster not found
2021/08/10 01:28:36 [ERROR] Failed to handling tunnel request from 10.42.1.0:44594: response 400: cluster not found
2021/08/10 01:28:37 [ERROR] Failed to handling tunnel request from 10.42.2.0:43608: response 400: cluster not found
2021/08/10 01:28:38 [ERROR] Failed to handling tunnel request from 172.31.2.231:57242: response 400: cluster not found
2021/08/10 01:28:39 [ERROR] Failed to handling tunnel request from 10.42.1.0:57378: response 400: cluster not found
2021/08/10 01:28:40 [ERROR] Failed to handling tunnel request from 172.31.2.231:56494: response 400: cluster not found
2021/08/10 01:28:41 [ERROR] Failed to handling tunnel request from 10.42.0.0:34454: response 400: cluster not found
2021/08/10 01:28:41 [ERROR] Failed to handling tunnel request from 10.42.1.0:45308: response 400: cluster not found
2021/08/10 01:28:43 [ERROR] Failed to handling tunnel request from 10.42.1.0:55750: response 400: cluster not found
2021/08/10 01:28:46 [ERROR] Failed to handling tunnel request from 10.42.2.0:44338: response 400: cluster not found
2021/08/10 01:28:46 [ERROR] Failed to handling tunnel request from 10.42.2.0:43608: response 400: cluster not found
2021/08/10 01:28:47 [ERROR] Failed to handling tunnel request from 10.42.0.0:37826: response 400: cluster not found
2021/08/10 01:28:48 [ERROR] Failed to handling tunnel request from 172.31.11.229:47872: response 400: cluster not found
2021/08/10 01:28:49 [ERROR] Failed to handling tunnel request from 172.31.2.231:59038: response 400: cluster not found
2021/08/10 01:28:50 [ERROR] Failed to handling tunnel request from 10.42.0.0:34634: response 400: cluster not found
2021/08/10 01:28:51 [ERROR] Failed to handling tunnel request from 10.42.0.0:37826: response 400: cluster not found
2021/08/10 01:28:51 [ERROR] Failed to handling tunnel request from 172.31.11.229:48290: response 400: cluster not found
2021/08/10 01:28:53 [ERROR] Failed to handling tunnel request from 172.31.11.229:48296: response 400: cluster not found
2021/08/10 01:28:56 [ERROR] Failed to handling tunnel request from 172.31.4.16:58256: response 400: cluster not found
2021/08/10 01:28:56 [ERROR] Failed to handling tunnel request from 10.42.0.0:36534: response 400: cluster not found
2021/08/10 01:28:57 [ERROR] Failed to handling tunnel request from 172.31.4.16:58444: response 400: cluster not found
2021/08/10 01:28:58 [ERROR] Failed to handling tunnel request from 172.31.2.231:51956: response 400: cluster not found
2021/08/10 01:28:59 [ERROR] Failed to handling tunnel request from 10.42.2.0:46462: response 400: cluster not found
```

**Comment by thedadams** [comment]
I did the following:
1. Deploy cluster with version 1.19.13+k3s1
2. Install cert-manager and rancher version 2.5.3.
3. Deployed two clusters: one DO and one EC2
4. Upgrade Rancher to 2.6.0-rc2

I didn't see any panics the errors I referenced above are not appearing. This is definitely an intermittent issue and may take some time to track down.

**Comment by sowmyav27** [comment]
Closing this as  lines of code in here dont match with the panic in the original issue

**Comment by abelit** [comment]
I came across the same problem,how to solve it? Anybody know?
