### ISSUE TITLE
[v2.5.9] Rancher single-node crashes

### ISSUE THREAD

**Issue by Isitar** [rancher/rancher#34111]
**Rancher Server Setup**
- Rancher version: v2.5.9
- Installation option (Docker install/Helm Chart): Docker install
- Proxy/Cert Details: behind nginx loadbalancer with ssl termination

**Information about the Cluster**
- Kubernetes version: 1.18.3, 1.19 and 1.20 but the clusters are fine
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom, and imported and hosted (azure)

**Describe the bug**
the rancher container crashes during startup, the clusters keep working. 
We had some network issues and the problems started appearing. But we have resolved the networking issues (bad switch) but the rancher server keeps crashing. 

Also the CPU load spikes very high.

**Additional context**
```
2021-08-10 08:24:04.618426 W | etcdserver: read-only range request "key:\"/registry/management.cattle.io/templates/\" range_end:\"/registry/management.cattle.io/templates0\" count_only:true " with result "range_response_count:0 size:11" took too long (178.939558ms) to execute
2021-08-10 08:24:04.619299 W | etcdserver: read-only range request "key:\"/registry/management.cattle.io/rkek8sserviceoptions/\" range_end:\"/registry/management.cattle.io/rkek8sserviceoptions0\" limit:10000 " with result "range_response_count:46 size:125601" took too long (123.253099ms) to execute
2021-08-10 08:24:04.619919 W | etcdserver: read-only range request "key:\"/registry/management.cattle.io/rkek8sserviceoptions/\" range_end:\"/registry/management.cattle.io/rkek8sserviceoptions0\" limit:1 " with result "range_response_count:1 size:2591" took too long (121.764283ms) to execute
2021-08-10 08:24:04.881305 W | etcdserver: read-only range request "key:\"/registry/csidrivers/\" range_end:\"/registry/csidrivers0\" limit:1 " with result "range_response_count:0 size:8" took too long (226.945508ms) to execute
2021-08-10 08:24:04.914756 W | etcdserver: request "header:<ID:14927597882375829105 > txn:<compare:<target:MOD key:\"/registry/events/fleet-system/fleet-controller-6b95d6f87c-mdqgp.1699e460c7a49a06\" mod_revision:0 > success:<request_put:<key:\"/registry/events/fleet-system/fleet-controller-6b95d6f87c-mdqgp.1699e460c7a49a06\" value_size:720 lease:5704225845521052866 >> failure:<>>" with result "size:22" took too long (186.858682ms) to execute
E0810 08:24:04.930107       8 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1637 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3e98060, 0x7819b40)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/runtime/runtime.go:74 +0x92
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/runtime/runtime.go:48 +0x82
panic(0x3e98060, 0x7819b40)
        /usr/local/go/src/runtime/panic.go:969 +0x166
os.(*Process).signal(0x0, 0x51a5240, 0x7730980, 0x0, 0x0)
        /usr/local/go/src/os/exec_unix.go:56 +0x3b
os.(*Process).Signal(...)
        /usr/local/go/src/os/exec.go:131
os.(*Process).kill(...)
        /usr/local/go/src/os/exec_posix.go:66
os.(*Process).Kill(...)
        /usr/local/go/src/os/exec.go:116
github.com/rancher/rancher/pkg/channelserver.Shutdown(0xc00617bd10, 0xc00617bc70)
        /go/src/github.com/rancher/rancher/pkg/channelserver/channelserver.go:101 +0x7f
github.com/rancher/rancher/pkg/controllers/managementapi/k3smetadata.(*handler).sync(0xc00639f900, 0xc00017e6e0, 0x13, 0xc0024ac6e0, 0xc000094380, 0x7f5cdef777d0, 0x0, 0x0)
        /go/src/github.com/rancher/rancher/pkg/controllers/managementapi/k3smetadata/settings_handler.go:80 +0x3b4
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*settingController).AddHandler.func1(0xc00017e6e0, 0x13, 0x4706d00, 0xc0024ac6e0, 0xc001e06b00, 0x3, 0x3, 0x0)
        /go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_setting_controller.go:155 +0x63
github.com/rancher/norman/controller.(*genericController).AddHandler.func1(0xc00017e6e0, 0x13, 0x518ff00, 0xc0024ac6e0, 0xc0024abf01, 0xc001e06bb0, 0x403c10, 0xc003c1d2f0)
        /go/pkg/mod/github.com/rancher/norman@v0.0.0-20210225010917-c7fd1e24145b/controller/generic_controller.go:62 +0x221
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc006481380, 0xc00017e6e0, 0x13, 0x518ff00, 0xc0024ac6e0, 0x4134cb, 0xc001e06c40, 0x5922b4bb, 0xd7cfd5a7053a9eee)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000ef0420, 0xc00017e6e0, 0x13, 0x518ff00, 0xc0024ac6e0, 0x1, 0x0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/sharedhandler.go:66 +0x150
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000964420, 0xc00017e6e0, 0x13, 0xc001301ec0, 0xc001e06d50)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/controller.go:213 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000964420, 0x3b652a0, 0xc003c1d300, 0x0, 0x0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/controller.go:195 +0xd7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000964420, 0x203001)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/controller.go:172 +0x51
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc000964420)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/controller.go:161 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc001b48370)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001b48370, 0x5162a60, 0xc001301fb0, 0x1, 0xc00138a5a0)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001b48370, 0x3b9aca00, 0x0, 0x1, 0xc00138a5a0)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc001b48370, 0x3b9aca00, 0xc00138a5a0)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/controller.go:132 +0x31f
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/runtime/runtime.go:74 +0x92
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/runtime/runtime.go:48 +0x82
panic(0x3e98060, 0x7819b40)
        /usr/local/go/src/runtime/panic.go:969 +0x166
os.(*Process).signal(0x0, 0x51a5240, 0x7730980, 0x0, 0x0)
        /usr/local/go/src/os/exec_unix.go:56 +0x3b
os.(*Process).Signal(...)
        /usr/local/go/src/os/exec.go:131
os.(*Process).kill(...)
        /usr/local/go/src/os/exec_posix.go:66
os.(*Process).Kill(...)
        /usr/local/go/src/os/exec.go:116
github.com/rancher/rancher/pkg/channelserver.Shutdown(0xc00617bd10, 0xc00617bc70)
        /go/src/github.com/rancher/rancher/pkg/channelserver/channelserver.go:101 +0x7f
github.com/rancher/rancher/pkg/controllers/managementapi/k3smetadata.(*handler).sync(0xc00639f900, 0xc00017e6e0, 0x13, 0xc0024ac6e0, 0xc000094380, 0x7f5cdef777d0, 0x0, 0x0)
        /go/src/github.com/rancher/rancher/pkg/controllers/managementapi/k3smetadata/settings_handler.go:80 +0x3b4
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*settingController).AddHandler.func1(0xc00017e6e0, 0x13, 0x4706d00, 0xc0024ac6e0, 0xc001e06b00, 0x3, 0x3, 0x0)
        /go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_setting_controller.go:155 +0x63
github.com/rancher/norman/controller.(*genericController).AddHandler.func1(0xc00017e6e0, 0x13, 0x518ff00, 0xc0024ac6e0, 0xc0024abf01, 0xc001e06bb0, 0x403c10, 0xc003c1d2f0)
        /go/pkg/mod/github.com/rancher/norman@v0.0.0-20210225010917-c7fd1e24145b/controller/generic_controller.go:62 +0x221
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc006481380, 0xc00017e6e0, 0x13, 0x518ff00, 0xc0024ac6e0, 0x4134cb, 0xc001e06c40, 0x5922b4bb, 0xd7cfd5a7053a9eee)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000ef0420, 0xc00017e6e0, 0x13, 0x518ff00, 0xc0024ac6e0, 0x1, 0x0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/sharedhandler.go:66 +0x150
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000964420, 0xc00017e6e0, 0x13, 0xc001301ec0, 0xc001e06d50)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/controller.go:213 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000964420, 0x3b652a0, 0xc003c1d300, 0x0, 0x0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/controller.go:195 +0xd7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000964420, 0x203001)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/controller.go:172 +0x51
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc000964420)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/controller.go:161 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc001b48370)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001b48370, 0x5162a60, 0xc001301fb0, 0x1, 0xc00138a5a0)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001b48370, 0x3b9aca00, 0x0, 0x1, 0xc00138a5a0)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc001b48370, 0x3b9aca00, 0xc00138a5a0)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/controller.go:132 +0x31f
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4e0d1b]

goroutine 1637 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/runtime/runtime.go:55 +0x105
panic(0x3e98060, 0x7819b40)
        /usr/local/go/src/runtime/panic.go:969 +0x166
os.(*Process).signal(0x0, 0x51a5240, 0x7730980, 0x0, 0x0)
        /usr/local/go/src/os/exec_unix.go:56 +0x3b
os.(*Process).Signal(...)
        /usr/local/go/src/os/exec.go:131
os.(*Process).kill(...)
        /usr/local/go/src/os/exec_posix.go:66
os.(*Process).Kill(...)
        /usr/local/go/src/os/exec.go:116
github.com/rancher/rancher/pkg/channelserver.Shutdown(0xc00617bd10, 0xc00617bc70)
        /go/src/github.com/rancher/rancher/pkg/channelserver/channelserver.go:101 +0x7f
github.com/rancher/rancher/pkg/controllers/managementapi/k3smetadata.(*handler).sync(0xc00639f900, 0xc00017e6e0, 0x13, 0xc0024ac6e0, 0xc000094380, 0x7f5cdef777d0, 0x0, 0x0)
        /go/src/github.com/rancher/rancher/pkg/controllers/managementapi/k3smetadata/settings_handler.go:80 +0x3b4
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*settingController).AddHandler.func1(0xc00017e6e0, 0x13, 0x4706d00, 0xc0024ac6e0, 0xc001e06b00, 0x3, 0x3, 0x0)
        /go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_setting_controller.go:155 +0x63
github.com/rancher/norman/controller.(*genericController).AddHandler.func1(0xc00017e6e0, 0x13, 0x518ff00, 0xc0024ac6e0, 0xc0024abf01, 0xc001e06bb0, 0x403c10, 0xc003c1d2f0)
        /go/pkg/mod/github.com/rancher/norman@v0.0.0-20210225010917-c7fd1e24145b/controller/generic_controller.go:62 +0x221
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc006481380, 0xc00017e6e0, 0x13, 0x518ff00, 0xc0024ac6e0, 0x4134cb, 0xc001e06c40, 0x5922b4bb, 0xd7cfd5a7053a9eee)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000ef0420, 0xc00017e6e0, 0x13, 0x518ff00, 0xc0024ac6e0, 0x1, 0x0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/sharedhandler.go:66 +0x150
github.com/rancher/norman/controller.(*genericController).AddHandler.func1(0xc00017e6e0, 0x13, 0x518ff00, 0xc0024ac6e0, 0xc0024abf01, 0xc001e06bb0, 0x403c10, 0xc003c1d2f0)
        /go/pkg/mod/github.com/rancher/norman@v0.0.0-20210225010917-c7fd1e24145b/controller/generic_controller.go:62 +0x221
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc006481380, 0xc00017e6e0, 0x13, 0x518ff00, 0xc0024ac6e0, 0x4134cb, 0xc001e06c40, 0x5922b4bb, 0xd7cfd5a7053a9eee)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000ef0420, 0xc00017e6e0, 0x13, 0x518ff00, 0xc0024ac6e0, 0x1, 0x0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/sharedhandler.go:66 +0x150
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000964420, 0xc00017e6e0, 0x13, 0xc001301ec0, 0xc001e06d50)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/controller.go:213 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000964420, 0x3b652a0, 0xc003c1d300, 0x0, 0x0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/controller.go:195 +0xd7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000964420, 0x203001)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/controller.go:172 +0x51
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc000964420)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/controller.go:161 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc001b48370)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001b48370, 0x5162a60, 0xc001301fb0, 0x1, 0xc00138a5a0)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001b48370, 0x3b9aca00, 0x0, 0x1, 0xc00138a5a0)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc001b48370, 0x3b9aca00, 0xc00138a5a0)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/controller.go:132 +0x31f
```

**Comment by ikogan** [comment]
I'm seeing this as well although it does recover. This seems to happen, I think, when the Rancher VM's storage is even the tiniest bit slow. This morning one of the hypervisor nodes fell over causing a lot of backfilling on the Ceph RBD pool that backs the VM's disk and Rancher started crashing.

When I was doing hypervisor OS upgrades, every time I would reboot a node, Rancher would crash, regardless which node it was on at the time.

**Comment by Isitar** [comment]
your hint was in the correct direction, our storage had bad performance, once we fixed it, the crashes went away

**Comment by moschlar** [comment]
But *should* it really be the case, that having temporarily slow I/O leads to actual crashes of the whole thing? :thinking:
