### ISSUE TITLE
Cluster goes into Error state intermittently on an upgrade of Rancher server

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#34267]
**Rancher Server Setup**
- Rancher version: Upgrade from 2.5.9 to 2.6.0-rc3
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Info:
         Cluster Type (RKE1, RKE2, k3s, EKS, etc): RKE1
         Node Setup: 3 nodes all roles
         Version: 1.20.9
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.20.9`
- Cluster Type (Local/Downstream): Custom - 1 etcd/control - t3.medium AWS and 4 t3.xlarge Worker nodes

**Describe the bug**

**To Reproduce**
**Note:**
This issue was seen after these steps were

- Deploy a 2.5.9 HA
- Deploy a downstream cluster
- Deploy all v2 charts on the cluster
- Upgrade rancher to 2.6.0-rc3
- Cluster keeps going into Error state intermittently
- Cattle cluster agent keeps restarting:
```
E0816 21:40:09.022894      55 gvks.go:69] failed to sync schemas: unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
time="2021-08-16T21:40:11Z" level=error msg="Failed to read API for groups map[custom.metrics.k8s.io/v1beta1:the server is currently unable to handle the request]"
E0816 21:40:11.103244      55 gvks.go:69] failed to sync schemas: unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0816 21:40:46.599317      55 leaderelection.go:325] error retrieving resource lock kube-system/cattle-controllers: Get "https://10.43.0.1:443/api/v1/namespaces/kube-system/configmaps/cattle-controllers?timeout=15m0s": context deadline exceeded
I0816 21:40:46.606352      55 leaderelection.go:278] failed to renew lease kube-system/cattle-controllers: timed out waiting for the condition
E0816 21:40:47.120964      55 leaderelection.go:301] Failed to release lock: resource name may not be empty
time="2021-08-16T21:40:47Z" level=fatal msg="leaderelection lost for cattle-controllers"
```
- cattle-cluster-agent logs: 
```
time="2021-08-16T21:31:04Z" level=info msg="Listening on :444"
time="2021-08-16T21:31:04Z" level=info msg="Updating TLS secret for serving-cert (count: 4): map[listener.cattle.io/cn-10.42.0.10:10.42.0.10 listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-localhost:localhost listener.cattle.io/cn-rancher.cattle-system:rancher.cattle-system listener.cattle.io/fingerprint:SHA1=<>]"
time="2021-08-16T21:31:04Z" level=info msg="Active TLS secret serving-cert (ver=84892) (count 4): map[listener.cattle.io/cn-10.42.0.10:10.42.0.10 listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-localhost:localhost listener.cattle.io/cn-rancher.cattle-system:rancher.cattle-system listener.cattle.io/fingerprint:SHA1=<>]"
E0816 21:31:05.249174      56 gvks.go:69] failed to sync schemas: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0816 21:31:06.090586      56 memcache.go:196] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
time="2021-08-16T21:31:06Z" level=error msg="Failed to read API for groups map[metrics.k8s.io/v1beta1:the server is currently unable to handle the request]"
E0816 21:31:06.146578      56 memcache.go:101] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
time="2021-08-16T21:31:06Z" level=info msg="Starting /v1, Kind=Secret controller"
2021/08/16 21:31:06 http: panic serving pipe: runtime error: invalid memory address or nil pointer dereference
goroutine 5188 [running]:
net/http.(*conn).serve.func1(0xc0083c4780)
  /usr/local/go/src/net/http/server.go:1804 +0x153
panic(0x3997540, 0x68f02e0)
  /usr/local/go/src/runtime/panic.go:971 +0x499
github.com/rancher/apiserver/pkg/server.(*SchemaBasedAccess).CanAction(0x69972e0, 0xc008194d20, 0x0, 0xc00b5ff827, 0x9, 0x0, 0x0)
  /go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20210810230850-96c000dcb0b4/pkg/server/access.go:76 +0x29
github.com/rancher/apiserver/pkg/server.ValidateAction(0xc008194d20, 0x0, 0x0, 0x39410c0)
  /go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20210810230850-96c000dcb0b4/pkg/server/validate.go:26 +0xb6
github.com/rancher/apiserver/pkg/server.(*Server).handleOp(0xc0044cef00, 0xc008194d20, 0xc00832ec80, 0x4, 0xc0014c8e08, 0x0, 0x203002)
  /go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20210810230850-96c000dcb0b4/pkg/server/server.go:148 +0x6c
github.com/rancher/apiserver/pkg/server.(*Server).handle(0xc0044cef00, 0xc008194d20, 0x43757d0)
  /go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20210810230850-96c000dcb0b4/pkg/server/server.go:132 +0x2a5
github.com/rancher/apiserver/pkg/server.(*Server).Handle(...)
  /go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20210810230850-96c000dcb0b4/pkg/server/server.go:92
github.com/rancher/steve/pkg/server/handler.(*apiServer).apiHandler.func1(0x48aab70, 0xc00b6d4180, 0xc00bb4b300)
  /go/pkg/mod/github.com/rancher/steve@v0.0.0-20210810230939-e9222c6ccffa/pkg/server/handler/apiserver.go:98 +0x90
net/http.HandlerFunc.ServeHTTP(0xc001375110, 0x48aab70, 0xc00b6d4180, 0xc00bb4b300)
  /usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/steve/pkg/auth.ToMiddleware.func1.1(0x48aab70, 0xc00b6d4180, 0xc00bb4b200)
  /go/pkg/mod/github.com/rancher/steve@v0.0.0-20210810230939-e9222c6ccffa/pkg/auth/filter.go:167 +0x1c7
net/http.HandlerFunc.ServeHTTP(0xc0044cf080, 0x48aab70, 0xc00b6d4180, 0xc00bb4b200)
  /usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/apiserver/pkg/urlbuilder.RedirectRewrite.func1(0x48b9ba0, 0xc000218a80, 0xc00bb4b200)
  /go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20210810230850-96c000dcb0b4/pkg/urlbuilder/redirect.go:24 +0x148
net/http.HandlerFunc.ServeHTTP(0xc008517938, 0x48b9ba0, 0xc000218a80, 0xc00bb4b200)
  /usr/local/go/src/net/http/server.go:2049 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00417d740, 0x48b9ba0, 0xc000218a80, 0xc00bb4b000)
  /go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rancher/rancher/pkg/auth/requests.authedFilter.ServeHTTP(0x4852620, 0xc0038b32b0, 0x4159800, 0x4, 0xc00450ba00, 0x1, 0x1, 0x48b9ba0, 0xc000218a80, 0xc00bb4b000)
  /go/src/github.com/rancher/rancher/pkg/auth/requests/filter.go:105 +0x1b5
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00417d8c0, 0x48b9ba0, 0xc000218a80, 0xc00bb4ae00)
  /go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00417d980, 0x48b9ba0, 0xc000218a80, 0xc00bb4ac00)
  /go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00417c900, 0x48b9ba0, 0xc000218a80, 0xc00bb4aa00)
  /go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00417cc00, 0x48b9ba0, 0xc000218a80, 0xc00bb4a700)
  /go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rancher/rancher/pkg/multiclustermanager.(*DeferredServer).Middleware.func1(0x48b9ba0, 0xc000218a80, 0xc00bb4a700)
  /go/src/github.com/rancher/rancher/pkg/multiclustermanager/deferred.go:110 +0xd9
net/http.HandlerFunc.ServeHTTP(0xc000cd3380, 0x48b9ba0, 0xc000218a80, 0xc00bb4a700)
  /usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/rancher/pkg/api/steve/aggregation.(*aggregationHandler).Middleware.func1(0x48b9ba0, 0xc000218a80, 0xc00bb4a700)
  /go/src/github.com/rancher/rancher/pkg/api/steve/aggregation/aggregation.go:52 +0x6e
net/http.HandlerFunc.ServeHTTP(0xc000cd33a0, 0x48b9ba0, 0xc000218a80, 0xc00bb4a700)
  /usr/local/go/src/net/http/server.go:2049 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00417d800, 0x48b9ba0, 0xc000218a80, 0xc00bb4a400)
  /go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rancher/rancher/pkg/api/steve/proxy.NewProxyMiddleware.func1.1(0x48b9ba0, 0xc000218a80, 0xc00bb4a400)
  /go/src/github.com/rancher/rancher/pkg/api/steve/proxy/proxy.go:75 +0x65
net/http.HandlerFunc.ServeHTTP(0xc000cd33c0, 0x48b9ba0, 0xc000218a80, 0xc00bb4a400)
  /usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/rancher/pkg/api/steve/proxy.RewriteLocalCluster.func1(0x48b9ba0, 0xc000218a80, 0xc00bb4a400)
  /go/src/github.com/rancher/rancher/pkg/api/steve/proxy/proxy.go:42 +0xf2
net/http.HandlerFunc.ServeHTTP(0xc001375410, 0x48b9ba0, 0xc000218a80, 0xc00bb4a400)
  /usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/rancher/pkg/websocket.websocketHandler.ServeHTTP(0x485a540, 0xc001375410, 0x48b9ba0, 0xc000218a80, 0xc00bb4a400)
  /go/src/github.com/rancher/rancher/pkg/websocket/handler.go:35 +0xa2
github.com/rancher/apiserver/pkg/middleware.ContentTypeOptions.func1(0x48b9ba0, 0xc000218a80, 0xc00bb4a400)
  /go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20210810230850-96c000dcb0b4/pkg/middleware/cache.go:47 +0x131
net/http.HandlerFunc.ServeHTTP(0xc001375428, 0x48b9ba0, 0xc000218a80, 0xc00bb4a400)
  /usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/rancher/pkg/auth.SetXAPICattleAuthHeader.func1(0x48b9ba0, 0xc000218a80, 0xc00bb4a400)
  /go/src/github.com/rancher/rancher/pkg/auth/server.go:180 +0x2ac
net/http.HandlerFunc.ServeHTTP(0xc001375440, 0x48b9ba0, 0xc000218a80, 0xc00bb4a400)
  /usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/steve/pkg/auth.ToMiddleware.func1.1(0x48b9ba0, 0xc000218a80, 0xc00bb4a100)
  /go/pkg/mod/github.com/rancher/steve@v0.0.0-20210810230939-e9222c6ccffa/pkg/auth/filter.go:167 +0x1c7
net/http.HandlerFunc.ServeHTTP(0xc004e6c270, 0x48b9ba0, 0xc000218a80, 0xc00bb4a100)
  /usr/local/go/src/net/http/server.go:2049 +0x44
net/http.serverHandler.ServeHTTP(0xc0013e15e0, 0x48b9ba0, 0xc000218a80, 0xc00bb4a100)
  /usr/local/go/src/net/http/server.go:2867 +0xa3
net/http.(*conn).serve(0xc0083c4780, 0x48c7de0, 0xc00b674a00)
  /usr/local/go/src/net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
  /usr/local/go/src/net/http/server.go:2993 +0x39b
2021/08/16 21:31:06 http: panic serving pipe: runtime error: invalid memory address or nil pointer dereference
goroutine 5210 [running]:
net/http.(*conn).serve.func1(0xc008229cc0)
  /usr/local/go/src/net/http/server.go:1804 +0x153
panic(0x3997540, 0x68f02e0)
  /usr/local/go/src/runtime/panic.go:971 +0x499
github.com/rancher/apiserver/pkg/server.(*SchemaBasedAccess).CanAction(0x69972e0, 0xc0082e3590, 0x0, 0xc00890d477, 0x9, 0x0, 0x0)
  /go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20210810230850-96c000dcb0b4/pkg/server/access.go:76 +0x29
github.com/rancher/apiserver/pkg/server.ValidateAction(0xc0082e3590, 0x0, 0x0, 0x39410c0)
  /go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20210810230850-96c000dcb0b4/pkg/server/validate.go:26 +0xb6
github.com/rancher/apiserver/pkg/server.(*Server).handleOp(0xc0044cef00, 0xc0082e3590, 0xc0081c0c80, 0x4, 0xc0014c8e08, 0x0, 0x203002)
  /go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20210810230850-96c000dcb0b4/pkg/server/server.go:148 +0x6c
github.com/rancher/apiserver/pkg/server.(*Server).handle(0xc0044cef00, 0xc0082e3590, 0x43757d0)
  /go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20210810230850-96c000dcb0b4/pkg/server/server.go:132 +0x2a5
github.com/rancher/apiserver/pkg/server.(*Server).Handle(...)
  /go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20210810230850-96c000dcb0b4/pkg/server/server.go:92
github.com/rancher/steve/pkg/server/handler.(*apiServer).apiHandler.func1(0x48aab70, 0xc008346c00, 0xc00bafac00)
  /go/pkg/mod/github.com/rancher/steve@v0.0.0-20210810230939-e9222c6ccffa/pkg/server/handler/apiserver.go:98 +0x90
net/http.HandlerFunc.ServeHTTP(0xc001375110, 0x48aab70, 0xc008346c00, 0xc00bafac00)
  /usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/steve/pkg/auth.ToMiddleware.func1.1(0x48aab70, 0xc008346c00, 0xc00bafab00)
  /go/pkg/mod/github.com/rancher/steve@v0.0.0-20210810230939-e9222c6ccffa/pkg/auth/filter.go:167 +0x1c7
net/http.HandlerFunc.ServeHTTP(0xc0044cf080, 0x48aab70, 0xc008346c00, 0xc00bafab00)
  /usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/apiserver/pkg/urlbuilder.RedirectRewrite.func1(0x48b9ba0, 0xc0013e0d20, 0xc00bafab00)
  /go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20210810230850-96c000dcb0b4/pkg/urlbuilder/redirect.go:24 +0x148
net/http.HandlerFunc.ServeHTTP(0xc008d2eca8, 0x48b9ba0, 0xc0013e0d20, 0xc00bafab00)
  /usr/local/go/src/net/http/server.go:2049 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00417d740, 0x48b9ba0, 0xc0013e0d20, 0xc00bafa900)
  /go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rancher/rancher/pkg/auth/requests.authedFilter.ServeHTTP(0x4852620, 0xc0038b32b0, 0x4159800, 0x4, 0xc00450ba00, 0x1, 0x1, 0x48b9ba0, 0xc0013e0d20, 0xc00bafa900)
  /go/src/github.com/rancher/rancher/pkg/auth/requests/filter.go:105 +0x1b5
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00417d8c0, 0x48b9ba0, 0xc0013e0d20, 0xc00bafa700)
  /go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00417d980, 0x48b9ba0, 0xc0013e0d20, 0xc00bafa500)
  /go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00417c900, 0x48b9ba0, 0xc0013e0d20, 0xc00bafa300)
  /go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00417cc00, 0x48b9ba0, 0xc0013e0d20, 0xc00bafa100)
  /go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rancher/rancher/pkg/multiclustermanager.(*DeferredServer).Middleware.func1(0x48b9ba0, 0xc0013e0d20, 0xc00bafa100)
  /go/src/github.com/rancher/rancher/pkg/multiclustermanager/deferred.go:110 +0xd9
net/http.HandlerFunc.ServeHTTP(0xc000cd3380, 0x48b9ba0, 0xc0013e0d20, 0xc00bafa100)
  /usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/rancher/pkg/api/steve/aggregation.(*aggregationHandler).Middleware.func1(0x48b9ba0, 0xc0013e0d20, 0xc00bafa100)
  /go/src/github.com/rancher/rancher/pkg/api/steve/aggregation/aggregation.go:52 +0x6e
net/http.HandlerFunc.ServeHTTP(0xc000cd33a0, 0x48b9ba0, 0xc0013e0d20, 0xc00bafa100)
  /usr/local/go/src/net/http/server.go:2049 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00417d800, 0x48b9ba0, 0xc0013e0d20, 0xc008325f00)
  /go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rancher/rancher/pkg/api/steve/proxy.NewProxyMiddleware.func1.1(0x48b9ba0, 0xc0013e0d20, 0xc008325f00)
  /go/src/github.com/rancher/rancher/pkg/api/steve/proxy/proxy.go:75 +0x65
net/http.HandlerFunc.ServeHTTP(0xc000cd33c0, 0x48b9ba0, 0xc0013e0d20, 0xc008325f00)
  /usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/rancher/pkg/api/steve/proxy.RewriteLocalCluster.func1(0x48b9ba0, 0xc0013e0d20, 0xc008325f00)
  /go/src/github.com/rancher/rancher/pkg/api/steve/proxy/proxy.go:42 +0xf2
net/http.HandlerFunc.ServeHTTP(0xc001375410, 0x48b9ba0, 0xc0013e0d20, 0xc008325f00)
  /usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/rancher/pkg/websocket.websocketHandler.ServeHTTP(0x485a540, 0xc001375410, 0x48b9ba0, 0xc0013e0d20, 0xc008325f00)
  /go/src/github.com/rancher/rancher/pkg/websocket/handler.go:35 +0xa2
github.com/rancher/apiserver/pkg/middleware.ContentTypeOptions.func1(0x48b9ba0, 0xc0013e0d20, 0xc008325f00)
  /go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20210810230850-96c000dcb0b4/pkg/middleware/cache.go:47 +0x131
net/http.HandlerFunc.ServeHTTP(0xc001375428, 0x48b9ba0, 0xc0013e0d20, 0xc008325f00)
  /usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/rancher/pkg/auth.SetXAPICattleAuthHeader.func1(0x48b9ba0, 0xc0013e0d20, 0xc008325f00)
  /go/src/github.com/rancher/rancher/pkg/auth/server.go:180 +0x2ac
net/http.HandlerFunc.ServeHTTP(0xc001375440, 0x48b9ba0, 0xc0013e0d20, 0xc008325f00)
  /usr/local/go/src/net/http/server.go:2049 +0x44
github.com/rancher/steve/pkg/auth.ToMiddleware.func1.1(0x48b9ba0, 0xc0013e0d20, 0xc008325e00)
  /go/pkg/mod/github.com/rancher/steve@v0.0.0-20210810230939-e9222c6ccffa/pkg/auth/filter.go:167 +0x1c7
net/http.HandlerFunc.ServeHTTP(0xc004e6c270, 0x48b9ba0, 0xc0013e0d20, 0xc008325e00)
  /usr/local/go/src/net/http/server.go:2049 +0x44
net/http.serverHandler.ServeHTTP(0xc0013e15e0, 0x48b9ba0, 0xc0013e0d20, 0xc008325e00)
  /usr/local/go/src/net/http/server.go:2867 +0xa3
net/http.(*conn).serve(0xc008229cc0, 0x48c7de0, 0xc00835e800)
  /usr/local/go/src/net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
  /usr/local/go/src/net/http/server.go:2993 +0x39b
time="2021-08-16T21:31:08Z" level=info msg="Watching metadata for acme.cert-manager.io/v1, Kind=Order"
time="2021-08-16T21:31:08Z" level=info msg="Watching metadata for networking.istio.io/v1beta1, Kind=Gateway"
```

**Other info:**
Some charts were upgraded on this setup like CIS/Loggingv2/OPA.

**Comment by sowmyav27** [comment]
**On an upgrade form 2.5.9 to 2.6-head commit id: `8898bf8`**

- Deploy a custom cluster
- enable monitoring v2, istio v2 and CIS v2 charts on the downstream cluster
- enable rancher backups on the local cluster
- Upgrade to 2.6-head
- System project workloads are good. 
- No restarts observed in cattle cluster agent of downstream cluster.
- Cluster is in Active state
