### ISSUE TITLE
Can't start rancher server for some reason - can't write to /tmp/

### ISSUE THREAD

**Issue by utrack** [rancher/rancher#3443]
Hi! I'm experiencing errors when starting a server.
I've got one-host setup (one server), running Ubuntu 14.04 Server. Rancher's version is 0.56.1.

```
15:17:05.205 [main] ERROR ConsoleStatus - Startup Failed [3964ms]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase-core' defined in URL [jar:file:/usr/share/cattle/8aeb028d5581b0d10de837b96653e04c/WEB-INF/lib/cattle-app-config-0.5.0-SNAPSHOT.jar!/META-INF/cattle/system/spring-db-loader-context.xml]: Invocation of init method failed; nested exception is liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: java.sql.SQLException: Can't create/write to file '/tmp/#sql_1_0.MYI' (Errcode: 13)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1512) ~[spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458) ~[spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:296) ~[spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223) ~[spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:293) ~[spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) ~[spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:628) ~[spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932) ~[spring-context-3.2.4.RELEASE.jar:3.2.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479) ~[spring-context-3.2.4.RELEASE.jar:3.2.4.RELEASE]
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.loadContext(DefaultModuleDefinitionSet.java:184) ~[cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet$2.with(DefaultModuleDefinitionSet.java:157) ~[cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:348) ~[cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:358) ~[cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:333) ~[cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.loadContexts(DefaultModuleDefinitionSet.java:152) ~[cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.load(DefaultModuleDefinitionSet.java:97) ~[cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.factory.ModuleBasedContextFactory.loadModules(ModuleBasedContextFactory.java:37) ~[cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.init(CloudStackSpringContext.java:75) ~[cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.<init>(CloudStackSpringContext.java:56) ~[cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.context.SpringContext.<init>(SpringContext.java:11) ~[cattle-iaas-system-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.context.WebContextLoaderListener.constructCloudStackSpringContext(WebContextLoaderListener.java:15) ~[cattle-iaas-system-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.web.CloudStackContextLoaderListener.contextInitialized(CloudStackContextLoaderListener.java:51) ~[cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800) ~[jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444) ~[jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791) ~[jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294) ~[jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349) ~[jetty-webapp-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342) ~[jetty-webapp-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741) ~[jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505) ~[jetty-webapp-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) ~[jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.Server.start(Server.java:387) ~[jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) ~[jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) ~[jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.Server.doStart(Server.java:354) ~[jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
        at io.cattle.platform.launcher.jetty.Main.main(Main.java:145) ~[8aeb028d5581b0d10de837b96653e04c/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_91]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_91]
        at io.cattle.platform.launcher.Main.run(Main.java:188) [8aeb028d5581b0d10de837b96653e04c/:na]
        at io.cattle.platform.launcher.Main.main(Main.java:251) [8aeb028d5581b0d10de837b96653e04c/:na]
Caused by: liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: java.sql.SQLException: Can't create/write to file '/tmp/#sql_1_0.MYI' (Errcode: 13)
        at liquibase.changelog.StandardChangeLogHistoryService.init(StandardChangeLogHistoryService.java:81) ~[liquibase-core-3.1.0.jar:na]
        at liquibase.Liquibase.checkLiquibaseTables(Liquibase.java:725) ~[liquibase-core-3.1.0.jar:na]
        at liquibase.Liquibase.update(Liquibase.java:196) ~[liquibase-core-3.1.0.jar:na]
        at liquibase.Liquibase.update(Liquibase.java:181) ~[liquibase-core-3.1.0.jar:na]
        at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:342) ~[liquibase-core-3.1.0.jar:na]
        at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:299) ~[liquibase-core-3.1.0.jar:na]
        at io.cattle.platform.liquibase.Loader.afterPropertiesSet(Loader.java:56) ~[cattle-framework-db-loader-0.5.0-SNAPSHOT.jar:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1571) ~[spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1509) ~[spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        ... 44 common frames omitted
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: java.sql.SQLException: Can't create/write to file '/tmp/#sql_1_0.MYI' (Errcode: 13)
        at liquibase.snapshot.jvm.ColumnSnapshotGenerator.addTo(ColumnSnapshotGenerator.java:82) ~[liquibase-core-3.1.0.jar:na]
        at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:72) ~[liquibase-core-3.1.0.jar:na]
        at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:47) ~[liquibase-core-3.1.0.jar:na]
        at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:131) ~[liquibase-core-3.1.0.jar:na]
        at liquibase.snapshot.DatabaseSnapshot.<init>(DatabaseSnapshot.java:36) ~[liquibase-core-3.1.0.jar:na]
        at liquibase.snapshot.JdbcDatabaseSnapshot.<init>(JdbcDatabaseSnapshot.java:23) ~[liquibase-core-3.1.0.jar:na]
        at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:129) ~[liquibase-core-3.1.0.jar:na]
        at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:137) ~[liquibase-core-3.1.0.jar:na]
        at liquibase.snapshot.SnapshotGeneratorFactory.getDatabaseChangeLogTable(SnapshotGeneratorFactory.java:144) ~[liquibase-core-3.1.0.jar:na]
        at liquibase.changelog.StandardChangeLogHistoryService.init(StandardChangeLogHistoryService.java:79) ~[liquibase-core-3.1.0.jar:na]
        ... 52 common frames omitted
Caused by: liquibase.exception.DatabaseException: java.sql.SQLException: Can't create/write to file '/tmp/#sql_1_0.MYI' (Errcode: 13)
        at liquibase.snapshot.ResultSetCache.get(ResultSetCache.java:73) ~[liquibase-core-3.1.0.jar:na]
        at liquibase.snapshot.JdbcDatabaseSnapshot$CachingDatabaseMetaData.getColumns(JdbcDatabaseSnapshot.java:187) ~[liquibase-core-3.1.0.jar:na]
        at liquibase.snapshot.jvm.ColumnSnapshotGenerator.addTo(ColumnSnapshotGenerator.java:75) ~[liquibase-core-3.1.0.jar:na]
        ... 61 common frames omitted
Caused by: java.sql.SQLException: Can't create/write to file '/tmp/#sql_1_0.MYI' (Errcode: 13)
        at org.mariadb.jdbc.internal.SQLExceptionMapper.get(SQLExceptionMapper.java:149) ~[mariadb-java-client-1.1.7.jar:na]
        at org.mariadb.jdbc.internal.SQLExceptionMapper.throwException(SQLExceptionMapper.java:106) ~[mariadb-java-client-1.1.7.jar:na]
        at org.mariadb.jdbc.MySQLStatement.executeQueryEpilog(MySQLStatement.java:264) ~[mariadb-java-client-1.1.7.jar:na]
        at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:288) ~[mariadb-java-client-1.1.7.jar:na]
        at org.mariadb.jdbc.MySQLStatement.executeQuery(MySQLStatement.java:302) ~[mariadb-java-client-1.1.7.jar:na]
        at org.mariadb.jdbc.MySQLStatement.executeQuery(MySQLStatement.java:361) ~[mariadb-java-client-1.1.7.jar:na]
        at org.mariadb.jdbc.MySQLDatabaseMetaData.executeQuery(MySQLDatabaseMetaData.java:122) ~[mariadb-java-client-1.1.7.jar:na]
        at org.mariadb.jdbc.MySQLDatabaseMetaData.getColumns(MySQLDatabaseMetaData.java:275) ~[mariadb-java-client-1.1.7.jar:na]
        at org.apache.commons.dbcp.DelegatingDatabaseMetaData.getColumns(DelegatingDatabaseMetaData.java:218) ~[commons-dbcp-1.4.jar:1.4]
        at liquibase.snapshot.JdbcDatabaseSnapshot$CachingDatabaseMetaData$3.fastFetchQuery(JdbcDatabaseSnapshot.java:222) ~[liquibase-core-3.1.0.jar:na]
        at liquibase.snapshot.ResultSetCache$SingleResultSetExtractor.fastFetch(ResultSetCache.java:250) ~[liquibase-core-3.1.0.jar:na]
        at liquibase.snapshot.ResultSetCache.get(ResultSetCache.java:51) ~[liquibase-core-3.1.0.jar:na]
        ... 63 common frames omitted
Caused by: org.mariadb.jdbc.internal.common.QueryException: Can't create/write to file '/tmp/#sql_1_0.MYI' (Errcode: 13)
        at org.mariadb.jdbc.internal.mysql.MySQLProtocol.getResult(MySQLProtocol.java:942) ~[mariadb-java-client-1.1.7.jar:na]
        at org.mariadb.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:991) ~[mariadb-java-client-1.1.7.jar:na]
        at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:281) ~[mariadb-java-client-1.1.7.jar:na]
        ... 71 common frames omitted
STARTUP FAILED [3968] ms
```

**Comment by deniseschannon** [comment]
Is this an upgraded setup or fresh install?

**Comment by utrack** [comment]
@deniseschannon nope, clean reinstall. DB is from 0.50.1, however the server can't even connect to it, so that's not a problem.

**Comment by deniseschannon** [comment]
Can you share your results of `docker ps` and the command you used to start?

**Comment by utrack** [comment]
@deniseschannon Sure
Command:
```
» docker run -d --restart=always -p 8080:8080 \
-e CATTLE_DB_CATTLE_MYSQL_HOST=192.168.10.5 \
-e CATTLE_DB_CATTLE_MYSQL_PORT=3307 \
-e CATTLE_DB_CATTLE_MYSQL_NAME=cattle \
-e CATTLE_DB_CATTLE_USERNAME=cattle \
-e CATTLE_DB_CATTLE_PASSWORD=<password> \
--name rancher_shepherd rancher/server:v0.56.1
```

Nothing too specific, not sure what to make of it. I can't `exec` anything inside the container (possibly because it's in the constant loop):
```
» docker exec -it rancher_shepherd bash                                                                                                                                                                       u@tacobell | 2016-02-04 14:53:45
Cannot run exec command c6430cd1415e6eb7ddbeb05c723a666703bfa7fcb2c592c74217dc46c2a8ab78 in container 934ccc54b74036f23027ea18ecd03302d69105ad28d334ce8349c748582a6dd3: [8] System error: exit status 1
                                                                                                                                                                                                       Error starting exec command in container c6430cd1415e6eb7ddbeb05c723a666703bfa7fcb2c592c74217dc46c2a8ab78: Cannot run exec command c6430cd1415e6eb7ddbeb05c723a666703bfa7fcb2c592c74217dc46c2a8ab78 in container 934ccc54b74036f23027ea18ecd03302d69105ad28d334ce8349c748582a6dd3: [8] System error: exit status 1
                           %                                                                                                                                                                                                                   
```

`docker stop` and `docker rm -f` don't work as well.

Here's my `docker ps`:
```
» docker ps                                                                                                                                                                                                   u@tacobell | 2016-02-04 14:53:53
CONTAINER ID        IMAGE                        COMMAND                CREATED             STATUS              PORTS                                                                                           NAMES
934ccc54b740        rancher/server:v0.56.1       "/usr/bin/s6-svscan    6 days ago          Up 6 days           3306/tcp, 0.0.0.0:8080->8080/tcp                                                                rancher_shepherd               
ec13562e9d46        file-lister:latest           "/bin/sh -c /proj/bi   6 weeks ago         Up 6 days           0.0.0.0:20050->8080/tcp                                                                         5528f9f6-78c7-415e-8a9d-c9dc988fb741
8eacee4e31eb        redis:latest                 "/entrypoint.sh redi   6 weeks ago         Up 6 days           6379/tcp                                                                                        5371870b-2d06-47e9-a8d7-2fbac07cade2
66c5f9720d7e        rancher/agent:v0.8.2         "/run.sh run"          6 weeks ago         Up 6 days                                                                                                           rancher-agent                  
dca388ae8652        service-dashboard:latest     "/bin/sh -c /service   7 weeks ago         Up 6 days           0.0.0.0:30002->9011/tcp                                                                         service-dashboard              
93aa9299677e        service-survey:latest        "/bin/sh -c /service   7 weeks ago         Up 6 days           0.0.0.0:38003->8080/tcp                                                                         service-survey                 
f6c1c1a9c7ae        pha-t:latest                 "/init"                10 weeks ago        Up 4 minutes        24/tcp, 443/tcp, 0.0.0.0:22->22/tcp, 843/tcp, 0.0.0.0:44003->80/tcp, 0.0.0.0:44002->22280/tcp   phabulous                      
60bf7381ce1c        mysql:latest                 "/entrypoint.sh mysq   10 weeks ago        Up 6 days           3306/tcp                                                                                        mysql1                         
26c39943a75b        tini-inf:latest              "/bin/sh -c /proj/bi   11 weeks ago        Up 6 days           0.0.0.0:30019->8080/tcp                                                                         tini-infi                      
a114031021d2        utrack/dash-service:latest   "/bin/sh -c /proj/bi   3 months ago        Up 6 days           0.0.0.0:37110->8080/tcp                                                                         dash-service                   
144f2f0ab34e        redis:latest                 "/entrypoint.sh redi   4 months ago        Up 6 days           6379/tcp                                                                                        redis-dash-cc-rb               
2fe272fc3b15        redis:latest                 "/entrypoint.sh redi   4 months ago        Up 6 days           6379/tcp                                                                                        redis-cc-survey                
4e07a7aeff00        redis:latest                 "/entrypoint.sh redi   4 months ago        Up 6 days           6379/tcp                                                                                        redis-cc                       
1872cdee2324        prom/promdash:latest         "./run ./bin/thin st   5 months ago        Up 6 days           0.0.0.0:3000->3000/tcp                                                                          prom_dashboard                 
c393be6be4c2        tini:latest                  "/bin/sh -c /proj/bi   6 months ago        Up 6 days           0.0.0.0:30020->8080/tcp                                                                         tini                           
c4f8c249b2ee        redis:latest                 "/entrypoint.sh redi   7 months ago        Up 6 days           6379/tcp                                                                                        redis-rb                       
99e799c903ed        redis:latest                 "/entrypoint.sh redi   7 months ago        Up 6 days           127.0.0.1:30010->6379/tcp                                                                       s-s-redis                      
dbc69186cf43        postgres:latest              "/docker-entrypoint.   8 months ago        Up 6 days           5432/tcp                                                                                        pg1                            
```
There's some proprietary containers running, none of them touch network routing or anything though.

**Comment by deniseschannon** [comment]
Have you tried just running rancher/server without connecting to the old DB to try and isolate the issue?

```
docker run -d --restart=always -p 8080:8080 rancher/server:v0.56.1
```

**Comment by utrack** [comment]
@deniseschannon this one works, possibly because of different mysql connection settings (?), that's odd.

**Comment by deniseschannon** [comment]
@utrack Have you tried going back to v0.50.1 to see if you are still able to connect to your external DB? From what you have described, it sounds like you are having connection issues with your external DB using v0.56.1. I'm not sure if that's an issue with v0.56.1 or if something is corrupted in the external DB. 

```
» docker run -d --restart=always -p 8080:8080 \
-e CATTLE_DB_CATTLE_MYSQL_HOST=192.168.10.5 \
-e CATTLE_DB_CATTLE_MYSQL_PORT=3307 \
-e CATTLE_DB_CATTLE_MYSQL_NAME=cattle \
-e CATTLE_DB_CATTLE_USERNAME=cattle \
-e CATTLE_DB_CATTLE_PASSWORD=<password> \
--name rancher_shepherd rancher/server:v0.50.1
```

**Comment by deniseschannon** [comment]
@utrack Please re-open if you are still having issues with connecting to your external DB.
