### ISSUE TITLE
metrics server, coredns and cluster agent are not available on an upgraded Rancher server on a RHEL 8.3 cluster and 1.18k8s

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#34541]
**Rancher Server Setup**
- Rancher version: 2.5.9 to 2.6.0-rc9
- Installation option (Docker install/Helm Chart): HELM
   - If Helm Chart, Kubernetes Info: 
         Cluster Type (RKE1, RKE2, k3s, EKS, etc): RKE1
         Node Setup: 3 nodes all toles
         Version: 1.20.9
- Proxy/Cert Details: rancher generated

**Information about the Cluster**
- Kubernetes version: 1.18.20
- Cluster Type (Local/Downstream): RHEL 8.3 1 etcd, 1 control plane and 3 worker nodes

**Describe the bug**
metrics server, coredns and cluster agent are not available on an upgraded Rancher server on a RHEL 8.3 cluster and 1.18k8s

**To Reproduce**

- In 2.5.9 rancher, deploy a custom RHEL 1.18.20 cluster
- Upgrade rancher to 2.6.0-rc9
- metrics server, coredns and cluster agent are not available 
- Metrics server in crashloop and logs:

```
I0829 22:37:06.414981       1 serving.go:312] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
Error: Get https://10.43.0.1:443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication: dial tcp 10.43.0.1:443: i/o timeout
Usage:
   [flags]
Flags:
      --alsologtostderr                                         log to standard error as well as files
      --authentication-kubeconfig string                        kubeconfig file pointing at the 'core' kubernetes server with enough rights to create tokenaccessreviews.authentication.k8s.io.
      --authentication-skip-lookup                              If false, the authentication-kubeconfig will be used to lookup missing authentication configuration from the cluster.
      --authentication-token-webhook-cache-ttl duration         The duration to cache responses from the webhook token authenticator. (default 10s)
      --authentication-tolerate-lookup-failure                  If true, failures to look up missing authentication configuration from the cluster are not considered fatal. Note that this can result in authentication that treats all requests as anonymous.
      --authorization-always-allow-paths strings                A list of HTTP paths to skip during authorization, i.e. these are authorized without contacting the 'core' kubernetes server.
      --authorization-kubeconfig string                         kubeconfig file pointing at the 'core' kubernetes server with enough rights to create subjectaccessreviews.authorization.k8s.io.
      --authorization-webhook-cache-authorized-ttl duration     The duration to cache 'authorized' responses from the webhook authorizer. (default 10s)
      --authorization-webhook-cache-unauthorized-ttl duration   The duration to cache 'unauthorized' responses from the webhook authorizer. (default 10s)
      --bind-address ip                                         The IP address on which to listen for the --secure-port port. The associated interface(s) must be reachable by the rest of the cluster, and by CLI/web clients. If blank, all interfaces will be used (0.0.0.0 for all IPv4 interfaces and :: for all IPv6 interfaces). (default 0.0.0.0)
      --cert-dir string                                         The directory where the TLS certs are located. If --tls-cert-file and --tls-private-key-file are provided, this flag will be ignored. (default "apiserver.local.config/certificates")
      --client-ca-file string                                   If set, any request presenting a client certificate signed by one of the authorities in the client-ca-file is authenticated with an identity corresponding to the CommonName of the client certificate.
      --contention-profiling                                    Enable lock contention profiling, if profiling is enabled
  -h, --help                                                    help for this command
      --http2-max-streams-per-connection int                    The limit that the server gives to clients for the maximum number of streams in an HTTP/2 connection. Zero means to use golang's default.
      --kubeconfig string                                       The path to the kubeconfig used to connect to the Kubernetes API server and the Kubelets (defaults to in-cluster config)
      --kubelet-certificate-authority string                    Path to the CA to use to validate the Kubelet's serving certificates.
      --kubelet-insecure-tls                                    Do not verify CA of serving certificates presented by Kubelets.  For testing purposes only.
      --kubelet-port int                                        The port to use to connect to Kubelets. (default 10250)
      --kubelet-preferred-address-types strings                 The priority of node address types to use when determining which address to use to connect to a particular node (default [Hostname,InternalDNS,InternalIP,ExternalDNS,ExternalIP])
      --log-flush-frequency duration                            Maximum number of seconds between log flushes (default 5s)
      --log_backtrace_at traceLocation                          when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                                          If non-empty, write log files in this directory
      --log_file string                                         If non-empty, use this log file
      --logtostderr                                             log to standard error instead of files (default true)
      --metric-resolution duration                              The resolution at which metrics-server will retain metrics. (default 1m0s)
      --profiling                                               Enable profiling via web interface host:port/debug/pprof/ (default true)
      --requestheader-allowed-names strings                     List of client certificate common names to allow to provide usernames in headers specified by --requestheader-username-headers. If empty, any client certificate validated by the authorities in --requestheader-client-ca-file is allowed.
      --requestheader-client-ca-file string                     Root certificate bundle to use to verify client certificates on incoming requests before trusting usernames in headers specified by --requestheader-username-headers. WARNING: generally do not depend on authorization being already done for incoming requests.
      --requestheader-extra-headers-prefix strings              List of request header prefixes to inspect. X-Remote-Extra- is suggested. (default [x-remote-extra-])
      --requestheader-group-headers strings                     List of request headers to inspect for groups. X-Remote-Group is suggested. (default [x-remote-group])
      --requestheader-username-headers strings                  List of request headers to inspect for usernames. X-Remote-User is common. (default [x-remote-user])
      --secure-port int                                         The port on which to serve HTTPS with authentication and authorization.If 0, don't serve HTTPS at all. (default 443)
      --skip_headers                                            If true, avoid header prefixes in the log messages
      --stderrthreshold severity                                logs at or above this threshold go to stderr
      --tls-cert-file string                                    File containing the default x509 Certificate for HTTPS. (CA cert, if any, concatenated after server cert). If HTTPS serving is enabled, and --tls-cert-file and --tls-private-key-file are not provided, a self-signed certificate and key are generated for the public address and saved to the directory specified by --cert-dir.
      --tls-cipher-suites strings                               Comma-separated list of cipher suites for the server. If omitted, the default Go cipher suites will be use.  Possible values: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_RC4_128_SHA,TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_RC4_128_SHA,TLS_RSA_WITH_3DES_EDE_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_RC4_128_SHA
      --tls-min-version string                                  Minimum TLS version supported. Possible values: VersionTLS10, VersionTLS11, VersionTLS12
      --tls-private-key-file string                             File containing the default x509 private key matching --tls-cert-file.
      --tls-sni-cert-key namedCertKey                           A pair of x509 certificate and private key file paths, optionally suffixed with a list of domain patterns which are fully qualified domain names, possibly with prefixed wildcard segments. If no domain patterns are provided, the names of the certificate are extracted. Non-wildcard matches trump over wildcard matches, explicit domain patterns trump over extracted names. For multiple key/certificate pairs, use the --tls-sni-cert-key multiple times. Examples: "example.crt,example.key" or "foo.crt,foo.key:*.foo.com,foo.com". (default [])
  -v, --v Level                                                 number for the log level verbosity
      --vmodule moduleSpec                                      comma-separated list of pattern=N settings for file-filtered logging
panic: Get https://10.43.0.1:443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication: dial tcp 10.43.0.1:443: i/o timeout
goroutine 1 [running]:
main.main()
	/go/src/github.com/kubernetes-incubator/metrics-server/cmd/metrics-server/metrics-server.go:39 +0x13b
```
- cattle-cluster agent pod logs
```
INFO: Environment: CATTLE_ADDRESS=10.42.4.3 CATTLE_CA_CHECKSUM=0f3f2e580399910bc470a5579e21fe3a034ed7376448b547f554efcb4d1244f0 CATTLE_CLUSTER=true CATTLE_CLUSTER_AGENT_PORT=tcp://10.43.51.173:80 CATTLE_CLUSTER_AGENT_PORT_443_TCP=tcp://10.43.51.173:443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_ADDR=10.43.51.173 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PORT=443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_PORT_80_TCP=tcp://10.43.51.173:80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_ADDR=10.43.51.173 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PORT=80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_SERVICE_HOST=10.43.51.173 CATTLE_CLUSTER_AGENT_SERVICE_PORT=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTP=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTPS_INTERNAL=443 CATTLE_FEATURES=embedded-cluster-api=false,fleet=false,monitoringv1=false,multi-cluster-management=false,multi-cluster-management-agent=true,provisioningv2=false,rke2=false CATTLE_INTERNAL_ADDRESS= CATTLE_IS_RKE=true CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-5874db49d9-b9fgj CATTLE_SERVER=https://server
INFO: Using resolv.conf: nameserver 10.43.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local us-east-2.compute.internal options ndots:5
ERROR: https://<server>/ping is not accessible (Could not resolve host: <server>)
```

**Note:**

- Works on RHel + 1.19 k8s
- Works on ubuntu + 1.18.20 k8s
- Coredns pod is in Unavailable state.
- Happens on an upgrade from 2.5.8 to 2.5.9 also

**Comment by cbron** [comment]
This is odd, is this repeatable ?

**Comment by snasovich** [comment]
@sowmyav27 , could you check if it's reproducible in 2.6.3?

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.5.9 to 2.6.3
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: custom RHEL 1.18.20 cluster

----------

### Testing: ###

Tested this issue with the following steps:
1. In 2.5.9 rancher, deploy a custom RHEL 1.18.20 cluster
2. Upgrade rancher to 2.6.3
3. Check if metrics server, coredns and cluster agent are available

**Result** - Reproducible

After upgrading to 2.6.3 from 2.5.9, cluster is not able to connect.
![image.png](https://zube.io/files/rancher/c0b9a7e8199bff960559011ef2c70810-image.png)

The pod log does say the address is accessible
INFO: Environment: CATTLE_ADDRESS=server CATTLE_AGENT_CONNECT=true CATTLE_CA_CHECKSUM= CATTLE_CLUSTER=false CATTLE_CLUSTER_AGENT_PORT=tcp://server:80 CATTLE_CLUSTER_AGENT_PORT_443_TCP=tcp://server:443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_ADDR=server CATTLE_CLUSTER_AGENT_PORT_443_TCP_PORT=443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_PORT_80_TCP=tcp://server:80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_ADDR=server
CATTLE_CLUSTER_AGENT_PORT_80_TCP_PORT=80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_SERVICE_HOST=server
CATTLE_CLUSTER_AGENT_SERVICE_PORT=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTP=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTPS_INTERNAL=443 CATTLE_INGRESS_IP_DOMAIN=sslip.io CATTLE_INSTALL_UUID=f79169bd-4777-43f9-8427-34660f3168dd CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=ip-server CATTLE_SERVER=https://server CATTLE_SERVER_VERSION=v2.6.3
INFO: Using resolv.conf: nameserver <server> search us-east-2.compute.internal
INFO: https://server/ping is accessible
INFO: server resolves to <server>

**Comment by jakefhyde** [comment]
This should be tested on RHEL 8.4 and 8.5 to see if it is reproducible on those versions as well. If so we should look into updating libraries to see if that resolves the issue, or look into upstream issues which may provide workarounds.

**Comment by HarrisonWAffel** [comment]
RHEL instances used to run Rancher and Kubernetes require several prerequisite steps in order to function properly, and it seems that this is another one of those steps for running 1.18 on RHEL. However, due to the fact that that this issue only reproduces on k8's 1.18 (both before and after an upgrade), and support for 1.18 will drop with the next release of Rancher, we do not feel it would be beneficial to implement a fix (silently editing `iptables` rules doesn't sound like a good idea) or add to the documentation as it would quickly be irrelevant.
