### ISSUE TITLE
Logging v1 - fluentd v0.1.29 pods fail to start ruby plugin, no logs flow to backend

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#34548]
**Rancher Server Setup**
- Rancher version: `v2.6.0-rc9`
- Installation option: HA RKE1
   - If Helm Chart, Kubernetes Info:
         Cluster Type: RKE1
         Node Setup: `t3.xlarge`
         Version: Ubuntu 18.04.3
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `1.20.10`
- Cluster Type: Downstream 
   - If downstream, what type of cluster?: Custom RKE1 AWS
   - RHEL 8.4
   - _Additional test done on Ubuntu 20.04.2 with same result_

**Describe the bug**

Error are observed in the logging fluentd daemonset pods:

`2021-08-30 16:52:19 +0000 [error]:  #0 unexpected error error_class=MultiJson::AdapterError error="Did not recognize your adapter specification (cannot load such file -- bigdecimal)."`

**To Reproduce**
- Install the V1 Logging app (0.3.0)
- Wait for the app to become installed and check the workloads in the System project
- Configure Elasticsearch as Backend
- Check the pods logs in the `rancher-logging-fluentd-linux` daemonset for errors
- Fluentd version is `v0.1.29`

**Result**

`2021-08-30 16:52:19 +0000 [error]:  #0 unexpected error error_class=MultiJson::AdapterError error="Did not recognize your adapter specification (cannot load such file -- bigdecimal)."`

No logs flowing to Elasticsearch

**Expected Result**
No Ruby errors in the Fluentd pods
Logs flowing to Elasticsearch

**Additional context**

- This works on `v2.5.9` using Elastic search as backend too and RHEL 8.3
- The Logging v1 app in `v2.5.9` has version `v0.2.4`
- fluentd in `v2.5.9` has version `v0.1.24`

**Complete error**

```
2021-08-30 18:09:43 +0000 [error]:  #0 unexpected error error_class=MultiJson::AdapterError error="Did not recognize your adapter specification (cannot load such file -- bigdecimal)."
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/oj-3.10.18/lib/oj/mimic.rb:2:in `<top (required)>'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/oj-3.10.18/lib/oj.rb:9:in `<top (required)>'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/multi_json-1.15.0/lib/multi_json/adapters/oj.rb:2:in `<top (required)>'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/multi_json-1.15.0/lib/multi_json.rb:157:in `load_adapter_from_string_name'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/multi_json-1.15.0/lib/multi_json.rb:101:in `load_adapter'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/multi_json-1.15.0/lib/multi_json.rb:103:in `load_adapter'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/multi_json-1.15.0/lib/multi_json.rb:91:in `use'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/multi_json-1.15.0/lib/multi_json.rb:73:in `adapter'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/multi_json-1.15.0/lib/multi_json.rb:133:in `current_adapter'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/multi_json-1.15.0/lib/multi_json.rb:120:in `load'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/elasticsearch-transport-7.13.1/lib/elasticsearch/transport/transport/serializer/multi_json.rb:41:in `load'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/elasticsearch-transport-7.13.1/lib/elasticsearch/transport/transport/base.rb:350:in `perform_request'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/elasticsearch-transport-7.13.1/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/elasticsearch-transport-7.13.1/lib/elasticsearch/transport/client.rb:192:in `perform_request'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/elasticsearch-api-7.13.1/lib/elasticsearch/api/actions/info.rb:37:in `info'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-3.8.0/lib/fluent/plugin/out_elasticsearch.rb:395:in `detect_es_major_version'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-3.8.0/lib/fluent/plugin/out_elasticsearch.rb:265:in `block in configure'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-3.8.0/lib/fluent/plugin/elasticsearch_index_template.rb:35:in `retry_operate'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-3.8.0/lib/fluent/plugin/out_elasticsearch.rb:264:in `configure'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.1/lib/fluent/plugin.rb:178:in `configure'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.1/lib/fluent/plugin/multi_output.rb:74:in `block in configure'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.1/lib/fluent/plugin/multi_output.rb:63:in `each'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.1/lib/fluent/plugin/multi_output.rb:63:in `configure'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.1/lib/fluent/plugin/out_copy.rb:39:in `configure'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.1/lib/fluent/plugin.rb:178:in `configure'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.1/lib/fluent/agent.rb:132:in `add_match'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.1/lib/fluent/agent.rb:74:in `block in configure'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.1/lib/fluent/agent.rb:64:in `each'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.1/lib/fluent/agent.rb:64:in `configure'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.1/lib/fluent/root_agent.rb:146:in `configure'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.1/lib/fluent/engine.rb:105:in `configure'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.1/lib/fluent/engine.rb:80:in `run_configure'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.1/lib/fluent/supervisor.rb:714:in `block in run_worker'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.1/lib/fluent/supervisor.rb:966:in `main_process'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.1/lib/fluent/supervisor.rb:706:in `run_worker'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.1/lib/fluent/command/fluentd.rb:364:in `<top (required)>'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.13.1/bin/fluentd:15:in `<top (required)>'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/bin/fluentd:23:in `load'
  2021-08-30 18:09:43 +0000 [error]:  #0 /usr/bin/fluentd:23:in `<main>'
```

**Comment by izaac** [comment]
Rancher version: `v2.6.0-rc10` - Fresh Install - RHEL 8.4 RKE1 Nodes

`v2.5.9` -> `v2.6.0-rc10` - Upgrade - RHEL 8.3 RKE1 Nodes

**Fresh install** worked, the fluentd pods no longer show the Ruby plugin error in the logs. The logs are flowing to Elasticsearch.
**Fresh install**  the fluentd image version was: `v0.1.30`

**Upgrade** path worked, logs were flowing before and after upgrade. 
During **Upgrade** the Logging v1 App was upgraded automatically without intervention as expected from `0.2.4` to `0.3.0`
During **Upgrade** the fluentd image was upgraded from `v0.1.24` to `v0.1.30`

`rancher-images.txt` is also including this new fluentd image version `v0.1.30`
