### ISSUE TITLE
if sidekick shares networking with main container and main container goes away, service cannot come back up

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#3475]
Steps to repro:
1 launch a stack like this:

```
foo:
  labels:
    io.rancher.sidekicks: bar
  image: nginx
bar:
  command:
  - sh
  tty: true
  image: alpine
  stdin_open: true
  net: container:foo
```

2 go to host and delete the foo container

result. rancher will try to restart the bar contianer (instead of delete/recreate it) and the container will always fail to start. You'll see this error in python-agent logs:

```
2016-01-29 22:49:11,768 ERROR agent [140150023370224] [event.py:112] Error in request : 39bd9c27-1a8c-4688-9920-71268109b295
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 34, in execute
    return method(req=req, **req.data.__dict__)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 481, in instance_activate
    self._do_instance_activate(instance, host, progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 559, in _do_instance_activate
    client.start(container_id)
  File "/var/lib/cattle/pyagent/dist/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/var/lib/cattle/pyagent/dist/docker/api/container.py", line 343, in start
    self._raise_for_status(res)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 142, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 500 Server Error: Internal Server Error ("Cannot start container 86214db4c59bef2a65fc9be3ce342a3d9eb1756e679cf633c0dbd40e9777632c: no such id: 9d12405ce8087d49844d714a17231b58794373d62c145528cbc04020791e3c66")
```

**Comment by alena1108** [comment]
@cjellick Here is what happens. The container foo that got destroyed on docker side (did it with docker rm -f), comes to stopping->stopped in Rancher. Then - just before Rancher gets a chance to execute container.remove - service.reconcile triggered by container.stop event for foo, tries to restart it, and it succeeds! Even though the container is gone on docker, rancher re-creates its and assigns to the same rancher instance object, but this time with a different external id:

```
mysql> select id, name, state, uuid, external_id from instance where id > 9;
+----+-----------------+---------+--------------------------------------+------------------------------------------------------------------+
| id | name            | state   | uuid                                 | external_id                                                      |
+----+-----------------+---------+--------------------------------------+------------------------------------------------------------------+
| 10 | craig_foo_1     | running | 67f25f27-eac7-4502-8c03-96fdbe11931a | c7c696b5a420155148bad51bd64db628d3cf2a0ea8ffbe284b9f471ddf41704c |
| 11 | craig_foo_bar_1 | running | 69252a2d-0f3f-4f9d-b27b-41c728a28bf3 | 0daca0c4de96c26f79c6ce9e8c24d859a74279872540c3335d73948f69294544 |
+----+-----------------+---------+--------------------------------------+------------------------------------------------------------------+
2 rows in set (0.00 sec)

after removal on docker side:

mysql> select id, name, state, uuid, external_id from instance where id > 9;
+----+-----------------+---------+--------------------------------------+------------------------------------------------------------------+
| id | name            | state   | uuid                                 | external_id                                                      |
+----+-----------------+---------+--------------------------------------+------------------------------------------------------------------+
| 10 | craig_foo_1     | running | 67f25f27-eac7-4502-8c03-96fdbe11931a | 4008c9e89539671c1c4fec2533d8816ff2545aa396344a74f7f4b2ab96c5b361 |
| 11 | craig_foo_bar_1 | stopped | 69252a2d-0f3f-4f9d-b27b-41c728a28bf3 | 0daca0c4de96c26f79c6ce9e8c24d859a74279872540c3335d73948f69294544 |
+----+-----------------+---------+--------------------------------------+------------------------------------------------------------------+
```

So the container foo_bar continues reference foo thinking that its exactly the same container. 

Not sure what would be the right way to handle that. Ideally we should allow going from running to removing state as there are all kinds of possible race conditions that can happen in a split of a second when container's chained Remove process is called (if thats what docker-rancher sync logic does when container gets removed on a docker side). Or other possible fix would be - don't allow restarting the container that no longer exists on docker.

**Comment by cjellick** [comment]
Was exploring ways to fix...it could be something simple down in python-agent like if we detect that a container we are trying to start exists and uses the net namespace of a container that doesn't exist, we delete it and attempt to recreate. @ibuildthecloud your thoughts?

**Comment by cjellick** [comment]
@ibuildthecloud and i discussed. the silent delete/recreate on the python-agent is a bad idea. It would be too tricky to "do the right thing" with the limit context that python-agent has in this case.

**Comment by alena1108** [comment]
@cjellick @ibuildthecloud isn't it a problem that we recreate a removed container on docker? So Rancher object can potentially correlate to 2 diff objects on Docker at diff time, while remaining as the same object in Rancher? There can be other potential issues when this container is referenced inside Rancher (volumeFrom, networkFrom, etc) as Rancher has no idea that the object got "swapped" on the docker side.

**Comment by cjellick** [comment]
yes, i do think its a problem...this use case highlights the fundamental flaw in it

**Comment by cjellick** [comment]
I _think_ that @ibuildthecloud and I left this at it should be orchestrated in cattle. Need to revisit.

**Comment by cjellick** [comment]
Moving out of GA. Here's is our theoretical solutoin:
in host-api, watch for stop and remove docker events if a container that has sidekicks that shares a net namespace gets stopped or removed, then stop/remove the sidekick

**Comment by will-chan** [comment]
Closing due to inactivity, please reopen if you think this is still relevant to current releases & important.
