### ISSUE TITLE
[CI] Rancher fails to start intermittently, leading to 1 hour test timeouts

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#34971]
This has been happening much more frequently with recent changes to `release/v2.6` leading to `v2.6.1`. This could reach a point where it becomes a release blocker if not resolved.

```
panic: indexer conflict: map[byPod:{}]

goroutine 3208 [running]:
k8s.io/apimachinery/pkg/util/runtime.Must(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/runtime/runtime.go:171
github.com/rancher/rancher/pkg/generated/controllers/catalog.cattle.io/v1.(*operationCache).AddIndexer(0xc008e31080, 0x4181464, 0x5, 0x439b4f8)
	/go/src/github.com/rancher/rancher/pkg/generated/controllers/catalog.cattle.io/v1/operation.go:247 +0x127
github.com/rancher/rancher/pkg/controllers/dashboard/helm.RegisterOperations(0x48f4aa8, 0xc008c81240, 0x4959c58, 0xc0016e2420, 0x4942700, 0xc00a0f6460, 0x4940240, 0xc00a0f64d0)
	/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/helm/operations.go:42 +0x1b8
github.com/rancher/rancher/pkg/controllers/dashboard/helm.Register(0x48f4aa8, 0xc008c81240, 0xc000c401a0)
	/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/helm/register.go:22 +0x3c5
github.com/rancher/rancher/pkg/controllers/dashboard.Register(0x48f4aa8, 0xc008c81240, 0xc000c401a0, 0xc008e30d01, 0x39b61a0, 0x69d2b38)
	/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/controller.go:23 +0x5a
github.com/rancher/rancher/pkg/rancher.(*Rancher).Start.func1.1(0x48f4aa8, 0xc008c81240, 0x39b61a0, 0x69d2b38)
	/go/src/github.com/rancher/rancher/pkg/rancher/rancher.go:245 +0x4e
github.com/rancher/rancher/pkg/wrangler.(*Context).StartWithTransaction(0xc000c401a0, 0x48f45d8, 0xc003346a80, 0xc0044c7f58, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/wrangler/context.go:152 +0xd9
github.com/rancher/rancher/pkg/rancher.(*Rancher).Start.func1(0x48f45d8, 0xc003346a80, 0x41f2607, 0x1e)
	/go/src/github.com/rancher/rancher/pkg/rancher/rancher.go:245 +0x107
github.com/rancher/wrangler/pkg/leader.(*Manager).OnLeader.func1(0xc000353e60, 0xc000c6ecc0)
	/go/pkg/mod/github.com/rancher/wrangler@v0.8.6-0.20210819203859-0babd42fbad8/pkg/leader/manager.go:51 +0xcc
created by github.com/rancher/wrangler/pkg/leader.(*Manager).OnLeader
	/go/pkg/mod/github.com/rancher/wrangler@v0.8.6-0.20210819203859-0babd42fbad8/pkg/leader/manager.go:48 +0x49
exit status 255
```

**Comment by cbron** [comment]
We can close it since its just CI, can you reopen if you see again.

**Comment by brandond** [comment]
Seeing this locally as well, running on K3s 1.21.5+k3s2

```
panic: indexer conflict: map[byPod:{}]

goroutine 5560 [running]:
k8s.io/apimachinery/pkg/util/runtime.Must(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/runtime/runtime.go:171
github.com/rancher/rancher/pkg/generated/controllers/catalog.cattle.io/v1.(*operationCache).AddIndexer(0xc0062c3050, 0x41824a4, 0x5, 0x439c570)
	/go/src/github.com/rancher/rancher/pkg/generated/controllers/catalog.cattle.io/v1/operation.go:247 +0x127
github.com/rancher/rancher/pkg/controllers/dashboard/helm.RegisterOperations(0x48f5b48, 0xc0067fd0c0, 0x495ad58, 0xc0019b6dc0, 0x4943800, 0xc008019180, 0x4941340, 0xc0080191f0)
	/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/helm/operations.go:42 +0x1b8
github.com/rancher/rancher/pkg/controllers/dashboard/helm.Register(0x48f5b48, 0xc0067fd0c0, 0xc000d4e680)
	/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/helm/register.go:22 +0x3c5
github.com/rancher/rancher/pkg/controllers/dashboard.Register(0x48f5b48, 0xc0067fd0c0, 0xc000d4e680, 0xc0062c2d00, 0x39b71c0, 0x69d3bf8)
	/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/controller.go:23 +0x5a
github.com/rancher/rancher/pkg/rancher.(*Rancher).Start.func1.1(0x48f5b48, 0xc0067fd0c0, 0x39b71c0, 0x69d3bf8)
	/go/src/github.com/rancher/rancher/pkg/rancher/rancher.go:245 +0x4e
github.com/rancher/rancher/pkg/wrangler.(*Context).StartWithTransaction(0xc000d4e680, 0x48f5678, 0xc003767700, 0xc005ac7f58, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/wrangler/context.go:152 +0xd9
github.com/rancher/rancher/pkg/rancher.(*Rancher).Start.func1(0x48f5678, 0xc003767700, 0x41f3641, 0x1e)
	/go/src/github.com/rancher/rancher/pkg/rancher/rancher.go:245 +0x107
github.com/rancher/wrangler/pkg/leader.(*Manager).OnLeader.func1(0xc001a62420, 0xc003d4f390)
	/go/pkg/mod/github.com/rancher/wrangler@v0.8.6-0.20210819203859-0babd42fbad8/pkg/leader/manager.go:51 +0xcc
created by github.com/rancher/wrangler/pkg/leader.(*Manager).OnLeader
	/go/pkg/mod/github.com/rancher/wrangler@v0.8.6-0.20210819203859-0babd42fbad8/pkg/leader/manager.go:48 +0x49
```

**Comment by Oats87** [comment]
Just hit this again with a `v2.6-head` build that I rebased onto this morning (Nov 2, 2021)

**Comment by annablender** [comment]
This is the webhook-rancher issue I hit last night on my PR. Rancher just failed and took k3s down with it. @nickgerace  can the fix for this race condition get merged?

**Comment by nickgerace** [comment]
@annablender there is not a permanent fix. It is likely that we will need to look into this further with @ibuildthecloud.

cc @Oats87

**Comment by snasovich** [comment]
@slickwarren , could you please confirm it's reopened due to dev template not filled out?

Given this is CI issue, I'm not sure if it needs to be formally validated by the QA.
@Oats87 , did your fixes from ~1 months ago address CI issues?

**Comment by slickwarren** [comment]
correct, only reopened for dev template. No tests from QA yet.

**Comment by snasovich** [comment]
Given the same panic happened at least once during Docker install https://github.com/rancher/rancher/issues/36925, we're not confident it's actually fixed. So we're putting this issue back to our team's column and 2.6.5 milestone.

**Comment by snasovich** [comment]
Closing, will reopen if we run into these issues

**Comment by all4innov** [comment]
Got the same error when migrating from 2.6.6 to 2.6.7 or 2.6.8 
(Rancher 2.6.6 deployed on AWS EKS 1.22)
Any tips ?
