### ISSUE TITLE
Rancher Console crashes

### ISSUE THREAD

**Issue by ekarlso** [rancher/rancher#35153]
**Rancher Server Setup**
- Rancher version:
2.6.1

- Installation option (Docker install/Helm Chart):
AKS -> 1.20.7

- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- 1.20.7
- 
- Cluster Type (Local/Downstream):
RKE1 + RKE2 

**Describe the bug**
rancher-server crashes with nil reference after adding RKE2 cluster

I upgraded a setup from 2.5.8 to 2.6.1 and created a RKE2 cluster on a sanitized set of vm's that was running RKE1.

After adding the last set of nodes the rancher-server just starts to crash with the below logs.

```2021/10/17 17:21:54 [ERROR] error parsing azure-group-cache-size, skipping update strconv.Atoi: parsing "": invalid syntax
2021/10/17 17:21:54 [INFO] Refreshing driverMetadata in 1440 minutes
E1017 17:21:54.150380      32 memcache.go:196] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
2021/10/17 17:21:54 [DEBUG] Loading data.json from local source
HEAD is now at e6ed1b3 Merge pull request #1499 from nickgerace/release-v2.6.1
E1017 17:21:54.208863      32 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 4504 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x39bff80, 0x692a730)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/runtime/runtime.go:48 +0x86
panic(0x39bff80, 0x692a730)
    /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/rancher/rancher/pkg/controllers/provisioningv2/rke2/machinedrain.(*handler).undrain(0xc00915e390, 0xc0022ba6c0, 0x41c6617, 0x16, 0xc001634338)
    /go/src/github.com/rancher/rancher/pkg/controllers/provisioningv2/rke2/machinedrain/machinedrain.go:74 +0xc9
github.com/rancher/rancher/pkg/controllers/provisioningv2/rke2/machinedrain.(*handler).OnChange(0xc00915e390, 0xc0021ff620, 0x21, 0xc0022ba6c0, 0x3fe9a00, 0x41146a0, 0x4954380)
    /go/src/github.com/rancher/rancher/pkg/controllers/provisioningv2/rke2/machinedrain/machinedrain.go:48 +0xd4
github.com/rancher/rancher/pkg/generated/controllers/cluster.x-k8s.io/v1alpha4.FromMachineHandlerToHandler.func1(0xc0021ff620, 0x21, 0x48b1d10, 0xc0022ba6c0, 0xc0022ba6c0, 0x4954380, 0xc0022ba6c0, 0x1)
    /go/src/github.com/rancher/rancher/pkg/generated/controllers/cluster.x-k8s.io/v1alpha4/machine.go:105 +0x6b
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc0072d8e80, 0xc0021ff620, 0x21, 0x48b1d10, 0xc0022ba6c0, 0x0, 0xc0022ba6c0, 0x0, 0x0)
    /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc003446200, 0xc0021ff620, 0x21, 0x48b1d10, 0xc0022ba6c0, 0xc00a278201, 0x0)
    /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/sharedhandler.go:69 +0x14c
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000b151e0, 0xc0021ff620, 0x21, 0xc00a278358, 0x4e4e304c755258)
    /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:215 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000b151e0, 0x37996e0, 0xc01356b440, 0x0, 0x0)
    /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:197 +0xe7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000b151e0, 0x203002)
    /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:174 +0x54
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
    /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:163
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc002a058d0)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc002a058d0, 0x48839e0, 0xc00a6aa120, 0x5a765a5656464e01, 0xc000a28480)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc002a058d0, 0x3b9aca00, 0x0, 0x5149705159556c01, 0xc000a28480)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc002a058d0, 0x3b9aca00, 0xc000a28480)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
    /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:134 +0x33b
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x2d1c5a9]
goroutine 4504 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/runtime/runtime.go:55 +0x109
panic(0x39bff80, 0x692a730)
    /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/rancher/rancher/pkg/controllers/provisioningv2/rke2/machinedrain.(*handler).undrain(0xc00915e390, 0xc0022ba6c0, 0x41c6617, 0x16, 0xc001634338)
    /go/src/github.com/rancher/rancher/pkg/controllers/provisioningv2/rke2/machinedrain/machinedrain.go:74 +0xc9
github.com/rancher/rancher/pkg/controllers/provisioningv2/rke2/machinedrain.(*handler).OnChange(0xc00915e390, 0xc0021ff620, 0x21, 0xc0022ba6c0, 0x3fe9a00, 0x41146a0, 0x4954380)
    /go/src/github.com/rancher/rancher/pkg/controllers/provisioningv2/rke2/machinedrain/machinedrain.go:48 +0xd4
github.com/rancher/rancher/pkg/generated/controllers/cluster.x-k8s.io/v1alpha4.FromMachineHandlerToHandler.func1(0xc0021ff620, 0x21, 0x48b1d10, 0xc0022ba6c0, 0xc0022ba6c0, 0x4954380, 0xc0022ba6c0, 0x1)
    /go/src/github.com/rancher/rancher/pkg/generated/controllers/cluster.x-k8s.io/v1alpha4/machine.go:105 +0x6b
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc0072d8e80, 0xc0021ff620, 0x21, 0x48b1d10, 0xc0022ba6c0, 0x0, 0xc0022ba6c0, 0x0, 0x0)
    /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc003446200, 0xc0021ff620, 0x21, 0x48b1d10, 0xc0022ba6c0, 0xc00a278201, 0x0)
    /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/sharedhandler.go:69 +0x14c
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000b151e0, 0xc0021ff620, 0x21, 0xc00a278358, 0x4e4e304c755258)
    /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:215 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000b151e0, 0x37996e0, 0xc01356b440, 0x0, 0x0)
    /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:197 +0xe7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000b151e0, 0x203002)
    /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:174 +0x54
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
    /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:163
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc002a058d0)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc002a058d0, 0x48839e0, 0xc00a6aa120, 0x5a765a5656464e01, 0xc000a28480)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc002a058d0, 0x3b9aca00, 0x0, 0x5149705159556c01, 0xc000a28480)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc002a058d0, 0x3b9aca00, 0xc000a28480)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
    /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:134 +0x33b
```

**To Reproduce**
Unsure

**Result**

**Expected Result**
Rancher should not be crashing in itself.

**Screenshots**

**Additional context**

**Comment by ikohlernz** [comment]
I have observed similar issue updating from 2.5.7 to 2.6.1. Rancher seems to be going fine for a while then keeps crashing with the error above. Thanks
