### ISSUE TITLE
Panic seen after deleting imported cluster

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#35160]
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x250 pc=0x2e38cfb]

goroutine 1782 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/runtime/runtime.go:55 +0x109
panic(0x39bff80, 0x692a730)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/rancher/rancher/pkg/controllers/management/usercontrollers.(*ClusterLifecycleCleanup).createCleanupClusterRole(0xc0162f13e0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/usercontrollers/controller.go:223 +0x6bb
github.com/rancher/rancher/pkg/controllers/management/usercontrollers.(*ClusterLifecycleCleanup).cleanupImportedCluster(0xc0162f13e0, 0xc03f137100, 0x3bd56e0, 0xc043752300)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/usercontrollers/controller.go:137 +0x85
github.com/rancher/rancher/pkg/controllers/management/usercontrollers.(*ClusterLifecycleCleanup).Remove(0xc0162f13e0, 0xc03f137100, 0x0, 0xffffffffffffffff, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/usercontrollers/controller.go:82 +0x90
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*clusterLifecycleAdapter).Finalize(0xc01702e7a0, 0x48a8ad0, 0xc03f137100, 0xc03f137370, 0x0, 0x8000104, 0x0)
	/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_cluster_lifecycle_adapter.go:39 +0x55
github.com/rancher/norman/lifecycle.checkNil(0x48a8ad0, 0xc03f137100, 0xc0110138c0, 0xc03a9e1800, 0x0, 0x0, 0xc0258c7695)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20210608202517-59b3523c3133/lifecycle/object.go:191 +0x3e
github.com/rancher/norman/lifecycle.(*objectLifecycleAdapter).record(0xc0169592f0, 0x48a8ad0, 0xc03a9e1800, 0xc0110138c0, 0x35, 0xc0258c7601, 0x35, 0x0)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20210608202517-59b3523c3133/lifecycle/object.go:181 +0xcf
github.com/rancher/norman/lifecycle.(*objectLifecycleAdapter).finalize(0xc0169592f0, 0x48a8ad0, 0xc03a9e1800, 0x48a8ad0, 0xc03a9e1800, 0x1, 0xc0110139e0, 0x2b03479)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20210608202517-59b3523c3133/lifecycle/object.go:106 +0x225
github.com/rancher/norman/lifecycle.(*objectLifecycleAdapter).sync(0xc0169592f0, 0xc002c262d0, 0x7, 0x40dbf20, 0xc03a9e1800, 0x7, 0x7f2ada43c350, 0xc011013a48, 0x40dbfb)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20210608202517-59b3523c3133/lifecycle/object.go:58 +0x145
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.NewClusterLifecycleAdapter.func1(0xc002c262d0, 0x7, 0xc03a9e1800, 0x10, 0x3798b60, 0x1, 0xc034b49130)
	/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_cluster_lifecycle_adapter.go:61 +0x53
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*clusterController).AddHandler.func1(0xc002c262d0, 0x7, 0x40dbf20, 0xc03a9e1800, 0xc011013b58, 0x3, 0x3, 0x0)
	/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_cluster_controller.go:155 +0x67
github.com/rancher/norman/controller.(*genericController).AddHandler.func1(0xc002c262d0, 0x7, 0x48a8ad0, 0xc03a9e1800, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20210608202517-59b3523c3133/controller/generic_controller.go:62 +0x224
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc016959380, 0xc002c262d0, 0x7, 0x48a8ad0, 0xc03a9e1800, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc002584100, 0xc002c262d0, 0x7, 0x48a8ad0, 0xc03a9e1800, 0xc0033caa01, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/sharedhandler.go:69 +0x14c
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000c976b0, 0xc002c262d0, 0x7, 0xc0033cabc8, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:215 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000c976b0, 0x37996e0, 0xc022fb8f20, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:197 +0xe7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000c976b0, 0x203001)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:174 +0x54
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:163
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00774fef0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00774fef0, 0x48839e0, 0xc002716060, 0x2c7d7d226e5c2d01, 0xc0018765a0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00774fef0, 0x3b9aca00, 0x0, 0x68712d63223a2201, 0xc0018765a0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc00774fef0, 0x3b9aca00, 0xc0018765a0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:134 +0x33b
```

**Comment by slickwarren** [comment]
on 2.6.1, I've tried the following to reproduce, however none of these have a panic in the logs:
* generate import command in rancher, delete 
* run import command on the import cluster, as soon as it shows resources in rancher, delete from rancher's end
* run import command on the import cluster, wait for cluster to come to active, then delete
* run import command on the import cluster, wait for cluster to start registering with rancher (after `waiting for api` log), then delete
* run import command on the import cluster, wait for cluster to start registering with rancher (after `waiting for api` log), then delete the cluster on the backend.  Also, after rancher health checks time out, delete it through rancher
however I did see what seems to be [an unrelated panic](https://github.com/rancher/rancher/issues/34971#issuecomment-946892840) early on (before importing a cluster)
