### ISSUE TITLE
updating rancher + changing rancher port : Not working - Failed to do service reconcile..

### ISSUE THREAD

**Issue by rvion** [rancher/rancher#3543]
I just updated rancher and in the same time, I changed rancher from port 8080 to port 80.

![image](https://cloud.githubusercontent.com/assets/2150990/12856828/151b5cb4-cc47-11e5-846b-cfeefdbbdf2a.png)

![image](https://cloud.githubusercontent.com/assets/2150990/12856838/24736648-cc47-11e5-8f01-9fca5f3e0e0c.png)

```
"processHandlerExecutions": [
{
"children": [ ],
"name": "ServiceUpdateActivate",
"startTime": 1454700280802,
"stopTime": 1454700280892,
"exception": {
"message": "Failed to do service reconcile for service [10]",
"clz": "java.lang.IllegalStateException",
"cause": null,
"stackTrace": "java.lang.IllegalStateException: Failed to do service reconcile for service [10]
at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl$1.doWithLock(DeploymentManagerImpl.java:130)
at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl$1.doWithLock(DeploymentManagerImpl.java:104)
at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl.activate(DeploymentManagerImpl.java:104)
at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl.activate(DeploymentManagerImpl.java:87)
at io.cattle.platform.servicediscovery.process.ServiceUpdateActivate.handle(ServiceUpdateActivate.java:57)
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:440)
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:387)
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:381)
at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42)
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:381)
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:487)
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:314)
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:254)
at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7)
at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3)
at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:251)
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:183)
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:156)
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:106)
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:103)
at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:103)
at io.cattle.platform.engine.eventing.impl.ProcessEventListenerImpl.processExecute(ProcessEventListenerImpl.java:66)
at sun.reflect.GeneratedMethodAccessor631.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at io.cattle.platform.eventing.annotation.MethodInvokingListener$1.doWithLockNoResult(MethodInvokingListener.java:76)
at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7)
at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3)
at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
at io.cattle.platform.eventing.annotation.MethodInvokingListener.onEvent(MethodInvokingListener.java:72)
at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135)
at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13)
at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108)
at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)\n",
},
"shouldContinue": false,
"shouldDelegate": false,
"chainProcessName": null,
},
],
```

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v0.57.0-rc5` Cattle: `v0.145.0` UI: `v0.89.0` |
|Access|`github` |
|Route|`null`|

**Comment by vincent99** [comment]
All your hosts need to re-register with the new (port 80) URL.. they are all in `reconnecting` state, and the service can't update because none of the containers can be reached.

**Comment by rvion** [comment]
@vincent99 Can't rancher server update the agents on each hosts itself ?

**Comment by vincent99** [comment]
The agent on the hosts opens the connection to the server, not the other way around. It works better with NAT, hosts that have no direct inbound access, etc this way and doesn't require the server to keep trying to connect to a host that's gone and never forever.  But if you move the server the agent need to know about it.  Using a DNS entry instead of an IP is a good idea, but doesn't help if it's the port you're changing.

**Comment by rvion** [comment]
it all makes sense.
I let you close this issue if you think that rancher doesn't need some tool to automatically reconfigure agents for now. I really think it would be useful, but I have no strong opinions, especially when I see all what's on your plate already :)
