### ISSUE TITLE
Convoy-nfs: unable to start container with docker 1.10

### ISSUE THREAD

**Issue by withinboredom** [rancher/rancher#3555]
Unable to start a container in docker 1.10 using convoy-nfs with data in a container... although I'm not sure how relevant that is. Other than when I add a volume that already has data in it, I cannot start the container.

In Docker 1.10, this issue was fixed: https://github.com/docker/docker/issues/18670

Looks remarkably like a permissions issue... going to go digging on my end.

Also, let me know if this isn't the right venue for this bug report:

Logs:

```
/6/2016 10:11:49 PM2016-02-07 03:11:49,723 ERROR [ad9a5c5a-4110-4eb3-ae91-0d8f560e361b:3708] [instance:77] [instance.start->(InstanceStart)] [] [cutorService-16] [i.c.p.process.instance.InstanceStart] Failed to Starting for instance [77]
2/6/2016 10:11:49 PM2016-02-07 03:11:49,732 ERROR [ad9a5c5a-4110-4eb3-ae91-0d8f560e361b:3708] [instance:77] [instance.start] [] [cutorService-16] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.eventing.exception.EventExecutionException: 500 Server Error: Internal Server Error ("chown /var/lib/rancher/convoy/convoy-nfs-cbbfc5ff-1034-4032-8ebc-25eff4fc8c66/mnt/blog: operation not permitted")
2/6/2016 10:11:49 PM    at io.cattle.platform.eventing.exception.EventExecutionException.fromEvent(EventExecutionException.java:53) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.agent.impl.RemoteAgentImpl.callSync(RemoteAgentImpl.java:72) ~[cattle-iaas-agent-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.agent.impl.RemoteAgentImpl.callSync(RemoteAgentImpl.java:158) ~[cattle-iaas-agent-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.process.common.handler.AgentBasedProcessHandler.callSync(AgentBasedProcessHandler.java:170) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.process.common.handler.AgentBasedProcessHandler.handleEvent(AgentBasedProcessHandler.java:156) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.process.common.handler.AgentBasedProcessHandler.handle(AgentBasedProcessHandler.java:101) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:440) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:387) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:381) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:381) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:487) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:314) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:254) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:251) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:183) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:156) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:106) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:103) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:103) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.executeStandardProcess(DefaultObjectProcessManager.java:29) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.process.common.handler.AbstractObjectProcessLogic.activate(AbstractObjectProcessLogic.java:31) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.process.instance.InstanceStart.compute(InstanceStart.java:216) ~[cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.process.instance.InstanceStart.handle(InstanceStart.java:84) ~[cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:440) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:387) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:381) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:381) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:487) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:314) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:254) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:251) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:183) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:156) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:106) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:103) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:103) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.engine.eventing.impl.ProcessEventListenerImpl.processExecute(ProcessEventListenerImpl.java:66) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at sun.reflect.GeneratedMethodAccessor430.invoke(Unknown Source) ~[na:na]
2/6/2016 10:11:49 PM    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_91]
2/6/2016 10:11:49 PM    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_91]
2/6/2016 10:11:49 PM    at io.cattle.platform.eventing.annotation.MethodInvokingListener$1.doWithLockNoResult(MethodInvokingListener.java:76) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.eventing.annotation.MethodInvokingListener.onEvent(MethodInvokingListener.java:72) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
2/6/2016 10:11:49 PM    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_91]
2/6/2016 10:11:49 PM    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_91]
2/6/2016 10:11:49 PM    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_91]
2/6/2016 10:11:49 PM
```

**Comment by Rucknar** [comment]
Docker 1.10 has seccomp enabled by default, just run into an issue around mounting NFS shares within a container. This now fails with 1.10 as CAP_SYS_ADMIN is no longer enough, you need to supply a custom seccomp profile with the syscalls allowed. Although we are approaching this without convoy, the above error looks pretty similar. 

Not sure rancher-compose yet supports seccomp profiles, i've not yet delved into them i'm afraid.

**Comment by cjellick** [comment]
Thanks for the report @Rucknar

**Comment by yasker** [comment]
Do you have any log for the container itself? And it only happened when volume has data in it?

I cannot reproduce the issue with my setup, even with Docker v1.10.2

**Comment by clamor** [comment]
I can reproduce this error using RancherOS v0.4.3 in a qemu/kvm VM. It works fine with RancherOS v.0.4.2 (docker-engine 1.9.1). Both new installs and empty volumes.

**Comment by willseward** [comment]
I'm seeing the same issue with Docker 1.10.3 and Rancher v1.0.1

**Comment by Berndinox** [comment]
Got the same issue, but after adding: "no_root_squash" in the exports conf, it does work. So it seems like an permissino issue?!

**Comment by willseward** [comment]
I had to add that as well.

**Comment by michaellopez** [comment]
We are hitting this too

**Comment by janeczku** [comment]
Docker tries to copy over ownership from the mount point in the image (if pre-existing) to the volume.
The default behavior of NFS is to squash the remote root user to an unprivileged user, hence the chown command executed by Docker on the NFS export mounted on the host fails.
Is there anything we can do to not require users to disable the root squash security feature in the NFS export? @cjellick

**Comment by sangeethah** [comment]
This issue is also seen with  docker 1.11.2.
Containers fail to start with error - ```500 Server Error: Internal Server Error (\"chown /var/lib/rancher/convoy/convoy-nfs-7d58fabe-a01a-47ae-a667-e581b1432671/mnt/4ccf7346006aaa03c4582a0313d2d435686d13bc4e6d83284df2f7a634a38b16: operation not permitted\")```

**Comment by galindro** [comment]
Any return about this issue? I could confirm it with RancherOS 0.7

**Comment by janeczku** [comment]
Either disable root squashing for the NFS export (`no_root_squash`) or use the `nocopy` option when specifying the volume, e.g. `vol_foo:/bar:nocopy`. See [here](https://docs.docker.com/engine/reference/run/#volume-shared-filesystems).

**Comment by will-chan** [comment]
Closing due to inactivity, please reopen if you think this is still relevant to current releases & important.  We are no longer supporting ConvoyNFS.  We use RancherNFS now so if issue still occurs there, let's reopen or file a new bug to track it.
