### ISSUE TITLE
Panic in rancher server while provisioning an RKE1 cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#35627]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `e322f8`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: 1.21
- Cluster Type (Local/Downstream): RKE1 DO cluster

**Describe the bug**

**To Reproduce**

- Provision a DO RKE1 cluster
- Rancher restarts with panic
- Logs in rancher server

```
2021/11/21 05:05:46 [INFO] Starting apps/v1, Kind=DaemonSet controller
2021/11/21 05:05:46 [INFO] Starting apps/v1, Kind=StatefulSet controller
2021/11/21 05:05:46 [INFO] Starting batch/v1, Kind=Job controller
2021/11/21 05:05:46 [INFO] Starting batch/v1beta1, Kind=CronJob controller
2021/11/21 05:05:46 [INFO] Starting apps/v1, Kind=ReplicaSet controller
2021/11/21 05:05:46 [INFO] Starting /v1, Kind=ReplicationController controller
2021/11/21 05:05:46 [INFO] Starting /v1, Kind=Service controller
2021/11/21 05:05:46 [INFO] Starting /v1, Kind=Event controller
2021/11/21 05:05:46 [INFO] Starting /v1, Kind=Pod controller
2021/11/21 05:05:46 [ERROR] error syncing 'c-9gkpz/p-b2qkv': handler system-image-upgrade-controller: upgrade cluster c-9gkpz system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [c-9gkpz] kubernetes version, requeuing
2021/11/21 05:05:46 [ERROR] error syncing 'local/p-5tcps': handler system-image-upgrade-controller: upgrade cluster local system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [local] kubernetes version, requeuing
2021/11/21 05:05:46 [ERROR] error syncing 'c-9gkpz/p-b2qkv': handler system-image-upgrade-controller: upgrade cluster c-9gkpz system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [c-9gkpz] kubernetes version, requeuing
2021/11/21 05:05:46 [ERROR] error syncing 'local/p-qfmbd': handler system-image-upgrade-controller: upgrade cluster local system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [local] kubernetes version, requeuing
2021/11/21 05:05:46 [ERROR] error syncing 'c-9gkpz/p-b2qkv': handler system-image-upgrade-controller: upgrade cluster c-9gkpz system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [c-9gkpz] kubernetes version, requeuing
2021/11/21 05:05:46 [ERROR] error syncing 'system-library': handler system-image-upgrade-catalog-controller: upgrade cluster local system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [local] kubernetes version, handler system-image-upgrade-catalog-controller: upgrade cluster c-9gkpz system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [c-9gkpz] kubernetes version, requeuing
2021/11/21 05:05:47 [ERROR] error syncing 'c-9gkpz/p-4vlrt': handler system-image-upgrade-controller: upgrade cluster c-9gkpz system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [c-9gkpz] kubernetes version, requeuing
2021/11/21 05:05:47 [ERROR] error syncing 'c-9gkpz/p-4vlrt': handler system-image-upgrade-controller: upgrade cluster c-9gkpz system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [c-9gkpz] kubernetes version, requeuing
2021/11/21 05:05:47 [INFO] Creating token for user user-fkd9n
2021/11/21 05:05:47 [INFO] kontainerdriver googlekubernetesengine listening on address 127.0.0.1:43461
2021/11/21 05:05:47 [INFO] kontainerdriver googlekubernetesengine stopped
2021/11/21 05:05:47 [INFO] dynamic schema for kontainerdriver googlekubernetesengine updating
time="2021-11-21 05:05:47" level=info msg="Telemetry Client v0.5.16"
time="2021-11-21 05:05:47" level=info msg="Listening on 0.0.0.0:8114"
2021/11/21 05:05:47 [INFO] kontainerdriver amazonelasticcontainerservice listening on address 127.0.0.1:41655
2021/11/21 05:05:47 [INFO] kontainerdriver amazonelasticcontainerservice stopped
2021/11/21 05:05:47 [INFO] dynamic schema for kontainerdriver amazonelasticcontainerservice updating
2021/11/21 05:05:47 [INFO] kontainerdriver azurekubernetesservice listening on address 127.0.0.1:38801
2021/11/21 05:05:47 [INFO] kontainerdriver azurekubernetesservice stopped
2021/11/21 05:05:47 [INFO] dynamic schema for kontainerdriver azurekubernetesservice updating
2021/11/21 05:05:47 [ERROR] error syncing 'c-9gkpz/p-b2qkv': handler system-image-upgrade-controller: upgrade cluster c-9gkpz system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [c-9gkpz] kubernetes version, requeuing
2021/11/21 05:05:47 [ERROR] error syncing 'c-9gkpz/p-4vlrt': handler system-image-upgrade-controller: upgrade cluster c-9gkpz system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [c-9gkpz] kubernetes version, requeuing
2021/11/21 05:05:47 [ERROR] error syncing 'c-9gkpz/p-b2qkv': handler system-image-upgrade-controller: upgrade cluster c-9gkpz system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [c-9gkpz] kubernetes version, requeuing
2021/11/21 05:05:47 [ERROR] error syncing 'c-9gkpz/p-4vlrt': handler system-image-upgrade-controller: upgrade cluster c-9gkpz system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [c-9gkpz] kubernetes version, requeuing
2021/11/21 05:05:48 [ERROR] error syncing 'local/p-5tcps': handler system-image-upgrade-controller: upgrade cluster local system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [local] kubernetes version, requeuing
2021/11/21 05:05:49 [ERROR] error syncing 'c-9gkpz/p-b2qkv': handler system-image-upgrade-controller: upgrade cluster c-9gkpz system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [c-9gkpz] kubernetes version, requeuing
2021/11/21 05:05:49 [ERROR] error syncing 'c-9gkpz/p-4vlrt': handler system-image-upgrade-controller: upgrade cluster c-9gkpz system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [c-9gkpz] kubernetes version, requeuing
2021/11/21 05:05:49 [ERROR] error syncing 'system-library': handler system-image-upgrade-catalog-controller: upgrade cluster local system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [local] kubernetes version, handler system-image-upgrade-catalog-controller: upgrade cluster c-9gkpz system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [c-9gkpz] kubernetes version, requeuing
2021/11/21 05:05:51 [ERROR] error syncing 'local/p-qfmbd': handler system-image-upgrade-controller: upgrade cluster local system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [local] kubernetes version, requeuing
2021/11/21 05:05:51 [ERROR] error syncing 'c-9gkpz/p-b2qkv': handler system-image-upgrade-controller: upgrade cluster c-9gkpz system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [c-9gkpz] kubernetes version, requeuing
2021/11/21 05:05:51 [ERROR] error syncing 'c-9gkpz/p-4vlrt': handler system-image-upgrade-controller: upgrade cluster c-9gkpz system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [c-9gkpz] kubernetes version, requeuing
2021/11/21 05:05:54 [ERROR] error syncing 'system-library': handler system-image-upgrade-catalog-controller: upgrade cluster local system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [local] kubernetes version, handler system-image-upgrade-catalog-controller: upgrade cluster c-9gkpz system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [c-9gkpz] kubernetes version, requeuing
2021/11/21 05:05:56 [ERROR] error syncing 'c-9gkpz/p-4vlrt': handler system-image-upgrade-controller: upgrade cluster c-9gkpz system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [c-9gkpz] kubernetes version, requeuing
2021/11/21 05:05:57 [ERROR] error syncing 'c-9gkpz/p-b2qkv': handler system-image-upgrade-controller: upgrade cluster c-9gkpz system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [c-9gkpz] kubernetes version, requeuing
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2b0daed]

goroutine 18262 [running]:
github.com/rancher/rancher/pkg/controllers/managementuser/healthsyncer.(*HealthSyncer).getComponentStatus(0xc0029036c0, 0xc008362700, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/healthsyncer/healthsyncer.go:89 +0x1ad
github.com/rancher/rancher/pkg/controllers/managementuser/healthsyncer.(*HealthSyncer).updateClusterHealth.func1(0x4439580, 0xc008362700, 0x44e4b04, 0x5)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/healthsyncer/healthsyncer.go:132 +0x6b
github.com/rancher/norman/condition.Cond.doInternal(0x44e4b04, 0x5, 0x4c6e101, 0x4c6e1e8, 0xc008362700, 0xc0071c5f20, 0x371e0d3, 0xd, 0x10, 0xc00c55eb60)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20211029152448-85ac7aa15a91/condition/condition.go:212 +0x9d
github.com/rancher/norman/condition.Cond.do2(0x44e4b04, 0x5, 0x101, 0x4c6e1e8, 0xc008362700, 0xc0071c5f20, 0x3a883c0, 0xc0056d1870, 0x198, 0x44e6829, ...)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20211029152448-85ac7aa15a91/condition/condition.go:181 +0x1dd
github.com/rancher/norman/condition.Cond.do(...)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20211029152448-85ac7aa15a91/condition/condition.go:170
github.com/rancher/norman/condition.Cond.Do(0x44e4b04, 0x5, 0x4c6e1e8, 0xc008362700, 0xc0071c5f20, 0x4, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20211029152448-85ac7aa15a91/condition/condition.go:140 +0x65
github.com/rancher/rancher/pkg/controllers/managementuser/healthsyncer.(*HealthSyncer).updateClusterHealth(0xc0029036c0, 0xc00c22c798, 0x37e11d601)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/healthsyncer/healthsyncer.go:130 +0x207
github.com/rancher/rancher/pkg/controllers/managementuser/healthsyncer.(*HealthSyncer).syncHealth(0xc0029036c0, 0x4cbf148, 0xc0091beb40, 0x37e11d600)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/healthsyncer/healthsyncer.go:70 +0xaf
created by github.com/rancher/rancher/pkg/controllers/managementuser/healthsyncer.Register
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/healthsyncer/healthsyncer.go:65 +0x278
2021/11/21 05:05:59 [INFO] Rancher version e322f8f82 (e322f8f82) is starting
2021/11/21 05:05:59 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features: ClusterRegistry:}
2021/11/21 05:05:59 [INFO] Listening on /tmp/log.sock

```

**Comment by cbron** [comment]
Bug with new component status code, version must be empty: https://github.com/rancher/rancher/blame/a39beeadcba4d2fa5c2e1686195e6d7c667ea3d2/pkg/controllers/managementuser/healthsyncer/healthsyncer.go#L89

**Comment by anupama2501** [comment]
Seeing this issue for RKE1 custom clusters on k8s 1.22.3-rancher1-1 
```
2021/11/22 16:00:57 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
2021/11/22 16:00:57 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2b0daed]

goroutine 74250 [running]:
github.com/rancher/rancher/pkg/controllers/managementuser/healthsyncer.(*HealthSyncer).getComponentStatus(0xc000f7d9d0, 0xc00ebeb500, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/healthsyncer/healthsyncer.go:89 +0x1ad
github.com/rancher/rancher/pkg/controllers/managementuser/healthsyncer.(*HealthSyncer).updateClusterHealth.func1(0x4439580, 0xc00ebeb500, 0x44e4b04, 0x5)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/healthsyncer/healthsyncer.go:132 +0x6b
github.com/rancher/norman/condition.Cond.doInternal(0x44e4b04, 0x5, 0x4c6e101, 0x4c6e1e8, 0xc00ebeb500, 0xc00d93df20, 0x371e0d3, 0xd, 0x10, 0xc014eb2dd8)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20211029152448-85ac7aa15a91/condition/condition.go:212 +0x9d
github.com/rancher/norman/condition.Cond.do2(0x44e4b04, 0x5, 0x101, 0x4c6e1e8, 0xc00ebeb500, 0xc00d93df20, 0x3a883c0, 0xc00a5866f0, 0x198, 0x44e6829, ...)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20211029152448-85ac7aa15a91/condition/condition.go:181 +0x1dd
github.com/rancher/norman/condition.Cond.do(...)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20211029152448-85ac7aa15a91/condition/condition.go:170
github.com/rancher/norman/condition.Cond.Do(0x44e4b04, 0x5, 0x4c6e1e8, 0xc00ebeb500, 0xc00d93df20, 0x4, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20211029152448-85ac7aa15a91/condition/condition.go:140 +0x65
github.com/rancher/rancher/pkg/controllers/managementuser/healthsyncer.(*HealthSyncer).updateClusterHealth(0xc000f7d9d0, 0xc00caf3f98, 0x37e11d601)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/healthsyncer/healthsyncer.go:130 +0x207
github.com/rancher/rancher/pkg/controllers/managementuser/healthsyncer.(*HealthSyncer).syncHealth(0xc000f7d9d0, 0x4cbf148, 0xc00a7506c0, 0x37e11d600)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/healthsyncer/healthsyncer.go:70 +0xaf
created by github.com/rancher/rancher/pkg/controllers/managementuser/healthsyncer.Register
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/healthsyncer/healthsyncer.go:65 +0x278
2021/11/22 16:00:59 [INFO] Rancher version e322f8f82 (e322f8f82) is starting
2021/11/22 16:00:59 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features: ClusterRegistry:}
```

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `4375161`**

- Deployed RKE1 EC2 node driver cluster. (Also had an EKS cluster downstream)
- Panic is not seen anymore. Will close the issue
