### ISSUE TITLE
[cli] rancher CLI v2.6.0 'rancher context switch' results in 'panic: ... nil pointer dereference'

### ISSUE THREAD

**Issue by nitram509** [rancher/rancher#36355]
**Rancher Server Setup**
* n/a
* CLI only - 

```
$> rancher --version
rancher version 2.6.0
```

**Information about the Cluster**
n/a

**User Information**
n/a

```
$> uname -a
Darwin host 19.6.0 Darwin Kernel Version 19.6.0: Sun Nov 14 19:58:51 PST 2021; root:xnu-6153.141.50~1/RELEASE_X86_64 x86_64
```

* Using MacOS 10.15.7
* used 'brew install rancher-cli'
   
**Describe the bug**
After a fresh installation I just run this simple command ....

```
$> rancher conter switch
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1473de6]

goroutine 1 [running]:
github.com/rancher/cli/cliclient.createClientOpts(...)
	github.com/rancher/cli/cliclient/cliclient.go:177
github.com/rancher/cli/cliclient.(*MasterClient).newManagementClient(0xc0002c8570)
	github.com/rancher/cli/cliclient/cliclient.go:103 +0x26
github.com/rancher/cli/cliclient.NewManagementClient(0x0)
	github.com/rancher/cli/cliclient/cliclient.go:59 +0x51
github.com/rancher/cli/cmd.contextSwitch(0xc0002ee2c0)
	github.com/rancher/cli/cmd/context.go:43 +0xe9
github.com/urfave/cli.HandleAction({0x16475a0, 0x17aa930}, 0x6)
	github.com/urfave/cli@v1.22.5/app.go:524 +0xa8
github.com/urfave/cli.Command.Run({{0x176dfed, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x177a2b3, 0x17}, {0x0, ...}, ...}, ...)
	github.com/urfave/cli@v1.22.5/command.go:173 +0x652
github.com/urfave/cli.(*App).RunAsSubcommand(0xc000196fc0, 0xc0002ee000)
	github.com/urfave/cli@v1.22.5/app.go:405 +0x9ec
github.com/urfave/cli.Command.startApp({{0x176e96e, 0x7}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x177c49f, 0x1a}, {0x0, ...}, ...}, ...)
	github.com/urfave/cli@v1.22.5/command.go:372 +0x6e9
github.com/urfave/cli.Command.Run({{0x176e96e, 0x7}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x177c49f, 0x1a}, {0x0, ...}, ...}, ...)
	github.com/urfave/cli@v1.22.5/command.go:102 +0x808
github.com/urfave/cli.(*App).Run(0xc000196e00, {0xc00007f500, 0x3, 0x4})
	github.com/urfave/cli@v1.22.5/app.go:277 +0x705
main.mainErr()
	github.com/rancher/cli/main.go:124 +0x1f9d
main.main()
	github.com/rancher/cli/main.go:56 +0x19
```

**To Reproduce**

See above.

**Result**

**Expected Result**

A user friendly error message, telling me, what I did wrong and how can I better do it.

**Comment by laurie-kepford** [comment]
I am having a similar problem.  Rancher cli 2.6.4
Works fine when I run it directly but I get this panic when I run it as part of a script.
