### ISSUE TITLE
Cannot launch machine on AWS - Seoul region

### ISSUE THREAD

**Issue by jloisel** [rancher/rancher#3636]
Hi,

version: v0.56.1
Issue: Rancher fails to launch machines in AWS Seoul region. It quickly fails with error message "exit status 1". There are the following logs been thrown by the server at very fast pace:

> 2016-02-16 17:29:49,347 ERROR [:] [] [] [] [cutorService-24] [i.c.p.e.e.i.ProcessEventListenerImpl] Unknown exception running process [instance.start:64581] on [2190] io.cattle.platform.eventing.exception.EventExecutionException: Can not start container with no image
	at io.cattle.platform.eventing.exception.EventExecutionException.fromEvent(EventExecutionException.java:53) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.agent.impl.RemoteAgentImpl.callSync(RemoteAgentImpl.java:72) ~[cattle-iaas-agent-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.agent.impl.RemoteAgentImpl.callSync(RemoteAgentImpl.java:158) ~[cattle-iaas-agent-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.common.handler.AgentBasedProcessHandler.callSync(AgentBasedProcessHandler.java:170) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.common.handler.AgentBasedProcessHandler.handleEvent(AgentBasedProcessHandler.java:156) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.common.handler.AgentBasedProcessHandler.handle(AgentBasedProcessHandler.java:101) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:440) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:387) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:381) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:381) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:487) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:314) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:254) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:251) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]

I can't put all the logs since there are too many. Let me know how i can help, if you need additional information.

**Comment by jloisel** [comment]
Same issue with Rancher v0.59.0 on another machine, with much more explicit log:

> ...time="2016-02-17T15:39:50Z" level=info msg="Cmd slice: [create -d amazonec2 --amazonec2-access-key <accessKey> --amazonec2-ami ami-xxxxxxxx --amazonec2-instance-type t2.micro --amazonec2-region ap-northeast-2 --amazonec2-root-size 8 --amazonec2-secret-key <secretKey> --amazonec2-security-group rancher-machine --amazonec2-subnet-id subnet-xxxxx --amazonec2-vpc-id vpc-xxxxxx --amazonec2-zone a seoul]" 
time="2016-02-17T15:39:50Z" level=info msg="stderr: Error setting machine configuration from flags provided: invalid region specified" resourceId=1ph26 
time="2016-02-17T15:39:50Z" level=info msg="starting cleanup..." machine name=seoul 
time="2016-02-17T15:39:50Z" level=error msg="Error processing event" err="exit status 1" eventId="bf3839af-71aa-4da3-a85b-87a6fb3b5034" eventName="physicalhost.create;handler=goMachineService" resourceId=xxxx

I have hidden some sensitive information coming from the logs. It's probably an issue with docker-machine bundled with rancher which does not support AWS Seoul yet.

**Comment by jloisel** [comment]
I've opened a pull-request to add support for AWS Seoul in Docker machine:
https://github.com/docker/machine/pull/3072

**Comment by cjellick** [comment]
Cool. Thanks @jloisel! We try to do a good job of keeping up with the docker machine releases, so when it lands in a release over there, it should be in a release of rancher pretty soon after.

**Comment by jloisel** [comment]
:+1: 

Thanks guys!

**Comment by jloisel** [comment]
Docker machine 0.7.0 with the fix is finally out:
https://github.com/docker/machine/releases/tag/v0.7.0

**Comment by tfiduccia** [comment]
Verison - Master 8/25
Verified - Can add AWS Seoul machine.
