### ISSUE TITLE
AKS-operator OMS agent panic

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#36425]
The aks-operator sets the omsAgent var. If the log analytics workspace returns an error we don't catch it properly. This can be tested by setting log analytics to something the service principle doesn't have access to. 
```
 Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
  goroutine 4486 [running]:
  k8s.io/apimachinery/pkg/util/runtime.logPanic(...)
  	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:74 +0x95
  k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
  	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:48 +0x86
  panic(0x3cde280, 0x6ec9b30)
  	/usr/local/go/src/runtime/panic.go:965 +0x1b9
  github.com/rancher/rancher/pkg/controllers/management/aks.(*aksOperatorController).onClusterChange(....)
  	/go/src/github.com/rancher/rancher/pkg/controllers/management/aks/aks_cluster_handler.go:183 +0xbf0
  github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3.FromClusterHandlerToHandler.func1(...)
  	/go/src/github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3/cluster.go:105 +0x6b
  github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(...)
```

Also, possibly related panic was observed in aks-operator:
```
E0207 04:41:05.814014      10 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:0, signed:true, code:0x0} (runtime error: index out of range [1] with length 0)
goroutine 531 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x14c2800, 0xc000a7e840)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/runtime/runtime.go:48 +0x86
panic(0x14c2800, 0xc000a7e840)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/rancher/aks-operator/controller.BuildUpstreamClusterState(0x1760678, 0xc0016d6ec0, 0x17609f8, 0xc000401bc0, 0x7fd89ebce080, 0xc0004081c0, 0xc0003865c8, 0xd18c2e2800, 0x3, 0x6fc23ac00)
	/go/src/github.com/rancher/aks-operator/controller/aks-cluster-config-handler.go:670 +0x125f
github.com/rancher/aks-operator/controller.(*Handler).checkAndUpdate(0xc00041c400, 0xc0003864b0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/aks-operator/controller/aks-cluster-config-handler.go:339 +0x55c
github.com/rancher/aks-operator/controller.(*Handler).OnAksConfigChanged(0xc00041c400, 0xc000045940, 0x1a, 0xc0003864b0, 0xc000dfd800, 0xc00004c800, 0xc000c6aad8)
	/go/src/github.com/rancher/aks-operator/controller/aks-cluster-config-handler.go:121 +0x9d
github.com/rancher/aks-operator/controller.(*Handler).recordError.func1(0xc000045940, 0x1a, 0xc0003864b0, 0xc000c6aba0, 0x5c6def, 0xc0004bb900)
	/go/src/github.com/rancher/aks-operator/controller/aks-cluster-config-handler.go:171 +0x67
github.com/rancher/aks-operator/pkg/generated/controllers/aks.cattle.io/v1.FromAKSClusterConfigHandlerToHandler.func1(0xc000045940, 0x1a, 0x1739d88, 0xc0003864b0, 0x7fd89efcea00, 0x20300000000000, 0xc000f26c18, 0x4eaeba)
	/go/src/github.com/rancher/aks-operator/pkg/generated/controllers/aks.cattle.io/v1/aksclusterconfig.go:105 +0x6b
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc00003a950, 0xc000045940, 0x1a, 0x1739d88, 0xc0003864b0, 0x1a, 0x756ea15039ce01, 0x40a43f, 0xc000030000)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc00041c380, 0xc000045940, 0x1a, 0x1739d88, 0xc0003864b0, 0xc001703d01, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/sharedhandler.go:69 +0x14c
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc00041e210, 0xc000045940, 0x1a, 0xc001703ee8, 0xc000f26da0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:215 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc00041e210, 0x13ce240, 0xc00167eeb0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:197 +0xe7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc00041e210, 0x203000)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:174 +0x54
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:163
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00167ef40)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00167ef40, 0x1734020, 0xc0016eab10, 0xc00167ee01, 0xc0004246c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00167ef40, 0x3b9aca00, 0x0, 0x1, 0xc0004246c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc00167ef40, 0x3b9aca00, 0xc0004246c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:134 +0x33b
panic: runtime error: index out of range [1] with length 0 [recovered]
	panic: runtime error: index out of range [1] with length 0

goroutine 531 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/runtime/runtime.go:55 +0x109
panic(0x14c2800, 0xc000a7e840)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/rancher/aks-operator/controller.BuildUpstreamClusterState(0x1760678, 0xc0016d6ec0, 0x17609f8, 0xc000401bc0, 0x7fd89ebce080, 0xc0004081c0, 0xc0003865c8, 0xd18c2e2800, 0x3, 0x6fc23ac00)
	/go/src/github.com/rancher/aks-operator/controller/aks-cluster-config-handler.go:670 +0x125f
github.com/rancher/aks-operator/controller.(*Handler).checkAndUpdate(0xc00041c400, 0xc0003864b0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/aks-operator/controller/aks-cluster-config-handler.go:339 +0x55c
github.com/rancher/aks-operator/controller.(*Handler).OnAksConfigChanged(0xc00041c400, 0xc000045940, 0x1a, 0xc0003864b0, 0xc000dfd800, 0xc00004c800, 0xc000c6aad8)
	/go/src/github.com/rancher/aks-operator/controller/aks-cluster-config-handler.go:121 +0x9d
github.com/rancher/aks-operator/controller.(*Handler).recordError.func1(0xc000045940, 0x1a, 0xc0003864b0, 0xc000c6aba0, 0x5c6def, 0xc0004bb900)
	/go/src/github.com/rancher/aks-operator/controller/aks-cluster-config-handler.go:171 +0x67
github.com/rancher/aks-operator/pkg/generated/controllers/aks.cattle.io/v1.FromAKSClusterConfigHandlerToHandler.func1(0xc000045940, 0x1a, 0x1739d88, 0xc0003864b0, 0x7fd89efcea00, 0x20300000000000, 0xc000f26c18, 0x4eaeba)
	/go/src/github.com/rancher/aks-operator/pkg/generated/controllers/aks.cattle.io/v1/aksclusterconfig.go:105 +0x6b
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc00003a950, 0xc000045940, 0x1a, 0x1739d88, 0xc0003864b0, 0x1a, 0x756ea15039ce01, 0x40a43f, 0xc000030000)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc00041c380, 0xc000045940, 0x1a, 0x1739d88, 0xc0003864b0, 0xc001703d01, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/sharedhandler.go:69 +0x14c
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc00041e210, 0xc000045940, 0x1a, 0xc001703ee8, 0xc000f26da0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:215 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc00041e210, 0x13ce240, 0xc00167eeb0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:197 +0xe7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc00041e210, 0x203000)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:174 +0x54
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:163
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00167ef40)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00167ef40, 0x1734020, 0xc0016eab10, 0xc00167ee01, 0xc0004246c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00167ef40, 0x3b9aca00, 0x0, 0x1, 0xc0004246c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc00167ef40, 0x3b9aca00, 0xc0004246c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:134 +0x33b
```

SURE-4034

**Comment by thedadams** [comment]
The problem, as I understand it, from where this was found was related to a permissions issue. The user that was creating the cluster had permissions to create the cluster in AKS, but not list the configuration for the omsAgent.

The problem is that it is assumed that the regex match [here](https://github.com/rancher/aks-operator/blob/master/controller/aks-cluster-config-handler.go#L670) and [here](https://github.com/rancher/aks-operator/blob/master/controller/aks-cluster-config-handler.go#L673) will have at least two matches. A check should be added in both places and something logical should happen (an error returned or the `omsAgent` config ignored).

**Comment by annablender** [comment]
## Testing template

#### Root cause

Customer has an Azure portal setup that returned a valid OMS agent profile but the configuration was somehow nil, empty or misconfigured. We check if an OMS agent profile exists in the code if logging analytics is enabled, but not if the configuration is valid.

#### What was fixed, or what changes have occurred

I added checks for a nil or empty OMS agent profile configuration. https://github.com/rancher/aks-operator/blob/7eec500b463848126ce1c9a322911fa11b191302/controller/aks-cluster-config-handler.go#L669

#### Areas or cases that should be tested
 
Add test code to a local copy of `rancher/aks-operator` simulating a nil or misconfigured OMS agent profile in an Azure portal setup
Run standalone `aks-operator`
Run an instance of Rancher v2.6-head and scale the ask-operator deployment count to 0
Create an AKS cluster through Rancher
Check that an invalid oms agent configuration error is seen in the UI

![image](https://user-images.githubusercontent.com/12955547/156077167-0730ce8f-e42e-4c7d-bc75-536c19c59d9b.png)

![image](https://user-images.githubusercontent.com/12955547/156077181-0007e729-40b2-41bc-b577-6f28723fe746.png)

#### What areas could experience regressions ?

Other weird edge cases of Azure returning misconfigured resources, possibly.
 
#### Are the repro steps accurate/minimal ?

Yes.

**Comment by timhaneunsoo** [comment]
After not being able to reproduce the issue and speaking with Dev team, these were the comments


For the AKS issue, there was a theory on how to reproduce it in the issue description but I couldn't figure out how to replicate it in Azure and we don't know what specifics of the customer's setup caused the bad response.

Basic P0 and an edit and upgrade usecases were all working as expected.
This issue will be reopened if this issue comes up again and is reproducible.
