### ISSUE TITLE
Rancher crashes when provisioning a RKE1 node driver cluster

### ISSUE THREAD

**Issue by sgapanovich** [rancher/rancher#36588]
**Rancher Server Setup**
- Rancher version: v2.6-head e55a04c
- Installation option (Docker install/Helm Chart): HA
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: self-signed
- RKE version for the local cluster: 1.3.7
- Local k8s: v1.22.6

**Information about the Cluster**
- Kubernetes version: v1.21.9-rancher1-2
- Cluster Type (Local/Downstream): Downstream 
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): RKE1 node driver (ec2)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Cluster Owner + Admin

**Describe the bug**

Rancher crashes when provisioning a RKE1 node driver with Rancher pods getting stuck in "CrashLoopBackOff" status

NOTE: i tried AWS and DO with rancher servers created from a scratch each time (because they become unusable)

**To Reproduce**
 
1. Create a HA Rancher
2. Create a standard user
3. Log in as the standard user
4. Add credentials + Node Template for aws
5. Create a RKE1 3 node  cluster (different roles)

**Result**
Infra created with no issues (instances are created and docker is installed as expected) but cluster never becomes Active and Rancher pod start to fail with Rancher server eventually becoming unavailable 

```
...
2022/02/21 01:18:52 [INFO] Provisioning cluster [c-46krd]
2022/02/21 01:18:52 [INFO] Creating cluster [c-46krd]
E0221 01:18:52.561696 32 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 5793 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3d478a0, 0x6fed760)
/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:48 +0x86
panic(0x3d478a0, 0x6fed760)
...
```
when checking a rancher pod's logs after one of restarts 
```
2022/02/21 00:40:38 [INFO] update kontainerdriver opentelekomcloudcontainerengine
2022/02/21 00:40:38 [INFO] getReleaseConfig: reloading config for rke2
2022/02/21 00:40:38 [INFO] Starting management.cattle.io/v3, Kind=GlobalDnsProvider controller
E0221 00:40:38.059411 32 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 5757 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3d478a0, 0x6fed760)
/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:74 +0x95
```

The Downstream cluster is stuck in "Provisioning" status

After some time Rancher is not reachable

```
 kubectl get po -n cattle-system -v 6
I0220 19:01:54.039991    4499 round_trippers.go:454] GET https://REDACTED/k8s/clusters/local/api?timeout=32s 503 Service Unavailable in 198 milliseconds
...
I0220 19:01:54.381588    4499 helpers.go:217] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "the server is currently unable to handle the request",
  "reason": "ServiceUnavailable",
  "details": {
    "causes": [
      {
        "reason": "UnexpectedServerResponse",
        "message": "\u003chtml\u003e\r\n\u003chead\u003e\u003ctitle\u003e503 Service Temporarily Unavailable\u003c/title\u003e\u003c/head\u003e\r\n\u003cbody\u003e\r\n\u003ccenter\u003e\u003ch1\u003e503 Service Temporarily Unavailable\u003c/h1\u003e\u003c/center\u003e\r\n\u003chr\u003e\u003ccenter\u003enginx\u003c/center\u003e\r\n\u003c/body\u003e\r\n\u003c/html\u003e"
      }
    ]
  },
  "code": 503
}]
F0220 19:01:54.382073    4499 helpers.go:116] Error from server (ServiceUnavailable): the server is currently unable to handle the request
```

**Expected Result**

- downstream RKE1 node driver is provisioned 
- Rancher is stable

**Screenshots**

![screen](https://user-images.githubusercontent.com/40282141/154873671-037cfa47-b790-4d2e-89a2-c24f22d13c32.jpg)
![fail](https://user-images.githubusercontent.com/40282141/154873692-0941c385-1ace-4138-b711-4bc8c0710457.jpg)

**Additional context**

**Comment by Josh-Diamond** [comment]
Steps to reproduce:
1. Create an instance and launch Rancher via docker
2. Attempt to provision ANY rke1 cluster within Rancher
3. Rancher server will drop and you will experience this issue, however instances on the specified service (linode, digitalocean, ec-2, etc) will be created

The following logs were documented when using Rancher v2.6-head with specified commit: `cccec97`:

```
2022/02/22 20:13:19 [INFO] [node-controller-rancher-machine] (jkeslarrr-cp1) Closing plugin on server side
2022/02/22 20:14:14 [INFO] Provisioning node jkeslarrr-cp1 done
2022/02/22 20:14:14 [INFO] Generating and uploading node config jkeslarrr-cp1
E0222 20:14:14.398850      33 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 3822 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3d47820, 0x6fed760)
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:48 +0x86
panic(0x3d47820, 0x6fed760)
	/usr/lib64/go/1.16/src/runtime/panic.go:965 +0x1b9
github.com/rancher/rancher/pkg/controllers/management/secretmigrator.AssembleS3Credential(0xc0094a2000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/secretmigrator/assemblers.go:53 +0x94
github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner.(*Provisioner).driverCreate(0xc005818340, 0xc0094a2000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner/driver.go:26 +0x1cc
github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner.(*Provisioner).reconcileCluster(0xc005818340, 0xc0094a2000, 0x3b05301, 0xc00a9a9b70, 0x198, 0x198)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner/provisioner.go:530 +0x1a7a
github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner.(*Provisioner).update(0xc005818340, 0xc0094a2000, 0x4574001, 0x6, 0x4576a9e, 0x7)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner/provisioner.go:354 +0x45
2022/02/22 20:14:14 [INFO] Provisioning cluster [c-vvcd8]
2022/02/22 20:14:14 [INFO] Creating cluster [c-vvcd8]
github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner.(*Provisioner).provision.func1(0x44c3d20, 0xc0094a2000, 0x45824e9, 0xb)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner/provisioner.go:414 +0x38
github.com/rancher/norman/condition.Cond.doInternal(0x45824e9, 0xb, 0x4d3a801, 0x4d3a8c8, 0xc0094a2000, 0xc00de3f620, 0x3b0a3a0, 0x384e084, 0x18, 0x50)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/norman@v0.0.0-20220107203912-4feb41eafabd/condition/condition.go:212 +0x9d
github.com/rancher/norman/condition.Cond.do2(0x45824e9, 0xb, 0x1, 0x4d3a8c8, 0xc0094a2000, 0xc00de3f620, 0x45be650, 0x7, 0x3b0a3a0, 0xc00a9a9c10, ...)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/norman@v0.0.0-20220107203912-4feb41eafabd/condition/condition.go:181 +0x1dd
github.com/rancher/norman/condition.Cond.do(...)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/norman@v0.0.0-20220107203912-4feb41eafabd/condition/condition.go:170
github.com/rancher/norman/condition.Cond.Do(0x45824e9, 0xb, 0x4d3a8c8, 0xc0094a2000, 0xc00de3f620, 0x1, 0x0, 0x0, 0xc00a9a9c10)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/norman@v0.0.0-20220107203912-4feb41eafabd/condition/condition.go:140 +0x65
github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner.(*Provisioner).provision(0xc005818340, 0xc0094a2000, 0xc0094a2000, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner/provisioner.go:413 +0x86
github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner.(*Provisioner).Create(0xc005818340, 0xc0094a2000, 0x0, 0xffffffffffffffff, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner/provisioner.go:409 +0x18d
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*clusterLifecycleAdapter).Create(0xc00510ff70, 0x4d3a8c8, 0xc0094a2000, 0xc0094a2270, 0x0, 0x8000105, 0x0)
	/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_cluster_lifecycle_adapter.go:31 +0x55
github.com/rancher/norman/lifecycle.checkNil(0x4d3a8c8, 0xc0094a2000, 0xc00de3f8c0, 0xc00bab1800, 0x0, 0x0, 0x3e0f0e0)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/norman@v0.0.0-20220107203912-4feb41eafabd/lifecycle/object.go:191 +0x3e
github.com/rancher/norman/lifecycle.(*objectLifecycleAdapter).record(0xc00366edb0, 0x4d3a8c8, 0xc00bab1800, 0xc00de3f8c0, 0xc00510ff70, 0x1, 0x0, 0xc002697780)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/norman@v0.0.0-20220107203912-4feb41eafabd/lifecycle/object.go:181 +0xcf
github.com/rancher/norman/lifecycle.(*objectLifecycleAdapter).create(0xc00366edb0, 0x4d3a8c8, 0xc00bab1800, 0x0, 0x0, 0xc00bab1801, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/norman@v0.0.0-20220107203912-4feb41eafabd/lifecycle/object.go:219 +0x29e
github.com/rancher/norman/lifecycle.(*objectLifecycleAdapter).sync(0xc00366edb0, 0xc00b99fa30, 0x7, 0x44c3d20, 0xc00bab1800, 0x3e17ce0, 0x7fc136b02e50, 0xc00de3fa48, 0x40dc1b)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/norman@v0.0.0-20220107203912-4feb41eafabd/lifecycle/object.go:64 +0x1d0
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.NewClusterLifecycleAdapter.func1(0xc00b99fa30, 0x7, 0xc00bab1800, 0x10, 0x3b09220, 0x1, 0xc000204620)
	/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_cluster_lifecycle_adapter.go:61 +0x53
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*clusterController).AddHandler.func1(0xc00b99fa30, 0x7, 0x44c3d20, 0xc00bab1800, 0xc00de3fb58, 0x3, 0x3, 0x0)
	/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_cluster_controller.go:155 +0x67
github.com/rancher/norman/controller.(*genericController).AddHandler.func1(0xc00b99fa30, 0x7, 0x4d3a8c8, 0xc00bab1800, 0xc00bab1800, 0x4dedbf0, 0xc00bab1800, 0x1)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/norman@v0.0.0-20220107203912-4feb41eafabd/controller/generic_controller.go:62 +0x224
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc00366ede0, 0xc00b99fa30, 0x7, 0x4d3a8c8, 0xc00bab1800, 0x0, 0xc00bab1800, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220110205840-98715bdd6b5b/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000451680, 0xc00b99fa30, 0x7, 0x4d3a8c8, 0xc00bab1800, 0xc004ba9601, 0x0)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220110205840-98715bdd6b5b/pkg/controller/sharedhandler.go:69 +0x14c
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000e1ac60, 0xc00b99fa30, 0x7, 0xc004ba9798, 0x0)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220110205840-98715bdd6b5b/pkg/controller/controller.go:218 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000e1ac60, 0x3b0a3a0, 0xc00a145190, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220110205840-98715bdd6b5b/pkg/controller/controller.go:200 +0xe7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000e1ac60, 0x203001)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220110205840-98715bdd6b5b/pkg/controller/controller.go:177 +0x54
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220110205840-98715bdd6b5b/pkg/controller/controller.go:166
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000bb5780)
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000bb5780, 0x4d120c0, 0xc002bb6390, 0x2c7d7b3a22737501, 0xc000074360)
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000bb5780, 0x3b9aca00, 0x0, 0x69736e6574786501, 0xc000074360)
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc000bb5780, 0x3b9aca00, 0xc000074360)
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220110205840-98715bdd6b5b/pkg/controller/controller.go:134 +0x35b
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x29d5bd4]

goroutine 3822 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:55 +0x109
panic(0x3d47820, 0x6fed760)
	/usr/lib64/go/1.16/src/runtime/panic.go:965 +0x1b9
github.com/rancher/rancher/pkg/controllers/management/secretmigrator.AssembleS3Credential(0xc0094a2000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/secretmigrator/assemblers.go:53 +0x94
github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner.(*Provisioner).driverCreate(0xc005818340, 0xc0094a2000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner/driver.go:26 +0x1cc
github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner.(*Provisioner).reconcileCluster(0xc005818340, 0xc0094a2000, 0x3b05301, 0xc00a9a9b70, 0x198, 0x198)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner/provisioner.go:530 +0x1a7a
github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner.(*Provisioner).update(0xc005818340, 0xc0094a2000, 0x4574001, 0x6, 0x4576a9e, 0x7)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner/provisioner.go:354 +0x45
github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner.(*Provisioner).provision.func1(0x44c3d20, 0xc0094a2000, 0x45824e9, 0xb)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner/provisioner.go:414 +0x38
github.com/rancher/norman/condition.Cond.doInternal(0x45824e9, 0xb, 0x4d3a801, 0x4d3a8c8, 0xc0094a2000, 0xc00de3f620, 0x3b0a3a0, 0x384e084, 0x18, 0x50)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/norman@v0.0.0-20220107203912-4feb41eafabd/condition/condition.go:212 +0x9d
github.com/rancher/norman/condition.Cond.do2(0x45824e9, 0xb, 0x1, 0x4d3a8c8, 0xc0094a2000, 0xc00de3f620, 0x45be650, 0x7, 0x3b0a3a0, 0xc00a9a9c10, ...)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/norman@v0.0.0-20220107203912-4feb41eafabd/condition/condition.go:181 +0x1dd
github.com/rancher/norman/condition.Cond.do(...)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/norman@v0.0.0-20220107203912-4feb41eafabd/condition/condition.go:170
github.com/rancher/norman/condition.Cond.Do(0x45824e9, 0xb, 0x4d3a8c8, 0xc0094a2000, 0xc00de3f620, 0x1, 0x0, 0x0, 0xc00a9a9c10)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/norman@v0.0.0-20220107203912-4feb41eafabd/condition/condition.go:140 +0x65
github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner.(*Provisioner).provision(0xc005818340, 0xc0094a2000, 0xc0094a2000, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner/provisioner.go:413 +0x86
github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner.(*Provisioner).Create(0xc005818340, 0xc0094a2000, 0x0, 0xffffffffffffffff, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner/provisioner.go:409 +0x18d
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*clusterLifecycleAdapter).Create(0xc00510ff70, 0x4d3a8c8, 0xc0094a2000, 0xc0094a2270, 0x0, 0x8000105, 0x0)
	/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_cluster_lifecycle_adapter.go:31 +0x55
github.com/rancher/norman/lifecycle.checkNil(0x4d3a8c8, 0xc0094a2000, 0xc00de3f8c0, 0xc00bab1800, 0x0, 0x0, 0x3e0f0e0)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/norman@v0.0.0-20220107203912-4feb41eafabd/lifecycle/object.go:191 +0x3e
github.com/rancher/norman/lifecycle.(*objectLifecycleAdapter).record(0xc00366edb0, 0x4d3a8c8, 0xc00bab1800, 0xc00de3f8c0, 0xc00510ff70, 0x1, 0x0, 0xc002697780)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/norman@v0.0.0-20220107203912-4feb41eafabd/lifecycle/object.go:181 +0xcf
github.com/rancher/norman/lifecycle.(*objectLifecycleAdapter).create(0xc00366edb0, 0x4d3a8c8, 0xc00bab1800, 0x0, 0x0, 0xc00bab1801, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/norman@v0.0.0-20220107203912-4feb41eafabd/lifecycle/object.go:219 +0x29e
github.com/rancher/norman/lifecycle.(*objectLifecycleAdapter).sync(0xc00366edb0, 0xc00b99fa30, 0x7, 0x44c3d20, 0xc00bab1800, 0x3e17ce0, 0x7fc136b02e50, 0xc00de3fa48, 0x40dc1b)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/norman@v0.0.0-20220107203912-4feb41eafabd/lifecycle/object.go:64 +0x1d0
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.NewClusterLifecycleAdapter.func1(0xc00b99fa30, 0x7, 0xc00bab1800, 0x10, 0x3b09220, 0x1, 0xc000204620)
	/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_cluster_lifecycle_adapter.go:61 +0x53
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*clusterController).AddHandler.func1(0xc00b99fa30, 0x7, 0x44c3d20, 0xc00bab1800, 0xc00de3fb58, 0x3, 0x3, 0x0)
	/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_cluster_controller.go:155 +0x67
github.com/rancher/norman/controller.(*genericController).AddHandler.func1(0xc00b99fa30, 0x7, 0x4d3a8c8, 0xc00bab1800, 0xc00bab1800, 0x4dedbf0, 0xc00bab1800, 0x1)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/norman@v0.0.0-20220107203912-4feb41eafabd/controller/generic_controller.go:62 +0x224
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc00366ede0, 0xc00b99fa30, 0x7, 0x4d3a8c8, 0xc00bab1800, 0x0, 0xc00bab1800, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220110205840-98715bdd6b5b/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000451680, 0xc00b99fa30, 0x7, 0x4d3a8c8, 0xc00bab1800, 0xc004ba9601, 0x0)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220110205840-98715bdd6b5b/pkg/controller/sharedhandler.go:69 +0x14c
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000e1ac60, 0xc00b99fa30, 0x7, 0xc004ba9798, 0x0)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220110205840-98715bdd6b5b/pkg/controller/controller.go:218 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000e1ac60, 0x3b0a3a0, 0xc00a145190, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220110205840-98715bdd6b5b/pkg/controller/controller.go:200 +0xe7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000e1ac60, 0x203001)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220110205840-98715bdd6b5b/pkg/controller/controller.go:177 +0x54
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220110205840-98715bdd6b5b/pkg/controller/controller.go:166
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000bb5780)
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000bb5780, 0x4d120c0, 0xc002bb6390, 0x2c7d7b3a22737501, 0xc000074360)
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000bb5780, 0x3b9aca00, 0x0, 0x69736e6574786501, 0xc000074360)
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc000bb5780, 0x3b9aca00, 0xc000074360)
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220110205840-98715bdd6b5b/pkg/controller/controller.go:134 +0x35b
```

**Comment by sgapanovich** [comment]
### Test Environment: ###
Rancher version: v2.6-head 8c785a1
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE1 node driver clusters
Downstream K8s version: different versions (see screenshot below)

----------

### Testing: ###
1. Provision aws, do, linode, azure node drivers
![clusters](https://user-images.githubusercontent.com/40282141/155600949-180c714f-546f-41ae-b097-2c9028ac9636.jpg)
2. Scale nodes up and down
3. Delete clusters

All clusters/nodes are provisioning as expected 
note: the issue is created while testing this issue https://github.com/rancher/rancher/issues/36640
