### ISSUE TITLE
Ability to pull rancher images from a self-hosted registry

### ISSUE THREAD

**Issue by laosb** [rancher/rancher#3662]
Our hosts are having connection problems with Docker Hub because of the special Internet limitations in China. To improve the availability of the service, we are planning to clone rancher images from Docker Hub so hosts can pull them from our own registry. If we could set a default registry of racncher images, this can be solved.

**Comment by deniseschannon** [comment]
You can read about how to launch Rancher server without internet here:
http://docs.rancher.com/rancher/installing-rancher/installing-server/no-internet-access/

Please note that right now we don't have the ability to use the catalog without internet access.

**Comment by wstam88** [comment]
You can add/config your own registries in Rancher already; 
Read more here: http://docs.rancher.com/rancher/configuration/registries/

**Comment by mtrofimm** [comment]
@wstam88  @deniseschannon  can you help with my private registry secured trusted ssl cert (docker login https://myregistry.domain.com works fine on the host. 
I added my registry in web gui together with necessary auth.

When I try to use image from my registry in agent logs I get:
```
2016-02-21 20:13:35,799 ERROR agent [139842942469456] [event.py:112] Error in request : ccdafca3-1cec-425f-b98f-144d97b722f2 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 34, in execute
    return method(req=req, **req.data.__dict__)
  File "/var/lib/cattle/pyagent/cattle/storage/__init__.py", line 27, in image_activate
    action=lambda: self._do_image_activate(image, storage_pool,
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 72, in _do
    action()
  File "/var/lib/cattle/pyagent/cattle/storage/__init__.py", line 28, in <lambda>
    progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/storage.py", line 160, in _do_image_activate
    raise e
ImageValidationError: Image [myregistry.domain.com/app/web:release-1-t5] failed to pull: Authentication is required.
