### ISSUE TITLE
Worker nodes unable to start up due to missing files

### ISSUE THREAD

**Issue by HansAarneLiblik** [rancher/rancher#36680]
**Rancher Server Setup**
- Rancher version: 2.6.0
- Installation option (Docker install/Helm Chart): Single-node Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: Self-signed

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? Admin

   
**Describe the bug**
Working rancher instance with a single cluster consisting of 3x worker & 3x etc/control plane nodes.
Node VMs had to be migrated.
**etc/controlplane** nodes migrated without issue (had to do clean install due to not having persistent `/etc/kubernetes`)

While migrating **worker** node (Same clean install: Delete from Rancher, redeploy VM, execute `register node` command) kubelet restarts constantly with exception

**Flow 1: (mounted persistent /etc/kubernetes)**
`sudo docker run -d --privileged --restart=unless-stopped --net=host -v /opt/local/etc/kubernetes:/etc/kubernetes -v /var/run:/var/run  rancher/rancher-agent:v2.6.0 --server https://<RANCHER-SERVER.DOMAIN> --token <TOKEN> --ca-checksum <CA_CHECKSUM> --worker`

> $ docker logs kubelet
....
F0301 12:18:26.288859   19994 server.go:257] unable to load client CA file /etc/kubernetes/ssl/kube-ca.pem: open /etc/kubernetes/ssl/kube-ca.pem: no such file or directory
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc00012c001, 0xc0001a81c0, 0xac, 0x1b2)
....

> $ docker logs share-mnt
...
time="2022-03-01T12:19:55Z" level=fatal msg="Certificate chain is not complete, please check if all needed intermediate certificates are included in the server certificate (in the correct order) and if the cacerts setting in Rancher either contains the correct CA certificate (in the case of using self signed certificates) or is empty (in the case of using a certificate signed by a recognized CA). Certificate information is displayed above. error: Get \"https://<RANCHER-SERVER.DOMAIN>\": x509: certificate signed by unknown authority"

> $ ls -la /opt/local/etc/kubernetes/
total 12
drwxr-xr-x 3 root root 4096 Mar  1 12:04 .
drwxr-xr-x 3 root root 4096 Mar  1 12:04 ..
-rw------- 1 root root    0 Mar  1 12:04 cloud-config
drwxr-xr-x 3 root root 4096 Mar  1 12:04 ssl

> $ ls -la /opt/local/etc/kubernetes/ssl/
total 12
drwx------ 2 root root 4096 Mar  1 12:04 .
drwxr-xr-x 3 root root 4096 Mar  1 12:04 ..
drwx------ 2 root root 4096 Mar  1 12:04 certs

> $ ls -la /etc/kubernetes/
total 16
drwxr-xr-x   2 root root  4096 Mar  1 12:05 .
drwxr-xr-x. 99 root root 12288 Mar  1 12:05 ..

**Flow 2: (Without persistent /etc/kubernetes)**
`sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run  rancher/rancher-agent:v2.6.0 --server https://<RANCHER-SERVER.DOMAIN> --token <TOKEN> --ca-checksum <CA_CHECKSUM> --worker`

> $ docker logs kubelet
....
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc00012c001, 0xc0001a81c0, 0xac, 0x1b2)
F0301 12:31:48.678865   11535 server.go:257] unable to load client CA file /etc/kubernetes/ssl/kube-ca.pem: open /etc/kubernetes/ssl/kube-ca.pem: no such file or directory
goroutine 1 [running]:
....

_(share-mnt does not exist)_

> $ ls -la /etc/kubernetes/
total 20
drwxr-xr-x   3 root root  4096 Mar  1 12:30 .
drwxr-xr-x. 99 root root 12288 Mar  1 12:30 ..
-rw-------   1 root root     0 Mar  1 12:30 cloud-config
drwxr-xr-x   3 root root  4096 Mar  1 12:30 ssl

> $ ls -la /etc/kubernetes/ssl/
total 12
drwxr-xr-x 3 root root 4096 Mar  1 12:30 .
drwxr-xr-x 3 root root 4096 Mar  1 12:30 ..
drwx------ 2 root root 4096 Mar  1 12:30 certs

**Expected result**
Not have any missing files files.
Worker and etc/controlplane VM setups are identical and there are no missing files in etc/controlplane VMs (Though, it also keeps it's file in `/etc/kubernetes` rather than in my defined mount `/opt/local/etc/kubernetes`)
> $ ls -la /etc/kubernetes/ssl/
total 124
drwxr-xr-x 3 root root 4096 Mar  1 08:10 .
drwxr-xr-x 3 root root 4096 Mar  1 10:27 ..
drwx------ 2 root root 4096 Mar  1 08:10 certs
-rw------- 1 root root 1675 Mar  1 08:30 kube-apiserver-key.pem
-rw------- 1 root root 1675 Mar  1 08:30 kube-apiserver-proxy-client-key.pem
-rw------- 1 root root 1107 Mar  1 08:30 kube-apiserver-proxy-client.pem
-rw------- 1 root root 1679 Mar  1 08:30 kube-apiserver-requestheader-ca-key.pem
-rw------- 1 root root 1082 Mar  1 08:30 kube-apiserver-requestheader-ca.pem
-rw------- 1 root root 1310 Mar  1 08:30 kube-apiserver.pem
-rw------- 1 root root 1675 Mar  1 08:30 kube-ca-key.pem
-rw------- 1 root root 1017 Mar  1 08:30 kube-ca.pem
...
...

**Comment by HansAarneLiblik** [comment]
This issue fixes itself, after I copy the missing files from currently still working node (Not yet restarted) to the new broken node, but this is not a sustainable solution

**Comment by HansAarneLiblik** [comment]
Managed to get the files to our local mount (/opt/local/etc/kubernetes), but kubelet and others do not read from there.

Have to manually copy the files to /etc/kubernetes
