### ISSUE TITLE
Cannot add new host

### ISSUE THREAD

**Issue by pedrommone** [rancher/rancher#3678]
This host was running an Ranher agent pretty well, but containers started get fucked but and I had to upgrade it to newest docker to fix an networking issue. Now with an new an fresh ubuntu 14.04 deployed I cannot register the host as an agent again.

Version: 

1. Docker version 1.10.2, build c3959b1
2. Rancher v0.59.0
3. Cattle v0.148.0

Steps: 

`sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher -e CATTLE_AGENT_IP=69.197.179.98 rancher/agent:v0.9.2 http://rancher.hiddenaddress.com:8080/v1/scripts/38C62E9C48A701DD4827:1456203600000:VGKG9t6Wm9K8SmgcbiJogPE8JI
`

Results: 

```
root@11:~# docker logs -f d5a8387c2ecf1646e40ed31f45d9623e7c8ddc9c81947b2085f91cfe12cd5a0b 

INFO: Running Agent Registration Process, CATTLE_URL=http://rancher.hiddenaddress.com:8080/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.10.2
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.10.2
INFO: docker version: Server API version: 1.22
INFO: docker version: Go version (server): go1.5.3
INFO: docker version: Git commit (server): c3959b1
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker info: Containers: 8
INFO: docker info: Images: 2
INFO: docker info: Storage Driver: aufs
INFO: docker info: Root Dir: /var/lib/docker/aufs
INFO: docker info: Backing Filesystem: extfs
INFO: docker info: Dirs: 58
INFO: docker info: Dirperm1 Supported: false
INFO: docker info: Execution Driver: native-0.2
INFO: docker info: Kernel Version: 3.13.0-77-generic
INFO: docker info: Operating System: Ubuntu 14.04.4 LTS
INFO: docker info: CPUs: 4
INFO: docker info: Total Memory: 31.37 GiB
INFO: docker info: Name: 11.servers.hiddenaddress.com
INFO: docker info: ID: PW4G:YADX:LZVT:SJRB:KUCE:WFK5:VA2C:IDFR:OYWA:CWFB:PPKT:FJBS
INFO: docker info: Http Proxy:
INFO: docker info: Https Proxy:
INFO: docker info: No Proxy:
WARNING: No swap limit support
INFO: Attempting to connect to: http://rancher.hiddenaddress.com:8080/v1
INFO: http://rancher.hiddenaddress.com:8080/v1 is accessible
INFO: Inspecting host capabilities
INFO: System: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
Traceback (most recent call last):
  File "./register.py", line 27, in <module>
    r = client.wait_success(r)
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 15, in wait_success
    obj = self.wait_transitioning(obj, timeout)
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 33, in wait_transitioning
    raise Exception(msg)
Exception: Timeout waiting for [register:1go1681] to be done after 46.9105370045 seconds
```

I've tried remove the agent images, remove state and networking directory. Run it with cattle IP agent and nothing make it finish the registration.

**Comment by pedrommone** [comment]
I've deployed an Ubuntu 14.04 at DigitalOcean and installed only Docker 1.10.1 and the issue persist on the same way.

´´´
root@ubuntu-512mb-nyc3-01:~# docker logs -f 4a

INFO: Running Agent Registration Process, CATTLE_URL=http://rancher.hidden.com:8080/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.10.2
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.10.2
INFO: docker version: Server API version: 1.22
INFO: docker version: Go version (server): go1.5.3
INFO: docker version: Git commit (server): c3959b1
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker info: Containers: 1
INFO: docker info: Images: 1
INFO: docker info: Storage Driver: aufs
INFO: docker info: Root Dir: /var/lib/docker/aufs
INFO: docker info: Backing Filesystem: extfs
INFO: docker info: Dirs: 21
INFO: docker info: Dirperm1 Supported: false
INFO: docker info: Execution Driver: native-0.2
INFO: docker info: Kernel Version: 3.13.0-77-generic
INFO: docker info: Operating System: Ubuntu 14.04.3 LTS
INFO: docker info: CPUs: 1
INFO: docker info: Total Memory: 490 MiB
INFO: docker info: Name: ubuntu-512mb-nyc3-01
INFO: docker info: ID: HL3G:CSQJ:P5ZI:JJ4H:7ZZ6:GVIF:5LVJ:Y33X:E2D4:R3BK:6G5Z:QLNW
INFO: docker info: Http Proxy:
INFO: docker info: Https Proxy:
INFO: docker info: No Proxy:
INFO: Attempting to connect to: http://rancher.hidden.com:8080/v1
WARNING: No swap limit support
INFO: http://rancher.hidden.com:8080/v1 is accessible
INFO: Inspecting host capabilities
INFO: System: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
Traceback (most recent call last):
  File "./register.py", line 31, in <module>
    r = client.wait_success(r)
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 15, in wait_success
    obj = self.wait_transitioning(obj, timeout)
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 33, in wait_transitioning
    raise Exception(msg)
Exception: Timeout waiting for [register:1go1685] to be done after 46.1150448322 seconds

´´´

**Comment by ibuildthecloud** [comment]
@pedrommone There is a possibility that your Rancher server is overwhelmed with tasks and can not complete the registration in time.  Can you look at the Admin->Processes page and see if there are a lot of "Running" tasks?

**Comment by pedrommone** [comment]
here we go

[](http://i.imgur.com/n4DOrPq.png)

**Comment by deniseschannon** [comment]
@pedrommone Have these processes cleared up so that you could try adding rancher/agent again?

**Comment by pedrommone** [comment]
We're created the whole environment again.

**Comment by deniseschannon** [comment]
Can we close it as it seems that the number of open of processes caused your issue? If you get into that state again, we can re-open and debug more. What do you think?

**Comment by pedrommone** [comment]
Its fine for me, but, is there a way to clean the queue of jobs? Or I need to wait?

**Comment by timbrand** [comment]
I'm having this exact same issue too.
Steps I took:
- Created new environment, for Kubernetes;
- Added 2 hosts, successfully (without entering the IPs);
- Deactivated the 2 hosts and deleted them;
- Stopped and removed all containers on both hosts;
- Add the host back again, including the cattle agent IP definition.
After that, the hosts fails to register:
`INFO: Running registration
Traceback (most recent call last):
  File "./register.py", line 31, in <module>
    r = client.wait_success(r, timeout=300)
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 15, in wait_success
    obj = self.wait_transitioning(obj, timeout)
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 33, in wait_transitioning
    raise Exception(msg)
Exception: Timeout waiting for [register:1r10] to be done after 300.56922102 seconds`

**Comment by timbrand** [comment]
I'm having a really hard time to deactivate the environment. Event full refresh of the UI is getting hard.

Some logs of the server node (which is a separated vm)
`2016-12-12 14:04:48,337 ERROR [3974c3e7-48a3-4157-8862-979de5c449a6:135694] [instance:11522] [instance.start->(InstanceStart)] [] [cutorService-10] [i.c.p.process.instance.InstanceStart] Failed to Waiting for dependencies for instance [11522]
2016-12-12 14:04:49,672 ERROR [b011c1e5-6a06-4a32-927c-0e184a674271:135699] [instance:11523] [instance.start->(InstanceStart)] [] [ecutorService-6] [i.c.p.process.instance.InstanceStart] Failed to Waiting for dependencies for instance [11523]
2016-12-12 14:04:53,487 ERROR [66580046-1928-4ed8-a9cc-02949064b28c:135700] [instance:11521] [instance.start->(InstanceStart)] [] [ecutorService-5] [i.c.p.process.instance.InstanceStart] Failed to Waiting for dependencies for instance [11521]
2016-12-12 14:04:53,586 ERROR [916b2c19-0127-4eb0-adca-f7af0d2988d8:135707] [instance:11525] [instance.start->(InstanceStart)] [] [ecutorService-8] [i.c.p.process.instance.InstanceStart] Failed to Waiting for dependencies for instance [11525]
2016-12-12 14:04:53,626 ERROR [61ba732d-8b43-4222-b438-a8cf4768dba0:135709] [instance:11527] [instance.start->(InstanceStart)] [] [cutorService-17] [i.c.p.process.instance.InstanceStart] Failed to Waiting for dependencies for instance [11527]
2016-12-12 14:04:53,699 ERROR [ea9f5862-9af0-471f-a378-eff6d8f3f03d:135719] [instance:11529] [instance.start->(InstanceStart)] [] [cutorService-15] [i.c.p.process.instance.InstanceStart] Failed to Waiting for dependencies for instance [11529]
2016-12-12 14:05:09,153 ERROR [ef4bb75c-2bdb-4ad5-a248-af47d567c0c5:135813] [instance:11533] [instance.start->(InstanceStart)] [] [cutorService-14] [i.c.p.process.instance.InstanceStart] Failed to Waiting for dependencies for instance [11533]
2016-12-12 14:05:38,403 ERROR [af369f5f-ccba-47be-b9ad-1392fd2a6fc7:135859] [instance:11538] [instance.start->(InstanceStart)] [] [ecutorService-7] [i.c.p.process.instance.InstanceStart] Failed to Waiting for dependencies for instance [11538]
2016-12-12 14:05:39,635 ERROR [45bbd0c0-b955-4149-a4fa-8bc9e5eb0a4f:135904] [instance:11540] [instance.start->(InstanceStart)] [] [ecutorService-6] [i.c.p.process.instance.InstanceStart] Failed to Waiting for dependencies for instance [11540]`

**Comment by nagliyvred** [comment]
I am having the same issue - hosts are just not getting registered. 
I am using rancher/agent:v1.1.1-rc1 and rancher/server:v1.2.1-rc3 

The list of processes does not seem to be getting shorter over time. Looks like a deadlock.
Can anyone please help?
