### ISSUE TITLE
Panic in rancher server

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#36867]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id `f904267`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.21.10+rke2r1`
- Cluster Type (Local/Downstream): RKE2 EC2 node driver cluster - 3 etcd, 2 cp and 3 worker nodes

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) admin

   
**Describe the bug**
Panic in rancher server

**To Reproduce**

- Deployed an ec2 node driver RKE2 cluster on rancher
- Panic seen in rancher logs

**Result**
Rancher logs:
```
2022/03/13 00:02:06 [INFO] [planner] rkecluster fleet-default/sowmya-1: waiting: waiting for at least one bootstrap node
E0313 00:02:06.934088      34 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 12298 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x37d20a0, 0x6e94e40})
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/runtime/runtime.go:74 +0x7d
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xfffffffe})
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/runtime/runtime.go:48 +0x75
panic({0x37d20a0, 0x6e94e40})
	/usr/lib64/go/1.17/src/runtime/panic.go:1038 +0x215
github.com/rancher/rancher/pkg/provisioningv2/rke2/planner.(*Planner).Process.func1()
	/go/src/github.com/rancher/rancher/pkg/provisioningv2/rke2/planner/planner.go:181 +0x3b
github.com/rancher/rancher/pkg/provisioningv2/rke2/planner.(*Planner).Process(0xc002c1c200, 0x0)
	/go/src/github.com/rancher/rancher/pkg/provisioningv2/rke2/planner/planner.go:197 +0xd50
github.com/rancher/rancher/pkg/controllers/provisioningv2/rke2/planner.(*handler).OnChange(_, _, {{0xc0060d8420, 0x1, 0x1}, 0x0, 0x1, 0x0, 0x0, {0x0, ...}, ...})
	/go/src/github.com/rancher/rancher/pkg/controllers/provisioningv2/rke2/planner/controller.go:63 +0x2b5
github.com/rancher/rancher/pkg/generated/controllers/rke.cattle.io/v1.(*rKEControlPlaneStatusHandler).sync(0xc00181a930, {0xc007919b68, 0x40b2b4}, 0xc00625d180)
	/go/src/github.com/rancher/rancher/pkg/generated/controllers/rke.cattle.io/v1/rkecontrolplane.go:307 +0x15e
github.com/rancher/rancher/pkg/generated/controllers/rke.cattle.io/v1.FromRKEControlPlaneHandlerToHandler.func1({0xc009baa8b8, 0xdcbd846aff2cc}, {0x4786828, 0xc00625d180})
	/go/src/github.com/rancher/rancher/pkg/generated/controllers/rke.cattle.io/v1/rkecontrolplane.go:105 +0x44
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc00625d180, {0xc009baa8b8, 0x40175d0}, {0x4786828, 0xc00625d180})
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc003d7c870, {0xc009baa8b8, 0x16}, {0x4786828, 0xc00625d180})
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000bf58c0, {0xc009baa8b8, 0x16})
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:220 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000bf58c0, {0x359b9e0, 0xc00d07bdc0})
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:201 +0x10e
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000bf58c0)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:178 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:167
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fd4e3302d90)
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0, {0x4758e60, 0xc004d4cde0}, 0x1, 0xc004586540)
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0xc004d72fd0, 0xc811c6, 0xc003dcf6e0)
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:90 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:135 +0x2c6
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x2af4c5b]

goroutine 12298 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xfffffffe})
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/runtime/runtime.go:55 +0xd8
panic({0x37d20a0, 0x6e94e40})
	/usr/lib64/go/1.17/src/runtime/panic.go:1038 +0x215
github.com/rancher/rancher/pkg/provisioningv2/rke2/planner.(*Planner).Process.func1()
	/go/src/github.com/rancher/rancher/pkg/provisioningv2/rke2/planner/planner.go:181 +0x3b
github.com/rancher/rancher/pkg/provisioningv2/rke2/planner.(*Planner).Process(0xc002c1c200, 0x0)
	/go/src/github.com/rancher/rancher/pkg/provisioningv2/rke2/planner/planner.go:197 +0xd50
github.com/rancher/rancher/pkg/controllers/provisioningv2/rke2/planner.(*handler).OnChange(_, _, {{0xc0060d8420, 0x1, 0x1}, 0x0, 0x1, 0x0, 0x0, {0x0, ...}, ...})
	/go/src/github.com/rancher/rancher/pkg/controllers/provisioningv2/rke2/planner/controller.go:63 +0x2b5
github.com/rancher/rancher/pkg/generated/controllers/rke.cattle.io/v1.(*rKEControlPlaneStatusHandler).sync(0xc00181a930, {0xc007919b68, 0x40b2b4}, 0xc00625d180)
	/go/src/github.com/rancher/rancher/pkg/generated/controllers/rke.cattle.io/v1/rkecontrolplane.go:307 +0x15e
github.com/rancher/rancher/pkg/generated/controllers/rke.cattle.io/v1.FromRKEControlPlaneHandlerToHandler.func1({0xc009baa8b8, 0xdcbd846aff2cc}, {0x4786828, 0xc00625d180})
	/go/src/github.com/rancher/rancher/pkg/generated/controllers/rke.cattle.io/v1/rkecontrolplane.go:105 +0x44
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc00625d180, {0xc009baa8b8, 0x40175d0}, {0x4786828, 0xc00625d180})
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc003d7c870, {0xc009baa8b8, 0x16}, {0x4786828, 0xc00625d180})
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000bf58c0, {0xc009baa8b8, 0x16})
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:220 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000bf58c0, {0x359b9e0, 0xc00d07bdc0})
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:201 +0x10e
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000bf58c0)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:178 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:167
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fd4e3302d90)
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0, {0x4758e60, 0xc004d4cde0}, 0x1, 0xc004586540)
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0xc004d72fd0, 0xc811c6, 0xc003dcf6e0)
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:90 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:135 +0x2c6
```

**Comment by snasovich** [comment]
Issue known to @thedadams and there is a PR for it already (to be linked).

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `5bb08b3`**

- Deployed an RKE2 - 3 etcd, 2 cp and 3 worker nodes EC2 cluster
- No panic seen in rancher logs
