### ISSUE TITLE
Rke1 azure cloud provider enabled worker nodes are stuck on waiting with a panic in kubelet logs

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#36891]
**Rancher Server Setup**
- Rancher version: v2.6-head 80465bd
- Installation option (Docker install/Helm Chart): Docker 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `v1.23.3+k3s1`
- Proxy/Cert Details: self-signed

**Information about the Cluster**
- Kubernetes version: `v1.23.4-rancher1-1`
- Cluster Type (Local/Downstream): RKE1 Infrastructure Provider Azure 1 etcd+cp, 1 worker

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
   
**Describe the bug**
Azure node driver cluster has worker node in waiting state with a panic seen in the kubelet logs. 

**To Reproduce**
1. Create an azure node driver cluster with the above config
2. Enable cloud provider 

**Result**
Worker node won't come up active

**Expected Result**
Panic seen in the kubelet on the worker node:
```
25190 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 222 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3f934e0, 0x79d6520})
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x7d
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0})
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x75
panic({0x3f934e0, 0x79d6520})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*Cloud).GetIPForMachineWithRetry.func1()
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_backoff.go:148 +0x62
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1({0x410b74, 0xc001305ac8})
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:220 +0x1b
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext({0x508a248, 0xc000132008}, 0x0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:233 +0x7c
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection(0x44a68c0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:226 +0x39
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff({0x0, 0x0, 0x0, 0x1, 0x0}, 0x0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:421 +0x5f
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*Cloud).GetIPForMachineWithRetry(0xc000766e00, {0x7fffb8d1ab07, 0xc})
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_backoff.go:146 +0x179
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*Cloud).getIPForMachine(...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_backoff.go:140
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*Cloud).addressGetter(0x0, {0x7fffb8d1ab07, 0xc})
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_instances.go:54 +0x39
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*Cloud).NodeAddresses(0xc000766e00, {0x410ec7, 0x20}, {0x7fffb8d1ab07, 0xc})
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_instances.go:113 +0x214
k8s.io/kubernetes/pkg/kubelet/cloudresource.(*cloudResourceSyncManager).getNodeAddresses(0xc000db24e0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/cloudresource/cloud_request_manager.go:102 +0x55
k8s.io/kubernetes/pkg/kubelet/cloudresource.(*cloudResourceSyncManager).syncNodeAddresses(0xc000db24e0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/cloudresource/cloud_request_manager.go:108 +0x145
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc001305ef8)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x67
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x9b3629, {0x4f84980, 0xc000b496e0}, 0x1, 0xc000102360)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x9b3565, 0x2540be400, 0x0, 0x0, 0x1)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/kubernetes/pkg/kubelet/cloudresource.(*cloudResourceSyncManager).Run(0x83dd46, 0xc000881e60)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/cloudresource/cloud_request_manager.go:134 +0x47
created by k8s.io/kubernetes/pkg/kubelet.(*Kubelet).Run
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1466 +0x1c5
I0315 04:06:42.205712   25190 azure_instances.go:56] NodeAddresses(anu-azsec-w1) abort backoff: timed out waiting for the condition
I0315 04:06:42.205735   25190 cloud_request_manager.go:115] "Node addresses from cloud provider for node not collected" nodeName=anu-azsec-w1 err="timed out waiting for the condition"
E0315 04:06:42.229348   25190 kubelet.go:2422] "Error getting node" err="node \"anu-azsec-w1\" not found"
E0315 04:06:42.329984   25190 kubelet.go:2422] "Error getting node" err="node \"anu-azsec-w1\" not found"
E0315 04:06:42.430390   25190 kubelet.go:2422] "Error getting node" err="node \"anu-azsec-w1\" not found"
E0315 04:06:42.439728   25190 kubelet.go:2347] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized"
E0315 04:06:42.530485   25190 kubelet.go:2422] "Error getting node" err="node \"anu-azsec-w1\" not found"
I0315 04:06:42.574873   25190 nodeinfomanager.go:401] Failed to publish CSINode: nodes "anu-azsec-w1" not found
I0315 04:06:42.594287   25190 nodeinfomanager.go:401] Failed to publish CSINode: nodes "anu-azsec-w1" not found
E0315 04:06:42.630550   25190 kubelet.go:2422] "Error getting node" err="node \"anu-azsec-w1\" not found"
I0315 04:06:42.656850   25190 nodeinfomanager.go:401] Failed to publish CSINode: nodes "anu-azsec-w1" not found
E0315 04:06:42.731675   25190 kubelet.go:2422] "Error getting node" err="node \"anu-azsec-w1\" not found"
E0315 04:06:42.832594   25190 kubelet.go:2422] "Error getting node" err="node \"anu-azsec-w1\" not found"
E0315 04:06:42.932699   25190 kubelet.go:2422] "Error getting node" err="node \"anu-azsec-w1\" not found"
E0315 04:06:42.932764   25190 nodelease.go:49] "Failed to get node when trying to set owner ref to the node lease" err="nodes \"anu-azsec-w1\" not found" node="anu-azsec-w1"
I0315 04:06:42.942019   25190 nodeinfomanager.go:401] Failed to publish CSINode: nodes "anu-azsec-w1" not found
E0315 04:06:42.942044   25190 csi_plugin.go:297] Failed to initialize CSINode: error updating CSINode annotation: timed out waiting for the condition; caused by: nodes "anu-azsec-w1" not found
F0315 04:06:42.942050   25190 csi_plugin.go:311] Failed to initialize CSINode after retrying: timed out waiting for the condition

```

**Additional context**

`only seen when a cloud provider is enabled`

Could be related to norman to steve as its not seen on 2.6.4-rc6 and seen on the latest commit when a cloud provider is enabled.

Could be related  https://github.com/rancher/rancher/issues/36691#issuecomment-1064277818

**Comment by cmurphy** [comment]
Most likely introduced by https://github.com/rancher/rancher/pull/36853

**Comment by cmurphy** [comment]
https://github.com/rancher/rancher/pull/36930

**Comment by anupama2501** [comment]
Verified on 2.6-head 417d4a4

Created an azure node driver with intree cloud provider enabled, created a wk deployment, ingress - works as expected
