### ISSUE TITLE
Rancher panic if helm release secret is empty

### ISSUE THREAD

**Issue by gprossliner** [rancher/rancher#37023]
**Rancher Server Setup**
- Rancher version:
v2.6.3-patch2

- Installation option (Docker install/Helm Chart):
Helm RKEv1

**Information about the Cluster**
- Kubernetes version:
v1.20.5

- Cluster Type (Local/Downstream):
vsphere provisioned 

**User Information**
cluster-admin role

**Describe the bug**
We observed the following panic in the rancher log:

```
E0323 15:14:59.049352 33 runtime.go:78] Observed a panic: runtime.boundsError{x:3, y:0, signed:true, code:0x2} (runtime error: slice bounds out of range [:3] with capacity 0)
goroutine 3517 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x41ef9e0, 0xc00e977b18)
/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:48 +0x86
panic(0x41ef9e0, 0xc00e977b18)
/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/rancher/rancher/pkg/catalogv2/helm.decodeHelm3(0x0, 0x0, 0x7f4b7ab89b58, 0xc001049348, 0x6e656d6572697501)
/go/src/github.com/rancher/rancher/pkg/catalogv2/helm/helm3.go:124 +0x2e8
github.com/rancher/rancher/pkg/catalogv2/helm.fromHelm3Data(0x0, 0x0, 0xc005682ab0, 0x5, 0xc0010493c8, 0x0)
/go/src/github.com/rancher/rancher/pkg/catalogv2/helm/helm3.go:23 +0x39
github.com/rancher/rancher/pkg/catalogv2/helm.ToRelease(0x4c91e30, 0xc0036cb1c0, 0xc005682ab0, 0x646e612079656b01, 0x2e7365756c617620, 0x7463656a626f062a)
/go/src/github.com/rancher/rancher/pkg/catalogv2/helm/release.go:74 +0x590
github.com/rancher/rancher/pkg/controllers/dashboard/helm.(*appHandler).OnSecretChange(0xc01c40aa50, 0xc002ef0ab0, 0x2b, 0xc0036cb1c0, 0x0, 0x0, 0x0)
/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/helm/apps.go:170 +0xa6
github.com/rancher/wrangler/pkg/generated/controllers/core/v1.FromSecretHandlerToHandler.func1(0xc002ef0ab0, 0x2b, 0x4c91e30, 0xc0036cb1c0, 0xc0036cb1c0, 0x7f4b7ab89b58, 0xc0036cb1c0, 0x1)
/go/pkg/mod/github.com/rancher/wrangler@v0.8.10/pkg/generated/controllers/core/v1/secret.go:102 +0x6b
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc00e490570, 0xc002ef0ab0, 0x2b, 0x4c91e30, 0xc0036cb1c0, 0x0, 0xc0036cb1c0, 0x0, 0x0)
/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20211217013041-3c6118a30611/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000506e00, 0xc002ef0ab0, 0x2b, 0x4c91e30, 0xc0036cb1c0, 0xc004ddc001, 0x0)
/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20211217013041-3c6118a30611/pkg/controller/sharedhandler.go:69 +0x14c
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000b4fef0, 0xc002ef0ab0, 0x2b, 0xc014410358, 0x31556c4d62686b)
/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20211217013041-3c6118a30611/pkg/controller/controller.go:215 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000b4fef0, 0x3aa4740, 0xc011a657d0, 0x0, 0x0)
/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20211217013041-3c6118a30611/pkg/controller/controller.go:197 +0xe7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000b4fef0, 0x203000)
/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20211217013041-3c6118a30611/pkg/controller/controller.go:174 +0x54
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20211217013041-3c6118a30611/pkg/controller/controller.go:163
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc003a34540)
/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc003a34540, 0x4c63ae0, 0xc001730210, 0x6f39485455676f01, 0xc00175fe60)
/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc003a34540, 0x3b9aca00, 0x0, 0x4d66425967433801, 0xc00175fe60)
/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc003a34540, 0x3b9aca00, 0xc00175fe60)
/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20211217013041-3c6118a30611/pkg/controller/controller.go:134 +0x33b
panic: runtime error: slice bounds out of range [:3] with capacity 0 [recovered]
panic: runtime error: slice bounds out of range [:3] with capacity 0
```

This caused the rancher pods (all replicas) to fail, resulting in tempoary, repeated rancher service outage.

Based on the callstack I checked the source, and found the problematic code:

https://github.com/rancher/rancher/blob/85d692518525d2a1f9eb740833145b242608632e/pkg/catalogv2/helm/helm3.go#L115-L126

After checking corrsponding Helm Release secrets:
```
kubectl --context rancher -n cattle-system get secrets
...
NAME                                    TYPE                                  DATA   AGE
sh.helm.release.v1.rancher.v8           helm.sh/release.v1                    0      19h
```

I realized that this specifc secret was empty. I can't tell what caused this to be empty. And Helm itself seems to have the same problem, because `helm ls` also failed with "the same" panic.

Deleting the secret fixed the problem, but the panic is really bad, because everything runs in a single pod.

The error handling in the function doesn't handle the case of an empty slice:

```
func decodeHelm3(data string) (*release.Release, error) { 
 	b, err := base64.StdEncoding.DecodeString(data) 
 	if err != nil { 
 		return nil, err 
 	} 

        // THIS SHOULD FIX THE PANIC
        // it could be advisable to include some context like release name, secret name
 	if len(data) == 0 { 
 		return nil, errors.New("secret is empty")
 	} 
     
   	// For backwards compatibility with releases that were stored before 
 	// compression was introduced we skip decompression if the 
 	// gzip magic header is not found 
 	if bytes.Equal(b[0:3], magicGzip) { 
```

I also expected to find somthing in debug logs, but the catalog packages doesn't seem to implement any logging.

Thanks

**Comment by MKlimuszka** [comment]
Without reproduction steps there isn't much we can do. But if anyone sees this behavior again, add to this ticket.

**Comment by niusmallnan** [comment]
@gprossliner please try this workaround: https://github.com/rancher/rancher/issues/35971
