### ISSUE TITLE
logging-operator 3.17.1 shows nil pointer on startup in Windows RKE1 cluster

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#37028]
**Rancher Server Setup**
- Rancher version: v2.6.4-rc11
- Installation option (Docker install/Helm Chart): n/a
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.22.7
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Windows

**Describe the bug**

**To Reproduce**
* Install rancher-logging `100.1.0+up3.17.1`
* Check `rancher-logging` Deployment

**Result**

Nil pointer seen:

```
2022-03-24T16:02:47.325Z        INFO    Notice: If the Buffer_Size value is empty we will set it 0. For more information: https://github.com/fluent/fluent-bit/issues/2111
2022-03-24T16:02:47.327Z        DEBUG   controllers.Logging     resource is in sync     {"name": "rancher-logging-root-fluentbit", "namespace": "cattle-logging-system", "apiVersion": "v1", "kind": "Secret"}
2022-03-24T16:02:47.337Z        DEBUG   controllers.Logging     resource is in sync     {"name": "rancher-logging-root-fluentbit", "namespace": "cattle-logging-system", "apiVersion": "apps/v1", "kind": "DaemonSet"}
2022-03-24T16:02:49.250Z        DEBUG   controllers.Logging     resource is in sync     {"name": "rancher-logging-root-win-agent-fluentbit", "namespace": "cattle-logging-system", "apiVersion": "v1", "kind": "ServiceAccount"}
2022-03-24T16:02:49.251Z        DEBUG   controllers.Logging     resource is in sync     {"name": "rancher-logging-root-win-agent-fluentbit", "apiVersion": "rbac.authorization.k8s.io/v1", "kind": "ClusterRole"}
2022-03-24T16:02:49.252Z        DEBUG   controllers.Logging     resource is in sync     {"name": "rancher-logging-root-win-agent-fluentbit", "apiVersion": "rbac.authorization.k8s.io/v1", "kind": "ClusterRoleBinding"}
2022-03-24T16:02:49.252Z        INFO    Notice: If the Buffer_Size value is empty we will set it 0. For more information: https://github.com/fluent/fluent-bit/issues/2111
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x162cc02]

goroutine 587 [running]:
github.com/banzaicloud/logging-operator/pkg/resources/nodeagent.(*nodeAgentInstance).configSecret(0xc0008fa120, 0x1be8a98, 0xc00103a2c0, 0x1c0f870, 0x1bc5440, 0x0, 0x0)
        /workspace/pkg/resources/nodeagent/configsecret.go:237 +0x8a2
github.com/banzaicloud/logging-operator/pkg/resources/nodeagent.(*nodeAgentInstance).Reconcile(0xc0008fa120, 0xc001103900, 0x170ea40, 0xc001174408)
        /workspace/pkg/resources/nodeagent/nodeagent.go:351 +0x310
github.com/banzaicloud/logging-operator/pkg/resources/nodeagent.(*Reconciler).Reconcile(0xc000d08510, 0x0, 0x0, 0x0)
        /workspace/pkg/resources/nodeagent/nodeagent.go:325 +0x215
github.com/banzaicloud/logging-operator/controllers/logging.(*LoggingReconciler).Reconcile(0xc0006167e0, 0x1c123d8, 0xc000c10ed0, 0x0, 0x0, 0xc000c397e8, 0x14, 0xc000c10ed0, 0xc000030000, 0x188c680, ...)
        /workspace/controllers/logging/logging_controller.go:128 +0x625
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00033f040, 0x1c12330, 0xc0006600c0, 0x184c5c0, 0xc000bea080)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:298 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00033f040, 0x1c12330, 0xc0006600c0, 0xc0003b8f00)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc0001e3a30, 0xc00033f040, 0x1c12330, 0xc0006600c0)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:214 +0x6b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:210 +0x425
```

Upstream: https://github.com/banzaicloud/logging-operator/issues/920

**Comment by luthermonson** [comment]
https://github.com/banzaicloud/logging-operator/pull/953

**Comment by luthermonson** [comment]
there's a nil pointer panic when using secrets for configuring output. the PR will fix that but we will probably need upstream to merge and release a new version

**Comment by sowmyav27** [comment]
https://github.com/rancher/rancher/issues/37028#issuecomment-1078552027 this PR has merged

**Comment by sirredbeard** [comment]
We will need to cut an RC and then pin relevant charts.

**Comment by PennyScissors** [comment]
FYI, I was able to reproduce this with rancher-logging 100.1.0+up3.17.1 in a RKE2 windows cluster (v2.6-head 6f9c19d, k8s 1.22.7+rke2r2), so this will need to be validated in a RKE2 windows cluster as well.
