### ISSUE TITLE
cannot create stack

### ISSUE THREAD

**Issue by opichon** [rancher/rancher#3710]
I am trying to create a stack using the wordpress sample docker-compose.ym file form your documentation, but it doesn't work. 

Both containers are marked as "unhealthy". I cannot see such containers on the host. The output of docker ps command on the host is:

CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                                          NAMES
76d9a6395ffd        rancher/agent-instance:v0.8.0   "/etc/init.d/agent-in"   7 minutes ago       Up 7 minutes        0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp   20effd44-afea-4e80-943f-e866a029b611
ab5d55d8cda4        rancher/agent:v0.9.2            "/run.sh run"            8 minutes ago       Up 8 minutes                                                       rancher-agent

As you can see, there is no trace of either the database or wordpress containers. 
What is this agent-instance container and why is it at version 0.8.0 while rancher agent is at 0.9.0?

Rancher server is running a newly updated image; the host was added just before trying to create the stack.

It looks like the server cannot communicate with the agent.

Please advise.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v0.59.1` Cattle: `v0.148.1` UI: `v0.90.0` |
|Access|`github` `admin`|
|Route|`null`|

**Comment by Rucknar** [comment]
Do the container hosts appear online in the Rancher GUI? 
If you can see the services under the applications tab, it might be viewing them as objects in the API to see if there is a status message around why they've not deployed. 

Regarding agent/agent-instance versions, they are separate images, versions won't necessarily match.

**Comment by opichon** [comment]
The host is visible in the rancher UI. It shows 2 running network agent containers. I presume these match the rancher/agent and rancher/agent-instance containers that I can see on the host.

The 2 containers for the wordpress stack are also shown in the UI for the host, but they keep being shown as alternatively being stopped and restarted.

The rancher-server log is full of errors too:
.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:381) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:487) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:314) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:254) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:251) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:183) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:156) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:106) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:103) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:103) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.executeStandardProcess(DefaultObjectProcessManager.java:29) [cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.common.handler.AbstractObjectProcessLogic.activate(AbstractObjectProcessLogic.java:31) [cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.instance.InstanceStart.compute(InstanceStart.java:216) [cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.instance.InstanceStart.handle(InstanceStart.java:84) [cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:440) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:387) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:381) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:381) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:487) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:314) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:254) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:251) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:183) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:156) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:106) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:103) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:103) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.eventing.impl.ProcessEventListenerImpl.processExecute(ProcessEventListenerImpl.java:68) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.eventing.impl.ProcessEventListenerImpl.processExecute(ProcessEventListenerImpl.java:54) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at sun.reflect.GeneratedMethodAccessor579.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_95]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_95]
	at io.cattle.platform.eventing.annotation.MethodInvokingListener$1.doWithLockNoResult(MethodInvokingListener.java:76) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.annotation.MethodInvokingListener.onEvent(MethodInvokingListener.java:72) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_95]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_95]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_95]

**Comment by Rucknar** [comment]
If you click on one of the containers, choose 'view in API' you might have to be fast. There will be a reason it can't start them. Failing that if you post the config you used to deploy in here, might be able to help.

**Comment by opichon** [comment]
Sorry, but I see nothing in the "view in api" output that explains why the container does not start. 

The config is exactly the config from your website.

wordpress:
    ports: 
        - "8080:80/tcp"
    environment:
        - "WORDPRESS_DB_HOST: database:3306"
        - "WORDPRESS_DB_PASSWORD: my-secret-pw"
    tty: true
    image: wordpress
    links:
         - database
    stdin_open: true

database:
    restart: "no"
    environment:
        - "MYSQL_ROOT_PASSWORD: my-secret-pw"
    tty: true
    image: mysql
    stdin_open: true

**Comment by Rucknar** [comment]
I don't work for Rancher! Just trying to help out :)

Looking at the above, i think the guide you took it from was probably a blog post based on an older version of Rancher. The formatting of that file's changed a little since then, try the below:

```
wordpress:
  ports: 
  - 8080:80/tcp
  environment:
  - WORDPRESS_DB_HOST:database:3306
  - WORDPRESS_DB_PASSWORD:my-secret-pw
  tty: true
  image: wordpress
  links:
  - database:database
  stdin_open: true

database:
  environment:
  - MYSQL_ROOT_PASSWORD:my-secret-pw
  tty: true
  image: mysql
  stdin_open: true
```

**Comment by Rucknar** [comment]
Just ran that into my own instance. The DB fails because: 
```
2/27/2016 3:56:17 PMerror: missing WORDPRESS_DB_HOST and MYSQL_PORT_3306_TCP environment variables
2/27/2016 3:56:17 PM  Did you forget to --link some_mysql_container:mysql or set an external db
2/27/2016 3:56:17 PM  with -e WORDPRESS_DB_HOST=hostname:port?
2/27/2016 3:56:26 PMerror: missing WORDPRESS_DB_HOST and MYSQL_PORT_3306_TCP environment variables
2/27/2016 3:56:26 PM  Did you forget to --link some_mysql_container:mysql or set an external db
2/27/2016 3:56:26 PM  with -e WORDPRESS_DB_HOST=hostname:port?
2/27/2016 3:56:56 PMerror: missing WORDPRESS_DB_HOST and MYSQL_PORT_3306_TCP environment variables
2/27/2016 3:56:56 PM  Did you forget to --link some_mysql_container:mysql or set an external db
2/27/2016 3:56:56 PM  with -e WORDPRESS_DB_HOST=hostname:port?
2/27/2016 3:57:26 PMerror: missing WORDPRESS_DB_HOST and MYSQL_PORT_3306_TCP environment variables
2/27/2016 3:57:26 PM  Did you forget to --link some_mysql_container:mysql or set an external db
2/27/2016 3:57:26 PM  with -e WORDPRESS_DB_HOST=hostname:port?
```

And the wordpress instance fails because:
```
2/27/2016 3:54:53 PMerror: database is uninitialized and password option is not specified 
2/27/2016 3:54:53 PM  You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
2/27/2016 3:55:01 PMerror: database is uninitialized and password option is not specified 
2/27/2016 3:55:01 PM  You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
2/27/2016 3:55:28 PMerror: database is uninitialized and password option is not specified 
2/27/2016 3:55:28 PM  You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
2/27/2016 3:55:31 PMerror: database is uninitialized and password option is not specified 
2/27/2016 3:55:31 PM  You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
2/27/2016 3:55:45 PMerror: database is uninitialized and password option is not specified 
2/27/2016 3:55:45 PM  You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
2/27/2016 3:56:13 PMerror: database is uninitialized and password option is not specified 
2/27/2016 3:56:13 PM  You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
2/27/2016 3:56:15 PMerror: database is uninitialized and password option is not specified 
2/27/2016 3:56:15 PM  You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
2/27/2016 3:56:31 PMerror: database is uninitialized and password option is not specified 
2/27/2016 3:56:31 PM  You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
2/27/2016 3:56:58 PMerror: database is uninitialized and password option is not specified 
2/27/2016 3:56:58 PM  You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
2/27/2016 3:57:01 PMerror: database is uninitialized and password option is not specified 
2/27/2016 3:57:01 PM  You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
2/27/2016 3:57:15 PMerror: database is uninitialized and password option is not specified 
2/27/2016 3:57:15 PM  You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
2/27/2016 3:57:43 PMerror: database is uninitialized and password option is not specified
2/27/2016 3:57:43 PM  You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
```

I suspect those images have changed also since that blog post. It's important to remember rancher is in beta still. It might also be worth looking at the catalog in rancher, it has many of those services ready to deploy from it.

**Comment by opichon** [comment]
I don;t see much difference between the 2 formats, except that you've removed quotes, which shouldn't make much difference in a yaml file (it may make the yaml file badly formed, and may actually explain the error you observed). Thanks anyway.

**Comment by opichon** [comment]
Actually, I have figured something out. The original syntax for environment variables is wrong. It should be one of the following:

environment:
    MYSQL_ROOT_PASSWORD: my-secret-pw

ORL

environment:
    - "MYSQL_ROOT_PASSWORD=my-secret-pw"


in other words, either an object or an array.

It still doesn't work, though.

**Comment by opichon** [comment]
At least the contains are launched on the host.
container log complains about [ERROR] InnoDB: Cannot allocate memory for the buffer pool

**Comment by Rucknar** [comment]
Have a look at those containers on the docker hub and make sure you've got the right variables set to run them.

**Comment by opichon** [comment]
adding swap to the host seems to resolve this.

now yet another problem. wordpress site is not available, i.e. when opening http://<host ip address>:8080  nothing is loaded.

**Comment by opichon** [comment]
From the wordpress container log:

2/27/2016 11:14:14 PMMySQL Connection Error: (1130) Host '10.42.242.205' is not allowed to connect to this MySQL server
2/27/2016 11:14:17 PM
2/27/2016 11:14:17 PMWarning: mysqli::mysqli(): (HY000/1130): Host '10.42.242.205' is not allowed to connect to this MySQL server in - on

**Comment by Rucknar** [comment]
Probably because you've not set a default password for mysql, ? It's shown in the logs i posted above when running that config in.

https://hub.docker.com/_/mysql/

Probably worth taking a moment to go through those images and making sure you have everything in-place.

**Comment by opichon** [comment]
I suspect that's because the wordpress DB is not initialized. The mysql container requires the following environment vars to initialize a DB:

database:
    environment:
        - "MYSQL_ROOT_PASSWORD=my-secret-pw"
        - "MYSQL_DATABASE=wordpress"
        - "MYSQL_USER=wordpress"
        - "MYSQL_PASSWORD=my-secret-pw"

**Comment by opichon** [comment]
This is a config that works:

wordpress:
    ports: 
        - 8080:80/tcp
    environment:
        - "WORDPRESS_DB_HOST=database:3306"
        - "WORDPRESS_DB_NAME=wordpress"
        - "WORDPRESS_DB_USER=wordpress"
        - "WORDPRESS_DB_PASSWORD=my-secret-pw"
    tty: true
    image: wordpress
    links:
        - database:database
    stdin_open: true

database:
    environment:
        - "MYSQL_ROOT_PASSWORD=my-secret-pw"
        - "MYSQL_DATABASE=wordpress"
        - "MYSQL_USER=wordpress"
        - "MYSQL_PASSWORD=my-secret-pw"
    tty: true
    image: mysql
    stdin_open: true

**Comment by deniseschannon** [comment]
FYI, I think you were looking at an old blog post, which we don't keep up to date as new versions/features come out. Documentation at docs.rancher.com are kept up to date as much as possible.
