### ISSUE TITLE
Import AKS cluster in Rancher 2.6.4 Fails

### ISSUE THREAD

**Issue by claudioser** [rancher/rancher#37202]
**Rancher Server Setup**
- Rancher version: 2.6.4
- Installation option (Docker install/Helm Chart): Helm Chart - RKE 1.19.3 but also seen on k3s 1.21.9
   
**Information about the Cluster**
- Kubernetes version: 
- Cluster Type (Local/Downstream): Downstream - AKS  Cluster. Tried several AKS versions
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Import AKS
 trying to import AKS cluster, the import stays in pending & does not finish and when looking ar Rancher Management server pods, the aks-config-operator pods and the rancher-xxx pods, keep on CrashLoopBackOff and Error, See screenshot
![image](https://user-images.githubusercontent.com/53047113/161919519-19e3abb9-ba05-4679-b178-d15b62c990ea.png)

**To Reproduce**
  Create AKS cluster directly within Azure and then import into Rancher

**Result**

**Expected Result**
 Cluster to become active and managed by rancher 

**Screenshots**

**Additional context**
 aks-config-operator pod log example:
```
kubectl -n cattle-system logs -f aks-config-operator-59c749b645-njmck
Doing /etc/rancher/ssl
W0406 07:29:19.378904      14 loader.go:221] Config not found: /home/aks-operator/.kube/config
time="2022-04-06T07:29:20Z" level=info msg="Starting aks.cattle.io/v1, Kind=AKSClusterConfig controller"
time="2022-04-06T07:29:20Z" level=info msg="Starting /v1, Kind=Secret controller"
time="2022-04-06T07:29:21Z" level=info msg="Checking configuration for cluster [aks-import]"
E0406 07:29:21.513611      14 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:0, signed:true, code:0x0} (runtime error: index out of range [1] with length 0)
goroutine 331 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x14c27a0, 0xc0017070c8)
        /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/runtime/runtime.go:48 +0x86
panic(0x14c27a0, 0xc0017070c8)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/rancher/aks-operator/controller.BuildUpstreamClusterState(0x1760658, 0xc0000bc700, 0x17609d8, 0xc00044c0c0, 0x7fafdac98570, 0xc0004381c0, 0xc000618118, 0xd18c2e2800, 0x3, 0x6fc23ac00)
        /go/src/github.com/rancher/aks-operator/controller/aks-cluster-config-handler.go:674 +0x131f
github.com/rancher/aks-operator/controller.(*Handler).checkAndUpdate(0xc0003ad1c0, 0xc000618000, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/aks-operator/controller/aks-cluster-config-handler.go:339 +0x55c
github.com/rancher/aks-operator/controller.(*Handler).OnAksConfigChanged(0xc0003ad1c0, 0xc000045360, 0x1a, 0xc000618000, 0xc00007f530, 0xc08b6e34143775f3, 0x39f9d6f5)
        /go/src/github.com/rancher/aks-operator/controller/aks-cluster-config-handler.go:121 +0x9d
github.com/rancher/aks-operator/controller.(*Handler).recordError.func1(0xc000045360, 0x1a, 0xc000618000, 0x14eb180, 0xeca0c0, 0x12cb0c0)
        /go/src/github.com/rancher/aks-operator/controller/aks-cluster-config-handler.go:171 +0x67
github.com/rancher/aks-operator/pkg/generated/controllers/aks.cattle.io/v1.FromAKSClusterConfigHandlerToHandler.func1(0xc000045360, 0x1a, 0x1739d68, 0xc000618000, 0xe0, 0xf, 0x14eb180, 0x40a84c)
        /go/src/github.com/rancher/aks-operator/pkg/generated/controllers/aks.cattle.io/v1/aksclusterconfig.go:105 +0x6b
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc0003b3820, 0xc000045360, 0x1a, 0x1739d68, 0xc000618000, 0x1a, 0xc000098c01, 0x40a56c, 0x2030288)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc0003ad140, 0xc000045360, 0x1a, 0x1739d68, 0xc000618000, 0xc000b82301, 0x0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/sharedhandler.go:69 +0x14c
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc0000e6840, 0xc000045360, 0x1a, 0xc000b82478, 0x448500)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:215 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0000e6840, 0x13ce1e0, 0xc00022aa00, 0x0, 0x0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:197 +0xe7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0000e6840, 0x203000)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:174 +0x54
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:163
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00022aab0)
        /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00022aab0, 0x1734000, 0xc00007f5c0, 0x1, 0xc000091080)
        /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00022aab0, 0x3b9aca00, 0x0, 0xc000944701, 0xc000091080)
        /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc00022aab0, 0x3b9aca00, 0xc000091080)
        /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:134 +0x33b
panic: runtime error: index out of range [1] with length 0 [recovered]
        panic: runtime error: index out of range [1] with length 0
goroutine 331 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/runtime/runtime.go:55 +0x109
panic(0x14c27a0, 0xc0017070c8)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/rancher/aks-operator/controller.BuildUpstreamClusterState(0x1760658, 0xc0000bc700, 0x17609d8, 0xc00044c0c0, 0x7fafdac98570, 0xc0004381c0, 0xc000618118, 0xd18c2e2800, 0x3, 0x6fc23ac00)
        /go/src/github.com/rancher/aks-operator/controller/aks-cluster-config-handler.go:674 +0x131f
github.com/rancher/aks-operator/controller.(*Handler).checkAndUpdate(0xc0003ad1c0, 0xc000618000, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/aks-operator/controller/aks-cluster-config-handler.go:339 +0x55c
github.com/rancher/aks-operator/controller.(*Handler).OnAksConfigChanged(0xc0003ad1c0, 0xc000045360, 0x1a, 0xc000618000, 0xc00007f530, 0xc08b6e34143775f3, 0x39f9d6f5)
        /go/src/github.com/rancher/aks-operator/controller/aks-cluster-config-handler.go:121 +0x9d
github.com/rancher/aks-operator/controller.(*Handler).recordError.func1(0xc000045360, 0x1a, 0xc000618000, 0x14eb180, 0xeca0c0, 0x12cb0c0)
        /go/src/github.com/rancher/aks-operator/controller/aks-cluster-config-handler.go:171 +0x67
github.com/rancher/aks-operator/pkg/generated/controllers/aks.cattle.io/v1.FromAKSClusterConfigHandlerToHandler.func1(0xc000045360, 0x1a, 0x1739d68, 0xc000618000, 0xe0, 0xf, 0x14eb180, 0x40a84c)
        /go/src/github.com/rancher/aks-operator/pkg/generated/controllers/aks.cattle.io/v1/aksclusterconfig.go:105 +0x6b
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc0003b3820, 0xc000045360, 0x1a, 0x1739d68, 0xc000618000, 0x1a, 0xc000098c01, 0x40a56c, 0x2030288)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc0003ad140, 0xc000045360, 0x1a, 0x1739d68, 0xc000618000, 0xc000b82301, 0x0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/sharedhandler.go:69 +0x14c
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc0000e6840, 0xc000045360, 0x1a, 0xc000b82478, 0x448500)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:215 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0000e6840, 0x13ce1e0, 0xc00022aa00, 0x0, 0x0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:197 +0xe7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0000e6840, 0x203000)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:174 +0x54
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:163
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00022aab0)
        /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00022aab0, 0x1734000, 0xc00007f5c0, 0x1, 0xc000091080)
        /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00022aab0, 0x3b9aca00, 0x0, 0xc000944701, 0xc000091080)
        /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc00022aab0, 0x3b9aca00, 0xc000091080)
        /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:134 +0x33b
```

and rancher pod log ( small extract )
```
kubectl -n cattle-system logs -f rancher-96d658cd7-gbhmx

E0406 07:35:57.338246      32 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:0, signed:true, code:0x0} (runtime error: index out of range [1] with length 0)
goroutine 3312 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3ce2060, 0xc00b35cd20})
        /go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/runtime/runtime.go:74 +0x7d
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0176401f0})
        /go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/runtime/runtime.go:48 +0x75
panic({0x3ce2060, 0xc00b35cd20})

```

**Comment by claudioser** [comment]
after rebooting rancher server, 1.20.15 was able to be brought in.. 1.21.9 always worked. sry for redherring
