### ISSUE TITLE
Rancher Server failed after installing Convoy GlusterFS & GlusterFS on one machine

### ISSUE THREAD

**Issue by laosb** [rancher/rancher#3720]
Docker Version: 1.10.0
OS: Ubuntu 12.04.4 LTS (GNU/Linux 3.11.0-15-generic x86_64)
Configurations: `rancher/server` `rancher/agent` on same server, installed Convoy GlusterFS and GlusterFS from catalog on the same server mentioned before.
Error logs:
```
2016-02-24 13:44:54,469 ERROR [f8f2c080-e12c-40d5-89fc-92f57dc351ea:29371] [instance:2877] [instance.start->(InstanceStart)] [] [torService-4978] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [2877]
2016-02-24 13:46:54,658 ERROR [1c6e3382-4c92-43c1-bee4-b185f3f2ae59:29381] [instance:2878] [instance.start->(InstanceStart)->instance.allocate->(InstanceAllocate)] [] [cutorService-18] [c.p.a.e.i.AllocatorEventListenerImpl] No allocator handled [EventVO [id=067abeda-1ecc-4cc3-8aab-0d85e958dc3c, name=instance.allocate, previousNames=null, replyTo=reply.5384101095060596488, resourceId=2878, resourceType=instance, publisher=null, transitioning=null, transitioningMessage=null, transitioningInternalMessage=null, previousIds=null, data={}, time=Wed Feb 24 13:46:54 UTC 2016, listenerKey=null, transitioningProgress=null]]
2016-02-24 13:46:54,663 ERROR [1c6e3382-4c92-43c1-bee4-b185f3f2ae59:29381] [instance:2878] [instance.start->(InstanceStart)->instance.allocate] [] [torService-4985] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.eventing.exception.EventExecutionException: Scheduling failed: host needs ports 8091/tcp available
	at io.cattle.platform.eventing.exception.EventExecutionException.fromEvent(EventExecutionException.java:53) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.impl.AbstractEventService.callSync(AbstractEventService.java:263) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.common.handler.EventBasedProcessHandler.handle(EventBasedProcessHandler.java:109) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.instance.InstanceAllocate.handle(InstanceAllocate.java:47) ~[cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:440) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
```
*(Deeper call stack hidden)*

**Comment by deniseschannon** [comment]
These errors don't look like they are related to convoy-gluster or glusterfs. 

The errors show 

1. You have a service that is trying to deploy (based on `Failed to Scheduling for instance`). If you go to your API page for services, you can see which service has a serviceID of 2877 to find which service is having issues. .
2. You have another service that also had scheduling failed as you don't have any hosts with port `8091` available.If you go to your API page for services, you can see which service has a serviceID of 2878 to find the service trying to expose port 8091.

**Comment by laosb** [comment]
Thanks! I would try it this weekend!

**Comment by laosb** [comment]
@deniseschannon Sorry, because `rancher/server` couldn't start, I can't reach the API page. Is there any other ways to reach them?

**Comment by deniseschannon** [comment]
Can you try to restart the container and send  the logs of Rancher server? 

http://docs.rancher.com/rancher/faqs/troubleshooting/#where-can-i-find-detailed-logs-of-the-rancher-server-container

**Comment by laosb** [comment]
OK, will try this week.

**Comment by deniseschannon** [comment]
@laosb If you are still having issues with your services, please re-open. As I mentioned above, your issue is not related glusterfs or convoy-gluster, so you'll need to find out why you have this service that is failing to schedule.
