### ISSUE TITLE
Observed a panic: runtime.boundsError when rancher starting up

### ISSUE THREAD

**Issue by wangxu6363** [rancher/rancher#37269]
**Rancher Server Setup**
- Rancher version:V2.6.4
- Installation option (Docker install/Helm Chart): docker version:19.03.12, 
   - If Helm Chart, Kubernetes Cluster and version : k8s v1.19.16
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:v1.19.16
- Cluster Type (Local/Downstream):Local

**User Information**
- What is the role of the user logged in? Admin
 
**Describe the bug**
rancher cluster crash at 4:00 pm last day, then give me many errors in restart
2022/04/11 22:27:21 [INFO] Starting fleet.cattle.io/v1alpha1, Kind=Cluster controller
2022/04/11 22:27:21 [INFO] Starting management.cattle.io/v3, Kind=ManagedChart controller
2022/04/11 22:27:21 [INFO] [CleanupOrphanBindingsDone] orphan bindings cleanup has already run, skipping
2022/04/11 22:27:21 [INFO] checking configmap cattle-system/admincreated to determine if orphan bindings cleanup needs to run
2022/04/11 22:27:21 [INFO] Starting management.cattle.io/v3, Kind=ClusterAlertGroup controller
2022/04/11 22:27:21 [INFO] Starting management.cattle.io/v3, Kind=GlobalDnsProvider controller
2022/04/11 22:27:21 [INFO] Starting admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration controller
2022/04/11 22:27:21 [INFO] duplicate bindings cleanup has already run, skipping
2022/04/11 22:27:21 [INFO] [CleanupOrphanCatalogBindingsDone] orphan bindings cleanup has already run, skipping
2022/04/11 22:27:21 [INFO] Starting cluster.x-k8s.io/v1alpha3, Kind=Cluster controller
E0411 22:27:21.326169 32 runtime.go:78] Observed a panic: runtime.boundsError{x:3, y:0, signed:true, code:0x2} (runtime error: slice bounds out of range [:3] with capacity 0)
goroutine 3838 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3ce2060, 0xc00f4e2048})
/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/runtime/runtime.go:74 +0x7d
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00c071540})
/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/runtime/runtime.go:48 +0x75
panic({0x3ce2060, 0xc00f4e2048})
/usr/lib64/go/1.17/src/runtime/panic.go:1038 +0x215
github.com/rancher/rancher/pkg/catalogv2/helm.decodeHelm3({0x0, 0xb899cd})
/go/src/github.com/rancher/rancher/pkg/catalogv2/helm/helm3.go:124 +0x1b1
github.com/rancher/rancher/pkg/catalogv2/helm.fromHelm3Data({0x0, 0xc004c753c0}, 0x3fb7059)
/go/src/github.com/rancher/rancher/pkg/catalogv2/helm/helm3.go:23 +0x25
github.com/rancher/rancher/pkg/catalogv2/helm.ToRelease({0x479d720, 0xc004c753c0}, 0xc011b49a78)
/go/src/github.com/rancher/rancher/pkg/catalogv2/helm/release.go:74 +0x3eb
github.com/rancher/rancher/pkg/controllers/dashboard/helm.(*appHandler).OnSecretChange(0xc00182a910, {0xc0045be120, 0x2d}, 0xc004c753c0)
/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/helm/apps.go:170 +0xa5
github.com/rancher/wrangler/pkg/generated/controllers/core/v1.FromSecretHandlerToHandler.func1({0xc0045be120, 0x2f34ef6a5e365a}, {0x479d720, 0xc004c753c0})
/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/wrangler@v0.8.11-0.20220217210408-3ecd23dfea3b/pkg/generated/controllers/core/v1/secret.go:102 +0x44
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc001774ab0, {0xc0045be120, 0x40631a7}, {0x479d720, 0xc004c753c0})
/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000265b80, {0xc0045be120, 0x2d}, {0x479d720, 0xc004c753c0})
/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc001349340, {0xc0045be120, 0x2d})
/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:220 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc001349340, {0x35a9ee0, 0xc00c071540})
/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:201 +0x10e
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc001349340)
/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:178 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:167
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fa73a3e0160)
/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4c33694633524a4b, {0x476bde0, 0xc002af8c90}, 0x1, 0xc0022123c0)
/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x5a3935716674502b, 0x3b9aca00, 0x0, 0x6e, 0x4631477154394d6a)
/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x5462477148785636, 0x7248783838655579, 0x7473794e4e734f72)
/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:90 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:135 +0x2c6
panic: runtime error: slice bounds out of range [:3] with capacity 0 [recovered]
panic: runtime error: slice bounds out of range [:3] with capacity 0
goroutine 3838 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00c071540})
/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/runtime/runtime.go:55 +0xd8
panic({0x3ce2060, 0xc00f4e2048})
/usr/lib64/go/1.17/src/runtime/panic.go:1038 +0x215
github.com/rancher/rancher/pkg/catalogv2/helm.decodeHelm3({0x0, 0xb899cd})
/go/src/github.com/rancher/rancher/pkg/catalogv2/helm/helm3.go:124 +0x1b1
github.com/rancher/rancher/pkg/catalogv2/helm.fromHelm3Data({0x0, 0xc004c753c0}, 0x3fb7059)
/go/src/github.com/rancher/rancher/pkg/catalogv2/helm/helm3.go:23 +0x25
github.com/rancher/rancher/pkg/catalogv2/helm.ToRelease({0x479d720, 0xc004c753c0}, 0xc011b49a78)
/go/src/github.com/rancher/rancher/pkg/catalogv2/helm/release.go:74 +0x3eb
github.com/rancher/rancher/pkg/controllers/dashboard/helm.(*appHandler).OnSecretChange(0xc00182a910, {0xc0045be120, 0x2d}, 0xc004c753c0)
/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/helm/apps.go:170 +0xa5
github.com/rancher/wrangler/pkg/generated/controllers/core/v1.FromSecretHandlerToHandler.func1({0xc0045be120, 0x2f34ef6a5e365a}, {0x479d720, 0xc004c753c0})
/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/wrangler@v0.8.11-0.20220217210408-3ecd23dfea3b/pkg/generated/controllers/core/v1/secret.go:102 +0x44
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc001774ab0, {0xc0045be120, 0x40631a7}, {0x479d720, 0xc004c753c0})
/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000265b80, {0xc0045be120, 0x2d}, {0x479d720, 0xc004c753c0})
/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc001349340, {0xc0045be120, 0x2d})
/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:220 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc001349340, {0x35a9ee0, 0xc00c071540})
/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:201 +0x10e
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc001349340)
/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:178 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:167
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fa73a3e0160)
/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4c33694633524a4b, {0x476bde0, 0xc002af8c90}, 0x1, 0xc0022123c0)
/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x5a3935716674502b, 0x3b9aca00, 0x0, 0x6e, 0x4631477154394d6a)
/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x5462477148785636, 0x7248783838655579, 0x7473794e4e734f72)
/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:90 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:135 +0x2c6

**To Reproduce**
always in restart

**Result**

**Expected Result**
rancher cluster ran startup

**Comment by wangxu6363** [comment]
delete all helm opernation secret , then issue was solved

**Comment by scheibling** [comment]
If anyone else stumbles upon this with k3s/rke/rke2, what helped for me was deleting a secret (user-[randomchars]-secret in the namespace cattle-system

**Comment by artm** [comment]
The underlying problem is with helm < 3.9.3 (https://github.com/helm/helm/issues/11142)
It can be solved if you can access it with a later version of helm. Hopefully you can find the broken chart release (`STATUS = failed`) with `helm ls -A`, and fix it by rolling back to a previous revision: 

```bash
$ helm ls -A
NAME  NAMESPACE  REVISION  STATUS  CHART
...
alpha keycloak   10        failed  keycloak-17.0.0
...

$ helm rollback -n keycloak alpha 9
Rollback was a success! Happy Helming!
```

After which you can either wait until cattle agent restarts or helm it by

```bash
$ kubectl -n cattle-system get pods
NAME                                    READY   STATUS             RESTARTS   AGE
cattle-cluster-agent-65f476c76b-6th9d   0/1     CrashLoopBackOff   47         3h41m

$ kubectl -n cattle-system delete pod cattle-cluster-agent-65f476c76b-6th9d
pod "cattle-cluster-agent-65f476c76b-6th9d" deleted

$ kubectl -n cattle-system get pods
NAME                                    READY   STATUS    RESTARTS   AGE
cattle-cluster-agent-65f476c76b-8mrq7   1/1     Running   0          9s

```
