### ISSUE TITLE
[cli] Rancher port forwarding issue on EKS hosted cluster: "error upgrading connection: Upgrade request required"

### ISSUE THREAD

**Issue by nshazly** [rancher/rancher#37355]
Steps to recreate issue:
1. Create EKS cluster
2. Use ALB or ELB (issue occurs on both)
    - terminate ssl on the load balancer
    - traffic forwarded to open nodeports, which forward to the running rancher application
4. Install rancher, `helm install --upgrade --namespace cattle-system rancher rancher-latest/rancher --version 2.5.12 --namespace cattle-system --set tls=external --set hostname=************************`
  
6. Create an api key to use the rancher cli tool
```
$ rancher2 login --skip-verify --token=****************************** https://<RANCHER_URL>
$ rancher kubectl port-forward deploy/rancher 8080:80 -n cattle-system
error: error upgrading connection: Upgrade request required
exit status 1
```

Detailed log output showing websocket upgrade issue, the GET request to port-forward receives a 400 response:
```
I0413 14:03:51.501611  220972 round_trippers.go:445] POST https://<RANCHER_URL>/k8s/clusters/local/api/v1/namespaces/cattle-system/pods/rancher-bdf95d7c8-q9lms/portforward 400 Bad Request in 187 milliseconds
I0413 14:03:51.501673  220972 round_trippers.go:451] Response Headers:
I0413 14:03:51.501693  220972 round_trippers.go:454]     Content-Type: application/json
I0413 14:03:51.501701  220972 round_trippers.go:454]     Content-Length: 139
I0413 14:03:51.501708  220972 round_trippers.go:454]     Connection: keep-alive
I0413 14:03:51.501762  220972 round_trippers.go:454]     Audit-Id: d46fe8bd-6752-446f-9e60-d83039f8cbd3
I0413 14:03:51.501780  220972 round_trippers.go:454]     Cache-Control: no-cache, private
I0413 14:03:51.501788  220972 round_trippers.go:454]     X-Content-Type-Options: nosniff
I0413 14:03:51.501796  220972 round_trippers.go:454]     Date: Wed, 13 Apr 2022 21:03:51 GMT
F0413 14:03:51.502339  220972 helpers.go:115] error: error upgrading connection: Upgrade request required
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc00013a001, 0xc000623180, 0x6a, 0x133)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x2a6c040, 0xc000000003, 0x0, 0x0, 0xc00003a2a0, 0x284c16b, 0xa, 0x73, 0x40e200)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:975 +0x19b
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0x2a6c040, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x2, 0xc000b26180, 0x1, 0x1)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:732 +0x16f
k8s.io/kubernetes/vendor/k8s.io/klog/v2.FatalDepth(...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1488
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.fatal(0xc000e5ab40, 0x3b, 0x1)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:93 +0x26e
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.checkErr(0x1cead20, 0xc000b26120, 0x1bb70f8)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:188 +0x945
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.CheckErr(...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:115
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/portforward.NewCmdPortForward.func1(0xc00075d340, 0xc00014e000, 0x2, 0x5)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/portforward/portforward.go:120 +0x197
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc00075d340, 0xc00057cf00, 0x5, 0x5, 0xc00075d340, 0xc00057cf00)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000168b00, 0xc00013c120, 0xc000140000, 0x7)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958 +0x375
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
main.main()
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x21d

goroutine 18 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2a6c040)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf

goroutine 5 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x1bb7018, 0x1cec100, 0xc000426930, 0x1, 0xc000114b40)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x149
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x1bb7018, 0x12a05f200, 0x0, 0x1, 0xc000114b40)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0x1bb7018, 0x12a05f200, 0xc000114b40)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs.InitLogs
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs/logs.go:51 +0x96

goroutine 24 [IO wait]:
internal/poll.runtime_pollWait(0x7fab4e2c3a58, 0x72, 0x1cef1c0)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000698318, 0x72, 0x1cef100, 0x2878610, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000698300, 0xc000720000, 0xba1c, 0xba1c, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:159 +0x1a5
net.(*netFD).Read(0xc000698300, 0xc000720000, 0xba1c, 0xba1c, 0x203000, 0x652cfb, 0xc000904be0)
	/usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc00051e690, 0xc000720000, 0xba1c, 0xba1c, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:182 +0x8e
crypto/tls.(*atLeastReader).Read(0xc000985400, 0xc000720000, 0xba1c, 0xba1c, 0x19, 0xa2a5, 0xc00010d730)
	/usr/local/go/src/crypto/tls/conn.go:779 +0x62
bytes.(*Buffer).ReadFrom(0xc000904d00, 0x1ceab00, 0xc000985400, 0x40b645, 0x18e4ea0, 0x1a4d560)
	/usr/local/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc000904a80, 0x1ced5a0, 0xc00051e690, 0x5, 0xc00051e690, 0x9)
	/usr/local/go/src/crypto/tls/conn.go:801 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc000904a80, 0x0, 0x0, 0xc00010dd38)
	/usr/local/go/src/crypto/tls/conn.go:608 +0x115
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:576
crypto/tls.(*Conn).Read(0xc000904a80, 0xc000185000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1252 +0x15f
bufio.(*Reader).Read(0xc000566de0, 0xc00084e658, 0x9, 0x9, 0xc00010dd38, 0x1bb7e00, 0x7ef24b)
	/usr/local/go/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x1cea920, 0xc000566de0, 0xc00084e658, 0x9, 0x9, 0x9, 0xc000116050, 0x0, 0x1cead20)
	/usr/local/go/src/io/io.go:314 +0x87
io.ReadFull(...)
	/usr/local/go/src/io/io.go:333
net/http.http2readFrameHeader(0xc00084e658, 0x9, 0x9, 0x1cea920, 0xc000566de0, 0x0, 0x0, 0xc00098a660, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:1477 +0x89
net/http.(*http2Framer).ReadFrame(0xc00084e620, 0xc00098a660, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:1735 +0xa5
net/http.(*http2clientConnReadLoop).run(0xc00010dfa8, 0x0, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:8251 +0x8d
net/http.(*http2ClientConn).readLoop(0xc000001680)
	/usr/local/go/src/net/http/h2_bundle.go:8179 +0x6f
created by net/http.(*http2Transport).newClientConn
	/usr/local/go/src/net/http/h2_bundle.go:7175 +0x685

goroutine 169 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/portforward.PortForwardOptions.RunPortForward.func1(0xc00007f440, 0xc0004fb9e0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/portforward/portforward.go:408 +0x34
created by k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/portforward.PortForwardOptions.RunPortForward
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/portforward/portforward.go:407 +0x2e5

goroutine 168 [syscall]:
os/signal.signal_recv(0x4738424d0a68457a)
	/usr/local/go/src/runtime/sigqueue.go:147 +0x9d
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	/usr/local/go/src/os/signal/signal.go:150 +0x45
exit status 255

```

Using the GUI, websocket connections successfully upgrade, receiving the 101 switch protocol. I can port forward using kubectl in the GUI, as well as exec into containers. The dev console shows the network requests using websockets:

![image](https://user-images.githubusercontent.com/1079547/163285666-e95e515d-bdd2-4344-8e55-01aa5a5a73bc.png)

Exec/Port-forward functions also work when using the kubectl tool without the rancher cli wrapper. However, we use Rancher to manage permissions for users instead of giving direct access to the EKS cluster. So we require this feature of the rancher cli tool.

The issue also occurs when using an ingress/api gateway that is configured to allow websocket upgrades (tested with the ambassador api gateway and mapping allowing spdy/3.1, http/2, and websocket protocol upgrade requests). 

This confirms that the issue is specific to the CLI tool.

**Comment by royerhq** [comment]
I get the same error for both **port-forward** and **exec** commands.
Based on the logs the call is failing at the following _POST request_

```
POST https://<RANCHER_URL>/k8s/clusters/c-m-fnak3nd/api/v1/namespaces/default/pods/k8s-test-5f4f566c5b-7nk9l/exec?command=sh&container=k8s-test&stdin=true&stdout=true&tty=true
```
**Output** 
```
{
    "kind": "Status",
    "apiVersion": "v1",
    "metadata": {},
    "status": "Failure",
    "message": "Upgrade request required",
    "reason": "BadRequest",
    "code": 400
}
```

**Comment by able8** [comment]
We also get the same error for `kubectl exec` commands.

**Comment by royerhq** [comment]
Any updates?

**Comment by nshazly** [comment]
This is still an open issue for us as well.

**Comment by NeillShazly** [comment]
This is still an issue for us.

**Comment by dcardozoo** [comment]
I have the same exact issue using `kubectl` with the rancher kubeconfig give me errors for both `exec` and `port-forward` 
```bash
$ k exec -it rancher-58f6c44c59-zg2ft -- bash
Error from server:

$ k port-forward svc/rancher 8080:80
error: error upgrading connection:
```

Weirdly enough if I do not use let's encrypt and leave rancher to use its self-signed certificate everything works (kubeconfig with `insecure-skip-tls-verify: true`)

I do not know if this has to be also, we use RKE2 as with other Rancher cluster I deployed on AWS EKS, everything works as expected.

**Comment by gdziwoki** [comment]
After doing some research, looks like port-forward, exec and a couple more use SPDY protocol, that is not supported by AWS ALB and that is causing the issue.

Starting from Kubernetes 1.31, [kubectl will use websockets](https://kubernetes.io/blog/2024/08/20/websockets-transition/), but that is still some way away.
For now, the workaround is exposing Rancher via NLB and terminating SSL on the ingress controller.
