### ISSUE TITLE
Windows worker nodes are showing as `Reconciling` in Cluster Management, but showing as `Active` in Cluster Explorer

### ISSUE THREAD

**Issue by markusewalker** [rancher/rancher#37628]
**Rancher Server Setup**
- Rancher version: `v2.6.5-rc8`
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.22.9+rke2r2`
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Standard
  - If custom, define the set of permissions:

   
**Describe the bug**

When creating an RKE2 cluster with Windows worker nodes, there is a regression where the cluster appears to be in `Updating` state despite the nodes all being in a state of `Active` in Cluster Management. See below:

![image](https://user-images.githubusercontent.com/52591819/167200391-d22260a0-bd3e-45c0-867c-b801377e01a4.png)
![167200624-2748fa77-d83b-4b2a-8b74-ae9b1fb142e7](https://user-images.githubusercontent.com/52591819/167200764-01007c73-d727-4fd7-a810-49d2fc1a5aef.png)

However, going over to cluster explorer, I see all the nodes as `Active`:

![Screen Shot 2022-05-06 at 11 58 20 AM](https://user-images.githubusercontent.com/52591819/167201109-387ba259-13c2-4d41-bb05-8813aac6fedf.png)

**To Reproduce**
 
1. Setup Rancher UI and navigate to the Rancher UI.
2. Create a standard user and login to Rancher as that user.
3. Create a custom RKE2 cluster with Windows worker nodes.
4. All of the Linux nodes should come up as `Active`, but the Windows worker nodes will be stuck in `Reconciling` status.

**Result**
The UI is giving two statuses for Windows worker nodes in Cluster Management and Cluster Explorer.

**Expected Result**
Cluster Management and Cluster Explorer should have the same status for Windows worker nodes for a cluster.

**Comment by markusewalker** [comment]
@luthermonson here are the Event Viewer logs requested from our side conversation:

```
> wins srv app run
time="2022-05-06T20:59:38Z" level=warning msg="cannot upgrade unless the current process is being executed as a Windows service"
time="2022-05-06T20:59:38Z" level=info msg="listening for tcp requests on rancher_wins_proxy destined for: [9796]"
time="2022-05-06T20:59:38Z" level=info msg="CSI Proxy will be enabled as a Windows service."
time="2022-05-06T20:59:38Z" level=info msg="Rancher System Agent version dev (HEAD) is starting"
time="2022-05-06T20:59:38Z" level=info msg="Setting C:/var/lib/rancher/agent/work as the working directory"
time="2022-05-06T20:59:38Z" level=info msg="Starting remote watch of plans"
time="2022-05-06T20:59:38Z" level=info msg="Listening on \\\\.\\pipe\\rancher_wins_proxy"
time="2022-05-06T20:59:38Z" level=info msg="Listening on \\\\.\\pipe\\rancher_wins"
time="2022-05-06T20:59:38Z" level=info msg="Starting /v1, Kind=Secret controller"
time="2022-05-06T20:59:38Z" level=info msg="Detected first start, force-applying one-time instruction set"
time="2022-05-06T20:59:38Z" level=info msg="[Applyinator] Applying one-time instructions for plan with checksum c552d8c2fb5ad5faa89cabef62663b48de11a4b538a3491faf9bbcbd5a624cde"
time="2022-05-06T20:59:38Z" level=info msg="[Applyinator] Extracting image rancher/system-agent-installer-rke2:v1.22.9-rke2r2 to directory C:\\var\\lib\\rancher\\agent\\work\\20220506-205938\\c552d8c2fb5ad5faa89cabef62663b48de11a4b538a3491faf9bbcbd5a624cde_0"
time="2022-05-06T20:59:38Z" level=info msg="Using private registry config file at /etc/rancher/agent/registries.yaml"
time="2022-05-06T20:59:38Z" level=info msg="Pulling image index.docker.io/rancher/system-agent-installer-rke2:v1.22.9-rke2r2"
time="2022-05-06T20:59:39Z" level=info msg="Extracting file Files/bin/installer.ps1 to C:\\var\\lib\\rancher\\agent\\work\\20220506-205938\\c552d8c2fb5ad5faa89cabef62663b48de11a4b538a3491faf9bbcbd5a624cde_0\\installer.ps1"
time="2022-05-06T20:59:39Z" level=info msg="Extracting file Files/bin/rke2.windows-amd64.tar.gz to C:\\var\\lib\\rancher\\agent\\work\\20220506-205938\\c552d8c2fb5ad5faa89cabef62663b48de11a4b538a3491faf9bbcbd5a624cde_0\\rke2.windows-amd64.tar.gz"
time="2022-05-06T20:59:40Z" level=info msg="Extracting file Files/bin/sha256sum-amd64.txt to C:\\var\\lib\\rancher\\agent\\work\\20220506-205938\\c552d8c2fb5ad5faa89cabef62663b48de11a4b538a3491faf9bbcbd5a624cde_0\\sha256sum-amd64.txt"
time="2022-05-06T20:59:40Z" level=info msg="Extracting file Files/bin/run.ps1 to C:\\var\\lib\\rancher\\agent\\work\\20220506-205938\\c552d8c2fb5ad5faa89cabef62663b48de11a4b538a3491faf9bbcbd5a624cde_0\\run.ps1"
time="2022-05-06T20:59:45Z" level=info msg="[Applyinator] Running command: powershell.exe [-File run.ps1]"
time="2022-05-06T20:59:46Z" level=info msg="[c552d8c2fb5ad5faa89cabef62663b48de11a4b538a3491faf9bbcbd5a624cde_0:stdout]: INFO: Checking if RKE2 agent service exists       "
time="2022-05-06T20:59:46Z" level=info msg="[c552d8c2fb5ad5faa89cabef62663b48de11a4b538a3491faf9bbcbd5a624cde_0:stdout]: INFO: RKE2 agent service found, stopping now      "
time="2022-05-06T20:59:47Z" level=info msg="[c552d8c2fb5ad5faa89cabef62663b48de11a4b538a3491faf9bbcbd5a624cde_0:stdout]: [INFO] Windows feature: 'Containers' is installed. Installation will proceed."
time="2022-05-06T20:59:47Z" level=info msg="[c552d8c2fb5ad5faa89cabef62663b48de11a4b538a3491faf9bbcbd5a624cde_0:stdout]: Using stable channel of rke2 for installation"
time="2022-05-06T20:59:47Z" level=info msg="[c552d8c2fb5ad5faa89cabef62663b48de11a4b538a3491faf9bbcbd5a624cde_0:stdout]: [INFO] staging local binary tarball from C:\\var\\lib\\rancher\\agent\\work\\20220506-205938\\c552d8c2fb5ad5faa89cabef62663b48de11a4b538a3491faf9bbcbd5a624cde_0/rke2.windows-amd64.tar.gz"
time="2022-05-06T20:59:48Z" level=info msg="[c552d8c2fb5ad5faa89cabef62663b48de11a4b538a3491faf9bbcbd5a624cde_0:stdout]: [INFO] verifying tarball"
time="2022-05-06T20:59:48Z" level=info msg="[c552d8c2fb5ad5faa89cabef62663b48de11a4b538a3491faf9bbcbd5a624cde_0:stdout]: [INFO] unpacking tarball file to c:/usr/local"
time="2022-05-06T20:59:50Z" level=info msg="[c552d8c2fb5ad5faa89cabef62663b48de11a4b538a3491faf9bbcbd5a624cde_0:stdout]: [INFO] install complete; you may want to run:  $env:PATH+=\";c:/usr/local\\bin;C:\\var\\lib\\rancher\\rke2\\bin\""
time="2022-05-06T20:59:50Z" level=info msg="[c552d8c2fb5ad5faa89cabef62663b48de11a4b538a3491faf9bbcbd5a624cde_0:stdout]: INFO: RKE2 agent service not found, enabling agent service"
time="2022-05-06T20:59:52Z" level=info msg="[c552d8c2fb5ad5faa89cabef62663b48de11a4b538a3491faf9bbcbd5a624cde_0:stderr]: time=\"2022-05-06T20:59:51Z\" level=fatal msg=\"The specified service already exists.\""
time="2022-05-06T20:59:57Z" level=info msg="[c552d8c2fb5ad5faa89cabef62663b48de11a4b538a3491faf9bbcbd5a624cde_0:stdout]: INFO: Starting for RKE2 agent service             "
time="2022-05-06T20:59:57Z" level=info msg="[Applyinator] Command powershell.exe [-File run.ps1] finished with err: <nil> and exit code: 0"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x1346333]

goroutine 311 [running]:
github.com/rancher/system-agent/pkg/prober.GetSystemCertPool(0xc00018d0d0, 0x7, 0x0, 0x0, 0x0)
        C:/gopath/pkg/mod/github.com/rancher/system-agent@v0.2.6/pkg/prober/prober_windows.go:48 +0x173
github.com/rancher/system-agent/pkg/prober.DoProbe(0xc00018d0d0, 0x7, 0x1, 0x5, 0x1, 0x2, 0xc00020e940, 0x1e, 0x0, 0x0, ...)
        C:/gopath/pkg/mod/github.com/rancher/system-agent@v0.2.6/pkg/prober/prober.go:61 +0xaa5
github.com/rancher/system-agent/pkg/prober.DoProbes.func1(0xc000ffe1d0, 0xc0006618c0, 0x18e34582201, 0xc00018d0d0, 0x7, 0xc00018d0d0, 0x7, 0x1, 0x5, 0x1, ...)
        C:/gopath/pkg/mod/github.com/rancher/system-agent@v0.2.6/pkg/prober/probes.go:27 +0x2b5
created by github.com/rancher/system-agent/pkg/prober.DoProbes
        C:/gopath/pkg/mod/github.com/rancher/system-agent@v0.2.6/pkg/prober/probes.go:15 +0x1c8
```

**Comment by markusewalker** [comment]
Considering that we are seeing a different issue related to the `rancher-wins` service not starting, I am going to spin up a separate issue for that. I will leave this issue open as well so that both issues get addressed in tandem.

**Comment by markusewalker** [comment]
Verified in  `2.6.5-rc91 with `v2.6-5f5fb230e6267ad1a4bd80e2ae20ede37f9e894b-head`.

**ENVIRONMENT DETAILS**
- Rancher HA
- RKE2 version: `v1.22.9+rke2r2`
     - 3 etcd, 2 cp, 5 worker (3 Linux, 2 Windows)
- Browser: Chrome

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher and navigate to the UI in a browser.
2. Created a standard user and logged into Rancher as that user.
3. Created a downstream RKE2 custom cluster with Window worker nodes.
4. Verified that Cluster Management has status `Active` and that all the nodes come up as `Active`:
![image](https://user-images.githubusercontent.com/52591819/167724893-0e991376-c439-4b1a-a322-1f37ab78c50e.png)
![image](https://user-images.githubusercontent.com/52591819/167724929-a7d459e0-df0c-46cd-a350-f6e8231c32f9.png)
5. Verified that in Cluster Explorer the status of the cluster and nodes show as `Active` as well:
![Screen Shot 2022-05-10 at 2 29 33 PM](https://user-images.githubusercontent.com/52591819/167725119-3385f4d8-5e2a-4586-aed9-b585b9c68ba8.png)
