### ISSUE TITLE
Registration always gives 401 after destroying and rebuilding rancher ui host

### ISSUE THREAD

**Issue by remkade** [rancher/rancher#3784]
Rancher Version: 0.59.1

Docker Version: 1.10.2

OS: ubuntu

Steps to Reproduce: Run rancher docker container with MySQL on an external host. Then destroy the host that is running the rancher UI. Fire up a new host running rancher ui pointing at external mysql. If you then login and fix the host registration URL and attempt to register a new node it will always fail with a 401.

Results: 
Registration container:

```
INFO: docker info: No Proxy:
INFO: Attempting to connect to: http://10.0.0.88/v1
INFO: http://10.0.0.88/v1 is accessible
INFO: Inspecting host capabilities
INFO: System: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
Traceback (most recent call last):
  File "./register.py", line 11, in <module>
    secret_key=os.environ['CATTLE_REGISTRATION_SECRET_KEY'])
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 45, in from_env
    return gdapi.from_env(prefix=prefix, factory=Client, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 608, in from_env
    return _from_env(prefix=prefix, factory=factory, **args)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 627, in _from_env
    return factory(**result)
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 12, in __init__
    super(Client, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 195, in __init__
    self._load_schemas()
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 313, in _load_schemas
    response = self._get_response(self._url)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 264, in _get_response
    self._error(r.text)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 253, in _error
    raise ApiError(self._unmarshall(text))
gdapi.ApiError: (ApiError(...), "Unauthorized : Unauthorized\n{'status': 401, 'code': u'Unauthorized', 'links': {}, 'detail': None, 'actions': {}, 'message': u'Unauthorized', 'type': u'error', 'id': u'f8c97285-36df-44ea-b10f-40910efd7f37'}")
```

Rancher Server:

```
time="2016-03-04T22:21:34Z" level=info msg="Exiting go-machine-service..."
time="2016-03-04T22:21:34Z" level=info msg="Starting rancher-compose-executor" version=v0.7.2
time="2016-03-04T22:21:34Z" level=fatal msg="Unable to create event router" error="Bad response statusCode [401]. Status [401 Unauthorized]. Body: [code=Unauthorized, message=Unauthorized] from [http://10.0.0.88/v1]"
time="2016-03-04T22:21:36Z" level=info msg="Setting log level" logLevel=info
time="2016-03-04T22:21:36Z" level=info msg="Starting go-machine-service..." gitcommit=5023ae4
time="2016-03-04T22:21:36Z" level=error msg="Unable to create EventRouter" Err="Bad response statusCode [401]. Status [401 Unauthorized]. Body: [code=Unauthorized, message=Unauthorized] from [http://10.0.0.88/v1]"
time="2016-03-04T22:21:36Z" level=info msg="Exiting go-machine-service..."
time="2016-03-04T22:21:36Z" level=info msg="Starting rancher-compose-executor" version=v0.7.2
time="2016-03-04T22:21:36Z" level=fatal msg="Unable to create event router" error="Bad response statusCode [401]. Status [401 Unauthorized]. Body: [code=Unauthorized, message=Unauthorized] from [http://10.0.0.88/v1]"
```

Expected: registration to succeed.

**Comment by remkade** [comment]
This was a misconfiguration with nginx. I was redirecting :80 -> :443, although I don't know why a 401 was being triggered for this.

**Comment by aemneina** [comment]
I see this issue when hosts are removed from an environment, cleaned up (removing /var/lib/rancher) then added back to the same env. Forum post that's related: https://forums.rancher.com/t/solved-rancher-agent-401-error/1841

**Comment by hdep** [comment]
Hello,

I think I might have the same issue. 
what I did : 
- delete the host from rancher UI,
- moving /var/lib/docker to /applis/docker 
- trying to redeploy the node I got the following error : 


```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
INFO: Starting agent for D7C4F107E2A8D538F9DA
INFO: Access Key: D7C4F107E2A8D538F9DA
INFO: Config URL: https://rancher.recette.local/v1
INFO: Storage URL: https://rancher.recette.local/v1
INFO: API URL: https://rancher.recette.local/v1
INFO: IP: 192.168.9.101
INFO: Port:
INFO: Required Image: rancher/agent:v1.0.2
INFO: Current Image: rancher/agent:v1.0.2
INFO: Using image rancher/agent:v1.0.2
INFO: Downloading agent https://rancher.recette.local/v1/configcontent/configscripts
{"id":"22cd9f6a-7cb6-47ab-8dee-302030ff49a5","type":"error","links":{},"actions":{},"status":401,"code":"Unauthorized","message":"Unauthorized","detail":null}
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

My rancher server is using external database too.
Any idea ?

**Comment by aemneina** [comment]
@hdep  i think youre talking about a different issue. Can you remove the host, remove `/var/lib/rancher` from that host, then re-add it back to rancher?

@remkade I believe its a similar issue for the rancher server. I dont think `/var/lib/rancher` exists in more modern rancher versions (1.3+) anymore. Going to close this out, feel free to reopen if this is reproducible there.

**Comment by junkiebev** [comment]
You might want to note in that comment that one should not remove ` /var/lib/rancher` if one is running RancherOS :)
