### ISSUE TITLE
canal/calico-node - ipset v7.1: Kernel and userspace incompatible

### ISSUE THREAD

**Issue by Raboo** [rancher/rancher#38017]
**Rancher Server Setup**
- Rancher version: 2.6.5
- Installation option (Docker install/Helm Chart): helm, rke1

**Information about the Cluster**
- Kubernetes version: v1.22.9
- Cluster Type (Local/Downstream): Custom

**Information about underlying OS**
- OS: Flatcar Linux
- Release: Beta Channel / 3227.1.0
- Kernel: 5.15.43
- ipset: ipset v7.11, protocol version: 7

**Describe the bug**
Canal container calico-node fails to run properly, it's failing to get ready and keeps spamming the same error.

**To Reproduce**
On Flatcar Linux 3227.1.0 upgrade your Kubernetes cluster to v1.22.9.

**Result**
Canal pods never enter a "Running" state.

**Expected Result**
Canal pods should enter "Running" state.

**Screenshots**

Logs from the calico-node container

```
2022-06-16 10:20:15.978 [WARNING][2189649] felix/ipsets.go 322: Failed to resync with dataplane error=exit status 1 family="inet"
2022-06-16 10:20:16.237 [ERROR][2189649] felix/ipsets.go 574: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v7.1: Kernel and userspace incompatible: settype hash:ip,port with revision 6 not supported by userspace.\n"
2022-06-16 10:20:16.237 [WARNING][2189649] felix/ipsets.go 322: Failed to resync with dataplane error=exit status 1 family="inet"
2022-06-16 10:20:16.754 [ERROR][2189649] felix/ipsets.go 974: Failed to read IP sets error=exit status 1 family="inet"
2022-06-16 10:20:16.754 [PANIC][2189649] felix/ipsets.go 355: Failed to update IP sets after multiple retries. family="inet"
panic: (*logrus.Entry) 0xc000fb00f0
goroutine 269 [running]:
github.com/sirupsen/logrus.Entry.log(0xc000140180, 0xc000a49500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/go/pkg/mod/github.com/projectcalico/logrus@v1.0.4-calico/entry.go:128 +0x6c5
github.com/sirupsen/logrus.(*Entry).Panic(0xc0007cd130, 0xc001723b80, 0x1, 0x1)
/go/pkg/mod/github.com/projectcalico/logrus@v1.0.4-calico/entry.go:173 +0xfa
github.com/projectcalico/felix/ipsets.(*IPSets).ApplyUpdates(0xc0006292c0)
/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20211111175437-b56ed543a3fb/ipsets/ipsets.go:355 +0x37a
github.com/projectcalico/felix/dataplane/linux.(*InternalDataplane).apply.func1(0xc0005b4c00, 0xc000ba6290, 0x370df90, 0xc0006292c0)
/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20211111175437-b56ed543a3fb/dataplane/linux/int_dataplane.go:1808 +0x35
created by github.com/projectcalico/felix/dataplane/linux.(*InternalDataplane).apply
/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20211111175437-b56ed543a3fb/dataplane/linux/int_dataplane.go:1807 +0x4ae
W0616 10:20:17.025597 2189717 warnings.go:70] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0616 10:20:17.048016 2189717 warnings.go:70] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
2022-06-16 10:20:17.376 [ERROR][2189717] felix/ipsets.go 574: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v7.1: Kernel and userspace incompatible: settype hash:ip,port with revision 6 not supported by userspace.\n"
2022-06-16 10:20:17.376 [WARNING][2189717] felix/ipsets.go 322: Failed to resync with dataplane error=exit status 1 family="inet"
2022-06-16 10:20:17.380 [ERROR][2189717] felix/ipsets.go 574: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v7.1: Kernel and userspace incompatible: settype hash:ip,port with revision 6 not supported by userspace.\n" 
```

**Additional context**

I was able to work around this error by editing the canal DaemonSet.
Simply replace all images that has version v3.21.1 with v3.22.2.
calico-node v3.21.1 has ipset v7.1, v3.22.2 has ipset v7.11

**Comment by Raboo** [comment]
I believe that to avoid this, there should be some mechanism for running specific canal versions based on what kernel/ipset version you have on your hosts.

**Comment by B3DTech** [comment]
Is there an update on this?  I'm running into the same thing trying to run metalLB.  After installing metallb, it appears there's a routing issue, and I can't get any responses on the ip pool I have configured.  It does work when accessing it directly from a node.  The resolution is supposed to be have kubeproxy use itvs mode instead, however that causes issues with Canal.  

    kubeproxy:
      extra_args:
        ipvs-strict-arp: 'true'
        proxy-mode: ipvs


`

2022-09-26 18:23:57.444 [WARNING][15138] felix/ipsets.go 322: Failed to resync with dataplane error=exit status 1 family="inet"
2022-09-26 18:23:57.704 [ERROR][15138] felix/ipsets.go 574: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v7.1: Kernel and userspace incompatible: settype hash:ip,port with revision 6 not supported by userspace.\n"
2022-09-26 18:23:57.705 [WARNING][15138] felix/ipsets.go 322: Failed to resync with dataplane error=exit status 1 family="inet"
2022-09-26 18:23:58.221 [ERROR][15138] felix/ipsets.go 974: Failed to read IP sets error=exit status 1 family="inet"
2022-09-26 18:23:58.221 [PANIC][15138] felix/ipsets.go 355: Failed to update IP sets after multiple retries. family="inet"
panic: (*logrus.Entry) 0xc00091cf00
 
goroutine 236 [running]:
github.com/sirupsen/logrus.Entry.log({0xc00012e180, 0xc0003e8060, {0x0, 0x0, 0x0}, 0x0, {0x0, 0x0}, 0x0}, 0x0, ...)
/go/pkg/mod/github.com/projectcalico/logrus@v1.0.4-calico/entry.go:128 +0x56c
github.com/sirupsen/logrus.(*Entry).Panic(0xc0006ccf00, {0xc000a6fb80, 0x1, 0x1})
/go/pkg/mod/github.com/projectcalico/logrus@v1.0.4-calico/entry.go:173 +0xfb
github.com/projectcalico/calico/felix/ipsets.(*IPSets).ApplyUpdates(0xc000b05900)
/go/src/github.com/projectcalico/calico/felix/ipsets/ipsets.go:355 +0x737
github.com/projectcalico/calico/felix/dataplane/linux.(*InternalDataplane).apply.func1({0x324f590, 0xc000b05900})
/go/src/github.com/projectcalico/calico/felix/dataplane/linux/int_dataplane.go:1822 +0x3d
created by github.com/projectcalico/calico/felix/dataplane/linux.(*InternalDataplane).apply
/go/src/github.com/projectcalico/calico/felix/dataplane/linux/int_dataplane.go:1821 +0xd88

`
