### ISSUE TITLE
Observed a panic: "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by themonaminor** [rancher/rancher#38142]
### the server is working fine and I can access the UI also. but after some time i got the error as

**Observed a panic: 
```
invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)**
goroutine 3662 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x37f4160, 0x6eaa280})
        /go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/runtime/runtime.go:74 +0x7d
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xfffffffe})
        /go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/runtime/runtime.go:48 +0x75
panic({0x37f4160, 0x6eaa280})
        /usr/lib64/go/1.17/src/runtime/panic.go:1038 +0x215
github.com/rancher/rancher/pkg/controllers/management/aks.(*aksOperatorController).onClusterChange(0xc001894410, {0xc0060b1b68, 0x40b2d4}, 0x3e41980)
        /go/src/github.com/rancher/rancher/pkg/controllers/management/aks/aks_cluster_handler.go:183 +0x811
github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3.FromClusterHandlerToHandler.func1({0xc002102840, 0x393bf333c2d}, {0x47b41b0, 0xc0055da000})
        /go/src/github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3/cluster.go:105 +0x44
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc0055da000, {0xc002102840, 0x4015ceb}, {0x47b41b0, 0xc0055da000})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc00024e3c0, {0xc002102840, 0x7}, {0x47b41b0, 0xc0015b6000})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000a9e580, {0xc002102840, 0x7})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:220 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000a9e580, {0x35bd920, 0xc00807bf30})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:201 +0x10e
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000a9e580)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:178 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:167
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f49119e0fb8)
        /go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000b7e280, {0x47886e0, 0xc0040c4360}, 0x1, 0xc00170e960)
        /go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x90, 0x440c45)
        /go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0xc001845758, 0xc001845778, 0xc001845768)
        /go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:90 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:135 +0x2c6
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe8 pc=0x2cf8ab1]

goroutine 3662 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xfffffffe})
        /go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/runtime/runtime.go:55 +0xd8
panic({0x37f4160, 0x6eaa280})
        /usr/lib64/go/1.17/src/runtime/panic.go:1038 +0x215
github.com/rancher/rancher/pkg/controllers/management/aks.(*aksOperatorController).onClusterChange(0xc001894410, {0xc0060b1b68, 0x40b2d4}, 0x3e41980)
        /go/src/github.com/rancher/rancher/pkg/controllers/management/aks/aks_cluster_handler.go:183 +0x811
github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3.FromClusterHandlerToHandler.func1({0xc002102840, 0x393bf333c2d}, {0x47b41b0, 0xc0055da000})
        /go/src/github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3/cluster.go:105 +0x44
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc0055da000, {0xc002102840, 0x4015ceb}, {0x47b41b0, 0xc0055da000})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc00024e3c0, {0xc002102840, 0x7}, {0x47b41b0, 0xc0015b6000})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000a9e580, {0xc002102840, 0x7})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:220 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000a9e580, {0x35bd920, 0xc00807bf30})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:201 +0x10e
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000a9e580)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:178 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:167
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f49119e0fb8)
        /go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000b7e280, {0x47886e0, 0xc0040c4360}, 0x1, 0xc00170e960)
        /go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x90, 0x440c45)
        /go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0xc001845758, 0xc001845778, 0xc001845768)
        /go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:90 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:135 +0x2c6**
```

### let me know which one is the right version to choose that does have this kind of issue.**

**Comment by themonaminor** [comment]
the same issue also there in 2.6.3 version of rancher helm chart.

**Comment by Oats87** [comment]
This shouldn't be considered stale. 

We should triage and fix this if we have not already @Sahota1225 @snasovich

**Comment by markusewalker** [comment]
**QA TEST PLAN**
1. Setup Rancher with AKS v1.22.6 as the local cluster, create a standard user and login as that user.
2. Navigate to Cluster Explorer > local > Deployments > rancher.
3. View the Rancher logs and note if there is a panic that occurs in this setup.

**Comment by markusewalker** [comment]
Unable to reproduce this using Rancher Helm chart `2.6.5`.

**ENVIRONMENT DETAILS**
- Rancher install: Helm w/AKS as local cluster
- Rancher version: `v2.6.5`
- Browser: Chrome

**TEST RESULT
NON-REPRO**

**REPRODUCTION STEPS**
1. Setup Rancher with AKS `v1.22.6` as the local cluster and navigated to the UI.
2. Navigated to Cluster Explorer > local > Deployments > `rancher`
3. Viewed the Rancher logs over an hour and did not see signs of a panic noting `invalid memory address or nil pointer dereference`.

Additionally, I tested this with `v2.6-head` https://github.com/rancher/rancher/commit/8a2e68267c882a8adf612a29ae2bf3274a4d8572 and was still unable to reproduce this issue.

**Comment by jakefhyde** [comment]
### Root cause

If rancher is stopped while the AKS cluster is being created, it's possible that the `UpstreamSpec` never gets set on the cluster. In later stages, rancher tries to access this field which is `nil`.

### What was fixed, or what changes have occurred

Perform a nil check on `cluster.Status.AKSStatus.UpstreamSpec`, setting it if it is `nil`.

### Areas or cases that should be tested

Once the cluster has moved out of `creating`, (i.e. the cluster has become active), delete the `cluster.Status.AKSStatus.UpstreamSpec` field from the cluster (by setting it to `nil` with a recent version of kubectl (>= 1.24)). On previous versions of rancher, this should cause a panic. On v2.7-head, this should cause the `UpstreamSpec` to be repopulated and synced with the aks-operator.

### What areas could experience regressions?

N/A

### Are the repro steps accurate/minimal?
:heavy_check_mark:

**Comment by markusewalker** [comment]
Validated that I do not see a panic in `v2.7-head` https://github.com/rancher/rancher/commit/55f507606b85f73b6378095399fcabada7f12c99.

**ENVIRONMENT DETAILS**
- Rancher install: Helm w/AKS as local cluster
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/55f507606b85f73b6378095399fcabada7f12c99
- Browser: Chrome
	
**TEST RESULT**
PASS

**REPRODUCTION STEPS**
1. Setup Rancher with AKS as the local cluster, setup a standard user and logged in.
2. Provisioned a downstream hosted AKS cluster; validate that the cluster and nodes are in a state of `Active` in Cluster Management and Cluster Explorer:
![image](https://user-images.githubusercontent.com/52591819/191798049-ecec9cc2-6675-41e7-bebb-d0cac053966d.png)
![image](https://user-images.githubusercontent.com/52591819/191798018-127bab16-d86f-4dad-a86a-cb0768bfe829.png)
![image](https://user-images.githubusercontent.com/52591819/191797998-ec3a2633-286e-41b0-84be-a6523acf360f.png) 
3. Logged back in as the admin user.
4. Downloaded the kubeconfig and cluster YAML of the management cluster and placed in a separate client machine.
5. Edit the cluster YAML through `kubectl edit <cluster-yaml>.yaml` and delete the following line:
     - `cluster.Status.AKSStatus.UpstreamSpec`
6. Saved the changes and navigate to the Rancher logs.
7. Validated that I did not see any panic as a result of removing the above line.
