### ISSUE TITLE
Unable to access accounts and API keys as a standard user 

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#38590]
Setup

Rancher version: 2.6-head 76d89bd
Browser type & version: Chrome

**Describe the bug**
Once we log into rancher server, if we try to access cluster management page or Account the page is stuck in loading and never loads.

**To Reproduce**

1. Create a rancher server on v2.6-head
2. Create a standard user as an admin from Users and auth >> users with standard user permissions
3. logout as admin and log in as the standard user.
4. From user profile >> Accounts & Api keys

**Result**
Page is stuck in loading and  never loads. following console logs are seen:

```
tls.vue?230f:26 TypeError: Cannot read properties of null (reading 'indexOf')
    at f.apiUrlBase (66a1009873864594806e.js:1:39360)
    at Tn.get (vue.runtime.esm.js:4495:25)
    at Tn.evaluate (vue.runtime.esm.js:4597:21)
    at f.apiUrlBase (vue.runtime.esm.js:4851:17)
    at f.apiUrl (66a1009873864594806e.js:1:39519)
    at Tn.get (vue.runtime.esm.js:4495:25)
    at Tn.evaluate (vue.runtime.esm.js:4597:21)
    at f.apiUrl (vue.runtime.esm.js:4851:17)
    at f.<anonymous> (PromptChangePassword.vue:1:1367)
    at t._render (vue.runtime.esm.js:3569:22)

```

**Expected Result**
Expected the page to be accessible as a standard user

**Screenshots**
<img width="300" alt="acciunts" src="https://user-images.githubusercontent.com/38144301/184093694-4835e019-fb68-41ad-b673-e49ba0fb1e56.png">

**Additional context**
Works fine for admin users.

**Comment by MbolotSuse** [comment]
I was able to somewhat repro this issue with the following steps:
- Run rancher/rancher:v2.8-head `5b42ca5`
- Create a new user with `user-base` permissions
- Remove the globalRoleBinding created from the user to `user-base` (must be done through the public api)
- In a new window, login to Rancher as the new user. Click the `Account & API Keys` button. 
- Observe that the UI stays loading permanently, with an error in the console.

This part of the issue needs to be turned back over to the UI team for further investigation, given that users can be created without a GlobalRole in the current team.

The RBAC team should attempt to repro the issue where a user was created with no GlobalRoleBindings, and investigate if that is still an active issue.
