### ISSUE TITLE
Rancher crash with keycloak auth provider [BUG]

### ISSUE THREAD

**Issue by dpzx** [rancher/rancher#38625]
**Rancher Server Setup**
- Rancher version: v2.6.7-rc9
- Installation option (Docker install/Helm Chart): v1.24.2_k3s2
- Proxy/Cert Details: ingress/rancher

**Information about the Cluster**
- Kubernetes version: v1.24.2
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**

The rancher pods crash with the following:

```
E0816 14:49:28.781073      33 runtime.go:79] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
goroutine 2931 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3f478c0, 0xc010d84150})
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0014d54f0})
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/runtime/runtime.go:49 +0x75
panic({0x3f478c0, 0xc010d84150})
        /usr/lib64/go/1.17/src/runtime/panic.go:1038 +0x215
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.getSearchURL({0xc00a08fa40, 0x4})
        /go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_client.go:172 +0xe5
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.(*KeyCloakClient).getFromKeyCloakByID(0xc00187a610, {0xc002e68ed4, 0x24}, {0xc002e68ecd, 0xeda8d942e}, 0xc00c58f0e0)
        /go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_client.go:135 +0xd3
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.(*keyCloakOIDCProvider).GetPrincipal(_, {_, _}, {{{0xc00187a599, 0x5}, {0xc001832a68, 0x17}}, {{0xc00187a600, 0xb}, {0xc00187a5c0, ...}, ...}, ...})
        /go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_provider.go:150 +0x2e7
github.com/rancher/rancher/pkg/auth/providers.GetPrincipal({_, _}, {{{0xc00187a599, 0x5}, {0xc001832a68, 0x17}}, {{0xc00187a600, 0xb}, {0xc00187a5c0, 0x6}, ...}, ...})
        /go/src/github.com/rancher/rancher/pkg/auth/providers/providers.go:164 +0x10e
github.com/rancher/rancher/pkg/auth/providerrefresh.(*refresher).refreshAttributes(0xc001476f00, 0xc0086c8580)
        /go/src/github.com/rancher/rancher/pkg/auth/providerrefresh/refresher.go:256 +0xc08
github.com/rancher/rancher/pkg/auth/providerrefresh.RefreshAttributes(0xc0086c8580)
        /go/src/github.com/rancher/rancher/pkg/auth/providerrefresh/daemon.go:83 +0x99
github.com/rancher/rancher/pkg/controllers/management/auth.(*UserAttributeController).sync(0xc00304c530, {0xc0014d5f40, 0x0}, 0xe)
        /go/src/github.com/rancher/rancher/pkg/controllers/management/auth/user_attribute_handler.go:39 +0x5f
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*userAttributeController).AddHandler.func1({0xc002dfad20, 0xc}, {0x418c100, 0xc0086c8580})
        /go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_user_attribute_controller.go:155 +0x42
github.com/rancher/norman/controller.(*genericController).AddHandler.func1({0xc002dfad20, 0xc}, {0x4b37fc8, 0xc0086c8580})
        /go/pkg/mod/github.com/rancher/norman@v0.0.0-20220627222520-b74009fac3ff/controller/generic_controller.go:60 +0x191
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc003060f40, {0xc002dfad20, 0x40d214}, {0x4b37fc8, 0xc0086c8580})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000fe04b0, {0xc002dfad20, 0xc}, {0x4b37fc8, 0xc0086c8580})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000a231e0, {0xc002dfad20, 0xc})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:233 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000a231e0, {0x37c5e40, 0xc0014d54f0})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:214 +0x10e
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000a231e0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:191 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:180
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fca57fcc328)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0, {0x4b09620, 0xc00380ec90}, 0x1, 0xc001cde960)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:90 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:148 +0x2c6
panic: runtime error: index out of range [1] with length 1 [recovered]
        panic: runtime error: index out of range [1] with length 1

goroutine 2931 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0014d54f0})
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/runtime/runtime.go:56 +0xd8
panic({0x3f478c0, 0xc010d84150})
        /usr/lib64/go/1.17/src/runtime/panic.go:1038 +0x215
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.getSearchURL({0xc00a08fa40, 0x4})
        /go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_client.go:172 +0xe5
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.(*KeyCloakClient).getFromKeyCloakByID(0xc00187a610, {0xc002e68ed4, 0x24}, {0xc002e68ecd, 0xeda8d942e}, 0xc00c58f0e0)
        /go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_client.go:135 +0xd3
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.(*keyCloakOIDCProvider).GetPrincipal(_, {_, _}, {{{0xc00187a599, 0x5}, {0xc001832a68, 0x17}}, {{0xc00187a600, 0xb}, {0xc00187a5c0, ...}, ...}, ...})
        /go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_provider.go:150 +0x2e7
github.com/rancher/rancher/pkg/auth/providers.GetPrincipal({_, _}, {{{0xc00187a599, 0x5}, {0xc001832a68, 0x17}}, {{0xc00187a600, 0xb}, {0xc00187a5c0, 0x6}, ...}, ...})
        /go/src/github.com/rancher/rancher/pkg/auth/providers/providers.go:164 +0x10e
github.com/rancher/rancher/pkg/auth/providerrefresh.(*refresher).refreshAttributes(0xc001476f00, 0xc0086c8580)
        /go/src/github.com/rancher/rancher/pkg/auth/providerrefresh/refresher.go:256 +0xc08
github.com/rancher/rancher/pkg/auth/providerrefresh.RefreshAttributes(0xc0086c8580)
        /go/src/github.com/rancher/rancher/pkg/auth/providerrefresh/daemon.go:83 +0x99
github.com/rancher/rancher/pkg/controllers/management/auth.(*UserAttributeController).sync(0xc00304c530, {0xc0014d5f40, 0x0}, 0xe)
        /go/src/github.com/rancher/rancher/pkg/controllers/management/auth/user_attribute_handler.go:39 +0x5f
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*userAttributeController).AddHandler.func1({0xc002dfad20, 0xc}, {0x418c100, 0xc0086c8580})
        /go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_user_attribute_controller.go:155 +0x42
github.com/rancher/norman/controller.(*genericController).AddHandler.func1({0xc002dfad20, 0xc}, {0x4b37fc8, 0xc0086c8580})
        /go/pkg/mod/github.com/rancher/norman@v0.0.0-20220627222520-b74009fac3ff/controller/generic_controller.go:60 +0x191
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc003060f40, {0xc002dfad20, 0x40d214}, {0x4b37fc8, 0xc0086c8580})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000fe04b0, {0xc002dfad20, 0xc}, {0x4b37fc8, 0xc0086c8580})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000a231e0, {0xc002dfad20, 0xc})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:233 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000a231e0, {0x37c5e40, 0xc0014d54f0})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:214 +0x10e
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000a231e0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:191 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:180
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fca57fcc328)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0, {0x4b09620, 0xc00380ec90}, 0x1, 0xc001cde960)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:90 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:148 +0x2c6
```

**To Reproduce**

I'm not sure what the cause is because the initial creation of the keycloak auth provider and login is successful. There would be one pod still running and the other two would be on a crash loop.

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Comment by Befisch** [comment]
Hi,
we have the exact same issue.

**Setup:**
Rancher 2.6.7 (we waited for this because of k8s 1.24)
Keycloak 19
Both on v1.23.8+k3s2

additionally two Clusters added:
Kubernetes 1.23
Kubernetes 1.24

**Describe the Bug:**
We added the Keycloak auth and enabled it.
After checking, everything is fine.

First User logs in

Rancher Pods in Crashloop.

**How to reproduce:**
- Disable Keycloak auth
- Redeploy Rancher (keep it fresh :) )
- Enable Keycloak auth
- Login with some new user

Pods will enter Crashloop. One after another.

Errormessage is exactly the same as described above.

**Comment by AlexisDucastel** [comment]
Hi everyone, exact same problem with rancher 2.6.7 using keycloak IDP on k8s 1.24.

The bug seems to not appear on rancher wieh keycloak on k8s 1.23 !

**Comment by AlexisDucastel** [comment]
Temporary workaround to disable Keycloak ⚠️ **OIDC** ⚠️ provider and retrieve a functionnal Rancher (without Keycloak of course) : 

## 1 : Stop Rancher
```
k -n cattle-system scale deploy/rancher --replicas=0
```

## 2 : Backup authconfig keycloak CRD in a configmap
```
k get authconfigs keycloakoidc -o yaml > rancher.authconfig.keycloakoidc.backup.yaml
k -n cattle-system create cm rancher-issue-38625-backup --from-file=rancher.authconfig.keycloakoidc.backup.yaml
```

## 3 : Replace config with no keycloak config
```
k delete authconfigs keycloakoidc
k apply -f - <<EOF
apiVersion: management.cattle.io/v3
kind: AuthConfig
metadata:
  labels:
    cattle.io/creator: norman
  name: keycloakoidc
type: keyCloakOIDCConfig
EOF
```

## 4 : Start Rancher 
Let's begin with 1 replica, but if it works, don't forget to get the right number of replicas depending on your setup
```
k -n cattle-system scale deploy/rancher --replicas=1
```

This should allow you to login to Rancher with Local accounts and continue to work while waiting for a fix.

**Comment by Mumie-hub** [comment]
Same problem here. Problem exists since v2.6.7.
Best Regards

**Comment by bpedersen2** [comment]
https://github.com/rancher/rancher/blob/v2.6.7/pkg/auth/providers/keycloakoidc/keycloak_client.go#L167-L174 

seems to be the problem with fresh keycloak install > keycloak17.  The standard url does not contain the auth prefix anymore.

Related to #38480,  duplicated by #38683

**Comment by AlexisDucastel** [comment]
In fact it was functionnal without the "auth" prefix before 2.6.7, we just had to go with custom URL. 
But the current bug is not related to this imho.

**Comment by AlexisDucastel** [comment]
Any news on this issue ? We are still using the workaround by disabling keycloak, but we need to reactivate it.

**Comment by dmlabs** [comment]
We are facing the same issue with Rancher 2.6.8 on K3s v1.24.6+k3s1 and Keycloak 19.0.2 with the Keycloak OIDC auth provider.

**Comment by dpzx** [comment]
@dmlabs there's a PR #38822 open to resolve the issue but someone needs to test backward compatibility. new keycloak removed /auth as the root context and you can specify your own.

**Comment by dmlabs** [comment]
@dpzx I set the Issuer and Authorization Endpoint exactly like defined in https://keycloak.example.com/realms/demo/.well-known/openid-configuration. Rancher accepted the configuration and I was able to login with Keycloak but Rancher crashes with the "panic: runtime error: index out of range [1] with length 1" after a while.

**Comment by daemonadmin** [comment]
Upgrade to 2.6.9 didn't resolve issue.
k get po -n cattle-system -o wide
NAME                             READY   STATUS             RESTARTS       AGE   IP            
rancher-7d5df87f75-rslw2         0/1     CrashLoopBackOff   4 (71s ago)    17m   10.42.0.15 
rancher-7d5df87f75-shf4g         0/1     Error              4 (2m4s ago)   17m   10.42.16.33  
rancher-webhook-d6f8b6cb-lq7tn   1/1     Running            0              3d    10.42.16.32

Log:
`2022/10/20 10:15:53 [INFO] Starting cluster.x-k8s.io/v1alpha3, Kind=Cluster controller
E1020 10:15:53.745975      33 runtime.go:79] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
goroutine 5393 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3de0fc0?, 0xc00a170150})
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xfffffffe?})
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/runtime/runtime.go:49 +0x75
panic({0x3de0fc0, 0xc00a170150})
        /usr/lib64/go/1.19/src/runtime/panic.go:884 +0x212
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.getSearchURL({0xc006b9aed0?, 0x0?})
        /go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_client.go:172 +0xe5
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.(*KeyCloakClient).getFromKeyCloakByID(0xc0075ed308?, {0xc0057e3d14, 0x24}, {0xc0057e3d0d, 0x4}, 0xc00e3ad0e0)
        /go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_client.go:135 +0xb9
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.(*keyCloakOIDCProvider).GetPrincipal(_, {_, _}, {{{0x40d5d10, 0x5}, {0xc00a199f50, 0x17}}, {{0xc0075ed310, 0xb}, {0xc0075ed2b0, ...}, ...}, ...})
        /go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_provider.go:150 +0x2a5
github.com/rancher/rancher/pkg/auth/providers.GetPrincipal({_, _}, {{{0x40d5d10, 0x5}, {0xc00a199f50, 0x17}}, {{0xc0075ed310, 0xb}, {0xc0075ed2b0, 0x6}, ...}, ...})
        /go/src/github.com/rancher/rancher/pkg/auth/providers/providers.go:164 +0x105
github.com/rancher/rancher/pkg/auth/providerrefresh.(*refresher).refreshAttributes(0xc0100d5f80, 0xc0064246e0?)
        /go/src/github.com/rancher/rancher/pkg/auth/providerrefresh/refresher.go:281 +0xfc8
github.com/rancher/rancher/pkg/auth/providerrefresh.RefreshAttributes(0xc0064246e0)
        /go/src/github.com/rancher/rancher/pkg/auth/providerrefresh/daemon.go:83 +0x99
github.com/rancher/rancher/pkg/controllers/management/auth.(*UserAttributeController).sync(0xc00dc447f0, {0xc008820230?, 0x0?}, 0x7365756c6176223a?)
        /go/src/github.com/rancher/rancher/pkg/controllers/management/auth/user_attribute_handler.go:39 +0x5f
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*userAttributeController).AddHandler.func1({0xc00c3cb260?, 0xa?}, {0x4028ee0?, 0xc0064246e0?})
        /go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_user_attribute_controller.go:155 +0x42
github.com/rancher/norman/controller.(*genericController).AddHandler.func1({0xc00c3cb260, 0xa}, {0x49f2928?, 0xc0064246e0})
        /go/pkg/mod/github.com/rancher/norman@v0.0.0-20220627222520-b74009fac3ff/controller/generic_controller.go:60 +0x18b
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0x227b3a22736c6562?, {0xc00c3cb260?, 0xc005373c48?}, {0x49f2928?, 0xc0064246e0?})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc0007bd180, {0xc00c3cb260, 0xa}, {0x49f2928, 0xc0064246e0})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc00049de40, {0xc00c3cb260, 0xa})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:233 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc00049de40, {0x3659060?, 0xc00d94e770?})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:214 +0x105
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc00049de40)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:191 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc003dd7ea0?)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:180 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x6e69727473?)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x6f6f68632079616d?, {0x49e7fc0, 0xc00540c720}, 0x1, 0xc00013d740)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x20746f6e2079616d?, 0x3b9aca00, 0x0, 0x67?, 0x2a8000190007a00?)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x1f7127974697265?, 0x5301d2220012000a?, 0x2079746972657665?)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:90 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:148 +0x2a7
panic: runtime error: index out of range [1] with length 1 [recovered]
        panic: runtime error: index out of range [1] with length 1

goroutine 5393 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xfffffffe?})
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/runtime/runtime.go:56 +0xd7
panic({0x3de0fc0, 0xc00a170150})
        /usr/lib64/go/1.19/src/runtime/panic.go:884 +0x212
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.getSearchURL({0xc006b9aed0?, 0x0?})
        /go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_client.go:172 +0xe5
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.(*KeyCloakClient).getFromKeyCloakByID(0xc0075ed308?, {0xc0057e3d14, 0x24}, {0xc0057e3d0d, 0x4}, 0xc00e3ad0e0)
        /go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_client.go:135 +0xb9
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.(*keyCloakOIDCProvider).GetPrincipal(_, {_, _}, {{{0x40d5d10, 0x5}, {0xc00a199f50, 0x17}}, {{0xc0075ed310, 0xb}, {0xc0075ed2b0, ...}, ...}, ...})
        /go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_provider.go:150 +0x2a5
github.com/rancher/rancher/pkg/auth/providers.GetPrincipal({_, _}, {{{0x40d5d10, 0x5}, {0xc00a199f50, 0x17}}, {{0xc0075ed310, 0xb}, {0xc0075ed2b0, 0x6}, ...}, ...})
        /go/src/github.com/rancher/rancher/pkg/auth/providers/providers.go:164 +0x105
github.com/rancher/rancher/pkg/auth/providerrefresh.(*refresher).refreshAttributes(0xc0100d5f80, 0xc0064246e0?)
        /go/src/github.com/rancher/rancher/pkg/auth/providerrefresh/refresher.go:281 +0xfc8
github.com/rancher/rancher/pkg/auth/providerrefresh.RefreshAttributes(0xc0064246e0)
        /go/src/github.com/rancher/rancher/pkg/auth/providerrefresh/daemon.go:83 +0x99
github.com/rancher/rancher/pkg/controllers/management/auth.(*UserAttributeController).sync(0xc00dc447f0, {0xc008820230?, 0x0?}, 0x7365756c6176223a?)
        /go/src/github.com/rancher/rancher/pkg/controllers/management/auth/user_attribute_handler.go:39 +0x5f
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*userAttributeController).AddHandler.func1({0xc00c3cb260?, 0xa?}, {0x4028ee0?, 0xc0064246e0?})
        /go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_user_attribute_controller.go:155 +0x42
github.com/rancher/norman/controller.(*genericController).AddHandler.func1({0xc00c3cb260, 0xa}, {0x49f2928?, 0xc0064246e0})
        /go/pkg/mod/github.com/rancher/norman@v0.0.0-20220627222520-b74009fac3ff/controller/generic_controller.go:60 +0x18b
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0x227b3a22736c6562?, {0xc00c3cb260?, 0xc005373c48?}, {0x49f2928?, 0xc0064246e0?})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc0007bd180, {0xc00c3cb260, 0xa}, {0x49f2928, 0xc0064246e0})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc00049de40, {0xc00c3cb260, 0xa})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:233 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc00049de40, {0x3659060?, 0xc00d94e770?})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:214 +0x105
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc00049de40)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:191 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc003dd7ea0?)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:180 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x6e69727473?)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x6f6f68632079616d?, {0x49e7fc0, 0xc00540c720}, 0x1, 0xc00013d740)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x20746f6e2079616d?, 0x3b9aca00, 0x0, 0x67?, 0x2a8000190007a00?)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x1f7127974697265?, 0x5301d2220012000a?, 0x2079746972657665?)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:90 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:148 +0x2a7`

**Comment by maxnitze** [comment]
Still having the same issue with 2.7.0 with Keycloak 19.0.3. Neither updating nor removing and re-configuring OIDC works. Stopped my upgrade at 2.6.6 and it seems to be working for now.

**Comment by websi96** [comment]
I came up with a solution for my self managed KeyCloak instance (Bitnami Helm Chart): 

Here are the relevant helm values:
```yaml
image:
  tag: 20.0.2-debian-11-r9
proxy: edge
httpRelativePath: /auth/
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"
    nginx.ingress.kubernetes.io/session-cookie-name: "KC-NGINX-SESSION"
    nginx.ingress.kubernetes.io/app-root: /auth
  tls: true
```

- `httpRelativePath` prefixes the `/auth/` path again
- `nginx.ingress.kubernetes.io/app-root: /auth` tells nginx to create a 301 (moved permanently) from `/` to `/auth`

**Comment by boxboatmatt** [comment]
So as a workaround I that I found is to add an additional `allowedPrincipalsId` to the `keycloakoidc` `authconfig`. The singular one you have is from the user who authorized keycloak, so I just grabbed the ID from another admin.


```
...
allowedPrincipalIds:
- keycloakoidc_user://XXXX
- keycloakoidc_user://YYYY
```

**Comment by cbron** [comment]
Appears to be a duplicate of: https://github.com/rancher/rancher/issues/38683
Closing this issue, please track in the above issue. If you disagree or that does not solve this issue please reopen.
