### ISSUE TITLE
[BUG] "View logs" Feature does not work for Windows workloads in RKE2

### ISSUE THREAD

**Issue by twi-github** [rancher/rancher#38643]
**Rancher Server Setup**
- Rancher version:
- Rancher 2.6.6 deployed using Helm on RKE1 cluster.

**Information about the Cluster**
- Kubernetes version: v1.23.7+rke2r2
- Cluster Type (Local/Downstream):
   - downstream, Custom = Running a docker command on a node, 1 Linux Node, 1 Win Server 2019 LTS node

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - Admin

**Describe the bug**

Viewing logs of Windows workloads running on RKE2 is not possible in the Rancher 2.6.6 console.

**To Reproduce**

Run a Windows workload on a windows node. Try to show the log output via the pod windows's "View Logs" button.
**Result**
Only an empty black window.

**Expected Result**
The log output as before on RKE1 clusters.

**Comment by clementhemidy** [comment]
I have the same issue with Rancher 2.6.5.

Since yesterday i cannot see the logs windows (just an empty box).

But my Rancher instance has not been updated for several weeks, I find it hard to believe that it comes from Rancher.

A Chrome update?

**Comment by twi-github** [comment]
A good and valid point! I just tested that scenario, I have the same problem as described with Chrome 102.0.5005.63 and Firefox 103.0.2.

**Comment by chsword** [comment]
same with Rancher 2.6.6

**Comment by longshine** [comment]
Same for me with Rancher 2.6.6, user Admin, Chrome 103.0.5060.134.

When clicking "View logs" on pods, it only shows an emply window, without any logs or buttons.
And from Chrome console it said:

```
TypeError: r.replace is not a function
    at C (opsgenie.vue?578b:153:1)
    at f.rangeOptions (opsgenie.vue?578b:116:9)
    at _n.get (vue.runtime.esm.js:4479:25)
    at _n.evaluate (vue.runtime.esm.js:4584:21)
    at f.rangeOptions (vue.runtime.esm.js:4836:17)
    at fn (rke2.svg:1:2097)
    at Object.r [as title] (vue.runtime.esm.js:2590:62)
    at f.r (rke.svg:1:159)
    at t._render (vue.runtime.esm.js:3548:22)
    at f.r (vue.runtime.esm.js:4066:21)

TypeError: Cannot read properties of undefined (reading 'addEventListener')
    at opsgenie.vue?578b:222:1
    at d (runtime.js:45:40)
    at Generator._invoke (runtime.js:274:22)
    at O.forEach.t.<computed> [as next] (runtime.js:97:21)
    at r (asyncToGenerator.js:3:20)
    at l (asyncToGenerator.js:25:9)
```


However if sign in as another user other than Admin, everything works well.

**Comment by ckothwal123** [comment]
I am facing the same issue on rancher 2.6.6

**Comment by rrgadeev** [comment]
+ v2.6.6

**Comment by exepirit** [comment]
Same issue on Rancher 2.6.6 and Linux containers.

**Comment by mohag** [comment]
https://github.com/rancher/dashboard/issues/6122#issuecomment-1152394027
That is the workaround...

Also see #38575
