### ISSUE TITLE
[BUG] Random panic encountered with managementapi/dynamicschema concurrent map read/write

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#38854]
**Rancher Server Setup**
- Rancher version: v2.6.6
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

On a fresh `docker run` install of Rancher v2.6.6, I encountered a panic due to a concurrent map read/write. Conveniently, I run my Rancher with trace logs and caught the corresponding trace log for it.

Relevant trace:
```
2022/09/09 01:45:36 [TRACE] ClusterController calling handler mgmt-cluster-rbac-remove _all_
2022/09/09 01:45:36 [INFO] uploading harvestercredentialConfig to credentialconfig schema
2022/09/09 01:45:36 [TRACE] REST UPDATE apis/management.cattle.io/v3//dynamicschemas/credentialconfig
2022/09/09 01:45:36 [TRACE] REST UPDATE apis/management.cattle.io/v3//nodedrivers/exoscale
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler whitelist-proxy google
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler node-driver-controller google
2022/09/09 01:45:36 [TRACE] REST UPDATE apis/management.cattle.io/v3//nodedrivers/rackspace
2022/09/09 01:45:36 [TRACE] REST UPDATE apis/management.cattle.io/v3//nodedrivers/vmwarevsphere
2022/09/09 01:45:36 [TRACE] REST UPDATE apis/management.cattle.io/v3//nodedrivers/packet
2022/09/09 01:45:36 [TRACE] REST UPDATE apis/management.cattle.io/v3//nodedrivers/pinganyunecs
2022/09/09 01:45:36 [TRACE] DynamicSchemaController calling handler dynamic-schema credentialconfig
2022/09/09 01:45:36 [TRACE] REST UPDATE apis/management.cattle.io/v3//nodedrivers/pnap
2022/09/09 01:45:36 [TRACE] ClusterController calling handler temporary-credentials local
2022/09/09 01:45:36 [TRACE] ClusterController calling handler restrictedAdminsRBACCluster local
2022/09/09 01:45:36 [TRACE] ClusterController calling handler cluster-secret-migrator local
2022/09/09 01:45:36 [TRACE] [secretmigrator] cluster local already migrated
2022/09/09 01:45:36 [TRACE] ClusterController calling handler scheduledScanHandler:clusterSync local
2022/09/09 01:45:36 [TRACE] ClusterController calling handler management-mcapp-cluster-controller local
2022/09/09 01:45:36 [TRACE] ClusterController calling handler mgmt-cluster-rbac-remove local
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler whitelist-proxy otc
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler node-driver-controller otc
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler whitelist-proxy openstack
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler node-driver-controller openstack
2022/09/09 01:45:36 [TRACE] REST CREATE apis/management.cattle.io/v3/cattle-global-data/rkek8ssystemimages
2022/09/09 01:45:36 [INFO] uploading digitaloceancredentialConfig to credentialconfig schema
2022/09/09 01:45:36 [TRACE] REST UPDATE apis/management.cattle.io/v3//dynamicschemas/credentialconfig
2022/09/09 01:45:36 [TRACE] REST UPDATE apis/management.cattle.io/v3//nodedrivers/softlayer
2022/09/09 01:45:36 [TRACE] REST UPDATE apis/management.cattle.io/v3//nodedrivers/oci
2022/09/09 01:45:36 [TRACE] REST UPDATE apis/management.cattle.io/v3//nodedrivers/aliyunecs
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler whitelist-proxy harvester
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler node-driver-controller harvester
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler whitelist-proxy pinganyunecs
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler node-driver-controller pinganyunecs
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler whitelist-proxy exoscale
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler node-driver-controller exoscale
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler whitelist-proxy pnap
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler node-driver-controller pnap
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler whitelist-proxy packet
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler node-driver-controller packet
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler whitelist-proxy vmwarevsphere
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler node-driver-controller vmwarevsphere
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler whitelist-proxy rackspace
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler node-driver-controller rackspace
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler whitelist-proxy aliyunecs
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler node-driver-controller aliyunecs
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler whitelist-proxy softlayer
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler node-driver-controller softlayer
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler whitelist-proxy oci
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler node-driver-controller oci
2022/09/09 01:45:36 [TRACE] DynamicSchemaController calling handler dynamic-schema credentialconfig
2022/09/09 01:45:36 [INFO] uploading harvestercredentialConfig to credentialconfig schema
2022/09/09 01:45:36 [TRACE] REST UPDATE apis/management.cattle.io/v3//dynamicschemas/credentialconfig
2022/09/09 01:45:36 [TRACE] REST UPDATE apis/management.cattle.io/v3//nodedrivers/nutanix
2022/09/09 01:45:36 [TRACE] REST UPDATE apis/management.cattle.io/v3//nodedrivers/digitalocean
2022/09/09 01:45:36 [DEBUG] getPluginData: no template found for k8sVersion v1.12.6-rancher1-2 plugin nodelocal
2022/09/09 01:45:36 [DEBUG] getPluginData: no template found for k8sVersion v1.12.6-rancher1-2 plugin aci
2022/09/09 01:45:36 [TRACE] REST CREATE apis/management.cattle.io/v3/cattle-global-data/rkek8ssystemimages
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler whitelist-proxy nutanix
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler node-driver-controller nutanix
2022/09/09 01:45:36 [DEBUG] getPluginData: no template found for k8sVersion v1.12.7-rancher1-1 plugin nodelocal
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler whitelist-proxy digitalocean
2022/09/09 01:45:36 [TRACE] NodeDriverController calling handler node-driver-controller digitalocean
2022/09/09 01:45:36 [TRACE] REST UPDATE apis/management.cattle.io/v3//nodedrivers/harvester
2022/09/09 01:45:36 [TRACE] REST UPDATE apis/management.cattle.io/v3//nodedrivers/aliyunecs
2022/09/09 01:45:36 [DEBUG] getPluginData: no template found for k8sVersion v1.12.7-rancher1-1 plugin aci
2022/09/09 01:45:36 [TRACE] REST CREATE apis/management.cattle.io/v3/cattle-global-data/rkek8ssystemimages
2022/09/09 01:45:36 [TRACE] DynamicSchemaController calling handler dynamic-schema credentialconfig
fatal error: concurrent map iteration and map write
2022/09/09 01:45:36 [INFO] uploading linodecredentialConfig to credentialconfig schema
2022/09/09 01:45:36 [TRACE] REST UPDATE apis/management.cattle.io/v3//dynamicschemas/credentialconfig

goroutine 4211 [running]:
runtime.throw({0x407649d, 0x100000000000020})
	/usr/lib64/go/1.17/src/runtime/panic.go:1198 +0x71 fp=0xc006e71138 sp=0xc006e71108 pc=0x4371f1
runtime.mapiternext(0x3eb6000)
	/usr/lib64/go/1.17/src/runtime/map.go:858 +0x4eb fp=0xc006e711a8 sp=0xc006e71138 pc=0x40fceb
runtime.mapiterinit(0x101, 0xc006e71218, 0x49b4ea)
	/usr/lib64/go/1.17/src/runtime/map.go:848 +0x236 fp=0xc006e711c8 sp=0xc006e711a8 pc=0x40f7b6
reflect.mapiterinit(0x37a3200, 0xc00a9b9010)
	/usr/lib64/go/1.17/src/runtime/map.go:1340 +0x45 fp=0xc006e71208 sp=0xc006e711c8 pc=0x464ee5
reflect.(*MapIter).Next(0xc00a9d4f00)
	/usr/lib64/go/1.17/src/reflect/value.go:1626 +0x5a fp=0xc006e71228 sp=0xc006e71208 pc=0x49b3fa
encoding/json.mapEncoder.encode({0xc006e71418}, 0xc0044e6000, {0x37a3200, 0xc00a9b9010, 0x0}, {0x11, 0x0})
	/usr/lib64/go/1.17/src/encoding/json/encode.go:799 +0x305 fp=0xc006e713e8 sp=0xc006e71228 pc=0x74f985
encoding/json.mapEncoder.encode-fm(0x37a3200, {0x37a3200, 0xc00a9b9010, 0x48030e}, {0x20, 0x3d})
	/usr/lib64/go/1.17/src/encoding/json/encode.go:779 +0x45 fp=0xc006e71428 sp=0xc006e713e8 pc=0x75a3a5
encoding/json.structEncoder.encode({{{0xc00309a000, 0x2000, 0x0}, 0xc0061fb410}}, 0xc0044e6000, {0x3e86360, 0xc00a9b8fc0, 0xc003221590}, {0x0, 0x1})
	/usr/lib64/go/1.17/src/encoding/json/encode.go:761 +0x1f4 fp=0xc006e714d8 sp=0xc006e71428 pc=0x74f3d4
encoding/json.structEncoder.encode-fm(0x3e86360, {0x3e86360, 0xc00a9b8fc0, 0x0}, {0x0, 0x0})
	/usr/lib64/go/1.17/src/encoding/json/encode.go:732 +0x69 fp=0xc006e71530 sp=0xc006e714d8 pc=0x75a2e9
encoding/json.(*encodeState).reflectValue(0xc006e715c8, {0x3e86360, 0xc00a9b8fc0, 0x203001}, {0x20, 0xb2})
	/usr/lib64/go/1.17/src/encoding/json/encode.go:360 +0x78 fp=0xc006e71590 sp=0xc006e71530 pc=0x74cf78
encoding/json.(*encodeState).marshal(0x10000c0044fc620, {0x3e86360, 0xc00a9b8fc0}, {0xb8, 0x0})
	/usr/lib64/go/1.17/src/encoding/json/encode.go:332 +0xfa fp=0xc006e71608 sp=0xc006e71590 pc=0x74cb9a
encoding/json.Marshal({0x3e86360, 0xc00a9b8fc0})
	/usr/lib64/go/1.17/src/encoding/json/encode.go:161 +0x45 fp=0xc006e71668 sp=0xc006e71608 pc=0x74c205
github.com/rancher/norman/types/convert.ToObj({0x3e86360, 0xc00a9b8fc0}, {0x3afaa60, 0xc0047aa5a0})
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20220406153559-82478fb169cb/types/convert/convert.go:221 +0x2d fp=0xc006e716a0 sp=0xc006e71668 pc=0x12d36ed
github.com/rancher/rancher/pkg/controllers/managementapi/dynamicschema.(*Controller).add(0xc0006d05a0, 0xc0039152c0)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementapi/dynamicschema/dynamicschema.go:50 +0x7e fp=0xc006e719c0 sp=0xc006e716a0 pc=0x31bef7e
github.com/rancher/rancher/pkg/controllers/managementapi/dynamicschema.(*Controller).Sync(0x760a85, {0xc00a9a7320, 0x3f50060}, 0xc00069e070)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementapi/dynamicschema/dynamicschema.go:37 +0xc5 fp=0xc006e71a30 sp=0xc006e719c0 pc=0x31beca5
github.com/rancher/rancher/pkg/controllers/managementapi/dynamicschema.(*Controller).Sync-fm({0xc00a9a7320, 0x35bc820}, 0xc00069e070)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementapi/dynamicschema/dynamicschema.go:29 +0x37 fp=0xc006e71a60 sp=0xc006e71a30 pc=0x31bf4f7
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*dynamicSchemaController).AddHandler.func1({0xc00a9a7320, 0x6}, {0x3f1c1e0, 0xc0039152c0})
	/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_dynamic_schema_controller.go:155 +0x42 fp=0xc006e71a88 sp=0xc006e71a60 pc=0x15154e2
github.com/rancher/norman/controller.(*genericController).AddHandler.func1({0xc00a9a7320, 0x10}, {0x47b48c0, 0xc0039152c0})
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20220406153559-82478fb169cb/controller/generic_controller.go:62 +0x1ad fp=0xc006e71b88 sp=0xc006e71a88 pc=0x128eb4d
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0x3840, {0xc00a9a7320, 0x6f2bf00}, {0x47b48c0, 0xc0039152c0})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/sharedcontroller.go:29 +0x38 fp=0xc006e71bb8 sp=0xc006e71b88 pc=0x1288938
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000ea8d20, {0xc00a9a7320, 0x10}, {0x47b48c0, 0xc0039152c0})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/sharedhandler.go:75 +0x23f fp=0xc006e71ce0 sp=0xc006e71bb8 pc=0x128bbdf
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000d38210, {0xc00a9a7320, 0x10})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:220 +0x93 fp=0xc006e71d30 sp=0xc006e71ce0 pc=0x1287cd3
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000d38210, {0x35bd9a0, 0xc00875cc40})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:201 +0x10e fp=0xc006e71e08 sp=0xc006e71d30 pc=0x128798e
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000d38210)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:178 +0x46 fp=0xc006e71e50 sp=0xc006e71e08 pc=0x1287786
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:167
github.com/rancher/lasso/pkg/controller.(*controller).runWorker-fm()
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:166 +0x32 fp=0xc006e71e70 sp=0xc006e71e50 pc=0x128c9d2
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f5e2c50dfe8)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:155 +0x67 fp=0xc006e71eb0 sp=0xc006e71e70 pc=0xc89fe7
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x76021a6574616470, {0x47889e0, 0xc0031a94d0}, 0x1, 0xc000c1a5a0)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:156 +0xb6 fp=0xc006e71f30 sp=0xc006e71eb0 pc=0xc89e56
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x722e746573746365, 0x3b9aca00, 0x0, 0x6c, 0x656a626f3a66222c)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:133 +0x89 fp=0xc006e71f80 sp=0xc006e71f30 pc=0xc89d49
k8s.io/apimachinery/pkg/util/wait.Until(0x3a2264692f6f692e, 0x626f3a66222c7d7b, 0x2e7465737463656a)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:90 +0x25 fp=0xc006e71fb8 sp=0xc006e71f80 pc=0xc89c85
github.com/rancher/lasso/pkg/controller.(*controller).run·dwrap·2()
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:135 +0x2e fp=0xc006e71fe0 sp=0xc006e71fb8 pc=0x128724e
runtime.goexit()
	/usr/lib64/go/1.17/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc006e71fe8 sp=0xc006e71fe0 pc=0x46b3c1
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:135 +0x2c6
```

Inspecting the trace with a cursory view, it appears that the the `dynamicSchema` object being passed to `add` is being mutated concurrently. 

Looking at the trace log, it appears we have a second controller that is running around utilizing the `DynamicSchemaLister`, and is performing unsafe mutations. See: https://github.com/rancher/rancher/blob/v2.6.6/pkg/controllers/management/drivers/nodedriver/machine_driver.go#L421

We need to fix the `machine_driver.go` controller and `DeepCopy` objects retrieved from the `DynamicSchemaLister` objects before allowing mutation.

**Comment by snasovich** [comment]
Ready to test on v2.7-head.

**Comment by jameson-mcghee** [comment]
Intended Test Setup

Rancher version(s): v2.6.6 & v2.7-head
Browser type & version: Brave & Most Current
Rancher Host: EC2
Rancher Setup:
o AWS_VOLUME_SIZE: 100
o AWS_AMI: ami-066f14e43aebc7472
o AWS_SECURITY_GROUPS: sg-0e753fd5550206e55 (open-all)
o AWS_INSTANCE_TYPE: t3a.xlarge
o AWS_VPC: vpc-bfccf4d7
o AWS_SUBNET: subnet-ee8cac86
o AWS_REGION: us-east-2
Deployment Type: Docker
User Permission: N/A
Test Approach

Verify that when execute a fresh Docker installation of Rancher on a node, that no errors appear in the Rancher (Docker) logs
Verify that when the installation is complete, Rancher comes up without error
Steps to reproduce:

Spin up a new instance in AWS
Once it is up, SSH into the new instance
Run the following command to install/enable Docker: sudo apt-get update && sudo apt -y install docker.io && sudo systemctl start docker && sudo systemctl enable docker && docker --version
Run the following command to install v2.6.6 of Rancher with the Log Level set to trace: sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged -e CATTLE_BOOTSTRAP_PASSWORD=admin rancher/rancher:v2.6.6 loglevel --set trace
--- Docker Logging info reference: https://docs.ranchermanager.rancher.io/v2.5/troubleshooting/other-troubleshooting-tips/logging
Run the following command to obtain the Docker Container ID: sudo docker ps
Run the following command to observe the logs: sudo docker logs {CONTAINER ID} -f

**Comment by jameson-mcghee** [comment]
I was unable to reproduce this issue on v2.6.6 (See Logs: [Bug38854Logs266.txt](https://zube.io/files/rancher/1083a5b8084dbdc6893186552669e46a-bug38854logs266.txt))

I was also unable to reproduce this issue on v2.6-head (Commit ID: 45bbbbf) (See Logs: [Bug38854Logs27head.txt](https://zube.io/files/rancher/20b68049bc2a7542cb8ad73064d3f69c-bug38854logs27head.txt))

Due to the statement "In certain cases, it is possible to have Rancher panic…" mentioned in the PR, it was deemed acceptable that I was unable to reproduce this issue on v2.6.6. With that in mind as well as the fact that I was unable to reproduce the issue at all, I am marking this ticket as completed.
