### ISSUE TITLE
[BUG] getting a panic: runtime.boundsError

### ISSUE THREAD

**Issue by themonaminor** [rancher/rancher#39259]
I have used rancher stable version helm chart ( 2.6.7)

I have installed it on AKS ( k8s version 1.23.12)

the rancher server pods installed to the cluster but as when i logged in as admin user and tried to import another aks cluster, the cluster could not able to be import and be in pending state.

where as if we check at pods status under cattle-system

NAME                                   READY   STATUS             RESTARTS         AGE
aks-config-operator-6648647485-gppvs   0/1     CrashLoopBackOff   40 (3m2s ago)    3h19m
rancher-7fb587c986-h2v2x               0/1     Running            34 (5m13s ago)   3h32m
rancher-7fb587c986-qst5l               0/1     CrashLoopBackOff   33 (2m13s ago)   3h32m
rancher-7fb587c986-sspq7               0/1     CrashLoopBackOff   33 (31s ago)     3h32m
rancher-webhook-f8785574f-qhmtv        1/1     Running            0                3h27m

also checked the logs of aks-config-operator-6648647485-gppvs pods

got the errors as below

Doing /etc/rancher/ssl
W1010 10:59:17.541053       9 loader.go:221] Config not found: /home/aks-operator/.kube/config
time="2022-10-10T10:59:17Z" level=info msg="Starting aks.cattle.io/v1, Kind=AKSClusterConfig controller"
time="2022-10-10T10:59:17Z" level=info msg="Starting /v1, Kind=Secret controller"
time="2022-10-10T10:59:18Z" level=info msg="Checking configuration for cluster [cfpdev-aks]"
time="2022-10-10T10:59:18Z" level=info msg="Checking configuration for cluster [testaks]"
E1010 10:59:18.909794       9 runtime.go:79] Observed a panic: runtime.boundsError{x:1, y:0, signed:true, code:0x0} (runtime error: index out of range [1] with length 0)
goroutine 96 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x14703a0, 0xc000b81818})
        /go/pkg/mod/k8s.io/apimachinery@v0.24.1/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0003fd910})
        /go/pkg/mod/k8s.io/apimachinery@v0.24.1/pkg/util/runtime/runtime.go:49 +0x75
panic({0x14703a0, 0xc000b81818})

kindly help me on this

**Comment by themonaminor** [comment]
please refer below for more detailed explanation

steps i followed

1. create a aks cluster with k8s version as 1.22.11
2. create ingress-basic ns and installed ingress controller on aks cluster, version of ingress controller is 4.1.3
3. created ns as "cattle-system"
4. installed rancher version 2.6.3 using helm chart in cattle-system ns
5. logged in to the rancher server as admin user
6. on cmd checked the pods status and logs, everything is fine
7. on rancher server created azure credentials
8. imported the alreday existing aks cluster on the rancher server by clicking on import cluster and completed required steps
9. as soon as i imported the cluster and looked the pods status under cattle-system
got a new pod named as "aks-config-operator-XXXXXXX" created with crashloopbackoff status and at the same time the rancher pods which was running successfully started sowing error status


refer below the complete logs of "aks-config-operator-XXXXXXX" pod

Doing /etc/rancher/ssl
W1010 13:26:54.107590      13 loader.go:221] Config not found: /home/aks-operator/.kube/config
time="2022-10-10T13:26:54Z" level=info msg="Starting aks.cattle.io/v1, Kind=AKSClusterConfig controller"
time="2022-10-10T13:26:54Z" level=info msg="Starting /v1, Kind=Secret controller"
time="2022-10-10T13:26:54Z" level=info msg="Checking configuration for cluster [cfpdev-aks]"
E1010 13:26:55.203489      13 runtime.go:79] Observed a panic: runtime.boundsError{x:1, y:0, signed:true, code:0x0} (runtime error: index out of range [1] with length 0)
goroutine 255 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x14703a0, 0xc0005bbf38})
        /go/pkg/mod/k8s.io/apimachinery@v0.24.1/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0003ba8d0})
        /go/pkg/mod/k8s.io/apimachinery@v0.24.1/pkg/util/runtime/runtime.go:49 +0x75
panic({0x14703a0, 0xc0005bbf38})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/rancher/aks-operator/controller.BuildUpstreamClusterState({0x1737358, 0xc0009a9a00}, {0x17377b8, 0xc00014ec30}, {0x7f09926f9d70, 0xc000356620}, 0xc000262118)
        /go/src/github.com/rancher/aks-operator/controller/aks-cluster-config-handler.go:679 +0xa97
github.com/rancher/aks-operator/controller.(*Handler).checkAndUpdate(0xc00050c580, 0xc000262000)
        /go/src/github.com/rancher/aks-operator/controller/aks-cluster-config-handler.go:342 +0x925
github.com/rancher/aks-operator/controller.(*Handler).OnAksConfigChanged(0x0, {0xc00044a440, 0x3b}, 0xc00009d890)
        /go/src/github.com/rancher/aks-operator/controller/aks-cluster-config-handler.go:124 +0xb1
github.com/rancher/aks-operator/controller.(*Handler).recordError.func1({0xc0000434a0, 0xc00009d890}, 0x0)
        /go/src/github.com/rancher/aks-operator/controller/aks-cluster-config-handler.go:174 +0x42
github.com/rancher/aks-operator/pkg/generated/controllers/aks.cattle.io/v1.FromAKSClusterConfigHandlerToHandler.func1({0xc0000434a0, 0x1a}, {0x1724110, 0xc000262000})
        /go/src/github.com/rancher/aks-operator/pkg/generated/controllers/aks.cattle.io/v1/aksclusterconfig.go:105 +0x44
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0x0, {0xc0000434a0, 0x0}, {0x1724110, 0xc000262000})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc00007d0e0, {0xc0000434a0, 0x1a}, {0x1724110, 0xc000262000})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc0000e4420, {0xc0000434a0, 0x1a})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:233 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0000e4420, {0x136a280, 0xc0003ba8d0})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:214 +0x10e
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0000e4420)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:191 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:180
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f09927ecbb8)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.1/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00007ce60, {0x1713a40, 0xc00009d980}, 0x1, 0xc00050e240)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.1/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0xf0, 0x43f305)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.1/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0xc000a58f58, 0xc000a58f78, 0xc000a58f68)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.1/pkg/util/wait/wait.go:90 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:148 +0x2c6
panic: runtime error: index out of range [1] with length 0 [recovered]
        panic: runtime error: index out of range [1] with length 0

goroutine 255 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0003ba8d0})
        /go/pkg/mod/k8s.io/apimachinery@v0.24.1/pkg/util/runtime/runtime.go:56 +0xd8
panic({0x14703a0, 0xc0005bbf38})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/rancher/aks-operator/controller.BuildUpstreamClusterState({0x1737358, 0xc0009a9a00}, {0x17377b8, 0xc00014ec30}, {0x7f09926f9d70, 0xc000356620}, 0xc000262118)
        /go/src/github.com/rancher/aks-operator/controller/aks-cluster-config-handler.go:679 +0xa97
github.com/rancher/aks-operator/controller.(*Handler).checkAndUpdate(0xc00050c580, 0xc000262000)
        /go/src/github.com/rancher/aks-operator/controller/aks-cluster-config-handler.go:342 +0x925
github.com/rancher/aks-operator/controller.(*Handler).OnAksConfigChanged(0x0, {0xc00044a440, 0x3b}, 0xc00009d890)
        /go/src/github.com/rancher/aks-operator/controller/aks-cluster-config-handler.go:124 +0xb1
github.com/rancher/aks-operator/controller.(*Handler).recordError.func1({0xc0000434a0, 0xc00009d890}, 0x0)
        /go/src/github.com/rancher/aks-operator/controller/aks-cluster-config-handler.go:174 +0x42
github.com/rancher/aks-operator/pkg/generated/controllers/aks.cattle.io/v1.FromAKSClusterConfigHandlerToHandler.func1({0xc0000434a0, 0x1a}, {0x1724110, 0xc000262000})
        /go/src/github.com/rancher/aks-operator/pkg/generated/controllers/aks.cattle.io/v1/aksclusterconfig.go:105 +0x44
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0x0, {0xc0000434a0, 0x0}, {0x1724110, 0xc000262000})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc00007d0e0, {0xc0000434a0, 0x1a}, {0x1724110, 0xc000262000})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc0000e4420, {0xc0000434a0, 0x1a})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:233 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0000e4420, {0x136a280, 0xc0003ba8d0})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:214 +0x10e
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0000e4420)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:191 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:180
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f09927ecbb8)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.1/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00007ce60, {0x1713a40, 0xc00009d980}, 0x1, 0xc00050e240)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.1/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0xf0, 0x43f305)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.1/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0xc000a58f58, 0xc000a58f78, 0xc000a58f68)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.1/pkg/util/wait/wait.go:90 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:148 +0x2c6










please help me on this.

i tried so many times with variety of version combination.

like aks cluster version:-  1.22.11, 1.23.12
rancher hem chart version: 2.6.3, 2.6.5, 2.6.7

i tied various combination of above but none imported my existing aks cluster to rancher server.
let me know where i am doing wrong.

Thanks

**Comment by annablender** [comment]
## Testing template

#### Root cause
 
When a customer creates an AKS cluster in Azure portal with monitoring configured (OMS agent profile), then import it into Rancher, Rancher will panic [here](https://github.com/rancher/aks-operator/blob/dc721007245a04f953523e91e01174b79f104e1e/controller/aks-cluster-config-handler.go#L700) because in this upstream config

```
"addonProfiles": {
    "omsagent": {
      "config": {
        "logAnalyticsWorkspaceResourceID": "/subscriptions/<workspace subscription id>/resourcegroups/<workspace group>/providers/microsoft.operationalinsights/workspaces/<workspace name>"
      },
      "enabled": true
    }
  }
```

The `logAnalyticsWorkspaceResourceID` contains `resourceGroups` instead of `resourcegroups` like Rancher expects [here](https://github.com/rancher/aks-operator/blob/dc721007245a04f953523e91e01174b79f104e1e/controller/aks-cluster-config-handler.go#L82).

#### What was fixed, or what changes have occurred

I added
* Case-insensitive regexp https://github.com/rancher/aks-operator/blob/eec3c304f66a08e2d872c02f739607f988a494a2/controller/aks-cluster-config-handler.go#L82
* Checks for regexp results before pulling the workspace group/name https://github.com/rancher/aks-operator/blob/eec3c304f66a08e2d872c02f739607f988a494a2/controller/aks-cluster-config-handler.go#L700

#### Areas or cases that should be tested

Test steps
*
*
*
 
#### What areas could experience regressions ?
 
#### Are the repro steps accurate/minimal ?

**Comment by annablender** [comment]
This issue can only be reproduced via an _imported_ AKS cluster into Rancher with a _custom Log Analytics workspace_. In this case, Azure creates the `logAnalyticsWorkspaceResourceID` with `resourceGroups` which doesn't match our regex. You have to `Create New` workspace in Azure to see this bug.

**Comment by jameson-mcghee** [comment]
During testing on `v2.6.7` helm deployment I was able to reproduce this issue by following the Steps to Reproduce. However, when testing on `v2.7-head` (Commit ID: 216bb7f) helm deployment, I no longer observed the reported error in the logs and the cluster was able to be imported into Rancher without error. Therefore I am closing this ticket.

**Steps to Reproduce:**
1. Create an AKS cluster via Azure portal 
    - Ensure the cluster has _Container Monitoring_ enabled and has a new _Log Analytics Workspace_ (not the default or pre-existing)
3. Import the AKS cluster into Rancher
4. Check the "aks-config-operator-XXXXXXX" pod logs on the `local` cluster for the panic error

**`v2.6.7`:**
![image](https://user-images.githubusercontent.com/13294321/207437271-69061ca4-7fe6-43a9-be4b-c148a53837c2.png)
[v267 aks-config-operator Logs test 39259.log](https://github.com/rancher/rancher/files/10221783/v267.aks-config-operator.Logs.test.39259.log)

**`v2.7-head` (Commit ID: 216bb7f):**
![image](https://user-images.githubusercontent.com/13294321/207437344-f77db18b-adcc-4ca3-8c6c-d07502761f1f.png)
[v27head aks-config-operator Logs test 39259.log](https://github.com/rancher/rancher/files/10221787/v27head.aks-config-operator.Logs.test.39259.log)
