### ISSUE TITLE
Exception seen in logs when rolling back service that are in "upgraded" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3930]
Server version - v0.63.0-rc3

Following exception seen multiple times  in logs when validation runs relating to rolling back services  are executed:

```
2016-03-11 15:18:06,163 ERROR [ae0af0c4-1096-4684-9a31-93cd8d07635c:13526] [service:214] [service.rollback] [] [cutorService-29] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception java.lang.IllegalStateException: null
        at java.util.ArrayList$Itr.remove(ArrayList.java:844) ~[na:1.7.0_95]
        at io.cattle.platform.servicediscovery.deployment.ServiceDeploymentPlanner.getUsedServiceIndexesIds(ServiceDeploymentPlanner.java:119) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.servicediscovery.deployment.ServiceDeploymentPlanner.cleanupUnusedAndDuplicatedServiceIndexes(ServiceDeploymentPlanner.java:221) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl.activateDeploymentUnits(DeploymentManagerImpl.java:215) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl$1.doWithLock(DeploymentManagerImpl.java:130) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl$1.doWithLock(DeploymentManagerImpl.java:109) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl.activate(DeploymentManagerImpl.java:109) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl.activate(DeploymentManagerImpl.java:92) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.servicediscovery.upgrade.impl.UpgradeManagerImpl.reconcile(UpgradeManagerImpl.java:523) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.servicediscovery.upgrade.impl.UpgradeManagerImpl$1.doWithLockNoResult(UpgradeManagerImpl.java:142) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.servicediscovery.upgrade.impl.UpgradeManagerImpl.upgradeDeploymentUnits(UpgradeManagerImpl.java:126) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.servicediscovery.upgrade.impl.UpgradeManagerImpl.doInServiceUpgrade(UpgradeManagerImpl.java:103) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.servicediscovery.upgrade.impl.UpgradeManagerImpl.rollback(UpgradeManagerImpl.java:284) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.servicediscovery.process.ServiceRollback.handle(ServiceRollback.java:31) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:440) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:387) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:381) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:381) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:487) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:314) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:254) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:251) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:183) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:156) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:106) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:103) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:103) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.eventing.impl.ProcessEventListenerImpl.processExecute(ProcessEventListenerImpl.java:68) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.eventing.impl.ProcessEventListenerImpl.processExecute(ProcessEventListenerImpl.java:54) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at sun.reflect.GeneratedMethodAccessor503.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_95]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_95]
        at io.cattle.platform.eventing.annotation.MethodInvokingListener$1.doWithLockNoResult(MethodInvokingListener.java:76) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.eventing.annotation.MethodInvokingListener.onEvent(MethodInvokingListener.java:72) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) [cattle-framework-eventing-0.5.0-SNAPSHOT
```

In this case rollback itself succeeds , but the upgraded instance was not removed successfully.

```
super_client = <cattle.Client object at 0x7fc948593f90>
client = <cattle.Client object at 0x7fc942fb8fd0>
rancher_compose_container = None

    @if_compose_data_files
    def test_rancher_compose_inservice_upgrade_rollback_retainip(
            super_client, client, rancher_compose_container):
    
        # Create a service with retainIp=True for upgrade
        env_name = random_str().replace("-", "")
        random_name = random_str()
        env_name = random_name.replace("-", "")
        env = client.create_environment(name=env_name)
        env = client.wait_success(env)
        assert env.state == "active"
    
        # Create Service
        launch_config = {"imageUuid": SSH_IMAGE_UUID,
                         "labels": {"test1": "value1"}
                         }
        service_name = "test1"
        service = client.create_service(name=service_name,
                                        environmentId=env.id,
                                        launchConfig=launch_config,
                                        retainIp=True,
                                        scale=5)
    
        service = client.wait_success(service)
        assert service.state == "inactive"
        activate_svc(client, service)
        check_config_for_service(super_client, service, {"test1": "value1"}, 1)
    
        containerips_before_upgrade = {}
        for i in range(1, 6):
            container_name = env.name + "_" + service.name+"_" + str(i)
            containers = super_client.list_container(name=container_name,
                                                     removed_null=True)
            assert len(containers) == 1
            containerips_before_upgrade[container_name+"ip"] = \
                containers[0].primaryIpAddress
            containerips_before_upgrade[container_name+"id"] = \
                containers[0].externalId
        """
        # Create an environment using up
        launch_rancher_compose_from_file(
            client, INSERVICE_SUBDIR, "dc_inservice1_retainip_1.yml", env_name,
            "up -d ",
            "Creating stack", "rc_inservice1_1.yml")
        """
    
        env, service = get_env_service_by_name(client, env_name, "test1")
        assert service.state == "active"
        check_config_for_service(super_client, service, {"test1": "value1"}, 1)
    
        # Upgrade environment using up --upgrade
        launch_rancher_compose_from_file(
            client, INSERVICE_SUBDIR, "dc_inservice1_retainip_2.yml", env_name,
            "up --upgrade -d --batch-size 3 --interval 500", "Upgrading")
        service = client.reload(service)
        assert service.state == "upgraded"
        check_config_for_service(super_client, service, {"test1": "value1"}, 0)
        check_config_for_service(super_client, service, {"test1": "value2"}, 1)
    
        assert service.upgrade["inServiceStrategy"]["batchSize"] == 3
        assert service.upgrade["inServiceStrategy"]["intervalMillis"] == 500
        assert service.upgrade["inServiceStrategy"]["startFirst"] is False
    
        # Rollback upgrade
    
        launch_rancher_compose_from_file(
            client, INSERVICE_SUBDIR, "dc_inservice1_retainip_2.yml", env_name,
            "up --rollback -d", "Started")
        service = client.reload(service)
        assert service.state == "active"
        check_config_for_service(super_client, service, {"test1": "value1"}, 1)
        containers = get_service_container_list(super_client, service, 0)
        assert len(containers) == 0
    
        # Confirm Ips of the containers after rollback were retained after upgrade
        for i in range(1, 6):
            container_name = env.name + "_" + service.name+"_" + str(i)
            containers = super_client.list_container(name=container_name,
                                                     removed_null=True)
>           assert len(containers) == 1
E           assert 2 == 1
E            +  where 2 = len({'sort': None, 'pagination': {'partial': False, 'first': None, 'next': None, 'limit': 100, 'total': None, 'previous': ... 9, 'dnsSearch': [u'test679249.rancher.internal', u'test1.test679249.rancher.internal'], 'ports': None, 'user': None}]})

tests/validation/cattlevalidationtest/core/test_rancher_compose_inservice_upgrade.py:1245: AssertionError
```

**Comment by sangeethah** [comment]
Tested with latest build from master - Mar/16
Exception mentioned in the logs are  not seen in logs when validation tests relating to rolling back upgraded services was performed multiple times.
