### ISSUE TITLE
DB exception seen in logs when cleanup task is run with large number of entries in process_execution table.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3968]
Setup -> Upgrade from v0.59.1 -> v0.63.1-rc1. This set up had about 300,000 entries in process_execution table before upgrade.

After upgrade is done , all most all the entries from the process_execution table gets cleared as part of cleanup task.

When cleanup task is executed we see the following DB exception logged:

```
2016-03-15 00:10:32,854 ERROR [:] [] [] [] [ecutorService-5] [i.c.p.task.impl.TaskManagerImpl     ] Task [database.cleanup] failed org.jooq.exception.DataAccessException: SQL [delete from `process_execution` where (`process_execution`.`created` is null or `process_execution`.`created` < ?)]; Connection timed out
    at org.jooq.impl.Utils.translate(Utils.java:1287) ~[jooq-3.3.0.jar:na]
    at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:495) ~[jooq-3.3.0.jar:na]
    at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:326) ~[jooq-3.3.0.jar:na]
    at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:140) ~[jooq-3.3.0.jar:na]
    at io.cattle.platform.core.cleanup.TableCleanUp.cleanUp(TableCleanUp.java:52) ~[cattle-iaas-model-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.core.cleanup.TableCleanUpCaller.doRun(TableCleanUpCaller.java:14) ~[cattle-iaas-model-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.task.AbstractSingletonTask.run(AbstractSingletonTask.java:18) ~[cattle-framework-system-task-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.task.impl.TaskManagerImpl$1.doRun(TaskManagerImpl.java:101) ~[cattle-framework-system-task-0.5.0-SNAPSHOT.jar:na]
    at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
    at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
    at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
    at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
    at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
    at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_95]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_95]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_95]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_95]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_95]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_95]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_95]
Caused by: java.sql.BatchUpdateException: Connection timed out
    at org.mariadb.jdbc.MariaDbServerPreparedStatement.execute(MariaDbServerPreparedStatement.java:376) ~[mariadb-java-client-1.3.4.jar:na]
    at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar:1.4]
    at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar:1.4]
    at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:194) ~[jooq-3.3.0.jar:na]
    at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:376) ~[jooq-3.3.0.jar:na]
    at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:322) ~[jooq-3.3.0.jar:na]
    ... 18 common frames omitted
Caused by: java.sql.SQLNonTransientConnectionException: Connection timed out
    at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:123) ~[mariadb-java-client-1.3.4.jar:na]
    at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69) ~[mariadb-java-client-1.3.4.jar:na]
    at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeQueryEpilog(MariaDbServerPreparedStatement.java:338) ~[mariadb-java-client-1.3.4.jar:na]
    at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:293) ~[mariadb-java-client-1.3.4.jar:na]
    at org.mariadb.jdbc.MariaDbServerPreparedStatement.execute(MariaDbServerPreparedStatement.java:371) ~[mariadb-java-client-1.3.4.jar:na]
    ... 23 common frames omitted
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Connection timed out
    at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executePreparedQuery(AbstractQueryProtocol.java:591) ~[mariadb-java-client-1.3.4.jar:na]
    at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:281) ~[mariadb-java-client-1.3.4.jar:na]
    ... 24 common frames omitted
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not read resultset: Read timed out
    at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:457) ~[mariadb-java-client-1.3.4.jar:na]
    at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executePreparedQuery(AbstractQueryProtocol.java:588) ~[mariadb-java-client-1.3.4.jar:na]
    ... 25 common frames omitted
Caused by: java.net.SocketTimeoutException: Read timed out
    at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.7.0_95]
    at java.net.SocketInputStream.read(SocketInputStream.java:152) ~[na:1.7.0_95]
    at java.net.SocketInputStream.read(SocketInputStream.java:122) ~[na:1.7.0_95]
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:235) ~[na:1.7.0_95]
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:275) ~[na:1.7.0_95]
    at java.io.BufferedInputStream.read(BufferedInputStream.java:334) ~[na:1.7.0_95]
    at org.mariadb.jdbc.internal.util.buffer.ReadUtil.readFully(ReadUtil.java:76) ~[mariadb-java-client-1.3.4.jar:na]
    at org.mariadb.jdbc.internal.packet.read.RawPacket.nextPacket(RawPacket.java:112) ~[mariadb-java-client-1.3.4.jar:na]
    at org.mariadb.jdbc.internal.packet.read.ReadPacketFetcher.getReusableRawPacket(ReadPacketFetcher.java:143) ~[mariadb-java-client-1.3.4.jar:na]
    at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:412) ~[mariadb-java-client-1.3.4.jar:na]
    ... 26 common frames omitted
```

**Comment by ibuildthecloud** [comment]
This error will happen once on upgrade if there are a significant number of records.  This is because the connection times out while executing the DELETE query.  This could be improved but after this one time records are cleaned every hour.  It is extremely unlikely a user would hit this error again after that one upgrade.  I don't think we need to fix this.
