### ISSUE TITLE
test panicked seen in CI for v2 integration test

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#39710]
Seems to happen intermittently, but should never fail the step.

```
Running: build-token-generator
=== RUN   TestProjectUserTestSuite
=== RUN   TestProjectUserTestSuite/TestCreateNamespaceProjectMember
=== CONT  TestProjectUserTestSuite
    dynamic.go:25: Dynamic Client Host:localhost:8443
=== CONT  TestProjectUserTestSuite/TestCreateNamespaceProjectMember
    project_user_test.go:82: 
        	Error Trace:	project_user_test.go:82
        	Error:      	Received unexpected error:
        	            	Resource type [namespace] is not creatable
        	            	github.com/rancher/rancher/tests/framework/pkg/clientbase.(*APIOperations).DoCreate
        	            		/go/src/github.com/rancher/rancher/tests/framework/pkg/clientbase/ops.go:190
        	            	github.com/rancher/rancher/tests/framework/clients/rancher/v1.(*SteveClient).Create
        	            		/go/src/github.com/rancher/rancher/tests/framework/clients/rancher/v1/client.go:121
        	            	github.com/rancher/rancher/tests/framework/extensions/namespaces.CreateNamespace
        	            		/go/src/github.com/rancher/rancher/tests/framework/extensions/namespaces/create.go:48
        	            	github.com/rancher/rancher/tests/v2/integration/projects.(*ProjectUserTestSuite).TestCreateNamespaceProjectMember
        	            		/go/src/github.com/rancher/rancher/tests/v2/integration/projects/project_user_test.go:81
        	            	reflect.Value.call
        	            		/usr/lib64/go/1.19/src/reflect/value.go:584
        	            	reflect.Value.Call
        	            		/usr/lib64/go/1.19/src/reflect/value.go:368
        	            	github.com/stretchr/testify/suite.Run.func1
        	            		/go/pkg/mod/github.com/stretchr/testify@v1.7.1/suite/suite.go:158
        	            	testing.tRunner
        	            		/usr/lib64/go/1.19/src/testing/testing.go:1446
        	            	runtime.goexit
        	            		/usr/lib64/go/1.19/src/runtime/asm_amd64.s:1594
        	Test:       	TestProjectUserTestSuite/TestCreateNamespaceProjectMember
    suite.go:63: test panicked: runtime error: invalid memory address or nil pointer dereference
        goroutine 90 [running]:
        runtime/debug.Stack()
        	/usr/lib64/go/1.19/src/runtime/debug/stack.go:24 +0x65
        github.com/stretchr/testify/suite.failOnPanic(0xc000c10340)
        	/go/pkg/mod/github.com/stretchr/testify@v1.7.1/suite/suite.go:63 +0x3e
        panic({0x1c88c40, 0x34ddf70})
        	/usr/lib64/go/1.19/src/runtime/panic.go:884 +0x212
        github.com/rancher/rancher/tests/v2/integration/projects.(*ProjectUserTestSuite).TestCreateNamespaceProjectMember(0xc00069fa80)
        	/go/src/github.com/rancher/rancher/tests/v2/integration/projects/project_user_test.go:83 +0x1ea
        reflect.Value.call({0xc00013d800?, 0xc00015beb8?, 0x13?}, {0x1fda5a4, 0x4}, {0xc000c09e70, 0x1, 0x1?})
        	/usr/lib64/go/1.19/src/reflect/value.go:584 +0x8c5
        reflect.Value.Call({0xc00013d800?, 0xc00015beb8?, 0xc00069fa80?}, {0xc0004e3e70?, 0x7f5b74121d90?, 0xd0?})
        	/usr/lib64/go/1.19/src/reflect/value.go:368 +0xbc
        github.com/stretchr/testify/suite.Run.func1(0xc000c10340)
        	/go/pkg/mod/github.com/stretchr/testify@v1.7.1/suite/suite.go:158 +0x4b6
        testing.tRunner(0xc000c10340, 0xc000a26120)
        	/usr/lib64/go/1.19/src/testing/testing.go:1446 +0x10b
        created by testing.(*T).Run
        	/usr/lib64/go/1.19/src/testing/testing.go:1493 +0x35f
=== RUN   TestProjectUserTestSuite/TestCreateNamespaceProjectOwner
=== CONT  TestProjectUserTestSuite
    dynamic.go:25: Dynamic Client Host:localhost:8443
    dynamic.go:25: Dynamic Client Host:https://localhost:8443/k8s/clusters/local
    session.go:47: error calling cleanup function: Resource type [namespace] can not be deleted
--- FAIL: TestProjectUserTestSuite (13.36s)
    --- FAIL: TestProjectUserTestSuite/TestCreateNamespaceProjectMember (1.00s)
    --- PASS: TestProjectUserTestSuite/TestCreateNamespaceProjectOwner (11.90s)
FAIL
FAIL	github.com/rancher/rancher/tests/v2/integration/projects	13.385s
?   	github.com/rancher/rancher/tests/v2/integration/setup	[no test files]
FAIL
Stopping rancher server
./test: line 10: 16096 Terminated              run_rancher
time="2022-11-28T14:36:01Z" level=fatal msg="exit status 1"
```

Full log: https://drone-pr.rancher.io/rancher/rancher/24858/3/2

**Comment by superseb** [comment]
Thanks @igomez06
