### ISSUE TITLE
Unknown exception running process

### ISSUE THREAD

**Issue by jmreicha** [rancher/rancher#3977]
Rancher Version: `v0.63.1`

Docker Version: `1.10`

OS: `CoreOS 970.1`

Steps to Reproduce: 

After upgrading from v0.59 to v0.63 and fixing an issue upgrading via https://github.com/rancher/rancher/issues/3960, start up the rancher server container and after intializing I see the following error in the logs.

Results: 

```
2016-03-15 20:53:57,406 ERROR [:] [] [] [] [cutorService-20] [i.c.p.e.e.i.ProcessEventListenerImpl] Unknown exception running process [dynamicschema.remove:768076] on [128] org.jooq.exception.DataAccessException: SQL [insert into `process_execution` (`process_instance_id`, `uuid`, `log`, `created`) values (?, ?, ?, ?)]; Unknown column 'created' in 'field list'
	at org.jooq.impl.Utils.translate(Utils.java:1287) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:495) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:326) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:140) ~[jooq-3.3.0.jar:na]
	at io.cattle.platform.engine.manager.impl.jooq.JooqProcessRecordDao.update(JooqProcessRecordDao.java:161) ~[cattle-iaas-engine-jooq-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.manager.impl.DefaultProcessManager.persistState(DefaultProcessManager.java:122) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:172) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:106) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:103) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:103) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.eventing.impl.ProcessEventListenerImpl.processExecute(ProcessEventListenerImpl.java:68) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.eventing.impl.ProcessEventListenerImpl.processExecute(ProcessEventListenerImpl.java:54) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at sun.reflect.GeneratedMethodAccessor519.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_95]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_95]
	at io.cattle.platform.eventing.annotation.MethodInvokingListener$1.doWithLockNoResult(MethodInvokingListener.java:76) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.annotation.MethodInvokingListener.onEvent(MethodInvokingListener.java:72) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_95]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_95]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_95]
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'created' in 'field list'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125) ~[mariadb-java-client-1.3.4.jar:na]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69) ~[mariadb-java-client-1.3.4.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:261) ~[mariadb-java-client-1.3.4.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:290) ~[mariadb-java-client-1.3.4.jar:na]
	at org.mariadb.jdbc.MariaDbClientPreparedStatement.execute(MariaDbClientPreparedStatement.java:148) ~[mariadb-java-client-1.3.4.jar:na]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar:1.4]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:194) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:376) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractStoreQuery.execute(AbstractStoreQuery.java:289) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:322) ~[jooq-3.3.0.jar:na]
	... 34 common frames omitted
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Unknown column 'created' in 'field list'
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:475) ~[mariadb-java-client-1.3.4.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.result(AbstractQueryProtocol.java:396) ~[mariadb-java-client-1.3.4.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:378) ~[mariadb-java-client-1.3.4.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:334) ~[mariadb-java-client-1.3.4.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:280) ~[mariadb-java-client-1.3.4.jar:na]
	... 41 common frames omitted
```

I removed the Errors in the Rancher UI for the dynamic drivers I saw but am seeing this error in the logs.  I'm guessing it was unrelated.

**Comment by deniseschannon** [comment]
What version had you originally started with Rancher?

**Comment by jmreicha** [comment]
@deniseschannon v0.59.1 originally.

**Comment by deniseschannon** [comment]
So v0.59.1 was your first install of Rancher?

**Comment by jmreicha** [comment]
@deniseschannon Yes that's correct.  I started at v0.59.1, upgraded to v0.63.0 and then to v0.63.1 to fix the first issue.

**Comment by ibuildthecloud** [comment]
This is covered in the release notes of v0.63.1 https://github.com/rancher/rancher/releases/tag/v0.63.1.  In short run

```
TRUNCATE `process_execution`;
ALTER TABLE `process_execution` DROP `created`;
```
before upgrading to v0.63.1.  This only need to be done if upgrade to v0.63.0 failed in a specific way causing `Unknown column 'created' in 'field list'`

**Comment by deniseschannon** [comment]
@jmreicha Please let me know if you are able to correct your setup.

**Comment by jmreicha** [comment]
@deniseschannon @ibuildthecloud output of the above commands.

```
sudo docker exec -it rancher-server mysql
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 29
Server version: 5.5.47-0ubuntu0.14.04.1-log (Ubuntu)

Copyright (c) 2000, 2015, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use cattle;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> TRUNCATE `process_execution`;
Query OK, 0 rows affected (0.05 sec)

mysql> ALTER TABLE `process_execution` DROP `created`;
ERROR 1091 (42000): Can't DROP 'created'; check that column/key exists
mysql>
```

Still seeing the errors after running above commands.

**Comment by ibuildthecloud** [comment]
@jmreicha Can you run `select * from DATABASECHANGELOG order by ORDEREXECUTED desc limit 10` and share the output?  I want to see what DB migrations have been applied.

**Comment by jmreicha** [comment]
@ibuildthecloud 

```
mysql> select * from DATABASECHANGELOG order by ORDEREXECUTED desc limit 10;
+--------+--------------------------+-----------------+---------------------+---------------+----------+------------------------------------+-------------------------+----------+------+-----------+
| ID     | AUTHOR                   | FILENAME        | DATEEXECUTED        | ORDEREXECUTED | EXECTYPE | MD5SUM                             | DESCRIPTION             | COMMENTS | TAG  | LIQUIBASE |
+--------+--------------------------+-----------------+---------------------+---------------+----------+------------------------------------+-------------------------+----------+------+-----------+
| dump2  | alena (generated)        | db/core-079.xml | 2016-03-15 19:37:36 |           784 | EXECUTED | 7:6b372475b94ee0eb39d1d3ac8e5176c2 | addColumn               |          | NULL | 3.1.0     |
| dump1  | alena (generated)        | db/core-079.xml | 2016-03-15 19:37:35 |           783 | EXECUTED | 7:d82ec495666679b8653507d6d898e36d | addColumn               |          | NULL | 3.1.0     |
| dump1  | darren (generated)       | db/core-078.xml | 2016-03-15 19:37:35 |           782 | EXECUTED | 7:cc8d54d8a8766baaf2023737b1f2449f | createIndex             |          | NULL | 3.1.0     |
| dump2  | darren (generated)       | db/core-077.xml | 2016-03-15 19:37:35 |           781 | EXECUTED | 7:f318dc5a1bff455232ace27c15d8da96 | createIndex             |          | NULL | 3.1.0     |
| dump1  | darren (generated)       | db/core-077.xml | 2016-03-15 19:37:34 |           780 | EXECUTED | 7:0733e7166cf961e8f0d9f861c87609aa | createIndex             |          | NULL | 3.1.0     |
| dump9  | wizardofmath (generated) | db/core-076.xml | 2016-03-15 19:37:34 |           779 | EXECUTED | 7:f84d314457f5fb4bdd21ee845b843a16 | createIndex             |          | NULL | 3.1.0     |
| dump1  | wizardofmath (generated) | db/core-076.xml | 2016-03-15 19:37:28 |           778 | EXECUTED | 7:937333ad5099d755b6f49a2a082c4de3 | addColumn               |          | NULL | 3.1.0     |
| dump10 | wizardofmath (generated) | db/core-075.xml | 2016-03-14 18:25:26 |           777 | EXECUTED | 7:4c9c20168f48c94e0626432e80b553da | addColumn               |          | NULL | 3.1.0     |
| dump9  | wizardofmath (generated) | db/core-075.xml | 2016-03-14 18:25:26 |           776 | EXECUTED | 7:ba5774913cfcd281e505f9e38da8ab12 | addForeignKeyConstraint |          | NULL | 3.1.0     |
| dump8  | wizardofmath (generated) | db/core-075.xml | 2016-03-14 18:25:26 |           775 | EXECUTED | 7:f596429c5907e1e5caf27aa908ec8a8f | createTable             |          | NULL | 3.1.0     |
+--------+--------------------------+-----------------+---------------------+---------------+----------+------------------------------------+-------------------------+----------+------+-----------+
10 rows in set (0.00 sec)
```

**Comment by ibuildthecloud** [comment]
Well, shoot....

**Comment by ibuildthecloud** [comment]
@jmreicha We dropped a column that should have been there.... So to add it back run

```sql
ALTER TABLE `process_execution` ADD `created` DATETIME NULL DEFAULT NULL; 
ALTER TABLE `cattle`.`process_execution` ADD INDEX `idx_processs_execution_created_time` (`created`);
```

**Comment by jmreicha** [comment]
@ibuildthecloud Thanks for helping out.  Here's the output.

```
mysql> ALTER TABLE `process_execution` ADD `created` DATETIME NULL DEFAULT NULL;
Query OK, 0 rows affected (0.03 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> ALTER TABLE `cattle`.`process_execution` ADD INDEX `idx_processs_execution_created_time` (`created`);
Query OK, 0 rows affected (0.02 sec)
Records: 0  Duplicates: 0  Warnings: 0
```

Logs are looking much better now.
