### ISSUE TITLE
Agent blows up if the SSL CA is unknown

### ISSUE THREAD

**Issue by brentkearney** [rancher/rancher#3982]
Rancher Version: v0.63.1

Docker Version: 1.10.3 

OS: Ubuntu 14.04

Steps to Reproduce: Setup nginx proxy for SSL as per Rancher documentation. Use COMODO signed wildcard certificate.

Results: Agent fails to connect. If CA bundle path is passed into the container with -e CURL_CA_BUNDLE="/etc/ssl/mycert.ca-bundle", then it connects, but resolve_url.py blows up.

`docker run -d -e CURL_CA_BUNDLE="/etc/ssl/myserver.ca-bundle" -v /etc/ssl:/etc/ssl:ro`... rancher/agent:v0.10.0`

```
INFO: Running Agent Registration Process, CATTLE_URL=https://myserver.ca/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.10.3
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.10.3
INFO: docker version: Server API version: 1.22
INFO: docker version: Go version (server): go1.5.3
INFO: docker version: Git commit (server): 20f81dd
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker info: Containers: 1
INFO: docker info: Images: 1
INFO: docker info: Storage Driver: aufs
INFO: docker info: Root Dir: /data/docker/aufs
INFO: docker info: Backing Filesystem: extfs
INFO: docker info: Dirs: 15
INFO: docker info: Dirperm1 Supported: true
INFO: docker info: Execution Driver: native-0.2
INFO: docker info: Kernel Version: 3.19.0-56-generic
INFO: docker info: Operating System: Ubuntu 14.04.4 LTS
INFO: docker info: CPUs: 8
INFO: docker info: Total Memory: 11.73 GiB
INFO: docker info: Name: nigel
INFO: docker info: ID: B7MO:TEDR:B5V3:BHWQ:MO4X:TONG:ER7G:WA3R:NV5Q:EXLY:4PEC:UOBI
INFO: docker info: Http Proxy:
INFO: docker info: Https Proxy:
INFO: docker info: No Proxy:
WARNING: No swap limit support
INFO: Attempting to connect to: https://myserver.ca/v1
INFO: https://myserver.ca/v1 is accessible
Traceback (most recent call last):
  File "./resolve_url.py", line 9, in <module>
    r = requests.get(url)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information

ERROR: returned
ERROR: --- START ---
ERROR: --- END ---
ERROR: Failed to load registration env from CATTLE_URL=https://myserver.ca/v1 ENV_URL=
ERROR: Please ensure the proper value for the Host Registration URL is set


```
Perhaps a way to fix this would be to have resolve_url.py look for the same environment variable that the command line curl client does, CURL_CA_BUNDLE. Then use it to specify the optional "verify" argument in the `requests.get` call in resolve_url.py. i.e.

```
ca_path = os.environ['CURL_CA_BUNDLE']
r = requests.get(url, verify=ca_path)
```

Expected:
Successful SSL connection to the Rancher server.

**Comment by cloudnautique** [comment]
Ah, yes we need to change the doc header. For any cert that is not part of the standard Ubuntu CA bundle you need to follow the self signed cert instructions.

**Comment by deniseschannon** [comment]
@brentkearney I've updated the docs to indicate in the requirements when you should use the self signed certificates. 

http://docs.rancher.com/rancher/installing-rancher/installing-server/basic-ssl-config/

And the specific section on self signed certificates
http://docs.rancher.com/rancher/installing-rancher/installing-server/basic-ssl-config/#using-self-signed-certs-beta

**Comment by deniseschannon** [comment]
Please re-open if the self signed certificate section doesn't work for you.

**Comment by brentkearney** [comment]
Thanks Denise! 

I added -v /etc/ssl/my-CA-cert:/ca.crt for the rancher-server container, but it tries to write a file to /etc/ssl, and gets a permissions error:


```
$ docker-compose up
Recreating rancher_server_1...
Recreating rancher_proxy_1...
Attaching to rancher_server_1, rancher_proxy_1
server_1 | 160317 20:03:15 [Note] /usr/sbin/mysqld (mysqld 5.5.47-0ubuntu0.14.04.1-log) starting as process 29 ...
server_1 | Uptime: 2  Threads: 1  Questions: 2  Slow queries: 0  Opens: 34  Flush tables: 1  Open tables: 26  Queries per second avg: 1.000
server_1 | Setting up database
server_1 | CATTLE_AGENT_PACKAGE_AGENT_BINARIES_URL=/usr/share/cattle/artifacts/agent-binaries.tar.gz
server_1 | CATTLE_AGENT_PACKAGE_CADVISOR_URL=/usr/share/cattle/artifacts/cadvisor.tar.gz
server_1 | CATTLE_AGENT_PACKAGE_HOST_API_URL=/usr/share/cattle/artifacts/host-api.tar.gz
server_1 | CATTLE_AGENT_PACKAGE_NODE_AGENT_URL=/usr/share/cattle/artifacts/node-agent.tar.gz
server_1 | CATTLE_AGENT_PACKAGE_PYTHON_AGENT_URL=/usr/share/cattle/artifacts/python-agent.tar.gz
server_1 | CATTLE_AGENT_PACKAGE_RANCHER_DNS_URL=/usr/share/cattle/artifacts/rancher-dns.tar.gz
server_1 | CATTLE_AGENT_PACKAGE_RANCHER_METADATA_URL=/usr/share/cattle/artifacts/rancher-metadata.tar.gz
server_1 | CATTLE_AGENT_PACKAGE_RANCHER_NET_URL=/usr/share/cattle/artifacts/rancher-net.tar.gz
server_1 | CATTLE_CATTLE_VERSION=v0.155.1
server_1 | CATTLE_DB_CATTLE_DATABASE=mysql
server_1 | CATTLE_DB_CATTLE_MYSQL_HOST=localhost
server_1 | CATTLE_DB_CATTLE_MYSQL_NAME=cattle
server_1 | CATTLE_DB_CATTLE_MYSQL_PORT=3306
server_1 | CATTLE_DB_CATTLE_USERNAME=cattle
server_1 | CATTLE_GRAPHITE_HOST=
server_1 | CATTLE_GRAPHITE_PORT=
server_1 | CATTLE_HOME=/var/lib/cattle
server_1 | CATTLE_HOST_API_PROXY_MODE=embedded
server_1 | CATTLE_LOGBACK_OUTPUT_GELF_HOST=
server_1 | CATTLE_LOGBACK_OUTPUT_GELF_PORT=
server_1 | CATTLE_RANCHER_COMPOSE_VERSION=v0.7.2
server_1 | CATTLE_RANCHER_SERVER_IMAGE=v0.63.1
server_1 | CATTLE_USE_LOCAL_ARTIFACTS=true
server_1 | DEFAULT_CATTLE_API_UI_INDEX=//releases.rancher.com/ui/0.95.0
server_1 | DEFAULT_CATTLE_CATALOG_EXECUTE=true
server_1 | DEFAULT_CATTLE_COMPOSE_EXECUTOR_EXECUTE=true
server_1 | DEFAULT_CATTLE_MACHINE_EXECUTE=true
server_1 | DEFAULT_CATTLE_RANCHER_COMPOSE_DARWIN_URL=https://releases.rancher.com/compose/beta/v0.7.2/rancher-compose-darwin-amd64-v0.7.2.tar.gz
server_1 | DEFAULT_CATTLE_RANCHER_COMPOSE_LINUX_URL=https://releases.rancher.com/compose/beta/v0.7.2/rancher-compose-linux-amd64-v0.7.2.tar.gz
server_1 | DEFAULT_CATTLE_RANCHER_COMPOSE_WINDOWS_URL=https://releases.rancher.com/compose/beta/v0.7.2/rancher-compose-windows-386-v0.7.2.zip
server_1 | Adding ca.crt to Certs.
server_1 | Updating certificates in /etc/ssl/certs... ln: failed to create symbolic link '/etc/ssl/certs/CA_WoSign_ECC_Root.pem': Read-only file system
rancher_server_1 exited with code 0
Gracefully stopping... (press Ctrl+C again to force)
Stopping rancher_proxy_1...
Stopping rancher_server_1...
```

**Comment by brentkearney** [comment]
Cancel that -- I'm not exactly sure what happened, but I noticed that after restarting without the -v ...:/ca.crt, I got the same error. So I deleted the rancher-server image, and the several containers associated to it, and re-ran it. This time it worked as documented!

```
...
server_1 | DEFAULT_CATTLE_RANCHER_COMPOSE_LINUX_URL=https://releases.rancher.com/compose/beta/v0.7.2/rancher-compose-linux-amd64-v0.7.2.tar.gz
server_1 | DEFAULT_CATTLE_RANCHER_COMPOSE_WINDOWS_URL=https://releases.rancher.com/compose/beta/v0.7.2/rancher-compose-windows-386-v0.7.2.zip
server_1 | Adding ca.crt to Certs.
server_1 | Updating certificates in /etc/ssl/certs... 1 added, 0 removed; done.
server_1 | Running hooks in /etc/ca-certificates/update.d....
server_1 | Adding debian:ca.pem
server_1 | done.
...
server_1 | 21:13:39.490 [main] INFO  ConsoleStatus - [DONE ] [26223ms] Startup Succeeded, Listening on port 8081
server_1 | time="2016-03-17T21:13:39Z" level=info msg="Starting websocket proxy. Listening on [:8080], Proxying to cattle API at [localhost:8081], Monitoring parent pid [8]." 
server_1 | time="2016-03-17T21:13:41Z" level=info msg="Starting Rancher Catalog service" 
...
```

**Comment by brentkearney** [comment]
Cancel that cancel! The server started properly, but on another host, starting the agent had the same result as this original issue. I have copied the CA cert to /var/lib/rancher/etc/ssl/ca.crt as per the docs:

```
$ ls -la /var/lib/rancher/etc/ssl
total 16
drwxr-xr-x 2 root root 4096 Mar 17 14:22 .
drwxr-xr-x 3 root root 4096 Mar 17 15:23 ..
-r--r--r-- 1 root root 4103 Mar 17 14:22 ca.crt
```

Yet running the agent still produces:

```
.... will edit
```

**Comment by cloudnautique** [comment]
Please make sure /var/lib/rancher/state is clean.

**Comment by brentkearney** [comment]
No dice. 

I played around for a bit, always getting the same SSL error. I removed /var/lib/rancher entirely, then recreated /var/lib/rancher/etc/ssl/ca.crt, and started a new container.

```
$ sudo docker run --name="rancher-agent" --restart=always -e CATTLE_HOST_LABELS='hostname=temple' -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v0.10.0 https://rancher.mydomain.ca/v1/scripts/88F797...774DE5:1...0000:KVTGz...Uc
0035f871cc606a03383164068b3ace1eddff102ef7883427640f61b5ecbdd813

$ docker logs -f rancher-agent
Updating certificates in /etc/ssl/certs... 1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....done.

INFO: Running Agent Registration Process, CATTLE_URL=https://rancher.mydomain.ca/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.10.3
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.10.3
INFO: docker version: Server API version: 1.22
INFO: docker version: Go version (server): go1.5.3
INFO: docker version: Git commit (server): 20f81dd
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker info: Containers: 7
INFO: docker info: Images: 60
INFO: docker info: Storage Driver: aufs
INFO: docker info: Root Dir: /data/docker/aufs
INFO: docker info: Backing Filesystem: extfs
INFO: docker info: Dirs: 119
INFO: docker info: Dirperm1 Supported: true
INFO: docker info: Execution Driver: native-0.2
INFO: docker info: Kernel Version: 3.19.0-56-generic
INFO: docker info: Operating System: Ubuntu 14.04.4 LTS
INFO: docker info: CPUs: 16
INFO: docker info: Total Memory: 62.92 GiB
INFO: docker info: Name: temple
WARNING: No swap limit support
INFO: docker info: ID: J46L:HDOD:EZKM:ASGN:26KW:6SUV:QCQO:FJ7X:7FIQ:CX3K:O3F4:HRVR
INFO: docker info: Http Proxy:
INFO: docker info: Https Proxy:
INFO: docker info: No Proxy:
INFO: Attempting to connect to: https://rancher.mydomain.ca/v1
INFO: https://rancher.mydomain.ca/v1 is accessible
Traceback (most recent call last):
  File "./resolve_url.py", line 9, in <module>
    r = requests.get(url)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
ERROR: returned
ERROR: --- START ---
ERROR: --- END ---

ERROR: Failed to load registration env from CATTLE_URL=https://rancher.mydomain.ca/v1 ENV_URL=
ERROR: Please ensure the proper value for the Host Registration URL is set
```

**Comment by deniseschannon** [comment]
You cannot have "--name=rancher-agent" to the rancher/agent command. 

http://docs.rancher.com/rancher/faqs/troubleshooting/#adding-in-name-rancher-agent

**Comment by cloudnautique** [comment]
The startup process first runs an agent that sets everything up for the actual agent. When run correctly there should be a file in /var/lib/rancher/etc/agent.conf . That will setup the variables for the actual rancher-agent container.

**Comment by brentkearney** [comment]
OK, I stop and deleted the container, and started a new one without a --name parameter. It does add a /var/lib/rancher/etc/agent.conf file:

```
$ sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v0.10.0 https://rancher.mydomain.ca/v1/scripts/8...E5:100000:KwDN...puS5pUc
f5993727055fd92449e093ebdea9a5337c1bd5ac87765c3c4280475e3db7594a

$ docker logs -f f5993727055fd
Updating certificates in /etc/ssl/certs... 1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....done.

INFO: Running Agent Registration Process, CATTLE_URL=https://rancher.mydomain.ca/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.10.3
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.10.3
INFO: docker version: Server API version: 1.22
INFO: docker version: Go version (server): go1.5.3
INFO: docker version: Git commit (server): 20f81dd
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker info: Containers: 7
INFO: docker info: Images: 60
INFO: docker info: Storage Driver: aufs
INFO: docker info: Root Dir: /data/docker/aufs
INFO: docker info: Backing Filesystem: extfs
INFO: docker info: Dirs: 119
INFO: docker info: Dirperm1 Supported: true
INFO: docker info: Execution Driver: native-0.2
INFO: docker info: Kernel Version: 3.19.0-56-generic
INFO: docker info: Operating System: Ubuntu 14.04.4 LTS
INFO: docker info: CPUs: 16
INFO: docker info: Total Memory: 62.92 GiB
INFO: docker info: Name: temple
INFO: docker info: ID: J46L:HDOD:EZKM:ASGN:26KW:6SUV:QCQO:FJ7X:7FIQ:CX3K:O3F4:HRVR
INFO: docker info: Http Proxy:
INFO: docker info: Https Proxy:
INFO: docker info: No Proxy:
WARNING: No swap limit support
INFO: Attempting to connect to: https://rancher.mydomain.ca/v1
INFO: https://rancher.mydomain.ca/v1 is accessible
Traceback (most recent call last):
  File "./resolve_url.py", line 9, in <module>
    r = requests.get(url)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
ERROR: returned
ERROR: --- START ---
ERROR: --- END ---

ERROR: Failed to load registration env from CATTLE_URL=https://rancher.mydomain.ca/v1 ENV_URL=
ERROR: Please ensure the proper value for the Host Registration URL is set


$ ls -la /var/lib/rancher/etc/
total 16
drwxr-xr-x 3 root root 4096 Mar 17 15:56 .
drwxr-xr-x 3 root root 4096 Mar 17 15:55 ..
-rw-r--r-- 1 root root  112 Mar 17 16:14 agent.conf
drwxr-xr-x 2 root root 4096 Mar 17 16:07 ssl

$ cat /var/lib/rancher/etc/agent.conf 
export CURL_CA_BUNDLE=/var/lib/rancher/etc/ssl/ca.crt
export REQUESTS_CA_BUNDLE=/var/lib/rancher/etc/ssl/ca.crt
```

I'm beginning to think maybe my ca.crt is problematic. Although, it works on the server and the reverse proxy, and I can connect with my web browser with https.

**Comment by cloudnautique** [comment]
Does your cert have all the intermediaries? Certain browsers will fetch the intermediaries silently... others will not. A good way to check is with curl from the command line... without -k :)

**Comment by brentkearney** [comment]
Without the -k:

```
$ curl -Iv https://XXX.XXX.XXX.XXX --header "Host: rancher.mydomain.com"
* Rebuilt URL to: https://XXX.XXX.XXX.XXX/
* Hostname was NOT found in DNS cache
*   Trying XXX.XXX.XXX.XXX...
* Connected to XXX.XXX.XXX.XXX (XXX.XXX.XXX.XXX) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

With the -k:

```
$ curl -Ikv https://XXX.XXX.XXX.XXX --header "Host: rancher.mydomain.com"
* Rebuilt URL to: https://XXX.XXX.XXX.XXX/
* Hostname was NOT found in DNS cache
*   Trying XXX.XXX.XXX.XXX...
* Connected to XXX.XXX.XXX.XXX (XXX.XXX.XXX.XXX) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
* 	 subject: OU=Domain Control Validated; OU=PositiveSSL Wildcard; CN=*.mydomain.com
* 	 start date: 2015-03-24 00:00:00 GMT
* 	 expire date: 2016-03-23 23:59:59 GMT
* 	 issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Domain Validation Secure Server CA
* 	 SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> HEAD / HTTP/1.1
> User-Agent: curl/7.35.0
> Accept: */*
> Host: rancher.mydomain.com
> 
< HTTP/1.1 401 Unauthorized
HTTP/1.1 401 Unauthorized
* Server nginx/1.9.12 is not blacklisted
< Server: nginx/1.9.12
Server: nginx/1.9.12
< Date: Thu, 17 Mar 2016 22:35:15 GMT
Date: Thu, 17 Mar 2016 22:35:15 GMT
< Content-Type: application/json; charset=utf-8
Content-Type: application/json; charset=utf-8
< Content-Length: 158
Content-Length: 158
< Connection: keep-alive
Connection: keep-alive
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Set-Cookie: PL=rancher;Path=/
Set-Cookie: PL=rancher;Path=/
< Www-Authenticate: Basic realm="Enter API access key and secret key as username and password"
Www-Authenticate: Basic realm="Enter API access key and secret key as username and password"
< X-Api-Schemas: https://rancher.mydomain.com/v1/schemas
X-Api-Schemas: https://rancher.mydomain.com/v1/schemas
```

This certificate is expiring in a few days -- I am playing around with LetsEncrypt.org right now. Hopefully I'll have better luck with those certificates!

**Comment by brentkearney** [comment]
Note, however, if I set the CURL_CA_BUNDLE environment variable, it works:

```
$ export CURL_CA_BUNDLE=/var/lib/rancher/etc/ssl/ca.crt
$ curl -Iv https://rancher.mydomain.com --header "Host: rancher.mydomain.com"
* Rebuilt URL to: https://rancher.mydomain.com/
* Hostname was NOT found in DNS cache
*   Trying XXX.XXX.XXX.XXX...
* Connected to rancher.mydomain.com (XXX.XXX.XXX.XXX) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: /var/lib/rancher/etc/ssl/ca.crt
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
* 	 subject: OU=Domain Control Validated; OU=PositiveSSL Wildcard; CN=*.mydomain.com
* 	 start date: 2015-03-24 00:00:00 GMT
* 	 expire date: 2016-03-23 23:59:59 GMT
* 	 subjectAltName: rancher.mydomain.com matched
* 	 issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Domain Validation Secure Server CA
* 	 SSL certificate verify ok.
> HEAD / HTTP/1.1
> User-Agent: curl/7.35.0
> Accept: */*
> Host: rancher.mydomain.com
> 
< HTTP/1.1 401 Unauthorized
HTTP/1.1 401 Unauthorized
* Server nginx/1.9.12 is not blacklisted
< Server: nginx/1.9.12
Server: nginx/1.9.12
< Date: Thu, 17 Mar 2016 22:42:28 GMT
Date: Thu, 17 Mar 2016 22:42:28 GMT
< Content-Type: application/json; charset=utf-8
Content-Type: application/json; charset=utf-8
< Content-Length: 158
Content-Length: 158
< Connection: keep-alive
Connection: keep-alive
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Set-Cookie: PL=rancher;Path=/
Set-Cookie: PL=rancher;Path=/
< Www-Authenticate: Basic realm="Enter API access key and secret key as username and password"
Www-Authenticate: Basic realm="Enter API access key and secret key as username and password"
< X-Api-Schemas: https://rancher.mydomain.com/v1/schemas
X-Api-Schemas: https://rancher.mydomain.com/v1/schemas

< 
* Connection #0 to host rancher.mydomain.com left intact
```

So, if you changed `r = requests.get(url)` to `r = requests.get(url, verify=/var/lib/rancher/etc/ssl/ca.crt)` (when it exists), then it will probably work for certificates like this one. :)

**Comment by cloudnautique** [comment]
We set the requests REQUESTS_CA_BUNDLE variable which has the same effect. That way we don't need to do file checking. 

This is pretty odd. I'd want to troubleshoot inside the rancher agent container. It seems like requests isn't liking something about the CA and/or cert. 

If your comfortable hacking inside the container if you switch the -d in the command to `-it` and the http string with  `-- bash` it should drop you into a shell. Trying a simple python request through the interactive python shell might shed more light. Also try curl or openssl s_client.

**Comment by cloudnautique** [comment]
We have verified in our latest stuff that we are:
1.) moving the ca.crt to the default OS stores.
2.) setting/sourcing agent.conf which sets CURL_CA_BUNDLE and REQUESTS_CA_BUNDLE.

This works with a self signed certificate setup. 

We will close this issue for now. If you do have issues with lets encrypt, please re-open.

**Comment by nav-nith** [comment]
I am experiencing the same issue on following environment
Rancher Server:
```
- Host OS: Ubuntu 16.04
- Rancher	v1.6.17
- Cattle	v0.183.49
- User Interface	v1.6.42
- Rancher CLI	v0.6.9
- Rancher Compose	v0.12.5
```
Rancher Host:
```
- Host OS: Ubuntu 16.04
- Docker Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:57 2018
 OS/Arch:           linux/amd64
 Experimental:      false
- Docker Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```
Steps :
- Rancher Server:
1. Signed Certificate using "OpenSSL 1.0.2g  1 Mar 2016".
2. Launch rancher server with option: -v <host_path>/ssl/ca.crt:/var/lib/rancher/etc/ssl/ca.crt (I see on server logs the cert was added)
Command: 
```
docker run --name rancher-server -d --restart=unless-stopped -v <host_path>/ssl/ca.crt:/var/lib/rancher/etc/ssl/ca.crt -v <host_path>/data:/var/lib/mysql rancher/server:v1.6.17
```
3. Launch Nginx proxy configuration as specified in https://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/basic-ssl-config/#example-nginx-configuration;
Command:
```
docker run -d --name=nginx --restart=unless-stopped -p 443:443 -p 80:80 -v <host_path>/ssl:/etc/rancher/ssl -v <host_path>/nginx/nginx.conf:/etc/nginx/conf.d/default.conf --link=rancher-server nginx:1.11
```
(I see that server is accessible on https:// and functional)
5. Set "Host Registration URL: https://" 

- Rancher Host
1. Added Rancher Server ca.crt to path /var/lib/rancher/etc/ssl/ in Rancher host.
2. Launch Rancher host container.
command: 
```
docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.10 https://my.rancher.com/v1/scripts/FDDXXXXXXXXXXX6:15XXXXXXXXXXXXXXXXBMlVA
```
I see that the agent.conf is created in host path /var/lib/rancher/etc with content..
export CURL_CA_BUNDLE=/var/lib/rancher/etc/ssl/ca.crt
export REQUESTS_CA_BUNDLE=/var/lib/rancher/etc/ssl/ca.crt

But the command fails with following error:
```
Updating certificates in /etc/ssl/certs...
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
INFO: Running Agent Registration Process, CATTLE_URL=https://my.rancher.com/v1
INFO: Attempting to connect to: https://my.rancher.com/v1
INFO: https://my.rancher.com/v1 is accessible
Traceback (most recent call last):
  File "./resolve_url.py", line 9, in <module>
    r = requests.get(url)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
INFO: Configured Host Registration URL info: CATTLE_URL=https://my.rancher.com/v1 ENV_URL=
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
ERROR: returned
ERROR: --- START ---

ERROR: --- END ---
ERROR: Failed to load registration env from CATTLE_URL=https://my.rancher.com/v1 ENV_URL=
```
