### ISSUE TITLE
Proxy settings for machine driver proxy not able to communicate over https

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#3997]
Rancher Version:
v0.63.0

Docker Version:

OS: 

Steps to Reproduce: 
1. Launch squid(docker run --net host -d jpetazzo/squid-in-a-can)
2. Drop outbound for port 80,443 for Docker containers.
```
iptables -A OUTPUT -p tcp --dport 443 --src 172.17.0.0/16 -j DROP
iptables -A OUTPUT -p tcp --dport 80 --src 172.17.0.0/16 -j DROP
```

3. Launch rancher/server with http_proxy and https_proxy settings.
4. Attempt to launch an AWS machine using the machine drivers in the UI.

Results: 
```
XMLParserError: s.getElementsByTagName(...)[0] is undefined
```
in the UI.

```
2016-03-16 23:22:02,804 ERROR [:] [] [] [] [tp2091949928-71] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [io.github.ibuildthecloud.gdapi.request.ApiRequest@7b5b45db] org.apache.http.conn.HttpHostConnectException: Connect to 192.168.211.131:443 [/192.168.211.131] failed: Connection refused
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:138) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:365) ~[httpclient-4.3.1.jar:4.3.1]
```

In the docker logs. It looks like its trying to hit the proxy host on 443 and not the https.proxyPort.

Expected:

**Comment by sangeethah** [comment]
Similar issue tracked in https://github.com/rancher/rancher/issues/1783

**Comment by ibuildthecloud** [comment]
@cloudnautique I tried this and it worked for me.  First, the squid-in-a-can would not work with SSL for me so I resorted to manually configuring a squid server.  Here is how I tested this:

Dockerfile
```
FROM ubuntu:16.04
RUN apt-get update && \
    apt-get install -y squid
RUN echo http_port 3128 >> ./conf
RUN echo acl localnet src all >> ./conf
RUN echo http_access allow localnet >> ./conf
CMD ["squid3", "-N", "-X", "-f", "./conf" ]
```
```
docker build -t squid .
docker run --name squid -d squid
docker run -p 8080:8080 -d --link squid -e http_proxy=squid:3128 -e https_proxy=squid:3128 rancher/server
```

@sangeethah This issue is not the same as #1783.  With this issue we are assuming you have a VPN connection to your VPC so SSH connections will work.  With Digital Ocean you would need the same but it is less likely for one to have such a setup.

**Comment by cloudnautique** [comment]
I was able to connect following @ibuildthecloud's instructions.

**Comment by will-chan** [comment]
Closing issue.  Please reopen if problem is still occurring.
