### ISSUE TITLE
KeyCloak OIDC Integration Errors

### ISSUE THREAD

**Issue by hutger** [rancher/rancher#40245]
Hi There, 

On enabling Rancher integration with KeyCloak, Rancher pods start crashing reporting panic. 

```
Doing /etc/rancher/ssl
2023/01/23 13:45:37 [INFO] Rancher version v2.7.0 (ce9a7aea4) is starting
2023/01/23 13:45:37 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:true AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features: ClusterRegistry:}
2023/01/23 13:45:37 [INFO] Listening on /tmp/log. Sock
...
2023/01/23 13:45:52 [INFO] Rancher startup complete
2023/01/23 13:45:52 [INFO] checking configmap cattle-system/admincreated to determine if orphan bindings cleanup needs to run
2023/01/23 13:45:52 [INFO] checking configmap cattle-system/admincreated to determine if duplicate bindings cleanup needs to run
2023/01/23 13:45:52 [INFO] [CleanupOrphanBindingsDone] orphan bindings cleanup has already run, skipping
2023/01/23 13:45:52 [INFO] checking configmap cattle-system/admincreated to determine if orphan bindings cleanup needs to run
2023/01/23 13:45:52 [INFO] duplicate bindings cleanup has already run, skipping
2023/01/23 13:45:52 [INFO] Watching metadata for cluster.x-k8s.io/v1alpha3, Kind=Machine
2023/01/23 13:45:52 [INFO] Starting cluster.x-k8s.io/v1alpha3, Kind=Cluster controller
2023/01/23 13:45:52 [INFO] [clean-catalog-orphan-bindings] cleaning up orphaned catalog bindings
2023/01/23 13:45:52 [INFO] [clean-catalog-orphan-bindings] Processing 13 rolebindings
2023/01/23 13:45:52 [INFO] [clean-catalog-orphan-bindings] Deleting orphaned role global-catalog
2023/01/23 13:45:52 [WARNING] [clean-catalog-orphan-bindings] Error when deleting role global-catalog, roles.rbac.authorization.k8s.io "global-catalog" not found
2023/01/23 13:45:52 [WARNING] [CleanupOrphanCatalogBindingsDone] error during orphan binding cleanup: roles.rbac.authorization.k8s.io "global-catalog" not found
2023/01/23 13:45:52 [ERROR] failed to cleanup orphan catalog bindings
2023/01/23 13:45:52 [INFO] Watching metadata for cluster.x-k8s.io/v1alpha3, Kind=MachineDeployment
2023/01/23 13:45:52 [INFO] Starting cluster.x-k8s.io/v1alpha3, Kind=Machine controller
E0123 13:45:52.783768      34 runtime.go:79] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
goroutine 2609 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3c4d0a0?, 0xc00cef2cf0})
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00c7d2dc0?})
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/runtime/runtime.go:49 +0x75
panic({0x3c4d0a0, 0xc00cef2cf0})
	/usr/lib64/go/1.19/src/runtime/panic.go:884 +0x212
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.getSearchURL({0xc00d87ec90?, 0x0?})
	/go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_client.go:172 +0xe5
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.(*KeyCloakClient).getFromKeyCloakByID(0xc002b40216?, {0xc002684ad4, 0x24}, {0xc002684acd, 0x4}, 0xc005d701e0)
	/go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_client.go:135 +0xb9
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.(*keyCloakOIDCProvider).GetPrincipal(_, {_, _}, {{{0xc002b401c9, 0x5}, {0xc002f98510, 0x17}}, {{0xc002b40220, 0xb}, {0xc002b401e0, ...}, ...}, ...})
	/go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_provider.go:150 +0x2a5
github.com/rancher/rancher/pkg/auth/providers.GetPrincipal({_, _}, {{{0xc002b401c9, 0x5}, {0xc002f98510, 0x17}}, {{0xc002b40220, 0xb}, {0xc002b401e0, 0x6}, ...}, ...})
	/go/src/github.com/rancher/rancher/pkg/auth/providers/providers.go:164 +0x105
github.com/rancher/rancher/pkg/auth/providerrefresh.(*refresher).refreshAttributes(0xc006886b00, 0xc003232a80?)
	/go/src/github.com/rancher/rancher/pkg/auth/providerrefresh/refresher.go:281 +0xfc8
github.com/rancher/rancher/pkg/auth/providerrefresh.RefreshAttributes(0xc003232a80)
	/go/src/github.com/rancher/rancher/pkg/auth/providerrefresh/daemon.go:83 +0x99
github.com/rancher/rancher/pkg/controllers/management/auth.(*UserAttributeController).sync(0xc003c9d1a0, {0xc000ef9980?, 0x0?}, 0xc004547a90?)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/auth/user_attribute_handler.go:39 +0x5f
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*userAttributeController).AddHandler.func1({0xc0073885c0?, 0xa?}, {0x3e81240?, 0xc003232a80?})
	/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_user_attribute_controller.go:155 +0x42
github.com/rancher/norman/controller.(*genericController).AddHandler.func1({0xc0073885c0, 0xa}, {0x4811ef8?, 0xc003232a80})
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20220627222520-b74009fac3ff/controller/generic_controller.go:60 +0x18b
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc00c7d2db0?, {0xc0073885c0?, 0xc004547c00?}, {0x4811ef8?, 0xc003232a80?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc0004bf5e0, {0xc0073885c0, 0xa}, {0x4811ef8, 0xc003232a80})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc0008b8c60, {0xc0073885c0, 0xa})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:233 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0008b8c60, {0x34feaa0?, 0xc00c7d2dc0?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:214 +0x105
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0008b8c60)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:191 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc004999ea0?)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:180 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x0?)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0?, {0x4807960, 0xc00454c0f0}, 0x1, 0xc000ec6a80)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x0?, 0x0?)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x0?, 0x0?, 0x0?)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/wait/wait.go:90 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:148 +0x2a7
panic: runtime error: index out of range [1] with length 1 [recovered]
	panic: runtime error: index out of range [1] with length 1

goroutine 2609 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00c7d2dc0?})
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/runtime/runtime.go:56 +0xd7
panic({0x3c4d0a0, 0xc00cef2cf0})
	/usr/lib64/go/1.19/src/runtime/panic.go:884 +0x212
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.getSearchURL({0xc00d87ec90?, 0x0?})
	/go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_client.go:172 +0xe5
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.(*KeyCloakClient).getFromKeyCloakByID(0xc002b40216?, {0xc002684ad4, 0x24}, {0xc002684acd, 0x4}, 0xc005d701e0)
	/go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_client.go:135 +0xb9
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.(*keyCloakOIDCProvider).GetPrincipal(_, {_, _}, {{{0xc002b401c9, 0x5}, {0xc002f98510, 0x17}}, {{0xc002b40220, 0xb}, {0xc002b401e0, ...}, ...}, ...})
	/go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_provider.go:150 +0x2a5
github.com/rancher/rancher/pkg/auth/providers.GetPrincipal({_, _}, {{{0xc002b401c9, 0x5}, {0xc002f98510, 0x17}}, {{0xc002b40220, 0xb}, {0xc002b401e0, 0x6}, ...}, ...})
	/go/src/github.com/rancher/rancher/pkg/auth/providers/providers.go:164 +0x105
github.com/rancher/rancher/pkg/auth/providerrefresh.(*refresher).refreshAttributes(0xc006886b00, 0xc003232a80?)
	/go/src/github.com/rancher/rancher/pkg/auth/providerrefresh/refresher.go:281 +0xfc8
github.com/rancher/rancher/pkg/auth/providerrefresh.RefreshAttributes(0xc003232a80)
	/go/src/github.com/rancher/rancher/pkg/auth/providerrefresh/daemon.go:83 +0x99
github.com/rancher/rancher/pkg/controllers/management/auth.(*UserAttributeController).sync(0xc003c9d1a0, {0xc000ef9980?, 0x0?}, 0xc004547a90?)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/auth/user_attribute_handler.go:39 +0x5f
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*userAttributeController).AddHandler.func1({0xc0073885c0?, 0xa?}, {0x3e81240?, 0xc003232a80?})
	/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_user_attribute_controller.go:155 +0x42
github.com/rancher/norman/controller.(*genericController).AddHandler.func1({0xc0073885c0, 0xa}, {0x4811ef8?, 0xc003232a80})
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20220627222520-b74009fac3ff/controller/generic_controller.go:60 +0x18b
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc00c7d2db0?, {0xc0073885c0?, 0xc004547c00?}, {0x4811ef8?, 0xc003232a80?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc0004bf5e0, {0xc0073885c0, 0xa}, {0x4811ef8, 0xc003232a80})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc0008b8c60, {0xc0073885c0, 0xa})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:233 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0008b8c60, {0x34feaa0?, 0xc00c7d2dc0?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:214 +0x105
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0008b8c60)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:191 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc004999ea0?)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:180 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x0?)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0?, {0x4807960, 0xc00454c0f0}, 0x1, 0xc000ec6a80)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x0?, 0x0?)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x0?, 0x0?, 0x0?)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/wait/wait.go:90 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:148 +0x2a7
```

Initially, only one pod gets in crashloop and then the remaining ones does the same after several minutes.

For any user provisioned by KeyCloak and already existing after integration is disabled, it returns the error:

```
2023/01/23 13:49:53 [ERROR] Error refreshing token principals, skipping: Get "/.well-known/openid-configuration": unsupported protocol scheme ""
2023/01/23 13:49:53 [ERROR] [keycloak oidc] GetPrincipal: error creating new http client: Get "/.well-known/openid-configuration": unsupported protocol scheme ""
2023/01/23 13:49:53 [ERROR] error syncing 'user-cgwlf': handler mgmt-auth-userattributes-controller: Get "/.well-known/openid-configuration": unsupported protocol scheme "", requeuing
2023/01/23 13:49:58 [ERROR] Error refreshing token principals, skipping: Get "/.well-known/openid-configuration": unsupported protocol scheme ""
2023/01/23 13:49:58 [ERROR] [keycloak oidc] GetPrincipal: error creating new http client: Get "/.well-known/openid-configuration": unsupported protocol scheme ""
2023/01/23 13:49:58 [ERROR] error syncing 'user-cgwlf': handler mgmt-auth-userattributes-controller: Get "/.well-known/openid-configuration": unsupported protocol scheme "", requeuing
2023/01/23 13:50:08 [ERROR] Error refreshing token principals, skipping: Get "/.well-known/openid-configuration": unsupported protocol scheme ""
2023/01/23 13:50:08 [ERROR] [keycloak oidc] GetPrincipal: error creating new http client: Get "/.well-known/openid-configuration": unsupported protocol scheme ""
2023/01/23 13:50:08 [ERROR] error syncing 'user-cgwlf': handler mgmt-auth-userattributes-controller: Get "/.well-known/openid-configuration": unsupported protocol scheme "", requeuing
2023/01/23 13:50:29 [ERROR] Error refreshing token principals, skipping: Get "/.well-known/openid-configuration": unsupported protocol scheme ""
2023/01/23 13:50:29 [ERROR] [keycloak oidc] GetPrincipal: error creating new http client: Get "/.well-known/openid-configuration": unsupported protocol scheme ""
2023/01/23 13:50:29 [ERROR] error syncing 'user-cgwlf': handler mgmt-auth-userattributes-controller: Get "/.well-known/openid-configuration": unsupported protocol scheme "", requeuing
2023/01/23 13:50:59 [ERROR] Error refreshing token principals, skipping: Get "/.well-known/openid-configuration": unsupported protocol scheme ""
2023/01/23 13:50:59 [ERROR] [keycloak oidc] GetPrincipal: error creating new http client: Get "/.well-known/openid-configuration": unsupported protocol scheme ""
2023/01/23 13:50:59 [ERROR] error syncing 'user-cgwlf': handler mgmt-auth-userattributes-controller: Get "/.well-known/openid-configuration": unsupported protocol scheme "", requeuing
2023/01/23 13:51:29 [ERROR] Error refreshing token principals, skipping: Get "/.well-known/openid-configuration": unsupported protocol scheme ""
```

Any suggestion on how to the address this issue?

**Comment by bpedersen2** [comment]
Until the fix for #38683 (#38822 ) is released (should be in 2.7.1 I guess) , OIDC and keycloak>v18 (without /auth context path) will cause this.

**Comment by bpedersen2** [comment]
Correct pull request: #39310

You  could use 2.7 head  (on your own risk) as the change is merged

**Comment by hutger** [comment]
> 

Thank you. The workaround worked fine. @bpedersen2
