### ISSUE TITLE
[BUG] Panic during etcd restore

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#40259]
**Rancher Server Setup**
- Rancher version: v2.7-head

**Describe the bug**

Rancher server crashes during etcd restore
```
goroutine 22041 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00a668690?})
	/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/runtime/runtime.go:56 +0xd7
panic({0x3701560, 0x6bc9e20})
	/usr/lib64/go/1.19/src/runtime/panic.go:884 +0x212
github.com/rancher/rancher/pkg/provisioningv2/rke2/planner.(*Planner).startOrRestartEtcdSnapshotRestore(_, {0xc005aae3c0, {0xc01213f0e0, 0x3, 0x3}, 0x1, 0x4, 0x0, 0x0, {0x0, ...}, ...}, ...)
	/go/src/github.com/rancher/rancher/pkg/provisioningv2/rke2/planner/etcdrestore.go:32 +0x97
github.com/rancher/rancher/pkg/provisioningv2/rke2/planner.(*Planner).restoreEtcdSnapshot(_, _, {0xc005aae3c0, {0xc01213f0e0, 0x3, 0x3}, 0x1, 0x4, 0x0, 0x0, ...}, ...)
	/go/src/github.com/rancher/rancher/pkg/provisioningv2/rke2/planner/etcdrestore.go:300 +0x105
github.com/rancher/rancher/pkg/provisioningv2/rke2/planner.(*Planner).Process(_, _, {0xc005aae3c0, {0xc01213f0e0, 0x3, 0x3}, 0x1, 0x4, 0x0, 0x0, ...})
	/go/src/github.com/rancher/rancher/pkg/provisioningv2/rke2/planner/planner.go:271 +0x4d9
github.com/rancher/rancher/pkg/controllers/provisioningv2/rke2/planner.(*handler).OnChange(_, _, {0xc005aae3c0, {0xc01213f0e0, 0x3, 0x3}, 0x1, 0x3, 0x0, 0x0, ...})
	/go/src/github.com/rancher/rancher/pkg/controllers/provisioningv2/rke2/planner/controller.go:70 +0x405
github.com/rancher/rancher/pkg/generated/controllers/rke.cattle.io/v1.(*rKEControlPlaneStatusHandler).sync(0xc00949d920, {0xc004775b70?, 0x40ba74?}, 0xc0050b9000)
	/go/src/github.com/rancher/rancher/pkg/generated/controllers/rke.cattle.io/v1/rkecontrolplane.go:307 +0x15c
```

**To Reproduce**

Try to perform an etcd restore

**Result**

Rancher crashes

**Expected Result**

No crash

**Screenshots**

**Additional context**

**Comment by markusewalker** [comment]
As part of testing for https://github.com/rancher/rancher/issues/40005#issuecomment-1419690816, validated that this behavior does not occur. This has been tracked in our internal test plan for K8s 1.25, therefore, closing this issue.
