### ISSUE TITLE
[BUG] "02 Start the server" doesn't work

### ISSUE THREAD

**Issue by idc77** [rancher/rancher#40505]
**Rancher Server Setup**
- Rancher version: 2.7
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:
almalinux 9.1
fresh system
bare metal
podman, also docker ce 23

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

Custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

root

**Describe the bug**

the container fails to start

**To Reproduce**

```
setenforce 0
// add http https to firewall, reload firewall (done via cockpit webui)
docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher
```

**Result**

**Expected Result**

A running and accessible rancher node via :80 or :443

**Screenshots**

**Additional context**

docker logs
```
INFO: Running k3s server --cluster-init --cluster-reset

ERROR:

time="2023-02-11T19:01:54Z" level=warning msg="remove /var/lib/rancher/k3s/agent/etc/k3s-api-server-agent-load-balancer.json: no such file or directory"

time="2023-02-11T19:01:54Z" level=info msg="Starting k3s v1.24.4+k3s1 (c3f830e9)"

time="2023-02-11T19:01:54Z" level=info msg="Managed etcd cluster bootstrap already complete and initialized"

time="2023-02-11T19:01:54Z" level=info msg="Starting temporary etcd to reconcile with datastore"

{"level":"info","ts":"2023-02-11T19:01:54.782Z","caller":"embed/etcd.go:131","msg":"configuring peer listeners","listen-peer-urls":["http://127.0.0.1:2400"]}

{"level":"info","ts":"2023-02-11T19:01:54.782Z","caller":"embed/etcd.go:139","msg":"configuring client listeners","listen-client-urls":["http://127.0.0.1:2399"]}

{"level":"info","ts":"2023-02-11T19:01:54.782Z","caller":"embed/etcd.go:308","msg":"starting an etcd server","etcd-version":"3.5.3","git-sha":"Not provided (use ./build instead of go build)","go-version":"go1.18.1","go-os":"linux","go-arch":"amd64","max-cpu-set":8,"max-cpu-available":8,"member-initialized":true,"name":"9cdd045aaa4a-6ceb887a","data-dir":"/var/lib/rancher/k3s/server/db/etcd-tmp","wal-dir":"","wal-dir-dedicated":"","member-dir":"/var/lib/rancher/k3s/server/db/etcd-tmp/member","force-new-cluster":true,"heartbeat-interval":"500ms","election-timeout":"5s","initial-election-tick-advance":true,"snapshot-count":10000,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["http://127.0.0.1:2400"],"listen-peer-urls":["http://127.0.0.1:2400"],"advertise-client-urls":["http://127.0.0.1:2399"],"listen-client-urls":["http://127.0.0.1:2399"],"listen-metrics-urls":[],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"","initial-cluster-state":"new","initial-cluster-token":"","quota-size-bytes":2147483648,"pre-vote":true,"initial-corrupt-check":true,"corrupt-check-time-interval":"0s","auto-compaction-mode":"","auto-compaction-retention":"0s","auto-compaction-interval":"0s","discovery-url":"","discovery-proxy":"","downgrade-check-interval":"5s"}

{"level":"info","ts":"2023-02-11T19:01:54.783Z","caller":"etcdserver/backend.go:81","msg":"opened backend db","path":"/var/lib/rancher/k3s/server/db/etcd-tmp/member/snap/db","took":"839.774µs"}

{"level":"info","ts":"2023-02-11T19:01:54.785Z","caller":"etcdserver/server.go:529","msg":"No snapshot found. Recovering WAL from scratch!"}

{"level":"info","ts":"2023-02-11T19:01:54.796Z","caller":"etcdserver/raft.go:556","msg":"forcing restart member","cluster-id":"b6c7ec2c9e50402b","local-member-id":"6d7c3a166a7ff3dc","commit-index":795}

{"level":"info","ts":"2023-02-11T19:01:54.796Z","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"6d7c3a166a7ff3dc switched to configuration voters=()"}

{"level":"info","ts":"2023-02-11T19:01:54.796Z","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"6d7c3a166a7ff3dc became follower at term 7"}

{"level":"info","ts":"2023-02-11T19:01:54.796Z","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"newRaft 6d7c3a166a7ff3dc [peers: [], term: 7, commit: 795, applied: 0, lastindex: 795, lastterm: 7]"}

{"level":"warn","ts":"2023-02-11T19:01:54.871Z","caller":"auth/store.go:1220","msg":"simple token is not cryptographically signed"}

{"level":"info","ts":"2023-02-11T19:01:54.883Z","caller":"mvcc/kvstore.go:415","msg":"kvstore restored","current-rev":758}

{"level":"info","ts":"2023-02-11T19:01:54.896Z","caller":"etcdserver/quota.go:94","msg":"enabled backend quota with default value","quota-name":"v3-applier","quota-size-bytes":2147483648,"quota-size":"2.1 GB"}

{"level":"info","ts":"2023-02-11T19:01:54.913Z","caller":"etcdserver/corrupt.go:46","msg":"starting initial corruption check","local-member-id":"6d7c3a166a7ff3dc","timeout":"15s"}

{"level":"info","ts":"2023-02-11T19:01:54.913Z","caller":"etcdserver/corrupt.go:116","msg":"initial corruption checking passed; no corruption","local-member-id":"6d7c3a166a7ff3dc"}

{"level":"info","ts":"2023-02-11T19:01:54.913Z","caller":"etcdserver/server.go:851","msg":"starting etcd server","local-member-id":"6d7c3a166a7ff3dc","local-server-version":"3.5.3","cluster-version":"to_be_decided"}

{"level":"info","ts":"2023-02-11T19:01:54.913Z","caller":"etcdserver/server.go:752","msg":"starting initial election tick advance","election-ticks":10}

{"level":"info","ts":"2023-02-11T19:01:54.914Z","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"6d7c3a166a7ff3dc switched to configuration voters=(7889244515196728284)"}

{"level":"info","ts":"2023-02-11T19:01:54.914Z","caller":"membership/cluster.go:421","msg":"added member","cluster-id":"b6c7ec2c9e50402b","local-member-id":"6d7c3a166a7ff3dc","added-peer-id":"6d7c3a166a7ff3dc","added-peer-peer-urls":["https://10.88.0.2:2380"]}

{"level":"info","ts":"2023-02-11T19:01:54.914Z","caller":"membership/cluster.go:584","msg":"set initial cluster version","cluster-id":"b6c7ec2c9e50402b","local-member-id":"6d7c3a166a7ff3dc","cluster-version":"3.5"}

{"level":"info","ts":"2023-02-11T19:01:54.914Z","caller":"api/capability.go:75","msg":"enabled capabilities for version","cluster-version":"3.5"}

{"level":"info","ts":"2023-02-11T19:01:54.915Z","caller":"embed/etcd.go:277","msg":"now serving peer/client/metrics","local-member-id":"6d7c3a166a7ff3dc","initial-advertise-peer-urls":["http://127.0.0.1:2400"],"listen-peer-urls":["http://127.0.0.1:2400"],"advertise-client-urls":["http://127.0.0.1:2399"],"listen-client-urls":["http://127.0.0.1:2399"],"listen-metrics-urls":[]}

{"level":"info","ts":"2023-02-11T19:01:54.915Z","caller":"embed/etcd.go:581","msg":"serving peer traffic","address":"127.0.0.1:2400"}

{"level":"info","ts":"2023-02-11T19:01:54.915Z","caller":"embed/etcd.go:553","msg":"cmux::serve","address":"127.0.0.1:2400"}

{"level":"info","ts":"2023-02-11T19:02:03.797Z","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"6d7c3a166a7ff3dc is starting a new election at term 7"}

{"level":"info","ts":"2023-02-11T19:02:03.797Z","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"6d7c3a166a7ff3dc became pre-candidate at term 7"}

{"level":"info","ts":"2023-02-11T19:02:03.797Z","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"6d7c3a166a7ff3dc received MsgPreVoteResp from 6d7c3a166a7ff3dc at term 7"}

{"level":"info","ts":"2023-02-11T19:02:03.797Z","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"6d7c3a166a7ff3dc became candidate at term 8"}

{"level":"info","ts":"2023-02-11T19:02:03.797Z","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"6d7c3a166a7ff3dc received MsgVoteResp from 6d7c3a166a7ff3dc at term 8"}

{"level":"info","ts":"2023-02-11T19:02:03.797Z","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"6d7c3a166a7ff3dc became leader at term 8"}

{"level":"info","ts":"2023-02-11T19:02:03.797Z","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"raft.node: 6d7c3a166a7ff3dc elected leader 6d7c3a166a7ff3dc at term 8"}

{"level":"info","ts":"2023-02-11T19:02:03.908Z","caller":"etcdserver/server.go:2044","msg":"published local member to cluster through raft","local-member-id":"6d7c3a166a7ff3dc","local-member-attributes":"{Name:9cdd045aaa4a-6ceb887a ClientURLs:[http://127.0.0.1:2399]}","request-path":"/0/members/6d7c3a166a7ff3dc/attributes","cluster-id":"b6c7ec2c9e50402b","publish-timeout":"15s"}

{"level":"info","ts":"2023-02-11T19:02:03.908Z","caller":"embed/serve.go:98","msg":"ready to serve client requests"}

{"level":"info","ts":"2023-02-11T19:02:03.909Z","caller":"embed/serve.go:140","msg":"serving client traffic insecurely; this is strongly discouraged!","address":"127.0.0.1:2399"}

time="2023-02-11T19:02:03Z" level=info msg="Defragmenting etcd database"

{"level":"info","ts":"2023-02-11T19:02:03.910Z","caller":"v3rpc/maintenance.go:89","msg":"starting defragment"}

{"level":"info","ts":"2023-02-11T19:02:03.975Z","caller":"backend/backend.go:497","msg":"defragmenting","path":"/var/lib/rancher/k3s/server/db/etcd-tmp/member/snap/db","current-db-size-bytes":2396160,"current-db-size":"2.4 MB","current-db-size-in-use-bytes":2392064,"current-db-size-in-use":"2.4 MB"}

{"level":"info","ts":"2023-02-11T19:02:04.050Z","caller":"backend/backend.go:549","msg":"finished defragmenting directory","path":"/var/lib/rancher/k3s/server/db/etcd-tmp/member/snap/db","current-db-size-bytes-diff":0,"current-db-size-bytes":2396160,"current-db-size":"2.4 MB","current-db-size-in-use-bytes-diff":-4096,"current-db-size-in-use-bytes":2387968,"current-db-size-in-use":"2.4 MB","took":"139.901625ms"}

{"level":"info","ts":"2023-02-11T19:02:04.050Z","caller":"v3rpc/maintenance.go:95","msg":"finished defragment"}

time="2023-02-11T19:02:04Z" level=info msg="etcd temporary data store connection OK"

time="2023-02-11T19:02:04Z" level=info msg="Reconciling bootstrap data between datastore and disk"

time="2023-02-11T19:02:04Z" level=info msg="Cluster reset: backing up certificates directory to /var/lib/rancher/k3s/server/tls-1676142124"

time="2023-02-11T19:02:04Z" level=warning msg="Updating bootstrap data on disk from datastore"

time="2023-02-11T19:02:04Z" level=info msg="stopping etcd"

{"level":"info","ts":"2023-02-11T19:02:04.140Z","caller":"embed/etcd.go:368","msg":"closing etcd server","name":"9cdd045aaa4a-6ceb887a","data-dir":"/var/lib/rancher/k3s/server/db/etcd-tmp","advertise-peer-urls":["http://127.0.0.1:2400"],"advertise-client-urls":["http://127.0.0.1:2399"]}

{"level":"info","ts":"2023-02-11T19:02:04.141Z","caller":"etcdserver/server.go:1453","msg":"skipped leadership transfer for single voting member cluster","local-member-id":"6d7c3a166a7ff3dc","current-leader-member-id":"6d7c3a166a7ff3dc"}

time="2023-02-11T19:02:04Z" level=fatal msg="starting kubernetes: preparing server: start managed database: Managed etcd cluster membership was previously reset, please remove the cluster-reset flag and start k3s normally. If you need to perform another cluster reset, you must first manually delete the /var/lib/rancher/k3s/server/db/reset-flag file"

INFO: Running k3s server --cluster-init --cluster-reset

2023/02/11 19:02:25 [INFO] Rancher version v2.7.1 (bb1c35fc4) is starting

2023/02/11 19:02:25 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features: ClusterRegistry:}

2023/02/11 19:02:25 [INFO] Listening on /tmp/log.sock

2023/02/11 19:02:25 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:02:27 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:02:29 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:02:31 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:02:33 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:02:35 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:02:40 [FATAL] k3s exited with: exit status 2

INFO: Running k3s server --cluster-init --cluster-reset

2023/02/11 19:03:02 [INFO] Rancher version v2.7.1 (bb1c35fc4) is starting

2023/02/11 19:03:02 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features: ClusterRegistry:}

2023/02/11 19:03:02 [INFO] Listening on /tmp/log.sock

2023/02/11 19:03:02 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:03:05 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:03:07 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:03:09 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:03:11 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:03:13 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:03:15 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:03:17 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:03:19 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:03:21 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:03:26 [FATAL] k3s exited with: exit status 2

INFO: Running k3s server --cluster-init --cluster-reset

2023/02/11 19:03:49 [INFO] Rancher version v2.7.1 (bb1c35fc4) is starting

2023/02/11 19:03:49 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features: ClusterRegistry:}

2023/02/11 19:03:49 [INFO] Listening on /tmp/log.sock

2023/02/11 19:03:49 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:03:51 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:03:53 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:03:55 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:03:57 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:03:59 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:04:01 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:04:04 [INFO] Running in single server mode, will not peer connections

2023/02/11 19:04:05 [INFO] Applying CRD features.management.cattle.io

2023/02/11 19:04:05 [INFO] Applying CRD navlinks.ui.cattle.io

2023/02/11 19:04:05 [INFO] Applying CRD clusters.management.cattle.io

2023/02/11 19:04:05 [INFO] Applying CRD apiservices.management.cattle.io

2023/02/11 19:04:05 [INFO] Applying CRD clusterregistrationtokens.management.cattle.io

2023/02/11 19:04:05 [INFO] Applying CRD settings.management.cattle.io

2023/02/11 19:04:05 [INFO] Applying CRD preferences.management.cattle.io

2023/02/11 19:04:05 [INFO] Applying CRD features.management.cattle.io

2023/02/11 19:04:05 [INFO] Applying CRD clusterrepos.catalog.cattle.io

2023/02/11 19:04:05 [INFO] Applying CRD operations.catalog.cattle.io

2023/02/11 19:04:05 [INFO] Applying CRD apps.catalog.cattle.io

2023/02/11 19:04:05 [INFO] Applying CRD fleetworkspaces.management.cattle.io

2023/02/11 19:04:05 [INFO] Applying CRD managedcharts.management.cattle.io

2023/02/11 19:04:06 [INFO] Applying CRD clusters.provisioning.cattle.io

2023/02/11 19:04:06 [INFO] Applying CRD clusters.provisioning.cattle.io

2023/02/11 19:04:06 [INFO] Applying CRD rkeclusters.rke.cattle.io

2023/02/11 19:04:06 [INFO] Applying CRD rkecontrolplanes.rke.cattle.io

2023/02/11 19:04:06 [INFO] Applying CRD rkebootstraps.rke.cattle.io

2023/02/11 19:04:06 [INFO] Applying CRD rkebootstraptemplates.rke.cattle.io

2023/02/11 19:04:06 [INFO] Applying CRD rkecontrolplanes.rke.cattle.io

2023/02/11 19:04:06 [INFO] Applying CRD custommachines.rke.cattle.io

2023/02/11 19:04:06 [INFO] Applying CRD etcdsnapshots.rke.cattle.io

2023/02/11 19:04:06 [FATAL] k3s exited with: exit status 2

INFO: Running k3s server --cluster-init --cluster-reset

2023/02/11 19:04:29 [INFO] Rancher version v2.7.1 (bb1c35fc4) is starting

2023/02/11 19:04:29 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features: ClusterRegistry:}

2023/02/11 19:04:29 [INFO] Listening on /tmp/log.sock

2023/02/11 19:04:29 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:04:31 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:04:33 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:04:35 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:04:37 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:04:39 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:04:41 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:04:43 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:04:45 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:04:49 [FATAL] k3s exited with: exit status 2

INFO: Running k3s server --cluster-init --cluster-reset

2023/02/11 19:05:14 [INFO] Rancher version v2.7.1 (bb1c35fc4) is starting

2023/02/11 19:05:14 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features: ClusterRegistry:}

2023/02/11 19:05:14 [INFO] Listening on /tmp/log.sock

2023/02/11 19:05:14 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:05:16 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:05:18 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:05:20 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:05:22 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:05:24 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:05:26 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:05:28 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused

2023/02/11 19:05:33 [FATAL] k3s exited with: exit status 2

INFO: Running k3s server --cluster-init --cluster-reset
```

**Comment by superseb** [comment]
Please supply the output of `docker info` and `docker cp <rancher-container>:/var/lib/rancher/k3s.log . && cat k3s.log`, I will see if I can include this output by default in the log.

**Comment by idc77** [comment]
```
# docker info
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
host:
  arch: amd64
  buildahVersion: 1.27.3
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.4-1.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: 24a4eb8c5272ea46c28889a24fc0a9ba1f4b0c74'
  cpuUtilization:
    idlePercent: 98.71
    systemPercent: 0.16
    userPercent: 1.12
  cpus: 8
  distribution:
    distribution: '"almalinux"'
    version: "9.1"
  eventLogger: journald
  hostname: data.local
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.14.0-162.12.1.el9_1.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 32057274368
  memTotal: 33467703296
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.5-1.el9.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.el9_0.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 16800280576
  swapTotal: 16800280576
  uptime: 0h 11m 56.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
```

**Comment by idc77** [comment]
<blockquote>
You can't comment at this time — your comment is too long (maximum is 65536 characters). 
</blockquote>
https://pastebin.com/QJepfKDF

**Comment by niusmallnan** [comment]
I am not an almalinux expert. However, I can see these panic logs from that `pastebin` url.
```
panic: F0217 14:09:36.199831      74 network_policy_controller.go:380] failed to run iptables command to create KUBE-ROUTER-INPUT chain due to running [/usr/bin/iptables -t filter -S KUBE-ROUTER-INPUT 1 --wait]: exit status 3: iptables v1.8.6 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
 
 
goroutine 10874 [running]:
k8s.io/klog/v2.(*loggingT).output(0x7eb5ea0, 0x3, 0x0, 0xc004a8c690, 0x1, {0x6469804?, 0x2?}, 0xc0000ae800?, 0x0)
	/go/pkg/mod/github.com/k3s-io/klog/v2@v2.60.1-k3s1/klog.go:820 +0x694
k8s.io/klog/v2.(*loggingT).printfDepth(0x7eb5ea0, 0x11?, 0x0, {0x0, 0x0}, 0x48cf9b?, {0x4cd8c99, 0x3b}, {0xc0059100c0, 0x2, ...})
	/go/pkg/mod/github.com/k3s-io/klog/v2@v2.60.1-k3s1/klog.go:630 +0x1f2
k8s.io/klog/v2.(*loggingT).printf(...)
	/go/pkg/mod/github.com/k3s-io/klog/v2@v2.60.1-k3s1/klog.go:612
k8s.io/klog/v2.Fatalf(...)
	/go/pkg/mod/github.com/k3s-io/klog/v2@v2.60.1-k3s1/klog.go:1496
github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).ensureTopLevelChains(0xc00602ec00)
	/go/pkg/mod/github.com/k3s-io/kube-router@v1.5.1-0.20220630214451-a43bcd8511d2/pkg/controllers/netpol/network_policy_controller.go:380 +0x150c
github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).Run(0xc00602ec00, 0xc00f497da0, 0xc000e50000, 0xc009730860)
	/go/pkg/mod/github.com/k3s-io/kube-router@v1.5.1-0.20220630214451-a43bcd8511d2/pkg/controllers/netpol/network_policy_controller.go:166 +0x16f
created by github.com/k3s-io/k3s/pkg/agent/netpol.Run
	/go/src/github.com/k3s-io/k3s/pkg/agent/netpol/netpol.go:135 +0xacc
```
This is not in the Rancher Support Matrix: https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-1/


I recommend this `Helm CLI Quick Start`. You may need to adjust k3s parameters to avoid panic.
https://ranchermanager.docs.rancher.com/getting-started/quick-start-guides/deploy-rancher-manager/helm-cli

**Comment by idc77** [comment]
Aparently nftables replace iptables. Not sure if only in Alma9 or if it's a RHEL thing in general or a Linux thing in general.
Gentoo wiki says https://wiki.gentoo.org/wiki/Nftables
I'm guessing before long k3s or rancher will have to adapt.
I installed Ubuntu 22.04 now and will close this issue.
