### ISSUE TITLE
[BUG] unable to create vsphere cloud provider rke2 custom cluster

### ISSUE THREAD

**Issue by ebenezar-mccoy** [rancher/rancher#40623]
**Rancher Server Setup**
- Rancher version: 2.7.1
- Installation option: Helm Chart

**Information about the Cluster**
- Kubernetes version: 1.24.9+rke2r2 | 1.23.15
- Cluster Type: downstream, custom-created using Registration Command.

**User Information**
- What is the role of the user logged in? Cluster Owner

**Describe the bug**
Unable to create new cluster with vsphere cloud provider enabled.

**To Reproduce**
Create a new rke2 Custom Cluster under 2.7.1 rancher

**Result**
Stuck on Reconciling
Error
Waiting for cluster agent to connect 

Detailed error from rancher-vsphere-cpi-cloud-controller-manager error:

```
E0220 21:53:10.513369       1 config_yaml.go:136] vsphere.conf does not have the VirtualCenter IP address specified
E0220 21:53:10.513392       1 config_yaml.go:214] validateConfig failed: vsphere.conf does not have the VirtualCenter IP address specified
W0220 21:53:10.513405       1 config.go:69] ReadCPIConfigYAML failed: vsphere.conf does not have the VirtualCenter IP address specified
E0220 21:53:10.513434       1 config.go:73] ReadConfigINI failed: 3:1: expected section header
F0220 21:53:10.513451       1 main.go:249] Cloud provider could not be initialized: could not init cloud provider "vsphere": 3:1: expected section header
goroutine 1 [running]:

```

**Screenshots**
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/20969095/220204012-05c5cd43-4f06-4200-aabe-950f9e2fa553.png">
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/20969095/220204045-4dd00d0e-9848-41fe-9ad2-f46574166715.png">

**Comment by ebenezar-mccoy** [comment]
I think I have fixed my issue by adding bellow configuration in Additional Manifest section 

`apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rancher-vsphere-cpi
  namespace: kube-system
spec:
  valuesContent: |-
    vCenter:
      host: "1.1.1.1"
      port: 443
      insecureFlag: true
      datacenters: "DC"
      username: "user"
      password: "password"
      credentialsSecret:
        generate: true
    cloudControllerManager:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rancher-vsphere-csi
  namespace: kube-system
spec:
  valuesContent: |-
    vCenter:
      host: "1.1.1.1"
      port: 443
      insecureFlag: true
      datacenters: "DC"
      username: "user"
      password: "password"
      configSecret:
        generate: true
    csiController:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      csiResizer:
        enabled: false
    storageClass:
      enabled: true
      name: k8sstorage
      isDefault: true`

**Comment by jordanorc** [comment]
I had the same problem and the @ebenezar-mccoy fix worked in my case. Thanks @ebenezar-mccoy

**Comment by tdportW** [comment]
I also experience this issue when upgrading a downstream RKE2 cluster from 1.26.14 to 1.27.12. Seems like when you edit config in the Rancher GUI some other values are not retained either.
