### ISSUE TITLE
DigitalOcean "Uncaught exception java.lang.IllegalStateException: COMPLETING"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#407]
Server - Version V0.14.2

Following exception seen when DigitalOcean machines were created and deleted:
Machine creation itself succeeds and no issues seen , but we see lot of these errors being reported in server logs.

2015-04-02 16:06:14,071 ERROR [:] [] [] [] [cutorService-54] [o.a.c.m.context.NoExceptionRunnable ] Uncaught exception java.lang.IllegalStateException: COMPLETING
        at org.eclipse.jetty.server.AsyncContinuation.complete(AsyncContinuation.java:579) ~[na:na]
        at io.cattle.platform.api.pubsub.subscribe.AsyncOutputStreamMessageWriter.close(AsyncOutputStreamMessageWriter.java:19) ~[cattle-framework-api-pub-sub-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.api.pubsub.subscribe.NonBlockingSubscriptionHandler.unsubscribe(NonBlockingSubscriptionHandler.java:210) ~[cattle-framework-api-pub-sub-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.api.pubsub.subscribe.NonBlockingSubscriptionHandler$2.run(NonBlockingSubscriptionHandler.java:185) ~[cattle-framework-api-pub-sub-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.async.retry.impl.RetryTimeoutServiceImpl$1$1.doRun(RetryTimeoutServiceImpl.java:63) ~[cattle-framework-async-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.async.retry.impl.RetryTimeoutServiceImpl$1.run(RetryTimeoutServiceImpl.java:59) [cattle-framework-async-0.5.0-SNAPSHOT.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]

2015-04-02 16:06:14,070 ERROR [:] [] [] [] [cutorService-40] [o.a.c.m.context.NoExceptionRunnable ] Uncaught exception java.lang.IllegalStateException: COMPLETING
        at org.eclipse.jetty.server.AsyncContinuation.complete(AsyncContinuation.java:579) ~[na:na]
        at io.cattle.platform.api.pubsub.subscribe.AsyncOutputStreamMessageWriter.close(AsyncOutputStreamMessageWriter.java:19) ~[cattle-framework-api-pub-sub-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.api.pubsub.subscribe.NonBlockingSubscriptionHandler.unsubscribe(NonBlockingSubscriptionHandler.java:210) ~[cattle-framework-api-pub-sub-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.api.pubsub.subscribe.NonBlockingSubscriptionHandler$2.run(NonBlockingSubscriptionHandler.java:185) ~[cattle-framework-api-pub-sub-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.async.retry.impl.RetryTimeoutServiceImpl$1$1.doRun(RetryTimeoutServiceImpl.java:63) ~[cattle-framework-async-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.async.retry.impl.RetryTimeoutServiceImpl$1.run(RetryTimeoutServiceImpl.java:59) [cattle-framework-async-0.5.0-SNAPSHOT.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Thre

**Comment by will-chan** [comment]
please re-test

**Comment by sangeethah** [comment]
Tested with latest build from master.

There are no errors reported in the server logs when DigitalOcean machine is created/deleted.
