### ISSUE TITLE
[BUG] OIDC-Auth Crash Container

### ISSUE THREAD

**Issue by hmh00** [rancher/rancher#40790]
**Rancher Server Setup**
- Rancher version: v2.7.1
- Installation option (Docker install/Helm Chart):
   - Rancher Stable HelmChart

- Proxy/Cert Details:
  General Use a Proxy 
  NO_PROXY to Keycloak
  Keycloak-Version: 19.0.3

**Information about the Cluster**
- Kubernetes version: v1.22.9
- Keycloak Version: 19.0.3

**Describe the bug**
Container Restart/Crash on User Add/Login or Restore a previous User Session with Keycloak-oidc.

**To Reproduce**
### Configure Keycloak OpenID with this guide

[ Rancher Keycloak OIDC ](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-keycloak-oidc)

Add Auth Provider in Rancher with this settings

<html>
<body>

Rancher URL: | https://rancher.example.com/verify-auth
-- | --
Client ID: | rancher
Issuer: | https://keycloak.example.com/realms/cool-realm
Auth Endpoint: | https://keycloak.example.com/realms/cool-realm/protocol/openid-connect/auth

</body>
</html>

**Result**
```console
2023/03/07 10:44:19 [DEBUG] [generic oidc] getUserInfo: getting user info
2023/03/07 10:44:19 [DEBUG] [generic oidc] getUserInfo: attempting to refresh access token
2023/03/07 10:44:19 [ERROR] Error refreshing token principals, skipping: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Token is not active"}
E0307 10:44:19.605845      32 runtime.go:79] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
goroutine 2069 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3c5fde0?, 0xc00aba34a0})
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc007bec0f0?})
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/runtime/runtime.go:49 +0x75
panic({0x3c5fde0, 0xc00aba34a0})
	/usr/lib64/go/1.19/src/runtime/panic.go:884 +0x212
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.getSearchURL({0xc00c49baa0?, 0x0?})
	/go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_client.go:172 +0xe5
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.(*KeyCloakClient).getFromKeyCloakByID(0xc005651fd6?, {0xc003be1594, 0x24}, {0xc003be158d, 0x4}, 0xc005843a40)
	/go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_client.go:135 +0xb9
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.(*keyCloakOIDCProvider).GetPrincipal(_, {_, _}, {{{0xc005651f79, 0x5}, {0xc004881fc8, 0x17}}, {{0xc005651fe0, 0xb}, {0xc005651fa0, ...}, ...}, ...})
	/go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_provider.go:150 +0x2a5
github.com/rancher/rancher/pkg/auth/providers.GetPrincipal({_, _}, {{{0xc005651f79, 0x5}, {0xc004881fc8, 0x17}}, {{0xc005651fe0, 0xb}, {0xc005651fa0, 0x6}, ...}, ...})
	/go/src/github.com/rancher/rancher/pkg/auth/providers/providers.go:164 +0x105
github.com/rancher/rancher/pkg/auth/providerrefresh.(*refresher).refreshAttributes(0xc00bf7c080, 0xc0011c0c50?)
	/go/src/github.com/rancher/rancher/pkg/auth/providerrefresh/refresher.go:278 +0x10c8
github.com/rancher/rancher/pkg/auth/providerrefresh.RefreshAttributes(0xc0011c0c50)
	/go/src/github.com/rancher/rancher/pkg/auth/providerrefresh/daemon.go:83 +0x99
github.com/rancher/rancher/pkg/controllers/management/auth.(*UserAttributeController).sync(0xc00986c190, {0xc008063880?, 0x0?}, 0xc00428da90?)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/auth/user_attribute_handler.go:35 +0x4f
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*userAttributeController).AddHandler.func1({0xc00152d4e0?, 0xa?}, {0x3e94c80?, 0xc0011c0c50?})
	/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_user_attribute_controller.go:155 +0x42
github.com/rancher/norman/controller.(*genericController).AddHandler.func1({0xc00152d4e0, 0xa}, {0x4828878?, 0xc0011c0c50})
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20220627222520-b74009fac3ff/controller/generic_controller.go:60 +0x18b
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc007bec0d0?, {0xc00152d4e0?, 0xc00428dc00?}, {0x4828878?, 0xc0011c0c50?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc00097ac30, {0xc00152d4e0, 0xa}, {0x4828878, 0xc0011c0c50})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000885340, {0xc00152d4e0, 0xa})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:233 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000885340, {0x35104c0?, 0xc007bec0f0?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:214 +0x105
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000885340)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:191 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc0049a26a0?)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:180 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x0?)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0?, {0x481e2e0, 0xc002260930}, 0x1, 0xc000087d40)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x0?, 0x0?)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x0?, 0x0?, 0x0?)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/wait/wait.go:90 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:148 +0x2a7
panic: runtime error: index out of range [1] with length 1 [recovered]
	panic: runtime error: index out of range [1] with length 1
goroutine 2069 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc007bec0f0?})
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/runtime/runtime.go:56 +0xd7
panic({0x3c5fde0, 0xc00aba34a0})
	/usr/lib64/go/1.19/src/runtime/panic.go:884 +0x212
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.getSearchURL({0xc00c49baa0?, 0x0?})
	/go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_client.go:172 +0xe5
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.(*KeyCloakClient).getFromKeyCloakByID(0xc005651fd6?, {0xc003be1594, 0x24}, {0xc003be158d, 0x4}, 0xc005843a40)
	/go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_client.go:135 +0xb9
github.com/rancher/rancher/pkg/auth/providers/keycloakoidc.(*keyCloakOIDCProvider).GetPrincipal(_, {_, _}, {{{0xc005651f79, 0x5}, {0xc004881fc8, 0x17}}, {{0xc005651fe0, 0xb}, {0xc005651fa0, ...}, ...}, ...})
	/go/src/github.com/rancher/rancher/pkg/auth/providers/keycloakoidc/keycloak_provider.go:150 +0x2a5
github.com/rancher/rancher/pkg/auth/providers.GetPrincipal({_, _}, {{{0xc005651f79, 0x5}, {0xc004881fc8, 0x17}}, {{0xc005651fe0, 0xb}, {0xc005651fa0, 0x6}, ...}, ...})
	/go/src/github.com/rancher/rancher/pkg/auth/providers/providers.go:164 +0x105
github.com/rancher/rancher/pkg/auth/providerrefresh.(*refresher).refreshAttributes(0xc00bf7c080, 0xc0011c0c50?)
	/go/src/github.com/rancher/rancher/pkg/auth/providerrefresh/refresher.go:278 +0x10c8
github.com/rancher/rancher/pkg/auth/providerrefresh.RefreshAttributes(0xc0011c0c50)
	/go/src/github.com/rancher/rancher/pkg/auth/providerrefresh/daemon.go:83 +0x99
github.com/rancher/rancher/pkg/controllers/management/auth.(*UserAttributeController).sync(0xc00986c190, {0xc008063880?, 0x0?}, 0xc00428da90?)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/auth/user_attribute_handler.go:35 +0x4f
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*userAttributeController).AddHandler.func1({0xc00152d4e0?, 0xa?}, {0x3e94c80?, 0xc0011c0c50?})
	/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_user_attribute_controller.go:155 +0x42
github.com/rancher/norman/controller.(*genericController).AddHandler.func1({0xc00152d4e0, 0xa}, {0x4828878?, 0xc0011c0c50})
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20220627222520-b74009fac3ff/controller/generic_controller.go:60 +0x18b
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc007bec0d0?, {0xc00152d4e0?, 0xc00428dc00?}, {0x4828878?, 0xc0011c0c50?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc00097ac30, {0xc00152d4e0, 0xa}, {0x4828878, 0xc0011c0c50})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000885340, {0xc00152d4e0, 0xa})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:233 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000885340, {0x35104c0?, 0xc007bec0f0?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:214 +0x105
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000885340)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:191 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc0049a26a0?)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:180 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x0?
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/wait/wait.go:155 +0x3
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0?, {0x481e2e0, 0xc002260930}, 0x1, 0xc000087d40)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x0?, 0x0?)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x0?, 0x0?, 0x0?)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/wait/wait.go:90 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:148 +0x2a7
```

**Comment by bpedersen2** [comment]
This a known bug, the fix is not in 2.7.1 and will probably be released in 2.7.2,see #38683
