### ISSUE TITLE
Operator panic if registration Namespace is not found

### ISSUE THREAD

**Issue by eumel8** [rancher/rancher#41214]
**Describe the bug**

If a registration namespace doesn't exists the Operator panic but listed the project installation as present:

```
% kubectl get ns cattle-project-p-82r22
Error from server (NotFound): namespaces "cattle-project-p-82r22" not found
```

```
% kubectl -n cattle-project-p-82r22 get projecthelmcharts.helm.cattle.io 
NAME                 STATUS                      SYSTEM NAMESPACE   RELEASE NAMESPACE   RELEASE NAME   TARGET NAMESPACES
project-monitoring   NoTargetProjectNamespaces                                                         <no value>
```

**To Reproduce**

delete project registration namespace

**Result**

```
time="2023-03-01T13:01:53Z" level=info msg="Registering embedded Helm Locker..."
time="2023-03-01T13:01:53Z" level=info msg="Registering embedded Helm Controller..."
I0301 13:01:53.904019       1 leaderelection.go:248] attempting to acquire leader lease cattle-monitoring-system/helm-project-operator-monitoring-lock...
I0301 13:01:53.918748       1 leaderelection.go:258] successfully acquired lease cattle-monitoring-system/helm-project-operator-monitoring-lock
E0301 13:01:54.012343       1 runtime.go:78] Observed a panic: &errors.errorString{s:"unable to calculate an index entry for key \"cattle-project-p-82r22/project-monitoring\" on index \"helm.cattle.io/project-helm-chart-by-release-name\": namespaces \"cattle-project-p-82r22\" not found"} (unable to calculate an index entry for key "cattle-project-p-82r22/project-monitoring" on index "helm.cattle.io/project-helm-chart-by-release-name": namespaces "cattle-project-p-82r22" not found)
goroutine 1222 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1655420?, 0xc0009860c0})
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:74 +0x86
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000b000a0?})
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:48 +0x75
panic({0x1655420, 0xc0009860c0})
	/usr/lib64/go/1.19/src/runtime/panic.go:884 +0x212
k8s.io/client-go/tools/cache.(*threadSafeMap).updateIndices(0xc00251d170, {0x0?, 0x0?}, {0x1855960, 0xc0002699f8}, {0xc0020d6d50, 0x29})
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/thread_safe_store.go:270 +0x385
k8s.io/client-go/tools/cache.(*threadSafeMap).Add(0xc00251d170, {0xc0020d6d50, 0x29}, {0x1855960?, 0xc0002699f8})
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/thread_safe_store.go:78 +0x147
k8s.io/client-go/tools/cache.(*cache).Add(0xc001f11a40, {0x1855960, 0xc0002699f8})
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/store.go:155 +0xb0
k8s.io/client-go/tools/cache.(*sharedIndexInformer).HandleDeltas(0xc0003c30e0, {0x16afa20?, 0xc000116228?})
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/shared_informer.go:558 +0x35c
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc000b000a0, 0xc0011cc350)
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/delta_fifo.go:539 +0x2f3
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc000b04510)
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/controller.go:183 +0x36
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x40d8bf?)
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xb5b065?, {0x1afe280, 0xc000b022d0}, 0x1, 0xc00092f620)
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000b04578?, 0x3b9aca00, 0x0, 0x0?, 0x7f7e6df0dcb0?)
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*controller).Run(0xc000b04510, 0xc00092f620)
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/controller.go:154 +0x2c6
k8s.io/client-go/tools/cache.(*sharedIndexInformer).Run(0xc0003c30e0, 0xc00092f620?)
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/shared_informer.go:410 +0x44c
github.com/rancher/lasso/pkg/cache.(*deferredCache).Run(0xc001f11a58, 0x0?)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220127-8cf5555ec03c/pkg/cache/cache.go:124 +0x42
created by github.com/rancher/lasso/pkg/cache.(*sharedCacheFactory).Start
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220127-8cf5555ec03c/pkg/cache/sharedinformerfactory.go:104 +0x278
E0301 13:01:54.012405       1 runtime.go:78] Observed a panic: &errors.errorString{s:"unable to calculate an index entry for key \"cattle-project-p-82r22/project-monitoring\" on index \"helm.cattle.io/project-helm-chart-by-release-name\": namespaces \"cattle-project-p-82r22\" not found"} (unable to calculate an index entry for key "cattle-project-p-82r22/project-monitoring" on index "helm.cattle.io/project-helm-chart-by-release-name": namespaces "cattle-project-p-82r22" not found)
goroutine 1222 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1655420?, 0xc0009860c0})
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:74 +0x86
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:48 +0x75
panic({0x1655420, 0xc0009860c0})
	/usr/lib64/go/1.19/src/runtime/panic.go:884 +0x212
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000b000a0?})
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:55 +0xd7
panic({0x1655420, 0xc0009860c0})
	/usr/lib64/go/1.19/src/runtime/panic.go:884 +0x212
k8s.io/client-go/tools/cache.(*threadSafeMap).updateIndices(0xc00251d170, {0x0?, 0x0?}, {0x1855960, 0xc0002699f8}, {0xc0020d6d50, 0x29})
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/thread_safe_store.go:270 +0x385
k8s.io/client-go/tools/cache.(*threadSafeMap).Add(0xc00251d170, {0xc0020d6d50, 0x29}, {0x1855960?, 0xc0002699f8})
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/thread_safe_store.go:78 +0x147
k8s.io/client-go/tools/cache.(*cache).Add(0xc001f11a40, {0x1855960, 0xc0002699f8})
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/store.go:155 +0xb0
k8s.io/client-go/tools/cache.(*sharedIndexInformer).HandleDeltas(0xc0003c30e0, {0x16afa20?, 0xc000116228?})
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/shared_informer.go:558 +0x35c
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc000b000a0, 0xc0011cc350)
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/delta_fifo.go:539 +0x2f3
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc000b04510)
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/controller.go:183 +0x36
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x40d8bf?)
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xb5b065?, {0x1afe280, 0xc000b022d0}, 0x1, 0xc00092f620)
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000b04578?, 0x3b9aca00, 0x0, 0x0?, 0x7f7e6df0dcb0?)
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*controller).Run(0xc000b04510, 0xc00092f620)
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/controller.go:154 +0x2c6
k8s.io/client-go/tools/cache.(*sharedIndexInformer).Run(0xc0003c30e0, 0xc00092f620?)
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/shared_informer.go:410 +0x44c
github.com/rancher/lasso/pkg/cache.(*deferredCache).Run(0xc001f11a58, 0x0?)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220127-8cf5555ec03c/pkg/cache/cache.go:124 +0x42
created by github.com/rancher/lasso/pkg/cache.(*sharedCacheFactory).Start
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220127-8cf5555ec03c/pkg/cache/sharedinformerfactory.go:104 +0x278
E0301 13:01:54.012498       1 runtime.go:78] Observed a panic: &errors.errorString{s:"unable to calculate an index entry for key \"cattle-project-p-82r22/project-monitoring\" on index \"helm.cattle.io/project-helm-chart-by-release-name\": namespaces \"cattle-project-p-82r22\" not found"} (unable to calculate an index entry for key "cattle-project-p-82r22/project-monitoring" on index "helm.cattle.io/project-helm-chart-by-release-name": namespaces "cattle-project-p-82r22" not found)
goroutine 1222 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1655420?, 0xc0009860c0})
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:74 +0x86
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000b1a300?})
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:48 +0x75
panic({0x1655420, 0xc0009860c0})
	/usr/lib64/go/1.19/src/runtime/panic.go:884 +0x212
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:55 +0xd7
panic({0x1655420, 0xc0009860c0})
	/usr/lib64/go/1.19/src/runtime/panic.go:884 +0x212
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000b000a0?})
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:55 +0xd7
panic({0x1655420, 0xc0009860c0})
	/usr/lib64/go/1.19/src/runtime/panic.go:884 +0x212
k8s.io/client-go/tools/cache.(*threadSafeMap).updateIndices(0xc00251d170, {0x0?, 0x0?}, {0x1855960, 0xc0002699f8}, {0xc0020d6d50, 0x29})
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/thread_safe_store.go:270 +0x385
k8s.io/client-go/tools/cache.(*threadSafeMap).Add(0xc00251d170, {0xc0020d6d50, 0x29}, {0x1855960?, 0xc0002699f8})
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/thread_safe_store.go:78 +0x147
k8s.io/client-go/tools/cache.(*cache).Add(0xc001f11a40, {0x1855960, 0xc0002699f8})
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/store.go:155 +0xb0
k8s.io/client-go/tools/cache.(*sharedIndexInformer).HandleDeltas(0xc0003c30e0, {0x16afa20?, 0xc000116228?})
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/shared_informer.go:558 +0x35c
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc000b000a0, 0xc0011cc350)
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/delta_fifo.go:539 +0x2f3
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc000b04510)
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/controller.go:183 +0x36
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x40d8bf?)
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xb5b065?, {0x1afe280, 0xc000b022d0}, 0x1, 0xc00092f620)
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000b04578?, 0x3b9aca00, 0x0, 0x0?, 0x7f7e6df0dcb0?)
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*controller).Run(0xc000b04510, 0xc00092f620)
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/controller.go:154 +0x2c6
k8s.io/client-go/tools/cache.(*sharedIndexInformer).Run(0xc0003c30e0, 0xc00092f620?)
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/shared_informer.go:410 +0x44c
github.com/rancher/lasso/pkg/cache.(*deferredCache).Run(0xc001f11a58, 0x0?)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220127-8cf5555ec03c/pkg/cache/cache.go:124 +0x42
created by github.com/rancher/lasso/pkg/cache.(*sharedCacheFactory).Start
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220127-8cf5555ec03c/pkg/cache/sharedinformerfactory.go:104 +0x278
panic: unable to calculate an index entry for key "cattle-project-p-82r22/project-monitoring" on index "helm.cattle.io/project-helm-chart-by-release-name": namespaces "cattle-project-p-82r22" not found [recovered]
	panic: unable to calculate an index entry for key "cattle-project-p-82r22/project-monitoring" on index "helm.cattle.io/project-helm-chart-by-release-name": namespaces "cattle-project-p-82r22" not found [recovered]
	panic: unable to calculate an index entry for key "cattle-project-p-82r22/project-monitoring" on index "helm.cattle.io/project-helm-chart-by-release-name": namespaces "cattle-project-p-82r22" not found [recovered]
	panic: unable to calculate an index entry for key "cattle-project-p-82r22/project-monitoring" on index "helm.cattle.io/project-helm-chart-by-release-name": namespaces "cattle-project-p-82r22" not found

goroutine 1222 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000b1a300?})
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:55 +0xd7
panic({0x1655420, 0xc0009860c0})
	/usr/lib64/go/1.19/src/runtime/panic.go:884 +0x212
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:55 +0xd7
panic({0x1655420, 0xc0009860c0})
	/usr/lib64/go/1.19/src/runtime/panic.go:884 +0x212
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000b000a0?})
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:55 +0xd7
panic({0x1655420, 0xc0009860c0})
	/usr/lib64/go/1.19/src/runtime/panic.go:884 +0x212
k8s.io/client-go/tools/cache.(*threadSafeMap).updateIndices(0xc00251d170, {0x0?, 0x0?}, {0x1855960, 0xc0002699f8}, {0xc0020d6d50, 0x29})
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/thread_safe_store.go:270 +0x385
k8s.io/client-go/tools/cache.(*threadSafeMap).Add(0xc00251d170, {0xc0020d6d50, 0x29}, {0x1855960?, 0xc0002699f8})
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/thread_safe_store.go:78 +0x147
k8s.io/client-go/tools/cache.(*cache).Add(0xc001f11a40, {0x1855960, 0xc0002699f8})
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/store.go:155 +0xb0
k8s.io/client-go/tools/cache.(*sharedIndexInformer).HandleDeltas(0xc0003c30e0, {0x16afa20?, 0xc000116228?})
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/shared_informer.go:558 +0x35c
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc000b000a0, 0xc0011cc350)
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/delta_fifo.go:539 +0x2f3
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc000b04510)
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/controller.go:183 +0x36
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x40d8bf?)
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xb5b065?, {0x1afe280, 0xc000b022d0}, 0x1, 0xc00092f620)
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000b04578?, 0x3b9aca00, 0x0, 0x0?, 0x7f7e6df0dcb0?)
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*controller).Run(0xc000b04510, 0xc00092f620)
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/controller.go:154 +0x2c6
k8s.io/client-go/tools/cache.(*sharedIndexInformer).Run(0xc0003c30e0, 0xc00092f620?)
	/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/shared_informer.go:410 +0x44c
github.com/rancher/lasso/pkg/cache.(*deferredCache).Run(0xc001f11a58, 0x0?)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220127-8cf5555ec03c/pkg/cache/cache.go:124 +0x42
created by github.com/rancher/lasso/pkg/cache.(*sharedCacheFactory).Start
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220127-8cf5555ec03c/pkg/cache/sharedinformerfactory.go:104 +0x278

```

**Expected Result**

Namespace will re-created if required or project monitoring should skipped/removed from the Operator watch

**Comment by AndrewHoffmanQA** [comment]
![image.png](https://zube.io/files/rancher/22575474c6b017cf55d2f19694023986-image.png)

QA testing notes

**Comment by AndrewHoffmanQA** [comment]
testing scope- 

run p0 test cases and an adhoc timeboxxed regression of prometheus federator functionality on both local and downstream clusters

testing results:
**local**: 
- install - pass
- helm locker functionality - pass
- project monitoring- in progress
- UI check - pass
- adhoc testing - in progress

**downstream**: 
- install - pass
- helm locker functionality - pass
- project monitoring- in progress
- UI check- pass
- adhoc testing - in progress

cluster information-
**Local cluster** 
3 nodes, all. roles each node
rancher image v2.6.13
k8- v1.24.13
RKE1

**downstream cluster**
3 nodes, 1 role each node. 2xlarge 100gb 
v1.24.13-rancher2-1


chart versions-
monitoring chart version- 100.2.0+up40.1.2 
promfetheus federator version pulled from https://github.com/rancher/prometheus-federator - version 0.3.1
