### ISSUE TITLE
"Attempt to cancel when process is still transitioning" - stuck host after upgrade to v1.0.0-rc4

### ISSUE THREAD

**Issue by frol** [rancher/rancher#4161]
Rancher Version: 1.0.0-rc4

Docker Version: 1.10.3

OS: Ubuntu 14.04

Steps to Reproduce: 

I'm not sure, but it seems that one of my hosts stuck while upgrading from Rancher v0.63 to v1.0.0-rc4. I have also removed the environment, where this host was registered, and now, when I try to register the host again, I'm seeing lots of tracebacks in Rancher Server logs.

Results: 

```
ERROR [:] [] [] [] [erviceReplay-20] [i.c.p.e.e.i.ProcessEventListenerImpl] Unknown exception running process [instance.purge:185501] on [144] java.lang.Ill
egalStateException: Attempt to cancel when process is still transitioning
      at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:191) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]server_1 |      at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:158) ~[cattle-framework-engine-0.5.0-SNAPSH
OT.jar:na]
      at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:108) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]server_1 |      at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:105) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
      at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
      at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
      at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
      at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
      at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:105) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
      at io.cattle.platform.engine.eventing.impl.ProcessEventListenerImpl.processExecute(ProcessEventListenerImpl.java:69) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
      at io.cattle.platform.engine.server.impl.ProcessInstanceParallelDispatcher$1.runInContext(ProcessInstanceParallelDispatcher.java:27) [cattle-framework-engine-0.5.0-SNAPSHOT.ja
r:na]
      at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]server_1 |      at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
      at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
      at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
      at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_95]
      at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_95]
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_95]
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_95]
      at java.lang.Thread.run(Thread.java:745) [na:1.7.0_95]
```

Expected:

I expect the host is registered just fine.

**Comment by ibuildthecloud** [comment]
Can you look at admin->processes in the UI and see if there is a process that is stuck?   Not related to that, there is a good chance you need to delete ‘/var/lib/rancher/state‘ and then the host should register fine.

**Comment by frol** [comment]
Here is a screenshot of the Processes page:

![rancher](https://cloud.githubusercontent.com/assets/304265/14068615/17fff626-f4b3-11e5-9780-abb37918dc08.png)

I'm going to clear all of those...

**Comment by frol** [comment]
BTW, there is no `/var/lib/rancher`:

```shell
# ls /var/lib/ | cat
apt
cattle
dhcp
dpkg
git
initramfs-tools
initscripts
insserv
libuuid
locales
logrotate
misc
mysql
nssdb
ntpdate
pam
plymouth
python
sudo
systemd
ucf
update-rc.d
urandom
ureadahead
vim
```

There is also no `state` file related to Rancher anywhere:

```shell
# find -name state | grep -v '/sys'
#
```

Thus, I have removed the `process_instance` records from MySQL:

```SQL
delete from process_instance where result is NULL;
```

**Comment by frol** [comment]
No stuck processes now, but the host cannot connect anyway. Here is the log from the agent:

```
INFO: Starting agent for BC0D7E52C2563E028334
INFO: Access Key: BC0D7E52C2563E028334
INFO: Config URL: http://10.250.10.10:8000/v1
INFO: Storage URL: http://10.250.10.10:8000/v1
INFO: API URL: http://10.250.10.10:8000/v1
INFO: IP: 172.18.0.1
INFO: Port:
INFO: Required Image: rancher/agent:v0.11.0
INFO: Current Image: rancher/agent:v0.11.0
INFO: Using image rancher/agent:v0.11.0
INFO: Downloading agent http://10.250.10.10:8000/v1/configcontent/configscripts
{"id":"xxxxxxxx-abe7-4b6f-b120-70662a4775d9","type":"error","links":{},"actions":{},"status":401,"code":"Unauthorized","message":"Unauthorized","detail":null}
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by frol** [comment]
Ah, ok, I figured it out. I was looking for `/var/lib/rancher` inside Rancher Server container, but I had to search for it on my host machine. Once I cleaned that folder up compltely and re-run `rancher/agent`, everything gets fine! Thank you!
