### ISSUE TITLE
[BUG] Import the CAPI cluster into Rancher fails

### ISSUE THREAD

**Issue by cpinjani** [rancher/rancher#41723]
**Rancher Server Setup**
- Rancher version: `2.7.3 or v2.7-head - fbca7c3`
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): K3S
- Proxy/Cert Details: Self-signed

**Information about the Cluster**
- Kubernetes version: k3s:v1.25.9-k3s1
- Cluster Type (Downstream):
   Imported = Running kubectl apply onto an existing CAPI docker cluster

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
Admin

**Describe the bug**

Importing the CAPI cluster into Rancher fails and Rancher crashes

**To Reproduce**

https://github.com/rancher/rancher/issues/39924#issuecomment-1568661964

**Expected Result**

Importing the CAPI cluster into Rancher should work, as in version 2.6.9

**Additional context**

- On 2.7.3, after registering the imported cluster rancher crashes (Regrdless of feature flag `embedded-cluster-api=false `set to true/false)
- On v2.7-head - fbca7c3, importing Custom cluster fails (screenshot below) But after registering, same error.

**Screenshots**

For v2.7-head - fbca7c3
![image](https://github.com/rancher/rancher/assets/73099870/7ad37159-1190-4919-9814-31982b1835f7)

**Logs**
```
2023/06/02 06:34:11 [INFO] Starting batch/v1, Kind=Job controller
2023/06/02 06:34:11 [INFO] Starting apps/v1, Kind=ReplicaSet controller
2023/06/02 06:34:11 [INFO] Starting /v1, Kind=Pod controller
2023/06/02 06:34:11 [INFO] Starting batch/v1, Kind=CronJob controller
2023/06/02 06:34:11 [INFO] Starting apps/v1, Kind=StatefulSet controller
2023/06/02 06:34:11 [INFO] Starting /v1, Kind=Event controller
2023/06/02 06:34:11 [INFO] Starting /v1, Kind=ReplicationController controller
2023/06/02 06:34:11 [INFO] Starting apps/v1, Kind=DaemonSet controller
2023/06/02 06:34:11 [INFO] Starting apps/v1, Kind=Deployment controller
2023/06/02 06:34:13 [INFO] EnsureSecretForServiceAccount: waiting for secret [cattle-impersonation-u-azlbd7nsxs-token-55msz] to be populated with token
2023/06/02 06:34:13 [INFO] Creating clusterRoleBinding User u-azlbd7nsxs Role cluster-owner
2023/06/02 06:34:15 [INFO] Loaded configuration from https://releases.rancher.com/kontainer-driver-metadata/release-v2.7/data.json in [0x6ceba18]
2023/06/02 06:34:15 [INFO] Loaded configuration from https://releases.rancher.com/kontainer-driver-metadata/release-v2.7/data.json in [0x6ceba18]
2023/06/02 06:34:22 [INFO] Creating system token for u-azlbd7nsxs, token: agent-u-azlbd7nsxs
E0602 06:34:22.366875      32 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 3350 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x372a4e0?, 0x6c36240})
        /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc005ad6020?})
        /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/runtime/runtime.go:49 +0x75
panic({0x372a4e0, 0x6c36240})
        /usr/lib64/go/1.19/src/runtime/panic.go:884 +0x212
github.com/rancher/rancher/pkg/provisioningv2/kubeconfig.(*Manager).kubeConfigValid(0x3f0ddde?, {0xc0002d4800?, 0x10?, 0x4867c40?}, 0xc0065df680, {0xc006d9d6e0, 0x14}, {0xc00ae1fb80, 0x298}, {0xc0060011a0, ...})
        /go/src/github.com/rancher/rancher/pkg/provisioningv2/kubeconfig/manager.go:265 +0x118
github.com/rancher/rancher/pkg/provisioningv2/kubeconfig.(*Manager).getKubeConfigData(0xc003b0b0e0, 0xc0065df680, {0xc0094e3c40, 0x10}, {0xc0060011a0, 0xc})
        /go/src/github.com/rancher/rancher/pkg/provisioningv2/kubeconfig/manager.go:296 +0x378
github.com/rancher/rancher/pkg/provisioningv2/kubeconfig.(*Manager).GetKubeConfig(0xc003b0b0e0, 0xc0065df680, {0x1, {0xc0060011a0, 0xc}, {0x0, 0x0}, 0x0, 0x1, {0xc00121bb00, ...}})
        /go/src/github.com/rancher/rancher/pkg/provisioningv2/kubeconfig/manager.go:390 +0x85
github.com/rancher/rancher/pkg/controllers/provisioningv2/cluster.(*handler).updateStatus(0xc003b04d00, {0xc00058fdc0, 0x1, 0x1}, 0xc0065df680, {0x0, {0xc0060011a0, 0xc}, {0x0, 0x0}, ...}, ...)
        /go/src/github.com/rancher/rancher/pkg/controllers/provisioningv2/cluster/controller.go:397 +0x2c5
github.com/rancher/rancher/pkg/controllers/provisioningv2/cluster.(*handler).createNewCluster(_, _, {0x0, {0xc0060011a0, 0xc}, {0x0, 0x0}, 0x0, 0x1, {0xc00d065800, ...}}, ...)
        /go/src/github.com/rancher/rancher/pkg/controllers/provisioningv2/cluster/controller.go:343 +0x89b
github.com/rancher/rancher/pkg/controllers/provisioningv2/cluster.(*handler).createCluster(_, _, {0x0, {0xc0060011a0, 0xc}, {0x0, 0x0}, 0x0, 0x1, {0xc00d065800, ...}}, ...)
        /go/src/github.com/rancher/rancher/pkg/controllers/provisioningv2/cluster/controller.go:268 +0x268
github.com/rancher/rancher/pkg/controllers/provisioningv2/cluster.(*handler).generateLegacyClusterFromProvisioningCluster(0xc003b04d00?, 0xc0065df680, {0x0, {0xc0060011a0, 0xc}, {0x0, 0x0}, 0x0, 0x1, {0xc00d065800, ...}})
        /go/src/github.com/rancher/rancher/pkg/controllers/provisioningv2/cluster/controller.go:212 +0x248
github.com/rancher/rancher/pkg/generated/controllers/provisioning.cattle.io/v1.(*clusterGeneratingHandler).Handle(0xc003a8dec0, 0xc0065df680, {0x0, {0xc0060011a0, 0xc}, {0x0, 0x0}, 0x0, 0x1, {0xc00d065800, ...}})
        /go/src/github.com/rancher/rancher/pkg/generated/controllers/provisioning.cattle.io/v1/cluster.go:367 +0x13c
github.com/rancher/rancher/pkg/generated/controllers/provisioning.cattle.io/v1.(*clusterStatusHandler).sync(0xc003b25da0, {0xc00407cb70?, 0x40ba74?}, 0xc00eceb8c0)
        /go/src/github.com/rancher/rancher/pkg/generated/controllers/provisioning.cattle.io/v1/cluster.go:307 +0x21c
github.com/rancher/rancher/pkg/generated/controllers/provisioning.cattle.io/v1.FromClusterHandlerToHandler.func1({0xc009880930?, 0x0?}, {0x480ca50?, 0xc00eceb8c0?})
        /go/src/github.com/rancher/rancher/pkg/generated/controllers/provisioning.cattle.io/v1/cluster.go:105 +0x44
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0x3e67460?, {0xc009880930?, 0x3f3c9c9?}, {0x480ca50?, 0xc00eceb8c0?})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000842550, {0xc009880930, 0x13}, {0x480ca50, 0xc00eceb8c0})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc0005a1290, {0xc009880930, 0x13})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:233 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0005a1290, {0x34ed8e0?, 0xc005ad6020?})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:214 +0x105
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0005a1290)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:191 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc003d116a0?)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:180 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x100034ed8e0?)
        /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x34ed8e0?, {0x48023e0, 0xc003e7e000}, 0x1, 0xc0001033e0)
        /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc002756bd0?, 0x3b9aca00, 0x0, 0xa0?, 0xc0027782e0?)
        /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0xc003d117c0?, 0xc002778320?, 0x19?)
        /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:92 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:148 +0x2a7
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x28bc1f8]

goroutine 3350 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc005ad6020?})
        /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/runtime/runtime.go:56 +0xd7
panic({0x372a4e0, 0x6c36240})
        /usr/lib64/go/1.19/src/runtime/panic.go:884 +0x212
github.com/rancher/rancher/pkg/provisioningv2/kubeconfig.(*Manager).kubeConfigValid(0x3f0ddde?, {0xc0002d4800?, 0x10?, 0x4867c40?}, 0xc0065df680, {0xc006d9d6e0, 0x14}, {0xc00ae1fb80, 0x298}, {0xc0060011a0, ...})
        /go/src/github.com/rancher/rancher/pkg/provisioningv2/kubeconfig/manager.go:265 +0x118
github.com/rancher/rancher/pkg/provisioningv2/kubeconfig.(*Manager).getKubeConfigData(0xc003b0b0e0, 0xc0065df680, {0xc0094e3c40, 0x10}, {0xc0060011a0, 0xc})
        /go/src/github.com/rancher/rancher/pkg/provisioningv2/kubeconfig/manager.go:296 +0x378
github.com/rancher/rancher/pkg/provisioningv2/kubeconfig.(*Manager).GetKubeConfig(0xc003b0b0e0, 0xc0065df680, {0x1, {0xc0060011a0, 0xc}, {0x0, 0x0}, 0x0, 0x1, {0xc00121bb00, ...}})
        /go/src/github.com/rancher/rancher/pkg/provisioningv2/kubeconfig/manager.go:390 +0x85
github.com/rancher/rancher/pkg/controllers/provisioningv2/cluster.(*handler).updateStatus(0xc003b04d00, {0xc00058fdc0, 0x1, 0x1}, 0xc0065df680, {0x0, {0xc0060011a0, 0xc}, {0x0, 0x0}, ...}, ...)
        /go/src/github.com/rancher/rancher/pkg/controllers/provisioningv2/cluster/controller.go:397 +0x2c5
github.com/rancher/rancher/pkg/controllers/provisioningv2/cluster.(*handler).createNewCluster(_, _, {0x0, {0xc0060011a0, 0xc}, {0x0, 0x0}, 0x0, 0x1, {0xc00d065800, ...}}, ...)
        /go/src/github.com/rancher/rancher/pkg/controllers/provisioningv2/cluster/controller.go:343 +0x89b
github.com/rancher/rancher/pkg/controllers/provisioningv2/cluster.(*handler).createCluster(_, _, {0x0, {0xc0060011a0, 0xc}, {0x0, 0x0}, 0x0, 0x1, {0xc00d065800, ...}}, ...)
        /go/src/github.com/rancher/rancher/pkg/controllers/provisioningv2/cluster/controller.go:268 +0x268
github.com/rancher/rancher/pkg/controllers/provisioningv2/cluster.(*handler).generateLegacyClusterFromProvisioningCluster(0xc003b04d00?, 0xc0065df680, {0x0, {0xc0060011a0, 0xc}, {0x0, 0x0}, 0x0, 0x1, {0xc00d065800, ...}})
        /go/src/github.com/rancher/rancher/pkg/controllers/provisioningv2/cluster/controller.go:212 +0x248
github.com/rancher/rancher/pkg/generated/controllers/provisioning.cattle.io/v1.(*clusterGeneratingHandler).Handle(0xc003a8dec0, 0xc0065df680, {0x0, {0xc0060011a0, 0xc}, {0x0, 0x0}, 0x0, 0x1, {0xc00d065800, ...}})
        /go/src/github.com/rancher/rancher/pkg/generated/controllers/provisioning.cattle.io/v1/cluster.go:367 +0x13c
github.com/rancher/rancher/pkg/generated/controllers/provisioning.cattle.io/v1.(*clusterStatusHandler).sync(0xc003b25da0, {0xc00407cb70?, 0x40ba74?}, 0xc00eceb8c0)
        /go/src/github.com/rancher/rancher/pkg/generated/controllers/provisioning.cattle.io/v1/cluster.go:307 +0x21c
github.com/rancher/rancher/pkg/generated/controllers/provisioning.cattle.io/v1.FromClusterHandlerToHandler.func1({0xc009880930?, 0x0?}, {0x480ca50?, 0xc00eceb8c0?})
        /go/src/github.com/rancher/rancher/pkg/generated/controllers/provisioning.cattle.io/v1/cluster.go:105 +0x44
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0x3e67460?, {0xc009880930?, 0x3f3c9c9?}, {0x480ca50?, 0xc00eceb8c0?})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000842550, {0xc009880930, 0x13}, {0x480ca50, 0xc00eceb8c0})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc0005a1290, {0xc009880930, 0x13})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:233 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0005a1290, {0x34ed8e0?, 0xc005ad6020?})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:214 +0x105
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0005a1290)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:191 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc003d116a0?)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:180 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x100034ed8e0?)
        /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x34ed8e0?, {0x48023e0, 0xc003e7e000}, 0x1, 0xc0001033e0)
        /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc002756bd0?, 0x3b9aca00, 0x0, 0xa0?, 0xc0027782e0?)
        /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0xc003d117c0?, 0xc002778320?, 0x19?)
        /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:92 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:148 +0x2a7
```

**Comment by cpinjani** [comment]
Blocks https://github.com/rancher/rancher/issues/39924
