### ISSUE TITLE
Errors seen in agent container logs.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4179]
Rancher Version: v1.0.0-rc6

When first container is launched on the host , following error is seen in agent's container logs.
```
iptables: No chain/target/match by that name.
2016-03-28 20:08:05,240 ERROR docker [139785082633104] [network.py:148] Failed to apply iptables 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/network.py", line 141, in setup_dns
    mark])
  File "/var/lib/cattle/pyagent/cattle/utils.py", line 337, in check_output
    raise e1
CalledProcessError: Command '['iptables', '-w', '-t', 'nat', '-A', 'CATTLE_PREROUTING', '!', '-s', '10.42.0.0/16', '-d', '169.254.169.250', '-m', 'mac', '--mac-source', u'02:e3:23:ee:6f:f0', '-j', 'MARK', '--set-mark', '171227']' returned non-zero exit status 1
```

**Comment by sangeethah** [comment]
Tested with Rancher Version: v1.0.0-rc7
Error message in bug is not present in the  agent's container logs.
