### ISSUE TITLE
Logs filled with basename errors

### ISSUE THREAD

**Issue by jwhitcraft** [rancher/rancher#4196]
Rancher Version: 1.0.0

Docker Version: 1.9.1

OS: ubuntu 14.04

I just upgraded to 1.0.0 and now i'm seeing these in the rancher-server log

```
2016-03-29 15:13:58,547 ERROR [:] [] [] [] [cutorService-10] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed null, exit code [1] output [INFO: Updating hosts
INFO: Downloading http://rancher.qa.sugarcrm.net/v1//configcontent//hosts current=hosts-96643-46bf3f2cd5e10e348cea0a9b2c2f20e1ff10eda99e38ca8db85820b45973a1d8
basename: missing operand
Try 'basename --help' for more information.
ERROR: Missing SHA1SUMS files, invalid download
]
```

**Comment by ibuildthecloud** [comment]
Typically there is a corresponding error in the rancher/server container logs.  Can you look there?

**Comment by jwhitcraft** [comment]
```
INFO: Updating hosts
[config.sh:264] UPTODATE=false
[config.sh:265] download hosts
[config.sh:82] cleanup
[config.sh:9] EXIT=0
[config.sh:11] '[' -e '' ']'
[config.sh:15] return 0
[[config.sh:84] mktemp -d /var/lib/cattle/download.XXXXXXX
[config.sh:84] DOWNLOAD_TEMP=/var/lib/cattle/download.o0yl4Wu
[config.sh:86] '[' -z http://rancher.qa.sugarcrm.net/v1 ']'
[config.sh:86] '[' -z 18EF42A4870C675CD133:QdKVoNVyCjb8hwuaLigdHvJueF2raAD5JsBrW87s ']'
[config.sh:92] local name=hosts
[config.sh:93] local current
[config.sh:94] local archive_version
[config.sh:96] purge_old /var/lib/cattle/download/hosts
[config.sh:63] local exclude=current
[config.sh:64] local dir=/var/lib/cattle/download/hosts
[config.sh:66] '[' '!' -d /var/lib/cattle/download/hosts ']'
[config.sh:67] return 0
[config.sh:98] '[' true '!=' true ']'
[config.sh:102] DOWNLOAD_URL=http://rancher.qa.sugarcrm.net/v1//configcontent//hosts
[config.sh:104] local get_opts
[config.sh:105] local archive_version
[config.sh:106] '[' -n '' ']'
[config.sh:118] info Downloading http://rancher.qa.sugarcrm.net/v1//configcontent//hosts current=
[scripts.sh:19] echo INFO: Downloading http://rancher.qa.sugarcrm.net/v1//configcontent//hosts current=
[config.sh:120] get 'http://rancher.qa.sugarcrm.net/v1//configcontent//hosts?current='
[scripts.sh:43] '[' 'http://rancher.qa.sugarcrm.net/v1//configcontent//hosts?current=' = --no-auth ']'
[scripts.sh:47] call_curl -L 'http://rancher.qa.sugarcrm.net/v1//configcontent//hosts?current='
[scripts.sh:29] local 'curl=curl -s --connect-timeout 20'
[scripts.sh:30] '[' '' = false ']'
[scripts.sh:32] '[' -n 'Basic MThFRjQyQTQ4NzBDNjc1Q0QxMzM6UWRLVm9OVnlDamI4aHd1YUxpZ2RIdkp1ZUYycmFBRDVKc0JyVzg3cw==' ']'
INFO: Downloading http://rancher.qa.sugarcrm.net/v1//configcontent//hosts current=
[scripts.sh:33] curl -s --connect-timeout 20 -H 'Authorization: Basic MThFRjQyQTQ4NzBDNjc1Q0QxMzM6UWRLVm9OVnlDamI4aHd1YUxpZ2RIdkp1ZUYycmFBRDVKc0JyVzg3cw==' -L 'http://rancher.qa.sugarcrm.net/v1//configcontent//hosts?current='
[[config.sh:121] cat /var/lib/cattle/download.o0yl4Wu/download
[[config.sh:121] head -n1
 �Om7��7��'\''('HEADER='��
 �Om7��7��'( =~ version:* ]]
[config.sh:126] tar xzf /var/lib/cattle/download.o0yl4Wu/download -C /var/lib/cattle/download.o0yl4Wu
[config.sh:135] rm /var/lib/cattle/download.o0yl4Wu/download
[[[config.sh:137] ls -1 /var/lib/cattle/download.o0yl4Wu
[[config.sh:137] basename
basename: missing operand
Try 'basename --help' for more information.
[config.sh:137] local dir=
[config.sh:138] '[' '!' -e /var/lib/cattle/download.o0yl4Wu/ ']'
[config.sh:145] cd /var/lib/cattle/download.o0yl4Wu
[config.sh:147] '[' '!' -e /SHA1SUMSSUM ']'
[config.sh:148] error 'Missing SHA1SUMS files, invalid download'
[scripts.sh:24] echo ERROR: 'Missing SHA1SUMS files, invalid download'
ERROR: Missing SHA1SUMS files, invalid download
[config.sh:149] exit 1
[config.sh:1] cleanup
[config.sh:9] EXIT=1
[config.sh:11] '[' -e /var/lib/cattle/download.o0yl4Wu ']'
[config.sh:12] rm -rf /var/lib/cattle/download.o0yl4Wu
[config.sh:15] return 1
```
Is what I found, i thikn that is also what is killing my networking ages in #4194

**Comment by jwhitcraft** [comment]
It also has this at the end of the networking agent

```
The system is going down NOW!
Sent SIGTERM to all processes
Sent SIGKILL to all processes
Requesting system reboot
```

**Comment by jwhitcraft** [comment]
I pulled back to 0.63.1 and all the problems i was seeing with the networking containers went away.

**Comment by ibuildthecloud** [comment]
@jwhitcraft Yes, that NullPointerException is what I was looking for, can you share the lines that follow in the log.  The stack trace is the most important part.

**Comment by jwhitcraft** [comment]
@ibuildthecloud, there was no stack trace associated with it, just that line reported multiple times in a row.

**Comment by ibuildthecloud** [comment]
Ah crap, that's the worse.

**Comment by ibuildthecloud** [comment]
@jwhitcraft Did you ever install a 1.0.0-rc build?

**Comment by jwhitcraft** [comment]
@ibuildthecloud, nope I was on 0.63.0 and saw 1.0.0 was released so i figured, I would try to upgrade to see if it solved my ip problem.

**Comment by ibuildthecloud** [comment]
@jwhitcraft We have found the issue and are fixing.  The odd thing though is why didn't that error print a stack trace.  When I run the same issue on my side I get a stack trace.

**Comment by jwhitcraft** [comment]
@ibuildthecloud, very strange.  Glad you found it though.

**Comment by alena1108** [comment]
@ibuildthecloud @jwhitcraft The issue was caused by existing service link pointing to a removed service (UI as well as API allowed to set a link to a removed target service). This kind of condition in turn triggered NPE in metadata config item update. Applied 2 fixes: API validation on a target service state as well as not null check in metadata config generation.

**Comment by sangeethah** [comment]
Rancher server version - v0.63.1

Create a service -s1.
Delete the service -s1.
Create another service - s2 and link to service s1.

mysql> select id, name, state from service where id in (select consumed_service_id from service_consume_map where removed is null) and removed is not null;
+----+--------------+---------+
| id | name         | state   |
+----+--------------+---------+
|  6 | testmeremove | removed |
+----+--------------+---------+
1 row in set (0.00 sec)

mysql> 

Upgrade to v1.0.0. 
Once upgrade is completed , following exception is seen repeatedly in logs:

```
2016-04-07 17:40:57,626 ERROR [:] [] [] [] [tp639313753-103] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [io.github.ibuildthecloud.gdapi.request.ApiRequest@257fe6e9] java.lang.NullPointerException: null
	at io.cattle.platform.configitem.context.impl.ServiceMetadataInfoFactory.setLinksInfo(ServiceMetadataInfoFactory.java:411) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.context.impl.ServiceMetadataInfoFactory.applyVersionToService(ServiceMetadataInfoFactory.java:224) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.context.impl.ServiceMetadataInfoFactory.getFullMetaData(ServiceMetadataInfoFactory.java:142) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.context.impl.ServiceMetadataInfoFactory.populateContext(ServiceMetadataInfoFactory.java:82) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.context.impl.AbstractAgentBaseContextFactory.populateContext(AbstractAgentBaseContextFactory.java:69) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.server.model.impl.AbstractArchiveBasedConfigItem.handleRequest(AbstractArchiveBasedConfigItem.java:56) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.server.impl.ConfigItemServerImpl.handleDownload(ConfigItemServerImpl.java:97) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.server.impl.ConfigItemServerImpl.handleRequest(ConfigItemServerImpl.java:40) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.api.manager.ConfigContentManager.handle(ConfigContentManager.java:80) ~[cattle-config-item-api-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.api.manager.ConfigContentManager.getByIdInternal(ConfigContentManager.java:49) ~[cattle-config-item-api-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.getById(AbstractBaseResourceManager.java:61) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.ResourceManagerRequestHandler.generate(ResourceManagerRequestHandler.java:49) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.AbstractResponseGenerator.handle(AbstractResponseGenerator.java:14) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.handle(DefaultReadWriteApiDelegate.java:27) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.read(DefaultReadWriteApiDelegate.java:17) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at sun.reflect.GeneratedMethodAccessor385.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_95]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_95]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96) ~[spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260) ~[spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94) ~[spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at com.sun.proxy.$Proxy45.read(Unknown Source) ~[na:na]
	at io.github.ibuildthecloud.gdapi.request.handler.write.ReadWriteApiHandler.handle(ReadWriteApiHandler.java:21) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:86) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:90) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:83) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [jetty-security-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.Server.handle(Server.java:499) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_95]

2016-04-07 17:40:57,646 ERROR [:] [] [] [] [ecutorService-8] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed null, exit code [1] output [INFO: Updating ipsec-hosts
INFO: Removing ipsec-hosts-34-04dc8ee18155dd4e7898fbcd23391737fc0ef00a77218e819e7e2d37bde03345
INFO: Downloading http://104.197.173.40:8080/v1//configcontent//ipsec-hosts current=ipsec-hosts-45-d9e643568adffad1bf56033ff5cba1231b2269bdf1ad1e92181810fc6769449c
INFO: Already up to date
INFO: Sending ipsec-hosts applied 45-d9e643568adffad1bf56033ff5cba1231b2269bdf1ad1e92181810fc6769449c
INFO: Updating hosts
INFO: Downloading http://104.197.173.40:8080/v1//configcontent//hosts current=hosts-188-46bf3f2cd5e10e348cea0a9b2c2f20e1ff10eda99e38ca8db85820b45973a1d8
basename: missing operand
Try 'basename --help' for more information.
ERROR: Missing SHA1SUMS files, invalid download
] 
2016-04-07 17:40:57,653 ERROR [:] [] [] [] [ecutorService-5] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed null, exit code [1] output [INFO: Updating ipsec-hosts
INFO: Removing ipsec-hosts-34-04dc8ee18155dd4e7898fbcd23391737fc0ef00a77218e819e7e2d37bde03345
INFO: Downloading http://104.197.173.40:8080/v1//configcontent//ipsec-hosts current=ipsec-hosts-45-d9e643568adffad1bf56033ff5cba1231b2269bdf1ad1e92181810fc6769449c
INFO: Already up to date
INFO: Sending ipsec-hosts applied 45-d9e643568adffad1bf56033ff5cba1231b2269bdf1ad1e92181810fc6769449c
INFO: Updating hosts
INFO: Downloading http://104.197.173.40:8080/v1//configcontent//hosts current=hosts-186-46bf3f2cd5e10e348cea0a9b2c2f20e1ff10eda99e38ca8db85820b45973a1d8
basename: missing operand
Try 'basename --help' for more information.
ERROR: Missing SHA1SUMS files, invalid download
```

Upgrade to v1.0.1-rc1.

After upgrading to  v1.0.1-rc1:
These errors are not seen any more in the logs.
Also I am able to start new instances on the upgraded setup.

**Comment by sangeethah** [comment]
Rancher server version - v0.63.1

Create a service -s1.
Delete the service -s1.
Create another service - s2 and link to service s1.

Create a service -s3. Activate the service.
Delete the service -s3.
Create another service - s4 and link to service s3.

upgraded to v1.0.0

Once upgrade is completed , NullPointerExceptions were seen in logs and starting new instances resulted in instances being stuck in "networking" state.

Downgrade to v0.63.1
NullPointerException was not seen anymore.
Created few more services.
Upgraded to v1.0.1

Following NullPointerExceptions are again seen in logs and I am not able to start new instances anymore , they get stuck in "networking" state.

```
2016-04-11 19:24:29,647 ERROR [:] [] [] [] [tp639313753-106] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [io.github.ibuildthecloud.gdapi.request.ApiRequest@fc88f91] java.lang.NullPointerException: null
	at io.cattle.platform.configitem.context.impl.ServiceMetadataInfoFactory.setLinksInfo(ServiceMetadataInfoFactory.java:410) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.context.impl.ServiceMetadataInfoFactory.applyVersionToService(ServiceMetadataInfoFactory.java:223) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.context.impl.ServiceMetadataInfoFactory.getFullMetaData(ServiceMetadataInfoFactory.java:142) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.context.impl.ServiceMetadataInfoFactory.populateContext(ServiceMetadataInfoFactory.java:82) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.context.impl.AbstractAgentBaseContextFactory.populateContext(AbstractAgentBaseContextFactory.java:69) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.server.model.impl.AbstractArchiveBasedConfigItem.handleRequest(AbstractArchiveBasedConfigItem.java:56) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.server.impl.ConfigItemServerImpl.handleDownload(ConfigItemServerImpl.java:97) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.server.impl.ConfigItemServerImpl.handleRequest(ConfigItemServerImpl.java:40) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.api.manager.ConfigContentManager.handle(ConfigContentManager.java:80) ~[cattle-config-item-api-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.api.manager.ConfigContentManager.getByIdInternal(ConfigContentManager.java:49) ~[cattle-config-item-api-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.getById(AbstractBaseResourceManager.java:61) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.ResourceManagerRequestHandler.generate(ResourceManagerRequestHandler.java:49) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.AbstractResponseGenerator.handle(AbstractResponseGenerator.java:14) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.handle(DefaultReadWriteApiDelegate.java:27) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.read(DefaultReadWriteApiDelegate.java:17) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at sun.reflect.GeneratedMethodAccessor363.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_95]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_95]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96) ~[spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260) ~[spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94) ~[spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at com.sun.proxy.$Proxy45.read(Unknown Source) ~[na:na]
	at io.github.ibuildthecloud.gdapi.request.handler.write.ReadWriteApiHandler.handle(ReadWriteApiHandler.java:21) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:86) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:90) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:83) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [jetty-security-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.Server.handle(Server.java:499) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_95]

2016-04-11 19:24:29,656 ERROR [:] [] [] [] [ecutorService-5] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed null, exit code [1] output [INFO: Updating hosts
INFO: Downloading http://146.148.107.5:8080/v1//configcontent//hosts current=hosts-249-46bf3f2cd5e10e348cea0a9b2c2f20e1ff10eda99e38ca8db85820b45973a1d8
basename: missing operand
Try 'basename --help' for more information.
ERROR: Missing SHA1SUMS files, invalid download
] 

```

mysql> select id, name, state from service where id in (select consumed_service_id from service_consume_map where removed is null) and removed is not null;    
+----+------+---------+
| id | name | state   |
+----+------+---------+
| 21 | yo1  | removed |
| 22 | yo2  | removed |
+----+------+---------+
2 rows in set (0.00 sec)

mysql> select id,name,state from service where name like "%_yo%";                                                                                              
+----+---------+--------+
| id | name    | state  |
+----+---------+--------+
| 23 | testyo1 | active |
| 24 | testyo2 | active |
+----+---------+--------+
2 rows in set (0.00 sec)

mysql> select id, name, state from service where id in (select consumed_service_id from service_consume_map where removed is null) and removed is not null;    
+----+------+---------+
| id | name | state   |
+----+------+---------+
| 21 | yo1  | removed |
| 22 | yo2  | removed |
+----+------+---------+
2 rows in set (0.00 sec)

```
