### ISSUE TITLE
[BUG] harvester feature causing go painc in v2.7.5

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#42200]
**Rancher Server Setup**
- Rancher version: v2.7.5
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: v1.27.4+rke2r1
- Cluster Type (Local/Downstream): local

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) N/A
  - If custom, define the set of permissions: N/A

**Describe the bug**

Out of the blue, all 3 Rancher server pods started crashing looping with the following go panic.

**To Reproduce**
Have the harvester feature enabled and upgrade from v2.7.4 -> v2.7.5.

If you disable this feature, the panic goes away.

```bash
kubectl edit features.management.cattle.io harvester
```

Just set it to the following:

```yaml
spec:
  value: true
```

**Result**
N/A

**Expected Result**
N/A

**Screenshots**

**Additional context**

Note: This is a very old Rancher deployment (it was deployed on v2.0.1 when it was released), so legacy settings/data might be causing this. Also, I was able to reproduce the same issue in another cluster using a Rancher Operator Backup.

GO Panic:

```
E0724 18:27:17.438847      33 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 4117 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3809be0?, 0x6e716f0})
	/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc048b4ab00?})
	/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/runtime/runtime.go:49 +0x75
panic({0x3809be0, 0x6e716f0})
	/usr/lib64/go/1.19/src/runtime/panic.go:884 +0x212
github.com/rancher/rancher/pkg/controllers/management/feature.(*handler).syncHarvesterFeature(0xc07c176380, 0xc007c7f390)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/feature/feature_handler.go:83 +0x1ef
github.com/rancher/rancher/pkg/controllers/management/feature.(*handler).sync(0x0?, {0xc0209dbb70?, 0x40ba74?}, 0x3e343e0?)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/feature/feature_handler.go:54 +0xf4
github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3.FromFeatureHandlerToHandler.func1({0xc00257b230?, 0x0?}, {0x4985270?, 0xc007c7f390?})
	/go/src/github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3/feature.go:105 +0x44
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0x3f52900?, {0xc00257b230?, 0x4041e04?}, {0x4985270?, 0xc007c7f390?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000c500f0, {0xc00257b230, 0x26}, {0x4985270, 0xc007c7f390})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc00115da20, {0xc00257b230, 0x26})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:232 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc00115da20, {0x35c70e0?, 0xc048b4ab00?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:213 +0x105
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc00115da20)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:190 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc0208996a0?)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:179 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x3a22736e6f?)
	/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x7463656a626f3a66?, {0x497c060, 0xc00b9cde30}, 0x1, 0xc001b9c060)
	/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x7d7d7b3a22656361?, 0x3b9aca00, 0x0, 0x3a?, 0x7461632e7465656c?)
	/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x626f3a66222c7d7b?, 0x2e7465737463656a?, 0x747461632e6f6972?)
	/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:92 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:147 +0x2a7
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2d74eaf]

goroutine 4117 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc048b4ab00?})
	/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/runtime/runtime.go:56 +0xd7
panic({0x3809be0, 0x6e716f0})
	/usr/lib64/go/1.19/src/runtime/panic.go:884 +0x212
github.com/rancher/rancher/pkg/controllers/management/feature.(*handler).syncHarvesterFeature(0xc07c176380, 0xc007c7f390)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/feature/feature_handler.go:83 +0x1ef
github.com/rancher/rancher/pkg/controllers/management/feature.(*handler).sync(0x0?, {0xc0209dbb70?, 0x40ba74?}, 0x3e343e0?)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/feature/feature_handler.go:54 +0xf4
github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3.FromFeatureHandlerToHandler.func1({0xc00257b230?, 0x0?}, {0x4985270?, 0xc007c7f390?})
	/go/src/github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3/feature.go:105 +0x44
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0x3f52900?, {0xc00257b230?, 0x4041e04?}, {0x4985270?, 0xc007c7f390?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000c500f0, {0xc00257b230, 0x26}, {0x4985270, 0xc007c7f390})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc00115da20, {0xc00257b230, 0x26})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:232 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc00115da20, {0x35c70e0?, 0xc048b4ab00?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:213 +0x105
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc00115da20)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:190 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc0208996a0?)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:179 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x3a22736e6f?)
	/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x7463656a626f3a66?, {0x497c060, 0xc00b9cde30}, 0x1, 0xc001b9c060)
	/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x7d7d7b3a22656361?, 0x3b9aca00, 0x0, 0x3a?, 0x7461632e7465656c?)
	/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x626f3a66222c7d7b?, 0x2e7465737463656a?, 0x747461632e6f6972?)
	/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:92 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:147 +0x2a7
```

**Comment by noahgildersleeve** [comment]
I was able to repro the issue in Rancher v2.7.5 in a single node docker instance. 

- [ ] Rancher v2.7-59b00c6f9a0a7c598e24c491c045a0fc0586ba6b-head single node Docker instance running on openSUSE Leap 15.4 with Harvester v1.2.0-rc4 imported

- [ ] Rancher v2.7-59b00c6f9a0a7c598e24c491c045a0fc0586ba6b-head single node Docker instance running on openSUSE Leap 15.4 with no Harvester imported.

**Comment by noahgildersleeve** [comment]
Validated as fixed. Both tests passed.

**Comment by noahgildersleeve** [comment]
Tested in v2.7.6-head. Tested with single node docker instance on opens use. After enabling the feature flag it caused a panic. 

```
E0825 22:05:44.203624      44 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 3268 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x381b2a0?, 0x6e8fb10})
	/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc006423140?})
	/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/runtime/runtime.go:49 +0x75
panic({0x381b2a0, 0x6e8fb10})
	/usr/lib64/go/1.19/src/runtime/panic.go:884 +0x212
github.com/rancher/rancher/pkg/controllers/management/feature.(*handler).syncHarvesterFeature(0xc00565b240, 0xc0028e2390)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/feature/feature_handler.go:83 +0x1ef
github.com/rancher/rancher/pkg/controllers/management/feature.(*handler).sync(0x0?, {0xc006792b70?, 0x40ba74?}, 0x3e465a0?)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/feature/feature_handler.go:54 +0xf4
github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3.FromFeatureHandlerToHandler.func1({0xc0027a8de0?, 0x0?}, {0x499d610?, 0xc0028e2390?})
	/go/src/github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3/feature.go:105 +0x44
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0x3f64e20?, {0xc0027a8de0?, 0x405436c?}, {0x499d610?, 0xc0028e2390?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc0006f03c0, {0xc0027a8de0, 0x26}, {0x499d610, 0xc0028e2390})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc00071ae70, {0xc0027a8de0, 0x26})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:232 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc00071ae70, {0x35d8600?, 0xc006423140?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:213 +0x105
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc00071ae70)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:190 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc0045fe6a0?)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:179 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x6765722d69?)
	/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x202020202020206e?, {0x49943c0, 0xc0041feba0}, 0x1, 0xc0015062a0)
	/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x206e5c7473756d20?, 0x3b9aca00, 0x0, 0x20?, 0x696c61635b206568?)
	/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x6c6176206e6f6967?, 0x69666e6f63206575?, 0x6e69206465727567?)
	/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:92 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:147 +0x2a7
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2d8530f]

goroutine 3268 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc006423140?})
	/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/runtime/runtime.go:56 +0xd7
panic({0x381b2a0, 0x6e8fb10})
	/usr/lib64/go/1.19/src/runtime/panic.go:884 +0x212
github.com/rancher/rancher/pkg/controllers/management/feature.(*handler).syncHarvesterFeature(0xc00565b240, 0xc0028e2390)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/feature/feature_handler.go:83 +0x1ef
github.com/rancher/rancher/pkg/controllers/management/feature.(*handler).sync(0x0?, {0xc006792b70?, 0x40ba74?}, 0x3e465a0?)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/feature/feature_handler.go:54 +0xf4
github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3.FromFeatureHandlerToHandler.func1({0xc0027a8de0?, 0x0?}, {0x499d610?, 0xc0028e2390?})
	/go/src/github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3/feature.go:105 +0x44
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0x3f64e20?, {0xc0027a8de0?, 0x405436c?}, {0x499d610?, 0xc0028e2390?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc0006f03c0, {0xc0027a8de0, 0x26}, {0x499d610, 0xc0028e2390})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc00071ae70, {0xc0027a8de0, 0x26})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:232 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc00071ae70, {0x35d8600?, 0xc006423140?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:213 +0x105
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc00071ae70)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:190 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc0045fe6a0?)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:179 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x6765722d69?)
	/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x202020202020206e?, {0x49943c0, 0xc0041feba0}, 0x1, 0xc0015062a0)
	/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x206e5c7473756d20?, 0x3b9aca00, 0x0, 0x20?, 0x696c61635b206568?)
	/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x6c6176206e6f6967?, 0x69666e6f63206575?, 0x6e69206465727567?)
	/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:92 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:147 +0x2a7
```

**Comment by noahgildersleeve** [comment]
I tested this in Rancher v2.7.6-rc5 and it seems to be working.
- Single node docker instance on Opensuse v2.7.6-rc5
- Harvester single node bare metal v1.2.0-rc5
![Greenshot 2023-08-27 09 16 33](https://github.com/rancher/rancher/assets/83787952/ba1f336b-1269-4b08-a127-0efd8c544f5a)
