### ISSUE TITLE
[flaky-test] TestProjectUserTestSuite/TestCreateNamespaceProjectMember integration/projects/project_user_test.go

### ISSUE THREAD

**Issue by felipe-colussi** [rancher/rancher#42264]
_Note: Description updated from more recent https://github.com/rancher/rancher/issues/45806 which will be closed as duplicate._

**Flaky test: TestProjectUserTestSuite**

```
=== RUN   TestProjectUserTestSuite/TestCreateNamespaceProjectMember
    project_user_test.go:82: 
        	Error Trace:	/go/src/github.com/rancher/rancher/tests/v2/integration/projects/project_user_test.go:82
        	Error:      	Received unexpected error:
        	            	Resource type [namespace] is not creatable
        	            	github.com/rancher/shepherd/pkg/clientbase.(*APIOperations).DoCreate
        	            		/go/pkg/mod/github.com/rancher/shepherd@v0.0.0-20240531204216-65735fd062c1/pkg/clientbase/ops.go:197
        	            	github.com/rancher/shepherd/clients/rancher/v1.(*SteveClient).Create
        	            		/go/pkg/mod/github.com/rancher/shepherd@v0.0.0-20240531204216-65735fd062c1/clients/rancher/v1/client.go:177
        	            	github.com/rancher/shepherd/extensions/namespaces.CreateNamespace
        	            		/go/pkg/mod/github.com/rancher/shepherd@v0.0.0-20240531204216-65735fd062c1/extensions/namespaces/create.go:56
        	            	github.com/rancher/rancher/tests/v2/integration/projects.(*ProjectUserTestSuite).TestCreateNamespaceProjectMember
        	            		/go/src/github.com/rancher/rancher/tests/v2/integration/projects/project_user_test.go:81
        	            	reflect.Value.call
        	            		/usr/lib64/go/1.22/src/reflect/value.go:596
        	            	reflect.Value.Call
        	            		/usr/lib64/go/1.22/src/reflect/value.go:380
        	            	github.com/stretchr/testify/suite.Run.func1
        	            		/go/pkg/mod/github.com/stretchr/testify@v1.9.0/suite/suite.go:202
        	            	testing.tRunner
        	            		/usr/lib64/go/1.22/src/testing/testing.go:1689
        	            	runtime.goexit
        	            		/usr/lib64/go/1.22/src/runtime/asm_amd64.s:1695
        	Test:       	TestProjectUserTestSuite/TestCreateNamespaceProjectMember
    panic.go:261: test panicked: runtime error: invalid memory address or nil pointer dereference
        goroutine 82 [running]:
        runtime/debug.Stack()
        	/usr/lib64/go/1.22/src/runtime/debug/stack.go:24 +0x5e
        github.com/stretchr/testify/suite.failOnPanic(0xc000a209c0, {0x375a6c0, 0x5aa8360})
        	/go/pkg/mod/github.com/stretchr/testify@v1.9.0/suite/suite.go:89 +0x37
        github.com/stretchr/testify/suite.Run.func1.1()
        	/go/pkg/mod/github.com/stretchr/testify@v1.9.0/suite/suite.go:188 +0x299
        panic({0x375a6c0?, 0x5aa8360?})
        	/usr/lib64/go/1.22/src/runtime/panic.go:770 +0x132
        github.com/rancher/rancher/tests/v2/integration/projects.(*ProjectUserTestSuite).TestCreateNamespaceProjectMember(0xc000052f00)
        	/go/src/github.com/rancher/rancher/tests/v2/integration/projects/project_user_test.go:83 +0x368
        reflect.Value.call({0xc0006e7900?, 0xc000691328?, 0x13?}, {0x3c395b5, 0x4}, {0xc0000acf28, 0x1, 0x1?})
        	/usr/lib64/go/1.22/src/reflect/value.go:596 +0xca6
        reflect.Value.Call({0xc0006e7900?, 0xc000691328?, 0x528c0b0?}, {0xc00011d728?, 0xf?, 0x0?})
        	/usr/lib64/go/1.22/src/reflect/value.go:380 +0xb9
        github.com/stretchr/testify/suite.Run.func1(0xc000a209c0)
        	/go/pkg/mod/github.com/stretchr/testify@v1.9.0/suite/suite.go:202 +0x4a5
        testing.tRunner(0xc000a209c0, 0xc000597830)
        	/usr/lib64/go/1.22/src/testing/testing.go:1689 +0xfb
        created by testing.(*T).Run in goroutine 13
        	/usr/lib64/go/1.22/src/testing/testing.go:1742 +0x390
--- FAIL: TestProjectUserTestSuite (1.17s)
    --- FAIL: TestProjectUserTestSuite/TestCreateNamespaceProjectMember (0.84s)
FAIL
FAIL	github.com/rancher/rancher/tests/v2/integration/projects	1.197s
```

**Release Branch** 2.9
source branch of PR: `release/v2.9`

**Drone Build (if applicable)**
 * good one (passing): https://drone-pr.rancher.io/rancher/rancher/40019/6/2
 * bad one (not passing): https://drone-pr.rancher.io/rancher/rancher/39965/6/2

**Comment by pjbgf** [comment]
Another instance: https://drone-pr.rancher.io/rancher/rancher/31178/5/2

**Comment by MbolotSuse** [comment]
Another instance: https://drone-pr.rancher.io/rancher/rancher/31275/5/2

**Comment by felipe-colussi** [comment]
Again on 2.8 : 
https://drone-pr.rancher.io/rancher/rancher/31611/5/2

**Comment by rohitsakala** [comment]
Closing this as we didn't see any recent failures on this test case. the last one reported was in drone in 2023.
