### ISSUE TITLE
[flaky-test] TestProjectUserTestSuite

### ISSUE THREAD

**Issue by nicholasSUSE** [rancher/rancher#42630]
**Flaky Test**

TestProjectUserTestSuite/TestCreateNamespaceProjectMember

**Release Branch**
source branch of PR: `release/v2.8`

**Drone Build (if applicable)**
https://drone-pr.rancher.io/rancher/rancher/32220/5/2

**Comment by nicholasSUSE** [comment]
Another build with the same problem:
https://drone-pr.rancher.io/rancher/rancher/32865/6/2

**Comment by nicholasSUSE** [comment]
@igomez06 can you please take a look at this?

**Comment by nicholasSUSE** [comment]
=== RUN   TestProjectUserTestSuite/TestCreateNamespaceProjectMember
    project_user_test.go:82: 
        	Error Trace:	/go/src/github.com/rancher/rancher/tests/v2/integration/projects/project_user_test.go:82
        	Error:      	Received unexpected error:
        	            	Resource type [namespace] is not creatable
        	            	github.com/rancher/rancher/tests/framework/pkg/clientbase.(*APIOperations).DoCreate
        	            		/go/src/github.com/rancher/rancher/tests/framework/pkg/clientbase/ops.go:197
        	            	github.com/rancher/rancher/tests/framework/clients/rancher/v1.(*SteveClient).Create
        	            		/go/src/github.com/rancher/rancher/tests/framework/clients/rancher/v1/client.go:175
        	            	github.com/rancher/rancher/tests/framework/extensions/namespaces.CreateNamespace
        	            		/go/src/github.com/rancher/rancher/tests/framework/extensions/namespaces/create.go:56
        	            	github.com/rancher/rancher/tests/v2/integration/projects.(*ProjectUserTestSuite).TestCreateNamespaceProjectMember
        	            		/go/src/github.com/rancher/rancher/tests/v2/integration/projects/project_user_test.go:81
        	            	reflect.Value.call
        	            		/usr/lib64/go/1.19/src/reflect/value.go:584
        	            	reflect.Value.Call
        	            		/usr/lib64/go/1.19/src/reflect/value.go:368
        	            	github.com/stretchr/testify/suite.Run.func1
        	            		/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:197
        	            	testing.tRunner
        	            		/usr/lib64/go/1.19/src/testing/testing.go:1446
        	            	runtime.goexit
        	            		/usr/lib64/go/1.19/src/runtime/asm_arm64.s:1172
        	Test:       	TestProjectUserTestSuite/TestCreateNamespaceProjectMember
    suite.go:87: test panicked: runtime error: invalid memory address or nil pointer dereference
        goroutine 33 [running]:
        runtime/debug.Stack()
        	/usr/lib64/go/1.19/src/runtime/debug/stack.go:24 +0x64
        github.com/stretchr/testify/suite.failOnPanic(0x400119e340, {0x183c460, 0x3216860})
        	/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:87 +0x34
        github.com/stretchr/testify/suite.Run.func1.1()
        	/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:183 +0x1f4
        panic({0x183c460, 0x3216860})
        	/usr/lib64/go/1.19/src/runtime/panic.go:884 +0x20c
        github.com/rancher/rancher/tests/v2/integration/projects.(*ProjectUserTestSuite).TestCreateNamespaceProjectMember(0x400061ae40)
        	/go/src/github.com/rancher/rancher/tests/v2/integration/projects/project_user_test.go:83 +0x1e4
        reflect.Value.call({0x400061bd40?, 0x40000114e0?, 0x13?}, {0x1bb95a8, 0x4}, {0x400009be68, 0x1, 0x1?})
        	/usr/lib64/go/1.19/src/reflect/value.go:584 +0x688
        reflect.Value.Call({0x400061bd40?, 0x40000114e0?, 0x400061ae40?}, {0x4000506e68?, 0x126123?, 0x2b5aaa8?})
        	/usr/lib64/go/1.19/src/reflect/value.go:368 +0x90
        github.com/stretchr/testify/suite.Run.func1(0x400119e340)
        	/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:197 +0x3f8
        testing.tRunner(0x400119e340, 0x4000b0b4d0)
        	/usr/lib64/go/1.19/src/testing/testing.go:1446 +0x10c
        created by testing.(*T).Run
        	/usr/lib64/go/1.19/src/testing/testing.go:1493 +0x328
--- FAIL: TestProjectUserTestSuite (3.52s)
    --- FAIL: TestProjectUserTestSuite/TestCreateNamespaceProjectMember (2.63s)
FAIL
FAIL	github.com/rancher/rancher/tests/v2/integration/projects	3.547s
