### ISSUE TITLE
[BUG] Rancher pods in panic loop after downstream cluster nodes were deleted

### ISSUE THREAD

**Issue by nickwsuse** [rancher/rancher#43003]
**Rancher Server Setup**
- Rancher version: `v2.8-head and v2.8.0-alpha1`
- Installation option (Docker install/Helm Chart): `Helm`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE1`
- Proxy/Cert Details: `byo-valid`

**Information about the Cluster**
- Kubernetes version: `v1.27.6`
- Cluster Type (Local/Downstream): `Local`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): `AWS EC2`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): `Admin`
 
**Describe the bug**
After the nodes for my two downstream clusters were deleted (by the AWS auto-cleanup that cleaned up a bit too early...), my local Rancher cluster is stuck in a panic loop and will work for some time, but then crash again and give a 503 in the browser.

Panic Specific Logs:
```
2023/09/28 20:36:01 [INFO] Watching metadata for rke-machine-config.cattle.io/v1, Kind=Amazonec2Config
2023/09/28 20:36:01 [INFO] Starting cluster.x-k8s.io/v1alpha3, Kind=MachineDeployment controller
2023/09/28 20:36:01 [INFO] [planner] rkecluster fleet-default/nickeks-rke2: force deleting etcd machine fleet-default/nickeks-rke2-e-66887fb7cxjcw4h-tvl4s as cluster was not sane and machine was deleting
E0928 20:36:01.758187      32 runtime.go:79] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
goroutine 10593 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x42dd320?, 0x571dd30})
	/go/pkg/mod/k8s.io/apimachinery@v0.27.4/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc008c09680?})
	/go/pkg/mod/k8s.io/apimachinery@v0.27.4/pkg/util/runtime/runtime.go:49 +0x75
panic({0x42dd320, 0x571dd30})
	/usr/lib64/go/1.20/src/runtime/panic.go:884 +0x213
github.com/rancher/rancher/pkg/capr/planner.(*Planner).forceDeleteAllDeletingEtcdMachines(0xc006b6ac80, 0xc007568000, 0x431ba40?)
	/go/src/github.com/rancher/rancher/pkg/capr/planner/etcdrestore.go:722 +0x43d
github.com/rancher/rancher/pkg/capr/planner.(*Planner).Process(_, _, {0x0, {0xc00663d860, 0x5, 0x5}, 0x0, 0x1, 0x0, 0x0, ...})
	/go/src/github.com/rancher/rancher/pkg/capr/planner/planner.go:288 +0x1578
github.com/rancher/rancher/pkg/controllers/capr/planner.(*handler).OnChange(_, _, {0x0, {0xc00663d860, 0x5, 0x5}, 0x0, 0x1, 0x0, 0x0, ...})
	/go/src/github.com/rancher/rancher/pkg/controllers/capr/planner/controller.go:92 +0x2cb
github.com/rancher/rancher/pkg/generated/controllers/rke.cattle.io/v1.(*rKEControlPlaneStatusHandler).sync(0xc0020c99e0, {0x0?, 0xc004c8ab88?}, 0xc004d77000)
	/go/src/github.com/rancher/rancher/pkg/generated/controllers/rke.cattle.io/v1/rkecontrolplane.go:92 +0x15c
github.com/rancher/wrangler/pkg/generic.FromObjectHandlerToHandler[...].func1({0x573e348?, 0xc004d77000?})
	/go/pkg/mod/github.com/rancher/wrangler@v1.1.1-0.20230831050635-df1bd5aae9df/pkg/generic/controller.go:169 +0x4e
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0x4c18480?, {0xc009161480?, 0x4d75de9?}, {0x573e348?, 0xc004d77000?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc004324a50, {0xc009161480, 0x1a}, {0x573e348, 0xc004d77000})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/sharedhandler.go:75 +0x218
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc007491600, {0xc009161480, 0x1a})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/controller.go:232 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc007491600, {0x3f8a880?, 0xc008c09680?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/controller.go:213 +0x105
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc007491600)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/controller.go:190 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/controller.go:179
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	/go/pkg/mod/k8s.io/apimachinery@v0.27.4/pkg/util/wait/backoff.go:226 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x20736e6961746e6f?, {0x572b7c0, 0xc00e313530}, 0x1, 0xc0018bac60)
	/go/pkg/mod/k8s.io/apimachinery@v0.27.4/pkg/util/wait/backoff.go:227 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc010f9ffb0?, 0x3b9aca00, 0x0, 0x0?, 0x4432c5?)
	/go/pkg/mod/k8s.io/apimachinery@v0.27.4/pkg/util/wait/backoff.go:204 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x96a46a?, 0x0?, 0xc010f9ff58?)
	/go/pkg/mod/k8s.io/apimachinery@v0.27.4/pkg/util/wait/backoff.go:161 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/controller.go:147 +0x2d5
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map

goroutine 10593 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc008c09680?})
	/go/pkg/mod/k8s.io/apimachinery@v0.27.4/pkg/util/runtime/runtime.go:56 +0xd7
panic({0x42dd320, 0x571dd30})
	/usr/lib64/go/1.20/src/runtime/panic.go:884 +0x213
github.com/rancher/rancher/pkg/capr/planner.(*Planner).forceDeleteAllDeletingEtcdMachines(0xc006b6ac80, 0xc007568000, 0x431ba40?)
	/go/src/github.com/rancher/rancher/pkg/capr/planner/etcdrestore.go:722 +0x43d
github.com/rancher/rancher/pkg/capr/planner.(*Planner).Process(_, _, {0x0, {0xc00663d860, 0x5, 0x5}, 0x0, 0x1, 0x0, 0x0, ...})
	/go/src/github.com/rancher/rancher/pkg/capr/planner/planner.go:288 +0x1578
github.com/rancher/rancher/pkg/controllers/capr/planner.(*handler).OnChange(_, _, {0x0, {0xc00663d860, 0x5, 0x5}, 0x0, 0x1, 0x0, 0x0, ...})
	/go/src/github.com/rancher/rancher/pkg/controllers/capr/planner/controller.go:92 +0x2cb
github.com/rancher/rancher/pkg/generated/controllers/rke.cattle.io/v1.(*rKEControlPlaneStatusHandler).sync(0xc0020c99e0, {0x0?, 0xc004c8ab88?}, 0xc004d77000)
	/go/src/github.com/rancher/rancher/pkg/generated/controllers/rke.cattle.io/v1/rkecontrolplane.go:92 +0x15c
github.com/rancher/wrangler/pkg/generic.FromObjectHandlerToHandler[...].func1({0x573e348?, 0xc004d77000?})
	/go/pkg/mod/github.com/rancher/wrangler@v1.1.1-0.20230831050635-df1bd5aae9df/pkg/generic/controller.go:169 +0x4e
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0x4c18480?, {0xc009161480?, 0x4d75de9?}, {0x573e348?, 0xc004d77000?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc004324a50, {0xc009161480, 0x1a}, {0x573e348, 0xc004d77000})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/sharedhandler.go:75 +0x218
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc007491600, {0xc009161480, 0x1a})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/controller.go:232 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc007491600, {0x3f8a880?, 0xc008c09680?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/controller.go:213 +0x105
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc007491600)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/controller.go:190 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/controller.go:179
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	/go/pkg/mod/k8s.io/apimachinery@v0.27.4/pkg/util/wait/backoff.go:226 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x20736e6961746e6f?, {0x572b7c0, 0xc00e313530}, 0x1, 0xc0018bac60)
	/go/pkg/mod/k8s.io/apimachinery@v0.27.4/pkg/util/wait/backoff.go:227 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc010f9ffb0?, 0x3b9aca00, 0x0, 0x0?, 0x4432c5?)
	/go/pkg/mod/k8s.io/apimachinery@v0.27.4/pkg/util/wait/backoff.go:204 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x96a46a?, 0x0?, 0xc010f9ff58?)
	/go/pkg/mod/k8s.io/apimachinery@v0.27.4/pkg/util/wait/backoff.go:161 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/controller.go:147 +0x2d5
```

I'v added the DoNotDelete tags to the local nodes so they won't get auto-deleted if any additional logs or info is needed.

**To Reproduce**
1. Provision an HA cluster using v2.8.0-alpha1 chart and v2.8-head image
2. Provision a downstream RKE1 cluster (3w, 2c, 3e)
3. Provision a downstream RKE2 cluster (3w, 2c, 3e)
4. Once the clusters are fully provisioned, delete the nodes for each of the clusters (not the clusters themselves, just the nodes)

**Result**
Rancher pod on local cluster goes into a panic loop

**Expected Result**
Rancher pod doesn't crash

**Additional context**
This setup was provisioned yesterday 9/28 and the overnight AWS cleanup job prematurely deleted the downstream nodes, leaving the clusters themselves in an error state

**Comment by susesgartner** [comment]
Ticket #43003 - Test Results - ✅ 
---
Verified with HA Helm on Rancher v2.8-head:

Steps:
1. Provision an HA cluster using v2.8.0-alpha1 chart and v2.8-head image
2. Provision a downstream RKE1 cluster (3w, 2c, 3e)
3. Provision a downstream RKE2 cluster (3w, 2c, 3e)
4. After the clusters come up delete the nodes from the AWS side.

Result: The rancher pod remains in a stable state and both downstream clusters go into an error state.
