### ISSUE TITLE
[BUG] helm-operation panics while installing charts on hosted clusters

### ISSUE THREAD

**Issue by rishabhmsra** [rancher/rancher#43197]
**Rancher Server Setup**
- Rancher version: v2.8-head(ac63e3a)
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):

**Information about the Cluster**
- Kubernetes version: AKS v1.27.3 or GKE v1.27.3 -gke.100
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Hosted (AKS or GKE)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**

- While installing rancher-alerting-driver chart on hosted AKS or GKE cluster, helm-operation fails with below error:
```
helm install --namespace=cattle-monitoring-system --timeout=10m0s --values=/home/shell/helm/values-rancher-alerting-drivers-103.0.0.yaml --version=103.0.0 --wait=true rancher-alerting-drivers /home/shell/helm/rancher-alerting-drivers-103.0.0.tgz
2023-10-18T12:12:21.193695722Z panic: runtime error: invalid memory address or nil pointer dereference
2023-10-18T12:12:21.193733523Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13a7e50]
2023-10-18T12:12:21.193737723Z 
goroutine 1 [running]:
k8s.io/client-go/discovery.convertAPIResource(...)
2023-10-18T12:12:21.193748623Z 	k8s.io/client-go@v0.26.2/discovery/aggregated_discovery.go:88
2023-10-18T12:12:21.193768923Z k8s.io/client-go/discovery.convertAPIGroup({{{0x0, 0x0}, {0x0, 0x0}}, {{0xc0007c71b8, 0x15}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
2023-10-18T12:12:21.193772523Z 	k8s.io/client-go@v0.26.2/discovery/aggregated_discovery.go:69 +0x5f0
2023-10-18T12:12:21.193776223Z k8s.io/client-go/discovery.SplitGroupsAndResources({{{0xc0007c6030, 0x15}, {0xc000368020, 0x1b}}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
2023-10-18T12:12:21.193779623Z 	k8s.io/client-go@v0.26.2/discovery/aggregated_discovery.go:35 +0x2f8
2023-10-18T12:12:21.193782823Z k8s.io/client-go/discovery.(*DiscoveryClient).downloadAPIs(0xc0007bee10?)
2023-10-18T12:12:21.193786123Z 	k8s.io/client-go@v0.26.2/discovery/discovery_client.go:310 +0x47c
2023-10-18T12:12:21.193789423Z k8s.io/client-go/discovery.(*DiscoveryClient).GroupsAndMaybeResources(0x1?)
2023-10-18T12:12:21.193792523Z 	k8s.io/client-go@v0.26.2/discovery/discovery_client.go:198 +0x5c
2023-10-18T12:12:21.193796223Z k8s.io/client-go/discovery/cached/memory.(*memCacheClient).refreshLocked(0xc00030b680)
	k8s.io/client-go@v0.26.2/discovery/cached/memory/memcache.go:222 +0x57
2023-10-18T12:12:21.193802824Z k8s.io/client-go/discovery/cached/memory.(*memCacheClient).GroupsAndMaybeResources(0xc00030b680)
2023-10-18T12:12:21.193805924Z 	k8s.io/client-go@v0.26.2/discovery/cached/memory/memcache.go:128 +0xc5
2023-10-18T12:12:21.193812624Z k8s.io/client-go/discovery/cached/memory.(*memCacheClient).ServerGroups(0xc0001014f0?)
2023-10-18T12:12:21.193815924Z 	k8s.io/client-go@v0.26.2/discovery/cached/memory/memcache.go:148 +0x19
2023-10-18T12:12:21.193819124Z k8s.io/client-go/discovery/cached/disk.(*CachedDiscoveryClient).ServerGroups(0xc0001014f0)
2023-10-18T12:12:21.193822124Z 	k8s.io/client-go@v0.26.2/discovery/cached/disk/cached_discovery.go:118 +0x172
2023-10-18T12:12:21.193825224Z k8s.io/client-go/discovery.ServerGroupsAndResources({0x221c498, 0xc0001014f0})
2023-10-18T12:12:21.193828224Z 	k8s.io/client-go@v0.26.2/discovery/discovery_client.go:397 +0xc8
2023-10-18T12:12:21.193831424Z k8s.io/client-go/discovery/cached/disk.(*CachedDiscoveryClient).ServerGroupsAndResources(0x0?)
	k8s.io/client-go@v0.26.2/discovery/cached/disk/cached_discovery.go:101 +0x25
2023-10-18T12:12:21.193837624Z helm.sh/helm/v3/pkg/action.GetVersionSet({0x7fb644ea79f8?, 0xc0001014f0?})
2023-10-18T12:12:21.193858624Z 	helm.sh/helm/v3/pkg/action/action.go:317 +0x42
2023-10-18T12:12:21.193862124Z helm.sh/helm/v3/pkg/action.(*Configuration).getCapabilities(0xc000123b00)
2023-10-18T12:12:21.193867424Z 	helm.sh/helm/v3/pkg/action/action.go:263 +0x97
2023-10-18T12:12:21.193871424Z helm.sh/helm/v3/pkg/action.(*Install).RunWithContext(0xc000176f20, {0x2212460?, 0xc0002f82c0}, 0x2?, 0x0?)
2023-10-18T12:12:21.193875124Z 	helm.sh/helm/v3/pkg/action/install.go:241 +0x625
2023-10-18T12:12:21.193878324Z main.runInstall({0xc000547490?, 0x2, 0x7}, 0xc000176f20, 0x0?, {0x21f97a0?, 0xc00011c008})
2023-10-18T12:12:21.193881725Z 	helm.sh/helm/v3/cmd/helm/install.go:281 +0x871
2023-10-18T12:12:21.193898125Z main.newInstallCmd.func2(0xc0005c1800?, {0xc000547490?, 0x7?, 0x7?})
2023-10-18T12:12:21.193901625Z 	helm.sh/helm/v3/cmd/helm/install.go:139 +0x51
2023-10-18T12:12:21.193904825Z github.com/spf13/cobra.(*Command).execute(0xc0005c1800, {0xc000547420, 0x7, 0x7})
2023-10-18T12:12:21.193908025Z 	github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
2023-10-18T12:12:21.193911325Z github.com/spf13/cobra.(*Command).ExecuteC(0xc00057b200)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
2023-10-18T12:12:21.193938325Z github.com/spf13/cobra.(*Command).Execute(...)
2023-10-18T12:12:21.193941725Z 	github.com/spf13/cobra@v1.6.1/command.go:968
2023-10-18T12:12:21.193944725Z main.main()
2023-10-18T12:12:21.193947925Z 	helm.sh/helm/v3/cmd/helm/helm.go:83 +0x235
```

**Note:** 
- Observed panic while installing alerting driver or OPA gatekeeper chart on AKS and GKE clusters. This issue did not occur on EKS `v1.27.6 -f8587cb` k8s cluster.
- Also observed panic while upgrading monitoring from `102.0.2+up40.1.2` to `103.0.0+up45.31.1`

**To Reproduce**

- Create docker rancher server v2.8-head(ac63e3a)
- Create hosted AKS `v1.27.3` or GKE `v1.27.3 -gke.100` cluster.
- Goto Apps -> Charts -> install Monitoring chart version `103.0.0+up45.31.1`
- Now install Alerting Drivers chart version `103.0.0` in cattle-monitoring-system namespace, observe the panic in helm-operation.

**Result**
- Chart installation fails due to panic in helm-operation

**Expected Result**

- Chart installation should be successful.

**Additional context**

- Similar issue is logged : https://github.com/rancher/rancher/issues/43183

**Comment by sowmyav27** [comment]
Same as https://github.com/rancher/rancher/issues/43183

**Comment by rohitsakala** [comment]
@rishabhmsra Can you test using these container images 

1. rohitsakala/rancher:fixed 
2. rohitsakala/rancher-agent:fixed1

I tested it and I couldn't reproduce using the above images. 
Can you test and confirm? so that I can merge PRs and release things.

Thanks 👍🏽

**Comment by rishabhmsra** [comment]
On rancher v2.8-head(136e9cc), provisioned EKS, AKS and GKE v1.27 clusters and validated it - issue is resolved hence closing it.
