### ISSUE TITLE
[BUG] bootstrap waiting for cluster agent to connect

### ISSUE THREAD

**Issue by jakobmolandergeus** [rancher/rancher#43215]
Hi

I'm trying to create a new k3s cluster using the system-agent script provided by the Rancher install.

When provisioning the etcd and Control Plane Node gets stuck on "waiting for cluster agent to connect":
<img width="1123" alt="Cluster" src="https://github.com/rancher/rancher/assets/26303145/90a9e0c3-3a13-4bc0-a19e-dfd497e7ce05">

Log from the Worker Node:
[Worker.log](https://github.com/rancher/rancher/files/13042212/Worker.log)

Log from the etcd and Control Plane Node:
[Controller.log](https://github.com/rancher/rancher/files/13042218/Controller.log)

The certificate file mentioned in the log does exist on the server.

I have bootstrapped a similar setup before without problems.

Can anyone tell me what the problem is and how to fix it?

Hosts: Ubuntu Server 22.04.2 LTS
Containerd Version: 1.6.22
Docker version 24.0.5
Kubernetes Version: v.1.26.8+k3s1

Thank you in advance.

**Comment by NosIreland** [comment]
Have same issue but with RKE2.
The only way to make it work is to provision first node with all 3 roles etc, control plane and worker. But removing the node that node afterwards seems to break something.
Kubernetes version does not make any difference here. I'm running rancher v2.7.6. The same as OP I had not problems creating clusters before.

**Comment by jakobmolandergeus** [comment]
@NosIreland: Retried from scratch having the Control Plane Node also as a Worker, but got stuck at the same place: waiting for cluster agent to connect

**Comment by Richardswe** [comment]
Hi, same here it doesn't matter if the first node has all 3 roles. my spec:
Rancher version: 2.7.6
Rancher upstream cluster: rke2 v.1.25.12rke2r1

Downstream provisioning 
Hosts: Ubuntu Server 22.04.2 LTS
CNI: Calico 
Kubernetes Version: v.1.25.13+rke2r1

The above worked in previous version, i ran (2.7.3) 
Hard to use Rancher in production when there are all these issues.

**Comment by NosIreland** [comment]
The setup that I'm trying at the moment
Rancher version: 2.7.6
Hosts: Ubuntu Server 22.04.2 LTS
CNI: Canal
Kubernetes Version: v.1.25.13+rke2r1
Even though I can get nodes into cluster with first one holding all 3 roles but it is still not working properly. Fleet-agent is in constant reboot loop with:

```
I1024 20:02:57.669525       1 leaderelection.go:248] attempting to acquire leader lease cattle-fleet-system/fleet-agent-lock...
2023-10-24T20:02:57.677306041Z I1024 20:02:57.677235       1 leaderelection.go:258] successfully acquired lease cattle-fleet-system/fleet-agent-lock
2023-10-24T20:02:57.678450758Z time="2023-10-24T20:02:57Z" level=warning msg="Cannot find fleet-agent secret, running registration"
panic: assignment to entry in nil map

goroutine 65 [running]:
github.com/rancher/fleet/internal/cmd/agent/register.createAgentSecret({0x2b21500, 0xc0005b1770}, {0x0, 0x0}, {0x2b2dd90, 0xc0004a9390}, 0xc0001388c0)
2023-10-24T20:02:58.172842824Z 	/go/src/github.com/rancher/fleet/internal/cmd/agent/register/register.go:174 +0x3dc
github.com/rancher/fleet/internal/cmd/agent/register.runRegistration({0x2b21500, 0xc0005b1770}, {0x2b2dd90?, 0xc0004a9390?}, {0xc00005800a, 0x13}, {0x0, 0x0})
	/go/src/github.com/rancher/fleet/internal/cmd/agent/register/register.go:118 +0x1af
github.com/rancher/fleet/internal/cmd/agent/register.tryRegister({0x2b21500, 0xc0005b1770}, {0xc00005800a, 0x13}, {0x0, 0x0}, 0x100c000010000?)
	/go/src/github.com/rancher/fleet/internal/cmd/agent/register/register.go:81 +0x325
github.com/rancher/fleet/internal/cmd/agent/register.Register({0x2b21500, 0xc0005b1770}, {0xc00005800a, 0x13}, {0x0, 0x0}, 0x0?)
	/go/src/github.com/rancher/fleet/internal/cmd/agent/register/register.go:53 +0x97
github.com/rancher/fleet/internal/cmd/agent.start.func1({0x2b21500, 0xc0005b1770})
	/go/src/github.com/rancher/fleet/internal/cmd/agent/start.go:58 +0x9e
created by github.com/rancher/wrangler/pkg/leader.run.func1
	/go/pkg/mod/github.com/rancher/wrangler@v1.1.1/pkg/leader/leader.go:58 +0x98
```
Also if I reboot the first node that joined the cluster with all 3 roles I cannot managed cluster properly. I cannot even create namespaces.
It is really disappointing. we've been using rancher for 2 years but never had such problems.

**Comment by jakobmolandergeus** [comment]
I tried reverting to a "last know good" combination: 

* Rancher v2.7.3
* Kubernetes v1.25.13-k3s1
 
I have an existing cluster running with those versions on similar hardware, but I got the exact same result when bootstrapping:

Log from the worker Node:

[Worker.log](https://github.com/rancher/rancher/files/13162451/Worker.log)

Log from the etcd and Control Plane Node:

[Controller.log](https://github.com/rancher/rancher/files/13162452/Controller.log)

Could a developer please take  look at this? 

It's frustrating when "known good" does not work either.

Thank you in advance.

**Comment by Richardswe** [comment]
@jakobmolandergeus  Rancher 2.7.3 has problems too. I got bad memory leak in cattle-agent pod.  I'm no developer but i will look at your problem when i got time.

**Comment by jakobmolandergeus** [comment]
I have just tried once more, with the same result. This time with:

* Hosts: Ubuntu Server 22.04.3 LTS
* Containerd:: 1.6.24
* Docker: 24.0.7
* Rancher: v2.7.9
* Kubernetes : v.1.26.8+k3s1

Log from Worker Node:

[Worker.log](https://github.com/rancher/rancher/files/13203167/Worker.log)

Log from etcd and Control Plane Node:

[Controller.log](https://github.com/rancher/rancher/files/13203171/Controller.log)

**Comment by ryanrca** [comment]
+1

**Comment by Richardswe** [comment]
Well okay, my mistake. It do work for me with Rancher 2.7.6. Just make sure that your nodes are 100 % clean from old RKE2/k8s installation.

**Comment by femtonelson** [comment]
Thanks @Richardswe for your comment. Indeed k3s provisioning failed with Rancher 2.7.9 and 2.8.0. With **Rancher 2.7.6** however, the cluster agent connects properly with **k3s v1.26.11+k3s2** and provisioning is successful.
Hardware for k3s : Raspberry Pi 4 Model B Rev 1.5 (cat /sys/firmware/devicetree/base/model), OS : Raspbian GNU/Linux 11

**Comment by gb-123-git** [comment]
+1
