### ISSUE TITLE
 memcache.go:265] couldn't get current server API group list: Get "https://xxxx.in/k8s/clusters/c-phll6/api?timeout=32s": tls: failed to verify certificate: x509: certificate signed by unknown authority Unable to connect to the server: tls: failed to verify certificate: x509: certificate signed by unknown authority[BUG]

### ISSUE THREAD

**Issue by sonia-pria** [rancher/rancher#44624]
I have installed a kubernetes cluster in Rancher. 
Kubelet .service is inactive
we are not able to connect  to Api-server
Kindly help

**Comment by sonia-pria** [comment]
kubectl describe kubelet
E0301 11:53:54.669942   16235 memcache.go:265] couldn't get current server API group list: Get "https://ranchert.cdot.in/k8s/clusters/c-phll6/api?timeout=32s": tls: failed to verify certificate: x509: certificate signed by unknown authority

**Comment by sonia-pria** [comment]
systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; disabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2024-03-01 12:17:45 IST; 8s ago
     Docs: https://kubernetes.io/docs/
  Process: 12664 ExecStart=/usr/bin/kubelet (code=exited, status=255)
 Main PID: 12664 (code=exited, status=255)

Mar 01 12:17:45 kubertm1.cdot.in kubelet[12664]: goroutine 119 [chan receive]:
Mar 01 12:17:45 kubertm1.cdot.in kubelet[12664]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch.(*Broadcaster).loop(0xc000111740)
Mar 01 12:17:45 kubertm1.cdot.in kubelet[12664]: /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch/mux.go:219 +0x66
Mar 01 12:17:45 kubertm1.cdot.in kubelet[12664]: created by k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch.NewBroadcaster
Mar 01 12:17:45 kubertm1.cdot.in kubelet[12664]: /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch/mux.go:73 +0xf7
Mar 01 12:17:45 server_name> kubelet[12664]: goroutine 120 [chan receive]:
Mar 01 12:17:45<server_name> kubelet[12664]: k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1(0x4f39760, 0xc000c42e10, 0xc000191380)
Mar 01 12:17:45  kubelet[12664]: /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record/event.go:301 +0xaa
Mar 01 12:17:45 kubertm1.cdot.in kubelet[12664]: created by k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher
Mar 01 12:17:45  kubelet[12664]: /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record/event.go:299 +0x6e
