### ISSUE TITLE
[BUG] Rancher CLI panics when trying to kubectl after a login 

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#44811]
**Rancher Server Setup**
- Rancher version: 2.8.3-rc1
- Installation option: Rancher HA - rke1 local

**Describe the bug**
When trying to get rancher current server context before logging in, rancher cli panics.

**Steps to reproduce**
1. Configure 2.8.0 rancher cli version
2. Created a rancher server on 2.8-head **c4743**
3. On the UI, set kubeconfig-generate-token = false from the global settings.
4. Using the rancher cli, run the following commands and notice rancher panics:
5. Run `~/Downloads/rancher-v2.8.0/rancher server current` 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x15eeda9]

goroutine 1 [running]:
github.com/rancher/cli/cmd.serverCurrent(0xc0002fe2c0?)
	/go/src/github.com/rancher/cli/cmd/server.go:74 +0xc9
github.com/urfave/cli.HandleAction({0x167e940?, 0x17fd848?}, 0x7?)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0x50
github.com/urfave/cli.Command.Run({{0x17ab715, 0x7}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x17b97d8, 0x1a}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x65b
github.com/urfave/cli.(*App).RunAsSubcommand(0xc0001b0fc0, 0xc0002fe000)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405 +0x91b
github.com/urfave/cli.Command.startApp({{0x17aac5c, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x17b8bdc, 0x19}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372 +0x6e7
github.com/urfave/cli.Command.Run({{0x17aac5c, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x17b8bdc, 0x19}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102 +0x825
github.com/urfave/cli.(*App).Run(0xc0001b0e00, {0xc00012b400, 0x3, 0x4})
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x8a7
main.mainErr()
	/go/src/github.com/rancher/cli/main.go:124 +0x1e66
main.main()
	/go/src/github.com/rancher/cli/main.go:56 +0x19
```

**Comment by anupama2501** [comment]
PR: https://github.com/rancher/cli/pull/350

**Comment by anupama2501** [comment]
This has been validated on a 2.8.3-rc1 rancher cli and 2.8.3-rc1 rancher server version:
Verified on rancher cli 2.8.3-rc1, when no configuration exists, rancher does not panic:

`FATA[0000] Current server not set`

Once the user logins in as follows, config is saved:

 ~/Downloads/rancher-v2.8.3-rc1/rancher login https://<redacted> --token token-<redacted> --name  <RancherIP>
