### ISSUE TITLE
No internet access on agent container

### ISSUE THREAD

**Issue by JaviSabalete** [rancher/rancher#4483]
Rancher Version: 1.0.0

Agent Version: 0.11.0

Docker Version: 1.11.0

OS: Debian 8.3 Jessie

Steps to Reproduce: Fresh install server (machine A), set local auth, click Add host, copy to clipboard.
Paste (machine B)

Results: 
INFO: Attempting to connect to: http://MACHINE_A/v1
ERROR: http://MACHINE_A/v1 is not accessible
ERROR: http://MACHINE_A/v1 is not accessible
ERROR: http://MACHINE_A/v1 is not accessible
ERROR: http://MACHINE_A/v1 is not accessible
ERROR: http://MACHINE_A/v1 is not accessible
ERROR: http://MACHINE_A/v1 is not accessible
ERROR: http://MACHINE_A/v1 is not accessible
......

Expected:
accesible

Test:
docker exec -ti DOCKERID bash
test ping, curls and others commands no internet access. Not working

**Comment by JaviSabalete** [comment]
Well, this happens when host was delete and added again

**Comment by JaviSabalete** [comment]
Again...

DNS problem, with ip get other error


Traceback (most recent call last):
  File "./register.py", line 11, in <module>
    secret_key=os.environ['CATTLE_REGISTRATION_SECRET_KEY'])
  File "/usr/local/lib/python2.7/site-packages/cattle.py", line 45, in from_env
    return gdapi.from_env(prefix=prefix, factory=Client, **kw)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 608, in from_env
    return _from_env(prefix=prefix, factory=factory, **args)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 627, in _from_env
    return factory(**result)
  File "/usr/local/lib/python2.7/site-packages/cattle.py", line 12, in __init__
    super(Client, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 195, in __init__
    self._load_schemas()
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 313, in _load_schemas
    response = self._get_response(self._url)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 262, in _get_response
    headers=self._headers)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='HOST', port=80): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f027f967410>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by JaviSabalete** [comment]
HOST problem

**Comment by yasahmed** [comment]
did resolve the problem ?
