### ISSUE TITLE
Start rancher agent failed

### ISSUE THREAD

**Issue by oema** [rancher/rancher#4498]
Hi,

I try to install a latest version of rancher. When I launch the command to start rancher agent, I have this error 
```
INFO: Running registration
Traceback (most recent call last):
  File "./register.py", line 11, in <module>
    secret_key=os.environ['CATTLE_REGISTRATION_SECRET_KEY'])
  File "/usr/local/lib/python2.7/site-packages/cattle.py", line 45, in from_env
    return gdapi.from_env(prefix=prefix, factory=Client, **kw)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 608, in from_env
    return _from_env(prefix=prefix, factory=factory, **args)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 627, in _from_env
    return factory(**result)
  File "/usr/local/lib/python2.7/site-packages/cattle.py", line 12, in __init__
    super(Client, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 195, in __init__
    self._load_schemas()
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 313, in _load_schemas
    response = self._get_response(self._url)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 262, in _get_response
    headers=self._headers)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fcbddc69550>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

Rancher Version: 1.0.1

Docker Version: 1.10.3

Agent version : 1.0.1

**Comment by vrince** [comment]
Kind of the same here (following the quick start guide) and I got : 

    INFO: Running registration
    Traceback (most recent call last):
    File "./register.py", line 11, in <module>
        secret_key=os.environ['CATTLE_REGISTRATION_SECRET_KEY'])
    File "/usr/local/lib/python2.7/site-packages/cattle.py", line 45, in from_env
        return gdapi.from_env(prefix=prefix, factory=Client, **kw)
    File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 608, in from_env
        return _from_env(prefix=prefix, factory=factory, **args)
    File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 627, in _from_env
        return factory(**result)
    File "/usr/local/lib/python2.7/site-packages/cattle.py", line 12, in __init__
        super(Client, self).__init__(*args, **kw)
    File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 195, in __init__
        self._load_schemas()
    File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 313, in _load_schemas
        response = self._get_response(self._url)
    File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 264, in _get_response
        self._error(r.text)
    File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 253, in _error
        raise ApiError(self._unmarshall(text))
    File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 298, in _unmarshall
        object_pairs_hook=self.object_pairs_hook)
    File "/usr/local/lib/python2.7/json/__init__.py", line 352, in loads
        return cls(encoding=encoding, **kw).decode(s)
    File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    File "/usr/local/lib/python2.7/json/decoder.py", line 382, in raw_decode
        raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded

Fresh pull Rancher 1.0.1 server/agent
Docker 1.10.3

**Comment by deniseschannon** [comment]
@oema How are you trying to add rancher/agent? Is it a separate host or is rancher/server running on it? 

What OS are you using?

Have you looked at the docs about Rancher agent?
http://docs.rancher.com/rancher/faqs/agents/

**Comment by deniseschannon** [comment]
@oema If you can provide more details, please re-open.

**Comment by besishblia** [comment]
Hello. I got same exception as @vrince 
Baremetal server with VWare virtualisation
OS: rancheros v0.6.1
Latest stable rancher server  v1.1.4
Rancher agent on same host as server, v1.0.2
docker v1.12.1

readed http://docs.rancher.com/rancher/faqs/agents/ and settings all right.

No more detail logs in /var/log/rancher/agent.log, no such file, because agent not started.
