### ISSUE TITLE
Can't add node

### ISSUE THREAD

**Issue by Vanuan** [rancher/rancher#4541]
Rancher Version:

v1.0.1

Docker Version:

Docker version 1.11.0, build 4dc5990

OS: 

Ubuntu 14.04

Steps to Reproduce: 

1. Get rancher installed.
2. Go to http://$IP:8080/env/1a5/infra/hosts/add/custom
3. Paste $IP (same ip rancher is running on)
4. ssh to that ip and paste command from ui
5. run `docker logs` to see output

Results: 

```
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_handlers.py", line 32, in execute
    type.on_ping(event, resp)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 125, in on_ping
    self._add_resources(ping, pong)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 272, in _add_resources
    resolved_ip = socket.gethostbyname(DockerConfig.docker_host_ip())
gaierror: [Errno -2] Name or service not known
time="2016-04-24T00:51:09Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=11
```

Host not added

Expected:

No errors, host added

**Comment by Vanuan** [comment]
Ok, accidently pasted http:// along with ip address.
