### ISSUE TITLE
[BUG] install-docker GH action workflow to add new docker versions is failing 

### ISSUE THREAD

**Issue by chiukapoor** [rancher/rancher#45525]
### Issue
* install-docker GH action workflow to add new docker versions is failing  https://github.com/rancher/install-docker/actions/runs/9123329120/job/25085592203

```
+ mkdir ./pkg/26.1.3
+ cd ./pkg/26.1.3
+ curl -Lsk http://get.docker.com/ -o 26.1.3.orig.sh
+ cp -p 26.1.3.orig.sh 26.1.3.sh
+ patch -p1 26.1.3.sh ../v26.1.2/v26.1.2.diff
patch: **** Can't open patch file ../v26.1.2/v26.1.2.diff : No such file or directory
Traceback (most recent call last):
Last added version: v26.1.2
  File "/home/runner/work/install-docker/install-docker/workflow_scripts/gen-new-version-files.py", line 100, in <module>
    main()
  File "/home/runner/work/install-docker/install-docker/workflow_scripts/gen-new-version-files.py", line 85, in main
Formatted new versions:  ['[26](https://github.com/rancher/install-docker/actions/runs/9123329120/job/25085592203#step:7:27).1.3']
executing add-new-version-script with PREVIOUS_ADD_DOCKER_VERSION:  v26.1.2  ADD_DOCKER_VERSION 26.1.3
    generate_diffs(last_added_version, version)
  File "/home/runner/work/install-docker/install-docker/workflow_scripts/gen-new-version-files.py", line 54, in generate_diffs
    subprocess.run(["bash", add_new_version_script_path], check=True, env=env_vars)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bash', './scripts/add-new-version']' returned non-zero exit status 2.
Error: Process completed with exit code 1.
```

* Refactor the "Add new docker versions" workflow to use [semver](https://github.com/python-semver/python-semver) package

**Comment by mitulshah-suse** [comment]
Closing since PR is merged and its automation related change so no need for testing.
