### ISSUE TITLE
[BUG] Enabling shibboleth causes a rancher panic

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#46187]
**Rancher Server Setup**
- Rancher version: v2.9-head `3c4ccdc` 
- Installation option (Docker install/Helm Chart): Docker install and HA 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 `v1.30.2`

**Information about the Cluster**
- Kubernetes version: Local `v1.30.2`
 

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**
Enabling shibboleth on rancher 2.9-head causes a panic and rancher server restarts.

**To Reproduce**
1. Create a rancher server v2.9-head
2. Enable shibboleth auth 

**Result**
Notice rancher restarts and in the rancher logs observer a panic. 

**Expected Result**
No panics expected

**Additional context**
On a rancher HA, rancher pod restarts and on a docker install container restarts. Once rancher is re installed, shibboleth auth is enabled.

```
E0716 15:22:58.853236      41 runtime.go:79] Observed a panic: &reflect.ValueError{Method:"reflect.Value.FieldByName", Kind:0x0} (reflect: call of reflect.Value.FieldByName on zero Value)
goroutine 2498 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x69761a0, 0xc003423890})
	/go/pkg/mod/k8s.io/apimachinery@v0.30.1/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc006791b30?})
	/go/pkg/mod/k8s.io/apimachinery@v0.30.1/pkg/util/runtime/runtime.go:49 +0x6b
panic({0x69761a0?, 0xc003423890?})
	/usr/lib64/go/1.22/src/runtime/panic.go:770 +0x132
reflect.flag.mustBe(...)
	/usr/lib64/go/1.22/src/reflect/value.go:233
reflect.Value.FieldByName({0x0?, 0x0?, 0x0?}, {0x810c5cf?, 0x0?})
	/usr/lib64/go/1.22/src/reflect/value.go:1361 +0x1c8
github.com/rancher/norman/condition.getFieldValue({0x0?, 0x0?, 0x0?}, {0xc0028b5968, 0x1, 0x1})
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20240708202514-a0127673d1b9/condition/condition.go:325 +0x45
github.com/rancher/norman/condition.getValue({0x8087180?, 0xc006ea1128?}, {0xc0028b5958, 0x2, 0x2})
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20240708202514-a0127673d1b9/condition/condition.go:321 +0x148
github.com/rancher/norman/condition.findOrNotCreateCond({0x8087180?, 0xc006ea1128?}, {0x8157eee, 0x15})
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20240708202514-a0127673d1b9/condition/condition.go:277 +0x6a
github.com/rancher/norman/condition.getStatus({0x8087180?, 0xc006ea1128?}, {0x8157eee?, 0xc01232cd56?})
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20240708202514-a0127673d1b9/condition/condition.go:243 +0x26
github.com/rancher/norman/condition.Cond.IsTrue(...)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20240708202514-a0127673d1b9/condition/condition.go:26
github.com/rancher/rancher/pkg/controllers/management/secretmigrator.(*handler).fixShibbolethSecretReference(0xc0022015f0, {0x9060588, 0xc006ea1128})
	/app/pkg/controllers/management/secretmigrator/authconfig.go:90 +0x5f
github.com/rancher/rancher/pkg/controllers/management/secretmigrator.(*handler).syncAuthConfig(0xc0022015f0, {0xc0009d4c40?, 0x803f8a0?}, 0xc0009d4c40?)
	/app/pkg/controllers/management/secretmigrator/authconfig.go:37 +0x107
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*authConfigController).AddHandler.func1({0xc00ed8faf6?, 0x6?}, {0x7fef620?, 0xc00cee3600?})
	/app/pkg/generated/norman/management.cattle.io/v3/zz_generated_auth_config_controller.go:155 +0x3a
github.com/rancher/norman/controller.(*genericController).AddHandler.func1({0xc00ed8faf6, 0xa}, {0x9061ae0, 0xc00cee3600})
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20240708202514-a0127673d1b9/controller/generic_controller.go:57 +0x170
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0x7fef620?, {0xc00ed8faf6?, 0x818cd22?}, {0x9061ae0?, 0xc00cee3600?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240705194423-b2a060d103c1/pkg/controller/sharedcontroller.go:29 +0x32
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc0012e9b80, {0xc00ed8faf6, 0xa}, {0x9061ae0, 0xc002400dc0})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240705194423-b2a060d103c1/pkg/controller/sharedhandler.go:75 +0x202
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc00144d600, {0xc00ed8faf6, 0xa})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240705194423-b2a060d103c1/pkg/controller/controller.go:236 +0x12e
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc00144d600, {0x658f740, 0xc006791b30})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240705194423-b2a060d103c1/pkg/controller/controller.go:217 +0xeb
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc00144d600)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240705194423-b2a060d103c1/pkg/controller/controller.go:194 +0x45
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240705194423-b2a060d103c1/pkg/controller/controller.go:183
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	/go/pkg/mod/k8s.io/apimachinery@v0.30.1/pkg/util/wait/backoff.go:226 +0x33
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00515b810, {0x904da40, 0xc0054fadb0}, 0x1, 0xc0000c9380)
	/go/pkg/mod/k8s.io/apimachinery@v0.30.1/pkg/util/wait/backoff.go:227 +0xaf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00515b810, 0x3b9aca00, 0x0, 0x1, 0xc0000c9380)
	/go/pkg/mod/k8s.io/apimachinery@v0.30.1/pkg/util/wait/backoff.go:204 +0x7f
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.30.1/pkg/util/wait/backoff.go:161
created by github.com/rancher/lasso/pkg/controller.(*controller).run in goroutine 1849
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240705194423-b2a060d103c1/pkg/controller/controller.go:151 +0x2ba
2024/07/16 15:22:58 [TRACE] REST GET apis/management.cattle.io/v3//authconfigs/azuread
panic: reflect: call of reflect.Value.FieldByName on zero Value [recovered]
	panic: reflect: call of reflect.Value.FieldByName on zero Value
goroutine 2498 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc006791b30?})
	/go/pkg/mod/k8s.io/apimachinery@v0.30.1/pkg/util/runtime/runtime.go:56 +0xcd
panic({0x69761a0?, 0xc003423890?})
	/usr/lib64/go/1.22/src/runtime/panic.go:770 +0x132
reflect.flag.mustBe(...)
	/usr/lib64/go/1.22/src/reflect/value.go:233
reflect.Value.FieldByName({0x0?, 0x0?, 0x0?}, {0x810c5cf?, 0x0?})
	/usr/lib64/go/1.22/src/reflect/value.go:1361 +0x1c8
github.com/rancher/norman/condition.getFieldValue({0x0?, 0x0?, 0x0?}, {0xc0028b5968, 0x1, 0x1})
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20240708202514-a0127673d1b9/condition/condition.go:325 +0x45
github.com/rancher/norman/condition.getValue({0x8087180?, 0xc006ea1128?}, {0xc0028b5958, 0x2, 0x2})
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20240708202514-a0127673d1b9/condition/condition.go:321 +0x148
github.com/rancher/norman/condition.findOrNotCreateCond({0x8087180?, 0xc006ea1128?}, {0x8157eee, 0x15})
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20240708202514-a0127673d1b9/condition/condition.go:277 +0x6a
github.com/rancher/norman/condition.getStatus({0x8087180?, 0xc006ea1128?}, {0x8157eee?, 0xc01232cd56?})
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20240708202514-a0127673d1b9/condition/condition.go:243 +0x26
github.com/rancher/norman/condition.Cond.IsTrue(...)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20240708202514-a0127673d1b9/condition/condition.go:26
github.com/rancher/rancher/pkg/controllers/management/secretmigrator.(*handler).fixShibbolethSecretReference(0xc0022015f0, {0x9060588, 0xc006ea1128})
	/app/pkg/controllers/management/secretmigrator/authconfig.go:90 +0x5f
github.com/rancher/rancher/pkg/controllers/management/secretmigrator.(*handler).syncAuthConfig(0xc0022015f0, {0xc0009d4c40?, 0x803f8a0?}, 0xc0009d4c40?)
	/app/pkg/controllers/management/secretmigrator/authconfig.go:37 +0x107
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*authConfigController).AddHandler.func1({0xc00ed8faf6?, 0x6?}, {0x7fef620?, 0xc00cee3600?})
	/app/pkg/generated/norman/management.cattle.io/v3/zz_generated_auth_config_controller.go:155 +0x3a
github.com/rancher/norman/controller.(*genericController).AddHandler.func1({0xc00ed8faf6, 0xa}, {0x9061ae0, 0xc00cee3600})
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20240708202514-a0127673d1b9/controller/generic_controller.go:57 +0x170
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0x7fef620?, {0xc00ed8faf6?, 0x818cd22?}, {0x9061ae0?, 0xc00cee3600?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240705194423-b2a060d103c1/pkg/controller/sharedcontroller.go:29 +0x32
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc0012e9b80, {0xc00ed8faf6, 0xa}, {0x9061ae0, 0xc002400dc0})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240705194423-b2a060d103c1/pkg/controller/sharedhandler.go:75 +0x202
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc00144d600, {0xc00ed8faf6, 0xa})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240705194423-b2a060d103c1/pkg/controller/controller.go:236 +0x12e
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc00144d600, {0x658f740, 0xc006791b30})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240705194423-b2a060d103c1/pkg/controller/controller.go:217 +0xeb
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc00144d600)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240705194423-b2a060d103c1/pkg/controller/controller.go:194 +0x45
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240705194423-b2a060d103c1/pkg/controller/controller.go:183
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	/go/pkg/mod/k8s.io/apimachinery@v0.30.1/pkg/util/wait/backoff.go:226 +0x33
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00515b810, {0x904da40, 0xc0054fadb0}, 0x1, 0xc0000c9380)
	/go/pkg/mod/k8s.io/apimachinery@v0.30.1/pkg/util/wait/backoff.go:227 +0xaf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00515b810, 0x3b9aca00, 0x0, 0x1, 0xc0000c9380)
	/go/pkg/mod/k8s.io/apimachinery@v0.30.1/pkg/util/wait/backoff.go:204 +0x7f
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.30.1/pkg/util/wait/backoff.go:161
created by github.com/rancher/lasso/pkg/controller.(*controller).run in goroutine 1849
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240705194423-b2a060d103c1/pkg/controller/controller.go:151 +0x2ba
```

**Comment by nickwsuse** [comment]
Validated on v2.9-head ID: `2d710f` ✅ 
----
There are no panics in the Rancher logs after enabling Shibboleth for either HAs or Docker installs, and no pod restarts either.
