### ISSUE TITLE
[BUG] Crash on startup v2.9.0 SIGSEGV

### ISSUE THREAD

**Issue by braunsonm** [rancher/rancher#46415]
**Rancher Server Setup**
- Rancher version: v2.9.0
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Helm RKE2
- Proxy/Cert Details: None.

**Information about the Cluster**
- Kubernetes version: 1.28
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): vSphere

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: N/A

**Describe the bug**
After upgrading from 2.8.5 to 2.9.0, Rancher pod is crashing on startup with the following:

```
panic: runtime error: invalid memory address of nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x26586b5]

goroutine 4639 [running]:
github.com/rancher/steve/pkg/schema/definitions.listGVKModels(...)
  /go/pkg/mod/github.com/rancher/steve@v0.0.0-20240709130809-47871606146c/pkg/schema/definitions/handler.go:226 +0x5b5
github.com/rancher/steve/pkg/schema/definitions.(*SchemaDefinitionHandler).Refresh(...)
  /go/pkg/mod/github.com/rancher/steve@v0.0.0-20240709130809-47871606146c/pkg/schema/definitions/handler.go:107 +0x17a
...
```

**To Reproduce**
For me, just try to upgrade from 2.8.5. I'm not sure what other steps cause this panic.

**Result**

**Expected Result**
Rancher should not crash

**Comment by braunsonm** [comment]
Looks related to https://github.com/rancher/rancher/issues/46213

I'll close this as a duplicate.
