### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by andryzhu** [rancher/rancher#46712]
**Rancher Server Setup**
- Rancher version: 2.8.4
- Installation option (Docker install/Helm Chart):
   - Installed on k3s via helm
   - The rancher service type is Load Balancer
- Proxy/Cert Details:  Use the nginx reverse proxy to the rancher service

**Information about the Cluster**
- Kubernetes version: v1.28.10+k3s1
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**
When custom metrics are used in hpa, hpa cannot display detailed information.
 http_server_requests_per_second is a custom metric.
![image](https://github.com/user-attachments/assets/df97d6a9-f465-476c-9d6e-6d740eb34ff7)
![image](https://github.com/user-attachments/assets/d2c27539-2ae3-4c7e-9f33-2d91c1dbef2e)

The apiserver interface can be used to obtain user-defined indicator data.
![image](https://github.com/user-attachments/assets/f4dff237-fa4b-4407-bce2-a5ef1caa194d)

**Comment by TrueBurn** [comment]
I end up having to run q kubectl command to view my custom metric HPA values and even my normal CPU utilization when I add a custom HPA. The custom HPA does work at least, its just the display.

```
watch -n 5 "kubectl describe hpa custom-metrics-demo -n demo-namespace | grep -A5 'Metrics:'"
```

browser conole error:

```
TypeError: Cannot read properties of undefined (reading 'name')
    at index.vue:46:1
    at Array.map (<anonymous>)
    at a.mappedMetrics (index.vue:43:1)
    at e.get (vue.runtime.esm.js:3446:33)
    at e.evaluate (vue.runtime.esm.js:3547:27)
    at a.mappedMetrics (vue.runtime.esm.js:5537:25)
    at a.n (index.vue:1:338)
    at Tn.e._render (vue.runtime.esm.js:2684:28)
    at a.r (vue.runtime.esm.js:3875:27)
    at e.get (vue.runtime.esm.js:3446:33)
 ``
