### ISSUE TITLE
[external-dns] Loops on initializing

### ISSUE THREAD

**Issue by russ** [rancher/rancher#4671]
Rancher Version: v0.4.4

Docker Version: 1.11.1

OS: Ubuntu 16.0.4

Steps to Reproduce: Launch the Route53 stack from the catalog 

Results: Stack loops from starting/unhealthy/initializing

Expected: To be active

Here is the container log:

```
5/3/2016 2:30:27 PMnet/http.(*noteEOFReader).Read(0xc82010ef80, 0xc8201a4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
5/3/2016 2:30:27 PM	<autogenerated>:126 +0xd0
5/3/2016 2:30:27 PMbufio.(*Reader).fill(0xc820144a20)
5/3/2016 2:30:27 PM	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
5/3/2016 2:30:27 PMbufio.(*Reader).Peek(0xc820144a20, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
5/3/2016 2:30:27 PM	/usr/local/go/src/bufio/bufio.go:132 +0xcc
5/3/2016 2:30:27 PMnet/http.(*persistConn).readLoop(0xc820164000)
5/3/2016 2:30:27 PM	/usr/local/go/src/net/http/transport.go:876 +0xf7
5/3/2016 2:30:27 PMcreated by net/http.(*Transport).dialConn
5/3/2016 2:30:27 PM	/usr/local/go/src/net/http/transport.go:685 +0xc78
5/3/2016 2:30:27 PM
5/3/2016 2:30:27 PMgoroutine 26 [IO wait]:
5/3/2016 2:30:27 PMnet.runtime_pollWait(0x7f6e049311d0, 0x72, 0xc82000a150)
5/3/2016 2:30:27 PM	/usr/local/go/src/runtime/netpoll.go:157 +0x60
5/3/2016 2:30:27 PMnet.(*pollDesc).Wait(0xc8201bedf0, 0x72, 0x0, 0x0)
5/3/2016 2:30:27 PM	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
5/3/2016 2:30:27 PMnet.(*pollDesc).WaitRead(0xc8201bedf0, 0x0, 0x0)
5/3/2016 2:30:27 PM	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
5/3/2016 2:30:27 PMnet.(*netFD).accept(0xc8201bed90, 0x0, 0x7f6e048f7698, 0xc8201baf60)
5/3/2016 2:30:27 PM	/usr/local/go/src/net/fd_unix.go:408 +0x27c
5/3/2016 2:30:27 PMnet.(*TCPListener).AcceptTCP(0xc8201c44b0, 0xc82017bd20, 0x0, 0x0)
5/3/2016 2:30:27 PM	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
5/3/2016 2:30:27 PMnet/http.tcpKeepAliveListener.Accept(0xc8201c44b0, 0x0, 0x0, 0x0, 0x0)
5/3/2016 2:30:27 PM	/usr/local/go/src/net/http/server.go:2135 +0x41
5/3/2016 2:30:27 PMnet/http.(*Server).Serve(0xc8201ccea0, 0x7f6e048f7660, 0xc8201c44b0, 0x0, 0x0)
5/3/2016 2:30:27 PM	/usr/local/go/src/net/http/server.go:1887 +0xb3
5/3/2016 2:30:27 PMnet/http.(*Server).ListenAndServe(0xc8201ccea0, 0x0, 0x0)
5/3/2016 2:30:27 PM	/usr/local/go/src/net/http/server.go:1877 +0x136
5/3/2016 2:30:27 PMnet/http.ListenAndServe(0xac5908, 0x5, 0x7f6e048f7600, 0xc8201c0230, 0x0, 0x0)
5/3/2016 2:30:27 PM	/usr/local/go/src/net/http/server.go:1967 +0x8f
5/3/2016 2:30:27 PMmain.startHealthcheck()
5/3/2016 2:30:27 PM	/source/healthcheck.go:17 +0x28c
5/3/2016 2:30:27 PMcreated by main.main
5/3/2016 2:30:27 PM	/source/main.go:91 +0x1aa
5/3/2016 2:30:27 PM
5/3/2016 2:30:27 PMgoroutine 57 [IO wait]:
5/3/2016 2:30:27 PMnet.runtime_pollWait(0x7f6e04931110, 0x72, 0xc82000a150)
5/3/2016 2:30:27 PM	/usr/local/go/src/runtime/netpoll.go:157 +0x60
5/3/2016 2:30:27 PMnet.(*pollDesc).Wait(0xc820208060, 0x72, 0x0, 0x0)
5/3/2016 2:30:27 PM	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
5/3/2016 2:30:27 PMnet.(*pollDesc).WaitRead(0xc820208060, 0x0, 0x0)
5/3/2016 2:30:27 PM	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
5/3/2016 2:30:27 PMnet.(*netFD).Read(0xc820208000, 0xc82020a000, 0x1000, 0x1000, 0x0, 0x7f6e04970050, 0xc82000a150)
5/3/2016 2:30:27 PM	/usr/local/go/src/net/fd_unix.go:232 +0x23a
5/3/2016 2:30:27 PMnet.(*conn).Read(0xc8201c4498, 0xc82020a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
5/3/2016 2:30:27 PM	/usr/local/go/src/net/net.go:172 +0xe4
5/3/2016 2:30:27 PMnet/http.noteEOFReader.Read(0x7f6e04931578, 0xc8201c4498, 0xc8201e6268, 0xc82020a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
5/3/2016 2:30:27 PM	/usr/local/go/src/net/http/transport.go:1370 +0x67
5/3/2016 2:30:27 PMnet/http.(*noteEOFReader).Read(0xc8201bad80, 0xc82020a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
5/3/2016 2:30:27 PM	<autogenerated>:126 +0xd0
5/3/2016 2:30:27 PMbufio.(*Reader).fill(0xc8201cccc0)
5/3/2016 2:30:27 PM	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
5/3/2016 2:30:27 PMbufio.(*Reader).Peek(0xc8201cccc0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
5/3/2016 2:30:27 PM	/usr/local/go/src/bufio/bufio.go:132 +0xcc
5/3/2016 2:30:27 PMnet/http.(*persistConn).readLoop(0xc8201e6210)
5/3/2016 2:30:27 PM	/usr/local/go/src/net/http/transport.go:876 +0xf7
5/3/2016 2:30:27 PMcreated by net/http.(*Transport).dialConn
5/3/2016 2:30:27 PM	/usr/local/go/src/net/http/transport.go:685 +0xc78
5/3/2016 2:30:27 PM
5/3/2016 2:30:27 PMgoroutine 58 [select]:
5/3/2016 2:30:27 PMnet/http.(*persistConn).writeLoop(0xc8201e6210)
5/3/2016 2:30:27 PM	/usr/local/go/src/net/http/transport.go:1009 +0x40c
5/3/2016 2:30:27 PMcreated by net/http.(*Transport).dialConn
5/3/2016 2:30:27 PM	/usr/local/go/src/net/http/transport.go:686 +0xc9d
5/3/2016 2:30:27 PM
5/3/2016 2:30:27 PMgoroutine 64 [IO wait]:
5/3/2016 2:30:27 PMnet.runtime_pollWait(0x7f6e04931290, 0x72, 0xc82000a150)
5/3/2016 2:30:27 PM	/usr/local/go/src/runtime/netpoll.go:157 +0x60
5/3/2016 2:30:27 PMnet.(*pollDesc).Wait(0xc8200545a0, 0x72, 0x0, 0x0)
5/3/2016 2:30:27 PM	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
5/3/2016 2:30:27 PMnet.(*pollDesc).WaitRead(0xc8200545a0, 0x0, 0x0)
5/3/2016 2:30:27 PM	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
5/3/2016 2:30:27 PMnet.(*netFD).Read(0xc820054540, 0xc8201a1800, 0x800, 0x800, 0x0, 0x7f6e04970050, 0xc82000a150)
5/3/2016 2:30:27 PM	/usr/local/go/src/net/fd_unix.go:232 +0x23a
5/3/2016 2:30:27 PMnet.(*conn).Read(0xc8201c4510, 0xc8201a1800, 0x800, 0x800, 0x0, 0x0, 0x0)
5/3/2016 2:30:27 PM	/usr/local/go/src/net/net.go:172 +0xe4
5/3/2016 2:30:27 PMcrypto/tls.(*block).readFromUntil(0xc820545bc0, 0x7f6e04931578, 0xc8201c4510, 0x5, 0x0, 0x0)
5/3/2016 2:30:27 PM	/usr/local/go/src/crypto/tls/conn.go:455 +0xcc
5/3/2016 2:30:27 PMcrypto/tls.(*Conn).readRecord(0xc8201f2580, 0xc15e17, 0x0, 0x0)
5/3/2016 2:30:27 PM	/usr/local/go/src/crypto/tls/conn.go:540 +0x2d1
5/3/2016 2:30:27 PMcrypto/tls.(*Conn).Read(0xc8201f2580, 0xc8202d0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
5/3/2016 2:30:27 PM	/usr/local/go/src/crypto/tls/conn.go:901 +0x167
5/3/2016 2:30:27 PMnet/http.noteEOFReader.Read(0x7f6e04900350, 0xc8201f2580, 0xc8201e6528, 0xc8202d0000, 0x1000, 0x1000, 0xc820032400, 0x0, 0x0)
5/3/2016 2:30:27 PM	/usr/local/go/src/net/http/transport.go:1370 +0x67
5/3/2016 2:30:27 PMnet/http.(*noteEOFReader).Read(0xc820570160, 0xc8202d0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
5/3/2016 2:30:27 PM	<autogenerated>:126 +0xd0
5/3/2016 2:30:27 PMbufio.(*Reader).fill(0xc82056e6c0)
5/3/2016 2:30:27 PM	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
5/3/2016 2:30:27 PMbufio.(*Reader).Peek(0xc82056e6c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
5/3/2016 2:30:27 PM	/usr/local/go/src/bufio/bufio.go:132 +0xcc
5/3/2016 2:30:27 PMnet/http.(*persistConn).readLoop(0xc8201e64d0)
5/3/2016 2:30:27 PM	/usr/local/go/src/net/http/transport.go:876 +0xf7
5/3/2016 2:30:27 PMcreated by net/http.(*Transport).dialConn
5/3/2016 2:30:27 PM	/usr/local/go/src/net/http/transport.go:685 +0xc78
5/3/2016 2:30:27 PM
5/3/2016 2:30:27 PMgoroutine 65 [select]:
5/3/2016 2:30:27 PMnet/http.(*persistConn).writeLoop(0xc8201e64d0)
5/3/2016 2:30:27 PM	/usr/local/go/src/net/http/transport.go:1009 +0x40c
5/3/2016 2:30:27 PMcreated by net/http.(*Transport).dialConn
5/3/2016 2:30:27 PM	/usr/local/go/src/net/http/transport.go:686 +0xc9d

```

**Comment by deniseschannon** [comment]
Can you share the logs in Rancher server?

**Comment by themadinventor** [comment]
We're experiencing the same behavior. When starting a shell on the container and run the daemon manually I get the following output:

```
/ # usr/bin/external-dns
INFO[0000] CLOUDFLARE_EMAIL is not set, skipping init of CloudFlare provider
INFO[0000] DNSIMPLE_TOKEN is not set, skipping init of DNSimple provider
INFO[0000] GANDI_APIKEY is not set, skipping init of Gandi provider
INFO[0000] POINTHQ_TOKEN is not set, skipping init of PointHQ provider
INFO[0000] Configured Route 53 with hosted zone 'our-secret-domain.com.' in region 'us-east-
1'
INFO[0000] Starting Rancher External DNS service
INFO[0000] Powered by Route 53
INFO[0000] Healthcheck handler is listening on :1000
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x53bfbe]

goroutine 1 [running]:
github.com/rancher/external-dns/providers.(*Route53Handler).GetRecords(0xc82000f
960, 0x0, 0x0, 0x0, 0x0, 0x0)
        /source/gopath/src/github.com/rancher/external-dns/providers/route53.go:
171 +0x5ae
main.getProviderDnsRecords(0x12, 0x0, 0x0)
        /source/external-dns.go:130 +0x4c
main.UpdateProviderDnsRecords(0xc82049ea20, 0x0, 0x0, 0x0, 0x0, 0x0)
        /source/external-dns.go:12 +0x67
main.main()
        /source/main.go:122 +0x4e9

goroutine 41 [select]:
net/http.(*persistConn).writeLoop(0xc82038a160)
        /usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 8 [IO wait]:
net.runtime_pollWait(0x7f278142c290, 0x72, 0xc82000a170)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82004c300, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82004c300, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82004c2a0, 0xc820166000, 0x1000, 0x1000, 0x0, 0x7f278146b05
0, 0xc82000a170)
        /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200280c8, 0xc820166000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f278146f950, 0xc8200280c8, 0xc820132268, 0xc82016
6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc82000f7a0, 0xc820166000, 0x1000, 0x1000, 0x0,
0x0, 0x0)
        <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc82001a360)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc82001a360, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc820132210)
        /usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 40 [IO wait]:
net.runtime_pollWait(0x7f278142c110, 0x72, 0xc82000a170)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201e63e0, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201e63e0, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201e6380, 0xc8203cb000, 0x800, 0x800, 0x0, 0x7f278146b050,
 0xc82000a170)
        /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200ec028, 0xc8203cb000, 0x800, 0x800, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8204ebc80, 0x7f278146f950, 0xc8200ec028, 0x
5, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc82008c580, 0xc15e17, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc82008c580, 0xc8204d8000, 0x1000, 0x1000, 0x0, 0x0, 0x
0)
        /usr/local/go/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x7f2781478b98, 0xc82008c580, 0xc82038a1b8, 0xc8204d
8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc820496e20, 0xc8204d8000, 0x1000, 0x1000, 0x0,
0x0, 0x0)
        <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc82001b260)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc82001b260, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82038a160)
        /usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 9 [select]:
net/http.(*persistConn).writeLoop(0xc820132210)
        /usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 13 [IO wait]:
net.runtime_pollWait(0x7f278142c1d0, 0x72, 0xc82000a170)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820456990, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820456990, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820456930, 0xc82017f000, 0x800, 0x800, 0x0, 0x7f278146b050,
 0xc82000a170)
        /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820028138, 0xc82017f000, 0x800, 0x800, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820469380, 0x7f278146f950, 0xc820028138, 0x
5, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc82045e2c0, 0xc15e17, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc82045e2c0, 0xc8204ac000, 0x1000, 0x1000, 0x0, 0x0, 0x
0)
        /usr/local/go/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x7f2781478b98, 0xc82045e2c0, 0xc8201323c8, 0xc8204a
c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc820496f60, 0xc8204ac000, 0x1000, 0x1000, 0x0,
0x0, 0x0)
        <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8203e17a0)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8203e17a0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc820132370)
        /usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 14 [select]:
net/http.(*persistConn).writeLoop(0xc820132370)
        /usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 35 [IO wait]:
net.runtime_pollWait(0x7f278142c350, 0x72, 0xc82000a170)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201e6ae0, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201e6ae0, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8201e6a80, 0x0, 0x7f278142f8d8, 0xc8204e6620)
        /usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8200ec520, 0xc82013dd20, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc8200ec520, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2135 +0x41
net/http.(*Server).Serve(0xc8201197a0, 0x7f278142f8a0, 0xc8200ec520, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc8201197a0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1877 +0x136
net/http.ListenAndServe(0xac5908, 0x5, 0x7f278142f840, 0xc820014cd0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1967 +0x8f
main.startHealthcheck()
        /source/healthcheck.go:17 +0x28c
created by main.main
        /source/main.go:91 +0x1aa
```

Rancher 1.1.0-dev1

external-dns v0.4.0

**Comment by russ** [comment]
Yep. Same logs over here.

**Comment by aemneina** [comment]
I was able to get this up and going using Rancher 1.1.0-dev1/ubuntu 16.04. Can you check if the cross-host communication is working? You can do that by executing shell on your network agents and see if they can ping each other. Their IP addresses (10.4.x.x) should be visible in the hosts tab.

**Comment by russ** [comment]
Works both ways for me.

```
root@0c657bc18f21:/# ping 10.42.212.150
PING 10.42.212.150 (10.42.212.150) 56(84) bytes of data.
64 bytes from 10.42.212.150: icmp_seq=1 ttl=64 time=0.461 ms
64 bytes from 10.42.212.150: icmp_seq=2 ttl=64 time=0.617 ms
64 bytes from 10.42.212.150: icmp_seq=3 ttl=64 time=0.525 ms
64 bytes from 10.42.212.150: icmp_seq=4 ttl=64 time=0.552 ms
64 bytes from 10.42.212.150: icmp_seq=5 ttl=64 time=0.603 ms
64 bytes from 10.42.212.150: icmp_seq=6 ttl=64 time=0.555 ms
64 bytes from 10.42.212.150: icmp_seq=7 ttl=64 time=0.558 ms
64 bytes from 10.42.212.150: icmp_seq=8 ttl=64 time=0.607 ms
64 bytes from 10.42.212.150: icmp_seq=9 ttl=64 time=0.537 ms
64 bytes from 10.42.212.150: icmp_seq=10 ttl=64 time=0.648 ms
^C
--- 10.42.212.150 ping statistics ---
10 packets transmitted, 10 received, 0% packet loss, time 8997ms
rtt min/avg/max/mdev = 0.461/0.566/0.648/0.054 ms
```

```
root@2e8631bf2b45:/# ping 10.42.122.240
PING 10.42.122.240 (10.42.122.240) 56(84) bytes of data.
64 bytes from 10.42.122.240: icmp_seq=1 ttl=64 time=0.480 ms
64 bytes from 10.42.122.240: icmp_seq=2 ttl=64 time=0.647 ms
64 bytes from 10.42.122.240: icmp_seq=3 ttl=64 time=0.750 ms
64 bytes from 10.42.122.240: icmp_seq=4 ttl=64 time=0.522 ms
64 bytes from 10.42.122.240: icmp_seq=5 ttl=64 time=0.612 ms
64 bytes from 10.42.122.240: icmp_seq=6 ttl=64 time=0.577 ms
64 bytes from 10.42.122.240: icmp_seq=7 ttl=64 time=0.524 ms
64 bytes from 10.42.122.240: icmp_seq=8 ttl=64 time=0.507 ms
64 bytes from 10.42.122.240: icmp_seq=9 ttl=64 time=0.606 ms
64 bytes from 10.42.122.240: icmp_seq=10 ttl=64 time=0.563 ms
^C
--- 10.42.122.240 ping statistics ---
10 packets transmitted, 10 received, 0% packet loss, time 8998ms
rtt min/avg/max/mdev = 0.480/0.578/0.750/0.081 ms
```

**Comment by themadinventor** [comment]
Works both ways here as well. I can also reach https://route53.amazonaws.com/ from within the container, which I believe is the REST API used by the failing code.
The segfault in the error intrigues me, but I'm not used to Go so I have to figure out how to debug it further... :)
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x53bfbe]

goroutine 1 [running]:
github.com/rancher/external-dns/providers.(*Route53Handler).GetRecords(0xc82000f
960, 0x0, 0x0, 0x0, 0x0, 0x0)
```

**Comment by alena1108** [comment]
@janeczku looks like the error happens when we cast TTL (line 171 in route53.go): 

```
TTL: int(*rrSet.TTL),
```

From what I remember, AWS doesn't allow null values for TTL, any idea what could have caused this error?

**Comment by janeczku** [comment]
I suspect that this might be triggered by having alias resource records (e.g. ELB routing) in the hosted zone. Apparently those records don't have a TTL and the AWS SDK probably just omits this field and it ends up having a nil value when we process it.

**Comment by janeczku** [comment]
@russ @themadinventor could you confirm whether you have any alias resource records configured in the affected hosted zones?

**Comment by themadinventor** [comment]
@janeczku yes, we have alias records for S3 and Elastic Beanstalk resources, with empty TTL values.

**Comment by russ** [comment]
@janeczku I also have alias records on the existing zone.

**Comment by alena1108** [comment]
@janeczku thank you for looking into it @russ @themadinventor we will work on the fix

**Comment by alena1108** [comment]
@janeczku thanks for the fix! I've released the new image; catalog will be updated soon too.

**Comment by dabeck** [comment]
@alena1108 Any news on the catalog update? I'm experiencing that problems with 0.4.0 as well.

**Comment by themadinventor** [comment]
We got it running by cloning an instance of the 0.4.0 version in the catalog and setting the image to `rancher/external-dns:v0.4.1`.

**Comment by deniseschannon** [comment]
@russ @dabeck @themadinventor The latest template has been released. Please let me know if there are any other issues.

**Comment by deniseschannon** [comment]
If there are issues with the latest template, please open a new issue.
