### ISSUE TITLE
[flaky-test] TestClusterRepoTestSuite/TestOCIRepo5 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#47088]
**Flaky Test**

`TestClusterRepoTestSuite/TestOCIRepo5` 
 ```
=== RUN   TestClusterRepoTestSuite/TestOCIRepo5
    cluster_repo_test.go:559: 
        	Error Trace:	/home/runner/_work/rancher/rancher/tests/v2/integration/catalogv2/cluster_repo_test.go:559
        	            				/home/runner/_work/rancher/rancher/tests/v2/integration/catalogv2/cluster_repo_test.go:485
        	Error:      	Received unexpected error:
        	            	resource name may not be empty
        	Test:       	TestClusterRepoTestSuite/TestOCIRepo5
    cluster_repo_test.go:563: 
        	Error Trace:	/home/runner/_work/rancher/rancher/tests/v2/integration/catalogv2/cluster_repo_test.go:563
        	            				/home/runner/_work/rancher/rancher/tests/v2/integration/catalogv2/cluster_repo_test.go:485
        	Error:      	Received unexpected error:
        	            	EOF
        	Test:       	TestClusterRepoTestSuite/TestOCIRepo5
    panic.go:261: test panicked: runtime error: invalid memory address or nil pointer dereference
        goroutine 789 [running]:
        runtime/debug.Stack()
        	/home/runner/_work/_tool/go/1.22.7/x64/src/runtime/debug/stack.go:24 +0x5e
        github.com/stretchr/testify/suite.failOnPanic(0xc000a41520, {0x42d5600, 0x6f9f5e0})
        	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.9.0/suite/suite.go:89 +0x37
        github.com/stretchr/testify/suite.Run.func1.1()
        	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.9.0/suite/suite.go:188 +0x299
        panic({0x42d5600?, 0x6f9f5e0?})
        	/home/runner/_work/_tool/go/1.22.7/x64/src/runtime/panic.go:770 +0x132
        compress/gzip.(*Reader).Close(...)
        	/home/runner/_work/_tool/go/1.22.7/x64/src/compress/gzip/gunzip.go:290
        panic({0x42d5600?, 0x6f9f5e0?})
        	/home/runner/_work/_tool/go/1.22.7/x64/src/runtime/panic.go:770 +0x132
        compress/gzip.(*Reader).Read(0xc0010c2680?, {0xc000fd4c00?, 0xc0011cb100?, 0x3806d65?})
        	/home/runner/_work/_tool/go/1.22.7/x64/src/compress/gzip/gunzip.go:247 +0x22
        io.ReadAll({0x5[296](https://github.com/rancher/rancher/actions/runs/10823870775/job/30031565635?pr=47034#step:32:297)9e0, 0x0})
        	/home/runner/_work/_tool/go/1.22.7/x64/src/io/io.go:712 +0x7e
        github.com/rancher/rancher/tests/v2/integration/catalogv2.(*ClusterRepoTestSuite).test429Error(0xc00094e5b0, {{0x48fab79, 0x15}, 0x2, {0xc000a2fec0, 0x18}, {0x0, 0x0}, 0x1, 0x0, ...})
        	/home/runner/_work/rancher/rancher/tests/v2/integration/catalogv2/cluster_repo_test.go:565 +0xd12
        github.com/rancher/rancher/tests/v2/integration/catalogv2.(*ClusterRepoTestSuite).TestOCIRepo5(0xc00094e5b0)
        	/home/runner/_work/rancher/rancher/tests/v2/integration/catalogv2/cluster_repo_test.go:485 +0x1e8
        reflect.Value.call({0xc00110b340?, 0xc000996ef0?, 0x0?}, {0x48a365e, 0x4}, {0xc0011d7f28, 0x1, 0x432a800?})
        	/home/runner/_work/_tool/go/1.22.7/x64/src/reflect/value.go:596 +0xca6
        reflect.Value.Call({0xc00110b340?, 0xc000996ef0?, 0x65ad7b8?}, {0xc0011d7f28?, 0xf?, 0x0?})
        	/home/runner/_work/_tool/go/1.22.7/x64/src/reflect/value.go:380 +0xb9
        github.com/stretchr/testify/suite.Run.func1(0xc000a41520)
        	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.9.0/suite/suite.go:202 +0x4a5
        testing.tRunner(0xc000a41520, 0xc00081e2d0)
        	/home/runner/_work/_tool/go/1.22.7/x64/src/testing/testing.go:1689 +0xfb
        created by testing.(*T).Run in goroutine 156
        	/home/runner/_work/_tool/go/1.22.7/x64/src/testing/testing.go:1742 +0x390
--- FAIL: TestClusterRepoTestSuite (159.06s)
```

**Release Branch**

source branch of PR: `main` 
 

pipeline stage URL: https://github.com/rancher/rancher/actions/runs/10823870775/job/30031565635?pr=47034#step:32:294

**Comment by jiaqiluo** [comment]
another occurrence: https://github.com/rancher/rancher/actions/runs/10856055454/job/30130739985#step:32:201
