### ISSUE TITLE
[BUG] Run RKE2 Agent on Windows Server 2019 fail, runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kenny2061** [rancher/rancher#47372]
Rancher Server Setup

Rancher version: v1.30.5+rke2r1
Installation option (Docker install/Helm Chart): Docker install
Proxy/Cert Details: N/A
Information about the Cluster

Kubernetes version: v1.30.5+rke2r1
Cluster Type (Local/Downstream): Downstream
If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom
User Information

What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin
If custom, define the set of permissions: N/A
Describe the bug
When attempting to install RKE2 as an agent node on a Windows Server 2019 Server Core VM using the command c:\usr\local\bin\rke2.exe agent --config C:\etc\rancher\rke2\config.yaml --token "my rke2 server token", a panic occurs due to a runtime error.

To Reproduce

Install RKE2 on a Debian 12 server in HA mode.
Use the PowerShell script from [Rancher's GitHub](https://raw.githubusercontent.com/rancher/rke2/master/install.ps1) to install RKE2 v1.30.5+rke2r1 on Windows Server 2019.
Run the command: c:\usr\local\bin\rke2.exe agent --config C:\etc\rancher\rke2\config.yaml --token "my rke2 server token".
Result
The following error messages are displayed:

```

time="2024-10-03T02:15:23+08:00" level=info msg="Starting rke2 agent v1.30.5+rke2r1 (0c83bc82315cd61664880d0b52a7e070e9fbd623)"
time="2024-10-03T02:15:23+08:00" level=info msg="Adding server to load balancer rke2-agent-load-balancer: rke2.2061.in:9345"
time="2024-10-03T02:15:23+08:00" level=info msg="Running load balancer rke2-agent-load-balancer 127.0.0.1:6444 -> [rke2.2061.in:9345] [default: rke2.2061.in:9345]"
time="2024-10-03T02:15:24+08:00" level=info msg="Adding server to load balancer rke2-api-server-agent-load-balancer: rke2.2061.in:6443"
time="2024-10-03T02:15:24+08:00" level=info msg="Running load balancer rke2-api-server-agent-load-balancer 127.0.0.1:6443 -> [rke2.2061.in:6443] [default: rke2.2061.in:6443]"
time="2024-10-03T02:15:24+08:00" level=warning msg="Host resolv.conf includes loopback or multicast nameservers - kubelet will use autogenerated resolv.conf with nameserver 8.8.8.8"
time="2024-10-03T02:15:24+08:00" level=info msg="Runtime image index.docker.io/rancher/rke2-runtime:v1.30.5-rke2r1-windows-amd64 bin and charts directories already exist; skipping extract"
time="2024-10-03T02:15:25+08:00" level=info msg="Skipping CNI setup"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x7ff7bbd9b8b7]

goroutine 1 [running]:
github.com/rancher/rke2/pkg/pebinaryexecutor.(*PEBinaryConfig).Bootstrap(_, {_, _}, _, {{0xc0000b7140, 0x55}, {0x0, 0x0}, {0x0, 0x0}, ...})
        /source/pkg/pebinaryexecutor/pebinary.go:132 +0x497
github.com/k3s-io/k3s/pkg/daemons/executor.Bootstrap(...)
        /go/pkg/mod/github.com/k3s-io/k3s@v1.30.5-0.20240906183023-9e06189a7cd5/pkg/daemons/executor/executor.go:138
github.com/k3s-io/k3s/pkg/agent.run({_, _}, {{0xc0000b7140, 0x55}, {0x0, 0x0}, {0x0, 0x0}, {0xc002082609, 0x19}, ...}, ...)
        /go/pkg/mod/github.com/k3s-io/k3s@v1.30.5-0.20240906183023-9e06189a7cd5/pkg/agent/run.go:134 +0x70e
github.com/k3s-io/k3s/pkg/agent.Run({_, _}, {{0xc0000b7140, 0x55}, {0x0, 0x0}, {0x0, 0x0}, {0xc002082609, 0x19}, ...})
        /go/pkg/mod/github.com/k3s-io/k3s@v1.30.5-0.20240906183023-9e06189a7cd5/pkg/agent/run.go:326 +0xf0
github.com/k3s-io/k3s/pkg/cli/agent.Run(0xc0014ccdc0)
        /go/pkg/mod/github.com/k3s-io/k3s@v1.30.5-0.20240906183023-9e06189a7cd5/pkg/cli/agent/agent.go:130 +0x6ad
github.com/rancher/rke2/pkg/rke2.Agent(_, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {{0x0, ...}, ...}, ...})
        /source/pkg/rke2/rke2.go:157 +0x75
github.com/rancher/rke2/pkg/cli/cmds.AgentRun(0xc0014ccdc0)
        /source/pkg/cli/cmds/agent.go:98 +0x85
github.com/urfave/cli.HandleAction({0x7ff7bc4ce2e0?, 0x7ff7bd8abc20?}, 0xc00143f180?)
        /go/pkg/mod/github.com/urfave/cli@v1.22.15/app.go:524 +0x50
github.com/urfave/cli.(*App).RunAsSubcommand(0xc00143f180, 0xc0014ccc60)
        /go/pkg/mod/github.com/urfave/cli@v1.22.15/app.go:410 +0xa65
github.com/urfave/cli.Command.startApp({{0x7ff7bd37d7e2, 0x5}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x7ff7bd39c513, 0xe}, {0xc0015a80f0, ...}, ...}, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.15/command.go:380 +0xb1e
github.com/urfave/cli.Command.Run({{0x7ff7bd37d7e2, 0x5}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x7ff7bd39c513, 0xe}, {0xc0015a80f0, ...}, ...}, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.15/command.go:103 +0x7c5
github.com/urfave/cli.(*App).Run(0xc001ae7dc0, {0xc0000f8000, 0x8, 0x8})
        /go/pkg/mod/github.com/urfave/cli@v1.22.15/app.go:277 +0xb3b
main.main()
        /source/main.go:24 +0xb26
```

Expected Result
The expected result is for the RKE2 agent to successfully start and join the cluster without encountering a panic or runtime error.

Screenshots
N/A

**Comment by HarrisonWAffel** [comment]
Could you share more about how you have configured your environment? The log message `time="2024-10-03T02:15:25+08:00" level=info msg="Skipping CNI setup"` indicates that you may not have the correct CNI configured. Currently, [Windows nodes only work when rke2 users the Calico or Flannel as its CNI](https://docs.rke2.io/install/quickstart#windows-agent-worker-node-installation). I was not able to reproduce this issue when registering a 2019 core or desktop edition using Calico.

**Comment by HarrisonWAffel** [comment]
As this is a standalone rke2 cluster I'm going to transfer this issue to the rke2 repository
