### ISSUE TITLE
Rancher compose restart results in a panic: runtime error for a non-existant service

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#4747]
**Rancher Version:**V1.1.0-dev1

**OS and where are the hosts located? (cloud, bare metal, etc):** : ubuntu:14.04.2, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Cattle
**Steps to Reproduce: **
1. Set up rancher-compose environment
2. Issue a restart command
./rancher-compose -f dc1.yml -r test1.yml -p stack1 restart 

Note: dc1.yml file contains service test3 although it was not created (does not exist in the set-up ):
```
test2:
  image: ubuntu:14.04.2
  stdin_open: true
test3:
  image: sangeetha/testnewhostrouting 
  stdin_open: true
```

test1.yml contains:
```
test2:
  scale: 3
test3:
  scale: 2
```
===============================================
**Results:** 

The restart functionality works correctly. All the containers of test2 stop and start again.
But there is a panic: runtime error as follows:
```
soumyas-MacBook-Pro:rancher-compose-v0.8.0 soumya$ ./rancher-compose -f dc1.yml -r **test1.yml** -p stack1 restart 
INFO[0000] Project [stack1]: Restarting project         
INFO[0000] [0/2] [test3]: Restarting                    
INFO[0000] [0/2] [test2]: Restarting                    
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x1c1aed]

goroutine 50 [running]:
panic(0x6b5f60, 0xc82000e0b0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/rancher/rancher-compose/vendor/github.com/rancher/go-rancher/client.(*ServiceClient).ActionRestart(0xc82002d5e0, 0x0, 0xc8203058f0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher-compose/vendor/github.com/rancher/go-rancher/client/generated_service.go:240 +0x11d
github.com/rancher/rancher-compose/rancher.(*RancherService).Restart(0xc8203b4cc0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher-compose/rancher/service.go:508 +0x12b
github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project.(*Project).Restart.func1.1(0xe09118, 0xc8203b4cc0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project/project.go:209 +0x36
github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project.(*serviceWrapper).Do(0xc82032c380, 0xc82034aa50, 0xd, 0xe, 0x92ae00)
	/go/src/github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project/service-wrapper.go:100 +0x202
github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project.(*Project).Restart.func1(0xc82032c380, 0xc82034aa50)
	/go/src/github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project/project.go:210 +0x49
created by github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project.(*Project).startService
	/go/src/github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project/project.go:373 +0x5a8
 ```

**Comment by alena1108** [comment]
@joshwget can you look at this issue?

**Comment by joshwget** [comment]
@alena1108 Yeah, no problem!

**Comment by deniseschannon** [comment]
Verified with v0.9.3-rc1 that there is no panic. 

```
INFO[0000] [0/2] [test3]: Restarting                    
INFO[0000] [0/2] [test2]: Restarting                    
ERRO[0000] Failed Restarting test3 : Failed to find test3 to restart 
ERRO[0000] Failed to start: test3 : Failed to find test3 to restart 
INFO[0014] [0/2] [test2]: Restarted                     
Failed to find test3 to restart
```
