### ISSUE TITLE
[BUG] Upgrade from 2.8.3 -> 2.9.2 failed on one of the nodes

### ISSUE THREAD

**Issue by johnwc** [rancher/rancher#47558]
**Rancher Server Setup**
- Rancher version: 2.9.2
- Installation option (Docker install/Helm Chart): Helm, RKE2
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.28
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? Admin
  - If custom, define the set of permissions:

**Describe the bug**
I upgraded our rancher from 2.8.3 to 2.9.2, and one of our nodes failed to reconnect. Looks like something with etcd failing.

```
2024-10-09T06:25:57.632642878Z stderr F {"level":"info","ts":"2024-10-09T06:25:57.632028Z","caller":"embed/etcd.go:569","msg":"cmux::serve","address":"10.100.0.14:2380"}
2024-10-09T06:25:57.632669939Z stderr F {"level":"info","ts":"2024-10-09T06:25:57.632203Z","caller":"embed/etcd.go:277","msg":"now serving peer/client/metrics","local-member-id":"4af4833621d97d24","initial-advertise-peer-urls":["$
2024-10-09T06:25:57.63268356Z stderr F {"level":"info","ts":"2024-10-09T06:25:57.632238Z","caller":"embed/etcd.go:857","msg":"serving metrics","address":"http://127.0.0.1:2381/"}
2024-10-09T06:25:57.632687889Z stderr F {"level":"panic","ts":"2024-10-09T06:25:57.632475Z","logger":"raft","caller":"etcdserver/zap_raft.go:101","msg":"tocommit(65450530) is out of range [lastIndex(65448169)]. Was the raft log c$
2024-10-09T06:25:57.635864491Z stderr F panic: tocommit(65450530) is out of range [lastIndex(65448169)]. Was the raft log corrupted, truncated, or lost?
2024-10-09T06:25:57.635880604Z stderr F
2024-10-09T06:25:57.635886086Z stderr F goroutine 118 [running]:
2024-10-09T06:25:57.635891052Z stderr F go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000cac000, {0x0, 0x0, 0x0})
2024-10-09T06:25:57.635895772Z stderr F         /go/pkg/mod/go.uber.org/zap@v1.17.0/zapcore/entry.go:234 +0x49b
2024-10-09T06:25:57.635906908Z stderr F go.uber.org/zap.(*SugaredLogger).log(0xc000014018, 0x4, {0x134b66d?, 0x40d8a5?}, {0xc000ca8220?, 0x112d2c0?, 0x48223a2264656900?}, {0x0, 0x0, 0x0})
2024-10-09T06:25:57.635911388Z stderr F         /go/pkg/mod/go.uber.org/zap@v1.17.0/sugar.go:227 +0xee
2024-10-09T06:25:57.635915704Z stderr F go.uber.org/zap.(*SugaredLogger).Panicf(...)
2024-10-09T06:25:57.635919015Z stderr F         /go/pkg/mod/go.uber.org/zap@v1.17.0/sugar.go:159
2024-10-09T06:25:57.635928024Z stderr F go.etcd.io/etcd/server/v3/etcdserver.(*zapRaftLogger).Panicf(0x3e6a8e9?, {0x134b66d?, 0x4e39415973493175?}, {0xc000ca8220?, 0x59526968634a4d58?, 0x706b495252316b35?})
2024-10-09T06:25:57.635932122Z stderr F         /go/src/go.etcd.io/etcd/server/etcdserver/zap_raft.go:101 +0x49
2024-10-09T06:25:57.635939582Z stderr F go.etcd.io/etcd/raft/v3.(*raftLog).commitTo(0xc000452000, 0x3e6b222)
2024-10-09T06:25:57.635943353Z stderr F         /go/src/go.etcd.io/etcd/raft/log.go:237 +0x103
2024-10-09T06:25:57.635981398Z stderr F go.etcd.io/etcd/raft/v3.(*raft).handleHeartbeat(_, {0x8, 0x4af4833621d97d24, 0x707d9c9d046e008a, 0x80, 0x0, 0x0, {0x0, 0x0, 0x0}, ...})
2024-10-09T06:25:57.635993251Z stderr F         /go/src/go.etcd.io/etcd/raft/raft.go:1508 +0x45
2024-10-09T06:25:57.636026089Z stderr F go.etcd.io/etcd/raft/v3.stepFollower(_, {0x8, 0x4af4833621d97d24, 0x707d9c9d046e008a, 0x80, 0x0, 0x0, {0x0, 0x0, 0x0}, ...})
2024-10-09T06:25:57.636045032Z stderr F         /go/src/go.etcd.io/etcd/raft/raft.go:1434 +0x3d8
2024-10-09T06:25:57.636049463Z stderr F go.etcd.io/etcd/raft/v3.(*raft).Step(_, {0x8, 0x4af4833621d97d24, 0x707d9c9d046e008a, 0x80, 0x0, 0x0, {0x0, 0x0, 0x0}, ...})
2024-10-09T06:25:57.636052732Z stderr F         /go/src/go.etcd.io/etcd/raft/raft.go:975 +0x1335
2024-10-09T06:25:57.636078716Z stderr F go.etcd.io/etcd/raft/v3.(*node).run(0xc0004fe180)
2024-10-09T06:25:57.636197123Z stderr F         /go/src/go.etcd.io/etcd/raft/node.go:356 +0x925
2024-10-09T06:25:57.636219643Z stderr F created by go.etcd.io/etcd/raft/v3.RestartNode
2024-10-09T06:25:57.636254832Z stderr F         /go/src/go.etcd.io/etcd/raft/node.go:244 +0x24a
```

**Comment by johnwc** [comment]
@bk201 @FrankYang0529 @Vicente-Cheng at this point, I just need to know how to get the node back online. It's been almost a month now with no response at all.

**Comment by bk201** [comment]
@snasovich Can you help with the issue? the user needs some help in the guest cluster.

**Comment by johnwc** [comment]
@bk201 @snasovich this is the rancher cluster node that failed, not a guest cluster.
