### ISSUE TITLE
[BUG] 2.9.3: harvester provisioned clusters show "unknown" in cluster mangaement and edit is not possible

### ISSUE THREAD

**Issue by bpedersen2** [rancher/rancher#47748]
**Rancher Server Setup**
- Rancher version: v2.9.3 - Installation option (Docker install/Helm Chart): docker

**Information about the Cluster**
- Cluster Type (Local/Downstream): harvester  provisoned downstream

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
 admin

**Describe the bug**
Unable to access the context menu for harvester-provisioned  clusters (on harvester 1.3.2) due to incorrectly handled errors:

```
ActionMenu.vue:112 TypeError: Cannot read properties of undefined (reading 'name')
    at n.get (provisioning.cattle.io.cluster.js:249:45)
    at n.get (resource-class.js:928:26)
    at get (<anonymous>)
    at n.get (provisioning.cattle.io.cluster.js:91:14)
    at n.get (resource-class.js:842:22)
    at options (action-menu.js:44:16)
    at C.e._wrappedGetters.<computed>.e._wrappedGetters.<computed> (vuex.esm.js:881:12)
    at Rr.<anonymous> (vuex.esm.js:140:12)
    at e.get (vue.min.js:11:28262)
    at e.evaluate (vue.min.js:11:2
```

`````**To Reproduce**
<!--Steps to reproduce the behavior-->

**Result**

**Expected Result**
<!--A clear and concise description of what you expected to happen.-->

**Screenshots**
<!-- If applicable, add screenshots to help explain your problem.-->

**Additional context**
<!--Add any other context about the problem here.-->

**Comment by bpedersen2** [comment]
non-harvester provisioned clusters are manageable.

**Comment by bpedersen2** [comment]
The problems seems more severe: All work loads (which are running fine, as seen by kuebctl directly) initially show  the  correct status in the UI, but after a few seconds they all show "unknown" and do not  show the correct infos. And a lot of the undefined 'name' errors pop in the browser console.

**Comment by khushboo-rancher** [comment]
Please note that Rancher 2.9.3 is not currently supported or tested with Harvester 1.3.2. We recommend reviewing the support matrix [here](https://www.suse.com/suse-harvester/support-matrix/all-supported-versions/harvester-v1-3-x/) to ensure compatibility before using this specific Rancher version with Harvester.

We’d be happy to assist in reproducing the issue. Could you kindly share more details about your cluster provisioning? For instance, is it an RKE2 cluster, and if so, which version? Did you use a node driver to set up the cluster, or were there any specific steps you followed?

**Comment by nagyclaudiu83** [comment]
I can confirm similar behaviour with a different setup.

Rancher Server Setup

Rancher version: v2.9.3 - Installation option (Docker install/Helm Chart): helm Chart installed on 1 node arm k3s

Information about the Cluster

Cluster Type (Local/Downstream): local cluster and imported downstream cluster (both k3s v1.30.3+k3s1) 

User Information

What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
admin

Describe the bug
The local and imported cluster show status Unknown  on home screen ( can be used as usual) . The cluster management page doesn't show the clusters . Inside the clusters, most resources show status Unknown ( briefly they show as normal green active/running). Ex. A node shows Unknown instead of Active,  but if drained or cordoned it will show ,with correct status.

**Comment by bpedersen2** [comment]
As also described by @nagyclaudiu83, the problems show up both on  harvester-provisoned  RKE2-clusters  and on directly provisoned K3s-clusters. The console errors  ('name' undefined) hint at a generic problem with a missing/msinamed field somwhere in the  gui code.

**Comment by bpedersen2** [comment]
more seemingly relevant errors(these are shown for many resources from cattle.io):

```Resource error [management] management.cattle.io.feature : event watch error: an error on the server ("unable to decode an event from the watch stream: http2: response body closed") has prevented the request from succeeding
```

```Resource error [cluster] pod : notifier watch error: name is required: name is required
resource.error @ 757098bc-7e55-40a5-a368-2aa31dd4dab4:8
(anonymous) @ 757098bc-7e55-40a5-a368-2aa31dd4dab4:8
dispatchEvent @ 757098bc-7e55-40a5-a368-2aa31dd4dab4:8
value @ 757098bc-7e55-40a5-a368-2aa31dd4dab4:8
value @ 757098bc-7e55-40a5-a368-2aa31dd4dab4:8
08:37:32.641 
```

**Comment by bpedersen2** [comment]
I traced this to here:
```
createWatcher: function(t) {
                Ce("createWatcher", t);
                var e = t.metadata
                  , n = t.maxTries
                  , r = t.url
                  , o = t.csrf;
                if (!Pe.watcher) {
                    Pe.watcher = new Vt(r,!0,null,null,n,o),
                    Pe.watcher.addEventListener(At, (function(t) {￼t = r {isTrusted: false}
                        var e = t.detail;
                        if (e.data) {
                            var n = JSON.parse(e.data);
                            n.name && (Fe[n.name] ? Fe[n.name](n) : Fe.dispatch(n))
                        }
                    }
```

n is set to maxTries, but expected to have a name member ??

**Comment by m-ildefons** [comment]
Thanks for reporting this issue.

Could you please add details about the Rancher installation? It would be helpful to have the logs from the Rancher container from around the time when the error happens. It would also be helpful to know if this Rancher was upgraded from an older version or if this is a fresh install and if the downstream clusters were imported or created on this Rancher.

And just to confirm, opening _this_ menu for any downstream cluster triggers the error?
![Screenshot at 2024-10-29 14-30-00](https://github.com/user-attachments/assets/9e719542-b7c7-4767-8ae7-df6b8ace9ead)

@bpedersen2 I'm not sure that code is necessarily the culprit. `n` is redefined at `var n = JSON.parse(e.data);` before `n.name` is accessed.

**Comment by bpedersen2** [comment]
For my case: 
docker install upgraded from 2.9.2 ( started out from a 2.6 or 2.7 install)

And the error is present at may places ( e.g. explore -> workloads/... , all workloads turn from green to  undefined after a few seconds). 

And yes that menu is  the one that is not popping up. 
@m-ildefons Yes, I overlooked that one, but that is the function in the js-backtrace where the error is thrown.

**Comment by niesel** [comment]
> Could you please add details about the Rancher installation? It would be helpful to have the logs from the Rancher container from around the time when the error happens. It would also be helpful to know if this Rancher was upgraded from an older version or if this is a fresh install and if the downstream clusters were imported or created on this Rancher.

Upgrade from 2.9.2 to 2.9.3 via HelmChart on ManagementCluster (3-node rke2). Downstream clusters were provisioned from this cluster.

> And just to confirm, opening _this_ menu for any downstream cluster triggers the error? !

No, it's not the opening of the Menu that triggers the error. 
Just loading the Page does (happens on a lot of other pages also) and triggers the error. After a few seconds the error appears, the status switches from "Active" to "Unknown" and after that the ContextMenus can't even be opened. 


Here is a log of the rancher pod and a Screenshot of the chrome js console.
The TypeErrors and the Resource errors repeat every few seconds. 


```
E1029 13:41:49.897570      41 reflector.go:150] pkg/mod/k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: Failed to watch metrics.k8s.io/v1beta1, Kind=NodeMetrics: the server does not allow this method on the requested resource

E1029 13:42:41.657633      41 reflector.go:150] pkg/mod/k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: Failed to watch metrics.k8s.io/v1beta1, Kind=NodeMetrics: the server does not allow this method on the requested resource

E1029 13:43:19.366629      41 reflector.go:150] pkg/mod/k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: Failed to watch metrics.k8s.io/v1beta1, Kind=NodeMetrics: the server does not allow this method on the requested resource
2024/10/29 13:43:37 [ERROR] Error during subscribe websocket: close sent                                                                                                                                                                

E1029 13:43:55.214576      41 reflector.go:150] pkg/mod/k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: Failed to watch metrics.k8s.io/v1beta1, Kind=NodeMetrics: the server does not allow this method on the requested resource

E1029 13:44:28.314111      41 reflector.go:150] pkg/mod/k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: Failed to watch metrics.k8s.io/v1beta1, Kind=NodeMetrics: the server does not allow this method on the requested resource
2024/10/29 13:44:46 [ERROR] Error during subscribe websocket: close sent                                                                                                                                                                

W1029 13:45:04.243001      41 reflector.go:470] pkg/mod/k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: watch of /v1, Kind=Event ended with: very short watch: pkg/mod/k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: Unexpected watch close - watch lasted less than a second and no items received                                                                                                                                                                     

E1029 13:45:05.316173      41 reflector.go:150] pkg/mod/k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: Failed to watch metrics.k8s.io/v1beta1, Kind=NodeMetrics: the server does not allow this method on the requested resource
E1029 13:45:49.872188      41 reflector.go:150] pkg/mod/k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: Failed to watch metrics.k8s.io/v1beta1, Kind=NodeMetrics: the server does not allow this method on the requested resource

E1029 13:46:44.176733      41 reflector.go:150] pkg/mod/k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: Failed to watch metrics.k8s.io/v1beta1, Kind=NodeMetrics: the server does not allow this method on the requested resource

E1029 13:47:31.349430      41 reflector.go:150] pkg/mod/k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: Failed to watch metrics.k8s.io/v1beta1, Kind=NodeMetrics: the server does not allow this method on the requested resource

E1029 13:48:14.524528      41 reflector.go:150] pkg/mod/k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: Failed to watch metrics.k8s.io/v1beta1, Kind=NodeMetrics: the server does not allow this method on the requested resource 
```
 
![Screenshot 2024-10-29 at 15 35 14](https://github.com/user-attachments/assets/e312b012-2f08-41cf-919b-15e06680263a)

**Comment by richard-cox** [comment]
The error is most probably coming from https://github.com/rancher/dashboard/blob/master/shell/models/provisioning.cattle.io.cluster.js#L248 --> https://github.com/rancher/dashboard/blob/master/shell/models/provisioning.cattle.io.cluster.js#L852-L858. Somehow the metadata.state of the provisioning.cattle.io cluster (or depending on how cluster is classified as rke2) the management.cattle.io version of the same cluster.

Generally the metadata.state is very important for the UI (visually and functionally).

**Comment by moio** [comment]
Is [UI Server-Side Pagination](https://ranchermanager.docs.rancher.com/how-to-guides/advanced-user-guides/enable-experimental-features/ui-server-side-pagination) enabled?

If so, does the problem manifest once it's turned off (both options)?

**Comment by bpedersen2** [comment]
No, I did not have server-side pagination enabled, but the advanced websocket  worker is enabled.

**Comment by niesel** [comment]
@richard-cox 
> If this is happening for other resources and not just provisioning and management clusters there may be an issue with how it's calculated.

It happens with pretty much all Resources in the UI under Workloads, Secrets, Apps, Policy, etc.
At first the state shows as "Active", then after a short time all States switch to "Unknown".
The difference is, when I look at these "normal" resources I don't get the TypeErrors. 
Just those Warnings/Errors appear
```Resource error [management] <blablub.io.xyz> event watch error: an error on the server ("unable to decode an event from the watch stream: http2: response body closed") has prevented the request from succeeding```

The TypeErrors seem to only appear when looking at "Cluster Management > Clusters".

----

@moio 
>Is Server-Side Pagination enabled?
If so, does the problem manifest once it's turned off(both options)?

It wasn't enabled here. 
We've tried some of the UI Performance Settings. They didn't change much in respect to appearance of this errors. It just takes a little longer. Now all UI Performance Settings are disabled. The Errors appear nonetheless.

**Comment by richard-cox** [comment]
@bpedersen2 @niesel thank you both for your quick responses.

@moio @MbolotSuse I would guess that the http request fetching the resources contain the correct metadata.state for the resource and then an update over websocket omits it.

**Comment by nagyclaudiu83** [comment]
![Screenshot_20241118_220738_Samsung Internet.jpg](https://github.com/user-attachments/assets/cded83e4-864a-487a-9a58-c66bb3fca679)

This started working again once I disabled the ui-sql-cache feature flag.

**Comment by niesel** [comment]
> The UI started working as expected once I disabled the ui-sql-cache feature flag.

can confirm this. after disabling the ui-sql-cache it works as expected.

**Comment by richard-cox** [comment]
Thank you both for the update.

The `ui-sql-cache` feature flag was part of the two settings in https://ranchermanager.docs.rancher.com/how-to-guides/advanced-user-guides/enable-experimental-features/ui-server-side-pagination. As a reminder server-side pagination is *not* meant for production and in 2.9 is only beneficial in specific scenarios (though this could all change in 2.11....).
