### ISSUE TITLE
Table 'rancher.setting' doesn't exist

### ISSUE THREAD

**Issue by jtwebman** [rancher/rancher#4792]
* Rancher Version:v1.0.1 and latest

* Docker Version:Docker version 1.11.1, build 5604cbe

* OS and where are the hosts located? (cloud, bare metal, etc): Ubuntu 14.04 on Rackspace

* Setup Details: (single node vs. single node, internal DB vs. external DB)*: single node external database

* Environment Type: (Cattle/Kubernetes/Swarm/Mesos): Haven't gotten this far

* Steps to Reproduce: Just starting using the follow docker command. Password and host stared out:
sudo docker run -d --restart=always -p 8080:8080 -e CATTLE_DB_CATTLE_MYSQL_HOST=%%%.rackspaceclouddb.com -e CATTLE_DB_CATTLE_MYSQL_PORT=3306 -e CATTLE_DB_CATTLE_MYSQL_NAME=rancher -e CATTLE_DB_CATTLE_USERNAME=%%% -e CATTLE_DB_CATTLE_PASSWORD=%%% rancher/server:v1.0.1

* Results: I get this in the logs
2016-05-13 02:13:50,298 ERROR [:] [] [] [] [igurationSource] [c.n.config.AbstractPollingScheduler ] Error getting result from polling source java.sql.SQLSyntaxErrorException: Table 'rancher.setting' doesn't exist
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125) ~[mariadb-java-client-1.3.4.jar:na]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69) ~[mariadb-java-client-1.3.4.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:261) ~[mariadb-java-client-1.3.4.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:290) ~[mariadb-java-client-1.3.4.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:448) ~[mariadb-java-client-1.3.4.jar:na]
	at org.mariadb.jdbc.MariaDbClientPreparedStatement.executeQuery(MariaDbClientPreparedStatement.java:119) ~[mariadb-java-client-1.3.4.jar:na]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96) ~[commons-dbcp-1.4.jar:1.4]
	at com.netflix.config.sources.JDBCConfigurationSource.load(JDBCConfigurationSource.java:107) ~[archaius-core-0.5.14.jar:na]
	at com.netflix.config.sources.JDBCConfigurationSource.poll(JDBCConfigurationSource.java:88) ~[archaius-core-0.5.14.jar:na]
	at io.cattle.platform.archaius.sources.LazyJDBCSource.poll(LazyJDBCSource.java:31) ~[cattle-framework-archaius-0.5.0-SNAPSHOT.jar:na]
	at com.netflix.config.AbstractPollingScheduler$1.run(AbstractPollingScheduler.java:163) ~[archaius-core-0.5.14.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_95]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_95]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_95]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_95]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_95]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_95]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_95]
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Table 'rancher.setting' doesn't exist
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:475) ~[mariadb-java-client-1.3.4.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.result(AbstractQueryProtocol.java:396) ~[mariadb-java-client-1.3.4.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:378) ~[mariadb-java-client-1.3.4.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:334) ~[mariadb-java-client-1.3.4.jar:na]
	at org.mariadb.jdbc.MariaDbSta

* Expected: For it to start up and make the tables

I did run docker exec -t -i containerid /bin/bash and connect successfully to the mariadb it is pointing too so it isn't a network issue.

**Comment by Rucknar** [comment]
@jtwebman Does the DB you connected to have any data in it? Are you able to write to those tables?

**Comment by jtwebman** [comment]
@Rucknar There is nothing in the database and I was able to create a table with that user.

MariaDB [rancher]> CREATE TABLE testing (id INT, data VARCHAR(100));
Query OK, 0 rows affected (0.02 sec)

MariaDB [rancher]> SHOW TABLES;
+-----------------------+
| Tables_in_rancher     |
+-----------------------+
| DATABASECHANGELOGLOCK |
| testing               |
+-----------------------+
2 rows in set (0.00 sec)

**Comment by jtwebman** [comment]
Ok I see the issue was something went wrong and the DATABASECHANGELOGLOCK got in a bad state. Once I dropped this table and restarted docker stable worked no issues. If anyone else runs into this issue make sure to clear the whole database of tables.
