### ISSUE TITLE
Failure to send result to graphite serve

### ISSUE THREAD

**Issue by jmreicha** [rancher/rancher#4816]
**Rancher Version:** `1.0.1`

**Docker Version:** `1.10.1`

**OS and where are the hosts located? (cloud, bare metal, etc):** `CoreOS 970.1.0`

**Setup Details: (single node vs. single node, internal DB vs. external DB)** Single node internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** `Cattle`

**Results:** 

I am seeing the following error being spammed in the Rancher server logs.  I had set up Rancher to use the IP as the Graphite server at one point but that server is no longer available but I don't know how to tell Rancher to stop using it.

Here are the logs.

```
2016-05-16 19:05:56,092 WARN  [:] [] [] [] [xtrans-export-1] [o.j.embedded.output.GraphiteWriter  ] Failure to send result to graphite server 'HostAndPort{host='172.26.1.120', port=2003}' with null java.net.SocketTimeoutException: connect timed out
    at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_95]
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_95]
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_95]
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_95]
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_95]
    at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_95]
    at org.jmxtrans.embedded.util.pool.SocketWriterPoolFactory.makeObject(SocketWriterPoolFactory.java:59) ~[embedded-jmxtrans-1.0.9.jar:na]
    at org.jmxtrans.embedded.util.pool.SocketWriterPoolFactory.makeObject(SocketWriterPoolFactory.java:40) ~[embedded-jmxtrans-1.0.9.jar:na]
    at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220) ~[commons-pool-1.6.jar:1.6]
    at org.jmxtrans.embedded.output.GraphiteWriter.write(GraphiteWriter.java:134) ~[embedded-jmxtrans-1.0.9.jar:na]
    at org.jmxtrans.embedded.Query.exportCollectedMetrics(Query.java:208) [embedded-jmxtrans-1.0.9.jar:na]
    at org.jmxtrans.embedded.EmbeddedJmxTrans$2.run(EmbeddedJmxTrans.java:152) [embedded-jmxtrans-1.0.9.jar:na]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_95]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_95]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_95]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_95]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_95]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_95]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_95]
```

**Expected:**

Is there an easy way to fix this?  I have tried editing the `graphite.host` settings but that hasn't helped.

**Comment by juandavidgc** [comment]
I have the same issue with this environment:

Rancher Version: 1.0.0

Docker Version: 1.11.1

OS and where are the hosts located? (cloud, bare metal, etc): Ubuntu 14.04.3 LTS (3.19.0-25-generic)

Setup Details: (single node vs. single node, internal DB vs. external DB) Single node internal DB

Environment Type: (Cattle/Kubernetes/Swarm/Mesos) Cattle

I've installed "Prometheus" but I uninstall it, and after that the error is appearing.

**Comment by crackmac** [comment]
Same here... I believe this has something to do with uninstalling Prometheus also.

**Comment by crackmac** [comment]
`/usr/share/cattle# cat cattle.sh`

I can see in the run script for cattle that it is setting `CATTLE_GRAPHITE_HOST` and `CATTLE_GRAPHITE_PORT` via environment variables `GRAPHITE_PORT_2003_TCP_ADDR` and `GRAPHITE_PORT_2003_TCP_PORT`

I do not see where or how those environment variables are being passed or set. Could they be set in the database?

**Comment by crackmac** [comment]
To answer my own question... yes

`mysql> use rancherserver;
mysql> select * from setting \G
*************************** 1. row ***************************
   id: 1
 name: api.security.enabled
value: true
... snip ...
*************************** 9. row ***************************
   id: 9
 name: graphite.host
value: 172.128.128.128
9 rows in set (0.00 sec)
`

Delete row with graphite.host. Be careful not to delete anything else and mack a backup of the db first!

`mysql> delete from setting where id = '9';
Query OK, 1 row affected (0.00 sec)
`

**Comment by jmreicha** [comment]
@crackmac I don't seem to have that database, but I do see an entry for it in the `cattle` db.

I'd like to try your method but before I make this change I'd feel better if we could get a blessing from a Rancher person.

**Comment by adamgoose** [comment]
@jmreicha I was able to find the same database table and row in the `cattle` database.

**Comment by vincent99** [comment]
Going to /v1/settings/graphite.host and sending a Delete request is simpler and safer..

**Comment by Rohlik** [comment]
You can also delete this variable in http://your-server:8080/admin/settings in `Advanced Settings`.

**Comment by vincent99** [comment]
@rohlik (in 1.4+ only).

You also have to restart the server container for this  particular setting change to take effect.

I'm assuming this is resolved now...
