### ISSUE TITLE
[BUG] Concurrent updates to annotated SAs when updating secrets

### ISSUE THREAD

**Issue by bigkevmcd** [rancher/rancher#48421]
**Rancher Server Setup**
- Rancher version: rancher:v2.8.6-hotfix-ch.1.8acab23bb
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: 

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**

Concurrent updates to a ServiceAccount Annotations:

```
2024-12-12 06:06:04.762 fatal error: concurrent map iteration and map write
2024-12-12 06:06:04.765 
2024-12-12 06:06:04.765 goroutine 8434014 [running]:
2024-12-12 06:06:04.765 reflect.mapiternext(0x4aad09?)
2024-12-12 06:06:04.765     /usr/lib64/go/1.21/src/runtime/map.go:1397 +0x13
2024-12-12 06:06:04.765 reflect.(*MapIter).Next(0xc48cd1ba38?)
2024-12-12 06:06:04.765     /usr/lib64/go/1.21/src/reflect/value.go:1940 +0x74
2024-12-12 06:06:04.765 encoding/json.mapEncoder.encode({0xc48cd1baf8?}, 0xc265f72840, {0x40ad0a0?, 0xc6a4692838?, 0x0?}, {0xe?, 0x0?})
2024-12-12 06:06:04.765     /usr/lib64/go/1.21/src/encoding/json/encode.go:744 +0x33e
2024-12-12 06:06:04.765 encoding/json.structEncoder.encode({{{0xc0006a5600, 0xf, 0x10}, 0xc001852ae0, 0xc001852b10}}, 0xc265f72840, {0x4a1c240?, 0xc6a46927a0?, 0xb?}, {0x0, ...})
2024-12-12 06:06:04.765     /usr/lib64/go/1.21/src/encoding/json/encode.go:706 +0x21e
2024-12-12 06:06:04.765 encoding/json.structEncoder.encode({{{0xc207689200, 0x6, 0x8}, 0xc12b89db30, 0xc12b89db60}}, 0xc265f72840, {0x47cbe20?, 0xc6a4692780?, 0x496bc5?}, {0x0, ...})
2024-12-12 06:06:04.765     /usr/lib64/go/1.21/src/encoding/json/encode.go:706 +0x21e
2024-12-12 06:06:04.765 encoding/json.ptrEncoder.encode({0x0?}, 0xc265f72840, {0x4ae3660?, 0xc6a4692780?, 0x4ae3660?}, {0x0?, 0x0?})
2024-12-12 06:06:04.765     /usr/lib64/go/1.21/src/encoding/json/encode.go:878 +0x20f
2024-12-12 06:06:04.765 encoding/json.(*encodeState).reflectValue(0xc48cd1bec8?, {0x4ae3660?, 0xc6a4692780?, 0x0?}, {0xa0?, 0xb7?})
2024-12-12 06:06:04.765     /usr/lib64/go/1.21/src/encoding/json/encode.go:323 +0x73
2024-12-12 06:06:04.765 encoding/json.(*encodeState).marshal(0x3d7bba0?, {0x4ae3660?, 0xc6a4692780?}, {0x10?, 0xbc?})
2024-12-12 06:06:04.765     /usr/lib64/go/1.21/src/encoding/json/encode.go:295 +0xb9
2024-12-12 06:06:04.765 encoding/json.(*Encoder).Encode(0xc48cd1bfe0, {0x4ae3660, 0xc6a4692780})
2024-12-12 06:06:04.765     /usr/lib64/go/1.21/src/encoding/json/stream.go:209 +0xdf
2024-12-12 06:06:04.765 k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).doEncode(0x4b5b6fc?, {0x5637960?, 0xc6a4692780?}, {0x5624f80, 0xc391900450})
2024-12-12 06:06:04.765     /go/pkg/mod/k8s.io/apimachinery@v0.28.6/pkg/runtime/serializer/json/json.go:246 +0x175
2024-12-12 06:06:04.765 k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Encode(0xc0009f45f0, {0x5637960, 0xc6a4692780}, {0x5624f80, 0xc391900450})
2024-12-12 06:06:04.765     /go/pkg/mod/k8s.io/apimachinery@v0.28.6/pkg/runtime/serializer/json/json.go:220 +0xf2
2024-12-12 06:06:04.765 k8s.io/apimachinery/pkg/runtime.WithVersionEncoder.Encode({{0x5637cd0, 0xc026296340}, {0x563dcb8, 0xc0009f45f0}, {0x5637d70, 0xc0005f7ea0}}, {0x5637960, 0xc6a4692780}, {0x5624f80, 0xc391900450})
2024-12-12 06:06:04.765     /go/pkg/mod/k8s.io/apimachinery@v0.28.6/pkg/runtime/helper.go:240 +0x2a5
2024-12-12 06:06:04.765 k8s.io/apimachinery/pkg/runtime.Encode({0x563cca0, 0xc391900420}, {0x5637960, 0xc6a4692780})
2024-12-12 06:06:04.765     /go/pkg/mod/k8s.io/apimachinery@v0.28.6/pkg/runtime/codec.go:49 +0x5e
2024-12-12 06:06:04.765 k8s.io/client-go/rest.(*Request).Body(0xc47808cc60, {0x4ae3660?, 0xc6a4692780?})
2024-12-12 06:06:04.765     /go/pkg/mod/github.com/rancher/client-go@v1.28.6-rancher1/rest/request.go:470 +0x434
2024-12-12 06:06:04.765 k8s.io/client-go/kubernetes/typed/core/v1.(*serviceAccounts).Update(0xc0af34e160, {0x5666d38, 0x84aea80}, 0xc6a4692780, {{{0x0, 0x0}, {0x0, 0x0}}, {0x0, 0x0, ...}, ...})
2024-12-12 06:06:04.765     /go/pkg/mod/github.com/rancher/client-go@v1.28.6-rancher1/kubernetes/typed/core/v1/serviceaccount.go:139 +0x166
2024-12-12 06:06:04.765 github.com/rancher/rancher/pkg/serviceaccounttoken.annotateSAWithSecret({0x5666d38, 0x84aea80}, 0xc6a4692780, 0xc4ea9db040, {0x5687fb8, 0xc0af34e160}, {0x567b8e0, 0xc110ae8e40})
2024-12-12 06:06:04.765     /app/pkg/serviceaccounttoken/secret.go:263 +0x1df
```

**Backports**

- [ ] #48469
- [ ] #48470

**Comment by bigkevmcd** [comment]
## Validation Template

## What was fixed, or what change has occurred

Sometimes when updating a created access secret, updating the annotations would cause an error (concurrent access to map).

## Areas or cases that should be tested

This will appear in the logs (and cause the container to crash).

* Add a cluster with the cache-mitigation bug to Rancher (this is in `HEAD`), and during the setup of service-account creation, it _may_ fail depending on how concurrently it accesses things.

## What areas could experience regressions

None, this is a fairly straightforward bug fix.

## Are the repro steps accurate/minimal?

**Comment by nickwsuse** [comment]
Verified on v2.11-head ID: 2053ce6 ✅ 
----
Since this isn't a bug that is guaranteed to happen, I created 10 different local and 20 different downstream clusters (two per local cluster). Then I enabled Active Directory with a Service Account and did not see this error at any point.
