### ISSUE TITLE
[BUG] Panic in nodesyncer

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#48428]
**Rancher Server Setup**
- Rancher version: v2.9.4

**Describe the bug**

The nodesyncer can panic with the following error:
```
E1212 18:01:26.687496      39 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 21371 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x82a1c60, 0x100f0fa0})
	/go/pkg/mod/k8s.io/apimachinery@v0.30.1/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc04532bf50?})
	/go/pkg/mod/k8s.io/apimachinery@v0.30.1/pkg/util/runtime/runtime.go:49 +0x6b
panic({0x82a1c60?, 0x100f0fa0?})
	/usr/lib64/go/1.22/src/runtime/panic.go:770 +0x132
github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer.(*nodeSyncer).sync(0xc02c3f7710, {0xc0281292e0?, 0x0?}, 0x0)
	/app/pkg/controllers/managementuser/nodesyncer/nodessyncer.go:176 +0x11f
github.com/rancher/rancher/pkg/generated/norman/core/v1.(*nodeController).AddHandler.func1({0xc0281292e0?, 0x10?}, {0x0?, 0x0?})
	/app/pkg/generated/norman/core/v1/zz_generated_node_controller.go:153 +0x62
github.com/rancher/norman/controller.(*genericController).AddHandler.func1({0xc0281292e0, 0x10}, {0x0, 0x0})
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20240708202514-a0127673d1b9/controller/generic_controller.go:57 +0x170
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc0130a6a80?, {0xc0281292e0?, 0xc023a8fc68?}, {0x0?, 0x0?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240923125127-ae858d002589/pkg/controller/sharedcontroller.go:29 +0x32
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc02be572c0, {0xc0281292e0, 0x10}, {0x0, 0x0})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240923125127-ae858d002589/pkg/controller/sharedhandler.go:75 +0x202
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc001398840, {0xc0281292e0, 0x10})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240923125127-ae858d002589/pkg/controller/controller.go:233 +0x8b
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc001398840, {0x79d6560, 0xc04532bf50})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240923125127-ae858d002589/pkg/controller/controller.go:217 +0xeb
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc001398840)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240923125127-ae858d002589/pkg/controller/controller.go:194 +0x45
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240923125127-ae858d002589/pkg/controller/controller.go:183
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	/go/pkg/mod/k8s.io/apimachinery@v0.30.1/pkg/util/wait/backoff.go:226 +0x33
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc014f8baf0, {0xaec5e20, 0xc0133f17d0}, 0x1, 0xc01886cf00)
	/go/pkg/mod/k8s.io/apimachinery@v0.30.1/pkg/util/wait/backoff.go:227 +0xaf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc014f8baf0, 0x3b9aca00, 0x0, 0x1, 0xc01886cf00)
	/go/pkg/mod/k8s.io/apimachinery@v0.30.1/pkg/util/wait/backoff.go:204 +0x7f
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.30.1/pkg/util/wait/backoff.go:161
created by github.com/rancher/lasso/pkg/controller.(*controller).run in goroutine 21235
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240923125127-ae858d002589/pkg/controller/controller.go:151 +0x2ba
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x230 pc=0x594267f]
```

**To Reproduce**

**Result**

Rancher panics

**Expected Result**

No panic

**Screenshots**

**Additional context**

**Comment by Josh-Diamond** [comment]
Ticket #48428 - Test Results - ✅ 
---

Verified on Rancher `v2.11-b435a2d786c50b03bd1ba7279a6a621ebcd19c84-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision 3 downstream RKE1 Node driver clusters; ensure no panics seen | ✅ |
| 2. | Provision 3 downstream RKE2 Node driver clusters; ensure no panics seen | ✅ |
| 3. | Provision 3 downstream K3s Node driver clusters; ensure no panics seen | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.11-head`
2. Provision 3 downstream RKE1 AWS Node driver clusters
3. Verified - clusters successfully provision; clean logs; no panics

---

Scenario 2 - ✅ 
1. Fresh install of Rancher `v2.11-head`
2. Provision 3 downstream RKE2 AWS Node driver clusters
3. Verified - clusters successfully provision; clean logs; no panics

---

Scenario 3 - ✅ 
1. Fresh install of Rancher `v2.11-head`
2. Provision 3 downstream K3s AWS Node driver clusters
3. Verified - clusters successfully provision; clean logs; no panics
