### ISSUE TITLE
Statically compiled cadvisor can crash under certain circumstances

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#4848]
**Rancher Version:**
1.0.1

**Docker Version:**
```
$ docker info
Containers: 8
Running: 6
Paused: 0
Stopped: 2
Images: 6
Server Version: 1.10.2
Storage Driver: devicemapper
Pool Name: docker-253:2-201326720-pool
Pool Blocksize: 65.54 kB
Base Device Size: 10.74 GB
Backing Filesystem: xfs
Data file: /dev/loop0
Metadata file: /dev/loop1
Data Space Used: 1.874 GB
Data Space Total: 107.4 GB
Data Space Available: 44.98 GB
Metadata Space Used: 3.432 MB
Metadata Space Total: 2.147 GB
Metadata Space Available: 2.144 GB
Udev Sync Supported: true
Deferred Removal Enabled: false
Deferred Deletion Enabled: false
Deferred Deleted Device Count: 0
Data loop file: /apps/docker/devicemapper/devicemapper/data
WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
Metadata loop file: /apps/docker/devicemapper/devicemapper/metadata
Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
Volume: local
Network: bridge null host
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.52 GiB
Name: mstlva-dsnsmt12
ID: EEHT:CD7T:UYTH:KMHO:YEZR:M2EY:RXFZ:ZREG:ZXPN:MULA:OUFH:ED4M
Http Proxy: http://bcpxy.nycnet:8080/
Https Proxy: http://bcpxy.nycnet:8080/
No Proxy: localhost,127.0.0.1,10.155.*
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**OS and where are the hosts located? (cloud, bare metal, etc):**
RHEL 7.2 

**Steps to Reproduce:**
Can't reproduce consistently

Here's the stack trace from the panc:
```
Monitoring mount context of PID 14244
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0xe58500, 0x2a)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x9ed680, 0xc82004dc60, 0xc800000000)
	/usr/local/go/src/runtime/cgocall.go:120 +0x11b fp=0xc82004dc10 sp=0xc82004dbe0
os/user._Cfunc_mygetpwuid_r(0x0, 0xc8200133b0, 0x169cf40, 0x400, 0xc82002c040, 0x0)
	??:0 +0x39 fp=0xc82004dc60 sp=0xc82004dc10
os/user.lookupUnix(0x0, 0x0, 0x0, 0xc82004db00, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/user/lookup_unix.go:99 +0x723 fp=0xc82004ddd0 sp=0xc82004dc60
os/user.current(0xd453a8, 0x0, 0x0)
	/usr/local/go/src/os/user/lookup_unix.go:39 +0x42 fp=0xc82004de10 sp=0xc82004ddd0
os/user.Current(0xc820018e50, 0x0, 0x0)
	/usr/local/go/src/os/user/lookup.go:9 +0x24 fp=0xc82004de30 sp=0xc82004de10
github.com/golang/glog.init.2()
	/source/build/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog_file.go:63 +0x81 fp=0xc82004dea0 sp=0xc82004de30
github.com/golang/glog.init()
	/source/build/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog_file.go:124 +0x1b8 fp=0xc82004dee0 sp=0xc82004dea0
github.com/google/cadvisor/events.init()
	/source/build/src/github.com/google/cadvisor/events/handler.go:334 +0x54 fp=0xc82004dee8 sp=0xc82004dee0
github.com/google/cadvisor/api.init()
	/source/build/src/github.com/google/cadvisor/api/versions.go:543 +0x74 fp=0xc82004df08 sp=0xc82004dee8
github.com/google/cadvisor/http.init()
	/source/build/src/github.com/google/cadvisor/http/handlers.go:110 +0x45 fp=0xc82004df10 sp=0xc82004df08
main.init()
	/source/build/src/github.com/google/cadvisor/storagedriver.go:48 +0x74 fp=0xc82004df50 sp=0xc82004df10
runtime.main()
	/usr/local/go/src/runtime/proc.go:100 +0x27f fp=0xc82004dfa0 sp=0xc82004df50
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc82004dfa8 sp=0xc82004dfa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 6 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x14c1720)
	/source/build/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:882 +0x67
created by github.com/golang/glog.init.1
	/source/build/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x297
```

It is pretty clear that `os/user._Cfunc_mygetpwuid_r` is the root cause. This particular function is known to cause problems under certain circumstances when used in a statically link go binary.

Since we originally implemented the statically compiled cadvisor, it appears k8s has figured out how to launch it properly without statically compiling it. We need to reverse engineer that and do the same.

**Comment by cjellick** [comment]
IMPORTANT: We originally had problems with cadvisor and coreos so we need to make sure whatever fix we implement doesnt cause a regression there

**Comment by ibuildthecloud** [comment]
https://github.com/rancher/cattle/pull/1757

**Comment by ibuildthecloud** [comment]
cadvisor is now compilied with musl and should also support Docker 1.11 now.

**Comment by soumyalj** [comment]
Verified with v1.1.0-dev5-rc2. Stats are showing up for containers and hosts for both Docker 1.10.3 and 1.11.2
