### ISSUE TITLE
Route53 DNS service (from official catalog) continously crashing

### ISSUE THREAD

**Issue by Kelindar** [rancher/rancher#4881]
**Rancher Version:**
1.0.1 and rancher/external-dns:v0.4.0 (route53)

**Docker Version:**
1.10.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
cloud, AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher with external DB on AWS RDS

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Simply selecting and starting Route53 DNS from the catalog

**Results:** 
The service crashes continuously, with the output below in the logs:

```
5/22/2016 1:21:36 AMmain.startHealthcheck()
5/22/2016 1:21:36 AM	/source/healthcheck.go:17 +0x28c
5/22/2016 1:21:36 AMcreated by main.main
5/22/2016 1:21:36 AM	/source/main.go:91 +0x1aa
5/22/2016 1:21:36 AM
5/22/2016 1:21:36 AMgoroutine 17 [IO wait]:
5/22/2016 1:21:36 AMnet.runtime_pollWait(0x7fb7ac211ca0, 0x72, 0xc82000a150)
5/22/2016 1:21:36 AM	/usr/local/go/src/runtime/netpoll.go:157 +0x60
5/22/2016 1:21:36 AMnet.(*pollDesc).Wait(0xc82011e060, 0x72, 0x0, 0x0)
5/22/2016 1:21:36 AM	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
5/22/2016 1:21:36 AMnet.(*pollDesc).WaitRead(0xc82011e060, 0x0, 0x0)
5/22/2016 1:21:36 AM	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
5/22/2016 1:21:36 AMnet.(*netFD).Read(0xc82011e000, 0xc820120000, 0x1000, 0x1000, 0x0, 0x7fb7ac20c050, 0xc82000a150)
5/22/2016 1:21:36 AM	/usr/local/go/src/net/fd_unix.go:232 +0x23a
5/22/2016 1:21:36 AMnet.(*conn).Read(0xc820028148, 0xc820120000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
5/22/2016 1:21:36 AM	/usr/local/go/src/net/net.go:172 +0xe4
5/22/2016 1:21:36 AMnet/http.noteEOFReader.Read(0x7fb7ac211ff8, 0xc820028148, 0xc8200af4f8, 0xc820120000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
5/22/2016 1:21:36 AM	/usr/local/go/src/net/http/transport.go:1370 +0x67
5/22/2016 1:21:36 AMnet/http.(*noteEOFReader).Read(0xc82011a820, 0xc820120000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
5/22/2016 1:21:36 AM	<autogenerated>:126 +0xd0
5/22/2016 1:21:36 AMbufio.(*Reader).fill(0xc82001ade0)
5/22/2016 1:21:36 AM	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
5/22/2016 1:21:36 AMbufio.(*Reader).Peek(0xc82001ade0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
5/22/2016 1:21:36 AM	/usr/local/go/src/bufio/bufio.go:132 +0xcc
5/22/2016 1:21:36 AMnet/http.(*persistConn).readLoop(0xc8200af4a0)
5/22/2016 1:21:36 AM	/usr/local/go/src/net/http/transport.go:876 +0xf7
5/22/2016 1:21:36 AMcreated by net/http.(*Transport).dialConn
5/22/2016 1:21:36 AM	/usr/local/go/src/net/http/transport.go:685 +0xc78
5/22/2016 1:21:36 AM
5/22/2016 1:21:36 AMgoroutine 39 [IO wait]:
5/22/2016 1:21:36 AMnet.runtime_pollWait(0x7fb7ac2119a0, 0x72, 0xc82000a150)
5/22/2016 1:21:36 AM	/usr/local/go/src/runtime/netpoll.go:157 +0x60
5/22/2016 1:21:36 AMnet.(*pollDesc).Wait(0xc8201b2ca0, 0x72, 0x0, 0x0)
5/22/2016 1:21:36 AM	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
5/22/2016 1:21:36 AMnet.(*pollDesc).WaitRead(0xc8201b2ca0, 0x0, 0x0)
5/22/2016 1:21:36 AM	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
5/22/2016 1:21:36 AMnet.(*netFD).Read(0xc8201b2c40, 0xc8204a2400, 0x400, 0x400, 0x0, 0x7fb7ac20c050, 0xc82000a150)
5/22/2016 1:21:36 AM	/usr/local/go/src/net/fd_unix.go:232 +0x23a
5/22/2016 1:21:36 AMnet.(*conn).Read(0xc820028728, 0xc8204a2400, 0x400, 0x400, 0x0, 0x0, 0x0)
5/22/2016 1:21:36 AM	/usr/local/go/src/net/net.go:172 +0xe4
5/22/2016 1:21:36 AMcrypto/tls.(*block).readFromUntil(0xc8204bf140, 0x7fb7ac211ff8, 0xc820028728, 0x5, 0x0, 0x0)
5/22/2016 1:21:36 AM	/usr/local/go/src/crypto/tls/conn.go:455 +0xcc
5/22/2016 1:21:36 AMcrypto/tls.(*Conn).readRecord(0xc8200878c0, 0xc15e17, 0x0, 0x0)
5/22/2016 1:21:36 AM	/usr/local/go/src/crypto/tls/conn.go:540 +0x2d1
5/22/2016 1:21:36 AMcrypto/tls.(*Conn).Read(0xc8200878c0, 0xc8201df000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
5/22/2016 1:21:36 AM	/usr/local/go/src/crypto/tls/conn.go:901 +0x167
5/22/2016 1:21:36 AMnet/http.noteEOFReader.Read(0x7fb7ac223970, 0xc8200878c0, 0xc82017e7e8, 0xc8201df000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
5/22/2016 1:21:36 AM	/usr/local/go/src/net/http/transport.go:1370 +0x67
5/22/2016 1:21:36 AMnet/http.(*noteEOFReader).Read(0xc8204d2320, 0xc8201df000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
5/22/2016 1:21:36 AM	<autogenerated>:126 +0xd0
5/22/2016 1:21:36 AMbufio.(*Reader).fill(0xc8204d40c0)
5/22/2016 1:21:36 AM	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
5/22/2016 1:21:36 AMbufio.(*Reader).Peek(0xc8204d40c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
5/22/2016 1:21:36 AM	/usr/local/go/src/bufio/bufio.go:132 +0xcc
5/22/2016 1:21:36 AMnet/http.(*persistConn).readLoop(0xc82017e790)
5/22/2016 1:21:36 AM	/usr/local/go/src/net/http/transport.go:876 +0xf7
5/22/2016 1:21:36 AMcreated by net/http.(*Transport).dialConn
5/22/2016 1:21:36 AM	/usr/local/go/src/net/http/transport.go:685 +0xc78
5/22/2016 1:21:36 AM
5/22/2016 1:21:36 AMgoroutine 18 [select]:
5/22/2016 1:21:36 AMnet/http.(*persistConn).writeLoop(0xc8200af4a0)
5/22/2016 1:21:36 AM	/usr/local/go/src/net/http/transport.go:1009 +0x40c
5/22/2016 1:21:36 AMcreated by net/http.(*Transport).dialConn
5/22/2016 1:21:36 AM	/usr/local/go/src/net/http/transport.go:686 +0xc9d
5/22/2016 1:21:36 AM
5/22/2016 1:21:36 AMgoroutine 29 [IO wait]:
5/22/2016 1:21:36 AMnet.runtime_pollWait(0x7fb7ac211a60, 0x72, 0xc82000a150)
5/22/2016 1:21:36 AM	/usr/local/go/src/runtime/netpoll.go:157 +0x60
5/22/2016 1:21:36 AMnet.(*pollDesc).Wait(0xc82011eca0, 0x72, 0x0, 0x0)
5/22/2016 1:21:36 AM	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
5/22/2016 1:21:36 AMnet.(*pollDesc).WaitRead(0xc82011eca0, 0x0, 0x0)
5/22/2016 1:21:36 AM	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
5/22/2016 1:21:36 AMnet.(*netFD).Read(0xc82011ec40, 0xc820138000, 0x1000, 0x1000, 0x0, 0x7fb7ac20c050, 0xc82000a150)
5/22/2016 1:21:36 AM	/usr/local/go/src/net/fd_unix.go:232 +0x23a
5/22/2016 1:21:36 AMnet.(*conn).Read(0xc820028610, 0xc820138000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
5/22/2016 1:21:36 AM	/usr/local/go/src/net/net.go:172 +0xe4
5/22/2016 1:21:36 AMnet/http.noteEOFReader.Read(0x7fb7ac211ff8, 0xc820028610, 0xc8200af868, 0xc820138000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
5/22/2016 1:21:36 AM	/usr/local/go/src/net/http/transport.go:1370 +0x67
5/22/2016 1:21:36 AMnet/http.(*noteEOFReader).Read(0xc82011ba20, 0xc820138000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
5/22/2016 1:21:36 AM	<autogenerated>:126 +0xd0
5/22/2016 1:21:36 AMbufio.(*Reader).fill(0xc82001be60)
5/22/2016 1:21:36 AM	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
5/22/2016 1:21:36 AMbufio.(*Reader).Peek(0xc82001be60, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
5/22/2016 1:21:36 AM	/usr/local/go/src/bufio/bufio.go:132 +0xcc
5/22/2016 1:21:36 AMnet/http.(*persistConn).readLoop(0xc8200af810)
5/22/2016 1:21:36 AM	/usr/local/go/src/net/http/transport.go:876 +0xf7
5/22/2016 1:21:36 AMcreated by net/http.(*Transport).dialConn
5/22/2016 1:21:36 AM	/usr/local/go/src/net/http/transport.go:685 +0xc78
5/22/2016 1:21:36 AM
5/22/2016 1:21:36 AMgoroutine 30 [select]:
5/22/2016 1:21:36 AMnet/http.(*persistConn).writeLoop(0xc8200af810)
5/22/2016 1:21:36 AM	/usr/local/go/src/net/http/transport.go:1009 +0x40c
5/22/2016 1:21:36 AMcreated by net/http.(*Transport).dialConn
5/22/2016 1:21:36 AM	/usr/local/go/src/net/http/transport.go:686 +0xc9d
5/22/2016 1:21:36 AM
5/22/2016 1:21:36 AMgoroutine 40 [select]:
5/22/2016 1:21:36 AMnet/http.(*persistConn).writeLoop(0xc82017e790)
5/22/2016 1:21:36 AM	/usr/local/go/src/net/http/transport.go:1009 +0x40c
5/22/2016 1:21:36 AMcreated by net/http.(*Transport).dialConn
5/22/2016 1:21:36 AM	/usr/local/go/src/net/http/transport.go:686 +0xc9d
```

![image](https://cloud.githubusercontent.com/assets/583116/15451313/6cd53a42-1fbc-11e6-81e0-76365dc7fdfd.png)

Any idea why and how can I fix this?

**Comment by deniseschannon** [comment]
I am unable to reproduce this. I was able to successfully launch with v1.0.2 and v1.1.0-dev3. 

The only difference is that I see is that I am running Docker 1.10.3, but I don't think that would be the reason why it works for me and not work you. 

What OS are you using? I am using Ubuntu 14.04 in my setup.

**Comment by Kelindar** [comment]
I'm using Ubuntu 14.04 as well. Rancher DNS was actually working before, but it started crashing right after I updated to the last version (I've been continuously updating it). I'm going to try to run it on a few different virtual machines and see why this happens.

**Comment by mvriel** [comment]
We are having the same issues; our entire stack works flawlessly but the Route 53 container keeps crashing with the exact same messages as above. We use Docker 1.10.2 on Debian.

**Comment by mvriel** [comment]
I just removed the route53 catalog item and reinstalled it using version 0.3; now it works as expected

**Comment by deniseschannon** [comment]
@Kelindar @mvriel We just made an update to the Route53 catalog entry, latest version 4.1. 

It sounds like you might have been hitting this issue: https://github.com/rancher/rancher/issues/4949

Please re-open or open a new issue if the latest template doens't work for you.
