### ISSUE TITLE
Cloned VMs fails with error -object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4940]
Rancher Version: Build from master

Hosts - 3 packets machine with ROS version - 4.5

Steps to reproduce the problem:

Deploy a VM. VM deploys successfully.
Clone this VM (Change the name of the VM)
Vm is stuck in "Starting" state for a while and then it gets to Error state with error message - Error (object of type 'NoneType' has no len())

Following exception seen in agent logs:

```
pResourceId":"59","processUuid":"842baa42-c4ac-40cf-988b-7e67866ed61a"}} 
2016-05-27 16:52:54,115 INFO agent [140712699037488] [utils.py:430] worker17 : Starting request 93c709c7-5e20-4747-810b-79347cbd3052 for compute.instance.activate 
2016-05-27 16:52:54,120 INFO agent [140712699037488] [utils.py:430] worker17 : Done request 93c709c7-5e20-4747-810b-79347cbd3052 for compute.instance.activate [0.00487995147705] second
s 
2016-05-27 16:52:54,120 ERROR agent [140712699037488] [event.py:112] Error in request : 93c709c7-5e20-4747-810b-79347cbd3052 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 34, in execute
    return method(req=req, **req.data.__dict__)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 529, in instance_activate
    self._do_instance_activate(instance, host, progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 575, in _do_instance_activate
    self._setup_dns_search(start_config, instance)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 402, in _setup_dns_search
    if len(dns_search) == 0:
TypeError: object of type 'NoneType' has no len()
2016-05-27 16:52:54,129 INFO agent [140712699037488] [utils.py:430] Response: {"name": "reply.3967790740032374375", "resourceType": "instanceHostMap", "resourceId": "1ihm59", "id": "ad
7336db-88f0-4f0e-9533-e96f0b555000", "transitioningInternalMessage": "object of type 'NoneType' has no len()", "time": 1464367974000, "previousNames": ["compute.instance.activate"], "t
ransitioning": "error", "data": {}, "previousIds": ["93c709c7-5e20-4747-810b-79347cbd3052"]} [0.00906991958618] seconds 
```

**Comment by sangeethah** [comment]
Tested with latest build from master:
VMs that get cloned from existing vms are able to start successfully.
