### ISSUE TITLE
upgrade catalog(certified) jenkins-ci stack,rancher compose plugin list not work?

### ISSUE THREAD

**Issue by Dreampie** [rancher/rancher#4951]
```

2016年5月30日 GMT+8 下午12:59:14May 30, 2016 4:59:14 AM jenkins.InitReactorRunner$1 onTaskFailed
2016年5月30日 GMT+8 下午12:59:14SEVERE: Failed Inspecting plugin /var/jenkins_home/plugins/git.jpi
2016年5月30日 GMT+8 下午12:59:14java.io.IOException: Failed to expand /var/jenkins_home/plugins/git.jpi
2016年5月30日 GMT+8 下午12:59:14	at hudson.ClassicPluginStrategy.explode(ClassicPluginStrategy.java:532)
2016年5月30日 GMT+8 下午12:59:14	at hudson.ClassicPluginStrategy.createPluginWrapper(ClassicPluginStrategy.java:167)
2016年5月30日 GMT+8 下午12:59:14	at hudson.PluginManager$1$3$1.run(PluginManager.java:289)
2016年5月30日 GMT+8 下午12:59:14	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
2016年5月30日 GMT+8 下午12:59:14	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
2016年5月30日 GMT+8 下午12:59:14	at jenkins.model.Jenkins$8.runTask(Jenkins.java:926)
2016年5月30日 GMT+8 下午12:59:14	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
2016年5月30日 GMT+8 下午12:59:14	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
2016年5月30日 GMT+8 下午12:59:14	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2016年5月30日 GMT+8 下午12:59:14	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2016年5月30日 GMT+8 下午12:59:14	at java.lang.Thread.run(Thread.java:745)
2016年5月30日 GMT+8 下午12:59:14Caused by: Error while expanding /var/jenkins_home/plugins/git.jpi
2016年5月30日 GMT+8 下午12:59:14java.util.zip.ZipException: archive is not a ZIP archive
2016年5月30日 GMT+8 下午12:59:14	at org.apache.tools.ant.taskdefs.Expand.expandFile(Expand.java:192)
2016年5月30日 GMT+8 下午12:59:14	at org.apache.tools.ant.taskdefs.Expand.execute(Expand.java:132)
2016年5月30日 GMT+8 下午12:59:14	at hudson.ClassicPluginStrategy.unzipExceptClasses(ClassicPluginStrategy.java:604)
2016年5月30日 GMT+8 下午12:59:14	at hudson.ClassicPluginStrategy.explode(ClassicPluginStrategy.java:529)
2016年5月30日 GMT+8 下午12:59:14	... 10 more
2016年5月30日 GMT+8 下午12:59:14Caused by: java.util.zip.ZipException: archive is not a ZIP archive
2016年5月30日 GMT+8 下午12:59:14	at org.apache.tools.zip.ZipFile.positionAtCentralDirectory(ZipFile.java:481)
2016年5月30日 GMT+8 下午12:59:14	at org.apache.tools.zip.ZipFile.populateFromCentralDirectory(ZipFile.java:320)
2016年5月30日 GMT+8 下午12:59:14	at org.apache.tools.zip.ZipFile.<init>(ZipFile.java:186)
2016年5月30日 GMT+8 下午12:59:14	at org.apache.tools.ant.taskdefs.Expand.expandFile(Expand.java:170)
2016年5月30日 GMT+8 下午12:59:14	... 13 more
2016年5月30日 GMT+8 下午12:59:14
2016年5月30日 GMT+8 下午12:59:20May 30, 2016 4:59:20 AM jenkins.InitReactorRunner$1 onAttained
2016年5月30日 GMT+8 下午12:59:20INFO: Listed all plugins
```

**Comment by deniseschannon** [comment]
Can you provide more details on what you are trying to do?

**Comment by Dreampie** [comment]
I recreate stack,it's ok ,but jenkins-ci can't set Volume when build it ?

**Comment by deniseschannon** [comment]
Unfortunatly, I am still not clear on the steps you are taking specifically to run into this error. Would you be able ot provide more details about it? 

Jenkins-CI isn't a certified stack, so I'm slightly confused.

**Comment by deniseschannon** [comment]
@Dreampie If you could provide more details on exact steps that you are doing, please re-open. As mentioned, I wasn't able to follow your steps so cannot help attempt to reproduce.
