### ISSUE TITLE
"Can not start container with no image" even with image correctly set

### ISSUE THREAD

**Issue by jloisel** [rancher/rancher#4995]
**Rancher Version:** v1.0.2

**Docker Version:** 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):** Amazon AWS, Ubuntu 14.04.3LTS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single server Rancher, internal DB, external docker node for container execution

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** Launched a container via the Rest api. Sometimes it fails with the following error message:
Stopped (Can not start container with no image)
When inspecting the docker container config imageUuid is correctly set:
"imageUuid": "docker:octoperf/jmeter:3.0.0",

**Results:** Should not fail. We launch all our containers via the API the same way, just a few of them fail because of this issue.

**Expected:** No issue with image.

**Comment by deniseschannon** [comment]
So it doesn't consistently fail? If you ran the same API command, it might succeed at a later time?

**Comment by jloisel** [comment]
It randomly fails. Running the same container from API again runs fine. the failed container doesn't start at all, even when trying to restart it from Rancher UI.

**Comment by jloisel** [comment]
When cloning the container, the cloned container launches successfully. But the original one still fails.

**Comment by jloisel** [comment]
We have reverted back to Rancher v1.0.1 and no longer see the issue happening. It seems like a regression in Rancher v1.0.2.

**Comment by deniseschannon** [comment]
@jloisel I'm surprised to hear that it would affect 1.0.2 but not 1.0.1. We only cherry picked a couple of ocmmits into 1.0.2 and nothing is around the area that you are working on.

https://github.com/rancher/rancher/issues/4722

There have been a lot of changes in our v1.1.0-devX releases. Would you be willing to try out v1.1.0-dev3 to see if you still hit this issue?

**Comment by jloisel** [comment]
We can't take the developer version on production server. As the issue is random, it's difficult to reproduce, we couldn't reproduce the issue on our local machines yet. Anyway, we don't have the issue anymore since we downgraded to v1.0.1 as strange as it seems. We changed only that.

**Comment by jloisel** [comment]
Maybe it's related to the fact we're having processes stuck on running state on our rancher instance? See the issue here: https://github.com/rancher/rancher/issues/4974

**Comment by jloisel** [comment]
We confirm that after downgrading to 1.0.1 we haven't had the issue anymore. 1.0.2 has very few changes but somehow one of them broke launching containers somehow.

**Comment by jloisel** [comment]
This issue is now critical, after migrating to a new server with a fresh install, we're getting this error 100% of time. Here are the logs from the agent which fails to load the image:

> Exception: Can not start container with no image
2016-06-29 20:12:41,322 ERROR agent [140257608509552] [event.py:112] Error in request : d463b12d-c721-4b02-83e1-9bae94172e4b 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 34, in execute
    return method(req=req, **req.data.__dict__)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 529, in instance_activate
    self._do_instance_activate(instance, host, progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 541, in _do_instance_activate
    image_tag = self._get_image_tag(instance)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 724, in _get_image_tag
    raise Exception('Can not start container with no image')
Exception: Can not start container with no image

**Comment by jloisel** [comment]
We have a Rancher instance which consistantly reproduces the issue, we can provide an access if you need to.

**Comment by jloisel** [comment]
Here is a typical payload when we call api.container.create:

> {
  "imageUuid": "docker:octoperf/jmeter:3.1.0",
  "startOnCreate": false,
  "labels": {
    "io.rancher.container.start_once": "true",
    "io.rancher.scheduler.affinity:host_label": "machine.providerId=xxx,machine.region=eu-west-1",
    "io.rancher.scheduler.affinity:host_label_soft": "machine.name=hyper-shadow"
  },
  "dns": [],
  "networkMode": "host",
  "hostname": "subjective_racism",
  "stdinOpen": true,
  "environment": {
    "API_KEY": "xxxx"
  },
  "description": "",
  "name": "random-name",
  "tty": true,
  "version": "0",
  "publishAllPorts": false,
  "privileged": false,
  "readOnly": false
}

**Comment by jloisel** [comment]
After investigating, we may have found a potential issue: we consecutively create and start containers via api calls, at very fast pace. It seems like Rancher fails to launch the containers when trying to start a container which is still in "creating" state. Maybe there is a race condition on Rancher side.

By ensuring the container is created before trying to start it, it seems like the issue is not seen anymore.

**Comment by will-chan** [comment]
Closing due to inactivity, please reopen if you think this is still relevant to current releases & important.
