### ISSUE TITLE
rancher-ingress-controller panic - index out of range

### ISSUE THREAD

**Issue by joshrendek** [rancher/rancher#5008]
**Rancher Version:**
v1.1.0-dev3

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu (Private Proxmox cluster)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, 1 docker node (so far to tesT)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Switch environment from Cattle to Kubernetes

**Results:** 
Kubernetes stack rancher-ingress-controller flaps yellow and crashes with:

```
6/4/2016 11:10:29 AMtime="2016-06-04T15:10:29Z" level=info msg="starting kubernetes-ingress-controller"
6/4/2016 11:10:29 AMtime="2016-06-04T15:10:29Z" level=info msg="Healthcheck handler is listening on :10241"
6/4/2016 11:10:59 AMpanic: runtime error: index out of range
6/4/2016 11:10:59 AM
6/4/2016 11:10:59 AMgoroutine 38 [running]:
6/4/2016 11:10:59 AMpanic(0x1407760, 0xc82001c020)
6/4/2016 11:10:59 AM	/usr/local/go/src/runtime/panic.go:481 +0x3e6
6/4/2016 11:10:59 AMgithub.com/rancher/ingress-controller/lbprovider.(*RancherLBProvider).syncupEndpoints(0xc8203005c0, 0x0, 0x0)
6/4/2016 11:10:59 AM	/go/src/github.com/rancher/ingress-controller/lbprovider/rancher.go:152 +0x452
6/4/2016 11:10:59 AMcreated by github.com/rancher/ingress-controller/lbprovider.(*RancherLBProvider).Run
6/4/2016 11:10:59 AM	/go/src/github.com/rancher/ingress-controller/lbprovider/rancher.go:133 +0x91
6/4/2016 11:11:01 AMtime="2016-06-04T15:11:01Z" level=info msg="Starting Rancher LB service"
6/4/2016 11:11:01 AMtime="2016-06-04T15:11:01Z" level=info msg="LB controller: kubernetes"
6/4/2016 11:11:01 AMtime="2016-06-04T15:11:01Z" level=info msg="LB provider: rancher"
6/4/2016 11:11:01 AMtime="2016-06-04T15:11:01Z" level=info msg="starting kubernetes-ingress-controller"
6/4/2016 11:11:01 AMtime="2016-06-04T15:11:01Z" level=info msg="Healthcheck handler is listening on :10241"
6/4/2016 11:11:31 AMpanic: runtime error: index out of range
6/4/2016 11:11:31 AM
6/4/2016 11:11:31 AMgoroutine 38 [running]:
6/4/2016 11:11:31 AMpanic(0x1407760, 0xc82001c020)
6/4/2016 11:11:31 AM	/usr/local/go/src/runtime/panic.go:481 +0x3e6
6/4/2016 11:11:31 AMgithub.com/rancher/ingress-controller/lbprovider.(*RancherLBProvider).syncupEndpoints(0xc8200aff40, 0x0, 0x0)
6/4/2016 11:11:31 AM	/go/src/github.com/rancher/ingress-controller/lbprovider/rancher.go:152 +0x452
6/4/2016 11:11:31 AMcreated by github.com/rancher/ingress-controller/lbprovider.(*RancherLBProvider).Run
6/4/2016 11:11:31 AM	/go/src/github.com/rancher/ingress-controller/lbprovider/rancher.go:133 +0x91
6/4/2016 11:11:34 AMtime="2016-06-04T15:11:34Z" level=info msg="Starting Rancher LB service"
6/4/2016 11:11:34 AMtime="2016-06-04T15:11:34Z" level=info msg="LB controller: kubernetes"
6/4/2016 11:11:34 AMtime="2016-06-04T15:11:34Z" level=info msg="LB provider: rancher"
6/4/2016 11:11:34 AMtime="2016-06-04T15:11:34Z" level=info msg="starting kubernetes-ingress-controller"
6/4/2016 11:11:34 AMtime="2016-06-04T15:11:34Z" level=info msg="Healthcheck handler is listening on :10241"
6/4/2016 11:12:04 AMpanic: runtime error: index out of range
6/4/2016 11:12:04 AM
6/4/2016 11:12:04 AMgoroutine 38 [running]:
6/4/2016 11:12:04 AMpanic(0x1407760, 0xc82001c020)
6/4/2016 11:12:04 AM	/usr/local/go/src/runtime/panic.go:481 +0x3e6
6/4/2016 11:12:04 AMgithub.com/rancher/ingress-controller/lbprovider.(*RancherLBProvider).syncupEndpoints(0xc8200aff60, 0x0, 0x0)
6/4/2016 11:12:04 AM	/go/src/github.com/rancher/ingress-controller/lbprovider/rancher.go:152 +0x452
6/4/2016 11:12:04 AMcreated by github.com/rancher/ingress-controller/lbprovider.(*RancherLBProvider).Run
6/4/2016 11:12:04 AM	/go/src/github.com/rancher/ingress-controller/lbprovider/rancher.go:133 +0x91
6/4/2016 11:12:06 AMtime="2016-06-04T15:12:06Z" level=info msg="Starting Rancher LB service"
6/4/2016 11:12:06 AMtime="2016-06-04T15:12:06Z" level=info msg="LB controller: kubernetes"
6/4/2016 11:12:06 AMtime="2016-06-04T15:12:06Z" level=info msg="LB provider: rancher"
6/4/2016 11:12:06 AMtime="2016-06-04T15:12:06Z" level=info msg="starting kubernetes-ingress-controller"
6/4/2016 11:12:06 AMtime="2016-06-04T15:12:06Z" level=info msg="Healthcheck handler is listening on :10241"
6/4/2016 11:12:36 AMpanic: runtime error: index out of range
6/4/2016 11:12:36 AM
6/4/2016 11:12:36 AMgoroutine 38 [running]:
6/4/2016 11:12:36 AMpanic(0x1407760, 0xc82001c020)
6/4/2016 11:12:36 AM	/usr/local/go/src/runtime/panic.go:481 +0x3e6
6/4/2016 11:12:36 AMgithub.com/rancher/ingress-controller/lbprovider.(*RancherLBProvider).syncupEndpoints(0xc82034ae20, 0x0, 0x0)
6/4/2016 11:12:36 AM	/go/src/github.com/rancher/ingress-controller/lbprovider/rancher.go:152 +0x452
6/4/2016 11:12:36 AMcreated by github.com/rancher/ingress-controller/lbprovider.(*RancherLBProvider).Run
6/4/2016 11:12:36 AM	/go/src/github.com/rancher/ingress-controller/lbprovider/rancher.go:133 +0x91
6/4/2016 11:12:39 AMtime="2016-06-04T15:12:39Z" level=info msg="Starting Rancher LB service"
6/4/2016 11:12:39 AMtime="2016-06-04T15:12:39Z" level=info msg="LB controller: kubernetes"
6/4/2016 11:12:39 AMtime="2016-06-04T15:12:39Z" level=info msg="LB provider: rancher"
6/4/2016 11:12:39 AMtime="2016-06-04T15:12:39Z" level=info msg="starting kubernetes-ingress-controller"
6/4/2016 11:12:39 AMtime="2016-06-04T15:12:39Z" level=info msg="Healthcheck handler is listening on :10241"
6/4/2016 11:13:09 AMpanic: runtime error: index out of range
6/4/2016 11:13:09 AM
6/4/2016 11:13:09 AMgoroutine 38 [running]:
6/4/2016 11:13:09 AMpanic(0x1407760, 0xc82001c020)
6/4/2016 11:13:09 AM	/usr/local/go/src/runtime/panic.go:481 +0x3e6
6/4/2016 11:13:09 AMgithub.com/rancher/ingress-controller/lbprovider.(*RancherLBProvider).syncupEndpoints(0xc8200aff60, 0x0, 0x0)
6/4/2016 11:13:09 AM	/go/src/github.com/rancher/ingress-controller/lbprovider/rancher.go:152 +0x452
6/4/2016 11:13:09 AMcreated by github.com/rancher/ingress-controller/lbprovider.(*RancherLBProvider).Run
6/4/2016 11:13:09 AM	/go/src/github.com/rancher/ingress-controller/lbprovider/rancher.go:133 +0x91
6/4/2016 11:13:12 AMtime="2016-06-04T15:13:12Z" level=info msg="Starting Rancher LB service"
6/4/2016 11:13:12 AMtime="2016-06-04T15:13:12Z" level=info msg="LB controller: kubernetes"
6/4/2016 11:13:12 AMtime="2016-06-04T15:13:12Z" level=info msg="LB provider: rancher"
6/4/2016 11:13:12 AMtime="2016-06-04T15:13:12Z" level=info msg="starting kubernetes-ingress-controller"
6/4/2016 11:13:12 AMtime="2016-06-04T15:13:12Z" level=info msg="Healthcheck handler is listening on :10241"
6/4/2016 11:13:42 AMpanic: runtime error: index out of range
6/4/2016 11:13:42 AM
6/4/2016 11:13:42 AMgoroutine 38 [running]:
6/4/2016 11:13:42 AMpanic(0x1407760, 0xc82001c020)
6/4/2016 11:13:42 AM	/usr/local/go/src/runtime/panic.go:481 +0x3e6
6/4/2016 11:13:42 AMgithub.com/rancher/ingress-controller/lbprovider.(*RancherLBProvider).syncupEndpoints(0xc8200d9f40, 0x0, 0x0)
6/4/2016 11:13:42 AM	/go/src/github.com/rancher/ingress-controller/lbprovider/rancher.go:152 +0x452
6/4/2016 11:13:42 AMcreated by github.com/rancher/ingress-controller/lbprovider.(*RancherLBProvider).Run
6/4/2016 11:13:42 AM	/go/src/github.com/rancher/ingress-controller/lbprovider/rancher.go:133 +0x91
6/4/2016 11:13:45 AMtime="2016-06-04T15:13:45Z" level=info msg="Starting Rancher LB service"
6/4/2016 11:13:45 AMtime="2016-06-04T15:13:45Z" level=info msg="LB controller: kubernetes"
6/4/2016 11:13:45 AMtime="2016-06-04T15:13:45Z" level=info msg="LB provider: rancher"
6/4/2016 11:13:45 AMtime="2016-06-04T15:13:45Z" level=info msg="starting kubernetes-ingress-controller"
6/4/2016 11:13:45 AMtime="2016-06-04T15:13:45Z" level=info msg="Healthcheck handler is listening on :10241"
6/4/2016 11:14:15 AMpanic: runtime error: index out of range
6/4/2016 11:14:15 AM
6/4/2016 11:14:15 AMgoroutine 38 [running]:
6/4/2016 11:14:15 AMpanic(0x1407760, 0xc82001c020)
6/4/2016 11:14:15 AM	/usr/local/go/src/runtime/panic.go:481 +0x3e6
6/4/2016 11:14:15 AMgithub.com/rancher/ingress-controller/lbprovider.(*RancherLBProvider).syncupEndpoints(0xc82030a7e0, 0x0, 0x0)
6/4/2016 11:14:15 AM	/go/src/github.com/rancher/ingress-controller/lbprovider/rancher.go:152 +0x452
6/4/2016 11:14:15 AMcreated by github.com/rancher/ingress-controller/lbprovider.(*RancherLBProvider).Run
6/4/2016 11:14:15 AM	/go/src/github.com/rancher/ingress-controller/lbprovider/rancher.go:133 +0x91
6/4/2016 11:14:18 AMtime="2016-06-04T15:14:18Z" level=info msg="Starting Rancher LB service"
6/4/2016 11:14:18 AMtime="2016-06-04T15:14:18Z" level=info msg="LB controller: kubernetes"
6/4/2016 11:14:18 AMtime="2016-06-04T15:14:18Z" level=info msg="LB provider: rancher"
6/4/2016 11:14:18 AMtime="2016-06-04T15:14:18Z" level=info msg="starting kubernetes-ingress-controller"
6/4/2016 11:14:18 AMtime="2016-06-04T15:14:18Z" level=info msg="Healthcheck handler is listening on :10241"
6/4/2016 11:14:48 AMpanic: runtime error: index out of range
6/4/2016 11:14:48 AM
6/4/2016 11:14:48 AMgoroutine 38 [running]:
6/4/2016 11:14:48 AMpanic(0x1407760, 0xc82001c020)
6/4/2016 11:14:48 AM	/usr/local/go/src/runtime/panic.go:481 +0x3e6
6/4/2016 11:14:48 AMgithub.com/rancher/ingress-controller/lbprovider.(*RancherLBProvider).syncupEndpoints(0xc820352e20, 0x0, 0x0)
6/4/2016 11:14:48 AM	/go/src/github.com/rancher/ingress-controller/lbprovider/rancher.go:152 +0x452
6/4/2016 11:14:48 AMcreated by github.com/rancher/ingress-controller/lbprovider.(*RancherLBProvider).Run
6/4/2016 11:14:48 AM	/go/src/github.com/rancher/ingress-controller/lbprovider/rancher.go:133 +0x91
````

**Expected:**
rancher-ingress-controller to stay green

**Comment by deniseschannon** [comment]
When you switched from cattle to k8s, did you have any hosts/services running in your environment already?

If you had services, we currently don't support switching between container orchestration types.

**Comment by joshrendek** [comment]
@deniseschannon yeah i had a few containers running - should i convert back to cattle, shutdown/remove them, then convert to k8?

**Comment by deniseschannon** [comment]
Honestly, I haven't tested those steps but feel free to try. ;) 

If it still throws an error after those steps, let me know and I can try and reproduce with those steps.

**Comment by joshrendek** [comment]
That worked for a bit and then the whole thing blew up throwing a /failed page - I rebuilt it using an external mysql DB this time so I'll report back if I can reproduce that.

**Comment by deniseschannon** [comment]
@joshrendek I'll close for now and can you re-open if you can reproduce. We've been putting in many bug fixes to our k8s services as well.
