### ISSUE TITLE
Kubernetes system stack does not come up after removing the library catalog

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5238]
**Rancher Version:**: Master

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes

**Steps to Reproduce:**
1. Create a Kubernetes environment with the library catalog (qa-catalog) added
2. Kuberntes comes up correctly.
3. Remove the qa-catalog. 
4. Create another Kuberntes environment

**Results:** 
The Kuberntes environment does not come up . It is stuck in "Creating Kuberntes Stack"
Here is the cattle-debuglog:

```
2016-06-23 22:31:31,411 ERROR [:] [] [] [] [cutorService-43] [o.a.c.m.context.NoExceptionRunnable ] Uncaught exception java.lang.IllegalS
tateException: Failed to process system stacks for [36]
        at io.cattle.platform.systemstack.listener.SystemStackUpdate$2.doWithLockNoResult(SystemStackUpdate.java:298) ~[cattle-system-sta
ck-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) ~[cattle-framework-lock-0.5.0-SNAPSHOT.ja
r:na]
        at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) ~[cattle-framework-lock-0.5.0-SNAPSHOT.ja
r:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) ~[cattle-framework-lock-0.5
.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) ~[cattle-framework-lock-0.5.0-SNAPS
HOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) ~[cattle-framework-lock-0.5.0-SNAPS
HOT.jar:na]
        at io.cattle.platform.systemstack.listener.SystemStackUpdate.reconcileForClient(SystemStackUpdate.java:285) ~[cattle-system-stack
-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.systemstack.listener.SystemStackUpdate.globalServiceUpdate(SystemStackUpdate.java:107) ~[cattle-system-stac
k-0.5.0-SNAPSHOT.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_101]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_101]
        at io.cattle.platform.eventing.annotation.MethodInvokingListener$1.doWithLockNoResult(MethodInvokingListener.java:76) ~[cattle-fr
amework-eventing-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) ~[cattle-framework-lock-0.5.0-SNAPSHOT.ja
r:na]
        at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) ~[cattle-framework-lock-0.5.0-SNAPSHOT.ja
r:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) ~[cattle-framework-lock-0.5
.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) ~[cattle-framework-lock-0.5.0-SNAPS
HOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) ~[cattle-framework-lock-0.5.0-SNAPS
HOT.jar:na]
        at io.cattle.platform.eventing.annotation.MethodInvokingListener.onEvent(MethodInvokingListener.java:72) ~[cattle-framework-event
ing-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) ~[cattl
e-framework-eventing-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15) ~[cattle-framework-managed
-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-c
ontext-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-manag
ed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-frame
work-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framewo
rk-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-con
text-0.5.0-SNAPSHOT.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_101]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_101]
Caused by: org.apache.http.client.HttpResponseException: Not Found
        at org.apache.http.client.fluent.ContentResponseHandler.handleResponse(ContentResponseHandler.java:47) ~[fluent-hc-4.3.1.jar:4.3.
1]
        at org.apache.http.client.fluent.ContentResponseHandler.handleResponse(ContentResponseHandler.java:40) ~[fluent-hc-4.3.1.jar:4.3.
1]
        at org.apache.http.client.fluent.Response.handleResponse(Response.java:85) ~[fluent-hc-4.3.1.jar:4.3.1]
        at org.apache.http.client.fluent.Response.returnContent(Response.java:92) ~[fluent-hc-4.3.1.jar:4.3.1]
        at io.cattle.platform.systemstack.listener.SystemStackUpdate.getTemplateFromCatalog(SystemStackUpdate.java:230) ~[cattle-system-s
tack-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.systemstack.listener.SystemStackUpdate.addStack(SystemStackUpdate.java:157) ~[cattle-system-stack-0.5.0-SNA
PSHOT.jar:na]
        at io.cattle.platform.systemstack.listener.SystemStackUpdate.process(SystemStackUpdate.java:128) ~[cattle-system-stack-0.5.0-SNAP
SHOT.jar:na]
        at io.cattle.platform.systemstack.listener.SystemStackUpdate$1.call(SystemStackUpdate.java:110) ~[cattle-system-stack-0.5.0-SNAPS
HOT.jar:na]
        at io.cattle.platform.systemstack.listener.SystemStackUpdate$1.call(SystemStackUpdate.java:107) ~[cattle-system-stack-0.5.0-SNAPS
HOT.jar:na]
        at io.cattle.platform.systemstack.listener.SystemStackUpdate$2.doWithLockNoResult(SystemStackUpdate.java:293) ~[cattle-system-sta
ck-0.5.0-SNAPSHOT.jar:na]
        ... 30 common frames omitted




```

**Comment by deniseschannon** [comment]
This is due to the fact that when you add in your own `library` catalog, it automatically disables the Rancher default `library` catalog. Since the k8s system stack is in the official default `library` catalog, it is not automatically enabled. 

Closing this in favor of https://github.com/rancher/rancher/issues/5228
