### ISSUE TITLE
Gandi DNS Provider failure : nil pointer dereference

### ISSUE THREAD

**Issue by digitalLumberjack** [rancher/rancher#5246]
**Rancher Version:**
v1.1.0-dev5

**Docker Version:**
1.11.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
Scaleway Docker Image

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a gandi dns provider with the following configuration : 

docker-compose

```
gandidns:
  environment:
    GANDI_APIKEY: xxxmyprodapikeyxxx
    ROOT_DOMAIN: mydomain.com
    TTL: '300'
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: external-dns
  command:
  - -provider
  - Gandi
  image: rancher/external-dns:v0.4.1
```

rancher-compose : 

```
gandidns:
  scale: 1
  health_check:
    port: 1000
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
```

**Results:** 

```

26/6/2016 14:17:20panic: runtime error: invalid memory address or nil pointer dereference
26/6/2016 14:17:20[signal 0xb code=0x1 addr=0x28 pc=0x405bf2]
26/6/2016 14:17:20
26/6/2016 14:17:20goroutine 1 [running]:
26/6/2016 14:17:20main.main()
26/6/2016 14:17:20  /source/main.go:89 +0x92
26/6/2016 14:17:20
26/6/2016 14:17:20goroutine 20 [chan receive]:
26/6/2016 14:17:20github.com/kolo/xmlrpc.(*clientCodec).ReadResponseHeader(0xc82005bac0, 0xc82011ea80, 0x0, 0x0)
26/6/2016 14:17:20  /source/Godeps/_workspace/src/github.com/kolo/xmlrpc/client.go:68 +0x79
26/6/2016 14:17:20net/rpc.(*Client).input(0xc82005c5a0)
26/6/2016 14:17:20  /usr/local/go/src/net/rpc/client.go:109 +0xbf
26/6/2016 14:17:20created by net/rpc.NewClientWithCodec
26/6/2016 14:17:20  /usr/local/go/src/net/rpc/client.go:201 +0xd2
26/6/2016 14:17:20
26/6/2016 14:17:20goroutine 28 [chan receive]:
26/6/2016 14:17:20github.com/kolo/xmlrpc.(*clientCodec).ReadResponseHeader(0xc820492f00, 0xc8204376b0, 0x0, 0x0)
26/6/2016 14:17:20  /source/Godeps/_workspace/src/github.com/kolo/xmlrpc/client.go:68 +0x79
26/6/2016 14:17:20net/rpc.(*Client).input(0xc82039b860)
26/6/2016 14:17:20  /usr/local/go/src/net/rpc/client.go:109 +0xbf
26/6/2016 14:17:20created by net/rpc.NewClientWithCodec
26/6/2016 14:17:20  /usr/local/go/src/net/rpc/client.go:201 +0xd2
26/6/2016 14:17:20
26/6/2016 14:17:20goroutine 46 [IO wait]:
26/6/2016 14:17:20net.runtime_pollWait(0x7f6041f0ec08, 0x72, 0xc82005e0b0)
26/6/2016 14:17:20  /usr/local/go/src/runtime/netpoll.go:157 +0x60
26/6/2016 14:17:20net.(*pollDesc).Wait(0xc820450290, 0x72, 0x0, 0x0)
26/6/2016 14:17:20  /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
26/6/2016 14:17:20net.(*pollDesc).WaitRead(0xc820450290, 0x0, 0x0)
26/6/2016 14:17:20  /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
26/6/2016 14:17:20net.(*netFD).Read(0xc820450230, 0xc820019000, 0x1000, 0x1000, 0x0, 0x7f6041f09028, 0xc82005e0b0)
26/6/2016 14:17:20  /usr/local/go/src/net/fd_unix.go:232 +0x23a
26/6/2016 14:17:20net.(*conn).Read(0xc82007e038, 0xc820019000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
26/6/2016 14:17:20  /usr/local/go/src/net/net.go:172 +0xe4
26/6/2016 14:17:20net/http.noteEOFReader.Read(0x7f6041f490d0, 0xc82007e038, 0xc8204527e8, 0xc820019000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
26/6/2016 14:17:20  /usr/local/go/src/net/http/transport.go:1370 +0x67
26/6/2016 14:17:20net/http.(*noteEOFReader).Read(0xc82051abc0, 0xc820019000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
26/6/2016 14:17:20  <autogenerated>:126 +0xd0
26/6/2016 14:17:20bufio.(*Reader).fill(0xc8204b2240)
26/6/2016 14:17:20  /usr/local/go/src/bufio/bufio.go:97 +0x1e9
26/6/2016 14:17:20bufio.(*Reader).Peek(0xc8204b2240, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
26/6/2016 14:17:20  /usr/local/go/src/bufio/bufio.go:132 +0xcc
26/6/2016 14:17:20net/http.(*persistConn).readLoop(0xc820452790)
26/6/2016 14:17:20  /usr/local/go/src/net/http/transport.go:876 +0xf7
26/6/2016 14:17:20created by net/http.(*Transport).dialConn
26/6/2016 14:17:20  /usr/local/go/src/net/http/transport.go:685 +0xc78
26/6/2016 14:17:20
26/6/2016 14:17:20goroutine 49 [select]:
26/6/2016 14:17:20net/http.(*persistConn).writeLoop(0xc8200d0000)
26/6/2016 14:17:20  /usr/local/go/src/net/http/transport.go:1009 +0x40c
26/6/2016 14:17:20created by net/http.(*Transport).dialConn
26/6/2016 14:17:20  /usr/local/go/src/net/http/transport.go:686 +0xc9d
26/6/2016 14:17:20
26/6/2016 14:17:20goroutine 52 [select]:
26/6/2016 14:17:20net/http.(*persistConn).writeLoop(0xc8200d00b0)
26/6/2016 14:17:20  /usr/local/go/src/net/http/transport.go:1009 +0x40c
26/6/2016 14:17:20created by net/http.(*Transport).dialConn
26/6/2016 14:17:20  /usr/local/go/src/net/http/transport.go:686 +0xc9d
26/6/2016 14:17:20
26/6/2016 14:17:20goroutine 47 [select]:
26/6/2016 14:17:20net/http.(*persistConn).writeLoop(0xc820452790)
26/6/2016 14:17:20  /usr/local/go/src/net/http/transport.go:1009 +0x40c
26/6/2016 14:17:20created by net/http.(*Transport).dialConn
26/6/2016 14:17:20  /usr/local/go/src/net/http/transport.go:686 +0xc9d
26/6/2016 14:17:20
26/6/2016 14:17:20goroutine 48 [runnable]:
26/6/2016 14:17:20net/http.(*persistConn).readLoop(0xc8200d0000)
26/6/2016 14:17:20  /usr/local/go/src/net/http/transport.go:976 +0xac7
26/6/2016 14:17:20created by net/http.(*Transport).dialConn
26/6/2016 14:17:20  /usr/local/go/src/net/http/transport.go:685 +0xc78
26/6/2016 14:17:20
26/6/2016 14:17:20goroutine 51 [IO wait]:
26/6/2016 14:17:20net.runtime_pollWait(0x7f6041f0ea88, 0x72, 0xc82005e0b0)
26/6/2016 14:17:20  /usr/local/go/src/runtime/netpoll.go:157 +0x60
26/6/2016 14:17:20net.(*pollDesc).Wait(0xc8201c05a0, 0x72, 0x0, 0x0)
26/6/2016 14:17:20  /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
26/6/2016 14:17:20net.(*pollDesc).WaitRead(0xc8201c05a0, 0x0, 0x0)
26/6/2016 14:17:20  /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
26/6/2016 14:17:20net.(*netFD).Read(0xc8201c0540, 0xc8203a2800, 0x800, 0x800, 0x0, 0x7f6041f09028, 0xc82005e0b0)
26/6/2016 14:17:20  /usr/local/go/src/net/fd_unix.go:232 +0x23a
26/6/2016 14:17:20net.(*conn).Read(0xc82007e0b0, 0xc8203a2800, 0x800, 0x800, 0x0, 0x0, 0x0)
26/6/2016 14:17:20  /usr/local/go/src/net/net.go:172 +0xe4
26/6/2016 14:17:20crypto/tls.(*block).readFromUntil(0xc820436870, 0x7f6041f490d0, 0xc82007e0b0, 0x5, 0x0, 0x0)
26/6/2016 14:17:20  /usr/local/go/src/crypto/tls/conn.go:455 +0xcc
26/6/2016 14:17:20crypto/tls.(*Conn).readRecord(0xc8204342c0, 0xc15e17, 0x0, 0x0)
26/6/2016 14:17:20  /usr/local/go/src/crypto/tls/conn.go:540 +0x2d1
26/6/2016 14:17:20crypto/tls.(*Conn).Read(0xc8204342c0, 0xc8201bf000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
26/6/2016 14:17:20  /usr/local/go/src/crypto/tls/conn.go:901 +0x167
26/6/2016 14:17:20net/http.noteEOFReader.Read(0x7f6041f17b58, 0xc8204342c0, 0xc8200d0108, 0xc8201bf000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
26/6/2016 14:17:20  /usr/local/go/src/net/http/transport.go:1370 +0x67
26/6/2016 14:17:20net/http.(*noteEOFReader).Read(0xc82042e0c0, 0xc8201bf000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
26/6/2016 14:17:20  <autogenerated>:126 +0xd0
26/6/2016 14:17:20bufio.(*Reader).fill(0xc8204b3a40)
26/6/2016 14:17:20  /usr/local/go/src/bufio/bufio.go:97 +0x1e9
26/6/2016 14:17:20bufio.(*Reader).Peek(0xc8204b3a40, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
26/6/2016 14:17:20  /usr/local/go/src/bufio/bufio.go:132 +0xcc
26/6/2016 14:17:20net/http.(*persistConn).readLoop(0xc8200d00b0)
26/6/2016 14:17:20  /usr/local/go/src/net/http/transport.go:876 +0xf7
26/6/2016 14:17:20created by net/http.(*Transport).dialConn
26/6/2016 14:17:20  /usr/local/go/src/net/http/transport.go:685 +0xc78
```

**Expected:**

**Comment by janeczku** [comment]
@digitalLumberjack On first appearance this looks like something that has to be addressed in the upstream Gandi library https://github.com/prasmussen/gandi-api. Could be related to the issue here: https://github.com/kolo/xmlrpc/issues/32. 

Either way, could you confirm whether this occurs in the current external-dns release https://github.com/rancher/external-dns/releases/tag/v0.5.0 ?

**Comment by aemneina** [comment]
Closing the issue due to inactivity.
