### ISSUE TITLE
ECR pull image failing in rancher

### ISSUE THREAD

**Issue by jclark360** [rancher/rancher#5382]
Is there any additional logging besides the agent on the rancher hosts to see why it can't pull the image?

**Rancher Version:**
1.12

**Docker Version:**
1.11.2, build b9f10c9

**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 14.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
ha rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
setup a registry for an ecr repo
add the container to refresh credentials, try and add an ecr image to run

**Results:** 
```
ImageValidationError: Image [123123123123.dkr.ecr.us-east-1.amazonaws.com/image_name:prod] failed to pull: Error: image image_name
2016-07-11 00:52:58,245 ERROR agent [140171808058736] [event.py:112] Error in request : 1d661285-5118-4358-9a7f-3d27c5e8cd29
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 34, in execute
    return method(req=req, **req.data.__dict__)
  File "/var/lib/cattle/pyagent/cattle/storage/__init__.py", line 27, in image_activate
    action=lambda: self._do_image_activate(image, storage_pool,
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 72, in _do
    action()
  File "/var/lib/cattle/pyagent/cattle/storage/__init__.py", line 28, in <lambda>
    progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/storage.py", line 162, in _do_image_activate
```

**Expected:**
The image starts

**Comment by deniseschannon** [comment]
We don't have support for ECR yet.  Closing in favor for the feature request. 

https://github.com/rancher/rancher/issues/3126
