### ISSUE TITLE
wordpress stack stuck in "Activating" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5470]
Rancher Version:v1.1.1

Deploy an environment with orchestration set to "swarm".
Once system stack - "Swarm" is active,deploy "wordpress" app from catalog.
Wordpress stack is stuck in "Activating" state even when after "db" and "wordpress" are services are in "Active" state.

Also not able to get to  the url to access  wordpress application , to see if it up and running.

<img width="1357" alt="screen shot 2016-07-18 at 11 15 48 am" src="https://cloud.githubusercontent.com/assets/4266958/16925475/40e2eaac-4cd9-11e6-9aeb-7ecc35519d19.png">

**Comment by cpoole** [comment]
I am experiencing identical issues for my stacks started through rancher-compose. 
rancher-ha 1.1.0 and rancher-compose 0.8.6 from linux and osx.

**Comment by deniseschannon** [comment]
@cpoole You are also using the swarm environment?

**Comment by cpoole** [comment]
@deniseschannon I am using cattle, sorry, forgot to mention that.

**Comment by aemneina** [comment]
Hey @cpoole can you expand that wordpress stack and get the resource id for the stuck container. Then navigate to admin->processes and find the resource id in there. Expand that until you see where the exception is, can you copy the stack trace here?

**Comment by cpoole** [comment]
Timeout exception: DockerComposeEnvironmentHandler -> Rancher-compose-executor
```
io.cattle.platform.async.utils.TimeoutException
	at io.cattle.platform.async.retry.impl.RetryTimeoutServiceImpl$1.run(RetryTimeoutServiceImpl.java:51)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cpoole** [comment]
ah nevermind. this is a different issue... I upgraded rancher HA and Rancher got stuck in an endless loop attempting to restart go-machine and rancher-compose-executor services on hosts that no longer existed... Upgrading a HA install is not very well documented. 

I would have figured literally destroying old rancher server hosts and building new ones would have worked but somewhere the ip address of the old hosts is kept around.

**Comment by jclark360** [comment]
I have the same issue as @cpoole above, how did you resolve it?

**Comment by cpoole** [comment]
@jclark360 I was provisioning my rancher-server hosts with terraform using AWS. So when I upgraded from 1.1.0-dev5 to 1.1.0 official I modified the userdata for the instances and then destroyed the old autoscaling group and built the new hosts but kept the external database. 

Somehow when the new management stack came online the old ip addresses for the rancher-server hosts must have been in the DB for the management stack. 

to fix this I went into the management environment and then individually deleted stacks that were stuck in the infinite loop (go machine, rancher compose executor, and websocket proxy in my case). Then i ssh'd to each of the rancher-server hosts and executed 
```
sudo docker rm -f $(sudo docker ps -a | grep rancher | awk {'print $1'}) 
```

then after running that on all of the hosts I reran the ha-setup.sh script
```
sudo sh rancher-ha.sh rancher/server:v1.1.0
```

hope that helps!

**Comment by tfiduccia** [comment]
@sangeethah Original issue - wordpress doesn't activate is working in 1.2.0-pre2.
