### ISSUE TITLE
Stack stuck in activating when one container fails to come up, holds up other containers

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#5481]
**Rancher Version:**
1.1.1

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. stack with multiple containers
2. launch (roll dice)

**Results:** 
if one of the containers coming up times out (or fails to come up) it stays stuck in activating state.
See this exception in the processes list, for the failed container :
```
io.cattle.platform.async.utils.TimeoutException
        at io.cattle.platform.async.retry.impl.RetryTimeoutServiceImpl$1.run(RetryTimeoutServiceImpl.java:51)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Expected:**
Ideally we retry the failed launch, or continue to bring up other containers?

**Comment by aemneina** [comment]
Learned thats the intended behavior, going to try to find the root of the container failing to start.

**Comment by aemneina** [comment]
closing ... invalid :)
