### ISSUE TITLE
Full stacktrace not needed for EventExecutionException: Scheduling failed

### ISSUE THREAD

**Issue by sorenroug** [rancher/rancher#5526]
Some users forget that to check that a stack came up correctly, and sometimes they schedule with a host label that doesn't exist in the environment. This causes the Rancher server to log a full stack trace every time it tries to launch the container. In my opinion it pollutes the log as it isn't a failure in the software.

Additionally, it would be very useful if `rancher-compose --verbose up` printed out those scheduling issues as well as when scheduling is impossible because a port is already used by another process.

**Rancher Version:** 1.1.0

**Docker Version:** 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS Linux release 7.2.1511

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Launch a stack with a scheduling requirement for a host label that doesn't exist.
**Results:** 

```
2016-07-23 09:12:50,716 ERROR [ab16a447-0baa-4de5-8fdb-46937f330d7a:18651394] [instance:197142] [instance.start->(InstanceStart)->instance.allocate] [] [ecutorService-4] [c.p.e.p.i.DefaultProcessInstanceImpl]
 Unknown exception io.cattle.platform.eventing.exception.EventExecutionException: Scheduling failed: needs host with label elastic: yes
        at io.cattle.platform.eventing.exception.EventExecutionException.fromEvent(EventExecutionException.java:53) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.eventing.impl.AbstractEventService.callSync(AbstractEventService.java:258) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.process.common.handler.EventBasedProcessHandler.handle(EventBasedProcessHandler.java:109) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.process.instance.InstanceAllocate.handle(InstanceAllocate.java:48) ~[cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:424) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:n
...
```

**Expected:**
No stacktrace.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
