### ISSUE TITLE
rancher-agent: Unable to get fs usage from thin pool for device

### ISSUE THREAD

**Issue by averri** [rancher/rancher#5555]
Rancher agent is generating this log messages, creating hundreds of log entries per minute.

```
I0726 18:21:56.740655   19525 thin_pool_watcher.go:117] reserving metadata snapshot for thin-pool docker-253:1-1442645-pool
E0726 18:21:56.788398   19525 thin_pool_watcher.go:65] encountered error refreshing thin pool watcher: error performing thin_ls on metadata device /dev/loop1: Error running command `thin_ls --no-headers -m -o DEV,EXCLUSIVE_BYTES /dev/loop1`: exec: "thin_ls": executable file not found in $PATH
output:

E0726 18:21:56.788677   19525 handler.go:278] unable to get fs usage from thin pool for device 171: no cached value for usage of device 171
E0726 18:21:56.815571   19525 handler.go:278] unable to get fs usage from thin pool for device 167: no cached value for usage of device 167
E0726 18:21:57.068911   19525 handler.go:278] unable to get fs usage from thin pool for device 196: no cached value for usage of device 196
E0726 18:21:57.262833   19525 handler.go:278] unable to get fs usage from thin pool for device 164: no cached value for usage of device 164
E0726 18:21:57.753428   19525 handler.go:278] unable to get fs usage from thin pool for device 171: no cached value for usage of device 171
E0726 18:21:57.901698   19525 handler.go:278] unable to get fs usage from thin pool for device 204: no cached value for usage of device 204
E0726 18:21:58.071546   19525 handler.go:278] unable to get fs usage from thin pool for device 167: no cached value for usage of device 167
E0726 18:21:58.490061   19525 handler.go:278] unable to get fs usage from thin pool for device 598: no cached value for usage of device 598
E0726 18:21:58.658848   19525 handler.go:278] unable to get fs usage from thin pool for device 164: no cached value for usage of device 164
E0726 18:21:58.883361   19525 handler.go:278] unable to get fs usage from thin pool for device 171: no cached value for usage of device 171
E0726 18:21:58.931404   19525 handler.go:278] unable to get fs usage from thin pool for device 196: no cached value for usage of device 196
E0726 18:21:59.273203   19525 handler.go:278] unable to get fs usage from thin pool for device 204: no cached value for usage of device 204
E0726 18:21:59.588066   19525 handler.go:278] unable to get fs usage from thin pool for device 598: no cached value for usage of device 598
E0726 18:21:59.592608   19525 handler.go:278] unable to get fs usage from thin pool for device 167: no cached value for usage of device 167
E0726 18:21:59.956931   19525 handler.go:278] unable to get fs usage from thin pool for device 164: no cached value for usage of device 164
E0726 18:22:00.588557   19525 handler.go:278] unable to get fs usage from thin pool for device 196: no cached value for usage of device 196
E0726 18:22:00.655871   19525 handler.go:278] unable to get fs usage from thin pool for device 171: no cached value for usage of device 171
E0726 18:22:00.681131   19525 handler.go:278] unable to get fs usage from thin pool for device 167: no cached value for usage of device 167
E0726 18:22:01.114392   19525 handler.go:278] unable to get fs usage from thin pool for device 204: no cached value for usage of device 204
E0726 18:22:01.160406   19525 handler.go:278] unable to get fs usage from thin pool for device 598: no cached value for usage of device 598
E0726 18:22:01.485588   19525 handler.go:278] unable to get fs usage from thin pool for device 164: no cached value for usage of device 164
E0726 18:22:01.673622   19525 handler.go:278] unable to get fs usage from thin pool for device 171: no cached value for usage of device 171
E0726 18:22:02.360604   19525 handler.go:278] unable to get fs usage from thin pool for device 167: no cached value for usage of device 167
E0726 18:22:02.507108   19525 handler.go:278] unable to get fs usage from thin pool for device 196: no cached value for usage of device 196
E0726 18:22:02.535419   19525 handler.go:278] unable to get fs usage from thin pool for device 598: no cached value for usage of device 598
E0726 18:22:02.561958   19525 handler.go:278] unable to get fs usage from thin pool for device 204: no cached value for usage of device 204
E0726 18:22:02.914540   19525 handler.go:278] unable to get fs usage from thin pool for device 171: no cached value for usage of device 171
2016-07-26 21:22:03,017 ERROR agent [139910216276880] [event.py:112] Error in request : a8aaa7b7-dc0f-47b7-90cc-4aded02b8fd8
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 97, in _worker_main
    publisher.publish(resp)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/publisher.py", line 24, in publish
    timeout=60)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/adapters.py", line 453, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
E0726 18:22:03.217480   19525 handler.go:278] unable to get fs usage from thin pool for device 164: no cached value for usage of device 164
E0726 18:22:03.553696   19525 handler.go:278] unable to get fs usage from thin pool for device 196: no cached value for usage of device 196
E0726 18:22:03.585513   19525 handler.go:278] unable to get fs usage from thin pool for device 598: no cached value for usage of device 598
E0726 18:22:03.627991   19525 handler.go:278] unable to get fs usage from thin pool for device 167: no cached value for usage of device 167
E0726 18:22:04.116587   19525 handler.go:278] unable to get fs usage from thin pool for device 204: no cached value for usage of device 204
E0726 18:22:04.137529   19525 handler.go:278] unable to get fs usage from thin pool for device 171: no cached value for usage of device 171
```

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.2` Cattle: `v0.165.8` UI: `v1.1.12` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`authenticated.project.waiting`|

**Comment by averri** [comment]
I had to stop rancher-agent because of the number of log messages. 

The Docker info:

```
# docker info
Containers: 12
 Running: 5
 Paused: 0
 Stopped: 7
Images: 71
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-253:1-1442645-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 10.22 GB
 Data Space Total: 107.4 GB
 Data Space Available: 35.71 GB
 Metadata Space Used: 18.5 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.129 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.703 GiB
Name: myserver.net
ID: EKF6:AJCQ:VJIA:EEGC:NMAI:JEOD:VMPU:7J4M:xxx
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: averri
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by cjellick** [comment]
Is this the same issue that we are discussing here #5512 @averri?

Read over that thread and let us know.

**Comment by cjellick** [comment]
I'd also suggest enabling log rotation for docker containers.
 https://docs.docker.com/v1.10/engine/admin/logging/overview/

**Comment by averri** [comment]
Hi @cjellick , yes, it is the same issue. Thank you for the information about log rotation.

**Comment by cjellick** [comment]
I'm going to close this issue in favor of the other one then.
