### ISSUE TITLE
etcd service stuck in updating active state

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5556]
**Rancher Version:**:1.1.2

**Docker Version:**:1.10.3

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes

**Steps to Reproduce:**
1. Create a Kubernetes environment with 3 hosts using https://github.com/LLParse/testing-catalog
2. Create pods/services
3. Turn off two hosts and bring back one host

**Results:** 
etcd recovers and Kubernetes is functional.
etcd service is stuck in "Updating active" state.

<img width="1141" alt="screen shot 2016-07-26 at 2 40 31 pm" src="https://cloud.githubusercontent.com/assets/18536626/17156615/9f1faa94-533f-11e6-9f2e-74e1af04dbd4.png">

Logs below
```
2016-07-26 21:39:23,340 ERROR [16a7ee3f-0e20-4dff-8a3f-0b4dcd0046db:3711] [instance:196] [instance.start->(InstanceStart)] [] [utorServic
e-159] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [196]
2016-07-26 21:39:38,482 ERROR [aa8a262a-2fc1-43c1-80a8-3edc4240cb6f:3717] [instance:197] [instance.start->(InstanceStart)->instance.alloc
ate->(InstanceAllocate)] [] [cutorService-45] [c.p.a.e.i.AllocatorEventListenerImpl] No allocator handled [EventVO [id=b9bec237-74b6-4a4a
-8805-805565f9cfed, name=instance.allocate, previousNames=null, replyTo=reply.6906618863420672321, resourceId=197, resourceType=instance,
 publisher=null, transitioning=null, transitioningMessage=null, transitioningInternalMessage=null, previousIds=null, data={}, time=Tue Ju
l 26 21:39:38 UTC 2016, listenerKey=null, transitioningProgress=null]]
2016-07-26 21:39:38,485 ERROR [aa8a262a-2fc1-43c1-80a8-3edc4240cb6f:3717] [instance:197] [instance.start->(InstanceStart)->instance.alloc
ate] [] [utorService-155] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.eventing.exception.EventExecutionEx
ception: Scheduling failed: io.cattle.platform.allocator.constraint.ContainerLabelAffinityConstraint@13ebec31
        at io.cattle.platform.eventing.exception.EventExecutionException.fromEvent(EventExecutionException.java:53) ~[cattle-framework-ev
enting-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.eventing.impl.AbstractEventService.callSync(AbstractEventService.java:258) ~[cattle-framework-eventing-0.5.
0-SNAPSHOT.jar:na]
        at io.cattle.platform.process.common.handler.EventBasedProcessHandler.handle(EventBasedProcessHandler.java:109) ~[cattle-iaas-log
ic-common-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.process.instance.InstanceAllocate.handle(InstanceAllocate.java:48) ~[cattle-iaas-logic-0.5.0-SNAPSHOT.jar:n
a]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:424) [cattle-fram
ework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:375) [cattle-frame
work-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:369) [cattle-frame
work-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:369) [cattle-fra
mework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:471) [cattle-framew
ork-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:305) [cat
tle-framework-engine-0.5.0-SNAPSHOT.jar:na]


```

**Comment by alena1108** [comment]
@soumyalj please test and reopen if you still see it on the latest.

**Comment by soumyalj** [comment]
Tested with 1.2.0-pre4-rc4. I still see that the etcd service is in updating-active state after executing the steps as described above:
```
{
"id": "1s1",
"type": "service",
"links": {
"self": "…/v2-beta/projects/1a5/services/1s1",
"account": "…/v2-beta/projects/1a5/services/1s1/account",
"consumedbyservices": "…/v2-beta/projects/1a5/services/1s1/consumedbyservices",
"consumedservices": "…/v2-beta/projects/1a5/services/1s1/consumedservices",
"instances": "…/v2-beta/projects/1a5/services/1s1/instances",
"networkDrivers": "…/v2-beta/projects/1a5/services/1s1/networkdrivers",
"serviceExposeMaps": "…/v2-beta/projects/1a5/services/1s1/serviceexposemaps",
"serviceLogs": "…/v2-beta/projects/1a5/services/1s1/servicelogs",
"stack": "…/v2-beta/projects/1a5/services/1s1/stack",
"storageDrivers": "…/v2-beta/projects/1a5/services/1s1/storagedrivers",
"containerStats": "…/v2-beta/projects/1a5/services/1s1/containerstats"
},
"actions": {
"update": "…/v2-beta/projects/1a5/services/1s1/?action=update",
"remove": "…/v2-beta/projects/1a5/services/1s1/?action=remove",
"setservicelinks": "…/v2-beta/projects/1a5/services/1s1/?action=setservicelinks",
"removeservicelink": "…/v2-beta/projects/1a5/services/1s1/?action=removeservicelink",
"addservicelink": "…/v2-beta/projects/1a5/services/1s1/?action=addservicelink",
"deactivate": "…/v2-beta/projects/1a5/services/1s1/?action=deactivate"
},
"baseType": "service",
"name": "etcd",
"state": "updating-active",
"accountId": "1a5",
"assignServiceIpAddress": false,
"createIndex": 82,
"created": "2016-10-17T22:36:11Z",
"createdTS": 1476743771000,
"currentScale": 3,
"description": null,
"externalId": null,
"fqdn": null,
"healthState": "started-once",
"instanceIds": [ 6 items
"1i1",
"1i2",
"1i4",
"1i5",
"1i118",
"1i119"
],


```

**Comment by soumyalj** [comment]
Tested with v1.2.0-pre4-rc4. If we start a Kubernetes set up with 3 hosts, turn off 2 hosts and turn back only one, then etcd will always try to reach its max scale which is 3. It is expected that it can be stuck in "updating active" state. 
The fix done above is to ensure the below, which has been tested and working:
If we start Kubernetes with a one host or a 2 host setup, etcd is not stuck in "updating active state".
