### ISSUE TITLE
why host been Starting (Networking)，can't add service

### ISSUE THREAD

**Issue by Dreampie** [rancher/rancher#5586]
![image](https://cloud.githubusercontent.com/assets/3667080/17234323/54b4ce58-556a-11e6-8a69-4273aa75bbdb.png)
stay here more than 10h

**Comment by deniseschannon** [comment]
Have you looked inside the rancher/server container logs to see what's wrong?

**Comment by Dreampie** [comment]
```shell
2016-07-29 01:55:58,768 ERROR [:] [] [] [] [ecutorService-1] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed null, exit code [1] output [ERROR: Agent instance has not started
]
2016-07-29 01:56:11,262 ERROR [:] [] [] [] [ecutorService-2] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed null, exit code [1] output [ERROR: Agent instance has not started
]
2016-07-29 01:56:31,781 ERROR [:] [] [] [] [cutorService-10] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed null, exit code [1] output [ERROR: Agent instance has not started
]
2016-07-29 01:56:41,531 ERROR [:] [] [] [] [ecutorService-5] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed null, exit code [1] output [ERROR: Agent instance has not started
]
2016-07-29 01:56:41,778 ERROR [:] [] [] [] [ecutorService-8] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed null, exit code [137] output [/var/lib/cattle/common/scripts.sh: line 62:  8799 Killed                  ${CATTLE_HOME}/config.sh "$@"
```

**Comment by Dreampie** [comment]
Please help me, I can not migrate services

**Comment by deniseschannon** [comment]
Can you please provide more details of your setup?

Rancher Version? OS Version? Setup details?

Did they just start happening or after an upgrade? 

It looks like your network-agent isn't functioning. Is it a new host?

**Comment by Dreampie** [comment]
rancher version: v1.1.0
OS version: ubuntu 14.04 tls
```
docker run -d --restart=always -p 8080:8080 \
-e CATTLE_DB_CATTLE_MYSQL_HOST=* \
-e CATTLE_DB_CATTLE_MYSQL_PORT=* \
-e CATTLE_DB_CATTLE_MYSQL_NAME=* \
-e CATTLE_DB_CATTLE_USERNAME=* \
-e CATTLE_DB_CATTLE_PASSWORD=* \
rancher/server
```
add new host happend

**Comment by deniseschannon** [comment]
Do you have ipv6 on your host?

**Comment by Dreampie** [comment]
no，only ipv4

**Comment by aemneina** [comment]
@Dreampie did you ever solve this? If not feel free to reopen.

**Comment by galindro** [comment]
@aemneina @deniseschannon 

Please, re-open this thread. This is happening with my env too.

Rancher version: 1.1.4
S.O.: ROS 0.7.0 (for booth server and hosts)

As I mentioned [here](https://forums.rancher.com/t/managed-container-stuck-in-starting-networking/2420/10), this being happening aftter I've restarted all of the Network Agent containers on all of my hosts.

Network Agent logs
`

04/12/2016 16:13:30INFO: ROOT -> ./etc/
04/12/2016 16:13:30INFO: ROOT -> ./etc/healthcheck/
04/12/2016 16:13:30INFO: ROOT -> ./etc/healthcheck/healthcheck.cfg
04/12/2016 16:13:30INFO: ROOT -> ./etc/monit/
04/12/2016 16:13:30INFO: ROOT -> ./etc/monit/conf.d/
04/12/2016 16:13:30INFO: ROOT -> ./etc/monit/conf.d/healthcheck
04/12/2016 16:13:30INFO: ROOT -> ./etc/monit/conf.d/haproxy-monitor
04/12/2016 16:13:30INFO: ROOT -> ./etc/init.d/
04/12/2016 16:13:30INFO: ROOT -> ./etc/init.d/haproxy-monitor
04/12/2016 16:13:30INFO: ROOT -> ./etc/default/
04/12/2016 16:13:30INFO: ROOT -> ./etc/default/haproxy-monitor
04/12/2016 16:13:30INFO: ROOT -> ./etc/default/haproxy
04/12/2016 16:13:30INFO: Sending healthcheck applied 326-65d5d9de1a6d13e42cd660a6a178baf58129b2dec06f43aa69e0603c72ac427e
04/12/2016 16:13:30INFO: Getting rancher-metadata
04/12/2016 16:13:30INFO: Updating rancher-metadata
04/12/2016 16:13:30INFO: Downloading http://rancher.internal.socialbase.com.br:8080/v1//configcontent//rancher-metadata current=
04/12/2016 16:13:30INFO: Running /var/lib/cattle/download/rancher-metadata/1-3d5c3295e1816daffdcefb0dde4fd79e5d9909c846bbd0c91719f82edbaecd2a/apply.sh
04/12/2016 16:13:30INFO: HOME -> ./
04/12/2016 16:13:30INFO: HOME -> ./etc/
04/12/2016 16:13:30INFO: HOME -> ./etc/cattle/
04/12/2016 16:13:30INFO: HOME -> ./etc/cattle/rancher-metadata/
04/12/2016 16:13:30INFO: HOME -> ./etc/cattle/rancher-metadata/http-reload
04/12/2016 16:13:30INFO: HOME -> ./bin/
04/12/2016 16:13:30INFO: HOME -> ./bin/rancher-metadata
04/12/2016 16:13:30INFO: ROOT -> ./
04/12/2016 16:13:30INFO: ROOT -> ./etc/
04/12/2016 16:13:30INFO: ROOT -> ./etc/monit/
04/12/2016 16:13:30INFO: ROOT -> ./etc/monit/conf.d/
04/12/2016 16:13:30INFO: ROOT -> ./etc/monit/conf.d/rancher-metadata
04/12/2016 16:13:30INFO: ROOT -> ./etc/init.d/
04/12/2016 16:13:30INFO: ROOT -> ./etc/init.d/rancher-metadata
04/12/2016 16:13:30 * rancher-metadata is running
04/12/2016 16:13:30 * Stopping rancher-metadata configuration rancher-metadata
04/12/2016 16:13:30   ...done.
04/12/2016 16:13:30 * Starting rancher-metadata configuration rancher-metadata
04/12/2016 16:13:30   ...done.
04/12/2016 16:13:30INFO: Sending rancher-metadata applied 1-3d5c3295e1816daffdcefb0dde4fd79e5d9909c846bbd0c91719f82edbaecd2a
04/12/2016 16:13:30INFO: Getting rancher-dns
04/12/2016 16:13:30INFO: Updating rancher-dns
04/12/2016 16:13:30INFO: Downloading http://rancher.internal.socialbase.com.br:8080/v1//configcontent//rancher-dns current=
04/12/2016 16:13:31INFO: Running /var/lib/cattle/download/rancher-dns/1-d138dbfdac3e71aa6b9d245e3e2e89db5398f5ad4b3543540389588d01174788/apply.sh
04/12/2016 16:13:31INFO: HOME -> ./
04/12/2016 16:13:31INFO: HOME -> ./etc/
04/12/2016 16:13:31INFO: HOME -> ./etc/cattle/
04/12/2016 16:13:31INFO: HOME -> ./etc/cattle/rancher-dns/
04/12/2016 16:13:31INFO: HOME -> ./etc/cattle/rancher-dns/http-reload
04/12/2016 16:13:31INFO: HOME -> ./bin/
04/12/2016 16:13:31INFO: HOME -> ./bin/rancher-dns
04/12/2016 16:13:31INFO: ROOT -> ./
04/12/2016 16:13:31INFO: ROOT -> ./etc/
04/12/2016 16:13:31INFO: ROOT -> ./etc/monit/
04/12/2016 16:13:31INFO: ROOT -> ./etc/monit/conf.d/
04/12/2016 16:13:31INFO: ROOT -> ./etc/monit/conf.d/rancher-dns
04/12/2016 16:13:31INFO: ROOT -> ./etc/init.d/
04/12/2016 16:13:31INFO: ROOT -> ./etc/init.d/rancher-dns
04/12/2016 16:13:31 * rancher-dns is running
04/12/2016 16:13:31 * Stopping rancher-dns configuration rancher-dns
04/12/2016 16:13:31   ...done.
04/12/2016 16:13:31 * Starting rancher-dns configuration rancher-dns
04/12/2016 16:13:31   ...done.
04/12/2016 16:13:31INFO: Sending rancher-dns applied 1-d138dbfdac3e71aa6b9d245e3e2e89db5398f5ad4b3543540389588d01174788
04/12/2016 16:13:31INFO: Getting host-api
04/12/2016 16:13:31INFO: Updating host-api
04/12/2016 16:13:31INFO: Downloading http://rancher.internal.socialbase.com.br:8080/v1//configcontent//host-api current=
04/12/2016 16:13:31INFO: Running /var/lib/cattle/download/host-api/1-22f92c68b705f60d5acea6373b28b7d4ab7233ef6c3eb90bb99d3764d08013a6/apply.sh
04/12/2016 16:13:31INFO: Sending host-api applied 1-22f92c68b705f60d5acea6373b28b7d4ab7233ef6c3eb90bb99d3764d08013a6
04/12/2016 16:13:31INFO: Getting rancher-net
04/12/2016 16:13:31INFO: Updating rancher-net
04/12/2016 16:13:31INFO: Downloading http://rancher.internal.socialbase.com.br:8080/v1//configcontent//rancher-net current=
04/12/2016 16:13:32INFO: Running /var/lib/cattle/download/rancher-net/1-4ff638972a3b918bd129626f79ba289baf0e8912c39c46f9870d1a2b5f6cb299/apply.sh
04/12/2016 16:13:32INFO: HOME -> ./
04/12/2016 16:13:32INFO: HOME -> ./bin/
04/12/2016 16:13:32INFO: HOME -> ./bin/rancher-net
04/12/2016 16:13:32INFO: ROOT -> ./
04/12/2016 16:13:32INFO: ROOT -> ./usr/
04/12/2016 16:13:32INFO: ROOT -> ./usr/local/
04/12/2016 16:13:32INFO: ROOT -> ./usr/local/etc/
04/12/2016 16:13:32INFO: ROOT -> ./usr/local/etc/strongswan.d/
04/12/2016 16:13:32INFO: ROOT -> ./usr/local/etc/strongswan.d/charon-log.conf
04/12/2016 16:13:32INFO: ROOT -> ./etc/
04/12/2016 16:13:32INFO: ROOT -> ./etc/monit/
04/12/2016 16:13:32INFO: ROOT -> ./etc/monit/conf.d/
04/12/2016 16:13:32INFO: ROOT -> ./etc/monit/conf.d/charon
04/12/2016 16:13:32INFO: ROOT -> ./etc/monit/conf.d/rancher-net
04/12/2016 16:13:32INFO: ROOT -> ./etc/init.d/
04/12/2016 16:13:32INFO: ROOT -> ./etc/init.d/charon
04/12/2016 16:13:32INFO: ROOT -> ./etc/init.d/rancher-net
04/12/2016 16:13:32INFO: ROOT -> ./etc/logrotate.d/
04/12/2016 16:13:32INFO: ROOT -> ./etc/logrotate.d/charon
04/12/2016 16:13:32INFO: Sending rancher-net applied 1-4ff638972a3b918bd129626f79ba289baf0e8912c39c46f9870d1a2b5f6cb299
04/12/2016 16:13:32INFO: HOME -> ./
04/12/2016 16:13:32INFO: HOME -> ./etc/
04/12/2016 16:13:32INFO: HOME -> ./etc/cattle/
04/12/2016 16:13:32INFO: HOME -> ./etc/cattle/startup-env
04/12/2016 16:13:32INFO: ROOT -> ./
04/12/2016 16:13:32INFO: ROOT -> ./etc/
04/12/2016 16:13:32INFO: ROOT -> ./etc/init.d/
04/12/2016 16:13:32INFO: ROOT -> ./etc/init.d/agent-instance-startup
04/12/2016 16:13:32INFO: Sending agent-instance-startup applied 3-b430a32b091e19d1daae48060cae567efa4443d03d1b3ee3ce2dd5ea31a70865
04/12/2016 16:13:32Starting monit daemon with http interface at [localhost:2812]
`
Rancher Agent
`
ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=2)
2016-12-04 18:37:33,548 ERROR agent [140402770987280] [event.py:112] Error in request : f0eb40db-c34c-4270-980a-417063fa604b 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 34, in execute
    return method(req=req, **req.data.__dict__)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/delegate.py", line 92, in delegate_request
    by_agent=True)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 320, in get_container
    'label': '{}={}'.format(UUID_LABEL, instance.uuid)})
  File "/var/lib/cattle/pyagent/dist/docker/api/container.py", line 69, in containers
    res = self._result(self._get(u, params=params), True)
  File "/var/lib/cattle/pyagent/dist/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 112, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/adapters.py", line 479, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
2016-12-04 18:37:33,888 ERROR agent [140402771010896] [event.py:112] Error in request : 162599c5-a540-4cf5-9687-89cc6e1db38e 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 34, in execute
    return method(req=req, **req.data.__dict__)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/delegate.py", line 92, in delegate_request
    by_agent=True)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 320, in get_container
    'label': '{}={}'.format(UUID_LABEL, instance.uuid)})
  File "/var/lib/cattle/pyagent/dist/docker/api/container.py", line 69, in containers
    res = self._result(self._get(u, params=params), True)
  File "/var/lib/cattle/pyagent/dist/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 112, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/adapters.py", line 479, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
2016-12-04 18:37:41,391 ERROR agent [140402771012656] [event.py:112] Error in request : 07ae1b5d-0592-4106-ade6-dd1a3d783802 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_handlers.py", line 32, in execute
    type.on_ping(event, resp)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 126, in on_ping
    self._add_instances(ping, pong)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 138, in _add_instances
    running, nonrunning = self._get_all_containers_by_state()
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 171, in _get_all_containers_by_state
    for c in client.containers(all=True):
  File "/var/lib/cattle/pyagent/dist/docker/api/container.py", line 69, in containers
    res = self._result(self._get(u, params=params), True)
  File "/var/lib/cattle/pyagent/dist/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 112, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/adapters.py", line 479, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=2)
`

**Comment by galindro** [comment]
I was able to workarround the problem by restarting the registered hosts

**Comment by aemneina** [comment]
@galindro rancher 1.1.x isnt meant to support docker > 1.11. If you can reproduce this with RancherOS (or any other OS) using docker 1.10/1.11, please open a new ticket.

**Comment by galindro** [comment]
Rancher v.1.2 will support docker > 1.11 ?

**Comment by aemneina** [comment]
@galindro yep! Glad you have your setup currently working.
