### ISSUE TITLE
 etcd panic with a  3 host Kubernetes set up

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5626]
**Rancher Version:**: 1.1.2

**Docker Version:**: 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Kuberentes

**Steps to Reproduce:**
1. Start  Kubernetes setup with 3 hosts using https://github.com/rancher/qa-catalog
2. Create pods/rcs
3. Power down 2 hosts. 
4. Power back 2 host after 5 mins

**Results:** 
etcds did not self heal.
There was a panic .  "8/2/2016 8:22:40 PMpanic: tocommit(22358) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost?" (edited)

```
8/2/2016 8:27:17 PM2016-08-03 03:27:17.412170 I | etcdserver: restarting member 1dce51dc03bae852 in cluster 564dd555b702 at commit index 0
8/2/2016 8:27:17 PM2016-08-03 03:27:17.412717 I | raft: 1dce51dc03bae852 became follower at term 1
8/2/2016 8:27:17 PM2016-08-03 03:27:17.412739 I | raft: newRaft 1dce51dc03bae852 [peers: [], term: 1, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
8/2/2016 8:27:17 PM2016-08-03 03:27:17.413050 I | etcdserver: starting server... [version: 2.3.7, cluster version: to_be_decided]
8/2/2016 8:27:17 PM2016-08-03 03:27:17.429882 I | raft: 1dce51dc03bae852 [term: 1] received a MsgHeartbeat message with higher term from 564dd555b701 [term: 668]
8/2/2016 8:27:17 PM2016-08-03 03:27:17.430044 I | raft: 1dce51dc03bae852 became follower at term 668
8/2/2016 8:27:17 PM2016-08-03 03:27:17.430292 C | raft: tocommit(22358) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost?
8/2/2016 8:27:17 PMpanic: tocommit(22358) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost?
8/2/2016 8:27:17 PM
8/2/2016 8:27:17 PMgoroutine 55 [running]:
8/2/2016 8:27:17 PMpanic(0xbeaf00, 0xc82012c3e0)
8/2/2016 8:27:17 PM     /usr/local/go/src/runtime/panic.go:481 +0x3e6
8/2/2016 8:27:17 PMgithub.com/coreos/etcd/Godeps/_workspace/src/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc8201a9a80, 0x10de7a0, 0x5d, 0xc8200daa40, 0x2, 0x2)
8/2/2016 8:27:17 PM     /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/coreos/pkg/capnslog/pkg_logger.go:73 +0x191
8/2/2016 8:27:17 PMgithub.com/coreos/etcd/raft.(*raftLog).commitTo(0xc8201e69a0, 0x5756)
8/2/2016 8:27:17 PM     /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/log.go:194 +0x1a6
8/2/2016 8:27:17 PMgithub.com/coreos/etcd/raft.(*raft).handleHeartbeat(0xc8201c8240, 0x8, 0x1dce51dc03bae852, 0x564dd555b701, 0x29c, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
8/2/2016 8:27:17 PM     /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:771 +0x44
8/2/2016 8:27:17 PMgithub.com/coreos/etcd/raft.stepFollower(0xc8201c8240, 0x8, 0x1dce51dc03bae852, 0x564dd555b701, 0x29c, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
8/2/2016 8:27:17 PM     /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:736 +0x119c
8/2/2016 8:27:17 PMgithub.com/coreos/etcd/raft.(*raft).Step(0xc8201c8240, 0x8, 0x1dce51dc03bae852, 0x564dd555b701, 0x29c, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
8/2/2016 8:27:17 PM     /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:564 +0x3e0
8/2/2016 8:27:17 PMgithub.com/coreos/etcd/raft.(*node).run(0xc8201ec5a0, 0xc8201c8240)
8/2/2016 8:27:17 PM     /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:310 +0x90e
8/2/2016 8:27:17 PMcreated by github.com/coreos/etcd/raft.RestartNode
8/2/2016 8:27:17 PM     /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:215 +0x2e4

```

**Expected:**
It should be a self healing scenario

**Comment by LLParse** [comment]
Fixed in `etcd:v2.3.7-9`

**Comment by deedubs** [comment]
I just encountered this with a 3-node cluster `etcd:v3.0.16`.

Was in the middle of a rolling re-deploy of the etcd cluster and the last node threw this error.

**Comment by bamb00** [comment]
Could this be a 3 etcd pod limitation? It seems to run into this panic mode consistently.  In kubernetes, deleting the affected etcd pod and the new etcd pod will not self heal.  Any suggestion? or workaround this issue.

I ran into this error in v3.1.16 consistently with 3 pod.  Each pod houses a etcd container.
