### ISSUE TITLE
Convoy-NFS: docker hangs when mounting volume

### ISSUE THREAD

**Issue by willseward** [rancher/rancher#5654]
**Rancher Version:** 1.1.2

**Docker Version:** 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 14.04 DO

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single Node, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** Start a container with a volume from a convoy-nfs driver

**Results:** The docker engine hangs, and the host has to be rebooted (or the docker engine needs to be restarted).

**Expected:** The container should start.

Ever since upgrading my storage backend from convoy-gluster to convoy-nfs, I've been having trouble starting containers with volumes. Every time I do an upgrade, I end up having to chase the container around my cluster and reboot the host that it kills until it finally starts.

Here are some relevant logs:

```text
# convoy-nfs logs

8/7/2016 7:10:10 PMWaiting for metadata
8/7/2016 7:10:11 PMtime="2016-08-08T00:10:11Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/6171/ns/mnt -F -- /var/lib/docker/aufs/mnt/80d34f0b0da4c55c09cd40ba9657328707da7a14ceaebb92d8a1d392d6770e16/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-nfs4-76017438-b36a-4d10-a13e-4cf551cff169 -- /launch volume-agent-nfs-internal 6171]"
8/7/2016 7:10:11 PMRegistering convoy socket at /var/run/convoy-convoy-nfs4.sock
8/7/2016 7:10:11 PMMounting at: /var/lib/rancher/convoy/convoy-nfs4-76017438-b36a-4d10-a13e-4cf551cff169/mnt
8/7/2016 7:10:11 PMMounting nfs. Command: mount -t nfs  10.132.22.36:/srv/ranchernfs /var/lib/rancher/convoy/convoy-nfs4-76017438-b36a-4d10-a13e-4cf551cff169/mnt
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=info msg="Listening for health checks on 0.0.0.0:10241/healthcheck"
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=info msg="Got: root /var/lib/rancher/convoy/convoy-nfs4-76017438-b36a-4d10-a13e-4cf551cff169"
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=info msg="Got: drivers [vfs]"
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=info msg="Got: driver-opts [vfs.path=/var/lib/rancher/convoy/convoy-nfs4-76017438-b36a-4d10-a13e-4cf551cff169/mnt]"
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=info msg="Got: ignore-docker-delete true"
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=info msg="Got: create-on-docker-mount true"
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=info msg="Launching convoy with args: [--socket=/host/var/run/convoy-convoy-nfs4.sock daemon --root=/var/lib/rancher/convoy/convoy-nfs4-76017438-b36a-4d10-a13e-4cf551cff169 --drivers=vfs --driver-opts=vfs.path=/var/lib/rancher/convoy/convoy-nfs4-76017438-b36a-4d10-a13e-4cf551cff169/mnt --ignore-docker-delete=true --create-on-docker-mount=true]"
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=debug msg="Found existing config. Ignoring command line opts, loading config from /var/lib/rancher/convoy/convoy-nfs4-76017438-b36a-4d10-a13e-4cf551cff169" pkg=daemon
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=debug msg= driver=vfs driver_opts=map[vfs.path:/var/lib/rancher/convoy/convoy-nfs4-76017438-b36a-4d10-a13e-4cf551cff169/mnt] event=init pkg=daemon reason=prepare root="/var/lib/rancher/convoy/convoy-nfs4-76017438-b36a-4d10-a13e-4cf551cff169"
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=debug msg= driver=vfs event=init pkg=daemon reason=complete
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=debug msg="Registering GET, /info" pkg=daemon
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=debug msg="Registering GET, /volumes/list" pkg=daemon
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=debug msg="Registering GET, /volumes/" pkg=daemon
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=debug msg="Registering GET, /snapshots/" pkg=daemon
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=debug msg="Registering GET, /backups/list" pkg=daemon
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=debug msg="Registering GET, /backups/inspect" pkg=daemon
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=debug msg="Registering POST, /volumes/mount" pkg=daemon
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=debug msg="Registering POST, /volumes/umount" pkg=daemon
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=debug msg="Registering POST, /snapshots/create" pkg=daemon
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=debug msg="Registering POST, /backups/create" pkg=daemon
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=debug msg="Registering POST, /volumes/create" pkg=daemon
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=debug msg="Registering DELETE, /volumes/" pkg=daemon
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=debug msg="Registering DELETE, /snapshots/" pkg=daemon
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=debug msg="Registering DELETE, /backups" pkg=daemon
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Mount" pkg=daemon
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Unmount" pkg=daemon
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Path" pkg=daemon
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Get" pkg=daemon
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.List" pkg=daemon
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=debug msg="Registering plugin handler POST, /Plugin.Activate" pkg=daemon
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Create" pkg=daemon
8/7/2016 7:10:12 PMtime="2016-08-08T00:10:12Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Remove" pkg=daemon
8/7/2016 7:11:54 PMtime="2016-08-08T00:11:54Z" level=debug msg="Handle plugin activate: POST /Plugin.Activate" pkg=daemon
8/7/2016 7:11:54 PMtime="2016-08-08T00:11:54Z" level=debug msg="Response:  {\n\t\"Implements\": [\n\t\t\"VolumeDriver\"\n\t]\n}" pkg=daemon
8/7/2016 7:11:54 PMtime="2016-08-08T00:11:54Z" level=debug msg="Handle plugin get volume: POST /VolumeDriver.Get" pkg=daemon
8/7/2016 7:11:54 PMtime="2016-08-08T00:11:54Z" level=debug msg="Request from docker: &{mmm_wp map[]}" pkg=daemon
8/7/2016 7:11:54 PMtime="2016-08-08T00:11:54Z" level=debug msg= event=mountpoint object=volume pkg=daemon reason=prepare volume="mmm_wp"
8/7/2016 7:11:54 PMtime="2016-08-08T00:11:54Z" level=debug msg= event=mountpoint mountpoint="/var/lib/rancher/convoy/convoy-nfs4-76017438-b36a-4d10-a13e-4cf551cff169/mnt/mmm_wp" object=volume pkg=daemon reason=complete volume="mmm_wp"
8/7/2016 7:11:54 PMtime="2016-08-08T00:11:54Z" level=debug msg="Found volume mmm_wp for docker" pkg=daemon
8/7/2016 7:11:54 PMtime="2016-08-08T00:11:54Z" level=debug msg="Response:  {\n\t\"Volume\": {\n\t\t\"Name\": \"mmm_wp\",\n\t\t\"Mountpoint\": \"/var/lib/rancher/convoy/convoy-nfs4-76017438-b36a-4d10-a13e-4cf551cff169/mnt/mmm_wp\"\n\t}\n}" pkg=daemon
8/7/2016 7:11:54 PMtime="2016-08-08T00:11:54Z" level=debug msg="Handle plugin get volume: POST /VolumeDriver.Get" pkg=daemon
8/7/2016 7:11:54 PMtime="2016-08-08T00:11:54Z" level=debug msg="Request from docker: &{mmm_wp map[]}" pkg=daemon
8/7/2016 7:11:54 PMtime="2016-08-08T00:11:54Z" level=debug msg= event=mountpoint object=volume pkg=daemon reason=prepare volume="mmm_wp"
8/7/2016 7:11:54 PMtime="2016-08-08T00:11:54Z" level=debug msg= event=mountpoint mountpoint="/var/lib/rancher/convoy/convoy-nfs4-76017438-b36a-4d10-a13e-4cf551cff169/mnt/mmm_wp" object=volume pkg=daemon reason=complete volume="mmm_wp"
8/7/2016 7:11:54 PMtime="2016-08-08T00:11:54Z" level=debug msg="Found volume mmm_wp for docker" pkg=daemon
8/7/2016 7:11:54 PMtime="2016-08-08T00:11:54Z" level=debug msg="Response:  {\n\t\"Volume\": {\n\t\t\"Name\": \"mmm_wp\",\n\t\t\"Mountpoint\": \"/var/lib/rancher/convoy/convoy-nfs4-76017438-b36a-4d10-a13e-4cf551cff169/mnt/mmm_wp\"\n\t}\n}" pkg=daemon
8/7/2016 7:11:54 PMtime="2016-08-08T00:11:54Z" level=debug msg="Handle plugin mount volume: POST /VolumeDriver.Mount" pkg=daemon
8/7/2016 7:11:54 PMtime="2016-08-08T00:11:54Z" level=debug msg="Request from docker: &{mmm_wp map[]}" pkg=daemon
8/7/2016 7:11:54 PMtime="2016-08-08T00:11:54Z" level=debug msg="Mount volume: mmm_wp for docker" pkg=daemon
8/7/2016 7:11:54 PMtime="2016-08-08T00:11:54Z" level=debug msg= event=mount object=volume opts=map[MountPoint:] pkg=daemon reason=prepare volume="mmm_wp"
```

```text
# rancher agent
2016-08-08 00:12:10,151 ERROR agent [140163476257840] [event.py:112] Error in request : 155cd77e-925a-4817-9832-9977a0fb7c2e
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_handlers.py", line 32, in execute
    type.on_ping(event, resp)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 126, in on_ping
    self._add_instances(ping, pong)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 138, in _add_instances
    running, nonrunning = self._get_all_containers_by_state()
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 171, in _get_all_containers_by_state
    for c in client.containers(all=True):
  File "/var/lib/cattle/pyagent/dist/docker/api/container.py", line 69, in containers
    res = self._result(self._get(u, params=params), True)
  File "/var/lib/cattle/pyagent/dist/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 112, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/adapters.py", line 479, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=2)
2016-08-08 00:12:25,259 ERROR agent [140163476257840] [event.py:112] Error in request : 5d3f5c53-a010-487d-a726-1e8f0bcc14e6
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_handlers.py", line 32, in execute
    type.on_ping(event, resp)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 126, in on_ping
    self._add_instances(ping, pong)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 138, in _add_instances
    running, nonrunning = self._get_all_containers_by_state()
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 171, in _get_all_containers_by_state
    for c in client.containers(all=True):
  File "/var/lib/cattle/pyagent/dist/docker/api/container.py", line 69, in containers
    res = self._result(self._get(u, params=params), True)
  File "/var/lib/cattle/pyagent/dist/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 112, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/adapters.py", line 479, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=2)
2016-08-08 00:12:40,304 ERROR agent [140163476257840] [event.py:112] Error in request : 6d0c8d54-f589-4395-8a9d-36d0d228814c
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_handlers.py", line 32, in execute
    type.on_ping(event, resp)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 126, in on_ping
    self._add_instances(ping, pong)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 138, in _add_instances
    running, nonrunning = self._get_all_containers_by_state()
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 171, in _get_all_containers_by_state
    for c in client.containers(all=True):
  File "/var/lib/cattle/pyagent/dist/docker/api/container.py", line 69, in containers
    res = self._result(self._get(u, params=params), True)
  File "/var/lib/cattle/pyagent/dist/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 112, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/adapters.py", line 479, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=2)
2016-08-08 00:12:54,514 ERROR agent [140163476438224] [event.py:112] Error in request : bd0c4038-8af8-44a2-ae39-5c55cae16a90
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 34, in execute
    return method(req=req, **req.data.__dict__)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 529, in instance_activate
    self._do_instance_activate(instance, host, progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 620, in _do_instance_activate
    raise e
ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
2016-08-08 00:12:55,386 ERROR agent [140163476257840] [event.py:112] Error in request : cace8dd9-1446-42d3-85a0-d939b29ebc72
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_handlers.py", line 32, in execute
    type.on_ping(event, resp)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 126, in on_ping
    self._add_instances(ping, pong)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 138, in _add_instances
    running, nonrunning = self._get_all_containers_by_state()
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 171, in _get_all_containers_by_state
    for c in client.containers(all=True):
  File "/var/lib/cattle/pyagent/dist/docker/api/container.py", line 69, in containers
    res = self._result(self._get(u, params=params), True)
  File "/var/lib/cattle/pyagent/dist/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 112, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/adapters.py", line 479, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=2)
2016-08-08 00:13:10,480 ERROR agent [140163476257840] [event.py:112] Error in request : 6161bf63-6a05-492f-88c8-4e0bdc5dfc34
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_handlers.py", line 32, in execute
    type.on_ping(event, resp)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 126, in on_ping
    self._add_instances(ping, pong)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 138, in _add_instances
    running, nonrunning = self._get_all_containers_by_state()
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 171, in _get_all_containers_by_state
    for c in client.containers(all=True):
  File "/var/lib/cattle/pyagent/dist/docker/api/container.py", line 69, in containers
    res = self._result(self._get(u, params=params), True)
  File "/var/lib/cattle/pyagent/dist/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 112, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/adapters.py", line 479, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=2)
```

It looks to me like a race-condition. Anytime the container starts normally the last line in the convoy log will be the mountpoint response.

**Comment by willseward** [comment]
Here's another example:

```text

8/7/2016 7:40:27 PMWaiting for metadata
8/7/2016 7:40:28 PMtime="2016-08-08T00:40:28Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/6249/ns/mnt -F -- /var/lib/docker/aufs/mnt/06d5519f2061a72de14db4c0a82fff0f632983d090631a66976e8bf7a8294b6d/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-nfs4-76017438-b36a-4d10-a13e-4cf551cff169 -- /launch volume-agent-nfs-internal 6249]"
8/7/2016 7:40:29 PMRegistering convoy socket at /var/run/convoy-convoy-nfs4.sock
8/7/2016 7:40:29 PMMounting at: /var/lib/rancher/convoy/convoy-nfs4-76017438-b36a-4d10-a13e-4cf551cff169/mnt
8/7/2016 7:40:29 PMMounting nfs. Command: mount -t nfs  10.132.22.36:/srv/ranchernfs /var/lib/rancher/convoy/convoy-nfs4-76017438-b36a-4d10-a13e-4cf551cff169/mnt
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=info msg="Listening for health checks on 0.0.0.0:10241/healthcheck"
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=info msg="Got: drivers [vfs]"
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=info msg="Got: driver-opts [vfs.path=/var/lib/rancher/convoy/convoy-nfs4-76017438-b36a-4d10-a13e-4cf551cff169/mnt]"
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=info msg="Got: ignore-docker-delete true"
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=info msg="Got: create-on-docker-mount true"
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=info msg="Got: root /var/lib/rancher/convoy/convoy-nfs4-76017438-b36a-4d10-a13e-4cf551cff169"
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=info msg="Launching convoy with args: [--socket=/host/var/run/convoy-convoy-nfs4.sock daemon --drivers=vfs --driver-opts=vfs.path=/var/lib/rancher/convoy/convoy-nfs4-76017438-b36a-4d10-a13e-4cf551cff169/mnt --ignore-docker-delete=true --create-on-docker-mount=true --root=/var/lib/rancher/convoy/convoy-nfs4-76017438-b36a-4d10-a13e-4cf551cff169]"
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=debug msg="Found existing config. Ignoring command line opts, loading config from /var/lib/rancher/convoy/convoy-nfs4-76017438-b36a-4d10-a13e-4cf551cff169" pkg=daemon
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=debug msg= driver=vfs driver_opts=map[vfs.path:/var/lib/rancher/convoy/convoy-nfs4-76017438-b36a-4d10-a13e-4cf551cff169/mnt] event=init pkg=daemon reason=prepare root="/var/lib/rancher/convoy/convoy-nfs4-76017438-b36a-4d10-a13e-4cf551cff169"
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=debug msg= driver=vfs event=init pkg=daemon reason=complete
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=debug msg="Registering GET, /snapshots/" pkg=daemon
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=debug msg="Registering GET, /backups/list" pkg=daemon
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=debug msg="Registering GET, /backups/inspect" pkg=daemon
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=debug msg="Registering GET, /info" pkg=daemon
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=debug msg="Registering GET, /volumes/list" pkg=daemon
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=debug msg="Registering GET, /volumes/" pkg=daemon
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=debug msg="Registering POST, /volumes/umount" pkg=daemon
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=debug msg="Registering POST, /snapshots/create" pkg=daemon
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=debug msg="Registering POST, /backups/create" pkg=daemon
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=debug msg="Registering POST, /volumes/create" pkg=daemon
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=debug msg="Registering POST, /volumes/mount" pkg=daemon
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=debug msg="Registering DELETE, /volumes/" pkg=daemon
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=debug msg="Registering DELETE, /snapshots/" pkg=daemon
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=debug msg="Registering DELETE, /backups" pkg=daemon
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Get" pkg=daemon
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.List" pkg=daemon
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=debug msg="Registering plugin handler POST, /Plugin.Activate" pkg=daemon
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Create" pkg=daemon
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Remove" pkg=daemon
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Mount" pkg=daemon
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Unmount" pkg=daemon
8/7/2016 7:40:29 PMtime="2016-08-08T00:40:29Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Path" pkg=daemon
8/10/2016 7:42:05 PMtime="2016-08-11T00:42:05Z" level=debug msg="Handle plugin activate: POST /Plugin.Activate" pkg=daemon
8/10/2016 7:42:05 PMtime="2016-08-11T00:42:05Z" level=debug msg="Response:  {\n\t\"Implements\": [\n\t\t\"VolumeDriver\"\n\t]\n}" pkg=daemon
8/10/2016 7:42:05 PMtime="2016-08-11T00:42:05Z" level=debug msg="Handle plugin get volume: POST /VolumeDriver.Get" pkg=daemon
8/10/2016 7:42:05 PMtime="2016-08-11T00:42:05Z" level=debug msg="Request from docker: &{certs map[]}" pkg=daemon
8/10/2016 7:42:05 PMtime="2016-08-11T00:42:05Z" level=debug msg= event=mountpoint object=volume pkg=daemon reason=prepare volume=certs
8/10/2016 7:42:05 PMtime="2016-08-11T00:42:05Z" level=debug msg= event=mountpoint mountpoint="/var/lib/rancher/convoy/convoy-nfs4-76017438-b36a-4d10-a13e-4cf551cff169/mnt/certs" object=volume pkg=daemon reason=complete volume=certs
8/10/2016 7:42:05 PMtime="2016-08-11T00:42:05Z" level=debug msg="Found volume certs for docker" pkg=daemon
8/10/2016 7:42:05 PMtime="2016-08-11T00:42:05Z" level=debug msg="Response:  {\n\t\"Volume\": {\n\t\t\"Name\": \"certs\",\n\t\t\"Mountpoint\": \"/var/lib/rancher/convoy/convoy-nfs4-76017438-b36a-4d10-a13e-4cf551cff169/mnt/certs\"\n\t}\n}" pkg=daemon
8/10/2016 7:42:05 PMtime="2016-08-11T00:42:05Z" level=debug msg="Handle plugin mount volume: POST /VolumeDriver.Mount" pkg=daemon
8/10/2016 7:42:05 PMtime="2016-08-11T00:42:05Z" level=debug msg="Request from docker: &{certs map[]}" pkg=daemon
8/10/2016 7:42:05 PMtime="2016-08-11T00:42:05Z" level=debug msg="Mount volume: certs for docker" pkg=daemon
8/10/2016 7:42:05 PMtime="2016-08-11T00:42:05Z" level=debug msg= event=mount object=volume opts=map[MountPoint:] pkg=daemon reason=prepare volume=certs
```

**Comment by willseward** [comment]
I'm closing this as I think my problems were due to my cluster being updated incrementally all the way from v0.35.0... 

A new fresh cluster doesn't have the same problems!
