### ISSUE TITLE
Could not support container.stack  as target address for gelf 

### ISSUE THREAD

**Issue by kala888** [rancher/rancher#5750]
**Rancher Version:**  v1.1.2

**Docker Version:**  1.11.1

**OS and where are the hosts located? (cloud, bare metal, etc):** centos7

**Setup Details:** single node

**Environment Type:** J2EE application with Gaylog2

**Steps to Reproduce:**
1.  Create graylog contains, Stack=Graylog2, Service=graylog2, open port 12201:12201
2. Start graylog containers, ip is 10.42.132.234
3.  Create application contains, Stack=Test, Service=test
4. Config log driver to gelf, config log option gelf-address=udp://graylog2.Graylog2:12201
5. Start test container

**Results:** Could start the test container
**Expected:** Start the test server and send the log to graylog2.Graylog2

**Tips:** 
1.  gelf-address=udp://graylog2.Graylog2:12201 to  gelf-address=udp://10.42.132.234:12201 it works fine.
2.  It looks like cause by docker/docker-compose.
   https://groups.google.com/forum/#!topic/docker-user/d1os7irAb5U
3.  part of error message:

```
2016-08-17 09:30:37,253 ERROR [98ace29e-0403-446f-a05c-b41a6750c960:4109] [instance:161] [instance.start->(InstanceStart)] [] [utorService-692] [i.c.p.process.instance.InstanceStart] Failed to Starting for instance [161] 
2016-08-17 09:30:39,721 ERROR [f7c6a19a-7e71-4dd0-9141-1a4b580e7711:4126] [instance:161->instanceHostMap:139] [instance.start->(InstanceStart)->instancehostmap.activate] [] [utorService-692] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.eventing.exception.EventExecutionException: 404 Client Error: Not Found ("Failed to initialize logging driver: gelf: cannot connect to GELF endpoint: graylog2.Graylog2:12201 dial udp: lookup graylog2.Graylog2 on 127.0.0.1:53: no such host")
    at io.cattle.platform.eventing.exception.EventExecutionException.fromEvent(EventExecutionException.java:53) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.agent.impl.RemoteAgentImpl.callSync(RemoteAgentImpl.java:87) ~[cattle-iaas-agent-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.agent.impl.RemoteAgentImpl.callSync(RemoteAgentImpl.java:135) ~[cattle-iaas-agent-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.process.common.handler.AgentBasedProcessHandler.callSync(AgentBasedProcessHandler.java:180) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.process.common.handler.AgentBasedProcessHandler.handleEvent(AgentBasedProcessHandler.java:166) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.process.common.handler.AgentBasedProcessHandler.handle(AgentBasedProcessHandler.java:104) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:424) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:375) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:369) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:369) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:471) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:305) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:245) [cattle-framework-eng
```

**Comment by drdaeman** [comment]
The `--log-opt gelf-address=udp://...` is passed to the Docker daemon, that's running on host. And it seems that host is unaware about Rancher DNS system, at least with the default setup (i.e. `ping graylog2.graylog2` will fail).

A quick hack/workaround in case there's a single graylog2 container is to explicitly set an IP address and tick "reuse address" option. Worked for me.

Don't know if there's a way to teach hosts to look up the containers as well. If there is any, it may solve the issue. Although I'm not sure when exactly Docker looks up the address as it may do so only on container startup or too infrequently and thus won't notice the updates (e.g. when GL2 container's upgraded).

I guess, the cleanliest and nicest option would be for Rancher to have its own logging driver that acts as a proxy. This way it could be able to survive any sort of reconfigurations, and also probably allow for a way to see the logs both at the normal destination (Graylog, syslog or whatever) and Rancher UI. Just a suggestion.

**Comment by aemneina** [comment]
@drdaeman in 1.2.0, I believe you'll be able to deploy a metadata service that listens on a public port, and query it externally. Closing this ticket out.
