### ISSUE TITLE
Initializing rancher command with external mysql cluster failes

### ISSUE THREAD

**Issue by lukaskroepfl** [rancher/rancher#5754]
**Rancher Version:**
1.1.2
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 LTS in azure
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
rancher ha with external MySQL cluster 7.4.12 and mysql 5.6
**Steps to Reproduce:**
1) setup mysql cluster
2)

```
CREATE DATABASE IF NOT EXISTS rancher COLLATE = 'utf8_general_ci' CHARACTER SET = 'utf8';
GRANT ALL ON rancher.* TO 'username'@'%' IDENTIFIED BY 'pw';
GRANT ALL ON rancher.* TO 'username'@'localhost' IDENTIFIED BY 'pw';
```

3)

```
sudo docker run -d -p 8080:8080 \
-e CATTLE_DB_CATTLE_MYSQL_HOST=10.2.0.4 \
-e CATTLE_DB_CATTLE_MYSQL_PORT=3306 \
-e CATTLE_DB_CATTLE_MYSQL_NAME=rancher \
-e CATTLE_DB_CATTLE_USERNAME=username \
-e CATTLE_DB_CATTLE_PASSWORD=pw \
-v /var/run/docker.sock:/var/run/docker.sock \
--name=rancher \
rancher/server:v1.0.2
```

(username and pw were replaced)

**Results:** (docker logs)

```
CATTLE_AGENT_PACKAGE_AGENT_BINARIES_URL=/usr/share/cattle/artifacts/agent-binaries.tar.gz
CATTLE_AGENT_PACKAGE_CADVISOR_URL=/usr/share/cattle/artifacts/cadvisor.tar.gz
CATTLE_AGENT_PACKAGE_HOST_API_URL=/usr/share/cattle/artifacts/host-api.tar.gz
CATTLE_AGENT_PACKAGE_NODE_AGENT_URL=/usr/share/cattle/artifacts/node-agent.tar.gz
CATTLE_AGENT_PACKAGE_PYTHON_AGENT_URL=/usr/share/cattle/artifacts/python-agent.tar.gz
CATTLE_AGENT_PACKAGE_RANCHER_DNS_URL=/usr/share/cattle/artifacts/rancher-dns.tar.gz
CATTLE_AGENT_PACKAGE_RANCHER_METADATA_URL=/usr/share/cattle/artifacts/rancher-metadata.tar.gz
CATTLE_AGENT_PACKAGE_RANCHER_NET_URL=/usr/share/cattle/artifacts/rancher-net.tar.gz
CATTLE_CATTLE_VERSION=v0.165.8
CATTLE_DB_CATTLE_DATABASE=mysql
CATTLE_DB_CATTLE_MYSQL_HOST=10.2.0.4
CATTLE_DB_CATTLE_MYSQL_NAME=rancher
CATTLE_DB_CATTLE_MYSQL_PORT=3306
CATTLE_DB_CATTLE_USERNAME=root
CATTLE_GRAPHITE_HOST=
CATTLE_GRAPHITE_PORT=
CATTLE_HOME=/var/lib/cattle
CATTLE_HOST_API_PROXY_MODE=embedded
CATTLE_LOGBACK_OUTPUT_GELF_HOST=
CATTLE_LOGBACK_OUTPUT_GELF_PORT=
CATTLE_RANCHER_COMPOSE_VERSION=v0.8.6
CATTLE_RANCHER_SERVER_IMAGE=rancher/server
CATTLE_RANCHER_SERVER_VERSION=v1.1.2
CATTLE_USE_LOCAL_ARTIFACTS=true
DEFAULT_CATTLE_API_UI_INDEX=//releases.rancher.com/ui/1.1.12
DEFAULT_CATTLE_CATALOG_EXECUTE=true
DEFAULT_CATTLE_CATALOG_URL=library=https://github.com/rancher/rancher-catalog.git,community=https://github.com/rancher/community-catalog.git
DEFAULT_CATTLE_COMPOSE_EXECUTOR_EXECUTE=true
DEFAULT_CATTLE_MACHINE_EXECUTE=true
DEFAULT_CATTLE_RANCHER_COMPOSE_DARWIN_URL=https://releases.rancher.com/compose/v0.8.6/rancher-compose-darwin-amd64-v0.8.6.tar.gz
DEFAULT_CATTLE_RANCHER_COMPOSE_LINUX_URL=https://releases.rancher.com/compose/v0.8.6/rancher-compose-linux-amd64-v0.8.6.tar.gz
DEFAULT_CATTLE_RANCHER_COMPOSE_WINDOWS_URL=https://releases.rancher.com/compose/v0.8.6/rancher-compose-windows-386-v0.8.6.zip
13:34:30.843 [main] WARN  o.e.jetty.security.SecurityHandler - ServletContext@o.e.j.w.WebAppContext@25295985{/,file:/usr/share/cattle/be21b2bf0c1a2d74b75c887ce9982c6e/,STARTING}{file:/usr/share/cattle/be21b2bf0c1a2d74b75c887ce9982c6e/} has uncovered http methods for path: /
13:34:31.701 [main] INFO  ConsoleStatus - [1/6] [0ms] [1ms] Loading config-bootstrap
13:34:31.826 [main] INFO  ConsoleStatus - [2/6] [127ms] [123ms] Loading base-config
13:34:32.027 [main] INFO  ConsoleStatus - [3/6] [328ms] [201ms] Loading config
13:34:32.032 [main] INFO  ConsoleStatus - [4/6] [333ms] [5ms] Starting config-bootstrap
13:34:32.226 [main] INFO  ConsoleStatus - [5/6] [527ms] [194ms] Starting base-config
13:34:32.226 [main] INFO  ConsoleStatus - [6/6] [527ms] [0ms] Starting config
2016-08-17 13:34:32,418 INFO    [main] [ConsoleStatus] [1/32] [0ms] [0ms] Loading bootstrap 
2016-08-17 13:34:32,473 INFO    [main] [ConsoleStatus] [2/32] [55ms] [55ms] Loading config-defaults 
2016-08-17 13:34:35,277 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case 
2016-08-17 13:34:35,413 ERROR   [main] [liquibase] classpath:db/changelog.xml: db/core-077.xml::dump2::darren (generated): Change Set db/core-077.xml::dump2::darren (generated) failed.  Error: Error executing SQL CREATE INDEX idx_volume_uri ON rancher.volume(uri): Index column size too large. The maximum column size is 767 bytes. liquibase.exception.DatabaseException: Error executing SQL CREATE INDEX idx_volume_uri ON rancher.volume(uri): Index column size too large. The maximum column size is 767 bytes.
    at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:61) ~[liquibase-core-3.1.0.jar:na]
    at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:106) ~[liquibase-core-3.1.0.jar:na]
    at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1189) ~[liquibase-core-3.1.0.jar:na]
    at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1172) ~[liquibase-core-3.1.0.jar:na]
    at liquibase.changelog.ChangeSet.execute(ChangeSet.java:352) ~[liquibase-core-3.1.0.jar:na]
    at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:40) [liquibase-core-3.1.0.jar:na]
    at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:64) [liquibase-core-3.1.0.jar:na]
    at liquibase.Liquibase.update(Liquibase.java:202) [liquibase-core-3.1.0.jar:na]
    at liquibase.Liquibase.update(Liquibase.java:181) [liquibase-core-3.1.0.jar:na]
    at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:342) [liquibase-core-3.1.0.jar:na]
    at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:299) [liquibase-core-3.1.0.jar:na]
    at io.cattle.platform.liquibase.Loader.afterPropertiesSet(Loader.java:62) [cattle-framework-db-loader-0.5.0-SNAPSHOT.jar:na]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1571) [spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1509) [spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:521) [spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458) [spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:296) [spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223) [spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:293) [spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) [spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:628) [spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932) [spring-context-3.2.4.RELEASE.jar:3.2.4.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479) [spring-context-3.2.4.RELEASE.jar:3.2.4.RELEASE]
    at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.loadContext(DefaultModuleDefinitionSet.java:184) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
    at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet$2.with(DefaultModuleDefinitionSet.java:157) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
    at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:348) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
    at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:358) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
    at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:333) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
    at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.loadContexts(DefaultModuleDefinitionSet.java:152) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
    at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.load(DefaultModuleDefinitionSet.java:97) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
    at org.apache.cloudstack.spring.module.factory.ModuleBasedContextFactory.loadModules(ModuleBasedContextFactory.java:37) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
    at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.init(CloudStackSpringContext.java:75) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
    at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.<init>(CloudStackSpringContext.java:56) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.context.SpringContext.<init>(SpringContext.java:11) [cattle-iaas-system-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.context.WebContextLoaderListener.constructCloudStackSpringContext(WebContextLoaderListener.java:15) [cattle-iaas-system-0.5.0-SNAPSHOT.jar:na]
    at org.apache.cloudstack.spring.module.web.CloudStackContextLoaderListener.contextInitialized(CloudStackContextLoaderListener.java:51) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349) [jetty-webapp-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342) [jetty-webapp-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505) [jetty-webapp-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.Server.start(Server.java:387) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.Server.doStart(Server.java:354) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
    at io.cattle.platform.launcher.jetty.Main.main(Main.java:145) [be21b2bf0c1a2d74b75c887ce9982c6e/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_101]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_101]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_101]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_101]
    at io.cattle.platform.launcher.Main.run(Main.java:188) [be21b2bf0c1a2d74b75c887ce9982c6e/:na]
    at io.cattle.platform.launcher.Main.main(Main.java:251) [be21b2bf0c1a2d74b75c887ce9982c6e/:na]
Caused by: java.sql.SQLException: Index column size too large. The maximum column size is 767 bytes.
    at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:136) ~[mariadb-java-client-1.3.4.jar:na]
    at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69) ~[mariadb-java-client-1.3.4.jar:na]
    at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:261) ~[mariadb-java-client-1.3.4.jar:na]
    at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:290) ~[mariadb-java-client-1.3.4.jar:na]
    at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:344) ~[mariadb-java-client-1.3.4.jar:na]
    at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264) ~[commons-dbcp-1.4.jar:1.4]
    at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264) ~[commons-dbcp-1.4.jar:1.4]
    at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:294) ~[liquibase-core-3.1.0.jar:na]
    at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:54) ~[liquibase-core-3.1.0.jar:na]
    ... 57 common frames omitted
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Index column size too large. The maximum column size is 767 bytes.
    at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:475) ~[mariadb-java-client-1.3.4.jar:na]
    at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.result(AbstractQueryProtocol.java:396) ~[mariadb-java-client-1.3.4.jar:na]
    at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:378) ~[mariadb-java-client-1.3.4.jar:na]
    at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:334) ~[mariadb-java-client-1.3.4.jar:na]
    at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:280) ~[mariadb-java-client-1.3.4.jar:na]
    ... 62 common frames omitted
```

**Expected**
Successful startup

**Comment by lukaskroepfl** [comment]
Update: Rancher does not work with mysql cluster as the database engine ndbcluster limits the maximum row size to 14000 bytes which cannot be changed.

**Comment by aemneina** [comment]
@lukaskroepfl we're only certified against the innodb mysql engine.

**Comment by nweiler** [comment]
I am seeing similar errors with creating a fresh install on a remote mysql instance (non-clustered):
```
docker volume create --name db1
docker run -d --name db1 -e MYSQL_ALLOW_EMPTY_PASSWORD=true -p 3306:3306 -v db1:/var/lib/mysql mysql
docker exec db1 mysql -e "CREATE DATABASE IF NOT EXISTS cattle COLLATE = 'utf8_general_ci' CHARACTER SET = 'utf8';"
docker exec db1 mysql -e "GRANT ALL ON cattle.* TO 'cattle'@'%' IDENTIFIED BY 'cattle';"
docker exec db1 mysql -e "GRANT ALL ON cattle.* TO 'cattle'@'localhost' IDENTIFIED BY 'cattle';"
docker exec db1 bash -c "echo 'bind-address=0.0.0.0' >> /etc/mysql/mysql.conf.d/mysqld.cnf"
docker restart db1
docker run -d --name rancher1 -p 8080:8080 --link db1:db1 rancher/server:latest --db-host db1 --db-port 3306 --db-user cattle --db-pass cattle --db-name cattle
```

Here are the logs:
```
CATTLE_AGENT_PACKAGE_HOST_API_URL=/usr/share/cattle/artifacts/host-api.tar.gz
CATTLE_AGENT_PACKAGE_PYTHON_AGENT_URL=/usr/share/cattle/artifacts/go-agent.tar.gz
CATTLE_API_UI_URL=//releases.rancher.com/api-ui/1.0.8
CATTLE_CATTLE_VERSION=v0.181.3
CATTLE_DB_CATTLE_DATABASE=mysql
CATTLE_DB_CATTLE_MYSQL_HOST=db1
CATTLE_DB_CATTLE_MYSQL_NAME=cattle
CATTLE_DB_CATTLE_MYSQL_PORT=3306
CATTLE_DB_CATTLE_USERNAME=cattle
CATTLE_GRAPHITE_HOST=
CATTLE_GRAPHITE_PORT=
CATTLE_HOME=/var/lib/cattle
CATTLE_HOST_API_PROXY_MODE=embedded
CATTLE_LOGBACK_OUTPUT_GELF_HOST=
CATTLE_LOGBACK_OUTPUT_GELF_PORT=
CATTLE_RANCHER_CLI_VERSION=v0.6.1
CATTLE_RANCHER_COMPOSE_VERSION=v0.12.5
CATTLE_RANCHER_SERVER_IMAGE=rancher/server
CATTLE_RANCHER_SERVER_VERSION=v1.6.1
CATTLE_USE_LOCAL_ARTIFACTS=true
DEFAULT_CATTLE_API_UI_CSS_URL=/api-ui/ui.min.css
DEFAULT_CATTLE_API_UI_INDEX=//releases.rancher.com/ui/1.6.5
DEFAULT_CATTLE_API_UI_JS_URL=/api-ui/ui.min.js
DEFAULT_CATTLE_AUTH_SERVICE_EXECUTE=true
DEFAULT_CATTLE_CATALOG_EXECUTE=true
DEFAULT_CATTLE_CATALOG_URL={"catalogs":{"community":{"url":"https://git.rancher.io/community-catalog.git","branch":"master"},"library":{"url":"https://git.rancher.io/rancher-catalog.git","branch":"${RELEASE}"}}}
DEFAULT_CATTLE_COMPOSE_EXECUTOR_EXECUTE=true
DEFAULT_CATTLE_MACHINE_EXECUTE=true
DEFAULT_CATTLE_RANCHER_CLI_DARWIN_URL=https://releases.rancher.com/cli/v0.6.1/rancher-darwin-amd64-v0.6.1.tar.gz
DEFAULT_CATTLE_RANCHER_CLI_LINUX_URL=https://releases.rancher.com/cli/v0.6.1/rancher-linux-amd64-v0.6.1.tar.gz
DEFAULT_CATTLE_RANCHER_CLI_WINDOWS_URL=https://releases.rancher.com/cli/v0.6.1/rancher-windows-386-v0.6.1.zip
DEFAULT_CATTLE_RANCHER_COMPOSE_DARWIN_URL=https://releases.rancher.com/compose/v0.12.5/rancher-compose-darwin-amd64-v0.12.5.tar.gz
DEFAULT_CATTLE_RANCHER_COMPOSE_LINUX_URL=https://releases.rancher.com/compose/v0.12.5/rancher-compose-linux-amd64-v0.12.5.tar.gz
DEFAULT_CATTLE_RANCHER_COMPOSE_WINDOWS_URL=https://releases.rancher.com/compose/v0.12.5/rancher-compose-windows-386-v0.12.5.zip
DEFAULT_CATTLE_SECRETS_API_EXECUTE=true
DEFAULT_CATTLE_WEBHOOK_SERVICE_EXECUTE=true
04:08:12.516 [main] INFO  ConsoleStatus - Loading configuration
2017-06-09 04:08:19,307 INFO    [main] [ConsoleStatus] Starting DB migration
2017-06-09 04:08:22,449 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2017-06-09 04:08:22,449 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2017-06-09 04:08:22,450 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2017-06-09 04:08:22,451 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2017-06-09 04:08:22,456 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2017-06-09 04:08:22,459 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2017-06-09 04:08:22,461 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2017-06-09 04:08:22,462 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2017-06-09 04:08:22,462 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2017-06-09 04:08:22,462 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2017-06-09 04:08:22,463 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
...
```

**Comment by Parth6288** [comment]
Is there a fix for this? I am also facing the same issue using non clustered mysql external db with rancher server.

**Comment by ekarlso** [comment]
Same error.

**Comment by vincent99** [comment]
the `modifyDataType will lose primary key/autoincrement/not null settings for mysql.` message does not indicate any actual problem that  something has to be done about...

**Comment by superseb** [comment]
This was closed a year ago, please file a new issue with the problem description.
