### ISSUE TITLE
First impressions, swarm env, netgap

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#5895]
**Rancher Version:**

1.1.2

**Docker Version:**

1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**

RHEL 7.2, Baremetal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single node, external DB. Agent nodes does not reach public internet.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Swarm.

**Steps to Reproduce:**

Add two nodes to a swarm env. Pulled rancher/swarm-agent from internal registry and retagged so it looks like it was pulled from docker hub.

**Results:** 

`Swarm_swarm_1` kept restarting, with the following log excerpt:

```
time="2016-09-05T10:32:46Z" level=info msg="Using temp file /tmp/swarm212715296" 
time="2016-09-05T10:32:46Z" level=info msg="Running swarm [manage --heartbeat 2s -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock file:///tmp/swarm212715296]" 
time="2016-09-05T10:32:46Z" level=info msg="Watching for changes DE2AEA6E285A3CC31913 http://api.rancher..../v1" 
time="2016-09-05T10:32:46Z" level=info msg="Listening for HTTP" addr="/var/run/docker.sock" proto=unix 
time="2016-09-05T10:32:46Z" level=info msg="Listening for HTTP" addr="0.0.0.0:2375" proto=tcp 
time="2016-09-05T10:32:48Z" level=error msg="Error gettings hosts: Get http://169.254.169.250/2015-12-19/hosts: read tcp 172.17.0.4:60121->169.254.169.250:80: read: connection reset by peer" 
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x63 pc=0x7f012dacb6a9]

runtime stack:
runtime.throw(0xa49e60, 0x2a)
    /usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
    /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 23 [syscall, locked to thread]:
runtime.cgocall(0x743aa0, 0xc820542438, 0xc800000000)
    /usr/local/go/src/runtime/cgocall.go:120 +0x11b fp=0xc8205423e0 sp=0xc8205423b0
net._C2func_getaddrinfo(0x7f0124000b30, 0x0, 0xc82050e4b0, 0xc8200fe030, 0x0, 0x0, 0x0)
    ??:0 +0x4d fp=0xc820542438 sp=0xc8205423e0
net.cgoLookupIPCNAME(0xc82050e420, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa9e600)
    /usr/local/go/src/net/cgo_unix.go:111 +0x1ac fp=0xc820542560 sp=0xc820542438
net.cgoLookupIP(0xc82050e420, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/cgo_unix.go:163 +0x56 fp=0xc8205425b8 sp=0xc820542560
net.lookupIP(0xc82050e420, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/lookup_unix.go:67 +0x94 fp=0xc820542628 sp=0xc8205425b8
net.glob.func15(0xa9e640, 0xc82050e420, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/hook.go:10 +0x4d fp=0xc820542668 sp=0xc820542628
net.lookupIPDeadline.func1(0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/lookup.go:106 +0x71 fp=0xc8205426e8 sp=0xc820542668
internal/singleflight.(*Group).doCall(0xe65310, 0xc820159180, 0xc82050e420, 0x20, 0xc820510280)
    /usr/local/go/src/internal/singleflight/singleflight.go:93 +0x2c fp=0xc820542798 sp=0xc8205426e8
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc8205427a0 sp=0xc820542798
created by internal/singleflight.(*Group).DoChan
    /usr/local/go/src/internal/singleflight/singleflight.go:86 +0x3ed

goroutine 1 [syscall]:
syscall.Syscall6(0x3d, 0xa, 0xc8200e6ca4, 0x0, 0xc8200c4480, 0x0, 0x0, 0x896fc0, 0xc82001a3c0, 0x0)
    /usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.wait4(0xa, 0xc8200e6ca4, 0x0, 0xc8200c4480, 0x90, 0x0, 0x0)
    /usr/local/go/src/syscall/zsyscall_linux_amd64.go:172 +0x72
syscall.Wait4(0xa, 0xc8200e6cec, 0x0, 0xc8200c4480, 0xc82005c018, 0x0, 0x0)
    /usr/local/go/src/syscall/syscall_linux.go:256 +0x55
os.(*Process).wait(0xc820010cc0, 0x8, 0x0, 0x0)
    /usr/local/go/src/os/exec_unix.go:22 +0x105
os.(*Process).Wait(0xc820010cc0, 0x0, 0x0, 0x0)
    /usr/local/go/src/os/doc.go:45 +0x2d
os/exec.(*Cmd).Wait(0xc8200d2500, 0x0, 0x0)
    /usr/local/go/src/os/exec/exec.go:380 +0x211
os/exec.(*Cmd).Run(0xc8200d2500, 0x0, 0x0)
    /usr/local/go/src/os/exec/exec.go:258 +0x64
main.runServer(0xc8200d23c0)
    /go/src/github.com/rancher/swarm-agent/main.go:96 +0xae0
github.com/rancher/swarm-agent/vendor/github.com/codegangsta/cli.Command.Run(0x9ad2d0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /go/src/github.com/rancher/swarm-agent/vendor/github.com/codegangsta/cli/command.go:174 +0x1397
github.com/rancher/swarm-agent/vendor/github.com/codegangsta/cli.(*App).Run(0xc8200d2140, 0xc82000a0b0, 0xb, 0xb, 0x0, 0x0)
    /go/src/github.com/rancher/swarm-agent/vendor/github.com/codegangsta/cli/app.go:187 +0x1135
main.main()
    /go/src/github.com/rancher/swarm-agent/main.go:65 +0x6d7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [chan receive]:
github.com/rancher/swarm-agent/vendor/github.com/rancher/event-subscriber/locks.locker()
    /go/src/github.com/rancher/swarm-agent/vendor/github.com/rancher/event-subscriber/locks/locks.go:61 +0xda
created by github.com/rancher/swarm-agent/vendor/github.com/rancher/event-subscriber/locks.init.1
    /go/src/github.com/rancher/swarm-agent/vendor/github.com/rancher/event-subscriber/locks/locks.go:7 +0x59

goroutine 6 [sleep]:
time.Sleep(0x77359400)
    /usr/local/go/src/runtime/time.go:59 +0xf9
github.com/rancher/swarm-agent/server.Watch(0xc8200109a0, 0x13, 0xc820010a80, 0x14, 0xc820014f90, 0x28, 0xc820014fc0, 0x2a, 0x0, 0x0)
    /go/src/github.com/rancher/swarm-agent/server/watch.go:37 +0x3d1
created by main.runServer
    /go/src/github.com/rancher/swarm-agent/main.go:86 +0x4f1

goroutine 20 [IO wait]:
net.runtime_pollWait(0x7f012ed1b000, 0x72, 0xc820016120)
    /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8205340d0, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8205340d0, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820534070, 0xc8202bb000, 0x1000, 0x1000, 0x0, 0x7f013055d050, 0xc820016120)
    /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200fe018, 0xc8202bb000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f012ecda000, 0xc8200fe018, 0xc820548058, 0xc8202bb000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc820510200, 0xc8202bb000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8204e18c0)
    /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8204e18c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc820548000)
    /usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 21 [select]:
net/http.(*persistConn).writeLoop(0xc820548000)
    /usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 9 [IO wait]:
net.runtime_pollWait(0x7f012ed1ae80, 0x72, 0xc820016120)
    /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820088370, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820088370, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820088310, 0xc820152000, 0x1000, 0x1000, 0x0, 0x7f013055d050, 0xc820016120)
    /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82005c058, 0xc820152000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f012ecda000, 0xc82005c058, 0xc82000a318, 0xc820152000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc820010f40, 0xc820152000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc82001a8a0)
    /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc82001a8a0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82000a2c0)
    /usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 10 [select]:
net/http.(*persistConn).writeLoop(0xc82000a2c0)
    /usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 22 [select]:
net.lookupIPDeadline(0xc82050e420, 0x20, 0xecf5f40f0, 0x17d00d4c, 0xe65da0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/lookup.go:109 +0x6a5
net.internetAddrList(0x9ad6d8, 0x3, 0xc82050e420, 0x23, 0xecf5f40f0, 0x17d00d4c, 0xe65da0, 0x0, 0x0, 0x0, ...)
    /usr/local/go/src/net/ipsock.go:252 +0x6ee
net.resolveAddrList(0x9ab768, 0x4, 0x9ad6d8, 0x3, 0xc82050e420, 0x23, 0xecf5f40f0, 0xc817d00d4c, 0xe65da0, 0x0, ...)
    /usr/local/go/src/net/dial.go:153 +0x466
net.(*Dialer).Dial(0xc82000e410, 0x9ad6d8, 0x3, 0xc82050e420, 0x23, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/dial.go:209 +0x124
net.(*Dialer).Dial-fm(0x9ad6d8, 0x3, 0xc82050e420, 0x23, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:38 +0x6e
net/http.(*Transport).dial(0xc8200c4090, 0x9ad6d8, 0x3, 0xc82050e420, 0x23, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:499 +0x79
net/http.(*Transport).dialConn(0xc8200c4090, 0x0, 0xc8204e1a40, 0x4, 0xc82050e420, 0x23, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:596 +0x19a9
net/http.(*Transport).getConn.func4(0xc8200c4090, 0x0, 0xc8204e1a40, 0x4, 0xc82050e420, 0x23, 0xc8204e1c20)
    /usr/local/go/src/net/http/transport.go:549 +0x66
created by net/http.(*Transport).getConn
    /usr/local/go/src/net/http/transport.go:551 +0x265

goroutine 51 [select]:
net/http.(*persistConn).roundTrip(0xc82000a2c0, 0xc8200177d0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:1164 +0xb0d
net/http.(*Transport).RoundTrip(0xc8200c4090, 0xc8200ea2a0, 0xae, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:235 +0x530
net/http.send(0xc8200ea2a0, 0x7f0130561500, 0xc8200c4090, 0xc82001ac00, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:220 +0x52c
net/http.(*Client).send(0xc82007db10, 0xc8200ea2a0, 0x55, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:143 +0x15a
net/http.(*Client).doFollowingRedirects(0xc82007db10, 0xc8200ea2a0, 0xa9e720, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:380 +0xbc0
net/http.(*Client).Do(0xc82007db10, 0xc8200ea2a0, 0xc82001aa80, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:175 +0x9c
github.com/rancher/swarm-agent/vendor/github.com/rancher/go-rancher/client.(*RancherBaseClient).doGet(0xc820140000, 0xc82001aa80, 0x55, 0xc82007da58, 0x7f0fc0, 0xc820001c80, 0x0, 0x0)
    /go/src/github.com/rancher/swarm-agent/vendor/github.com/rancher/go-rancher/client/common.go:249 +0x37f
github.com/rancher/swarm-agent/vendor/github.com/rancher/go-rancher/client.(*RancherBaseClient).doById(0xc820140000, 0x9ac020, 0x4, 0xc820528360, 0x24, 0x7f0fc0, 0xc820001c80, 0x0, 0x0)
    /go/src/github.com/rancher/swarm-agent/vendor/github.com/rancher/go-rancher/client/common.go:431 +0x5a2
github.com/rancher/swarm-agent/vendor/github.com/rancher/go-rancher/client.(*HostClient).ById(0xc82010a270, 0xc820528360, 0x24, 0x0, 0x0, 0x0)
    /go/src/github.com/rancher/swarm-agent/vendor/github.com/rancher/go-rancher/client/generated_host.go:114 +0xbe
github.com/rancher/swarm-agent/vendor/github.com/rancher/rancher-docker-api-proxy.(*Proxy).getHost(0xc820538300, 0x815fc0, 0x0, 0x0)
    /go/src/github.com/rancher/swarm-agent/vendor/github.com/rancher/rancher-docker-api-proxy/server.go:155 +0x7f
github.com/rancher/swarm-agent/vendor/github.com/rancher/rancher-docker-api-proxy.(*Proxy).ListenAndServe(0xc820538300, 0x0, 0x0)
    /go/src/github.com/rancher/swarm-agent/vendor/github.com/rancher/rancher-docker-api-proxy/server.go:66 +0x54
github.com/rancher/swarm-agent/server.(*Proxy).AddHosts.func1(0xc820538300, 0xc820528360, 0x24)
    /go/src/github.com/rancher/swarm-agent/server/server.go:48 +0x30
created by github.com/rancher/swarm-agent/server.(*Proxy).AddHosts
    /go/src/github.com/rancher/swarm-agent/server/server.go:51 +0xb24

goroutine 52 [select]:
net/http.(*Transport).getConn(0xc8200c4090, 0xc8200fa380, 0x0, 0xc8204e1a40, 0x4, 0xc82050e420, 0x23, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:554 +0x663
net/http.(*Transport).RoundTrip(0xc8200c4090, 0xc8200fa380, 0xae, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:228 +0x4ac
net/http.send(0xc8200fa380, 0x7f0130561500, 0xc8200c4090, 0xc8204e1bc0, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:220 +0x52c
net/http.(*Client).send(0xc82054fb10, 0xc8200fa380, 0x55, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:143 +0x15a
net/http.(*Client).doFollowingRedirects(0xc82054fb10, 0xc8200fa380, 0xa9e720, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:380 +0xbc0
net/http.(*Client).Do(0xc82054fb10, 0xc8200fa380, 0xc8204e1a40, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:175 +0x9c
github.com/rancher/swarm-agent/vendor/github.com/rancher/go-rancher/client.(*RancherBaseClient).doGet(0xc820140000, 0xc8204e1a40, 0x55, 0xc82054fa58, 0x7f0fc0, 0xc820094c00, 0x0, 0x0)
    /go/src/github.com/rancher/swarm-agent/vendor/github.com/rancher/go-rancher/client/common.go:249 +0x37f
github.com/rancher/swarm-agent/vendor/github.com/rancher/go-rancher/client.(*RancherBaseClient).doById(0xc820140000, 0x9ac020, 0x4, 0xc820528450, 0x24, 0x7f0fc0, 0xc820094c00, 0x0, 0x0)
    /go/src/github.com/rancher/swarm-agent/vendor/github.com/rancher/go-rancher/client/common.go:431 +0x5a2
github.com/rancher/swarm-agent/vendor/github.com/rancher/go-rancher/client.(*HostClient).ById(0xc82010a270, 0xc820528450, 0x24, 0x0, 0x0, 0x0)
    /go/src/github.com/rancher/swarm-agent/vendor/github.com/rancher/go-rancher/client/generated_host.go:114 +0xbe
github.com/rancher/swarm-agent/vendor/github.com/rancher/rancher-docker-api-proxy.(*Proxy).getHost(0xc820538340, 0x0, 0x0, 0x0)
    /go/src/github.com/rancher/swarm-agent/vendor/github.com/rancher/rancher-docker-api-proxy/server.go:155 +0x7f
github.com/rancher/swarm-agent/vendor/github.com/rancher/rancher-docker-api-proxy.(*Proxy).ListenAndServe(0xc820538340, 0x0, 0x0)
    /go/src/github.com/rancher/swarm-agent/vendor/github.com/rancher/rancher-docker-api-proxy/server.go:66 +0x54
github.com/rancher/swarm-agent/server.(*Proxy).AddHosts.func1(0xc820538340, 0xc820528450, 0x24)
    /go/src/github.com/rancher/swarm-agent/server/server.go:48 +0x30
created by github.com/rancher/swarm-agent/server.(*Proxy).AddHosts
    /go/src/github.com/rancher/swarm-agent/server/server.go:51 +0xb24
```

And `Swarm_swarm-agent_1` is active, green, but also with stacktraces in the logs:

```
time="2016-09-05T09:54:32Z" level=info msg="Listening for health checks on 0.0.0.0:10240/healthcheck" 
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x63 pc=0x7fa83a7086a9]

runtime stack:
runtime.throw(0xa49e60, 0x2a)
    /usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
    /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 22 [syscall, locked to thread]:
runtime.cgocall(0x743aa0, 0xc82005cc38, 0xc800000000)
    /usr/local/go/src/runtime/cgocall.go:120 +0x11b fp=0xc82005cbe0 sp=0xc82005cbb0
net._C2func_getaddrinfo(0x7fa8300008c0, 0x0, 0xc8200e2420, 0xc8200e8420, 0x0, 0x0, 0x0)
    ??:0 +0x4d fp=0xc82005cc38 sp=0xc82005cbe0
net.cgoLookupIPCNAME(0xc8200e2390, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa9e600)
    /usr/local/go/src/net/cgo_unix.go:111 +0x1ac fp=0xc82005cd60 sp=0xc82005cc38
net.cgoLookupIP(0xc8200e2390, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fa83b15a880)
    /usr/local/go/src/net/cgo_unix.go:163 +0x56 fp=0xc82005cdb8 sp=0xc82005cd60
net.lookupIP(0xc8200e2390, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/lookup_unix.go:67 +0x94 fp=0xc82005ce28 sp=0xc82005cdb8
net.glob.func15(0xa9e640, 0xc8200e2390, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/hook.go:10 +0x4d fp=0xc82005ce68 sp=0xc82005ce28
net.lookupIPDeadline.func1(0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/lookup.go:106 +0x71 fp=0xc82005cee8 sp=0xc82005ce68
internal/singleflight.(*Group).doCall(0xe65310, 0xc8200fe140, 0xc8200e2390, 0x20, 0xc8200fa2c0)
    /usr/local/go/src/internal/singleflight/singleflight.go:93 +0x2c fp=0xc82005cf98 sp=0xc82005cee8
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc82005cfa0 sp=0xc82005cf98
created by internal/singleflight.(*Group).DoChan
    /usr/local/go/src/internal/singleflight/singleflight.go:86 +0x3ed

goroutine 1 [chan receive]:
main.launch(0xc8200c6280)
    /go/src/github.com/rancher/swarm-agent/main.go:117 +0xf1
github.com/rancher/swarm-agent/vendor/github.com/codegangsta/cli.(*App).Run(0xc8200c6140, 0xc82000a210, 0x1, 0x1, 0x0, 0x0)
    /go/src/github.com/rancher/swarm-agent/vendor/github.com/codegangsta/cli/app.go:192 +0x1187
main.main()
    /go/src/github.com/rancher/swarm-agent/main.go:65 +0x6d7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [chan receive]:
github.com/rancher/swarm-agent/vendor/github.com/rancher/event-subscriber/locks.locker()
    /go/src/github.com/rancher/swarm-agent/vendor/github.com/rancher/event-subscriber/locks/locks.go:61 +0xda
created by github.com/rancher/swarm-agent/vendor/github.com/rancher/event-subscriber/locks.init.1
    /go/src/github.com/rancher/swarm-agent/vendor/github.com/rancher/event-subscriber/locks/locks.go:7 +0x59

goroutine 6 [select]:
net/http.(*Transport).getConn(0xc820012240, 0xc8200ec0e0, 0x0, 0xc8200dc4c0, 0x4, 0xc8200e2390, 0x23, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:554 +0x663
net/http.(*Transport).RoundTrip(0xc820012240, 0xc8200ec0e0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:228 +0x4ac
net/http.send(0xc8200ec0e0, 0x7fa83b15a500, 0xc820012240, 0xc8200dc6c0, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:220 +0x52c
net/http.(*Client).send(0xc82008ba80, 0xc8200ec0e0, 0x32, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:143 +0x15a
net/http.(*Client).doFollowingRedirects(0xc82008ba80, 0xc8200ec0e0, 0xa9e720, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:380 +0xbc0
net/http.(*Client).Do(0xc82008ba80, 0xc8200ec0e0, 0x14, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:175 +0x9c
github.com/rancher/swarm-agent/vendor/github.com/rancher/go-rancher/client.setupRancherBaseClient(0xc8200e6000, 0xc8200dc040, 0x0, 0x0)
    /go/src/github.com/rancher/swarm-agent/vendor/github.com/rancher/go-rancher/client/common.go:151 +0x8d8
github.com/rancher/swarm-agent/vendor/github.com/rancher/go-rancher/client.NewRancherClient(0xc8200dc040, 0xc8200dc040, 0x0, 0x0)
    /go/src/github.com/rancher/swarm-agent/vendor/github.com/rancher/go-rancher/client/generated_client.go:272 +0x4b
github.com/rancher/swarm-agent/vendor/github.com/rancher/event-subscriber/events.NewEventRouter(0x0, 0x0, 0x0, 0xc820018e70, 0x2a, 0xc820010900, 0x14, 0xc820018ea0, 0x28, 0x0, ...)
    /go/src/github.com/rancher/swarm-agent/vendor/github.com/rancher/event-subscriber/events/listener.go:49 +0xe7
github.com/rancher/swarm-agent/rancherevents.ConnectToEventStream(0xc820018e70, 0x2a, 0xc820010900, 0x14, 0xc820018ea0, 0x28, 0x32, 0x2800, 0x0, 0x0, ...)
    /go/src/github.com/rancher/swarm-agent/rancherevents/listener.go:16 +0x2e6
main.launch.func1(0xc820018e70, 0x2a, 0xc820010900, 0x14, 0xc820018ea0, 0x28, 0x32, 0x2800, 0x0, 0x0, ...)
    /go/src/github.com/rancher/swarm-agent/main.go:106 +0x34
created by main.launch
    /go/src/github.com/rancher/swarm-agent/main.go:109 +0x9a

goroutine 7 [IO wait]:
net.runtime_pollWait(0x7fa83b119fa0, 0x72, 0xc82000a130)
    /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200f4140, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200f4140, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8200f40e0, 0x0, 0x7fa83b11a098, 0xc8200fa120)
    /usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8200e8408, 0xc8200d7c60, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc8200e8408, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:2135 +0x41
net/http.(*Server).Serve(0xc8200ee540, 0x7fa83b11a060, 0xc8200e8408, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc8200ee540, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1877 +0x136
net/http.ListenAndServe(0xc82000b1d0, 0x6, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1967 +0x8f
github.com/rancher/swarm-agent/healthcheck.StartHealthCheck(0x2800, 0x0, 0x0)
    /go/src/github.com/rancher/swarm-agent/healthcheck/healthcheck.go:22 +0x1db
main.launch.func2(0xc820018e70, 0x2a, 0xc820010900, 0x14, 0xc820018ea0, 0x28, 0x32, 0x2800, 0x0, 0x0, ...)
    /go/src/github.com/rancher/swarm-agent/main.go:112 +0x2b
created by main.launch
    /go/src/github.com/rancher/swarm-agent/main.go:115 +0xce

goroutine 8 [select]:
net/http.(*persistConn).readLoop(0xc8200fc000)
    /usr/local/go/src/net/http/transport.go:976 +0xac7
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 9 [select]:
net/http.(*persistConn).writeLoop(0xc8200fc000)
    /usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 21 [select]:
net.lookupIPDeadline(0xc8200e2390, 0x20, 0xecf5f37f7, 0x3f8fd32, 0xe65da0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/lookup.go:109 +0x6a5
net.internetAddrList(0x9ad6d8, 0x3, 0xc8200e2390, 0x23, 0xecf5f37f7, 0x3f8fd32, 0xe65da0, 0x0, 0x0, 0x0, ...)
    /usr/local/go/src/net/ipsock.go:252 +0x6ee
net.resolveAddrList(0x9ab768, 0x4, 0x9ad6d8, 0x3, 0xc8200e2390, 0x23, 0xecf5f37f7, 0x3f8fd32, 0xe65da0, 0x0, ...)
    /usr/local/go/src/net/dial.go:153 +0x466
net.(*Dialer).Dial(0xc82000e690, 0x9ad6d8, 0x3, 0xc8200e2390, 0x23, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/dial.go:209 +0x124
net.(*Dialer).Dial-fm(0x9ad6d8, 0x3, 0xc8200e2390, 0x23, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:38 +0x6e
net/http.(*Transport).dial(0xc820012240, 0x9ad6d8, 0x3, 0xc8200e2390, 0x23, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:499 +0x79
net/http.(*Transport).dialConn(0xc820012240, 0x0, 0xc8200dc4c0, 0x4, 0xc8200e2390, 0x23, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:596 +0x19a9
net/http.(*Transport).getConn.func4(0xc820012240, 0x0, 0xc8200dc4c0, 0x4, 0xc8200e2390, 0x23, 0xc8200ee720)
    /usr/local/go/src/net/http/transport.go:549 +0x66
created by net/http.(*Transport).getConn
    /usr/local/go/src/net/http/transport.go:551 +0x265
time="2016-09-05T09:56:23Z" level=info msg="Listening for health checks on 0.0.0.0:10240/healthcheck" 
time="2016-09-05T09:56:23Z" level=info msg="Initializing event router" workerCount=50 
time="2016-09-05T09:56:23Z" level=info msg="Connection established" 
time="2016-09-05T09:56:23Z" level=info msg="Starting websocket pings" 
```

**Questions:**

Should we still expect to see rancher/agent and rancher/agent-instance running on nodes joined to a swarm env?

What additional instances should there be, and what role do they play (thinking of the rancher/swarm image, for instance, which seems to be started twice, with different args).

**Comment by aemneina** [comment]
hey @kaos Not sure if 1.1.x is the swarm implementation you'd want to use. Have you tried it in 1.2.0-pre3?

**Comment by superseb** [comment]
Please retry with a recent version, and file a new issue so we can help you.

**Comment by kaos** [comment]
Will do. Thanks.
