### ISSUE TITLE
Disabling all catalog sources prompts java.lang.ArrayIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by bradjones1** [rancher/rancher#5896]
**Rancher Version:**

v1.2.0-pre2

**Docker Version:**

1.11.1

**OS and where are the hosts located? (cloud, bare metal, etc):**

SoftLayer cloud - Ubuntu

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single node rancher with external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

One cattle environment, one "legacy" Swarm

**Steps to Reproduce:**

Disable both the official and community catalog sources.

**Results:** 

The following message is repeated constantly in the rancher server's log.
```
9/5/2016 4:13:20 PM2016-09-05 22:13:20,731 ERROR [:] [] [] [] [ecutorService-9] [o.a.c.m.context.NoExceptionRunnable ] Uncaught exception java.lang.ArrayIndexOutOfBoundsException: 1
9/5/2016 4:13:20 PM	at io.cattle.platform.docker.machine.launch.CatalogLauncher.prepareConfigFile(CatalogLauncher.java:121) ~[cattle-docker-machine-0.5.0-SNAPSHOT.jar:na]
9/5/2016 4:13:20 PM	at io.cattle.platform.docker.machine.launch.CatalogLauncher.prepareProcess(CatalogLauncher.java:98) ~[cattle-docker-machine-0.5.0-SNAPSHOT.jar:na]
9/5/2016 4:13:20 PM	at io.cattle.platform.service.launcher.GenericServiceLauncher.doRun(GenericServiceLauncher.java:203) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
9/5/2016 4:13:20 PM	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
9/5/2016 4:13:20 PM	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
9/5/2016 4:13:20 PM	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
9/5/2016 4:13:20 PM	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
9/5/2016 4:13:20 PM	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
9/5/2016 4:13:20 PM	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
9/5/2016 4:13:20 PM	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_101]
9/5/2016 4:13:20 PM	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_101]
9/5/2016 4:13:20 PM	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_101]
9/5/2016 4:13:20 PM	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_101]
9/5/2016 4:13:20 PM	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_101]
9/5/2016 4:13:20 PM	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_101]
9/5/2016 4:13:20 PM	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_101]
```

**Expected:**

Log is not polluted with the above message, and the catalog service is not available in the top menu. Enable a catalog source and the service is started, and the log quiets.

**Comment by mrajashree** [comment]
Seems to work fine with rancher/server:v1.2.0-pre4-rc3
The PRs in which it has been referenced seem to have fixed this

**Comment by sangeethah** [comment]
Tested with rancher/server:v1.2.0-pre4-rc3.

There is no errors in the logs when "Rancher Infrastructure","Rancher Certified Library" and "Community Contributed" are disabled:

Catalog service halts at this time:
```
time="2016-10-17T22:25:42Z" level=info msg="Halting Catalog service, Catalog git repo url not provided"
```

Catalog Menu will have  no catalog options under it.
User is presented with following message:

```
There are no compatible templates.
```
