### ISSUE TITLE
host continues to remain in "Disconnected" state even after the host that was powered down was powered on.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5906]
Server version - v1.2.0-pre2

Steps that lead to the problem:
Had a set up with 4 hosts in "Kubernetes" environment.
One host was being powered down to see if etcd always scales to 3 and is functional after that.
After which the host will be powered on.

After multiple attempts to do this , one of the host remained in "Disconnected" state even after the host that was powered off was powered on.

```
2016-09-06T19:58:19.700718908Z time="2016-09-06T19:58:19Z" level="error" msg="Error processing event &docker.APIEvents{Status:\"stop\", ID:\"1f339ed1be628d4a9a58b46c3a3d5a33f286c8b1472f7b0b46ab00ad241e5829\", From:\"rancher/k8s:v1.3.0-rancher3\", Time:1473191899}. Error: dial unix /var/run/docker.sock: connection refused" 
2016-09-06T19:58:19.749192844Z 2016-09-06 19:58:19,685 ERROR agent [140355276481712] [event.py:112] Error in request : a15fdeab-9a52-4a61-89e6-b91fe8cd5cb6 
2016-09-06T19:58:19.749264077Z Traceback (most recent call last):
2016-09-06T19:58:19.749274781Z   File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
2016-09-06T19:58:19.749280790Z     resp = agent.execute(req)
2016-09-06T19:58:19.749286026Z   File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
2016-09-06T19:58:19.749291453Z     return self._router.route(req)
2016-09-06T19:58:19.749296729Z   File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
2016-09-06T19:58:19.749301872Z     resp = handler.execute(req)
2016-09-06T19:58:19.749306676Z   File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 34, in execute
2016-09-06T19:58:19.749311714Z     return method(req=req, **req.data.__dict__)
2016-09-06T19:58:19.749317951Z   File "/var/lib/cattle/pyagent/cattle/plugins/docker/delegate.py", line 92, in delegate_request
2016-09-06T19:58:19.749323279Z     by_agent=True)
2016-09-06T19:58:19.749327785Z   File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 320, in get_container
2016-09-06T19:58:19.749335351Z     'label': '{}={}'.format(UUID_LABEL, instance.uuid)})
2016-09-06T19:58:19.749358470Z   File "/var/lib/cattle/pyagent/dist/docker/api/container.py", line 69, in containers
2016-09-06T19:58:19.749364545Z     res = self._result(self._get(u, params=params), True)
2016-09-06T19:58:19.749369233Z   File "/var/lib/cattle/pyagent/dist/docker/utils/decorators.py", line 47, in inner
2016-09-06T19:58:19.749374062Z     return f(self, *args, **kwargs)
2016-09-06T19:58:19.749411965Z   File "/var/lib/cattle/pyagent/dist/docker/client.py", line 112, in _get
2016-09-06T19:58:19.749418109Z     return self.get(url, **self._set_request_timeout(kwargs))
2016-09-06T19:58:19.749422700Z   File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 487, in get
2016-09-06T19:58:19.749427640Z     return self.request('GET', url, **kwargs)
2016-09-06T19:58:19.749432183Z   File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 475, in request
2016-09-06T19:58:19.749436957Z     resp = self.send(prep, **send_kwargs)
2016-09-06T19:58:19.749441339Z   File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 585, in send
2016-09-06T19:58:19.749446077Z     r = adapter.send(request, **kwargs)
2016-09-06T19:58:19.749450457Z   File "/var/lib/cattle/pyagent/dist/requests/adapters.py", line 453, in send
2016-09-06T19:58:19.749455108Z     raise ConnectionError(err, request=request)
2016-09-06T19:58:19.749459697Z ConnectionError: ('Connection aborted.', error(111, 'ECONNREFUSED'))
2016-09-06T19:58:19.749621392Z time="2016-09-06T19:58:19Z" level="error" msg="Error processing event &docker.APIEvents{Status:\"stop\", ID:\"2c525588d2fc5f33ce371830ae99595a443587139ee6a65033d35c20d71a6b08\", From:\"rancher/k8s:v1.3.0-rancher3\", Time:1473191899}. Error: dial unix /var/run/docker.sock: connection refused" 
2016-09-06T19:58:19.749639673Z time="2016-09-06T19:58:19Z" level="error" msg="Error processing event &docker.APIEvents{Status:\"stop\", ID:\"c699dca1f54f5e47131d59cef7c25f2eade274f8bdaae81187fd28bb1dc62d4e\", From:\"rancher/k8s:v1.3.0-rancher3\", Time:1473191899}. Error: dial unix /var/run/docker.sock: connection refused" 
2016-09-06T19:58:19.752007225Z time="2016-09-06T19:58:19Z" level="error" msg="Error processing event &docker.APIEvents{Status:\"stop\", ID:\"6e55d5f10947672283261620b893fb2b7a7a1d0cdfecf503b73d4eb965b12945\", From:\"sangeetha/testclient44:latest\", Time:1473191899}. Error: dial unix /var/run/docker.sock: connection refused" 
2016-09-06T19:58:19.814652661Z 2016-09-06 19:58:19,814 ERROR agent [140355276480752] [event.py:112] Error in request : 0ea3d555-9bde-4a2d-a689-d96e30be4ff2 
2016-09-06T19:58:19.814683577Z Traceback (most recent call last):
2016-09-06T19:58:19.814689897Z   File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
2016-09-06T19:58:19.814695008Z     resp = agent.execute(req)
2016-09-06T19:58:19.814699435Z   File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
2016-09-06T19:58:19.814720827Z     return self._router.route(req)
2016-09-06T19:58:19.814727285Z   File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
2016-09-06T19:58:19.814747920Z     resp = handler.execute(req)
2016-09-06T19:58:19.814753413Z   File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 34, in execute
2016-09-06T19:58:19.814757867Z     return method(req=req, **req.data.__dict__)
2016-09-06T19:58:19.814762390Z   File "/var/lib/cattle/pyagent/cattle/plugins/docker/delegate.py", line 92, in delegate_request
2016-09-06T19:58:19.814766746Z     by_agent=True)
2016-09-06T19:58:19.814770811Z   File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 320, in get_container
2016-09-06T19:58:19.814775612Z     'label': '{}={}'.format(UUID_LABEL, instance.uuid)})
2016-09-06T19:58:19.814779848Z   File "/var/lib/cattle/pyagent/dist/docker/api/container.py", line 69, in containers
2016-09-06T19:58:19.814784235Z     res = self._result(self._get(u, params=params), True)
2016-09-06T19:58:19.814804339Z   File "/var/lib/cattle/pyagent/dist/docker/utils/decorators.py", line 47, in inner
2016-09-06T19:58:19.814809360Z     return f(self, *args, **kwargs)
2016-09-06T19:58:19.814813391Z   File "/var/lib/cattle/pyagent/dist/docker/client.py", line 112, in _get
2016-09-06T19:58:19.814818037Z     return self.get(url, **self._set_request_timeout(kwargs))
2016-09-06T19:58:19.814822233Z   File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 487, in get
2016-09-06T19:58:19.814826504Z     return self.request('GET', url, **kwargs)
2016-09-06T19:58:19.814830580Z   File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 475, in request
2016-09-06T19:58:19.814834936Z     resp = self.send(prep, **send_kwargs)
2016-09-06T19:58:19.814839006Z   File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 585, in send
2016-09-06T19:58:19.814843308Z     r = adapter.send(request, **kwargs)
2016-09-06T19:58:19.814847391Z   File "/var/lib/cattle/pyagent/dist/requests/adapters.py", line 453, in send
2016-09-06T19:58:19.814851722Z     raise ConnectionError(err, request=request)
2016-09-06T19:58:19.814855979Z ConnectionError: ('Connection aborted.', error(111, 'ECONNREFUSED'))
2016-09-06T19:58:19.878231827Z 2016-09-06 19:58:19,877 ERROR agent [140355276458736] [event.py:112] Error in request : b37c4230-184c-4ad6-b321-33d643f50059 
2016-09-06T19:58:19.878276915Z Traceback (most recent call last):
2016-09-06T19:58:19.878301630Z   File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
2016-09-06T19:58:19.878308743Z     resp = agent.execute(req)
2016-09-06T19:58:19.878313404Z   File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
2016-09-06T19:58:19.878318414Z     return self._router.route(req)
2016-09-06T19:58:19.878322957Z   File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
2016-09-06T19:58:19.878327847Z     resp = handler.execute(req)
2016-09-06T19:58:19.878332404Z   File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 34, in execute
2016-09-06T19:58:19.878350925Z     return method(req=req, **req.data.__dict__)
2016-09-06T19:58:19.878356703Z   File "/var/lib/cattle/pyagent/cattle/plugins/docker/delegate.py", line 92, in delegate_request
2016-09-06T19:58:19.878361408Z     by_agent=True)
2016-09-06T19:58:19.878380426Z   File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 320, in get_container
2016-09-06T19:58:19.878387623Z     'label': '{}={}'.format(UUID_LABEL, instance.uuid)})
2016-09-06T19:58:19.878392006Z   File "/var/lib/cattle/pyagent/dist/docker/api/container.py", line 69, in containers
2016-09-06T19:58:19.878409228Z     res = self._result(self._get(u, params=params), True)
2016-09-06T19:58:19.878414056Z   File "/var/lib/cattle/pyagent/dist/docker/utils/decorators.py", line 47, in inner
2016-09-06T19:58:19.878418748Z     return f(self, *args, **kwargs)
2016-09-06T19:58:19.878423029Z   File "/var/lib/cattle/pyagent/dist/docker/client.py", line 112, in _get
2016-09-06T19:58:19.878427563Z     return self.get(url, **self._set_request_timeout(kwargs))
2016-09-06T19:58:19.878431997Z   File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 487, in get
2016-09-06T19:58:19.878436515Z     return self.request('GET', url, **kwargs)
2016-09-06T19:58:19.878440803Z   File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 475, in request
2016-09-06T19:58:19.878462112Z     resp = self.send(prep, **send_kwargs)
2016-09-06T19:58:19.878468632Z   File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 585, in send
2016-09-06T19:58:19.878473202Z     r = adapter.send(request, **kwargs)
2016-09-06T19:58:19.878477438Z   File "/var/lib/cattle/pyagent/dist/requests/adapters.py", line 453, in send
2016-09-06T19:58:19.878481879Z     raise ConnectionError(err, request=request)
2016-09-06T19:58:19.878799711Z ConnectionError: ('Connection aborted.', error(111, 'ECONNREFUSED'))
2016-09-06T19:58:20.060460513Z Caught EXIT
2016-09-06T19:58:20.062495886Z I0906 19:58:20.062230    1957 manager.go:1062] Exiting thread watching subcontainers
2016-09-06T19:58:20.062521376Z I0906 19:58:20.062322    1957 manager.go:347] Exiting global housekeeping thread
2016-09-06T19:58:20.063647463Z I0906 19:58:20.062428    1957 cadvisor.go:185] Exiting given signal: terminated
2016-09-06T19:58:20.116907837Z Terminated
2016-09-06T20:03:59.800245228Z INFO: Starting agent for 9F57C3552785E7189251
2016-09-06T20:03:59.835509454Z INFO: Access Key: 9F57C3552785E7189251
2016-09-06T20:03:59.835544712Z INFO: Config URL: http://130.211.201.80:8080/v1
2016-09-06T20:03:59.835551440Z INFO: Storage URL: http://130.211.201.80:8080/v1
2016-09-06T20:03:59.835556666Z INFO: API URL: http://130.211.201.80:8080/v1
2016-09-06T20:03:59.835580000Z INFO: IP: 159.203.92.98
2016-09-06T20:03:59.835598899Z INFO: Port:
2016-09-06T20:03:59.835604105Z INFO: Required Image: rancher/agent:v1.0.2
2016-09-06T20:03:59.835608700Z INFO: Current Image: rancher/agent:v1.0.2
2016-09-06T20:03:59.835765456Z INFO: Using image rancher/agent:v1.0.2
2016-09-06T20:03:59.841893519Z INFO: Downloading agent http://130.211.201.80:8080/v1/configcontent/configscripts
2016-09-06T20:03:59.943662946Z INFO: Updating configscripts
2016-09-06T20:03:59.958450071Z INFO: Downloading http://130.211.201.80:8080/v1//configcontent//configscripts current=
2016-09-06T20:04:00.067252118Z INFO: Running /var/lib/cattle/download/configscripts/configscripts-1-f0f3fb2e1110b5ada7c441705981f93a480313a324294321cff467f0c3e12319/apply.sh
2016-09-06T20:04:00.096873241Z INFO: Sending configscripts applied 1-f0f3fb2e1110b5ada7c441705981f93a480313a324294321cff467f0c3e12319
2016-09-06T20:04:00.171354390Z INFO: Updating pyagent
2016-09-06T20:04:00.185679068Z INFO: Downloading http://130.211.201.80:8080/v1//configcontent//pyagent current=
2016-09-06T20:04:00.288641187Z INFO: Running /var/lib/cattle/download/pyagent/pyagent-1-9e3dcab12585149a65d818082279708965cd826df1937a55b24f48428f8f0c0673b9f37ae03c16234efdd22657d02b33/apply.sh
2016-09-06T20:04:00.306018254Z INFO: Updating host-api
2016-09-06T20:04:00.316756796Z INFO: Downloading http://130.211.201.80:8080/v1//configcontent//host-api current=1-22f92c68b705f60d5acea6373b28b7d4ab7233ef6c3eb90bb99d3764d08013a6
2016-09-06T20:04:00.409956127Z INFO: Already up to date
2016-09-06T20:04:00.410389026Z INFO: Sending host-api applied 1-22f92c68b705f60d5acea6373b28b7d4ab7233ef6c3eb90bb99d3764d08013a6
2016-09-06T20:04:00.500225153Z INFO: Updating agent-binaries
2016-09-06T20:04:00.514817714Z INFO: Downloading http://130.211.201.80:8080/v1//configcontent//agent-binaries current=1-4200f9b686342da8e941359211b1d8c5f98877ae293d0ead231d43507f1c9eae
2016-09-06T20:04:00.602714237Z INFO: Already up to date
2016-09-06T20:04:00.603078856Z INFO: Sending agent-binaries applied 1-4200f9b686342da8e941359211b1d8c5f98877ae293d0ead231d43507f1c9eae
2016-09-06T20:04:00.690852422Z INFO: Updating python-agent
2016-09-06T20:04:00.702714015Z INFO: Downloading http://130.211.201.80:8080/v1//configcontent//python-agent current=1-c6ccea681cb7aa4c7a5507d3de4e0a843903fb86c0c8ad9e50d29f1ef80c3fd9
2016-09-06T20:04:00.795854231Z INFO: Already up to date
2016-09-06T20:04:00.796145895Z INFO: Sending python-agent applied 1-c6ccea681cb7aa4c7a5507d3de4e0a843903fb86c0c8ad9e50d29f1ef80c3fd9
2016-09-06T20:04:00.884732968Z INFO: Updating cadvisor
2016-09-06T20:04:00.897817619Z INFO: Downloading http://130.211.201.80:8080/v1//configcontent//cadvisor current=1-353f387d604d999e342ad5420d6224d8f86b159a7bd080a553cdb6e806dadd5a
2016-09-06T20:04:00.990169079Z INFO: Already up to date
2016-09-06T20:04:00.990629275Z INFO: Sending cadvisor applied 1-353f387d604d999e342ad5420d6224d8f86b159a7bd080a553cdb6e806dadd5a
2016-09-06T20:04:01.070472201Z INFO: Sending pyagent applied 1-9e3dcab12585149a65d818082279708965cd826df1937a55b24f48428f8f0c0673b9f37ae03c16234efdd22657d02b33
2016-09-06T20:04:01.148477690Z INFO: Starting agent /var/lib/cattle/pyagent/apply.sh
2016-09-06T20:04:01.164828673Z INFO: Executing /var/lib/cattle/pyagent/main.py
2016-09-06T20:04:01.191103848Z INFO: Updating host-config
2016-09-06T20:04:01.204308769Z INFO: Downloading http://130.211.201.80:8080/v1//configcontent//host-config current=host-config-1-c8f252cf2dba2322790b45051f71f22606f8f16ce47a342685ae4fa5221ff46b
2016-09-06T20:04:01.293779215Z INFO: Already up to date
2016-09-06T20:04:01.294110466Z INFO: Sending host-config applied 1-c8f252cf2dba2322790b45051f71f22606f8f16ce47a342685ae4fa5221ff46b
2016-09-06T20:04:03.100003243Z time="2016-09-06T20:04:03Z" level="info" msg="Starting event router." 
2016-09-06T20:04:03.108044340Z time="2016-09-06T20:04:03Z" level="info" msg="Watching state directory: /var/lib/rancher/state/containers" 
2016-09-06T20:04:03.111166373Z time="2016-09-06T20:04:03Z" level="info" msg="Assigning IP [10.42.195.147/16], ContainerId [777ba786965f817145eaf664f2e551642e0cbd001ad73d5f8674feb33b6ab674], Pid [1595]" 
2016-09-06T20:04:03.130529282Z Monitoring mount context of PID 1150
2016-09-06T20:04:03.214613426Z I0906 20:04:03.214343    1967 storagedriver.go:50] Caching stats in memory for 2m0s
2016-09-06T20:04:03.214844695Z I0906 20:04:03.214723    1967 manager.go:138] cAdvisor running in container: "/docker/f8a06f88f048895857e17cf2d55c786ae6074c32d721e836b444d96bf7128e70"
2016-09-06T20:04:03.275854494Z time="2016-09-06T20:04:03Z" level="info" msg="Connecting to proxy." url="ws://130.211.201.80:8080/v1/connectbackend?token=eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjE0NzMxOTI1NDMsInN1YiI6ImNhdHRsZSIsImlzcyI6Imh0dHA6XC9cL2NhdHRsZS5pbyIsInJlcG9ydGVkVXVpZCI6IjVjOWFjOWFiLTQ4OTItNGM3Ni1hZjBjLTZjOGE0YjA3MjQ1ZCIsImlhdCI6MTQ3MzE5MjI0Mywia2lkIjoiZGVmYXVsdCJ9.N0guguChrQ1VoV3Z4ByPyi5JH2LMd7oregwjAElnalbh8IGikBjh_G48pgGYebyKdslqWVObybEVpVNeVYfvyKHv4iYq7yjvlir7Kr4u0jk4CfvWJypse0doStgH3QW8qCiLg8ElBhBBJ5MUl7nd0_xMEQssQ86v6k3qAlS5Kpo2MrTkpsjG1iyrOBZc4cmY1XWIvFIZa3Ud6A6NQvhl_UXmRtP_42rn_Si7WXDF5er-dXT1WnotB7ZYK3lTNGsf1f9tvZBVRyUVSYqt82fAaRkwiNP8q3o4c0hMXnskOnfphf9kL970UDG0K2dn26Q_2P9txovnXXt25iJIQNqQDQ" 
2016-09-06T20:04:03.426741687Z W0906 20:04:03.415730    1967 manager.go:146] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0.1:15441: getsockopt: connection refused
2016-09-06T20:04:03.598063097Z I0906 20:04:03.595681    1967 fs.go:119] Filesystem partitions: map[/dev/vda1:{mountpoint:/var/lib/docker/aufs major:253 minor:1 fsType:ext4 blockSize:0}]
2016-09-06T20:04:03.600708020Z I0906 20:04:03.600485    1967 manager.go:192] Machine: {NumCores:1 CpuFrequency:1797917 MemoryCapacity:1040908288 MachineID:9829945b0098be2d46ee2ed457c5ba5b SystemUUID:067C6DBF-B4B0-4CCC-AF58-A1B8A96BDD06 BootID:5d3f9cf6-9bcb-4839-8e45-8ca2c7eeca7d Filesystems:[{Device:/dev/vda1 Capacity:31572467712 Type:vfs Inodes:1958400}] DiskMap:map[253:0:{Name:vda Major:253 Minor:0 Size:32212254720 Scheduler:none}] NetworkDevices:[{Name:eth0 MacAddress:66:45:5a:08:3a:dc Speed:-1 Mtu:1500} {Name:eth1 MacAddress:ae:78:f7:0d:ef:2f Speed:0 Mtu:1500}] Topology:[{Id:0 Memory:1040908288 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:31457280 Type:Unified Level:3}]}] CloudProvider:Unknown InstanceType:Unknown InstanceID:None}
2016-09-06T20:04:03.601455986Z I0906 20:04:03.601313    1967 manager.go:198] Version: {KernelVersion:4.4.0-36-generic ContainerOsVersion:Ubuntu 14.04.5 LTS DockerVersion:1.10.3 CadvisorVersion:0.23.2 CadvisorRevision:}
2016-09-06T20:04:03.786491634Z I0906 20:04:03.783477    1967 factory.go:217] registering Docker factory
2016-09-06T20:04:03.786530779Z E0906 20:04:03.783512    1967 manager.go:240] Registration of the rkt container factory failed: unable to communicate with Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0.1:15441: getsockopt: connection refused
2016-09-06T20:04:03.786539458Z I0906 20:04:03.783519    1967 factory.go:54] Registering systemd factory
2016-09-06T20:04:03.786544666Z I0906 20:04:03.784561    1967 factory.go:86] Registering Raw factory
2016-09-06T20:04:03.786549499Z I0906 20:04:03.785334    1967 manager.go:1072] Started watching for new ooms in manager
2016-09-06T20:04:03.786554193Z I0906 20:04:03.785444    1967 oomparser.go:200] OOM parser using kernel log file: "/var/log/kern.log"
2016-09-06T20:04:03.789525449Z I0906 20:04:03.789436    1967 manager.go:281] Starting recovery of all containers
2016-09-06T20:04:03.834226874Z I0906 20:04:03.834012    1967 manager.go:286] Recovery completed
2016-09-06T20:04:03.845136923Z I0906 20:04:03.844970    1967 cadvisor.go:151] Starting cAdvisor version: 0.23.2- on port 9344
2016-09-06T20:04:06.074888950Z 2016-09-06 20:04:06,074 ERROR docker [140519270019952] [delegate.py:104] Can not call [557163d7-b422-4d41-987a-0d22d7f2052a], container is not running 
2016-09-06T20:15:09.229533031Z W0906 20:15:09.229321    1967 container.go:352] Failed to create summary reader for "/user/0.user/1.session": none of the resources are being tracked.
2016-09-06T20:47:19.044719754Z W0906 20:47:19.044377    1967 container.go:352] Failed to create summary reader for "/user/0.user/2.session": none of the resources are being tracked.
2016-09-06T20:52:06.020140305Z 2016-09-06 20:52:06,017 ERROR docker [140519270044208] [delegate.py:104] Can not call [557163d7-b422-4d41-987a-0d22d7f2052a], container is not running 
2016-09-06T20:52:08.265216347Z time="2016-09-06T20:52:08Z" level="info" msg="Assigning IP [10.42.195.147/16], ContainerId [777ba786965f817145eaf664f2e551642e0cbd001ad73d5f8674feb33b6ab674], Pid [1595]" 
2016-09-06T20:52:08.365942652Z time="2016-09-06T20:52:08Z" level="info" msg="Container [81f9543a342a7435c1f028ba574f833ed9254eb7c9f3f2642f975422b8f3897d] not running. Can't assign IP [10.42.23.150/16]." 
2016-09-06T20:52:09.553933279Z time="2016-09-06T20:52:09Z" level="info" msg="Assigning IP [10.42.31.248/16], ContainerId [fe9496d4dbf23c1bc4de30c785900b3b43dc1b7d102ef24bd2b3eee1f3213564], Pid [4484]" 
2016-09-06T20:52:09.700234936Z time="2016-09-06T20:52:09Z" level="info" msg="Assigning IP [10.42.31.248/16], ContainerId [fe9496d4dbf23c1bc4de30c785900b3b43dc1b7d102ef24bd2b3eee1f3213564], Pid [4484]" 
2016-09-06T20:53:40.917942952Z 2016-09-06 20:53:40,917 WARNING docker [140519270046608] [storage.py:282] Encountered conflict (409 Client Error: Conflict ("Conflict: remove a20718f5f989497d25f6f2a6751f326fa0d54c7f5f9e0c46466048114bab3cb3: volume is in use - [37c820b8a36439456ad90c9fac337f10bbd415b1f75a873e63e3cda5c4179a49]")) while deleting volume. Orphaning volume. 
2016-09-06T20:53:41.126392278Z 2016-09-06 20:53:41,125 WARNING docker [140519270019952] [storage.py:282] Encountered conflict (409 Client Error: Conflict ("Conflict: remove a20718f5f989497d25f6f2a6751f326fa0d54c7f5f9e0c46466048114bab3cb3: volume is in use - [37c820b8a36439456ad90c9fac337f10bbd415b1f75a873e63e3cda5c4179a49]")) while deleting volume. Orphaning volume. 
2016-09-06T20:54:04.464370037Z E0906 20:54:04.464139    1967 fsHandler.go:106] failed to collect filesystem stats - du command failed on /var/lib/docker/aufs/diff/e5a489064e0d7afac148a9b22f2ae878b220ef091e2d7d952823ece412edb415 with output stdout: , stderr: du: cannot access '/var/lib/docker/aufs/diff/e5a489064e0d7afac148a9b22f2ae878b220ef091e2d7d952823ece412edb415': No such file or directory
2016-09-06T20:54:04.464415012Z  - exit status 1
2016-09-06T20:57:42.658906272Z time="2016-09-06T20:57:42Z" level="info" msg="Assigning IP [10.42.123.184/16], ContainerId [9a675ac6c57a3144f034439d6f4670414ffd871b4ec59e4485518421725b0004], Pid [7259]" 
2016-09-06T20:58:26.849118021Z time="2016-09-06T20:58:26Z" level="info" msg="Assigning IP [10.42.93.224/16], ContainerId [4c8b339d8da5b55abb6956a9bc02e36dce6bbf8ffe0b4848e9813908f0c7b057], Pid [8001]" 
2016-09-06T20:58:37.943486675Z time="2016-09-06T20:58:37Z" level="info" msg="Assigning IP [10.42.221.65/16], ContainerId [e5d5af96925eab6aefec747e033ef7673cd1fdcde3561e73cfba3f9164df0c13], Pid [8678]" 
2016-09-06T20:58:43.644951328Z time="2016-09-06T20:58:43Z" level="info" msg="Assigning IP [10.42.45.97/16], ContainerId [4356095e8f675a110fb68c3383d4337eaff685b39e9c9c2889e88363a0db9014], Pid [9421]" 
2016-09-06T20:58:47.996978078Z time="2016-09-06T20:58:47Z" level="info" msg="Assigning IP [10.42.221.65/16], ContainerId [e5d5af96925eab6aefec747e033ef7673cd1fdcde3561e73cfba3f9164df0c13], Pid [10085]"

```

**Comment by sangeethah** [comment]
When 1 container was deployed on the host (out side of rancher-server), host got back to "Active" state.

**Comment by sangeethah** [comment]
When 1 container was deployed on the host (out side of rancher-server), host got back to "Active" state.

**Comment by deniseschannon** [comment]
With the new go-agent code, can you check again if this is still an issue?

**Comment by sangeethah** [comment]
Tested with latest build from master.
When testing with host being powered down and on multiple times , did not see this issue were host were reported as being in "Disconnected" state. They got back to "Active" state as expected.
