### ISSUE TITLE
Processes stuck forever cause slow system

### ISSUE THREAD

**Issue by CBR09** [rancher/rancher#5950]
**Rancher Version:**
1.2.0-pre2
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 14.04.3 and VM
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher vs external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

Hi @ibuildthecloud and everyone
After a period of use, I saw in admin/process tab have many processes in state RESOURCE_BUSY or 'TIMEOUT'. They make the system run very slow. Example: when I upgrade service, instance.stop or instance.start process took a lot of time to complete, it's so bad for my CI system :(
Some logs I got from admin/process

VolumeStoragePoolMapDeactivate

```
io.cattle.platform.async.utils.TimeoutException: Timeout
    at io.cattle.platform.agent.impl.WrappedEventService.call(WrappedEventService.java:73)
    at io.cattle.platform.agent.impl.EventCallProgressHelper.call(EventCallProgressHelper.java:57)
    at io.cattle.platform.agent.impl.RemoteAgentImpl.call(RemoteAgentImpl.java:99)
    at io.cattle.platform.agent.impl.RemoteAgentImpl.callSync(RemoteAgentImpl.java:72)
    at io.cattle.platform.agent.impl.RemoteAgentImpl.callSync(RemoteAgentImpl.java:135)
    at io.cattle.platform.process.common.handler.AgentBasedProcessLogic.callSync(AgentBasedProcessLogic.java:180)
    at io.cattle.platform.process.instance.IgnoreReconnectionAgentHandler.callSync(IgnoreReconnectionAgentHandler.java:19)
    at io.cattle.platform.process.common.handler.AgentBasedProcessLogic.handleEvent(AgentBasedProcessLogic.java:166)
    at io.cattle.platform.process.common.handler.AgentBasedProcessLogic.handle(AgentBasedProcessLogic.java:104)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:422)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:373)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:367)
    at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:367)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:469)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:303)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:242)
    at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7)
    at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3)
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
    at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:239)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:181)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:154)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:107)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:104)
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
    at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:104)
    at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.executeStandardProcess(DefaultObjectProcessManager.java:29)
    at io.cattle.platform.process.common.handler.AbstractObjectProcessLogic.deactivate(AbstractObjectProcessLogic.java:35)
    at io.cattle.platform.process.volume.VolumeDeactivate.handle(VolumeDeactivate.java:27)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:422)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:373)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:367)
    at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:367)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:469)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:303)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:242)
    at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7)
    at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3)
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
    at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:239)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:181)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:154)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:107)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:104)
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
    at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:104)
    at io.cattle.platform.engine.eventing.impl.ProcessEventListenerImpl.processExecute(ProcessEventListenerImpl.java:75)
    at io.cattle.platform.engine.server.impl.ProcessInstanceParallelDispatcher$1.runInContext(ProcessInstanceParallelDispatcher.java:27)
    at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
    at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
    at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108)
    at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
    at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

InstanceHostMapActivate

```
io.cattle.platform.async.utils.TimeoutException: Timeout
    at io.cattle.platform.async.retry.impl.RetryTimeoutServiceImpl$1.run(RetryTimeoutServiceImpl.java:51)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

How can I fix my issue?, Is there any workaround for it?. I need it as soon as possible 
Some issue related:
#5388
#4974
#5349

Thanks

**Comment by aemneina** [comment]
@CBR09 the word is that this [pr](https://github.com/rancher/cattle/pull/1958) will fix that. Should be in 1.2.0-pre3 already, and is expected to be in 1.1.4 as well.

**Comment by aemneina** [comment]
closing issue.
