### ISSUE TITLE
packets.go:33: unexpected EOF

### ISSUE THREAD

**Issue by VFT** [rancher/rancher#5998]
I got any errors  if the mysql configuation of  rancher-ha is using nginx for TCP proxy:

```
[mysql] 2016/09/19 08:31:28 packets.go:124: write tcp 192.168.2.71:46220->192.168.2.91:3306: write: broken pipe
[mysql] 2016/09/19 08:31:33 packets.go:33: unexpected EOF
[mysql] 2016/09/19 08:31:38 packets.go:33: unexpected EOF
[mysql] 2016/09/19 08:31:47 packets.go:33: unexpected EOF
[mysql] 2016/09/19 08:31:53 packets.go:33: unexpected EOF
[mysql] 2016/09/19 08:31:58 packets.go:33: unexpected EOF
[mysql] 2016/09/19 08:32:03 packets.go:33: unexpected EOF
[mysql] 2016/09/19 08:32:08 packets.go:33: unexpected EOF
```

`192.168.2.91:3306` is the nginx server and port for mysql.

it is normal if using other tools for mysql connecting.

version of each component:
docker:  1.11.2
rancher:  1.1.3
nginx:  1.11.3
mysql:  mariadb 10.1

**Comment by aemneina** [comment]
@VFT did you manage to sort this out? I dont think its normal to have an LB in between rancher and the DB, I'd imagine if you remove the LB everything operates fine?

**Comment by njordr** [comment]
Same issue on a new installation of Rancher (last release). It happens both behind haproxy and directly connected to mysql

**Comment by njordr** [comment]
Another exception raised with mysql 5.7 (no docker and no proxy between rancher and mysql):
Caused by: java.sql.SQLNonTransientConnectionException: (conn:13) Could not read packet: unexpected end of stream, read 0 bytes from 4
Query is: select `process_instance`.`id`, `process_instance`.`start_time`, `process_instance`.`end_time`, `process_instance`.`data`, `process_instance`.`priority`, `process_instance`.`process_name`, `process_instance`.`resource_type`, `process_instance`.`resource_id`, `process_instance`.`result`, `process_instance`.`exit_reason`, `process_instance`.`phase`, `process_instance`.`start_process_server_id`, `process_instance`.`running_process_server_id`, `process_instance`.`execution_count`, `process_instance`.`run_after`, `process_instance`.`account_id` from `process_instance` where `process_instance`.`id` = ?, parameters [127]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:137) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.getException(ExceptionMapper.java:101) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwAndLogException(ExceptionMapper.java:77) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:224) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:411) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.MariaDbServerPreparedStatement.execute(MariaDbServerPreparedStatement.java:361) ~[mariadb-java-client-1.5.8.jar:na]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar:1.4]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:194) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:261) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:322) ~[jooq-3.3.0.jar:na]
	... 31 common frames omitted
