### ISSUE TITLE
Stack stuck in "Activating" state with error message- Unknown schema type [stack]

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6080]
Rancher Version: rancher/server:master from Sep 28

Steps to reproduce the problem:
Create a stack.
Stack stuck in "Activating" state for ever with error message "Unknown schema type [stack]"

rancher-compose-executor process throws this error:
```
io.cattle.platform.async.utils.TimeoutException: Timeout
    at io.cattle.platform.async.retry.impl.RetryTimeoutServiceImpl$1.run(RetryTimeoutServiceImpl.java:51)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

cattle logs:
```
16-09-28 20:26:40,172 DEBUG [:] [] [] [] [ecutorService-6] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [PROCESS_ALREADY_IN_PROGRESS] process [stack.create:421889] on resource [950] 
2016-09-28 20:26:40,176 DEBUG [:] [] [] [] [ecutorService-6] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [stack.create:421890] on resource [951] 
2016-09-28 20:26:40,176 DEBUG [:] [] [] [] [ecutorService-6] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [PROCESS_ALREADY_IN_PROGRESS] process [stack.create:421890] on resource [951] 
2016-09-28 20:26:40,180 DEBUG [:] [] [] [] [ecutorService-6] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [stack.create:421891] on resource [952] 
2016-09-28 20:26:40,180 DEBUG [:] [] [] [] [ecutorService-6] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [PROCESS_ALREADY_IN_PROGRESS] process [stack.create:421891] on resource [952] 
2016-09-28 20:26:40,184 DEBUG [:] [] [] [] [ecutorService-6] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [stack.create:421892] on resource [953] 
2016-09-28 20:26:40,184 DEBUG [:] [] [] [] [ecutorService-6] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [PROCESS_ALREADY_IN_PROGRESS] process [stack.create:421892] on resource [953] 
2016-09-28 20:26:40,188 DEBUG [:] [] [] [] [ecutorService-6] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [stack.create:421893] on resource [954] 
2016-09-28 20:26:40,188 DEBUG [:] [] [] [] [ecutorService-6] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [PROCESS_ALREADY_IN_PROGRESS] process [stack.create:421893] on resource [954] 
2016-09-28 20:26:40,192 DEBUG [:] [] [] [] [ecutorService-6] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [stack.create:421894] on resource [955] 
2016-09-28 20:26:40,193 DEBUG [d76e7337-6117-4706-92cd-24e4f933abc8:421894] [stack:955] [stack.create->(StackAgentHandler)] [] [ecutorService-6] [c.p.e.p.i.DefaultProcessInstanceImpl] Running handler [StackAgentHandler] 
2016-09-28 20:26:40,194 DEBUG [d76e7337-6117-4706-92cd-24e4f933abc8:421894] [stack:955] [stack.create->(StackAgentHandler)] [] [ecutorService-6] [c.p.e.p.i.DefaultProcessInstanceImpl] Finished handler [StackAgentHandler] 
2016-09-28 20:26:40,194 DEBUG [d76e7337-6117-4706-92cd-24e4f933abc8:421894] [stack:955] [stack.create->(rancher-compose-executor)] [] [ecutorService-6] [c.p.e.p.i.DefaultProcessInstanceImpl] Running handler [rancher-compose-executor] 
2016-09-28 20:26:41,184 DEBUG [:] [] [] [] [ServiceReplay-9] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [TIMEOUT] process [stack.create:421884] on resource [945] 
2016-09-28 20:26:41,185 INFO  [:] [] [] [] [ServiceReplay-9] [i.c.p.e.e.i.ProcessEventListenerImpl] Communication timeout on process [stack.create:421884] on [945] : Timeout 
2016-09-28 20:26:41,186 DEBUG [:] [] [] [] [erviceReplay-23] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [TIMEOUT] process [stack.create:421885] on resource [946] 
2016-09-28 20:26:41,186 INFO  [:] [] [] [] [erviceReplay-23] [i.c.p.e.e.i.ProcessEventListenerImpl] Communication timeout on process [stack.create:421885] on [946] : Timeout 
2016-09-28 20:26:41,187 DEBUG [:] [] [] [] [erviceReplay-11] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [TIMEOUT] process [stack.create:421880] on resource [941] 
2016-09-28 20:26:41,187 INFO  [:] [] [] [] [erviceReplay-11] [i.c.p.e.e.i.ProcessEventListenerImpl] Communication timeout on process [stack.create:421880] on [941] : Timeout 
2016-09-28 20:26:41,188 DEBUG [:] [] [] [] [erviceReplay-24] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [TIMEOUT] process [stack.create:421883] on resource [944] 
2016-09-28 20:26:41,189 INFO  [:] [] [] [] [erviceReplay-24] [i.c.p.e.e.i.ProcessEventListenerImpl] Communication timeout on process [stack.create:421883] on [944] : Timeout 
```

**Comment by deniseschannon** [comment]
Can you re-test @sangeethah ?

**Comment by sangeethah** [comment]
Tested with build from master. This issue is not seen anymore.
