### ISSUE TITLE
rancher-compose failing intermittently with stack trace. Rarely completes tasks

### ISSUE THREAD

**Issue by cooperaj** [rancher/rancher#6088]
**Rancher Version:**
v1.1.4

**Docker Version:**
1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
macOS Sierra client
Ubuntu 14.04, VMWare vSphere. 1 Rancher HA instance and 4 Hosts.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single HA Rancher instance.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Run rancher-compose -p project up
or 
rancher-compose -p project up --force-upgrade
or
rancher-compose -p project up --confirm-upgrade

**Results:** 
In a project comprised of 3 components I may be lucky enough to have the first one go through. The rancher-compose process then may either a) crash out with a stack trace or b) hang. Subsequent re-runs of the command will likely get you further. As it does not seem to hang/crash on `Service blah must be state=active or inactive to upgrade, currently: state=upgraded`

Example stack trace on failure after succeeding with first component of 3 in this stack

```
rancher-compose -p cache up
INFO[0000] [0/3] [redis-bootstrap]: Starting            
INFO[0000] [1/3] [redis-bootstrap]: Started             
INFO[0000] [1/3] [redis-sentinel]: Starting             
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x3efeb809381c pc=0xcd7b0]

goroutine 130 [running]:
runtime.throw(0x8c2e20, 0x2a)
    /usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc8205fb238 sp=0xc8205fb220
runtime.sigpanic()
    /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc8205fb288 sp=0xc8205fb238
sync.(*Pool).Get(0xbbc1a0, 0x0, 0x0)
    /usr/local/go/src/sync/pool.go:102 +0x40 fp=0xc8205fb2d8 sp=0xc8205fb288
fmt.newPrinter(0x10)
    /usr/local/go/src/fmt/print.go:133 +0x27 fp=0xc8205fb318 sp=0xc8205fb2d8
fmt.Fprintf(0xd77400, 0xc8204e88c0, 0x86a4c0, 0x18, 0xc8205fb510, 0x4, 0x4, 0xc81ffe9f96, 0x0, 0x0)
    /usr/local/go/src/fmt/print.go:187 +0x30 fp=0xc8205fb360 sp=0xc8205fb318
github.com/rancher/rancher-compose/vendor/github.com/Sirupsen/logrus.(*TextFormatter).printColored(0xc82000e220, 0xc8204e88c0, 0xc820171580, 0xbed908, 0x0, 0x0)
    /go/src/github.com/rancher/rancher-compose/vendor/github.com/Sirupsen/logrus/text_formatter.go:110 +0x38c fp=0xc8205fb558 sp=0xc8205fb360
github.com/rancher/rancher-compose/vendor/github.com/Sirupsen/logrus.(*TextFormatter).Format(0xc82000e220, 0xc820171580, 0x0, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/rancher/rancher-compose/vendor/github.com/Sirupsen/logrus/text_formatter.go:78 +0x5d0 fp=0xc8205fb6c8 sp=0xc8205fb558
github.com/rancher/rancher-compose/vendor/github.com/Sirupsen/logrus.(*Entry).Reader(0xc820171580, 0xc800000002, 0x0, 0x0)
    /go/src/github.com/rancher/rancher-compose/vendor/github.com/Sirupsen/logrus/entry.go:41 +0x67 fp=0xc8205fb760 sp=0xc8205fb6c8
github.com/rancher/rancher-compose/vendor/github.com/Sirupsen/logrus.(*Entry).log(0xc820171580, 0x2, 0xc82013f680, 0x94)
    /go/src/github.com/rancher/rancher-compose/vendor/github.com/Sirupsen/logrus/entry.go:84 +0x270 fp=0xc8205fb880 sp=0xc8205fb760
github.com/rancher/rancher-compose/vendor/github.com/Sirupsen/logrus.(*Entry).Error(0xc820171580, 0xc8205fb908, 0x1, 0x1)
    /go/src/github.com/rancher/rancher-compose/vendor/github.com/Sirupsen/logrus/entry.go:135 +0x78 fp=0xc8205fb8c0 sp=0xc8205fb880
github.com/rancher/rancher-compose/vendor/github.com/Sirupsen/logrus.(*Entry).Errorf(0xc820171580, 0x885420, 0x24, 0xc8205fba90, 0x1, 0x1)
    /go/src/github.com/rancher/rancher-compose/vendor/github.com/Sirupsen/logrus/entry.go:183 +0x139 fp=0xc8205fb948 sp=0xc8205fb8c0
github.com/rancher/rancher-compose/vendor/github.com/Sirupsen/logrus.(*Logger).Errorf(0xc82000a380, 0x885420, 0x24, 0xc8205fba90, 0x1, 0x1)
    /go/src/github.com/rancher/rancher-compose/vendor/github.com/Sirupsen/logrus/logger.go:97 +0x101 fp=0xc8205fb998 sp=0xc8205fb948
github.com/rancher/rancher-compose/vendor/github.com/Sirupsen/logrus.Errorf(0x885420, 0x24, 0xc8205fba90, 0x1, 0x1)
    /go/src/github.com/rancher/rancher-compose/vendor/github.com/Sirupsen/logrus/exported.go:137 +0x55 fp=0xc8205fb9d0 sp=0xc8205fb998
github.com/rancher/rancher-compose/rancher.(*RancherService).Log(0xc8203e1640, 0x0, 0x0)
    /go/src/github.com/rancher/rancher-compose/rancher/service.go:530 +0x21c fp=0xc8205fbf78 sp=0xc8205fb9d0
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8205fbf80 sp=0xc8205fbf78
created by github.com/rancher/rancher-compose/rancher.(*RancherService).up.func1
    /go/src/github.com/rancher/rancher-compose/rancher/service.go:99 +0x50

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc82030a5dc)
    /usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc82030a5d0)
    /usr/local/go/src/sync/waitgroup.go:127 +0xb4
github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project.(*serviceWrapper).Wait(0xc82030a5b0, 0x0, 0x0)
    /go/src/github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project/service-wrapper.go:112 +0x39
github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project.(*Project).traverse(0xc8201fdb00, 0x1, 0xc820560a40, 0xc820477920, 0x947450, 0x947458, 0x0, 0x0)
    /go/src/github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project/project.go:422 +0x8f0
github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project.(*Project).forEach(0xc8201fdb00, 0xbed908, 0x0, 0x0, 0x947450, 0x947458, 0x0, 0x0)
    /go/src/github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project/project.go:327 +0x223
github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project.(*Project).perform(0xc8201fdb00, 0x23, 0x24, 0xbed908, 0x0, 0x0, 0x947450, 0x947458, 0x0, 0x0)
    /go/src/github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project/project.go:309 +0x9f
github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project.(*Project).Up(0xc8201fdb00, 0xbed908, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project/project.go:249 +0x7c
github.com/rancher/rancher-compose/app.ProjectUp(0xc8201fdb00, 0xc8200daa80)
    /go/src/github.com/rancher/rancher-compose/app/app.go:208 +0x21c
github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/cli/app.WithProject.func1(0xc8200daa80)
    /go/src/github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/cli/app/app.go:42 +0x150
github.com/rancher/rancher-compose/vendor/github.com/codegangsta/cli.Command.Run(0x7cecb0, 0x2, 0x0, 0x0, 0x843200, 0x15, 0x0, 0x0, 0x0, 0x0, ...)
    /go/src/github.com/rancher/rancher-compose/vendor/github.com/codegangsta/cli/command.go:113 +0x1087
github.com/rancher/rancher-compose/vendor/github.com/codegangsta/cli.(*App).Run(0xc8202fc4e0, 0xc82000a300, 0x4, 0x4, 0x0, 0x0)
    /go/src/github.com/rancher/rancher-compose/vendor/github.com/codegangsta/cli/app.go:156 +0xbc0
main.cliMain()
    /go/src/github.com/rancher/rancher-compose/main.go:85 +0x11a2
main.main()
    /go/src/github.com/rancher/rancher-compose/main.go:27 +0x93

... much more ...
```

Occasional error message if I get as far as seeing service logs (rancher-compose hangs if it shows up):
`ERRO[0050] Failed to read log: websocket: close 1006 unexpected EOF`

**Expected:**
rancher-compose successfully completes.

**Comment by sra** [comment]
I'm experiencing this as well - repeating the command over and over will result in different results. More than 50% of the time it segfault. I've tried rancher-compose versions 0.8.6 and 0.9.0, 0.9.2

```
rancher-compose --env-file foo.env --project-name foo -f docker-compose-apps.yml -r rancher-compose-apps.yml create
unexpected fault address 0x503ac4fe67f
fatal error: fault
[signal 0xb code=0x1 addr=0x503ac4fe67f pc=0x28f301]
```

Also on macOS 10.12

I've also tried recompiling rancher-compose v0.9.0 from source with the same result. go is installed via homebrew, version 1.7.1

**Comment by sra** [comment]
Actually I believe this is because of a known issue with sierra and go-lang pre 1.7. I rebuilt the binary again after clearing my whole GOPATH of any previously build binaries and the problem is no longer happening.

**Comment by zambon** [comment]
I'm experiencing similar problems. The differences in my environment are:

**Docker version:** 1.11.2
**rancher-compose version:** 0.9.2
**OS:** Boot2docker VM

**Comment by dsvmacdonald** [comment]
Me too

Docker version: 1.11.4
rancher-compose version: v0.8.6
OS: macOS Sierra client & Boot2docker VM

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
