### ISSUE TITLE
Containers stuck in starting state forever when trying to start service with shared volumes with scale >1.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6140]
Rancher Server version - Build from master
Rancher Compose version - rancher-compose-v0.11.0-rc1

Steps to reproduce the problem:
Create a service with shared volumes ( at stack level using external: false) with scale >1.
Containers of the services are stuck in "strating" state forever:

```
Sangeethas-MacBook-Pro:rancher-compose-v0.11.0-rc1 sangeethahariharan1$ cat  test-stack.yml
version: '2'
services:
  nginx3:
    image: nginx
    volumes:
    - foo3:/tmp

volumes:
  foo3:
    driver: convoy-nfs
    external: false
Sangeethas-MacBook-Pro:rancher-compose-v0.11.0-rc1 sangeethahariharan1$ cat  test-r-stack.yml
nginx3:
  scale: 3
Sangeethas-MacBook-Pro:rancher-compose-v0.11.0-rc1 sangeethahariharan1$ 
```

```
Sangeethas-MacBook-Pro:rancher-compose-v0.11.0-rc1 sangeethahariharan1$ ./rancher-compose -p new2 -r test-r-stack.yml -f test-stack.yml up
INFO[0000] Creating stack new2                          
INFO[0000] [0/1] [nginx3]: Creating                     
INFO[0000] Creating service nginx3                      
INFO[0001] [0/1] [nginx3]: Created                      
INFO[0001] [0/1] [nginx3]: Starting     
```

Following exception seen in cattle logs:

```
2016-10-04 22:00:58,122 DEBUG [:] [] [] [] [ServiceReplay-7] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [UNKNOWN_EXCEPTION] process [instance.start:22077] on resource [441] 
2016-10-04 22:00:58,124 ERROR [:] [] [] [] [ServiceReplay-7] [i.c.p.e.e.i.ProcessEventListenerImpl] Unknown exception running process [instance.start:22077] on [441] java.lang.IllegalStateException: More than one volume exists for volume URI [convoy-nfs:///var/lib/rancher/convoy/convoy-nfs-fb33ad74-92f8-4f4f-8516-8f4b45659444/mnt/new2_foo3] or name/externalId [new2_foo3] and storage pool [4].
    at io.cattle.platform.docker.process.dao.impl.DockerComputeDaoImpl.getDockerVolumeInPool(DockerComputeDaoImpl.java:97) ~[cattle-docker-compute-0.5.0-SNAPSHOT.jar:na]
    at sun.reflect.GeneratedMethodAccessor1454.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_111]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_111]
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:280) ~[spring-tx-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at com.sun.proxy.$Proxy52.getDockerVolumeInPool(Unknown Source) ~[na:na]
    at io.cattle.platform.docker.process.instancehostmap.DockerPostInstanceHostMapActivate.createVolumeInStoragePool(DockerPostInstanceHostMapActivate.java:216) ~[cattle-docker-compute-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.docker.process.instancehostmap.DockerPostInstanceHostMapActivate.processVolumes(DockerPostInstanceHostMapActivate.java:195) ~[cattle-docker-compute-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.docker.process.instancehostmap.DockerPostInstanceHostMapActivate.handle(DockerPostInstanceHostMapActivate.java:120) ~[cattle-docker-compute-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:427) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:378) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:372) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:372) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:477) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:308) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:247) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:244) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:186) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:159) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:108) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:105) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:105) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.executeStandardProcess(DefaultObjectProcessManager.java:29) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.process.common.handler.AbstractObjectProcessLogic.activate(AbstractObjectProcessLogic.java:31) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.process.instance.InstanceStart.compute(InstanceStart.java:363) ~[cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.process.instance.InstanceStart.handle(InstanceStart.java:125) ~[cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:427) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:378) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:372) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:372) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:474) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:308) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:247) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:244) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:186) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:159) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:108) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:105) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:105) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.eventing.impl.ProcessEventListenerImpl.processExecute(ProcessEventListenerImpl.java:75) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.engine.server.impl.ProcessInstanceParallelDispatcher$1.runInContext(ProcessInstanceParallelDispatcher.java:27) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
    at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
    at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
    at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
    at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
    at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_111]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_111]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_111]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_111]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_111]

```

***Note: This does not happen all the time. Seems like we hit a race condition where all the 3 instances are the service tries to create volume.

**Comment by cjellick** [comment]
@ibuildthecloud is completely refactoring how volumes work in stacks, so that it actually makes sense. This was a scenario we explicitly discussed.

**Comment by sangeethah** [comment]
This issue is almost always reproducible when I try to create 2 services with same volume that does not exists yet (with scope stack) at the same time .

using the following yml when volume foo5 does not exist , reproduces the issues always.
```
version: '2'
services:
  nginx3:
    image: nginx
    volumes:
    - foo5:/tmp
  nginx4:
    image: nginx
    volumes:
    - foo5:/mydata1

volumes:
  foo5:
    driver: convoy-nfs
    external: false
```

**Comment by deniseschannon** [comment]
Can you please test with rancher-nfs as I believe it's working now with the new storage stuff?

**Comment by sangeethah** [comment]
Tested with rancher-nfs - rancher/storage-nfs:v0.4.0 and rancher-server version -v1.2.0-pre4-rc14

**Comment by nrgiroux** [comment]
Hi,

I have this issue with the exception that scale is 1 for the new service.
I am using rancher-nfs from the catalog, starting a service either from the UI or from rancher-compose with simple parameters (from the docs' examples).

Server and hosts running on RancherOS.

Component | Version
-- | --
Rancher | v1.6.14
Cattle | v0.183.37
User Interface | v1.6.37
Rancher CLI | v0.6.7
Rancher Compose | v0.12.5

I can't see what is (I'm doing) wrong.

Could you help me please. 
(Should I open new issue ?)

Thanks
