### ISSUE TITLE
Host toggle between Reconnecting/Disconnected state and sometimes get to "Active" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6189]
Rancher server version - v1.2.0-pre4-rc2

Steps to reproduce the problem:
Had a setup with 3 hosts.
Validation tests was run on this setup.
All the 3 hosts in this setup toggle between Reconnecting/Disconnected state and sometimes get to "Active" state.

rancher-agent logs:

```
time="2016-10-07T17:01:24Z" level="info" msg="Connecting to proxy." url="ws://104.198.197.230:8080/v1/connectbackend?token=eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjE0NzU4NTk5ODQsInN1YiI6ImNhdHRsZSIsImlzcyI6Imh0dHA6XC9cL2NhdHRsZS5pbyIsInJlcG9ydGVkVXVpZCI6IjhkMDMyMGQ0LWVmZDQtNDQ1NC00MmIyLTZlZTcxNzRjYmE1ZSIsImlhdCI6MTQ3NTg1OTY4NCwia2lkIjoiZGVmYXVsdCJ9.vMEiscrmim3slvybm4_aAjmtIxBt5cNvLYCM4wWI9IykVh4tpHk2n2V2H-2_Eh61s8_xROyd0ZnMLaHep_8N3GdoNleIeIuzZpLlrWiJf1IDkM0h820vnzpkOi-goBTEMEINK3d_9XmeyMiMdNsuaeqFq1kHqJgD9E96ussP7FiH5PgI7QO_hZ-73G2rALaU42515os0e-KwyuvZSoMxUDFl1qFQWLIlvTq84-i88gqpWPjfbeTiu7f-wXf1PZLuKzEMsXXqnNeinSsN1SX4k065qEO8VZuVZ_6mVVrQv4sCaECnB2eUz-ZuYCpdxZ4vqYkrPzBhJJDncKtpXfHjHQ" 
time="2016-10-07T17:01:37Z" level=info msg="Reply: a465dd3f-8428-4c4a-59b7-d74254318910, reply.470413378590552946, 1ihm6579:instanceHostMap, data: empty" 
time="2016-10-07T17:01:37Z" level=info msg="Reply: bb108f9e-7364-4b6f-6af2-39a9211b6592, reply.3101982709947740752, 1ihm6595:instanceHostMap, data: empty" 
time="2016-10-07T17:01:37Z" level=info msg="Reply: da2b5fb3-0490-45a5-4d45-fcddc1f53789, reply.4946332540952921802, 1ihm6623:instanceHostMap, data: empty" 
time="2016-10-07T17:01:37Z" level=info msg="Reply: 6381aaf0-287b-484a-657c-2082407510ed, reply.219003722485451031, 1ihm6586:instanceHostMap, data: empty" 
time="2016-10-07T17:01:37Z" level=info msg="Reply: ea45bc94-0c8e-4bea-606d-0b08e9e810a7, reply.3028607732875987833, 1ihm6587:instanceHostMap, data: empty" 
time="2016-10-07T17:01:38Z" level=info msg="Reply: 6b6d20c0-dcf6-4011-67da-1c0ec2cf79f1, reply.3992751872493959001, 1ihm6593:instanceHostMap, data: empty" 
time="2016-10-07T17:01:38Z" level=info msg="Reply: e165e7f8-7d96-42ee-726f-04799aa3ee80, reply.67612285511751211, 1ihm6603:instanceHostMap, data: empty" 
time="2016-10-07T17:01:38Z" level=info msg="Reply: 1143f100-82c7-4754-484a-281289d79b53, reply.6937325363366492275, 1ihm6573:instanceHostMap, data: empty" 
time="2016-10-07T17:01:38Z" level=info msg="Reply: b6f87586-3eb6-45bc-6e55-6ab61fd5c85d, reply.7228453019770259519, 1ihm6625:instanceHostMap, data: empty" 
time="2016-10-07T17:01:37Z" level=info msg="Reply: 9425dbde-7ef8-4178-5afe-fb018345e013, reply.6209298666050293362, 1ihm6601:instanceHostMap, data: empty" 
time="2016-10-07T17:01:37Z" level=info msg="Reply: eda11031-e13e-46c3-4aec-846944c8e205, reply.7587500385461317084, 1ihm6599:instanceHostMap, data: empty" 
time="2016-10-07T17:01:37Z" level=info msg="Reply: 3cb91922-1883-46bb-697a-81c576780fb2, reply.2498385056153818753, 1ihm6620:instanceHostMap, data: empty" 
time="2016-10-07T17:01:43Z" level="warning" msg="Rancher state watcher returned with error. Waiting 0 and then restarting. Error that caused exit: Failed health check." 
time="2016-10-07T17:01:48Z" level="warning" msg="Hit websocket pong timeout. Last websocket ping received at 2016-10-07 17:01:34.318605984 +0000 UTC. Closing connection." 
time="2016-10-07T17:01:58Z" level="error" msg="Received error reading from socket. Exiting." error="read tcp 10.128.0.35:51792->104.198.197.230:8080: use of closed network connection" 
time="2016-10-07T17:02:02Z" level=warning msg="websocket closed: websocket: write timeout" 
time="2016-10-07T17:02:05Z" level=info msg="Hit websocket pong timeout. Last websocket ping received at 2016-10-07 17:01:30.909965341 +0000 UTC. Closing connection." 
time="2016-10-07T17:02:18Z" level=info msg="Hit websocket pong timeout. Last websocket ping received at 2016-10-07 17:01:55.821304232 +0000 UTC. Closing connection." 
time="2016-10-07T17:02:20Z" level=info msg="Hit websocket pong timeout. Last websocket ping received at 2016-10-07 17:01:55.821304232 +0000 UTC. Closing connection." 
time="2016-10-07T17:02:20Z" level=info msg="Hit websocket pong timeout. Last websocket ping received at 2016-10-07 17:01:55.821304232 +0000 UTC. Closing connection." 
INFO: Starting agent for B2F068DB51DFC395C484
INFO: Access Key: B2F068DB51DFC395C484
INFO: Config URL: http://104.198.197.230:8080/v1
INFO: Storage URL: http://104.198.197.230:8080/v1
INFO: API URL: http://104.198.197.230:8080/v1
INFO: IP: 104.197.168.199
INFO: Port:
INFO: Required Image: rancher/agent:v1.1.0-rc1
INFO: Current Image: rancher/agent:v1.1.0-rc1
INFO: Using image rancher/agent:v1.1.0-rc1
INFO: Downloading agent http://104.198.197.230:8080/v1/configcontent/configscripts
INFO: Updating configscripts
INFO: Downloading http://104.198.197.230:8080/v1//configcontent//configscripts current=
INFO: Running /var/lib/cattle/download/configscripts/configscripts-1-f0f3fb2e1110b5ada7c441705981f93a480313a324294321cff467f0c3e12319/apply.sh
INFO: Sending configscripts applied 1-f0f3fb2e1110b5ada7c441705981f93a480313a324294321cff467f0c3e12319
INFO: Updating pyagent
INFO: Downloading http://104.198.197.230:8080/v1//configcontent//pyagent current=
INFO: Running /var/lib/cattle/download/pyagent/pyagent-1-9e3dcab12585149a65d818082279708965cd826df1937a55b24f48428f8f0c06124d5aac5091904d537563fe28f04808/apply.sh
INFO: Updating host-api
INFO: Downloading http://104.198.197.230:8080/v1//configcontent//host-api current=1-bc5083f29be45a4f692503122265b29c99b207922ad5b3728f11645999674744
INFO: Already up to date
INFO: Sending host-api applied 1-bc5083f29be45a4f692503122265b29c99b207922ad5b3728f11645999674744
INFO: Updating agent-binaries
INFO: Downloading http://104.198.197.230:8080/v1//configcontent//agent-binaries current=1-4200f9b686342da8e941359211b1d8c5f98877ae293d0ead231d43507f1c9eae
INFO: Already up to date
INFO: Sending agent-binaries applied 1-4200f9b686342da8e941359211b1d8c5f98877ae293d0ead231d43507f1c9eae
INFO: Updating python-agent
INFO: Downloading http://104.198.197.230:8080/v1//configcontent//python-agent current=1-185cc486e80d335c18a6c4b23541d43b58927fa9ad5f95079f5df959ebcf827d
INFO: Already up to date
INFO: Sending python-agent applied 1-185cc486e80d335c18a6c4b23541d43b58927fa9ad5f95079f5df959ebcf827d
INFO: Updating cadvisor
INFO: Downloading http://104.198.197.230:8080/v1//configcontent//cadvisor current=1-eb42843d0db697ef150153c74be6661f4cda810dae85fe63a4b8d258d7fda733
INFO: Already up to date
INFO: Sending cadvisor applied 1-eb42843d0db697ef150153c74be6661f4cda810dae85fe63a4b8d258d7fda733
INFO: Sending pyagent applied 1-9e3dcab12585149a65d818082279708965cd826df1937a55b24f48428f8f0c06124d5aac5091904d537563fe28f04808
INFO: Starting agent /var/lib/cattle/pyagent/apply.sh
INFO: Executing /var/lib/cattle/pyagent/agent
INFO: Updating host-config
INFO: Downloading http://104.198.197.230:8080/v1//configcontent//host-config current=host-config-1-4bb409d816031e53102c119afe7a3452b2795142a4b3ff5f89082018b44f871e
INFO: Already up to date
INFO: Sending host-config applied 1-4bb409d816031e53102c119afe7a3452b2795142a4b3ff5f89082018b44f871e
time="2016-10-07T17:02:45Z" level=info msg="Launching agent" 
time="2016-10-07T17:02:45Z" level=info msg="Listening for events on http://104.198.197.230:8080/v1" 
time="2016-10-07T17:02:46Z" level=info msg="launching hostapi" 
time="2016-10-07T17:02:54Z" level="info" msg="Starting event router." 
time="2016-10-07T17:02:54Z" level="info" msg="Watching state directory: /var/lib/rancher/state/containers" 
time="2016-10-07T17:03:22Z" level="warning" msg="Rancher state watcher returned with error. Waiting 0 and then restarting. Error that caused exit: Failed health check." 
time="2016-10-07T17:03:34Z" level="warning" msg="Rancher state watcher returned with error. Waiting 2 and then restarting. Error that caused exit: Failed health check." 
time="2016-10-07T17:03:55Z" level="warning" msg="Rancher state watcher returned with error. Waiting 4 and then restarting. Error that caused exit: Failed health check." 
time="2016-10-07T17:04:17Z" level="warning" msg="Rancher state watcher returned with error. Waiting 8 and then restarting. Error that caused exit: Failed health check." 
panic: Unable to successfully start rancher state watcher.

goroutine 21 [running]:
panic(0x7d7aa0, 0xc4202e8a70)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/rancher/host-api/events.(*rancherStateWatcher).watch(0xc4201a94a0)
    /go/src/github.com/rancher/host-api/events/rancher_state_watcher.go:54 +0x317
created by github.com/rancher/host-api/events.(*DockerEventsProcessor).Process
    /go/src/github.com/rancher/host-api/events/entry.go:49 +0x219
time="2016-10-07T17:05:20Z" level=error msg="exit status 2" 
time="2016-10-07T17:04:57Z" level="warning" msg="Rancher state watcher returned with error. Waiting 16 and then restarting. Error that caused exit: Failed health check." 
2016/10/07 17:06:07 FATAL error killing process: os: process already finished
time="2016-10-07T17:06:39Z" level="fatal" msg="Get http://104.198.197.230:8080/v1: EOF" 
time="2016-10-07T17:06:43Z" level=error msg="exit status 1" 
time="2016-10-07T17:08:02Z" level="info" msg="Starting event router." 
time="2016-10-07T17:08:03Z" level="info" msg="Watching state directory: /var/lib/rancher/state/containers" 
time="2016-10-07T17:08:43Z" level="info" msg="Assigning IP [10.42.97.130/16], ContainerId [2a3432176e86776078d018d9fb60233cbef23a78f0779034bf95a1cae54adc2d], Pid [24146]" 
time="2016-10-07T17:08:43Z" level="info" msg="Assigning IP [10.42.92.246/16], ContainerId [6dc17c800a26c12be5b02e5a4eb71d36f0eca9224926be0648b0821d32b74a5b], Pid [8973]" 
time="2016-10-07T17:08:43Z" level="info" msg="Assigning IP [10.42.190.62/16], ContainerId [f9bbe40b57777f0e1eca995940fb9777bcdbfa931e233a57b9fe5bd4ed7f3761], Pid [17316]" 
time="2016-10-07T17:08:43Z" level="info" msg="Assigning IP [10.42.189.235/16], ContainerId [3987f8866e56f91bf5b4c5e4385fed2cc045706a8d9610048da797cf82214218], Pid [13334]" 
time="2016-10-07T17:08:43Z" level="info" msg="Assigning IP [10.42.30.221/16], ContainerId [9880643d62df71099df86184bc3b476339ae4772f85d5798b5a2691581a07e72], Pid [22699]" 
time="2016-10-07T17:08:43Z" level="info" msg="Assigning IP [10.42.200.154/16], ContainerId [1297fcabfc544d7b502a0de298629f6514d98fb8036d001372bb111a13d9553b], Pid [21594]" 
time="2016-10-07T17:08:43Z" level="info" msg="Assigning IP [10.42.161.157/16], ContainerId [a13d79c86223a83985866230064456642ae41964cffec05b0e030c5a6d91365f], Pid [11099]" 
time="2016-10-07T17:08:43Z" level="info" msg="Assigning IP [10.42.10.219/16], ContainerId [71ad94920f84b84efaa9c275e1b5a063e2ef5f4cf79cfe53f616788086105d60], Pid [8971]" 
time="2016-10-07T17:08:43Z" level="info" msg="Assigning IP [10.42.106.127/16], ContainerId [ef8ad63816e0f903a071ea07a0582b4e35ef443ea6ef221c5cbc0169bb3ca176], Pid [19170]" 
time="2016-10-07T17:08:43Z" level="info" msg="Assigning IP [10.42.27.19/16], ContainerId [3542b9a3c6106649037a03f15a87e212fcbb2a519828cb2c9dac6ec6e540111c], Pid [28673]" 
time="2016-10-07T17:09:04Z" level=info msg="Initializing event router" workerCount=50 
time="2016-10-07T17:09:04Z" level=info msg="Connection established" 
time="2016-10-07T17:09:04Z" level=info msg="Starting websocket pings" 
time="2016-10-07T17:09:18Z" level="info" msg="Assigning IP [10.42.103.129/16], ContainerId [b1e40c92935030520ccf3ffc7df0ce03bdb290d82104740c48b5c5a6dfd67a26], Pid [29658]" 
time="2016-10-07T17:09:19Z" level="info" msg="Assigning IP [10.42.95.68/16], ContainerId [5968f9b035da1e48a6f359e575ec966bcd1affe4cc74c60c3835012b0dbab867], Pid [19874]" 
time="2016-10-07T17:09:19Z" level="info" msg="Assigning IP [10.42.39.162/16], ContainerId [cf63d8983b1ba042cdd2e181e3abfa31db7fc9b6df60bb461bf1479f8c07fd18], Pid [29129]" 
time="2016-10-07T17:09:19Z" level="info" msg="Assigning IP [10.42.65.80/16], ContainerId [6e90ff1f5a3f5c1b7ace89531dfa01501e4ad57b4f74723e245985f8311dc54f], Pid [29130]" 
time="2016-10-07T17:09:19Z" level="info" msg="Assigning IP [10.42.63.188/16], ContainerId [f795174e88d5d12679a017faaa216a78560d5db91272fb20fc447a0c6d0e9e0f], Pid [11994]" 
time="2016-10-07T17:09:19Z" level="info" msg="Assigning IP [10.42.7.7/16], ContainerId [819de4252dc514023d5f6b6288c59050a60450d053615d55b1497525181bbf72], Pid [29128]" 
time="2016-10-07T17:09:19Z" level="info" msg="Assigning IP [10.42.89.200/16], ContainerId [670038807b4cbd3399d6e795576e40224cb00d2e8c964b13cf1387cb031443fe], Pid [29659]" 
time="2016-10-07T17:09:19Z" level="info" msg="Assigning IP [10.42.112.89/16], ContainerId [635c7cf9af04403a787e49e99ac7e836df14b9121638d55f6bd2ede44bbe5c30], Pid [28378]" 
time="2016-10-07T17:09:19Z" level="info" msg="Assigning IP [10.42.10.84/16], ContainerId [ce7e9595abc38c3a035944cb74eddb6ab38337cd4f0ee07b08751137af705f74], Pid [9845]" 
time="2016-10-07T17:09:19Z" level="info" msg="Assigning IP [10.42.48.36/16], ContainerId [bb64e2307c035e087ec0b63f9424e2471efb651ee08bbc1563738cd4f4602b1e], Pid [18716]" 
time="2016-10-07T17:09:24Z" level=info msg="Reply: 2452dbee-a99e-41a8-79dd-4ce07b646ea9, reply.8190107422815049783, 1a2:agent, data: not empty" 
```

**Comment by sangeethah** [comment]
Lot of tests have failed with service activation failing with this error message - "Scheduling failed: No healthy hosts with sufficient resources available"

**Comment by sangeethah** [comment]
Tested with lastet build from master - Oct 13 ~5:30 pm.
This issue is still seen in setups with large number of containers.

**Comment by sangeethah** [comment]
@StrongMonkey , I still see this issue when testing with v1.2.0-pre4-rc4.

**Comment by sangeethah** [comment]
@StrongMonkey , I still see this issue when testing with v1.2.0-pre4-rc5. I have shared the environment with you.

**Comment by cjellick** [comment]
@will-chan we talked through this with @sangeethah and @ibuildthecloud. This only happened most recently when the number of containers were really high and the rancher/server host was underpowered.

Can we move out of 1.2 and revisit when/if @cloudnautique does proper scale testing?

**Comment by superseb** [comment]
Do we need to keep this open @cjellick ?
