### ISSUE TITLE
java.lang.OutOfMemoryError:Java heap space encountered when starting containers.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#625]
Server version - V0.17.1

Server has been up for 3 days now.
I have been performing use cases relating to LoadBalancer and services which involved starting and stopping of lot of containers.

The server's response time was very high and some of the request were timing out. 
Server has hit "java.lang.OutOfMemoryError:Java heap space" .

Following exception seen in the server logs:

2015-04-27 21:46:29,918 DEBUG [93552f8e-6029-4f4d-a722-4b8f7643a1c7:18146] [instance:779->nic:778] [instance.start->(InstanceStart)->nic.activate->(AgentInstanceApplyItems)] [] [torService-8127] [i.c.p.e.memory.InMemoryEventService ]
 Subscribing to [reply.4581200577453231439] 
2015-04-27 21:46:29,924 DEBUG [0557c136-2128-433c-9410-aee21472a355:18145] [instance:778->nic:779] [instance.start->(InstanceStart)->nic.activate->(AgentInstanceApplyItems)] [] [torService-8075] [i.c.p.e.memory.InMemoryEventService ]
 Subscribing to [reply.7801606432559164390] 
2015-04-27 21:46:29,927 DEBUG [:] [] [] [] [torService-8179] [i.c.p.e.memory.InMemoryEventService ] Subscribing to [reply.847906280266519208] 
2015-04-27 21:46:29,927 DEBUG [0557c136-2128-433c-9410-aee21472a355:18145] [instance:778->nic:779] [instance.start->(InstanceStart)->nic.activate->(AgentInstanceApplyItems)] [] [torService-7960] [i.c.p.e.memory.InMemoryEventService ]
 Subscribing to [reply.8438257432329845665] 
2015-04-27 21:46:29,930 DEBUG [:] [] [] [] [torService-7666] [i.c.p.e.memory.InMemoryEventService ] Subscribing to [reply.3936065744233316201] 
:

^2015-04-27 21:46:29,902 ERROR [:] [] [] [] [p416565147-8916] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [io.github.ibuildthecloud.gdapi.request.ApiRequest@1a468d19] java.lang.OutOfMemoryError: Java heap space
        at com.fasterxml.jackson.core.util.BufferRecycler.calloc(BufferRecycler.java:115) ~[jackson-core-2.3.1.jar:2.3.1]
        at com.fasterxml.jackson.core.util.BufferRecycler.allocCharBuffer(BufferRecycler.java:90) ~[jackson-core-2.3.1.jar:2.3.1]
        at com.fasterxml.jackson.core.util.BufferRecycler.allocCharBuffer(BufferRecycler.java:79) ~[jackson-core-2.3.1.jar:2.3.1]
        at com.fasterxml.jackson.core.io.IOContext.allocTokenBuffer(IOContext.java:159) ~[jackson-core-2.3.1.jar:2.3.1]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.<init>(ReaderBasedJsonParser.java:84) ~[jackson-core-2.3.1.jar:2.3.1]
        at com.fasterxml.jackson.core.JsonFactory._createParser(JsonFactory.java:1273) ~[jackson-core-2.3.1.jar:2.3.1]
        at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:844) ~[jackson-core-2.3.1.jar:2.3.1]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2098) ~[jackson-databind-2.3.1.jar:2.3.1]
        at io.cattle.platform.json.JacksonJsonMapper.readValue(JacksonJsonMapper.java:68) ~[cattle-framework-json-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.json.JacksonJsonMapper.readValue(JacksonJsonMapper.java:146) ~[cattle-framework-json-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.db.jooq.converter.impl.JsonUnmodifiableMap.<init>(JsonUnmodifiableMap.java:20) ~[cattle-framework-jooq-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.db.jooq.converter.DataConverter.from(DataConverter.java:31) ~[cattle-framework-jooq-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.db.jooq.converter.DataConverter.from(DataConverter.java:16) ~[cattle-framework-jooq-0.5.0-SNAPSHOT.jar:na]
        at org.jooq.impl.ConvertedDataType.convert(ConvertedDataType.java:89) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.AbstractRecord$TransferRecordState.operate(AbstractRecord.java:560) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:123) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.AbstractRecord.intoRecord(AbstractRecord.java:536) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.DefaultRecordMapper$RecordToRecordMapper.map(DefaultRecordMapper.java:386) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.DefaultRecordMapper$RecordToRecordMapper.map(DefaultRecordMapper.java:380) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.DefaultRecordMapper.map(DefaultRecordMapper.java:305) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.ResultImpl.into(ResultImpl.java:1081) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.AbstractResultQuery.fetchInto(AbstractResultQuery.java:634) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.SelectImpl.fetchInto(SelectImpl.java:2517) ~[jooq-3.3.0.jar:na]
        at io.cattle.platform.configitem.context.dao.impl.NetworkInfoDaoImpl.networkServices(NetworkInfoDaoImpl.java:172) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.configitem.context.impl.HostRouteInfoFactory.populateContext(HostRouteInfoFactory.java:22) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.configitem.context.impl.AbstractAgentBaseContextFactory.populateContext(AbstractAgentBaseContextFactory.java:69) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.configitem.server.model.impl.AbstractArchiveBasedConfigItem.handleRequest(AbstractArchiveBasedConfigItem.java:56) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.configitem.server.impl.ConfigItemServerImpl.handleDownload(ConfigItemServerImpl.java:92) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.configitem.server.impl.ConfigItemServerImpl.handleRequest(ConfigItemServerImpl.java:35) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.configitem.api.manager.ConfigContentManager.handle(ConfigContentManager.java:80) ~[cattle-config-item-api-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.configitem.api.manager.ConfigContentManager.getByIdInternal(ConfigContentManager.java:49) ~[cattle-config-item-api-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.getById(AbstractBaseResourceManager.java:61) ~[gdapi-java-server-0.10.3.jar:na]

2015-04-27 21:46:29,904 DEBUG [0557c136-2128-433c-9410-aee21472a355:18145] [instance:778->nic:779] [instance.start->(InstanceStart)->nic.activate->(AgentInstanceApplyItems)] [] [torService-8166] [i.c.p.e.memory.InMemoryEventService ] Subs
cribing to [reply.1636328086407698123] 
2015-04-27 21:46:29,908 DEBUG [50ee83c5-e0eb-4160-887a-32c905645e3e:18143] [instance:776->nic:777] [instance.start->(InstanceStart)->nic.activate->(AgentInstanceApplyItems)] [] [torService-8090] [i.c.p.e.memory.InMemoryEventService ] Subs
cribing to [reply.2890571945659570158] 
2015-04-27 21:46:29,908 DEBUG [:] [] [] [] [torService-7842] [i.c.p.e.memory.InMemoryEventService ] Subscribing to [reply.5890930887486045624] 
2015-04-27 21:46:29,909 DEBUG [50ee83c5-e0eb-4160-887a-32c905645e3e:18143] [instance:776->nic:777] [instance.start->(InstanceStart)->nic.activate->(AgentInstanceApplyItems)] [] [torService-8021] [i.c.p.e.memory.InMemoryEventService ] Subs
cribing to [reply.5347925768963665230]

**Comment by sangeethah** [comment]
This issue is seen with server version - rancher/server:v0.22.0-rc2.

Cattle server process takes up almost 100% of cpu.
top - 19:58:11 up 19:25,  1 user,  load average: 1.09, 1.16, 0.98
Tasks:  95 total,   2 running,  92 sleeping,   0 stopped,   1 zombie
%Cpu(s): 98.7 us,  1.0 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 st
KiB Mem:   3790088 total,  3660088 used,   130000 free,   134360 buffers
KiB Swap:        0 total,        0 used,        0 free.  2291204 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                            
 3519 root      20   0 1469800 644356  22348 S 98.8 17.0  79:37.17 java  

Following exception seen in the logs:
2015-05-28 19:02:19,763 ERROR [:] [] [] [] [1849376398-3342] [i.g.i.g.s.ApiRequestFilterDelegate  ] Unhandled exception in API for request [io.github.ibuildthecloud.gd
api.request.ApiRequest@2b28d436] java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:2271) ~[na:1.7.0_79]
        at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:113) ~[na:1.7.0_79]
        at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93) ~[na:1.7.0_79]
        at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:140) ~[na:1.7.0_79]
        at com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:1848) ~[jackson-core-2.5.3.jar:2.5.3]
        at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeFieldName(UTF8JsonGenerator.java:210) ~[jackson-core-2.5.3.jar:2.5.3]
        at com.fasterxml.jackson.databind.ser.std.StdKeySerializers$StringKeySerializer.serialize(StdKeySerializers.java:77) ~[jackson-databind-2.5.3.jar:2.5.3]
        at com.fasterxml.jackson.databind.ser.std.StdKeySerializers$StringKeySerializer.serialize(StdKeySerializers.java:71) ~[jackson-databind-2.5.3.jar:2.5.3]
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:538) ~[jackson-databind-2.5.3.jar:2.5.3]
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:466) ~[jackson-databind-2.5.3.jar:2.5.3]
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:29) ~[jackson-databind-2.5.3.jar:2.5.3]
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:575) ~[jackson-databind-2.5.3.jar:2.5.3]
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:666) ~[jackson-databind-2.5.3.jar:2.5.3]
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:156) ~[jackson-databind-2.5.3.jar:2.5.3]
        at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:132) ~[jackson-databind-2.5.3.jar:2.5.3]
        at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:94) ~[jackson-databind-2.5.3.jar:2.5.3]
        at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:24) ~[jackson-databind-2.5.3.jar:2.5.3]
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:575) ~[jackson-databind-2.5.3.jar:2.5.3]
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:666) ~[jackson-databind-2.5.3.jar:2.5.3]
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:156) ~[jackson-databind-2.5.3.jar:2.5.3]
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:129) ~[jackson-databind-2.5.3.jar:2.5.3]
        at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3385) ~[jackson-databind-2.5.3.jar:2.5.3]
        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2745) ~[jackson-databind-2.5.3.jar:2.5.3]
        at io.github.ibuildthecloud.gdapi.json.JacksonMapper.writeValue(JacksonMapper.java:67) ~[gdapi-java-server-0.10.7.jar:na]
        at io.github.ibuildthecloud.gdapi.response.JsonResponseWriter.writeJson(JsonResponseWriter.java:103) ~[gdapi-java-server-0.10.7.jar:na]
        at io.github.ibuildthecloud.gdapi.response.JsonResponseWriter.handle(JsonResponseWriter.java:44) ~[gdapi-java-server-0.10.7.jar:na]
        at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:88) ~[gdapi-java-server-0.10.7.jar:na]
        at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:60) ~[cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar
:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) ~[cattle-framework-managed-context-0.5.0-SN
APSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) ~[cattle-framework-managed-context-0.5.0-SNAP
SHOT.jar:na]

**Comment by will-chan** [comment]
obsolete.
