### ISSUE TITLE
Image not found in private repository when creating a service

### ISSUE THREAD

**Issue by retog** [rancher/rancher#6271]
**Rancher Version: v1.1.4**

**Docker Version: 1.12.2**

**OS and where are the hosts located? Ubuntu 14:04 on virtual host (contabo.de)**

**Setup Details: single node rancher, internal DB **

**Environment Type: Cattle**

**Steps to Reproduce:**

- Register a private registry
- Create a container from that registry by clicking on "Add Container" in Infrastructure -> Hosts
- Add service with a container from that registry by clicking on "Add Service" in Stacks

**Results:** 

Adding a container to the host works. Creating a service fails with the message saying that the image could not be found.

**Expected:**

I expected to be able to create a service in a stack.

**Comment by aemneina** [comment]
Have you registered the repo omitting the http(s) and image name? Also when deploying are you giving the repo url/image in the image definition?

**Comment by retog** [comment]
@aemneina, the registry is registered with https://myorg.org:5000, the image is specified as 	myorg.org:5000/myimage,

**Comment by retog** [comment]
In the logs of rancher/agent-instance I see:

```
2016-10-14 17:35:43,315 ERROR agent [139828982239472] [event.py:112] Error in request : 0d7e3cf5-e040-434d-b113-13a2fa25f325 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 34, in execute
    return method(req=req, **req.data.__dict__)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 529, in instance_activate
    self._do_instance_activate(instance, host, progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 607, in _do_instance_activate
    progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 636, in _create_container
    }), progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 951, in _do_instance_pull
    DockerPool.image_pull(pull_info.image, progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/storage.py", line 96, in image_pull
    return DockerPool()._do_image_activate(image, None, progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/storage.py", line 162, in _do_image_activate
    raise e
ImageValidationError: Image [myorg.org:5000/myimage:latest] failed to pull: Error: image myimage:latest not found
```

**Comment by aemneina** [comment]
@retog can you remove and readd the registry with myorg.org:5000 and when deploying the image specify myorg.org:5000/myimage ... can you let us know if that works?

**Comment by retog** [comment]
Great, this works. Thanks a lot @aemneina.
