### ISSUE TITLE
Saml: error is not displayed when adding user that has no access on the server

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#6322]
**Rancher version:** master image

**Steps to produce:** 

- Enable SAML authentication
- Authenticate with a user that exists on the SAML server
- open "Manage Environments" 
- Edit environment
- Add new user with any name
- Click save

**Results**
User gets added

rancher server logs
```
time="2016-10-18T22:38:56Z" level=info msg="shibboleth IdentityProvider does not support GetIdentity API" 
time="2016-10-18T22:38:56Z" level=info msg="shibboleth IdentityProvider does not support GetIdentity API" 
time="2016-10-18T22:38:56Z" level=info msg="shibboleth IdentityProvider does not support GetIdentity API" 
2016-10-18 22:38:56,898 ERROR [:] [] [] [] [cutorService-21] [o.a.c.m.context.NoExceptionRunnable ] Uncaught exc
eption java.lang.NullPointerException: null
        at io.cattle.platform.iaas.api.auth.AbstractTokenUtil.findAndSetJWT(AbstractTokenUtil.java:215) ~[cattle
-iaas-auth-logic-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.iaas.api.auth.integration.external.ExternalServiceAuthProvider.getIdentity(Externa
lServiceAuthProvider.java:202) ~[cattle-iaas-auth-logic-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.iaas.api.auth.identity.IdentityManager.projectMemberToIdentity(IdentityManager.jav
a:143) ~[cattle-iaas-auth-logic-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.iaas.api.auth.identity.IdentityManager.projectMemberToIdentity(IdentityManager.jav
a:167) ~[cattle-iaas-auth-logic-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.iaas.api.auth.projects.ProjectMemberResourceManager.listInternal(ProjectMemberReso
urceManager.java:71) ~[cattle-iaas-auth-logic-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.getByIdInternal(Abst
ractBaseResourceManager.java:68) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.getById(AbstractBase
ResourceManager.java:61) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.iaas.api.change.impl.ResourceChangeEventProcessor.processEvent(ResourceChangeEvent
        at io.cattle.platform.api.pubsub.subscribe.NonBlockingSubscriptionHandler$1.onEvent(NonBlockingSubscript
Processor.java:50) ~[cattle-iaas-api-logic-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.api.pubsub.subscribe.NonBlockingSubscriptionHandler.postProcess(NonBlockingSubscriptionHandler.java:99) ~[cattle-framework-api-pub-sub-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.api.pubsub.subscribe.NonBlockingSubscriptionHandler$1.onEvent(NonBlockingSubscriptionHandler.java:75) ~[cattle-framework-api-pub-sub-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_111]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_111]
```
**Expected**
The Rancher server should display an error showing that the user doesn't exist on the server

**Comment by prachidamle** [comment]
This is not possible to fix due limitation of SAML. There is no way to do a lookup on the SAML server, it only supports authenticating a given set of credentials.

So there is no way to verify what user enters is a valid user/group or not. That is why we just add what the user enters.
