### ISSUE TITLE
Load balancer fail to start. (master branch)

### ISSUE THREAD

**Issue by Dremor** [rancher/rancher#6488]
**Rancher Version:** Master

**Docker Version:** 1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
OpenSUSE Tumbleweed

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
- Run from rancher/server:master
- Add an host (I used the same host as Rancher server)
- Add a service (I used the Ghost image from docker library)
- Add a load balancer

**Results:** 

Load balancer fail to start :

Error log :

```
02/11/2016 13:36:50time="2016-11-02T12:36:50Z" level=info msg="LB provider: haproxy"
02/11/2016 13:36:50time="2016-11-02T12:36:50Z" level=info msg="starting rancher controller"
02/11/2016 13:36:50time="2016-11-02T12:36:50Z" level=info msg="Healthcheck handler is listening on :10241"
02/11/2016 13:36:51time="2016-11-02T12:36:51Z" level=info msg=" -- starting haproxy\n[ALERT] 306/123650 (27) : Starting frontend GLOBAL: cannot bind UNIX socket [/run/haproxy/admin.sock]\n"
02/11/2016 13:37:28time="2016-11-02T12:37:28Z" level=error msg="Error initiating metadata client: Get http://rancher-metadata/2015-12-19/version: dial tcp: lookup rancher-metadata on 8.8.8.8:53: no such host"
02/11/2016 13:37:28time="2016-11-02T12:37:28Z" level=info msg="Shutting down rancher controller"
02/11/2016 13:37:28time="2016-11-02T12:37:28Z" level=info msg="Shutting down provider haproxy"
02/11/2016 13:37:28panic: runtime error: invalid memory address or nil pointer dereference
02/11/2016 13:37:28[signal 0xb code=0x1 addr=0x80 pc=0x5139cf]
02/11/2016 13:37:28
02/11/2016 13:37:28goroutine 1 [running]:
02/11/2016 13:37:28panic(0x19236a0, 0xc820016070)
02/11/2016 13:37:28	/usr/local/go/src/runtime/panic.go:481 +0x3e6
02/11/2016 13:37:28github.com/rancher/lb-controller/controller/rancher.rMetaFetcher.OnChange(0x0, 0x0, 0x5, 0xc820550c80)
02/11/2016 13:37:28	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:125 +0x3f
02/11/2016 13:37:28github.com/rancher/lb-controller/controller/rancher.(*rMetaFetcher).OnChange(0xc820550c70, 0x5, 0xc820550c80)
02/11/2016 13:37:28	<autogenerated>:6 +0xac
02/11/2016 13:37:28github.com/rancher/lb-controller/controller/rancher.(*loadBalancerController).Run(0xc8204349c0, 0x7f61d3aadba8, 0xc8203dcfa0)
02/11/2016 13:37:28	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:119 +0x42d
02/11/2016 13:37:28main.main()
02/11/2016 13:37:28	/go/src/github.com/rancher/lb-controller/main.go:43 +0x2b4
02/11/2016 13:37:34time="2016-11-02T12:37:34Z" level=info msg="KUBERNETES_URL is not set, skipping init of kubernetes controller"
02/11/2016 13:37:34time="2016-11-02T12:37:34Z" level=info msg="Starting Rancher LB service"
02/11/2016 13:37:34time="2016-11-02T12:37:34Z" level=info msg="LB controller: rancher"
02/11/2016 13:37:34time="2016-11-02T12:37:34Z" level=info msg="LB provider: haproxy"
02/11/2016 13:37:34time="2016-11-02T12:37:34Z" level=info msg="starting rancher controller"
02/11/2016 13:37:34time="2016-11-02T12:37:34Z" level=info msg="Healthcheck handler is listening on :10241"
02/11/2016 13:37:35time="2016-11-02T12:37:35Z" level=info msg=" -- starting haproxy\n[ALERT] 306/123734 (27) : Starting frontend GLOBAL: cannot bind UNIX socket [/run/haproxy/admin.sock]\n"
02/11/2016 13:38:36time="2016-11-02T12:38:36Z" level=error msg="Error initiating metadata client: Get http://rancher-metadata/2015-12-19/version: dial tcp: lookup rancher-metadata on 8.8.8.8:53: no such host"
02/11/2016 13:38:36time="2016-11-02T12:38:36Z" level=info msg="Shutting down rancher controller"
02/11/2016 13:38:36time="2016-11-02T12:38:36Z" level=info msg="Shutting down provider haproxy"
02/11/2016 13:38:36panic: runtime error: invalid memory address or nil pointer dereference
02/11/2016 13:38:36[signal 0xb code=0x1 addr=0x80 pc=0x5139cf]
02/11/2016 13:38:36
02/11/2016 13:38:36goroutine 1 [running]:
02/11/2016 13:38:36panic(0x19236a0, 0xc820016070)
02/11/2016 13:38:36	/usr/local/go/src/runtime/panic.go:481 +0x3e6
02/11/2016 13:38:36github.com/rancher/lb-controller/controller/rancher.rMetaFetcher.OnChange(0x0, 0x0, 0x5, 0xc820521500)
02/11/2016 13:38:36	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:125 +0x3f
02/11/2016 13:38:36github.com/rancher/lb-controller/controller/rancher.(*rMetaFetcher).OnChange(0xc8205214f0, 0x5, 0xc820521500)
02/11/2016 13:38:36	<autogenerated>:6 +0xac
02/11/2016 13:38:36github.com/rancher/lb-controller/controller/rancher.(*loadBalancerController).Run(0xc8204349c0, 0x7f9b97736ba8, 0xc8203dafe0)
02/11/2016 13:38:36	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:119 +0x42d
02/11/2016 13:38:36main.main()
02/11/2016 13:38:36	/go/src/github.com/rancher/lb-controller/main.go:43 +0x2b4
02/11/2016 13:38:44time="2016-11-02T12:38:44Z" level=info msg="KUBERNETES_URL is not set, skipping init of kubernetes controller"
02/11/2016 13:38:44time="2016-11-02T12:38:44Z" level=info msg="Starting Rancher LB service"
02/11/2016 13:38:44time="2016-11-02T12:38:44Z" level=info msg="LB controller: rancher"
02/11/2016 13:38:44time="2016-11-02T12:38:44Z" level=info msg="LB provider: haproxy"
02/11/2016 13:38:44time="2016-11-02T12:38:44Z" level=info msg="starting rancher controller"
02/11/2016 13:38:44time="2016-11-02T12:38:44Z" level=info msg="Healthcheck handler is listening on :10241"
02/11/2016 13:38:45time="2016-11-02T12:38:45Z" level=info msg=" -- starting haproxy\n[ALERT] 306/123844 (25) : Starting frontend GLOBAL: cannot bind UNIX socket [/run/haproxy/admin.sock]\n"
02/11/2016 13:39:15time="2016-11-02T12:39:15Z" level=error msg="Error initiating metadata client: Get http://rancher-metadata/2015-12-19/version: dial tcp: lookup rancher-metadata on 8.8.8.8:53: no such host"
02/11/2016 13:39:15time="2016-11-02T12:39:15Z" level=info msg="Shutting down rancher controller"
02/11/2016 13:39:15time="2016-11-02T12:39:15Z" level=info msg="Shutting down provider haproxy"
02/11/2016 13:39:15panic: runtime error: invalid memory address or nil pointer dereference
02/11/2016 13:39:15[signal 0xb code=0x1 addr=0x80 pc=0x5139cf]
02/11/2016 13:39:15
02/11/2016 13:39:15goroutine 1 [running]:
02/11/2016 13:39:15panic(0x19236a0, 0xc820016070)
02/11/2016 13:39:15	/usr/local/go/src/runtime/panic.go:481 +0x3e6
02/11/2016 13:39:15github.com/rancher/lb-controller/controller/rancher.rMetaFetcher.OnChange(0x0, 0x0, 0x5, 0xc820656130)
02/11/2016 13:39:15	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:125 +0x3f
02/11/2016 13:39:15github.com/rancher/lb-controller/controller/rancher.(*rMetaFetcher).OnChange(0xc820656120, 0x5, 0xc820656130)
02/11/2016 13:39:15	<autogenerated>:6 +0xac
02/11/2016 13:39:15github.com/rancher/lb-controller/controller/rancher.(*loadBalancerController).Run(0xc8200629c0, 0x7f5d9a1c8ca8, 0xc820100300)
02/11/2016 13:39:15	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:119 +0x42d
02/11/2016 13:39:15main.main()
02/11/2016 13:39:15	/go/src/github.com/rancher/lb-controller/main.go:43 +0x2b4
02/11/2016 13:39:22time="2016-11-02T12:39:22Z" level=info msg="KUBERNETES_URL is not set, skipping init of kubernetes controller"
02/11/2016 13:39:22time="2016-11-02T12:39:22Z" level=info msg="Starting Rancher LB service"
02/11/2016 13:39:22time="2016-11-02T12:39:22Z" level=info msg="LB controller: rancher"
02/11/2016 13:39:22time="2016-11-02T12:39:22Z" level=info msg="LB provider: haproxy"
02/11/2016 13:39:22time="2016-11-02T12:39:22Z" level=info msg="starting rancher controller"
02/11/2016 13:39:22time="2016-11-02T12:39:22Z" level=info msg="Healthcheck handler is listening on :10241"
02/11/2016 13:39:23time="2016-11-02T12:39:23Z" level=info msg=" -- starting haproxy\n[ALERT] 306/123922 (26) : Starting frontend GLOBAL: cannot bind UNIX socket [/run/haproxy/admin.sock]\n"
02/11/2016 13:39:54time="2016-11-02T12:39:54Z" level=error msg="Error initiating metadata client: Get http://rancher-metadata/2015-12-19/version: dial tcp: lookup rancher-metadata on 8.8.8.8:53: no such host"
02/11/2016 13:39:54time="2016-11-02T12:39:54Z" level=info msg="Shutting down rancher controller"
02/11/2016 13:39:54time="2016-11-02T12:39:54Z" level=info msg="Shutting down provider haproxy"
02/11/2016 13:39:54panic: runtime error: invalid memory address or nil pointer dereference
02/11/2016 13:39:54[signal 0xb code=0x1 addr=0x80 pc=0x5139cf]
02/11/2016 13:39:54
02/11/2016 13:39:54goroutine 1 [running]:
02/11/2016 13:39:54panic(0x19236a0, 0xc820016070)
02/11/2016 13:39:54	/usr/local/go/src/runtime/panic.go:481 +0x3e6
02/11/2016 13:39:54github.com/rancher/lb-controller/controller/rancher.rMetaFetcher.OnChange(0x0, 0x0, 0x5, 0xc820656cc0)
02/11/2016 13:39:54	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:125 +0x3f
02/11/2016 13:39:54github.com/rancher/lb-controller/controller/rancher.(*rMetaFetcher).OnChange(0xc820656cb0, 0x5, 0xc820656cc0)
02/11/2016 13:39:54	<autogenerated>:6 +0xac
02/11/2016 13:39:54github.com/rancher/lb-controller/controller/rancher.(*loadBalancerController).Run(0xc8204309c0, 0x7fbc81b7dba8, 0xc8203d4fc0)
02/11/2016 13:39:54	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:119 +0x42d
02/11/2016 13:39:54main.main()
02/11/2016 13:39:54	/go/src/github.com/rancher/lb-controller/main.go:43 +0x2b4
02/11/2016 13:40:14time="2016-11-02T12:40:14Z" level=info msg="KUBERNETES_URL is not set, skipping init of kubernetes controller"
02/11/2016 13:40:14time="2016-11-02T12:40:14Z" level=info msg="Starting Rancher LB service"
02/11/2016 13:40:14time="2016-11-02T12:40:14Z" level=info msg="LB controller: rancher"
02/11/2016 13:40:14time="2016-11-02T12:40:14Z" level=info msg="LB provider: haproxy"
02/11/2016 13:40:14time="2016-11-02T12:40:14Z" level=info msg="starting rancher controller"
02/11/2016 13:40:14time="2016-11-02T12:40:14Z" level=info msg="Healthcheck handler is listening on :10241"
02/11/2016 13:40:15time="2016-11-02T12:40:15Z" level=info msg=" -- starting haproxy\n[ALERT] 306/124014 (27) : Starting frontend GLOBAL: cannot bind UNIX socket [/run/haproxy/admin.sock]\n"
02/11/2016 13:40:50time="2016-11-02T12:40:50Z" level=error msg="Error initiating metadata client: Get http://rancher-metadata/2015-12-19/version: dial tcp: lookup rancher-metadata on 8.8.8.8:53: no such host"
02/11/2016 13:40:50time="2016-11-02T12:40:50Z" level=info msg="Shutting down rancher controller"
02/11/2016 13:40:50time="2016-11-02T12:40:50Z" level=info msg="Shutting down provider haproxy"
02/11/2016 13:40:50panic: runtime error: invalid memory address or nil pointer dereference
02/11/2016 13:40:50[signal 0xb code=0x1 addr=0x80 pc=0x5139cf]
02/11/2016 13:40:50
02/11/2016 13:40:50goroutine 1 [running]:
02/11/2016 13:40:50panic(0x19236a0, 0xc820016070)
02/11/2016 13:40:50	/usr/local/go/src/runtime/panic.go:481 +0x3e6
02/11/2016 13:40:50github.com/rancher/lb-controller/controller/rancher.rMetaFetcher.OnChange(0x0, 0x0, 0x5, 0xc82014eff0)
02/11/2016 13:40:50	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:125 +0x3f
02/11/2016 13:40:50github.com/rancher/lb-controller/controller/rancher.(*rMetaFetcher).OnChange(0xc82014efe0, 0x5, 0xc82014eff0)
02/11/2016 13:40:50	<autogenerated>:6 +0xac
02/11/2016 13:40:50github.com/rancher/lb-controller/controller/rancher.(*loadBalancerController).Run(0xc8204329c0, 0x7fa5c59bbba8, 0xc8203d3000)
02/11/2016 13:40:50	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:119 +0x42d
02/11/2016 13:40:50main.main()
02/11/2016 13:40:50	/go/src/github.com/rancher/lb-controller/main.go:43 +0x2b4
```

**Expected:**

Load-balancer start normally.

**Comment by deniseschannon** [comment]
@Dremor When did you build your master container? Our current master branch just got a lot of significant changes and is not quite working right now. :)
