### ISSUE TITLE
Not able to create LB service using v1format for LB.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6569]
Rancher server build - Latest from master
Rancher-compose version  - v0.11.0-rc9

```
Sangeethas-MacBook-Pro:rancher-compose-v0.11.0-rc9 sangeethahariharan1$ ./rancher-compose -p hello -f test-lb.yml up 
INFO[0000] Creating stack hello                         
INFO[0000] [0/3] [web1]: Creating                       
INFO[0000] [0/3] [web2]: Creating                       
INFO[0000] Creating service web1                        
INFO[0000] Creating service web2                        
INFO[0001] [0/3] [web1]: Created                        
INFO[0001] [0/3] [web2]: Created                        
INFO[0001] [0/3] [lb-1]: Creating                       
INFO[0001] Creating service lb-1                        
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x14e579]

goroutine 25 [running]:
panic(0x74ebc0, 0x820e36090)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/rancher/rancher-compose/rancher.populateLbFields(0x82100c860, 0x820f13800, 0x821113400, 0x0, 0x0)
    /go/src/github.com/rancher/rancher-compose/rancher/lb_service.go:106 +0x1269
github.com/rancher/rancher-compose/rancher.(*NormalFactory).config(0xce5d80, 0x82100c860, 0x82105e008, 0x148, 0x0, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/rancher/rancher-compose/rancher/normal.go:73 +0x74f
github.com/rancher/rancher-compose/rancher.(*NormalFactory).configAndHash(0xce5d80, 0x82100c860, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8211f6a70, 0x0, 0x0)
    /go/src/github.com/rancher/rancher-compose/rancher/normal.go:21 +0x7c
github.com/rancher/rancher-compose/rancher.(*NormalFactory).Create(0xce5d80, 0x82100c860, 0x0, 0x0)
    /go/src/github.com/rancher/rancher-compose/rancher/normal.go:81 +0x6c
github.com/rancher/rancher-compose/rancher.(*RancherService).createService(0x82100c860, 0x8212658d8, 0x0, 0x0)
    /go/src/github.com/rancher/rancher-compose/rancher/service.go:295 +0x1ef
github.com/rancher/rancher-compose/rancher.(*RancherService).Create(0x82100c860, 0x8820e7c8d8, 0x820e36238, 0x0, 0x0, 0x0)
    /go/src/github.com/rancher/rancher-compose/rancher/service.go:79 +0x7e
github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project.(*Project).Create.func1.1(0x8820f3f120, 0x82100c860, 0x0, 0x0)
    /go/src/github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project/project_create.go:22 +0x96
github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project.(*serviceWrapper).Do(0x8210f47e0, 0x821234ab0, 0x7, 0x8, 0x82131bf48)
    /go/src/github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project/service-wrapper.go:101 +0x202
github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project.(*Project).Create.func1(0x8210f47e0, 0x821234ab0)
    /go/src/github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project/project_create.go:23 +0xd2
created by github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project.(*Project).startService
    /go/src/github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project/project.go:428 +0xbb0
```

```
Sangeethas-MacBook-Pro:rancher-compose-v0.11.0-rc9 sangeethahariharan1$ cat test-lb.yml 
lb-1:
  ports:
  - 100:80
  tty: true
  image: rancher/load-balancer-service
  links:
  - web1:web1
  - web2:web2
  stdin_open: true
web1:
  tty: true
  image: sangeetha/testnewhostrouting
  stdin_open: true
web2:
  tty: true
  image: sangeetha/testnewhostrouting
  stdin_open: true
Sangeethas-MacBook-Pro:rancher-compose-v0.11.0-rc9 sangeethahariharan1$ 
```

**Comment by sangeethah** [comment]
Blocks following 2 automated runs:
```
cattlevalidationtest.core.test_rancher_compose_metadata.test_metadata_lb
cattlevalidationtest.core.test_rancher_compose_metadata.test_metadata_lb_updatetarget
```

**Comment by sangeethah** [comment]
Tested with latest build from master Nov11:

Able to create a stack with docker-compose.yml provided in this issue.
Able to get an LB created with correct targets.
