### ISSUE TITLE
Failed to get connect to database when connecting to Azure MySQL due to MariaDB connector bug

### ISSUE THREAD

**Issue by kvaes** [rancher/rancher#6576]
**Rancher Version:** v1.1.4

**Cattle Version:** 0.165.8.4

**Docker Version:** 1.12.3, build 6b644ec

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubunt 16.04 TLS on Azure

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** External MySQL Database (hosted on Azure)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** not relevant

**Steps to Reproduce:**

CATTLE_DB_CATTLE_DATABASE=mysql
CATTLE_DB_CATTLE_MYSQL_HOST=ranchermysql.mydomain.tld
CATTLE_DB_CATTLE_MYSQL_NAME=cattle
CATTLE_DB_CATTLE_MYSQL_PORT=3306
CATTLE_DB_CATTLE_USERNAME=kvaes@ranchermysql

**Results:** 

15:34:52.047 [main] ERROR i.c.p.a.sources.LazyJDBCSource - Failed to get connection to database, will retry for 5 minutes
15:34:53.057 [main] ERROR i.c.p.a.sources.LazyJDBCSource - Failed to get connection to database, will retry for 5 minutes
15:34:54.067 [main] ERROR i.c.p.a.sources.LazyJDBCSource - Failed to get connection to database, will retry for 5 minutes
15:34:55.081 [main] ERROR i.c.p.a.sources.LazyJDBCSource - Failed to get connection to database, will retry for 5 minutes
15:34:56.092 [main] ERROR i.c.p.a.sources.LazyJDBCSource - Failed to get connection to database, will retry for 5 minutes
15:34:57.105 [main] ERROR i.c.p.a.sources.LazyJDBCSource - Failed to get connection to database, will retry for 5 minutes
15:34:58.117 [main] ERROR i.c.p.a.sources.LazyJDBCSource - Failed to get connection to database, will retry for 5 minutes

**Expected:**

Connects...

**Debugging:**
Connection works with the same information from my laptop, directly from the docker host & from the rancher container.

From the host ; 
kvaes@ranchermgmt01:~$ sudo mysql -h ranchermysql.mydomain.tld -P 3306 -u kvaes@ranchermysql -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 65533
Server version: 5.6.26.0 MySQL Community Server (GPL)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| cattle             |
| mysql              |
| performance_schema |
+--------------------+
4 rows in set (0.08 sec)

mysql>

From the rancher container ;

kvaes@ranchermgmt01:~$ sudo docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                              NAMES
d333f361b122        rancher/server      "/usr/bin/s6-svscan /"   6 minutes ago       Up 35 seconds       3306/tcp, 0.0.0.0:8080->8080/tcp   cranky_austin
kvaes@ranchermgmt01:~$ sudo docker exec -it d333f361b122 /bin/bash
root@d333f361b122:/# mysql -h ranchermysql.mydomain.tld -P 3306 -u kvaes@ranchermysql -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 65533
Server version: 5.6.26.0 MySQL Community Server (GPL)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| cattle             |
| mysql              |
| performance_schema |
+--------------------+
4 rows in set (0.05 sec)

mysql>

**Comment by patientayo** [comment]
you set empty password in this user ?
retry by setting a password.

**Comment by kvaes** [comment]
@patientayo you funny guy ;-) But I can understand you want to double check that one...

The log file doesn't show the password, and in my example's I used a password everytime.(hence the "Enter password:"-prompt).

In regards to the startup of Rancher, I used the following command;

sudo docker run -d --restart=unless-stopped -p 8080:8080 \
    -e CATTLE_DB_CATTLE_MYSQL_HOST="ranchermysql.mydomain.tld" \
    -e CATTLE_DB_CATTLE_MYSQL_PORT="3306" \
    -e CATTLE_DB_CATTLE_MYSQL_NAME="cattle" \
    -e CATTLE_DB_CATTLE_USERNAME="kvaes@ranchermysql" \
    -e CATTLE_DB_CATTLE_PASSWORD="Mysecretranchermysqlpassword666!" \
    rancher/server

Sidenote; the hostname & password have been replaced everywhere for obvious reasons.
The host is located on an external host. So not on the same system. But the tests show it is reachable from the host and from within the created container.
The password is "complex", hence it consists of lowercase, uppercase, a special character (I tested "?" & "!" to see if that was the issue and numberic values.

**Comment by kvaes** [comment]
the environment variables from my rancher container 

root@d333f361b122:/usr/share/cattle# env | grep -i CATTLE_DB
CATTLE_DB_CATTLE_PASSWORD=Mysecretranchermysqlpassword666!
CATTLE_DB_CATTLE_MYSQL_PORT=3306
CATTLE_DB_CATTLE_USERNAME=kvaes@ranchermysql
CATTLE_DB_CATTLE_MYSQL_NAME=cattle
CATTLE_DB_CATTLE_DATABASE=mysql
CATTLE_DB_CATTLE_MYSQL_HOST=ranchermysql.mydomain.tld

**Comment by vincent99** [comment]
Try the IP address instead of the name to see if it's related to Java name resolution?

Tcpdump?  Lots of people use external databases so there's got to be something special about your situation.

**Comment by kvaes** [comment]
A connection on IP has the same result.

When doing a tcpdump, I can see the following error message passing ; #08S01Bad handshake

Sidenote, the service I'm connecting to uses ; Server version: 5.6.26.0 MySQL Community Server (GPL)

**Comment by kvaes** [comment]
When I look at a tcpdump from a working connection (f.e. the mysql command from the host to the mysql service), then I see "SSL SHA20.." passing by after the login.

Could it be that the service is enforcing encryption, and that I'm running into this one ; #4199

**Comment by vincent99** [comment]
Yes that sounds like the problem; MySQL uses StartTLS-style encryption where the client upgrades a that specific connection to TLS.  On the server side either the whole server can be set to require TLS (http://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_require_secure_transport) or for individual users (http://dev.mysql.com/doc/refman/5.7/en/create-user.html#create-user-tls).

**Comment by kvaes** [comment]
The full error message ;

19:48:02.754 [main] ERROR i.c.p.a.sources.LazyJDBCSource - Failed to get connection to database, will retry for 5 minutes
org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Could not connect: Bad handshake)
        at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549) ~[commons-dbcp-1.4.jar:1.4]
        at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388) ~[commons-dbcp-1.4.jar:1.4]
        at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044) ~[commons-dbcp-1.4.jar:1.4]
        at io.cattle.platform.archaius.sources.LazyJDBCSource.checkInitial(LazyJDBCSource.java:50) [cattle-framework-archaius-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.archaius.sources.LazyJDBCSource.poll(LazyJDBCSource.java:34) [cattle-framework-archaius-0.5.0-SNAPSHOT.jar:na]
        at com.netflix.config.AbstractPollingScheduler$1.run(AbstractPollingScheduler.java:163) [archaius-core-0.5.14.jar:na]
        at io.cattle.platform.archaius.polling.RefreshableFixedDelayPollingScheduler.refresh(RefreshableFixedDelayPollingScheduler.java:34) [cattle-framework-archaius-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.archaius.startup.ArchaiusStartup.load(ArchaiusStartup.java:91) [cattle-iaas-archaius-management-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.archaius.startup.ArchaiusStartup.start(ArchaiusStartup.java:68) [cattle-iaas-archaius-management-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.extension.spring.BackgroundStart.run(BackgroundStart.java:63) [cattle-framework-extension-spring-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet$1.with(DefaultModuleDefinitionSet.java:139) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:348) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:358) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:333) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.runHookInContexts(DefaultModuleDefinitionSet.java:131) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.startContexts(DefaultModuleDefinitionSet.java:123) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.load(DefaultModuleDefinitionSet.java:100) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.factory.ModuleBasedContextFactory.loadModules(ModuleBasedContextFactory.java:37) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.init(CloudStackSpringContext.java:75) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_111]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_111]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1638) [spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1579) [spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1509) [spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:521) [spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458) [spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:296) [spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223) [spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:293) [spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) [spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:628) [spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932) [spring-context-3.2.4.RELEASE.jar:3.2.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479) [spring-context-3.2.4.RELEASE.jar:3.2.4.RELEASE]
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.loadContext(DefaultModuleDefinitionSet.java:184) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.loadRootContext(DefaultModuleDefinitionSet.java:117) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.load(DefaultModuleDefinitionSet.java:87) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.factory.ModuleBasedContextFactory.loadModules(ModuleBasedContextFactory.java:37) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.init(CloudStackSpringContext.java:75) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.<init>(CloudStackSpringContext.java:56) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.context.SpringContext.<init>(SpringContext.java:11) [cattle-iaas-system-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.context.WebContextLoaderListener.constructCloudStackSpringContext(WebContextLoaderListener.java:15) [cattle-iaas-system-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.web.CloudStackContextLoaderListener.contextInitialized(CloudStackContextLoaderListener.java:51) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349) [jetty-webapp-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342) [jetty-webapp-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505) [jetty-webapp-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.Server.start(Server.java:387) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.Server.doStart(Server.java:354) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
        at io.cattle.platform.launcher.jetty.Main.main(Main.java:145) [58488b81592773dcae114770406e3e1b/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_111]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_111]
        at io.cattle.platform.launcher.Main.run(Main.java:188) [58488b81592773dcae114770406e3e1b/:na]
        at io.cattle.platform.launcher.Main.main(Main.java:251) [58488b81592773dcae114770406e3e1b/:na]
Caused by: java.sql.SQLNonTransientConnectionException: Could not connect: Bad handshake
        at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:123) ~[mariadb-java-client-1.3.4.jar:na]
        at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69) ~[mariadb-java-client-1.3.4.jar:na]
        at org.mariadb.jdbc.Driver.connect(Driver.java:110) ~[mariadb-java-client-1.3.4.jar:na]
        at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
        at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582) ~[commons-dbcp-1.4.jar:1.4]
        at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556) ~[commons-dbcp-1.4.jar:1.4]
        at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545) ~[commons-dbcp-1.4.jar:1.4]
        ... 65 common frames omitted
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Bad handshake
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:470) ~[mariadb-java-client-1.3.4.jar:na]
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:434) ~[mariadb-java-client-1.3.4.jar:na]
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:355) ~[mariadb-java-client-1.3.4.jar:na]
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:669) ~[mariadb-java-client-1.3.4.jar:na]
        at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:580) ~[mariadb-java-client-1.3.4.jar:na]
        at org.mariadb.jdbc.Driver.connect(Driver.java:105) ~[mariadb-java-client-1.3.4.jar:na]
        ... 69 common frames omitted

**Comment by kvaes** [comment]
I've been pondering that the SSL part is a "distraction" from the real root cause.
It might also be caused by a mismatch between mariadb client & mysql server version (like f.i. a bug of the past ; https://jira.mariadb.org/browse/CONJ-64 )

**Comment by kvaes** [comment]
More debug attempts ; 
installed mariadb client libraries
=> kvaes@kvaesranchermgmt01:~$ sudo apt-get install mariadb-client-core-5.5
And the login test was succesful

Next up was to install a mysql server (as docker container) and connect to that one

kvaes@kvaesranchermgmt01:~$ sudo docker run --name mysql  -e MYSQL_ROOT_PASSWORD=mysecretpw -e MYSQL_DATABASE=cattle -e MYSQL_PASSWORD=mysecretpw -p 6603:3306 -d mysql/mysql-server

#!/bin/bash
sudo docker run -d --restart=unless-stopped -p 8080:8080 \
--link mysql:mysql \
-e CATTLE_DB_CATTLE_MYSQL_HOST="mysql" \
-e CATTLE_DB_CATTLE_MYSQL_PORT="3306" \
-e CATTLE_DB_CATTLE_MYSQL_NAME="cattle" \
-e CATTLE_DB_CATTLE_USERNAME="root" \
-e CATTLE_DB_CATTLE_PASSWORD="mysecretpw" \
rancher/server

kvaes@kvaesranchermgmt01:~$ sudo docker ps -a
CONTAINER ID        IMAGE                COMMAND                  CREATED              STATUS              PORTS                               NAMES
db8c1a1be0c1        rancher/server       "/usr/bin/s6-svscan /"   About a minute ago   Up 59 seconds       3306/tcp, 0.0.0.0:8080->8080/tcp    kickass_lichterman
6cfbbccbd92d        mysql/mysql-server   "/entrypoint.sh mysql"   10 minutes ago       Up 10 minutes       33060/tcp, 0.0.0.0:6603->3306/tcp   mysql

kvaes@kvaesranchermgmt01:~$ sudo docker exec -ti 6cfbbccbd92d /bin/bash
[root@6cfbbccbd92d /]# mysql -V
mysql  Ver 14.14 Distrib 5.7.16, for Linux (x86_64) using  EditLine wrapper

But that one worked...


So tried back towards the version used by my mysql service ;

kvaes@kvaesranchermgmt01:~$ sudo docker run --name mysql -e MYSQL_ROOT_PASSWORD=mysecretpw -e MYSQL_DATABASE=cattle -d mysql/mysql-server:5.6.26

And that one also worked...

**Comment by kvaes** [comment]
After debugging on the service side, it appears to be a bug in the MariaDB connector. This one has been fixed in version ;  1.5.6 => https://jira.mariadb.org/browse/CONJ-394

Would it be possible to update this one? I think the current one is set a few versions back...

<groupId>org.mariadb.jdbc</groupId>
<artifactId>mariadb-java-client</artifactId>
<version>1.3.4</version>

Thanks in advance!

**Comment by ibuildthecloud** [comment]
@kvaes Let me look at this.  I tried bumping up the maria db driver before and things exploded.

**Comment by RobAWilkinson** [comment]
@kvaes what was your workaround to get this going?

**Comment by kvaes** [comment]
(Disclaimer : I recently joined Microsoft.)

There are two facets to linking Rancher to the Azure MySQL.
* SSL Requirement : Check this issue ; https://github.com/rancher/rancher/issues/6576 
* MariaDB Client Compatibility issue : This issue .. ;-)

If both of these are fixed, then you can start using them. And to be honest, you do not want to use a non-ssl link when using PaaS services. Really, you don't, very bad idea.

**Comment by superseb** [comment]
Version was bumped in https://github.com/rancher/cattle/commit/d7243d33051de93e609c8252bc5a6116a2fcf064 which should at least fix the first part of this.

**Comment by fkollmann** [comment]
Issue still exists with 1.6.2-rc1:

`level=fatal msg="this user requires mysql native password authentication."`

**Comment by fkollmann** [comment]
@kvaes: Did you run into this issue, too? #9018

**Comment by janeczku** [comment]
@fkollmann @kvaes Are you still running into this issue in v1.5/v1.6 or can we close the ticket?

**Comment by kvaes** [comment]
I would guess this one would fix it ; https://github.com/rancher/rancher/issues/4199
Though I haven't been able to test it yet.

**Comment by superseb** [comment]
Think this can be closed, let me know if you still run into anything.
