### ISSUE TITLE
Agent error when using LetsEncrypt cert

### ISSUE THREAD

**Issue by natami** [rancher/rancher#6607]
I am having trouble registering a host/agent using certificates from letsencrypt.
I used the certbot to generate the certificates - and configured those into nginx - and browser is accepting the certificate with no warnings.

**Rancher Version:**
pre4-rc5

**Docker Version:**

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ununtu 16.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, Nginx ssl proxy

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:** 

INFO: docker info: Total Memory: 7.784 GiB
INFO: docker info: Name: dev01.local.lan
INFO: docker info: ID: xxxxxxxxxx
INFO: docker info: Http Proxy:
INFO: docker info: Https Proxy:
INFO: docker info: No Proxy:
INFO: Attempting to connect to: https://xxxx.xxxxxxxxxx.dk:5001/v1
INFO: https://xxxx.xxxxxxxxxx:5001/v1 is accessible
Traceback (most recent call last):
  File "./resolve_url.py", line 9, in <module>
    r = requests.get(url)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
ERROR: returned
ERROR: --- START ---

ERROR: --- END ---
ERROR: Failed to load registration env from CATTLE_URL=https://xxxx.xxxxxxxxxx:5001/v1 ENV_URL=
ERROR: Please ensure the proper value for the Host Registration URL is set

**Expected:**
Agent registers with Rancher

**Comment by vincent99** [comment]
Closing due to inactivity.

**Comment by MarcSaric** [comment]
I have the same problem.

**Comment by superseb** [comment]
Usually this is due to incorrect proxy config (missing intermediate or wrong order), if you believe this is an issue in the agent, file a new issue with the used versions of all components, and the configurations so we can take a look and reproduce.
