### ISSUE TITLE
Rancher CLI segfaults

### ISSUE THREAD

**Issue by schuylr** [rancher/rancher#6624]
**Rancher Version:** 1.2.0-pre3

**Docker Version:** 1.10.2/1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** CoreOS/RancherOS, AWS EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** External DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

Run a rancher command, get these intermittent errors.

**Results:** 

```
Schuylers-Work-Computer:jewlr4 sjagr$ rancher hosts
unexpected fault address 0x1cbab11fcb1e
fatal error: fault
[signal 0xb code=0x1 addr=0x1cbab11fcb1e pc=0x228f71]

goroutine 1 [running]:
runtime.throw(0x9016b0, 0x5)
	/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc8205ec368 sp=0xc8205ec350
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:27 +0x2ba fp=0xc8205ec3b8 sp=0xc8205ec368
net/http.send(0xc8201b6380, 0x1cbab11fcafe, 0x0, 0xe7791f70a, 0x0, 0xd9d0a0, 0xc8201b4370, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:260 +0x6b1 fp=0xc8205ec5d0 sp=0xc8205ec3b8
net/http.(*Client).send(0xc82018eb40, 0xc8201b6380, 0xe7791f70a, 0x0, 0xd9d0a0, 0xc8200954a0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:155 +0x185 fp=0xc8205ec6b8 sp=0xc8205ec5d0
net/http.(*Client).doFollowingRedirects(0xc82018eb40, 0xc8201b6380, 0xac15b8, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:475 +0x8a4 fp=0xc8205ec8d0 sp=0xc8205ec6b8
net/http.(*Client).Do(0xc82018eb40, 0xc8201b6380, 0xc82032cc30, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:188 +0xff fp=0xc8205ec970 sp=0xc8205ec8d0
github.com/rancher/cli/vendor/github.com/rancher/go-rancher/v2.(*RancherBaseClient).doGet(0xc820342000, 0xc82032cc30, 0x47, 0xc8205ecb20, 0x613080, 0xc820524150, 0x0, 0x0)
	/go/src/github.com/rancher/cli/vendor/github.com/rancher/go-rancher/v2/common.go:265 +0x378 fp=0xc8205ecae0 sp=0xc8205ec970
github.com/rancher/cli/vendor/github.com/rancher/go-rancher/v2.(*RancherBaseClient).GetLink(0xc820342000, 0xc820153278, 0x5, 0xc820153290, 0x4, 0xc820288600, 0xc820288630, 0x919ef0, 0xb, 0x613080, ...)
	/go/src/github.com/rancher/cli/vendor/github.com/rancher/go-rancher/v2/common.go:324 +0x211 fp=0xc8205ecb98 sp=0xc8205ecae0
github.com/rancher/cli/cmd.hostLs(0xc8202f5540, 0x0, 0x0)
	/go/src/github.com/rancher/cli/cmd/host.go:112 +0x858 fp=0xc8205eda60 sp=0xc8205ecb98
github.com/rancher/cli/cmd.defaultAction.func1(0xc8202f5540, 0x0, 0x0)
	/go/src/github.com/rancher/cli/cmd/common.go:292 +0x86 fp=0xc8205eda90 sp=0xc8205eda60
runtime.call32(0xc82032b040, 0xc820301370, 0xc8202cbdc0, 0x800000018)
	/usr/local/go/src/runtime/asm_amd64.s:472 +0x3e fp=0xc8205edab8 sp=0xc8205eda90
reflect.Value.call(0x682ca0, 0xc820301370, 0x13, 0x8fdb30, 0x4, 0xc8205edf98, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d fp=0xc8205ede08 sp=0xc8205edab8
reflect.Value.Call(0x682ca0, 0xc820301370, 0x13, 0xc8205edf98, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1 fp=0xc8205ede68 sp=0xc8205ede08
github.com/rancher/cli/vendor/github.com/urfave/cli.HandleAction(0x682ca0, 0xc820301370, 0xc8202f5540, 0x0, 0x0)
	/go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:481 +0x2ee fp=0xc8205ee020 sp=0xc8205ede68
github.com/rancher/cli/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc820080780, 0xc8202f5400, 0x0, 0x0)
	/go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:360 +0x1156 fp=0xc8205ee7b0 sp=0xc8205ee020
github.com/rancher/cli/vendor/github.com/urfave/cli.Command.startApp(0x901de8, 0x5, 0x901dd8, 0x4, 0x0, 0x0, 0x0, 0x992210, 0x13, 0x0, ...)
	/go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/command.go:273 +0xa30 fp=0xc8205eee68 sp=0xc8205ee7b0
github.com/rancher/cli/vendor/github.com/urfave/cli.Command.Run(0x901de8, 0x5, 0x901dd8, 0x4, 0x0, 0x0, 0x0, 0x992210, 0x13, 0x0, ...)
	/go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/command.go:74 +0x7b fp=0xc8205ef458 sp=0xc8205eee68
github.com/rancher/cli/vendor/github.com/urfave/cli.(*App).Run(0xc820080600, 0xc82007e060, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:235 +0xa9c fp=0xc8205ef758 sp=0xc8205ef458
main.mainErr(0x0, 0x0)
	/go/src/github.com/rancher/cli/main.go:149 +0x2496 fp=0xc8205f1eb0 sp=0xc8205ef758
main.main()
	/go/src/github.com/rancher/cli/main.go:37 +0x1c fp=0xc8205f1f20 sp=0xc8205f1eb0
runtime.main()
	/usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc8205f1f70 sp=0xc8205f1f20
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8205f1f78 sp=0xc8205f1f70

goroutine 18 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 19 [chan send]:
github.com/rancher/cli/vendor/github.com/docker/libcompose/cli/logger.generateColors()
	/go/src/github.com/rancher/cli/vendor/github.com/docker/libcompose/cli/logger/colors.go:27 +0x182
created by github.com/rancher/cli/vendor/github.com/docker/libcompose/cli/logger.init.1
	/go/src/github.com/rancher/cli/vendor/github.com/docker/libcompose/cli/logger/colors.go:33 +0x2b

goroutine 39 [IO wait]:
net.runtime_pollWait(0x112be88, 0x72, 0xc820384000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8203701b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203701b0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820370150, 0xc820384000, 0x1000, 0x1000, 0x0, 0xf8b028, 0xc82006a080)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820372018, 0xc820384000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820364960, 0x112c2b0, 0xc820372018, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc820380000, 0xac1a17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc820380000, 0xc8202fa000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
bufio.(*Reader).fill(0xc820518660)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc820518660, 0xc8200de878, 0x9, 0x9, 0x234494, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0xf936d0, 0xc820518660, 0xc8200de878, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0xf936d0, 0xc820518660, 0xc8200de878, 0x9, 0x9, 0x13847, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
net/http.http2readFrameHeader(0xc8200de878, 0x9, 0x9, 0xf936d0, 0xc820518660, 0x20000000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:715 +0xa5
net/http.(*http2Framer).ReadFrame(0xc8200de840, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:906 +0xe9
net/http.(*http2clientConnReadLoop).run(0xc820174000, 0x0, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:5583 +0xa6
net/http.(*http2ClientConn).readLoop(0xc820528000)
	/usr/local/go/src/net/http/h2_bundle.go:5544 +0x162
created by net/http.(*http2Transport).NewClientConn
	/usr/local/go/src/net/http/h2_bundle.go:4975 +0xd94

goroutine 206 [select]:
net/http.setRequestCancel.func4(0x0, 0xc82018ebd0, 0xc82034c900, 0xc82062ec60)
	/usr/local/go/src/net/http/client.go:333 +0x12e
created by net/http.setRequestCancel
	/usr/local/go/src/net/http/client.go:341 +0x2f7
```

**Expected:**

Working Rancher CLI. Should I just go to the RCs?

One notable thing is that I upgraded to MacOS Sierra last night. This could have affected things?

**Comment by schuylr** [comment]
Rancher CLI v0.3.0 rc3 seems to work fine whereas 0.2.0 does not above.

**Comment by schuylr** [comment]
There seems to be known issues with Go 1.6.x on MacOS Sierra whereas the latest Go 1.7.3 should have fixed these issues. I tried bumping the compiled binary in rancher/cli but go this:

```
Schuylers-Work-Computer:cli sjagr$ CROSS=1 make build
./.dapper build
Sending build context to Docker daemon 12.02 MB
Step 1 : FROM golang:1.7.3
 ---> ef15416724f6
Step 2 : RUN apt-get update &&     apt-get install -y xz-utils zip rsync
 ---> Using cache
 ---> 5dcc71f35781
Step 3 : RUN go get github.com/rancher/trash
 ---> Using cache
 ---> 48c1d7129f11
Step 4 : RUN go get github.com/golang/lint/golint
 ---> Running in 935f3dd578c5
package golang.org/x/tools/go/gcimporter15: unrecognized import path "golang.org/x/tools/go/gcimporter15" (https fetch: Get https://golang.org/x/tools/go/gcimporter15?go-get=1: dial tcp: lookup golang.org on 192.168.65.1:53: read udp 172.17.0.2:56309->192.168.65.1:53: i/o timeout)
The command '/bin/sh -c go get github.com/golang/lint/golint' returned a non-zero code: 1
FATA[0013] exit status 1                                
make: *** [build] Error 1
```

**Comment by schuylr** [comment]
Looks like it was temporary DNS issues. The build works with `golang:1.7.3` and I can confirm that MacOS Sierra works with this build.

**Comment by ibuildthecloud** [comment]
We'll bump to go 1.7.x

**Comment by deniseschannon** [comment]
We've bumped up to Go 1.7.3. 

@schuylr Can you test using Rancher CLI v0.4.0-rc1 to confirm that the errors are no longer around?

**Comment by schuylr** [comment]
Thanks @deniseschannon!

Confirmed, both my manual build haven't been bugging me with any errors for the past few weeks now, and I just tried out v0.4.0-rc1 with no issues when getting large amounts of info or running `rancher rm -s` on multiple disconnected hosts. I'll continue using the RC and reopen this issue if I encounter any problems.
