### ISSUE TITLE
Container with links cant startup in bridge network mode "Could not get container for xxx"

### ISSUE THREAD

**Issue by rdechow-magari** [rancher/rancher#6656]
**Rancher Version:**
- 1.1.4
- rancher/agent:v1.0.2 

**Docker Version:**
- 1.12.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
- bare metal ubuntu 16.04 and Virtuozzo7 centos7 same failure

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
- single node rancher
- internal DB 

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
- Cattle

**Steps to Reproduce:**
- first container -> addService image: ubuntu:14.04.3 Network:Bridge
- second container -> addService image: ubuntu:14.04.3 Network:Bridge Link to first container
- first container is running
- second container cant start: "Could not get container for 13b5b54a-547c-48c8-8ea7-8905d55e7feb"

- In a managed network it runs without problems

**Results:** 
2016-11-17 08:58:24,982 ERROR agent [139919545746288] [event.py:112] Error in request : fb1c5074-ccbb-4a92-86ca-a9f6d27efd5b 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 34, in execute
    return method(req=req, **req.data.__dict__)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 529, in instance_activate
    self._do_instance_activate(instance, host, progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 607, in _do_instance_activate
    progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 653, in _create_container
    container = client.create_container_from_config(config, name)
  File "/var/lib/cattle/pyagent/dist/docker/api/container.py", line 130, in create_container_from_config
    return self._result(res, True)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 150, in _result
    self._raise_for_status(response)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 146, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 500 Server Error: Internal Server Error ("Could not get container for 13b5b54a-547c-48c8-8ea7-8905d55e7feb")

**Comment by tfiduccia** [comment]
@rdechow-magari - I verified that this is indeed a problem in 1.1.4 version of Rancher.  But I also retested in our master build and this has been fixed.  So when 1.2.0 is available please upgrade.  I'm going to close it.  If you find you are having problem after our next release, please re-open and let me know.
