### ISSUE TITLE
Upgrade io.rancher.scheduler.global label to true does not work

### ISSUE THREAD

**Issue by typia** [rancher/rancher#6741]
**Rancher Version:**

1.2pre3

**Docker Version:**

Docker 1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**

Debian 8 VMs in a datacenter

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single Node Rancher External DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

I want to upgrade a container to make it available automatically on every host.
I wanted to make it so by adding io.rancher.scheduler.global label to the container and set it to true

**Results:** 

Container is stucked as upgrading and marked as null in stack page, scale is set to global in container page.

**Expected:**

Upgrade complete

**Logs:**
 `java.lang.NumberFormatException: null
at java.lang.Long.parseLong(Long.java:404) ~[na:1.7.0_111]
at java.lang.Long.valueOf(Long.java:540) ~[na:1.7.0_111]
at io.cattle.platform.servicediscovery.deployment.impl.planner.GlobalServiceDeploymentPlanner.(GlobalServiceDeploymentPlanner.java:35) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.servicediscovery.deployment.impl.planner.ServiceDeploymentPlannerFactoryImpl.createServiceDeploymentPlanner(ServiceDeploymentPlannerFactoryImpl.java:33) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl.getPlanner(DeploymentManagerImpl.java:284) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:248) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl.reconcileDeployment(DeploymentManagerImpl.java:135) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl$1.doWithLock(DeploymentManagerImpl.java:123) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl$1.doWithLock(DeploymentManagerImpl.java:117) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl.activate(DeploymentManagerImpl.java:117) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl.activate(DeploymentManagerImpl.java:100) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.servicediscovery.upgrade.impl.UpgradeManagerImpl$1.doWithLockNoResult(UpgradeManagerImpl.java:149) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.servicediscovery.upgrade.impl.UpgradeManagerImpl.upgradeDeploymentUnits(UpgradeManagerImpl.java:142) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.servicediscovery.upgrade.impl.UpgradeManagerImpl.doInServiceUpgrade(UpgradeManagerImpl.java:119) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.servicediscovery.upgrade.impl.UpgradeManagerImpl.doUpgrade(UpgradeManagerImpl.java:340) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.servicediscovery.upgrade.impl.UpgradeManagerImpl.upgrade(UpgradeManagerImpl.java:321) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.servicediscovery.process.ServiceUpgrade$1.run(ServiceUpgrade.java:37) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.activity.ActivityService.run(ActivityService.java:43) ~[cattle-activity-log-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.servicediscovery.process.ServiceUpgrade.handle(ServiceUpgrade.java:34) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:427) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:378) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:372) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:372) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:474) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:308) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:247) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:244) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:186) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:159) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:108) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:105) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:105) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.engine.eventing.impl.ProcessEventListenerImpl.processExecute(ProcessEventListenerImpl.java:75) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.engine.server.impl.ProcessInstanceParallelDispatcher$1.runInContext(ProcessInstanceParallelDispatcher.java:27) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_111]
at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_111]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_111]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_111]
at java.lang.Thread.run(Thread.java:745) [na:1.7.0_111]`

**Comment by vincent99** [comment]
Switching between regular scale and global is not supported on upgrade.  The same people read the forums and GitHub, please don't post same thing in [multiple places].

**Comment by typia** [comment]
Hi @vincent99 , thanks for your answer.
I did not know the issues where on github and found it was more appropriate for my problem but could not find a way to remove my post on the forum.
Sorry for the annoyance.
