### ISSUE TITLE
[UI] Got "schema.linkFor is not a function" when redirecting to any page . 

### ISSUE THREAD

**Issue by EcoRIIHC** [rancher/rancher#6769]
**Rancher Version:*v1.1.4*

I just follow the instructions to run `npm start` , and I get into the index page , all looks good .  
But I get an error when I click any button to redirect to any page . Anybody has this issue ?

`schema.linkFor is not a function`

I got this on my console :
`ember.debug.js:19160 TypeError: schema.linkFor is not a function
    at store.js:161
    at tryCatch (ember.debug.js:50954)
    at invokeCallback (ember.debug.js:50969)
    at publish (ember.debug.js:50937)
    at ember.debug.js:40417
    at invoke (ember.debug.js:990)
    at Queue.flush (ember.debug.js:1054)
    at DeferredActionQueues.flush (ember.debug.js:862)
    at Backburner.end (ember.debug.js:176)
    at ember.debug.js:742`

When I click any button to redirect to any page , the console throw Error: 
`Application Error TypeError: schema.linkFor is not a function
    at http://172.18.0.1:8000/assets/vendor.js:151167:28
    at tryCatch (http://172.18.0.1:8000/assets/vendor.js:65900:14)
    at invokeCallback (http://172.18.0.1:8000/assets/vendor.js:65915:15)
    at publish (http://172.18.0.1:8000/assets/vendor.js:65883:9)
    at http://172.18.0.1:8000/assets/vendor.js:55363:16
    at invoke (http://172.18.0.1:8000/assets/vendor.js:15936:16)
    at Queue.flush (http://172.18.0.1:8000/assets/vendor.js:16000:11)
    at DeferredActionQueues.flush (http://172.18.0.1:8000/assets/vendor.js:15808:17)
    at Backburner.end (http://172.18.0.1:8000/assets/vendor.js:15122:25)
    at http://172.18.0.1:8000/assets/vendor.js:15688:18`

**Comment by vincent99** [comment]
The UI in `master` is for Rancher 1.2 and does not work against a 1.1 server.  You can use the [1.1-fixes](https://github.com/rancher/ui/tree/1.1-fixes) branch if you need something that works for 1.1.
