### ISSUE TITLE
HA - "502 Bad Gateway" errors seen in rancher-server logs when one of the rancher-server in cluster is powered down.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6798]
Rancher server version - v1.2.0-dev1

HA setup with 3 rancher-servers in cluster.

While automation runs are being executed on the HA setup , bring down one of the rancher server in the cluster.

Following errors seen in other rancher-servers logs for sometime:

```
2016-11-28 21:06:16,914 ERROR [60348db8-496f-428f-b17d-3809f14952c0:34835] [instance:830->instanceHostMap:828] [instance.start->(InstanceStart)->instancehostmap.activate] [] [ecutorService-6] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.activate.reply;agent=3]: Error response from daemon: linux runtime spec resources: no such file or directory 
2016-11-28 21:06:16,914 ERROR [60348db8-496f-428f-b17d-3809f14952c0:34835] [instance:830] [instance.start->(InstanceStart)] [] [ecutorService-6] [i.c.p.process.instance.InstanceStart] Failed to Starting for instance [830] 
2016-11-28 21:06:18,135 ERROR [124c7fb2-cc99-475a-aa70-1dd12a7b7cf0:13946] [service:176] [service.activate] [] [cutorService-10] [c.p.e.p.i.DefaultProcessInstanceImpl] Expected state running but got error: Error response from daemon: linux runtime spec resources: no such file or directory 
2016-11-28 21:06:18,154 ERROR [:] [] [] [] [cutorService-10] [.e.s.i.ProcessInstanceDispatcherImpl] Expected state running but got error: Error response from daemon: linux runtime spec resources: no such file or directory 
2016-11-28 21:08:13,790 WARN  [:] [] [] [] [.IO.thread-in-0] [c.hazelcast.nio.tcp.TcpIpConnection ] [172.31.28.196]:9345 [4a2a5569-b610-478b-a4b8-ea629b4d5a34] [3.7.1] Connection[id=1, /172.17.0.2:41957->/172.31.28.198:9345, endpoint=[172.31.28.198]:9345, alive=false, type=MEMBER] closed. Reason: Exception in NonBlockingSocketReader java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_72]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_72]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_72]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.8.0_72]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_72]
	at com.hazelcast.nio.tcp.DefaultSocketChannelWrapper.read(DefaultSocketChannelWrapper.java:59) ~[hazelcast-3.7.1.jar:3.7.1]
	at com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketReader.handle(NonBlockingSocketReader.java:148) ~[hazelcast-3.7.1.jar:3.7.1]
	at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.handleSelectionKey(NonBlockingIOThread.java:345) [hazelcast-3.7.1.jar:3.7.1]
	at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.handleSelectionKeys(NonBlockingIOThread.java:330) [hazelcast-3.7.1.jar:3.7.1]
	at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.selectLoop(NonBlockingIOThread.java:248) [hazelcast-3.7.1.jar:3.7.1]
	at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.run(NonBlockingIOThread.java:201) [hazelcast-3.7.1.jar:3.7.1]

2016-11-28 21:08:14,096 WARN  [:] [] [] [] [cached.thread-1] [c.h.nio.tcp.TcpIpConnectionMonitor  ] [172.31.28.196]:9345 [4a2a5569-b610-478b-a4b8-ea629b4d5a34] [3.7.1] Removing connection to endpoint [172.31.28.198]:9345 Cause => java.net.SocketException {Connection refused to address /172.31.28.198:9345}, Error-Count: 5 
2016-11-28 21:08:19,853 ERROR [34dfa91c-de8c-4e7a-8c01-0253ac48b52e:34170] [instance:826->volumeStoragePoolMap:1307] [instance.start->(InstanceStart)->volume.activate->(VolumeActivate)->volumestoragepoolmap.activate] [] [cutorService-15] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [storage.volume.activate.reply;agent=2]: Error sending reply 4653d8a4-cce5-4eaa-8893-39d38890f54f: Bad response statusCode [502]. Status [502 Bad Gateway]. Body: [<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>awselb/2.0</center>
</body>
</html>
] from [http://ahmad.rancher.space:8080/v1/publish] 
2016-11-28 21:08:19,855 ERROR [34dfa91c-de8c-4e7a-8c01-0253ac48b52e:34170] [instance:826->volume:1254] [instance.start->(InstanceStart)->volume.activate] [] [cutorService-15] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [storage.volume.activate.reply;agent=2]: Error sending reply 4653d8a4-cce5-4eaa-8893-39d38890f54f: Bad response statusCode [502]. Status [502 Bad Gateway]. Body: [<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>awselb/2.0</center>
</body>
</html>
] from [http://ahmad.rancher.space:8080/v1/publish] 
2016-11-28 21:08:19,855 ERROR [34dfa91c-de8c-4e7a-8c01-0253ac48b52e:34170] [instance:826] [instance.start->(InstanceStart)] [] [cutorService-15] [i.c.p.process.instance.InstanceStart] Failed to Storage for instance [826] 
2016-11-28 21:08:31,454 ERROR [dd21c09a-84bd-41b3-b04c-8a6df986411e:35764] [instance:858->instanceHostMap:857] [instance.start->(InstanceStart)->instancehostmap.activate] [] [ecutorService-3] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.activate.reply;agent=2]: Error response from daemon: linux runtime spec resources: no such file or directory 
2016-11-28 21:08:31,454 ERROR [dd21c09a-84bd-41b3-b04c-8a6df986411e:35764] [instance:858] [instance.start->(InstanceStart)] [] [ecutorService-3] [i.c.p.process.instance.InstanceStart] Failed to Starting for instance [858] 
2016-11-28 21:08:31,851 ERROR [53ec7fd8-5919-4b9b-bfd9-0cbe2f22cade:35770] [instance:858->instanceHostMap:857] [instance.stop->(InstanceStop)->instancehostmap.deactivate] [] [cutorService-10] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.deactivate.reply;agent=2]: Error sending reply fcde49f5-8b01-4f63-8b45-a258fda1606b: Bad response statusCode [502]. Status [502 Bad Gateway]. Body: [<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>awselb/2.0</center>
</body>
</html>
] from [http://ahmad.rancher.space:8080/v1/publish] 
2016-11-28 21:08:31,857 ERROR [53ec7fd8-5919-4b9b-bfd9-0cbe2f22cade:35770] [instance:858] [instance.stop] [] [cutorService-10] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.deactivate.reply;agent=2]: Error sending reply fcde49f5-8b01-4f63-8b45-a258fda1606b: Bad response statusCode [502]. Status [502 Bad Gateway]. Body: [<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>awselb/2.0</center>
</body>
</html>
] from [http://ahmad.rancher.space:8080/v1/publish] 
2016-11-28 21:08:31,878 ERROR [:] [] [] [] [cutorService-10] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [compute.instance.deactivate.reply;agent=2]: Error sending reply fcde49f5-8b01-4f63-8b45-a258fda1606b: Bad response statusCode [502]. Status [502 Bad Gateway]. Body: [<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>awselb/2.0</center>
</body>
</html>
] from [http://ahmad.rancher.space:8080/v1/publish] 
2016-11-28 21:08:37,500 INFO    [pool-1-thread-1] [ConsoleStatus] Cluster membership changed [172.31.28.196:9345, 172.31.28.197:9345] 
time="2016-11-28 21:08:37" level=info msg="Telemetry Client v0.4.0" 
time="2016-11-28 21:08:37" level=info msg="Listening on 0.0.0.0:8114" 
time="2016-11-28T21:08:37Z" level=info msg="Starting rancher-compose-executor" version=v0.11.0-rc14 
time="2016-11-28T21:08:37Z" level=info msg="Setting log level" logLevel=info 
time="2016-11-28T21:08:37Z" level=info msg="Starting go-machine-service..." gitcommit=v0.33.1 
time="2016-11-28T21:08:37Z" level=info msg="Waiting for handler registration (1/2)" 
time="2016-11-28T21:08:39Z" level=info msg="Initializing event router" workerCount=10 
time="2016-11-28T21:08:39Z" level=info msg="Connection established" 
time="2016-11-28T21:08:39Z" level=info msg="Starting websocket pings" 
time="2016-11-28T21:08:39Z" level=info msg="Waiting for handler registration (2/2)" 
time="2016-11-28T21:08:39Z" level=info msg="Initializing event router" workerCount=10 
time="2016-11-28T21:08:39Z" level=info msg="Initializing event router" workerCount=10 
time="2016-11-28T21:08:39Z" level=info msg="Connection established" 
time="2016-11-28T21:08:39Z" level=info msg="Starting websocket pings" 
time="2016-11-28T21:08:39Z" level=info msg="Connection established" 
time="2016-11-28T21:08:39Z" level=info msg="Starting websocket pings" 
time="2016-11-28T21:08:39Z" level=info msg="Installing builtin drivers" 
time="2016-11-28T21:08:39Z" level=info msg="Downloading all drivers" 
time="2016-11-28T21:08:39Z" level=info msg="Download https://github.com/packethost/docker-machine-driver-packet/releases/download/v0.1.2/docker-machine-driver-packet_linux-amd64.zip" 
2016-11-28 21:08:43,216 ERROR [:] [] [] [] [TaskScheduler-1] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [1] count [3] 
time="2016-11-28T21:08:43Z" level=info msg="Found driver docker-machine-driver-packet" 
time="2016-11-28T21:08:43Z" level=info msg="Copying /var/lib/cattle/machine-drivers/1f7058341420e2f525168052818c3f819ff78e9ca5f57d5a650a049bcd5945e9-docker-machine-driver-packet => /usr/local/bin/docker-machine-driver-packet" 
time="2016-11-28T21:08:43Z" level=info msg="Done downloading all drivers" 
2016-11-28 21:08:44,333 ERROR [57855ad0-e7ca-41f9-828c-a2e6ee12db9c:35784] [instance:790] [instance.purge] [] [ecutorService-7] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.remove.reply;agent=3]: Error sending reply 631604ea-57db-4706-b354-af1281b79a55: Bad response statusCode [502]. Status [502 Bad Gateway]. Body: [<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>awselb/2.0</center>
</body>
</html>
] from [http://ahmad.rancher.space:8080/v1/publish] 
2016-11-28 21:08:44,370 ERROR [:] [] [] [] [ecutorService-7] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [compute.instance.remove.reply;agent=3]: Error sending reply 631604ea-57db-4706-b354-af1281b79a55: Bad response statusCode [502]. Status [502 Bad Gateway]. Body: [<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>awselb/2.0</center>
</body>
</html>
] from [http://ahmad.rancher.space:8080/v1/publish] 
2016-11-28 21:08:44,475 ERROR [4af20fec-9564-4358-a515-e8557b61ed03:35786] [instance:839] [instance.purge->(InstancePurge)->instance.deallocate] [] [cutorService-11] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [[instance.deallocate]]: Failed to deallocate: Error releasing resources: [Resource: instanceReservation, amount: 1] 
2016-11-28 21:08:44,484 ERROR [4af20fec-9564-4358-a515-e8557b61ed03:35786] [instance:839] [instance.purge] [] [cutorService-11] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [[instance.deallocate]]: Failed to deallocate: Error releasing resources: [Resource: instanceReservation, amount: 1] 
2016-11-28 21:08:44,515 ERROR [:] [] [] [] [cutorService-11] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [[instance.deallocate]]: Failed to deallocate: Error releasing resources: [Resource: instanceReservation, amount: 1] 
2016-11-28 21:08:48,217 ERROR [:] [] [] [] [TaskScheduler-1] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [1] count [4] 
```

**Comment by deniseschannon** [comment]
Per @ibuildthecloud This is an error on the external load balancer and not something that Rancher can fix.
