### ISSUE TITLE
Kubernetes upgrade to 1.4.6 fails in a HA setup

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6806]
**Rancher Version:**1.1.4 to 1.2.0-rc1

**Docker Version:**1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**HA

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Kubernetes

**Steps to Reproduce:**
1. Create a HA setup in v1.1.4 and create a Kuberentes env
2. Upgrade rancher to 1.2.0-rc1
3. Upgrade Kuberentes env
4. After Kubernetes env upgrade, upgrade to Kubernetes 1.4.6

**Results:** 
Upgrade to Kubernetes1.4.6 fails. Errors from one of the servers:
```
016-11-29 00:29:11,208 ERROR [:] [] [] [] [ration.thread-0] [c.h.c.l.operations.UnlockOperation  ] [172.31.35.124]:9345 [dcea95d0-c4e1-4041-85b6-9ff65688aca0] [3.7.1] Current thread is not owner of the lock! -> <not-locked> java.lang.IllegalMonitorStateException: Current thread is not owner of the lock! -> <not-locked>
    at com.hazelcast.concurrent.lock.operations.UnlockOperation.unlock(UnlockOperation.java:73) ~[hazelcast-3.7.1.jar:3.7.1]
    at com.hazelcast.concurrent.lock.operations.UnlockOperation.run(UnlockOperation.java:62) ~[hazelcast-3.7.1.jar:3.7.1]
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:181) ~[hazelcast-3.7.1.jar:3.7.1]
    at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:122) [hazelcast-3.7.1.jar:3.7.1]
    at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102) [hazelcast-3.7.1.jar:3.7.1]

2016-11-29 00:29:11,245 ERROR [:] [] [] [] [ration.thread-1] [c.h.c.l.operations.UnlockOperation  ] [172.31.35.124]:9345 [dcea95d0-c4e1-4041-85b6-9ff65688aca0] [3.7.1] Current thread is not owner of the lock! -> <not-locked> java.lang.IllegalMonitorStateException: Current thread is not owner of the lock! -> <not-locked>
    at com.hazelcast.concurrent.lock.operations.UnlockOperation.unlock(UnlockOperation.java:73) ~[hazelcast-3.7.1.jar:3.7.1]
    at com.hazelcast.concurrent.lock.operations.UnlockOperation.run(UnlockOperation.java:62) ~[hazelcast-3.7.1.jar:3.7.1]
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:181) ~[hazelcast-3.7.1.jar:3.7.1]
    at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:122) [hazelcast-3.7.1.jar:3.7.1]
    at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102) [hazelcast-3.7.1.jar:3.7.1]

```

**Comment by chrisurwin** [comment]
I've replicated this, but both the HA and K8s have been upgraded and are working, but i get this error every 5 minutes or so after it has finished upgrading both.
The `<not-locked>` error was there before upgrading K8s but was by the `[cutor-Service-x]` not the `[ration.thread-x]` which appear after both have upgraded

**Comment by deniseschannon** [comment]
Unable to reproduce consistently. After several hours, these setups self corrected.

**Comment by deniseschannon** [comment]
plugin manager v0.2.12

**Comment by soumyalj** [comment]
Tested with upgrade from 1.1.4 to 1.2.0-rc2. Upgrade to Kubernetes 1.4.6 was successful on a HA setup.
