### ISSUE TITLE
HA upgrade: Kubelet and controller manager are failing Kubernetes 1.4.6

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#6849]
**Rancher Version:**
v1.1.4 --> v1.2.0-rc2
**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
ROS 0.7.1
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
- Install Rancher HA 1.1.4
- Deploy kubernetes 1.2.4
- Register 3 ROS hosts on the setup
- Upgrade the setup to rc2

**Results:** 

Kubelet and controller manager keep failing with the following error message:

```
I1130 23:20:28.213336   18591 rancher.go:639] ExternalID [hussein-ha-k8s1]
12/1/2016 1:20:28 AMI1130 23:20:28.213370   18591 rancher.go:645] InstanceID [hussein-ha-k8s1]
12/1/2016 1:20:28 AMI1130 23:20:28.213594   18591 server.go:118] Starting to listen on 0.0.0.0:10250
12/1/2016 1:20:28 AMpanic: runtime error: invalid memory address or nil pointer dereference
12/1/2016 1:20:28 AM[signal 0xb code=0x1 addr=0x0 pc=0x128d595]
12/1/2016 1:20:28 AM
12/1/2016 1:20:28 AMgoroutine 98 [running]:
12/1/2016 1:20:28 AMpanic(0x30c29e0, 0xc82001c0b0)
12/1/2016 1:20:28 AM	/usr/local/go/src/runtime/panic.go:481 +0x3e6
12/1/2016 1:20:28 AMk8s.io/kubernetes/pkg/cloudprovider/providers/rancher.(*CloudProvider).InstanceID(0xc820adfb80, 0x7ffdc72531c6, 0xf, 0x0, 0x0, 0x0, 0x0)
12/1/2016 1:20:28 AM	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/rancher/rancher.go:651 +0x175
12/1/2016 1:20:28 AMk8s.io/kubernetes/pkg/cloudprovider/providers/rancher.(*CloudProvider).ExternalID(0xc820adfb80, 0x7ffdc72531c6, 0xf, 0x0, 0x0, 0x0, 0x0)
12/1/2016 1:20:28 AM	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/rancher/rancher.go:640 +0x13c
12/1/2016 1:20:28 AMk8s.io/kubernetes/pkg/kubelet.(*Kubelet).initialNode(0xc8201aaa00, 0x7ffdc72531c6, 0x0, 0x0)
12/1/2016 1:20:28 AM	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go:226 +0x94c
12/1/2016 1:20:28 AMk8s.io/kubernetes/pkg/kubelet.(*Kubelet).getNodeAnyWay(0xc8201aaa00, 0x0, 0x0, 0x0)
12/1/2016 1:20:28 AM	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_getters.go:208 +0xb3
12/1/2016 1:20:28 AMk8s.io/kubernetes/pkg/kubelet.(*Kubelet).initializeModules(0xc8201aaa00, 0x0, 0x0)
12/1/2016 1:20:28 AM	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1120 +0x434
12/1/2016 1:20:28 AMk8s.io/kubernetes/pkg/kubelet.(*Kubelet).Run(0xc8201aaa00, 0xc820adcba0)
12/1/2016 1:20:28 AM	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1162 +0x2d9
12/1/2016 1:20:28 AMk8s.io/kubernetes/cmd/kubelet/app.startKubelet.func1()
12/1/2016 1:20:28 AM	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:721 +0x3f
12/1/2016 1:20:28 AMk8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc820ac5560)
12/1/2016 1:20:28 AM	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:84 +0x19
12/1/2016 1:20:28 AMk8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc820ac5560, 0x0, 0x0, 0x302f2b36616f7601, 0xc82001b260)
12/1/2016 1:20:28 AM	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:85 +0xb4
12/1/2016 1:20:28 AMk8s.io/kubernetes/pkg/util/wait.Until(0xc820ac5560, 0x0, 0xc82001b260)
12/1/2016 1:20:28 AM	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x43
12/1/2016 1:20:28 AMcreated by k8s.io/kubernetes/cmd/kubelet/app.startKubelet
12/1/2016 1:20:28 AM	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:721 +0xb8
```

**Comment by wlan0** [comment]
This is because of a known bug in DM, where if you upgrade from rancher 1.1.4 to 1.2, go-rancher parsing fails. @ibuildthecloud is developing a workaround for this.

**Comment by galal-hussein** [comment]
@wlan0 @ibuildthecloud Tested the upgrade on rc3 and the kubernetes stack upgraded successfully.
