### ISSUE TITLE
Exception related to load balancer conversion during Upgrade to 1.2.0

### ISSUE THREAD

**Issue by bascht** [rancher/rancher#6882]
**Rancher Version:**
v1.2.0 (image ae0bc36ab32e)

**Docker Version:**
Docker version 1.12.3, build 6b644ec

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS. Rancher Host running Ubuntu 14.04, Agents running RancherOS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher host with external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Pulled latest stable image and upgrade a `v1.1.4` installation to `v1.2.0`. 

**Results:** 
Rancher started to upgrade my environments but took > 30 minutes. I checked the processes tab and the upgrade process threw an exception:

```
java.lang.IllegalArgumentException: No enum constant io.cattle.platform.core.addon.PortRule.Protocol.ssl
	at java.lang.Enum.valueOf(Enum.java:238)
	at io.cattle.platform.core.addon.PortRule$Protocol.valueOf(PortRule.java:19)
	at io.cattle.platform.core.dao.impl.LoadBalancerInfoDaoImpl.generateLBConfig(LoadBalancerInfoDaoImpl.java:264)
	at io.cattle.platform.process.driver.EnvironmentUpgrade.upgradeServices(EnvironmentUpgrade.java:89)
	at io.cattle.platform.process.driver.EnvironmentUpgrade.handle(EnvironmentUpgrade.java:63)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:448)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:399)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:393)
	at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:393)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:495)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:326)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:243)
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7)
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:240)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:182)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:155)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:114)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:111)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:111)
	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl.processExecuteWithLock(ProcessInstanceDispatcherImpl.java:98)
	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl$1$1.doWithLockNoResult(ProcessInstanceDispatcherImpl.java:71)
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7)
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$4.doWithLock(AbstractLockManagerImpl.java:50)
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:25)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:47)
	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl$1.doRun(ProcessInstanceDispatcherImpl.java:68)
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I deleted two of my Stacks that used the Rancher Loadbalancer from that Environment and after that the upgrade went through. I'd love to give more debugging info but the Stacks are already gone and I need to get on with the upgrade. :)

**Comment by cjellick** [comment]
@bascht you wouldn't happen to still have the docker and rancher compose yaml files for the offending stacks, would you?

**Comment by cjellick** [comment]
Ping @alena1108

**Comment by bascht** [comment]
@cjellick Thanks for the quick response. Yip, I still have the files. I needed to scrub out a bit of the customer specific info. ;)

### docker-compose.yml
```
www-ssl:
  external_links:
    - acme-corp/otherapp:otherapp
  image: rancher/load-balancer-service
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.loadbalancer.ssl.ports: '443'
    io.rancher.loadbalancer.target.www: www.example.com:443=8000
    io.rancher.loadbalancer.target.acme-corp/otherapp: other.example.com:443=4678
    io.rancher.scheduler.affinity:host_label: stack=app
  links:
    - www:www
  ports:
    - 443:8000
www:
  environment:
    AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY:
    AWS_SMTP_PASS:
    AWS_SMTP_USER:
    BASICAUTH_PW:
    BASICAUTH_USER:
    COOKIE_SECRET:
    INFLUXDB_URL:
    JWT_SECRET:
    LOGSTASH_URL:
    MONGODB_URI:
    NODE_ENV: production
  external_links:
    - 'MongoDB/mongodb:mongo'
    - 'monitoring-metrics/influxdb:influx'
    - 'monitoring-logs/logstash-collector:logstash'
  image: acme-corp/app:$DOCKER_TAG
  labels:
    io.rancher.scheduler.affinity:host_label: stack=app
    io.rancher.container.pull_image: always
  read_only: true
```

### rancher-compose.yml
```
www-ssl:
  load_balancer_config:
    lb_cookie_stickiness_policy:
      cookie: sid
      nocache: true
      domain: www.example.com
      mode: prefix
  default_cert: reach-aero-staging
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
www:
  scale: 2
  health_check:
    port: 8000
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: none
    response_timeout: 2000
    request_line: ''
    healthy_threshold: 2
```

Let me know if I can supply more info. :)

**Comment by cjellick** [comment]
Thanks @bascht this'll be very helpful

**Comment by soumyalj** [comment]
Tested with upgrade from 1.1.4 to v1.2.1-rc2. Created Lbs with certs using TCP and HTTP in protocols in v1.1.4 and performed the upgrade. Upgrade succeeded and the Lbs were functional. Here is the dc.yml and rc.yml files in v1.1.4

dc1.yml
--------
```
ssllb1:
  ports:
  - 8001:80
  labels:
    io.rancher.loadbalancer.ssl.ports: '8001'
    io.rancher.loadbalancer.target.service1: abc.com/name.html=80
    io.rancher.loadbalancer.target.service2: test.com/service3.html=81
  tty: true
  image: rancher/load-balancer-service
  links:
  - service1:service1
  - service2:service2
  stdin_open: true
service1:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: sangeetha/testnewhostrouting
  stdin_open: true
service2:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: sangeetha/testnewhostrouting
  stdin_open: true
ssllb:
  ports:
  - 8000:80/tcp
  labels:
    io.rancher.loadbalancer.ssl.ports: '8000'
  tty: true
  image: rancher/load-balancer-service
  links:
  - service1:service1
  stdin_open: true
```
rc.yml
------
```
ssllb1:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  default_cert: test1cert
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
service1:
  scale: 1
service2:
  scale: 1
ssllb:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  default_cert: test1cert
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
```

**Comment by bascht** [comment]
👍 Thanks! :)
