### ISSUE TITLE
volume Data too long for column 'external_id' at row 1

### ISSUE THREAD

**Issue by trendsoa** [rancher/rancher#6915]
**Rancher Version:**
1.2
**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS 7.1
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node with external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
just fresh install and click upgrade "network-services"
**Results:** 
time="2016-12-05T02:40:48Z" level=info msg="Finish Stack Upgrade Event Done" eventId=385a4508-2e6d-4ca1-9788-03b10198c35d resourceId=1st2 
2016-12-05 02:42:11,697 ERROR [e5b60938-22b5-4279-868e-bc99a91f4b8c:287] [volume:41] [volume.create] [] [ecutorService-9] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception org.jooq.exception.DataAccessException: SQL [update `volume` set `volume`.`external_id` = ? where `volume`.`id` = ?]; Data too long for column 'external_id' at row 1
        at org.jooq.impl.Utils.translate(Utils.java:1287) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:495) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:326) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.UpdatableRecordImpl.storeUpdate0(UpdatableRecordImpl.java:296) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.UpdatableRecordImpl.access$200(UpdatableRecordImpl.java:90) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.UpdatableRecordImpl$3.operate(UpdatableRecordImpl.java:260) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:123) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.UpdatableRecordImpl.storeUpdate(UpdatableRecordImpl.java:255) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.UpdatableRecordImpl.update(UpdatableRecordImpl.java:149) ~[jooq-3.3.0.jar:na]
        at io.cattle.platform.object.impl.JooqObjectManager.persistRecord(JooqObjectManager.java:223) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
**Expected:**
no exception

**Comment by trendsoa** [comment]
oh..it's due to my other mesos test, will close it.
