### ISSUE TITLE
HA Cluster multi node issue

### ISSUE THREAD

**Issue by chrisurwin** [rancher/rancher#6924]
**Rancher Version:**
1.2.0
**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
Rancher OS in AWS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
multi node HA
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
N/A
**Steps to Reproduce:**
Stand up a multi node HA instance (say 3 nodes) with the nodes in an ASG. When its working set the ASG to scale of 3 and wait for all nodes to be destroyed. Scale the ASG back up to 3
**Results:** 
only 1 of the nodes will start correctly, the other 2 will error with 
```2016-12-05 11:42:04,110 ERROR   [main] [ConsoleStatus] Failed to connect to master at xxx.xxx.xxx.xxx
FATAL: Exiting due to failed cluster check-in
2016-12-05 11:42:04,120 ERROR   [pool-1-thread-1] [ConsoleStatus] Check-in failed java.lang.IllegalStateException: Failed to update check-in, registration deleted
        at io.cattle.platform.hazelcast.membership.dao.impl.ClusterMembershipDAOImpl.checkin(ClusterMembershipDAOImpl.java:35) ~[cattle-hazelcast-common-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.hazelcast.membership.DBDiscovery.checkin(DBDiscovery.java:169) ~[cattle-hazelcast-common-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.hazelcast.membership.DBDiscovery.doRun(DBDiscovery.java:158) ~[cattle-hazelcast-common-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_72]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_72]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_72]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_72]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
```
The containers will then stop unless set to restart. Restarting the servers once 1 nodes is successful will allow the containers to start successfully
**Expected:**
All 3 nodes will join the HA cluster successfully on the first attempt

**Comment by deniseschannon** [comment]
Workaround: Make sure to include `--restart=unless=stopped` per the docs for running HA on ASG nodes.

**Comment by chrisurwin** [comment]
Testing with 1.3.0 appears that this issue is now resolved.
