### ISSUE TITLE
Deis Workflow or any Helm package install returned `Error: transport is closing`       

### ISSUE THREAD

**Issue by strobe** [rancher/rancher#6944]
**Rancher Version:**
1.2.0
**Docker Version:**
1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04.1 LTS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single w internal DB + 3 nodes
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
I did setup of Helm package manager via ```helm init``` as result I got ```tiller-deploy``` at kube-system namespace.
After I tried to install Deis Workflow by:
```
>helm repo add deis https://charts.deis.com/workflow
>helm install deis/workflow --namespace deis
```
**Results:** 
```
Fetched deis/workflow to workflow-v2.9.0.tgz                                                                            
Error: transport is closing                                                                                             
```
log from tiller pod
```
12/6/2016 4:03:14 AMCannot initialize Kubernetes connection: the server has asked for the client to provide credentials2016-12-05 23:03:14.459670 I | storage.go:37: Getting release "solitary-blackbird" (v1) from storage
12/6/2016 4:03:14 AMpanic: runtime error: invalid memory address or nil pointer dereference
12/6/2016 4:03:14 AM[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x805505]
12/6/2016 4:03:14 AM
12/6/2016 4:03:14 AMgoroutine 81 [running]:
12/6/2016 4:03:14 AMpanic(0x1abbfc0, 0xc42000a030)
12/6/2016 4:03:14 AM	/usr/local/go/src/runtime/panic.go:500 +0x1a1
12/6/2016 4:03:14 AMk8s.io/helm/vendor/k8s.io/kubernetes/pkg/client/unversioned.(*ConfigMaps).Get(0xc4202ae7a0, 0xc420368180, 0x15, 0x1ca7431, 0x6, 0xc4202596a0)
12/6/2016 4:03:14 AM	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/k8s.io/kubernetes/pkg/client/unversioned/configmap.go:58 +0x75
12/6/2016 4:03:14 AMk8s.io/helm/pkg/storage/driver.(*ConfigMaps).Get(0xc4201a3f60, 0xc420368180, 0x15, 0xc420368180, 0x15, 0xc420368140)
12/6/2016 4:03:14 AM	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/driver/cfgmaps.go:69 +0x62
12/6/2016 4:03:14 AMk8s.io/helm/pkg/storage.(*Storage).Get(0xc4201a3f70, 0xc420368140, 0x12, 0xc400000001, 0x12, 0x0, 0xc4203f3e30)
12/6/2016 4:03:14 AM	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/storage.go:38 +0x160
12/6/2016 4:03:14 AMk8s.io/helm/pkg/tiller.(*ReleaseServer).uniqName(0xc420020608, 0x0, 0x0, 0xc420259800, 0xd66b43, 0xc4202721c0, 0xc42035e640, 0xc420478b01)
12/6/2016 4:03:14 AM	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/tiller/release_server.go:589 +0xd7
12/6/2016 4:03:14 AMk8s.io/helm/pkg/tiller.(*ReleaseServer).prepareRelease(0xc420020608, 0xc42035e230, 0xc420068001, 0xc4200aa3c0, 0xc42015b040)
12/6/2016 4:03:14 AM	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/tiller/release_server.go:642 +0x71
12/6/2016 4:03:14 AMk8s.io/helm/pkg/tiller.(*ReleaseServer).InstallRelease(0xc420020608, 0x7f6c435686a8, 0xc420477bf0, 0xc42035e230, 0x0, 0x108d7, 0x108d7)
12/6/2016 4:03:14 AM	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/tiller/release_server.go:616 +0x78
12/6/2016 4:03:14 AMk8s.io/helm/pkg/proto/hapi/services._ReleaseService_InstallRelease_Handler(0x1c51f80, 0xc420020608, 0x7f6c435686a8, 0xc420477bf0, 0xc42035e1e0, 0x0, 0x0, 0x0, 0x0, 0x0)
12/6/2016 4:03:14 AM	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:747 +0x27d
12/6/2016 4:03:14 AMk8s.io/helm/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc42015b040, 0x28610a0, 0xc420068000, 0xc4200aa3c0, 0xc4203c48a0, 0x288cbe8, 0xc420477b90, 0x0, 0x0)
12/6/2016 4:03:14 AM	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:608 +0xc50
12/6/2016 4:03:14 AMk8s.io/helm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc42015b040, 0x28610a0, 0xc420068000, 0xc4200aa3c0, 0xc420477b90)
12/6/2016 4:03:14 AM	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:766 +0x6b0
12/6/2016 4:03:14 AMk8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420478c40, 0xc42015b040, 0x28610a0, 0xc420068000, 0xc4200aa3c0)
12/6/2016 4:03:14 AM	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:419 +0xab
12/6/2016 4:03:14 AMcreated by k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
12/6/2016 4:03:14 AM	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:420 +0xa3
```
**Expected:**

**Comment by aemneina** [comment]
@strobe tiller is now deployed in k8s environments, and should be more robust. If you see a similar issue using rancher 1.5.9+ please file a new issue.

**Comment by strobe** [comment]
cool, I will try it with 1.5.9+
