### ISSUE TITLE
If an environment has over ~8000 volumes, the UI wont load.

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#6985]
**Rancher Version:**
1.2.0
**Docker Version:**
N/A

**OS and where are the hosts located? (cloud, bare metal, etc):**
N/A

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Observiced in both a single node and HA environment.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Observed in both cattle and k8s

**Steps to Reproduce:**
1. Create  a bunch of volumes. This script will do it:
```
set -e
for i in `seq 1 10000`; do
    curl -H 'Content-Type: application/json' -X POST -d '{"name": "foo", "driver": "local"}' http://localhost:8080/v2-beta/projects/1a5/volumes
done
```
Try to load the UI

**Results:** 

Leads to the UI not loading, a HTTP 500 error being returned from the /volume?limit=-1 API call and one of two different stack traces in cattle:
```
2016-12-07 23:47:11,630 ERROR [:] [] [] [] [p1830712962-520] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [https://localhost/v2-beta/projects/1a318/volumes]. Error id: [8e5651dc-5008-4173-8b8f-bd6a2a199d1d]. java.nio.BufferOverflowException: null
    at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:189) ~[na:1.8.0_72]
    at java.nio.ByteBuffer.put(ByteBuffer.java:859) ~[na:1.8.0_72]
    at org.mariadb.jdbc.internal.packet.send.SendExecutePrepareStatementPacket.send(SendExecutePrepareStatementPacket.java:105) ~[mariadb-java-client-1.3.4.jar:na]
    at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executePreparedQuery(AbstractQueryProtocol.java:574) ~[mariadb-java-client-1.3.4.jar:na]
    at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:281) ~[mariadb-java-client-1.3.4.jar:na]
    at org.mariadb.jdbc.MariaDbServerPreparedStatement.execute(MariaDbServerPreparedStatement.java:371) ~[mariadb-java-client-1.3.4.jar:na]
    at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar:1.4]
    at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar:1.4]
    at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:194) ~[jooq-3.3.0.jar:na]
    at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:261) ~[jooq-3.3.0.jar:na]
    at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:322) ~[jooq-3.3.0.jar:na]
    at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:330) ~[jooq-3.3.0.jar:na]
    at org.jooq.impl.AbstractResultQuery.fetchInto(AbstractResultQuery.java:656) ~[jooq-3.3.0.jar:na]
    at org.jooq.impl.SelectImpl.fetchInto(SelectImpl.java:2537) ~[jooq-3.3.0.jar:na]
    at io.cattle.platform.core.dao.impl.VolumeDaoImpl.getMountsForVolumes(VolumeDaoImpl.java:242) ~[cattle-iaas-model-0.5.0-SNAPSHOT.jar:na]
    at sun.reflect.GeneratedMethodAccessor2252.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_72]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_72]
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(Reflect
```
or
```
2016-12-07 23:06:13,860 ERROR [:] [] [] [] [p1830712962-401] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [https://localhost/v2-beta/projects/1a318/volumes]. Error id: [fd0e21eb-e21a-4e09-aea9-285c4fb8449b]. java.lang.NegativeArraySizeException: null
    at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.prepare(AbstractQueryProtocol.java:166) ~[mariadb-java-client-1.3.4.jar:na]
    at org.mariadb.jdbc.MariaDbServerPreparedStatement.prepare(MariaDbServerPreparedStatement.java:99) ~[mariadb-java-client-1.3.4.jar:na]
    at org.mariadb.jdbc.MariaDbServerPreparedStatement.<init>(MariaDbServerPreparedStatement.java:87) ~[mariadb-java-client-1.3.4.jar:na]
    at org.mariadb.jdbc.MariaDbConnection.internalPrepareStatement(MariaDbConnection.java:376) ~[mariadb-java-client-1.3.4.jar:na]
    at org.mariadb.jdbc.MariaDbConnection.prepareStatement(MariaDbConnection.java:222) ~[mariadb-java-client-1.3.4.jar:na]
    at org.apache.commons.dbcp.DelegatingConnection.prepareStatement(DelegatingConnection.java:281) ~[commons-dbcp-1.4.jar:1.4]
    at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.prepareStatement(PoolingDataSource.java:313) ~[commons-dbcp-1.4.jar:1.4]
    at sun.reflect.GeneratedMethodAccessor247.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_72]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_72]
    at org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler.invoke(TransactionAwareDataSourceProxy.java:240) ~[spring-jdbc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at com.sun.proxy.$Proxy37.prepareStatement(Unknown Source) ~[na:na]
    at org.jooq.impl.ProviderEnabledConnection.prepareStatement(ProviderEnabledConnection.java:112) ~[jooq-3.3.0.jar:na]
    at org.jooq.impl.SettingsEnabledConnection.prepareStatement(SettingsEnabledConnection.java:76) ~[jooq-3.3.0.jar:na]
    at org.jooq.impl.AbstractResultQuery.prepare(AbstractResultQuery.java:230) ~[jooq-3.3.0.jar:na]
    at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:296) ~[jooq-3.3.0.jar:na]
    at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:330) ~[jooq-3.3.0.jar:na]
    at org.jooq.impl.AbstractResultQuery.fetchInto(AbstractResultQuery.java:656) ~[jooq-3.3.0.jar:na]
    at org.jooq.impl.SelectImpl.fetchInto(SelectImpl.java:2537) ~[jooq-3.3.0.jar:na]
    at io.cattle.platform.core.dao.impl.VolumeDaoImpl.getMountsForVolumes(VolumeDaoImpl.java:242) ~[cattle-iaas-model-0.5.0-SNAPSHOT.jar:na]
    at sun.reflect.GeneratedMethodAccessor2252.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_72]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_72]
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocati
```

**Expected:**
Don't blow up.

**Comment by cjellick** [comment]
High number of volumes is due to this issue: #6826. We need to ultimately address that too

**Comment by soumyalj** [comment]
Tested using 1.2.1-rc1 and 1.2.1-rc1 with having around 10000 volumes in Cattle and Kubernetes environments. The BufferOverflowException and NegativeArraySizeException are not seen in the logs. The UI took longer to load (25s) did not freeze though.
