### ISSUE TITLE
Not able to cleanup Bad volumes (of deleted instance) that are in "inactive" state  from 1.1.4 rancher-server version.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7037]
Rancher Version: Upgrade from 1.1.4 ->  v1.2.1-rc1

On a fresh install of 1.1.4 , have 1 cattle and 1 k8s environment.

On cattle environment , have few services that have local volume. Delete these services.
On K8s environment , create and delete pods.

This will result in volumes relating to the deleted containers still being present in the volumes table in "inactive" state.

```
766 | inactive | /var/lib/kubelet/pods/187193eb-c167-11e6-90fb-02cf6749580b/volumes/kubernetes.io~secret/default-token-zj4b1 | inactive |         10 |
| 767 | inactive | /var/lib/kubelet/pods/187193eb-c167-11e6-90fb-02cf6749580b/etc-hosts                                        | inactive |         10 |
| 768 | inactive | /var/lib/kubelet/pods/187193eb-c167-11e6-90fb-02cf6749580b/containers/testnginx9/8b6f8c3a                   | inactive |         10 |
| 769 | inactive | 18676350455ba870685580aa26b52a6f05a875659f8f146157dfb6a4e3c4c02a                                            | inactive |         10 |
```

Upgrade to v1.2.1-rc1 
Upgrade cattle and k8s environment.

After upgrade , we expect all the volumes in "inactive" state (relating to the deleted containers) to be cleaned up from DB.

Attempt to delete them does not succeed and following exception is seen in logs:

```
2016-12-13 19:52:59,748 ERROR [d49764b2-f110-473b-8854-e889a9b89f64:17827] [volume:630] [volume.deactivate->volume.remove] [] [cutorService-17] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception java.
lang.IllegalStateException: Failed to find state to transition from [inactive] to "done"
        at io.cattle.platform.engine.process.impl.ResourceStatesDefinition.getDoneState(ResourceStatesDefinition.java:73) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]

        at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:111) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.manager.impl.DefaultProcessManager.scheduleProcessInstance(DefaultProcessManager.java:61) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$5.run(DefaultProcessInstanceImpl.java:565) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.object.process.impl.ObjectExecutionExceptionHandler.wrapChainSchedule(ObjectExecutionExceptionHandler.java:27) [cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.scheduleChain(DefaultProcessInstanceImpl.java:574) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.preRunStateCheck(DefaultProcessInstanceImpl.java:256) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:180) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:155) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:114) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:111) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:111) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.manager.impl.DefaultProcessManager.scheduleProcessInstance(DefaultProcessManager.java:61) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.scheduleProcessInstance(DefaultObjectProcessManager.java:50) [cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.scheduleStandardProcess(DefaultObjectProcessManager.java:43) [cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.scheduleStandardProcess(DefaultObjectProcessManager.java:37) [cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.object.process.impl.DefaultObjectProcessManager$2.run(DefaultObjectProcessManager.java:130) [cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.deferred.util.DeferredUtils$3.call(DeferredUtils.java:43) [cattle-framework-deferred-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.deferred.util.DeferredUtils.nest(DeferredUtils.java:53) [cattle-framework-deferred-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.deferred.util.DeferredUtils.nest(DeferredUtils.java:40) [cattle-framework-deferred-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.scheduleStandardProcessAsync(DefaultObjectProcessManager.java:127) [cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.scheduleStandardChainedProcessAsync(DefaultObjectProcessManager.java:146) [cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.core.cleanup.BadDataCleanup$3.doRun(BadDataCleanup.java:94) [cattle-iaas-model-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]

2016-12-13 19:52:59,748 ERROR [:] [] [] [] [ecutorService-6] [i.c.p.task.impl.TaskManagerImpl     ] Task [bad.data] failed java.util.concurrent.RejectedExecutionException: Task io.cattle.platform.core.cleanu
p.BadDataCleanup$3@69e5043 rejected from [ThreadPoolExecutorFactory.SpringJmxEnabledThreadPoolExecutor@4ff620f8 objectName = java.util.concurrent:type=ThreadPoolExecutor,name=PriorityProcessExecutorService,
corePoolSize = 10, maximumPoolSize = 20, keepAliveTimeInMillis = 120000, queue = LinkedBlockingQueue, rejectedExecutionHandler = [ThreadPoolExecutorFactory.CountingRejectedExecutionHandler@6c94af1 rejectedEx
ecutionCount = 1, rejectedExecutionHandler = java.util.concurrent.ThreadPoolExecutor$AbortPolicy@7da295d6]]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047) ~[na:1.8.0_72]
        at fr.xebia.springframework.concurrent.ThreadPoolExecutorFactory$CountingRejectedExecutionHandler.rejectedExecution(ThreadPoolExecutorFactory.java:67) ~[xebia-management-extras-1.2.3.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823) [na:1.8.0_72]
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369) [na:1.8.0_72]
        at io.cattle.platform.core.cleanup.BadDataCleanup.run(BadDataCleanup.java:89) ~[cattle-iaas-model-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.task.impl.TaskManagerImpl$1.doRun(TaskManagerImpl.java:100) ~[cattle-framework-system-task-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_72]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_72]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_72]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_72]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
```

**Comment by sangeethah** [comment]
Tested with upgrade from 1.1.4 -> v1.2.1-rc2

Deletion of  Bad volumes (of deleted instance) that are in "inactive" state now succeeds. 
Exception mentioned in the bug is not seen anymore.

bad.data.batch.size is set to 1000  by default. But i see only 100 of them being deleted every time the  cleanup thread is executed.

Also I dont see "invalid" volumes from cattle environment being removed.
