### ISSUE TITLE
Exception when deleting storagepool when hosts are deleted.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7049]
Server version - v1.2.1-rc1

Steps to reproduce the problem:
Create a K8s environment.
Delete hosts in the k8s environment.
Deleted environment.

Following exception seen repeatedly in logs when trying to delete storage pool:
```
2016-12-14 04:35:13,148 ERROR [81bbe62d-570f-4e65-b100-53e58b0a583b:33510] [storagePool:4] [storagepool.purge] [] [cutorService-15] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.engine.manager.ProcessNotFoundException: Failed to find ProcessDefinition for [storagepoolhostmap.deactivate]
	at io.cattle.platform.engine.manager.impl.DefaultProcessManager.createProcessInstance(DefaultProcessManager.java:78) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.manager.impl.DefaultProcessManager.createProcessInstance(DefaultProcessManager.java:54) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.createProcessInstance(DefaultObjectProcessManager.java:77) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.executeStandardProcess(DefaultObjectProcessManager.java:31) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.common.handler.AbstractObjectProcessLogic.deactivate(AbstractObjectProcessLogic.java:35) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.storagepool.StoragePoolPurge.handle(StoragePoolPurge.java:46) ~[cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:448) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:399) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:393) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:393) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:495) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:326) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:243) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:240) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:182) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:155) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:114) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:111) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:111) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl.processExecuteWithLock(ProcessInstanceDispatcherImpl.java:98) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl$1$1.doWithLockNoResult(ProcessInstanceDispatcherImpl.java:71) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$4.doWithLock(AbstractLockManagerImpl.java:50) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:25) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:47) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl$1.doRun(ProcessInstanceDispatcherImpl.java:68) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
```

```
2016-12-14 02:00:47,062 ERROR [7cca68ea-132c-4a92-b809-39acbbba3325:33510] [storagePool:4] [storagepool.purge] [] [cutorService-19] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.engine.manager.ProcessNotFoundException: Failed to find ProcessDefinition for [storagepoolhostmap.deactivate]
2016-12-14 02:01:02,297 ERROR [ca6d1cb2-1fbd-49ae-bf9c-4212b47e69e6:33510] [storagePool:4] [storagepool.purge] [] [ecutorService-3] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.engine.manager.ProcessNotFoundException: Failed to find ProcessDefinition for [storagepoolhostmap.deactivate]
2016-12-14 02:01:18,160 ERROR [232cd620-c4b9-4f5a-99b9-88b71c8f8e64:33510] [storagePool:4] [storagepool.purge] [] [ecutorService-5] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.engine.manager.ProcessNotFoundException: Failed to find ProcessDefinition for [storagepoolhostmap.deactivate]
2016-12-14 02:01:34,328 ERROR [60a4d1c3-17b4-47b3-9f8a-ac9a5f023ceb:33510] [storagePool:4] [storagepool.purge] [] [cutorService-12] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.engine.manager.ProcessNotFoundException: Failed to find ProcessDefinition for [storagepoolhostmap.deactivate]
2016-12-14 02:01:48,664 ERROR [4294b6d4-bece-486b-bd6b-8f989c5d18a7:34463] [storagePool:5] [storagepool.purge] [] [cutorService-17] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.engine.manager.ProcessNotFoundException: Failed to find ProcessDefinition for [storagepoolhostmap.deactivate]
2016-12-14 02:01:48,754 ERROR [83a8ac1f-4318-41fd-b60f-a8383c6e656d:34464] [storagePool:6] [storagepool.purge] [] [cutorService-10] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.engine.manager.ProcessNotFoundException: Failed to find ProcessDefinition for [storagepoolhostmap.deactivate]
2016-12-14 02:01:50,420 ERROR [0ac6908d-5848-46fe-b804-c59b4a230a01:33510] [storagePool:4] [storagepool.purge] [] [cutorService-10] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.engine.manager.ProcessNotFoundException: Failed to find ProcessDefinition for [storagepoolhostmap.deactivate]
2016-12-14 02:02:04,499 ERROR [612a0f33-da7e-4cd9-bac9-4c3d85f6fab9:34463] [storagePool:5] [storagepool.purge] [] [cutorService-16] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.engine.manager.ProcessNotFoundException: Failed to find ProcessDefinition for [storagepoolhostmap.deactivate]
2016-12-14 02:02:04,499 ERROR [f2d7fef8-3c48-4c97-ba34-5b0563f68c56:34464] [storagePool:6] [storagepool.purge] [] [cutorService-13] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.engine.manager.ProcessNotFoundException: Failed to find ProcessDefinition for [storagepoolhostmap.deactivate]
2016-12-14 02:02:08,516 ERROR [6d1074e9-df4a-4484-8d9c-c30f6beb7e04:33510] [storagePool:4] [storagepool.purge] [] [ecutorService-3] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.engine.manager.ProcessNotFoundException: Failed to find ProcessDefinition for [storagepoolhostmap.deactivate]
2016-12-14 02:02:20,557 ERROR [740d728e-4863-4013-b760-9bd51d76acad:34464] [storagePool:6] [storagepool.purge] [] [cutorService-15] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.engine.manager.ProcessNotFoundException: Failed to find ProcessDefinition for [storagepoolhostmap.deactivate]
2016-12-14 02:02:20,559 ERROR [5e3849d3-a249-469c-9d5c-8cad20caa54f:34463] [storagePool:5] [storagepool.purge] [] [cutorService-13] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.engine.manager.ProcessNotFoundException: Failed to find ProcessDefinition for [storagepoolhostmap.deactivate]
2016-12-14 02:02:26,558 ERROR [d7dc3c45-198c-43a7-9a52-21528a55084d:33510] [storagePool:4] [storagepool.purge] [] [cutorService-15] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.engine.manager.ProcessNotFoundException: Failed to find ProcessDefinition for [storagepoolhostmap.deactivate]
2016-12-14 02:02:36,686 ERROR [6c2ce2d6-83bf-444c-a1d5-87ea1e52ad00:34464] [storagePool:6] [storagepool.purge] [] [ecutorService-1] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.engine.manager.ProcessNotFoundException: Failed to find ProcessDefinition for [storagepoolhostmap.deactivate]
2016-12-14 02:02:36,703 ERROR [ff75df94-cac5-4157-9964-9aee0817e4ce:34463] [storagePool:5] [storagepool.purge] [] [ecutorService-4] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.engine.manager.ProcessNotFoundException: Failed to find ProcessDefinition for [storagepoolhostmap.deactivate]
```

```
mysql> select id,name,state from storage_pool;
+----+-----------------------------------------------------------+---------+
| id | name                                                      | state   |
+----+-----------------------------------------------------------+---------+
|  1 | sangeev121rc1-10acre-2.c.rancher-qa.internal Storage Pool | active  |
|  2 | sangeev121rc1-10acre-3.c.rancher-qa.internal Storage Pool | active  |
|  3 | sangeev121rc1-10acre-1.c.rancher-qa.internal Storage Pool | active  |
|  4 | test-839954.localdomain Storage Pool                      | purging |
|  5 | test-956785.localdomain Storage Pool                      | purging |
|  6 | test-704374.localdomain Storage Pool                      | purging |
|  7 | test-676763.localdomain Storage Pool                      | active  |
|  8 | test-802734.localdomain Storage Pool                      | active  |
|  9 | test-96626.localdomain Storage Pool                       | active  |
+----+-----------------------------------------------------------+---------+
9 rows in set (0.00 sec)
```

**Comment by sangeethah** [comment]
Tested with Server version - v1.2.1-rc2

Exception reported in the bug is not seen anymore.
Storage pool gets to "purged" state successfully.
```
  7 | test-425208.localdomain Storage Pool                  | purged |
|  8 | test-381115.localdomain Storage Pool                  | purged |
|  9 | test-120764.localdomain Storage Pool                  | purged |

```
