### ISSUE TITLE
Failure to run HA 3 nodes (1.2.1) on RancherOS, AWS

### ISSUE THREAD

**Issue by Dmitry1987** [rancher/rancher#7125]
**Rancher Version:**
1.2.1
**Docker Version:**
1.12

**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS , AWS, default latest AMI  , Oregon

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Trying 1.2.1  HA setup with external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
none 

**Steps to Reproduce:**
Run 3 RancherOS  t2.medium instances in Oregon. Run 1 RDS t2.medium.  Follow documentation steps (created mysql database + cattle user).  Run the "docker run ..." with all needed params as in docs. (sec groups open, verified with telnet access to needed ports)

**Results:** 
Rancher master containers always restart and I see this error which causes it:

_2016-12-19 10:16:02,914 ERROR   [main] [ConsoleStatus] Startup Failed [303228ms] org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase-core' defined in URL [jar:file:/usr/share/cattle/25c9f1ae8bd5f53e3de69ecd95cf203f/WEB-INF/lib/cattle-app-config-0.5.0-SNAPSHOT.jar!/META-INF/cattle/system/spring-system-context.xml]: Invocation of init method failed; nested exception is liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by 382c6d3c0e68 (fe80:0:0:0:42:acff:fe11:2%eth0) since 12/18/16 4:25 PM_

-----------------------

In mysql I see 90 tables in "cattle" database, so schema was created, machines had access.

**Comment by Dmitry1987** [comment]
Then, we just wiped all this setup (drop database, remove containers), and tried again. This time have this result:

1 master that was launched first, created the DB schema, and got stuck somewhere, like you see in log last lines here:

>time="2016-12-19T10:53:35Z" level=info msg="Using catalog community=https://git.rancher.io/community-catalog.git"
time="2016-12-19T10:53:36Z" level=error msg="Failed to pull the catalog from git repo https://git.rancher.io/rancher-catalog.git, error: exit status 1"
time="2016-12-19T10:53:36Z" level=error msg="Failed to pull the catalog from git repo https://git.rancher.io/community-catalog.git, error: exit status 1"
time="2016-12-19T10:53:37Z" level=info msg="Setting log level" logLevel=info
time="2016-12-19T10:53:37Z" level=info msg="Starting go-machine-service..." gitcommit=v0.34.1
time="2016-12-19T10:53:37Z" level=info msg="Waiting for handler registration (1/2)"
time="2016-12-19T10:53:37Z" level=info msg="Initializing event router" workerCount=10
time="2016-12-19T10:53:37Z" level=info msg="Connection established"
time="2016-12-19T10:53:37Z" level=info msg="Starting websocket pings"
time="2016-12-19T10:53:38Z" level=info msg="Initializing event router" workerCount=10
time="2016-12-19T10:53:38Z" level=info msg="Connection established"
time="2016-12-19T10:53:38Z" level=info msg="Starting websocket pings"
time="2016-12-19T10:53:38Z" level=info msg="Waiting for handler registration (2/2)"
time="2016-12-19T10:53:38Z" level=info msg="Initializing event router" workerCount=10
time="2016-12-19T10:53:38Z" level=info msg="Connection established"
time="2016-12-19T10:53:38Z" level=info msg="Starting websocket pings"
time="2016-12-19T10:53:39Z" level=info msg="Installing builtin drivers"
time="2016-12-19T10:53:39Z" level=info msg="Downloading all drivers"
time="2016-12-19T10:53:39Z" level=info msg="Copying /var/lib/cattle/machine-drivers/1f7058341420e2f525168052818c3f819ff78e9ca5f57d5a650a049bcd5945e9-docker-machine-driver-packet => /usr/local/bin/docker-machine-driver-packet"
time="2016-12-19T10:53:39Z" level=info msg="Done downloading all drivers"
time="2016-12-19T10:58:36Z" level=info msg="Refresh for this catalog library is already in process, skipping"
time="2016-12-19T11:03:36Z" level=info msg="Refresh for this catalog library is already in process, skipping"
time="2016-12-19T11:03:37Z" level=info msg="Refresh for this catalog community is already in process, skipping"


the other 2 machines were launched with same command, just their IPs specified (internal IPs, access verified between all, and between them and DB), and they get to this point:


> DEFAULT_CATTLE_RANCHER_CLI_DARWIN_URL=https://releases.rancher.com/cli/v0.4.1/rancher-darwin-amd64-v0.4.1.tar.gz
DEFAULT_CATTLE_RANCHER_CLI_LINUX_URL=https://releases.rancher.com/cli/v0.4.1/rancher-linux-amd64-v0.4.1.tar.gz
DEFAULT_CATTLE_RANCHER_CLI_WINDOWS_URL=https://releases.rancher.com/cli/v0.4.1/rancher-windows-386-v0.4.1.zip
DEFAULT_CATTLE_RANCHER_COMPOSE_DARWIN_URL=https://releases.rancher.com/compose/v0.12.1/rancher-compose-darwin-amd64-v0.12.1.tar.gz
DEFAULT_CATTLE_RANCHER_COMPOSE_LINUX_URL=https://releases.rancher.com/compose/v0.12.1/rancher-compose-linux-amd64-v0.12.1.tar.gz
DEFAULT_CATTLE_RANCHER_COMPOSE_WINDOWS_URL=https://releases.rancher.com/compose/v0.12.1/rancher-compose-windows-386-v0.12.1.zip
DEFAULT_CATTLE_TRAEFIK_EXECUTE=true
11:03:04.697 [main] WARN  o.e.jetty.security.SecurityHandler - ServletContext@o.e.j.w.WebAppContext@6a4f787b{/,file:/usr/share/cattle/25c9f1ae8bd5f53e3de69ecd95cf203f/,STARTING}{file:/usr/share/cattle/25c9f1ae8bd5f53e3de69ecd95cf203f/} has uncovered http methods for path: /
11:03:05.623 [main] INFO  ConsoleStatus - [1/6] [0ms] [0ms] Loading config-bootstrap
11:03:05.709 [main] INFO  ConsoleStatus - [2/6] [86ms] [86ms] Loading base-config
11:03:05.884 [main] INFO  ConsoleStatus - [3/6] [261ms] [174ms] Loading config
11:03:05.891 [main] INFO  ConsoleStatus - [4/6] [268ms] [7ms] Starting config-bootstrap
11:03:06.019 [main] ERROR i.c.p.a.sources.LazyJDBCSource - Failed to get connection to database, will retry for 5 minutes
org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Could not connect to address=(host=rancher-production.c7wtacx9psly.us-west-2.rds.amazonaws.com)(port=3306)(type=master) : rancher-production.c7wtacx9psly.us-west-2.rds.amazonaws.com)
        at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549) ~[commons-dbcp-1.4.jar:1.4]
        at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388) ~[commons-dbcp-1.4.jar:1.4]
        at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044) ~[commons-dbcp-1.4.jar:1.4]
        at io.cattle.platform.archaius.sources.LazyJDBCSource.checkInitial(LazyJDBCSource.java:50) [cattle-framework-archaius-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.archaius.sources.LazyJDBCSource.poll(LazyJDBCSource.java:34) [cattle-framework-archaius-0.5.0-SNAPSHOT.jar:na]
        at com.netflix.config.AbstractPollingScheduler$1.run(AbstractPollingScheduler.java:163) [archaius-core-0.5.14.jar:na]
        at io.cattle.platform.archaius.polling.RefreshableFixedDelayPollingScheduler.refresh(RefreshableFixedDelayPollingScheduler.java:34) [cattle-framework-archaius-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.archaius.startup.ArchaiusStartup.load(ArchaiusStartup.java:91) [cattle-iaas-archaius-management-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.archaius.startup.ArchaiusStartup.start(ArchaiusStartup.java:68) [cattle-iaas-archaius-management-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.extension.spring.BackgroundStart.run(BackgroundStart.java:63) [cattle-framework-extension-spring-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet$1.with(DefaultModuleDefinitionSet.java:139) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:348) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:358) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:333) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.runHookInContexts(DefaultModuleDefinitionSet.java:131) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.startContexts(DefaultModuleDefinitionSet.java:123) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.load(DefaultModuleDefinitionSet.java:100) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.factory.ModuleBasedContextFactory.loadModules(ModuleBasedContextFactory.java:37) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.init(CloudStackSpringContext.java:75) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_72]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_72]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_72]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_72]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1706) [spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1645) [spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574) [spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) [spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) [spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) [spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) [spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) [spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) [spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:776) [spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861) [spring-context-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541) [spring-context-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.loadContext(DefaultModuleDefinitionSet.java:184) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.loadRootContext(DefaultModuleDefinitionSet.java:117) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.load(DefaultModuleDefinitionSet.java:87) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.factory.ModuleBasedContextFactory.loadModules(ModuleBasedContextFactory.java:37) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.init(CloudStackSpringContext.java:75) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.<init>(CloudStackSpringContext.java:56) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.context.SpringContext.<init>(SpringContext.java:11) [cattle-iaas-system-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.context.WebContextLoaderListener.constructCloudStackSpringContext(WebContextLoaderListener.java:15) [cattle-iaas-system-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.spring.module.web.CloudStackContextLoaderListener.contextInitialized(CloudStackContextLoaderListener.java:51) [cattle-framework-spring-module-0.5.0-SNAPSHOT.jar:na]
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349) [jetty-webapp-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342) [jetty-webapp-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505) [jetty-webapp-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.Server.start(Server.java:387) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.Server.doStart(Server.java:354) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
        at io.cattle.platform.launcher.jetty.Main.main(Main.java:146) [25c9f1ae8bd5f53e3de69ecd95cf203f/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_72]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_72]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_72]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_72]
        at io.cattle.platform.launcher.Main.run(Main.java:188) [25c9f1ae8bd5f53e3de69ecd95cf203f/:na]
        at io.cattle.platform.launcher.Main.main(Main.java:251) [25c9f1ae8bd5f53e3de69ecd95cf203f/:na]
Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=rancher-production.c7wtacx9psly.us-west-2.rds.amazonaws.com)(port=3306)(type=master) : rancher-production.c7wtacx9psly.us-west-2.rds.amazonaws.com
        at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:123) ~[mariadb-java-client-1.3.4.jar:na]
        at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69) ~[mariadb-java-client-1.3.4.jar:na]
        at org.mariadb.jdbc.Driver.connect(Driver.java:110) ~[mariadb-java-client-1.3.4.jar:na]
        at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
        at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582) ~[commons-dbcp-1.4.jar:1.4]
        at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556) ~[commons-dbcp-1.4.jar:1.4]
        at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545) ~[commons-dbcp-1.4.jar:1.4]
        ... 65 common frames omitted
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect to address=(host=rancher-production.c7wtacx9psly.us-west-2.rds.amazonaws.com)(port=3306)(type=master) : rancher-production.c7wtacx9psly.us-west-2.rds.amazonaws.com
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:674) ~[mariadb-java-client-1.3.4.jar:na]
        at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:580) ~[mariadb-java-client-1.3.4.jar:na]
        at org.mariadb.jdbc.Driver.connect(Driver.java:105) ~[mariadb-java-client-1.3.4.jar:na]
        ... 69 common frames omitted
Caused by: java.net.UnknownHostException: rancher-production.c7wtacx9psly.us-west-2.rds.amazonaws.com
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_72]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_72]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_72]
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:344) ~[mariadb-java-client-1.3.4.jar:na]
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:669) ~[mariadb-java-client-1.3.4.jar:na]
        ... 71 common frames omitted
11:03:07.020 [main] ERROR i.c.p.a.sources.LazyJDBCSource - Failed to get connection to database, will retry for 5 minutes
11:03:08.021 [main] ERROR i.c.p.a.sources.LazyJDBCSource - Failed to get connection to database, will retry for 5 minutes
11:03:09.022 [main] ERROR i.c.p.a.sources.LazyJDBCSource - Failed to get connection to database, will retry for 5 minutes
11:03:10.023 [main] ERROR i.c.p.a.sources.LazyJDBCSource - Failed to get connection to database, will retry for 5 minutes
11:03:11.024 [main] ERROR i.c.p.a.sources.LazyJDBCSource - Failed to get connection to database, will retry for 5 minutes
11:03:12.025 [main] ERROR i.c.p.a.sources.LazyJDBCSource - Failed to get connection to database, will retry for 5 minutes
11:03:13.026 [main] ERROR i.c.p.a.sources.LazyJDBCSource - Failed to get connection to database, will retry for 5 minutes
11:03:14.027 [main] ERROR i.c.p.a.sources.LazyJDBCSource - Failed to get connection to database, will retry for 5 minutes
11:03:15.028 [main] ERROR i.c.p.a.sources.LazyJDBCSource - Failed to get connection to database, will retry for 5 minutes


Any advice appreciated! :)

**Comment by vincent99** [comment]
The locked database means you had a half completed upgrade for that database; http://docs.rancher.com/rancher/v1.2/en/faqs/server/

And the other two servers can't reach the RDS DB... Check it'ss security group.

**Comment by aemneina** [comment]
Closing due to inactivity.
