### ISSUE TITLE
can not switch to a rancher environment v1.2 (forcing us to authentication page)

### ISSUE THREAD

**Issue by mfar-bcgdv** [rancher/rancher#7135]
**Rancher Version:1.2**

**Docker Version:1.12.2, build bb80604**

**OS and where are the hosts located? (cloud, bare metal, etc): AWS ubuntu 16.04**

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB): single node rancher**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos): Cattle**

**Steps to Reproduce: one of our rancher environments frozen on 'initializing' status, when we want to switch to that env, it keep forcing us to authenticate(we using github for authentication).
I tried to Deactivate/activate it couple times, didn't help.
I can use 'View in Api' option for that env and pull it's setting, however could not switch to it**

**Results:can't switch to that env, other environments working just fine** 

**Expected:**

here what i found in rancher logs":
"rancher_1                | 2016-12-19 20:35:04,750 ERROR [:] [] [] [] [tp1830712962-80] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [https://example.com/v2-beta/projects/1a33/volumes]. Error id: [3ad518cf-59cf-460d-a9f0-07c34fc61d6d]. java.nio.BufferOverflowException: null
rancher_1                | 	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:189) ~[na:1.8.0_72]
rancher_1                | 	at java.nio.ByteBuffer.put(ByteBuffer.java:859) ~[na:1.8.0_72]
rancher_1                | 	at org.mariadb.jdbc.internal.packet.send.SendExecutePrepareStatementPacket.send(SendExecutePrepareStatementPacket.java:105) ~[mariadb-java-client-1.3.4.jar:na]
rancher_1                | 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executePreparedQuery(AbstractQueryProtocol.java:574) ~[mariadb-java-client-1.3.4.jar:na]
rancher_1                | 	at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:281) ~[mariadb-java-client-1.3.4.jar:na]
rancher_1                | 	at org.mariadb.jdbc.MariaDbServerPreparedStatement.execute(MariaDbServerPreparedStatement.java:371) ~[mariadb-java-client-1.3.4.jar:na]
rancher_1                | 	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar:1.4]
rancher_1                | 	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar:1.4]
rancher_1                | 	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:194) ~[jooq-3.3.0.jar:na]
rancher_1                | 	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:261) ~[jooq-3.3.0.jar:na]
rancher_1                | 	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:322) ~[jooq-3.3.0.jar:na]
rancher_1                | 	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:330) ~[jooq-3.3.0.jar:na]
rancher_1                | 	at org.jooq.impl.AbstractResultQuery.fetchInto(AbstractResultQuery.java:656) ~[jooq-3.3.0.jar:na]
rancher_1                | 	at org.jooq.impl.SelectImpl.fetchInto(SelectImpl.java:2537) ~[jooq-3.3.0.jar:na]
rancher_1                | 	at io.cattle.platform.core.dao.impl.VolumeDaoImpl.getMountsForVolumes(VolumeDaoImpl.java:242) ~[cattle-iaas-model-0.5.0-SNAPSHOT.jar:na]
rancher_1                | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_72]
rancher_1                | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_72]
rancher_1                | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_72]
rancher_1                | 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_72]
rancher_1                | 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
rancher_1                | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
rancher_1                | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
rancher_1                | 	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.3.2.RELEASE.jar:4.3.2.RELEASE]
rancher_1                | 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:280) ~[spring-tx-4.3.2.RELEASE.jar:4.3.2.RELEASE]
rancher_1                | 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.2.RELEASE.jar:4.3.2.RELEASE]
rancher_1                | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
rancher_1                | 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
rancher_1                | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
rancher_1                | 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
rancher_1                | 	at com.sun.proxy.$Proxy44.getMountsForVolumes(Unknown Source) ~[na:na]
rancher_1                | 	at io.cattle.platform.iaas.api.filter.volume.VolumeOutputFilter.newObject(VolumeOutputFilter.java:62) ~[cattle-iaas-api-logic-0.5.0-SNAPSHOT.jar:na]
rancher_1                | 	at io.cattle.platform.iaas.api.filter.volume.VolumeOutputFilter.newObject(VolumeOutputFilter.java:20) ~[cattle-iaas-api-logic-0.5.0-SNAPSHOT.jar:na]
rancher_1                | 	at io.cattle.platform.iaas.api.filter.common.CachedOutputFilter.getCached(CachedOutputFilter.java:24) ~[cattle-iaas-api-logic-0.5.0-SNAPSHOT.jar:na]
rancher_1                | 	at io.cattle.platform.iaas.api.filter.volume.VolumeOutputFilter.filter(VolumeOutputFilter.java:44) ~[cattle-iaas-api-logic-0.5.0-SNAPSHOT.jar:na]
rancher_1                | 	at io.github.ibuildthecloud.gdapi.response.impl.ResourceOutputFilterChain.filter(ResourceOutputFilterChain.java:23) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
rancher_1                | 	at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.convertResponse(AbstractBaseResourceManager.java:200) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
rancher_1                | 	at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.createCollection(AbstractBaseResourceManager.java:242) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
rancher_1                | 	at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.convertResponse(AbstractBaseResourceManager.java:191) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
rancher_1                | 	at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.convertResponse(FilteredResourceManager.java:71) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
rancher_1                | 	at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.convertResponse(FilteredResourceManager.java:71) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
rancher_1                | 	at io.github.ibuildthecloud.gdapi.response.ResponseObjectConverter.handle(ResponseObjectConverter.java:35) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
rancher_1                | 	at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:99) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
rancher_1                | 	at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:95) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
rancher_1                | 	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
rancher_1                | 	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
rancher_1                | 	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
rancher_1                | 	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
rancher_1                | 	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
rancher_1                | 	at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:88) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
rancher_1                | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
rancher_1                | 	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
rancher_1                | 	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
rancher_1                | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
rancher_1                | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
rancher_1                | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
rancher_1                | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [jetty-security-9.2.11.v20150529.jar:9.2.11.v20150529]
rancher_1                | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
rancher_1                | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
rancher_1                | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
rancher_1                | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
rancher_1                | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
rancher_1                | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
rancher_1                | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
rancher_1                | 	at org.eclipse.jetty.server.Server.handle(Server.java:499) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
rancher_1                | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
rancher_1                | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
rancher_1                | 	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
rancher_1                | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
rancher_1                | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
rancher_1                | 	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]"

**Comment by deniseschannon** [comment]
If your DB has a significant amount of volumes (in any state), it could have caused your UI to freeze up. Can you upgrade to 1.2.1? We have addressed 2 major UI issues and added in a cleanup script for unused volumes.

**Comment by mfar-bcgdv** [comment]
sure, will give it try now

**Comment by mfar-bcgdv** [comment]
after upgrade it finally opened up that environment UI, although overall rancher is running much slower and that env's UI showed up after ~30 secs.
i'm seeing lots of errors related  to cattle db now, are they expected? : 
"rancher_1                | 2016-12-19 22:34:10,932 ERROR [:] [] [] [] [ecutorService-3] [i.c.p.core.cleanup.TableCleanup     ] Skipped "cattle"."instance" where id in [13371, 14593, 14601, 14605, 14609, 28873, 28879, 28880, 28881, 28882, 28883, 28884, 28885, 28886, 28887, 28888, 28889, 28890, 30, 544, 551, 553, 554, 555, 556, 557, 558, 560, 562, 563, 564, 566, 568, 569, 570, 572, 574, 575, 576, 577, 580, 581, 582, 583, 584, 586, 587, 588, 589, 590, 593, 594, 595, 596, 597, 598, 600, 601, 602, 603, 604, 607, 608, 609, 610, 611, 613, 614, 615, 616, 617, 619, 620, 621, 622, 623, 625, 626, 627, 628, 629, 631, 632, 633, 634, 636, 638, 640, 643, 648, 682, 1682, 1683, 1684, 1685, 1710, 1711, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1723, 1725, 1726, 1727, 1728, 1730, 1732, 1733, 1734, 1735, 1736, 1766, 1767, 1768, 1769, 1799, 12828, 12831, 12835, 12838, 12841, 12872, 12873, 12874, 12875, 12887, 12888, 12889, 12890, 12891, 12893, 12894, 12895, 12896, 12897, 12899, 12900, 12901, 12902, 12903, 12914, 12915, 12917, 12918, 12920, 12937, 12942, 12943, 12944, 12945, 12946, 12948, 12950, 12951, 12952, 12954, 12956, 12957, 12958, 12959, 12960, 12962, 12963, 12964, 12965, 12966, 12968, 12969, 12970, 12971, 12972, 12973, 12974, 12975, 12976, 12980, 12983, 12984, 12985, 12986, 12987, 13000, 13023, 13026, 13067, 13074, 13075, 13076, 13077, 13078, 13080, 13082, 13083, 13084, 13085, 13087, 13088, 13089, 13090, 13092, 13093, 13094, 13095, 13096, 13097, 13099, 13104, 13105, 13106, 13107, 13108, 13112, 13113, 13114, 13115, 13116, 13118, 13119, 13120, 13121, 13122, 13124, 13125, 13126, 13127, 13128, 13131, 13133, 13134, 13135, 13140, 13141, 13183, 13243, 13244, 13245, 13246, 13247, 13253, 13254, 13255, 13256, 13257, 13267, 13278, 13279, 13281, 13285, 13323, 13324, 13325, 13326, 13327, 13330, 13331, 13333, 13334, 13335, 13336, 13337, 13338, 13339, 13340, 13341, 13342, 13343, 13344, 13345, 13346, 13347, 13348, 13349, 13350, 13351, 13352, 13353, 13354, 13355, 13356, 13357, 13359, 13360, 13361, 13362, 13363, 13364, 13365, 13366, 13367, 13368, 13369, 13370, 13372, 13373, 13374, 13375, 13376, 13377, 13378, 13379, 13380, 13381, 13382, 13383, 13384, 13385, 13386, 13387, 13388, 13389, 13390, 13391, 13392, 13393, 13394, 13395, 13398, 13407, 13408, 13409, 13410, 13411, 13412, 13413, 13414, 13415, 13416, 13417, 13418, 13419, 13421, 13422, 13429, 13430, 13431, 13432, 13433, 13434, 13435, 13436, 13437, 13438, 13439, 13440, 13441, 13442, 13443, 13444, 13445, 13446, 13447, 13448, 13449, 13450, 13451, 13452, 13453, 13454, 13455, 13456, 13457, 13458, 13459, 13460, 13461, 13462, 13463, 13464, 13465, 13466, 13467, 13468, 13469, 13470, 13471, 13472, 13473, 13474, 13475, 13476, 13477, 13478, 13479, 13480, 13481, 13482, 13483, 13484, 13485, 13486, 13487, 13488, 13489, 13490, 13491, 13492, 13493, 13494, 13495, 13496, 13497, 13498, 13499, 13500, 13501, 13502, 13503, 13504, 13505, 13506, 13507, 13508, 13509, 13510, 13511, 13512, 13513, 13514, 13515, 13516, 13517, 13518, 13519, 13520, 13521, 13522, 13523, 13524, 13525, 13526, 13527, 13528, 13529, 13530, 13531, 13532, 13533, 13534, 13535, 13536, 13537, 13538, 13539, 13540, 13541, 13542, 13543, 13544, 13545, 13546, 13547, 13548, 13550, 13551, 13552, 13553, 13554, 13555, 13556, 13557, 13558, 13559, 13560, 13561, 13568, 13569, 13570, 13571, 13572, 13573, 13574, 13581, 13613, 13614, 13615, 13616, 13617, 13618, 13619, 13621, 13622, 13629, 13633, 13635, 13636, 13637, 13638, 13639, 13645, 13646, 13647, 13648, 13649, 13650, 13653, 13654, 13655, 13656, 13658, 13660, 13661, 13662, 13663, 13664, 13703, 13704, 13705, 13706, 13709, 13730, 14525, 14591, 14600, 14604, 14608, 14616, 14635, 14655, 14656, 14657, 14658, 14659, 14660, 14668, 17282, 23044, 28878]"

**Comment by mfar-bcgdv** [comment]
is there any guidance to downgrade rancher to v1.1?

**Comment by deniseschannon** [comment]
@mfar-bcgdv We added cleanup code in 1.2.1, so it might take a bit for your setup to be cleaned up as we don't clean it all instantly. 

For downgrades, if you backed up your database (as we recommend), you can just point to the backed up database. Otherwise, there is no option to downgrade from 1.2 to 1.1 using the same DB from 1.2.

**Comment by aemneina** [comment]
Closing due to inactivity. Cleanup code has been improved in subsequent releases.
