### ISSUE TITLE
Failed to find instance to delegate to for agent

### ISSUE THREAD

**Issue by willseward** [rancher/rancher#7166]
**Rancher Version:** 1.2.1

**Docker Version:** 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 16.04, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** External Db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

Not quite sure. It pops up in my error log about once a minute or so...

**Results:** 

```
Dec 21 08:48:35 6e325bfbf6f2 rancher-server info 2016-12-21 14:48:35,977 ERROR [:] [] [] [] [ecutorService-1] [i.c.p.agent.impl.AgentLocatorImpl   ] Failed to find instance to delegate to for agent [16] uri [delegate:///?vnetId=4&networkServiceProviderId=1] 
Dec 21 08:48:36 6e325bfbf6f2 rancher-server info 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199) ~[guava-15.0.jar:na]
Dec 21 08:48:36 6e325bfbf6f2 rancher-server info 2016-12-21 14:48:35,979 ERROR [:] [] [] [] [ecutorService-1] [.p.c.v.i.ConfigItemStatusManagerImpl] Error updating item(s) [configscripts, services, agent-instance-scripts, monit, agent-instance-startup, node-services, ipsec] on [agent:16] com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Delegate [delegate:///?vnetId=4&networkServiceProviderId=1] has no instance associated
Dec 21 08:48:36 6e325bfbf6f2 rancher-server info 	at com.google.common.cache.LocalCache.get(LocalCache.java:3932) ~[guava-15.0.jar:na]
Dec 21 08:48:36 6e325bfbf6f2 rancher-server info 	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
Dec 21 08:48:36 6e325bfbf6f2 rancher-server info 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
Dec 21 08:48:36 6e325bfbf6f2 rancher-server info 	at io.cattle.platform.agent.impl.AgentLocatorImpl.getAgentForDelegate(AgentLocatorImpl.java:132) ~[cattle-iaas-agent-0.5.0-SNAPSHOT.jar:na]
Dec 21 08:48:36 6e325bfbf6f2 rancher-server info 	at io.cattle.platform.agent.impl.AgentLocatorImpl$1.load(AgentLocatorImpl.java:52) ~[cattle-iaas-agent-0.5.0-SNAPSHOT.jar:na]
Dec 21 08:48:36 6e325bfbf6f2 rancher-server info 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278) ~[guava-15.0.jar:na]
Dec 21 08:48:36 6e325bfbf6f2 rancher-server info 	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
Dec 21 08:48:36 6e325bfbf6f2 rancher-server info 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_72]
Dec 21 08:48:36 6e325bfbf6f2 rancher-server info 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
Dec 21 08:48:36 6e325bfbf6f2 rancher-server info Caused by: java.lang.IllegalStateException: Delegate [delegate:///?vnetId=4&networkServiceProviderId=1] has no instance associated
Dec 21 08:48:36 6e325bfbf6f2 rancher-server info 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193) ~[guava-15.0.jar:na]
Dec 21 08:48:51 6e325bfbf6f2 rancher-server info 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199) ~[guava-15.0.jar:na]
Dec 21 08:48:51 6e325bfbf6f2 rancher-server info 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3936) ~[guava-15.0.jar:na]
Dec 21 08:48:51 6e325bfbf6f2 rancher-server info 	at io.cattle.platform.configitem.version.impl.ConfigUpdatePublisher.call(ConfigUpdatePublisher.java:327) [cattle-config-item-common-0.5.0-SNAPSHOT.jar:na]
Dec 21 08:48:51 6e325bfbf6f2 rancher-server info 	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
Dec 21 08:48:51 6e325bfbf6f2 rancher-server info 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_72]
Dec 21 08:48:51 6e325bfbf6f2 rancher-server info 	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
Dec 21 08:48:51 6e325bfbf6f2 rancher-server info 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278) ~[guava-15.0.jar:na]
```

**Expected:**

This error shouldn't appear.

**Comment by Ilya-Kuchaev** [comment]
+1

**Comment by daxingplay** [comment]
Same issue here with rancher 1.5.0 and docker 1.12.6, Googled a lot but no solutions found.

I've ran into this problem since rancher 1.2.x, after upgrading all way along, the problem was not fixed. I'm using rancher NSF driver for volumes, there are some errors about removing file system error as well.

These errors keep spamming my rancher-server logs and cause my server high load.

```
2017-03-11 15:05:54,954 ERROR [:] [] [] [] [ecutorService-9] [i.c.p.agent.impl.AgentLocatorImpl   ] Failed to find instance to delegate to for agent [19036] uri [delegate:///?vnetId=8&networkServiceProviderId=3]
2017-03-11 15:05:54,958 ERROR [:] [] [] [] [ecutorService-9] [.p.c.v.i.ConfigItemStatusManagerImpl] Error updating item(s) [agent-instance-startup] on [agent:19036] com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Delegate [delegate:///?vnetId=8&networkServiceProviderId=3] has no instance associated
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199) ~[guava-15.0.jar:na]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3932) ~[guava-15.0.jar:na]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3936) ~[guava-15.0.jar:na]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4806) ~[guava-15.0.jar:na]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4812) ~[guava-15.0.jar:na]
	at io.cattle.platform.agent.impl.AgentLocatorImpl.lookupAgent(AgentLocatorImpl.java:85) ~[cattle-iaas-agent-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.version.impl.ConfigUpdatePublisher.call(ConfigUpdatePublisher.java:327) [cattle-config-item-common-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.version.impl.ConfigUpdatePublisher.publishUpdate(ConfigUpdatePublisher.java:231) [cattle-config-item-common-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.version.impl.ConfigUpdatePublisher.publish(ConfigUpdatePublisher.java:201) [cattle-config-item-common-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.version.impl.ConfigUpdatePublisher.loopBody(ConfigUpdatePublisher.java:127) [cattle-config-item-common-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.version.impl.ConfigUpdatePublisher.doRun(ConfigUpdatePublisher.java:100) [cattle-config-item-common-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_72]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_72]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_72]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
Caused by: java.lang.IllegalStateException: Delegate [delegate:///?vnetId=8&networkServiceProviderId=3] has no instance associated
	at io.cattle.platform.agent.impl.AgentLocatorImpl.getAgentForDelegate(AgentLocatorImpl.java:132) ~[cattle-iaas-agent-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.agent.impl.AgentLocatorImpl.buildDelegate(AgentLocatorImpl.java:104) ~[cattle-iaas-agent-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.agent.impl.AgentLocatorImpl$1.load(AgentLocatorImpl.java:52) ~[cattle-iaas-agent-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.agent.impl.AgentLocatorImpl$1.load(AgentLocatorImpl.java:47) ~[cattle-iaas-agent-0.5.0-SNAPSHOT.jar:na]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522) ~[guava-15.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315) ~[guava-15.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278) ~[guava-15.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193) ~[guava-15.0.jar:na]
	... 23 common frames omitted

2017-03-11 15:05:55,283 ERROR [26330db7-dd46-45b0-bf57-a6e0d5955bd8:5293747] [instance:188843] [instance.purge] [] [ecutorService-9] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.remove.reply;agent=2]: Error response from daemon: Unable to remove filesystem for b1182728e736bf62d68d46d1ee1177295fe5614b86948a03908fa8449465241d: remove /var/lib/docker/containers/b1182728e736bf62d68d46d1ee1177295fe5614b86948a03908fa8449465241d/shm: device or resource busy
2017-03-11 15:05:55,294 ERROR [:] [] [] [] [ecutorService-9] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [compute.instance.remove.reply;agent=2]: Error response from daemon: Unable to remove filesystem for b1182728e736bf62d68d46d1ee1177295fe5614b86948a03908fa8449465241d: remove /var/lib/docker/containers/b1182728e736bf62d68d46d1ee1177295fe5614b86948a03908fa8449465241d/shm: device or resource busy
```

**Comment by aemneina** [comment]
This issue stems from upgrades where the system being upgraded from has orphaned agents. Take a look here for the solution: https://github.com/rancher/rancher/issues/7133#issuecomment-290677460
