### ISSUE TITLE
test_docker.py test_docker_volumes fails randomly

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#722]
We are frequently seeing build failures where test_docker.py's `test_docker_volumes` is failing on the finally block:
```
finally:
        if c is not None:
            admin_client.wait_success(admin_client.delete(c))
```

I believe I tracked the error down to:
>[i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [io.github.ibuildthecloud.gdapi.request.ApiRequest@6f44d9de] io.cattle.platform.engine.process.impl.ProcessCancelException: State [purged] is not valid

The problem is that before `admin_client.delete()` is called, we do a stop and remove here:
`c.stop(remove=True, timeout=0)` - https://github.com/rancherio/cattle/blob/master/tests/integration/cattletest/core/test_docker.py#L549
And that stop and remove leads to a purge.

So, the container is sometimes getting to the state purged before the delete is called and the API returns a 500 in that scenario. You can see this behavior by purging a container and then doing a curl delete:
```
curl -X DELETE http://localhost:8080/v1/containers/1i1
```
That returns a 500:
```
{"id":"f9851216-2f93-4d93-bc0f-635f404ce920","type":"error","links":{},"actions":{},"status":500,"code":"Internal Server Error","message":"Internal Server Error","detail":null}
```

For more context, here's a bigger snippet of the stack
```
2015-05-05 18:21:59,297 ERROR [:] [] [] [] [p1117259261-124] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [io.github.ibuildthecloud.gdapi.request.ApiRequest@6f44d9de] io.cattle.platform.engine.process.impl.ProcessCancelException: State [purged] is not valid
...
at io.cattle.platform.api.resource.AbstractObjectResourceManager.deleteInternal(AbstractObjectResourceManager.java:127) ~[cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.iaas.api.manager.InstanceManager.deleteInternal(InstanceManager.java:37) ~[cattle-iaas-api-logic-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.delete(AbstractBaseResourceManager.java:140) ~[gdapi-java-server-0.10.4.jar:na]
	at io.github.ibuildthecloud.gdapi.request.resource.AbstractResourceManagerFilter.delete(AbstractResourceManagerFilter.java:53) ~[gdapi-java-server-0.10.4.jar:na]
	at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.delete(FilteredResourceManager.java:66) ~[gdapi-java-server-0.10.4.jar:na]
	at io.github.ibuildthecloud.gdapi.request.resource.AbstractResourceManagerFilter.delete(AbstractResourceManagerFilter.java:53) ~[gdapi-java-server-0.10.4.jar:na]
	at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.delete(FilteredResourceManager.java:66) ~[gdapi-java-server-0.10.4.jar:na]
	at io.github.ibuildthecloud.gdapi.request.resource.AbstractResourceManagerFilter.delete(AbstractResourceManagerFilter.java:53) ~[gdapi-java-server-0.10.4.jar:na]
	at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.delete(FilteredResourceManager.java:66) ~[gdapi-java-server-0.10.4.jar:na]
	at io.github.ibuildthecloud.gdapi.request.resource.AbstractResourceManagerFilter.delete(AbstractResourceManagerFilter.java:53) ~[gdapi-java-server-0.10.4.jar:na]
	at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.delete(FilteredResourceManager.java:66) ~[gdapi-java-server-0.10.4.jar:na]
```

**Comment by cjellick** [comment]
Being addressed here:
 https://github.com/rancherio/cattle/pull/396

**Comment by deniseschannon** [comment]
the cattle issue is merged, so it this fixed? @cjellick

**Comment by cjellick** [comment]
This is fixed. Needs closed
