### ISSUE TITLE
HA: server container failed to start when adding --advertise-address option

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#7224]
**Rancher Version:**
v1.3.0-rc2
**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
ROS 0.7
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
- Configure external databsae and set up cattle database
```
> CREATE DATABASE IF NOT EXISTS cattle COLLATE = 'utf8_general_ci' CHARACTER SET = 'utf8';
> GRANT ALL ON cattle.* TO 'cattle'@'%' IDENTIFIED BY 'cattle';
> GRANT ALL ON cattle.* TO 'cattle'@'localhost' IDENTIFIED BY 'cattle';
```
- start rancher server with external database and advertise-address option:
```
docker run -d --restart=unless-stopped -p 8080:8080 -p 9345:9345 rancher/server:v1.3.0-rc2 --advertise-address  <ip-of-the-node> --db-host <external-db-address> --db-name cattle --db-user cattle --db-pass cattle
```

**Results:** 

The Rancher server container failed to start and it looks like it can't create tables:
```
CATTLE_AGENT_PACKAGE_HOST_API_URL=/usr/share/cattle/artifacts/host-api.tar.gz
CATTLE_AGENT_PACKAGE_PYTHON_AGENT_URL=/usr/share/cattle/artifacts/go-agent.tar.gz
CATTLE_API_UI_URL=//releases.rancher.com/api-ui/1.0.8
CATTLE_CATTLE_VERSION=v0.175.1
CATTLE_CLUSTER_ADVERTISE_ADDRESS=<node's ip>
CATTLE_DB_CATTLE_DATABASE=mysql
CATTLE_DB_CATTLE_MYSQL_HOST=<external-db-address>
CATTLE_DB_CATTLE_MYSQL_NAME=cattle
CATTLE_DB_CATTLE_MYSQL_PORT=3306
CATTLE_DB_CATTLE_USERNAME=cattle
CATTLE_GRAPHITE_HOST=
CATTLE_GRAPHITE_PORT=
CATTLE_HOME=/var/lib/cattle
CATTLE_HOST_API_PROXY_MODE=embedded
CATTLE_LOGBACK_OUTPUT_GELF_HOST=
CATTLE_LOGBACK_OUTPUT_GELF_PORT=
CATTLE_RANCHER_CLI_VERSION=v0.4.0
CATTLE_RANCHER_COMPOSE_VERSION=v0.12.0
CATTLE_RANCHER_SERVER_IMAGE=rancher/server
CATTLE_RANCHER_SERVER_VERSION=v1.3.0-rc2
CATTLE_USE_LOCAL_ARTIFACTS=true
DEFAULT_CATTLE_API_UI_CSS_URL=/api-ui/ui.min.css
DEFAULT_CATTLE_API_UI_INDEX=//releases.rancher.com/ui/1.3.2
DEFAULT_CATTLE_API_UI_JS_URL=/api-ui/ui.min.js
DEFAULT_CATTLE_AUTH_SERVICE_EXECUTE=true
DEFAULT_CATTLE_CATALOG_EXECUTE=true
DEFAULT_CATTLE_CATALOG_URL={"catalogs":{"community":{"url":"https://git.rancher.io/community-catalog.git","branch":"master"},"library":{"url":"https://git.rancher.io/rancher-catalog.git","branch":"v1.3.0-rc2"}}}
DEFAULT_CATTLE_COMPOSE_EXECUTOR_EXECUTE=true
DEFAULT_CATTLE_MACHINE_EXECUTE=true
DEFAULT_CATTLE_RANCHER_CLI_DARWIN_URL=https://releases.rancher.com/cli/v0.4.0/rancher-darwin-amd64-v0.4.0.tar.gz
DEFAULT_CATTLE_RANCHER_CLI_LINUX_URL=https://releases.rancher.com/cli/v0.4.0/rancher-linux-amd64-v0.4.0.tar.gz
DEFAULT_CATTLE_RANCHER_CLI_WINDOWS_URL=https://releases.rancher.com/cli/v0.4.0/rancher-windows-386-v0.4.0.zip
DEFAULT_CATTLE_RANCHER_COMPOSE_DARWIN_URL=https://releases.rancher.com/compose/v0.12.0/rancher-compose-darwin-amd64-v0.12.0.tar.gz
DEFAULT_CATTLE_RANCHER_COMPOSE_LINUX_URL=https://releases.rancher.com/compose/v0.12.0/rancher-compose-linux-amd64-v0.12.0.tar.gz
DEFAULT_CATTLE_RANCHER_COMPOSE_WINDOWS_URL=https://releases.rancher.com/compose/v0.12.0/rancher-compose-windows-386-v0.12.0.zip
DEFAULT_CATTLE_TRAEFIK_EXECUTE=true
DEFAULT_CATTLE_WEBHOOK_SERVICE_EXECUTE=true
13:12:48.342 [main] INFO  ConsoleStatus - Loading configuration
13:12:49.955 [main] ERROR ConsoleStatus - Failed to initialize discovery
org.jooq.exception.DataAccessException: SQL [delete from `cluster_membership` where `cluster_membership`.`uuid` = ?]; Table 'cattle.cluster_membership' doesn't exist
	at org.jooq.impl.Utils.translate(Utils.java:1287) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:495) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:326) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:140) ~[jooq-3.3.0.jar:na]
	at io.cattle.platform.hazelcast.membership.dao.impl.ClusterMembershipDAOImpl.checkin(ClusterMembershipDAOImpl.java:24) ~[cattle-hazelcast-common-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.hazelcast.membership.DBDiscovery.checkin(DBDiscovery.java:169) ~[cattle-hazelcast-common-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.hazelcast.membership.DBDiscovery.init(DBDiscovery.java:79) ~[cattle-hazelcast-common-0.5.0-SNAPSHOT.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_72]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_72]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_72]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:365) [spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
.....
```

**Comment by galal-hussein** [comment]
Rancher server: v1.3.0-rc5

Tested and validated HA deployment on 3 nodes, all nodes synced and were up and running.

**Comment by ocasta** [comment]
I'm seeing this same issue on 1.3.4
