### ISSUE TITLE
rancher-compose panics

### ISSUE THREAD

**Issue by DanielDent** [rancher/rancher#7348]
**Rancher Versions:**
Server: 1.2.2

**Docker Version:**
1.12.5
**OS and where are the hosts located? (cloud, bare metal, etc):**
bare metal
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle
**Steps to Reproduce:**
rancher-compose up -p -u
**Results:** 
```
INFO[0000] [0/2] [svc1]: Creating                       
INFO[0000] [0/2] [svc2]: Creating                        
INFO[0001] [0/2] [svc2]: Created                         
INFO[0001] [0/2] [svc1]: Created                        
INFO[0001] [0/2] [svc2]: Starting                        
INFO[0001] [0/2] [svc1]: Starting                       
INFO[0001] [1/2] [svc1]: Started                        
INFO[0001] [2/2] [svc2]: Started                         

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1372c5]

goroutine 76 [running]:
panic(0x559340, 0xc420010080)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/rancher/rancher-compose/rancher.(*RancherService).containers(0xc42017a180, 0x7, 0x616d81, 0x7, 0x1, 0x0)
	/go/src/github.com/rancher/rancher-compose/rancher/service.go:444 +0xc5
github.com/rancher/rancher-compose/rancher.(*RancherService).Log(0xc42017a180, 0x8d0440, 0xc4200103e0, 0x11d301, 0xc420023ee8, 0xc420023ef8)
	/go/src/github.com/rancher/rancher-compose/rancher/service.go:487 +0xdb
github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project.(*Project).Log.func1.1(0x8d8320, 0xc42017a180, 0xc4201fb600, 0x3)
	/go/src/github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project/project_log.go:13 +0x4b
github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project.(*serviceWrapper).Do(0xc4202ba3f0, 0x0, 0x0, 0x0, 0xc420719f50)
	/go/src/github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project/service-wrapper.go:101 +0x127
github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project.(*Project).Log.func1(0xc4202ba3f0, 0xc4203540c0)
	/go/src/github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project/project_log.go:14 +0x8c
created by github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project.(*Project).startService
	/go/src/github.com/rancher/rancher-compose/vendor/github.com/docker/libcompose/project/project.go:428 +0x59d
```
rancher-compose.yml:

```
svc1:
  scale: 2
  upgrade_strategy:
    start_first: true
  health_check:
    port: 80
    interval: 5000
    unhealth_threshold: 3
    request_line: GET / HTTP/1.0
    health_threshold: 2
    response_time: 2000
    strategy: recreate
svc2:
  scale: 2
  upgrade_strategy:
    start_first: true
  health_check:
    port: 80
    interval: 5000
    unhealth_threshold: 3
    request_line: GET / HTTP/1.0
    health_threshold: 2
    response_time: 2000
    strategy: recreate
```
docker-compose.yml:
```
version: '2'

services:
  svc1:
    restart: always
    image: animagename
    labels:
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    logging:
      driver: "json-file"
      options:
        max-size: 1m
    expose:
      - '80'

  svc2:
    restart: always
    image: someimagename
    environment:
      SOMETHING: else
    labels:
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    volumes:
      - "/something"
    logging:
      driver: "json-file"
      options:
        max-size: 1m
    expose:
      - '1234'

```

Re-running the same command works without a panic.

One thing I note is that I had used a mix of v1 and v2 syntax (docker-compose is v2, whereas rancher-compose is v1).

**Comment by aemneina** [comment]
@DanielDent what version of rancher compose is this? I think host OS you're running rancher-compose would also be helpful.

**Comment by DanielDent** [comment]
rancher-compose version v0.12.1 on OS X

**Comment by joshwget** [comment]
@DanielDent Is this consistently reproducible? Does it still occur in latest Rancher?

**Comment by superseb** [comment]
Closing as stale.

**Comment by iamsteadman** [comment]
Bumping as this needs re-opening (this issue hasn't been addressed so unusable on Mac.)
