### ISSUE TITLE
Rancher stuck on login

### ISSUE THREAD

**Issue by danielschlegel** [rancher/rancher#7597]
I have this issue since version 1.2 of Rancher. Unfortunetely no update did help to solve it. When i login to rancher the loading screen does not appear for minutes!
This is a serious issue for us. We even consider to switch to Openstack or something else. Also different browsers do not help.
 
In console i see some of this requests before i get logged in:
Depaginate, requesting https://rancher.example.com:8080/v2-beta/projects/1a7/mounts?limit=-1&marker=m6000

This is my nginx config in front of rancher.
```
upstream rancher {
    server rancher:8080;
}

server {
    server_name rancher.example.com;
    listen 8080 ssl;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;  # don’t use SSLv3 ref: POODLE
    ssl_certificate /etc/letsencrypt/live/rancher.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/rancher.example.com/privkey.pem;

    error_log /var/log/nginx/error.https.rancher.example.com.log;
    access_log /var/log/nginx/access.https.rancher.example.com.log;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://rancher;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        # This allows the ability for the execute shell window to remain open for up to 15 minutes. Without this parameter, the default is 1 minute and will automatically close.
        proxy_read_timeout 900s;
    }
}
```

---
| Useful | Info | 
|Versions|Rancher `v1.3.3` Cattle: `v0.175.9` UI: `v1.3.5` |
|Access|`github` `admin`|
|Orchestration|`Kubernetes`| 
|Docker|1.12.3|

**Comment by HenryTheSir** [comment]
Hi Daniel,

have you tested the options discussed here? https://github.com/rancher/rancher/issues/7548
Your issue seems very simular.

**Comment by danielschlegel** [comment]
i had an exception while running clean script.
```
java.sql.SQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`cattle`.`volume_storage_pool_map`, CONSTRAINT `fk_volume_storage_pool_map__volume_id` FOREIGN KEY (`volume_id`) REFERENCES `volume` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:119)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:261)
	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:290)
	at org.mariadb.jdbc.MariaDbStatement.executeUpdate(MariaDbStatement.java:474)
	at org.mariadb.jdbc.MariaDbStatement.executeUpdate(MariaDbStatement.java:490)
	at io.cattle.platform.core.cleanup.Main.runIncremental(Main.java:85)
	at io.cattle.platform.core.cleanup.Main.run(Main.java:77)
	at io.cattle.platform.core.cleanup.Main.runUp(Main.java:68)
	at io.cattle.platform.core.cleanup.Main.mainWithError(Main.java:114)
	at io.cattle.platform.core.cleanup.Main.main(Main.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Cannot delete or update a parent row: a foreign key constraint fails (`cattle`.`volume_storage_pool_map`, CONSTRAINT `fk_volume_storage_pool_map__volume_id` FOREIGN KEY (`volume_id`) REFERENCES `volume` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:475)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.result(AbstractQueryProtocol.java:396)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:378)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:334)
	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:280)
	... 13 more

```

Anyways. This still helped. Rancher login seam to be fast again!

Thank you so much! You can close if this exception is not an issue.
