### ISSUE TITLE
process_execution and service_log MySQL database tables grow indefinitely

### ISSUE THREAD

**Issue by ghost** [rancher/rancher#7616]
**Rancher Versions:**
Server: 1.3.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04 LTS, VMWare

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher HA, External MySQL DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
N/A

**Steps to Reproduce:**
1) Start Rancher
2) log tables grow indefinitely and exceed their max size, causing this error:

```
Caused by: java.sql.SQLException: The table 'process_instance' is full
        at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:136) ~[mariadb-java-client-1.3.4.jar:na]
        at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69) ~[mariadb-java-client-1.3.4.jar:na]
        at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeQueryEpilog(MariaDbServerPreparedStatement.java:338) ~[mariadb-java-client-1.3.4.jar:na]
        at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:293) ~[mariadb-java-client-1.3.4.jar:na]
        at org.mariadb.jdbc.MariaDbServerPreparedStatement.execute(MariaDbServerPreparedStatement.java:371) ~[mariadb-java-client-1.3.4.jar:na]
        ... 40 common frames omitted
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: The table 'process_instance' is full
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:475) ~[mariadb-java-client-1.3.4.jar:na]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executePreparedQuery(AbstractQueryProtocol.java:588) ~[mariadb-java-client-1.3.4.jar:na]
        at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:281) ~[mariadb-java-client-1.3.4.jar:na]
        ... 41 common frames omitted
```

**Results:** 
Unable to restart Rancher server.

Should the Rancher Server process periodically truncate these tables to avoid this condition?

**Comment by loganhz** [comment]
Please try https://rancher.com/docs/rancher/v1.6/en/faqs/server/#rancher-server-database-is-growing-too-quickly

Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
