### ISSUE TITLE
Secrets: using vault backend shows "Error in request, code : 400"

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#7650]
**Rancher Versions:**
Server: 1.4.0-rc7

**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 16.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle
**Steps to Reproduce:**
- start vault with address 0.0.0.0:8200
- mount transit backend
`vault mount transit`
- create rancher encryption key
`vault write -f transit/keys/rancher`
- create policy.hcl file
```
path "transit/random/rancher" {
  capabilities = ["sudo"]
}

path "transit/hmac/rancher" {
  capabilities = ["sudo"]
}

path "transit/encrypt/rancher" {
  capabilities = ["sudo"]
}

path "transit/decrypt/rancher" {
  capabilities = ["sudo"]
}

path "transit/verify/rancher" {
  capabilities = ["sudo"]
}
```
- create rancher policy
`vault token-create -display-name="rancher-token" -policy="rancher-policy"`
- start rancher server with the vault backend 
`docker run -d --restart=unless-stopped -p 8080:8080 -e VAULT_ADDR=http://x.x.x.x:8200 -e VAULT_TOKEN="xxxxxxxxxxxxxx" rancher/server:v1.4.0-rc7`
- change the advanced settings for rancher to use vault instead of localkey
- create a secret

**Results:** 
The creation hung for a while and i got the following error in rancher server:

```

time="2017-02-02T13:15:43Z" level=error msg="Error in request, code : 400: Issue encrypting with rancher key" 
2017-02-02 13:15:43,802 ERROR [:] [] [] [] [qtp5592464-124 ] [i.c.p.iaas.api.manager.SecretManager] Failed to secret java.io.IOException: Failed to encrypt secret :Bad Request
    at io.cattle.platform.framework.secret.SecretsServiceImpl$1.handleResponse(SecretsServiceImpl.java:57) ~[cattle-framework-encryption-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.framework.secret.SecretsServiceImpl$1.handleResponse(SecretsServiceImpl.java:52) ~[cattle-framework-encryption-0.5.0-SNAPSHOT.jar:na]
    at org.apache.http.client.fluent.Response.handleResponse(Response.java:85) ~[fluent-hc-4.3.1.jar:4.3.1]
    at io.cattle.platform.framework.secret.SecretsServiceImpl.encrypt(SecretsServiceImpl.java:50) ~[cattle-framework-encryption-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.iaas.api.manager.SecretManager.createAndScheduleObject(SecretManager.java:42) ~[cattle-iaas-api-logic-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.api.resource.AbstractObjectResourceManager.doCreate(AbstractObjectResourceManager.java:98) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.api.resource.AbstractObjectResourceManager.createInternal(AbstractObjectResourceManager.java:89) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
    at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.create(AbstractBaseResourceManager.java:115) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
    at io.github.ibuildthecloud.gdapi.request.resource.AbstractResourceManagerFilter.create(AbstractResourceManagerFilter.java:43) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
    at io.cattle.platform.iaas.api.filter.secret.SecretValidationFilter.create(SecretValidationFilter.java:22) [cattle-iaas-api-logic-0.5.0-SNAPSHOT.jar:na]
    at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.create(FilteredResourceManager.java:56) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
    at io.github.ibuildthecloud.gdapi.request.handler.ResourceManagerRequestHandler.generate(ResourceManagerRequestHandler.java:40) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
    ....
```

**Comment by cloudnautique** [comment]
The policy needed to be updated to:
path "transit/random/*" {
  capabilities = ["create", "update"]
}

path "transit/hmac/rancher/*" {
  capabilities = ["create", "update"]
}

path "transit/encrypt/rancher" {
  capabilities = ["create", "update"]
}

path "transit/decrypt/rancher" {
  capabilities = ["create", "update"]
}

path "transit/verify/rancher/*" {
  capabilities = ["create", "update", "read"]
}

path "transit/keys/*" {
  capabilities = ["deny"]
}

path "sys/*" {
  capabilities = ["deny"]
}

**Comment by cloudnautique** [comment]
```
path "transit/random/*" {
  capabilities = ["create", "update"]
}

path "transit/hmac/*" {
  capabilities = ["create", "update"]
}

path "transit/encrypt/rancher" {
  capabilities = ["create", "update"]
}

path "transit/decrypt/rancher" {
  capabilities = ["create", "update"]
}

path "transit/verify/rancher/*" {
  capabilities = ["create", "update", "read"]
}

path "transit/keys/*" {
  capabilities = ["deny"]
}

path "sys/*" {
  capabilities = ["deny"]
}
```

**Comment by galal-hussein** [comment]
@cloudnautique Rancher v1.4.0-rc8, i was able to create secrets using the latest policy in the last comment:

```
path "transit/random/*" {
  capabilities = ["create", "update"]
}

path "transit/hmac/*" {
  capabilities = ["create", "update"]
}

path "transit/encrypt/rancher" {
  capabilities = ["create", "update"]
}

path "transit/decrypt/rancher" {
  capabilities = ["create", "update"]
}

path "transit/verify/rancher/*" {
  capabilities = ["create", "update", "read"]
}

path "transit/keys/*" {
  capabilities = ["deny"]
}

path "sys/*" {
  capabilities = ["deny"]
}
```

**Comment by swartel-fa** [comment]
My god, I lost half a day due to this typo:
```
# diff rancher.hcl rancher.hcl.new                                    17-02-19 - 15:58:59
5c5
< path "transit/hmac/rancher/*" {
---
> path "transit/hmac/*" {
```

> time="2017-02-19T14:45:36Z" level=error msg="Error making API request.\n\nURL: PUT http://x.x.x.x:8200/v1/transit/hmac/rancher\nCode: 403. Errors:\n\n* permission denied"

@cloudnautique Could you please update the documentation accordingly https://docs.rancher.com/rancher/v1.4/en/cattle/secrets/ 

Many thanks 👍
