### ISSUE TITLE
Failure to send result to graphite server - java.net.SocketException: Broken pipe

### ISSUE THREAD

**Issue by hiscal2015** [rancher/rancher#7753]
**Rancher Versions:** v1.4.0

**Docker Version:** 0.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 16.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**

After upgrade to rancher 1.4.0, or even with clean install, rancher stats failed to send to graphite server
From docker logs, rancher repeats to pop up below errors:

2017-02-09 08:48:31,370 WARN  [:] [] [] [] [xtrans-export-1] [o.j.embedded.output.GraphiteWriter  ] Failure to send result to graphite server 'HostAndPort{host='influxdb.devops.demo.com', port=2003}' with SocketWriter{socket=Socket[addr=influxdb.devops.demo.com/10.10.1.10,port=2003,localport=43484]} java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method) ~[na:1.8.0_72]
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109) ~[na:1.8.0_72]
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153) ~[na:1.8.0_72]
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221) ~[na:1.8.0_72]
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291) ~[na:1.8.0_72]
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295) ~[na:1.8.0_72]
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141) ~[na:1.8.0_72]
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229) ~[na:1.8.0_72]
	at java.io.BufferedWriter.flush(BufferedWriter.java:254) ~[na:1.8.0_72]
	at java.io.FilterWriter.flush(FilterWriter.java:100) ~[na:1.8.0_72]
	at org.jmxtrans.embedded.output.GraphiteWriter.write(GraphiteWriter.java:140) ~[embedded-jmxtrans-1.0.9.jar:na]
	at org.jmxtrans.embedded.Query.exportCollectedMetrics(Query.java:208) [embedded-jmxtrans-1.0.9.jar:na]
	at org.jmxtrans.embedded.EmbeddedJmxTrans$2.run(EmbeddedJmxTrans.java:152) [embedded-jmxtrans-1.0.9.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_72]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_72]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_72]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]

I can telnet port 2003 of influxdb successfully.
Trying 10.10.1.10...
Connected to influxdb.devops.demo.com.
Escape character is '^]'.

**Comment by hiscal2015** [comment]
it turns out my influxdb issue, issue closed

**Comment by ttalla14** [comment]
Hi @yongzhang - What was your influxdb issue?
I am trying to build TICK Stack using InfluxDB + Graphite exporter and I am seeing these messages
```
{"message":"Unable to report to Graphite","timestamp":"2020-08-20T03:18:08.562Z","environment":null,"component":"example-app","level":"WARN","location":"com.codahale.metrics.graphite.GraphiteReporter:192","threadName":"metrics-graphite-reporter-1-thread-1"}
java.net.SocketException: Broken pipe (Write failed)
```
...and I can do both `telnet` and `curl` on port 2003 successfully
```
curl -kv http://test-influxdb-graphite-alb-450697386.us-east-1.elb.amazonaws.com:2003/                                   21:53:46
*   Trying 34.223.10.88...
* TCP_NODELAY set
* Connected to test-influxdb-graphite-alb-450697386.us-east-1.elb.amazonaws.com (34.223.10.88) port 2003 (#0)
> GET / HTTP/1.1
> Host: test-influxdb-graphite-alb-450697386.us-east-1.elb.amazonaws.com:2003
> User-Agent: curl/7.64.1
> Accept: */*
>
^C
```
So, can you please help me in figuring out what would be the issue connecting to Graphite?

**Comment by yongzhang** [comment]
@ttalla14 Sorry it has been 3 years I can't remember what the exact issue was.
