### ISSUE TITLE
CentOS 7: Error Exception when starting up Rancher, but Rancher successfully starts

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#779]
Docker Version: 1.5.0-dev
Rancher Version: 18.2

Ran `docker run -d -p 8080:8080 rancher/server:v0.18.2`

In the logs, I see an error. 

```bash
2015-05-12 17:04:40,756 INFO    [main] [ConsoleStatus] [2/108] [196ms] [196ms] Loading config-defaults 
2015-05-12 17:05:09,200 ERROR [:] [] [] [] [igurationSource] [c.n.config.AbstractPollingScheduler ] Error getting result from polling source java.sql.SQLSyntaxErrorException: Table 'cattle.setting' doesn't exist
        at org.mariadb.jdbc.internal.SQLExceptionMapper.get(SQLExceptionMapper.java:138) ~[mariadb-java-client-1.1.7.jar:na]
        at org.mariadb.jdbc.internal.SQLExceptionMapper.throwException(SQLExceptionMapper.java:106) ~[mariadb-java-client-1.1.7.jar:na]
        at org.mariadb.jdbc.MySQLStatement.executeQueryEpilog(MySQLStatement.java:264) ~[mariadb-java-client-1.1.7.jar:na]
        at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:288) ~[mariadb-java-client-1.1.7.jar:na]
        at org.mariadb.jdbc.MySQLStatement.executeQuery(MySQLStatement.java:302) ~[mariadb-java-client-1.1.7.jar:na]
        at org.mariadb.jdbc.MySQLPreparedStatement.executeQuery(MySQLPreparedStatement.java:112) ~[mariadb-java-client-1.1.7.jar:na]
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96) ~[commons-dbcp-1.4.jar:1.4]
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96) ~[commons-dbcp-1.4.jar:1.4]
        at com.netflix.config.sources.JDBCConfigurationSource.load(JDBCConfigurationSource.java:107) ~[archaius-c
ore-0.5.14.jar:na]
        at com.netflix.config.sources.JDBCConfigurationSource.poll(JDBCConfigurationSource.java:88) ~[archaius-co
re-0.5.14.jar:na]
        at io.cattle.platform.archaius.sources.LazyJDBCSource.poll(LazyJDBCSource.java:30) ~[cattle-framework-arc
haius-0.5.0-SNAPSHOT.jar:na]
        at com.netflix.config.AbstractPollingScheduler$1.run(AbstractPollingScheduler.java:163) ~[archaius-core-0
.5.14.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExe
cutor.java:178) [na:1.7.0_79]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.j
ava:293) [na:1.7.0_79]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Caused by: org.mariadb.jdbc.internal.common.QueryException: Table 'cattle.setting' doesn't exist
        at org.mariadb.jdbc.internal.mysql.MySQLProtocol.getResult(MySQLProtocol.java:942) ~[mariadb-java-client-
1.1.7.jar:na]
        at org.mariadb.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:991) ~[mariadb-java-clie
nt-1.1.7.jar:na]
        at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:281) ~[mariadb-java-client-1.1.7.jar:na]
        ... 15 common frames omitted
2015-05-12 17:05:16,569 WARN  [:] [] [] [] [main           ] [liquibase                           ] modifyDataTyp
e will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if
 this is the case 
2015-05-12 17:05:16,578 WARN  [:] [] [] [] [main           ] [liquibase                           ] modifyDataTyp
e will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if
 this is the case 
```

**Comment by vincent99** [comment]
#391 and #581?

**Comment by will-chan** [comment]
Is this still valid?  I thought we need a min of 1.6.2 on Centos7 for it to work.

**Comment by deniseschannon** [comment]
This error still exists with 1.6.2.

**Comment by will-chan** [comment]
please re-test

**Comment by deniseschannon** [comment]
Error doesn't exist anymore, but it doesn't appear that Rancher server is starting with v0.61.0-rc3 on CentOS 7.2.

**Comment by deniseschannon** [comment]
Closed in favor of https://github.com/rancher/rancher/issues/3801
