### ISSUE TITLE
Can't start IPSec service

### ISSUE THREAD

**Issue by willseward** [rancher/rancher#7812]
*Describe your issue here*

```
Feb 14 17:56:06 RANCHER-SERVER docker[22401]: 2017-02-14 17:56:06,978 ERROR [:] [] [] [] [cutorService-16] [.e.s.i.ProcessInstanceDispatcherImpl] Unknown exception running process [instance.create:293861] on [8521] io.cattle.platform.util.exception.ExecutionException: Could not process named volume rancher-cni-driver. More than one volume with that name exists.
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.process.instance.InstanceVolumeLookupPreCreate.handle(InstanceVolumeLookupPreCreate.java:115) ~[cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:470) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:421) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:415) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:415) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:514) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:345) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:245) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:242) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:184) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:157) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:116) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:113) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:113) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl.processExecuteWithLock(ProcessInstanceDispatcherImpl.java:117) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl$1.doWithLock(ProcessInstanceDispatcherImpl.java:104) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl$1.doWithLock(ProcessInstanceDispatcherImpl.java:101) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.lock.impl.AbstractLockManagerImpl$4.doWithLock(AbstractLockManagerImpl.java:50) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:25) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:47) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl.execute(ProcessInstanceDispatcherImpl.java:101) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at io.cattle.platform.engine.server.ProcessInstanceReference.doRun(ProcessInstanceReference.java:58) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
Feb 14 17:56:06 RANCHER-SERVER docker[22401]:         at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
```

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.4.1` Cattle: `v0.176.9` UI: `v1.4.6` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stack.index`|

**Comment by willseward** [comment]
Fixed it with a:

```
delete from mount where volume_id in (select id from volume where name = 'rancher-cni-driver' and state = 'detached');
delete from volume where name = 'rancher-cni-driver' and state = 'detached';
```

**Comment by leodotcloud** [comment]
@willseward Could you please share steps to reproduce this issue?

**Comment by willseward** [comment]
I am unsure about the steps reproduce. A production host went down and this exception was being thrown. I can't really give any more details than that. Sorry.

I'll close since this is obscure.
