### ISSUE TITLE
Can't reconnect agents to host since this morning

### ISSUE THREAD

**Issue by dj-hedgehog** [rancher/rancher#7900]
**Rancher Version:** 1.3.0
**Docker Version:** 1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):** cloud
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher, internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

I've been running Rancher with 4 hosts for like two months without problems.
Today 3 of them show DISCONNECTED in the server UI without me doing anything. One is still connected.

When stopping and re-creating an agent on one of the hosts I get this log output:

*What can I do about this?*

```
INFO: Running Agent Registration Process, CATTLE_URL=http://rancher.storyx.company:8080/v1
INFO: Attempting to connect to: http://rancher.storyx.company:8080/v1
INFO: http://rancher.storyx.company:8080/v1 is accessible
Traceback (most recent call last):
  File "./resolve_url.py", line 21, in <module>
    client = from_env(url=url)
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 45, in from_env
    return gdapi.from_env(prefix=prefix, factory=Client, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 613, in from_env
    return _from_env(prefix=prefix, factory=factory, **args)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 632, in _from_env
    return factory(**result)
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 12, in __init__
    super(Client, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 197, in __init__
    self._load_schemas()
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 315, in _load_schemas
    response = self._get_response(self._url)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 266, in _get_response
    self._error(r.text)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 255, in _error
    raise ApiError(self._unmarshall(text))
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 300, in _unmarshall
    object_pairs_hook=self.object_pairs_hook)
  File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
ERROR: returned
ERROR: --- START ---
ERROR: --- END ---

ERROR: Failed to load registration env from CATTLE_URL=http://rancher.storyx.company:8080/v1 ENV_URL=
ERROR: Please ensure the proper value for the Host Registration URL is set
```

**Comment by superseb** [comment]
What output do you get when you run a `curl` inside the container to the URL you specify?

**Comment by superseb** [comment]
Closed due to inactivity, please comment if you still need help so we can track this down.
