### ISSUE TITLE
[Rancher agent] - Cannot register rancher agent to rancher server via IP adress only

### ISSUE THREAD

**Issue by Niceplace** [rancher/rancher#7910]
**Rancher Versions:**
Server: stable
healthcheck: 0.2.0
ipsec: 0.8.1
network-services: 0.4.0
scheduler: 0.5.1
kubernetes (if applicable): N/A (using Cattle)

**Docker Version:** : 1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):** : RHEL7.2 - Cloud (Virtual machine on a ESXI host)
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** : Single node rancher with external db (MYSQL)
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** : Cattle
**Steps to Reproduce:**

1. The machine where the rancher server must only be reachable via IP adress.
2. The rancher agent is run with the command below from another machine.

Note : I am executing the command "as-is" from what the rancher-server GUI generated.

```
sudo docker run --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.1.3 http://10.36.76.21:11080/v1/scripts/48B992A0404E4F869F0E:1487700000000:VYogufIevE3vInb4Tg0n2xLFgk
```

**Results:** 

Note : In the logs I replaced my actual hostname with $HOSTNAME_TO_REACH in order not to reveal potentially sensitive information.

```
INFO: Running Agent Registration Process, CATTLE_URL=http://10.36.76.21:11080/v1
INFO: Attempting to connect to: http://10.36.76.21:11080/v1
INFO: http://10.36.76.21:11080/v1 is accessible
INFO: Inspecting host capabilities
INFO: Boot2Docker: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
Traceback (most recent call last):
  File "./register.py", line 11, in <module>
    secret_key=os.environ['CATTLE_REGISTRATION_SECRET_KEY'])
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 45, in from_env
    return gdapi.from_env(prefix=prefix, factory=Client, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 613, in from_env
    return _from_env(prefix=prefix, factory=factory, **args)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 632, in _from_env
    return factory(**result)
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 12, in __init__
    super(Client, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 197, in __init__
    self._load_schemas()
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 315, in _load_schemas
    response = self._get_response(self._url)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 264, in _get_response
    headers=self._headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='$HOSTNAME_TO_REACH', port=11080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f79b31df810>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
```

**Comment by superseb** [comment]
As far as I can determine, the Host registration URL is set to the value with the hostname, which cannot be reached by the script that is running inside the `rancher/agent` container. Can you double check the Host registration URL?

**Comment by Niceplace** [comment]
Unfortunately, the project I am no longer working on this project and do not have access to the rancher instance as of today, I don't think I will be able to provide more information any time soon, you can close this.
