### ISSUE TITLE
[Webhooks: scaleHost] Panic in webhook-service after host scale down below min

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#7918]
**Rancher Versions:**
Server:Master

**Docker Version:**1.13.0

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Create a 4 host setup with few hosts having label "test=value" 
2. Create a webhook to scale up hosts by amount=1
3. Power off the oldest host with the label "test=value" and wait till it goes to disconnected state
4. Execute the webhook to scale up while the oldest host is in disconnected state. A new host gets added as per the request
5. Edit the local storage resource limit to a lower value in the host settings on the disconnected host
6. Execute the webhook again, the request is stuck without any response
7. Created another webhook to scale down hosts and executed the webhook. Hosts scaled down as per the request.
8. After the min required scale was reached, the execution of the webhook gave an internal server error.
```
soumyas-MBP:~ soumya$ curl -i -H 'X-API-Project-Id: 1a5' -H 'Accept: application/json' -H 'Content-Type: application/json' -X POST http://35.184.42.95:8080/v1-webhooks/endpoint\?key=16kVHt5kqVotAV3hqAACAPqdWPea8Sh06MsxwxNh\&projectId\=1a5
HTTP/1.1 500 Internal Server Error
Content-Type: application/json; charset=utf-8
Date: Wed, 22 Feb 2017 01:22:27 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Jetty(9.2.11.v20150529)
Set-Cookie: PL=rancher;Path=/
X-Api-Schemas: http://35.184.42.95:8080/v1/schemas
Content-Length: 195

{"id":"72f5f0d4-a668-4ce1-babf-8a5a644c8e49","type":"error","links":{},"actions":{},"status":500,"code":"Internal Server Error","message":"Internal Server Error","detail":null,"baseT

```
The cattle logs have a panic
```
2017/02/22 01:26:09 http: panic serving 127.0.0.1:48188: runtime error: index out of range
goroutine 526 [running]:
net/http.(*conn).serve.func1(0xc82011b380)
	/usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0xa0e600, 0xc82000a060)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/rancher/webhook-service/drivers.(*ScaleHostDriver).Execute(0x104be88, 0x8f0fc0, 0xc820ccfe60, 0xc820a5aa00, 0x0, 0x0, 0xc820001380, 0x0, 0x0)
	/go/src/github.com/rancher/webhook-service/drivers/scale_host.go:149 +0x1d26
github.com/rancher/webhook-service/service.(*RouteHandler).ExecuteWithKey(0xc8200f4b20, 0xc82066e79f, 0x28, 0xc82066e7d2, 0x3, 0x0, 0x0, 0xc8206380a8, 0x0, 0x0)
	/go/src/github.com/rancher/webhook-service/service/execute_handler.go:144 +0x804
github.com/rancher/webhook-service/service.(*RouteHandler).Execute(0xc8200f4b20, 0x7fcb5de21d00, 0xc820ec21a0, 0xc82001e620, 0x104bfa0, 0x0, 0x0)
	/go/src/github.com/rancher/webhook-service/service/execute_handler.go:50 +0x5d2
github.com/rancher/webhook-service/service.(*RouteHandler).Execute-fm(0x7fcb5de21d00, 0xc820ec21a0, 0xc82001e620, 0x8, 0x0, 0x0)
	/go/src/github.com/rancher/webhook-service/service/routes.go:73 +0x4c
github.com/rancher/webhook-service/service.HandleError.func1(0x7fcb5de21d00, 0xc820ec21a0, 0xc82001e620)
	/go/src/github.com/rancher/webhook-service/service/routes.go:19 +0x4e
net/http.HandlerFunc.ServeHTTP(0xc820122580, 0x7fcb5de21d00, 0xc820ec21a0, 0xc82001e620)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/rancher/webhook-service/vendor/github.com/rancher/go-rancher/api.ApiHandler.func1(0x7fcb5de21d00, 0xc820ec21a0, 0xc82001e620)
	/go/src/github.com/rancher/webhook-service/vendor/github.com/rancher/go-rancher/api/handler.go:20 +0x13c
net/http.HandlerFunc.ServeHTTP(0xc82010cdc0, 0x7fcb5de21d00, 0xc820ec21a0, 0xc82001e620)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/rancher/webhook-service/vendor/github.com/gorilla/context.ClearHandler.func1(0x7fcb5de21d00, 0xc820ec21a0, 0xc82001e620)
	/go/src/github.com/rancher/webhook-service/vendor/github.com/gorilla/context/context.go:141 +0x85
net/http.HandlerFunc.ServeHTTP(0xc82010cde0, 0x7fcb5de21d00, 0xc820ec21a0, 0xc82001e620)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/rancher/webhook-service/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc8200f0eb0, 0x7fcb5de21d00, 0xc820ec21a0, 0xc82001e620)
	/go/src/github.com/rancher/webhook-service/vendor/github.com/gorilla/mux/mux.go:100 +0x29e
net/http.serverHandler.ServeHTTP(0xc82011ab00, 0x7fcb5de21d00, 0xc820ec21a0, 0xc82001e620)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82011b380)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e
2017-02-22 01:26:09,206 ERROR [:] [] [] [] [tp192881625-619] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [http://35.184.42.95:8080/v1/proxy/http://localhost:8085/v1-webhooks/endpoint]. Error id: [72f5f0d4-a668-4ce1-babf-8a5a644c8e49]. org.apache.http.NoHttpResponseException: The target server failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260) ~[httpcore-4.3.jar:4.3]
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161) ~[httpcore-4.3.jar:4.3]
	at sun.reflect.GeneratedMethodAccessor482.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_72]
	at org.apache.http.impl.conn.CPoolProxy.invoke(CPoolProxy.java:138) ~[httpclient-4.3.1.jar:4.3.1]
	at com.sun.proxy.$Proxy83.receiveResponseHeader(Unknown Source) ~[na:na]
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271) ~[httpcore-4.3.jar:4.3]
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123) ~[httpcore-4.3.jar:4.3]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:253) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.client.fluent.Executor.execute(Executor.java:215) ~[fluent-hc-4.3.1.jar:4.3.1]
	at io.cattle.platform.iaas.api.request.handler.GenericWhitelistedProxy.generate(GenericWhitelistedProxy.java:342) ~[cattle-iaas-api-logic-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.AbstractResponseGenerator.handle(AbstractResponseGenerator.java:14) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:99) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:96) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:106) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at io.cattle.platform.iaas.api.servlet.filter.ProxyPreFilter.doFilter(ProxyPreFilter.java:22) [cattle-iaas-api-logic-0.5.0-SNAPSHOT.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:595) [jetty-security-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:191) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:72) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at io.cattle.platform.iaas.api.servlet.filter.ProxyFilter.doFilter(ProxyFilter.java:45) [cattle-iaas-api-logic-0.5.0-SNAPSHOT.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [jetty-security-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.Server.handle(Server.java:499) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]



```

**Comment by soumyalj** [comment]
This issue happens when we try to scale down below the min and the host remaining is a custom host.

**Comment by mrajashree** [comment]
@soumyalj I'm unable to produce the condition where host is put to `Disconnected` state and then its resource limits are changed but you can't scale up. I can still scale up hosts using that host for cloning. 
Webhook-service already has log messages for handlers such as "Creating webhook", "Listing Webhooks". In your setup I'm not able to see even the message for "Listing webhooks".
The only log constantly seen is this `2017-02-22 10:43:09,261 INFO  [:] [] [] [] [ecutorService-9] [.e.s.i.ProcessInstanceDispatcherImpl] Timeout on process [instance.start:11332] on [15] : Timeout`

But the 500 error for scaling down custom hosts is a bug, and I've put a PR for that.

**Comment by mrajashree** [comment]
Since there's a separate bug to track the first part (webhook-service hanging) and second part is resolved I'm marking this one status/to-test

**Comment by soumyalj** [comment]
Tested with v1.5.0-rc1. Created a setup with 3 custom hosts and label "test=value". Created a webhook to scale down hosts with label test=value deleteOption="leastRecent", min=1 and max=4. Executed the webhook. Least recently created custom host gets deleted as expected. Executed again and the next host gets deleted too. Executing the third time gives the message
```Error Cannot scale below provided min scale value in executing driver scaleHost``` as expected.
No panic seen in the logs.
