### ISSUE TITLE
building rancherui fails.

### ISSUE THREAD

**Issue by chandra2017** [rancher/rancher#7991]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.9.3
3 info using node@v4.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ui@1.5.2~prestart: ui@1.5.2
6 silly lifecycle ui@1.5.2~prestart: no script for prestart, continuing
7 info lifecycle ui@1.5.2~start: ui@1.5.2
8 verbose lifecycle ui@1.5.2~start: unsafe-perm in lifecycle true
9 verbose lifecycle ui@1.5.2~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/ckeerthy/Downloads/rancher-ui/ui/node_modules/.bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle ui@1.5.2~start: CWD: /Users/ckeerthy/Downloads/rancher-ui/ui
11 silly lifecycle ui@1.5.2~start: Args: [ '-c', 'ember server' ]
12 silly lifecycle ui@1.5.2~start: Returned: code: 1  signal: null
13 info lifecycle ui@1.5.2~start: Failed to exec start script
14 verbose stack Error: ui@1.5.2 start: `ember server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:829:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid ui@1.5.2
16 verbose cwd /Users/ckeerthy/Downloads/rancher-ui/ui
17 error Darwin 16.3.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v4.5.0
20 error npm  v3.9.3
21 error code ELIFECYCLE
22 error ui@1.5.2 start: `ember server`
22 error Exit status 1
23 error Failed at the ui@1.5.2 start script 'ember server'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ui package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ember server
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ui
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ui
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by superseb** [comment]
What step in the `README.md` did you get this error?

**Comment by superseb** [comment]
Let me know if you still need help with this
