### ISSUE TITLE
[rancher-metadata] fails to start in the swarm environment

### ISSUE THREAD

**Issue by banh-gao** [rancher/rancher#8082]
**Rancher Versions:**
Server: v1.5.1
network-services/metadata: v0.8.11

**Docker Version:**
17.03.0-ce

**OS and where are the hosts located? (cloud, bare metal, etc):**
Debian 8 on OpenStack VMs: 1 rancher server and 3 hosts.

**Environment Type: Swarm**

**Steps to Reproduce:**
Create a swarm environment from the default swarm template.

**Results:** 

The metadata service fails to start on all hosts, not allowing to initialize the environment.

The log from the metadata container is the following:
```
time="2017-03-07T15:23:04Z" level=info msg="Subscribing to events"
7/3/2017 16:23:04time="2017-03-07T15:23:04Z" level=info msg="Starting rancher-metadata v0.8.11"
7/3/2017 16:23:04time="2017-03-07T15:23:04Z" level=info msg="Loading answers"
7/3/2017 16:23:04time="2017-03-07T15:23:04Z" level=warning msg="Failed to find: ./answers.json"
7/3/2017 16:23:04time="2017-03-07T15:23:04Z" level=info msg="Loaded answers from file"
7/3/2017 16:23:04time="2017-03-07T15:23:04Z" level=info msg="Listening for Reload on 127.0.0.1:8112"
7/3/2017 16:23:04time="2017-03-07T15:23:04Z" level=info msg="Listening on :80"
7/3/2017 16:23:04time="2017-03-07T15:23:04Z" level=info msg="Initializing event router" workerCount=3
7/3/2017 16:23:04time="2017-03-07T15:23:04Z" level=info msg="Connection established"
7/3/2017 16:23:04time="2017-03-07T15:23:04Z" level=info msg="Starting websocket pings"
7/3/2017 16:23:04time="2017-03-07T15:23:04Z" level=info msg="Downloaded in 684.159529ms"
7/3/2017 16:23:04time="2017-03-07T15:23:04Z" level=info msg="Generating and reloading answers"
7/3/2017 16:23:04time="2017-03-07T15:23:04Z" level=info msg="Generating answers"
7/3/2017 16:23:04panic: interface conversion: interface is nil, not string
7/3/2017 16:23:04
7/3/2017 16:23:04goroutine 29 [running]:
7/3/2017 16:23:04panic(0xa48f20, 0xc42025c900)
7/3/2017 16:23:04	/usr/local/go/src/runtime/panic.go:500 +0x1a1
7/3/2017 16:23:04main.applyVersionToData(0xc42023d1d0, 0xc42023d200, 0xc42023d230, 0xc42023d260, 0xc42023d2c0, 0xc42023d290, 0xc42023d2f0, 0xc42023d320, 0xc420013b00, 0x5, ...)
7/3/2017 16:23:04	/go/src/github.com/rancher/rancher-metadata/generator.go:301 +0x19b3
7/3/2017 16:23:04main.generateVersions(0xc420119d38, 0xb206b3, 0xa, 0xc4201f2840, 0xc42025aa20, 0x0)
7/3/2017 16:23:04	/go/src/github.com/rancher/rancher-metadata/generator.go:53 +0x6e
7/3/2017 16:23:04main.GenerateAnswers(0xc42016dc00, 0x59, 0x80, 0x0, 0x0, 0x0)
7/3/2017 16:23:04	/go/src/github.com/rancher/rancher-metadata/generator.go:42 +0x554
7/3/2017 16:23:04main.(*Subscriber).downloadAndReload(0xc4200547e0, 0x0, 0x0)
7/3/2017 16:23:04	/go/src/github.com/rancher/rancher-metadata/subscribe.go:187 +0x5c0
7/3/2017 16:23:04main.NewSubscriber.func1()
7/3/2017 16:23:04	/go/src/github.com/rancher/rancher-metadata/subscribe.go:66 +0x2e
7/3/2017 16:23:04github.com/rancher/rancher-metadata/pkg/kicker.(*Kicker).run(0xc420110d50)
7/3/2017 16:23:04	/go/src/github.com/rancher/rancher-metadata/pkg/kicker/kicker.go:52 +0x2f
7/3/2017 16:23:04created by github.com/rancher/rancher-metadata/pkg/kicker.(*Kicker).Kick
7/3/2017 16:23:04	/go/src/github.com/rancher/rancher-metadata/pkg/kicker/kicker.go:35 +0xed
```

**Comment by tfiduccia** [comment]
@banh-gao - Is private Networking enabled on your hosts?

**Comment by banh-gao** [comment]
Yes, all hosts are connected through a private network with internet access.
