### ISSUE TITLE
Kubernetes - StatefulSet usage is causing inserts on label table to fail

### ISSUE THREAD

**Issue by LLParse** [rancher/rancher#8168]
**Rancher Versions:**
Server: 1.5.1
kubernetes (if applicable): v1.5.2-rancher1-3

**Docker Version:** 1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):** cloud, AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**
1. Create a verbose StatefulSet via kubectl

**Results:** 
```
Caused by: java.sql.SQLDataException: (conn:273) Data too long for column 'value' at row 1
Query is: insert into `label` (`account_id`, `kind`, `uuid`, `state`, `created`, `data`, `type`, `key`, `value`) values (?, ?, ?, ?, ?, ?, ?, ?, ?), parameters [5,'label','f2bd1897-e678-4e5f-8583-89e708069e2a','created','2017-03-14 00:17:50.73','{}','container','io.kubernetes.pod.data','{"kind":"Pod","apiVersion":"v1","metadata":{"name":"james-etcd-0-2","generateName":"james-etcd-0-","namespace":"james","selfLink":"/api/v1/namespaces/james/pods/james-etcd-0-2","uid":"5c8595c3-084b-11e7-94c4-02ee7a622b17","resourceVersion":"540","creationTimestamp":"2017-03-14T00:15:42Z","labels":{"app":"etcd","release":"james-etcd-0","type":"member"},"annotations":{"kubernetes.io/config.seen":"2017-03-14T00:15:42.670025998Z","kubernetes.io/config.source":"api","kubernetes.io/created-by":"{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"StatefulSet\",\"namespace\":\"james\",\"name\":\"james-etcd-0\",\"uid\":\"522c4de5-084b-11e7-94c4-02ee7a622b17\",\"apiVersion\":\"apps\",\"resourceVersion\":\"469\"}}\...
    at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:129) ~[mariadb-java-client-1.5.8.jar:na]
    at org.mariadb.jdbc.internal.util.ExceptionMapper.getException(ExceptionMapper.java:101) ~[mariadb-java-client-1.5.8.jar:na]
    at org.mariadb.jdbc.internal.util.ExceptionMapper.throwAndLogException(ExceptionMapper.java:77) ~[mariadb-java-client-1.5.8.jar:na]
    at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:224) ~[mariadb-java-client-1.5.8.jar:na]
```

**Comment by galal-hussein** [comment]
Rancher server: v1.6.0-rc3
Kubernetes: rancher/k8s:v1.5.4-rancher1-4

Steps to validate:

- Run statefulset with environment variable with value more than 4096 character:
    - name: TEST_ENV
      value: "aaaaaaa....aaaaaa"
- Make sure that Labels in pod inspect shows `io.kubernetes.pod.data` more than 4096 character.
- Check Labels table and make sure `io.kubernetes.pod.data` label is truncated to 4096
- Make sure that the statefulset is working successfully.
