### ISSUE TITLE
SQL exception when trying to insert into service_log

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8340]
Rancher version - Build from wagyu

Following exception seen in rancher-server logs when trying to deploy services/standalone containers/load balancers.

```
2017-03-29 16:57:27,924 ERROR [:] [] [] [] [cutorService-13] [o.a.c.m.context.NoExceptionRunnable ] Uncaught exception org.jooq.exception.DataAccessException: SQL [insert into `service_log` (`account_id
`, `kind`, `description`, `created`, `data`, `end_time`, `event_type`, `service_id`, `instance_id`, `transaction_id`, `sub_log`, `level`, `deployment_unit_id`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
, ?)]; (conn:36915) Data too long for column 'description' at row 1
Query is: insert into `service_log` (`account_id`, `kind`, `description`, `created`, `data`, `end_time`, `event_type`, `service_id`, `instance_id`, `transaction_id`, `sub_log`, `level`, `deployment_unit
_id`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), parameters [5,'serviceLog','SQL [insert into `instance` (`name`, `account_id`, `kind`, `uuid`, `state`, `created`, `data`, `allocation_state`, `zone
_id`, `instance_triggered_stop`, `network_container_id`, `start_count`, `create_index`, `deployment_unit_uuid`, `version`, `service_index_id`, `system`, `service_id`, `environment_id`, `deployment_unit_
id`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; (conn:36914) Deadlock found when trying to get lock; try restarting transaction
Query is: insert into `instance` (`name`, `account_id`, `kind`, `uuid`, `state`, `created`, `data`, `allocation_state`, `zone_id`, `instance_triggered_stop`, `network_container_id`, `start_count`, `crea
te_index`, `deployment_unit_uuid`, `version`, `service_index_id`, `s...
        at org.jooq.impl.Utils.translate(Utils.java:1287) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:495) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:326) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.UpdatableRecordImpl.storeInsert0(UpdatableRecordImpl.java:230) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.UpdatableRecordImpl.access$100(UpdatableRecordImpl.java:90) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.UpdatableRecordImpl$2.operate(UpdatableRecordImpl.java:201) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:123) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.UpdatableRecordImpl.storeInsert(UpdatableRecordImpl.java:196) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.UpdatableRecordImpl.insert(UpdatableRecordImpl.java:144) ~[jooq-3.3.0.jar:na]
        at io.cattle.platform.object.impl.JooqObjectManager$1.executeNoResult(JooqObjectManager.java:80) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.idempotent.IdempotentExecutionNoReturn.execute(IdempotentExecutionNoReturn.java:7) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.idempotent.IdempotentExecutionNoReturn.execute(IdempotentExecutionNoReturn.java:3) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.idempotent.Idempotent.change(Idempotent.java:88) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.object.impl.JooqObjectManager.insert(JooqObjectManager.java:77) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.object.impl.AbstractObjectManager.create(AbstractObjectManager.java:51) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.object.impl.AbstractObjectManager.create(AbstractObjectManager.java:33) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.activity.impl.ActivityLogImpl.create(ActivityLogImpl.java:191) ~[cattle-activity-log-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.activity.impl.ActivityLogImpl.exception(ActivityLogImpl.java:187) ~[cattle-activity-log-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.activity.impl.EntryImpl.exception(EntryImpl.java:31) ~[cattle-activity-log-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.activity.ActivityService.run(ActivityService.java:58) ~[cattle-activity-log-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.servicediscovery.deployment.impl.manager.DeploymentUnitManagerImpl$2.run(DeploymentUnitManagerImpl.java:166) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.configitem.version.impl.ConfigItemStatusManagerImpl$1.doWithLock(ConfigItemStatusManagerImpl.java:92) ~[cattle-config-item-common-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl$4.doWithLock(AbstractLockManagerImpl.java:50) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:25) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:47) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.configitem.version.impl.ConfigItemStatusManagerImpl.runUpdateForEvent(ConfigItemStatusManagerImpl.java:85) ~[cattle-config-item-common-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.servicediscovery.deployment.impl.manager.DeploymentUnitManagerImpl.deploymentUnitUpdate(DeploymentUnitManagerImpl.java:156) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
        at sun.reflect.GeneratedMethodAccessor1899.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_72]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_72]
        at io.cattle.platform.eventing.annotation.MethodInvokingListener$1.doWithLockNoResult(MethodInvokingListener.java:76) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.eventing.annotation.MethodInvokingListener.onEvent(MethodInvokingListener.java:72) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:141) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
Caused by: java.sql.SQLDataException: (conn:36915) Data too long for column 'description' at row 1
Query is: insert into `service_log` (`account_id`, `kind`, `description`, `created`, `data`, `end_time`, `event_type`, `service_id`, `instance_id`, `transaction_id`, `sub_log`, `level`, `deployment_unit_id`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), parameters [5,'serviceLog','SQL [insert into `instance` (`name`, `account_id`, `kind`, `uuid`, `state`, `created`, `data`, `allocation_state`, `zone_id`, `instance_triggered_stop`, `network_container_id`, `start_count`, `create_index`, `deployment_unit_uuid`, `version`, `service_index_id`, `system`, `service_id`, `environment_id`, `deployment_unit_id`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; (conn:36914) Deadlock found when trying to get lock; try restarting transaction
Query is: insert into `instance` (`name`, `account_id`, `kind`, `uuid`, `state`, `created`, `data`, `allocation_state`, `zone_id`, `instance_triggered_stop`, `network_container_id`, `start_count`, `create_index`, `deployment_unit_uuid`, `version`, `service_index_id`, `s...
        at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:129) ~[mariadb-java-client-1.5.8.jar:na]
        at org.mariadb.jdbc.internal.util.ExceptionMapper.getException(ExceptionMapper.java:101) ~[mariadb-java-client-1.5.8.jar:na]
        at org.mariadb.jdbc.internal.util.ExceptionMapper.throwAndLogException(ExceptionMapper.java:77) ~[mariadb-java-client-1.5.8.jar:na]
        at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:224) ~[mariadb-java-client-1.5.8.jar:na]
        at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:411) ~[mariadb-java-client-1.5.8.jar:na]
        at org.mariadb.jdbc.MariaDbServerPreparedStatement.execute(MariaDbServerPreparedStatement.java:361) ~[mariadb-java-client-1.5.8.jar:na]
        at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeUpdate(MariaDbServerPreparedStatement.java:350) ~[mariadb-java-client-1.5.8.jar:na]
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
        at org.jooq.tools.jdbc.DefaultPreparedStatement.executeUpdate(DefaultPreparedStatement.java:88) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.AbstractStoreQuery.execute(AbstractStoreQuery.java:346) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:322) ~[jooq-3.3.0.jar:na]
        ... 46 common frames omitted
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Data too long for column 'description' at row 1
Query is: insert into `service_log` (`account_id`, `kind`, `description`, `created`, `data`, `end_time`, `event_type`, `service_id`, `instance_id`, `transaction_id`, `sub_log`, `level`, `deployment_unit_id`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), parameters [5,'serviceLog','SQL [insert into `instance` (`name`, `account_id`, `kind`, `uuid`, `state`, `created`, `data`, `allocation_state`, `zone_id`, `instance_triggered_stop`, `network_container_id`, `start_count`, `create_index`, `deployment_unit_uuid`, `version`, `service_index_id`, `system`, `service_id`, `environment_id`, `deployment_unit_id`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; (conn:36914) Deadlock found when trying to get lock; try restarting transaction
Query is: insert into `instance` (`name`, `account_id`, `kind`, `uuid`, `state`, `created`, `data`, `allocation_state`, `zone_id`, `instance_triggered_stop`, `network_container_id`, `start_count`, `create_index`, `deployment_unit_uuid`, `version`, `service_index_id`, `s...
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1115) ~[mariadb-java-client-1.5.8.jar:na]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1047) ~[mariadb-java-client-1.5.8.jar:na]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1002) ~[mariadb-java-client-1.5.8.jar:na]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executePreparedQuery(AbstractQueryProtocol.java:588) ~[mariadb-java-client-1.5.8.jar:na]
        at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:399) ~[mariadb-java-client-1.5.8.jar:na]
        ... 53 common frames omitted

2017-03-29 16:57:27,965 DEBUG [:] [] [] [] [ecutorService-7] [i.c.p.a.i.d.i.AgentInstanceDaoImpl  ] Priority value not found for agent 4456. Set it as default 
2
```

**Comment by sangeethah** [comment]
Tested with build from master.

No sql exceptions seen in rancher-server logs when trying to deploy services/standalone containers/load balancers.
