### ISSUE TITLE
rancher/net container cannot startup due to rancher-matadata missing

### ISSUE THREAD

**Issue by snipking** [rancher/rancher#8368]
**Rancher Versions:**
Server: 1.5.2
healthcheck: latest match rancher 1.5.2
ipsec: latest match rancher 1.5.2
vxlan: latest match rancher 1.5.2
network-services: latest match rancher 1.5.2
scheduler: latest match rancher 1.5.2
kubernetes (if applicable):

**Docker Version:**
Docker version 1.12.6, build d5236f0

**OS and where are the hosts located? (cloud, bare metal, etc):**
CoreOS 1298.6.0 on Azure or self hosted PC Server

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
After host reboot, found some host shows rancher/net startup failed. The log below.

```

+ trap 'exit 1' SIGTERM SIGINT
+ export PIDFILE=/var/run/rancher-net.pid
+ PIDFILE=/var/run/rancher-net.pid
++ grep via
++ ip route get 8.8.8.8
++ awk '{print $7}'
+ export LOCAL_IP=10.42.116.167
+ LOCAL_IP=10.42.116.167
+ '[' false == true ']'
+ DEBUG=
++ ip route get 8.8.8.8
++ awk '{print $3}'
+ GATEWAY=10.42.0.1
+ iptables -t nat -I POSTROUTING -o vtep1042 -s 10.42.0.1 -j MASQUERADE
+ exec rancher-net -i 10.42.116.167/16 --pid-file /var/run/rancher-net.pid --use-metadata --backend vxlan
time="2017-03-31T01:48:07Z" level=info msg="Writing pid 1 to /var/run/rancher-net.pid"
time="2017-03-31T01:48:07Z" level=info msg="Using backend: vxlan"
time="2017-03-31T01:48:07Z" level=info msg="Using metadata: true"
time="2017-03-31T01:48:07Z" level=info msg="Reading info from metadata"
time="2017-03-31T01:48:07Z" level=error msg="couldn't get self container from metadata: Error 404 accessing /self/container path"
time="2017-03-31T01:48:07Z" level=error msg="error: invalid CIDR address: "
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x77b940, 0xc420014090)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/rancher/rancher-net/vendor/github.com/codegangsta/cli.HandleAction.func1(0xc4200e5980)
	/go/src/github.com/rancher/rancher-net/vendor/github.com/codegangsta/cli/app.go:478 +0x247
panic(0x77b940, 0xc420014090)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/rancher/rancher-net/backend/vxlan.getMACAddressForVxlanIP(0x7e6df8, 0x11, 0x0, 0x0, 0x0, 0x9, 0x6, 0x0, 0x0, 0xc41fff6eff)
	/go/src/github.com/rancher/rancher-net/backend/vxlan/vxlan_utils.go:163 +0x10e
github.com/rancher/rancher-net/backend/vxlan.(*Overlay).GetMyVTEPInfo(0xc420017130, 0x23, 0x0, 0x0, 0x0, 0xc42000f201)
	/go/src/github.com/rancher/rancher-net/backend/vxlan/vxlan.go:393 +0x1a4
github.com/rancher/rancher-net/backend/vxlan.(*Overlay).getDefaultVxlanInterfaceInfo(0xc420017130, 0xc420017130, 0xc4200e51f0, 0x1)
	/go/src/github.com/rancher/rancher-net/backend/vxlan/vxlan.go:404 +0x66
github.com/rancher/rancher-net/backend/vxlan.NewOverlay(0x0, 0x0, 0x989a40, 0xc420122000, 0x1, 0x1a4, 0x0)
	/go/src/github.com/rancher/rancher-net/backend/vxlan/vxlan.go:55 +0x104
main.appMain(0xc42009e3c0, 0xc420090b00, 0xc420090b28)
	/go/src/github.com/rancher/rancher-net/main.go:165 +0xaaf
main.main.func1(0xc42009e3c0)
	/go/src/github.com/rancher/rancher-net/main.go:88 +0x2f
reflect.Value.call(0x75a040, 0x816a48, 0x13, 0x7e28bd, 0x4, 0xc4200e5940, 0x1, 0x1, 0x48f698, 0x7d7b00, ...)
	/usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x75a040, 0x816a48, 0x13, 0xc4200e5940, 0x1, 0x1, 0x1, 0x2, 0x2)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/rancher/rancher-net/vendor/github.com/codegangsta/cli.HandleAction(0x75a040, 0x816a48, 0xc42009e3c0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher-net/vendor/github.com/codegangsta/cli/app.go:487 +0x1e0
github.com/rancher/rancher-net/vendor/github.com/codegangsta/cli.(*App).Run(0xc4200da000, 0xc42000a100, 0x8, 0x8, 0x0, 0x0)
	/go/src/github.com/rancher/rancher-net/vendor/github.com/codegangsta/cli/app.go:245 +0x59b
main.main()
	/go/src/github.com/rancher/rancher-net/main.go:93 +0x8d5
```

After some investigation we found the cause is rancher metadata service. When I call `curl http://rancher-metadata/2015-12-19/self` on a working host container which use `Managed` network, it returns below.

```
container/
host/
service/
stack/
```

But when I call it on a failed host container which use `Managed` network, it returns below.

```
host/
```

I've tried to restart the metadata container even delete it and let rancher re-run it. But still not working.

Also there are some error in metadata container log.

```
time="2017-03-31T02:57:27Z" level=info msg="Subscribing to events" 
time="2017-03-31T02:57:28Z" level=info msg="Starting rancher-metadata v0.8.11" 
time="2017-03-31T02:57:28Z" level=info msg="Loading answers" 
time="2017-03-31T02:57:28Z" level=warning msg="Failed to find: ./answers.json" 
time="2017-03-31T02:57:28Z" level=info msg="Loaded answers from file" 
time="2017-03-31T02:57:28Z" level=info msg="Listening for Reload on 127.0.0.1:8112" 
time="2017-03-31T02:57:28Z" level=info msg="Listening on :80" 
time="2017-03-31T02:57:28Z" level=info msg="Initializing event router" workerCount=3 
time="2017-03-31T02:57:28Z" level=info msg="Connection established" 
time="2017-03-31T02:57:28Z" level=info msg="Starting websocket pings" 
time="2017-03-31T02:57:28Z" level=info msg="Downloaded in 5.164225ms" 
time="2017-03-31T02:57:28Z" level=info msg="Generating and reloading answers" 
time="2017-03-31T02:57:28Z" level=info msg="Generating answers" 
time="2017-03-31T02:57:28Z" level=info msg="Generated and reloaded answers" 
time="2017-03-31T02:57:28Z" level=info msg="Applied http://10.213.0.19:8180/v1/configcontent/metadata-answers?client=v2&requestedVersion=?version=16446-14a7928f14789d3a00ab33efdfd9c22c" 

...

time="2017-03-31T02:58:21Z" level=info msg="Download and reload in: 47.187279ms" 
time="2017-03-31T02:58:30Z" level=info msg="Error: /self/container" client=172.17.0.1 version=2016-07-29 
time="2017-03-31T02:58:31Z" level=info msg="Error: /self/container" client=172.17.0.1 version=2016-07-29 
time="2017-03-31T02:58:32Z" level=info msg="Error: /self/container" client=172.17.0.1 version=2016-07-29 
time="2017-03-31T02:58:33Z" level=info msg="Error: /self/container" client=172.17.0.1 version=2016-07-29 
time="2017-03-31T02:58:33Z" level=info msg="Error: /self/container" client=172.17.0.1 version=2016-07-29 
time="2017-03-31T02:58:34Z" level=info msg="Error: /self/container" client=172.17.0.1 version=2016-07-29 
time="2017-03-31T02:59:35Z" level=info msg="Update requested for version: 16463" 
time="2017-03-31T02:59:35Z" level=info msg="Downloaded in 29.122177ms" 
time="2017-03-31T02:59:35Z" level=info msg="Generating and reloading answers" 
time="2017-03-31T02:59:35Z" level=info msg="Generating answers" 
time="2017-03-31T02:59:35Z" level=info msg="Generated and reloaded answers" 
time="2017-03-31T02:59:35Z" level=info msg="Applied http://10.213.0.19:8180/v1/configcontent/metadata-answers?client=v2&requestedVersion=16463?version=16463-14a7928f14789d3a00ab33efdfd9c22c" 

...
```

**Results:** 

Is it a bug? Any work around?

**Comment by snipking** [comment]
We've tried:

- Reboot host server
- Delete rancher-agent & network stack & vxlan stack, then re-add the host to the rancher environment
- downgrade the network stack version (0.1.1 to 0.1.0)

Still not work and totally no idea.

PS. Currently only one host which also run rancher-server can't get metadata work. And it works yesterday. This issue happens after a host reboot.

**Comment by niusmallnan** [comment]
Hi @snipking,
Did you have a try on AWS or Aliyun?
I am a Rancher engineer in China, maybe I can help you.

shoud I reproduce this issue on Azure China?

BTW, my wechat ID: niusmallnan

**Comment by fedya** [comment]
`time="2017-04-15T21:21:30Z" level=error msg="Error processing event &docker.APIEvents{Action:\"start\", Type:\"container\", Actor:docker.APIActor{ID:\"b7bb4ba531471279b7a9287e0f33334f9cf08d5e5c41cc44c624b70ca86be15d\", Attributes:map[string]string{\"io.rancher.stack.name\":\"scheduler\", \"image\":\"rancher/scheduler:v0.6.3\", \"io.rancher.container.agent_id\":\"230\", \"io.rancher.container.name\":\"scheduler-scheduler1-1\", \"io.rancher.container.system\":\"true\", \"io.rancher.project.name\":\"scheduler\", \"io.rancher.service.deployment.unit\":\"59afcdac-420d-41e0-b930-d497d8df4a15\", \"io.rancher.service.launch.config\":\"io.rancher.service.primary.launch.config\", \"io.rancher.container.agent_service.scheduling\":\"true\", \"io.rancher.container.ip\":\"10.42.244.187/16\", \"io.rancher.container.uuid\":\"2b9e1965-19a6-4847-a536-7fc21406ec57\", \"io.rancher.cni.wait\":\"true\", \"io.rancher.container.create_agent\":\"true\", \"io.rancher.container.mac_address\":\"02:23:9d:f0:09:0d\", \"io.rancher.project_service.name\":\"scheduler/scheduler1\", \"io.rancher.stack_service.name\":\"scheduler/scheduler1\", \"name\":\"r-scheduler-scheduler1-1-2b9e1965\", \"io.rancher.cni.network\":\"ipsec\"}}, Status:\"start\", ID:\"b7bb4ba531471279b7a9287e0f33334f9cf08d5e5c41cc44c624b70ca86be15d\", From:\"rancher/scheduler:v0.6.3\", Time:1492291290, TimeNano:1492291290540136485}. Error: netplugin failed but error parsing its diagnostic message \"\": unexpected end of JSON input" `

**Comment by superseb** [comment]
How many hosts/environments do you have?

Are you running `rancher/server` and `rancher/agent` on the same host? What IPs are displayed your Infrastructure -> Hosts view?

**Comment by aemneina** [comment]
@snipking can you share the output from `docker info` and `ip link` of `ifconfig` output for the docker bridge interface?

**Comment by snipking** [comment]
docker info

```
Containers: 37
 Running: 26
 Paused: 0
 Stopped: 11
Images: 95
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp selinux
Kernel Version: 4.11.12-coreos-r1
Operating System: Container Linux by CoreOS 1409.8.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 24.53 GiB
Name: coreos1
ID: ZBAR:RL72:ULJ6:CLCG:SFU5:SGW3:BX4S:KJ27:GSZH:KW6D:I2ZO:A6BM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: tomaer
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

ip link

```
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether 02:42:19:e4:38:b9 brd ff:ff:ff:ff:ff:ff
```

ifconfig

```
docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 0.0.0.0
        inet6 fe80::42:19ff:fee4:38b9  prefixlen 64  scopeid 0x20<link>
        ether 02:42:19:e4:38:b9  txqueuelen 0  (Ethernet)
        RX packets 46416413  bytes 131509253106 (122.4 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 49918557  bytes 26498512736 (24.6 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by tuwid** [comment]
same behaviour with 1.6.10

**Comment by thilobillerbeck** [comment]
I experience the same behavior too in 1.6.10 on Docker 17.06.2-ce

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
