### ISSUE TITLE
network-manager crashes and keeps restarting.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8432]
Rancher Versions:v1.1.4

Deploy K8s env.
Point "Library" catalog to  - https://github.com/rancher/rancher-catalog branch - v1.4.3-updates.
Update  ipsec , network-manager and ipsec services that have "upgrade required" option.

Bring down the host where kube-dns pod is running.
Wait for kube-dns pod to get recreated in a different host ( takes atleast 5 minutes for this to happen).
After this , try to ping google.com from user pod container.
Notice that there is packet loss.
Also network-manager on the host where this user pod was present , keeps crashing and restarting.
Following exceptions see in logs:
```
4/5/2017 7:57:07 PMtime="2017-04-06T02:57:07Z" level=info msg="Setting up resolv.conf for ContainerId [b3947c44113077493324935f0e70f97604df6676fd79d56896271e81e563206b]"
4/5/2017 7:57:07 PMpanic: runtime error: index out of range
4/5/2017 7:57:07 PM
4/5/2017 7:57:07 PMgoroutine 76 [running]:
4/5/2017 7:57:07 PMpanic(0x8c65e0, 0xc420016090)
4/5/2017 7:57:07 PM /usr/local/go/src/runtime/panic.go:500 +0x1a1
4/5/2017 7:57:07 PMgithub.com/rancher/plugin-manager/conntracksync/conntrack.parseOneConntrackEntry(0xc420690744, 0x97, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
4/5/2017 7:57:07 PM /go/src/github.com/rancher/plugin-manager/conntracksync/conntrack/conntrack.go:153 +0x524
4/5/2017 7:57:07 PMgithub.com/rancher/plugin-manager/conntracksync/conntrack.parseMultipleEntries(0xc420642000, 0x539a1, 0x539a1, 0x7fe00, 0xc420642000)
4/5/2017 7:57:07 PM /go/src/github.com/rancher/plugin-manager/conntracksync/conntrack/conntrack.go:111 +0xd3
4/5/2017 7:57:07 PMgithub.com/rancher/plugin-manager/conntracksync/conntrack.cmdCTListDNAT(0x24, 0xc420240690, 0x1, 0xc420240480, 0x24)
4/5/2017 7:57:07 PM /go/src/github.com/rancher/plugin-manager/conntracksync/conntrack/conntrack.go:102 +0xe8
4/5/2017 7:57:07 PMgithub.com/rancher/plugin-manager/conntracksync/conntrack.ListDNAT(0xc42049a720, 0xc420240780, 0x0, 0x0, 0x0)
4/5/2017 7:57:07 PM /go/src/github.com/rancher/plugin-manager/conntracksync/conntrack/conntrack.go:46 +0x22
4/5/2017 7:57:07 PMgithub.com/rancher/plugin-manager/conntracksync.(*ConntrackTableWatcher).doSync(0xc42049a720, 0x31c4ff25, 0xd8ac80)
4/5/2017 7:57:07 PM /go/src/github.com/rancher/plugin-manager/conntracksync/watcher.go:70 +0x9b
4/5/2017 7:57:07 PMgithub.com/rancher/plugin-manager/conntracksync.(*ConntrackTableWatcher).onChangeNoError(0xc42049a720, 0xc42024af00, 0x25)
4/5/2017 7:57:07 PM /go/src/github.com/rancher/plugin-manager/conntracksync/watcher.go:57 +0x1b1
4/5/2017 7:57:07 PMgithub.com/rancher/plugin-manager/conntracksync.(*ConntrackTableWatcher).(github.com/rancher/plugin-manager/conntracksync.onChangeNoError)-fm(0xc42024af00, 0x25)
4/5/2017 7:57:07 PM /go/src/github.com/rancher/plugin-manager/conntracksync/watcher.go:44 +0x3e
4/5/2017 7:57:07 PMgithub.com/rancher/plugin-manager/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).OnChange.func1(0xc42024af00, 0x25)
4/5/2017 7:57:07 PM /go/src/github.com/rancher/plugin-manager/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:36 +0x5f
4/5/2017 7:57:07 PMgithub.com/rancher/plugin-manager/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).onChangeFromVersionWithError(0xc4202dcb70, 0x94b501, 0x4, 0x78, 0xc420415f60, 0x0, 0x0)
4/5/2017 7:57:07 PM /go/src/github.com/rancher/plugin-manager/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:25 +0x1e5
4/5/2017 7:57:07 PMgithub.com/rancher/plugin-manager/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).OnChange(0xc4202dcb70, 0x78, 0xc420482630)
4/5/2017 7:57:07 PM /go/src/github.com/rancher/plugin-manager/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:40 +0xa6
4/5/2017 7:57:07 PMcreated by github.com/rancher/plugin-manager/conntracksync.Watch
4/5/2017 7:57:07 PM /go/src/github.com/rancher/plugin-manager/conntracksync/watcher.go:44 +0x1d8
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="routesync: DOCKER_BRIDGE=docker0, METADATA_IP=169.254.169.250"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="routesync: starting monitoring on bridge: docker0, for metadataIP: 169.254.169.250 every 60 seconds"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Waiting for metadata"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Inspecting on start" cid=2d1892c7e4e0447e32fb32249c6cce471797cd0a75b5176d827ae4317aeb3024 running=true startedAt="2017-04-06T02:19:17.786334537Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Recording previously started" cid=2d1892c7e4e0447e32fb32249c6cce471797cd0a75b5176d827ae4317aeb3024 startedAt="2017-04-06T02:19:17.786334537Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Inspecting on start" cid=e4b7a56f1b18723121568109dc77da17b01af3d57dd5301afa309a122acc061a running=true startedAt="2017-04-06T02:19:03.096825613Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Recording previously started" cid=e4b7a56f1b18723121568109dc77da17b01af3d57dd5301afa309a122acc061a startedAt="2017-04-06T02:19:03.096825613Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Inspecting on start" cid=da42f912d2c984089e4ee13a83c2174963dd37914feda433c748b0ce5828b51a running=true startedAt="2017-04-06T02:18:47.030869421Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Recording previously started" cid=da42f912d2c984089e4ee13a83c2174963dd37914feda433c748b0ce5828b51a startedAt="2017-04-06T02:18:47.030869421Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Inspecting on start" cid=10196fbe514e48757160238ffee1a216617cdeabeb3ae72d6d50bcd66ea0986f running=true startedAt="2017-04-06T01:42:38.601182313Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Recording previously started" cid=10196fbe514e48757160238ffee1a216617cdeabeb3ae72d6d50bcd66ea0986f startedAt="2017-04-06T01:42:38.601182313Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Inspecting on start" cid=d0a1beaa8a885b4b5adab42df3a6eb661c3401383f4a2a74e106fd7cfcbe8a0c running=true startedAt="2017-04-06T01:42:19.66608264Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Recording previously started" cid=d0a1beaa8a885b4b5adab42df3a6eb661c3401383f4a2a74e106fd7cfcbe8a0c startedAt="2017-04-06T01:42:19.66608264Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Inspecting on start" cid=d98eddf7848a51579baddc8d667cca638f66b62222eb356484f8cb0781653b45 running=true startedAt="2017-04-06T01:42:19.700003083Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Recording previously started" cid=d98eddf7848a51579baddc8d667cca638f66b62222eb356484f8cb0781653b45 startedAt="2017-04-06T01:42:19.700003083Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Inspecting on start" cid=0bd3d98c5e3e3c6c6589e2b87f8e954ac154d9c3381d3a51189bf75127759034 running=true startedAt="2017-04-06T01:39:12.931054712Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Recording previously started" cid=0bd3d98c5e3e3c6c6589e2b87f8e954ac154d9c3381d3a51189bf75127759034 startedAt="2017-04-06T01:39:12.931054712Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Inspecting on start" cid=c5599b0f787efb11125424e6efc328695966bbd643d1cd4a4bb451edc963466a running=true startedAt="2017-04-06T02:57:07.9831684Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Recording previously started" cid=c5599b0f787efb11125424e6efc328695966bbd643d1cd4a4bb451edc963466a startedAt="2017-04-06T02:57:07.9831684Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Inspecting on start" cid=2a8548d6dd2d5a29dabd50f49a3dc6539346cc809785307f25f0ae63ab433246 running=true startedAt="2017-04-06T01:32:52.937603356Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Recording previously started" cid=2a8548d6dd2d5a29dabd50f49a3dc6539346cc809785307f25f0ae63ab433246 startedAt="2017-04-06T01:32:52.937603356Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Inspecting on start" cid=239099bcf63ee042d9bed0f5f3872d4bb88b734eb1a8c319b9eba79d76ac806c running=true startedAt="2017-04-06T01:32:37.522840362Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Recording previously started" cid=239099bcf63ee042d9bed0f5f3872d4bb88b734eb1a8c319b9eba79d76ac806c startedAt="2017-04-06T01:32:37.522840362Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Inspecting on start" cid=ab98487f7dc2f8286fffa3e8a048333b9dd23f0c4996b863577afd7171054b52 running=true startedAt="2017-04-06T01:32:31.798905617Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Recording previously started" cid=ab98487f7dc2f8286fffa3e8a048333b9dd23f0c4996b863577afd7171054b52 startedAt="2017-04-06T01:32:31.798905617Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Inspecting on start" cid=b3947c44113077493324935f0e70f97604df6676fd79d56896271e81e563206b running=true startedAt="2017-04-06T01:32:29.93714474Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Recording previously started" cid=b3947c44113077493324935f0e70f97604df6676fd79d56896271e81e563206b startedAt="2017-04-06T01:32:29.93714474Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Inspecting on start" cid=f6d1e99292621516ed8c32ee664f4e5eab591c1cc02f8274ea9e2102f333cf32 running=true startedAt="2017-04-06T01:29:46.245973982Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Recording previously started" cid=f6d1e99292621516ed8c32ee664f4e5eab591c1cc02f8274ea9e2102f333cf32 startedAt="2017-04-06T01:29:46.245973982Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Inspecting on start" cid=145bfff7bf75ea2a8946d13414bc806eb786259cca36b04fbfa700a8acce6356 running=true startedAt="2017-04-06T01:29:35.340759009Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Recording previously started" cid=145bfff7bf75ea2a8946d13414bc806eb786259cca36b04fbfa700a8acce6356 startedAt="2017-04-06T01:29:35.340759009Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Inspecting on start" cid=60c68edae1895b6fd0b39b1f46c1184b106d3725fb2d0227d8253c8aef71ac55 running=true startedAt="2017-04-06T01:17:11.377729102Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Recording previously started" cid=60c68edae1895b6fd0b39b1f46c1184b106d3725fb2d0227d8253c8aef71ac55 startedAt="2017-04-06T01:17:11.377729102Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Inspecting on start" cid=1b027a8cd0b547415cb4c60a99b6e610c32818df2b1029020628c2ffbee9c168 running=true startedAt="2017-04-06T01:17:10.927278836Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Recording previously started" cid=1b027a8cd0b547415cb4c60a99b6e610c32818df2b1029020628c2ffbee9c168 startedAt="2017-04-06T01:17:10.927278836Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Inspecting on start" cid=bf0d0f677fc6a633bae27b410bdf033ddc5e4d3ed02d6b3d873ca31cd6c61777 running=true startedAt="2017-04-06T01:16:17.590864564Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Recording previously started" cid=bf0d0f677fc6a633bae27b410bdf033ddc5e4d3ed02d6b3d873ca31cd6c61777 startedAt="2017-04-06T01:16:17.590864564Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Inspecting on start" cid=aaafe8cc033d733507601a454ae40715fb620b6fed84d0469c48229db39b4258 running=true startedAt="2017-04-06T01:16:13.541075565Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Recording previously started" cid=aaafe8cc033d733507601a454ae40715fb620b6fed84d0469c48229db39b4258 startedAt="2017-04-06T01:16:13.541075565Z"
4/5/2017 7:57:10 PMtime="2017-04-06T02:57:10Z" level=info msg="Inspecting on start" cid=347cb9e07740d91dcd0f8ce47e482e28c38d1397dc89db73c6cbdee8d1d38308 running=false startedAt="2017-04-06T01:15:56.976383509Z"
```

**Comment by sangeethah** [comment]
Rancher Versions:v1.1.4

Deploy K8s env.
Point "Library" catalog to - https://github.com/rancher/rancher-catalog branch - v1.4.3-updates.
Update ipsec , network-manager and ipsec services that have "upgrade required" option.

Bring down the host where kube-dns pod is running.
Wait for kube-dns pod to get recreated in a different host ( takes atleast 5 minutes for this to happen).
After this , try to ping google.com from user pod container.
There is no packet loss when pinging google.com. 
Also network-manager does not crash.
