### ISSUE TITLE
lb-service-haproxy Run Exception

### ISSUE THREAD

**Issue by XdaTk** [rancher/rancher#8434]
**Rancher Versions:**
Server: 1.5.3
healthcheck: v0.2.3
vxlan: v0.9.4
network-services: metadata:v0.8.11 network-manager:v0.5.3
scheduler:v0.7.5

**Docker Version:**
1.12.6 (yum install docker)

**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS 7.3

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher and external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

** Host Info **

Aliyun VPC 10.0.0.0/8

**Steps to Reproduce:**

Deployed a Ghost, the use of load balancing for port mapping, load balancing can not start, has been tested 0.6.4-> 0.5.9 all versions

docker-compose.yml 

```yml
version: '2'
services:
  ghost:
    image: ghost
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  ghostHa:
    image: rancher/lb-service-haproxy:v0.6.2
    ports:
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
```

rancher-compose.yml
```yml
version: '2'
services:
  ghost:
    scale: 1
    start_on_create: true
  ghostHa:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ghost.zhongfl.io
        path: ''
        priority: 1
        protocol: http
        service: ghost
        source_port: 80
        target_port: 2368
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000
```

**Results:** 

Error Info

```

2017/4/6 下午5:13:08goroutine 37 [IO wait]:
2017/4/6 下午5:13:08net.runtime_pollWait(0x7f7c24531b68, 0x72, 0x0)
2017/4/6 下午5:13:08	/usr/local/go/src/runtime/netpoll.go:160 +0x60
2017/4/6 下午5:13:08net.(*pollDesc).Wait(0xc82038c610, 0x72, 0x0, 0x0)
2017/4/6 下午5:13:08	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
2017/4/6 下午5:13:08net.(*pollDesc).WaitRead(0xc82038c610, 0x0, 0x0)
2017/4/6 下午5:13:08	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
2017/4/6 下午5:13:08net.(*netFD).accept(0xc82038c5b0, 0x0, 0x7f7c24527900, 0xc82052c1c0)
2017/4/6 下午5:13:08	/usr/local/go/src/net/fd_unix.go:426 +0x27c
2017/4/6 下午5:13:08net.(*TCPListener).AcceptTCP(0xc8200244e8, 0x4c0771, 0x0, 0x0)
2017/4/6 下午5:13:08	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
2017/4/6 下午5:13:08net/http.tcpKeepAliveListener.Accept(0xc8200244e8, 0x0, 0x0, 0x0, 0x0)
2017/4/6 下午5:13:08	/usr/local/go/src/net/http/server.go:2427 +0x41
2017/4/6 下午5:13:08net/http.(*Server).Serve(0xc820014680, 0x7f7c225a1408, 0xc8200244e8, 0x0, 0x0)
2017/4/6 下午5:13:08	/usr/local/go/src/net/http/server.go:2117 +0x129
2017/4/6 下午5:13:08net/http.(*Server).ListenAndServe(0xc820014680, 0x0, 0x0)
2017/4/6 下午5:13:08	/usr/local/go/src/net/http/server.go:2098 +0x136
2017/4/6 下午5:13:08net/http.ListenAndServe(0x254b980, 0x6, 0x7f7c225a13a8, 0xc82023a5f0, 0x0, 0x0)
2017/4/6 下午5:13:08	/usr/local/go/src/net/http/server.go:2195 +0x98
2017/4/6 下午5:13:08main.startHealthcheck()
2017/4/6 下午5:13:08	/go/src/github.com/rancher/lb-controller/healthcheck.go:17 +0x28c
2017/4/6 下午5:13:08created by main.main
2017/4/6 下午5:13:08	/go/src/github.com/rancher/lb-controller/main.go:47 +0x2b4
2017/4/6 下午5:13:08goroutine 38 [semacquire]:
2017/4/6 下午5:13:08sync.runtime_Syncsemacquire(0xc820012350)
2017/4/6 下午5:13:08	/usr/local/go/src/runtime/sema.go:241 +0x201
2017/4/6 下午5:13:08sync.(*Cond).Wait(0xc820012340)
2017/4/6 下午5:13:08	/usr/local/go/src/sync/cond.go:63 +0x9b
2017/4/6 下午5:13:08github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/workqueue.(*Type).Get(0xc82000a5a0, 0x0, 0x0, 0x0)
2017/4/6 下午5:13:08	/go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/workqueue/queue.go:124 +0x102
2017/4/6 下午5:13:08github.com/rancher/lb-controller/utils.(*TaskQueue).worker(0xc8200b4a00)
2017/4/6 下午5:13:08	/go/src/github.com/rancher/lb-controller/utils/utils.go:58 +0x30
2017/4/6 下午5:13:08github.com/rancher/lb-controller/utils.(*TaskQueue).(github.com/rancher/lb-controller/utils.worker)-fm()
2017/4/6 下午5:13:08	/go/src/github.com/rancher/lb-controller/utils/utils.go:33 +0x20
2017/4/6 下午5:13:08github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc82001df90)
2017/4/6 下午5:13:08	/go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:84 +0x19
2017/4/6 下午5:13:08github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc82001df90, 0x3b9aca00, 0x0, 0x1, 0xc82005a540)
2017/4/6 下午5:13:08	/go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:85 +0xb4
2017/4/6 下午5:13:08github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.Until(0xc82001df90, 0x3b9aca00, 0xc82005a540)
2017/4/6 下午5:13:08	/go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x43
2017/4/6 下午5:13:08github.com/rancher/lb-controller/utils.(*TaskQueue).Run(0xc8200b4a00, 0x3b9aca00, 0xc82005a540)
2017/4/6 下午5:13:08	/go/src/github.com/rancher/lb-controller/utils/utils.go:33 +0x48
2017/4/6 下午5:13:08created by github.com/rancher/lb-controller/controller/rancher.(*LoadBalancerController).Run
2017/4/6 下午5:13:08	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:105 +0x19c
2017/4/6 下午5:13:08goroutine 39 [runnable]:
2017/4/6 下午5:13:08syscall.Syscall(0x0, 0xc, 0xc820036910, 0x8, 0x0, 0x8, 0x0)
2017/4/6 下午5:13:08	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
2017/4/6 下午5:13:08syscall.readlen(0xc, 0xc820036910, 0x8, 0x4, 0x0, 0x0)
2017/4/6 下午5:13:08	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1085 +0x51
2017/4/6 下午5:13:08syscall.forkExec(0xc82051c259, 0x7, 0xc82051e390, 0x3, 0x3, 0xc820036ae0, 0x10, 0x0, 0x0)
2017/4/6 下午5:13:08	/usr/local/go/src/syscall/exec_unix.go:202 +0x567
2017/4/6 下午5:13:08syscall.StartProcess(0xc82051c259, 0x7, 0xc82051e390, 0x3, 0x3, 0xc820036ae0, 0x2, 0x4, 0x0, 0x0)
2017/4/6 下午5:13:08	/usr/local/go/src/syscall/exec_unix.go:240 +0x6b
2017/4/6 下午5:13:08os.startProcess(0xc82051c259, 0x7, 0xc82051e390, 0x3, 0x3, 0xc820036d18, 0xc820310500, 0x0, 0x0)
2017/4/6 下午5:13:08	/usr/local/go/src/os/exec_posix.go:45 +0x33e
2017/4/6 下午5:13:08os.StartProcess(0xc82051c259, 0x7, 0xc82051e390, 0x3, 0x3, 0xc820036d18, 0x0, 0x0, 0x0)
2017/4/6 下午5:13:08	/usr/local/go/src/os/doc.go:28 +0x69
2017/4/6 下午5:13:08os/exec.(*Cmd).Start(0xc820152500, 0x0, 0x0)
2017/4/6 下午5:13:08	/usr/local/go/src/os/exec/exec.go:332 +0x761
2017/4/6 下午5:13:08os/exec.(*Cmd).Run(0xc820152500, 0x0, 0x0)
2017/4/6 下午5:13:08	/usr/local/go/src/os/exec/exec.go:259 +0x2d
2017/4/6 下午5:13:08os/exec.(*Cmd).CombinedOutput(0xc820152500, 0x0, 0x0, 0x0, 0x0, 0x0)
2017/4/6 下午5:13:08	/usr/local/go/src/os/exec/exec.go:453 +0x310
2017/4/6 下午5:13:08github.com/rancher/lb-controller/provider/haproxy.(*haproxyConfig).start(0xc82005a900, 0x0, 0x0)
2017/4/6 下午5:13:08	/go/src/github.com/rancher/lb-controller/provider/haproxy/haproxy.go:158 +0x114
2017/4/6 下午5:13:08github.com/rancher/lb-controller/provider/haproxy.(*Provider).StartHaproxy(0xc8200b4a80, 0x0, 0x0)
2017/4/6 下午5:13:08	/go/src/github.com/rancher/lb-controller/provider/haproxy/haproxy.go:182 +0x30
2017/4/6 下午5:13:08github.com/rancher/lb-controller/provider/haproxy.(*Provider).Run(0xc8200b4a80, 0x0)
2017/4/6 下午5:13:08	/go/src/github.com/rancher/lb-controller/provider/haproxy/haproxy.go:190 +0x21
2017/4/6 下午5:13:08created by github.com/rancher/lb-controller/controller/rancher.(*LoadBalancerController).Run
2017/4/6 下午5:13:08	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:107 +0x1f3
2017/4/6 下午5:13:08goroutine 40 [runnable]:
2017/4/6 下午5:13:08net/http.setRequestCancel.func4(0x0, 0xc8204f9f50, 0xc8204ff9c0, 0xc820504f60)
2017/4/6 下午5:13:08	/usr/local/go/src/net/http/client.go:332
2017/4/6 下午5:13:08created by net/http.setRequestCancel
2017/4/6 下午5:13:08	/usr/local/go/src/net/http/client.go:341 +0x2f7
2017/4/6 下午5:13:08goroutine 41 [select]:
2017/4/6 下午5:13:08net.lookupIPDeadline(0xc8205145e0, 0x10, 0xed077fdc2, 0x34bc0924, 0x3667ba0, 0x0, 0x0, 0x0, 0x0, 0x0)
2017/4/6 下午5:13:08	/usr/local/go/src/net/lookup.go:109 +0x6a6
2017/4/6 下午5:13:08net.internetAddrList(0x2555df0, 0x3, 0xc8205145e0, 0x13, 0xed077fdc2, 0x34bc0924, 0x3667ba0, 0x0, 0x0, 0x0, ...)
2017/4/6 下午5:13:08	/usr/local/go/src/net/ipsock.go:252 +0x6ee
2017/4/6 下午5:13:08net.resolveAddrList(0x25511e0, 0x4, 0x2555df0, 0x3, 0xc8205145e0, 0x13, 0xed077fdc2, 0x34bc0924, 0x3667ba0, 0x0, ...)
2017/4/6 下午5:13:08	/usr/local/go/src/net/dial.go:158 +0x466
2017/4/6 下午5:13:08net.(*Dialer).Dial(0xc82000a4b0, 0x2555df0, 0x3, 0xc8205145e0, 0x13, 0x0, 0x0, 0x0, 0x0)
2017/4/6 下午5:13:08	/usr/local/go/src/net/dial.go:216 +0x124
2017/4/6 下午5:13:08net.(*Dialer).Dial-fm(0x2555df0, 0x3, 0xc8205145e0, 0x13, 0x0, 0x0, 0x0, 0x0)
2017/4/6 下午5:13:08	/usr/local/go/src/net/http/transport.go:38 +0x6e
2017/4/6 下午5:13:08net/http.(*Transport).dial(0xc8200bc000, 0x2555df0, 0x3, 0xc8205145e0, 0x13, 0x0, 0x0, 0x0, 0x0)
2017/4/6 下午5:13:08	/usr/local/go/src/net/http/transport.go:659 +0x96
2017/4/6 下午5:13:08net/http.(*Transport).dialConn(0xc8200bc000, 0x0, 0xc8204f9ec0, 0x4, 0xc8205145e0, 0x13, 0x0, 0x0, 0x0)
2017/4/6 下午5:13:08	/usr/local/go/src/net/http/transport.go:762 +0x1e3d
2017/4/6 下午5:13:08net/http.(*Transport).getConn.func4(0xc8200bc000, 0x0, 0xc8204f9ec0, 0x4, 0xc8205145e0, 0x13, 0xc820505020)
2017/4/6 下午5:13:08	/usr/local/go/src/net/http/transport.go:706 +0x66
2017/4/6 下午5:13:08created by net/http.(*Transport).getConn
2017/4/6 下午5:13:08	/usr/local/go/src/net/http/transport.go:708 +0x262
```

**Comment by zhangalex** [comment]
same issue.

**Comment by mathop** [comment]
I had the same issue and I fixed it by changing the "Host Registration URL". In my case I have a private hosted zone in Route 53 and I created a record set pointing to my Rancher's Server private IP. The DNS was reachable by other nodes in the cluster but for some reason I got the same error when deploying a load balancer in a node using this hostname. Changing the "Host Registration URL" to an IP instead of a hostname and registering the node again (through IP) fixed the issue.

**Comment by superseb** [comment]
What was the hostname you had before @mathop ?

**Comment by zhangalex** [comment]
I think this issue has been fixed in newer version of rancher.

**Comment by mathop** [comment]
@superseb It was an internal hostname managed by Amazon Route53 (private hosted zone).

**Comment by superseb** [comment]
Closing to due inactivity, please file a new issue with recent version if you are still experiencing issues.
