### ISSUE TITLE
Network manager crash when containers with exposed ports were deployed on all hosts in the setup.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8436]
Rancher Versions:v1.5.4-rc1

Set up with 3 hosts:

Executing the following automated test - test_sibling_pinging from test_container.py always results in 1 or all of the network-managers to crash.

Logs from network-manager:
```
4/6/2017 10:13:49 AMnet.ipv4.conf.docker0.route_localnet = 1
4/6/2017 10:13:49 AMtime="2017-04-06T17:13:49Z" level=info msg="Setting up binaries for: map[rancher-bridge:ad9337a16be3e1539914a9d36c3edc32e0ec2b1a3cdd41196e925e6dfe6e513d]"
4/6/2017 10:13:49 AMpanic: runtime error: index out of range
4/6/2017 10:13:49 AM
4/6/2017 10:13:49 AMgoroutine 50 [running]:
4/6/2017 10:13:49 AMpanic(0x8c65e0, 0xc420016090)
4/6/2017 10:13:49 AM	/usr/local/go/src/runtime/panic.go:500 +0x1a1
4/6/2017 10:13:49 AMgithub.com/rancher/plugin-manager/conntracksync.(*ConntrackTableWatcher).buildContainersMaps(0xc420372210, 0x897bc0, 0xc4203b2300, 0x0)
4/6/2017 10:13:49 AM	/go/src/github.com/rancher/plugin-manager/conntracksync/watcher.go:125 +0x42f
4/6/2017 10:13:49 AMgithub.com/rancher/plugin-manager/conntracksync.(*ConntrackTableWatcher).doSync(0xc420372210, 0x8b2968d, 0xd8ac80)
4/6/2017 10:13:49 AM	/go/src/github.com/rancher/plugin-manager/conntracksync/watcher.go:64 +0x66
4/6/2017 10:13:49 AMgithub.com/rancher/plugin-manager/conntracksync.(*ConntrackTableWatcher).onChangeNoError(0xc420372210, 0xc4203d2690, 0x25)
4/6/2017 10:13:49 AM	/go/src/github.com/rancher/plugin-manager/conntracksync/watcher.go:57 +0x1b1
4/6/2017 10:13:49 AMgithub.com/rancher/plugin-manager/conntracksync.(*ConntrackTableWatcher).(github.com/rancher/plugin-manager/conntracksync.onChangeNoError)-fm(0xc4203d2690, 0x25)
4/6/2017 10:13:49 AM	/go/src/github.com/rancher/plugin-manager/conntracksync/watcher.go:44 +0x3e
4/6/2017 10:13:49 AMgithub.com/rancher/plugin-manager/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).OnChange.func1(0xc4203d2690, 0x25)
4/6/2017 10:13:49 AM	/go/src/github.com/rancher/plugin-manager/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:36 +0x5f
4/6/2017 10:13:49 AMgithub.com/rancher/plugin-manager/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).onChangeFromVersionWithError(0xc4202cc390, 0x94b501, 0x4, 0x78, 0xc420385f60, 0x0, 0x0)
4/6/2017 10:13:49 AM	/go/src/github.com/rancher/plugin-manager/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:25 +0x1e5
4/6/2017 10:13:49 AMgithub.com/rancher/plugin-manager/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).OnChange(0xc4202cc390, 0x78, 0xc42036e290)
4/6/2017 10:13:49 AM	/go/src/github.com/rancher/plugin-manager/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:40 +0xa6
4/6/2017 10:13:49 AMcreated by github.com/rancher/plugin-manager/conntracksync.Watch
4/6/2017 10:13:49 AM	/go/src/github.com/rancher/plugin-manager/conntracksync/watcher.go:44 +0x1d8
4/6/2017 10:14:03 AMtime="2017-04-06T17:14:03Z" level=info msg="routesync: DOCKER_BRIDGE=docker0, METADATA_IP=169.254.169.250"
4/6/2017 10:14:03 AMtime="2017-04-06T17:14:03Z" level=info msg="routesync: starting monitoring on bridge: docker0, for metadataIP: 169.254.169.250 every 60 seconds"
4/6/2017 10:14:03 AMtime="2017-04-06T17:14:03Z" level=info msg="Waiting for metadata"
4/6/2017 10:14:03 AMtime="2017-04-06T17:14:03Z" level=info msg="Inspecting on start" cid=01119d19e66337191a48250875d4f176000246553917157789b71d1cba0d8263 running=true startedAt="2017-04-06T17:12:34.327135459Z"
4/6/2017 10:14:03 AMtime="2017-04-06T17:14:03Z" level=info msg="Recording previously started" cid=01119d19e66337191a48250875d4f176000246553917157789b71d1cba0d8263 startedAt="2017-04-06T17:12:34.327135459Z"
4/6/2017 10:14:03 AMtime="2017-04-06T17:14:03Z" level=info msg="Inspecting on start" cid=2d0d226f10fe3842d6037887e02be577cfe93c049e0e4025e66c1fce9d402829 running=true startedAt="2017-04-06T14:08:16.747202041Z"
4/6/2017 10:14:03 AMtime="2017-04-06T17:14:03Z" level=info msg="Recording previously started" cid=2d0d226f10fe3842d6037887e02be577cfe93c049e0e4025e66c1fce9d402829 startedAt="2017-04-06T14:08:16.747202041Z"
4/6/2017 10:14:03 AMtime="2017-04-06T17:14:03Z" level=info msg="Inspecting on start" cid=2a4a27d04fdf752f19f2c17db985d85853481933731640784a8a416d1f40275e running=true startedAt="2017-04-06T14:08:12.969943731Z"
4/6/2017 10:14:03 AMtime="2017-04-06T17:14:03Z" level=info msg="Recording previously started" cid=2a4a27d04fdf752f19f2c17db985d85853481933731640784a8a416d1f40275e startedAt="2017-04-06T14:08:12.969943731Z"
4/6/2017 10:14:03 AMtime="2017-04-06T17:14:03Z" level=info msg="Inspecting on start" cid=402670c025661904f072123ac35d673174592ce1c16e1622281c1338e2e4026b running=true startedAt="2017-04-06T17:14:03.400116986Z"
4/6/2017 10:14:03 AMtime="2017-04-06T17:14:03Z" level=info msg="Recording previously started" cid=402670c025661904f072123ac35d673174592ce1c16e1622281c1338e2e4026b startedAt="2017-04-06T17:14:03.400116986Z"
4/6/2017 10:14:03 AMtime="2017-04-06T17:14:03Z" level=info msg="Inspecting on start" cid=962b865ab6462d74bd9db09282394a7428fe94e91eb24d5344e28b02b617506f running=true startedAt="2017-04-06T14:08:01.18312088Z"
4/6/2017 10:14:03 AMtime="2017-04-06T17:14:03Z" level=info msg="Recording previously started" cid=962b865ab6462d74bd9db09282394a7428fe94e91eb24d5344e28b02b617506f startedAt="2017-04-06T14:08:01.18312088Z"
4/6/2017 10:14:03 AMtime="2017-04-06T17:14:03Z" level=info msg="Inspecting on start" cid=e1a9c3bf3219dc64ae2606d59ddd2e467c6da4899624dd5dae47563598d4da43 running=true startedAt="2017-04-06T14:07:58.762317861Z"
4/6/2017 10:14:03 AMtime="2017-04-06T17:14:03Z" level=info msg="Recording previously started" cid=e1a9c3bf3219dc64ae2606d59ddd2e467c6da4899624dd5dae47563598d4da43 startedAt="2017-04-06T14:07:58.762317861Z"
4/6/2017 10:14:03 AMtime="2017-04-06T17:14:03Z" level=info msg="Inspecting on start" cid=1f2adf756791ec2fb5497f1783c30c48a2f443375a313d2a46abf6016f640108 running=true startedAt="2017-04-06T14:07:57.482824218Z"
4/6/2017 10:14:03 AMtime="2017-04-06T17:14:03Z" level=info msg="Recording previously started" cid=1f2adf756791ec2fb5497f1783c30c48a2f443375a313d2a46abf6016f640108 startedAt="2017-04-06T14:07:57.482824218Z"
4/6/2017 10:14:03 AMtime="2017-04-06T17:14:03Z" level=info msg="Inspecting on start" cid=ad9337a16be3e1539914a9d36c3edc32e0ec2b1a3cdd41196e925e6dfe6e513d running=true startedAt="2017-04-06T14:07:54.386304596Z"
4/6/2017 10:14:03 AMtime="2017-04-06T17:14:03Z" level=info msg="Recording previously started" cid=ad9337a16be3e1539914a9d36c3edc32e0ec2b1a3cdd41196e925e6dfe6e513d startedAt="2017-04-06T14:07:54.386304596Z"
4/6/2017 10:14:03 AMtime="2017-04-06T17:14:03Z" level=info msg="Inspecting on start" cid=6ddf3fa8f570972afb18cf4b0475be083170bf192399bf67219c8c3ef7f2f738 running=true startedAt="2017-04-06T14:06:47.492576224Z"
4/6/2017 10:14:03 AMtime="2017-04-06T17:14:03Z" level=info msg="Recording previously started" cid=6ddf3fa8f570972afb18cf4b0475be083170bf192399bf67219c8c3ef7f2f738 startedAt="2017-04-06T14:06:47.492576224Z"
4/6/2017 10:14:03 AMtime="2017-04-06T17:14:03Z" level=info msg="Inspecting on start" cid=484ece0db118d75985a183ce2ab5320b90b5db13a3347e4e9b51a590d3d0896e running=false startedAt="2017-04-06T14:06:44.188669147Z"
4/6/2017 10:14:03 AMnet.bridge.bridge-nf-call-iptables = 1
4/6/2017 10:14:03 AMtime="2017-04-06T17:14:03Z" level=info msg="Setting up binaries for: map[rancher-bridge:ad9337a16be3e1539914a9d36c3edc32e0ec2b1a3cdd41196e925e6dfe6e513d]"
4/6/2017 10:14:03 AMpanic: runtime error: index out of range
4/6/2017 10:14:03 AM
4/6/2017 10:14:03 AMgoroutine 50 [running]:
4/6/2017 10:14:03 AMpanic(0x8c65e0, 0xc420016090)
4/6/2017 10:14:03 AM	/usr/local/go/src/runtime/panic.go:500 +0x1a1
4/6/2017 10:14:03 AMgithub.com/rancher/plugin-manager/conntracksync.(*ConntrackTableWatcher).buildContainersMaps(0xc42036a210, 0x897bc0, 0xc4203aa300, 0x0)
4/6/2017 10:14:03 AM	/go/src/github.com/rancher/plugin-manager/conntracksync/watcher.go:125 +0x42f
4/6/2017 10:14:03 AMgithub.com/rancher/plugin-manager/conntracksync.(*ConntrackTableWatcher).doSync(0xc42036a210, 0x2b1b620f, 0xd8ac80)
4/6/2017 10:14:03 AM	/go/src/github.com/rancher/plugin-manager/conntracksync/watcher.go:64 +0x66
4/6/2017 10:14:03 AMgithub.com/rancher/plugin-manager/conntracksync.(*ConntrackTableWatcher).onChangeNoError(0xc42036a210, 0xc42036b440, 0x25)
4/6/2017 10:14:03 AM	/go/src/github.com/rancher/plugin-manager/conntracksync/watcher.go:57 +0x1b1
4/6/2017 10:14:03 AMgithub.com/rancher/plugin-manager/conntracksync.(*ConntrackTableWatcher).(github.com/rancher/plugin-manager/conntracksync.onChangeNoError)-fm(0xc42036b440, 0x25)
4/6/2017 10:14:03 AM	/go/src/github.com/rancher/plugin-manager/conntracksync/watcher.go:44 +0x3e
4/6/2017 10:14:03 AMgithub.com/rancher/plugin-manager/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).OnChange.func1(0xc42036b440, 0x25)
4/6/2017 10:14:03 AM	/go/src/github.com/rancher/plugin-manager/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:36 +0x5f
4/6/2017 10:14:03 AMgithub.com/rancher/plugin-manager/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).onChangeFromVersionWithError(0xc4202c4390, 0x94b501, 0x4, 0x78, 0xc42037df60, 0x0, 0x0)
4/6/2017 10:14:03 AM	/go/src/github.com/rancher/plugin-manager/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:25 +0x1e5
4/6/2017 10:14:03 AMgithub.com/rancher/plugin-manager/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).OnChange(0xc4202c4390, 0x78, 0xc4203662c0)
4/6/2017 10:14:03 AM	/go/src/github.com/rancher/plugin-manager/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:40 +0xa6
4/6/2017 10:14:03 AMcreated by github.com/rancher/plugin-manager/conntracksync.Watch
4/6/2017 10:14:03 AM	/go/src/github.com/rancher/plugin-manager/conntracksync/watcher.go:44 +0x1d8
4/6/2017 10:14:19 AMtime="2017-04-06T17:14:19Z" level=info msg="routesync: DOCKER_BRIDGE=docker0, METADATA_IP=169.254.169.250"
4/6/2017 10:14:19 AMtime="2017-04-06T17:14:19Z" level=info msg="routesync: starting monitoring on bridge: docker0, for metadataIP: 169.254.169.250 every 60 seconds"
4/6/2017 10:14:19 AMtime="2017-04-06T17:14:19Z" level=info msg="Waiting for metadata"
4/6/2017 10:14:19 AMtime="2017-04-06T17:14:19Z" level=info msg="Inspecting on start" cid=01119d19e66337191a48250875d4f176000246553917157789b71d1cba0d8263 running=false startedAt="2017-04-06T17:12:34.327135459Z"
4/6/2017 10:14:19 AMtime="2017-04-06T17:14:19Z" level=info msg="Inspecting on start" cid=2d0d226f10fe3842d6037887e02be577cfe93c049e0e4025e66c1fce9d402829 running=true startedAt="2017-04-06T14:08:16.747202041Z"
4/6/2017 10:14:19 AMtime="2017-04-06T17:14:19Z" level=info msg="Recording previously started" cid=2d0d226f10fe3842d6037887e02be577cfe93c049e0e4025e66c1fce9d402829 startedAt="2017-04-06T14:08:16.747202041Z"
4/6/2017 10:14:19 AMtime="2017-04-06T17:14:19Z" level=info msg="Inspecting on start" cid=2a4a27d04fdf752f19f2c17db985d85853481933731640784a8a416d1f40275e running=true startedAt="2017-04-06T14:08:12.969943731Z"
4/6/2017 10:14:19 AMtime="2017-04-06T17:14:19Z" level=info msg="Recording previously started" cid=2a4a27d04fdf752f19f2c17db985d85853481933731640784a8a416d1f40275e startedAt="2017-04-06T14:08:12.969943731Z"
4/6/2017 10:14:19 AMtime="2017-04-06T17:14:19Z" level=info msg="Inspecting on start" cid=402670c025661904f072123ac35d673174592ce1c16e1622281c1338e2e4026b running=true startedAt="2017-04-06T17:14:18.536797218Z"
4/6/2017 10:14:19 AMtime="2017-04-06T17:14:19Z" level=info msg="Recording previously started" cid=402670c025661904f072123ac35d673174592ce1c16e1622281c1338e2e4026b startedAt="2017-04-06T17:14:18.536797218Z"
4/6/2017 10:14:19 AMtime="2017-04-06T17:14:19Z" level=info msg="Inspecting on start" cid=962b865ab6462d74bd9db09282394a7428fe94e91eb24d5344e28b02b617506f running=true startedAt="2017-04-06T14:08:01.18312088Z"
4/6/2017 10:14:19 AMtime="2017-04-06T17:14:19Z" level=info msg="Recording previously started" cid=962b865ab6462d74bd9db09282394a7428fe94e91eb24d5344e28b02b617506f startedAt="2017-04-06T14:08:01.18312088Z"
4/6/2017 10:14:19 AMtime="2017-04-06T17:14:19Z" level=info msg="Inspecting on start" cid=e1a9c3bf3219dc64ae2606d59ddd2e467c6da4899624dd5dae47563598d4da43 running=true startedAt="2017-04-06T14:07:58.762317861Z"
4/6/2017 10:14:19 AMtime="2017-04-06T17:14:19Z" level=info msg="Recording previously started" cid=e1a9c3bf3219dc64ae2606d59ddd2e467c6da4899624dd5dae47563598d4da43 startedAt="2017-04-06T14:07:58.762317861Z"
4/6/2017 10:14:19 AMtime="2017-04-06T17:14:19Z" level=info msg="Inspecting on start" cid=1f2adf756791ec2fb5497f1783c30c48a2f443375a313d2a46abf6016f640108 running=true startedAt="2017-04-06T14:07:57.482824218Z"
4/6/2017 10:14:19 AMtime="2017-04-06T17:14:19Z" level=info msg="Recording previously started" cid=1f2adf756791ec2fb5497f1783c30c48a2f443375a313d2a46abf6016f640108 startedAt="2017-04-06T14:07:57.482824218Z"
4/6/2017 10:14:19 AMtime="2017-04-06T17:14:19Z" level=info msg="Inspecting on start" cid=ad9337a16be3e1539914a9d36c3edc32e0ec2b1a3cdd41196e925e6dfe6e513d running=true startedAt="2017-04-06T14:07:54.386304596Z"
4/6/2017 10:14:19 AMtime="2017-04-06T17:14:19Z" level=info msg="Recording previously started" cid=ad9337a16be3e1539914a9d36c3edc32e0ec2b1a3cdd41196e925e6dfe6e513d startedAt="2017-04-06T14:07:54.386304596Z"
4/6/2017 10:14:19 AMtime="2017-04-06T17:14:19Z" level=info msg="Inspecting on start" cid=6ddf3fa8f570972afb18cf4b0475be083170bf192399bf67219c8c3ef7f2f738 running=true startedAt="2017-04-06T14:06:47.492576224Z"
4/6/2017 10:14:19 AMtime="2017-04-06T17:14:19Z" level=info msg="Recording previously started" cid=6ddf3fa8f570972afb18cf4b0475be083170bf192399bf67219c8c3ef7f2f738 startedAt="2017-04-06T14:06:47.492576224Z"
4/6/2017 10:14:19 AMtime="2017-04-06T17:14:19Z" level=info msg="Inspecting on start" cid=484ece0db118d75985a183ce2ab5320b90b5db13a3347e4e9b51a590d3d0896e running=false startedAt="2017-04-06T14:06:44.188669147Z"
4/6/2017 10:14:19 AMnet.bridge.bridge-nf-call-iptables = 1
4/6/2017 10:14:19 AMtime="2017-04-06T17:14:19Z" level=info msg="Setting up binaries for: map[rancher-bridge:ad9337a16be3e1539914a9d36c3edc32e0ec2b1a3cdd41196e925e6dfe6e513d]"
4/6/2017 10:14:19 AMtime="2017-04-06T17:14:19Z" level=info msg="Starting event router."
4/6/2017 10:14:19 AMtime="2017-04-06T17:14:19Z" level=info msg="Applying new nat rules"
4/6/2017 10:14:19 AMnet.ipv4.conf.docker0.route_localnet = 1
4/6/2017 10:14:19 AMtime="2017-04-06T17:14:19Z" level=info msg="Applying new port rules"

```
This test attempt to start 1 container with exposed port/per host.
Containers fails to start and we see the network-manager keeps restarting because of the crash.

**Comment by leodotcloud** [comment]
Fixing this in `network-manager`. Also a good idea to fix it on cattle side as well: https://github.com/rancher/rancher/issues/8439

**Comment by sangeethah** [comment]
Tested with v1.5.4-rc1 using rancher/network-manager:v0.6.2 .
test_sibling_pinging from test_container.py reports success. Network manager crash is not seen anymore.
