### ISSUE TITLE
EventExecutionException when creating new container

### ISSUE THREAD

**Issue by diogogmt** [rancher/rancher#845]
I'm running rancher v0.20.4 with Vagrant.

rancher/server latest imageId 12b4ac8493de
rancher/agent v0.6.1 aadcaa910140

When I create a new container the rancher/server raises the following exception:
```
2015-05-18 22:06:40,704 ERROR [8833106d-ae9b-4a4c-8ecc-6f500f6f8e83:28] [instance:1->instanceHostMap:1] [instance.start->(InstanceStart)->instancehostmap.activate] [] [cutorService-17] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.eventing.exception.EventExecutionException: 3928d11d-014e-43c9-a759-f1c220667696 : ('Connection aborted.', error(111, 'ECONNREFUSED'))
	at io.cattle.platform.eventing.impl.FutureEventListener.onEvent(FutureEventListener.java:46) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]

2015-05-18 22:06:40,705 ERROR [8833106d-ae9b-4a4c-8ecc-6f500f6f8e83:28] [instance:1] [instance.start->(InstanceStart)] [] [cutorService-17] [i.c.p.process.instance.InstanceStart] Failed to create compute for instance [1]
2015-05-18 22:06:40,706 ERROR [8833106d-ae9b-4a4c-8ecc-6f500f6f8e83:28] [instance:1] [instance.start] [] [cutorService-17] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.eventing.exception.EventExecutionException: 3928d11d-014e-43c9-a759-f1c220667696 : ('Connection aborted.', error(111, 'ECONNREFUSED'))
	at io.cattle.platform.eventing.impl.FutureEventListener.onEvent(FutureEventListener.java:46) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]

2015-05-18 22:06:40,745 ERROR [:] [] [] [] [cutorService-17] [i.c.p.e.e.i.ProcessEventListenerImpl] Unknown exception running process [instance.start:28] on [1] io.cattle.platform.eventing.exception.EventExecutionException: 3928d11d-014e-43c9-a759-f1c220667696 : ('Connection aborted.', error(111, 'ECONNREFUSED'))
	at io.cattle.platform.eventing.impl.FutureEventListener.onEvent(FutureEventListener.java:46) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
```

And the rancher/agent raises the following exception:

```
time="2015-05-18T22:06:37Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"create\", ID:\"4db04659f65ceffffd3fc0975c0f8bc7b6634c264105e3cef73757c41b275723\", From:\"rancher/agent-instance:v0.3.0\", Time:1431986797}"
time="2015-05-18T22:06:37Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"4db04659f65ceffffd3fc0975c0f8bc7b6634c264105e3cef73757c41b275723\", From:\"rancher/agent-instance:v0.3.0\", Time:1431986797}"
time="2015-05-18T22:06:37Z" level="info" msg="Assigning IP [10.42.201.169/16], ContainerId [4db04659f65ceffffd3fc0975c0f8bc7b6634c264105e3cef73757c41b275723], Pid [4680]"
time="2015-05-18T22:06:37Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"4db04659f65ceffffd3fc0975c0f8bc7b6634c264105e3cef73757c41b275723\", From:\"watcher-simulated\", Time:0}"
time="2015-05-18T22:06:37Z" level="info" msg="Container locked. Can't run StartHandler. ID: [4db04659f65ceffffd3fc0975c0f8bc7b6634c264105e3cef73757c41b275723]"
2015-05-18 22:06:40,660 ERROR agent [139784237054384] [event.py:108] 3928d11d-014e-43c9-a759-f1c220667696 : Unknown error
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 91, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 33, in execute
    return method(req=req, **req.data.__dict__)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/delegate.py", line 146, in delegate_request
    event)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/delegate.py", line 88, in container_exec
    }, timeout=DockerConfig.delegate_timeout())
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 500, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(111, 'ECONNREFUSED'))
time="2015-05-18T22:06:43Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"create\", ID:\"71c6922918c5da899c180a251c2f531b201aa3e834c05a7a8844ead7413764e0\", From:\"ubuntu:14.04.1\", Time:1431986803}"
time="2015-05-18T22:06:43Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"71c6922918c5da899c180a251c2f531b201aa3e834c05a7a8844ead7413764e0\", From:\"ubuntu:14.04.1\", Time:1431986803}"
time="2015-05-18T22:06:43Z" level="info" msg="Assigning IP [10.42.248.191/16], ContainerId [71c6922918c5da899c180a251c2f531b201aa3e834c05a7a8844ead7413764e0], Pid [5857]"
time="2015-05-18T22:06:43Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"71c6922918c5da899c180a251c2f531b201aa3e834c05a7a8844ead7413764e0\", From:\"watcher-simulated\", Time:0}"
time="2015-05-18T22:06:43Z" level="info" msg="Container locked. Can't run StartHandler. ID: [71c6922918c5da899c180a251c2f531b201aa3e834c05a7a8844ead7413764e0]"
2015/05/18 22:06:57 "unable to unmarshal container info for \"docker/71c6922918c5da899c180a251c2f531b201aa3e834c05a7a8844ead7413764e0\" (failed to get container \"/docker/71c6922918c5da899c180a251c2f531b201aa3e834c05a7a8844ead7413764e0\" with error: unknown container \"/docker/71c6922918c5da899c180a251c2f531b201aa3e834c05a7a8844ead7413764e0\"\n): invalid character 'i' in literal false (expecting 'l')"
goroutine 44 [running]:
github.com/rancherio/host-api/app/common.CheckError(0x7f1a91aea980, 0xc2080994f0, 0x2)
	/source/gopath/src/github.com/rancherio/host-api/app/common/error.go:17 +0x8a
github.com/rancherio/host-api/app/common.ErrorHandler.ServeHTTP(0x943fd8, 0x7f1a91af3fd0, 0xc20805e320, 0xc208032b60)
	/source/gopath/src/github.com/rancherio/host-api/app/common/error_handler.go:13 +0x8a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc20802e5a0, 0x7f1a91af3fd0, 0xc20805e320, 0xc208032b60)
	/source/Godeps/_workspace/src/github.com/gorilla/mux/mux.go:98 +0x297
github.com/rancherio/host-api/auth.func·002(0x7f1a91af3fd0, 0xc20805e320, 0xc208032b60)
	/source/gopath/src/github.com/rancherio/host-api/auth/auth.go:55 +0xfc
net/http.HandlerFunc.ServeHTTP(0xc2080ba490, 0x7f1a91af3fd0, 0xc20805e320, 0xc208032b60)
	/usr/src/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc20803a780, 0x7f1a91af3fd0, 0xc20805e320, 0xc208032b60)
	/usr/src/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc20805ce40, 0x7f1a91af3fd0, 0xc20805e320, 0xc208032b60)
	/usr/src/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20805e000)
	/usr/src/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/src/go/src/net/http/server.go:1751 +0x35e

E0518 22:06:57.880017    2894 error.go:26] %q
%s
 unable to unmarshal container info for "docker/71c6922918c5da899c180a251c2f531b201aa3e834c05a7a8844ead7413764e0" (failed to get container "/docker/71c6922918c5da899c180a251c2f531b201aa3e834c05a7a8844ead7413764e0" with error: unknown container "/docker/71c6922918c5da899c180a251c2f531b201aa3e834c05a7a8844ead7413764e0"
): invalid character 'i' in literal false (expecting 'l')
2015/05/18 22:06:57 http: response.WriteHeader on hijacked connection
2015/05/18 22:06:57 http: response.Write on hijacked connection
I0518 22:06:57.880826    2894 access.go:43] 172.17.8.1 HTTP/1.1 GET: /v1/stats/71c6922918c5da899c180a251c2f531b201aa3e834c05a7a8844ead7413764e0?token=eyJhbGciOiJSUzI1NiJ9.eyJwb3J0Ijo5MzQ1LCJleHAiOjE0MzE5ODcxMTcsInN1YiI6ImNhdHRsZSIsImlzcyI6Imh0dHA6XC9cL2NhdHRsZS5pbyIsImhvc3RVdWlkIjoiMjQ5ZGQ4NDMtM2M5ZS00ZTg5LWI4MDgtMWVkNDc2ZGNjZDI5IiwiaWF0IjoxNDMxOTg2ODE3LCJpcEFkZHJlc3MiOiIxNzIuMTcuOC4xMDAiLCJraWQiOiJkZWZhdWx0In0.HoO3_RUYuqla_fkCUbrPv9meq8GiIP7vLcU8sLcM7GqTdS2N4GZgDqk7RLn0Cp4fYNHQEsmh242RxViwzJDaViwCGt_ahT-cieeEtcgY1L_9gMsDG45usTp2O1arg0OS2MdV53ASDoyfSecU462ud3d-qR8WKWM3lBXlBsRjzaFeQpRStAduqu3RjwqIxHSwGKXskD-6vlYLyrh8GeAP8t82tjheIscwo833f2nUWyIws-jD4b8Yyu3K4NJ58aSkJmCKg2JReU8od_ROHe4r8Vl6DRq_F5ZThSpM7_20a_FG_WqdbvGrqE3PrdOpa6GFtF7T0aAkSb3bPnw7iD7ULg, host: 172.17.8.100:9345 (load time: 0.03950 seconds)
2015/05/18 22:07:20 "unable to unmarshal container info for \"docker/71c6922918c5da899c180a251c2f531b201aa3e834c05a7a8844ead7413764e0\" (failed to get container \"/docker/71c6922918c5da899c180a251c2f531b201aa3e834c05a7a8844ead7413764e0\" with error: unknown container \"/docker/71c6922918c5da899c180a251c2f531b201aa3e834c05a7a8844ead7413764e0\"\n): invalid character 'i' in literal false (expecting 'l')"
goroutine 48 [running]:
github.com/rancherio/host-api/app/common.CheckError(0x7f1a91aea980, 0xc208098b70, 0x2)
	/source/gopath/src/github.com/rancherio/host-api/app/common/error.go:17 +0x8a
github.com/rancherio/host-api/app/common.ErrorHandler.ServeHTTP(0x943fd8, 0x7f1a91af3fd0, 0xc20805e320, 0xc208032b60)
	/source/gopath/src/github.com/rancherio/host-api/app/common/error_handler.go:13 +0x8a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc20802e5a0, 0x7f1a91af3fd0, 0xc20805e320, 0xc208032b60)
	/source/Godeps/_workspace/src/github.com/gorilla/mux/mux.go:98 +0x297
github.com/rancherio/host-api/auth.func·002(0x7f1a91af3fd0, 0xc20805e320, 0xc208032b60)
	/source/gopath/src/github.com/rancherio/host-api/auth/auth.go:55 +0xfc
net/http.HandlerFunc.ServeHTTP(0xc2080ba490, 0x7f1a91af3fd0, 0xc20805e320, 0xc208032b60)
	/usr/src/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc20803a780, 0x7f1a91af3fd0, 0xc20805e320, 0xc208032b60)
	/usr/src/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc20805ce40, 0x7f1a91af3fd0, 0xc20805e320, 0xc208032b60)
	/usr/src/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20805e000)
	/usr/src/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/src/go/src/net/http/server.go:1751 +0x35e

E0518 22:07:20.470997    2894 error.go:26] %q
%s
 unable to unmarshal container info for "docker/71c6922918c5da899c180a251c2f531b201aa3e834c05a7a8844ead7413764e0" (failed to get container "/docker/71c6922918c5da899c180a251c2f531b201aa3e834c05a7a8844ead7413764e0" with error: unknown container "/docker/71c6922918c5da899c180a251c2f531b201aa3e834c05a7a8844ead7413764e0"
): invalid character 'i' in literal false (expecting 'l')
2015/05/18 22:07:20 http: response.WriteHeader on hijacked connection
2015/05/18 22:07:20 http: response.Write on hijacked connection
I0518 22:07:20.475230    2894 access.go:43] 172.17.8.1 HTTP/1.1 GET: /v1/stats/71c6922918c5da899c180a251c2f531b201aa3e834c05a7a8844ead7413764e0?token=eyJhbGciOiJSUzI1NiJ9.eyJwb3J0Ijo5MzQ1LCJleHAiOjE0MzE5ODcxMTcsInN1YiI6ImNhdHRsZSIsImlzcyI6Imh0dHA6XC9cL2NhdHRsZS5pbyIsImhvc3RVdWlkIjoiMjQ5ZGQ4NDMtM2M5ZS00ZTg5LWI4MDgtMWVkNDc2ZGNjZDI5IiwiaWF0IjoxNDMxOTg2ODE3LCJpcEFkZHJlc3MiOiIxNzIuMTcuOC4xMDAiLCJraWQiOiJkZWZhdWx0In0.HoO3_RUYuqla_fkCUbrPv9meq8GiIP7vLcU8sLcM7GqTdS2N4GZgDqk7RLn0Cp4fYNHQEsmh242RxViwzJDaViwCGt_ahT-cieeEtcgY1L_9gMsDG45usTp2O1arg0OS2MdV53ASDoyfSecU462ud3d-qR8WKWM3lBXlBsRjzaFeQpRStAduqu3RjwqIxHSwGKXskD-6vlYLyrh8GeAP8t82tjheIscwo833f2nUWyIws-jD4b8Yyu3K4NJ58aSkJmCKg2JReU8od_ROHe4r8Vl6DRq_F5ZThSpM7_20a_FG_WqdbvGrqE3PrdOpa6GFtF7T0aAkSb3bPnw7iD7ULg, host: 172.17.8.100:9345 (load time: 0.01307 seconds)
W0518 22:08:55.896951 02909 handler.go:524] Error while processing event ("/sys/fs/cgroup/memory/system.slice/motdgen.service": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/memory/system.slice/motdgen.service: no such file or directory
W0518 22:10:56.068468 02909 handler.go:524] Error while processing event ("/sys/fs/cgroup/cpu,cpuacct/system.slice/motdgen.service": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/cpu,cpuacct/system.slice/motdgen.service: no such file or directory
W0518 22:10:56.068539 02909 handler.go:524] Error while processing event ("/sys/fs/cgroup/blkio/system.slice/motdgen.service": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/blkio/system.slice/motdgen.service: no such file or directory
W0518 22:10:56.068561 02909 handler.go:524] Error while processing event ("/sys/fs/cgroup/memory/system.slice/motdgen.service": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/memory/system.slice/motdgen.service: no such file or directory
```

**Comment by deniseschannon** [comment]
What image are you trying to use the launch the container?

We've just tagged a new latest. v0.23.0-rc6 that has a lot of fixes. could you give it a try with the latest and see if you have the same issues?

**Comment by diogogmt** [comment]
Could not reproduce the issue with the latest rancher/server image.
