### ISSUE TITLE
Exeptions in rancher server

### ISSUE THREAD

**Issue by meggarr** [rancher/rancher#8455]
**Rancher Versions:**
Server: stable 1.5.3

**Docker Version:**
Docker version 1.12.6, build 78d1802

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04, bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Full HA setup, external DB, 3 rancher server instances run in 3 dockers with static IP in custom network

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
- network
```
docker network create --driver=bridge --subnet=172.27.1.0/24 --ip-range=172.27.1.0/24 --gateway=172.27.1.1 rancher
```

- rancher1
```
docker run -d --restart=unless-stopped --name rancher1 \
 --network rancher --ip 172.27.1.21 \
 -e JAVA_OPTS="-Xmx2560m" \
 rancher/server:stable \
 --db-host <mysql_host> --db-port 3306 \
 --db-user cattle --db-pass cattle --db-name cattle1 \
 --advertise-address 172.27.1.21
```

- rancher2
```
docker run -d --restart=unless-stopped --name rancher2 \
 --network rancher --ip 172.27.1.22 \
 -e JAVA_OPTS="-Xmx2560m" \
 rancher/server:stable \
 --db-host <mysql_host> --db-port 3306 \
 --db-user cattle --db-pass cattle --db-name cattle1 \
 --advertise-address 172.27.1.22
```

- rancher3
```
docker run -d --restart=unless-stopped --name rancher3 \
 --network rancher --ip 172.27.1.23 \
 -e JAVA_OPTS="-Xmx2560m" \
 rancher/server:stable \
 --db-host <mysql_host> --db-port 3306 \
 --db-user cattle --db-pass cattle --db-name cattle1 \
 --advertise-address 172.27.1.23
```

- haproxy
Follows the document;s setup

**Results:** 

The rancher1 instances always throw exceptions like below

```
time="2017-04-09T03:06:55Z" level=error msg="Failed to update existing repo cache: exit status 1"
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f459c36fb2c]
 
runtime stack:
runtime.throw(0xab68f0, 0x2a)
        /usr/local/go/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x2cc
 
goroutine 37 [syscall, locked to thread]:
runtime.cgocall(0x850050, 0xc42003cb30, 0xc400000000)
        /usr/local/go/src/runtime/cgocall.go:131 +0x110 fp=0xc42003cae8 sp=0xc42003caa8
net._C2func_getaddrinfo(0x7f45880008c0, 0x0, 0xc421562750, 0xc4209011b0, 0x0, 0x0, 0x0)
        ??:0 +0x68 fp=0xc42003cb30 sp=0xc42003cae8
net.cgoLookupIPCNAME(0xc4201914b2, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/cgo_unix.go:146 +0x37c fp=0xc42003cc50 sp=0xc42003cb30
net.cgoLookupIP(0xf51fa0, 0xc42001a448, 0xc4201914b2, 0x14, 0x1, 0xc420453e20, 0x433991, 0xc42008fa00, 0x200000003, 0xc420023500)
        /usr/local/go/src/net/cgo_unix.go:204 +0x3a1 fp=0xc42003cdb8 sp=0xc42003cc50
net.lookupIP(0xf51fa0, 0xc42001a448, 0xc4201914b2, 0x14, 0x0, 0x40f7ec, 0xc420453e90, 0x4121e5, 0xc420542240)
        /usr/local/go/src/net/lookup_unix.go:70 +0xf9 fp=0xc42003ce18 sp=0xc42003cdb8
net.glob..func11(0xf51fa0, 0xc42001a448, 0xaeb458, 0xc4201914b2, 0x14, 0xc420542240, 0xc420453f90, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/hook.go:19 +0x52 fp=0xc42003ce70 sp=0xc42003ce18
net.lookupIPContext.func1(0xc420453f68, 0x80149f, 0xc4204c0f60, 0x0)
        /usr/local/go/src/net/lookup.go:119 +0x5c fp=0xc42003cef8 sp=0xc42003ce70
internal/singleflight.(*Group).doCall(0xf68310, 0xc4217930e0, 0xc4201914b2, 0x14, 0xc4215626f0)
        /usr/local/go/src/internal/singleflight/singleflight.go:93 +0x3c fp=0xc42003cf88 sp=0xc42003cef8
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42003cf90 sp=0xc42003cf88
created by internal/singleflight.(*Group).DoChan
        /usr/local/go/src/internal/singleflight/singleflight.go:86 +0x339
 
goroutine 1 [IO wait]:
net.runtime_pollWait(0x7f459c583e68, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4202595d0, 0x72, 0xc42004d7e0, 0xc42001a038)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc4202595d0, 0xf4e320, 0xc42001a038)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).accept(0xc420259570, 0x0, 0xf4c8a0, 0xc42098c000)
        /usr/local/go/src/net/fd_unix.go:419 +0x238
net.(*TCPListener).accept(0xc420032ce8, 0x29e8d60800, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:132 +0x2e
net.(*TCPListener).AcceptTCP(0xc420032ce8, 0xc42004d908, 0xc42004d910, 0xc42004d900)
        /usr/local/go/src/net/tcpsock.go:209 +0x49
net/http.tcpKeepAliveListener.Accept(0xc420032ce8, 0xaeb4e8, 0xc4209ac000, 0xf52020, 0xc420244f60)
        /usr/local/go/src/net/http/server.go:2608 +0x2f
net/http.(*Server).Serve(0xc420241400, 0xf51a60, 0xc420032ce8, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2273 +0x1ce
net/http.(*Server).ListenAndServe(0xc420241400, 0xc420241400, 0x1)
        /usr/local/go/src/net/http/server.go:2219 +0xb4
net/http.ListenAndServe(0xc4202061d0, 0x5, 0xf4b820, 0xc420256c70, 0x1, 0xc4202061d0)
        /usr/local/go/src/net/http/server.go:2351 +0xa0
github.com/rancher/catalog-service/cmd.run(0xf411a0, 0xc4201f6100, 0x0, 0x4)
        /go/src/github.com/rancher/catalog-service/cmd/root.go:141 +0x6d9
github.com/rancher/catalog-service/vendor/github.com/spf13/cobra.(*Command).execute(0xf411a0, 0xc42000c1a0, 0x4, 0x4, 0xf411a0, 0xc42000c1a0)
        /go/src/github.com/rancher/catalog-service/vendor/github.com/spf13/cobra/command.go:650 +0x443
github.com/rancher/catalog-service/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xf411a0, 0x1, 0xf, 0x0)
        /go/src/github.com/rancher/catalog-service/vendor/github.com/spf13/cobra/command.go:737 +0x367
github.com/rancher/catalog-service/vendor/github.com/spf13/cobra.(*Command).Execute(0xf411a0, 0x0, 0xc420181dd0)
        /go/src/github.com/rancher/catalog-service/vendor/github.com/spf13/cobra/command.go:695 +0x2b
main.main()
        /go/src/github.com/rancher/catalog-service/main.go:10 +0x31
 
goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1
 
goroutine 5 [chan receive]:
database/sql.(*DB).connectionOpener(0xc4201d9e40)
        /usr/local/go/src/database/sql/sql.go:730 +0x4a
created by database/sql.Open
        /usr/local/go/src/database/sql/sql.go:493 +0x1e9
 
goroutine 7 [select]:
net.lookupIPContext(0xf51fa0, 0xc42001a448, 0xc4201914b2, 0x14, 0x0, 0x0, 0x0, 0x0, 0xc420196801)
        /usr/local/go/src/net/lookup.go:122 +0x7bc
net.internetAddrList(0xf51fa0, 0xc42001a448, 0xc4201914ae, 0x3, 0xc4201914b2, 0x19, 0x0, 0x0, 0x0, 0x2, ...)
        /usr/local/go/src/net/ipsock.go:241 +0x5e0
net.resolveAddrList(0xf51fa0, 0xc42001a448, 0xa9dbe9, 0x4, 0xc4201914ae, 0x3, 0xc4201914b2, 0x19, 0x0, 0x0, ...)
        /usr/local/go/src/net/dial.go:179 +0x106
net.(*Dialer).DialContext(0xc420196d18, 0xf51fa0, 0xc42001a448, 0xc4201914ae, 0x3, 0xc4201914b2, 0x19, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/dial.go:329 +0x238
net.(*Dialer).Dial(0xc420196d18, 0xc4201914ae, 0x3, 0xc4201914b2, 0x19, 0xc420196d00, 0x6d09e7, 0x9f8a20, 0xc420fd6150)
        /usr/local/go/src/net/dial.go:282 +0x75
github.com/rancher/catalog-service/vendor/github.com/go-sql-driver/mysql.MySQLDriver.Open(0xc4201914a0, 0x43, 0xa8dc80, 0xc4215cfcc0, 0xc421296060, 0x128)
        /go/src/github.com/rancher/catalog-service/vendor/github.com/go-sql-driver/mysql/driver.go:68 +0x888
github.com/rancher/catalog-service/vendor/github.com/go-sql-driver/mysql.(*MySQLDriver).Open(0xf8cb48, 0xc4201914a0, 0x43, 0x7f459ddde4b0, 0x0, 0x3974fab8, 0xc4215626c0)
        <autogenerated>:6 +0x60
database/sql.(*DB).conn(0xc4201d9e40, 0x7f459c59c601, 0x0, 0x0, 0x0)
        /usr/local/go/src/database/sql/sql.go:824 +0x24e
database/sql.(*DB).begin(0xc4201d9e40, 0xc420181f01, 0x0, 0xc420196fa0, 0x40f0e9)
        /usr/local/go/src/database/sql/sql.go:1165 +0x38
database/sql.(*DB).Begin(0xc4201d9e40, 0xf52160, 0xc4201d9e40, 0xc420197000)
        /usr/local/go/src/database/sql/sql.go:1153 +0x4c
github.com/rancher/catalog-service/vendor/github.com/jinzhu/gorm.(*DB).Begin(0xc4201f4d20, 0x6cf346)
        /go/src/github.com/rancher/catalog-service/vendor/github.com/jinzhu/gorm/main.go:423 +0x98
github.com/rancher/catalog-service/manager.(*Manager).updateDb(0xc4201f6180, 0xc420a1eca4, 0x6, 0xc420a1ece0, 0x9, 0xc420244750, 0x2c, 0xc420a1ecea, 0x6, 0xc4202447b0, ...)
        /go/src/github.com/rancher/catalog-service/manager/db.go:63 +0x47
github.com/rancher/catalog-service/manager.(*Manager).refreshCatalog(0xc4201f6180, 0xc420a1eca4, 0x6, 0xc420a1ece0, 0x9, 0xc420244750, 0x2c, 0xc420a1ecea, 0x6, 0xc4202447b0, ...)
        /go/src/github.com/rancher/catalog-service/manager/manager.go:117 +0x3e7
github.com/rancher/catalog-service/manager.(*Manager).refreshConfigCatalogs(0xc4201f6180, 0x1, 0x0, 0x0)
        /go/src/github.com/rancher/catalog-service/manager/manager.go:64 +0x250
github.com/rancher/catalog-service/manager.(*Manager).RefreshAll(0xc4201f6180, 0x7e0e01, 0x0, 0x0)
        /go/src/github.com/rancher/catalog-service/manager/manager.go:31 +0x38
github.com/rancher/catalog-service/cmd.refresh(0xc4201f6180, 0x1)
        /go/src/github.com/rancher/catalog-service/cmd/root.go:166 +0x38
github.com/rancher/catalog-service/cmd.autoRefresh(0xc4201f6180, 0x12c)
        /go/src/github.com/rancher/catalog-service/cmd/root.go:175 +0x4f
created by github.com/rancher/catalog-service/cmd.run
        /go/src/github.com/rancher/catalog-service/cmd/root.go:134 +0x4b2
 
goroutine 9 [IO wait]:
net.runtime_pollWait(0x7f459c583ce8, 0x72, 0x7)
        /usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4201b2450, 0x72, 0xc420aaa7d0, 0xc42001a038)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc4201b2450, 0xf4e320, 0xc42001a038)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc4201b23f0, 0xc4218b0000, 0x698dc, 0xb0000, 0x0, 0xf4e320, 0xc42001a038)
        /usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc420900068, 0xc4218b0000, 0x698dc, 0xb0000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:173 +0x70
github.com/rancher/catalog-service/vendor/github.com/go-sql-driver/mysql.(*buffer).fill(0xc420902480, 0x4, 0xc4218b0000, 0xb)
        /go/src/github.com/rancher/catalog-service/vendor/github.com/go-sql-driver/mysql/buffer.go:68 +0x10e
github.com/rancher/catalog-service/vendor/github.com/go-sql-driver/mysql.(*buffer).readNext(0xc420902480, 0x4, 0xb, 0x443e84, 0x0, 0x0, 0x18)
        /go/src/github.com/rancher/catalog-service/vendor/github.com/go-sql-driver/mysql/buffer.go:97 +0xb2
github.com/rancher/catalog-service/vendor/github.com/go-sql-driver/mysql.(*mysqlConn).readPacket(0xc420902480, 0x547431, 0xc420902480, 0xc4218b0000, 0xb, 0xb0000)
        /go/src/github.com/rancher/catalog-service/vendor/github.com/go-sql-driver/mysql/packets.go:31 +0x61
github.com/rancher/catalog-service/vendor/github.com/go-sql-driver/mysql.(*mysqlConn).readResultSetHeaderPacket(0xc420902480, 0xc420aaaa03, 0xa9ee84, 0x6)
        /go/src/github.com/rancher/catalog-service/vendor/github.com/go-sql-driver/mysql/packets.go:516 +0x2f
github.com/rancher/catalog-service/vendor/github.com/go-sql-driver/mysql.(*mysqlConn).exec(0xc420902480, 0xa9ee84, 0x6, 0x0, 0xa3e500)
        /go/src/github.com/rancher/catalog-service/vendor/github.com/go-sql-driver/mysql/connection.go:298 +0x69
github.com/rancher/catalog-service/vendor/github.com/go-sql-driver/mysql.(*mysqlTx).Commit(0xc4209010d8, 0xc420aaab08, 0x40f0e9)
        /go/src/github.com/rancher/catalog-service/vendor/github.com/go-sql-driver/mysql/transaction.go:19 +0x77
database/sql.(*Tx).Commit(0xc4205aa6e0, 0x7f459c59c640, 0xc4205aa6e0)
        /usr/local/go/src/database/sql/sql.go:1253 +0x5c
github.com/rancher/catalog-service/vendor/github.com/jinzhu/gorm.(*DB).Commit(0xc420134aa0, 0x9e0620)
        /go/src/github.com/rancher/catalog-service/vendor/github.com/jinzhu/gorm/main.go:435 +0x81
github.com/rancher/catalog-service/manager.(*Manager).updateDb(0xc4201f6180, 0xc420869a44, 0x6, 0xc420869a80, 0x9, 0xc420983e90, 0x2c, 0xc420869a8a, 0x6, 0xc420983ec0, ...)
        /go/src/github.com/rancher/catalog-service/manager/db.go:189 +0x14ca
github.com/rancher/catalog-service/manager.(*Manager).refreshCatalog(0xc4201f6180, 0xc420869a44, 0x6, 0xc420869a80, 0x9, 0xc420983e90, 0x2c, 0xc420869a8a, 0x6, 0xc420983ec0, ...)
        /go/src/github.com/rancher/catalog-service/manager/manager.go:117 +0x3e7
github.com/rancher/catalog-service/manager.(*Manager).refreshConfigCatalogs(0xc4201f6180, 0x1, 0xa9f658, 0x6)
        /go/src/github.com/rancher/catalog-service/manager/manager.go:64 +0x250
github.com/rancher/catalog-service/manager.(*Manager).Refresh(0xc4201f6180, 0xa9f658, 0x6, 0xc42066c101, 0x0, 0x0)
        /go/src/github.com/rancher/catalog-service/manager/manager.go:39 +0xbf
github.com/rancher/catalog-service/service.refreshTemplates(0xf517a0, 0xc4201f2000, 0xc4207a0000, 0xa9f658, 0x6, 0xc42066c138, 0xa45b00, 0xc4201f6440)
        /go/src/github.com/rancher/catalog-service/service/template.go:113 +0x4a
github.com/rancher/catalog-service/service.handler.func1(0xf517a0, 0xc4201f2000, 0xc4207a0000)
        /go/src/github.com/rancher/catalog-service/service/routes.go:41 +0xa5
net/http.HandlerFunc.ServeHTTP(0xc420250980, 0xf517a0, 0xc4201f2000, 0xc4207a0000)
        /usr/local/go/src/net/http/server.go:1726 +0x44
github.com/rancher/catalog-service/vendor/github.com/rancher/go-rancher/api.ApiHandler.func1(0xf517a0, 0xc4201f2000, 0xc4207a0000)
        /go/src/github.com/rancher/catalog-service/vendor/github.com/rancher/go-rancher/api/handler.go:20 +0x143
net/http.HandlerFunc.ServeHTTP(0xc4202509a0, 0xf517a0, 0xc4201f2000, 0xc4207a0000)
        /usr/local/go/src/net/http/server.go:1726 +0x44
github.com/rancher/catalog-service/vendor/github.com/gorilla/context.ClearHandler.func1(0xf517a0, 0xc4201f2000, 0xc4207a0000)
        /go/src/github.com/rancher/catalog-service/vendor/github.com/gorilla/context/context.go:141 +0x8b
net/http.HandlerFunc.ServeHTTP(0xc4202509c0, 0xf517a0, 0xc4201f2000, 0xc4207a0000)
        /usr/local/go/src/net/http/server.go:1726 +0x44
github.com/rancher/catalog-service/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201917c0, 0xf517a0, 0xc4201f2000, 0xc4207a0000)
        /go/src/github.com/rancher/catalog-service/vendor/github.com/gorilla/mux/mux.go:98 +0x255
github.com/rancher/catalog-service/service.(*MuxWrapper).ServeHTTP(0xc420256c70, 0xf517a0, 0xc4201f2000, 0xc4207a0000)
        /go/src/github.com/rancher/catalog-service/service/routes.go:21 +0x4d
net/http.serverHandler.ServeHTTP(0xc420241400, 0xf517a0, 0xc4201f2000, 0xc4207a0000)
        /usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc4203ade80, 0xf51f60, 0xc4201f6200)
        /usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2293 +0x44d
 
goroutine 22 [runnable]:
syscall.Syscall(0x1, 0x3, 0xc420d00000, 0xfbd, 0xfbd, 0xfbd, 0x0)
        /usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.write(0x3, 0xc420d00000, 0xfbd, 0x80000, 0x77, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:1064 +0x55
syscall.Write(0x3, 0xc420d00000, 0xfbd, 0x80000, 0xc42019a2b8, 0x444311, 0x1a)
        /usr/local/go/src/syscall/syscall_unix.go:180 +0x49
net.(*netFD).Write(0xc420208000, 0xc420d00000, 0xfbd, 0x80000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/fd_unix.go:321 +0x12a
net.(*conn).Write(0xc420032c00, 0xc420d00000, 0xfbd, 0x80000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:185 +0x70
github.com/rancher/catalog-service/vendor/github.com/go-sql-driver/mysql.(*mysqlConn).writePacket(0xc4200203f0, 0xc420d00000, 0xfbd, 0x80000, 0x1, 0x20)
        /go/src/github.com/rancher/catalog-service/vendor/github.com/go-sql-driver/mysql/packets.go:115 +0x10a
github.com/rancher/catalog-service/vendor/github.com/go-sql-driver/mysql.(*mysqlStmt).writeExecutePacket(0xc4212ee000, 0xc4211fa0a0, 0x5, 0x5, 0xc42019a670, 0x69e4e8)
        /go/src/github.com/rancher/catalog-service/vendor/github.com/go-sql-driver/mysql/packets.go:1082 +0x1e67
github.com/rancher/catalog-service/vendor/github.com/go-sql-driver/mysql.(*mysqlStmt).Exec(0xc4212ee000, 0xc4211fa0a0, 0x5, 0x5, 0xc4211fa0a0, 0x5, 0x5, 0x0)
        /go/src/github.com/rancher/catalog-service/vendor/github.com/go-sql-driver/mysql/statement.go:53 +0x5d
database/sql.resultFromStatement(0xf4ed60, 0xc4202080e0, 0xf521e0, 0xc4212ee000, 0xc420590900, 0x5, 0x8, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/database/sql/sql.go:1503 +0x1d8
database/sql.(*Tx).Exec(0xc420358190, 0xc42016ba40, 0x68, 0xc420590900, 0x5, 0x8, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/database/sql/sql.go:1400 +0x2cd
github.com/rancher/catalog-service/vendor/github.com/jinzhu/gorm.createCallback(0xc420590800)
        /go/src/github.com/rancher/catalog-service/vendor/github.com/jinzhu/gorm/callback_create.go:110 +0xf45
github.com/rancher/catalog-service/vendor/github.com/jinzhu/gorm.(*Scope).callCallbacks(0xc420590800, 0xc420182e00, 0x9, 0x10, 0xc421129ce0)
        /go/src/github.com/rancher/catalog-service/vendor/github.com/jinzhu/gorm/scope.go:798 +0x4c
github.com/rancher/catalog-service/vendor/github.com/jinzhu/gorm.(*DB).Create(0xc42112e320, 0x9e0620, 0xc421129ce0, 0xc420823860)
        /go/src/github.com/rancher/catalog-service/vendor/github.com/jinzhu/gorm/main.go:372 +0x86
github.com/rancher/catalog-service/manager.(*Manager).updateDb(0xc4201f6180, 0xc4207d6944, 0x6, 0xc4207d6970, 0x9, 0xc420a9b3b0, 0x2c, 0xc4207d697a, 0x6, 0xc420a9b3e0, ...)
        /go/src/github.com/rancher/catalog-service/manager/db.go:181 +0xe31
github.com/rancher/catalog-service/manager.(*Manager).refreshCatalog(0xc4201f6180, 0xc4207d6944, 0x6, 0xc4207d6970, 0x9, 0xc420a9b3b0, 0x2c, 0xc4207d697a, 0x6, 0xc420a9b3e0, ...)
        /go/src/github.com/rancher/catalog-service/manager/manager.go:117 +0x3e7
github.com/rancher/catalog-service/manager.(*Manager).refreshConfigCatalogs(0xc4201f6180, 0x1, 0xa9f658, 0x6)
        /go/src/github.com/rancher/catalog-service/manager/manager.go:64 +0x250
github.com/rancher/catalog-service/manager.(*Manager).Refresh(0xc4201f6180, 0xa9f658, 0x6, 0xc420a56101, 0x0, 0x0)
        /go/src/github.com/rancher/catalog-service/manager/manager.go:39 +0xbf
github.com/rancher/catalog-service/service.refreshTemplates(0xf517a0, 0xc420a22000, 0xc4209ae000, 0xa9f658, 0x6, 0xc420a560f8, 0xa45b00, 0xc4208de240)
        /go/src/github.com/rancher/catalog-service/service/template.go:113 +0x4a
github.com/rancher/catalog-service/service.handler.func1(0xf517a0, 0xc420a22000, 0xc4209ae000)
        /go/src/github.com/rancher/catalog-service/service/routes.go:41 +0xa5
net/http.HandlerFunc.ServeHTTP(0xc420250980, 0xf517a0, 0xc420a22000, 0xc4209ae000)
        /usr/local/go/src/net/http/server.go:1726 +0x44
github.com/rancher/catalog-service/vendor/github.com/rancher/go-rancher/api.ApiHandler.func1(0xf517a0, 0xc420a22000, 0xc4209ae000)
        /go/src/github.com/rancher/catalog-service/vendor/github.com/rancher/go-rancher/api/handler.go:20 +0x143
net/http.HandlerFunc.ServeHTTP(0xc4202509a0, 0xf517a0, 0xc420a22000, 0xc4209ae000)
        /usr/local/go/src/net/http/server.go:1726 +0x44
github.com/rancher/catalog-service/vendor/github.com/gorilla/context.ClearHandler.func1(0xf517a0, 0xc420a22000, 0xc4209ae000)
        /go/src/github.com/rancher/catalog-service/vendor/github.com/gorilla/context/context.go:141 +0x8b
net/http.HandlerFunc.ServeHTTP(0xc4202509c0, 0xf517a0, 0xc420a22000, 0xc4209ae000)
        /usr/local/go/src/net/http/server.go:1726 +0x44
github.com/rancher/catalog-service/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201917c0, 0xf517a0, 0xc420a22000, 0xc4209ae000)
        /go/src/github.com/rancher/catalog-service/vendor/github.com/gorilla/mux/mux.go:98 +0x255
github.com/rancher/catalog-service/service.(*MuxWrapper).ServeHTTP(0xc420256c70, 0xf517a0, 0xc420a22000, 0xc4209ae000)
        /go/src/github.com/rancher/catalog-service/service/routes.go:21 +0x4d
net/http.serverHandler.ServeHTTP(0xc420241400, 0xf517a0, 0xc420a22000, 0xc4209ae000)
        /usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc4209ac000, 0xf51f60, 0xc4208de0c0)
        /usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2293 +0x44d
time="2017-04-09T03:06:56Z" level=info msg="Starting Catalog Service (port 8088, refresh interval 300 seconds)"
```

**Comment by WoLfulus** [comment]
I'm also receiving this on network-services... everything goes down for no reason, some segfaults can be seen

**Comment by superseb** [comment]
Thanks for reporting, can you please reproduce this on the latest version and file a new issue when you encounter it again?
