### ISSUE TITLE
previously removed/orphaned hosts are failing to purge

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#8473]
**Rancher Versions:**
Server: v1.5.4

**Steps to Reproduce:**
after upgrade observed the following:
```
time="2017-04-11T11:34:23Z" level=info msg="Registering backend for host 4d993771-1ccb-4a42-5a63-e19bf14a76c2 with session ID afce8141-556e-446d-8960-12542e97a41d."

2017-04-11 11:49:13,870 ERROR [:] [] [] [] [ecutorService-7] [i.c.p.task.impl.TaskManagerImpl ] Task [evacuate.hosts] failed java.lang.NullPointerException: null
at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.getStandardProcessName(DefaultObjectProcessManager.java:66) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.getProcessName(DefaultObjectProcessManager.java:61) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.scheduleStandardChainedProcessAsync(DefaultObjectProcessManager.java:136) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.process.host.HostRemoveMonitorImpl.run(HostRemoveMonitorImpl.java:40) ~[cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.task.impl.TaskManagerImpl$1.doRun(TaskManagerImpl.java:100) ~[cattle-framework-system-task-0.5.0-SNAPSHOT.jar:na]
at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
```
**Results:**

**Comment by aemneina** [comment]
Linking fix https://github.com/rancher/cattle/pull/2627

**Comment by deniseschannon** [comment]
Validated with v1.5.5-rc1
