### ISSUE TITLE
Stack trace on instance ping logic

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#852]
@ibuildthecloud encountered this excpection. Cutting an issue for it so that I can ciricle back to it.

```
2015-05-20 16:15:04,187 ERROR [:] [] [] [] [utorService-153] [o.a.c.m.context.NoExceptionRunnable ] Uncaught exception com.google.common.cache.CacheLoader$InvalidCacheLoadException: CacheLoader returned null for key (38,5bbbf5a3-fb81-4c92-87e0-1400b945f4ac-0).
    at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2346) ~[guava-15.0.jar:na]
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2316) ~[guava-15.0.jar:na]
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278) ~[guava-15.0.jar:na]
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193) ~[guava-15.0.jar:na]
    at com.google.common.cache.LocalCache.get(LocalCache.java:3932) ~[guava-15.0.jar:na]
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3936) ~[guava-15.0.jar:na]
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4806) ~[guava-15.0.jar:na]
    at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4812) ~[guava-15.0.jar:na]
    at io.cattle.platform.ha.monitor.impl.PingInstancesMonitorImpl.pingReply(PingInstancesMonitorImpl.java:105) ~[classes/:na]
    at sun.reflect.GeneratedMethodAccessor734.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_65]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_65]
    at io.cattle.platform.eventing.annotation.MethodInvokingListener$1.doWithLockNoResult(MethodInvokingListener.java:69) ~[classes/:na]
    at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) ~[classes/:na]
    at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:1) ~[classes/:na]
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) ~[classes/:na]
    at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) ~[classes/:na]
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) ~[classes/:na]
    at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) ~[classes/:na]
    at io.cattle.platform.eventing.annotation.MethodInvokingListener.onEvent(MethodInvokingListener.java:65) ~[classes/:na]
    at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) ~[classes/:na]
    at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) ~[classes/:na]
    at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [classes/:na]
    at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [classes/:na]
    at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [classes/:na]
    at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [classes/:na]
    at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [classes/:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_65]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_65]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_65]
```

**Comment by alena1108** [comment]
@cjellick I saw it multiple times as well. Anything specific information (logs, db info) should I watch for, to help you with debugging?

**Comment by cjellick** [comment]
Were you doing anything in particular at the time @alena1108 ? Running integration tests? If so, particular ones?

**Comment by alena1108** [comment]
Yes, integration tests on simulator with idempotent checks off. The tests were starting/stopping/removing instances via service.activate/service.deactivate. The tests I've run are test_svc_discovery and test_svc_discovery_lb

**Comment by alena1108** [comment]
And its also possible that I had containers + python-agent on the boot2docker host that weren't registered in the DB (not sure if it matters)

**Comment by cjellick** [comment]
Thanks @alena1108 the extra info will be very helpful

**Comment by alena1108** [comment]
Looked through the code. The potential suspect is PingInstancesMonitorImpl, computeInstanceActivateReply. There we call instanceCache.invalidate(agentId) without checking if the key exists in cache. We do it implicitly in all other places with instanceCache.getUnchecked. 

But again, I'm not sure, just throwing in the theory.

**Comment by cjellick** [comment]
This particular scenario is occurring not because of the instanceCache but because of the hostCache, which is newly added. The method that loads that host cant find a matching record in the db and returns null and the LoadingCache doesnt allow nulls.
