### ISSUE TITLE
Blank page when trying to add an Environment

### ISSUE THREAD

**Issue by AlexandreOuellet** [rancher/rancher#8638]
I had a couple of environments, all using various templates (Cattle, Swarm, Windows).  When trying to add a new environment, it goes to /settings/env/add, and then nothing else happens.

Chrome's debug console gives me this error : 

ui-75c22fcbbbbec68ca05c03041d7a797a.js:94 Uncaught TypeError: Cannot read property 'includes' of undefined
    at http://10.137.10.36:8080/assets/ui-75c22fcbbbbec68ca05c03041d7a797a.js:94:3586
    at Array.find (native)
    at n.<anonymous> (http://10.137.10.36:8080/assets/ui-75c22fcbbbbec68ca05c03041d7a797a.js:94:3543)
    at d.f.get (http://10.137.10.36:8080/assets/vendor-0f5234ec3ba2a6f843abe79a8d0cccf9.js:10:23458)
    at Object.r (http://10.137.10.36:8080/assets/vendor-0f5234ec3ba2a6f843abe79a8d0cccf9.js:11:30682)
    at n.get (http://10.137.10.36:8080/assets/vendor-0f5234ec3ba2a6f843abe79a8d0cccf9.js:14:19994)
    at http://10.137.10.36:8080/assets/ui-75c22fcbbbbec68ca05c03041d7a797a.js:80:3121
    at http://10.137.10.36:8080/assets/vendor-0f5234ec3ba2a6f843abe79a8d0cccf9.js:14:12018
    at n.forEach (http://10.137.10.36:8080/assets/vendor-0f5234ec3ba2a6f843abe79a8d0cccf9.js:14:11784)
    at n.map (http://10.137.10.36:8080/assets/vendor-0f5234ec3ba2a6f843abe79a8d0cccf9.js:14:11980)

The code seems to have been minified, but the failing part is this  : 
return e.get("categories").includes("Orchestration")

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.3` Cattle: `v0.177.10` UI: `v1.5.8` |
|Access|`Disabled`|
|Orchestration|`Swarm`|
|Route|`settings.projects.index`|

**Comment by AlexandreOuellet** [comment]
Also, from time to time, I am able to see my old environments in the "Manage Environments" menu, with the status "purged".  But when I try to access them, it directs me to my only environment left active.

**Comment by vincent99** [comment]
This happens when you have an environment template that refers to catalog templates that don't exist (i.e. turn off community catalog), and was fixed in a later 1.5.x.

**Comment by AlexandreOuellet** [comment]
Wow, thanks a lot for the quick reply
