### ISSUE TITLE
"Out of memory exception" when creating 20 EBS volumes

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#8651]
**Rancher Versions:**
Server:v1.6.0-rc4

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Create a setup with AWS hosts and deploy EBS catalog
2. Create a service with 20 new volumes using the yaml file below:
```
version: '2'
services:
  foo:
    image: ubuntu
    stdin_open: true
    scale: 2
    volumes:
    - testvol1:/mydata1
    - testvol2:/mydata2
    - testvol3:/mydata3
    - testvol4:/mydata4
    - testvol5:/mydata5
    - testvol6:/mydata6
    - testvol7:/mydata7
    - testvol8:/mydata8
    - testvol9:/mydata9
    - testvol10:/mydata10
    - testvol11:/mydata11
    - testvol12:/mydata12
    - testvol13:/mydata13
    - testvol14:/mydata14
    - testvol15:/mydata15
    - testvol16:/mydata16
    - testvol17:/mydata17
    - testvol18:/mydata18
    - testvol19:/mydata19
    - testvol20:/mydata20
volumes:
  testvol1:
    driver: rancher-ebs
    driver_opts:
      size: '5'
  testvol2:
    driver: rancher-ebs
    driver_opts:
      size: '5'
  testvol3:
    driver: rancher-ebs
    driver_opts:
      size: '5'
  testvol4:
    driver: rancher-ebs
    driver_opts:
      size: '5'
  testvol5:
    driver: rancher-ebs
    driver_opts:
      size: '5'
  testvol6:
    driver: rancher-ebs
    driver_opts:
      size: '5'
  testvol7:
    driver: rancher-ebs
    driver_opts:
      size: '5'
  testvol8:
    driver: rancher-ebs
    driver_opts:
      size: '5'
  testvol9:
    driver: rancher-ebs
    driver_opts:
      size: '5'
  testvol10:
    driver: rancher-ebs
    driver_opts:
      size: '5'
  testvol11:
    driver: rancher-ebs
    driver_opts:
      size: '5'
  testvol12:
    driver: rancher-ebs
    driver_opts:
      size: '5'
  testvol13:
    driver: rancher-ebs
    driver_opts:
      size: '5'
  testvol14:
    driver: rancher-ebs
    driver_opts:
      size: '5'
  testvol15:
    driver: rancher-ebs
    driver_opts:
      size: '5'
  testvol16:
    driver: rancher-ebs
    driver_opts:
      size: '5'
  testvol17:
    driver: rancher-ebs
    driver_opts:
      size: '5'
  testvol18:
    driver: rancher-ebs
    driver_opts:
      size: '5'
  testvol19:
    driver: rancher-ebs
    driver_opts:
      size: '5'
  testvol20:
    driver: rancher-ebs
    driver_opts:
      size: '5'
```
The service foo fails to get created with the error below:
```
time="2017-05-03T17:27:03Z" level=info msg="[multivoltest:foo]: Starting " eventId=06e0105d-a078-4968-a10e-9afa6b57c4cb resourceId=1st6 
time="2017-05-03T17:28:13Z" level=error msg="Failed Starting foo : Get http://localhost:8080/v2-beta/projects/1a5/services/1s7: net/http: request cance
led (Client.Timeout exceeded while awaiting headers)" 
time="2017-05-03T17:28:13Z" level=error msg="Failed to start: foo : Get http://localhost:8080/v2-beta/projects/1a5/services/1s7: net/http: request canc
eled (Client.Timeout exceeded while awaiting headers)" 
time="2017-05-03T17:28:13Z" level=error msg="Stack Create Event Failed: Get http://localhost:8080/v2-beta/projects/1a5/services/1s7: net/http: request 
canceled (Client.Timeout exceeded while awaiting headers)" eventId=06e0105d-a078-4968-a10e-9afa6b57c4cb resourceId=1st6 
2017/05/03 17:28:13 http: proxy error: net/http: request canceled
time="2017-05-03T17:28:13Z" level=info msg="[multivoltest:]: Project started " eventId=06e0105d-a078-4968-a10e-9afa6b57c4cb resourceId=1st6 
2017/05/03 17:28:31 http: proxy error: net/http: request canceled
2017/05/03 17:28:33 http: proxy error: net/http: request canceled
time="2017-05-03T17:28:33Z" level=info msg="Hit websocket pong timeout. Last websocket ping received at 2017-05-03 17:28:20.075634304 +0000 UTC. Closin
g connection." 
time="2017-05-03T17:28:33Z" level=info msg="Exiting go-machine-service" service=gms 
2017-05-03 17:28:39,589 ERROR   [pool-3-thread-1] [ConsoleStatus] Check-in failed org.jooq.exception.DataAccessException: SQL [update `cluster_membersh
ip` set `cluster_membership`.`heartbeat` = ? where `cluster_membership`.`uuid` = ?]; Could not connect to localhost:3306: unexpected end of stream, rea
d 0 bytes from 4
        at org.jooq.impl.Utils.translate(Utils.java:1287) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:495) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:326) ~[jooq-3.3.0.jar:na]
        at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:140) ~[jooq-3.3.0.jar:na]
        at io.cattle.platform.hazelcast.membership.dao.impl.ClusterMembershipDAOImpl.checkin(ClusterMembershipDAOImpl.java:32) ~[cattle-hazelcast-commo
n-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.hazelcast.membership.DBDiscovery.checkin(DBDiscovery.java:174) ~[cattle-hazelcast-common-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.hazelcast.membership.DBDiscovery.doRun(DBDiscovery.java:163) ~[cattle-hazelcast-common-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15) [cattle-framework-managed-context-0.5.0-
SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-S
NAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5
.0-SNAPSHOT.jar:na]
```
Rancher server hangs with out of memory exception as below:
```
ime="2017-05-03T17:30:10Z" level=info msg="Shutting down backend c4d8ed40-000b-44e4-9e0e-e0481f679302. Connection closed because: websocket: close 100
6 unexpected EOF." 
time="2017-05-03T17:30:10Z" level=info msg="Removed backend. Key: c4d8ed40-000b-44e4-9e0e-e0481f679302. Session ID 0222b5c0-0a68-4212-a369-bd5751f2cc07
 ." 
2017/05/03 17:30:19 http: proxy error: net/http: request canceled
time="2017-05-03T17:30:32Z" level=info msg="Shutting down backend 3567fdc4-1505-4b85-bbb2-c413f3bccc11. Connection closed because: websocket: close 100
6 unexpected EOF." 
time="2017-05-03T17:30:32Z" level=info msg="Removed backend. Key: 3567fdc4-1505-4b85-bbb2-c413f3bccc11. Session ID 34941d95-138c-4150-89d9-701fc00d6a5f
 ." 
java.lang.OutOfMemoryError: Java heap space
Dumping heap to /var/lib/cattle/logs/java_pid8.hprof ...
time="2017-05-03T17:30:43Z" level=info msg="Shutting down backend 5a883314-6a12-4002-87d4-ce9f3fddf0c7. Connection closed because: websocket: close 100
6 unexpected EOF." 
time="2017-05-03T17:30:43Z" level=info msg="Removed backend. Key: 5a883314-6a12-4002-87d4-ce9f3fddf0c7. Session ID 66ed2129-035a-4df3-93c7-770d74e3751d
 ." 
2017/05/03 17:32:23 http: proxy error: net/http: request canceled
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "qtp1020391880-134"
Heap dump file created [3644083021 bytes in 294.160 secs]
2017-05-03 17:32:08,217 ERROR [:] [] [] [] [p1020391880-134] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [http://146.148.96.108
:8080/v2-beta/publish]. Error id: [cb2ae455-ea0e-41dd-b5b7-c5bd9a7e529b]. java.lang.OutOfMemoryError: Java heap space
2017-05-03 17:32:49,950 ERROR [:] [] [] [] [p1020391880-134] [i.g.i.g.s.ApiRequestFilterDelegate  ] Unhandled exception in API for request [http://146.
148.96.108:8080/v2-beta/publish] java.lang.OutOfMemoryError: Java heap space
2017-05-03 17:33:18,897 WARN  [:] [] [] [] [p1020391880-134] [o.e.jetty.servlet.ServletHandler    ] Error for /v2-beta/publish java.lang.OutOfMemoryErr
or: Java heap space
2017/05/03 17:35:43 http: proxy error: EOF
2017-05-03 17:35:43,617 ERROR [1062fc75-438d-40bd-ba8b-e69893a1d029:592] [instance:32] [instance.start->(InstanceStart)->instance.allocate] [] [cutorSe
rvice-26] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception java.lang.OutOfMemoryError: Java heap space
2017-05-03 17:35:43,621 ERROR [1062fc75-438d-40bd-ba8b-e69893a1d029:592] [instance:32] [instance.start] [] [cutorService-26] [c.p.e.p.i.DefaultProcessI
nstanceImpl] Unknown exception java.lang.OutOfMemoryError: Java heap space



```

**Comment by cjellick** [comment]
How big is your rancher server host (memory, cpu)?
Does this consistently reproduce?

**Comment by soumyalj** [comment]
The server has 4GRAM and Intel(R) Xeon(R) CPU @ 2.50GHz. It happened in rc3 and rc4.

**Comment by StrongMonkey** [comment]
@cjellick Confirmed this is reproducible in master now. After launching the yaml above, rancher-server become unresponsive, my laptop starts flapping. 
the logs from the server:
```time="2017-05-03T13:57:25-07:00" level=info msg="[test:]: Starting project " eventId=a67c3877-900e-4f1f-bc40-bc758cbbe77e resourceId=1st7 
time="2017-05-03T13:57:25-07:00" level=info msg="[test:foo]: Starting " eventId=a67c3877-900e-4f1f-bc40-bc758cbbe77e resourceId=1st7 
2017-05-03 20:57:25,886 INFO  [4d52c56e-8c18-4e02-b6e9-e35d6c4e8e8d:308] [instance:15] [instance.start->(InstanceStart)->instance.allocate->(InstanceAllocate)] [] [ecutorService-6] [i.c.p.a.s.impl.AllocatorServiceImpl ] Allocating instance [15] 
2017-05-03 20:57:25,915 INFO  [22c64402-8865-42da-b6d4-bb988ec4a27c:311] [instance:16] [instance.start->(InstanceStart)->instance.allocate->(InstanceAllocate)] [] [cutorService-10] [i.c.p.a.s.impl.AllocatorServiceImpl ] Allocating instance [16] 
2017-05-03 20:57:25,933 INFO  [:] [] [] [] [tp1237550792-85] [i.c.p.c.s.impl.ConfigItemServerImpl ] Processing [metadata-answers] for client [agent:2] 
2017-05-03 20:57:25,939 INFO  [4d52c56e-8c18-4e02-b6e9-e35d6c4e8e8d:308] [instance:15] [instance.start->(InstanceStart)->instance.allocate->(InstanceAllocate)] [] [ecutorService-6] [i.c.p.a.s.impl.AllocatorServiceImpl ] [722a5f9c-2e2c-4d3d-a48c-ac3180aff553] Attempting allocation for:
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553] instance [[15]]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553] volume [36]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553] volume [37]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553] volume [34]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553] volume [38]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553] volume [41]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553] volume [46]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553] volume [26]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553] volume [31]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553] volume [33]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553] volume [39]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553] volume [32]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553] volume [35]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553] volume [42]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553] volume [44]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553] volume [45]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553] volume [29]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553] volume [30]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553] volume [43]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553] volume [28]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553] volume [40]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553] volume [27]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553] constraints:
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   volume [36] must be one of pool(s) [2]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   valid host(s) [1]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   volume [37] must be one of pool(s) [2]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   valid host(s) [1]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   volume [34] must be one of pool(s) [2]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   valid host(s) [1]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   volume [38] must be one of pool(s) [2]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   valid host(s) [1]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   volume [41] must be one of pool(s) [2]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   valid host(s) [1]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   storage pool for volume 46 must be one of kind [sim, docker]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   volume [26] must be one of pool(s) [2]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   valid host(s) [1]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   volume [31] must be one of pool(s) [2]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   valid host(s) [1]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   volume [33] must be one of pool(s) [2]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   valid host(s) [1]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   volume [39] must be one of pool(s) [2]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   valid host(s) [1]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   volume [32] must be one of pool(s) [2]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   valid host(s) [1]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   volume [35] must be one of pool(s) [2]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   valid host(s) [1]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   volume [42] must be one of pool(s) [2]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   valid host(s) [1]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   volume [44] must be one of pool(s) [2]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   valid host(s) [1]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   volume [45] must be one of pool(s) [2]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   valid host(s) [1]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   volume [29] must be one of pool(s) [2]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   valid host(s) [1]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   volume [30] must be one of pool(s) [2]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   valid host(s) [1]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   volume [43] must be one of pool(s) [2]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   valid host(s) [1]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   volume [28] must be one of pool(s) [2]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   valid host(s) [1]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   volume [40] must be one of pool(s) [2]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   valid host(s) [1]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   volume [27] must be one of pool(s) [2]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   valid host(s) [1]
  [722a5f9c-2e2c-4d3d-a48c-ac3180aff553]   account id must be 5 
2017-05-03 20:57:26,106 INFO  [:] [] [] [] [tp1237550792-83] [i.c.p.c.s.impl.ConfigItemServerImpl ] Setting item [metadata-answers] to version [85-0faac2a6d078bed38bf68beb6edc64f8] for [agent:2] 
time="2017-05-03T13:57:49-07:00" level=error msg="Failed Starting foo : Get http://localhost:8080/v2-beta/projects/1a5/services/1s7: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2017-05-03T13:57:49-07:00" level=error msg="Failed to start: foo : Get http://localhost:8080/v2-beta/projects/1a5/services/1s7: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
2017/05/03 13:57:49 http: proxy error: net/http: request canceled
time="2017-05-03T13:57:49-07:00" level=error msg="Stack Create Event Failed: Get http://localhost:8080/v2-beta/projects/1a5/services/1s7: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" eventId=a67c3877-900e-4f1f-bc40-bc758cbbe77e resourceId=1st7 
time="2017-05-03T13:57:49-07:00" level=info msg="[test:]: Project started " eventId=a67c3877-900e-4f1f-bc40-bc758cbbe77e resourceId=1st7 
time="2017-05-03T13:58:01-07:00" level=info msg="Hit websocket pong timeout. Last websocket ping received at 2017-05-03 13:57:50.906223752 -0700 MST. Closing connection." 
time="2017-05-03T13:58:01-07:00" level=info msg="Exiting rancher-compose-executor" version= 
2017/05/03 13:58:01 http: proxy error: net/http: request canceled
time="2017-05-03T13:58:02-07:00" level=info msg="Hit websocket pong timeout. Last websocket ping received at 2017-05-03 13:57:50.906359917 -0700 MST. Closing connection." 
time="2017-05-03T13:58:02-07:00" level=info msg="Exiting go-machine-service" ```
