### ISSUE TITLE
rancher-ingress-controller: slice bounds out of range

### ISSUE THREAD

**Issue by LoicMahieu** [rancher/rancher#8726]
**Rancher Versions:**
Server: 1.6.0
healthcheck: 0.3.0
ipsec: 0.10
network-services: 0.2.0
kubernetes (if applicable): v1.5.4-rancher1-4.1

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
KVM -  Ubuntu 16.04.2 LTS (4.4.0)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher HA

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
- Create a Kubernetes stack
- Create some Ingress resource

**Results:** 
An error in Rancher Ingress Controller:
```
10/05/2017 14:31:08time="2017-05-10T12:31:08Z" level=info msg="Starting Rancher LB service"
10/05/2017 14:31:08time="2017-05-10T12:31:08Z" level=info msg="LB controller: kubernetes"
10/05/2017 14:31:08time="2017-05-10T12:31:08Z" level=info msg="LB provider: rancher"
10/05/2017 14:31:08time="2017-05-10T12:31:08Z" level=info msg="starting kubernetes controller"
10/05/2017 14:31:08time="2017-05-10T12:31:08Z" level=info msg="Healthcheck handler is listening on :10241"
10/05/2017 14:31:08time="2017-05-10T12:31:08Z" level=info msg="Event(api.ObjectReference{Kind:\"Ingress\", Namespace:\"my-awesome-app\", Name:\"app\", UID:\"001868d0-1de0-11e7-85eb-022ddfe71a26\", APIVersion:\"extensions\", ResourceVersion:\"9950698\", FieldPath:\"\"}): type: 'Normal' reason: 'CREATE' my-awesome-app/app"
10/05/2017 14:31:08time="2017-05-10T12:31:08Z" level=info msg="LB [my-awesome-app/app] is not ready yet, skipping endpoint update"
10/05/2017 14:31:08time="2017-05-10T12:31:08Z" level=info msg="Updating ingress my-awesome-app/app. Removing IP 172.16.8.8"
10/05/2017 14:31:08time="2017-05-10T12:31:08Z" level=info msg="Updating ingress my-awesome-app/app. Removing IP 172.16.8.9"
10/05/2017 14:31:08panic: runtime error: slice bounds out of range
10/05/2017 14:31:08
10/05/2017 14:31:08goroutine 46 [running]:
10/05/2017 14:31:08panic(0x2222ca0, 0xc820018040)
10/05/2017 14:31:08	/usr/local/go/src/runtime/panic.go:481 +0x3e6
10/05/2017 14:31:08github.com/rancher/lb-controller/controller/kubernetes.(*loadBalancerController).updateIngressStatus(0xc8202ba1e0, 0xc820368720, 0x1b)
10/05/2017 14:31:08	/go/src/github.com/rancher/lb-controller/controller/kubernetes/kubernetes.go:275 +0x1784
10/05/2017 14:31:08github.com/rancher/lb-controller/controller/kubernetes.(*loadBalancerController).(github.com/rancher/lb-controller/controller/kubernetes.updateIngressStatus)-fm(0xc820368720, 0x1b)
10/05/2017 14:31:08	/go/src/github.com/rancher/lb-controller/controller/kubernetes/kubernetes.go:96 +0x34
10/05/2017 14:31:08github.com/rancher/lb-controller/utils.(*TaskQueue).worker(0xc8203c8bc0)
10/05/2017 14:31:08	/go/src/github.com/rancher/lb-controller/utils/utils.go:64 +0x138
10/05/2017 14:31:08github.com/rancher/lb-controller/utils.(*TaskQueue).(github.com/rancher/lb-controller/utils.worker)-fm()
10/05/2017 14:31:08	/go/src/github.com/rancher/lb-controller/utils/utils.go:33 +0x20
10/05/2017 14:31:08github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc820891f60)
10/05/2017 14:31:08	/go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:84 +0x19
10/05/2017 14:31:08github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc820891f60, 0x3b9aca00, 0x0, 0x4d6401, 0xc820406180)
10/05/2017 14:31:08	/go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:85 +0xb4
10/05/2017 14:31:08github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.Until(0xc820891f60, 0x3b9aca00, 0xc820406180)
10/05/2017 14:31:08	/go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x43
10/05/2017 14:31:08github.com/rancher/lb-controller/utils.(*TaskQueue).Run(0xc8203c8bc0, 0x3b9aca00, 0xc820406180)
10/05/2017 14:31:08	/go/src/github.com/rancher/lb-controller/utils/utils.go:33 +0x48
10/05/2017 14:31:08created by github.com/rancher/lb-controller/controller/kubernetes.(*loadBalancerController).Run
10/05/2017 14:31:08	/go/src/github.com/rancher/lb-controller/controller/kubernetes/kubernetes.go:340 +0x246
```

Notes:
- All my ingress have a annotation:
```
io.rancher.scheduler.affinity.host_label: "host=no_ingress_please"
```

Because we handle ingress control by ourself and I don't find a way to disable rancher ingress controller and I stop the `rancher-ingress-controller` after each update.
(If we have better idea... ?)

**Comment by deniseschannon** [comment]
@LoicMahieu Currently, the best way is to stop/delete the rancher-ingress-controller in your k8s stack. 

Do you have an example ingress that could be used to try and reproduce?

**Comment by LoicMahieu** [comment]
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    io.rancher.scheduler.affinity.host_label: host=no_ingress_please
  name: app
spec:
  rules:
  - host: my-awesome-app.com
    http:
      paths:
      - backend:
          serviceName: app
          servicePort: 4000
        path: /
```

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
