### ISSUE TITLE
Rancher agent does not support SNI

### ISSUE THREAD

**Issue by shubb30** [rancher/rancher#8792]
**Rancher versions:**
rancher/server: 1.6.0
rancher/agent: 1.2.2

**Docker version: **
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:45:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:45:26 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: **
16.04.2 LTS

**Setup details:**
Rancher HA with external DB.  Front-end HAproxy doing SSL offloading and forwarding to servers:8080
**Environment Template: **
Cattle

**Steps to Reproduce:**
After having issues using a certificate for my .local domain, I decided to use the IP address instead.
I created an SSL certificate from my own CA using the IP address of the HAproxy VIP.  I also included the hostname and IP in the Subject Alternative Name.

When I try to run the agent I get the following:
    docker run -e CATTLE_AGENT_IP="10.102.50.60"  --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.2 https://10.102.50.12/v1/scripts/<***registration-key***>
    Updating certificates in /etc/ssl/certs...
    1 added, 0 removed; done.
    Running hooks in /etc/ca-certificates/update.d...
    done.
    
    INFO: Running Agent Registration Process, CATTLE_URL=https://10.102.50.12/v1
    INFO: Attempting to connect to: https://10.102.50.12/v1
    INFO: https://10.102.50.12/v1 is accessible
    Traceback (most recent call last):
      File "./resolve_url.py", line 9, in <module>
        r = requests.get(url)
      File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
        return request('get', url, params=params, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
        raise SSLError(e, request=request)
    requests.exceptions.SSLError: hostname '10.102.50.12' doesn't match either of 'rancher.mydomain.local', '10.102.50.12'
    curl: no URL specified!
    curl: try 'curl --help' or 'curl --manual' for more information
    ERROR: returned
    ERROR: --- START ---
    ERROR: --- END ---
    ERROR: Failed to load registration env from CATTLE_URL=https://10.102.50.12/v1 ENV_URL=
    ERROR: Please ensure the proper value for the Host Registration URL is set

**Results:**
I exec'ed into another agent that was still working from my previously configured hostname-based agent, and tried to use python requests to the registration URL, and I see the same error.

    >>> import requests
    >>> requests.get("https://10.102.50.12/v1/scripts/<***registration-key***>", verify="/var/lib/rancher/etc/ssl/ca.crt")
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
        return request('get', url, params=params, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
       raise SSLError(e, request=request)
    requests.exceptions.SSLError: hostname '10.102.50.12' doesn't match either of 'rancher.mydomain.local', '10.102.50.12'
    >>>

If I Install pyopenssl, then it works
    root@cattle-04:/# pip install pyopenssl

    >>> import requests
    >>> requests.get("https://10.102.50.12/v1/scripts/<***registration-key***>", verify="/var/lib/rancher/etc/ssl/ca.crt")
    <Response [200]>
    >>>

**Comment by shubb30** [comment]
By the way, the latest 1.2.5 agent apparently has the additional code mentioned in #9366, because I was able to create a working agent by just adding the pyopenssl library to the image.

I made a repo at https://github.com/shubb30/rancher-agent-sni, and the image is available at https://hub.docker.com/r/shubb30/rancher-agent-sni/ for anyone else running into this issue.
