### ISSUE TITLE
Can't rancher-ingress-controller start succesfully when installing Kubernetes on rancher/server using Cattle environment template

### ISSUE THREAD

**Issue by cho-cloud-cloud** [rancher/rancher#8813]
**Rancher versions:**
rancher/server: stable
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck: 0.2.3
ipsec: 0.11.2
network-services: 0.6.6
scheduler: 
kubernetes (if applicable): v1.5.4-rancher1-4

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS 7
3.10.0-514.el7.x86_64
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
- master
- node1
- node2

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

**Results:**
`rancher-ingress-controller` can't start.
![](https://i.stack.imgur.com/LRfuv.png)
## Logs
```
5/18/2017 3:55:15 PMgithub.com/rancher/lb-controller/utils.(*TaskQueue).Run(0xc8200122e0, 0x3b9aca00, 0xc82043c180)
5/18/2017 3:55:15 PM    /go/src/github.com/rancher/lb-controller/utils/utils.go:32
5/18/2017 3:55:15 PMcreated by github.com/rancher/lb-controller/controller/kubernetes.(*loadBalancerController).Run
5/18/2017 3:55:15 PM    /go/src/github.com/rancher/lb-controller/controller/kubernetes/kubernetes.go:340 +0x246
5/18/2017 3:55:15 PMgoroutine 33 [runnable]:
5/18/2017 3:55:15 PMgithub.com/rancher/lb-controller/utils.(*TaskQueue).Run(0xc820012300, 0x3b9aca00, 0xc82043c180)
5/18/2017 3:55:15 PM    /go/src/github.com/rancher/lb-controller/utils/utils.go:32
5/18/2017 3:55:15 PMcreated by github.com/rancher/lb-controller/controller/kubernetes.(*loadBalancerController).Run
5/18/2017 3:55:15 PM    /go/src/github.com/rancher/lb-controller/controller/kubernetes/kubernetes.go:341 +0x284
5/18/2017 3:55:15 PMgoroutine 34 [chan receive]:
5/18/2017 3:55:15 PMgithub.com/rancher/lb-controller/provider/rancher.(*LBProvider).Run(0xc8202da4e0, 0xc8202da8e0)
5/18/2017 3:55:15 PM    /go/src/github.com/rancher/lb-controller/provider/rancher/rancher.go:153 +0xb8
5/18/2017 3:55:15 PMcreated by github.com/rancher/lb-controller/controller/kubernetes.(*loadBalancerController).Run
5/18/2017 3:55:15 PM    /go/src/github.com/rancher/lb-controller/controller/kubernetes/kubernetes.go:344 +0x355
5/18/2017 3:55:15 PMgoroutine 35 [runnable]:
5/18/2017 3:55:15 PMgithub.com/rancher/lb-controller/utils.(*TaskQueue).Run(0xc8202da8e0, 0x3b9aca00, 0xc820015ce0)
5/18/2017 3:55:15 PM    /go/src/github.com/rancher/lb-controller/utils/utils.go:32
5/18/2017 3:55:15 PMcreated by github.com/rancher/lb-controller/provider/rancher.(*LBProvider).Run
5/18/2017 3:55:15 PM    /go/src/github.com/rancher/lb-controller/provider/rancher/rancher.go:149 +0x6f
5/18/2017 3:55:15 PMgoroutine 36 [sleep]:
5/18/2017 3:55:15 PMtime.Sleep(0x6fc23ac00)
5/18/2017 3:55:15 PM    /usr/local/go/src/runtime/time.go:59 +0xf9
5/18/2017 3:55:15 PMgithub.com/rancher/lb-controller/provider/rancher.(*LBProvider).syncupEndpoints(0xc8202da4e0, 0x0, 0x0)
5/18/2017 3:55:15 PM    /go/src/github.com/rancher/lb-controller/provider/rancher/rancher.go:161 +0x5f
5/18/2017 3:55:15 PMcreated by github.com/rancher/lb-controller/provider/rancher.(*LBProvider).Run
5/18/2017 3:55:15 PM    /go/src/github.com/rancher/lb-controller/provider/rancher/rancher.go:151 +0x91
5/18/2017 3:55:15 PMgoroutine 37 [select, locked to thread]:
5/18/2017 3:55:15 PMruntime.gopark(0x296b370, 0xc820225728, 0x25553f0, 0x6, 0x657572743a226518, 0x2)
5/18/2017 3:55:15 PM    /usr/local/go/src/runtime/proc.go:262 +0x163
5/18/2017 3:55:15 PMruntime.selectgoImpl(0xc820225728, 0x0, 0x18)
5/18/2017 3:55:15 PM    /usr/local/go/src/runtime/select.go:392 +0xa67
5/18/2017 3:55:15 PMruntime.selectgo(0xc820225728)
5/18/2017 3:55:15 PM    /usr/local/go/src/runtime/select.go:215 +0x12
5/18/2017 3:55:15 PMruntime.ensureSigM.func1()
5/18/2017 3:55:15 PM    /usr/local/go/src/runtime/signal1_unix.go:279 +0x358
5/18/2017 3:55:15 PMruntime.goexit()
5/18/2017 3:55:15 PM    /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1
5/18/2017 3:55:15 PMgoroutine 38 [select]:
5/18/2017 3:55:15 PMnet/http.(*Transport).getConn(0xc8200b4000, 0xc8200b81c0, 0x0, 0xc82000efc0, 0x4, 0xc8201171d0, 0x29, 0x0, 0x0, 0x0)
5/18/2017 3:55:15 PM    /usr/local/go/src/net/http/transport.go:711 +0x4ef
5/18/2017 3:55:15 PMnet/http.(*Transport).RoundTrip(0xc8200b4000, 0xc8200b81c0, 0xa, 0x0, 0x0)
5/18/2017 3:55:15 PM    /usr/local/go/src/net/http/transport.go:311 +0x7e9
5/18/2017 3:55:15 PMgithub.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/client/transport.(*userAgentRoundTripper).RoundTrip(0xc8204314a0, 0xc8200b81c0, 0xc8204314a0, 0x0, 0x0)
5/18/2017 3:55:15 PM    /go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/client/transport/round_trippers.go:92 +0x130
5/18/2017 3:55:15 PMnet/http.send(0xc8200b8000, 0x7f73370ddb08, 0xc8204314a0, 0x0, 0x0, 0x0, 0xc82000f110, 0x0, 0x0)
5/18/2017 3:55:15 PM    /usr/local/go/src/net/http/client.go:260 +0x6b7
5/18/2017 3:55:15 PMnet/http.(*Client).send(0xc820439d10, 0xc8200b8000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
5/18/2017 3:55:15 PM    /usr/local/go/src/net/http/client.go:155 +0x185
5/18/2017 3:55:15 PMnet/http.(*Client).doFollowingRedirects(0xc820439d10, 0xc8200b8000, 0x296af18, 0x0, 0x0, 0x0)
5/18/2017 3:55:15 PM    /usr/local/go/src/net/http/client.go:475 +0x8a4
5/18/2017 3:55:15 PMnet/http.(*Client).Do(0xc820439d10, 0xc8200b8000, 0x0, 0x0, 0x0)
5/18/2017 3:55:15 PM    /usr/local/go/src/net/http/client.go:188 +0xff
5/18/2017 3:55:15 PMgithub.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/client/restclient.(*Request).request(0xc8202d4680, 0xc8204ad830, 0x0, 0x0)
5/18/2017 3:55:15 PM    /go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/client/restclient/request.go:809 +0x5e5
5/18/2017 3:55:15 PMgithub.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/client/restclient.(*Request).Do(0xc8202d4680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
5/18/2017 3:55:15 PM    /go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/client/restclient/request.go:868 +0x87
5/18/2017 3:55:15 PMgithub.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/client/unversioned.(*ingress).List(0xc8202dab80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
5/18/2017 3:55:15 PM    /go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/client/unversioned/ingress.go:55 +0x19f
5/18/2017 3:55:15 PMgithub.com/rancher/lb-controller/controller/kubernetes.ingressListFunc.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x254b748, ...)
5/18/2017 3:55:15 PM    /go/src/github.com/rancher/lb-controller/controller/kubernetes/kubernetes.go:168 +0x114
5/18/2017 3:55:15 PMgithub.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/client/cache.(*ListWatch).List(0xc8204a5060, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
5/18/2017 3:55:15 PM    /go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/client/cache/listwatch.go:80 +0x5f
5/18/2017 3:55:15 PMgithub.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch(0xc82001aa80, 0xc82043c180, 0x0, 0x0)
5/18/2017 3:55:15 PM    /go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:258 +0x30a
5/18/2017 3:55:15 PMgithub.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/client/cache.(*Reflector).RunUntil.func1()
5/18/2017 3:55:15 PM    /go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:213 +0x29
5/18/2017 3:55:15 PMgithub.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc8202dab20)
5/18/2017 3:55:15 PM    /go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:84 +0x19
5/18/2017 3:55:15 PMgithub.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc8202dab20, 0x3b9aca00, 0x0, 0xc820398101, 0xc82043c180)
5/18/2017 3:55:15 PM    /go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:85 +0xb4
5/18/2017 3:55:15 PMgithub.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.Until(0xc8202dab20, 0x3b9aca00, 0xc82043c180)
5/18/2017 3:55:15 PM    /go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x43
5/18/2017 3:55:15 PMcreated by github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/client/cache.(*Reflector).RunUntil
5/18/2017 3:55:15 PM    /go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:216 +0x276
5/18/2017 3:55:15 PMgoroutine 39 [select]:
5/18/2017 3:55:15 PMnet.lookupIPDeadline(0xc8201171d0, 0x26, 0xed0af3c71, 0x256c90f2, 0x3667ba0, 0x0, 0x0, 0x0, 0x0, 0x0)
5/18/2017 3:55:15 PM    /usr/local/go/src/net/lookup.go:109 +0x6a6
5/18/2017 3:55:15 PMnet.internetAddrList(0x2555df0, 0x3, 0xc8201171d0, 0x29, 0xed0af3c71, 0x256c90f2, 0x3667ba0, 0x0, 0x0, 0x0, ...)
5/18/2017 3:55:15 PM    /usr/local/go/src/net/ipsock.go:252 +0x6ee
5/18/2017 3:55:15 PMnet.resolveAddrList(0x25511e0, 0x4, 0x2555df0, 0x3, 0xc8201171d0, 0x29, 0xed0af3c71, 0x256c90f2, 0x3667ba0, 0x0, ...)
5/18/2017 3:55:15 PM    /usr/local/go/src/net/dial.go:158 +0x466
5/18/2017 3:55:15 PMnet.(*Dialer).Dial(0xc82001c5f0, 0x2555df0, 0x3, 0xc8201171d0, 0x29, 0x0, 0x0, 0x0, 0x0)
5/18/2017 3:55:15 PM    /usr/local/go/src/net/dial.go:216 +0x124
5/18/2017 3:55:15 PMnet.(*Dialer).Dial-fm(0x2555df0, 0x3, 0xc8201171d0, 0x29, 0x0, 0x0, 0x0, 0x0)
5/18/2017 3:55:15 PM    /usr/local/go/src/net/http/transport.go:38 +0x6e
5/18/2017 3:55:15 PMnet/http.(*Transport).dial(0xc8200b4000, 0x2555df0, 0x3, 0xc8201171d0, 0x29, 0x0, 0x0, 0x0, 0x0)
5/18/2017 3:55:15 PM    /usr/local/go/src/net/http/transport.go:659 +0x96
5/18/2017 3:55:15 PMnet/http.(*Transport).dialConn(0xc8200b4000, 0x0, 0xc82000efc0, 0x4, 0xc8201171d0, 0x29, 0x7f73370ddfa0, 0x0, 0x0)
5/18/2017 3:55:15 PM    /usr/local/go/src/net/http/transport.go:762 +0x1e3d
5/18/2017 3:55:15 PMnet/http.(*Transport).getConn.func4(0xc8200b4000, 0x0, 0xc82000efc0, 0x4, 0xc8201171d0, 0x29, 0xc82043cc00)
5/18/2017 3:55:15 PM    /usr/local/go/src/net/http/transport.go:706 +0x66
5/18/2017 3:55:15 PMcreated by net/http.(*Transport).getConn
5/18/2017 3:55:15 PM    /usr/local/go/src/net/http/transport.go:708 +0x262
```

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
