### ISSUE TITLE
Installation to external database fails: SQLSyntaxErrorException: (conn:3264) Table 'cattle.setting' doesn't exist

### ISSUE THREAD

**Issue by neotreat** [rancher/rancher#8962]
**Rancher versions:**
rancher/server: `CATTLE_RANCHER_SERVER_VERSION=v1.6.1`
rancher/agent: `none`

**Infrastructure Stack versions:**
healthcheck: `none`
ipsec: `none`
network-services: `none`
scheduler: `none`
kubernetes (if applicable): `none`

**Docker version: (`docker version`,`docker info` preferred)**

```bash
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```bash
NAME="RancherOS"
VERSION=v1.0.2
ID=rancheros
ID_LIKE=
VERSION_ID=v1.0.2
PRETTY_NAME="RancherOS v1.0.2"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
`VMWare ESXi 6.0.0`

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher with external MariaDB database.

```bash
mysql  Ver 15.1 Distrib 5.5.52-MariaDB, for Linux (x86_64) using readline 5.1
```

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
`none`

**Steps to Reproduce:**

1.  Create external database
```bash
CREATE DATABASE IF NOT EXISTS cattle COLLATE = 'utf8_general_ci' CHARACTER SET = 'utf8';
GRANT ALL ON cattle.* TO 'cattle'@'<RANCHER_SERVER_IP>' IDENTIFIED BY 'cattle';
```

2. Run rancher/server

```bash
sudo docker run -d --name rancher-server --restart=unless-stopped -p 8080:8080 rancher/server --db-host <MARIADB_SERVER_IP> --db-port 3306 --db-user cattle --db-pass cattle --db-name cattle
```

**Results:**

The connections details are correct, because several tables are successfully created. The `setting` table exists, but only the `DATABASECHANGELOG` and  `DATABASECHANGELOGLOCK` table has entries. The installation without an external database works and the stable version of rancher fails with the same error.

I had a look at the old issues (especially #391), which is closed with the resolution "obsolete". However the issue seems to still exist. I'm happy to support you with testing different setup constellations and more log files to examine the error!

```bash
CATTLE_AGENT_PACKAGE_HOST_API_URL=/usr/share/cattle/artifacts/host-api.tar.gz
CATTLE_AGENT_PACKAGE_PYTHON_AGENT_URL=/usr/share/cattle/artifacts/go-agent.tar.gz
CATTLE_API_UI_URL=//releases.rancher.com/api-ui/1.0.8
CATTLE_CATTLE_VERSION=v0.181.3
CATTLE_DB_CATTLE_DATABASE=mysql
CATTLE_DB_CATTLE_MYSQL_HOST=mariadb.milzarek.net
CATTLE_DB_CATTLE_MYSQL_NAME=cattle
CATTLE_DB_CATTLE_MYSQL_PORT=3306
CATTLE_DB_CATTLE_USERNAME=cattle
CATTLE_GRAPHITE_HOST=
CATTLE_GRAPHITE_PORT=
CATTLE_HOME=/var/lib/cattle
CATTLE_HOST_API_PROXY_MODE=embedded
CATTLE_LOGBACK_OUTPUT_GELF_HOST=
CATTLE_LOGBACK_OUTPUT_GELF_PORT=
CATTLE_RANCHER_CLI_VERSION=v0.6.1
CATTLE_RANCHER_COMPOSE_VERSION=v0.12.5
CATTLE_RANCHER_SERVER_IMAGE=rancher/server
CATTLE_RANCHER_SERVER_VERSION=v1.6.1
CATTLE_USE_LOCAL_ARTIFACTS=true
DEFAULT_CATTLE_API_UI_CSS_URL=/api-ui/ui.min.css
DEFAULT_CATTLE_API_UI_INDEX=//releases.rancher.com/ui/1.6.5
DEFAULT_CATTLE_API_UI_JS_URL=/api-ui/ui.min.js
DEFAULT_CATTLE_AUTH_SERVICE_EXECUTE=true
DEFAULT_CATTLE_CATALOG_EXECUTE=true
DEFAULT_CATTLE_CATALOG_URL={"catalogs":{"community":{"url":"https://git.rancher.io/community-catalog.git","branch":"master"},"library":{"url":"https://git.rancher.io/rancher-catalog.git","branch":"${RELEASE}"}}}
DEFAULT_CATTLE_COMPOSE_EXECUTOR_EXECUTE=true
DEFAULT_CATTLE_MACHINE_EXECUTE=true
DEFAULT_CATTLE_RANCHER_CLI_DARWIN_URL=https://releases.rancher.com/cli/v0.6.1/rancher-darwin-amd64-v0.6.1.tar.gz
DEFAULT_CATTLE_RANCHER_CLI_LINUX_URL=https://releases.rancher.com/cli/v0.6.1/rancher-linux-amd64-v0.6.1.tar.gz
DEFAULT_CATTLE_RANCHER_CLI_WINDOWS_URL=https://releases.rancher.com/cli/v0.6.1/rancher-windows-386-v0.6.1.zip
DEFAULT_CATTLE_RANCHER_COMPOSE_DARWIN_URL=https://releases.rancher.com/compose/v0.12.5/rancher-compose-darwin-amd64-v0.12.5.tar.gz
DEFAULT_CATTLE_RANCHER_COMPOSE_LINUX_URL=https://releases.rancher.com/compose/v0.12.5/rancher-compose-linux-amd64-v0.12.5.tar.gz
DEFAULT_CATTLE_RANCHER_COMPOSE_WINDOWS_URL=https://releases.rancher.com/compose/v0.12.5/rancher-compose-windows-386-v0.12.5.zip
DEFAULT_CATTLE_SECRETS_API_EXECUTE=true
DEFAULT_CATTLE_WEBHOOK_SERVICE_EXECUTE=true
15:16:41.369 [main] INFO  ConsoleStatus - Loading configuration
2017-06-05 15:17:06,431 INFO    [main] [ConsoleStatus] Starting DB migration
2017-06-05 15:17:11,295 ERROR [:] [] [] [] [igurationSource] [c.n.config.AbstractPollingScheduler ] Error getting result from polling source java.sql.SQLSyntaxErrorException: (conn:3264) Table 'cattle.setting' doesn't exist
Query is: SELECT distinct name, value FROM setting
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:139) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.getException(ExceptionMapper.java:101) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwAndLogException(ExceptionMapper.java:77) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:224) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.MariaDbClientPreparedStatement.executeInternal(MariaDbClientPreparedStatement.java:232) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.MariaDbClientPreparedStatement.executeQuery(MariaDbClientPreparedStatement.java:177) ~[mariadb-java-client-1.5.8.jar:na]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96) ~[commons-dbcp-1.4.jar:1.4]
	at com.netflix.config.sources.JDBCConfigurationSource.load(JDBCConfigurationSource.java:107) ~[archaius-core-0.5.14.jar:na]
	at com.netflix.config.sources.JDBCConfigurationSource.poll(JDBCConfigurationSource.java:88) ~[archaius-core-0.5.14.jar:na]
	at io.cattle.platform.archaius.sources.LazyJDBCSource.poll(LazyJDBCSource.java:31) ~[cattle-framework-archaius-0.5.0-SNAPSHOT.jar:na]
	at com.netflix.config.AbstractPollingScheduler$1.run(AbstractPollingScheduler.java:163) ~[archaius-core-0.5.14.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_72]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_72]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_72]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Table 'cattle.setting' doesn't exist
Query is: SELECT distinct name, value FROM setting
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1115) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1047) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1002) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:174) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.MariaDbClientPreparedStatement.executeInternal(MariaDbClientPreparedStatement.java:223) ~[mariadb-java-client-1.5.8.jar:na]
	... 14 common frames omitted
2017-06-05 15:17:18,174 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2017-06-05 15:17:18,175 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2017-06-05 15:17:18,176 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2017-06-05 15:17:18,177 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2017-06-05 15:17:18,181 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2017-06-05 15:17:18,182 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2017-06-05 15:17:18,183 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2017-06-05 15:17:18,185 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2017-06-05 15:17:18,185 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2017-06-05 15:17:18,186 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2017-06-05 15:17:18,187 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2017-06-05 15:17:18,187 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2017-06-05 15:17:18,188 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2017-06-05 15:17:18,188 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
...
```

**Comment by laszlocph** [comment]
@neotreat did you find a solution?

I see the same. My workaround is to start with an in-memory db, dump it, import it to the external db, and restart the server container with external db params :(

**Comment by superseb** [comment]
What database server version are you running @laszlocph ?

**Comment by laszlocph** [comment]
v1.6.2

**Comment by neotreat** [comment]
@laszlocph Sorry no, I did not give it another try yet.

My only option was to start Rancher with the in-memory db as well. Your workaround sounds worth trying, but it would be nice, if it works out of the box.

**Comment by superseb** [comment]
Would like to get this reproduced, do you have a reproducible case from scratch so I can reproduce?

**Comment by laszlocph** [comment]
Okay, it seems that the schema creation was simply slow.

I recreated the case locally, and did see the same WARN messages. But quickly finished the migration.

Then I went to my cloud instance and saw that after 17 minutes it finished the schema creation. So as of now I don't think there is an issue. Besides it's slow. @neotreat @superseb 

---

As a reference here is a repro case:

docker run -e MYSQL_ROOT_PASSWORD=password --name=ranchermysql -d mysql:5.7

docker exec -it ranchermysql bash
mysql -p
CREATE DATABASE IF NOT EXISTS cattle COLLATE = 'utf8_general_ci' CHARACTER SET = 'utf8';

docker run -d --restart=unless-stopped -p 8080:8080 --link ranchermysql:ranchermysql rancher/server \
    --db-host ranchermysql --db-port 3306 --db-user root --db-pass password --db-name cattle

**Comment by neotreat** [comment]
@laszlocph Did you also get the ERROR message `Table 'cattle.setting' doesn't exist`?

I'll give it another try on my server an wait for longer to see, if this really solves the error. I'll try to provide a short reproduction case for my issue, if it still exists.

**Comment by laszlocph** [comment]
@neotreat not in this specific case. 

I did see that before, in other cases, but I don't remember exactly.

**Comment by superseb** [comment]
I just reproduced;

Same setup as @laszlocph posted (`mariadb` container, `rancher/server` container), run `pumba` between adding `'[delay 3000ms 10ms 20.00]'` between `rancher/server` and `mariadb` container and the message appears. Also explains why it only happens sometimes.

**Comment by superseb** [comment]
@neotreat @laszlocph How is the network between `rancher/server` and the database server? Latency/bandwidth?

**Comment by blaggacao** [comment]
I've documented my failure scenario, which, I guess, is syntactically identical to the one from @neotreat here:
https://github.com/rancher/rancher/issues/391#issuecomment-315566649
It shows the error message, proof of table creation and a closer look on the DATABSELOGLOCK which I copy here:
```sql
mysql> SELECT * FROM DATABASECHANGELOGLOCK                         ;
+----+--------+---------------------+---------------------------+
| ID | LOCKED | LOCKGRANTED         | LOCKEDBY                  |
+----+--------+---------------------+---------------------------+
|  1 |       | 2017-07-15 22:18:43 | 0a11622d11db (172.18.0.2) |
+----+--------+---------------------+---------------------------+
1 row in set (0.00 sec)
```

**Comment by superseb** [comment]
@neotreat @blaggacao Does it not complete on Google Cloud MySQL, also not after a longer time?

**Comment by superseb** [comment]
Slow database performance causes these issues. You need a proper size/instance on cloud providers to get any decent performance.

Please report back if you are still experiencing issues.

**Comment by proxity** [comment]
I get the Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Table 'cattle.setting' doesn't exist Query is: SELECT distinct name, value FROM setting
when Rancher v1.6.20 is creating a fresh db with mariadb 10.2. With 10.1 it works on the same server.
Still Rancher starts, is the error harmful?
