### ISSUE TITLE
Can't run in the local network

### ISSUE THREAD

**Issue by hlj** [rancher/rancher#90]
I want to use Racher inside my company. But my intranet can't access the internet directly. Please improve the support for the non-internet network.

**Comment by ibuildthecloud** [comment]
Do you have zero Internet connectivity, or do you have an internet proxy available?

**Comment by hlj** [comment]
No, My network is a totally local network, can't connect to internet by anyway.

**Comment by hlj** [comment]
I must download all software to my laptop, then switch to local network, upload these software to server and run them.

**Comment by feliksik** [comment]
I had some connectivity problems today and had problems starting rancher server. 
Docker logs did not show everything, and I did restart the container a few times. Stacktrace is on https://gist.github.com/feliksik/c361340967d008c69d27 . 
It looks like an xsd is loaded remotely. Is this a dependency on internet connection? Is this intentional?

**Comment by ibuildthecloud** [comment]
@feliksik One of the libraries we are using (liquibase) is trying to go out to the Internet and download an XSD for validation.  We need to turn that off.  It should not be doing that.  I just need to do some research on how to disable it.

**Comment by vincent99** [comment]
There will be other issues once you get past there though. e.g. the master makes a request to http://cdn.rancher.io/ui/${VERSION}/static/index.html to serve up the UI...

**Comment by jose-cardoso** [comment]
Still experiencing this problem on the latest release:

`12:33:11.117 [main] INFO  ConsoleStatus - [DONE ] [94782ms] Startup Succeeded, Listening on port 8080
2015-06-05 12:33:21,681 ERROR [:] [] [] [] [tp1068863502-42] [i.c.p.i.a.s.filter.UIPathFilter     ] Failed to load UI from [http://releases.rancher.com/ui/0.22.0-rc2/static/index.html] java.net.ConnectException: Connection refused`

This environment is internal only so this will never work for us.

**Comment by will-chan** [comment]
We have not tagged the latest 0.23-rc releases that has this fix.  However, even with this fix, we still need a proxy to d/l other artifacts.  We plan to ship a release of Rancher that requires no internet access before our product goes 1.0 GA.  Our first step was to require at least a proxy to the internet to install Rancher.  Our second step is to repackage it so it does not require any downloading of required artifacts.

**Comment by kaos** [comment]
I'm on a company network too. Running from my dev machine works fine, but trying it on one of our servers, I need to go through a proxy to get out to internet.

Is it documented somewhere what I need to do to get an agent up & running using a proxy?

I got the management server up and running just fine.

**Comment by sangeethah** [comment]
@kaos , we will be documenting the following steps required to run agent in a machine that needs a proxy soon.

set proxy for docker in /etc/default/docker (set http_proxy parameter)  and restart docker.
To run agent :
Get the command to add custom host from UI. Add the following options to the docker run command:
-e "http_proxy=<proxy>" -e "https_proxy=<proxy>"  -e "NO_PROXY=<ip>"

**Comment by kaos** [comment]
Thanks!

Will give that a go tomorrow :)

**Comment by flaccid** [comment]
I'm trying to run Rancher UI/API behind corporate proxy. dockerd is configured to use proxy and we have also started rancher with:

```
docker run -d --restart=always -p 8080:8080 -e http_proxy="10.10.234.10:8080" -e https_proxy="10.10.234.10:8080" rancher/server
```

This does not seem to make a difference. The server appears to timeout when trying to reach github after I authorize the popup to set up the access control.

Could you please let me know where to go from here? Happy to provide debug/logging etc. when provided some pointers.

```
2015-06-19 06:26:47,735 DEBUG [:] [] [] [] [ecutorService-5] [a.p.s.NonBlockingSubscriptionHandler] Got exception on write, disconnecting : class org.eclipse.jetty.io.EofException [null]
2015-06-19 06:26:47,735 DEBUG [:] [] [] [] [ecutorService-5] [i.c.p.a.p.s.j.WebSocketMessageWriter] Websocket connection closed
2015-06-19 06:26:51,780 ERROR [:] [] [] [] [tp1974668487-43] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [io.github.ibuildthecloud.gdapi.request.ApiRequest@533af804] java.lang.RuntimeException: org.apache.http.conn.ConnectTimeoutException: Connect to github.com:443 [github.com/192.30.252.131] failed: Connection timed out
	at io.cattle.platform.iaas.api.auth.github.TokenResourceManager.createInternal(TokenResourceManager.java:52) ~[cattle-iaas-auth-logic-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.create(AbstractBaseResourceManager.java:115) ~[gdapi-java-server-0.11.1.1.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.ResourceManagerRequestHandler.generate(ResourceManagerRequestHandler.java:39) ~[gdapi-java-server-0.11.1.1.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.AbstractResponseGenerator.handle(AbstractResponseGenerator.java:14) ~[gdapi-java-server-0.11.1.1.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.handle(DefaultReadWriteApiDelegate.java:27) ~[gdapi-java-server-0.11.1.1.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.write(DefaultReadWriteApiDelegate.java:22) ~[gdapi-java-server-0.11.1.1.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96) ~[spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260) ~[spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94) ~[spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at com.sun.proxy.$Proxy36.write(Unknown Source) ~[na:na]
	at io.github.ibuildthecloud.gdapi.request.handler.write.ReadWriteApiHandler.handle(ReadWriteApiHandler.java:19) ~[gdapi-java-server-0.11.1.1.jar:na]
	at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:88) ~[gdapi-java-server-0.11.1.1.jar:na]
	at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:60) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:53) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419) [jetty-servlet-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:82) [jetty-servlets-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:256) [jetty-servlets-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419) [jetty-servlet-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455) [jetty-servlet-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557) [jetty-security-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384) [jetty-servlet-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.server.Server.handle(Server.java:370) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865) [jetty-http-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) [jetty-http-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668) [jetty-io-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52) [jetty-io-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [jetty-util-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [jetty-util-8.1.11.v20130520.jar:8.1.11.v20130520]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to github.com:443 [github.com/192.30.252.131] failed: Connection timed out
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:136) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:357) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:218) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.client.fluent.Request.execute(Request.java:143) ~[fluent-hc-4.3.1.jar:4.3.1]
	at io.cattle.platform.iaas.api.auth.github.GithubClient.getAccessToken(GithubClient.java:52) ~[cattle-iaas-auth-logic-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.iaas.api.auth.github.GithubTokenHandler.getToken(GithubTokenHandler.java:123) ~[cattle-iaas-auth-logic-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.iaas.api.auth.github.TokenResourceManager.getToken(TokenResourceManager.java:59) ~[cattle-iaas-auth-logic-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.iaas.api.auth.github.TokenResourceManager.createInternal(TokenResourceManager.java:50) ~[cattle-iaas-auth-logic-0.5.0-SNAPSHOT.jar:na]
	... 55 common frames omitted
Caused by: java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_79]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_79]
	at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_79]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:625) ~[na:1.7.0_79]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:250) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:118) ~[httpclient-4.3.1.jar:4.3.1]
	... 70 common frames omitted
```

Seems to get passed to the app ok:

```
# ps aux | grep java
root         7 16.4  2.9 3107056 478500 ?      Ssl  06:22   0:59 java -Xms128m -Xmx512m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/lib/cattle/logs -Dhttp.proxyHost=10.10.234.10 -Dhttp.proxyPort=8080 -Dhttps.proxyHost=10.10.234.10 -Dhttps.proxyPort=8080 -jar /usr/share/cattle/cattle.jar
```
Verified with telnet in the container that it can open a connection to 10.10.234.10:8080.

@vincent99 this was the conclusion from what you advised to try on irc today.

**Comment by kaos** [comment]
@sangeethah Ok, had a few weeks vacation come in between, but I just got back, and it seems to work! :) Thanks :+1:

**Comment by wenlock** [comment]
@vincent99 we're seeing the same issue as well in our end.

**Comment by wenlock** [comment]
As an aside, we also have the option at our company to authenticate with github enterprise, which is private auth and corporate creds anyway, so this is better for us.  This avoided the need for an external github connection over proxy, so i no longer get this issue.  However, if you have a private github instance with a custom ssl cert, then you'll get another issue that we solved in the following gist:  https://gist.github.com/wenlock/8bca54ce036b8fec00b3

**Comment by kaos** [comment]
Resolved, right?

**Comment by vincent99** [comment]
The UI is now packaged with the Rancher releases and it loads all the css/fonts/etc from `rancher/server`.  So it is now possible to run `rancher/server` and a browser pointed at the UI on an air-gapped network with no internet access.

Exceptions:
  - The "API UI" is not packaged yet, so clicking to view the API in a browser needs to load JS from the internet (#2077)
  - Some authentication methods (specifically GitHub not-enterprise) obviously require the browser and/or server be able to hit public endpoints.  Local Auth is completely local.
  - Similarly, adding hosts with docker-machine to public clouds (AWS, DigitalOcean, etc) needs to reach their public API endpoints.  Some of the "Other" drivers like OpenStack or VMWare could work locally.
