### ISSUE TITLE
Crashlooping LB service after upgrade to v1.6.2

### ISSUE THREAD

**Issue by skyscooby** [rancher/rancher#9065]
**Rancher versions:**
rancher/server: 1.6.2
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.1
ipsec: v0.11.2
network-services:
rancher/metadata:v0.9.1
rancher/network-manager:v0.7.1
scheduler:

kubernetes (if applicable):
rancher/k8s:v1.5.4-rancher1-4

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      1.12.6

Server Version: 1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS Linux release 7.3.1611 (Core)
3.10.0-514.2.2.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VSphere VM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single master internal DB.

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Upgraded from 1.5.7. Upgraded all components in the stack..

Rancher LB service container keeps crashlooping.

**Results:**
```
time="2017-06-14T21:45:21Z" level=info msg="Starting Rancher LB service" 
time="2017-06-14T21:45:21Z" level=info msg="LB controller: kubernetes" 
time="2017-06-14T21:45:21Z" level=info msg="LB provider: rancher" 
time="2017-06-14T21:45:21Z" level=info msg="starting kubernetes controller" 
time="2017-06-14T21:45:21Z" level=info msg="Healthcheck handler is listening on :10241" 
time="2017-06-14T21:45:21Z" level=info msg="Event(api.ObjectReference{Kind:\"Ingress\", Namespace:\"sean\", Name:\"admin-dashboard\", UID:\"810a0397-5146-11e7-a11f-02184866681d\", APIVersion:\"extensions\", ResourceVersion:\"5107396\", FieldPath:\"\"}): type: 'Normal' reason: 'CREATE' sean/admin-dashboard" 
time="2017-06-14T21:45:21Z" level=info msg="Updating ingress sean/admin-dashboard. Removing IP 172.16.132.85" 
time="2017-06-14T21:45:21Z" level=info msg="Event(api.ObjectReference{Kind:\"Ingress\", Namespace:\"sean\", Name:\"admin-dashboard\", UID:\"810a0397-5146-11e7-a11f-02184866681d\", APIVersion:\"extensions\", ResourceVersion:\"5107416\", FieldPath:\"\"}): type: 'Normal' reason: 'UPDATE' sean/admin-dashboard" 
time="2017-06-14T21:45:21Z" level=info msg="Event(api.ObjectReference{Kind:\"Ingress\", Namespace:\"sean\", Name:\"admin-dashboard\", UID:\"810a0397-5146-11e7-a11f-02184866681d\", APIVersion:\"extensions\", ResourceVersion:\"5107396\", FieldPath:\"\"}): type: 'Normal' reason: 'DELETE' ip: 172.16.132.85" 
time="2017-06-14T21:45:42Z" level=info msg="Event(api.ObjectReference{Kind:\"Ingress\", Namespace:\"sean\", Name:\"admin-dashboard\", UID:\"810a0397-5146-11e7-a11f-02184866681d\", APIVersion:\"extensions\", ResourceVersion:\"5107452\", FieldPath:\"\"}): type: 'Normal' reason: 'UPDATE' sean/admin-dashboard" 
time="2017-06-14T21:45:42Z" level=info msg="Updating ingress sean/admin-dashboard. Removing IP 172.16.132.83" 
time="2017-06-14T21:45:42Z" level=info msg="Updating ingress sean/admin-dashboard. Removing IP 172.16.132.85" 
time="2017-06-14T21:45:42Z" level=info msg="Event(api.ObjectReference{Kind:\"Ingress\", Namespace:\"sean\", Name:\"admin-dashboard\", UID:\"810a0397-5146-11e7-a11f-02184866681d\", APIVersion:\"extensions\", ResourceVersion:\"5107457\", FieldPath:\"\"}): type: 'Normal' reason: 'UPDATE' sean/admin-dashboard" 
time="2017-06-14T21:45:42Z" level=info msg="Event(api.ObjectReference{Kind:\"Ingress\", Namespace:\"sean\", Name:\"admin-dashboard\", UID:\"810a0397-5146-11e7-a11f-02184866681d\", APIVersion:\"extensions\", ResourceVersion:\"5107452\", FieldPath:\"\"}): type: 'Normal' reason: 'DELETE' ip: 172.16.132.83" 
time="2017-06-14T21:45:42Z" level=info msg="Updating ingress sean/admin-dashboard. Removing IP 172.16.132.85" 
panic: runtime error: slice bounds out of range

goroutine 48 [running]:
panic(0x2222ca0, 0xc82001e040)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/rancher/lb-controller/controller/kubernetes.(*loadBalancerController).updateIngressStatus(0xc8202ca140, 0xc820636420, 0x14)
	/go/src/github.com/rancher/lb-controller/controller/kubernetes/kubernetes.go:275 +0x1784
github.com/rancher/lb-controller/controller/kubernetes.(*loadBalancerController).(github.com/rancher/lb-controller/controller/kubernetes.updateIngressStatus)-fm(0xc820636420, 0x14)
	/go/src/github.com/rancher/lb-controller/controller/kubernetes/kubernetes.go:96 +0x34
github.com/rancher/lb-controller/utils.(*TaskQueue).worker(0xc8203ccac0)
	/go/src/github.com/rancher/lb-controller/utils/utils.go:64 +0x138
github.com/rancher/lb-controller/utils.(*TaskQueue).(github.com/rancher/lb-controller/utils.worker)-fm()
	/go/src/github.com/rancher/lb-controller/utils/utils.go:33 +0x20
github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc8206ebf60)
	/go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:84 +0x19
github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc8206ebf60, 0x3b9aca00, 0x0, 0x1, 0xc82040a180)
	/go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:85 +0xb4
github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.Until(0xc8206ebf60, 0x3b9aca00, 0xc82040a180)
	/go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x43
github.com/rancher/lb-controller/utils.(*TaskQueue).Run(0xc8203ccac0, 0x3b9aca00, 0xc82040a180)
	/go/src/github.com/rancher/lb-controller/utils/utils.go:33 +0x48
created by github.com/rancher/lb-controller/controller/kubernetes.(*loadBalancerController).Run
	/go/src/github.com/rancher/lb-controller/controller/kubernetes/kubernetes.go:340 +0x246
```

**Comment by superseb** [comment]
Closing as duplicate as https://github.com/rancher/rancher/issues/8726, can you supply your config there to reproduce?
