### ISSUE TITLE
Rancher CLI panics in parsing

### ISSUE THREAD

**Issue by TimLudwinski** [rancher/rancher#9094]
**Rancher versions:**
rancher/server: v1.6.2
rancher/agent: N/A
rancher/CLI: v0.6.1

**Infrastructure Stack versions:**
healthcheck: N/A
ipsec: N/A
network-services: N/A
scheduler: N/A
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.03.x-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
```3.10.0-229.14.1.el7.x86_64```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Custom

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node with Bind Mounted Database

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle (with Secrets)

**Steps to Reproduce:**
```
> rancher export zaim-backend
> cd zaim-backend
> cat docker-compose.yml
version: '2'
services:
  zaim-backend-webserver:
    mem_limit: 2147483648
    image: dockerregistry1.infra.idef:5000/zaim_sample_processor:0.1.32
    environment:
      PYTHONPATH: /zaim_common:/zaim_sample_processor/lib
    stdin_open: true
    volumes:
    - /mnt/working:/mnt/working
    dns:
    - 192.168.120.28
    tty: true
    ports:
    - 8180:8180/tcp
    memswap_limit: 4294967296
    secrets:
    - gid: '0'
      mode: '444'
      name: zaim_config.cfg
      secretId: 6
      uid: '0'
    - gid: '0'
      mode: '444'
      name: encrypt_passfile
      secretId: 3
      uid: '0'
    - gid: '0'
      mode: '444'
      name: zaim-sampleprocessor.research.idef.crt
      secretId: 4
      uid: '0'
    - gid: '0'
      mode: '444'
      name: zaim-sampleprocessor.research.idef.key
      secretId: 5
      uid: '0'
    labels:
      environment: PRODUCTION
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
  zaim-backend-processor:
    mem_limit: 2147483648
    image: dockerregistry1.infra.idef:5000/zaim_sample_processor:0.1.31
    environment:
      ZAIM_PROC_NUM_START: '1'
      PYTHONPATH: /zaim_common:/zaim_sample_processor/lib
    stdin_open: true
    volumes:
    - /mnt/working:/mnt/working
    dns:
    - 192.168.120.28
    tty: true
    memswap_limit: 4294967296
    secrets:
    - gid: '0'
      mode: '444'
      name: zaim_config.cfg
      secretId: 6
      uid: '0'
    - gid: '0'
      mode: '444'
      name: encrypt_passfile
      secretId: 3
      uid: '0'
    command:
    - python
    - ProcessorDaemon.py
    labels:
      environment: PRODUCTION
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
  zaim-backend-cronjob:
    mem_limit: 4294967296
    image: dockerregistry1.infra.idef:5000/zaim_cronjobs:0.1.46
    environment:
      PYTHONPATH: /zaim_common
      TZ: /usr/share/zoneinfo/America/New_York
    stdin_open: true
    volumes:
    - /mnt/working:/mnt/working
    - /mnt/home/docker-container:/home/docker-container
    dns:
    - 192.168.120.28
    tty: true
    memswap_limit: 8589934592
    secrets:
    - gid: '0'
      mode: '444'
      name: zaim_config.cfg
      secretId: 6
      uid: '0'
    - gid: '0'
      mode: '444'
      name: encrypt_passfile
      secretId: 3
      uid: '0'
    labels:
      environment: PRODUCTION
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
> cat rancher-compose.yml
version: '2'
services:
  zaim-backend-webserver:
    start_on_create: true
  zaim-backend-processor:
    scale: 8
    start_on_create: true
  zaim-backend-cronjob:
    scale: 1
    start_on_create: true
> rancher up
```

**Results:**

```
panic: interface conversion: interface {} is nil, not map[string]interface {} [recovered]
        panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
panic(0xa3f320, 0xc42015d040)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/rancher/cli/vendor/github.com/urfave/cli.HandleAction.func1(0xc4204be968)
        /go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:472 +0x29e
panic(0xa3f320, 0xc42015d040)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/config.parseValidTypesFromSchema(0xc42037fd70, 0xc420012e70, 0x27, 0x0, 0xc420012e70, 0x27)
        /go/src/github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/config/schema_helpers.go:72 +0x6e5
github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/config.oneOfMessage(0xc4203ba240, 0xc42037fd70, 0xe3d0c0, 0xc420387300, 0xe3cb40, 0xc420387200, 0x9b61c0, 0xc420071d40)
        /go/src/github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/config/validation.go:162 +0x5d5
github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/config.generateErrorMessages(0xc4203ba240, 0xc42037fd70, 0xc4203f3ae0, 0xc4203bc2a0, 0xc4203f3ae0)
        /go/src/github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/config/validation.go:258 +0x10f4
github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/config.validateV2(0xc42037f320, 0x0, 0x0)
        /go/src/github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/config/validation.go:222 +0x127
github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/config.MergeServicesV2(0xc4203748a0, 0xe33bc0, 0xc420374860, 0xe33c00, 0xe7ced0, 0xb1f501, 0x12, 0xc42037f320, 0xc4202ad700, 0xa5a, ...)
        /go/src/github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/config/merge_v2.go:13 +0x43
github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/config.Merge(0xc4203748a0, 0xe33bc0, 0xc420374860, 0xe33c00, 0xe7ced0, 0x0, 0x0, 0x0, 0x0, 0xb1f501, ...)
        /go/src/github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/config/merge.go:167 +0x11c8
github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/project.(*Project).load(0xc4200e2a50, 0xb1f501, 0x12, 0xc420336d00, 0xa5a, 0xc5a, 0xc42037e1e0, 0xc42037e1b0)
        /go/src/github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/project/project.go:165 +0xf1
github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/project.(*Project).Parse(0xc4200e2a50, 0xc4200e2a50, 0x5)
        /go/src/github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/project/project.go:97 +0x153
github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/rancher.NewProject(0xc4202a6b60, 0xb1324d, 0x4, 0x300)
        /go/src/github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/rancher/project.go:35 +0x252
github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/app.(*RancherProjectFactory).Create(0xc4204be3c0, 0xc420325040, 0xb13005, 0x4, 0xc4200f5678)
        /go/src/github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/app/app.go:67 +0x6b6
github.com/rancher/cli/cmd.(*projectFactory).Create(0xe7ced0, 0xc420325040, 0x8, 0xc420311e00, 0xc420311e20)
        /go/src/github.com/rancher/cli/cmd/up.go:63 +0x390
github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/app.WithProject.func1(0xc420325040, 0x0, 0x0)
        /go/src/github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/app/app.go:105 +0x4e
reflect.Value.call(0x9f7ca0, 0xc420310c60, 0x13, 0xb12b7d, 0x4, 0xc4204be908, 0x1, 0x1, 0x49f318, 0xaf94c0, ...)
        /usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x9f7ca0, 0xc420310c60, 0x13, 0xc4204be908, 0x1, 0x1, 0x0, 0x140, 0x140)
        /usr/local/go/src/reflect/value.go:302 +0xa4
github.com/rancher/cli/vendor/github.com/urfave/cli.HandleAction(0x9f7ca0, 0xc420310c60, 0xc420325040, 0x0, 0x0)
        /go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:481 +0x1e0
github.com/rancher/cli/vendor/github.com/urfave/cli.Command.Run(0xb12325, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb214a9, 0x15, 0x0, ...)
        /go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/command.go:186 +0xc26
github.com/rancher/cli/vendor/github.com/urfave/cli.(*App).Run(0xc420312180, 0xc42007e060, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:235 +0x60c
main.mainErr(0x0, 0xc420352670)
        /go/src/github.com/rancher/cli/main.go:150 +0x20e6
main.main()
        /go/src/github.com/rancher/cli/main.go:37 +0x26
```

Also `rancher up --render` also panics similarly.

**Comment by TimLudwinski** [comment]
This happens both on Linux and on Windows.

**Comment by TimLudwinski** [comment]
This still happens in CLI: v0.6.2 and server: v1.6.5.

**Comment by amy** [comment]
@TimLudwinski Apologies for the go panic. We're currently looking into preventing this panic from happening.

In the mean time, under the `secrets` fields you have a field called `mode`. Please remove the quotes from those numbers.

For instance...
```
secrets:
    - gid: '0'
      mode: '444'
      name: zaim_config.cfg
      secretId: 6
      uid: '0'
```
Should be changed to...
```
secrets:
    - gid: '0'
      mode: 444
      name: zaim_config.cfg
      secretId: 6
      uid: '0'
```

**Comment by TimLudwinski** [comment]
I'm closing this issue as #9483 seems to encompass it.  I created #9489 for the underlying problem of round trips from `rancher export` and `rancher up -u` not working even after the workaround.
