### ISSUE TITLE
Add host with vSphere ESXi driver fail

### ISSUE THREAD

**Issue by mythay** [rancher/rancher#9292]
**Rancher versions:**
rancher/server:  v1.5-v1.6
rancher/agent: N/A

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vSphere ESXi v6.0
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
A complete new Rancher server , add a host witch vSphere driver. 

**Results:**
The host can not be added to Rancher with error message "https://192.168.88.117:2376/images/create?fromImage=rancher%2Fagent&tag=v1.2.2: net/http: TLS handshake timeout"

I have check the vsphere client that the virtual host has been added and started successfully.

from the docker log I saw
```
time="2017-07-10T08:27:52Z" level=info msg="stdout: Checking connection to Docker..." resourceId: =1ph3 service=gms 
time="2017-07-10T08:27:53Z" level=info msg="stdout: Docker is up and running!" resourceId: =1ph3 service=gms 
time="2017-07-10T08:27:53Z" level=info msg="stdout: To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env node03" resourceId: =1ph3 service=gms 
time="2017-07-10T08:27:53Z" level=info msg="Machine Created" eventId=6fbdb852-5c78-4166-a3bf-886b02cd51cc resourceId=1ph3 service=gms 
time="2017-07-10T08:27:53Z" level=info msg="Creating and uploading extracted machine config" resourceId=1ph3 service=gms 
time="2017-07-10T08:27:54Z" level=info msg="Machine config file saved." eventId=6fbdb852-5c78-4166-a3bf-886b02cd51cc resourceId=1ph3 service=gms 
time="2017-07-10T08:27:54Z" level=info msg="Activating Machine" eventId=644914da-1237-49ff-94fa-ae2585a1b451 resourceId=1ph3 service=gms 
time="2017-07-10T08:27:54Z" level=info msg="Extracting /var/lib/cattle/machine/machines/3503565f-a63f-45c0-b9d5-b992881668cb/cache" service=gms 
time="2017-07-10T08:27:54Z" level=info msg="Extracting /var/lib/cattle/machine/machines/3503565f-a63f-45c0-b9d5-b992881668cb/certs" service=gms 
time="2017-07-10T08:27:54Z" level=info msg="Extracting /var/lib/cattle/machine/machines/3503565f-a63f-45c0-b9d5-b992881668cb/certs/ca-key.pem" service=gms 
time="2017-07-10T08:27:54Z" level=info msg="Extracting /var/lib/cattle/machine/machines/3503565f-a63f-45c0-b9d5-b992881668cb/certs/ca.pem" service=gms 
time="2017-07-10T08:27:54Z" level=info msg="Extracting /var/lib/cattle/machine/machines/3503565f-a63f-45c0-b9d5-b992881668cb/certs/cert.pem" service=gms 
time="2017-07-10T08:27:54Z" level=info msg="Extracting /var/lib/cattle/machine/machines/3503565f-a63f-45c0-b9d5-b992881668cb/certs/key.pem" service=gms 
time="2017-07-10T08:27:54Z" level=info msg="Extracting /var/lib/cattle/machine/machines/3503565f-a63f-45c0-b9d5-b992881668cb/machines" service=gms 
time="2017-07-10T08:27:54Z" level=info msg="Extracting /var/lib/cattle/machine/machines/3503565f-a63f-45c0-b9d5-b992881668cb/machines/node03" service=gms 
time="2017-07-10T08:27:54Z" level=info msg="Extracting /var/lib/cattle/machine/machines/3503565f-a63f-45c0-b9d5-b992881668cb/machines/node03/ca.pem" service=gms 
time="2017-07-10T08:27:54Z" level=info msg="Extracting /var/lib/cattle/machine/machines/3503565f-a63f-45c0-b9d5-b992881668cb/machines/node03/cert.pem" service=gms 
time="2017-07-10T08:27:54Z" level=info msg="Extracting /var/lib/cattle/machine/machines/3503565f-a63f-45c0-b9d5-b992881668cb/machines/node03/config.json" service=gms 
time="2017-07-10T08:27:54Z" level=info msg="Extracting /var/lib/cattle/machine/machines/3503565f-a63f-45c0-b9d5-b992881668cb/machines/node03/created" service=gms 
time="2017-07-10T08:27:54Z" level=info msg="Extracting /var/lib/cattle/machine/machines/3503565f-a63f-45c0-b9d5-b992881668cb/machines/node03/id_rsa" service=gms 
time="2017-07-10T08:27:54Z" level=info msg="Extracting /var/lib/cattle/machine/machines/3503565f-a63f-45c0-b9d5-b992881668cb/machines/node03/id_rsa.pub" service=gms 
time="2017-07-10T08:27:54Z" level=info msg="Extracting /var/lib/cattle/machine/machines/3503565f-a63f-45c0-b9d5-b992881668cb/machines/node03/key.pem" service=gms 
time="2017-07-10T08:27:54Z" level=info msg="Extracting /var/lib/cattle/machine/machines/3503565f-a63f-45c0-b9d5-b992881668cb/machines/node03/server-key.pem" service=gms 
time="2017-07-10T08:27:54Z" level=info msg="Extracting /var/lib/cattle/machine/machines/3503565f-a63f-45c0-b9d5-b992881668cb/machines/node03/server.pem" service=gms 
time="2017-07-10T08:27:54Z" level=info msg="Extracting /var/lib/cattle/machine/machines/3503565f-a63f-45c0-b9d5-b992881668cb/machines/node03/userdata.tar" service=gms 
time="2017-07-10T08:27:55Z" level=info msg="pulling rancher/agent:v1.2.2 image." service=gms 
time="2017-07-10T08:28:05Z" level=error msg="Error processing event" err="Post https://192.168.88.117:2376/images/create?fromImage=rancher%2Fagent&tag=v1.2.2: net/http: TLS handshake timeout" eventId=644914da-1237-49ff-94fa-ae2585a1b451 eventName="physicalhost.bootstrap;handler=goMachineService" resourceId=1ph3 
2017-07-10 08:28:05,731 ERROR [3ff08da6-78d7-4330-9c38-bd3a1db71578:221] [physicalHost:3] [physicalhost.bootstrap] [] [ecutorService-2] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [physicalhost.bootstrap.reply;handler=goMachineService]: Post https://192.168.88.117:2376/images/create?fromImage=rancher%2Fagent&tag=v1.2.2: net/http: TLS handshake timeout 
2017-07-10 08:28:05,844 ERROR [:] [] [] [] [ecutorService-2] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [physicalhost.bootstrap.reply;handler=goMachineService]: Post https://192.168.88.117:2376/images/create?fromImage=rancher%2Fagent&tag=v1.2.2: net/http: TLS handshake timeout 
2017-07-10 08:28:07,462 ERROR [a416e43d-99f0-48c2-9f31-7382e9765110:222] [host:3] [host.provision] [] [ecutorService-6] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.util.exception.ExecutionException: Post https://192.168.88.117:2376/images/create?fromImage=rancher%2Fagent&tag=v1.2.2: net/http: TLS handshake timeout
	at io.cattle.platform.process.host.HostProvision.handle(HostProvision.java:77) ~[cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:470) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:421) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:415) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:415) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:517) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:345) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:245) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:242) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:184) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:157) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:116) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:113) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:113) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl.processExecuteWithLock(ProcessInstanceDispatcherImpl.java:117) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl$1.doWithLock(ProcessInstanceDispatcherImpl.java:104) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl$1.doWithLock(ProcessInstanceDispatcherImpl.java:101) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$4.doWithLock(AbstractLockManagerImpl.java:50) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:25) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:47) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl.execute(ProcessInstanceDispatcherImpl.java:101) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.server.ProcessInstanceReference.doRun(ProcessInstanceReference.java:58) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
```
Then I use curl to test the url to see if the host is not accessiable

```
root@be0bc2f252d5:/# curl -k https://192.168.88.117:2376/images/create?fromImage=rancher%2Fagent&tag=v1.2.2
[1] 446
root@be0bc2f252d5:/# curl: (35) error:14094412:SSL routines:SSL3_READ_BYTES:sslv3 alert bad certificate

[1]+  Exit 35                 curl -k https://192.168.88.117:2376/images/create?fromImage=rancher%2Fagent
```

**Comment by rockandska** [comment]
Does your ESXI is managed by a provider ?
If i'm right, i had exactly the same issue with my ESXI managed by OVH and was related to a bug on their side.
After they applied a correction on their side, everything was fine for me

**Comment by chrodriguez** [comment]
I think the problem is with **cattle-iaas-logic-0.5.0-SNAPSHOT.jar**. We are using rancher server 1.6.7 and the problem is reported differently but, I think is the same problem.
rancher server logs says:

```
time="2018-03-08T15:07:07Z" level=info msg="Extracting /var/lib/cattle/machine/machines/0143400a-a5b2-42a2-b927-164b34f844d0/machines/test-rancher-dm-01/server-key.pem" service=gms 
time="2018-03-08T15:07:07Z" level=info msg="Extracting /var/lib/cattle/machine/machines/0143400a-a5b2-42a2-b927-164b34f844d0/machines/test-rancher-dm-01/server.pem" service=gms 
time="2018-03-08T15:07:07Z" level=info msg="Extracting /var/lib/cattle/machine/machines/0143400a-a5b2-42a2-b927-164b34f844d0/machines/test-rancher-dm-01/userdata.tar" service=gms 
time="2018-03-08T15:07:07Z" level=info msg="pulling rancher/agent:v1.2.5 image." service=gms 
time="2018-03-08T15:08:07Z" level=error msg="Error processing event" err="Post https://10.0.56.45:2376/images/create?fromImage=rancher%2Fagent&tag=v1.2.5: Service Unavailable" eventId=796c517a-52b3-45a6-9e50-98b7bad6f8b2 eventName="physicalhost.bootstrap;handler=goMachineService" resourceId=1ph97 
2018-03-08 15:08:09,661 ERROR [71203e60-f1b7-4fa2-8e74-c9d86e76f122:684535] [host:97] [host.provision] [] [cutorService-43] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.util.exception.ExecutionException: Post https://10.0.56.45:2376/images/create?fromImage=rancher%2Fagent&tag=v1.2.5: Service Unavailable
	at io.cattle.platform.process.host.HostProvision.handle(HostProvision.java:77) ~[cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]

``` 

Looking at recently created VM docker logs, we can see the TLS handshake error. It seems to be a problem with the iaas logic library, that tries to interact with docker API without proper certificates

**Comment by chrodriguez** [comment]
I've found our problem.  It seems to be a proxy problem. We solved this issue not using proxy for accesisng nodes machines network

**Comment by superseb** [comment]
Thanks for reporting back @chrodriguez !
