### ISSUE TITLE
Failed to find instance to delegate to for agent 1.4.3

### ISSUE THREAD

**Issue by robertoamoreno** [rancher/rancher#9316]
Component	Version
Rancher	v1.4.3
Cattle	v0.176.11
User Interface	v1.4.9
Rancher CLI	v0.4.1
Rancher Compose	v0.12.2

Having similiar issues as [7133](https://github.com/rancher/rancher/issues/7133) non of the solutions work does anybody have any other ideas.

Related to this post on forums https://forums.rancher.com/t/cant-add-hosts-health-timeout/6827

**Comment by cjellick** [comment]
Original problem statement from forum post:
>Suddenly when adding new host it dosent properly add to rancher. 
Health Agent fails with a time out and not much log info from other containers. Nothing really changes just stopped working.


Logs from the above forum post, just to have them in one place:

Net manager
```
7/9/2017 2:43:42 PMtime="2017-07-09T20:43:42Z" level=info msg="Starting event router."
7/9/2017 2:43:42 PMiptables: No chain/target/match by that name.
7/9/2017 2:43:42 PMtime="2017-07-09T20:43:42Z" level=info msg="Container [795984be201e6fe320528f0161d31dfb3d8e8a3b27c379de079d025d0f892da8] not running. Can't setup resolv.conf."
7/9/2017 2:43:45 PMtime="2017-07-09T20:43:45Z" level=info msg="Setting up resolv.conf for ContainerId [cc6a8a71f975573bfb2633456b971b048b2226319036a156a93aebccde16f529]"
7/9/2017 2:43:45 PMtime="2017-07-09T20:43:45Z" level=info msg="CNI up" cid=cc6a8a71f975573bfb2633456b971b048b2226319036a156a93aebccde16f529 networkMode=ipsec
7/9/2017 2:43:45 PMtime="2017-07-09T20:43:45Z" level=info msg="CNI up done" cid=cc6a8a71f975573bfb2633456b971b048b2226319036a156a93aebccde16f529 networkMode=ipsec result=
7/9/2017 2:44:49 PMtime="2017-07-09T20:44:49Z" level=info msg="CNI down" cid=cc6a8a71f975573bfb2633456b971b048b2226319036a156a93aebccde16f529 networkMode=ipsec
7/9/2017 2:45:26 PMtime="2017-07-09T20:45:26Z" level=info msg="Setting up resolv.conf for ContainerId [610a4dcedf72c8451e4a051e6af22a05224f6e2e31067e7d0147a45583aeae2b]"
7/9/2017 2:45:26 PMtime="2017-07-09T20:45:26Z" level=info msg="CNI up" cid=610a4dcedf72c8451e4a051e6af22a05224f6e2e31067e7d0147a45583aeae2b networkMode=ipsec
7/9/2017 2:45:26 PMtime="2017-07-09T20:45:26Z" level=info msg="CNI up done" cid=610a4dcedf72c8451e4a051e6af22a05224f6e2e31067e7d0147a45583aeae2b networkMode=ipsec result=
7/9/2017 2:46:30 PMtime="2017-07-09T20:46:30Z" level=info msg="CNI down" cid=610a4dcedf72c8451e4a051e6af22a05224f6e2e31067e7d0147a45583aeae2b networkMode=ipsec
7/9/2017 2:47:11 PMtime="2017-07-09T20:47:11Z" level=info msg="Setting up resolv.conf for ContainerId [b0a82eeb2d933e053caba27cfac8c03b35e60e3d35927d1b4ee8ff3c76613997]"
7/9/2017 2:47:11 PMtime="2017-07-09T20:47:11Z" level=info msg="CNI up" cid=b0a82eeb2d933e053caba27cfac8c03b35e60e3d35927d1b4ee8ff3c76613997 networkMode=ipsec
7/9/2017 2:47:11 PMtime="2017-07-09T20:47:11Z" level=info msg="CNI up done" cid=b0a82eeb2d933e053caba27cfac8c03b35e60e3d35927d1b4ee8ff3c76613997 networkMode=ipsec result=
7/9/2017 2:48:15 PMtime="2017-07-09T20:48:15Z" level=info msg="CNI down" cid=b0a82eeb2d933e053caba27cfac8c03b35e60e3d35927d1b4ee8ff3c76613997 networkMode=ipsec
7/9/2017 2:49:11 PMnet.ipv4.conf.docker0.route_localnet = 1
7/9/2017 2:49:11 PMiptables: No chain/target/match by that name.
7/9/2017 2:49:11 PMtime="2017-07-09T20:49:11Z" level=info msg="Setting up resolv.conf for ContainerId [2aee2b241ae8be0c9a4e4467130aa25582dbbce02005704ce2cb545d14a4fc61]"
7/9/2017 2:49:11 PMtime="2017-07-09T20:49:11Z" level=info msg="CNI up" cid=2aee2b241ae8be0c9a4e4467130aa25582dbbce02005704ce2cb545d14a4fc61 networkMode=ipsec
7/9/2017 2:49:11 PMtime="2017-07-09T20:49:11Z" level=info msg="CNI up done" cid=2aee2b241ae8be0c9a4e4467130aa25582dbbce02005704ce2cb545d14a4fc61 networkMode=ipsec result=
```

Agent
```
Id: b9aae88c-5b5b-4a00-aaba-006cf5beafe1, Resource Id: 1ihm127691" 
time="2017-07-10T15:52:06Z" level=info msg="rancher id [1230091]: Container with docker id [211a59b47ed0591070c8bb02beb27a16dab058b2f82acb6c7bdf39f57e07a838] has been started" 
time="2017-07-10T15:52:37Z" level=error msg="Error processing event" err=Timeout getting IP address eventId=b9aae88c-5b5b-4a00-aaba-006cf5beafe1 eventName=compute.instance.activate resourceId=1ihm127691 
time="2017-07-10T15:52:37Z" level=info msg="Received event: Name: compute.instance.activate, Event Id: 5550b448-dde2-4295-b985-0c8122d85206, Resource Id: 1ihm127691" 
time="2017-07-10T15:52:37Z" level=error msg="Error processing event" err=Timeout getting IP address eventId=5550b448-dde2-4295-b985-0c8122d85206 eventName=compute.instance.activate resourceId=1ihm127691 
time="2017-07-10T15:52:38Z" level=info msg="Received event: Name: compute.instance.activate, Event Id: a82a6b19-e9ea-486d-91ce-d99deecc28ee, Resource Id: 1ihm127691" 
time="2017-07-10T15:53:09Z" level=error msg="Error processing event" err=Timeout getting IP address eventId=a82a6b19-e9ea-486d-91ce-d99deecc28ee eventName=compute.instance.activate resourceId=1ihm127691 
time="2017-07-10T15:53:09Z" level=info msg="Received event: Name: compute.instance.deactivate, Event Id: 588041be-368b-4b3b-99f6-51992298fe59, Resource Id: 1ihm127691" 
time="2017-07-10T15:53:10Z" level=info msg="rancher id [1230091]: Container with docker id [211a59b47ed0591070c8bb02beb27a16dab058b2f82acb6c7bdf39f57e07a838] has been deactivated" 
time="2017-07-10T15:53:10Z" level=info msg="Reply: 588041be-368b-4b3b-99f6-51992298fe59, compute.instance.deactivate, 1ihm127691:instanceHostMap" 
time="2017-07-10T15:55:03Z" level=info msg="Received event: Name: storage.volume.remove, Event Id: 680f7b1f-e9db-4f83-8108-e452a4ad3eae, Resource Id: 1vspm257370" 
time="2017-07-10T15:55:03Z" level=info msg="rancher id [1vspm257370]: Volume with name [] has been removed" 
time="2017-07-10T15:55:03Z" level=info msg="Reply: 680f7b1f-e9db-4f83-8108-e452a4ad3eae, storage.volume.remove, 1vspm257370:volumeStoragePoolMap" 
time="2017-07-10T15:57:21Z" level=info msg="Received event: Name: storage.image.activate, Event Id: 2adb5c72-1984-4b40-9131-2f3a3b08729e, Resource Id: 1ispm125835" 
time="2017-07-10T15:57:21Z" level=info msg="Reply: 2adb5c72-1984-4b40-9131-2f3a3b08729e, storage.image.activate, 1ispm125835:imageStoragePoolMap" 
time="2017-07-10T15:57:21Z" level=info msg="Received event: Name: storage.volume.activate, Event Id: 04aa5e15-6dee-4c00-a8a4-71e8a9e567d7, Resource Id: 1vspm257371" 
time="2017-07-10T15:57:21Z" level=info msg="Reply: 04aa5e15-6dee-4c00-a8a4-71e8a9e567d7, storage.volume.activate, 1vspm257371:volumeStoragePoolMap" 
time="2017-07-10T15:57:21Z" level=info msg="Received event: Name: compute.instance.activate, Event Id: 353f5dbd-3ea5-4604-8967-9d14857711ab, Resource Id: 1ihm127692" 
time="2017-07-10T15:57:22Z" level=info msg="rancher id [1230092]: Container with docker id [b7831b6c48784b0c4609a70e9ef3c46235ea79e0fff6bf05508737a3e7a04b70] has been started" 
time="2017-07-10T15:57:53Z" level=error msg="Error processing event" err=Timeout getting IP address eventId=353f5dbd-3ea5-4604-8967-9d14857711ab eventName=compute.instance.activate resourceId=1ihm127692 
time="2017-07-10T15:57:53Z" level=info msg="Received event: Name: compute.instance.activate, Event Id: a80ac0a1-41c0-4d63-91f4-741a763f8b26, Resource Id: 1ihm127692" 
time="2017-07-10T15:57:53Z" level=error msg="Error processing event" err=Timeout getting IP address eventId=a80ac0a1-41c0-4d63-91f4-741a763f8b26 eventName=compute.instance.activate resourceId=1ihm127692 
time="2017-07-10T15:57:54Z" level=info msg="Received event: Name: compute.instance.activate, Event Id: 3db4d606-bc41-49b9-8457-0ec1d34dee9b, Resource Id: 1ihm127692" 
time="2017-07-10T15:58:25Z" level=error msg="Error processing event" err=Timeout getting IP address eventId=3db4d606-bc41-49b9-8457-0ec1d34dee9b eventName=compute.instance.activate resourceId=1ihm127692 
time="2017-07-10T15:58:26Z" level=info msg="Received event: Name: compute.instance.deactivate, Event Id: 8052a9bf-b735-4c91-a1d4-f00e02ebe7e0, Resource Id: 1ihm127692" 
time="2017-07-10T15:58:26Z" level=info msg="rancher id [1230092]: Container with docker id [b7831b6c48784b0c4609a70e9ef3c46235ea79e0fff6bf05508737a3e7a04b70] has been deactivated" 
time="2017-07-10T15:58:26Z" level=info msg="Reply: 8052a9bf-b735-4c91-a1d4-f00e02ebe7e0, compute.instance.deactivate, 1ihm127692:instanceHostMap" 
time="2017-07-10T15:58:32Z" level=info msg="Received event: Name: compute.instance.remove, Event Id: 44ef19c1-8a20-4676-a931-c9236c320991, Resource Id: 1ihm127690" 
time="2017-07-10T15:58:32Z" level=info msg="Reply: 44ef19c1-8a20-4676-a931-c9236c320991, compute.instance.remove, 1ihm127690:instanceHostMap" 
time="2017-07-10T16:00:17Z" level=info msg="Received event: Name: storage.volume.remove, Event Id: 1af3be5a-bd44-4ef5-8c81-3654716c2ca4, Resource Id: 1vspm257371" 
time="2017-07-10T16:00:17Z" level=info msg="rancher id [1vspm257371]: Volume with name [] has been removed" 
time="2017-07-10T16:00:17Z" level=info msg="Reply: 1af3be5a-bd44-4ef5-8c81-3654716c2ca4, storage.volume.remove, 1vspm257371:volumeStoragePoolMap" 
time="2017-07-10T16:02:32Z" level=info msg="Received event: Name: compute.instance.remove, Event Id: 3dcb4f3c-de25-4c3a-9765-28c60f0755be, Resource Id: 1ihm127692" 
time="2017-07-10T16:02:32Z" level=info msg="Reply: 3dcb4f3c-de25-4c3a-9765-28c60f0755be, compute.instance.remove, 1ihm127692:instanceHostMap" 
time="2017-07-10T16:02:32Z" level=info msg="Received event: Name: compute.instance.remove, Event Id: 8f702db2-8420-4248-90d4-05d161593279, Resource Id: 1ihm127691" 
time="2017-07-10T16:02:32Z" level=info msg="Reply: 8f702db2-8420-4248-90d4-05d161593279, compute.instance.remove, 1ihm127691:instanceHostMap" 
time="2017-07-10T16:02:34Z" level=info msg="Received event: Name: storage.image.activate, Event Id: 5bd6db04-5847-4cb1-9c85-7642782c6797, Resource Id: 1ispm125836" 
time="2017-07-10T16:02:34Z" level=info msg="Reply: 5bd6db04-5847-4cb1-9c85-7642782c6797, storage.image.activate, 1ispm125836:imageStoragePoolMap" 
time="2017-07-10T16:02:36Z" level=info msg="Received event: Name: storage.volume.activate, Event Id: 3199a2a7-4709-4355-879a-5dc1ac7b0607, Resource Id: 1vspm257372" 
time="2017-07-10T16:02:36Z" level=info msg="Reply: 3199a2a7-4709-4355-879a-5dc1ac7b0607, storage.volume.activate, 1vspm257372:volumeStoragePoolMap" 
time="2017-07-10T16:02:37Z" level=info msg="Received event: Name: compute.instance.activate, Event Id: 49cbd633-7efe-4eef-96d7-767c8ec00432, Resource Id: 1ihm127693" 
time="2017-07-10T16:02:37Z" level=info msg="rancher id [1230093]: Container with docker id [fcc043f99d9de1430bd68062c398b320af93b0aa7a653d164380737d3e8fa229] has been started" 
time="2017-07-10T16:03:09Z" level=error msg="Error processing event" err=Timeout getting IP address eventId=49cbd633-7efe-4eef-96d7-767c8ec00432 eventName=compute.instance.activate resourceId=1ihm127693 
time="2017-07-10T16:03:09Z" level=info msg="Received event: Name: compute.instance.activate, Event Id: adfc8740-9856-47b2-8eb2-e0cbf344f145, Resource Id: 1ihm127693" 
time="2017-07-10T16:03:09Z" level=error msg="Error processing event" err=Timeout getting IP address eventId=adfc8740-9856-47b2-8eb2-e0cbf344f145 eventName=compute.instance.activate resourceId=1ihm127693 
time="2017-07-10T16:03:09Z" level=info msg="Received event: Name: compute.instance.activate, Event Id: 396fb637-e801-4d39-b149-35241182a654, Resource Id: 1ihm127693" 
time="2017-07-10T16:03:41Z" level=error msg="Error processing event" err=Timeout getting IP address eventId=396fb637-e801-4d39-b149-35241182a654 eventName=compute.instance.activate resourceId=1ihm127693 
time="2017-07-10T16:03:41Z" level=info msg="Received event: Name: compute.instance.deactivate, Event Id: 0ff7c093-ef90-4838-a64d-c208b86d39f5, Resource Id: 1ihm127693" 
time="2017-07-10T16:03:41Z" level=info msg="rancher id [1230093]: Container with docker id [fcc043f99d9de1430bd68062c398b320af93b0aa7a653d164380737d3e8fa229] has been deactivated" 
time="2017-07-10T16:03:41Z" level=info msg="Reply: 0ff7c093-ef90-4838-a64d-c208b86d39f5, compute.instance.deactivate, 1ihm127693:instanceHostMap" 
time="2017-07-10T16:05:32Z" level=info msg="Received event: Name: storage.volume.remove, Event Id: 23a98df8-6e04-48d5-b8ac-4ced6659979c, Resource Id: 1vspm257372" 
time="2017-07-10T16:05:32Z" level=info msg="rancher id [1vspm257372]: Volume with name [] has been removed" 
time="2017-07-10T16:05:32Z" level=info msg="Reply: 23a98df8-6e04-48d5-b8ac-4ced6659979c, storage.volume.remove, 1vspm257372:volumeStoragePoolMap"
```

From OP:
>I did notice this error log on server over and over
```
2017-07-11 09:13:45,573 ERROR [:] [] [] [] [ecutorService-5] [i.c.p.agent.impl.AgentLocatorImpl ] Failed to find instance to delegate to for agent [15303] uri [delegate:///?vnetId=4742&networkServiceProviderId=1]
2017-07-11 09:13:45,574 ERROR [:] [] [] [] [ecutorService-5] [.p.c.v.i.ConfigItemStatusManagerImpl] Error updating item(s) [agent-instance-startup, healthcheck, iptables, hosts, ipsec-hosts, ipsec, node-services] on [agent:153
03] com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Delegate [delegate:///?vnetId=4742&networkServiceProviderId=1] has no instance associated
at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199) ~[guava-15.0.jar:na]
at com.google.common.cache.LocalCache.get(LocalCache.java:3932) ~[guava-15.0.jar:na]
at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3936) ~[guava-15.0.jar:na]
at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4806) ~[guava-15.0.jar:na]
at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4812) ~[guava-15.0.jar:na]
```

**Comment by cjellick** [comment]
@leodotcloud Does anything in the network manager logs look obviously broken to you?
@ibuildthecloud is that cattle error a known issue?

**Comment by leodotcloud** [comment]
@cjellick @robertoamoreno What do the logs of `ipsec*cni*` container look like? Do you see the IP being found for the containers? The network manager log doesn't tell me about that, I can just see the containers going up and down.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
