### ISSUE TITLE
Configuring SAML with PingFederate cause a panic

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#9429]
**Rancher versions:**
rancher/server: v1.6.6-rc1

**Steps to Reproduce:**
- Enable SAML with PingFederate authentication
- Add attribute:
```
sAMAccountName
displayName
givenName
memberOf
```
- Add self signed certificate
- Add the exported metadata from the ping federate server

**Results:**

I get 500 error, here are the server logs:
```
2017/07/21 16:56:58 http: panic serving 127.0.0.1:56998: runtime error: invalid memory address or nil pointer dereference
goroutine 570 [running]:
net/http.(*conn).serve.func1(0xc42054aa00)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0xb89c40, 0x11accd0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/rancher/rancher-auth-service/vendor/github.com/crewjam/saml.(*ServiceProvider).GetSSOBindingLocation(0xc4203b0e60, 0xc4a73f, 0x32, 0x0, 0x0)
	/go/src/github.com/rancher/rancher-auth-service/vendor/github.com/crewjam/saml/service_provider.go:137 +0x3f
github.com/rancher/rancher-auth-service/vendor/github.com/crewjam/saml/samlsp.(*Middleware).RequireAccount.func1(0x11cd5e0, 0xc420682620, 0xc420584b00)
	/go/src/github.com/rancher/rancher-auth-service/vendor/github.com/crewjam/saml/samlsp/middleware.go:122 +0x133
net/http.HandlerFunc.ServeHTTP(0xc42045f480, 0x11cd5e0, 0xc420682620, 0xc420584b00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/rancher/rancher-auth-service/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201d67d0, 0x11cd5e0, 0xc420682620, 0xc420584b00)
	/go/src/github.com/rancher/rancher-auth-service/vendor/github.com/gorilla/mux/mux.go:107 +0x10c
net/http.serverHandler.ServeHTTP(0xc4201cec60, 0x11cd5e0, 0xc420682620, 0xc420584600)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42054aa00, 0x11cde20, 0xc4201f8cc0)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
2017/07/21 16:56:58 http: panic serving 127.0.0.1:57006: runtime error: invalid memory address or nil pointer dereference
goroutine 608 [running]:
net/http.(*conn).serve.func1(0xc42054ae60)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0xb89c40, 0x11accd0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/rancher/rancher-auth-service/vendor/github.com/crewjam/saml.(*ServiceProvider).GetSSOBindingLocation(0xc4203b0e60, 0xc4a73f, 0x32, 0x0, 0x0)
	/go/src/github.com/rancher/rancher-auth-service/vendor/github.com/crewjam/saml/service_provider.go:137 +0x3f
github.com/rancher/rancher-auth-service/vendor/github.com/crewjam/saml/samlsp.(*Middleware).RequireAccount.func1(0x11cd5e0, 0xc4206827e0, 0xc420584e00)
	/go/src/github.com/rancher/rancher-auth-service/vendor/github.com/crewjam/saml/samlsp/middleware.go:122 +0x133
net/http.HandlerFunc.ServeHTTP(0xc42045f480, 0x11cd5e0, 0xc4206827e0, 0xc420584e00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/rancher/rancher-auth-service/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201d67d0, 0x11cd5e0, 0xc4206827e0, 0xc420584e00)
	/go/src/github.com/rancher/rancher-auth-service/vendor/github.com/gorilla/mux/mux.go:107 +0x10c
net/http.serverHandler.ServeHTTP(0xc4201cec60, 0x11cd5e0, 0xc4206827e0, 0xc420584c00)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42054ae60, 0x11cde20, 0xc4202b33c0)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
2017/07/21 16:56:58 http: panic serving 127.0.0.1:57008: runtime error: invalid memory address or nil pointer dereference
goroutine 610 [running]:
net/http.(*conn).serve.func1(0xc42054af00)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0xb89c40, 0x11accd0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/rancher/rancher-auth-service/vendor/github.com/crewjam/saml.(*ServiceProvider).GetSSOBindingLocation(0xc4203b0e60, 0xc4a73f, 0x32, 0x0, 0x0)
	/go/src/github.com/rancher/rancher-auth-service/vendor/github.com/crewjam/saml/service_provider.go:137 +0x3f
github.com/rancher/rancher-auth-service/vendor/github.com/crewjam/saml/samlsp.(*Middleware).RequireAccount.func1(0x11cd5e0, 0xc420683880, 0xc420585100)
	/go/src/github.com/rancher/rancher-auth-service/vendor/github.com/crewjam/saml/samlsp/middleware.go:122 +0x133
net/http.HandlerFunc.ServeHTTP(0xc42045f480, 0x11cd5e0, 0xc420683880, 0xc420585100)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/rancher/rancher-auth-service/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201d67d0, 0x11cd5e0, 0xc420683880, 0xc420585100)
	/go/src/github.com/rancher/rancher-auth-service/vendor/github.com/gorilla/mux/mux.go:107 +0x10c
net/http.serverHandler.ServeHTTP(0xc4201cec60, 0x11cd5e0, 0xc420683880, 0xc420584f00)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42054af00, 0x11cde20, 0xc4202b3740)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
2017/07/21 16:56:58 http: panic serving 127.0.0.1:57010: runtime error: invalid memory address or nil pointer dereference
goroutine 612 [running]:
net/http.(*conn).serve.func1(0xc42054afa0)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0xb89c40, 0x11accd0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/rancher/rancher-auth-service/vendor/github.com/crewjam/saml.(*ServiceProvider).GetSSOBindingLocation(0xc4203b0e60, 0xc4a73f, 0x32, 0x0, 0x0)
	/go/src/github.com/rancher/rancher-auth-service/vendor/github.com/crewjam/saml/service_provider.go:137 +0x3f
github.com/rancher/rancher-auth-service/vendor/github.com/crewjam/saml/samlsp.(*Middleware).RequireAccount.func1(0x11cd5e0, 0xc420683c00, 0xc420585400)
	/go/src/github.com/rancher/rancher-auth-service/vendor/github.com/crewjam/saml/samlsp/middleware.go:122 +0x133
net/http.HandlerFunc.ServeHTTP(0xc42045f480, 0x11cd5e0, 0xc420683c00, 0xc420585400)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/rancher/rancher-auth-service/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201d67d0, 0x11cd5e0, 0xc420683c00, 0xc420585400)
	/go/src/github.com/rancher/rancher-auth-service/vendor/github.com/gorilla/mux/mux.go:107 +0x10c
net/http.serverHandler.ServeHTTP(0xc4201cec60, 0x11cd5e0, 0xc420683c00, 0xc420585200)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42054afa0, 0x11cde20, 0xc4202b3b40)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
2017-07-21 16:56:58,917 ERROR [:] [] [] [] [tp1020391880-14] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [http://x.x.x.x:8080/v1/proxy/http://localhost:8090/v1-auth/saml/login]. Error id: [2269afa3-c4c5-4790-889b-849097cf5195]. org.apache.http.NoHttpResponseException: The target server failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260) ~[httpcore-4.3.jar:4.3]
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161) ~[httpcore-4.3.jar:4.3]
	at sun.reflect.GeneratedMethodAccessor598.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_72]
	at org.apache.http.impl.conn.CPoolProxy.invoke(CPoolProxy.java:138) ~[httpclient-4.3.1.jar:4.3.1]
	at com.sun.proxy.$Proxy83.receiveResponseHeader(Unknown Source) ~[na:na]
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271) ~[httpcore-4.3.jar:4.3]
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123) ~[httpcore-4.3.jar:4.3]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:253) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57) ~[httpclient-4.3.1.jar:4.3.1]
	at org.apache.http.client.fluent.Executor.execute(Executor.java:215) ~[fluent-hc-4.3.1.jar:4.3.1]
	at io.cattle.platform.iaas.api.request.handler.GenericWhitelistedProxy.generate(GenericWhitelistedProxy.java:353) ~[cattle-iaas-api-logic-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.AbstractResponseGenerator.handle(AbstractResponseGenerator.java:14) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:99) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:96) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:106) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at io.cattle.platform.iaas.api.servlet.filter.ProxyPreFilter.doFilter(ProxyPreFilter.java:22) [cattle-iaas-api-logic-0.5.0-SNAPSHOT.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:595) [jetty-security-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:191) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:72) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at io.cattle.platform.iaas.api.servlet.filter.ProxyFilter.doFilter(ProxyFilter.java:65) [cattle-iaas-api-logic-0.5.0-SNAPSHOT.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [jetty-security-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.Server.handle(Server.java:499) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
```

**Comment by mrajashree** [comment]
https://github.com/rancher/rancher/issues/9417
Related because you first entered `cn` that was not released by the pingFederdate, later you changed it to sAMAccountName but the config wasn't updated because of the above bug, fix for that is in, once auth-service is released these both can be tested

**Comment by galal-hussein** [comment]
Rancher Server: v1.6.6-rc2

Steps to validate:

- Enable SAML authentication with PingFederate using the following attribute
  - displayName
  - givenName
  - memberOf
  - cn (which is wrong)
- Save and test
you should not be able to authenticate
- Fix the attribute and change `cn` with `sAMAccountName` 
- Save and Test
SAML authentication enabled normally.
