### ISSUE TITLE
Panic in AuthService when upgrading openLDAP enabled setup from 1.6.5-> 1.6.6-rc2.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#9448]
Setup:
Rancher server setup ->1.6.5
Have openLDAP enabled 

Upgrade to  1.6.6-rc2
Once rancher-server is upgraded , there is constant Panic seen in AuthService

Not able to access "Admin"-> AccessControl tab from UI.

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x80ad14]

goroutine 1 [running]:
github.com/rancher/rancher-auth-service/vendor/github.com/urfave/cli.HandleAction.func1(0xc420207988)
	/go/src/github.com/rancher/rancher-auth-service/vendor/github.com/urfave/cli/app.go:472 +0x28d
panic(0xb89c40, 0x11accd0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/rancher/rancher-auth-service/server.UpgradeCase(0xc420105488, 0x1)
	/go/src/github.com/rancher/rancher-auth-service/server/auth_server.go:652 +0x8b4
main.StartService(0xc4200c2280)
	/go/src/github.com/rancher/rancher-auth-service/main.go:135 +0x1a7
reflect.Value.call(0xb35940, 0xc50bf0, 0x13, 0xc300a9, 0x4, 0xc420055928, 0x1, 0x1, 0xc4200558b0, 0xc1b3c0, ...)
	/usr/local/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0xb35940, 0xc50bf0, 0x13, 0xc420055928, 0x1, 0x1, 0xb84b00, 0xc4200119b0, 0xc3376e)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/rancher/rancher-auth-service/vendor/github.com/urfave/cli.HandleAction(0xb35940, 0xc50bf0, 0xc4200c2280, 0x0, 0x0)
	/go/src/github.com/rancher/rancher-auth-service/vendor/github.com/urfave/cli/app.go:481 +0x198
github.com/rancher/rancher-auth-service/vendor/github.com/urfave/cli.(*App).Run(0xc4200fc000, 0xc4200104b0, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/rancher/rancher-auth-service/vendor/github.com/urfave/cli/app.go:240 +0x560
main.main()
	/go/src/github.com/rancher/rancher-auth-service/main.go:116 +0xcfb
```

**Comment by sangeethah** [comment]
Rancher server setup ->1.6.5
Have openLDAP enabled
Upgrade to 1.6.6-rc3
Once rancher-server is upgraded , there is no panic seen in  AuthService .

Able to access "Admin"-> AccessControl tab from UI successfully.
