### ISSUE TITLE
agent should properly error out if host registration url does not match (subset of) provided url

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#9464]
**Rancher versions:**
rancher/agent: v1.2.5

When the provided URL to `rancher/agent` and the host registration url at the `rancher/server` differ, we can notice this and error out instead.

**Steps to Reproduce:**

Running `sudo docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.5 http://188.226.161.165:8080/v1/scripts/xxx:xxx` when host registration url is set to `http://127.0.0.1:80801 results in:

```
...
INFO: Running registration                                                     
Traceback (most recent call last):                                             
  File "./register.py", line 11, in <module>                                   
    secret_key=os.environ['CATTLE_REGISTRATION_SECRET_KEY'])                   
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 45, in from_env                                                                               
    return gdapi.from_env(prefix=prefix, factory=Client, **kw)                 
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 613, in from_env                                                                               
    return _from_env(prefix=prefix, factory=factory, **args)                   
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 632, in _from_env                                                                              
    return factory(**result)                                                   
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 12, in __init__                                                                               
    super(Client, self).__init__(*args, **kw)                                  
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 197, in __init__                                                                               
    self._load_schemas()                                                       
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 315, in _load_schemas                                                                          
    response = self._get_response(self._url)                                   
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 264, in _get_response                                                                          
    headers=self._headers)                                                     
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get                                                                        
    return self.request('GET', url, **kwargs)                                  
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request                                                                    
    resp = self.send(prep, **send_kwargs)                                      
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send                                                                       
    r = adapter.send(request, **kwargs)                                        
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send                                                                       
    raise ConnectionError(e, request=request)                                  
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f49a05f6810>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by Caroga** [comment]
Today I've got this same error. I'm glad that superseb could tell me what was wrong as I totally did not understand. As this is my first setup with a differing ip address, I can really say that it should have a nice error. 
Thanks @superseb!

:+1:

**Comment by sangeethah** [comment]
Tested with rancher server version - v1.6.15-rc3

When there is a mismatch between the registration url set in rancher server (in my case had port as 8081) and in agent registration command , user is not presented with the following error message and no stack trace is seen:

```
 INFO: Running Agent Registration Process, CATTLE_URL=http://***:8080/v1
INFO: Attempting to connect to: http://***:8080/v1
INFO: http://35.224.190.120:8080/v1 is accessible
ERROR: Failed to load registration env from CATTLE_URL=http://***:8081/v1 ENV_URL=http://****:8080/v1
ERROR: Please ensure the proper value for the Host Registration URL is set
```
