### ISSUE TITLE
Migrated Database from Windows to Ubuntu and getting errors

### ISSUE THREAD

**Issue by timothystewart6** [rancher/rancher#9572]
Hi.  I l moved my database from a Windows host to an Ubuntu host and I am getting these errors when trying to start it:

I dumped the database and restored it with mysqldump and I can restore it to Windows hosts fine, just not linux.  Am I missing a package?

The command I used to start it was:
`docker run -d --restart=unless-stopped -p 9090:8080 rancher/server --db-host 192.168.3.23 --db-port 3306 --db-user cattle --db-pass ******** --db-name cattle
`

```
CATTLE_AGENT_PACKAGE_HOST_API_URL=/usr/share/cattle/artifacts/host-api.tar.gz
CATTLE_AGENT_PACKAGE_PYTHON_AGENT_URL=/usr/share/cattle/artifacts/go-agent.tar.g                                                                                                                          z
CATTLE_API_UI_URL=//releases.rancher.com/api-ui/1.0.8
CATTLE_CATTLE_VERSION=v0.183.5
CATTLE_DB_CATTLE_DATABASE=mysql
CATTLE_DB_CATTLE_MYSQL_HOST=192.168.3.23
CATTLE_DB_CATTLE_MYSQL_NAME=cattle
CATTLE_DB_CATTLE_MYSQL_PORT=3306
CATTLE_DB_CATTLE_USERNAME=cattle
CATTLE_GRAPHITE_HOST=
CATTLE_GRAPHITE_PORT=
CATTLE_HOME=/var/lib/cattle
CATTLE_HOST_API_PROXY_MODE=embedded
CATTLE_LOGBACK_OUTPUT_GELF_HOST=
CATTLE_LOGBACK_OUTPUT_GELF_PORT=
CATTLE_RANCHER_CLI_VERSION=v0.6.3
CATTLE_RANCHER_COMPOSE_VERSION=v0.12.5
CATTLE_RANCHER_SERVER_IMAGE=rancher/server
CATTLE_RANCHER_SERVER_VERSION=v1.6.6
CATTLE_USE_LOCAL_ARTIFACTS=true
DEFAULT_CATTLE_API_UI_CSS_URL=/api-ui/ui.min.css
DEFAULT_CATTLE_API_UI_INDEX=//releases.rancher.com/ui/1.6.17
DEFAULT_CATTLE_API_UI_JS_URL=/api-ui/ui.min.js
DEFAULT_CATTLE_AUTH_SERVICE_EXECUTE=true
DEFAULT_CATTLE_CATALOG_EXECUTE=true
DEFAULT_CATTLE_CATALOG_URL={"catalogs":{"community":{"url":"https://git.rancher.                                                                                                                          io/community-catalog.git","branch":"master"},"library":{"url":"https://git.ranch                                                                                                                          er.io/rancher-catalog.git","branch":"${RELEASE}"}}}
DEFAULT_CATTLE_COMPOSE_EXECUTOR_EXECUTE=true
DEFAULT_CATTLE_MACHINE_EXECUTE=true
DEFAULT_CATTLE_RANCHER_CLI_DARWIN_URL=https://releases.rancher.com/cli/v0.6.3/ra                                                                                                                          ncher-darwin-amd64-v0.6.3.tar.gz
DEFAULT_CATTLE_RANCHER_CLI_LINUX_URL=https://releases.rancher.com/cli/v0.6.3/ran                                                                                                                          cher-linux-amd64-v0.6.3.tar.gz
DEFAULT_CATTLE_RANCHER_CLI_WINDOWS_URL=https://releases.rancher.com/cli/v0.6.3/r                                                                                                                          ancher-windows-386-v0.6.3.zip
DEFAULT_CATTLE_RANCHER_COMPOSE_DARWIN_URL=https://releases.rancher.com/compose/v                                                                                                                          0.12.5/rancher-compose-darwin-amd64-v0.12.5.tar.gz
DEFAULT_CATTLE_RANCHER_COMPOSE_LINUX_URL=https://releases.rancher.com/compose/v0                                                                                                                          .12.5/rancher-compose-linux-amd64-v0.12.5.tar.gz
DEFAULT_CATTLE_RANCHER_COMPOSE_WINDOWS_URL=https://releases.rancher.com/compose/                                                                                                                          v0.12.5/rancher-compose-windows-386-v0.12.5.zip
DEFAULT_CATTLE_SECRETS_API_EXECUTE=true
DEFAULT_CATTLE_WEBHOOK_SERVICE_EXECUTE=true
03:30:33.743 [main] INFO  ConsoleStatus - Loading configuration
2017-08-04 03:30:37,386 INFO    [main] [ConsoleStatus] Starting DB migration
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,725 WARN    [main] [liquibase] modifyDataType will lose prim                                                                                                                          ary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all                                                                                                                           configuration if this is the case
2017-08-04 03:30:39,757 ERROR   [main] [liquibase] classpath:db/changelog.xml: d                                                                                                                          b/core-001.xml::dump1::darren (generated): Change Set db/core-001.xml::dump1::da                                                                                                                          rren (generated) failed.  Error: Error executing SQL CREATE TABLE cattle.account                                                                                                                           (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NULL, kind VARCHAR(255) N                                                                                                                          OT NULL, uuid VARCHAR(128) NOT NULL, description VARCHAR(1024) NULL, state VARCH                                                                                                                          AR(128) NOT NULL, created datetime NULL, removed datetime NULL, remove_time date                                                                                                                          time NULL, data TEXT NULL, CONSTRAINT PK_ACCOUNT PRIMARY KEY (id)): (conn:7) Tab                                                                                                                          le 'account' already exists
Query is : CREATE TABLE cattle.account (id BIGINT AUTO_INCREMENT NOT NULL, name                                                                                                                           VARCHAR(255) NULL, kind VARCHAR(255) NOT NULL, uuid VARCHAR(128) NOT NULL, descr                                                                                                                          iption VARCHAR(1024) NULL, state VARCHAR(128) NOT NULL, created datetime NULL, r                                                                                                                          emoved datetime NULL, remove_time datetime NULL, data TEXT NULL, CONSTRAINT PK_A                                                                                                                          CCOUNT PRIMARY KEY (id)) liquibase.exception.DatabaseException: Error executing                                                                                                                           SQL CREATE TABLE cattle.account (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR                                                                                                                          (255) NULL, kind VARCHAR(255) NOT NULL, uuid VARCHAR(128) NOT NULL, description                                                                                                                           VARCHAR(1024) NULL, state VARCHAR(128) NOT NULL, created datetime NULL, removed                                                                                                                           datetime NULL, remove_time datetime NULL, data TEXT NULL, CONSTRAINT PK_ACCOUNT                                                                                                                           PRIMARY KEY (id)): (conn:7) Table 'account' already exists
Query is : CREATE TABLE cattle.account (id BIGINT AUTO_INCREMENT NOT NULL, name                                                                                                                           VARCHAR(255) NULL, kind VARCHAR(255) NOT NULL, uuid VARCHAR(128) NOT NULL, descr                                                                                                                          iption VARCHAR(1024) NULL, state VARCHAR(128) NOT NULL, created datetime NULL, r                                                                                                                          emoved datetime NULL, remove_time datetime NULL, data TEXT NULL, CONSTRAINT PK_A                                                                                                                          CCOUNT PRIMARY KEY (id))
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:61) ~[l                                                                                                                          iquibase-core-3.1.0.jar:na]
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:106) ~[                                                                                                                          liquibase-core-3.1.0.jar:na]
        at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.                                                                                                                          java:1189) ~[liquibase-core-3.1.0.jar:na]
        at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdb                                                                                                                          cDatabase.java:1172) ~[liquibase-core-3.1.0.jar:na]
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:352) ~[liquibase                                                                                                                          -core-3.1.0.jar:na]
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:40                                                                                                                          ) [liquibase-core-3.1.0.jar:na]
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:64)                                                                                                                           [liquibase-core-3.1.0.jar:na]
        at liquibase.Liquibase.update(Liquibase.java:202) [liquibase-core-3.1.0.                                                                                                                          jar:na]
        at liquibase.Liquibase.update(Liquibase.java:181) [liquibase-core-3.1.0.                                                                                                                          jar:na]
        at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiqu                                                                                                                          ibase.java:342) [liquibase-core-3.1.0.jar:na]
        at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(Sprin                                                                                                                          gLiquibase.java:299) [liquibase-core-3.1.0.jar:na]
        at io.cattle.platform.liquibase.Loader.afterPropertiesSet(Loader.java:66                                                                                                                          ) [cattle-framework-db-loader-0.5.0-SNAPSHOT.jar:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean                                                                                                                          Factory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637) [spring-                                                                                                                          beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean                                                                                                                          Factory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574) [spring-bea                                                                                                                          ns-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean                                                                                                                          Factory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) [spring-beans-                                                                                                                          4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean                                                                                                                          Factory.createBean(AbstractAutowireCapableBeanFactory.java:482) [spring-beans-4.                                                                                                                          3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getOb                                                                                                                          ject(AbstractBeanFactory.java:306) [spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE                                                                                                                          ]

```

**Comment by superseb** [comment]
What error do you get when you try to restore it on Linux?

It looks like the table `DATABASECHANGELOG` was not copied because it tries to execute the database migration scripts. Can you verify the content of the database on Windows and Linux in this table?

`SELECT * FROM DATABASECHANGELOG;`

**Comment by junkiebev** [comment]
I'm having this problem too.
I think that the problem might be that on windows the databasechangelog and databasechangeloglock table's (all of them actually) are lowercase in windows but in the migration to linux it seems to be uppercase.

Are they all supposed to be uppercase or just the databasechangelog* tables?

**Comment by vincent99** [comment]
`DATABASECHANGELOG` and `DATABASECHANGELOGLOCK` are the only two with uppercase letters in them (because they're really liquibase's, not ours).  It seems sort of awful that Windows MySQL is case-insensitive and case-forgetting...

**Comment by junkiebev** [comment]
you can put a setting in my.cnf for mysql and mariadb
 
    lower_case_table_names=1

and that makes it works but god knows if it breaks anything else

**Comment by superseb** [comment]
Please comment if you still need help on this.

**Comment by timothystewart6** [comment]
Found this post almost a year after a posted it.  I took the plunge once again and tried to move to linux.  To anyone finding this you need to:

* Add `lower_case_table_names=1` to your `my.cnf`
* Copy data or rename your `databasechangelog` table to `DATABASECHANGELOG`

Thanks @junkiebev and @vincent99
