### ISSUE TITLE
rancher-metadata No workers available, dropping event.

### ISSUE THREAD

**Issue by svensp** [rancher/rancher#9724]
**Rancher versions:**
rancher/server: 1.6.5
rancher/agent: v1.2.5

**Infrastructure Stack versions:**
healthcheck: v0.3.0
ipsec: 0.1.3
network-services: v0.2.5
scheduler: v0.6.5

**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:17:22 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:16:12 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
Containers: 82
 Running: 61
 Paused: 0
 Stopped: 21
Images: 51
Server Version: 17.06.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: convoy local pxd
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.11.0-0.bpo.1-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 62.89GiB
Name: matthaes-web02
ID: BZEJ:IDP6:ASRV:EZU2:42VT:QZHO:GXMC:IWXE:VQRW:ATKU:2VO2:AUCM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```
Note: only one of the hosts this occurs on

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

4.11.0-0.bpo.1-amd64
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Hetzner Bare-metal Host

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
3 Host HA-Setup

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Start/Stop large amounts of Containers. Usually after a Host went down and is being re-setup by Rancher

**Results:**
The metadata-service deadlocks with the message `No workers available, dropping event.  workerCount: 3, event: ...`
Services are not started anymore with the message `Timeout getting Ip-Address`

The only way to break this deadlock is to restart the metadata container.

I'm not very good with go but I checked the code for rancher-metadata and it seems to me that the rancher-metadata Service is simply flooded. It creates a fixed worker pool of 3 workers and when large amounts of requests come in from starting lots of containers this is not enough to service every request coming in.
Creating a service takes a number of successful requests so some go through, then one is dropped -> process restarts because it seems to have failed. No service ever finishes and the strain doesn't lessen over time.

This is simply a guess on how this happens but I'd think a worker count of 3 is simply not enough to service the amount of requests coming in when 3 rancher-servers do work. I'd like to test with a higher amount of workers but the number is hardcoded, not read/overwritten by an environment variable

**Comment by cjellick** [comment]
Can you ellaborate on the size of your rancher deployment? Number of hosts, number of containers, number of environments, etc

**Comment by svensp** [comment]
A total of 6 hosts
3 powerful bare-metal hosts, Intel Xeon E5-1650 with 64Gb RAM
3 smaller virtual hosts Hetzner cx30
- all started with the correct CATTLE_AGENT_IP
a single environment
the container api endpoint lists 410 containers
`docker ps | wc -l` on all hosts list a total of 310 lines displayed, so roughly 300 containers running

The rancher-server ha-setup runs on the bare-metal hosts.
The rancher mysql database and haproxy loadbalancer is located on one of the smaller virtual hosts

The problem most often appears after one or sometimes 2 of the baremetal servers restart due to a process-hang kernel panic following the `waiting for lo to become free` docker problem

I don't think it is the total size of the deployment tho. We had rancher running as single node on the same host as the database and lb for quite a while and never ran into this problem.
It only appeared after moving to the 3-Host HA-Setup.

**Comment by mattdodge** [comment]
Seeing something similar on my setup, the error happens frequently on a 2-node HA setup but not a single node. I see the worker error in the `rancher/metadata` container. Relevant snippet of logs (took out my rancher URL)
```
time="2017-10-03T01:17:43Z" level=info msg="Update requested for version: 141619"
time="2017-10-03T01:17:44Z" level=info msg="Update requested for version: 141622"
time="2017-10-03T01:17:51Z" level=info msg="Update requested for version: 141619"
time="2017-10-03T01:17:52Z" level=warning msg="No workers available, dropping event. workerCount: 3, event: {config.update 8ba7c5c9-77ee-4622-9f68-e841fcf3d491    reply.1236800241846954678 1a23164 agent     map[configUrl:https://myrancher.com/v1 items:[map[name:metadata-answers requestedVersion:141622 setVersion:141622 apply:true increment:true checkInSyncOnly:false]]] 1.50699346418e+12}"
time="2017-10-03T01:17:53Z" level=warning msg="No workers available, dropping event. workerCount: 3, event: {ping c4ad3f39-1289-4823-a35c-b66885a79829           map[options:map[] resources:[]] 1.506993473475e+12}"
time="2017-10-03T01:17:58Z" level=warning msg="No workers available, dropping event. workerCount: 3, event: {ping 51c805d1-0f37-4e55-8c68-dce127b76a92           map[options:map[] resources:[]] 1.506993478478e+12}"
time="2017-10-03T01:17:59Z" level=warning msg="No workers available, dropping event. workerCount: 3, event: {config.update 649a2335-3e1a-4add-b766-4a1bd55497d5    reply.7358476156002256397 1a23164 agent     map[configUrl:https://myrancher.com/v1 items:[map[name:metadata-answers requestedVersion:141619 setVersion:141619 apply:true increment:true checkInSyncOnly:false]]] 1.506993463828e+12}"
time="2017-10-03T01:18:00Z" level=warning msg="No workers available, dropping event. workerCount: 3, event: {config.update 8ba7c5c9-77ee-4622-9f68-e841fcf3d491    reply.1236800241846954678 1a23164 agent     map[items:[map[setVersion:141622 apply:true increment:true checkInSyncOnly:false name:metadata-answers requestedVersion:141622]] configUrl:https://myrancher.com/v1] 1.50699346418e+12}"
time="2017-10-03T01:18:00Z" level=info msg="Downloaded in 16.941871476s"
time="2017-10-03T01:18:00Z" level=info msg="Generating and reloading answers"
time="2017-10-03T01:18:00Z" level=info msg="Generating answers"
time="2017-10-03T01:18:00Z" level=info msg="Generated and reloadedanswers"
time="2017-10-03T01:18:00Z" level=info msg="Applied https://myrancher.com/v1/configcontent/metadata-answers?client=v2&requestedVersion=141619?version=141619-4f3c5c96fb170da7fa8781d4ac55192c"
time="2017-10-03T01:18:00Z" level=info msg="Download and reload in: 17.117396725s"
time="2017-10-03T01:18:00Z" level=info msg="Downloaded in 18.561305ms"
time="2017-10-03T01:18:00Z" level=info msg="Generating and reloading answers"
time="2017-10-03T01:18:00Z" level=info msg="Update requested for version: 141627"
time="2017-10-03T01:18:01Z" level=info msg="Generating answers"
time="2017-10-03T01:18:01Z" level=info msg="Generated and reloadedanswers"
time="2017-10-03T01:18:01Z" level=info msg="Applied https://myrancher.com/v1/configcontent/metadata-answers?client=v2&requestedVersion=141619?version=141619-4f3c5c96fb170da7fa8781d4ac55192c"
time="2017-10-03T01:18:01Z" level=info msg="Download and reload in: 308.43758ms"
time="2017-10-03T01:18:01Z" level=info msg="Update requested for version: 141627"
time="2017-10-03T01:18:09Z" level=info msg="Update requested for version: 141627"
time="2017-10-03T01:18:17Z" level=info msg="Update requested for version: 141627"
time="2017-10-03T01:18:18Z" level=info msg="Downloaded in 17.144539898s"
time="2017-10-03T01:18:18Z" level=info msg="Generating and reloading answers"
time="2017-10-03T01:18:18Z" level=warning msg="No workers available, dropping event. workerCount: 3, event: {ping a2fd548a-86a7-49c1-87e4-185a92fda147           map[options:map[] resources:[]] 1.506993498485e+12}"
time="2017-10-03T01:18:18Z" level=info msg="Generating answers"
time="2017-10-03T01:18:18Z" level=info msg="Generated and reloadedanswers"
time="2017-10-03T01:18:18Z" level=info msg="Applied https://myrancher.com/v1/configcontent/metadata-answers?client=v2&requestedVersion=141627?version=141629-4f3c5c96fb170da7fa8781d4ac55192c"
time="2017-10-03T01:18:18Z" level=info msg="Download and reload in: 17.309815333s"
time="2017-10-03T01:18:18Z" level=info msg="Downloaded in 19.317296ms"
time="2017-10-03T01:18:18Z" level=info msg="Generating and reloading answers"
time="2017-10-03T01:18:18Z" level=info msg="Generating answers"
time="2017-10-03T01:18:18Z" level=info msg="Generated and reloadedanswers"
time="2017-10-03T01:18:18Z" level=info msg="Applied https://myrancher.com/v1/configcontent/metadata-answers?client=v2&requestedVersion=141627?version=141629-4f3c5c96fb170da7fa8781d4ac55192c"
time="2017-10-03T01:18:18Z" level=info msg="Download and reload in: 308.859319ms"
time="2017-10-03T01:18:20Z" level=info msg="Update requested for version: 141630"
```

**Comment by mattdodge** [comment]
Priority negative 1...I assume that means this isn't getting fixed...

**Comment by vincent99** [comment]
(I will grant you it's dumb, but) -1 is our "highest" priority.

**Comment by svensp** [comment]
We have changed our infrastructure quite a bit and this problem almost never happens anymore.
I can't be sure which change 'fixed' this problem but I attribute it to moving to a more powerful database server and scaling the rancher nodes from 3 to 2
Hardware change:
1x2gb ram hetzner cx20 vserver running only the database server
to
2x 64gb ram i7 hetzner bare metal running database server, rancher node and traefik loadbalancer.
Database running on one of the nodes sharing data via drbd
Access to the database via haproxy running on each node on 3307
The database is now running on mariadb, before it was running on mysql.

Another lead that could be followed is the symptoms also appeared when the old mysql server once had a deadlock that was only solved by restarting the mysql service. Thus I think it could be related to racing conditions when locking databases between the different rancher nodes in the cluster

**Comment by mattdodge** [comment]
Haha, good to hear, thanks @vincent99. 

That's also helpful to know @svensp. I had assumed high availability in general was causing this (seems to be the common denominator) but I plan on running a few more tests later today. Maybe a beefier database is the way to go.

**Comment by marcbachmann** [comment]
I'm also seeing this issue with rancher v1.6.11 and agent v1.2.7.
It first appeared when I added a fourth host (8GB memory, 8 Cores, same as the rancher server).

In my case the healthcheck service got deployed before the metadata service and didn't get the token for the rancher server (that's probably another issue). That's how I saw that the metadata service didn't work.

Additionally to that the metadata service failed to start properly and logged the "No workers available" error message. It never recovered from that.

At the same time all other hosts also started logging this error.
Restarting the metadata service and then the healthcheck service on every host gets it working again.

**Comment by marcbachmann** [comment]
I'm not sure it is related, but at about the same time I'm getting those errors on the rancher server:
```
2017-11-24 20:53:16,782 ERROR [e56eeb89-43c0-4dea-b4a8-cce51d8b03d9:269666] [instance:8408->instanceHostMap:8314] [instance.start->(InstanceStart)->instancehostmap.activate] [] [ecutorService-8] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.activate.reply;agent=3136]: Timeout getting IP address
2017-11-24 20:53:16,782 ERROR [e56eeb89-43c0-4dea-b4a8-cce51d8b03d9:269666] [instance:8408] [instance.start->(InstanceStart)] [] [ecutorService-8] [i.c.p.process.instance.InstanceStart] Failed [5/5] to Starting for instance [8408]
2017-11-24 20:53:17,010 ERROR [e56eeb89-43c0-4dea-b4a8-cce51d8b03d9:269666] [instance:8408] [instance.start] [] [ecutorService-8] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.activate.reply;agent=3136]: Timeout getting IP address
2017-11-24 20:53:17,403 ERROR [:] [] [] [] [ecutorService-8] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [compute.instance.activate.reply;agent=3136]: Timeout getting IP address
2017-11-24 20:53:23,276 ERROR [2ab38e5e-eaad-4ba4-bb11-9b3beec5b233:269642] [service:40] [service.update] [] [ecutorService-3] [c.p.e.p.i.DefaultProcessInstanceImpl] Expected state running but got error: Timeout getting IP address
2017-11-24 20:53:23,349 ERROR [:] [] [] [] [ecutorService-3] [.e.s.i.ProcessInstanceDispatcherImpl] Expected state running but got error: Timeout getting IP address
2017-11-24 20:53:24,653 ERROR [c635248f-bc34-41ea-ad72-0571095b75cc:269691] [instance:8411->instanceHostMap:8324] [instance.start->(InstanceStart)->instancehostmap.activate] [] [utorService-285] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.activate.reply;agent=3136]: Timeout getting IP address
2017-11-24 20:53:24,653 ERROR [c635248f-bc34-41ea-ad72-0571095b75cc:269691] [instance:8411] [instance.start->(InstanceStart)] [] [utorService-285] [i.c.p.process.instance.InstanceStart] Failed [5/5] to Starting for instance [8411]
2017-11-24 20:53:24,918 ERROR [c635248f-bc34-41ea-ad72-0571095b75cc:269691] [instance:8411] [instance.start] [] [utorService-285] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.activate.reply;agent=3136]: Timeout getting IP address
2017-11-24 20:53:25,091 ERROR [:] [] [] [] [utorService-285] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [compute.instance.activate.reply;agent=3136]: Timeout getting IP address
2017-11-24 20:53:29,018 ERROR [7cdfbe6e-7a7f-497f-84bc-c11cf40e1275:269667] [instance:8407] [instance.start->(InstanceStart)] [] [cutorService-14] [i.c.p.process.instance.InstanceStart] Failed [Dependencies readiness error instance is not running] for instance [8407]
2017-11-24 20:53:30,074 ERROR [1b221782-5a5b-46a3-b68e-42082268b1ab:269655] [instance:8404->instanceHostMap:8320] [instance.start->(InstanceStart)->instancehostmap.activate] [] [ecutorService-8] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.activate.reply;agent=3136]: Timeout getting IP address
2017-11-24 20:53:30,075 ERROR [1b221782-5a5b-46a3-b68e-42082268b1ab:269655] [instance:8404] [instance.start->(InstanceStart)] [] [ecutorService-8] [i.c.p.process.instance.InstanceStart] Failed [5/5] to Starting for instance [8404]
2017-11-24 20:53:30,299 ERROR [1b221782-5a5b-46a3-b68e-42082268b1ab:269655] [instance:8404] [instance.start] [] [ecutorService-8] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.activate.reply;agent=3136]: Timeout getting IP address
2017-11-24 20:53:30,750 ERROR [:] [] [] [] [ecutorService-8] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [compute.instance.activate.reply;agent=3136]: Timeout getting IP address
2017-11-24 20:53:31,041 ERROR [351af0b9-9b94-436c-bd1b-3739127f2a5c:269637] [service:33] [service.update] [] [ecutorService-7] [c.p.e.p.i.DefaultProcessInstanceImpl] Expected state running but got error: Timeout getting IP address
2017-11-24 20:53:31,122 ERROR [:] [] [] [] [ecutorService-7] [.e.s.i.ProcessInstanceDispatcherImpl] Expected state running but got error: Timeout getting IP address
2017-11-24 20:53:38,164 ERROR [b95a0a46-f58f-40fa-8c2e-5cb58af5ce77:269639] [service:3] [service.update] [] [cutorService-13] [c.p.e.p.i.DefaultProcessInstanceImpl] Expected state running but got error: Timeout getting IP address
2017-11-24 20:53:38,233 ERROR [:] [] [] [] [cutorService-13] [.e.s.i.ProcessInstanceDispatcherImpl] Expected state running but got error: Timeout getting IP address
2017-11-24 20:54:00,597 ERROR [30b29064-0c7c-4121-bc13-daa75781e768:269943] [service:23] [service.update] [] [utorService-309] [c.p.e.p.i.DefaultProcessInstanceImpl] Expected state running but got removed
2017-11-24 20:54:00,682 ERROR [:] [] [] [] [utorService-309] [.e.s.i.ProcessInstanceDispatcherImpl] Expected state running but got removed
2017-11-24 20:54:05,799 ERROR [55b6079f-4662-4e9b-84ae-55b7278292e0:269932] [service:28] [service.update] [] [utorService-308] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception org.jooq.exception.DataChangedException: Database record has been changed
	at org.jooq.impl.UpdatableRecordImpl.checkIfChanged(UpdatableRecordImpl.java:550)
	at org.jooq.impl.UpdatableRecordImpl.storeUpdate0(UpdatableRecordImpl.java:291)
	at org.jooq.impl.UpdatableRecordImpl.access$200(UpdatableRecordImpl.java:90)
	at org.jooq.impl.UpdatableRecordImpl$3.operate(UpdatableRecordImpl.java:260)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:123)
	at org.jooq.impl.UpdatableRecordImpl.storeUpdate(UpdatableRecordImpl.java:255)
	at org.jooq.impl.UpdatableRecordImpl.update(UpdatableRecordImpl.java:149)
	at io.cattle.platform.object.impl.JooqObjectManager.persistRecord(JooqObjectManager.java:228)
	at io.cattle.platform.object.impl.JooqObjectManager.setFieldsInternal(JooqObjectManager.java:133)
	at io.cattle.platform.object.impl.JooqObjectManager$3.execute(JooqObjectManager.java:121)
	at io.cattle.platform.engine.idempotent.Idempotent.change(Idempotent.java:88)
	at io.cattle.platform.object.impl.JooqObjectManager.setFields(JooqObjectManager.java:118)
	at io.cattle.platform.object.impl.JooqObjectManager.setFields(JooqObjectManager.java:113)
	at io.cattle.platform.object.impl.AbstractObjectManager.setFields(AbstractObjectManager.java:139)
	at io.cattle.platform.servicediscovery.process.LoadBalancerServiceUpdatePostListener.updateInstanceWithNewPorts(LoadBalancerServiceUpdatePostListener.java:137)
	at io.cattle.platform.servicediscovery.process.LoadBalancerServiceUpdatePostListener.updateServicePorts(LoadBalancerServiceUpdatePostListener.java:124)
	at io.cattle.platform.servicediscovery.process.LoadBalancerServiceUpdatePostListener.handle(LoadBalancerServiceUpdatePostListener.java:66)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:470)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:421)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:415)
	at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:415)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:520)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:345)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:245)
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7)
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:242)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:184)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:157)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:116)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:113)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:113)
	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl.processExecuteWithLock(ProcessInstanceDispatcherImpl.java:136)
	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl$1.doWithLock(ProcessInstanceDispatcherImpl.java:123)
	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl$1.doWithLock(ProcessInstanceDispatcherImpl.java:120)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$4.doWithLock(AbstractLockManagerImpl.java:50)
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:25)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:47)
	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl.execute(ProcessInstanceDispatcherImpl.java:120)
	at io.cattle.platform.engine.server.ProcessInstanceReference.doRun(ProcessInstanceReference.java:59)
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

```
time="2017-11-24T20:52:41Z" level=info msg="Generating and reloading answers"
time="2017-11-24T20:52:41Z" level=info msg="Generating answers"
time="2017-11-24T20:52:41Z" level=info msg="Generated and reloaded answers"
time="2017-11-24T20:52:41Z" level=info msg="Applied https://my-rancher-server-domain/v1/configcontent/metadata-answers?client=v2&requestedVersion=112528?version=112531-4f3c5c96fb170da7fa8781d4ac55192c"
time="2017-11-24T20:52:42Z" level=info msg="Download and reload in: 1.679490342s"
time="2017-11-24T20:52:42Z" level=info msg="Update requested for version: 112532"
time="2017-11-24T20:52:50Z" level=info msg="Update requested for version: 112532"
time="2017-11-24T20:52:58Z" level=info msg="Update requested for version: 112532"
time="2017-11-24T20:53:01Z" level=warning msg="No workers available, dropping event. workerCount: 3, event: {ping aee5c66c-2300-45ee-b0c1-6064b8cf2300           map[options:map[] resources:[]] 1.511556781925e+12}"
time="2017-11-24T20:53:06Z" level=warning msg="No workers available, dropping event. workerCount: 3, event: {ping e94061b5-8128-4491-a5f7-8911bb7d965d           map[options:map[] resources:[]] 1.511556786933e+12}"
time="2017-11-24T20:53:07Z" level=warning msg="No workers available, dropping event. workerCount: 3, event: {config.update 078dd498-6294-4595-9abf-0657181e569c    reply.8420363080793510647 1a3121 agent     map[configUrl:https://my-rancher-server-domain/v1 items:[map[apply:true increment:true checkInSyncOnly:false name:metadata-answers requestedVersion:112554 setVersion:112554]]] 1.511556787267e+12}"
time="2017-11-24T20:53:11Z" level=warning msg="No workers available, dropping event. workerCount: 3, event: {ping c058dbef-4848-45d8-a077-21c0adee40cc           map[options:map[] resources:[]] 1.511556791933e+12}"
time="2017-11-24T20:53:14Z" level=warning msg="No workers available, dropping event. workerCount: 3, event: {config.update 078dd498-6294-4595-9abf-0657181e569c    reply.8420363080793510647 1a3121 agent     map[configUrl:https://my-rancher-server-domain/v1 items:[map[checkInSyncOnly:false name:metadata-answers requestedVersion:112554 setVersion:112554 apply:true increment:true]]] 1.511556787267e+12}"
time="2017-11-24T20:53:16Z" level=warning msg="No workers available, dropping event. workerCount: 3, event: {ping 8f15ccb0-b29d-4494-b452-71e150393496           map[options:map[] resources:[]] 1.511556796934e+12}"
time="2017-11-24T20:53:21Z" level=warning msg="No workers available, dropping event. workerCount: 3, event: {ping d307d360-ecec-4839-a209-2d6955681668           map[options:map[] resources:[]] 1.511556801946e+12}"
time="2017-11-24T20:53:23Z" level=warning msg="No workers available, dropping event. workerCount: 3, event: {config.update 078dd498-6294-4595-9abf-0657181e569c    reply.8420363080793510647 1a3121 agent     map[configUrl:https://my-rancher-server-domain/v1 items:[map[setVersion:112554 apply:true increment:true checkInSyncOnly:false name:metadata-answers requestedVersion:112554]]] 1.511556787267e+12}"
time="2017-11-24T20:53:26Z" level=warning msg="No workers available, dropping event. workerCount: 3, event: {ping f681a65c-0759-47c1-9724-514acf43c988           map[options:map[] resources:[]] 1.511556806947e+12}"
time="2017-11-24T20:53:31Z" level=warning msg="No workers available, dropping event. workerCount: 3, event: {ping edf15a85-501c-49ce-a773-b17713ea10fa           map[options:map[] resources:[]] 1.511556811948e+12}"
time="2017-11-24T20:53:32Z" level=warning msg="No workers available, dropping event. workerCount: 3, event: {config.update ac221846-33b6-4031-a2b3-5dbc65db3203    reply.4564437533782780499 1a3121 agent     map[configUrl:https://my-rancher-server-domain/v1 items:[map[name:metadata-answers requestedVersion:112600 setVersion:112600 apply:true increment:true checkInSyncOnly:false]]] 1.511556812671e+12}"
time="2017-11-24T20:53:36Z" level=warning msg="No workers available, dropping event. workerCount: 3, event: {ping 4361994a-d361-4cfb-8c0a-f4c65d03b2a9           map[options:map[] resources:[]] 1.511556816949e+12}"
time="2017-11-24T20:53:40Z" level=warning msg="No workers available, dropping event. workerCount: 3, event: {config.update ac221846-33b6-4031-a2b3-5dbc65db3203    reply.4564437533782780499 1a3121 agent     map[items:[map[checkInSyncOnly:false name:metadata-answers requestedVersion:112600 setVersion:112600 apply:true increment:true]] configUrl:https://my-rancher-server-domain/v1] 1.511556812671e+12}"
```

**Comment by warroyo** [comment]
I have started seeing this on `1.6.14` and network services `0.2.8` my environment has about 24 hosts. 

the issue I am seeing is that when this happens the metadata service then returns "Not Found" when querying it. 

is there a way to increase workers for the metadata service?

**Comment by dindurthy** [comment]
We're seeing this too on `1.6.15`, network services `0.7.20`.  It's not consistent on every host add, and restarting the metadata service does appear to resolve it.

**Comment by sm6yvr** [comment]
Have anyone found a way to solve this issue? I have exactly the same issue in one of my three rancher environments (using the same rancher 1.6.21 server with two nodes in ha). I plan to upgrade to 2.x but not yet so I need to find a way to resolv this.

**Comment by chrisgacsal** [comment]
We faced with a very similar issue and we solved it by increasing the `CpuPeriod` and `CpuQuota` for the `metadata` service in `network-services` stack.
