### ISSUE TITLE
Store binary files in Rancher Secrets

### ISSUE THREAD

**Issue by slavniyteo** [rancher/rancher#9740]
rancher/server: v1.6.3

I need to store java truststore file in the secret.
I tried to add new secret with binaries but rancher ui throws exception
```
Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at n.userValueChanged (https://monetafarm-demo-man1/assets/ui-94f79ed01de738b93aeb6048df5dbc6d.js:64:27184)
    at Object.p [as applyStr] (https://monetafarm-demo-man1/assets/vendor-67bbfad62aeceea28fc65fb877a62f60.js:12:7641)
    at Object.h [as sendEvent] (https://monetafarm-demo-man1/assets/vendor-67bbfad62aeceea28fc65fb877a62f60.js:10:31229)
    at b (https://monetafarm-demo-man1/assets/vendor-67bbfad62aeceea28fc65fb877a62f60.js:12:78)
    at Object.u [as propertyDidChange] (https://monetafarm-demo-man1/assets/vendor-67bbfad62aeceea28fc65fb877a62f60.js:11:30968)
    at Object.l [as set] (https://monetafarm-demo-man1/assets/vendor-67bbfad62aeceea28fc65fb877a62f60.js:12:1594)
    at n.setValue (https://monetafarm-demo-man1/assets/vendor-67bbfad62aeceea28fc65fb877a62f60.js:9:23722)
    at Object.k [as setValue] (https://monetafarm-demo-man1/assets/vendor-67bbfad62aeceea28fc65fb877a62f60.js:10:404)
    at i.setValue (https://monetafarm-demo-man1/assets/vendor-67bbfad62aeceea28fc65fb877a62f60.js:9:22044)
    at n.setValue (https://monetafarm-demo-man1/assets/vendor-67bbfad62aeceea28fc65fb877a62f60.js:9:24687)
```

Rancher Secrets may be very useful feature to propogate files to containers (like ssl certs or keystores) without manually created volumes with putting files into every host.

**Comment by vincent99** [comment]
@westlywright Can you backport https://github.com/rancher/rancher/issues/7670 to 1.6-dev please

**Comment by tfiduccia** [comment]
Version - 1.6.8-rc6
Verified fixed
