### ISSUE TITLE
Rancher EBS volumes eventually cause hosts to get into an inoperable state

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#9760]
**Rancher versions:**
rancher/server: not sure yet, but presumably recent
rancher/agent:

**Infrastructure Stack versions:**

**Docker version: (`docker version`,`docker info` preferred)**
17.03

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
centos 7 and devicemapper in loopback

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
Not consistently reproducible and happens randomly but the user has observed that docker will become unresponsive when trying to mount/unmount EBS containers. They  have several different stacks using either stack or per_container scoped volumes including the redis and elastic search cluster catalog items from the community catalog.

**Results:**
Everything seems to be operating normally and then a service using ebs is either deployed to or deleted from a host and rancner-ebs goes sideways and the host eventually locks up and requires a full reboot.

**Comment by cjellick** [comment]
Note that the ES Cluster template is using the experimental per_container volume feature. I wander if this could contribute to the flakiness

**Comment by oskapt** [comment]
I worked on this issue with the user. 

## Details

- They used the Elasticsearch Cluster catalog item but changed backing storage to `rancher-ebs` in the `volumes` section of the config, keeping the `per_container` portion of the config intact
- When they scale, new volumes are correctly created for stacks in other AZs, and generally everything works fine
- After some period of time, hosts can no longer attach/detach volumes. volumes that I saw were `Detached` in Rancher and `Attaching` in AWS for 22 hours. The result was that services in Rancher were left in `Starting` state forever.
- Even after forcibly detaching volumes in AWS, I was unable to restart services or delete containers that were in 'Starting' state.
- For one stack Rancher appeared to kick off 30+ copies of each container, all of which hung in `Starting` state. Neither these containers nor the original one existed in Docker, so there was nothing to delete manually.
- Rancher EBS driver container didn't report much of interest - some errors about volumes being mounted on the host/container that didn't exist in Docker
- No infra stack reported any errors that looked to be related. Load on the machine was negligible. It had 8 cores doing nothing and 16GB of RAM free.
- According to the user, the only solution is to restart Docker, which takes forever (5-10 minutes is what we saw), as it cannot interact with the volumes and has an exponential backoff until timeout on each volume umount/detach operation
- When Docker won't restart, the solution is to restart the host. Sometimes Docker doesn't restart, possibly because systemd had it in `stopping` state when the system restarted, and that request completes after the host restarts (speculation). 
- After restarting Docker manually after reboot, the user encounters the race condition associated with containers that use EBS starting before the EBS driver container is available, resulting in a total freeze of Docker and the aforementioned exponential timeout. Eventually, sometimes, Docker comes back up.
- Correlated issues with this are hosts disconnecting from Rancher (due to Docker being hung) and other workloads on the host also freezing (due to Docker being hung). 
- The problem is transient. It appears randomly throughout 43 hosts in 7 environments. They are unable to reproduce it at will, but once it appears on a host, that host is permanently unable to use Rancher EBS until Docker restart or host reboot. 
- Sometimes a host will develop the condition without yet starting/stopping containers that use EBS, so the user doesn't know that the host is broken until they attempt to interact with it

## Next Steps

- We asked the user to capture logs from the storage process on the host the next time that they see the issue by issuing `kill -3 <pid>` on the process and sending us the stack trace
- We also asked the user to switch from `per_container` to named EBS volumes to see if this and correlated problems abate.
- We also asked that the user check the Processes tab within Rancher to identify the state of processes related to EBS during the event.
- We will meet again in 10-14 days.

**Comment by cjellick** [comment]
random notes for myself while debugging:

1. what is this error: 
```
time="2017-08-31T16:38:08Z" level=error msg="Mounted but not registered in Docker: /var/lib/rancher/volumes/rancher-ebs/vol-test-stack_vol_1_a4452c97-5c31-458d-aab4-4a642bbb02d9_3b371-staging" 
```

2. I was able to cause a volume to get stuck during attach, which led to a locked up host. The problem is that the call to Mount is a fully blocking call in docker. if Mount is blocked, then no other calls can get through
```
goroutine 8432 [syscall]:
syscall.Syscall6(0xf7, 0x1, 0x51ed, 0xc420013a80, 0x1000004, 0x0, 0x0, 0x91e600, 0xc4202594e0, 0x43375b)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
os.(*Process).blockUntilWaitable(0xc4204b0060, 0x9f0200, 0xc4204238c0, 0xc420483600)
	/usr/local/go/src/os/wait_waitid.go:28 +0xbc
os.(*Process).wait(0xc4204b0060, 0x0, 0xc420483540, 0xc4200261f8)
	/usr/local/go/src/os/exec_unix.go:22 +0xab
os.(*Process).Wait(0xc4204b0060, 0xc4202595e8, 0x0, 0x0)
	/usr/local/go/src/os/doc.go:49 +0x2b
os/exec.(*Cmd).Wait(0xc4204238c0, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:434 +0x6d
os/exec.(*Cmd).Run(0xc4204238c0, 0xb, 0xc4204833a0)
	/usr/local/go/src/os/exec/exec.go:279 +0x48
github.com/rancher/storage/docker/volumeplugin.(*RancherStorageDriver).exec(0xc420012e80, 0x9b8a19, 0x6, 0xc4202597b0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/storage/docker/volumeplugin/exec.go:33 +0x249
github.com/rancher/storage/docker/volumeplugin.(*RancherStorageDriver).doAttach(0xc420012e80, 0xc4202f80f0, 0x41, 0xc4203c9860, 0xcb, 0x0, 0x0, 0x0, 0xc4200d4b18)
	/go/src/github.com/rancher/storage/docker/volumeplugin/plugin.go:181 +0xaf
github.com/rancher/storage/docker/volumeplugin.(*RancherStorageDriver).Mount(0xc420012e80, 0xc4202f80f0, 0x41, 0xc4204f0c80, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/storage/docker/volumeplugin/plugin.go:244 +0x59d
github.com/rancher/storage/vendor/github.com/docker/go-plugins-helpers/volume.(*Handler).initMux.func6(0xc4202f80f0, 0x41, 0xc4204f0c80, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/storage/vendor/github.com/docker/go-plugins-helpers/volume/api.go:114 +0x9a
github.com/rancher/storage/vendor/github.com/docker/go-plugins-helpers/volume.(*Handler).handleMount.func1(0xe0d580, 0xc42047d2b0, 0xc42039cd20)
	/go/src/github.com/rancher/storage/vendor/github.com/docker/go-plugins-helpers/volume/api.go:145 +0xef
net/http.HandlerFunc.ServeHTTP(0xc420229c20, 0xe0d580, 0xc42047d2b0, 0xc42039cd20)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0xc4202377a0, 0xe0d580, 0xc42047d2b0, 0xc42039cd20)
	/usr/local/go/src/net/http/server.go:2022 +0x7f
net/http.serverHandler.ServeHTTP(0xc420013180, 0xe0d580, 0xc42047d2b0, 0xc42039cd20)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc4201f2300, 0xe0de00, 0xc4202452c0)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

3. Repro'd again but this time the stuck volume was trying to *detach*. this vol: vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8 got stuck waiting to get to detached. it was in in-use in aws
Mentions of this volume in the storage-ebs container logs
```
root@craignode2:~# docker logs 352fc6841cc8342a2e78cd678c1ea54850815885a9cad767748d53b91ea04611 2>&1 | grep 1ebe8
time="2017-08-31T19:20:02Z" level=info msg=create.request name="vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8" options=map[size:1] 
time="2017-08-31T19:22:39Z" level=info msg="Updating volume vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8 (1v1129) rancher-ebs:1sd1 on 1h6, state inactive => updating-inactive" err=<nil> 
time="2017-08-31T19:23:45Z" level=info msg=attach.request name="vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8" 
time="2017-08-31T19:23:58Z" level=error msg="Mounted but not registered in Docker: /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8-staging" 
time="2017-08-31T19:23:58Z" level=error msg="Mounted but not registered in Docker: /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8-staging" 
time="2017-08-31T19:23:58Z" level=error msg="Mounted but not registered in Docker: /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8-staging" 
time="2017-08-31T19:23:58Z" level=error msg="Mounted but not registered in Docker: /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8-staging" 
time="2017-08-31T19:23:58Z" level=error msg="Mounted but not registered in Docker: /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8-staging" 
time="2017-08-31T19:23:58Z" level=error msg="Mounted but not registered in Docker: /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8-staging" 
time="2017-08-31T19:24:45Z" level=info msg=attach.request name="vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8" 
time="2017-08-31T19:24:48Z" level=info msg=mount.request name="vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8" 
time="2017-08-31T19:24:48Z" level=error msg="Mounted but not registered in Docker: /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8-staging" 
time="2017-08-31T19:24:48Z" level=error msg="Mounted but not registered in Docker: /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8-staging" 
time="2017-08-31T19:24:48Z" level=error msg="Mounted but not registered in Docker: /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8-staging" 
time="2017-08-31T19:24:48Z" level=error msg="Mounted but not registered in Docker: /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8-staging" 
time="2017-08-31T19:24:48Z" level=error msg="Mounted but not registered in Docker: /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8-staging" 
time="2017-08-31T19:24:48Z" level=error msg="Mounted but not registered in Docker: /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8-staging" 
time="2017-08-31T19:24:48Z" level=error msg="Mounted but not registered in Docker: /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8-staging" 
time="2017-08-31T19:24:48Z" level=error msg="Mounted but not registered in Docker: /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8-staging" 
time="2017-08-31T19:24:49Z" level=info msg=mount.response mountpoint="/var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8" 
time="2017-08-31T19:25:40Z" level=info msg="Unmounting /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8-staging" 
time="2017-08-31T19:25:52Z" level=info msg="Unmounting /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8-staging" 
time="2017-08-31T19:26:06Z" level=info msg=mount.request name="vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8" 
time="2017-08-31T19:26:06Z" level=info msg=unmount.request name="vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8" 
time="2017-08-31T19:26:06Z" level=info msg="Unmounting /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8-staging" 
time="2017-08-31T19:26:06Z" level=info msg="Unmounting /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8-staging" 
time="2017-08-31T19:26:06Z" level=info msg="Unmounting /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8-staging" 
time="2017-08-31T19:26:06Z" level=info msg="Unmounting /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8-staging" 
time="2017-08-31T19:26:06Z" level=info msg="Unmounting /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8-staging" 
time="2017-08-31T19:26:07Z" level=info msg="Unmounting /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8-staging" 
time="2017-08-31T19:26:07Z" level=error msg="Mounted but not registered in Docker: /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8" 
time="2017-08-31T19:26:07Z" level=error msg="Mounted but not registered in Docker: /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8" 
time="2017-08-31T19:26:07Z" level=error msg="Mounted but not registered in Docker: /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8" 
time="2017-08-31T19:26:07Z" level=error msg="Mounted but not registered in Docker: /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8" 
time="2017-08-31T19:26:07Z" level=error msg="Mounted but not registered in Docker: /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8" 
time="2017-08-31T19:26:07Z" level=error msg="Mounted but not registered in Docker: /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8" 
time="2017-08-31T19:26:07Z" level=info msg="Unmounting /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8-staging" 
time="2017-08-31T19:26:07Z" level=info msg="Unmounting /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8-staging" 
time="2017-08-31T19:26:07Z" level=info msg="Unmounting /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8-staging" 
time="2017-08-31T19:26:07Z" level=info msg="Unmounting /var/lib/rancher/volumes/rancher-ebs/vol-test-stack-7_vol_2_d240d509-0605-4e52-a536-edee4d605de9_1ebe8"
```

**Comment by cjellick** [comment]
Here's a diagram of how we can get into this state:
![fullsizerender](https://user-images.githubusercontent.com/2473240/29944254-aba1fcec-8e51-11e7-9588-8a5468818b17.jpg)

**Comment by moelsayed** [comment]
https://github.com/rancher/storage/pull/70

**Comment by galal-hussein** [comment]
Rancher version: v1.6.11-rc1
Ebs driver: 0.8.11

I tested the driver with over than 30 stacks that create/attach/mount/delete ebs volumes, and writes data to the volumes, also tested with failing image that kept creating/deleting volumes due to container flapping, i didn't notice any issues nor i saw the hosts in reconnecting state.
