### ISSUE TITLE
Expected state running but got stopped

### ISSUE THREAD

**Issue by lvsir625** [rancher/rancher#9806]
**Rancher versions:**
rancher/server: 1.2.2
rancher/agent: 1.1.2

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.12.5
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
centos 7
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

question:
build server faild,and the errors is as follows: Expected state running but got stopped
and then,pull image from the registry is faild

**Comment by lvsir625** [comment]
The registry   is  no problem

**Comment by lvsir625** [comment]
Caused by: io.cattle.platform.engine.process.impl.ProcessExecutionExitException: PROCESS_ALREADY_IN_PROGRESS
        ... 35 more
Aug 31, 2017 4:55:18 PM com.google.common.util.concurrent.ExecutionList executeListener
SEVERE: RuntimeException while executing runnable com.google.common.util.concurrent.Futures$4@18ffa8d7 with executor com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService@64e84261
io.cattle.platform.engine.process.ProcessInstanceException: io.cattle.platform.engine.process.impl.ProcessExecutionExitException: PROCESS_ALREADY_IN_PROGRESS
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:120)
        at io.cattle.platform.engine.manager.impl.DefaultProcessManager.scheduleProcessInstance(DefaultProcessManager.java:61)
        at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.scheduleProcessInstance(DefaultObjectProcessManager.java:50)
        at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.scheduleProcessInstance(DefaultObjectProcessManager.java:55)
        at io.cattle.platform.agent.server.ping.impl.PingMonitorImpl.pingFailure(PingMonitorImpl.java:145)
        at io.cattle.platform.agent.server.ping.impl.PingMonitorImpl$2.onFailure(PingMonitorImpl.java:122)
        at com.google.common.util.concurrent.Futures$4.run(Futures.java:1160)
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
        at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:202)
        at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:845)
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
        at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:202)
        at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:845)
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
        at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:202)
        at com.google.common.util.concurrent.SettableFuture.setException(SettableFuture.java:68)
        at io.cattle.platform.async.retry.impl.RetryTimeoutServiceImpl.retry(RetryTimeoutServiceImpl.java:43)
        at sun.reflect.GeneratedMethodAccessor737.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: io.cattle.platform.engine.process.impl.ProcessExecutionExitException: PROCESS_ALREADY_IN_PROGRESS
        ... 35 more
time="2017-09-01T00:37:58Z" level=info msg="Shutting down backend 0d3aa31e-e8b0-40a8-725f-3508ae8df809. Connection closed because: websocket: close 1006 unexpected EOF." 
time="2017-09-01T00:37:58Z" level=info msg="Removed backend. Key: 0d3aa31e-e8b0-40a8-725f-3508ae8df809. Session ID d2956d82-c2fd-441d-9aae-e3409de13ad1 ." 
time="2017-09-01T00:38:05Z" level=info msg="Handling backend connection request." 
time="2017-09-01T00:38:05Z" level=info msg="Registering backend for host 0d3aa31e-e8b0-40a8-725f-3508ae8df809 with session ID c00f3f95-7eda-46ec-9acd-9865807bbb90." 
time="2017-09-01T00:38:07Z" level=info msg="Exiting go-machine-service" 
time="2017-09-01T00:38:09Z" level=info msg="Setting log level" logLevel=info 
time="2017-09-01T00:38:09Z" level=info msg="Starting go-machine-service..." gitcommit=v0.34.1 
time="2017-09-01T00:38:09Z" level=info msg="Waiting for handler registration (1/2)" 
time="2017-09-01T00:38:17Z" level=info msg="Initializing event router" workerCount=10 
time="2017-09-01T00:38:17Z" level=info msg="Connection established" 
time="2017-09-01T00:38:17Z" level=info msg="Waiting for handler registration (2/2)" 
time="2017-09-01T00:38:17Z" level=info msg="Starting websocket pings" 
time="2017-09-01T00:38:20Z" level=info msg="Initializing event router" workerCount=10 
time="2017-09-01T00:38:20Z" level=info msg="Connection established" 
time="2017-09-01T00:38:20Z" level=info msg="Starting websocket pings" 
time="2017-09-01T00:38:20Z" level=info msg="Installing builtin drivers" 
time="2017-09-01T00:38:20Z" level=info msg="Downloading all drivers" 
time="2017-09-01T00:38:20Z" level=info msg="Done downloading all drivers" 
time="2017-09-01T00:43:22Z" level=info msg="Shutting down backend 9b69aafb-6c09-4a91-65fa-3d22da413b14. Connection closed because: websocket: close 1006 unexpected EOF." 
time="2017-09-01T00:43:22Z" level=info msg="Removed backend. Key: 9b69aafb-6c09-4a91-65fa-3d22da413b14. Session ID 1e8debb0-6f61-424a-9f07-77b92c79f132 ." 
time="2017-09-01T00:43:31Z" level=info msg="Handling backend connection request." 
time="2017-09-01T00:43:31Z" level=info msg="Registering backend for host 9b69aafb-6c09-4a91-65fa-3d22da413b14 with session ID 9da381dc-e6a6-41e2-8bbf-07c3068ba989." 
time="2017-09-01T01:15:23Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-09-01T01:15:27Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-09-01T01:15:32Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-09-01T01:15:38Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-09-01T01:15:45Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-09-01T01:15:53Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-09-01T01:16:02Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-09-01T01:16:12Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-09-01T01:16:23Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-09-01T01:16:35Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-09-01T01:16:48Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-09-01T01:17:02Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-09-01T01:17:17Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-09-01T01:17:33Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-09-01T01:17:50Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-09-01T01:18:08Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-09-01T01:18:27Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-09-01T01:18:47Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-09-01T01:19:08Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-09-01T01:19:30Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-09-01T01:19:54Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-09-01T01:20:18Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
2017-09-01 02:25:22,245 ERROR [6dd5b841-994a-4be9-9a47-c59c255ecfe7:8937842] [volumeStoragePoolMap:298547] [volumestoragepoolmap.remove] [] [cutorService-37] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [storage.volume.remove.reply;agent=149382]: Error response from daemon: Unable to remove filesystem for 66880277ff42125cc6f6e6d395167a7ad4c301f3bd86396814376ff4eca5e179: remove /home/lib/docker/containers/66880277ff42125cc6f6e6d395167a7ad4c301f3bd86396814376ff4eca5e179/shm: device or resource busy 
2017-09-01 02:25:23,074 ERROR [:] [] [] [] [cutorService-37] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [storage.volume.remove.reply;agent=149382]: Error response from daemon: Unable to remove filesystem for 66880277ff42125cc6f6e6d395167a7ad4c301f3bd86396814376ff4eca5e179: remove /home/lib/docker/containers/66880277ff42125cc6f6e6d395167a7ad4c301f3bd86396814376ff4eca5e179/shm: device or resource busy 
2017-09-01 02:25:23,074 ERROR [:] [] [] [] [cutorService-40] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [storage.volume.remove.reply;agent=149382]: Error response from daemon: Unable to remove filesystem for 1583f5390746ec76ef1787003016b31951e48b8b173d7572cdcbc8dee5fe2b27: remove /home/lib/docker/containers/1583f5390746ec76ef1787003016b31951e48b8b173d7572cdcbc8dee5fe2b27/shm: device or resource busy 
2017-09-01 02:25:31,270 ERROR [:] [] [] [] [cutorService-43] [o.a.c.m.context.NoExceptionRunnable ] Expected state running but got stopped 
2017-09-01 02:25:37,124 ERROR [92d4f080-3a60-4761-aa83-2f325ebdeb2e:8885670] [volumeStoragePoolMap:298804] [volumestoragepoolmap.remove] [] [cutorService-10] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [storage.volume.remove.reply;agent=149382]: Error response from daemon: Unable to remove filesystem for 1583f5390746ec76ef1787003016b31951e48b8b173d7572cdcbc8dee5fe2b27: remove /home/lib/docker/containers/1583f5390746ec76ef1787003016b31951e48b8b173d7572cdcbc8dee5fe2b27/shm: device or resource busy 
2017-09-01 02:25:37,701 ERROR [:] [] [] [] [cutorService-10] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [storage.volume.remove.reply;agent=149382]: Error response from daemon: Unable to remove filesystem for 1583f5390746ec76ef1787003016b31951e48b8b173d7572cdcbc8dee5fe2b27: remove /home/lib/docker/containers/1583f5390746ec76ef1787003016b31951e48b8b173d7572cdcbc8dee5fe2b27/shm: device or resource busy 
2017-09-01 02:25:38,085 ERROR [f644a93c-230f-4854-a033-f78f79e0ec8c:8925052] [instance:315230] [instance.start->(InstanceStart)] [] [cutorService-16] [i.c.p.process.instance.InstanceStart] Failed [Dependencies readiness error instance is not running] for instance [315230] 
2017-09-01 02:25:47,011 ERROR [:] [] [] [] [cutorService-24] [o.a.c.m.context.NoExceptionRunnable ] Expected state running but got stopped 
2017-09-01 02:25:52,165 ERROR [192e026f-4b20-4e08-9947-e0871f94982f:8885676] [volumeStoragePoolMap:298804] [volumestoragepoolmap.remove] [] [ecutorService-6] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [storage.volume.remove.reply;agent=149382]: Error response from daemon: Unable to remove filesystem for 1583f5390746ec76ef1787003016b31951e48b8b173d7572cdcbc8dee5fe2b27: remove /home/lib/docker/containers/1583f5390746ec76ef1787003016b31951e48b8b173d7572cdcbc8dee5fe2b27/shm: device or resource busy 
2017-09-01 02:25:52,564 ERROR [:] [] [] [] [ecutorService-6] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [storage.volume.remove.reply;agent=149382]: Error response from daemon: Unable to remove filesystem for 1583f5390746ec76ef1787003016b31951e48b8b173d7572cdcbc8dee5fe2b27: remove /home/lib/docker/containers/1583f5390746ec76ef1787003016b31951e48b8b173d7572cdcbc8dee5fe2b27/shm: device or resource busy

**Comment by vincent99** [comment]
You're using a release that is almost a year old.  There have been many improvements and bug fixes to the event handling and clean up of resources since then.

**Comment by aemneina** [comment]
@lvsir625 you'll most likely want to start up another fresh modern rancher install and migrate your workload to that.

To work through this issue, i'd try to stop all the user stacks and focus on getting the infrastructure stacks stable. starting with the network services stack, then ipsec...

**Comment by superseb** [comment]
Please try a newer version and file a new issue when you encounter problems.
