### ISSUE TITLE
[rancher-catalog][rancher-nfs] Can't mount my custom NFS share

### ISSUE THREAD

**Issue by jri-sp** [rancher/rancher#9809]
**Rancher versions:**
rancher/server: 1.6.8
rancher/agent: 1.2.6

**Infrastructure Stack versions:**
healthcheck: 0.3.3
ipsec: 0.1.4
network-services: 0.2.6
scheduler: 0.8.2
nfs: 0.8.5

**Docker version: (`docker version`,`docker info` preferred)**
```
$ docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.5
 Git commit:   a82d35e
 Built:        Tue Jul 18 23:18:48 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.5
 Git commit:   a82d35e
 Built:        Tue Jul 18 23:18:48 2017
 OS/Arch:      linux/amd64


$ docker info
Containers: 19
 Running: 15
 Paused: 0
 Stopped: 4
Images: 25
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local rancher-nfs
 Network: bridge host overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp selinux
Kernel Version: 4.11.11-coreos
Operating System: Container Linux by CoreOS 1409.7.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 7.712 GiB
Name: docker01.xxx.fr
ID: ZBPQ:KLGI:VC4S:4ECN:HNGA:YE5S:5QZ4:5IDL:MNDH:U2A3:ZBL2:IUA6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 registry-01.xxx.fr:5000
 127.0.0.0/8
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1409.7.0
VERSION_ID=1409.7.0
BUILD_ID=2017-07-19-0005
PRETTY_NAME="Container Linux by CoreOS 1409.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

$ uname -r
4.11.11-coreos
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Virtual Machine in XenServer 7.2

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher with two nodes. External DB in MySQL cluster.

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a stack with this `docker-compose.yml`:
```
version: '2'
services:
  foo:
    image: alpine
    stdin_open: true
    volumes:
    - bar:/data
volumes:
  bar:
    driver: rancher-nfs
    driver_opts:
      host: 10.24.1.15
      exportBase: /​m​n​t​/​l​v​m​/​l​v​m​_​a​r​r​a​y​1​/​l​v​m​1​0​2​_​share/​share
```

**Results:**

There is an error message "Conflict" in the UI.
And this in the rancher  log:
```
2017-09-01 07:49:02,855 ERROR [:] [] [] [] [1020391880-1176] [i.g.i.g.s.ApiRequestFilterDelegate  ] Unhandled exception in API for request [http://rancher.xxx.fr:8080/v2-beta/projects/1a395/stack] org.jooq.exception.DataAccessException: SQL [insert into `audit_log` (`account_id`, `authenticated_as_account_id`, `kind`, `auth_type`, `event_type`, `resource_type`, `resource_id`, `description`, `created`, `data`, `authenticated_as_identity_id`, `runtime`, `client_ip`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; (conn:4353) Incorrect string value: '\xE2\x80\x8Bm\xE2\x80...' for column 'data' at row 1
Query is: insert into `audit_log` (`account_id`, `authenticated_as_account_id`, `kind`, `auth_type`, `event_type`, `resource_type`, `resource_id`, `description`, `created`, `data`, `authenticated_as_identity_id`, `runtime`, `client_ip`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), parameters [395,1,'auditLog','TokenAuth','api.stack.create','stack',<null>,<null>,'2017-09-01 07:49:02.853','{"fields":{"responseObject":"{\"id\":\"78f37656-f08b-4418-b0b2-f7f0cb7117c2\",\"type\":\"error\",\"links\":{},\"actions\":{},\"status\":409,\"code\":\"Conflict\",\"message\":\"Conflict\",\"detail\":null,\"baseType\":\"error\"}","requestObject":"{\"previousExternalId\":null,\"description\":null,\"externalId\":\"\",\"dockerCompose\":\"version: '2'\\nservices:\\n  foo:\\n    image: alpine\\n    stdin_open: true\\n    volumes:\\n    - bar:\\/data\\nvolumes:\\n  bar:\\n    driver: rancher-nfs\\n    driver_opts:\\n      host: 10.24.1.15\\n      exportBase: \\/mnt\\/lvm\\/lvm_array1\\/lvm102_share\\/share\",\...
	at org.jooq.impl.Utils.translate(Utils.java:1287) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:495) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:326) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.UpdatableRecordImpl.storeInsert0(UpdatableRecordImpl.java:230) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.UpdatableRecordImpl.access$100(UpdatableRecordImpl.java:90) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.UpdatableRecordImpl$2.operate(UpdatableRecordImpl.java:201) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:123) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.UpdatableRecordImpl.storeInsert(UpdatableRecordImpl.java:196) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.UpdatableRecordImpl.insert(UpdatableRecordImpl.java:144) ~[jooq-3.3.0.jar:na]
	at io.cattle.platform.object.impl.JooqObjectManager$1.executeNoResult(JooqObjectManager.java:80) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.idempotent.IdempotentExecutionNoReturn.execute(IdempotentExecutionNoReturn.java:7) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.idempotent.IdempotentExecutionNoReturn.execute(IdempotentExecutionNoReturn.java:3) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.idempotent.Idempotent.change(Idempotent.java:88) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.object.impl.JooqObjectManager.insert(JooqObjectManager.java:77) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.object.impl.AbstractObjectManager.create(AbstractObjectManager.java:51) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.object.impl.AbstractObjectManager.create(AbstractObjectManager.java:33) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.iaas.api.auditing.dao.impl.AuditLogDaoImpl.create(AuditLogDaoImpl.java:39) ~[cattle-framework-auditing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.iaas.api.auditing.AuditServiceImpl.logRequest(AuditServiceImpl.java:102) ~[cattle-framework-auditing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.iaas.api.auditing.AuditLogsRequestHandler.handle(AuditLogsRequestHandler.java:23) ~[cattle-framework-auditing-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:99) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:96) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:106) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [jetty-security-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.Server.handle(Server.java:499) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
Caused by: java.sql.SQLDataException: (conn:4353) Incorrect string value: '\xE2\x80\x8Bm\xE2\x80...' for column 'data' at row 1
Query is: insert into `audit_log` (`account_id`, `authenticated_as_account_id`, `kind`, `auth_type`, `event_type`, `resource_type`, `resource_id`, `description`, `created`, `data`, `authenticated_as_identity_id`, `runtime`, `client_ip`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), parameters [395,1,'auditLog','TokenAuth','api.stack.create','stack',<null>,<null>,'2017-09-01 07:49:02.853','{"fields":{"responseObject":"{\"id\":\"78f37656-f08b-4418-b0b2-f7f0cb7117c2\",\"type\":\"error\",\"links\":{},\"actions\":{},\"status\":409,\"code\":\"Conflict\",\"message\":\"Conflict\",\"detail\":null,\"baseType\":\"error\"}","requestObject":"{\"previousExternalId\":null,\"description\":null,\"externalId\":\"\",\"dockerCompose\":\"version: '2'\\nservices:\\n  foo:\\n    image: alpine\\n    stdin_open: true\\n    volumes:\\n    - bar:\\/data\\nvolumes:\\n  bar:\\n    driver: rancher-nfs\\n    driver_opts:\\n      host: 10.24.1.15\\n      exportBase: \\/mnt\\/lvm\\/lvm_array1\\/lvm102_share\\/share\",\...
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:129) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.getException(ExceptionMapper.java:101) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwAndLogException(ExceptionMapper.java:77) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:224) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:411) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.MariaDbServerPreparedStatement.execute(MariaDbServerPreparedStatement.java:361) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeUpdate(MariaDbServerPreparedStatement.java:350) ~[mariadb-java-client-1.5.8.jar:na]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.executeUpdate(DefaultPreparedStatement.java:88) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractStoreQuery.execute(AbstractStoreQuery.java:346) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:322) ~[jooq-3.3.0.jar:na]
	... 45 common frames omitted
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Incorrect string value: '\xE2\x80\x8Bm\xE2\x80...' for column 'data' at row 1
Query is: insert into `audit_log` (`account_id`, `authenticated_as_account_id`, `kind`, `auth_type`, `event_type`, `resource_type`, `resource_id`, `description`, `created`, `data`, `authenticated_as_identity_id`, `runtime`, `client_ip`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), parameters [395,1,'auditLog','TokenAuth','api.stack.create','stack',<null>,<null>,'2017-09-01 07:49:02.853','{"fields":{"responseObject":"{\"id\":\"78f37656-f08b-4418-b0b2-f7f0cb7117c2\",\"type\":\"error\",\"links\":{},\"actions\":{},\"status\":409,\"code\":\"Conflict\",\"message\":\"Conflict\",\"detail\":null,\"baseType\":\"error\"}","requestObject":"{\"previousExternalId\":null,\"description\":null,\"externalId\":\"\",\"dockerCompose\":\"version: '2'\\nservices:\\n  foo:\\n    image: alpine\\n    stdin_open: true\\n    volumes:\\n    - bar:\\/data\\nvolumes:\\n  bar:\\n    driver: rancher-nfs\\n    driver_opts:\\n      host: 10.24.1.15\\n      exportBase: \\/mnt\\/lvm\\/lvm_array1\\/lvm102_share\\/share\",\...
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1115) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1047) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1002) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executePreparedQuery(AbstractQueryProtocol.java:588) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:399) ~[mariadb-java-client-1.5.8.jar:na]
	... 52 common frames omitted

```

I've tried to mount my share directly on my docker hosts and it's working great, so my share is OK.

I think the issue come from the path in `exportBase` driver option. 
Maybe we can't use a long path ? but I can't choose it because my share is on a NAS server and the NFS path is generated.

**Comment by vincent99** [comment]
Is your database charset something other than `utf8`?

**Comment by jri-sp** [comment]
Hi @vincent99 !

Thanks for your answer!

No... I'm in `latin1` for the database, and `latin1_swedish_ci` for the tables.

Should I change ?

**Comment by vincent99** [comment]
Yes, you can't store UTF-8 in a latin1 table.  http://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/#single-container-external-database

(this may or may not be related to your actual problem, but that's what the stack trace is for)

**Comment by jri-sp** [comment]
Thank you very much @vincent99 !

I've converted my Database, tables and columns charsets and it's working know!

I close this issue then.
