### ISSUE TITLE
Rancher container restarts

### ISSUE THREAD

**Issue by rmdort** [rancher/rancher#9823]
**Rancher versions:**
rancher/server: v1.6.7
rancher/agent: v1.2.5

**Docker version: (`docker version`,`docker info` preferred)**
1.12.5

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Debian GNU/Linux 9 (stretch)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
GCE

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.7.2

**Steps to Reproduce:**
* Deploy a pod to K8
* Rancher container started restarting
* Started getting this error on K8 `Pod sandbox changed, it will be killed and re-created`
* I cant stop or restart the rancher/server container either

Logs from rancher-server

````
2017-09-04 13:55:24,695 ERROR [:] [] [] [] [ecutorService-8] [.e.s.i.ProcessInstanceDispatcherImpl] Unknown exception running process [containerevent.create:29364] on [5057] org.jooq.exception.DataAccessException: SQL [insert into `process_execution` (`process_instance_id`, `uuid`, `log`, `created`) values (?, ?, ?, ?)]; (conn:487) The table 'process_execution' is full
Query is: insert into `process_execution` (`process_instance_id`, `uuid`, `log`, `created`) values (?, ?, ?, ?), parameters [29364,'1e7f5c95-7b60-44c6-a472-b15346cece35','{"uuid":"1e7f5c95-7b60-44c6-a472-b15346cece35","executions":[{"children":[],"id":"f33add80-9b13-4224-8f21-bdedabe0c856","startTime":1504533324560,"processName":"containerevent.create","stopTime":1504533324625,"processingServerId":"172.17.0.2","resourceType":"containerEvent","resourceId":"5057","processId":29364,"transitions":[],"processHandlerExecutions":[],"exception":{"message":"SQL [insert into `process_execution` (`process_instance_id`, `uuid`, `log`, `created`) values (?, ?, ?, ?)]; (conn:487) The table 'process_execution' is full\nQuery is: insert into `process_execution` (`process_instance_id`, `uuid`, `log`, `created`) values (?, ?, ?, ?), parameters [29364,'1e7f5c95-7b60-44c6-a472-b15346cece35','{\"uuid\":\"1e7f5c95-7b60-44c6-a472-b15346cece35\",\"executions\":[{\"children\":[],\"id\":\"f33add80-9b13-4224-8f21-bdedabe0c856\",\"startTime\":...
       	at org.jooq.impl.Utils.translate(Utils.java:1287) ~[jooq-3.3.0.jar:na]
       	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:495) ~[jooq-3.3.0.jar:na]
       	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:326) ~[jooq-3.3.0.jar:na]
       	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:140) ~[jooq-3.3.0.jar:na]
       	at io.cattle.platform.engine.manager.impl.jooq.JooqProcessRecordDao.update(JooqProcessRecordDao.java:202) ~[cattle-iaas-engine-jooq-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.engine.manager.impl.DefaultProcessManager.persistState(DefaultProcessManager.java:131) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:173) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:116) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:113) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:113) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl.processExecuteWithLock(ProcessInstanceDispatcherImpl.java:117) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl$1.doWithLock(ProcessInstanceDispatcherImpl.java:104) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl$1.doWithLock(ProcessInstanceDispatcherImpl.java:101) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$4.doWithLock(AbstractLockManagerImpl.java:50) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:25) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:47) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl.execute(ProcessInstanceDispatcherImpl.java:101) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.engine.server.ProcessInstanceReference.doRun(ProcessInstanceReference.java:58) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
       	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
       	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
       	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
       	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
       	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
       	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
       	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
Caused by: java.sql.SQLException: (conn:487) The table 'process_execution' is full
Query is: insert into `process_execution` (`process_instance_id`, `uuid`, `log`, `created`) values (?, ?, ?, ?), parameters [29364,'1e7f5c95-7b60-44c6-a472-b15346cece35','{"uuid":"1e7f5c95-7b60-44c6-a472-b15346cece35","executions":[{"children":[],"id":"f33add80-9b13-4224-8f21-bdedabe0c856","startTime":1504533324560,"processName":"containerevent.create","stopTime":1504533324625,"processingServerId":"172.17.0.2","resourceType":"containerEvent","resourceId":"5057","processId":29364,"transitions":[],"processHandlerExecutions":[],"exception":{"message":"SQL [insert into `process_execution` (`process_instance_id`, `uuid`, `log`, `created`) values (?, ?, ?, ?)]; (conn:487) The table 'process_execution' is full\nQuery is: insert into `process_execution` (`process_instance_id`, `uuid`, `log`, `created`) values (?, ?, ?, ?), parameters [29364,'1e7f5c95-7b60-44c6-a472-b15346cece35','{\"uuid\":\"1e7f5c95-7b60-44c6-a472-b15346cece35\",\"executions\":[{\"children\":[],\"id\":\"f33add80-9b13-4224-8f21-bdedabe0c856\",\"startTime\":...
       	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:150) ~[mariadb-java-client-1.5.8.jar:na]
       	at org.mariadb.jdbc.internal.util.ExceptionMapper.getException(ExceptionMapper.java:101) ~[mariadb-java-client-1.5.8.jar:na]
       	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwAndLogException(ExceptionMapper.java:77) ~[mariadb-java-client-1.5.8.jar:na]
       	at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:224) ~[mariadb-java-client-1.5.8.jar:na]
       	at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:411) ~[mariadb-java-client-1.5.8.jar:na]
       	at org.mariadb.jdbc.MariaDbServerPreparedStatement.execute(MariaDbServerPreparedStatement.java:361) ~[mariadb-java-client-1.5.8.jar:na]
       	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar:1.4]
       	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar:1.4]
       	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:194) ~[jooq-3.3.0.jar:na]
       	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:376) ~[jooq-3.3.0.jar:na]
       	at org.jooq.impl.AbstractStoreQuery.execute(AbstractStoreQuery.java:289) ~[jooq-3.3.0.jar:na]
       	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:322) ~[jooq-3.3.0.jar:na]
       	... 29 common frames omitted
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: The table 'process_execution' is full
Query is: insert into `process_execution` (`process_instance_id`, `uuid`, `log`, `created`) values (?, ?, ?, ?), parameters [29364,'1e7f5c95-7b60-44c6-a472-b15346cece35','{"uuid":"1e7f5c95-7b60-44c6-a472-b15346cece35","executions":[{"children":[],"id":"f33add80-9b13-4224-8f21-bdedabe0c856","startTime":1504533324560,"processName":"containerevent.create","stopTime":1504533324625,"processingServerId":"172.17.0.2","resourceType":"containerEvent","resourceId":"5057","processId":29364,"transitions":[],"processHandlerExecutions":[],"exception":{"message":"SQL [insert into `process_execution` (`process_instance_id`, `uuid`, `log`, `created`) values (?, ?, ?, ?)]; (conn:487) The table 'process_execution' is full\nQuery is: insert into `process_execution` (`process_instance_id`, `uuid`, `log`, `created`) values (?, ?, ?, ?), parameters [29364,'1e7f5c95-7b60-44c6-a472-b15346cece35','{\"uuid\":\"1e7f5c95-7b60-44c6-a472-b15346cece35\",\"executions\":[{\"children\":[],\"id\":\"f33add80-9b13-4224-8f21-bdedabe0c856\",\"startTime\":...
       	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1115) ~[mariadb-java-client-1.5.8.jar:na]
       	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1047) ~[mariadb-java-client-1.5.8.jar:na]
       	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1002) ~[mariadb-java-client-1.5.8.jar:na]
       	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executePreparedQuery(AbstractQueryProtocol.java:588) ~[mariadb-java-client-1.5.8.jar:na]
       	at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:399) ~[mariadb-java-client-1.5.8.jar:na]
       	... 36 common frames omitted

2017-09-04 13:55:24,706 ERROR [baaef029-cda7-4936-936d-68d4bfbdec2d:29367] [containerEvent:5060] [containerevent.create] [] [cutorService-10] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception org.jooq.exception.DataAccessException: SQL [insert into `process_execution` (`process_instance_id`, `uuid`, `log`, `created`) values (?, ?, ?, ?)]; (conn:490) The table 'process_execution' is full
Query is: insert into `process_execution` (`process_instance_id`, `uuid`, `log`, `created`) values (?, ?, ?, ?), parameters [29367,'373609ab-44f3-4665-baf2-b54e2e6fcd3a','{"uuid":"373609ab-44f3-4665-baf2-b54e2e6fcd3a","executions":[{"children":[],"id":"baaef029-cda7-4936-936d-68d4bfbdec2d","startTime":1504533324592,"processName":"containerevent.create","stopTime":null,"processingServerId":"172.17.0.2","resourceType":"containerEvent","resourceId":"5060","processId":29367,"transitions":[],"processHandlerExecutions":[],"exception":null,"exitReason":null,"name":"containerevent.create"}]}','2017-09-04 13:55:24.617']
       	at org.jooq.impl.Utils.translate(Utils.java:1287) ~[jooq-3.3.0.jar:na]
       	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:495) ~[jooq-3.3.0.jar:na]
       	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:326) ~[jooq-3.3.0.jar:na]
       	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:140) ~[jooq-3.3.0.jar:na]
       	at io.cattle.platform.engine.manager.impl.jooq.JooqProcessRecordDao.update(JooqProcessRecordDao.java:202) ~[cattle-iaas-engine-jooq-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.engine.manager.impl.DefaultProcessManager.persistState(DefaultProcessManager.java:131) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:341) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:245) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
````

**Comment by rmdort** [comment]
Issue seems to be fixed now. No idea what the problem was.

I had to restart the server and then restart rancher/server docker container.

**Comment by cjellick** [comment]
Those `The table 'process_execution' is full` errors aren't good. Means you're running out of disk space. Is your rancher/server host nearly out of diskspace? It could be that some disk was freed up when you rebooted, but you may run into the issue again soon if you don't have much disk.
