### ISSUE TITLE
Service stuck in "Starting (starting)"

### ISSUE THREAD

**Issue by zuoez02** [rancher/rancher#9876]
**Rancher versions:**
rancher/server: v1.6.4
rancher/agent: v1.2.5

**Infrastructure Stack versions:**
healthcheck: v0.3.1
ipsec: rancher/net:v0.11.3
network-services: rancher/metadata:v0.9.2
scheduler: v0.8.2

**Docker version: (`docker version`,`docker info` preferred)**
```
Containers: 13
 Running: 10
 Paused: 0
 Stopped: 3
Images: 12
Server Version: 17.07.0-ce-rc2
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 3addd840653146c90a254301d6c3a663c7fd6429
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.64GiB
Name: localhost.localdomain
ID: AF42:TUU2:AM4V:6QE2:RM7K:TWK3:RZ7B:YKGG:HRQW:SDSY:YQXB:UHF5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-ip6tables is disabled
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
# cat /etc/os-release
3.10.0-514.el7.x86_64
 # cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware vSphere
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher with external DB
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1. Add a new service in user stack.
2. Service is starting.
3. Actually the container is started on the host through ssh and docker ps

**Results:**
I see the log of rancher server and get:
```
Query is: update `instance` set `instance`.`data` = ?, `instance`.`external_id` = ? where `instance`.`id` = ?, parameters ['{"fields":{"vcpu":1,"ports":[],"allocatedIpAddress":null,"startOnCreate":true,"capAdd":[],"imageUuid":"docker:192.168.97.242:5000/venustech/monitor-kibana:5.5.0","networkMode":"managed","serviceIndex":"1","dataVolumesFrom":[],"logConfig":{"config":{},"driver":null},"publishAllPorts":false,"dataVolumesFromLaunchConfigs":[],"devices":[],"stdinOpen":true,"dataVolumes":[],"dns":["169.254.169.250"],"readOnly":false,"secrets":[],"labels":{"io.rancher.service.deployment.unit":"4dab90be-6821-4e0c-9f3e-ccce14485a69","io.rancher.stack_service.name":"asap/monitorKibana","io.rancher.service.launch.config":"io.rancher.service.primary.launch.config","io.rancher.project.name":"asap","io.rancher.project_service.name":"asap/monitorKibana","io.rancher.stack.name":"asap","io.rancher.container.pull_image":"always"},"privileged":false,"environment":{"ELASTICSEARCH_URL":"http://common-elasticsearch:9200","KIBANA_IND...
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:150) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.getException(ExceptionMapper.java:101) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwAndLogException(ExceptionMapper.java:77) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:224) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:411) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.MariaDbServerPreparedStatement.execute(MariaDbServerPreparedStatement.java:361) ~[mariadb-java-client-1.5.8.jar:na]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar:1.4]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:194) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:376) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractStoreQuery.execute(AbstractStoreQuery.java:289) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:322) ~[jooq-3.3.0.jar:na]
	... 83 common frames omitted
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Incorrect string value: '\xE3\x80\x81169...' for column 'data' at row 1
```
I don't know how to resolve the problem and need some help.

**Comment by vincent99** [comment]
Some part of the service definition contains a UTF-8 character (`\xE3\x80\81` is an comma-like character: `、`) and your database was not setup with the correct character set so it cannot be stored.  http://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/#single-container-external-database

**Comment by zuoez02** [comment]
@vincent99 It works, thank you for your help
