### ISSUE TITLE
After updating Rancher and RancherOS on the host logging in with the Active Directory provider fails.

### ISSUE THREAD

**Issue by larssb** [rancher/rancher#9889]
**Rancher versions:**
rancher/server: v1.6.9
rancherOS: v1.1.0
rancher/agent: .....

**Infrastructure Stack versions:**
healthcheck:  
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
`
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 4
Server Version: 17.03.2-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.45-rancher
Operating System: RancherOS v1.1.0
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 9.767 GiB
Name: "SERVERNAME"
ID: B7HC:OKKG:PA7N:EWFD:54FJ:NEYM:LEWR:R3QX:7WSO:OQYV:PYOL:B5DL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: 192.168.199.2:8080
Https Proxy: 192.168.199.2:8080
No Proxy: localhost,127.0.0.1
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
`

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.9.45-rancher

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VmWare v5 455964

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node with an internal db.

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
1. Install RancherOS
2. Install Rancher
3. Have an Microsoft AD server ready. (Windows Server 2008R2 forest functional lvl).
3a. OS 2012R2
4. Create an account with "Domain user" rights.
4a. Use that as the 'Service Account'
5. Configure "Active Directory" integration through this endpoint --> /admin/access/activedirectory
6. Test.....error thrown.

**Results:**
The error I get in the cattle debug log is -->
`
2017-09-15 14:02:29,246 ERROR [:] [] [] [] [p1020391880-132] [.a.a.i.e.ExternalServiceAuthProvider] Failed to get token from Auth                                                             Service. org.apache.http.NoHttpResponseException: The target server failed to respond
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143) ~[httpclient-4.3.1.ja                                                            r:4.3.1]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57) ~[httpclient-4.3.1.jar                                                            :4.3.1]
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260) ~[httpcore-4.3.jar:4.3]
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161) ~[httpco                                                            re-4.3.jar:4.3]
        at sun.reflect.GeneratedMethodAccessor527.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_72]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_72]
        at org.apache.http.impl.conn.CPoolProxy.invoke(CPoolProxy.java:138) ~[httpclient-4.3.1.jar:4.3.1]
        at com.sun.proxy.$Proxy82.receiveResponseHeader(Unknown Source) ~[na:na]
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271) ~[httpcore-4.3.jar:4.3]
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123) ~[httpcore-4.3.jar:4.3]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:253) ~[httpclient-4.3.1.jar:4.3.1]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194) ~[httpclient-4.3.1.jar:4.3.1]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85) ~[httpclient-4.3.1.jar:4.3.1]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108) ~[httpclient-4.3.1.jar:4.3.1]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186) ~[httpclient-4.3.1.jar:4.3.1]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.3.1.jar:4.3.1]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106) ~[httpclient-4.3.1.jar:4.3.1]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57) ~[httpclient-4.3.1.jar:4.3.1]
        at org.apache.http.client.fluent.Request.execute(Request.java:143) ~[fluent-hc-4.3.1.jar:4.3.1]
        at io.cattle.platform.iaas.api.auth.integration.external.ExternalServiceAuthProvider.getToken(ExternalServiceAuthProvider.                                                            java:80) ~[cattle-iaas-auth-logic-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.iaas.api.auth.identity.TokenResourceManager.createToken(TokenResourceManager.java:105) [cattle-iaas-                                                            auth-logic-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.iaas.api.auth.identity.TokenResourceManager.createInternal(TokenResourceManager.java:82) [cattle-iaa                                                            s-auth-logic-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.create(AbstractBaseResourceManager.jav                                                            a:115) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.handler.ResourceManagerRequestHandler.generate(ResourceManagerRequestHandler.jav                                                            a:40) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.handler.AbstractResponseGenerator.handle(AbstractResponseGenerator.java:14) [cat                                                            tle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.handle(DefaultReadWriteApiDelegate.jav                                                            a:27) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.write(DefaultReadWriteApiDelegate.java                                                            :22) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at sun.reflect.GeneratedMethodAccessor485.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_72]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_72]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) [spring-aop-4.3.2.RELEASE.ja                                                            r:4.3.2.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) [spri                                                            ng-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4                                                            .3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:                                                            99) [spring-tx-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.j                                                            ava:280) [spring-tx-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) [spring-tx-4.                                                            3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4                                                            .3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) [spring-aop                                                            -4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4                                                            .3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) [spring-aop-4.3.2.RELEASE.jar:                                                            4.3.2.RELEASE]
        at com.sun.proxy.$Proxy67.write(Unknown Source) [na:na]
        at io.github.ibuildthecloud.gdapi.request.handler.write.ReadWriteApiHandler.handle(ReadWriteApiHandler.java:19) [cattle-fr                                                            amework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:99) [cattle-fram                                                            ework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:96) [cattle-framework-api-0.5.0-SN                                                            APSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-ma                                                            naged-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framewor                                                            k-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattl                                                            e-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-                                                            framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-mana                                                            ged-context-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:106) [cattle-framework-api-0.5.0-SNAPSHO                                                            T.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529                                                            .jar:9.2.11.v20150529]
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [jetty-servlets-9.2.11.v20150529.jar:9.2.1                                                            1.v20150529]
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v201505                                                            29]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529                                                            .jar:9.2.11.v20150529]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v                                                            20150529]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.11.v20150529.jar:9.2.11                                                            .v20150529]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [jetty-security-9.2.11.v20150529.jar:9.2.11                                                            .v20150529]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.11.v20150529.jar:9.                                                            2.11.v20150529]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.11.v20150529.jar:9                                                            .2.11.v20150529]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v2                                                            0150529]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.11.v20150529.jar:9.2                                                            .11.v20150529]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.11.v20150529.jar:9.                                                            2.11.v20150529]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.11.v20150529.jar:9.2.11                                                            .v20150529]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.11.v20150529.jar:9.2.1                                                            1.v20150529]
        at org.eclipse.jetty.server.Server.handle(Server.java:499) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.11.v20150529.jar:9.2.11.v                                                            20150529]
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.11.v20150529.jar:9.2.11.v20150                                                            529]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.11.v20150529.jar:9.2.1                                                            1.v20150529]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.11.v20150529.jar:9.2.11                                                            .v20150529]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]

`

**Tried:**
(no specific order)
- Checked with my network department that required ports are open == Everything is okay.
-- If i deliberately write an incorrect password I'm getting: `Error in ldap bind: LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C0903D9, comment: AcceptSecurityContext error, data 52e, v2580` <-- so connection to AD is there.
- Booted the Rancher server == No change
- Logs on the AD server to which the login was sent: `
An account was successfully logged on.

Subject:
	Security ID:		SYSTEM
	Account Name:		"DC SERVERNAME"$
	Account Domain:		"DOMAIN"
	Logon ID:		0x3E7

Logon Type:			3

Impersonation Level:		Impersonation

New Logon:
	Security ID:		"DOMAIN"\"USERNAME"
	Account Name:		"USERNAME"
	Account Domain:		"DOMAIN"
	Logon ID:		0x9F47C51C
	Logon GUID:		{00000000-0000-0000-0000-000000000000}

Process Information:
	Process ID:		0x230
	Process Name:		C:\Windows\System32\lsass.exe

Network Information:
	Workstation Name:	"SERVERNAME"
	Source Network Address:	"SERVER IP"
	Source Port:		49200

Detailed Authentication Information:
	Logon Process:		Advapi  
	Authentication Package:	MICROSOFT_AUTHENTICATION_PACKAGE_V1_0
	Transited Services:	-
	Package Name (NTLM only):	-
	Key Length:		0

This event is generated when a logon session is created. It is generated on the computer that was accessed.

The subject fields indicate the account on the local system which requested the logon. This is most commonly a service such as the Server service, or a local process such as Winlogon.exe or Services.exe.

The logon type field indicates the kind of logon that occurred. The most common types are 2 (interactive) and 3 (network).

The New Logon fields indicate the account for whom the new logon was created, i.e. the account that was logged on.

.......
`
So everything seems to go well. However, the AD authentication provider in Rancher do not believe so.

--------------

Any ideas? And also, I get the impression that you configure the AD auth provider by giving it a specific DC IP. If I'm correct, that's a single point of failure issue. Or is the provider coded so that it asks the domain for an available DC and goes from there?

Thank you :-)

**Comment by sur1v** [comment]
Please check release notes, there are some lines for Active Directory + TLS users...
https://github.com/rancher/rancher/releases

**Comment by larssb** [comment]
Thanx @sur1v, however none of the notes apply.
- We don't use TLS as of now (test environment).
- Haven't had any of the other mentioned issued.

So looks like it has to be something else. If I in any way can help by providing logs or similar info. Let me know.

Thank you.

**Comment by mrajashree** [comment]
@larssb are there any error logs right above this one
```
2017-09-15 14:02:29,246 ERROR [:] [] [] [] [p1020391880-132] [.a.a.i.e.ExternalServiceAuthProvider] Failed to get token from Auth Service. org.apache.http.NoHttpResponseException: The target server failed to respond
```

**Comment by larssb** [comment]
Hi @mrajashree  

Yeah there actually is. Here it is:

`
time="2017-09-18T09:25:53Z" level=info msg="Now generating Ldap token"
2017/09/18 09:25:53 http: panic serving 127.0.0.1:60984: runtime error: index out of range
goroutine 663 [running]:
net/http.(*conn).serve.func1(0xc42049c000)
        /usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0xb8ed60, 0x11b3d20)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/rancher/rancher-auth-service/providers/ldap.(*LClient).GenerateToken(0xc42068f580, 0xc420400510, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, .                                         ..)
        /go/src/github.com/rancher/rancher-auth-service/providers/ldap/ldap_client.go:157 +0xe5d
github.com/rancher/rancher-auth-service/providers/ldap/ad.(*ADProvider).GenerateToken(0xc42076c018, 0xc420400510, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,                                          0x0, ...)
        /go/src/github.com/rancher/rancher-auth-service/providers/ldap/ad/ad_provider.go:88 +0x7d
github.com/rancher/rancher-auth-service/server.CreateToken(0xc420400510, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/rancher/rancher-auth-service/server/auth_server.go:877 +0x8a
github.com/rancher/rancher-auth-service/service.CreateToken(0x11d4600, 0xc4201ac2a0, 0xc42000ac00)
        /go/src/github.com/rancher/rancher-auth-service/service/route_handlers.go:45 +0x6cb
net/http.HandlerFunc.ServeHTTP(0xc56060, 0x11d4600, 0xc4201ac2a0, 0xc42000ac00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/rancher/rancher-auth-service/vendor/github.com/rancher/go-rancher/api.ApiHandler.func1(0x11d4600, 0xc4201ac2a0, 0xc42000ac00)
        /go/src/github.com/rancher/rancher-auth-service/vendor/github.com/rancher/go-rancher/api/handler.go:20 +0x131
net/http.HandlerFunc.ServeHTTP(0xc420269840, 0x11d4600, 0xc4201ac2a0, 0xc42000ac00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/rancher/rancher-auth-service/vendor/github.com/gorilla/context.ClearHandler.func1(0x11d4600, 0xc4201ac2a0, 0xc42000ac00)
        /go/src/github.com/rancher/rancher-auth-service/vendor/github.com/gorilla/context/context.go:141 +0x8b
net/http.HandlerFunc.ServeHTTP(0xc420269880, 0x11d4600, 0xc4201ac2a0, 0xc42000ac00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/rancher/rancher-auth-service/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4206878b0, 0x11d4600, 0xc4201ac2a0, 0xc42000ac00)
        /go/src/github.com/rancher/rancher-auth-service/vendor/github.com/gorilla/mux/mux.go:107 +0x10c
net/http.serverHandler.ServeHTTP(0xc4207400b0, 0x11d4600, 0xc4201ac2a0, 0xc42000a800)
        /usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42049c000, 0x11d4e40, 0xc4203841c0)
        /usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2ce
`

- Does that give an indication of what could be the problem? Thank you :-) 👍

**Comment by mrajashree** [comment]
@larssb can you share the login name you used to setup auth? Did you provide any domain as well?

**Comment by larssb** [comment]
Login name: rancherADauth@DOMAIN.LOCAL
Domain provided: DC=DOMAIN,DC=LOCAL
Hostname: SERVER.DOMAIN.LOCAL

**Comment by mrajashree** [comment]
@larssb  Okay so you entered username as `rancherADauth@DOMAIN.LOCAL`. In the ldap settings the user login field by default is `sAMAccountName`. Is that what you have selected as well? Is your account's `sAMAccountName`=`rancherADauth@DOMAIN.LOCAL` in the AD server? Also I was referring to Default Login Domain when I asked about domain, so can you please provide that too?

**Comment by larssb** [comment]
- Misunderstood the reference to "Default Login Domain". I have nothing in that field.
- Just tried by specifying DOMAIN\rancherADauth in the "Service Account Username" field. --> the result is the same. For the end-user I'm testing with I also specify DOMAIN\sAMAccountName

**Comment by mrajashree** [comment]
Okay thanks for providing these fields. Can you please try the following
1. `Default Login Domain` = DOMAIN
2. `Service Account Username` = rancherADauth
3. `Your Username` in `Test and enable authentication` = sAMAccountName
The username fields without the DOMAIN prefix

**Comment by larssb** [comment]
Hi @mrajashree that made it work. Niceness! However, what changed? It used to work :-D. The error `index out of range goroutine` could be telling. In the way that some requests that are index bound do not fail now because data has been split up. But maybe I'm forestalling the scenario here, or just plain misunderstanding.

Also could you be so kind to elaborate on the second question (or should I create a specific incident for that question?): 
- I get the impression that one configure the AD auth. provider by giving it a specific DC IP. If I'm correct, that's a single point of failure issue. Or is the provider coded so that it asks the domain for an available DC and goes from there?

Thank you.

**Comment by galal-hussein** [comment]
Rancher server: v1.6.10-rc1

I was able to test AD authentication with empty value to Default Login Domain, and service account username `<default-login-domain>\<sa username>` and Username `<default-login-domain>\<username>`

The AD authentication worked successfully and login worked as well.

**Comment by larssb** [comment]
@galal-hussein and @mrajashree 
--
Also could you be so kind to elaborate on the second question (or should I create a specific incident for that question?):

    I get the impression that one configure the AD auth. provider by giving it a specific DC IP. If I'm correct, that's a single point of failure issue. Or is the provider coded so that it asks the domain for an available DC and goes from there?
--

**Comment by vincent99** [comment]
The implementation is "AD-flavored" LDAP.  It connects to the name or IP given, and knows nothing about domain controllers. Most non-Windows AD integrations work this way.

Whether it's a single point of failure depends on how you've configured it. There's DNS round-robin, floating IPs, load balancers, anycast, etc.
