### ISSUE TITLE
exportconfig issue when exporting secrets with 'mode'

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#9950]
**Rancher versions:**
rancher/server: 1.6.10

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA

**Steps to Reproduce:**
1. create a secret from within rancher, leverage with this stack definition:
```
version: '2' 
services: 
  test: 
    image: ubuntu:16.04
    stdin_open: true
    tty: true
    secrets:
    - source: joeschmoe
      mode: 0400
    labels:
      io.rancher.container.pull_image: always
```
2. view config or export stack config

**Results:**
UI shows: 500 Internal Server Error
cattle-debug.log
```
2017-09-27 03:42:46,617 ERROR [:] [] [] [] [p1020391880-192] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [https://my-rancher.com-ha.rancher.space/v2-beta/projects/1a5/stacks/1st29/]. Error id: [bbaf6875-c4b5-4c15-9bdb-2321aabbe6fd]. java.lang.NullPointerException: null
        at io.cattle.platform.servicediscovery.api.service.impl.ServiceDiscoveryApiServiceImpl.populateSecrets(ServiceDiscoveryApiServiceImpl.java:409) ~[cattle-iaas-service-discovery-api-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.servicediscovery.api.service.impl.ServiceDiscoveryApiServiceImpl.createComposeData(ServiceDiscoveryApiServiceImpl.java:208) ~[cattle-iaas-service-discovery-api-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.servicediscovery.api.service.impl.ServiceDiscoveryApiServiceImpl.buildDockerComposeConfig(ServiceDiscoveryApiServiceImpl.java:130) ~[cattle-iaas-service-discovery-api-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.servicediscovery.api.service.impl.ServiceDiscoveryApiServiceImpl.buildComposeConfig(ServiceDiscoveryApiServiceImpl.java:121) ~[cattle-iaas-service-discovery-api-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.servicediscovery.api.action.StackExportConfigActionHandler.perform(StackExportConfigActionHandler.java:57) ~[cattle-iaas-service-discovery-api-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.api.resource.AbstractObjectResourceManager.resourceActionInternal(AbstractObjectResourceManager.java:382) ~[cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.resourceAction(AbstractBaseResourceManager.java:414) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.resource.AbstractResourceManagerFilter.resourceAction(AbstractResourceManagerFilter.java:58) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.servicediscovery.api.filter.ServiceStackStorageDriverFilter.resourceAction(ServiceStackStorageDriverFilter.java:85) ~[cattle-iaas-service-discovery-api-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.resourceAction(FilteredResourceManager.java:86) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.resource.AbstractResourceManagerFilter.resourceAction(AbstractResourceManagerFilter.java:58) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.servicediscovery.api.filter.ServiceStackNetworkDriverFilter.resourceAction(ServiceStackNetworkDriverFilter.java:85) ~[cattle-iaas-service-discovery-api-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.resourceAction(FilteredResourceManager.java:86) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.resource.AbstractResourceManagerFilter.resourceAction(AbstractResourceManagerFilter.java:58) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.resourceAction(FilteredResourceManager.java:86) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.handler.ResourceManagerRequestHandler.generate(ResourceManagerRequestHandler.java:44) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.handler.AbstractResponseGenerator.handle(AbstractResponseGenerator.java:14) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.handle(DefaultReadWriteApiDelegate.java:27) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.write(DefaultReadWriteApiDelegate.java:22) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at sun.reflect.GeneratedMethodAccessor690.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_72]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_72]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:280) ~[spring-tx-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at com.sun.proxy.$Proxy73.write(Unknown Source) ~[na:na]
        at io.github.ibuildthecloud.gdapi.request.handler.write.ReadWriteApiHandler.handle(ReadWriteApiHandler.java:19) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:99) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:96) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:106) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [jetty-security-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.Server.handle(Server.java:499) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
```

**Comment by chrisgacsal** [comment]
I have also encountered the same issue. It is really annoying. :/

**Comment by vincent99** [comment]
As a workaround the mode just need to not have any leading zeros.  It's being interpreted as octal and converted to decimal by the yaml parser, then expected to still be octal later.

**Comment by StrongMonkey** [comment]
we do have an known issue as @vincent99 mentioned: if you put any leading zeros for mode, the mode will be parsed to an octal and the result will be wrong

**Comment by cjellick** [comment]
Spoke with @StrongMonkey. The current fix of stripping the leading zero doesn't really fix the bug at its core. Need to dig deeper

**Comment by soumyalj** [comment]
Reproduced the issue in v1.6.10
Tested with v1.6.11-rc4. Created a stack with the following yml in UI/ CLI
```
version: '2'
services:
  newtest:
    image: nginx
    stdin_open: true
    tty: true
    secrets:
      - source: mysecret
        target: mysecretincontainer
        mode: 0400
        name: mysecret
        secretId: 1
secrets:
  mysecret:
    external: true
```
The stack was created successfully with the secret inside the container.
View config/export config did not result in "Internal server error"
Verified the logs and no errors were observed
