### ISSUE TITLE
Kubernetes - Jenkins fails on downloading plugins

### ISSUE THREAD

**Issue by Adiqq** [rancher/rancher#9965]
**Rancher versions:**
rancher/server: 1.6.10
rancher/agent: 1.2.6

**Infrastructure Stack versions:**
healthcheck:0.3.3
ipsec: 0.1.4
network-services:0.2.6
scheduler: -
kubernetes (if applicable): 1.7.4-rancher2

**Docker version: (`docker version`,`docker info` preferred)**
```
[root@localhost .ssh]# docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-55.gitc4618fb.el7.centos.x86_64
 Go version:      go1.8.3
 Git commit:      c4618fb/1.12.6
 Built:           Thu Sep 21 22:33:52 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-55.gitc4618fb.el7.centos.x86_64
 Go version:      go1.8.3
 Git commit:      c4618fb/1.12.6
 Built:           Thu Sep 21 22:33:52 2017
 OS/Arch:         linux/amd64
[root@localhost .ssh]# docker info
Containers: 47                                                                          
 Running: 45                                                                            
 Paused: 0                                                                              
 Stopped: 2                                                                             
Images: 33                                                                              
Server Version: 1.12.6                                                                  
Storage Driver: devicemapper                                                            
 Pool Name: docker-253:0-677848-pool                                                    
 Pool Blocksize: 65.54 kB                                                               
 Base Device Size: 10.74 GB                                                             
 Backing Filesystem: xfs                                                                
 Data file: /dev/loop0                                                                  
 Metadata file: /dev/loop1                                                              
 Data Space Used: 6.038 GB                                                              
 Data Space Total: 107.4 GB                                                             
 Data Space Available: 19.89 GB                                                         
 Metadata Space Used: 11.04 MB                                                          
 Metadata Space Total: 2.147 GB                                                         
 Metadata Space Available: 2.136 GB                                                     
 Thin Pool Minimum Free Space: 10.74 GB                                                 
 Udev Sync Supported: true                                                              
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp selinux
Kernel Version: 3.10.0-693.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 2
Total Memory: 3.702 GiB
Name: localhost.localdomain
ID: AKGZ:CLBS:VPHP:KNYA:ABA7:QD4L:7ZLA:BDC3:OVEN:WIZ7:LY4S:HTB3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Registries: docker.io (secure)
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
[root@localhost .ssh]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[root@localhost .ssh]# uname -r
3.10.0-693.el7.x86_64
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox
```
❯ vboxmanage --version
5.1.28r117968
```
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher 
internal DB
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**

1. Install [CentOS 7](http://isoredirect.centos.org/centos/7/isos/x86_64/CentOS-7-x86_64-Minimal-1708.iso) on [Virtualbox](https://www.virtualbox.org/wiki/Downloads)
In Virtualbox set two networks, NAT and Host-Only.
Use Standard Docker Host Profile security profile for CentOS.
Host-Only network provides IP in range 192.168.99.100-192.168.99.254 

2. Disable firewall and setup NFS on VM.
Create exports file in current direcotry with content:
```
/var/jenkinsshare *(rw,sync,no_root_squash,no_all_squash)
/var/dockerregistryshare *(rw,sync,no_root_squash,no_all_squash)
```

Create and execute script
```
#!/usr/bin/env bash

systemctl disable firewalld
systemctl stop firewalld

yum install nfs-utils -y

systemctl enable rpcbind
systemctl enable nfs-server
systemctl enable nfs-lock
systemctl enable nfs-idmap
systemctl start rpcbind
systemctl start nfs-server
systemctl start nfs-lock
systemctl start nfs-idmap

mkdir -p /var/jenkinsshare
chmod -R 777 /var/jenkinsshare/

mkdir -p /var/dockerregistryshare
chmod -R 777 /var/dockerregistryshare/

cp exports /etc/exports

systemctl restart nfs-server
```
3. Install Docker 1.12.6 on VM
```
#!/usr/bin/env bash

yum install -y yum-utils \
  device-mapper-persistent-data \
  lvm2

yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo

yum install docker-1.12.6
systemctl start docker
systemctl enable docker
```
4.Start Rancher image on VM
```
sudo docker run -d --restart=unless-stopped -p 8080:8080 rancher/server:stable
```
5.Remove default environment, create new Kubernetes env named "Default"
6.Install Rancher agent on the same VM.
7.Use kubectl apply -f deployment.yaml

deployment.yaml content:
```
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  labels:
    type: jenkins
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /var/jenkinsshare
    server: 192.168.99.100
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      type: "jenkins"
---
kind: Service
apiVersion: v1
metadata:
    name: jenkins-service
    namespace: jenkins
spec:
    selector:
        app: jenkins
    ports:
        - protocol: TCP
          port: 8000
          targetPort: 8080

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
  namespace: jenkins
  annotations:
      http.port: "8000"
spec:
  backend:
    serviceName: jenkins-service
    servicePort: 8000
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name:  jenkins
          image: jenkinsci/blueocean
          ports:
            - containerPort: 8080

```
8. Go to [http://192.168.99.100:8000](http://192.168.99.100:8000)
9. Try to install Jenkins

**Results:**
Jenkins plugin installation fails.
```
27.09.2017 17:48:24INFO: Downloading Email Extension Plugin
27.09.2017 17:49:24Sep 27, 2017 3:49:24 PM hudson.model.UpdateCenter$DownloadJob run
27.09.2017 17:49:24SEVERE: Failed to install Email Extension Plugin
27.09.2017 17:49:24hudson.util.IOException2: Failed to download from http://updates.jenkins-ci.org/download/plugins/email-ext/2.60/email-ext.hpi (redirected to: http://ftp-chi.osuosl.org/pub/jenkins/plugins/email-ext/2.60/email-ext.hpi)
27.09.2017 17:49:24	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1172)
27.09.2017 17:49:24	at hudson.model.UpdateCenter$DownloadJob._run(UpdateCenter.java:1677)
27.09.2017 17:49:24	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1874)
27.09.2017 17:49:24	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1651)
27.09.2017 17:49:24	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
27.09.2017 17:49:24	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
27.09.2017 17:49:24	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:110)
27.09.2017 17:49:24	at java.lang.Thread.run(Thread.java:745)
27.09.2017 17:49:24Caused by: java.io.IOException: Failed to load http://updates.jenkins-ci.org/download/plugins/email-ext/2.60/email-ext.hpi to /var/jenkins_home/plugins/email-ext.jpi.tmp
27.09.2017 17:49:24	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1146)
27.09.2017 17:49:24	... 7 more
27.09.2017 17:49:24Caused by: java.net.SocketTimeoutException: Read timed out
27.09.2017 17:49:24	at java.net.SocketInputStream.socketRead0(Native Method)
27.09.2017 17:49:24	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
27.09.2017 17:49:24	at java.net.SocketInputStream.read(SocketInputStream.java:171)
27.09.2017 17:49:24	at java.net.SocketInputStream.read(SocketInputStream.java:141)
27.09.2017 17:49:24	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
27.09.2017 17:49:24	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
27.09.2017 17:49:24	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
27.09.2017 17:49:24	at java.io.FilterInputStream.read(FilterInputStream.java:133)
27.09.2017 17:49:24	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3375)
27.09.2017 17:49:24	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3368)
27.09.2017 17:49:24	at org.apache.commons.io.input.ProxyInputStream.read(ProxyInputStream.java:77)
27.09.2017 17:49:24	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1141)
27.09.2017 17:49:24	... 7 more
27.09.2017 17:49:36Sep 27, 2017 3:49:36 PM hudson.model.UpdateSite$Plugin deploy
27.09.2017 17:49:36INFO: Adding dependent install of bouncycastle-api for plugin email-ext
27.09.2017 17:49:36Sep 27, 2017 3:49:36 PM hudson.model.UpdateCenter$DownloadJob run
27.09.2017 17:49:36INFO: Starting the installation of bouncycastle API Plugin on behalf of admin
27.09.2017 17:49:37Sep 27, 2017 3:49:37 PM hudson.model.UpdateCenter$UpdateCenterConfiguration download
27.09.2017 17:49:37INFO: Downloading bouncycastle API Plugin
27.09.2017 17:50:37Sep 27, 2017 3:50:37 PM hudson.model.UpdateCenter$DownloadJob run
27.09.2017 17:50:37SEVERE: Failed to install bouncycastle API Plugin
27.09.2017 17:50:37hudson.util.IOException2: Failed to download from http://updates.jenkins-ci.org/download/plugins/bouncycastle-api/2.16.2/bouncycastle-api.hpi (redirected to: http://ftp-chi.osuosl.org/pub/jenkins/plugins/bouncycastle-api/2.16.2/bouncycastle-api.hpi)
27.09.2017 17:50:37	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1172)
27.09.2017 17:50:37	at hudson.model.UpdateCenter$DownloadJob._run(UpdateCenter.java:1677)
27.09.2017 17:50:37	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1874)
27.09.2017 17:50:37	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1651)
27.09.2017 17:50:37	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
27.09.2017 17:50:37	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
27.09.2017 17:50:37	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:110)
27.09.2017 17:50:37	at java.lang.Thread.run(Thread.java:745)
27.09.2017 17:50:37Caused by: java.io.IOException: Failed to load http://updates.jenkins-ci.org/download/plugins/bouncycastle-api/2.16.2/bouncycastle-api.hpi to /var/jenkins_home/plugins/bouncycastle-api.jpi.tmp
27.09.2017 17:50:37	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1146)
27.09.2017 17:50:37	... 7 more
27.09.2017 17:50:37Caused by: java.net.SocketTimeoutException: Read timed out
27.09.2017 17:50:37	at java.net.SocketInputStream.socketRead0(Native Method)
27.09.2017 17:50:37	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
27.09.2017 17:50:37	at java.net.SocketInputStream.read(SocketInputStream.java:171)
27.09.2017 17:50:37	at java.net.SocketInputStream.read(SocketInputStream.java:141)
27.09.2017 17:50:37	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
27.09.2017 17:50:37	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
27.09.2017 17:50:37	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
27.09.2017 17:50:37	at java.io.FilterInputStream.read(FilterInputStream.java:133)
27.09.2017 17:50:37	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3375)
27.09.2017 17:50:37	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3368)
27.09.2017 17:50:37	at org.apache.commons.io.input.ProxyInputStream.read(ProxyInputStream.java:77)
27.09.2017 17:50:37	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1141)
27.09.2017 17:50:37	... 7 more
27.09.2017 17:50:37Sep 27, 2017 3:50:37 PM hudson.model.UpdateCenter$DownloadJob run
27.09.2017 17:50:37INFO: Starting the installation of Email Extension Plugin on behalf of admin
27.09.2017 17:50:39Sep 27, 2017 3:50:39 PM hudson.model.UpdateCenter$UpdateCenterConfiguration download
27.09.2017 17:50:39INFO: Downloading Email Extension Plugin
27.09.2017 17:51:39Sep 27, 2017 3:51:39 PM hudson.model.UpdateCenter$DownloadJob run
27.09.2017 17:51:39SEVERE: Failed to install Email Extension Plugin
27.09.2017 17:51:39hudson.util.IOException2: Failed to download from http://updates.jenkins-ci.org/download/plugins/email-ext/2.60/email-ext.hpi (redirected to: http://ftp-nyc.osuosl.org/pub/jenkins/plugins/email-ext/2.60/email-ext.hpi)
27.09.2017 17:51:39	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1172)
27.09.2017 17:51:39	at hudson.model.UpdateCenter$DownloadJob._run(UpdateCenter.java:1677)
27.09.2017 17:51:39	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1874)
27.09.2017 17:51:39	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1651)
27.09.2017 17:51:39	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
27.09.2017 17:51:39	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
27.09.2017 17:51:39	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:110)
27.09.2017 17:51:39	at java.lang.Thread.run(Thread.java:745)
27.09.2017 17:51:39Caused by: java.io.IOException: Failed to load http://updates.jenkins-ci.org/download/plugins/email-ext/2.60/email-ext.hpi to /var/jenkins_home/plugins/email-ext.jpi.tmp
27.09.2017 17:51:39	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1146)
27.09.2017 17:51:39	... 7 more
27.09.2017 17:51:39Caused by: java.net.SocketTimeoutException: Read timed out
27.09.2017 17:51:39	at java.net.SocketInputStream.socketRead0(Native Method)
27.09.2017 17:51:39	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
27.09.2017 17:51:39	at java.net.SocketInputStream.read(SocketInputStream.java:171)
27.09.2017 17:51:39	at java.net.SocketInputStream.read(SocketInputStream.java:141)
27.09.2017 17:51:39	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
27.09.2017 17:51:39	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
27.09.2017 17:51:39	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
27.09.2017 17:51:39	at java.io.FilterInputStream.read(FilterInputStream.java:133)
27.09.2017 17:51:39	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3375)
27.09.2017 17:51:39	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3368)
27.09.2017 17:51:39	at org.apache.commons.io.input.ProxyInputStream.read(ProxyInputStream.java:77)
27.09.2017 17:51:39	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1141)
27.09.2017 17:51:39	... 7 more
27.09.2017 18:06:40Sep 27, 2017 4:06:40 PM jenkins.branch.MultiBranchProject$BranchIndexing run
27.09.2017 18:06:40INFO: kubernetes #20170927.160636 branch indexing action completed: SUCCESS in 3.9 sec
```

Curl works, but there's problem with downloading files. Just after start, they quickly hang.
```
bash-4.3$ curl http://google.pl
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.pl/">here</A>.
</BODY></HTML>
bash-4.3$ wget http://ipv4.download.thinkbroadband.com/1GB.zip
Connecting to ipv4.download.thinkbroadband.com (80.249.99.148:80)
1GB.zip                0% |                               |    28k  - stalled -
```
[screen](http://oi68.tinypic.com/309ojex.jpg)

**Comment by Adiqq** [comment]
Ok, I found the problem.
After switching to bridged network in Virtualbox, it worked without problem.
